### ISSUE TITLE
Tree chart type: 'broken' modified in latest version

### ISSUE THREAD

**Issue by BrianWahinya** [apache/incubator-echarts#10005]
### Version
4.2.1-rc1

### Steps to reproduce
Creating a tree diagram (using echarts version 3 or 4) with straight lines and square corners like in echarts version 2 using type:'broken'

### What is expected?
Tree chart with straight lines and square corners 

### What is actually happening?
On the new version of echarts tree chart, type:’broken’ modifies the texture of the line, not the shape of the line as in older version.

---
The link below shows the type of  broken tree chart in echarts version 2.

https://echarts.baidu.com/echarts2/doc/example/tree1.html#-en

**Comment by Ovilia** [comment]
@BrianWahinya Can you provide the code in ECharts v4?

**Comment by BrianWahinya** [comment]
// executed once html doc is 100% loaded

$(document).ready(onReady);

// main function

 function onReady(){
  var data = {
      name: "Total (15 a 24 años)",
            children: [ {
                   name: '20 a 24 años',
                         children: [ {
                               name: "Urbana",
                               value: 20.9 
                            },
                            {
                               name: "Rural",
                               value: 27.5 
                             } ]
                     },
                    {
                      name: '15 a 19 años',
                           children: [ {
                               name: "Urbana", 
                               value: 13.3  
                               },
                               { 
                                name: "Rural", 
                                value: 16.9   
                                } ]
                     } ]
   };

//Generate Tree series
 var serie = {
          type: 'tree',
          data: [data],
           //lineStyle: { color:'#C41188',       width:1.5, type:'solid', curveness:0.5 },
          //lineStyle: { color:'#C41188',       width:1.5, type:'dotted', curveness:0.5    },
         //lineStyle: { color:'#C41188',       width:1.5, type:'dashed', curveness:0.5    },
         lineStyle: { color:'#C41188',          width:1.5, type:'broken', curveness:0.5    },
         label: { normal: {  position: 'bottom', align: 'center' } },
         leaves: { label: { normal: { position: 'right', verticalAlign: 'middle', align: 'left' }  }  }
  };
 var option = { series: serie };
 var myChart = echarts.init(document.getElementById('1.3.5'));
 if (option && typeof option === "object") {
                   myChart.setOption(option, true);
   };
 $(window).on('resize', function(){
                   if(myChart!= null && myChart != undefined){
                   myChart.resize();
      }
   });
};

**Comment by Jivanvl** [comment]
I think the API has changed since then, I tried this myself and tree charts seem to work fine, but I think the option you're looking for is the `curveness` inside the `lineStyle` option: https://ecomfe.github.io/echarts-doc/public/en/option.html#series-tree.lineStyle.curveness

Here's a working codepen for version 4.1.0:
https://codepen.io/jivanvl/pen/ZPpypZ

**Comment by BrianWahinya** [comment]
@Jivanvl your option is valid and i had prior knowledge of it. But i dont want that design of tree chart. Check the link below for the design that I would like to get help in. I'm not sure if they removed that 'broken' functionality and thats why I am enquiring. Its present when you use version 2 but its different when you try to use version 4.

https://echarts.baidu.com/echarts2/doc/example/tree1.html#-en

**Comment by deqingli** [comment]
Hi @BrianWahinya, I know what you want, the straight-line layout of tree in version4 will be released in 4.7.0 with this [PR](https://github.com/apache/incubator-echarts/pull/11808).
