### ISSUE TITLE
echarts.connect 無法雙方向聯動

### ISSUE THREAD

**Issue by GarnixJu2015** [apache/incubator-echarts#10016]
### Version
4.1.0-release

### Steps to reproduce
此狀況中圖表A為heat map，圖表B為Area Chart，使用group ID做連結，無法雙向聯動。

### What is expected?
AB圖表能雙向聯動成功

### What is actually happening?
1. 連動圖表A(heat map) 可以順利Trigger 圖表B(Area Chart)，但當滑鼠滑至圖表B時無法連動A。

---
為做測試另外新增了同為Area chart 的圖表C，並assign同樣的group ID，B C之間可以順利雙向聯動，卻仍然無法連動A，A可以聯動B和C。

**Comment by Ovilia** [comment]
@GarnixJu2015 你好，請問可以為這個問題提供一個例子便於我們復現嗎？
