### ISSUE TITLE
使用百度地图拓展在地图上标点时value显示的是纬度值

### ISSUE THREAD

**Issue by horizon98** [apache/incubator-echarts#10023]
### Version
4.1.0-release

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=effectScatter-bmap](https://www.echartsjs.com/examples/editor.html?c=effectScatter-bmap)

### Steps to reproduce
该实例中地图上的标点显示的数值大小为纬度大小，但是标点的大小根据数值得出，希望能够帮助解决，谢谢！
根据https://github.com/apache/incubator-echarts/tree/master/extension/bmap处的说明，使用如data: [[125.03,46.58,50]，[125.03,46.90,200]]的数据进行标点依旧是此情况.

### What is expected?
data中的value值能够使用

### What is actually happening?
data中的value值被纬度值替代，实际无用

**Comment by plainheart** [comment]
try 
```js
encode: { 
    value: 2 
}
```
or use `tooltip.formatter`

**Comment by Ovilia** [comment]
这的确是示例的 bug，感谢 @plainheart 提供的解决方案！
