### ISSUE TITLE
两个图表同时使用异步数据加载,会有图表数据渲染不出来

### ISSUE THREAD

**Issue by Iamzz-cn** [apache/incubator-echarts#10021]
### Version
4.2.1-rc1

### Steps to reproduce
在同一个页面创建两个或两个以上图标,使用异步数据加载,在同一个ajax请求中加载数据,第一次多数情况下,会成功,刷新当前页面,bug就会出现了!

### What is expected?
两个表格都正常渲染数据

### What is actually happening?
只有一个表格渲染了数据

**Comment by Iamzz-cn** [comment]
似乎是第一个表的的init影响了第二个表格的init,同样的数据,我才用了同步流程,先init第一个表格在init第二个表格,问题没有出现.

**Comment by Ovilia** [comment]
请提供可复现的例子 https://gallery.echartsjs.com/editor.html

**Comment by godbuttton** [comment]
我也遇到这个问题了 在IE11里面可以复现 ，chrome出现概率比较少，我是同时发起异步请求然后去渲染echart，会有部分表格无法显示 有时候是所有表格。
