### ISSUE TITLE
整个图表加载完成如何监听？rendered和finished都不正确

### ISSUE THREAD

**Issue by dousee163** [apache/incubator-echarts#10037]
### Version
4.2.1-rc.3

### Steps to reproduce
比如
var myChart = echarts.init(...);
myChart.setOption(...);
myChart.on('......', function() {
//我的代码在这里
});

### What is expected?
我要图表的所有绘画结束之后，调用ajax处理其他逻辑。
应该怎么写?

### What is actually happening?
没有回调函数

**Comment by pissang** [comment]
I think `finished` can be used in your situation. Can you describe your issue with more infomation?

**Comment by dousee163** [comment]
> I think `finished` can be used in your situation. Can you describe your issue with more information?

	chart.on('finished', function () {
	    console.log('dfa');
	});

我只想要在首次渲染完毕调用，而finished事件在鼠标挪动的时候也会被触发。

**Comment by plainheart** [comment]
如果 `finished` 事件对你有用，那完全可以定义一个变量标识是否为首次渲染，默认true，回调函数执行后，标识其为false，解绑该事件不再继续执行相关代码即可

**Comment by zhoufanglu** [comment]
> 如果 `finished` 事件对你有用，那完全可以定义一个变量标识是否为首次渲染，默认true，回调函数执行后，标识其为false，解绑该事件不再继续执行相关代码即可

这个很矛盾，万一我重新setOption了之后， 还想要触发finished，这该如何解决

**Comment by plainheart** [comment]
@zhoufanglu 可以考虑在 setOption 前监听 finished，finished 后取消监听。

```js
function onFinished(e) {
   console.log('onFinished', e)
   myChart.off('finished', onFinished)
}

function setOption(options) {
  myChart.on('finished', onFinished)
  myChart.setOption(options)
}
```

**Comment by zhoufanglu** [comment]
> @zhoufanglu 可以考虑在 setOption 前监听 finished，finished 后取消监听。
> 
> ```js
> function onFinished(e) {
>    console.log('onFinished', e)
>    myChart.off('finished', onFinished)
> }
> 
> function setOption(options) {
>   myChart.on('finished', onFinished)
>   myChart.setOption(options)
> }
> ```

这似乎是个好办法。谢谢大佬，我试试。
