### ISSUE TITLE
pie图表的label的rotate属性设置不生效，当设置rotate时，显示结果总是rotate='radial'的效果。

### ISSUE THREAD

**Issue by xyang12138** [apache/incubator-echarts#10045]
### Version
4.1.0-release

### Steps to reproduce
新建pie图表，设置label的totate属性，则无论rotate设置为何值，效果总是radial。

### What is expected?
rotate依据设置的结果进行显示

### What is actually happening?
无论rotate设置为何值，效果总是radial。

**Comment by pissang** [comment]
Currently pie doesn't support label rotation.
