### ISSUE TITLE
折线图 堆叠bug

### ISSUE THREAD

**Issue by wenbinobject** [apache/incubator-echarts#10046]
### Version
4.2.1-rc1

### Steps to reproduce
option = {
title: {
text: '折线图堆叠'
},
tooltip: {
trigger: 'axis'
},
legend: {
data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
},
grid: {
left: '3%',
right: '4%',
bottom: '3%',
containLabel: true
},
toolbox: {
feature: {
saveAsImage: {}
}
},
xAxis: {
type: 'category',
boundaryGap: false,
data: ['周一','周二','周三','周四','周五','周六','周日']
},
yAxis: {
type: 'value'
},
series: [
{
name:'邮件营销',
type:'line',
stack: '总量',
data:[25, 11, 30, 3, 95, 101, 91]

    },
    {
        name:'联盟广告',
        type:'line',
        stack: '总量',
         data:[5, 5, 0, 5, 8, 8, 3]
    },

]

};

### What is expected?
期望按照实际的数据比例展示

### What is actually happening?
没有按照实际的比例展示 导致使用户以为数据一致或相近

---
按照option里面的数据编写代码 就会出现相应的问题，可以直接粘贴到 https://echarts.baidu.com/examples/editor.html?c=line-stack echarts 官网的demo中进行查看效果

**Comment by pissang** [comment]
That's what `stack` do.

**Comment by wenbinobject** [comment]
> 
> 
> That's what `stack` do.

你的意思是 我这样写的data数据 展示这样的效果是正常的咯?

**Comment by wenbinobject** [comment]
抱歉是我理解问题 让您浪费时间了
