### ISSUE TITLE
echarts java api 设置xAxis.offset问题 

### ISSUE THREAD

**Issue by zhymovie** [apache/incubator-echarts#10056]
### What problem does this feature solve?
Echarts API for Java中的类CategoryAxis没有提供设置xAxis.offset 的方法，导致设置偏移量不能实现。

### What does the proposed API look like?
CategoryAxis支持设置xAxis.offset

**Comment by plainheart** [comment]
这不属于官方维护的内容，如果你使用的是 [ECharts-Java by abel533](https://github.com/abel533/ECharts)， 你不应该在这里提问。

**Comment by zhymovie** [comment]
> 这不属于官方维护的内容，如果你使用的是 [ECharts-Java by abel533](https://github.com/abel533/ECharts)， 你不应该在这里提问。

这个java类库好像不维护了，我们已对其进行了扩展，谢谢。

**Comment by plainheart** [comment]
所以你应该关闭这个Issue.

**Comment by zhymovie** [comment]
好～
