### ISSUE TITLE
E4 多个series树图 都设置roam 无法同时移动或者放大

### ISSUE THREAD

**Issue by liuyuebai** [apache/incubator-echarts#10070]
### Version
4.2.0-rc.2

### Reproduction link
[https://github.com/liuyuebai/echarts.git（由于穷没有服务器）（就只有一个页面）](https://github.com/liuyuebai/echarts.git（由于穷没有服务器）（就只有一个页面）)

### Steps to reproduce
只要下载项目（项目只有一个html和echart.js）

### What is expected?
E4 多个series树图 都设置roam同时移动或者放大，鼠标放在节点上，节点不要消失

### What is actually happening?
不能

**Comment by Ovilia** [comment]
@liuyuebai Please provide your demo using https://gallery.echartsjs.com/editor.html
