### ISSUE TITLE
Variable interval on xAxis

### ISSUE THREAD

**Issue by pieroliviermarquis** [apache/incubator-echarts#10077]
### Version
4.1.0-release

### Reproduction link
[https://jsfiddle.net/pieroliviermarquis/gawcjmuo/](https://jsfiddle.net/pieroliviermarquis/gawcjmuo/)

### Steps to reproduce
See JSFiddle

### What is expected?
Fixed intervals. There should be a straight line through the scatter as data["residual_inv_pred"] is a linear regression.

### What is actually happening?
Variable intervals distort the regression

**Comment by pissang** [comment]
You are using category axis in this example.

Set `type` to `'value'` in axis will fix it. https://jsfiddle.net/cq5x760u/
