### ISSUE TITLE
折线图 tooltip 溢出边界 可不可以scrollable （How to make the echarts tooltip scrollable? ）

### ISSUE THREAD

**Issue by Aslantoe** [apache/incubator-echarts#10086]
### What problem does this feature solve?
触发方式为axis时，如果tooltip中的数据太多，导致溢出边界，scrollable可以滚动查看；

### What does the proposed API look like?
可以给tooltip设置一个高度，超过这个高度，让其中的内容scroll.

**Comment by Aslantoe** [comment]
![51313153-d51f0d80-1a87-11e9-94c2-86d64e8a0a63](https://user-images.githubusercontent.com/18546413/54124205-ad6f7480-443c-11e9-9bb1-0b954302d595.png)
BROWSER_VERSION：google chrome 72.0.3626.121
浏览器版本：谷歌浏览器 72.0.3626.121

**Comment by deqingli** [comment]
Tooltip is an HTML essentially, you can do anything just like you do with HTML.

**Comment by HowToMeetYou** [comment]
可以实现
但是要将tooltips的触发triggerOn改为click
然后tooltips的formatter回调的html中设置height和overflow：scroll
即可实现

**Comment by HowToMeetYou** [comment]
tooltips的触发triggerOn不影响overflow效果
但是position位置要调一下
即在鼠标移到tooltips框前
tooptip框不能消失
