### ISSUE TITLE
怎样设置动态柱状图的初始数

### ISSUE THREAD

**Issue by DorisOu** [apache/incubator-echarts#10081]
### What problem does this feature solve?
我的配置如下，一开始是加载了所有数据
option = {
xAxis: [{
            type: 'category',
            boundaryGap: true,
            data: ['产品质量追溯', '打码设备', '供应链管理', '经营管理', '设备远程运维及服务', '设备智能调机', '生产品质管控', '生产设备状态监控', '研发管理协同', '智能排单调度', '应用服务目录']
        }]
}

option.timeTicket = setInterval(function() {
        var data0 = option.series[0].data;
        var p2 = data0.shift();
        data0.push(p2);

        var kl = option.xAxis[0].data.shift();
        option.xAxis[0].data.push(kl);
        myChart.setOption(option);
    }, 3000);

### What does the proposed API look like?
是否可以设置文档的某个API实现？参考过X轴是时间轴的写法，但是无法实现

**Comment by deqingli** [comment]
You can reference this [demo](https://www.echartsjs.com/examples/editor.html?c=dynamic-data).
