### ISSUE TITLE
Save as image background for connected charts

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/incubator-echarts#10099]
### Version
4.2.1-rc.2

### Reproduction link
[https://jsfiddle.net/z9hj8xqd/3/](https://jsfiddle.net/z9hj8xqd/3/)

### Steps to reproduce
Notice that the 2 charts are connected.

Click the save as image toolbox button. 

See the transparent background between the charts in the exported png image.

### What is expected?
When "save as image" is clicked for connected charts, the exported image should contain the background color for every part of the image.

### What is actually happening?
Where there are no charts (e.g. other DOM elements), the background of the image is transparent.

---
I ran into this bug, because I have connected charts on my page and they have DOM elements in between them.

**Comment by Ovilia** [comment]
@MINDoSOFT Sorry I could not get it. The transparent between the two charts is expected since there's no chart and thus no background there.

**Comment by Meldanen** [comment]
I have the same issue.
@Ovilia Even though it's expected it doesn't make much sense from a user's perspective. 
Shouldn't the space between the charts be filled in the the same background colour as the chart's? (e.g. white)

**Comment by Ovilia** [comment]
@Meldanen In this case, you can set the `background` of the container using CSS.

**Comment by MINDoSOFT** [comment]
Hello there,

@Ovilia I have tried your suggested approach by setting the background color of the parent div but still when saving the image the background for the space between the charts is transparent. You can see the [jsfiddle here](https://jsfiddle.net/15nehc7z/).

Here is how it looks in the browser 
![Screenshot from 2019-03-22 09-00-49](https://user-images.githubusercontent.com/890368/54805899-12b73700-4c81-11e9-81b2-bb891b7ee6fc.png)

And here is how it looks after save as image (the black background is the transparent part)
![echarts (32)](https://user-images.githubusercontent.com/890368/54805979-5f027700-4c81-11e9-9387-4ca8986126a7.png)

Thank you for your time.

**Comment by Ovilia** [comment]
I see. So what do you think if we use CSS background color to render first, and then the chart background?

**Comment by MINDoSOFT** [comment]
For my use case, I believe only the chart background should be used. There is no need to use the css background color.

Best regards,

Sergios.

**Comment by Meldanen** [comment]
Chart background makes sense for me as well

**Comment by Ovilia** [comment]
But there are two chart instances, and thus two possible `backgroundColor` options.
What is expected if they are set to be different values?

**Comment by MINDoSOFT** [comment]
Hi @Ovilia ,

in the case where the charts have different background colors, I think the container css background color should be used.

**Comment by Ovilia** [comment]
I think this breaks the consistency of expectation. For example, if the user has set CSS background, he may confuse why in some cases it is used and some not.

**Comment by Ovilia** [comment]
I had a second thought and found CSS background may not be accurate, because the container may have a transparent background while the ancestors may have a background color.
So, in [this commit](https://github.com/apache/incubator-echarts/pull/10205/commits/b0eeda9b882e929c50420aabea622c63d1e55b6e), I added an option `toolbox.feature.saveAsImage.connectedBackgroundColor` to configure the background color between the connected charts, and the default value is `'#fff'`.
