### ISSUE TITLE
Echarts官方文档没有标明normal属性，望及时更新

### ISSUE THREAD

**Issue by jyp114110** [apache/incubator-echarts#10092]
normal 属性官方文档没有标明
 markLine: {
              symbol: '',
              data: [
                {
                  type: 'average',
                  name: '平均值',
                  lineStyle: {
                    normal: {
                      // 必须有normal配置 才会生效 但官方文档没有写
                      type: 'dashed',
                      color: 'red'
                    }
                  }
                }
              ]
            },

            itemStyle: {
              // 必须有normal配置 才会生效 但官方文档没有写
              normal: {
                color: 'skyblue'
              }
            }

**Comment by tanwuyu** [comment]
都2020年11月了，美国总统都即将换届了，为啥还没出normal的介绍

**Comment by pissang** [comment]
4.0 版本已经去掉了 normal 这个层级

**Comment by weixioaxiao201803** [comment]
> 都2020年11月了，美国总统都即将换届了，为啥还没出normal的介绍

现在是2021年5月26日，拜登执政4个多月了，官网上还是没有normal的介绍
