### ISSUE TITLE
Chart in candlestick demo has the wrong color for up and down candles

### ISSUE THREAD

**Issue by kimgysen** [apache/incubator-echarts#10101]
### Version
4.2.1-rc.3

### Steps to reproduce
Go to: https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-sh
And load the chart. Red and green candles have been reversed of color. 
Just accidentally happened to notice it ;-) 

### What is expected?
Down candles should be green, and up candles should be red. 

### What is actually happening?
Down candles are green and up candles are red. 

---
Nope:-) Btw, just added random version. Amazing library otherwise, keep up the great work.

**Comment by deqingli** [comment]
Thank you for your suggestion, we will fix it.

**Comment by deqingli** [comment]
@kimgysen  I checked some information about candlestick diagram, which in China is down candles are grown and up candles are red, but it is the opposite in Europe and America.

**Comment by kimgysen** [comment]
Wow seriously? I totally did not take that possibility into account, sorry for that!

**Comment by oom-** [comment]
So is there an option to switch colors for Europe & America ?
