### ISSUE TITLE
移动端echarts渲染崩溃

### ISSUE THREAD

**Issue by YunDuanke** [apache/incubator-echarts#10105]
### Version
4.2.0-rc.2

### Steps to reproduce
移动端X轴数据(type为category)长度超过71，echarts就渲染崩溃，减少X轴数据后，series折线图数据绘制36个后就不再连线，停止渲染了

### What is expected?
可以不崩溃将数据渲染完整

### What is actually happening?
X轴数据长度超过71echarts崩溃；
减少X数据后，echarts不崩溃但是折线图数据连线到36个时停止连线渲染

**Comment by Ovilia** [comment]
崩溃可能是由于内存不够引起的，通常这种情况我们建议[使用 SVG 渲染](https://www.echartsjs.com/tutorial.html#%E4%BD%BF%E7%94%A8%20Canvas%20%E6%88%96%E8%80%85%20SVG%20%E6%B8%B2%E6%9F%93)。如果还有问题的话，请在 https://gallery.echartsjs.com/editor.html 提供一个可复现的例子。
