### ISSUE TITLE
Circular graph does not fit into canvas

### ISSUE THREAD

**Issue by volgin** [apache/incubator-echarts#10104]
### Version
4.1.0-release

### Steps to reproduce
Circular graph with labels longer than 7-8 characters.

### What is expected?
Graph should fit into canvas, or there should be a way to specify how much space to leave between a circle and canvas (similar to grid.top, grid.left, etc.)

### What is actually happening?
The circle fits into the canvas, but some labels are cut off.

---
Only short labels fit into canvas, but there is no documentation on how much space is available for labels, and no way to change that space.

<img width="1152" alt="Screen Shot 2019-03-14 at 6 24 22 PM" src="https://user-images.githubusercontent.com/297748/54396269-c9ffec80-4688-11e9-911d-dc39dba0f898.png">

**Comment by volgin** [comment]
The problem occurs at any size of the canvas - as canvas gets bigger, the circle gets bigger, but the space for labels remains the same. If the library provides a method to set radius of a circle in pixels or "%", that would help solve this problem.

**Comment by deqingli** [comment]
You can set [graph.left](https://www.echartsjs.com/option.html#series-graph.left), and other position info such as width, height, etc.

**Comment by volgin** [comment]
I do not see graph.left anywhere in the documentation. Do you have a link? I only see 'width' and 'height'.

**Comment by volgin** [comment]
Yes, it solves the problem. Thank you!
It would be nice to have documentation explain that .left, etc., affect only the chart itself, not the labels.
