### ISSUE TITLE
导入数据时同样内容的.txt文件出现不同结果

### ISSUE THREAD

**Issue by SPONGE-BOB0-0** [apache/incubator-echarts#10100]
### Version
4.2.1-rc1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xZTdyZWdG0&comment=0](https://gallery.echartsjs.com/editor.html?c=xZTdyZWdG0&comment=0)

### Steps to reproduce
链接里的脚本是从另一个例子里下载的A.txt，换入自己的数据出现的图；
但是本地新建一个B.txt，粘贴A的内容，再导入数据放进脚本时就不行？？？？？

### What is expected?
实现导入数据

### What is actually happening?
报错

**Comment by deqingli** [comment]
sorry, I don't understand what you mean.

**Comment by deqingli** [comment]
Please provide a more detailed message.

**Comment by Ovilia** [comment]
这种情况通常是由于版本问题引起的，请检查两个 demo 的 ECharts 版本（在 console 打印 `echarts.version`）以及其他相关文件是否相同。
