### ISSUE TITLE
移动端我的y轴数据值有null值，然后在开启tooltip提示框的情况下点击在null的时候图表会闪烁，有时就没了再点又有了，有知道该怎么解决的么？

### ISSUE THREAD

**Issue by wangzhongITger** [apache/incubator-echarts#10116]
### Version
4.2.1-rc1

### Steps to reproduce
我传入的数据中y轴的值是有null出现的，然后我在我去点击的情况下图表会闪烁消失又出现这样的情况。如果观掉tooltip或者将null设为0是不会这样的但这达不到我的要求的效果，请问有知道该如何处理这个点击闪烁的问题么？

### What is expected?
有null值时点击不闪烁可正常查看图表

### What is actually happening?
点击在y轴值为null的部分时图表会经常性的消失

---
我这个是在微信小程序中引入的

**Comment by Ovilia** [comment]
请提供可复现的配置项代码

**Comment by wangzhongITger** [comment]
> 请提供可复现的配置项代码
const chartOption = {
    tooltip: {
      trigger: "axis",
      axisPointer: {
        type: "cross"
      },
      textStyle: {
        color: "#000"
      },
      backgroundColor: "rgba(245, 245, 245, 0.8)",
      borderWidth: 1,
      padding: 10,
      borderColor: "#ccc",
    },
    grid: {
      top: 30,
      bottom: 70,
      left: 60,
      right: 50
    },
    xAxis: {
      type: "time",
      boundaryGap: false,
      splitLine: {
        show: false
      },
      nameTextStyle: {
        color: "#ffff00"
      },
    },
    yAxis: {
      nameLocation: 'end',
      type: "value",
      axisLine: {
        show: false
      },
      splitLine: {
        show: false,
        lineStyle: {
          type: "dotted",
          color: "#e6e6e6",
          width: 1
        }
      }
    },
    dataZoom: [
      {
        type: "slider",
        show: true,
        xAxisIndex: [0],
        start: 1,
        end: 100
      }
    ],
    series: {
      name: "测试值",
      type: "line",
      smooth: true,
      data: null,
      symbol: "none",
    }
  };

series中data值事例如下：
[[1,100],[2,200],[3,100],[4,150],[5,""],[6,null],[7,undefined],[8,100],[9,null]]
我尝试过null，undefined以及“”,图上显示是线是断开的，这是没问题，但是点击的时候就会消失，空值越多，现象越是明显，如果禁用点击事件的话是没有任何问题的，正常显示，包括图表中数据连续无空值出现时，点击也不会出任何问题，但是一点有空值出现，就会出现点击图表消失闪现这样的情况，我实在微信小程序上引用的echarts

**Comment by Ovilia** [comment]
这个例子在网页中也没法正常显示。在https://gallery.echartsjs.com/editor.html 创建一个确保能运行的吧~

**Comment by wangzhongITger** [comment]
> 这个例子在网页中也没法正常显示。在https://gallery.echartsjs.com/editor.html 创建一个确保能运行的吧~

option = {
    tooltip: {
        trigger: "axis",
        axisPointer: {
            type: "cross"
        },
        textStyle: {
            color: "#000"
        },
        backgroundColor: "rgba(245, 245, 245, 0.8)",
        borderWidth: 1,
        padding: 10,
        borderColor: "#ccc",
    },
    grid: {
        top: 30,
        bottom: 70,
        left: 60,
        right: 50
    },
    xAxis: {
        type: "category",
        boundaryGap: false,
        splitLine: {
            show: false
        },
        nameTextStyle: {
            color: "#ffff00"
        },
    },
    yAxis: {
        nameLocation: 'end',
        type: "value",
        axisLine: {
            show: false
        },
        splitLine: {
            show: false,
            lineStyle: {
                type: "dotted",
                color: "#e6e6e6",
                width: 1
            }
        }
    },
    dataZoom: [{
        type: "slider",
        show: true,
        xAxisIndex: [0],
        start: 1,
        end: 100
    }],
    series: {
        name: "测试值",
        type: "line",
        smooth: true,
        data: [
            [1, 100],
            [2, 120],
            [3, 130],
            [4, 120],
            [5, null],
            [6, null],
            [7, null],
            [8, 100],
            [9, 120]
        ],
        symbol: "none",
    }
};

编好了，这个在web上是没问题的，但是小程序上显示就会出现问题，我们的项目属性监测是一个很长时间段的监测，所以中间是肯定会出现null这样的断点的，现在就是显示这些断点后再小程序的页面时进行点击，图表会消失，也会点击再次出现，没法像连续数据以及，web上这样正常显示

**Comment by Ovilia** [comment]
@wangzhongITger https://github.com/ecomfe/echarts-for-weixin/issues 在这个创建一个 issue，然后把复现环境说一下（真机还是调试工具，什么版本）
