### ISSUE TITLE
end point of rectangle bar

### ISSUE THREAD

**Issue by Mhasansiddiqui** [apache/incubator-echarts#10122]
### What problem does this feature solve?
i am implement renko chart through echart . i have start and end point of bar but i am not able to find out where i can place end point.

### What does the proposed API look like?
https://jsfiddle.net/canvasjs/4fk78yn0/

**Comment by Ovilia** [comment]
You should probably use [custom series](https://ecomfe.github.io/echarts-examples/public/index.html#chart-type-custom) to do such things. Doc: https://ecomfe.github.io/echarts-doc/public/en/option.html#series-custom
