### ISSUE TITLE
在react使用时tooltip 和toolbox等不显示

### ISSUE THREAD

**Issue by githubyong** [apache/incubator-echarts#10131]
### Version
4.1.0-release

### Reproduction link
[https://codesandbox.io/s/pmly397xjx](https://codesandbox.io/s/pmly397xjx)

### Steps to reproduce
打开重现连接

### What is expected?
显示tooltip,toolbox,legend等

### What is actually happening?
没有显示上述内容

**Comment by githubyong** [comment]
import 'echarts/lib/component/tooltip';
需要导入tooltip等

**Comment by zhulei11223** [comment]
canvas标签换成div
