### ISSUE TITLE
legend图例当使用了富文本，会显示异常且不可点击

### ISSUE THREAD

**Issue by kxcc** [apache/incubator-echarts#10137]
### Version
4.2.1-rc1

### Steps to reproduce
设置 如下，省略号为任意内容
legend: {
        data: [.........],
        textStyle:{
            rich:{..............}
        }
    },

### What is expected?
富文本生效

### What is actually happening?
所有图例被挤在左上角

---
官网示例可复现
https://www.echartsjs.com/examples/editor.html?c=bar-rich-text

![123](https://user-images.githubusercontent.com/24751083/54673645-9d8b1b00-4b35-11e9-8b20-30cf9b992abe.png)

**Comment by kxcc** [comment]
虽然可以选择不升级最新版本，但是这么低级的错误，你们发布正式版本为啥都没验证到呢？ 建议丰富你们的测试用例，以及对该BUG进行回溯。

**Comment by Ovilia** [comment]
Gallery 上的 ECharts 版本是 4.2.1-rc1，经测试，最新版的 4.2.1 正式版不存在这个问题。Gallery 的版本会尽快更新。
