### ISSUE TITLE
axisPointer动画无法关闭 或手段不明、配置文档不清晰

### ISSUE THREAD

**Issue by holgor** [apache/incubator-echarts#10149]
### Version
4.2.1

### Steps to reproduce
tooltip的axisPointer怎么关闭动画啊？？tooltip是用click触发的，axisPointer移动时会有一个很小的过渡动画，但无论是shadow和cross的axisPointer的移动动画都不知道怎么关闭。尝试过tooltip的transitionDuration和根部配置的animation都不行

### What is expected?
可以实现axisPointer移动是无动画的 瞬间的

### What is actually happening?
axisPointer仍然有动画

**Comment by Ovilia** [comment]
请提供一个例子 https://gallery.echartsjs.com/editor.html

**Comment by holgor** [comment]
> 请提供一个例子 https://gallery.echartsjs.com/editor.html

option = {
    animation:false,
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {},
    tooltip: {
        triggerOn: 'click',
        trigger: 'axis',
        transitionDuration: 0,
        show: true,
        axisPointer: {
            type: 'shadow',
        }
    },
    series: [{
        type: 'line',
        data: [220, 182, 191, 234, 290, 330, 310]
    }]
};

**Comment by Ovilia** [comment]
Hi, I found this is a doc problem rather than a bug. Please use `tooltip.axisPointer.animation: 0` to disable the animation.

```
option = {
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {},
    tooltip: {
        triggerOn: 'click',
        trigger: 'axis',
        transitionDuration: 0,
        show: true,
        axisPointer: {
            type: 'shadow',
            animation: 0,
        }
    },
    series: [{
        type: 'line',
        data: [220, 182, 191, 234, 290, 330, 310]
    }]
};
```

**Comment by holgor** [comment]
> Hi, I found this is a doc problem rather than a bug. Please use `tooltip.axisPointer.animation: 0` to disable the animation.
> 
> ```
> option = {
>     title: {
>         text: 'Awesome Chart'
>     },
>     xAxis: {
>         data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
>     },
>     yAxis: {},
>     tooltip: {
>         triggerOn: 'click',
>         trigger: 'axis',
>         transitionDuration: 0,
>         show: true,
>         axisPointer: {
>             type: 'shadow',
>             animation: 0,
>         }
>     },
>     series: [{
>         type: 'line',
>         data: [220, 182, 191, 234, 290, 330, 310]
>     }]
> };
> ```

thanks for help！！！😁
