### ISSUE TITLE
Y Axis values are displayed but the graph does not appear 

### ISSUE THREAD

**Issue by shivamsriva31093** [apache/incubator-echarts#10153]
![Screenshot from 2019-03-23 18-17-18](https://user-images.githubusercontent.com/17279956/54866308-230e0580-4d98-11e9-9839-68955cdebcb0.png)
### Version
4.1.0-release

### Steps to reproduce
Followed tutorial. Installed echarts in webpack 4   angular 7 project. Created one directive to faciliate the chart usage. It works fine in development build. But when I switch to production mode, Only grid lines and Y -Axis are visible, no chart appear. I get the following error on console:
```
ERROR TypeError: Cannot read property '__ec_inner_8_0.83450' of undefined
    at vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:7834
    at h (vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:7554)
    at c (vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:7547)
    at e.createAxisLabels (vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:7609)
    at r.getViewLabels (vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:95432)
    at vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:382
    at o.axisTickLabel (vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:421)
    at o.add (vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:256)
    at Array.forEach (<anonymous>)
    at Object.y [as each] (vendors~main.b164bad6f3acc8308f3c.chunk.js:formatted:86246)

```
EchartOptions:

```
{
    title: {
      text: '某地区蒸发量和降水量',
      subtext: '纯属虚构'
    },
    tooltip: {
      trigger: 'axis'
    },
    legend: {
      data: ['蒸发量', '降水量']
    },
    toolbox: {
      show: true,
      feature: {
        mark: {show: true},
        dataView: {show: true, readOnly: false},
        magicType: {show: true, type: ['line', 'bar']},
        restore: {show: true},
        saveAsImage: {show: true}
      }
    },
    calculable: true,
    xAxis: [
      {
        type: 'category',
        data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
      }
    ],
    yAxis: [
      {
        type: 'value'
      }
    ],
    series: [
      {
        name: '蒸发量',
        type: 'bar',
        data: [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
        markPoint: {
          data: [
            {type: 'max', name: '最大值'},
            {type: 'min', name: '最小值'}
          ]
        },
        markLine: {
          data: [
            {type: 'average', name: '平均值'}
          ]
        }
      },
      {
        name: '降水量',
        type: 'bar',
        data: [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
        markPoint: {
          data: [
            {name: '年最高', value: 182.2, xAxis: 7, yAxis: 183, symbolSize: 18},
            {name: '年最低', value: 2.3, xAxis: 11, yAxis: 3}
          ]
        },
        markLine: {
          data: [
            {type: 'average', name: '平均值'}
          ]
        }
      }
    ]
  }
```

### What is expected?
The graphs should display as it is in development build  as shown in https://echarts.baidu.com/echarts2/doc/example/bar1.html#-en

### What is actually happening?
Y Axis values are displayed but the graph does not appear

**Comment by Ovilia** [comment]
This should have something to do with the way you import ECharts (maybe something wrong with webpack config). The option itself has no problem.

**Comment by shivamsriva31093** [comment]
In the webpack config, I define a Provider Plugin as 
```
new Provider Plugin {
     echarts: 'echarts'
}
```

Then in an angular component, import the module as:
```
import echarts from 'echarts';
```
Even I tried using angular Adapter by xieziyu.github.io but still getting the same issue.

**Comment by Ovilia** [comment]
Please try with an un-minified version and find what function throws this error in your code.

**Comment by shivamsriva31093** [comment]
I tried using the un-minified version of echarts, but still getting the same error in console in the production build. I downloaded the js file, created one directive and followed the starter tutorial https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Get%20Started%20with%20ECharts%20in%205%20minutes

`import {
  Directive, ElementRef, Input, OnInit, HostBinding, OnChanges, OnDestroy
} from '@angular/core';

import { Subject, Subscription } from 'rxjs';

import * as echarts from '../../../assets/echarts.js';
// import ECharts = echarts.ECharts;
// import EChartOption = echarts.EChartOption;
import { distinctUntilChanged } from 'rxjs/operators';

@Directive({
  selector: '[ts-chart]',
})
export class EchartsDirective implements OnChanges, OnInit, OnDestroy {

  @Input('ts-chart') public options: any;

  @HostBinding('style.height.px')
  public elHeight: number;
  private chart: any;
  private sizeCheckInterval = null;
  private reSize$ = new Subject<string>();
  private onResize: Subscription;

  constructor(private el: ElementRef) {
    this.chart = echarts.init(this.el.nativeElement, 'vintage');
  }

  public ngOnChanges(changes) {
    if (this.options) {
      this.chart.setOption(this.options);
    }
  }

  public ngOnInit() {
    this.sizeCheckInterval = setInterval(() => {
      this.reSize$.next(`${this.el.nativeElement.offsetWidth}:${this.el.nativeElement.offsetHeight}`);
    }, 100);
    this.onResize = this.reSize$.pipe(distinctUntilChanged())
      .subscribe((_) => this.chart.resize());

    this.elHeight = this.el.nativeElement.offsetHeight;
    if (this.elHeight < 300) {
      this.elHeight = 300;
    }
  }

  public ngOnDestroy() {
    if (this.sizeCheckInterval) {
      clearInterval(this.sizeCheckInterval);
    }
    this.reSize$.complete();
    if (this.onResize) {
      this.onResize.unsubscribe();
    }
  }
}
`

the echarts file I also tried using the one generated in dist folder of this project.

**Comment by Ovilia** [comment]
Checkout what's undefined.

**Comment by shivamsriva31093** [comment]
Hi. I filtered the echart.js file in minimizer so that it does not get minified/compressed in production build and it works fine. The following method was returning undefined:

```
function makeCategoryLabelsActually(axis, labelModel) {
    var labelsCache = getListCache(axis, 'labels');
    var optionLabelInterval = getOptionCategoryInterval(labelModel);
    var result = **listCacheGet(labelsCache, optionLabelInterval);**

    if (result) {
      return result;
    }
.
.
.
  function listCacheGet(cache, key) {
    for (var i = 0; i < cache.length; i++) {
      if (cache[i].key === key) {
        return **cache[i]**.value;
      }
    }
  }

```

**Comment by shivamsriva31093** [comment]
@Ovilia Can you suggest what could be the issue with production build?

**Comment by Ovilia** [comment]
I cannot reproduce the error with the option provided. It should be a problem of your own environment, which I'm afraid I could not offer any help.

**Comment by shivamsriva31093** [comment]
Thanks for your reply. Can you please suggest a recommended webpack
configuration. I tried looking up on Google/SO but could not find anything
relevant?
