### ISSUE TITLE
建议地图部分图表能重新搞起来

### ISSUE THREAD

**Issue by Hexa-gram** [apache/incubator-echarts#10169]
What problem does this feature solve?
目前国内的图表库echarts是数一数二的了,但是对于地图库,大部分的人应用地图库只是为了做一个简单的热点图一类的,百度地图太重了,而别的地图库又很少有做的比较好的中国地图,所以希望能搞一个最nb的中国地图库出来,这对于大部分开发者来说,都是一个硬需求,毕竟国内才是中小企业的重点

### What does the proposed API look like?
像以前一样,能提供一个不乱码的china.js就行,现在npm包里的china.js海南诸岛部分乱码

**Comment by Ovilia** [comment]
这个不是乱码，是 ECharts 地图坐标系编码后的，所以其实没问题的。
另外，由于地图版号的问题，ECharts 不提供地图下载功能。

**Comment by Hexa-gram** [comment]
![image](https://user-images.githubusercontent.com/28613856/55056483-31fafd80-50a1-11e9-903b-2d15717d160d.png)

**Comment by Ovilia** [comment]
可以在 https://gallery.echartsjs.com/explore.html#charts=map~sort=rank~timeframe=all~author=all 找一个没问题的下载（通过 console 网络面板）

**Comment by musicode** [comment]
确实需要一个中国地图 + 散点图，每个点 hover 上去能显示地点名称，点越多，那个区域就越亮。

为了做地图图表，搭配一个百度地图实在有点恶心，因为百度地图线条太多了，还有各种外国地名，把图表本该表现的重点，由 `数据` 变成了 `地图`。
