### ISSUE TITLE
实例演示中（mix-line-bar）没有涉及百度地图，却引用了百度地图js

### ISSUE THREAD

**Issue by jason1004** [apache/incubator-echarts#10168]
### Version
4.2.1

### Steps to reproduce
打开 https://echarts.baidu.com/examples/editor.html?c=mix-line-bar

download   html 文件，里面引用了
 <script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=xfhhaTThl11qYVrqLZii6w8qE5ggnhrY&__ec_v__=20190126"></script>

我们线上是按照demo 引用的， 最近ak 发生变化了，导致提示“百度未授权使用地图API”

### What is expected?
按需引用JS ，移除无用的JS

### What is actually happening?
引用的百度地图JS

**Comment by Ovilia** [comment]
这个下载功能是为了便于调试的，所以把相关的一些代码都一起下载了。如果不需要的话，自己移除就可以了。
