### ISSUE TITLE
当树图放大缩小或者移动后，点击根节点后，图表会消失。

### ISSUE THREAD

**Issue by longrenkai** [apache/incubator-echarts#10164]
### Version
4.2.1

### Steps to reproduce
设置树图roam: true,当生成出来的树图放大缩小或者移动后，再次点击根节点收起时，图表会消失。

### What is expected?
点击根节点正常收起，展开，根节点依然还在图表上。

### What is actually happening?
点击根节点后图表消失，根节点不在图表上，无法收起，展开。

**Comment by gaorubin1990** [comment]
确实有这个问题。。坐等更新。。

**Comment by caidaodumogu** [comment]
![图片](https://user-images.githubusercontent.com/18117106/56637134-788e4880-669d-11e9-88a6-bccb28673063.png)
进行移动或放大缩小操作后
![图片](https://user-images.githubusercontent.com/18117106/56637184-95c31700-669d-11e9-84cb-e0f30fa38fec.png)

**Comment by qiuguomuhai** [comment]
我也遇到该问题了，怎么还没更新？

**Comment by deqingli** [comment]
#10291
