### ISSUE TITLE
1 pixel offset between chart area and axis tick mark

### ISSUE THREAD

**Issue by phazor** [apache/incubator-echarts#10161]
### Version
4.2.1

### Reproduction link
[https://ecomfe.github.io/echarts-examples/public/editor.html?c=area-basic](https://ecomfe.github.io/echarts-examples/public/editor.html?c=area-basic)

### Steps to reproduce
1. Create a basic area chart, configured with x-axis tick marks.
2. View the lower right-hand corner.

### What is expected?
The shaded area lines up with the xAxis tick mark.

### What is actually happening?
The shaded area stops 1 pixel before the xAxis tick mark.

Retina screen:
<img width="87" alt="Screenshot 2019-03-25 at 18 43 53" src="https://user-images.githubusercontent.com/1484323/54942035-86ca3700-4f2e-11e9-9dc3-cd5a6baf1cfb.png">

Non-retina screen:
![Screenshot 2019-03-25 at 18 43 43](https://user-images.githubusercontent.com/1484323/54942040-8cc01800-4f2e-11e9-8ab1-d56928792d9b.png)

**Comment by Ovilia** [comment]
This is expected. Consider the left side with axis.
<img width="136" alt="屏幕快照 2019-03-26 17 22 21" src="https://user-images.githubusercontent.com/779050/54985470-d28ee600-4feb-11e9-9760-6927f59532fa.png">
