### ISSUE TITLE
Pie Chart is not drawing label lines when toggling labels and redrawing

### ISSUE THREAD

**Issue by zevero** [apache/incubator-echarts#10167]
### Version
4.2.1

### Steps to reproduce
Pseudocode:
var option = pie chart with label: {show: false}
chart = echarts.init(...)
chart.setOption(option)

all fine ... chart is drawn without labels

now make a new 
var option_label = pie chart with label: {position: 'outside', show: true}
and redraw with
chart.setOption(option_label)

chart is drawn with labels. BUT there are no lines lines to the labels

### What is expected?
Labels should be drawn with lines.

### What is actually happening?
Labels are drawn without lines

---
If the first draw is omitted, lines are drawn just fine.

The other way round first plotting with labels and then plotting without labels will remove the labels, BUT the lines are STILL HERE!

**Comment by zevero** [comment]
First draw without label, then with label
![image](https://user-images.githubusercontent.com/2234140/55015600-7036e500-4fed-11e9-867c-05f5cee4b8fc.png)

First draw with label, then without label
![image](https://user-images.githubusercontent.com/2234140/55015668-9197d100-4fed-11e9-86da-57b36fcb2741.png)

When drawn with label it should look like this
![image](https://user-images.githubusercontent.com/2234140/55015720-aecc9f80-4fed-11e9-91e7-f6d9b6ecf823.png)

**Comment by Ovilia** [comment]
Please provide a demo at https://gallery.echartsjs.com/editor.html or http://jsfiddle.net

**Comment by zevero** [comment]
Here you are 

1) Removing Labels
https://jsfiddle.net/4qcfbx1a/8/
when you click removeLabel, the label is removed, but lines are still there.

2) Adding Labels
https://jsfiddle.net/4qcfbx1a/9
when you click addLabel, the label appear, but lines are not drawn.

**Comment by susiwen8** [comment]
You should add labelLine option
https://echarts.apache.org/option.html#series-pie.labelLine

**Comment by Ovilia** [comment]
@susiwen8 is right.
@zevero You may use
```js
option.series[0].label.show = true;
option.series[0].labelLine = {show: true};
```

**Comment by zevero** [comment]
Thank you a lot!
