### ISSUE TITLE
series.encode可以取消默认设置

### ISSUE THREAD

**Issue by cn-xufei** [apache/incubator-echarts#10160]
### What problem does this feature solve?
在没有配置encode时，echarts会默认选择数据，但当用户没有决定或者明确决定图表展示哪些维度时，这样有点不太友好，希望可以选择，当没有配置encode时，图表不渲染

### What does the proposed API look like?
encode.x = null/undefined

**Comment by Ovilia** [comment]
这个不太合适，图表不渲染用户也不知道是为什么不渲染，只会觉得是 bug。

**Comment by cn-xufei** [comment]
有一种使用场景，就是用户是来做数据分析的，他决定x、y渲染哪个维度，当没有配置默认和维度的时候，出现数据不太恰当

**Comment by Ovilia** [comment]
这种情况的话，在初始化的时候先不用传入数据，或者传个假的 encode 之类的都行。但是把没有设置 encode 就不显示数据作为一种默认的逻辑是不合适的。
