### ISSUE TITLE
your issue helper uses `GET` method instead of `POST` to create new issues, which doesn't work if you create detailed issues.

### ISSUE THREAD

**Issue by arashdalir** [apache/incubator-echarts#10179]
### Version
4.2.1

### Steps to reproduce
open your [issue helper](https://ecomfe.github.io/echarts-issue-helper/),, also open issue [#10178](https://github.com/apache/incubator-echarts/issues/10178), copy my comments from the two sections into your tools, click preview, and create the issue! you will get:

`414 Request-URI Too Large - nginx`

### What is expected?
the form should be submitted using `POST`: it's basic ReST or web-page design!

### What is actually happening?
you are sending the issue using `GET`:

```html
Request URL: https://github.com/apache/incubator-echarts/issues/new?title=Axis%20Information%20for%20tooltip.axisPointer.label.formatter%20function&body=%23%23%23%20What%20problem%20does%20this%20feature%20solve%3F%0A**using%20Echarts%20v4.2.1**%0A%0Awhen%20using%20%20%60tooltip.axisPointer.label.formatter%60%2C%20(usually)%20there%20is%20no%20information%2C%20to%20which%20axis%20the%20data%20belongs.%20this%20makes%20it%20hard%20to%20format%20the%20value%20as%20desired.%0A%0AAlthough%20the%20%5Bdocumatation%5D(https%3A%2F%2Fecomfe.github.io%2Fecharts-doc%2Fpublic%2Fen%2Foption.html%23tooltip.axisPointer.label.formatter)%20talks%20about%20each%20item%20of%20the%20%60params.seriesData%60%20having%20axis%20information%20delivered%20with%20them%2C%20as%20shown%20in%20the%20example%20below%2C%20the%20%60params.seriesData%60%20is%20emp
```

**Comment by Ovilia** [comment]
Is there any document states that GitHub supporting POST when creating new issue?
If so, please raise an issue at https://github.com/Ovilia/echarts-robot .
