### ISSUE TITLE
echart3.x 和 4.x版本中，legend 由多变少时，图表无更新

### ISSUE THREAD

**Issue by zhangdxchn** [apache/incubator-echarts#10171]
### Version
4.2.1-rc1

### Reproduction link
[https://jsbin.com/vayovaguve/edit?html,output](https://jsbin.com/vayovaguve/edit?html,output)

### Steps to reproduce
注意看，alert提示， 数据重新加载，但legend 的标签数量变化了，但数据显示还在

### What is expected?
折线由两条变为1条

### What is actually happening?
无变化

---
异步数据加载，切换不同数量的legend数据

**Comment by Ovilia** [comment]
应该使用 `chart.setOption(option, true)` 使得不和之前的配置项合并，也就是可以删除系列。但是这个 case 好像的确存在 bug。

**Comment by zhangdxchn** [comment]
确认了，可以解决问题，比我 depose 掉重新绘制合理多了。感谢！！！
自动合并是有问题的，官网教程写的太简单啦，对回归使用最新版本的老手不友好 😂https://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0
