### ISSUE TITLE
echarts 的 convertToPixel  方法无法获取 tree图节点坐标

### ISSUE THREAD

**Issue by nuancheng** [apache/incubator-echarts#10175]
### What problem does this feature solve?
树图的节点上可能会需要展示很多信息，采用图表展示，所以需要节点的坐标，可是根据提供的API并不能获取

### What does the proposed API look like?
convertToPixel  方法可以获取所有节点的位置

**Comment by deqingli** [comment]
https://echarts.apache.org/zh/api.html#echartsInstance.convertToPixel，该接口用于转换坐标系上的点到像素坐标值。tree 并不是一个坐标系。
