### ISSUE TITLE
clicking on scatter upon a map will trigger a click event on map

### ISSUE THREAD

**Issue by lee88688** [apache/incubator-echarts#10181]
### Version
4.2.1

### Steps to reproduce
I both register click event for map and scatter in a chart, and both in map and scatter click callback will call setOption function to refresh chart. When I click on scatter, the scatter click callback will executive but the map click will be also called. On the contrary, when I click on map, the map click callback calls and the scatter callback is not called. here is my code for register callbacks.
    echartsInstance.on("click", "series.scatter", function (e) {
        self._drawLine();
        self._highlightProvince();
        self.refresh();  // in this function will call echartsInstance.setOption
    });

    echartsInstance.on("click", "series.map", function (e) {
        self._drawLine();
        self._highlightProvince(e.name);
        self.refresh();
    });

### What is expected?
only scatter callback is called.

### What is actually happening?
both scatter and map callback is called.

**Comment by Ovilia** [comment]
Can you provide an online demo at http://jsfiddle.net ?

**Comment by lee88688** [comment]
https://codepen.io/lee88688/full/MRweJL
on line 228 and line 234, I register click event for map and scatter. when I click on scatter item, it will log both 'click on scatter' and 'click on map'. only 'click on scatter' log is expected.
@Ovilia

**Comment by Ovilia** [comment]
Why don't you just remove the listener on map `myChart.on("click", "series.map", function (e) {`?

**Comment by lee88688** [comment]
I want clicking both map and scatter would highlight the province. if I remove click event on map, when clicking on map, it would not highlight the province.

**Comment by Ovilia** [comment]
How about removing
```js
self._drawLine();
self._highlightProvince(e.name);
self.refresh();
```

I'm not quite sure if I fully understand what you want.

**Comment by lee88688** [comment]
if I use echartsInstance.setOption in scatter's click event, it will trigger map's click event.
