### ISSUE TITLE
设置serie的属性

### ISSUE THREAD

**Issue by tinybright** [apache/incubator-echarts#10187]
### What problem does this feature solve?
文档里要我们用setOption 更新数据  又不让我们用getOption 然后改变的方式变更 请问怎么变更？
var options = chart.getOption();
options.series[0]['type'] = 'line';
chart.setOption(options)

### What does the proposed API look like?
chart.getSerieByIndex()
chart.updateSerie()

**Comment by Ende93** [comment]
比如：
```js
const opt = {...}
charts.setOption(opt)
// 修改 opt
opt.xAxis = {...}
// 设置
charts.setOption(opt)
```

**Comment by Ovilia** [comment]
https://echarts.baidu.com/api.html#echartsInstance.setOption setOption 的第二个参数设为 true

**Comment by tinybright** [comment]
notMerge

可选，是否不跟之前设置的 option 进行合并，默认为 false，即合并。

lazyUpdate

可选，在设置完 option 后是否不立即更新图表，默认为 false，即立即更新。

不合并的意思是重新设置 也是浪费 @Ovilia

**Comment by tinybright** [comment]
@Ende93 
现在就是这么搞得 会不会有性能问题

**Comment by Ende93** [comment]
性能其实没啥影响
