### ISSUE TITLE
Toolbox: Stack Mode (MagicType) not compatible with DataZoom

### ISSUE THREAD

**Issue by jbadilla** [apache/incubator-echarts#10193]
### Version
4.2.1

### Steps to reproduce
If you have an active `toolbox.feature.magicType` (line, bar, stack and tiled) in your graph, then you cannot also have a `toolbox.feature.dataZoom`, otherwise the 'Stack' mode will not work correctly.

This is a minor bug, but needs to be fixed.

### What is expected?
I expect the stack mode to work correctly (i.e. re-set the value axis labels to match the scale of the stacked bars).

### What is actually happening?
Bug: The Stack mode overflows the given Y-Axis if there is a `toolbox.feature.dataZoom`, even if `show` is set to `true`

**Comment by Ovilia** [comment]
Please provide an onlinde demo at http://jsfiddle.net

**Comment by beda42** [comment]
Hello, I ran into this problem as well. Here is the requested fiddle:

http://jsfiddle.net/t51qgve2/1/

You can see the data overflowing the top of the Y-axis. If you comment out the dataZoom toolbox feature, if works ok again.
(BTW, it worked correctly with echarts 3.2.2)

Cheers
Beda

**Comment by akenverus** [comment]
Not fixed.
