### ISSUE TITLE
xAxis-axisLabel 是否能提供加入icon功能

### ISSUE THREAD

**Issue by mmmaomao21** [apache/incubator-echarts#10198]
### What problem does this feature solve?
demo中可以通过rich实现插入图片，想知道是否可能直接插入tag <Icon>，直接插入图标
axisLabel: {
            formatter: function (value) {
                return '{' + value + '| }\n{value|' + value + '}';
            },
            margin: 20,
            rich: {
                value: {
                    lineHeight: 30,
                    align: 'center'
                },
                Sunny: {
                    height: 40,
                    align: 'center',
                    backgroundColor: {
                        image: weatherIcons.Sunny
                    }
                },
                Cloudy: {
                    height: 40,
                    align: 'center',
                    backgroundColor: {
                        image: weatherIcons.Cloudy
                    }
                },
                Showers: {
                    height: 40,
                    align: 'center',
                    backgroundColor: {
                        image: weatherIcons.Showers
                    }
                }
            }
        }
### What does the proposed API look like?
能够直接插入标签

**Comment by Ovilia** [comment]
直接插入标签是什么意思？

**Comment by mmmaomao21** [comment]
@Ovilia 例如tooltips中可以用formatter:function(){  return '<i class="icon"></i>'  }
可以直接插入标签，显示图标。而axisLabel似乎只有通过rich设置图片，没办法通过插入dom的方法插入icon。有办法可以在axisLabel中插入图标吗（不使用rich的情况下）？

**Comment by mmmaomao21** [comment]
`tooltip : {
        formatter:function(){
            return '<i class="icon"></i>'
        }
    },`

**Comment by Ovilia** [comment]
axisLabel 是画在 canvas 上的，tooltip （如果不用 rich 模式）默认是产生新的 DOM 节点的。所以 axisLabel 没法实现自定义的 DOM 结构。
