### ISSUE TITLE
利用echart画graph图的线颜色百分比的起始位置设置为箭头的开始位置

### ISSUE THREAD

**Issue by lakakala** [apache/incubator-echarts#10207]
### What problem does this feature solve?
我利用Echart graph图表示一段时间内两个服务器链路连通性，需要用不同的颜色来表示此时链路状态，我是将时间转换为百分比来设置两个服务器之间线的颜色。由于两个服务器的位置是不固定的，所以需要设置颜色百分比的起始位置跟服务器的关系一致

### What does the proposed API look like?
设置lineStyle时可以设定颜色百分比的起始位置为series[i]-graph.links[i].source的位置

**Comment by Ovilia** [comment]
不明白什么意思，请提供可复现的代码和想要的效果
