### ISSUE TITLE
大数据量折线图性能问题

### ISSUE THREAD

**Issue by lr1739** [apache/incubator-echarts#10200]
### Version
4.2.1

### Steps to reproduce
var dataLength=10000;
var _xPoints = new Array(dataLength);
var first = 88;
for (var i = 0; i < dataLength; i  ) {
	_xPoints[i] = (first   0.025 * i).toFixed(3);
}
option = {
    animation:false,
    xAxis: {
        type: 'category',
        data: _xPoints
    },
    yAxis: {
        type: 'value',
        min:0,
        max:100
    },
    series: [{
        data: [],
        type: 'line'
    }]
};
function getRandomData(){
	var data=[];
	for (var i = 0; i < dataLength; i  ) {
		data.push(Math.floor(Math.random()*90));
	}
	return data;
}
setInterval(function(){
    myChart.setOption({series:[{
                data: getRandomData()
            }]})
},500)

### What is expected?
大数据量折线图能够流畅绘制

### What is actually happening?
卡顿

---
动态更新折线图，折线最多能达到10多万个点。
在1万个点以上的时候，动态更新的时候就已经开始不流畅。
在数据量很大的情况下能否使用webgl对2D图形的绘制进行加速，highcharts就有类似的实现

**Comment by Ovilia** [comment]
建议将 [showSymbol](https://echarts.baidu.com/option.html#series-line.showSymbol) 设为 false，并且开启 [samping](https://echarts.baidu.com/option.html#series-line.sampling)

**Comment by lr1739** [comment]
> samping



> 建议将 [showSymbol](https://echarts.baidu.com/option.html#series-line.showSymbol) 设为 false，并且开启 [samping](https://echarts.baidu.com/option.html#series-line.sampling)

showSymbol几乎没什么作用，sampling开启之后图形严重失真

**Comment by Ovilia** [comment]
可以提供下截图对比吗？

**Comment by nerffei** [comment]
我是8万个点显示，我的x轴类型设置的是value类型，我开了最大值采样, 没有遇到卡顿跟失帧真问题
