### ISSUE TITLE
4.0版本以后,绘制半圆的南丁格尔图的 数据value为0的时候无法隐藏label和labelline,

### ISSUE THREAD

**Issue by dengzengjian** [apache/incubator-echarts#10218]
![1554369766(1)](https://user-images.githubusercontent.com/21662617/55549605-d36cf980-5708-11e9-8368-23177e5ba987.jpg)
### Version
4.1.0-release

### Steps to reproduce
在gallery中即3.8.0版本 运行是正常的,在4.0版本以后有多余的label线和label,设置了minShowLabelAngle 为true 也无效
代码如下:
this.chart.setOption({
// backgroundColor: "rgb(43, 51, 59)",
toolbox: {
show: false,
feature: {
mark: {
show: true
},
dataView: {
show: true,
readOnly: false
},
magicType: {
show: true,
type: ["pie", "funnel"]
},
restore: {
show: true
},
saveAsImage: {
show: true
}
}
},
calculable: true,
tooltip: {
trigger: "item",
formatter: "{a}
{b}:{c}个"
},
title: {
// text: "受纳场项目统计",
left: "center",
top: 10,
textStyle: {
color: "#ccc"
}
},
calculable: true,
legend: {
// icon: "circle",
x: "center",
y: "15%",
data: ["在建", "已完工", "为规划", "已规划"],
textStyle: {
color: "#fff"
}
},
series: [
{
name: "受纳场项目",
type: "pie",
radius: [17, 85],
avoidLabelOverlap: false,
stillShowZeroSum:true,
startAngle: 0,
// radius:'55%',绘制半圆
center: ["50.0%", "38%"],
roseType: "area",
selectedMode: "single",
label: {
normal: {
show: true,
formatter: "{c}个"
},
emphasis: {
show: true
}
},
labelLine: {
normal: {
show: true,
smooth: false,
length: 20,
length2: 10
},
emphasis: {
show: true
}
},
data: [
{
value: 600.58,
name: "已完工",
itemStyle: {
normal: {
color: "#FFD900"
}
}
},
{
value: 1100.58,
name: "在建",
itemStyle: {
normal: {
color: "#24C768"
}
}
},
{
value: 1200.58,
name: "未规划",
itemStyle: {
borderWidth:0,
normal: {
color: "#FF7E00"
}
}
},
{
value: 1300.58,
name: "已规划",
itemStyle: {
normal: {
color: "#00A1E4"
}
}
},
{
value: 0,
name: "",
itemStyle: {
opacity: 0,
normal: {
label: {
show: false
},
labelLine: {
show: false
}
}
}
},
{
value: 0,
name: "",
itemStyle: {
normal: {
label: {
show: false
},
labelLine: {
show: false
}
}
}
},
{
value: 0,
name: "",
itemStyle: {
normal: {
label: {
show: false
},
labelLine: {
show: false
}
}
}
},
{
value: 0,
name: "",
itemStyle: {
normal: {
label: {
show: false
},
labelLine: {
show: false
}
}
}
}
/* {
value: 0,
name: "",
itemStyle: {
normal: {
label: {
show: false
},
labelLine: {
show: false
}
}
}
},
{
value: 0,
name: "",
itemStyle: {
normal: {
label: {
show: false
},
labelLine: {
show: false
}
}
}
} */
]
}
]
});

### What is expected?
不会显示多余的label和label线

### What is actually happening?
显示了多余的label和label线

**Comment by susiwen8** [comment]
@dengzengjian 你应该这么设置
`                        {
                            value: 0,
                            name: "",
                            label: {
                                show: false
                            },
                            labelLine: {
                                show: false
                            },
                        }
`
文档中的配置项itemStyle没有normal
https://www.echartsjs.com/option.html#series-pie.data.itemStyle

**Comment by dengzengjian** [comment]
> @dengzengjian 你应该这么设置
> ` { value: 0, name: "", label: { show: false }, labelLine: { show: false }, }`
> 文档中的配置项itemStyle没有normal
> https://www.echartsjs.com/option.html#series-pie.data.itemStyle

谢谢,解决了.这个4.0 以后的版本跟3版本是不一样的,按你说的,把itemStyle和normal两层去掉就行了
