### ISSUE TITLE
在作pie饼图时候负数时出现了斜线

### ISSUE THREAD

**Issue by lengmoukong** [apache/incubator-echarts#10213]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xkC8Tjydh0&comment=0](https://gallery.echartsjs.com/editor.html?c=xkC8Tjydh0&comment=0)

### Steps to reproduce
更改value值为负数

### What is expected?
不出现斜线

### What is actually happening?
出现斜线了

---
在一些分析数据报告时会进行24小时的变化，其中会有负数

**Comment by Ovilia** [comment]
饼图数据就不该有负数，负数想表达什么意义呢？期望什么效果呢？

**Comment by lengmoukong** [comment]
> 饼图数据就不该有负数，负数想表达什么意义呢？期望什么效果呢？
我们在做24小时数据均值变化得时候  发现变化有正有负 采用的饼图

**Comment by Ovilia** [comment]
传入数据的时候，map 一下你的数据，把负数变为 0

**Comment by lengmoukong** [comment]
好的
