### ISSUE TITLE
【咨询】在折线图中鼠标hover时，tooltip能否只展示最近一条线的数据？

### ISSUE THREAD

**Issue by kxcc** [apache/incubator-echarts#10216]
### What problem does this feature solve?
类似于echart2的tooltip功能
当前的实现是：展示x轴点上所有的y轴数据。

### What does the proposed API look like?
类似于echart2的tooltip功能

**Comment by Ovilia** [comment]
https://echarts.baidu.com/option.html#tooltip.trigger trigger 是 item 的时候，应该是这个效果，但是如果不是 hover 在数据点上就不会显示。
