### ISSUE TITLE
Toolbox zoom returns chart in odd state

### ISSUE THREAD

**Issue by ClemMakesApps** [apache/incubator-echarts#10224]
### Version
4.2.1

### Steps to reproduce
1. Go to https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-tooltip-touch
1. Select the first toolbox icon
1. Select a small area of the chart

### What is expected?
Zoomed in area of the chart

### What is actually happening?
No data displayed on the chart

![2019-04-05 09 41 57](https://user-images.githubusercontent.com/3363898/55635987-8aa85580-5787-11e9-8f0c-a4c2d4758cc6.gif)

**Comment by Ovilia** [comment]
This is a bug when no data is selected in the visible area, but `areaStyle` should still be applied, which in this case is the background color under data lines.
We should improve our clipping ability so that the area can be rendered and clipped. 
Related to #10010 .

**Comment by pissang** [comment]
It's because of the `dataZoom` component filter out all the data and there are only one point exits.

Just pushed a commit https://github.com/apache/incubator-echarts/commit/d80db8e577a80efaed0c84ff96a424e0e37ad8de to support [filterMode](https://echarts.apache.org/en/option.html#dataZoom-slider.filterMode) in the toolbox dataZoom.

It can be fixed by following config:

```js
toolbox: {
  feature: {
    dataZoom: { filterMode: 'none' }
  }
}
```

**Comment by pissang** [comment]
I found in this case. Set `filterMode: 'none' ` in the exists dataZoom also works.

![image](https://user-images.githubusercontent.com/841551/65043858-5c61af80-d98e-11e9-977a-a8aab0296d1c.png)

But if you only want the dataZoom in toolbox. You may need this commit.

**Comment by Muqeet1** [comment]
@Ovilia @pissang this issue seems to still linger on even in 5.1.2, I have tried 5.3.2 as well & your fix mentioned here did not work for my use case either, please re-open this issue or maybe we can create a new one
