### ISSUE TITLE
连续刷新，ios系统的表现出一片白板，不渲染。建议echarts团队看看这个问题

### ISSUE THREAD

**Issue by Chasen-Zhang** [apache/incubator-echarts#10226]
### Version
4.1.0-release

### Steps to reproduce
连续刷新，ios系统的表现出一片白板，不渲染。建议echarts团队看看这个问题

### What is expected?
解决部分苹果机渲染出现白屏的问题

### What is actually happening?
解决部分苹果机渲染出现白屏的问题

**Comment by Ovilia** [comment]
请提供一个可复现的例子 https://gallery.echartsjs.com/editor.html
连续刷新是指多次 setOption 吗？
部分苹果机有特定的型号吗？

**Comment by Chasen-Zhang** [comment]
改成了svg渲染ok了 ，暂时可以了
myChart = echarts.init(document.getElementById("echarts"),null,{renderer:'svg'})

**Comment by Chasen-Zhang** [comment]
> 请提供一个可复现的例子 https://gallery.echartsjs.com/editor.html
> 连续刷新是指多次 setOption 吗？
> 部分苹果机有特定的型号吗？

刷新只一次setOption，没有多次。
苹果7plus、iphoneX上出现，其他机型未测。我觉得很多人都出现了这个问题哦。

**Comment by Ovilia** [comment]
只设置一次的话，连续刷新是指什么，动画的渲染吗？
有特定的例子吗，还是说所有图标都有这个问题？
我虽然找了个图表，在 iPhone 7 上并不能复现。请提供更多的信息。

**Comment by Chasen-Zhang** [comment]
> 只设置一次的话，连续刷新是指什么，动画的渲染吗？
> 有特定的例子吗，还是说所有图标都有这个问题？
> 我虽然找了个图表，在 iPhone 7 上并不能复现。请提供更多的信息。

刷新一下，等图渲染出来。再刷新一下，等图出来。像这样重复20次以上就会复现，请用iphone7plus 或者iphoneX实验

**Comment by luruxi** [comment]
> 改成了svg渲染ok了 ，暂时可以了
> myChart = echarts.init(document.getElementById("echarts"),null,{renderer:'svg'})

我也遇到这个问题了，试试你这个方法吧，3q
