### ISSUE TITLE
4.2.1版本横轴设置rotate后最后一个label加粗

### ISSUE THREAD

**Issue by xjh3173** [apache/incubator-echarts#10220]
### Version
4.2.1

### Steps to reproduce
option = {
grid: [{
left: 32,
right: 32,
top: 80,
bottom: 15,
containLabel: true
}],
tooltip: {
trigger: 'axis',
axisPointer: {
type: 'shadow'
}
},
xAxis: [{
type: 'category',
axisLine: {
show: false
},
axisTick: {
show: false
},
axisLabel: {
interval: 0,
margin: 10,
rotate: 30,
color: '#666'
},
data: ['福田区', '罗湖区', '龙岗区']
}],
yAxis: [{
type: 'value',
axisLine: {
show: false
},
axisTick: {
show: false
},
splitLine: {
show: true
}
}],
series: [{
type: 'bar',
barWidth: 16,
data: [210, 130, 66],
itemStyle: {
normal: {
color: '#ccc'
}
},
label: {
show: true,
position: 'top',
fontWeight: 'bold',
color: '#000'
}
}]
}

### What is expected?
label不加粗

### What is actually happening?
label加粗

![image](https://user-images.githubusercontent.com/26913672/55552683-9c9ae180-5710-11e9-89d0-4def20db36f0.png)

**Comment by Ovilia** [comment]
4.2.1 正式版本无法复现，Canvas 渲染效果正常，SVG 查看属性也没有加粗。
请确保使用的不是 rc 版本，而是正式版本。如需进一步帮助，请在 https://gallery.echartsjs.com/editor.html 复现。
