### ISSUE TITLE
Echarts 对TypedArray的支持问题

### ISSUE THREAD

**Issue by nerffei** [apache/incubator-echarts#10223]
### Version
4.2.1

### Steps to reproduce
我需要用echarts渲染一些折线图，但是我的数据源是TypedArray,我的配置大概如下面

```javascript
{
  xAxis: { type: 'value' },
  yAxis: { type: 'value' },
  dataset: {
    dimensions:[
      { name: 'x', type: 'float'}, 
      { name: 'y', type: 'float'}
    ],
    source: [
      x, y
    ],        
  },
  series: {
    type: 'line',
    sampling: 'max',
    encode: {
      'y': 'y',
      'x': 'x'
    },
    seriesLayoutBy: 'row'
  }
}
```

其中**dataset.source**中的**x**,**y**是**float64Array**

### What is expected?
正确的显示折线图

### What is actually happening?
页面空白没有显示任何信息

---
但是如果我用

```javascript
Array.from(x)
Array.from(y)
```

即把typedarray转化成array之后, 图表能正常显示

我尝试去定位这个问题. 

我在 **lib/data/helper/sourceHelper.js**中的函数**detectSourceFormat**中发现了些问题, 这个函数的功能好像是决定source类型

```javascript
function detectSourceFormat(datasetModel) {
  var data = datasetModel.option.source;
  // 这个data来自于配置中的source
  ....
  for (var i = 0, len = data.length; i < len; i  ) {
    var item = data[i];
    if (item == null) {
      continue;
     // 问题出现在这边判断上, 如果是source是[typedarray, typedarray], 无法识别为typedarray
    } else if (isArray(item)) {
      sourceFormat = SOURCE_FORMAT_ARRAY_ROWS;
      break;
    } else if (isObject(item)) {
      sourceFormat = SOURCE_FORMAT_OBJECT_ROWS;
      break;
    }
  }
}
```

后面我加上了判断

```javascript
....
var item = data[i];
// 有问题
if (item == null) {
  continue;
} else if(isTypedArray(item)) { // 判断了是不是类型数组
  sourceFormat = SOURCE_FORMAT_TYPED_ARRAY
  break;
} else if (isArray(item)) {
  sourceFormat = SOURCE_FORMAT_ARRAY_ROWS;
  break;
} else if (isObject(item)) {
  sourceFormat = SOURCE_FORMAT_OBJECT_ROWS;
  break;
}
...
```

修改完成之后，图表依旧无法显示.之后，我在**lib/data/List.js**下发现 **listProto.initData**中的

```
this._initDataFromProvider(0, data.count())
```

这行好像有问题，**data.count()**的返回值是1, 这个错误的返回值导致后面计算storage时候出现了问题,在**listProto._initDataFromProvider**

```javascript
prepareChunks(storage, dimInfo, chunkSize, originalChunkCount, end);
// 这里storage是[NaN]
```

我在**lib/data/helper/dataProvider.js**中找到了typedArray **count**方法的实现

```javascript
  'typedArray': {
    persistent: false,
    pure: true,
    count: function () {
      // 我的dataset.source是输入两个类型数组, 这里永远返回1
      return this._data ? this._data.length / this._dimSize : 0;
    },
    getItem: function (idx, out) {
      idx = idx - this._offset;
      out = out || [];
      var offset = this._dimSize * idx;

      for (var i = 0; i < this._dimSize; i  ) {
        out[i] = this._data[offset   i];
      }

      return out;
    },
    appendData: function (newData) {
      this._data = newData;
    },
    // Clean self if data is already used.
    clean: function () {
      // PENDING
      this._offset  = this.count();
      this._data = null;
    }
  }
```

我很想继续追踪解决这个问题，但是我实在没搞清楚这个cout跟**prepareChunks**具体是做什么的，抱歉，水平有限，来找帮助了

**Comment by EqualMa** [comment]
To reproduce this issue:

Open [echarts online editor](https://www.echartsjs.com/examples/zh/editor.html) and paste the following coding, click *Run*

## repro the issue

```js
const x = new Float64Array([1,2,3,4,5,6,7,8,9,10]);
const y = new Float64Array([34,7657,235.5,54,0,5477,3325,500,4000,2000]);

option = {
  xAxis: { type: 'value' },
  yAxis: { type: 'value' },
  dataset: {
    dimensions:[
      { name: 'x', type: 'float'}, 
      { name: 'y', type: 'float'}
    ],
    source: [
      x, y
    ],        
  },
  series: {
    type: 'line',
    sampling: 'max',
    encode: {
      'y': 'y',
      'x': 'x'
    },
    seriesLayoutBy: 'row'
  }
};
```

It doesn't work.

## workaround 1

With `x` being a js array, it works. (You don't even need to change `y`)

```js
const x = Array.from(new Float64Array([1,2,3,4,5,6,7,8,9,10]));
```

## workaround 2

Note that the following code also works:

```js
const data = new Float64Array([1,34, 2,7657, 3,235.5, 4,54, 5,0, 6,5477, 7,3325, 8,500, 9,4000, 10,2000])

var option = {
  xAxis: { type: 'value' },
  yAxis: { type: 'value' },
  dataset: {
    dimensions:[
      { name: 'x', type: 'float'}, 
      { name: 'y', type: 'float'}
    ],
    source: data // NOTE: use an one dimension Float64Array to represent [x1, y1, x2, y2, ...]
  },
  series: {
    type: 'line',
    sampling: 'max',
    encode: {
      'y': 'y',
      'x': 'x'
    },
    seriesLayoutBy: 'row'
  }
};
```

So I guess using an one dimension Float64Array to represent `[x1, y1, x2, y2, ...]` is the proper way to use TypedArray, but I couldn't find any docs about that, though the main page of the site says it features supporting TypedArray.

**Comment by nerffei** [comment]
> features

Thanks for your reply ! 

This question is too long, I almost have forgot  😢

But maybe，
![image](https://user-images.githubusercontent.com/25292690/79227091-fa204d00-7e91-11ea-9ee7-4c3272adc3aa.png)
here is the problem, So an one dimension arrary  is fine.

I tried to solve this problem by my self, but it's hard for me to unstanderstand  that code

I solved it by using **Array.from** 

Thanks again,  i'll close this issuse soon

**Comment by anymos** [comment]
not sure why this issue is closed ... it is not fixed, as of now there is still a need to use 

const x = Array.from(new Float64Array([1,2,3,4,5,6,7,8,9,10]));

to then use const y = new Float64Array([34,7657,235.5,54,0,5477,3325,500,4000,2000]);
