### ISSUE TITLE
柱状图的柱子的宽度支持到itemStyle定义

### ISSUE THREAD

**Issue by wind108369** [apache/incubator-echarts#10229]
### What problem does this feature solve?
柱状图中的柱状宽度是可以提供一个维度的信息的，目前echarts中barWidth是会被共享的，期望能够支持更细粒度的配置。

![image](https://user-images.githubusercontent.com/1305983/55697925-1cb59580-59f6-11e9-8b20-b5b4f5d0d808.png)
如图，可以使用柱子宽度表示利润率，可视化的效果得到提升。

### What does the proposed API look like?
```
{
   type: 'bar',
   barWidth: 5,
   data: [
      { value: 100, barWidth: 10},
      { value: 10, barWidth: 20},
   ]
}
```

**Comment by deqingli** [comment]
You can custom the barWidth through `custom.series`, see the [demo](https://www.echartsjs.com/examples/editor.html?c=custom-profit).
