### ISSUE TITLE
visualMap piecewise, when categories' items are the same, it won't mapping the correct color

### ISSUE THREAD

**Issue by susiwen8** [apache/incubator-echarts#10225]
### Version
4.2.1

### Steps to reproduce
Just set all items in visualMap's categories as same value, for example ['a', 'a']. but inRange color are't, say ['blue', 'red']

### What is expected?
The first 'a' should be blue and the second one should be red

### What is actually happening?
Both 'a' are red

---
Here is my option:
            var option = {
                legend: {},
                grid: {},
                tooltip: {},
                xAxis: {
                    splitLine: {
                        show: false
                    }
                },
                yAxis: {
                    splitLine: {
                        show: false
                    }
                },
                : [{
                    left: 'right',
                    top: '10%',
                    type: 'piecewise',
                    dimension: 2,
                    categories: ['a', 'a'],
                    inRange: {
                        color: ['blue', 'red']
                    },
                    outOfRange: {
                        color: 'gray'
                    },
                }, ],
                series: [{
                    name: '北京',
                    type: 'scatter',
                    data: [
                        [0.78, 3.29, 'a'],
                        [1.05, 5.678, 'a'],
                    ]
                }, ]
            };

**Comment by susiwen8** [comment]
The problem is caused by function preprocessForSpecifiedCategory, specifically, when create categoryMap object, 
` each$9(categories, function (cate, index) {
        categoryMap[cate] = index;
    });` 
The second one will cover the first one.

**Comment by Ovilia** [comment]
Categories are served as IDs and should be unique.

**Comment by susiwen8** [comment]
@Ovilia Yes, that's what I thought, and I think in production no one will use same categories.
