### ISSUE TITLE
data-background not visible for custom series

### ISSUE THREAD

**Issue by tmtron** [apache/incubator-echarts#10238]
### Version
4.2.1

### Reproduction link
[https://ecomfe.github.io/echarts-examples/public/editor.html?c=cycle-plot](https://ecomfe.github.io/echarts-examples/public/editor.html?c=cycle-plot)

### Steps to reproduce
create a chart with a custom series and activate the zoom-slider component.

### What is expected?
the data-zoom should show the data-background

### What is actually happening?
the data-background is empty

---

Not sure if this is a bug - or has just not been implemented (in the later case, please consider this a feature request)

Since the custom render function returns graphic elements, it should be possible to show a data-preview, right?  

If not, then it is maybe possible to use the data  (via encode), so that we can at least display the regions where we have some data.

**Comment by Ovilia** [comment]
What is the data background do you mean? What's the related code?

**Comment by tmtron** [comment]
> What is the data background do you mean?

e.g. in this [example](https://ecomfe.github.io/echarts-examples/public/editor.html?c=area-simple) (I've highlighted) the data-background in the zoomslider (the small red line):
![image](https://user-images.githubusercontent.com/20422904/55777993-f2b9ad00-5aa1-11e9-827e-24861796652b.png)
This does not work for custom series.

> What's the related code?

Not sure what your mean: there is not really any code for this - when you activate the [zoom slider](https://ecomfe.github.io/echarts-doc/public/en/option.html#dataZoom-slider.type)  in the options, 

```
    option = {
        dataZoom: [{
            type: 'slider',
            },
        ...
```
you automatically see the data-background (there are however some [styling options](https://ecomfe.github.io/echarts-doc/public/en/option.html#dataZoom-slider.dataBackground))

**Comment by Ovilia** [comment]
This is a feature not supported, rather than a bug.

**Comment by mathiaslaramee** [comment]
@Ovilia is this something that is being worked on?
I think it'd be nice if custom series/plotting could be visualized in the sparkline too. If not supported internally, any idea on how to do this manually?
