### ISSUE TITLE
v4.2.1 toolbox.feature.magicType.icon 设置成 svg 导致页面卡死 v4.1.1 对应功能正常

### ISSUE THREAD

**Issue by xiezhongfu** [apache/incubator-echarts#10247]
### Version
4.2.1

### Steps to reproduce
toolbox.feature.magicType.icon 设置成 svg
```svg
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1500985172208" class="icon" style="" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1868" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24"><defs><style type="text/css"></style></defs><path d="M921.984 255.808a96 96 0 1 0-58.88-25.088L759.04 450.752a96.192 96.192 0 0 0-93.12 27.648L448 349.568a96 96 0 1 0-179.456 49.92l-138.24 182.784a96 96 0 1 0 48.832 41.6l137.92-182.4a95.808 95.808 0 0 0 110.208-29.824l212.928 125.888a96 96 0 1 0 172.672-51.008l109.12-230.72zM32 832h896a32 32 0 1 1 0 64H32a32 32 0 1 1 0-64z" p-id="1869"></path></svg>
```

### What is expected?
图形正常渲染

### What is actually happening?
页面卡死

**Comment by Ovilia** [comment]
icon svg 的正确写法是 `'path://M921.984 255.808a96 96 0 1 0-58.88-25.088L759.04 450.752a96.192 96.192 0 0 0-93.12 27.648L448 349.568a96 96 0 1 0-179.456 49.92l-138.24 182.784a96 96 0 1 0 48.832 41.6l137.92-182.4a95.808 95.808 0 0 0 110.208-29.824l212.928 125.888a96 96 0 1 0 172.672-51.008l109.12-230.72zM32 832h896a32 32 0 1 1 0 64H32a32 32 0 1 1 0-64z'`

**Comment by xiezhongfu** [comment]
> icon svg 的正确写法是 `'path://M921.984 255.808a96 96 0 1 0-58.88-25.088L759.04 450.752a96.192 96.192 0 0 0-93.12 27.648L448 349.568a96 96 0 1 0-179.456 49.92l-138.24 182.784a96 96 0 1 0 48.832 41.6l137.92-182.4a95.808 95.808 0 0 0 110.208-29.824l212.928 125.888a96 96 0 1 0 172.672-51.008l109.12-230.72zM32 832h896a32 32 0 1 1 0 64H32a32 32 0 1 1 0-64z'`

v4.2.1 版本开始不支持 issue 中列出的 svg 写法？：https://github.com/apache/incubator-echarts/issues/10247#issue-430972816

**Comment by Ovilia** [comment]
一直就是这样写的，参见文档 https://echarts.baidu.com/option.html#toolbox.feature.brush.icon

> 可以通过 'path://' 将图标设置为任意的矢量路径……
