### ISSUE TITLE
希望实现对轴线名称(axis.name)更精细的设置

### ISSUE THREAD

**Issue by dagundejuzi** [apache/incubator-echarts#10240]
### What problem does this feature solve?
碰上的需求是：轴线名称竖向书写，位于Y轴左侧，顶端对齐Y轴顶端。如图
![Snip20190409_1](https://user-images.githubusercontent.com/16382880/55781149-1568b780-5adc-11e9-802b-11711d6352eb.png)

现有属性不支持这样布局，使用了比较死板的方式暂时实现了相同的视觉效果。设置如下：
```
                    name: '{a|成'+'\n'+'绩'+'\n'+'分'+'\n'+'数}',  
                    nameLocation : 'end',  
                    nameGap : -80,  
                    nameTextStyle: {  
                        rich: {  
                            a: {  
                                color: '#fff',  
                                width:100,  
                                height:20,  
                                align:'left',  
                                verticalAlign: 'bottom',  
                                fontSize: 16,  
                                backgroundColor : '#ccc'  
                            }
                        }
                    },  
```
加上底色能看清楚点
![Snip20190409_2](https://user-images.githubusercontent.com/16382880/55781198-34674980-5adc-11e9-8a98-041f77452301.png)

### What does the proposed API look like?
1、当前 nameLocation 表示名称与轴线平行方向上的相对位置，希望能再添加一个属性表示名称与轴线垂直方向的相对位置。
比如：
```
  nameLocationV: 'top'    //  middle bottom    
  nameLocationH: 'right'  //   center left 
```
2、希望文字能支持竖向书写。

**Comment by dagundejuzi** [comment]
还希望能设置整个图表的圆角。用浏览器调试，直接修改canvas的border-radius属性就能有效果，所以只要把接口暴露出来就好了吧。
![Snip20190409_4](https://user-images.githubusercontent.com/16382880/55791062-49e66e80-5af0-11e9-8a65-5c76e3375bd9.png)

**Comment by Ovilia** [comment]
rich 就是用在这种场景下，更灵活地设置文字的。
想获得 canvas 的话，接口是 https://echarts.baidu.com/api.html#echartsInstance.getDom

**Comment by dagundejuzi** [comment]
getDom获取的不是canvas，是最外层的容器元素，对它设置borderRadius无效。最后使用getElementsByTagName('canvas') 得到canvas改了圆角。
我用rich算是写了个绝对位置，一旦名称长度变化了，位置就不对了。
类似的对齐方式需求应该不少，在目前位置配置下，应该还有左上、中上、右下等等8种方位，用矩阵来表示，左上是(-1,-1)，右下是(1,1)。
打算支持这样的设置吗？

**Comment by Ovilia** [comment]
获得容器后再获得 canvas 是正确的做法。
rich 可以指定对齐方式，比如右对齐是否可以满足你的需求。
因为类似的需求可能有很多种变化，我们更希望`提供机制而非策略`，所以 rich 是一种比较通用的解决方案，可能不太会考虑支持更多的配置项实现配置特定的效果。

**Comment by dagundejuzi** [comment]
唔，现在只是显示的话没什么问题，但title所占范围侵入了图表区，如果有轴线或者title覆盖区域的数据点的点击事件，是否会影响点击事件的响应？

**Comment by dagundejuzi** [comment]
另外，请问折线图下数据点的emphasis效果，能不能设置自定义的放大大小？有看到shadow、border等的设置，但是没看到设置itemSize的。

**Comment by Ovilia** [comment]
如果影响了点击事件，可以通过调整 z 实现改变绘制顺序。
散点图 emphasis 后的缩放大小么？应该暂时不支持，如果有需要的话，可以开一个 new feature 的 issue。跟这个 issue 不是很相关。
