### ISSUE TITLE
需要一份图示化的概念说明文档

### ISSUE THREAD

**Issue by dumbdonkey** [apache/incubator-echarts#10249]
### What problem does this feature solve?
目前echarts文档缺少一个概念说明性的文档，虽然从配置项中可以隐约获取到一些概念，但不够直观，对于新手来说，想要找到对应的配置项较为困难.

比如:

![WX20190410-113106](https://user-images.githubusercontent.com/16414369/55849694-31279880-5b84-11e9-820a-a0fc1576c13b.png)

我想去掉那条线,就很难找到对应的配置项...

这一点，highcharts的方式可以借鉴.

eg: https://www.highcharts.com/docs/chart-concepts/understanding-highcharts
![image](https://user-images.githubusercontent.com/16414369/55849570-b6f71400-5b83-11e9-8927-66b4939c382c.png)

谢谢

### What does the proposed API look like?
none

**Comment by Ovilia** [comment]
我们正在着手做这方面的工作，预计下半年上线。
