### ISSUE TITLE
请问官方有国际化的例子么？

### ISSUE THREAD

**Issue by mrxu0** [apache/incubator-echarts#10254]
目前有一个国际化的要求，页面中有一个下拉框能够选择多国语言，例如：默认中文显示，接着选择英文，图例，轴坐标，提示等等页面上所有出现的中文汉字都必须修改成英文。如果有麻烦给个链接，或者是靠谱的答案。谢谢

**Comment by Ovilia** [comment]
设置语言的时候调用一下 setOption，把文字相关的都替换成对应语言的。至于文字内容，需要自己写。
