### ISSUE TITLE
雷达图数据为空时显示问题

### ISSUE THREAD

**Issue by feijuncheng** [apache/incubator-echarts#10269]
### Version
4.2.1

### Steps to reproduce
在series中存在多个数据且数据中存在null，具体看下面的options

### 多个点，并且hover到点上的时候连的线或者fill的颜色直接没了

```
option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        name: {
            textStyle: {
                color: '#fff',
                backgroundColor: '#999',
                borderRadius: 3,
                padding: [3, 5]
           }
        },
        indicator: [
           { name: '销售（sales）', max: 6500},
           { name: '管理（Administration）', max: 16000},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        symbolSize: 7,
        itemStyle: {
            normal: {
                lineStyle: {
                    width: 3
                },
                borderWidth: 3
            }
        },
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            },
             {
                value : [null, 4000, null, 6000, null, 21000],
                name : '实际开销（Actual Spending）'
            }
        ]
    }]
};
```

### What is expected?
存在null时、不会多点、也不影响其他数据的点的样式，并且有正常的hover效果

### What is actually happening?
1.hover到数据节点上的时候线直接消失了
2.数据中有null的时候有时候会多个点

---
我在一个series的data中写多条数据和写多个series都能出现这个问题。在官方示例中随便改改options也能重现。
在我的项目中，使用的是4.2.1的最新版
我在源码里面看到好像有处理这个问题，但是从npm install的包里面没有，自己build了一份之后发现所有的null和NAN都归到了0点，这样处理感觉并不符合空的含义。

**Comment by yufeng04** [comment]
看了这个问题, 源码里把null处理成NAN, 再把不合理的点转换为中心点的坐标. 具体代码如下:

1. null处理成NAN
![bed2c4dbeba0c7205e10ca290](https://user-images.githubusercontent.com/22974511/56012614-dd51b680-5d1f-11e9-9bc3-8ae6ec9e9de3.png)

2. 不合理的点转换为中心点的坐标
![53e40486a5254053aade45cb0](https://user-images.githubusercontent.com/22974511/56012632-f5293a80-5d1f-11e9-8fa4-9ea1e8bd48b1.png)

**Comment by feijuncheng** [comment]
> 看了这个问题, 源码里把null处理成NAN, 再把不合理的点转换为中心点的坐标. 具体代码如下:
> 
> 1. null处理成NAN
>    ![bed2c4dbeba0c7205e10ca290](https://user-images.githubusercontent.com/22974511/56012614-dd51b680-5d1f-11e9-9bc3-8ae6ec9e9de3.png)
> 2. 不合理的点转换为中心点的坐标
>    ![53e40486a5254053aade45cb0](https://user-images.githubusercontent.com/22974511/56012632-f5293a80-5d1f-11e9-8fa4-9ea1e8bd48b1.png)

是的，昨晚我也看了master分上的源码，确实用0点位置处理了，但是好像npm发布的版本还没改。而且用0点表示空，感觉怪怪的
