### ISSUE TITLE
label for series data overlaps

### ISSUE THREAD

**Issue by KapilJethava** [apache/incubator-echarts#10260]
### Version
4.1.0-release

### Steps to reproduce
For line charts when 2 point having same x values and y values having smaller difference then those 2 points will be very close to each other. In such a cases if we display label for series data points then label for both these points gets overlapped

### What is expected?
label should be placed without overlap 
or 
should provide custom function/handler to handle position of series data 

### What is actually happening?
Labels gets overlapped

**Comment by Ovilia** [comment]
Could you provide a demo based on https://jsfiddle.net/ovilia/yh76w9Lt/ ?
