### ISSUE TITLE
line的坐标轴显示不正确

### ISSUE THREAD

**Issue by rilaohn** [apache/incubator-echarts#10261]
### Version
4.2.1

### Reproduction link
[https://echarts.baidu.com/examples/editor.html?c=line-stack](https://echarts.baidu.com/examples/editor.html?c=line-stack)

### Steps to reproduce
直接看上面的官方，最大值是820，但是显示的时候现实都1500上面去了

### What is expected?
正确的结果的，在820的位置

### What is actually happening?
错误的结果，在1700的位置

**Comment by yufeng04** [comment]
@rilaohn Hi,  you can change the value of `series[i].stack`!
Hope it helps.

**Comment by Ovilia** [comment]
This is not a bug, but an expected result of stack. @yufeng04 is correct.

**Comment by rilaohn** [comment]
解决了，不是问题，是应为使用了stack

**Comment by rilaohn** [comment]
> stack

yes not a bug，is use stack
