### ISSUE TITLE
echarts-wordcloud

### ISSUE THREAD

**Issue by wang01ping** [apache/incubator-echarts#10268]
### Version
4.0.0

### Steps to reproduce
echarts-wordcloud 的dataview只支持编辑词云的数值，但是不支持编辑词云的词汇，为什么呢？急~~

### What is expected?
希望支持编辑词云的词汇

### What is actually happening?
不支持编辑词云的词汇

**Comment by deqingli** [comment]
Please provide a demo, thanks
