### ISSUE TITLE
怎么显现K线现价线带有刻度的

### ISSUE THREAD

**Issue by zwb910615** [apache/incubator-echarts#10265]
![WechatIMG15](https://user-images.githubusercontent.com/6219605/55927557-0e5eb800-5c48-11e9-8481-1818be7d3c4f.jpeg)
### What problem does this feature solve?
怎么显现K线现价线带有刻度 如上图

### What does the proposed API look like?
无

**Comment by yufeng04** [comment]
Is this one?
![497c8586023f5bc90371e5470](https://user-images.githubusercontent.com/22974511/55928178-672f5000-5c4a-11e9-8bea-de35b22df601.png)
If not, can you mark it?

**Comment by zwb910615** [comment]
One that exists by default, then mouseover  One more

**Comment by zwb910615** [comment]
<img width="484" alt="WX20190411-125753@2x" src="https://user-images.githubusercontent.com/6219605/55931792-78338d80-5c59-11e9-9638-32b9f53b5f7c.png">

**Comment by yufeng04** [comment]
[Document link](https://www.echartsjs.com/option.html#series-candlestick.markLine.data)

![80e2e5f420c008297c16d4745](https://user-images.githubusercontent.com/22974511/55936823-fb5cdf80-5c69-11e9-86dc-46bf8f6d0858.png)

Hope it helps!

**Comment by zwb910615** [comment]
我希望样式和mouseover时的样式一样的

**Comment by yufeng04** [comment]
https://www.echartsjs.com/option.html#series-candlestick.markLine.emphasis

Hope it helps!

**Comment by zwb910615** [comment]
@yufeng04 thanks
