### ISSUE TITLE
how to show grid inside chart cell as like high chart

### ISSUE THREAD

**Issue by prathapjayaraj** [apache/incubator-echarts#10279]
I want to generate grid inside the grid cell in the echart component as like highchart. I have attached the image of the both highchart and echart components.
![echart](https://user-images.githubusercontent.com/1684672/56035083-ca9ea800-5d46-11e9-9cd2-206617efb9b3.JPG)
### Version
4.2.1

### Steps to reproduce
create any component in echart and split the x and y axis with 10 split number

### What is expected?
I want to show the grid inside the chart cell

### What is actually happening?
grid is not showing

**Comment by deqingli** [comment]
sorry, we haven't provided this feature so far.

**Comment by Ovilia** [comment]
You can use an array value like `['#ccc', '#eee', '#eee', '#eee', '#eee']` for [axisLine.lineStyle.color](http://echarts.apache.org/option.html#xAxis.axisLine.lineStyle.color).

**Comment by chenchenkaib** [comment]
you can add this code in xAxis to open  minor split line, just like
xAxis: {
 ....,
       minorSplitLine: {
        show: true,
        lineStyle: {
          color: ['#ccc', '#eee', '#eee', '#eee', '#eee'],
        },
      },
  }

**Comment by Subharthee-K** [comment]
> you can add this code in xAxis to open minor split line, just like xAxis: { ...., minorSplitLine: { show: true, lineStyle: { color: ['#ccc', '#eee', '#eee', '#eee', '#eee'], }, }, }

Perfectly worked .
