### ISSUE TITLE
markpoint可以实现如图的效果吗

### ISSUE THREAD

**Issue by zwb910615** [apache/incubator-echarts#10277]
![F7A43AC7-80EC-4AE8-8229-E30688E5CFFC](https://user-images.githubusercontent.com/6219605/56024041-c623c080-5d41-11e9-87e5-cae1836049ec.png)
### What problem does this feature solve?
markpoint可以实现如图的效果吗

### What does the proposed API look like?
无

**Comment by yufeng04** [comment]
Maybe you can do like this!

![84d2c0a6ab30d8e159f6962a8](https://user-images.githubusercontent.com/22974511/56032345-903c0780-5d54-11e9-9dfa-f5b260130343.png)

Result:
![70463dd4fc4d510befdf17453](https://user-images.githubusercontent.com/22974511/56032524-faed4300-5d54-11e9-9d8c-ef71a5bd0f19.png)

The detailed configuration can be referenced in the [documentation](https://www.echartsjs.com/option.html#series-candlestick.markPoint.data.emphasis).

**Comment by zwb910615** [comment]
@yufeng04 
<img width="364" alt="WX20190430-105515@2x" src="https://user-images.githubusercontent.com/6219605/56938875-3f3f5800-6b37-11e9-9c09-861aaeb099e8.png">

The value disappears in the emphasis state.

**Comment by yufeng04** [comment]
The normal value of label replaced by the value in  emphasis state. @zwb910615

**Comment by zwb910615** [comment]
How to keep it down in the emphasis state

**Comment by zwb910615** [comment]
@yufeng04

**Comment by yufeng04** [comment]
I don't know how to keep it down in the emphasis state. But I tried the following way:
`formatter: [
        '{a|这段文本采用样式a}',
        '{b|{c}}'
    ].join('\n')`
`{b|{c}}` will show the normal value of label, and you can set the style in `rich.b`.
Hope it helps!

**Comment by zwb910615** [comment]
thanks
