### ISSUE TITLE
Hello, I want to make some extensions to implement grouped categories, but I don't know where should I start？Any ideas?

### ISSUE THREAD

**Issue by 4096void** [apache/incubator-echarts#10276]
### Version
3.7.1

### Reproduction link
[http://blacklabel.github.io/grouped_categories/](http://blacklabel.github.io/grouped_categories/)

### Steps to reproduce
none

### What is expected?
Maybe some links.

### What is actually happening?
Nothing happened, I just want to asked for some help.

**Comment by 4096void** [comment]
Related issues: [#8557](https://github.com/apache/incubator-echarts/issues/8557) [#8540](https://github.com/apache/incubator-echarts/issues/8540)

**Comment by 4096void** [comment]
@pissang

**Comment by deqingli** [comment]
You can reference this example: http://gallery.echartsjs.com/editor.html?c=xBk7TY_hWx

**Comment by 4096void** [comment]
@deqingli though [your exmaple](https://gallery.echartsjs.com/editor.html?c=xBk7TY_hWx) 's categories doesn't match in quantities, but they still layout accordingly side by side, especially the `''` and `'直播'`.
