### ISSUE TITLE
多个网格时图例可以自动匹配每个网格的位置（legend[i].gridIndex)

### ISSUE THREAD

**Issue by junh2017** [apache/incubator-echarts#10287]
### What problem does this feature solve?
当一个dataset关联多个grid时，如果图例都在最上方，对图表的阅读不友好。比如查看要查看页面最下面的grid，要返回到最上面去查看图例对应的颜色。

### What does the proposed API look like?

        legend: [{
            data:'a',
            gridIndex: 0,
        },{
            data:'b',
            gridIndex: 1,
        },{
            data:'c',
            gridIndex: 2,
        },{
            data:'d',
            gridIndex: 3,
        }]

**Comment by Ovilia** [comment]
是配网格的位置还是图例的位置？

**Comment by junh2017** [comment]
> 是配网格的位置还是图例的位置？
不好意思，你的回复被刷下来了现在才看到回复。
我的意思是，如果配置了多个网格，显示图例的时候只会把所有图例显示在第一个网格上面，能否进行设置让图例显示在每一个网格有该图例的网格上面。
