### ISSUE TITLE
y轴数据是从后台请求过来的，Y轴网格线的颜色不同，导致有的图网格线多出一条

### ISSUE THREAD

**Issue by Deadpool957** [apache/incubator-echarts#10294]
### Version
4.1.0-rc.2

### Steps to reproduce
 yAxis: [{
                        type: 'value',
                        axisLine: {
                            show: false
                        },
                        axisTick: {
                            show: false
                        },
                        splitLine: {
                            show: true,
                            lineStyle: {
                                color: ["#fff", "#eeeeee", "#eeeeee", "#eeeeee", "#eeeeee", "#eeeeee", "#eeeeee", "#fff"]
                            }
                        }, 

                        min: 0,

                        max: Math.ceil(Math.max.apply(null, that.trendValue)),
                        splitNumber:5,
                        //设置x轴文本颜色
                        axisLabel: {
                            show: true,
                            padding: [0, 10, 0, 24],
                            textStyle: {
                                color: '#9ea6ad', //x轴文本颜色
                                fontFamily: 'Microsoft YaHei',
                                fontWeight: "normal"
                            }
                        }

                    }],

### What is expected?
y轴数据是从后台请求过来的，Y轴网格线的颜色不同，导致有的图网格线多出一条

### What is actually happening?
网格线有的多出一条，

**Comment by Ovilia** [comment]
`["#fff", "#eeeeee", "#eeeeee", "#eeeeee", "#eeeeee", "#eeeeee", "#eeeeee", "#fff"]` 表示的就是间隔的颜色，不知道你指的多出一条是什么意思？可否截图说明一下现在的样式和期望的样式？
