### ISSUE TITLE
tree type series set roam as true cause the root node disapear in sight

### ISSUE THREAD

**Issue by peter-wang-wsl** [apache/incubator-echarts#10291]
### Version
4.2.1

### Steps to reproduce
1、add roam:true to option of https://echarts.baidu.com/examples/editor.html?c=tree-basic
2、click util node
3、click math node
4、click flare

### What is expected?
display only flare node in original position

### What is actually happening?
chart disapper

**Comment by yufeng04** [comment]
According to the reproducing steps:
1. add roam:true to option
![image](https://user-images.githubusercontent.com/22974511/56128915-882dd300-5fb3-11e9-9c0a-cf1bf3214e95.png)
2. click 'util' and 'math' node
![image](https://user-images.githubusercontent.com/22974511/56128980-b6131780-5fb3-11e9-96ab-ab2f59ee367f.png)
3. click 'flare'
![image](https://user-images.githubusercontent.com/22974511/56129034-d4791300-5fb3-11e9-8383-1fe02b0ed3de.png)
The root node didn't disapear in sight.

**Comment by peter-wang-wsl** [comment]
> 
> 
> According to the reproducing steps:
> 
>     1. add roam:true to option
>        ![image](https://user-images.githubusercontent.com/22974511/56128915-882dd300-5fb3-11e9-9c0a-cf1bf3214e95.png)
> 
>     2. click 'util' and 'math' node
>        ![image](https://user-images.githubusercontent.com/22974511/56128980-b6131780-5fb3-11e9-96ab-ab2f59ee367f.png)
> 
>     3. click 'flare'
>        ![image](https://user-images.githubusercontent.com/22974511/56129034-d4791300-5fb3-11e9-8383-1fe02b0ed3de.png)
>        The root node didn't disapear in sight.

@yufeng04 you need click run to update your change, i can reproduce with chrome and fire fox

**Comment by sicraf** [comment]
作者的步骤并不能很好的重现这个bug，请参考以下步骤：
1、添加roam:true
2、拖动树
![image](https://user-images.githubusercontent.com/21838694/57204840-dd766680-6fec-11e9-826e-3884aaa6e94f.png)
![image](https://user-images.githubusercontent.com/21838694/57204854-ef580980-6fec-11e9-968e-59ffd12533dc.png)
3、点击flare
![image](https://user-images.githubusercontent.com/21838694/57204856-fda62580-6fec-11e9-88f1-88535f2efe5d.png)
整个树消失了

**Comment by yufeng04** [comment]
The reason lies in the function [_updateViewCoordSys](https://github.com/apache/incubator-echarts/blob/master/src/chart/tree/TreeView.js#L153);
When we click `flare`, the number of points and the running result of function [fromPoints](https://github.com/ecomfe/zrender/blob/master/src/core/bbox.js#L25) will changes. So the value of [defaultCenter](https://github.com/apache/incubator-echarts/blob/master/src/coord/View.js#L193) will also change. 
The the value of `viewCoordSys.position` is wrong, so the root node disappear in sight

**Comment by deqingli** [comment]
#10986

**Comment by goSunadeod** [comment]
为什么 我在官网测试没问题，自己使用就还会复现此问题。。。。困惑，版本4.3.0
