### ISSUE TITLE
Y轴的0刻度值和X轴的刻度值在一条水平线上

### ISSUE THREAD

**Issue by Deadpool957** [apache/incubator-echarts#10297]
### Version
4.1.0-rc.1

### Steps to reproduce
Y轴的0刻度值和X轴的刻度值在一条水平线上

### What is expected?
Y轴的0刻度值和X轴的刻度值在一条水平线上

### What is actually happening?
Y轴的0刻度值和X轴的刻度值在一条水平线上

**Comment by Ovilia** [comment]
https://echarts.baidu.com/option.html#xAxis.axisLine.onZero

**Comment by Deadpool957** [comment]
![QQ截图20190415153832](https://user-images.githubusercontent.com/20964110/56479448-0a545500-64e8-11e9-97dd-f6015c27eecd.png)

**Comment by Deadpool957** [comment]
onZeroAxisIndex这个并不能生效

**Comment by Ovilia** [comment]
期望的效果是怎么样的？
