### ISSUE TITLE
Legend doesn't allow series with display names containing spaces

### ISSUE THREAD

**Issue by paskaran** [apache/incubator-echarts#10298]
### Version
4.1.0-release

### Steps to reproduce
Simply create a chart containing more than 2 series data.
Each series data should have a display name which contains spaces e.g. "Line 1", "Line Two" etc.
Add series to chart.

### What is expected?
Legends should be visible for each series

### What is actually happening?
Only legends that contains no spaces in their names are visible

---
May be an internal conversion to non spaced version of the name to map them properly can fix this issue.

**Comment by Ovilia** [comment]
Please provide a demo based on https://jsfiddle.net/ovilia/yh76w9Lt/5/
