### ISSUE TITLE
4.2.1柱状图series设置label里面的formatter使用\n换行bug

### ISSUE THREAD

**Issue by LiBinRui** [apache/incubator-echarts#10302]
### Version
4.2.1

### Steps to reproduce
柱状图series设置label的formatter里面使用\n换行符，\n后面的部分会直接跑到\n前半部分下面去，形成两部分文字重叠，无法识别

### What is expected?
柱状图series设置label里面的formatter可以正常换行显示

### What is actually happening?
\n前后部分文字重叠在一起

**Comment by Ovilia** [comment]
请提供可复现的代码例子 https://gallery.echartsjs.com/editor.html

**Comment by LiBinRui** [comment]
option = {
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data:['aaa']
    },
    yAxis: {
        
    },
    series: [{
        type: 'bar',
        data: [233],
        label:{
            show:true,
            position:'top',
            color:"#000000",
            lineHeight:'40',
            formatter:'存量:\n{c}'
            
        }
    }]
};

**Comment by Ovilia** [comment]
`lineHeight:'40'` 应为 `lineHeight:40`

**Comment by LiBinRui** [comment]
谢谢
