### ISSUE TITLE
X Axis Label的interval设为0时，x轴最后一个label变成粗体

### ISSUE THREAD

**Issue by brookshi** [apache/incubator-echarts#10304]
### Version
4.2.1

### Steps to reproduce
option = {
	"xAxis": {
		"type": "category",
		"data": ["水电费撒旦", "这一行为什么会变粗"],
		"axisTick": {
			"show": false
		},
		"axisLabel": {
			"fontSize": 14,
			"fontWeight": 'normal',
			"interval": 0,
			"rotate": 0,
		}
	},
	"yAxis": {
		"type": "value",
	},
	"series": [{
		"data": [2, 3],
		"type": "bar",
		"name": "水电费",
	}, {
		"data": [3, 4],
		"type": "bar",
		"name": "大师傅",
	}]
}

### What is expected?
X轴字体正常

### What is actually happening?
X轴最后一个文本字体变粗

**Comment by Deadpool957** [comment]
这个版本的echart.common.min.js这一块有做更新吗？

**Comment by Ovilia** [comment]
@Deadpool957 目前并没有发版，发版周期大约三个月，如果比较急的话可以自己编译。

**Comment by FengHuangDong** [comment]
我用着4.6版本还是有这个问题，目前发的版本是还没有包括这个fix吗？

**Comment by toastbin** [comment]
同遇到这个问题，目前还是没有修复吗？ @Ovilia

**Comment by lhf-nife** [comment]
同遇到了这个问题，然后换了个角度解决了，贴出来供参考：
interval设置成(index, value) => {return value};
参见echarts文档，interval可以是number，也可以是function
https://echarts.apache.org/zh/option.html#xAxis.axisLabel.interval

**Comment by zhuqiandai** [comment]
> 同遇到了这个问题，然后换了个角度解决了，贴出来供参考：
> interval设置成(index, value) => {return value};
> 参见echarts文档，interval可以是number，也可以是function
> https://echarts.apache.org/zh/option.html#xAxis.axisLabel.interval
thanks
