### ISSUE TITLE
桑基图节点很小时，link展示中断

### ISSUE THREAD

**Issue by helloNLw** [apache/incubator-echarts#10308]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/gallery/editor.html?c=sankey-energy](https://www.echartsjs.com/gallery/editor.html?c=sankey-energy)

### Steps to reproduce
桑基图节点很小时，link展示中断

### What is expected?
桑基图节点很小时，link展示不要中断

### What is actually happening?
桑基图节点很小时，link展示中断

**Comment by Boxie5** [comment]
Same here, looking forward to any update.

**Comment by deqingli** [comment]
We seem to solve this problem before, and it works normally on my computer.  Do you still have this problem?

**Comment by Boxie5** [comment]
Tried several sankey graph just now,  didn't reproduce.

Not sure if it's solved or just not the right data to reproduce.

I'll post again if it happens.

thanks deqing!

**Comment by deqingli** [comment]
@helloNLw @Boxie5  I will close this issue, if your still have any problem, feel free to reopen this issue.
