### ISSUE TITLE
堆叠图一组数据为line，另一组数据为bar时，无法正常堆叠

### ISSUE THREAD

**Issue by segmafrontend** [apache/incubator-echarts#10318]
### Version
4.2.1-rc1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xmlSS3qFS8&v=1](https://gallery.echartsjs.com/editor.html?c=xmlSS3qFS8&v=1)

### Steps to reproduce
```javascript
option = {
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {},
    series: [{
        type: 'line',
        data:[220, 182, 191, 234, 290, 330, 310],
        stack: 'all'
    },
    {
        type: 'bar',
        data:[220, 182, 191, 234, 290, 330, 310],
        stack: 'all'
    }]
    // bar在line的后面就无法正常堆叠，交换顺序就正常了
    /*series: [{
        type: 'bar',
        data:[220, 182, 191, 234, 290, 330, 310],
        stack: 'all'
    },
    {
        type: 'line',
        data:[220, 182, 191, 234, 290, 330, 310],
        stack: 'all'
    }]*/
};
```
### What is expected?
正常堆叠

### What is actually happening?
线图没有正常堆叠到柱图上

**Comment by Ovilia** [comment]
不确定这算不算 bug，柱状图堆叠折线图感觉很奇怪，会给读者带来误解，有什么场景需要这样的设定吗？

**Comment by segmafrontend** [comment]
> 不确定这算不算 bug，柱状图堆叠折线图感觉很奇怪，会给读者带来误解，有什么场景需要这样的设定吗？

这个需求确实很奇怪，不过我觉得要么就不支持这样设置，如果支持就应该是正确的显示，目前来说是支持的，但是在某些特殊情况下会出错，应该就算bug了吧

**Comment by Ovilia** [comment]
目前是不支持的（不能按有些情况正好符合预期就认为是支持的），如果需要这个功能，还请解释下什么场景下需要。

**Comment by segmafrontend** [comment]
人工智能编程这是~我倒不是需要这个功能，只是偶尔发现了，以为是bug，如果不是bug就打扰了

**Comment by Ovilia** [comment]
@segmafrontend 好的，那我先关闭了。谢谢反馈！
