### ISSUE TITLE
4.2.1版本无法实现dataZoom在移动端的缩放

### ISSUE THREAD

**Issue by lvding** [apache/incubator-echarts#10312]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/gallery/editor.html?c=doc-example/scatter-dataZoom-all](https://www.echartsjs.com/gallery/editor.html?c=doc-example/scatter-dataZoom-all)

### Steps to reproduce
在手机端打开链接无法实现双指缩放,但是如果我本地从4.21切回3.85版本之后,使用同样的option双指缩放可正常使用

### What is expected?
双指缩放可以在移动端正常使用

### What is actually happening?
双指缩放无效

---
目前只在4.21发现这个问题 3.85版本并无此问题 但是3.85需要我重写option,还是希望各位大佬能修复一下

**Comment by Ovilia** [comment]
Duplicate of #10309

**Comment by wsxgs** [comment]
4.0.0 支持双指缩放，配置配置参数也基本不修改修改

**Comment by wu568431592** [comment]
@wsxgs 切换至 4.1.0 和 4.0.0 都不支持双指缩放啊、您怎么设置的

**Comment by wz71014q** [comment]
4.2.1确实不行，但我切回4.1.0就可以了

**Comment by winston1991** [comment]
同样的情况， 4.1.0和3.8.5都是支持移动端双指缩放的，最新的4.4.0不行
