### ISSUE TITLE
Set dataZoom.fillerColor is no use.

### ISSUE THREAD

**Issue by 0lddriv3r** [apache/incubator-echarts#10311]
### Version
4.2.1

### Steps to reproduce
dataZoom: {
                fillerColor: 'rgba(167,183,204,0.4)',
                borderColor: 'rgba(167,183,204,0.4)'
            }

### What is expected?
The color of selected dataZoom changes into rgba(167,183,204,0.4).

### What is actually happening?
But it's still the default grey.

**Comment by Ovilia** [comment]
I checked and the colors changed. Maybe it's just because `'rgba(167,183,204,0.4)'` looks like gray. You may use `'red'` to make it more visible.
If it doesn't work, please provide a demo based on https://jsfiddle.net/ovilia/yh76w9Lt/5/

**Comment by 0lddriv3r** [comment]
In slider dataZoom it's ok but in rect-select circumstance it seems no use:( Or i use it in wrong way?

**Comment by Ovilia** [comment]
@0lddriv3r Can you provide an image to show what do you mean?

**Comment by 0lddriv3r** [comment]
Just in the official example: [dataZoom](https://www.echartsjs.com/examples/editor.html?c=line-marker).
I change the toolbox option like that:
```
toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none',
                fillerColor: 'red'
            }
        }
    }
```
And after i click the button of dataZoom and select an area, it's also the defualt grey:
![demo](https://user-images.githubusercontent.com/19923627/56343941-c3681600-61ee-11e9-9e6c-2d76bec06c9b.png)
Did i use it wrong?

**Comment by Ovilia** [comment]
There is no `toolbox.feature.dataZoom.fillerColor`. And `dataZoom.fillerColor` is worked for this part:
<img width="735" alt="" src="https://user-images.githubusercontent.com/779050/56346699-55731d00-61f5-11e9-8a94-a67a0ae36250.png">
I didn't find an option for this.

**Comment by 0lddriv3r** [comment]
Oh got it. But how could i change the color in my Area-dataZoom demo above？

**Comment by Ovilia** [comment]
As I said, I didn't find an option for your requirement. Maybe you should try changing the source code.

**Comment by 0lddriv3r** [comment]
OK thank u so much! I'll try it
