### ISSUE TITLE
svg渲染的图标，导出的图片无法打开

### ISSUE THREAD

**Issue by leij1ang** [apache/incubator-echarts#10313]
### Version
4.2.1

### Steps to reproduce
1.`echart.init(dom,null{renderer:'svg'})`

2.通过`toolbox`的`saveAsImage`导出图片

图片无法打开

### What is expected?
图片正确打开并显示正确

### What is actually happening?
文件成功下载
mac报错：'它可能已损坏，或者可能使用了“预览”无法识别的文件格式。'

---
我尝试用getDataURL()和blob导出,拿到的结果是`data:image/svg xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg"`，我猜测，可能是由于svg相关数据没有并转化成base64引起的

**Comment by Ovilia** [comment]
使用 SVG 时候 toolbox 的正确写法类似：
```js
toolbox: {
    right: 100,
    show: true,
    feature: {
        saveAsImage: {
            show: true,
            type: 'svg'
        }
    }
},
```
之前测试过是 OK 的，目前导出的 SVG 文件会缺少一部分，形如：
```xml
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" baseProfile="full" width="600" height="300" style="user-select: none; position: absolute; left: 0px; top: 0px;"><path d="M 300 130 L 300 85 A 65 65 0 1 1 237.882 130.8597 L 280.8868 144.1107 A 20 20 0 1 0 300 130 Z" fill="
```
传入 MouseEvent 的数据是正常的，怀疑是浏览器的 bug。

至于导出 png 格式的图片，目前还没有支持。

**Comment by leij1ang** [comment]
已明确
提个建议，是否能svg转canvas，之后canvas转png/jepg呢，毕竟导出图片是某些场景的刚需

**Comment by ISBN9527** [comment]
想用SVG去渲染，但是奈何下载图片无法使用

**Comment by ISBN9527** [comment]
按照上面你的提示报错

![image](https://user-images.githubusercontent.com/30942709/70122949-98aecd00-16ac-11ea-8bcd-57b56188a46b.png)

**Comment by ISBN9527** [comment]
@Ovilia

**Comment by vasttian** [comment]
> 按照上面你的提示报错
> 
> ![image](https://user-images.githubusercontent.com/30942709/70122949-98aecd00-16ac-11ea-8bcd-57b56188a46b.png)

Chrome 下载有问题，用 Safari  可以正常下载

**Comment by Ovilia** [comment]
@ISBN9527 `console.log(chart.getOption())` 贴一下看看？
