### ISSUE TITLE
关于Echarts中地理坐标上点的标签显示问题

### ISSUE THREAD

**Issue by AlexSJJ** [apache/incubator-echarts#10328]
为什么在点标签上的内容是显示经纬度而不是该点数值的大小呢，有什么办法可以解决将label内容显示为数值大小吗？

**Comment by weecoding123** [comment]
`
可以使用如下方式设置
tooltip: {
            formatter:function(params){
                        //自定义模版，获取value的值，默认使用的是经纬度
                        return params.seriesName + '<br/>' + params.name + ":" + params.value[2]
                   }
        }
`
