### ISSUE TITLE
希望markLine中lable的formatter选项可以支持自定义html

### ISSUE THREAD

**Issue by Jarvis2018** [apache/incubator-echarts#10321]
### What problem does this feature solve?
希望markLine中lable的formatter选项可以支持自定义html，当前只能自定以文字但不能编写出自己想要的样式

### What does the proposed API look like?
`label: {
            formatter: '<p style="color: red; padding:24px;">markLine</p>
      }`

**Comment by Ovilia** [comment]
markLine 是 canvas 绘制的，而不是 DOM 节点，所以这个功能一般来说没法支持。

**Comment by Jarvis2018** [comment]
> markLine是canvas绘制的，而不是DOM节点，所以这个功能一般来说没法支持。

之前通过 symbol 引用自定义的svg来实现的，但是在控制symbol的位置的时候不是很方便。那能否可以有类似的选项可以控制？

**Comment by Ovilia** [comment]
即使是使用 SVG，也是不建议自己操作 DOM 节点的，因为这会使得 ECharts 的行为变得不可控。
目前看起来并没有更好的解决方案。
