### ISSUE TITLE
极坐标下的柱状图，控制内半径

### ISSUE THREAD

**Issue by cn-xufei** [apache/incubator-echarts#10336]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xRzpEiB3Hs&v=2](https://gallery.echartsjs.com/editor.html?c=xRzpEiB3Hs&v=2)

### Steps to reproduce
polar.radius如果是个数组的话，图表无法渲染，我是想用数组控制内半径的大小

### What is expected?
可以正常的控制内半径，如下：
![image](https://user-images.githubusercontent.com/14144811/56488277-8cf10a80-6510-11e9-84e2-ac51b98af14a.png)

### What is actually happening?
图表无法渲染

**Comment by 100pah** [comment]
Before the inside radius supported on polar, we have a workaround:
<https://gallery.echartsjs.com/editor.html?c=xJzZu1Q1ri&v=2>
