### ISSUE TITLE
[feature] 请问曲线图的markArea是否可以只在曲线图以下展示？

### ISSUE THREAD

**Issue by Meriky** [apache/incubator-echarts#10337]
### What problem does this feature solve?
* 目前曲线图上的MarkArea是上下联通的，根据我对MarkArea配置项的了解，没有办法让它实现 “markArea的阴影区只在曲线图以下展示” 的功能
* 需要一种方案可以将markArea以及line图的areaStyle关联一下
* 或者是说目前有什么方案可以迂回地做到这一点

图片示例：
![image](https://user-images.githubusercontent.com/5638016/56488885-6b911e00-6512-11e9-8172-5424ee0183b0.png)

### What does the proposed API look like?
在markArea配置项添加一个只在曲线图生效的参数，用来实现上述功能，布尔值应该就可以

**Comment by 100pah** [comment]
有一个比较繁琐的迂回方法，新加一个 x 轴在顶上，新加另一个 line series 在这个 x 轴上，设置上 `areaStyle: {color: '#fff'}` 从而能遮盖住上半部分的 markArea。

**Comment by Meriky** [comment]
> 有一个比较繁琐的迂回方法，新加一个 x 轴在顶上，新加另一个 line series 在这个 x 轴上，设置上 `areaStyle: {color: '#fff'}` 从而能遮盖住上半部分的 markArea。

好办法，但是有一个问题就是markArea阴影的渐变就不好搞了，linearGradient起点不是曲线上

**Comment by paradox010** [comment]
新建一个一样的series,设定其visualMap。类似
visualMap: {
        show: true,
        dimension: 0,
        pieces: [{
            gt: 6,
            lte: 8,
            color: '#fff'
        }],
    },
其中可以设置颜色，但不支持渐变色。
