### ISSUE TITLE
百万级数据支持dataZoom的热力图

### ISSUE THREAD

**Issue by nkcs2016** [apache/incubator-echarts#10340]
### What problem does this feature solve?
热力图目前渲染太慢

### What does the proposed API look like?
希望提供一个类似line-samping的功能，或者直接筛掉不要的。不知道是不是计算没有优化的原因，反正觉得慢

**Comment by Ovilia** [comment]
line-samping 是指？
和 dataZoom 的关系是什么？是说着百万级的数据很多是不在绘制区域内的吗？

**Comment by zhaobinhong** [comment]
700万的渲染数据如何渲染呢？

**Comment by Ovilia** [comment]
@zhaobinhong 要看是什么类型的图表了，有具体问题可以再开一个新的 issue

**Comment by zhaobinhong** [comment]
@Ovilia [https://github.com/ElemeFE/v-charts/issues/746#issue-451756778](new issue)

**Comment by zhaobinhong** [comment]
@Ovilia [new issue](https://github.com/ElemeFE/v-charts/issues/746#issue-451756778)
