### ISSUE TITLE
echarts tooltip

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [apache/incubator-echarts#10352]
### Version
4.2.1

### Steps to reproduce
一个折线图里大概有二三十条折线。

div高度300
tooltp高度大小超出div大小导致限制不全
设置  extraCssText: 'z-index: 1000'  和  父div  overflow: visible  均无效

### What is expected?
期望  tooltip 显示完整

### What is actually happening?
期望  tooltip 显示不完整

**Comment by SamGenTLEManKaka** [comment]
![image](https://user-images.githubusercontent.com/24671601/56642095-4e428800-66a9-11e9-92cf-b986ec8ac08c.png)

**Comment by SamGenTLEManKaka** [comment]
![image](https://user-images.githubusercontent.com/24671601/56642217-85b13480-66a9-11e9-90e0-c7f70ff76fab.png)

父div  设置了  overflow: visible

![image](https://user-images.githubusercontent.com/24671601/56642517-2bfd3a00-66aa-11e9-8533-35cbd51baee1.png)

tooltip设置了 z-index

**Comment by Ovilia** [comment]
1. 确保 [renderMode](https://www.echartsjs.com/option.html#tooltip.renderMode) 是默认值 `'html'`
2. 将 [confine](https://www.echartsjs.com/option.html#tooltip.confine) 设为 true
