### ISSUE TITLE
SPDX style licenses

### ISSUE THREAD

**Issue by el** [apache/incubator-echarts#10361]
### Version
4.2.1

### Steps to reproduce
Look at the license information, see it is `Apache` instead of `Apache-2.0` or `Apache-1.0`

### What is expected?
License to be from this list:
https://spdx.org/licenses/

### What is actually happening?
It is not

**Comment by Ovilia** [comment]
Hi. Why is it `Apache`? In https://spdx.org/licenses/ , I see only `Apache-2.0` in Identifier.
