### ISSUE TITLE
echarts中国地图省市文字偏移不居中，更改china.js不生效

### ISSUE THREAD

**Issue by wangxianping321** [apache/incubator-echarts#10362]
![image](https://user-images.githubusercontent.com/32926615/56727749-e01ec380-6783-11e9-86ff-ea2b54105596.png)
例如青岛

**Comment by Wang-Kai** [comment]
这个问题解决了吗？

**Comment by wangxianping321** [comment]
已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] echarts中国地图省市文字偏移不居中，更改china.js不生效 (#10362)





 
这个问题解决了吗？

**Comment by Wang-Kai** [comment]
@wangxianping321

**Comment by wangxianping321** [comment]
更改地图js源码，可以在网上搜一下，或者CSDN博客搜索素味平生，私信




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] echarts中国地图省市文字偏移不居中，更改china.js不生效 (#10362)





 
@wangxianping321 怎么解决的？求方案

**Comment by Wang-Kai** [comment]
@wangxianping321 你可以把你获得的贴出来吗？以便帮助到更多人
