### ISSUE TITLE
建议增加resize选项

### ISSUE THREAD

**Issue by fog3211** [apache/incubator-echarts#10364]
### What problem does this feature solve?
建议option中增加一个参数，可以设置图表的大小是否随父元素的大小变化而变化。  
目前的版本中即使设置了图表的宽度为父元素的100%，在父元素的大小改变时，图表的大小仍不会发生变化。  
如：  
[https://codesandbox.io/s/8x1lk9ll9l](https://codesandbox.io/s/8x1lk9ll9l)    
1.当屏幕的分辨率小于1300px时，打开菜单栏会导致图表超出边界（无论怎么改变屏幕大小canvas的宽度始终不会改变）  
2.当用户从较小窗口切换到全屏时，会出现空白区域。  

### What does the proposed API look like?
建议option中增加一个responsive参数，参数为true时，会监视canvas的父元素的大小，如果发生变化，则重新设置canvas的大小，参数为false时，canvas大小不变.

**Comment by cuijian-dexter** [comment]
https://echarts.baidu.com/api.html#echartsInstance.resize

**Comment by Ovilia** [comment]
在 HTML 中，是没法监听某一个 DIV 是否变化了大小，只能监听全局的 onresize 事件，所以还是用户自己处理事件更合适，然后再手动调用 chart.resize()
