### ISSUE TITLE
堆叠柱图，设置yAxis的最小值导致堆叠错误

### ISSUE THREAD

**Issue by segmafrontend** [apache/incubator-echarts#10377]
### Version
4.2.1-rc1

### Steps to reproduce
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value',
        min: 4
    },
    series: [{
        data: [12],
        type: 'bar',
        stack: 'all'
    },
    {
        data: [5],
        type: 'bar',
        stack: 'all',
    },]
};
![image](https://user-images.githubusercontent.com/43062793/56879034-8707a600-6a89-11e9-8ae9-84e933b76c7d.png)

PS：echarts-issue-helper无法保存了，获取版本的接口报错403了
![image](https://user-images.githubusercontent.com/43062793/56879022-7a834d80-6a89-11e9-9ad8-624cf6bcb66f.png)

### What is expected?
堆叠柱图，设置yAxis的最小值不影响堆叠

### What is actually happening?
堆叠柱图，设置yAxis的最小值导致堆叠错误

**Comment by meatRoll** [comment]
什么时候解决这个问题啊？4.1.0版本及以前都没有这个问题的

**Comment by susiwen8** [comment]
@meatRoll It have been fixed in master branch, you can pull the latest version an try it on. Sorry for keeping you waiting
