### ISSUE TITLE
使用百度地图之后，解决toolbox下载为图片中没有百度地图？

### ISSUE THREAD

**Issue by gao384688949** [apache/incubator-echarts#10378]
### What problem does this feature solve?
可视化视图之后，可能会导出图片分享。
使用百度地图之后，toolbox下载为图片背景中没有百度地图，而是只有其余部分。

### What does the proposed API look like?
改进

**Comment by gao384688949** [comment]
![image](https://user-images.githubusercontent.com/11517544/56881006-87a43a80-6a91-11e9-9c91-b7e85681f258.png)

**Comment by deyihu** [comment]
@gao384688949  
出现这个问题是使用bmap扩展，echarts容器以div的方式插入到百度地图的容器中，整个百度地图的渲染没有被echarts托管，百度地图瓦片的渲染完全有bmap来完成的，所以导出图片的时候，echarts只能导出自己自己画布上的内容，而且任何的第三方地图引擎（非 geo组件）和echarts结合的都会存在这个问题。


想要将百度地图和echarts的绘制结果一并导出图片你需要将百度地图的瓦片渲染结果和echarts的渲染结果合并绘制到一个新的的画布上，

我做的一个例子 https://gallery.echartsjs.com/editor.html?c=xKdf51HpRE&v=1

目前百度地图关于瓦片的渲染使用的是dom(img标签），合并的时候有点烦，需要将瓦片的图片集一个一个的合并起来，如果你使用其他的地图组件（瓦片渲染是使用画布的（canvas）），整个合并将很简单，只需要将地图的画布和echarts的画布合并起来即可，例如openlayers,maptalks,mapbox-gl等，关于这些地图引擎和echarts的结合，社区应该都能找到相应的插件

**Comment by susiwen8** [comment]
@deyihu 不知道你在写什么，但是觉得好厉害！6666

**Comment by Ovilia** [comment]
确实好厉害！

**Comment by deyihu** [comment]
@gao384688949 
这个不能算是echarts 的feature,如果要适配的话，echarts内部 toolbox 必须要对bmap做适配了，会加大echarts和bmap的耦合度，而且类似bmap这样的组件太多了，根本适配不过来的

**Comment by gao384688949** [comment]
@deyihu 嗯，这个只能算是解决了单张图的导出，如果是多个图的导出还是不好处理。感谢大神！

**Comment by ArthurLoveGY** [comment]
> @gao384688949
> 出现这个问题是使用bmap扩展，echarts容器以div的方式插入到百度地图的容器中，整个百度地图的渲染没有被echarts托管，百度地图瓦片的渲染完全有bmap来完成的，所以导出图片的时候，echarts只能导出自己自己画布上的内容，**而且任何的第三方地图引擎（非 geo组件）和echarts结合的都会存在这个问题**。
> 
> 想要将百度地图和echarts的绘制结果一并导出图片你需要将百度地图的瓦片渲染结果和echarts的渲染结果合并绘制到一个新的的画布上，
> 
> 我做的一个例子 https://gallery.echartsjs.com/editor.html?c=xKdf51HpRE&v=1
> 
> 目前百度地图关于瓦片的渲染使用的是dom(img标签），合并的时候有点烦，需要将瓦片的图片集一个一个的合并起来，如果你使用其他的地图组件（瓦片渲染是使用画布的（canvas）），整个合并将很简单，只需要将地图的画布和echarts的画布合并起来即可，例如openlayers,maptalks,mapbox-gl等，关于这些地图引擎和echarts的结合，社区应该都能找到相应的插件

我在拖拽或者缩放以后再使用截图，会出现截图不全的情况，请问怎么处理这样的情况呢
![1570872286987](https://user-images.githubusercontent.com/19769776/66698955-44731680-ed15-11e9-8827-36b9f858c9b9.png)

**Comment by ArthurLoveGY** [comment]
@deyihu  我在拖拽后或者缩放后截图还是会有截图不全的情况，您有没有什么解决思路
