### ISSUE TITLE
柱状图实例调用dispatchAction显示tooltip，提示框的层级在柱子下面

### ISSUE THREAD

**Issue by renbuzhudek** [apache/incubator-echarts#10373]
### Version
4.2.1

### Steps to reproduce
实例化柱形图后调用：
dispatchAction({
type: 'showTip',
})

### What is expected?
提示框的层级应该在柱子上面

### What is actually happening?
提示框的层级在柱子下面，实际上加了setTimout延迟1000毫秒，刷新几次页面偶尔也会出现这种情况，

---
需要刷新页面，这个情况并不是一定会出现，刷新几次，随机会出现几次，事实上我加了延迟1000毫秒执行，依然会出现这个问题

**Comment by renbuzhudek** [comment]
对了 需要模拟移动端

**Comment by 100pah** [comment]
是否可以提供图片、可运行的 option、运行环境。
