### ISSUE TITLE
click angleAxis.category can not be triggered 

### ISSUE THREAD

**Issue by peter-wang-wsl** [apache/incubator-echarts#10382]
### Version
4.2.1

### Steps to reproduce
1、add myChart.on('click','angleAxis.category',function (params) {alert(1)}); to end of https://gallery.echartsjs.com/editor.html?c=xINzhTRaHL&v=1

### What is expected?
alert 1 when click 周一

### What is actually happening?
nothing alert

**Comment by Ovilia** [comment]
I tried with current js files under `dist` (which is the same with `npm i`) and it has this bug. But it cannot reproduce with the build result of the latest source file in the master branch. So the conclusion is, this problem has been fixed but not released.
If you want to build by yourself, clone the project and:
```
npm i
node build/build.js --release
```
And use the result of `dist`.
