### ISSUE TITLE
使用dataSet时，饼图和漏斗的label=>formatter中设置{c}格式时输出了{b},{c}格式数据

### ISSUE THREAD

**Issue by somsne** [apache/incubator-echarts#10383]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xJHaaX8dAS&v=1](https://gallery.echartsjs.com/editor.html?c=xJHaaX8dAS&v=1)

### Steps to reproduce
使用dataset时在饼图和漏斗的label=>formatter中设置{c}即可复现
或者直接查看复现链接

### What is expected?
{c}

### What is actually happening?
{b},{c}

**Comment by yufeng04** [comment]
#10380 
The reason lies [here](https://github.com/apache/incubator-echarts/blob/master/src/data/helper/dataProvider.js#L232), but I haven't found the right way to fix it yet.

**Comment by susiwen8** [comment]
@yufeng04 We can use the way from https://github.com/apache/incubator-echarts/blob/master/src/chart/pie/PieSeries.js#L80

**Comment by somsne** [comment]
@susiwen8 I can fix it by your way.
Thanks for your help!

**Comment by susiwen8** [comment]
@somsne Happy to help.

**Comment by susiwen8** [comment]
@somonus I just find a bug in my code, you hover on chart, the value won't display, I just update my PR, please try the new one.
