### ISSUE TITLE
3.6.2版本series-bar.markLine 多series设置线颜色无效

### ISSUE THREAD

**Issue by ZJongs** [apache/incubator-echarts#10385]
### Version
3.6.2

### Steps to reproduce

`markLine:  {
                symbol : 'none',
                itemStyle : {
                    normal : {
                        label : {
                            show:true,
                            formatter: '{b}'
                        }
                    }
                },
                lineStyle: {
                    normal: {
                        type: 'solid'
                    }
                },
                data:[{yAxis:100,name:'自定义',lineStyle:{color:'red'},{yAxis:200,name:'自定义',lineStyle:{color:'blue'}}]
            };`

3.6.2版本设置以上颜色时，线颜色不起作用。
4.0.7版本设置时可以正常使用
没有在更新版本记录中看到对这个的记录。

### What is expected?
从3.6.2中找到解决办法

### What is actually happening?
从3.6.2中找到解决办法

**Comment by Ovilia** [comment]
请使用最新版本，或者没有问题的版本。
