### ISSUE TITLE
堆叠折线图标记最大值错误

### ISSUE THREAD

**Issue by arex0** [apache/incubator-echarts#10398]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xPj_cVCT5Ls&v=1](https://gallery.echartsjs.com/editor.html?c=xPj_cVCT5Ls&v=1)

### Steps to reproduce
https://gallery.echartsjs.com/editor.html?c=xPj_cVCT5Ls&v=1

### What is expected?
正确标注最大值

标注堆叠最大值

### What is actually happening?
标注错误

无法标记堆叠最大值

---
https://gallery.echartsjs.com/editor.html?c=xPj_cVCT5Ls&v=1

**Comment by deqingli** [comment]
Update this feature of `markPoint`, after the stack implementation mechanism changed

**Comment by susiwen8** [comment]
Fix in #11965
