### ISSUE TITLE
树图的每个项目显示不同的图片

### ISSUE THREAD

**Issue by cos800** [apache/incubator-echarts#10399]
![image](https://user-images.githubusercontent.com/635184/57210103-fe02e880-700d-11e9-98dd-e618d93c50c4.png)

这样子的一个图表，我想把圆圈改成用户头像，每个项目的头像是不同的，有没有办法实现。

**Comment by cos800** [comment]
Echarts里的树图，能不能把每个项目图标改成不同的图片？

我看了echarts的文档，
https://www.echartsjs.com/option.html#series-tree.symbol
有说：

> 如果需要每个数据的图形不一样，可以设置为如下格式的回调函数：
> `(value: Array|number, params: Object) => number|Array`
> 其中第一个参数 value 为 data 中的数据值。第二个参数params 是其它的数据项参数。

所以我把 `symbol: 'emptyCircle'` 改成：
```
symbol: function (value, params) {
    console.log('symbol callback:', value, params);
    return 'emptyCircle';
},
```
按道理 只要有执行这个回调函数，console就会有输出。
但是并没有，却输出一个错误：

![image](https://user-images.githubusercontent.com/635184/57211429-d4988b80-7012-11e9-8deb-6f99266b1ec3.png)

这是echarts的bug吗？
还是我写法有什么问题？

**Comment by SummerYY16** [comment]
mark
