### ISSUE TITLE
如何使横坐标线对齐到最小值

### ISSUE THREAD

**Issue by qqfei1858** [apache/incubator-echarts#10390]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xU1WuKR3EW&v=1](https://gallery.echartsjs.com/editor.html?c=xU1WuKR3EW&v=1)

### Steps to reproduce
直接设置Y轴最小值为负值,希望横坐标轴线自动对齐到最小值

### What is expected?
直接设置Y轴最小值为负值,希望横坐标轴线自动对齐到最小值

### What is actually happening?
暂无

**Comment by Ovilia** [comment]
https://www.echartsjs.com/option.html#yAxis.min
可以是一个 function，返回最小值即可
```js
min: function(value) {
    return value.min;
}
```

**Comment by qqfei1858** [comment]
我说说横轴轴线,不是Y轴值,Y轴0对应的轴线,自动对齐到最小值!
@Ovilia 
![QQ图片20190505154418](https://user-images.githubusercontent.com/26538473/57190435-abadc300-6f4c-11e9-8278-e22f0f0faa45.png)

**Comment by Ovilia** [comment]
https://echarts.baidu.com/option.html#xAxis.axisLine.onZero 设为 false

**Comment by banli17** [comment]
@Ovilia  onZero false 现在不生效了
