### ISSUE TITLE
如何使横坐标线对齐到最小值

### ISSUE THREAD

**Issue by qqfei1858** [apache/incubator-echarts#10392]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xU1WuKR3EW&v=1](https://gallery.echartsjs.com/editor.html?c=xU1WuKR3EW&v=1)

### Steps to reproduce
1.没有得到结果!所以重新开个!
2.对于上一个回复,我希望的是将横坐标轴线,随着Y轴轴线自动适应

### What is expected?
直接设置Y轴最小值为负值,希望横坐标轴线自动对齐到最小值

### What is actually happening?
直接设置Y轴最小值为负值,希望横坐标轴线自动对齐到最小值

**Comment by qqfei1858** [comment]
![QQ图片20190505185135](https://user-images.githubusercontent.com/26538473/57192796-e290d280-6f66-11e9-807b-d0e7dfab6f6d.png)

**Comment by Ovilia** [comment]
Duplicate of #10390
