### ISSUE TITLE
饼图系列中相同的数据显示为不同的百分比

### ISSUE THREAD

**Issue by jiangchaoting** [apache/incubator-echarts#10400]
### Version
4.2.1

### Reproduction link
[https://echarts.baidu.com/examples/editor.html?c=pie-simple](https://echarts.baidu.com/examples/editor.html?c=pie-simple)

### Steps to reproduce
https://echarts.baidu.com/examples/editor.html?c=pie-simple，在此地址修改配置属性   {value:1, name:'直接访问'},
                {value:1, name:'邮件营销'},
                {value:1, name:'联盟广告'},
                {value:1, name:'视频广告'},
                {value:2, name:'搜索引擎'}，我们会发现其中某一个1鼠标放上去会显示16.66%，而其它3 个是16.67%

### What is expected?
应该所有1的模块都保存一样的百分比

### What is actually happening?
所有1的模块不是一样的百分比值

---
https://echarts.baidu.com/echarts2/doc/example/pie1.html ，这个地方修改为  {value:1, name:'直接访问'},
                {value:1, name:'邮件营销'},
                {value:1, name:'联盟广告'},
                {value:1, name:'视频广告'},
                {value:2, name:'搜索引擎'} ，饼图显示的所有的1%的都是16.67%

**Comment by susiwen8** [comment]
我不觉得这是bug，为了相加等于100%有一个是要不同。

**Comment by jiangchaoting** [comment]
> 我不觉得这是bug，为了相加等于100%有一个是要不同。

https://echarts.baidu.com/echarts2/doc/example/pie1.html  这个就是显示很正常。那他不是为了相加等于1

**Comment by jiangchaoting** [comment]
为什么以前是不为保证相加为1，现在的版本是为了保证相加为一，理由？

**Comment by jiangchaoting** [comment]
都是四舍五入原则，原则因为另外个原则而改变以前的原则，用户看着都问，为什么这个百分比不一样？ 用户的角度怎么考虑？

**Comment by susiwen8** [comment]
不是我改的代码，回答不上来。

**Comment by Ovilia** [comment]
这个是有意的设计而不是 bug，主要目的就是让所有的总和是 100%，具体的算法参见[我的博客](http://zhangwenli.com/blog/2017/06/13/pie-percentage/)。
对于「为什么相同的数字显示不同的百分比」，我的回应是，相比这一点，总和不是 100% 更不舒适。
如果不喜欢这样的设定，可以自行用 formatter 修改显示内容。

**Comment by jiangchaoting** [comment]
> 这个是有意的设计而不是 bug，主要目的就是让所有的总和是 100%，具体的算法参见[我的博客](http://zhangwenli.com/blog/2017/06/13/pie-percentage/)。
> 对于「为什么相同的数字显示不同的百分比」，我的回应是，相比这一点，总和不是 100% 更不舒适。
> 如果不喜欢这样的设定，可以自行用 formatter 修改显示内容。

这是相对于以前echart2的修改，是不是应该有某处说明，或者强调一下，让开发者知道此处的会出现这样的情况

**Comment by jiangchaoting** [comment]
![1](https://user-images.githubusercontent.com/10701144/57265992-9f407c00-70ac-11e9-8d8b-93346f381c47.png)
http://zhangwenli.com/blog/2017/06/13/pie-percentage/  ，认识大神真好，不过容我提一个文字BUG，O(∩_∩)O哈哈~

**Comment by Ovilia** [comment]
这种非常细微的差别我们一般不会给出差别，因为修复的时候是认为我们修复了一个 bug，所以不太可能在文档里说这些。
谢谢指正哈~

**Comment by ddx2019** [comment]
formatter一下，保留一位小数能解决echarts饼图的 相同数字不同百分比的情况，目前采取的是这种解决方式；如有更好的方法，请大佬告知。参数：option = {
  title: {
    text: "某站点用户访问来源",
    subtext: "纯属虚构",
    left: "center"
  },
  tooltip: {
    trigger: "item",
    // formatter:"{a} <br/>{b} : {c} ({d}%)"
    formatter: function(data) {
      const { name, value } = data.data;
      const { seriesName, percent } = data;
      return `${seriesName}<br/>${name}: ${value} (${percent.toFixed(1)}%)`;
    }
  },
  legend: {
    orient: "vertical",
    left: "left"
  },
  series: [
    {
      name: "访问来源",
      type: "pie",
      radius: "50%",
      data: [
        { value: 1048, name: "搜索引擎" },
        { value: 735, name: "直接访问" },
        { value: 580, name: "邮件营销" },
        { value: 300, name: "联盟广告" },
        { value: 300, name: "视频广告" }
      ],
      emphasis: {
        itemStyle: {
          shadowBlur: 10,
          shadowOffsetX: 0,
          shadowColor: "rgba(0, 0, 0, 0.5)"
        }
      }
    }
  ]
};

https://echarts.apache.org/v4/examples/zh/editor.html?c=pie-simple  旧版本echarts (v4)
