### ISSUE TITLE
地图背景设置纹理无法正常显示

### ISSUE THREAD

**Issue by chengang0621** [apache/incubator-echarts#10405]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x6G-oE-Vas&comment=0](https://gallery.echartsjs.com/editor.html?c=x6G-oE-Vas&comment=0)

### Steps to reproduce
请查看 https://gallery.echartsjs.com/editor.html?c=x6G-oE-Vas&comment=0

### What is expected?
背景纹理能正常显示，比如如下效果
https://www.echartsjs.com/gallery/editor.html?c=pie-pattern

### What is actually happening?
纹理被模糊拉伸了

---
另外设置的纹理不能马上出现，需要鼠标移入

**Comment by pissang** [comment]
Will be fixed in 4.4.0
