### ISSUE TITLE
4.2.1 版本的 geo 图表在移动端无法进行缩放

### ISSUE THREAD

**Issue by rni-l** [apache/incubator-echarts#10401]
### Version
4.2.1

### Reproduction link
[https://codepen.io/rnil/pen/WBNPJB?editors=1010](https://codepen.io/rnil/pen/WBNPJB?editors=1010)

### Steps to reproduce
用手机（无论是 android 还是 ios）打开链接后，地图是无法缩放的

### What is expected?
可以缩放

### What is actually happening?
不能缩放

---
我改成用 v3.8.0 版本的话，就可以进行缩放

**Comment by zhilanlv** [comment]
想麻烦问一下，你这边echarts的geo移动端双指缩放的问题解决了么

**Comment by rni-l** [comment]
> 想麻烦问一下，你这边echarts的geo移动端双指缩放的问题解决了么

没有，可以选择使用 3.x 版本，那版本是可以缩放

**Comment by YueminHu** [comment]
`^4.6.0` 这个版本可以了

**Comment by zhilanlv** [comment]
> `^4.6.0` 这个版本可以了

好的

**Comment by zhoufanglu** [comment]
"echarts": "^5.0.1",
这个版本好像在移动端无法缩放
