### ISSUE TITLE
rich.backgroundColor 设置img是gif动图，但是渲染上去是静态的。

### ISSUE THREAD

**Issue by ouzhenlin** [apache/incubator-echarts#10417]
### Version
4.2.0-rc.2

### Steps to reproduce
rich.backgroundColor.image 设置动态的gif图片。

### What is expected?
gif是动态图片，或者有其他的方式设置标题闪烁的效果。一闪一闪。

### What is actually happening?
gif是静态的图片

![QQ截图20190508140432](https://user-images.githubusercontent.com/25323119/57354462-186bcc00-719e-11e9-944a-d01460847e89.png)
![QQ截图20190508140513](https://user-images.githubusercontent.com/25323119/57354463-19046280-719e-11e9-9f88-66ebf3b9b4da.png)

**Comment by Ovilia** [comment]
不支持 gif 图

**Comment by ouzhenlin** [comment]
> 
> 
> 不支持 gif 图

那有没有其他的思路，让那个标题能够有一个闪烁的动画呢》？

**Comment by Ovilia** [comment]
自己通过 setInterval 调用 setOption 改变图片内容
