### ISSUE TITLE
更新数据时图表中会多出一条横线

### ISSUE THREAD

**Issue by jinhuang3115** [apache/incubator-echarts#10420]
### Version
4.2.1

### Steps to reproduce
1. 初始化echarts
2. 轮询更新数据 使用setOption方法

### What is expected?
图表可以正常显示

### What is actually happening?
图表中多了一条横线。 偶现

![echarts1](https://user-images.githubusercontent.com/3615077/57369353-e4090780-71bf-11e9-81d5-375a5b485c80.png)
正常

![echarts](https://user-images.githubusercontent.com/3615077/57369331-d6ec1880-71bf-11e9-9924-896041382fa6.png)
非正常

---
不是必现，更新几次数据偶尔就会多出一条横线

**Comment by Ovilia** [comment]
请提供可复现的代码：https://gallery.echartsjs.com/editor.html
