### ISSUE TITLE
使用dataset传入数据，以及x轴类型为time时，横轴不能正确显示时间

### ISSUE THREAD

**Issue by yimelia** [apache/incubator-echarts#10423]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xzwYtSuCNn&v=1](https://gallery.echartsjs.com/editor.html?c=xzwYtSuCNn&v=1)

### Steps to reproduce
给定2个dataset，分别包含了若干个带有time字段和value字段的object，希望能够将他们按照time字段为X轴进行排序和显示

### What is expected?
X轴能够按照大小顺序，显示出每个数据点的time字段内容（如果两个dataset的time字段不完全相符的话，希望能够自动合并，按时间大小排序）

### What is actually happening?
X轴的头和尾总共只显示了一个时间戳信息

**Comment by Ovilia** [comment]
这个 `time` 是秒的，time 轴接受的是毫秒的，类似 `new Date().getTime()` 可以看到是你数据的 1000 多倍。
可以通过自定义 formatter 实现：
```js
axisLabel: {
    formatter: function (v) {
        var date = new Date(v * 1000);
        return date.getFullYear() + '-' + (date.getMonth() + 1)
            + '-' + date.getDate() + ' '
            + date.getHours() + ':' + date.getMinutes()
            + ':' + date.getSeconds();
    }
}
```
已更新到 https://gallery.echartsjs.com/editor.html?c=xzwYtSuCNn&v=3

**Comment by yimelia** [comment]
原来如此。。。辛苦 @Ovilia 回复和帮忙修改，非常感谢！
