### ISSUE TITLE
设置legend不起作用

### ISSUE THREAD

**Issue by cuibenjun0809** [apache/incubator-echarts#10427]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=custom-profile](https://www.echartsjs.com/examples/editor.html?c=custom-profile)

### Steps to reproduce
官方自定义实例中，option中我加入legend不起作用。

### What is expected?
出现图例

### What is actually happening?
不出现图例

**Comment by Ovilia** [comment]
能出现图例的，你需要在系列里增加 `name: 'aaa'` 然后在 `legend` 的 `data: ['aaa']`

**Comment by cuibenjun0809** [comment]
非常感谢

**Comment by cuibenjun0809** [comment]
你好，图例的颜色该怎么修改？

**Comment by shiyingyan** [comment]
@cuibenjun0809   @Ovilia
