### ISSUE TITLE
sankey图 focusNodeAdjacency 为true情况下，emphasis style 无效

### ISSUE THREAD

**Issue by sliverna** [apache/incubator-echarts#10424]
### Version
4.2.1

### Steps to reproduce
myChart.showLoading();
$.get('data/asset/data/energy.json', function (data) {
    myChart.hideLoading();
    myChart.setOption(option = {
        title: {
            text: 'Sankey Diagram'
        },
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'sankey',
                data: data.nodes,
                links: data.links,
                focusNodeAdjacency: true,
                itemStyle: {
                    normal: {
                        borderWidth: 1,
                        borderColor: '#aaa'
                    }
                },
                lineStyle: {
                    normal: {
                        color: 'source',
                        curveness: 0.5
                    }
                },
                emphasis:{
                    itemStyle:{
                        color:"#f00"
                    },
                    lineStyle:{
                        color:"#f00"
                    }
                }
            }
        ]
    });
});

### What is expected?
高亮效果显示

### What is actually happening?
没法使用高亮样式

**Comment by yufeng04** [comment]
#9942
