### ISSUE TITLE
当yAxis的max较大时，min无效？

### ISSUE THREAD

**Issue by Veigar-C** [apache/incubator-echarts#10438]
### Version
4.2.1

### Steps to reproduce
例如：
   yAxis: {
        type: 'value',
        min:0,
        max:10000
    },
依旧会把 小于0的 值渲染出来

### What is expected?
设置最小值0值，0以下的值被隐藏

### What is actually happening?
依旧会把小于0值渲染出来

**Comment by Ovilia** [comment]
请提供一个例子 https://gallery.echartsjs.com/editor.html

**Comment by Veigar-C** [comment]
https://gallery.echartsjs.com/editor.html?c=xRrLkkyMxn&v=2

**Comment by Ovilia** [comment]
这个看起来不是 bug，-1 那个数据确实显示的是连线的超出 0 的部分，所以是没有问题的。如果想要不显示连线的话，请把 -1 数据改为 `'-'`
