### ISSUE TITLE
4.0版本 series[i]-line.symbol为Function时出现bug

### ISSUE THREAD

**Issue by Coober-Ding** [apache/incubator-echarts#10440]
### Version
4.1.0-release

### Steps to reproduce
{
  series: {
            name: 'Beijing AQI',
            type: 'line',
            data: somedata,
            symbol: function (value) {
                return 'circle'
            }
        }
}

### What is expected?
折线图中每个点位的symbol可以根据他的value变化

### What is actually happening?
直接导致折线图无法显示

**Comment by Ovilia** [comment]
请提供一个例子 https://gallery.echartsjs.com/editor.html

**Comment by Coober-Ding** [comment]
`
option = {
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {},
    series: [{
        type: 'line',
        data:[220, 182, 191, 234, 290, 330, 310],
        // 文档中说symbol可以是Function，但我观察代码，发现并没有实现此功能。
        symbol: function (value) {
            if (value > 200) {
                return 'circle'
            }
            return 'rect'
        }
    }]
};
`

**Comment by Ovilia** [comment]
https://github.com/apache/incubator-echarts/commit/2b86ddd81780198a5d1a126e29a196558b8c4411 已修复，请使用最新版本，应该是 OK 的。

**Comment by zhibikanmohuakai** [comment]
@Ovilia https://gallery.echartsjs.com/editor.html?c=xJRpq5QC2j&v=2,好像还是存在这个问题
[https://gallery.echartsjs.com/editor.html?c=xJRpq5QC2j&v=2](url)

**Comment by zhibikanmohuakai** [comment]
@Ovilia 我已经修复了这个bug，想提个PR

**Comment by Ovilia** [comment]
@zhibikanmohuakai 这是两个问题，#10481 是 markLine 的，而本 issue #10440 是系列的。前者的确存在问题，我会看下你的 PR，非常感谢；后者是没有问题的。

**Comment by zhibikanmohuakai** [comment]
@Ovilia 应该都是同样的问题，同样的修复方法。

**Comment by zhibikanmohuakai** [comment]
@Ovilia 让symbol显示出来，就是修改symbol.js文件，这个是公用的，但是function不一定能收到参数，我改了MarkLine上的代码，能收到参数了。有位朋友按我的改，说没有参数，因为他改的是MarkLine上的，而不是系列上的。修改方法应该是和MarkLine一样的。

**Comment by AlexPeng19** [comment]
@Ovilia series-tree.symbol也存在这个问题貌似。

**Comment by rizhaoxianglushengziyan** [comment]
我想知道这个symbol函数这个问题解决没有请问！

**Comment by alonesmall** [comment]
4的最新版本4.9.0仍旧存在这个问题。这情何以堪啊。
