### ISSUE TITLE
数据框选无法正确选中密集数据

### ISSUE THREAD

**Issue by sjtuzwj** [apache/incubator-echarts#10443]
### Version
4.2.1

### Steps to reproduce

我使用4000个数据样本，在8*10的方格上绘制散点图，要求能根据框选导出被选点的索引，但是某些区域无法导出索引，但是，在dataZoom放大后，导出又正确。

### What is expected?

导出正确数目的数组样本（如140）

### What is actually happening?

在正常视图下无法正确选中，放大后才能正确运行。

---
我怀疑可能和brush点与图大小相比过于密集有关，可能是某些地方出现了崩溃才返回了空值。

**Comment by sjtuzwj** [comment]
![black-big](https://user-images.githubusercontent.com/32933716/57581821-a83bae00-74ef-11e9-9324-a02bfcc06df1.JPG)
![black-big](https://user-images.githubusercontent.com/32933716/57581822-aa057180-74ef-11e9-9f6b-e3f37beead76.JPG)
补充两个图片，分别是放大和缩小时的输出结果，根据
```
		var id = [];
		var mainSeries = params.batch[0].selected[0];

		for (var i = 0; i < mainSeries.dataIndex.length; i++) {
				var dataIndex = mainSeries.dataIndex[i];
				id.push(tsjson[dataIndex][3]);
		}
		console.log(id);``
```

**Comment by sjtuzwj** [comment]
![black](https://user-images.githubusercontent.com/32933716/57581833-e89b2c00-74ef-11e9-9cd1-b2b9fb5c295a.JPG)
不好意思，上面图片传错了一张

**Comment by Ovilia** [comment]
可能是因为数据太多，在显示的时候做了优化处理，把 https://echarts.baidu.com/option.html#series-scatter.largeThreshold 这个值设得大一点（10000）试试？

**Comment by sjtuzwj** [comment]
> 可能是因为数据太多，在显示的时候做了优化处理，把 https://echarts.baidu.com/option.html#series-scatter.largeThreshold 这个值设得大一点（10000）试试？
large
[ default: false ]
是否开启大数据量优化，在数据图形特别多而出现卡顿时候可以开启。
我尝试了几组参数：
large：false threshold： 2000 无效
large：false  threshold：10000 无效
large： true threshold：10000 正常
large：true threshold： 2000 异常（优化开启）
请问这个默认不该是不开优化的么。

**Comment by sjtuzwj** [comment]
> 可能是因为数据太多，在显示的时候做了优化处理，把 https://echarts.baidu.com/option.html#series-scatter.largeThreshold 这个值设得大一点（10000）试试？

large
[ default: false ]
是否开启大数据量优化，在数据图形特别多而出现卡顿时候可以开启。
我尝试了几组参数：
large：false threshold： 2000 无效
large：false threshold：10000 无效
large： true threshold：10000 正常
large：true threshold： 2000 异常（优化开启）
请问这个是因为默认开了优化导致我必须使用large进行覆盖么

**Comment by Ovilia** [comment]
是的，所以是文档错了对吧，默认值其实是 true
