### ISSUE TITLE
用了axisLabel 属性，横坐标的最后一项会加粗

### ISSUE THREAD

**Issue by 695750180** [apache/incubator-echarts#10445]
### Version
4.1.0-release

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xUk6_ZbrEF&v=1](https://gallery.echartsjs.com/editor.html?c=xUk6_ZbrEF&v=1)

### Steps to reproduce
打开链接就能重现

### What is expected?
最后一项与前面几项横坐标的文字格式一样，不要加粗

### What is actually happening?
最后一项的横坐标会被加粗

**Comment by Ovilia** [comment]
Duplicate of #10304
