### ISSUE TITLE
y轴最后一行展示单位的项是单位，也就是y轴和x轴多出一条网格线，这个如何做到

### ISSUE THREAD

**Issue by Deadpool957** [apache/incubator-echarts#10452]
### Version
4.2.1

### Steps to reproduce
Y轴多出一条展示单位

### What is expected?
y轴最后一行展示单位的项是单位，也就是y轴和x轴多出一条网格线

### What is actually happening?
不能确定y轴数据分割的段数

**Comment by cuijian-dexter** [comment]
Please provide an example.https://gallery.echartsjs.com/editor.html
