### ISSUE TITLE
How to properly adapt negative data in the stacked line plot？

### ISSUE THREAD

**Issue by sjtuzwj** [apache/incubator-echarts#10458]
### Version
4.2.1

### Steps to reproduce
我使用了一组数据，这组数据理论上应该能是相加等于1，但是由于原始采集数据出现了问题，其中出现了负值，因此显示异常，但是我并不想因为这些错误的数据影响我自己的表现方式。

### What is expected?
负值的线能出现在下方

### What is actually happening?
负值出现了异常（直接大跳跃）

---
我使用了一组数据，这组数据理论上应该能是相加等于1，但是由于采集数据出现了问题，其中出现了负值，因此显示异常，但是我并不想因为这些错误的数据影响我自己的表现方式。

**Comment by sjtuzwj** [comment]
![stack](https://user-images.githubusercontent.com/32933716/57666147-8cd8bc00-7631-11e9-9f5b-341957023be3.JPG)
图形大概像这样

**Comment by Ovilia** [comment]
目前 ECharts 不支持正负叠加，只能正数和正数叠加，负数和负数叠加。不是很有精力支持这个功能，欢迎提 PR。
