### ISSUE TITLE
bootstrap tab切换的时候，怎么关闭echarts的从小到大的动画效果？而保留其他正常的动画效果

### ISSUE THREAD

**Issue by dousee163** [apache/incubator-echarts#10455]
### What problem does this feature solve?
包含echarts的div，从display:none切换到display:block的时候，echarts会从小到大变化，希望能够去掉该动画。

### What does the proposed API look like?
如果可以通过option中增加相应的属性可以指定是否需要该动画就完美了。

**Comment by Ovilia** [comment]
series 的 animation 设为 false 试下

**Comment by dousee163** [comment]
> series 的 animation 设为 false 试下

正常的动画效果要保留
tab切换的时候我调用了resize，就是像去掉这个resize带来的动画效果。
因为从0开始变大，效果不是很理想。

如果关闭不了这个动画，那么有没有办法tab隐藏的时候，echarts的高度和宽度不是0，而是实际的数值？
现在echart最外层那个div，在tab隐藏的时候宽度和高度都是0，应该是这个引起的。
