### ISSUE TITLE
关系图为circular时，node重叠

### ISSUE THREAD

**Issue by wuyong0103** [apache/incubator-echarts#10462]
### Version
4.2.1

### Reproduction link
[http://www.szdb.org/SZDB2/temp.html](http://www.szdb.org/SZDB2/temp.html)

### Steps to reproduce
直接打开链接即可

### What is expected?
node不会重叠

### What is actually happening?
node会重叠

**Comment by susiwen8** [comment]
@wuyong0103 Could you provide full options, Thanks.

**Comment by wuyong0103** [comment]
[Uploading temp.txt…]()

**Comment by susiwen8** [comment]
Can't open this. Could you copy past options or create a gallery https://gallery.echartsjs.com/editor.html

**Comment by wuyong0103** [comment]
sorry， please refer to https://gallery.echartsjs.com/editor.html?c=xS_cKjFJ_s

**Comment by susiwen8** [comment]
Last 3 datas' value are 0, 
https://github.com/apache/incubator-echarts/blob/master/src/chart/graph/circularLayoutHelper.js#L45
So the last 3 circle will overlap.
