### ISSUE TITLE
The gradient color near boundary of pieces of visualMap

### ISSUE THREAD

**Issue by yanzijun** [apache/incubator-echarts#10469]
### Version
4.1.0-release

### Steps to reproduce
1. Use line chart
2. Use visualMap and set dimension on xAxis
3. The setting:
```
{
    type: 'piecewise',
    seriesIndex: 0,
    show: false,
    dimension: 0,
    outOfRange: {
         color: this.color.angle
    },
   pieces: [
        {lte: 131, color: "#bdbdbd"},
        {gt: 131, lte: 439, color: "#3f51b5"},
        {gt: 439, lte: 593, color: "#c5cae9"},
        {gt: 593, lte: 900, color: "#3f51b5"},
        {gt: 900, lte: 1052, color: "#c5cae9"},
        {gt: 1052, lte: 1360, color: "#3f51b5"},
        {gt: 1360, lte: 1515, color: "#c5cae9"},
        {gt: 1515, lte: 1823, color: "#3f51b5"},
        {gt: 1823, lte: 1977, color: "#c5cae9"},
        {gt: 1977, lte: 2285, color: "#3f51b5"},
        {gt: 2285, lte: 2295, color: "#c5cae9"},
        {gt: 2295, lte: 2302, color: "#bdbdbd"},
  ]
}
```

![](https://i.imgur.com/r41Roxe.png)

### What is expected?
Same color of the piece

### What is actually happening?
Gradient color of the piece

**Comment by yanzijun** [comment]
And I found that if I removed the pieces after ``{gt: 1360, lte: 1515, color '#3f51b5'}`` the gradient wouldn't appear.

**Comment by Ovilia** [comment]
Please provide a full demo at https://gallery.echartsjs.com/editor.html or https://jsfiddle.net/ovilia/yh76w9Lt/

**Comment by yanzijun** [comment]
@Ovilia  Thanks.
Here is my full demo on jsfiddle.
https://jsfiddle.net/iamyanjun/k96Lxupb/1/

**Comment by Ovilia** [comment]
It doesn't seem with v4.2.1 in your demo.
<img width="448" alt="屏幕快照 2019-05-17 15 32 16" src="https://user-images.githubusercontent.com/779050/57910960-16e68600-78b9-11e9-9453-81113df31d8f.png">
Is this expected?

**Comment by yanzijun** [comment]
@Ovilia  But the bug occurred again when I zoomed in.

![image](https://user-images.githubusercontent.com/19961707/57914094-9d529600-78c0-11e9-8b89-f8d6df344bb3.png)

**Comment by Ovilia** [comment]
Please make the data as minimum as possible. It's so hard to debug such data.
And there are quite a lot of colors in `pieces` colors. Make it two.
