### ISSUE TITLE
expandAndCollapse works incorrect

### ISSUE THREAD

**Issue by CatWithWings** [apache/incubator-echarts#10471]
### Version
4.2.1

### Steps to reproduce
echarts的tree，设置expandAndCollapse: true时关于收缩之后的data diff唯一的标识是如何确定的呢。当我的tree数据中有2个分支部分数据重复时，会出现收缩分支之后，原来旧的分支没有被擦除，导致视图上出现许多多余分支，新旧分支视图重叠的现象。
![test](https://user-images.githubusercontent.com/33889739/57746958-0b069280-7706-11e9-8d50-1e12311df591.jpg)

### What is expected?
只出现收缩或展开后的新视图

### What is actually happening?
新旧视图同时出现

**Comment by deqingli** [comment]
we do data diff based on data index.

**Comment by deqingli** [comment]
You can see [here]( https://github.com/apache/incubator-echarts/blob/master/src/chart/tree/TreeView.js#L104).

**Comment by CatWithWings** [comment]
> You can see [here](https://github.com/apache/incubator-echarts/blob/master/src/chart/tree/TreeView.js#L104).
So, does the data I pass in have nothing to do with the diff of the graph? 
Try this options:
`
  const options = {
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'tree',

                data: [{
                    name: "Root",
                    children: [
                        {
                            "name": "ss",
                            "children": [
                                {
                                    "id": "71",
                                    "name": "alan",
                                    "children": [
                                        {
                                            "id": "55",
                                            "name": "test11"
                                        },
                                        {
                                            "id": "02",
                                            "name": "test12"
                                        }
                                    ]
                                },
                                {
                                    "id": "24",
                                    "name": "liu",
                                    "children": [
                                        {
                                            "id": "71",
                                            "name": "测25试2222222222222222",
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }],

                top: '1%',
                left: '7%',
                bottom: '1%',
                right: '20%',

                symbolSize: 7,

                label: {
                    normal: {
                        position: 'left',
                        verticalAlign: 'middle',
                        align: 'right',
                        fontSize: 9
                    }
                },

                leaves: {
                    label: {
                        normal: {
                            position: 'right',
                            verticalAlign: 'middle',
                            align: 'left'
                        }
                    }
                },

                expandAndCollapse: true,
                initialTreeDepth: 3,
                animationDuration: 550,
                animationDurationUpdate: 750
            }
`

**Comment by deqingli** [comment]
@CatWithWings  I want to ask why you set the same `id` of node 'alan' and node '测25试222222222'
