### ISSUE TITLE
y轴是类目轴，x轴是数值轴, x轴如何实现向类目轴那样的 坐标轴分割间隔？

### ISSUE THREAD

**Issue by maxiong88** [apache/incubator-echarts#10477]
### What problem does this feature solve?
我在 x轴设置了
``` js
axis：{
min:0,
max:  100,
interval: 10,
type: 'value',
}
```
实际展示的是0， 10， 20， 30， 40， 50， 60，70，80，90，100

### What does the proposed API look like?
期望展示的是0， 20，40，60，80，100

**Comment by Ovilia** [comment]
Then you should probably set `interval` to be 20.

**Comment by maxiong88** [comment]
> Then you should probably set `interval` to be 20.

可能我没有表达清楚，

我的意思是 

x轴是数值轴 ，我期望展示 0 ，10， 20， 30，40，50，60，70，80，90，100（显示11个刻度标签）

然后把 10， 30， 50， 70， 90 这四个值隐藏掉，只显示刻度标签

类似 类目轴

`axisLabel.interval` 这个属性

**Comment by Ovilia** [comment]
哦哦，用 formatter，不要的值返回空字符串

**Comment by maxiong88** [comment]
> Then you should probably set `interval` to be 20.



> 哦哦，用 formatter，不要的值返回空字符串

非常感谢，可以的
