### ISSUE TITLE
symbol无法使用

### ISSUE THREAD

**Issue by WhoIsSmile** [apache/incubator-echarts#10473]
### Steps to reproduce
使用timelinme   data 中配置 symbol   值为 diamond

### What is expected?
symbol  值为diamond ，4.0.4可以使用

### What is actually happening?
没有展示

**Comment by susiwen8** [comment]
Can you provide a demo? Cause this link is working
https://www.echartsjs.com/gallery/editor.html?c=doc-example/mix-timeline-all
