### ISSUE TITLE
ajax 请求数据后 setOption(option, true) 报错

### ISSUE THREAD

**Issue by oushiun** [apache/incubator-echarts#10497]
### Version
4.2.1

### Steps to reproduce
通过ajax 请求数据后，设置setOption(option, true) 
console 报错
Uncaught TypeError: Cannot read property 'get' of undefined

### What is expected?
重新加载数据重新渲染

### What is actually happening?
Uncaught TypeError

**Comment by Ovilia** [comment]
get 方法是什么对象上的呢？请使用非压缩版本，查看 console 中出问题的地方是哪一行引起的
