### ISSUE TITLE
使用曲线图或饼图,鼠标移出图区后再移进来,提示窗口(气泡)就在图区下面和很远处,甚至在屏幕外面

### ISSUE THREAD

**Issue by iceelee** [apache/incubator-echarts#10493]
### Version
4.2.1

### Steps to reproduce
option如下：
    var option = {
        title: {
            text: title
        },
        tooltip: {
            trigger: 'axis'
        },
        legend: {
            data: lines_name
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        toolbox: {
            feature: {
                saveAsImage: {}
            }
        },
        xAxis: {
            type: 'category',
            boundaryGap: false,
            data: lines_date
        },
        yAxis: {
            type: 'value'
        },
        series: series
    };

### What is expected?
希望提示窗口(气泡)能跟随鼠标弹出，例如在右下角。 当屏幕下方区域不够时，可以在右上角弹出。类似于windows sdk的listbox上的右键窗口一样。

### What is actually happening?
气泡位置太远，导致屏幕上无法看到。

**Comment by iceelee** [comment]
![无标题](https://user-images.githubusercontent.com/18380546/57995515-12a6ac80-7af5-11e9-8661-f959a38fe05b.png)

**Comment by Ovilia** [comment]
请提供一个可运行的例子 https://gallery.echartsjs.com/editor.html
