### ISSUE TITLE
柱状图，x轴文字颜色深浅不一致，最后一个加粗，怀疑是重复渲染。

### ISSUE THREAD

**Issue by fanyifanbumaimeng** [apache/incubator-echarts#10507]
### Version
4.2.1

### Steps to reproduce
// 基于准备好的dom，初始化echarts实例
    let myChart = echarts.init(document.getElementById('bar'));
    // 绘制图表
    myChart.setOption({
      title: {
        text: '风险内容',
        textStyle: {
          fontSize: 16,
          color: '#24344E',
        },
      },
      tooltip: {},
      xAxis: {
        data: ['涉政暴恐', '敏感人物', '用户定义', '内容篡改', '垃圾信息', '色情低俗'],
        axisLabel: {
          interval: 0,
          show: true,
          textStyle: { color: 'rgba(0,0,0,0.80)' },
        },
        axisLine: { lineStyle: { color: '#eee' } },
        axisTick: { show: false },
        scale: false,
      },
      grid: {
        containLabel: true,
        left: 10,
      },
      yAxis: {
        axisLine: { show: false },
        axisLabel: {},
        axisTick: { show: false },
        scale: false,
      },
      series: [{
        data: this.props.data,
        name: '风险内容',
        type: 'bar',
        barWidth: 18, // 柱图宽度
        itemStyle: {
          normal: {
            // 每根柱子颜色设置
            color (params) {
              let colorList = [
                '#FF0080',
                '#FF3B60',
                '#FF7342',
                '#FFA12A',
                '#FFCA14',
                '#FFEE00',
              ];
              return colorList[params.dataIndex];
            },
            label: {
              show: true, // 开启显示
              position: 'top', // 在上方显示
              textStyle: { // 数值样式
                color: 'rgba(0,0,0,0.80)',
                fontSize: 12,
              },
            },
          },
        },
      }],
    }, true, false);

### What is expected?
x轴文字粗细一致。

### What is actually happening?
x轴文字粗细不一致

**Comment by Ovilia** [comment]
Duplicate of #10304

**Comment by 18595439829** [comment]
请问楼主解决了吗?

**Comment by YaoKaiPeng** [comment]
@Ovilia 请问近期会做更新吗？

**Comment by Ovilia** [comment]
预计本周开始在 Apache 进入发版投票流程，具体发版时间要看投票过程是否顺利

**Comment by foolzhang** [comment]
#### xAxis :{
     axisLable:{
         borderWidth:10, // 大小盖住你的文本即可 
         borderColor:'#fff', // 背景色
         interval:0
    }
#### }
