### ISSUE TITLE
legend.height is not working

### ISSUE THREAD

**Issue by Nilegfx** [apache/incubator-echarts#10504]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/bgrL3yp2/](https://jsfiddle.net/bgrL3yp2/)

### Steps to reproduce
add `height` to any legend component

### What is expected?
height being reflected on the legend component

### What is actually happening?
height is not reflected on the legend component

**Comment by Ovilia** [comment]
`legend.height` is for determining new columns when `orient` is `'verticle'`. See https://jsfiddle.net/ovilia/0dvm9wn4/1/

**Comment by futaz** [comment]
If you want the chart area's top to be lower, use ```grid.top``` instead. See the [docs](https://echarts.apache.org/v4/en/option.html#grid.top) for details.
