### ISSUE TITLE
3.7.2升级到4.1.0，设置堆叠属性stack之后，markline还在原来的位置。

### ISSUE THREAD

**Issue by LingboCN** [apache/incubator-echarts#10502]
### Version
4.1.0-release

### Steps to reproduce
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200],
        type: 'bar',
        stack: 'savings',
        
    },
    {
        data: [100,50],
        type: 'bar',
        stack: 'savings',
        markLine: {
            data: [{
                yAxis: 'max'
            },{
                type: 'max'
            }],
            lineStyle: {
                width:0.5,
                type: 'dashed',
                color: '#333'
            }
        }
    }]
};

### What is expected?
期望结果markline在220的位置

### What is actually happening?
实际markline在100的位置

---
如果有规避方法请尽快回复

**Comment by Ovilia** [comment]
应该 max 是 250 而不是 220 吧？

**Comment by LingboCN** [comment]
120+100 = 220；200 + 50 = 250；
关键是markline还是在100上，没有根据stack属性堆叠起来

**Comment by Ovilia** [comment]
哦懂了，因为 markLine 是在后一个 series 中的，所以应该判断后一个的 max 然后画到正确的位置。标记为 bug 了。

**Comment by susiwen8** [comment]
@LingboCN @Ovilia problem is here
https://github.com/apache/incubator-echarts/blob/master/src/component/marker/MarkLineView.js#L54 cause markline did't check  whether this was a stack or not.

**Comment by Ovilia** [comment]
@susiwen8 Excellent!
