### ISSUE TITLE
使用最新代码报错symbolType.indexOf is not a function

### ISSUE THREAD

**Issue by 863062879** [apache/incubator-echarts#10512]
看了以前的报的bug说修复了    但是刚下载的文件使用依然报这个错误

**Comment by AnonymousArthur** [comment]
This issue should be re-opened. This is still a issue. @100pah

**Comment by l-hammer** [comment]
This issue should be re-opened. This is still a issue. @100pah

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/82f6a086-3a85-4b19-8057-234f02874da0">
