### ISSUE TITLE
使用markline画分区域，导致拖拽很卡有办法优化吗

### ISSUE THREAD

**Issue by gelibin** [apache/incubator-echarts#10517]
### What problem does this feature solve?
需求需要在图表中划分十几二十个区域，现在是用markline画线的方式实现。网络拓扑图需要在不同区域间实现拖拽以及图表缩放功能，现在问题是当markline线太多时拖拽拓扑图节点很卡顿，而且缩放功能markline的线并不会像grid线那样一直保持存在。

### What does the proposed API look like?
怎么优化当用markline画分区域时拖拽功能会变得流畅，多条线形成的区域缩放能否像grid网格线样保持不消失，是否能出个api控制个背景缩放功能。

**Comment by Ovilia** [comment]
不太理解网络拓扑图中 markline 是怎么用的，只是用来画线的吗？那可以试试 https://echarts.baidu.com/option.html#graphic.elements-line

**Comment by gelibin** [comment]
@Ovilia series: [{
                type: 'graph',
                layout: 'force',
                id:'a',
                // coordinateSystem: 'cartesian2d',
                coordinateSystem: 'cartesian2d',
                edgeSymbol: ['',''],
                // symbolSize: 20,
//                force: {
//                  repulsion: 1000,
//                  edgeLength: [150, 200],
//                  layoutAnimation: false
//                },
                label: {
                  normal: {
                    show: true,
                    position: 'bottom',
                    color: '#12b5d0'
                  }
                },
                lineStyle: {
                  normal: {
                    width: 2,
                    shadowColor: 'none'
                  }
                },
                xAxis: {
                  min: 0,
                  max: 100,
                  show: false,
                  type: 'value'
                },
                yAxis: {
                  min: 0,
                  max: 100,
                  show: false,
                  type: 'value'
                },
                 //画虚线框-南北楼
                markLine : {
                    symbol:'none',
                    lineStyle: {
                        normal: {
                            type: 'dashed',
                            color:'#3162B1',
                            opacity:1
                        },
                        
                    },
                    label:{
                      normal:{
                        position:'middle',
                        color: '#3576DB',
                        // formatter:function(params){
                        //     if(params.name){
                        //     var str =  params.name.replace(/(.{6})/g, '$1\n')
                        //     return str
                        //     }
                        // },
                      }
                    },
                    data : outsideCoords
                },
                // edgeSymbolSize: 8,
                draggable:true,
                data: this.charts.nodes,
                links: this.charts.links,
                z:9,
                itemStyle: {
                  normal: {
                    label: {
                      show: true,
                      formatter: function(item) {
                        return item.data.name
                      }
                    }
                  }
                }
              }
              , {
                name: 'A',
                id:'b',
                type: 'lines',
                coordinateSystem: 'cartesian2d',
                // edgeSymbol: ['circle', 'arrow'],
                // effect: {
                //   show: true,
                //   trailLength: 0,
                //   // constantSpeed: 30,
                //   symbol: 'arrow',
                //   color: '#12b5d0',
                //   // color:'#FF0000',
                //   symbolSize: 8
                // },
                // data: this.charts.linesData,
                z:9,
                //画虚线框-内部
                markLine : {
                    symbol:'none',
                    lineStyle: {
                        normal: {
                            type: 'solid',
                            color:'#3162B1',
                            opacity:1
                        },
                        
                    },
                    label:{
                      normal:{
                        position:'middle',
                        color: '#7BA4E3',
                        formatter:function(params){
                            if(params.name){
                            var str =  params.name.replace(/(.{6})/g, '$1\n')
                            return str
                            }
                        },
                      }
                    },
                    data : coords
                },
              }
              ]
markline的data值是：
coords = [
    //每个框都按照左上右下的方式
          [
              {
                  yAxis: 55,
                  xAxis: 0
              },
              {
                  yAxis: 100,
                  xAxis: 0
              }
          ],
          [
              {
                  yAxis: 100,
                  xAxis: 0
              },
              {
                  yAxis: 100,
                  xAxis: 100
              }
          ],
          [
              {
                  yAxis: 100,
                  xAxis: 100
              },
              {
                  yAxis: 55,
                  xAxis: 100
              }
          ],
          [
              {
                 name:'北楼',
                  yAxis: 55,
                  xAxis: 100
              },
              {
                  yAxis: 55,
                  xAxis: 0
              }
          ]]

**Comment by Ovilia** [comment]
https://gallery.echartsjs.com/editor.html 在这里放个完整的吧
