### ISSUE TITLE
在页面返回时,X轴变形

### ISSUE THREAD

**Issue by qqfei1858** [apache/incubator-echarts#10513]
### Version
4.2.1

### Steps to reproduce
1.定时走线
2.页面缩小到任务栏或者切换到其他页面,过一会再返回页面就变形了!

### What is expected?
解决变形问题!

### What is actually happening?
变形

**Comment by qqfei1858** [comment]
变形
![QQ图片20190521175552](https://user-images.githubusercontent.com/26538473/58086691-b2e1fb80-7bf1-11e9-82ea-f3ab3df2d6ec.png)

正常(不离开页面)
![QQ图片20190521175625](https://user-images.githubusercontent.com/26538473/58086723-c2f9db00-7bf1-11e9-876e-063c18492c98.png)

**Comment by Ovilia** [comment]
请提供一个简单的能复现的例子 http://gallery.echartsjs.com/editor.html

**Comment by agua001** [comment]
只看图不明白其中的问题
