### ISSUE TITLE
 堆积柱状图拖动dateZoom平移时bar的长度会缩小并且bar会超出坐标轴

### ISSUE THREAD

**Issue by YFzuoye** [apache/incubator-echarts#10518]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xcwOnvKZ22&comment=0](https://gallery.echartsjs.com/editor.html?c=xcwOnvKZ22&comment=0)

### Steps to reproduce
拖动dataZoom平移

### What is expected?
拖动dataZoom平移，bar的末尾对应时间

### What is actually happening?
拖动dateZoom平移时bar的长度会缩小并且bar会超出坐标轴

**Comment by Ovilia** [comment]
Ralate to #8935

**Comment by 100pah** [comment]
Fixed in 4.4.0
