### ISSUE TITLE
柱状堆叠图，当设置坐标轴的type为log时，显示错误

### ISSUE THREAD

**Issue by yj0zhang** [apache/incubator-echarts#10520]
### Version
4.2.1

### Reproduction link
[https://codepen.io/yj0zhang/pen/xNpZyd](https://codepen.io/yj0zhang/pen/xNpZyd)

### Steps to reproduce
打开CodePen的链接，xAxis的type是log，柱子的长度计算错了，改成value是对的

### What is expected?
期望显示正常

### What is actually happening?
图中红框中应该有个长度为100的柱子，实际上没有显示
![image](https://user-images.githubusercontent.com/9312245/58165278-01f36380-7cba-11e9-93d0-39c2f3de5485.png)

**Comment by susiwen8** [comment]
Same problem with  #10501
