### ISSUE TITLE
【功能建议】建议ECharts图例和悬停提示支撑部分html内容，在某些专业领域对此很注重。

### ISSUE THREAD

**Issue by vv-lin** [apache/incubator-echarts#10524]
### What problem does this feature solve?
建议ECharts图例和悬停提示只是部分html内容，<b>在某些专业领域对此很注重。</b><br><br>
比如：<br><br>
空气质量的PM<sub>2.5</sub>中的“2.5”就是下标。<br><br>
化学里面的离子Na<sup> </sup>中的“ ”就是上标。<br><br>
长度单位m<sup>2</sup>中的“2”是上标。<br><br>

### What does the proposed API look like?
<xmp>
legend: {
        data:['PM<sub>2.5</sub>','Na<sup> </sup>','M<sup>2</sup>']
}
</xmp>

**Comment by Ovilia** [comment]
悬停提示是指 tooltip 吗？tooltip 默认是 html 的。图例的 html 是指图例右边的文字吗？这个从技术角度来看不太可能支持 html

**Comment by vv-lin** [comment]
您好，非常感谢您百忙之中的答复！
我没有仔细研究过ECharts的源码，所以不知道legend的具体实现过程。
但是我有个构想，当然，这构想仅供参考：
目前legend和series中的name必须一致，所以我简单粗暴的理解为，legend和series是通过名称关联。
那么是不是可以让legend支持key-value这种模式呢，显示的时候是value，关联的时候是key。
比如可以在legend中构建:
legend: {
    data: [{name: 'key1', text: 'm<sup>3</sup>'}, {name: 'key2', text: 'Na<sup>+</sup>'}]
}
或：
legend: {
    data: ['key1', 'key2'],
    text: ['m<sup>3</sup>', 'Na<sup>+</sup>']
}

当然，如何构建只是方式而已，确立关联关系才是重点。这个改动量应该很大。


鼠标悬停确实是指的tooltip，我的意思是如果legend中支持html，那么对应tooltip应该自动就变成了legend中的样式。
举例：
legend中变成了‘m³’，那么在tooltip中如果显示m3就是不对的，应该默认就变成了‘m³’。




------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 上午10:56
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "怑喥嶶涼╭ァ"<1009019067@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/incubator-echarts] 【功能建议】建议ECharts图例和悬停提示支撑部分html内容，在某些专业领域对此很注重。 (#10524)




悬停提示是指 tooltip 吗？tooltip 默认是 html 的。图例的 html 是指图例右边的文字吗？这个从技术角度来看不太可能支持 html

**Comment by Ovilia** [comment]
legend 不支持 html，所以即使支持你说的 key-value 的形式，支持了 `'m<sup>3</sup>'`，也没法做成上标的效果。目前来看这个需求不太容易实现。

**Comment by C-racker** [comment]
> legend 不支持 html，所以即使支持你说的 key-value 的形式，支持了 `'m<sup>3</sup>'`，也没法做成上标的效果。目前来看这个需求不太容易实现。

请问现在有更好的解决办法吗？

**Comment by vv-lin** [comment]
> > legend不支持html，所以即使支持你说的key-value的形式，支持了`'m<sup>3</sup>'`，也没法造成上标的效果。目前来看这个需求不太容易实现。
> 
> 请问现在有更好的解决办法吗？

> 我这边使用了小数字解决，但是兼容性不算好。可以搜索一下“小数字”

**Comment by C-racker** [comment]
> > > legend不支持html，所以即使支持你说的key-value的形式，支持了`'m<sup>3</sup>'`，也没法造成上标的效果。目前来看这个需求不太容易实现。
> > 
> > 
> > 请问现在有更好的解决办法吗？
> 
> 我这边使用了小数字解决，但是兼容性不算好。可以搜索一下“小数字”

有没有办法支持斜体等其他 html 标签，如果挨个处理工程量很大。

**Comment by pissang** [comment]
echarts 的标签不支持 HTML 模式（这样可以尽可能的保证不同平台的一致性），如果需要斜体的话可以设置 fontStyle，复杂的组合样式可以通过富文本实现。

如果是需要 HTML 的排版能力，目前在外部用 html 绘制 legend，然后通过 dispatchAction 来控制交互
