### ISSUE TITLE
Split line(width:4, color:white) of RadiusAxis is hidden when SplitArea colors applied in polar chart, type scatter.

### ISSUE THREAD

**Issue by Venkat-codeworld** [apache/incubator-echarts#10526]
### Version
2.2.1

### Reproduction link
[https://jsfiddle.net/3cqtv7gu/](https://jsfiddle.net/3cqtv7gu/)

### Steps to reproduce
Follow jsfiddle link. Search and go to test comment in the code.

### What is expected?
Expecting circular gaps with white colour between blue areas.

### What is actually happening?
White colour lines are hidden under blue areas

**Comment by Ovilia** [comment]
Sorry. Your demo is a little complicated. I cannot understand what's wrong here.
Please give the code for `Expecting circular gaps with white colour between blue areas.`.
And some images may here to better illustrate.
