### ISSUE TITLE
Treemap Blinking

### ISSUE THREAD

**Issue by hemantITT** [apache/incubator-echarts#10521]
### Version
4.2.1

### Steps to reproduce
OS: MacOS
ScreenSize: 27inch
Browser: Chrome

1) there is large number of data for TreeMap.  2) Use below similar settings.  3) Treemap is used same as demo: https://ecomfe.github.io/echarts-examples/public/editor.html?c=treemap-show-parent

{
                    name: 'Main',
                    type: 'treemap',
                    // width: '98%',
                    // height: '95%',
                    // left: 30,
                    roam: false,
                    visibleMin: 300,

                    label: {
                        show: true,
                        color: fontColor,
                        position: 'absolute',
                        formatter: function (info) {
                            var labelData = info.data.labels;
                            var labelValueArr = [];
                            if(labelData !== undefined) {
                                Object.keys(labelData).forEach(function (label) {
                                    var labelVal = '';
                                    //Check lable value is not null or undefined.If undefined then keep blank.
                                    if(util.nullCheck(labelData[label])) {
                                        labelVal = labelData[label];
                                    }

                                    if(label === 'guest') {
                                        labelValueArr.push(labelVal);
                                    } else if(label === 'stand') {
                                        label = 'Location';
                                        labelValueArr.push(label   ':'   labelVal);
                                    } else {
                                        labelValueArr.push(label   ':'   labelVal);
                                    }
                                });
                            }
                            return labelValueArr.join('\n');
                        },
                    },
                    upperLabel: {
                        normal: {
                            show: true,
                            height: 30
                        }
                    },
                    itemStyle: {
                        normal: {
                            borderColor: '#fff'
                        }
                    },
                    levels: $scope.levelOption,
                    data: $scope.treemapData
                }

### What is expected?
Treemap should be displayed properly

### What is actually happening?
Treemap result is displayed but when mouse is hovered on parent label then all the items of treemap go invisible

---
It only happens on large data

**Comment by hemantITT** [comment]
When mouse hovered on label :

![Screen Shot 2019-05-22 at 3 00 52 PM](https://user-images.githubusercontent.com/50147906/58171988-e76abb80-7cb4-11e9-96a4-91f46fcb6c83.png)

When the treemap is loaded
![Screen Shot 2019-05-22 at 3 03 32 PM](https://user-images.githubusercontent.com/50147906/58171996-ef2a6000-7cb4-11e9-9864-75320a1e993b.png)

**Comment by Ovilia** [comment]
Please provide a working demo as simple as possible here: https://jsfiddle.net/ovilia/n6xc4df3/

**Comment by hemantITT** [comment]
Hi could not save into above given url. I have created a new one. 
https://jsfiddle.net/hemantss/uwh2543p/2/

**Comment by hemantITT** [comment]
Hi Ovilia please do you have any update for this issue.

**Comment by Ovilia** [comment]
@susiwen8 Could you help with this issue?

**Comment by susiwen8** [comment]
@Ovilia Sure, challenge accepted.

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/blob/master/src/echarts.js#L1666

**Comment by Ovilia** [comment]
@susiwen8 Nice job for finding out the reason! Although I don't think it is wise to change `progressiveThreshold` to be `Infinity` in the source code. Even it is the correct way to fix this demo, it should be changed in user code rather than source code. @100pah Please have a look.

**Comment by 100pah** [comment]
@hemantITT 

As @susiwen8 said, please set
```js
option: {
     hoverLayerThreshold: Infinity,
     series: { 
          ...
     }
}
```
to resolve this problem.

And the default `hoverLayerThreshold` of `treemap` will be fixed soon.

**Comment by hemantITT** [comment]
Thank you for fixing this one
