### ISSUE TITLE
堆叠图，未显示stack

### ISSUE THREAD

**Issue by chenyiqi** [apache/incubator-echarts#10530]
### What problem does this feature solve?
堆叠图中，怎么将stack的值展示出来，目前在页面上是看不到的，导致图的信息展示不明确

### What does the proposed API look like?
加一个参数配置，然后页面中就可以将stack的每个条形上展示

**Comment by Ovilia** [comment]
目前最简单的办法是，自己计算一下系列数值的和，然后作为最上面的系列的 label formatter 的返回值。

**Comment by chenyiqi** [comment]
我的需求不是求和，因为已经给分类了，但是这些分类在图表里根本没有体现，如果官方的例子，网络分类、广告，但是在图表里无法体现，代码里能看出来，我觉得官网应该考虑处理下这个问题，

**Comment by Ovilia** [comment]
想要什么样的效果，可以给个图说明一下吗？

**Comment by chenyiqi** [comment]
![1](https://user-images.githubusercontent.com/3357208/58417346-1a4af000-80b7-11e9-9055-0f9e28f69549.png)

**Comment by Ovilia** [comment]
这种支持的呀，正常地用就行了，参考例子 https://gallery.echartsjs.com/editor.html?c=xRQpCsH8Ci

**Comment by chenyiqi** [comment]
你注意到左侧有一个时间为201903的大的分类，然后还有子分类，另外你给的例子baseOption，在官网api上查不到是什么东西
