### ISSUE TITLE
tooltip.formatter function receives wrong data when using dataset.source

### ISSUE THREAD

**Issue by oktav777** [apache/incubator-echarts#10542]
### Version
4.2.1

### Reproduction link
[https://stackblitz.com/edit/typescript-tjkfuf?file=index.ts](https://stackblitz.com/edit/typescript-tjkfuf?file=index.ts)

### Steps to reproduce
- Open the reproduction link
- Hover over any series
- Open the console and investigate

### What is expected?
The `array[i].data` should contain the correct data for hovered group.

### What is actually happening?
The `array[i].data` contains incorrect data.

**Comment by Ovilia** [comment]
Why do you think the data is incorrect? What data is expected?

**Comment by oktav777** [comment]
I'm sorry, misunderstanding from my side. I managed to do what I intended. Closing the issue.
