### ISSUE TITLE
绑定事件能够给定一个明确id

### ISSUE THREAD

**Issue by yzhang921** [apache/incubator-echarts#10551]
### What problem does this feature solve?
目前echartsInstance.off, 事件解绑方法，两种格式一种是全部类型的事件都解绑，另外一种传递function，文档上说有function传递的情况下能够只解绑传递的function，但是测试了一下没有效果；不知道内部是通过什么机制追踪eventHanlder的，觉得如果能够让用户绑定事件的时候给定一个明确的id，这样在绑定多个不同的事件，如click、click alt，click ctrl多个不同的事件，能够精确解绑。

### What does the proposed API look like?
echartsInstance.on('click', id, function() {})
echartsInstance.off('click', id)

**Comment by Ovilia** [comment]
正确的使用方式：
```js
var a = function() {};
echartsInstance.on('click', a);
...
echartsInstance.off('click', a);
```

**Comment by yzhang921** [comment]
是的，但是感觉不准确，而且这个函数很有可能大部分场景下是局部变量，每次会随echartsInstance重复生成，有个类似ID的机制会更加好用

**Comment by Ovilia** [comment]
「不准确」是不可能的，局部变量的问题可以通过各种方法解决，比如 export 这个变量等。这一方法比较类似 JS 的 `addEventListener`

**Comment by yzhang921** [comment]
好吧，我换个说法，支持id绑定事件api会更加好用，更符合普通普通人的思维:smile:  
这个问题我已经用其他的办法绕过去了；这里只是提个小小的建议希望ECharts能够更好用
