### ISSUE TITLE
"echarts": "^4.2.1"这个版本的echarts哪些浏览器版本支持呀？

### ISSUE THREAD

**Issue by Daiqiangdeveloper** [apache/incubator-echarts#10558]
### Version
4.2.1

### Steps to reproduce
"echarts": "^4.2.1"这个版本的echarts哪些浏览器版本支持呀？

### What is expected?
"echarts": "^4.2.1"这个版本的echarts哪些浏览器版本支持呀？

### What is actually happening?
"echarts": "^4.2.1"这个版本的echarts哪些浏览器版本支持呀？

---
"echarts": "^4.2.1"这个版本的echarts哪些浏览器版本支持呀？

**Comment by Daiqiangdeveloper** [comment]
或者说  哪些浏览器及对应版本不支持  麻烦详细一点

**Comment by Ovilia** [comment]
IE8 及以下不支持，其他理论上都是支持的

**Comment by Daiqiangdeveloper** [comment]
谢谢回复 

> IE8 及以下不支持，其他理论上都是支持的
