### ISSUE TITLE
能否给axisPointer的label 增加一个align，而且 label 中的padding 设置并不生效，当左右两个值不相同时

### ISSUE THREAD

**Issue by CorruptKubCzh** [apache/incubator-echarts#10569]
### What problem does this feature solve?
在使用axisPointer.label 时，如果 文字内容被要求多行显示时，可以不再是居中显示

### What does the proposed API look like?
https://gallery.echartsjs.com/editor.html?c=xVszi2WnZ3&comment=0

app.title = '多 X 轴示例';
var colors = ['#5793f3', '#d14a61', '#675bba'];
option = {
    color: colors,

    tooltip: {
        trigger: 'none',
        axisPointer: {
            type: 'cross'
        }
    },
    legend: {
        data: ['2015 降水量', '2016 降水量']
    },
    grid: {
        top: 70,
        bottom: 90
    },
    xAxis: [{
            type: 'category',
            axisTick: {
                alignWithLabel: true
            },
            axisLine: {
                onZero: false,
                lineStyle: {
                    color: colors[1]
                }
            },
            axisPointer: {
                label: {
                    formatter: function(params) {
                        return '降水量 '   params.value  
                            (params.seriesData.length ? '：'   params.seriesData[0].data : '');
                    },
                    margin: 60,
                    align: 'left',
                    padding: [
                        5, // 上
                        60, // 右
                        5, // 下
                        0, // 左
                    ]
                }
            },
            data: ["2016-1", "2016-2", "2016-3", "2016-4", "2016-5", "2016-6", "2016-7", "2016-8", "2016-9", "2016-10", "2016-11", "2016-12"]
        },
        {
            type: 'category',
            axisTick: {
                alignWithLabel: true
            },
            axisLine: {
                onZero: false,
                lineStyle: {
                    color: colors[0]
                }
            },
            axisPointer: {
                label: {
                    formatter: function(params) {
                        return '降水量  '   params.value  
                            (params.seriesData.length ? '：'   params.seriesData[0].data : '');
                    }
                }
            },
            data: ["2015-1", "2015-2", "2015-3", "2015-4", "2015-5", "2015-6", "2015-7", "2015-8", "2015-9", "2015-10", "2015-11", "2015-12"]
        }
    ],
    yAxis: [{
        type: 'value'
    }],
    series: [{
            name: '2015 降水量',
            type: 'line',
            xAxisIndex: 1,
            smooth: true,
            data: [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
        },
        {
            name: '2016 降水量',
            type: 'line',
            smooth: true,
            data: [3.9, 5.9, 11.1, 18.7, 48.3, 69.2, 231.6, 46.6, 55.4, 18.4, 10.3, 0.7]
        }
    ]
};

**Comment by Ovilia** [comment]
配置项中没有看到 `align` 选项，但是现在 `padding` 没有 work 可能是 bug
