### ISSUE TITLE
large属性和单个数据项样式的冲突问题

### ISSUE THREAD

**Issue by 52jc** [apache/incubator-echarts#10568]
### Version
4.2.1

### Steps to reproduce
要写一个柱状图组成的频谱图,50ms发送2000条数据,数据量大,所以用了large属性,但是这个柱状图要求根据状态不同柱子显示不同的颜色,large属性用了之后就不能对单个柱子设样式了

### What is expected?
能优化大数据的同时,可以使频谱图的柱子根据状态显示不同的颜色

### What is actually happening?
使用large优化了数据之后就不能单个设置数据项的样式了

**Comment by Ovilia** [comment]
大数据优化的原理是采用批量设置样式，也就是在绘制所有的柱子前，统一设置样式，然后批量绘制柱子。所以在这个期间是不会检查单独的柱子样式的（否则会有严重的性能损耗）。
如果需要为单独的柱子设置样式，可以不开启 large，或者将这个样式不同的柱子设置在另一个系列中，对其他数据仍然开启 large。

**Comment by 52jc** [comment]
如何将柱子设置在另一个系列啊？外观能看出不是在同一个系列吗？

**Comment by Ovilia** [comment]
将原来系列中该数据的位置替换为 `'-'`，然后新建一个系列，其他只设为 `'-'`。样式自己相应调整即可。

**Comment by 52jc** [comment]
可是即使把数据换成'-',图上依然会为他留位置，有什么方法能把这个位置去掉吗？

**Comment by Ovilia** [comment]
我什么不留位置呢？留出位置才能用另一个系列在这个地方占位呀

**Comment by Ovilia** [comment]
给你写了个例子 https://gallery.echartsjs.com/editor.html?c=xRug8P9KEm&v=1

**Comment by 52jc** [comment]
十分感谢
