### ISSUE TITLE
地图显示异常

### ISSUE THREAD

**Issue by wxingheng** [apache/incubator-echarts#10576]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/preview.html?c=xBkVnciA0b&v=6](https://gallery.echartsjs.com/preview.html?c=xBkVnciA0b&v=6)

### Steps to reproduce
通过安卓5.1的手机访问，或者安卓6.0的手机访问   

地图会错乱分散

### What is expected?
地图正常显示

### What is actually happening?
地图分散

**Comment by Ovilia** [comment]
找不到 5 或 6 的安卓手机，建议尝试 SVG 版本看看有没有问题

**Comment by wxingheng** [comment]
@Ovilia   非常感谢😀，以通过SVG 模式渲染，成功解决问题。在低版本客户端中用SVG渲染方式可以达到更好的效果。

**Comment by Ovilia** [comment]
是的，安卓机上 SVG 的性能也高很多~
