### ISSUE TITLE
bmap中使用styleJson进行自定义地图样式，地图无法正常显示

### ISSUE THREAD

**Issue by Lost-Kun** [apache/incubator-echarts#10579]
### Version
4.2.1

### Steps to reproduce
bmap: {
  mapStyle: {
    styleJson: [...]
  }
}

### What is expected?
产生自定义主题的地图

### What is actually happening?
地图消失，无法正常显示

---
删除styleJson选项则可以正常显示默认样式地图

**Comment by Ovilia** [comment]
请提供可复现的例子。另外，我没有在[文档](https://github.com/apache/incubator-echarts/tree/master/extension/bmap)中找到 `styleJson` 相关的，请问是在哪里看到的？

**Comment by tkamkb** [comment]
请问这个问题解决了吗 我也有这样的问题

**Comment by afetmin** [comment]
我也是这个问题

**Comment by Ovilia** [comment]
@tkamkb @afetmin 可以提供一个例子吗？

**Comment by afetmin** [comment]
@Ovilia 你可以到 [百度地图开放平台](http://lbsyun.baidu.com/index.php?title=jspopular3.0/guide/custom)

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/en/index.html#chart-type-map 这几个例子都是可以的

**Comment by Lost-Kun** [comment]
> https://echarts.apache.org/examples/en/index.html#chart-type-map 这几个例子都是可以的

我这边原因是没有发送referrer，导致getscript获取失败吧

**Comment by youyiying** [comment]
> > https://echarts.apache.org/examples/en/index.html#chart-type-map 这几个例子都是可以的
> 
> 我这边是没有发送referrer造成的，导致getscript代码中获取地图片段失败

使用IONIC打包App也是因为没有Referer导致跳转到error.html,请问现在有解决方案吗？

**Comment by Lost-Kun** [comment]
> > > https://echarts.apache.org/examples/en/index.html#chart-type-map 这几个例子都是可以的
> > 
> > 
> > 我这边是没有发送referrer造成的，导致getscript代码中获取地图片段失败
> 
> 使用IONIC打包App也是因为没有Referer导致跳转到error.html,请问现在有解决方案吗？
我这边是网页，直接取消屏蔽referrer。你这种情况我不太清楚，或许可以尝试伪造referrer或者使用服务端AK
