### ISSUE TITLE
Examples are not loading for English version

### ISSUE THREAD

**Issue by dileepyelleti** [apache/incubator-echarts#10587]
### Version
4.2.1

### Reproduction link
[https://ecomfe.github.io/echarts-examples/public/index.html](https://ecomfe.github.io/echarts-examples/public/index.html)

### Steps to reproduce
Examples are not opening saying site can't be reached.
https://ecomfe.github.io/echarts-examples/public/index.html

### What is expected?
Should load examples page

### What is actually happening?
Examples are not opening saying site can't be reached.
https://ecomfe.github.io/echarts-examples/public/index.html

**Comment by Ovilia** [comment]
Sorry, the website is under updating.

**Comment by Ovilia** [comment]
It has been fixed now. Please visit https://echarts.apache.org/examples/en/index.html.

**Comment by dileepyelleti** [comment]
Thank you. Examples are opening fine now.
But inline iframe examples in tutorials are not loading with 404 not found. For example graphs in https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Get%20Started%20with%20ECharts%20in%205%20minutes
