### ISSUE TITLE
Incorrect URL path breaking demo page

### ISSUE THREAD

**Issue by JasonKeirstead** [apache/incubator-echarts#10589]
### Version
4.2.1

### Reproduction link
[http://echarts.apache.org/examples/en/index.html#chart-type-graph](http://echarts.apache.org/examples/en/index.html#chart-type-graph)

### Steps to reproduce
Click on any of the demo charts in the "Graph" section. None load.

### What is expected?
The demo should load

### What is actually happening?
The demo does not load because the relative paths in the demos are incorrect, and thus returning 404 errors.

An example incorrect path:

$.get('data/asset/data/les-miserables.gexf', function (xml) {

The correct path:

$.get('../data/asset/data/les-miserables.gexf', function (xml) {

**Comment by Ovilia** [comment]
Thanks for reporting. We are working on it.

**Comment by Ovilia** [comment]
It should work now. Please make sure using HTTPS instead of HTTP.
https://echarts.apache.org/examples/en/editor.html?c=graph
