### ISSUE TITLE
Cursor setting in graph not working

### ISSUE THREAD

**Issue by topvis** [apache/incubator-echarts#10582]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xfSxInuEWv&v=1](https://gallery.echartsjs.com/editor.html?c=xfSxInuEWv&v=1)

### Steps to reproduce
Add cursor: 'wait' in option
```cursor: 'wait',```

### What is expected?
Expect 'wait' cursor when hovering over the nodes and edges.

### What is actually happening?
the cursor is still the default 'pointer'.

The same issue was reported in #7764 . It still exists in the latest version 4.2.1.

**Comment by susiwen8** [comment]
Actually, It's been fixed 8 months ago
https://github.com/apache/incubator-echarts/blob/master/src/chart/helper/Symbol.js#L158
Maybe you need to build Echarts from source code

**Comment by susiwen8** [comment]
4.2.1 didn't include this fix. I don't know why.

**Comment by Ovilia** [comment]
I tested. The fix is included in the source code of master branch but not in `dist`, which is 4.2.1. It will be included in the next release.
