### ISSUE TITLE
Problem with dynamic multi line chart based on Json data

### ISSUE THREAD

**Issue by dileepyelleti** [apache/incubator-echarts#10592]
### Version
4.2.1

### Steps to reproduce
I am trying to plot time line chart with multiple lines (number of lines is dynamic based on Json data). I am getting Json data as mentioned. I would like to have each line plotted for each product. Is it possible with current data structure? If not how should I convert data so that echarts supports.

[
{date: "2019-05-21 00:00:00 UTC", value: 100, product: 'p1'},
{date: "2019-05-21 00:00:00 UTC", value: 50, product: 'p2'},
{date: "2019-05-19 00:00:00 UTC", value: 200, product: 'p3'},
{date: "2019-05-18 00:00:00 UTC", value: 70, product: 'p1'},
{date: "2019-05-18 00:00:00 UTC", value: 125, product: 'p2'},
{date: "2019-05-18 00:00:00 UTC", value: 55, product: 'p3'}
]

**Comment by Ovilia** [comment]
You can use [dataset](https://echarts.apache.org/en/option.html#dataset). Please refer to the document.

**Comment by dileepyelleti** [comment]
@Ovilia 
As per dataset documentation I need to convert above data to below format to plot in line chart for different products with time on x axis
dataset = {
dimensions: ['date', 'p1Value', 'p2Value', 'p3Value']
[
{date: "2019-05-21 00:00:00 UTC", p1Value: 100, p2Value: 50},
{date: "2019-05-19 00:00:00 UTC", p3Value: 200},
{date: "2019-05-18 00:00:00 UTC", p1value: 70, p2Value: 125, p3Value: 55}
]
}

But problem is data is dynamic and there might not be value for all products at particular time (19th only p3 has data). So for such nodes tooltip is showing remaining values as empty. Ideally it should not show empty values if there is no point on line chart.
Ex: If p3Value is turned off from legend and there is no point on remaining lines at 2019-05-19. But by hovering it is showing tooltip at 2019-05-19 with empty values.

**Comment by Ovilia** [comment]
How about using `dimensions` as `['date', 'group']`, in which `group` value can be `'p1Value'`, `'p2Value'`, or `'p3Value'`. And use visual map to use different color or other things to note different values.

**Comment by dileepyelleti** [comment]
@Ovilia 
By the way you suggested is it possible to chart different lines for different products(One line for p1Values other for p2Values)

**Comment by Ovilia** [comment]
Then you should probably use data as
```
[
  ['p1Data', 'p2Data', 'p3Data'],
  [1, '-', '-'],
  ['-', 3, '-']
]
```
`'-'` stands for no data.
