### ISSUE TITLE
examples and english language in documentation is not working

### ISSUE THREAD

**Issue by Nilegfx** [apache/incubator-echarts#10599]
### Version
4.2.1

### Reproduction link
[https://ecomfe.github.io/echarts-examples/public/](https://ecomfe.github.io/echarts-examples/public/)

### Steps to reproduce
visit https://ecomfe.github.io/echarts-examples/public/

### What is expected?
examples shown correctly

### What is actually happening?
all examples are broken.

**Comment by cuijian-dexter** [comment]
You can visit the following address：https://echarts.apache.org/examples/en/index.html

**Comment by sxmpasch** [comment]
@cuijian-dexter: Take a look at e.g.
https://echarts.apache.org/en/tutorial.html#Rich%20Text
There, you can see in the Chrome console: "Uncaught TypeError: Cannot read property 'editDemo' of undefined" (view.js)
It seems, in view.js, there is a variable called "lang" containing the language-specific button texts (e.g. lang.en.editDemo). The code in view.js tries to access "lang.editDemo" without language selection.
You could use e.g. 
var langInfo = { ... }; 
var lang=langInfo[currentLanguage];
...

**Comment by Ovilia** [comment]
Please see the demos [here](https://echarts.apache.org/examples/en/index.html). https://ecomfe.github.io/echarts-examples/public/ will be fixed and redirect to that later.

**Comment by sxmpasch** [comment]
It seems this is still work in progress. If you look at e.g. https://echarts.apache.org/en/tutorial.html#Dataset
the charts are not working:
1. Chinese button labels
2. dynamic data load uses a ecomfe.github.io link which is getting a 404 response (not found)...

**Comment by Ovilia** [comment]
@sxmpasch It has been fixed now. Please visit https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE
Note that the Chinese link is not exactly as English one because it reads the title of the page, and the Chinese title is no the same with the English one.
