### ISSUE TITLE
怎么获取当前柱状图的颜色？

### ISSUE THREAD

**Issue by dousee** [apache/incubator-echarts#10596]
### What problem does this feature solve?
我用一系列数据datas，生成echarts对象chart。
再用datas画传统的表格table，我需要在table中标识最大值，并且保证背景颜色跟chart当前柱子颜色一致。

### What does the proposed API look like?
取背景颜色 chart.getBackgroundColor(seriesIndex)
取字体颜色 chart.getTextColor(seriesIndex)

**Comment by cuijian-dexter** [comment]
`myChart.getOption().color` is an Array type.This is assigned in a sequential loop.
