### ISSUE TITLE
Total Canvas size exceeds the maximum limit in iOS

### ISSUE THREAD

**Issue by YogeshJC** [apache/incubator-echarts#10593]
### Version
4.0.0

### Steps to reproduce
We have a dashboard of which displays 4 pie charts. We have the option to toggle to expand each chart to take up the whole area of dashboard or collapse to the dashboard view. 

It seems that upon toggling the charts exactly 10 times, we get an error called total canvas size exceeds maximum limit on iPad. 
This also happens when you change the orientation of the device multiple times with the dashboard on. 

### What is expected?
Charts should be loaded without any errors.

### What is actually happening?
Charts are not loaded. 
Error is thrown 
Total canvas memory use exceeds the maximum limit (224 MB).
"TypeError: null is not an object (evaluating 'this.ctx.dpr = this.dpr')"

---
I have tried to clear the canvas memory using the clearRect method  and using the dispose method to destroy the chart object. 
Is there anything else that can be done from eCharts side to mitigate the memory leak which is caused when the device orientation is changed in iOS 12 devices.

**Comment by Ovilia** [comment]
Can you provide a demo at https://jsfiddle.net/ovilia/n6xc4df3/ ?

**Comment by YogeshJC** [comment]
Added a Gif of the error.

[
![CanvasError](https://user-images.githubusercontent.com/16590453/58852384-00f80400-86b4-11e9-9756-e15da825c5f4.gif)
](url)

**Comment by Ovilia** [comment]
I cannot tell without code. Basically, you have to provide the code where you set the resize logic.

**Comment by YogeshJC** [comment]
```
    window.onresize = function () { 
        _chartModels.map(function(chart){
            if(chart && chart.clearView){
                chart.clearView();
            }
        });
    };

    clearView() {
        this.view.disposeChart();
    }
    disposeChart() {
	_private(this)._chart && _private(this)._chart.dispose();
    }
```

Here `_private(this)` refers to the eCharts object

**Comment by Ovilia** [comment]
Have you tried adding `console.log` to `disposeChart` to make sure it has been called? Maybe the DOM element is removed before it is called. And you should set `_private(this)._chart = null` after disposing.
You may probably not need to dispose these charts. You can call `chart.resize()` to resize them according to container size.

**Comment by YogeshJC** [comment]
```
refreshView() {
    let _privateMembers = _private(this);
    if (this.chartModule) {
        _privateMembers._chartContainer = _privateMembers._layoutManager.getChartCanvasContainer();
        if (_privateMembers._chart) {
            //_privateMembers._chart.dispose();
            _privateMembers._chart.resize();
        } else {
            _privateMembers._chart = this.chartModule.init(_privateMembers._chartContainer, 
                this.model.defaultProperties.theme.name);
            this.model.beforeDraw();
            this.setOption();
	}
    }
}
```

I called the refreshView() method on the resize of the charts(Orientation Change).  As you suggested the I removed dispose and changed it to resize. 
I still notice the error message thrown when the orientation is changed.

**Comment by Ovilia** [comment]
Not enough information to know what's going on.
I'd suggest you make a minimum demo on jsfiddle.

**Comment by YogeshJC** [comment]
Hi Ovilia, I found out there was a memory leak in our code. 
This issue can be closed. Thank you for your time.
