### ISSUE TITLE
日历饼图（calendar-pie）自适应显示异常

### ISSUE THREAD

**Issue by whd3365** [apache/incubator-echarts#10601]
### Version
4.2.1

### Steps to reproduce
官方案例在script末尾添加window.onresize = myChart.resize;
修改浏览器窗口大小

### What is expected?
图标根据浏览器宽高自适应

### What is actually happening?
日历表格可以自适应，饼图不行

**Comment by Ovilia** [comment]
这个例子并没有设计成响应式的，如果想改进的话，欢迎在 https://github.com/ecomfe/echarts-examples/blob/gh-pages/public/data/calendar-pie.js 项目提 PR。
