### ISSUE TITLE
Echarts pie图 百分比精确度

### ISSUE THREAD

**Issue by yualwang** [apache/incubator-echarts#10616]
### Version
4.2.1

### Steps to reproduce
在基本的pie图中使用数据：
data:[
                {value:1324, name:'直接访问'},
                {value:19085, name:'邮件营销'},
                {value:3950, name:'联盟广告'}
            ]
使用数据
data:[
                {value:1324, name:'直接访问'},
                {value:19086, name:'邮件营销'},
                {value:3950, name:'联盟广告'}   
            ]

### What is expected?
两次结果直接访问所占比例为5.44%

### What is actually happening?
第一组直接访问所占比例为5.43%
第二组直接访问所占比例为5.44%

---
具体的百分比计算方式，需要展示各组数据所占百分比

**Comment by Ovilia** [comment]
看一下这个 issue 是不是能解决你的问题 https://github.com/apache/incubator-echarts/issues/10400
