### ISSUE TITLE
Hover animation for series

### ISSUE THREAD

**Issue by prathapjayaraj** [apache/incubator-echarts#10614]
### Version
4.2.1

### Steps to reproduce
1. Create line chart with a marker like

### What is expected?
Hover the marker line in the chart. it gets highlighted. Same way while hovering the echart series, I'm expecting the entire series highlighted .

### What is actually happening?
Only the plots get animated, not the entire line chart series

**Comment by Ovilia** [comment]
You can listen to hover events by `chart.on('mouseover', function(n) { ...})` and use setOption to update style in callback function. See https://echarts.apache.org/en/api.html#events.Mouse%20events.mouseover for more information.

**Comment by prathapjayaraj** [comment]
The event is triggered only in the data points not in the hovering the series lines. I have attached the file. Please rename to html and hover the data points to see the event gets triggered. But I want the same event to be triggered even hovering the series line.

[multiple-x-axis.html.txt](https://github.com/apache/incubator-echarts/files/3253944/multiple-x-axis.html.txt)

**Comment by MINDoSOFT** [comment]
Hi there @prathapjayaraj ,

please use jsfiddle when uploading examples. It is really time saving!
I have added your code in the following jsfiddle
https://jsfiddle.net/hoynve9m/1/

**Comment by Ovilia** [comment]
I don't think ECharts supports highlight the line.

**Comment by renwenci** [comment]
anyone has a solution ? also encounter the same problem

**Comment by nouman0320** [comment]
Is there any update if this feature is going to be implemented?

**Comment by JJZolper** [comment]
> I don't think ECharts supports highlight the line.

Why not? My client needs this feature and I'm handicapped.

**Comment by susiwen8** [comment]
@JJZolper I think 5.0 support this feature now cc @pissang

**Comment by JJZolper** [comment]
Great, I see that when I hover over the line the animation on the line emboldens the line.

Maybe I need a new ticket but unlike the scatter graph shown in my fiddle I do not get an event when I hover over the line: https://jsfiddle.net/JJZolper/10q3nyk8/21/
