### ISSUE TITLE
PictorialBar example image path bug

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/incubator-echarts#10617]
### Version
4.2.1

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=pictorialBar-hill](https://echarts.apache.org/examples/zh/editor.html?c=pictorialBar-hill)

### Steps to reproduce
Hello there, I see that the images used in the specific example have the wrong path.
Changing the paths to 
symbol: 'image://../data/asset/img/hill-Qomolangma.png',
symbol: 'image://../data/asset/img/hill-Kilimanjaro.png',
fixes the example.

### What is expected?
To see the mountain images in the example.

### What is actually happening?
The mountains are not shown because 

Failed to load resource: the server responded with a status of 404 () 

exception occurs.

**Comment by Ovilia** [comment]
@MINDoSOFT Thanks for the report. It has been fixed now.
