### ISSUE TITLE
VisualMap 修改数据项颜色，显示问题

### ISSUE THREAD

**Issue by Alshley** [apache/incubator-echarts#10626]
### Version
4.2.1

### Steps to reproduce
Echarts series custom图，在ToolBox.features中添加MyAdd增加数据项工具，在ToolTip提示框增加修改数据项信息功能，VisualMap的color映射到数据项的“name”维度。当添加数据项时，都正常渲染并显示，当添加一项数据并修改该数据的"name"后（修改数据其他维度不影响），再添加一项数据，该数据存在但不显示图形。当连续添加几项数据后，再修改某一项数据“name”维度的值，该数据之后的数据都存在但不显示图形。在编辑数据项“name”值获取一种颜色之后，鼠标滑过该数据项，数据项的颜色变换新增加数据项时设定的颜色。
大家遇到过类似问题吗？求解答~

### What is expected?
1.添加数据项并编辑后，不影响其他数据项；
2.修改数据项颜色后，鼠标滑过，颜色不会变回原来的

### What is actually happening?
1.添加数据项并编辑后，会影响该数据之后的所有数据不显示；
2.修改过的数据项颜色，在鼠标滑过后会变回最初添加时的颜色

**Comment by Ovilia** [comment]
请提供一个可复现的例子 https://gallery.echartsjs.com/editor.html ，并且用更简单的方法（比如图片）表述你想要的效果和现在的问题
