### ISSUE TITLE
自定义系列图表放大后背景异常

### ISSUE THREAD

**Issue by qcasxy** [apache/incubator-echarts#10627]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=custom-profile](https://www.echartsjs.com/examples/editor.html?c=custom-profile)

### Steps to reproduce
官方示例中将第3行dataCount变量设置为1000后（模拟大数据情况）点击运行。
图表正常显示，放大图表，左右滑动。
此时背景异常，但是各个图表块显示正常。

### What is expected?
背景应该为空白的

### What is actually happening?
背景显示为图表初次显示时的“截图状态”（不知道是否可以理解为画布未清空）

---
数据点较少时没问题，但当数据量达到上千（999都没问题）就会出现该问题

**Comment by Ovilia** [comment]
怀疑是自定义图表对 dataZoom 的支持不是很好

**Comment by qcasxy** [comment]
> 怀疑是自定义图表对dataZoom的支持不是很好

那有没有什么灿办法可以临时解决一下这个问题。比如说修改某个参数的默认值，因为我发现1000个数据点这个规模是个临界点，当数据量小于1000的时候从未出现过这样的问题 但是当数据量一旦大于等于1000就一定会出现这种问题。

**Comment by Ovilia** [comment]
这个例子的作者应该是 @100pah ，可否回答一下？

**Comment by trikunai** [comment]
hi, any update on this bug?

i am also having this weird bug, hope it is fixed soon!

**Comment by qcasxy** [comment]
设置series时根据Y轴的分类创建多个系列可以解决该问题。
```language
series: [{
    type: 'custom',
    name: 'name1',
    ...
},{
    type: 'custom',
    name: 'name2',
    ...
},
...]
```

**Comment by trikunai** [comment]
@qcasxy thanks, but i can not display your solution in a fiddle... can you share a full code example? over a jsfidle like this https://www.echartsjs.com/examples/editor.html?c=custom-profile

thanks!

**Comment by qcasxy** [comment]
> @qcasxy thanks, but i can not display your solution in a fiddle... can you share a full code example? over a jsfidle like this https://www.echartsjs.com/examples/editor.html?c=custom-profile
> 
> thanks!

You can take a look at the source code of my Demo.(http://file.hence.cn/szgc/StatusChart.html)
The focus is on line 180, setting the series. You need to group the data into multiple series by category.
