### ISSUE TITLE
tab导致echarts的height和width不正确

### ISSUE THREAD

**Issue by dousee163** [apache/incubator-echarts#10624]
### Version
4.0.4

### Steps to reproduce
1.有两个botstrap tab， tab1和tab2，tab1里面有chart1高度400px宽度400px， tab2里面有chart2高度400px宽度400px
2.页面初始化的时候，tab1是active的，这时候显示chart1，宽度高度都很正常
3.这时候chart2的height是100px，width是0px，而不是我事先设置好的400px
4.切换到tab2，chart2显示成非常小，即高度100px
5.我调用resize，重新render一次，能够达到400*400

### What is expected?
最好的效果是 tab隐藏的时候要实际的大小，而不是100*0，这样切换tab的时候不会有从小到大的动画效果

### What is actually happening?
chart2显示成非常小，即高度100px

---
由于之前的issue被close了，所以重新提一遍

**Comment by Ovilia** [comment]
当容器大小变化后，请调用 `chart.resize()`

**Comment by dousee163** [comment]
> 当容器大小变化后，请调用 `chart.resize()`

可能我表达的不够清楚，我是调用resize了，只是chart从0开始重新render一次。
即使是重新render，是不是应该从之前的size变化啊？现在是从100*0开始变化，之前的size没有保存住

**Comment by monkey01127** [comment]
我也遇到了，同样的问题，请问是怎么解决的？
