### ISSUE TITLE
官网例子里的地图底图没了

### ISSUE THREAD

**Issue by RoronoaZoro325** [apache/incubator-echarts#10630]
### Version
4.0.4

### Reproduction link
[https://echarts.baidu.com/examples/editor.html?c=map-polygon&theme=dark](https://echarts.baidu.com/examples/editor.html?c=map-polygon&theme=dark)

### Steps to reproduce
打开链接

### What is expected?
有地图

### What is actually happening?
无地图

---
。。。

**Comment by Ovilia** [comment]
已修复，请在 https://echarts.apache.org/examples/en/editor.html?c=map-polygon&theme=dark 查看。echarts.baidu.com 的域名将在稍后迁移到 apache 域名。
