### ISSUE TITLE
npm install error after cloning incubator-echarts by git

### ISSUE THREAD

**Issue by yingwang2** [apache/incubator-echarts#10638]
### Version
4.2.1

### Steps to reproduce
System: MacOs 10.14

npm version: 6.9.0

Steps:
1. Fork incubator-echarts
2. In my local computer terminal, run "git clone https://github.com/mygitname/incubator-echarts.git"
3. cd "incubator-echarts" directory
4. run "npm install"

Error occured:
ENOENT: no such file or directory, rename '\~/incubator-echarts/node_modules/.staging/zrender-18a9b0d0/node_modules/@babel/code-frame' -> '~/incubator-echarts/node_modules/.staging/@babel/code-frame-9fc56fe7

### What is expected?
Although this error can be solved by deleting the package-lock.json file, is it possible to avoid this error?

### What is actually happening?
I fixed the error by: 

1. delete package-lock.json
2. run "npm install"

**Comment by Ovilia** [comment]
Did you have `zrender` installed at the same directory with `incubator-echarts`?

**Comment by yingwang2** [comment]
> Did you have `zrender` installed at the same directory with `incubator-echarts`?

Thanks. Running "npm install zrender" first and then "npm install" can fix the error.

I followed instruction in this file, https://github.com/apache/incubator-echarts/blob/master/.github/CONTRIBUTING.md. Maybe it's better to indicate "npm install zrender first" in this file.

**Comment by Ovilia** [comment]
Have you tried with cloning echarts and zrender without forking, that is, `git clone git@github.com:apache/incubator-echarts.git`?

**Comment by yingwang2** [comment]
> Have you tried with cloning echarts and zrender without forking, that is, `git clone git@github.com:apache/incubator-echarts.git`?

Just tried. Cloned zrender locally by `git clone git@github.com:ecomfe/zrender.git` in "~/workspace/zrender", and cloned echarts locally by `git clone git@github.com:apache/incubator-echarts.git` in "\~/workspace/echarts".

The same error occurred.

**Comment by chfw** [comment]
Update package-lock.json?

**Comment by yingwang2** [comment]
> Update package-lock.json?

I cloned the latest incubator-echarts, the package-lock.json should be updated. I also compared my local file with the git one, and they're the same.

**Comment by chfw** [comment]
what I am saying is: package-lock.json in the repo may have been updated.

**Comment by yingwang2** [comment]
> what I am saying is: package-lock.json in the repo may have been updated.

Do you mean this file? https://github.com/apache/incubator-echarts/blob/master/package-lock.json
If so, yes, I am using the latest one.

**Comment by Ovilia** [comment]
Not quite sure what's the problem here. Wait for someone else to help.

**Comment by yingwang2** [comment]
> Not quite sure what's the problem here. Wait for someone else to help.

Sorry if this is confusing. I just start to look at this project. What I'm trying to say is:
By following the instruction in https://github.com/apache/incubator-echarts/blob/master/.github/CONTRIBUTING.md, the error is shown when running (Step 2):
```
cd ~/workspace/echarts
npm install
```
Since zrender is one of the dependencies, why it couldn't be installed after running "npm install"?

**Comment by chfw** [comment]
echarts core team have left it out on purpose, because they do it manually. For development purpose, they would like to install latest and development version zrender.

**Comment by yingwang2** [comment]
> echarts core team have left it out on purpose, because they do it manually. For development purpose, they would like to install latest and development version zrender.

This makes sense, thanks for the clarification!

**Comment by susiwen8** [comment]
If memory serve me, just run 'npm install zrender' at root directory, then all set. 
If you want to build Echarts
'cd build/'
'node build.js'

**Comment by yingwang2** [comment]
> If memory serve me, just run 'npm install zrender' at root directory, then all set.
> If you want to build Echarts
> 'cd build/'
> 'node build.js'

Thanks for making this clear.
