### ISSUE TITLE
https://gallery.echartsjs.com/ 打不开

### ISSUE THREAD

**Issue by zhouxin314** [apache/incubator-echarts#10645]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/](https://gallery.echartsjs.com/)

### Steps to reproduce
Request URL: https://gallery.echartsjs.com/
Request Method: GET
Status Code: 302 Found
Remote Address: 111.206.37.147:443
Referrer Policy: no-referrer-when-downgrade

### What is expected?
正常访问

### What is actually happening?
跳转至贴吧 404 页面

**Comment by wuyinxing** [comment]
gallery 示例社区打不开，报错

https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all   

![image](https://user-images.githubusercontent.com/17865784/59196491-6753b980-8bc1-11e9-8eb6-08ea0be2e145.png)

**Comment by Ovilia** [comment]
谢谢反馈，目前大部分功能已恢复，只有截图还在修复中。
