### ISSUE TITLE
如何将柱状图x轴 刻度标签放在轴刻度下

### ISSUE THREAD

**Issue by mmmaomao21** [apache/incubator-echarts#10642]
### What problem does this feature solve?
怎么样能在柱状图type为category的情况下，使柱状图x轴 刻度标签放在轴刻度下。主要是为了表现在0到100之间的数据，如果放在柱状图的正下方，容易让人理解为当x轴值为100的时候的数据

### What does the proposed API look like?
期望：100放在刻度下方，而不是放在柱状图正下方
![image](https://user-images.githubusercontent.com/23095457/59180629-02379e00-8b98-11e9-8aed-8e5c9f203b48.png)

现有配置能做到吗？

**Comment by Ovilia** [comment]
可以参考 https://echarts.apache.org/examples/zh/editor.html?c=bar-histogram 需要自己写一种自定义系列
