### ISSUE TITLE
geo3d怎么和bmap结合，还是用geo3d必须下载地图数据

### ISSUE THREAD

**Issue by Carolineliu** [apache/incubator-echarts#10648]
### What problem does this feature solve?
geo3d需要引入map,但是现在不允许下载数据了，可以用bmap代替吗

**Comment by Ovilia** [comment]
只是官网没有下载入口，还是可以在这里找到：https://github.com/apache/incubator-echarts/tree/master/map/js

**Comment by Carolineliu** [comment]
> 只是官网没有下载入口，还是可以在这里找到：https://github.com/apache/incubator-echarts/tree/master/map/js

不可以结合bmap使用吗
