### ISSUE TITLE
Can I use the dataZoom or Timeline in Surface diagram?

### ISSUE THREAD

**Issue by lirumeng** [apache/incubator-echarts#10657]
### Version
4.2.1

### Steps to reproduce
null

### What is expected?
Achieve similar effect in 2d

### What is actually happening?
unrealized

you can click this link to see: 
https://gallery.echartsjs.com/editor.html?c=xYz_Kl4U5r&v=3

**Comment by Ovilia** [comment]
I can't see https://gallery.echartsjs.com/editor.html?c=xYz_Kl4U5r&v=3 . Please check if it's visible to all (click comment icon on the right side of the navbar, click "修改").
