### ISSUE TITLE
Inconstant dynamic interval for category axis

### ISSUE THREAD

**Issue by amichaud-ingtech** [apache/incubator-echarts#10663]
### Version
4.2.1

### Reproduction link
https://jsfiddle.net/1xhnzojf/4/ (idk why jquery dont work here)

### Steps to reproduce
Using jquery ".on('resize', ...)" to call the resize method of the chart, load the page with all the necessary width. Resize the window to change the interval of the x axis to 1 for 2. Resize the window to his original width.

### What is expected?
After the seconds resize, the interval should update to 1 for 1

### What is actually happening?
After the seconds resize, the interval stay with 1 for 2 despite it has the space to be 1 for 1

---
You can see the result in the screen shot https://i.imgur.com/Hz2wgJQ.png

**Comment by Ovilia** [comment]
Sorry, I didn't see which part of your code has the logic of making "the interval of the x axis to 1 for 2"
