### ISSUE TITLE
IOS 一个页面渲染多个 折线图时报错：TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')

### ISSUE THREAD

**Issue by WangSuwen** [apache/incubator-echarts#10674]
### Version
4.1.0-release

### Steps to reproduce
无

### What is expected?
能够同时正常渲染多个 折线图

### What is actually happening?
不能正常渲染

---
我们现在 是在 移动端用Vue框架实现的H5页面，现在一个页面有两个Tab，每个Tab需要同时渲染多个折线图，然后在来回切换Tab时，会报错：TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr') 。 导致折线图无法渲染。麻烦官方帮忙指导一下O(∩_∩)O谢谢。目前比较紧急🙏。

**Comment by Ovilia** [comment]
这可能是因为找不到 DOM 节点引起的。
可以试试离开 tab 的时候，dispose 掉，chart 实例设为 null；进入 tab 的时候重新 init 图表。
