### ISSUE TITLE
Gallery社区无法正常浏览

### ISSUE THREAD

**Issue by WQone** [apache/incubator-echarts#10672]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all)

### Steps to reproduce
打开Gallery网址：https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all

### What is expected?
希望网址上的图片和资源可以正常浏览和加载

### What is actually happening?
无法加载，大部分图片404错误

**Comment by WQone** [comment]
![image](https://user-images.githubusercontent.com/25738656/59490343-0248de00-8eb7-11e9-9e54-050c6410fbcc.png)
Gallery社区为我们提供的大量示例能帮助我们快速开发，希望能得到尽快修复

**Comment by Ovilia** [comment]
目前已恢复访问频率高的图片，剩下的在持续恢复中。对造成的不便表示抱歉！
