### ISSUE TITLE
echarts 如何实时抓取屏幕base64

### ISSUE THREAD

**Issue by jesoonluo** [apache/incubator-echarts#10687]
### What problem does this feature solve?
实时获取屏幕base64，跟随legend等改变

### What does the proposed API look like?
可以快速获取当前屏幕echarts的base64

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/api.html#echartsInstance.getDataURL

**Comment by jesoonluo** [comment]
@Ovilia 看到了有个getConnectedDataURL,对不起，我有罪。。。

**Comment by Ovilia** [comment]
那个是联动图表用来输出图片的，你用 getDataURL 就好~
