### ISSUE TITLE
柱状图点击以后实现，shadow的效果

### ISSUE THREAD

**Issue by Gamehu** [apache/incubator-echarts#10685]
### Version
4.2.1

### Steps to reproduce
option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220],
             //该处为点击事件
                itemStyle:{
                        normal: {
                            color: function(params) {
                                var key = params.name.replace(/<\/?.+?>/g,"").replace(/[\r\n]/g, "");
                                if(key  == value){
                                    return "#FE8463";
                                }else{
                                    return "#4ABACE";
                                }
                            }
                        }
                    }
        },
       
    ]
};

  myChart.on('click', function eConfig(param){
                value=param.name;
                let option = myChart.getOption();
                myChart.dispatchAction({
                    type: 'showTip'
                });
              
                myChart.setOption(option);
  });
  

### What is expected?
期望点击之后，点击所在的柱状图出现shadow，跟tooltip的axisPointer type=shadow效果一样，

### What is actually happening?
没有出现

---
目的是为了，当某个柱状图的值特别小时，无法通过肉眼判断是否选中了柱状图，所以想通过添加shadow的形式，告诉客户，选中了改柱状图

**Comment by Ovilia** [comment]
正则代码那边有语法报错，请检查。
一种更简单的方法：https://gallery.echartsjs.com/editor.html?c=xFNoCnePRv&v=1

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/59581753-71694100-9108-11e9-9a62-63d9aa6ecd40.png)
你好 我是想实现点击后也有鼠标移上去的这种效果

**Comment by Ovilia** [comment]
不太懂，现在不是也有吗？

**Comment by Gamehu** [comment]
现在试鼠标移上去有，但是点击之后没有shadow

**Comment by Ovilia** [comment]
<img width="658" alt="屏幕快照 2019-06-18 11 27 34" src="https://user-images.githubusercontent.com/779050/59651354-1c870280-91bc-11e9-94e4-054b9719b757.png">
这不是 shadow 吗？你想要什么样的效果？

**Comment by Gamehu** [comment]
你好：效果是，点击之后shadow停留，就算鼠标移开也不消失

**Comment by Ovilia** [comment]
你照着我的例子自己想一下怎么修改，道理是类似的

**Comment by emyly** [comment]
> 你照着我的例子自己想一下怎么修改，道理是类似的

想问下最终是怎么实现的，我也有一样的问题，希望点击后，shadow不消失，直到点击下一个柱子shadow才会消失

**Comment by emyly** [comment]
> 

想问下你这边有实现这个点击后柱子背景色一直保持的效果吗
