### ISSUE TITLE
Echarts 4 do not support vnee?

### ISSUE THREAD

**Issue by didiaoshengjianbao** [apache/incubator-echarts#10689]
### What problem does this feature solve?
echarts无法支持韦恩图，我们有什么方法可以基于echart 4 画出韦恩图？

### What does the proposed API look like?
韦恩图

**Comment by Ovilia** [comment]
不支持，但是可以通过自定义系列自己实现，文档在：https://echarts.apache.org/zh/option.html#series-custom
