### ISSUE TITLE
旭日图可否支持类似饼图可设置最小的扇区角度

### ISSUE THREAD

**Issue by lynzz** [apache/incubator-echarts#10702]
### What problem does this feature solve?
扇区值为0或很小时，影响交互，希望能提供一个最小角度显示，如饼图的 minAngle。

### What does the proposed API look like?
旭日图的 label 是有一个 minAngle 配置，但只是小于指定角度不显示文本，
是不是可如饼图那样，提供一个 minAngle 和 minShowLabelAngle

**Comment by susiwen8** [comment]
Relate to https://github.com/apache/incubator-echarts/issues/10414
To support minAngle in sunburst is quite difficult.
