### ISSUE TITLE
Does the heatmap support local incremental rendering? #heatmap

### ISSUE THREAD

**Issue by marlonchiu** [apache/incubator-echarts#10704]
### Version
4.2.0-rc.2

### Steps to reproduce
开发中有这样的一个业务场景：热力图用来标识了一些分析指标，数据是实时增量分析的，通过建立websocket长链接，每次接收收据之后都是把新数据和上一次的数据组合，然后在页面上重新渲染视图，这个渲染过程刚开始是几十毫秒，不怎么影响；待到数据量增大以后目前40分钟以后，渲染一次的时间回达到700毫秒左右，这样就导致页面非常的卡顿。
此外因为是实时分析，页面上有两个ckplayer播放窗口，热力图渲染导致播放器流卡顿延迟很明显，同时如果强制关闭浏览器也是关不掉或者说关闭起来很困难。
请问echarts是否支持增量局部渲染数据，意思就是：已经渲染的数据图就不重新绘制了，只绘制新增加的？

### What is expected?
已经渲染的数据图就不重新绘制了，只绘制新增加的

### What is actually happening?
所有的数据更新视图重新绘制一遍

**Comment by Ovilia** [comment]
不支持
