### ISSUE TITLE
Ability to add additional data to tooltip formatter

### ISSUE THREAD

**Issue by robertjorg** [apache/incubator-echarts#10708]
### What problem does this feature solve?
You can put data in the tooltip formatter for the given data point. On the line graph you seem to only be able to use the name and value like this:

```    formatter: function (params) { return params.value   '<br />'   '('   params.name   ')' }```

It would be nice to have the ability to use data that are not present in the param to display in the tool tip. An example is when the line graph shows the percentage of a numerator and denominator. The tool tip could show the percent, numerator, and denominator (the numerator and denominator come from another array of data)

### What does the proposed API look like?
```   tooltip: {
 formatter: function (params) { return params.value   '<br />'   '('   params.name   ')'   '<br />'   'Numerator: '   this.data.numerator   '<br />'   'Denominator: '   this.data.numerator }
}```

<!-- This issue is generated by echarts-issue-helper. DO NOT REMOVE -->
<!-- This issue is in English. DO NOT REMOVE -->

**Comment by Ovilia** [comment]
Please refer to https://echarts.apache.org/en/option.html#dataset
