### ISSUE TITLE
areaStyle.origin 支持数值配置

### ISSUE THREAD

**Issue by shuihan03** [apache/incubator-echarts#10719]
### Version
4.2.1

### Steps to reproduce
目前只支持，可选值包括 'auto'（默认值）、 'start'、 'end'。

### What is expected?
期望可以配置数值，这样可以实现每条线的区域是一段区间。

### What is actually happening?
实际配置成数值无效

---
此处无法传图片，目前我是修改了源码支持了我的功能。源码里面方法名，getValueStart添加代码片段
  if(!isNaN(valueOrigin)){//temp如果为数字时，按照数字开始绘制区域
        valueStart=valueOrigin;
  }
![image](https://user-images.githubusercontent.com/15643529/60000165-3af66d80-9696-11e9-95ab-ea36a31363cb.png)

**Comment by Ovilia** [comment]
origin 和这个左右的位置没有关系，控制的是填充线条以上还是线条以下。如果想要实现你说的效果（如果我没理解错的话），应该是创建只有中间一段的折线图，然后用 areaStyle 填充。
