### ISSUE TITLE
屏幕发生改变时，如何重新加载graphic中自己画的图形

### ISSUE THREAD

**Issue by 52jc** [apache/incubator-echarts#10714]
### Version
4.2.1

### Steps to reproduce
屏幕大小发生改变时，如何重新加载graphic中自己画的图形

### What is expected?
自己画的图形也随着echarts原来的图表放大，缩小

### What is actually happening?
就算计算好了重新加载也跟echarts原来的图表对应不上

**Comment by Ovilia** [comment]
用百分比形式比如 `'10%'` 表示相对容器的大小

**Comment by 52jc** [comment]
是用react写的，一个页面有多个组件，多个组件里有图表，如果在多个组件里加window.onresize的话会冲突，有的不执行，如果在页面里面写的话，因为有graphic自己画的东西，所以需要往主页面传很多参数，包括在graphic上绑定的函数等，所以想问一下，对于这种情况，有什么更好的办法吗

**Comment by Ovilia** [comment]
应该不是组件响应 onresize，而是外部整体响应一次，然后调组件 resize 方法？
