### ISSUE TITLE
同行正负轴动态数据切换数据替换不完全

### ISSUE THREAD

**Issue by zyj1022** [apache/incubator-echarts#10721]
### Version
4.2.1

### Reproduction link
[http://zyj1022.github.io/demos/react-echarts-packet/](http://zyj1022.github.io/demos/react-echarts-packet/)

### Steps to reproduce
点击数据切换对下拉列表，图例1、图例2、图例3，切换数据
可以发现：由图例1切换到图例2的时候，图例2的数据被图例1的影响了。

业务场景：正负轴展示一条数据，并且希望bar的宽度保持一致宽度（每组数据条数不同，如果要让bar宽度一致，需要填充空数据占位）

### What is expected?
正负同轴数据动态切换可以正常显示数据

### What is actually happening?
旧的数据会影响（类似叠加覆盖部分）新的图表展示

---
经过多方排查，当前解决方案是让所有动态切换数据的数组长度相同。
猜想bug原因：新的图表绘制的时候，旧的数据图表并未销毁或销毁不完全所致。
另：已经在多个其它 react  echarts 库验证此问题及解决方案，非react包装所致。

**Comment by Ovilia** [comment]
setOption 第二个参数传 true 试试 https://echarts.apache.org/zh/api.html#echartsInstance.setOption

**Comment by zyj1022** [comment]
ok，测试了一下，相互覆盖的问题已经解决。thank you！
