### ISSUE TITLE
平行坐标图不支持只有一个轴线的图

### ISSUE THREAD

**Issue by lvybriage** [apache/incubator-echarts#10720]
### Version
4.1.0-release

### Steps to reproduce
parallel的option
```javascript
option = {
    parallelAxis: [
        {dim: 0, name: 'Price'}
    ],
    series: {
        type: 'parallel',
        lineStyle: {
            width: 4
        },
        data: [
            [12.99],
            [9.99],
            [20]
        ]
    }
};
```

### What is expected?
平行坐标图可以支持单轴

### What is actually happening?
平行坐标图暂时不支持单轴图

**Comment by Ovilia** [comment]
只有一个轴的话都没有线，怎么表现数据？

**Comment by lvybriage** [comment]
> 只有一个轴的话都没有线，怎么表现数据？

谢谢回复 :)
我觉得就算只有单条轴，没有可连出的线条，也可以在轴上表现出数据的分布呀。当前如果只有一条轴，render出来的图是有bug的。

**Comment by Ovilia** [comment]
因为现在数据点是不会绘制点的，只有轴和轴之间的线，所以单轴就应该什么都不绘制，当然如果跑不起来的话可能的确是 bug……

**Comment by zhouxin860114** [comment]
把别的轴隐藏了行吗
![image](https://user-images.githubusercontent.com/8022228/60480686-0fd6d400-9cbd-11e9-8a97-cf9a4fc863ee.png)

**Comment by lvybriage** [comment]
@zhouxin860114 不太清楚你的问题是什么，是希望把其他轴隐藏掉吗？好像你已经实现了呀。
