### ISSUE TITLE
矩形树图下钻到第二级，更新数据后图表却回到了第一级。

### ISSUE THREAD

**Issue by Wy38722** [apache/incubator-echarts#10729]
### Version
4.2.1

### Reproduction link
[http://www.smallwhite.work/test/](http://www.smallwhite.work/test/)

### Steps to reproduce
选择第一级第一个“nanana”淡黄色节点，下钻到第二层，然后选择图例（此图例是自己写的）“正常”，改变节点颜色setoption后，结果回到了矩形树突第一级。

### What is expected?
停留在下钻的二级位置

### What is actually happening?
回到了第一级

---
此网页有点点的慢，希望可以多等一下。

**Comment by susiwen8** [comment]
I cannot open you website, please provide options or create a gallery https://gallery.echartsjs.com/editor.html

**Comment by Wy38722** [comment]
Sorry, I changed the Json file, and you can try it again. It should be fine.

**Comment by susiwen8** [comment]
Could you provide options? Coz It really hard to debugger without it......

**Comment by Wy38722** [comment]
> Could you provide options? Coz It really hard to debugger without it......

problem source: https://github.com/Wy38722/treemap-question.git
![image](https://user-images.githubusercontent.com/29934627/60251453-236bee80-98fb-11e9-800d-8bd2c6f7f6bd.png)

**Comment by zhouxin860114** [comment]
用过旭日图的下钻，估计和矩形树图的下钻类似，也是用 setOption 更新图表，下钻状态就消失了
可能是跟这个下钻的实现方式有关… 更新图表时把这个下钻的状态重置了

既然图例都重写了，为什么不把下钻也自己重写一下呢？统一用 setOption 完成，这样就不冲突了

**Comment by zhouxin860114** [comment]
奥，对了，还遇到个更尴尬的情况：
我做过一个 时间轴 + 旭日图 ，当我点了旭日图的下钻后（未返回第一层），时间轴自动切换了，于是上一个时间点的 下钻后的图形，和新一个时间点的 新图形，重叠在一起了 - -b

最后只好不响应鼠标事件了（放弃下钻）。。用了个自定义图例勉强代替
![image](https://user-images.githubusercontent.com/8022228/60479590-f16ed980-9cb8-11e9-81d4-d1a54a6b60e1.png)

**Comment by Wy38722** [comment]
> 奥，对了，还遇到个更尴尬的情况：
> 我做过一个 时间轴 + 旭日图 ，当我点了旭日图的下钻后（未返回第一层），时间轴自动切换了，于是上一个时间点的 下钻后的图形，和新一个时间点的 新图形，重叠在一起了 - -b
> 
> 最后只好不响应鼠标事件了（放弃下钻）。。用了个自定义图例勉强代替
> ![image](https://user-images.githubusercontent.com/8022228/60479590-f16ed980-9cb8-11e9-81d4-d1a54a6b60e1.png)



> 用过旭日图的下钻，估计和矩形树图的下钻类似，也是用 setOption 更新图表，下钻状态就消失了
> 可能是跟这个下钻的实现方式有关… 更新图表时把这个下钻的状态重置了
> 
> 既然图例都重写了，为什么不把下钻也自己重写一下呢？统一用 setOption 完成，这样就不冲突了
tanks
