### ISSUE TITLE
Multiple yAxis how to share zero value

### ISSUE THREAD

**Issue by hhummell81** [apache/incubator-echarts#10735]
### Version
4.2.1

### Steps to reproduce
Create a bar chart with 2 series, one of them with some negative data and the other only positive data, but different scales. I want to have both series sharing the same 0 line.

### What is expected?
I want the zero to be in the same line for both axis

### What is actually happening?
Zero is in a different position in each axis

<img width="365" alt="2019-06-25 15_22_06-Clipboard" src="https://user-images.githubusercontent.com/36505653/60102379-d868a480-975d-11e9-8e1b-fc325831ac22.png">

**Comment by Ovilia** [comment]
Currently, you can set the `min` and `max` for both yAxis, and make sure they are at the same ratio. For example, left yAxis min -10, max 30; right yAxis min -20, max 60.
But I think this should be improved to have a better plan than this.

**Comment by hhummell81** [comment]
@Ovilia Thank you for your answer. Finally is that what I am doing. Closing issue!
