### ISSUE TITLE
Calendar graph example doesn't work

### ISSUE THREAD

**Issue by ruixuel** [apache/incubator-echarts#10736]
### Version
4.2.1

### Steps to reproduce
1. go to page: https://echarts.apache.org/examples/en/editor.html?c=calendar-graph
2. the chart cannot load

### What is expected?
The chart should load

### What is actually happening?
There's error on the page

---
The error occurs in the GraphView.js, line: 184
edge.getGraphicEl() returns undefined

**Comment by Ovilia** [comment]
It works for me. Please check again. If not, please clear the cache.

**Comment by ruixuel** [comment]
It doesn't work for me. I mean the calendar can show, but there's no graph and color showed on the calendar chart. I tried it in different browsers (chrome, safari, firefox, incognito mode) and also clear the cache.
The error is: 
```
editor.js?_v_=1559800464994:1 
TypeError: Cannot read property '__focusNodeAdjacency' of undefined
    at echarts.min.js?_v_=1559800464994:22
    at IL.TL.eachEdge (echarts.min.js?_v_=1559800464994:22)
    at i.render (echarts.min.js?_v_=1559800464994:22)
    at mr.progress (echarts.min.js?_v_=1559800464994:22)
    at vr (echarts.min.js?_v_=1559800464994:22)
    at mr.UI.perform (echarts.min.js?_v_=1559800464994:22)
    at echarts.min.js?_v_=1559800464994:22
    at i.<anonymous> (echarts.min.js?_v_=1559800464994:22)
    at Array.forEach (<anonymous>)
    at d (echarts.min.js?_v_=1559800464994:22)
```

**Comment by yahyavi** [comment]
Hello,
I have the same problem. Please see screenshots below.

![ECharts-Error](https://user-images.githubusercontent.com/1531957/60372331-2aedcf00-99b1-11e9-84e7-28820bc68374.jpg)
![Screen Shot 2019-06-28 at 10 39 51 AM](https://user-images.githubusercontent.com/1531957/60372417-68525c80-99b1-11e9-8dd6-bd91ac78973f.png)

**Comment by Ovilia** [comment]
This seems to be a bug related to timezone. @100pah will have a look at it.

**Comment by yahyavi** [comment]
Thanks. Any idea on when the next release with recent fixes will be released?
