### ISSUE TITLE
Can “treemap” control the direction of shape in ECharts?

### ISSUE THREAD

**Issue by Wy38722** [apache/incubator-echarts#10759]
### Version
4.2.1

### Reproduction link
[https://i.stack.imgur.com/wrxjI.png](https://i.stack.imgur.com/wrxjI.png)

### Steps to reproduce
Can the treemap in ECharts control the direction of the shape, making it more probable in one direction?

### What is expected?
Make sure the rectangle is more in one direction

### What is actually happening?
View link

**Comment by Ovilia** [comment]
I'm afraid this is not possible.
