### ISSUE TITLE
微信小程序 tab切换图表显示不正常

### ISSUE THREAD

**Issue by sldeng** [apache/incubator-echarts#10753]
### Version
4.2.1

### Steps to reproduce
初始化图标时显示正常，切换tab时图表挤一起了

### What is expected?
切换tab能正常显示

### What is actually happening?
切换tab时图表挤一起了

**Comment by sldeng** [comment]
![image](https://user-images.githubusercontent.com/38899368/60246795-0d0d6500-98f2-11e9-9700-c43808e7ba18.png)

**Comment by Ovilia** [comment]
切换 tab 的时候调用一下 chart.resize()

**Comment by sldeng** [comment]
有demo吗


来自 魅族 PRO 6 Plus

-------- 原始邮件 --------
发件人：Ovilia <notifications@github.com>
时间：2019年6月28日 15:58
收件人：apache/incubator-echarts <incubator-echarts@noreply.github.com>
抄送：sldeng <13163374901@163.com>,Author <author@noreply.github.com>
主题：Re: [apache/incubator-echarts] 微信小程序 tab切换图表显示不正常 (#10753)

**Comment by Liuliu73** [comment]
请问问题解决了吗？在小程序里用resize() 貌似不起作用

**Comment by Ovilia** [comment]
@Liuliu73 检查一下在调用 resize 之前宽高是不是正确（比如是不是需要在 nextTick 再 resize），实在不行可以考虑 dispose 再重新 init

**Comment by sldeng** [comment]
是不起作用，高低都为0display为none  我在全局保存下高宽勉强解决了


来自 魅族 PRO 6 Plus

-------- 原始邮件 --------
发件人：Liuliu73 <notifications@github.com>
时间：2019年7月2日 13:59
收件人：apache/incubator-echarts <incubator-echarts@noreply.github.com>
抄送：sldeng <13163374901@163.com>,Author <author@noreply.github.com>
主题：Re: [apache/incubator-echarts] 微信小程序 tab切换图表显示不正常 (#10753)

**Comment by Ovilia** [comment]
高宽都没有的话，应该通过 css 控制小程序代码，这不是 ECharts 的问题

**Comment by sldeng** [comment]
你试过吗
