### ISSUE TITLE
世界地图nameMap转换后有部分国家的label偏移Bug

### ISSUE THREAD

**Issue by DavilF** [apache/incubator-echarts#10765]
### Version
4.2.1

### Steps to reproduce
用world.js，渲染处世界地图，然后用namemap转换成中文；然后鼠标悬浮到以下几个国家（法国，俄罗斯，美国），label文字偏移过于明显Bug

### What is expected?
期望如echart2版本时候，对应国家的label显示在板块的中间位置。

### What is actually happening?
label文字偏移过多，且显示了很多位置，殖民地也被标志，希望只标志主要板块

---
希望label能如chart2版本时候的显示方式。

**Comment by Ovilia** [comment]
同 https://github.com/apache/incubator-echarts/issues/4275#issuecomment-256822819

**Comment by xieyezi** [comment]
同样的版本，同样的bug，请问如何解决？
