### ISSUE TITLE
Echarts中的区域缩放组件dataZoom，能实现拖动滑块，根据范围的大小，去动态请求数据，改变x轴上面的值吗？

### ISSUE THREAD

**Issue by thriver2010** [apache/incubator-echarts#10767]
### What problem does this feature solve?
比如x轴上是时间点，默认显示过来时每天的数据，2019.1.1 -2019.1.2--2019.6.1等等；拖动滑块后，范围变小，动态去请求每小时的数据点，2019.1.1 00:00 --2019.1.1 01:00--2019.1.1 02:00等等。能实现这种功能吗

### What does the proposed API look like?
期望滑动组件，能动态改变x轴上面数据节点值

**Comment by Ovilia** [comment]
可以的，获取 dataZoom 事件：https://echarts.apache.org/zh/api.html#events.datarangeselected
