### ISSUE TITLE
Handle Legend double click event

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/incubator-echarts#10762]
### What problem does this feature solve?
Because we have legends with many items (over 30 items), we would like to have the functionality where a legend item is double clicked, and show just that series. This helps the user save time, because he doesn't have to disable 29 series to focus on a specific series.

### What does the proposed API look like?
Enhance the
https://ecomfe.github.io/echarts-doc/public/en/api.html#events.Mouse%20events.dblclick  
event to respond to the legend area of the chart. 
The componentType can be 'legend' and the name can be the legend item that has been double clicked.

Currently the dblclick responds only in the grid area.

**Comment by deqingli** [comment]
Hi @MINDoSOFT,  we have added `All` and `Inverse` selection button for the legend, which result is this:
![image](https://user-images.githubusercontent.com/13548221/60331749-efaaca80-99c7-11e9-9f55-7b8805e91622.png)
With these, you can quickly show the series you want.

**Comment by deqingli** [comment]
This new feature has already pushed to master branch and will be released in some next version. Anyway, thank you for your suggestion.

**Comment by sudheer9047** [comment]
Is this available in echarts examples ??

**Comment by MINDoSOFT** [comment]
Hi ! I don't know if its available in the examples. But this is the option you must use

https://echarts.apache.org/en/option.html#legend.selector

**Comment by DanielBogenrieder** [comment]
Hey,

is there any specific reason a double click event is not exposed in the legend area?
The buttons are an interesting idea, but require space where space is usually sparse.

Greetings and thanks,
Daniel
