### ISSUE TITLE
饼图的series—> data —> name，当name的值相同时，饼图的颜色是一样的。

### ISSUE THREAD

**Issue by Huangqinyi** [apache/incubator-echarts#10774]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xBTijRd-kz&v=1](https://gallery.echartsjs.com/editor.html?c=xBTijRd-kz&v=1)

### Steps to reproduce
需要实现的效果是希望显示饼图中每部分的百分比值，定义的name是一个变量，而不是固定写明每一部分代表的名字是什么，所以name的值会有相同的情况存在，我们发现当name相同时，饼图的颜色也是一样的。

### What is expected?
当name的值相同时，饼图的颜色也能够区分

### What is actually happening?
当name的值相同时，饼图的颜色是一样的。

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/issues/10225

**Comment by Ovilia** [comment]
请使用不同的 name 给不同的数据，如果要显示为同样的文字，可以通过 [label.formatter](https://echarts.apache.org/zh/option.html#series-pie.label.formatter) 修改显示文字。
