### ISSUE TITLE
饼图的series—> data —> name，当name的值相同时，饼图的颜色是一样的。

### ISSUE THREAD

**Issue by Huangqinyi** [apache/incubator-echarts#10773]
版本为：4.2.1，需要实现的效果是希望显示饼图中每部分的百分比值，定义的name是一个变量，而不是固定写明每一部分代表的名字是什么，所以name的值会有相同的情况存在，我们发现当name相同时，饼图的颜色也是一样的。
效果预览：https://gallery.echartsjs.com/editor.html?c=xBTijRd-kz&v=1

**Comment by zhouxin860114** [comment]
> 版本为：4.2.1，需要实现的效果是希望显示饼图中每部分的百分比值，定义的name是一个变量，而不是固定写明每一部分代表的名字是什么，所以name的值会有相同的情况存在，我们发现当name相同时，饼图的颜色也是一样的。
> 效果预览：https://gallery.echartsjs.com/editor.html?c=xBTijRd-kz&v=1

为啥要让 数据的名称一样呢。。标记 50% 不是应该通过 formatter 设置么
