### ISSUE TITLE
文档中的自定义构建Echarts的export（引入）是否错误

### ISSUE THREAD

**Issue by jxderic** [apache/incubator-echarts#10779]
### Version
4.2.1

### Steps to reproduce
查看文档

### What is expected?
// 引入 echarts 主模块。
import * from 'echarts/src/echarts';
// 引入饼图。
import 'echarts/src/chart/pie';
// 在这个场景下，可以引用 `echarts/src` 或者 `echarts/lib` 下的文件（但是不可混用），
// 参见下方的解释：“引用 `echarts/lib/**` 还是 `echarts/src/**`”。

### What is actually happening?
// 引入 echarts 主模块。
export * from 'echarts/src/echarts';
// 引入饼图。
import 'echarts/src/chart/pie';
// 在这个场景下，可以引用 `echarts/src` 或者 `echarts/lib` 下的文件（但是不可混用），
// 参见下方的解释：“引用 `echarts/lib/**` 还是 `echarts/src/**`”。

**Comment by pissang** [comment]
这个文档里指的是如果要自定义构建的话，需要把 echarts 的这些接口都 export 出去，所以这部分没有问题

**Comment by xingyuehaiqing** [comment]
不太清楚具体怎么使用，需要再明确一下

**Comment by ZENETOM** [comment]
// custom-echarts.js
export * from 'echarts/lib/echarts';

import 'echarts/lib/chart/funnel';

import 'echarts/lib/component/tooltip';
import 'echarts/lib/component/title';
import 'echarts/lib/component/legend';
