### ISSUE TITLE
地图标题在拖动时会抖动

### ISSUE THREAD

**Issue by andygithubchen** [apache/incubator-echarts#10776]
### Version
4.0.4

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=effectScatter-bmap](https://www.echartsjs.com/examples/editor.html?c=effectScatter-bmap)

### Steps to reproduce
https://www.echartsjs.com/examples/editor.html?c=effectScatter-bmap
这个例子里的标题在地图拖动时会抖动，有办法解决吗？

### What is expected?
地图拖动时标题不要抖动

### What is actually happening?
会抖动

**Comment by Ovilia** [comment]
没有，可以考虑不用 title，在 DOM 里自己写

**Comment by andygithubchen** [comment]
emmm..... 好吧 @Ovilia
