### ISSUE TITLE
npm install echarts v4.2.1 在项目中 import 打印看到的版本号是4.1.0

### ISSUE THREAD

**Issue by houjiazong** [apache/incubator-echarts#10784]
### Version
4.2.1

### Steps to reproduce
import echarts from 'echarts/lib/echarts'

console.log(echarts.version)

### What is expected?
4.2.1

### What is actually happening?
4.1.0

**Comment by Ovilia** [comment]
安装的时候是 `npm i echarts@4.2.1` 的吗？

**Comment by houjiazong** [comment]
^4.2.1
dist/echarts 中的 version 是4.2.1，zrender为4.0.6
webpack现在设置了externals，表现正常了
