### ISSUE TITLE
map动画无效

### ISSUE THREAD

**Issue by zhaoxiaoran** [apache/incubator-echarts#10782]
### Version
4.1.0-release

### Steps to reproduce
设定地图展示动画无效

### What is expected?
有展示动画

### What is actually happening?
无展示动画

`visualMap: [{
    type: 'continuous',
    min: 0,
    max: 100,
    inRange: {color: ['yellow', 'red']}
}],
animationDuration: 1000,
animationEasing: 'cubicOut',
animationDurationUpdate: 1000,
series:[{
    type: 'map',
}]
`

**Comment by Ovilia** [comment]
期望有怎么样的动效？
