### ISSUE TITLE
vue引用echarts在iphone真机上显示空白

### ISSUE THREAD

**Issue by xiangguobin123** [apache/incubator-echarts#10789]
### Version
4.2.1

### Steps to reproduce
在一个父div中定义一个子div，子div作为echarts图表的容器，当父div的高度小于子div的高度且父div有滚动条时，echarts在iphone真机上渲染，并且tooltip可见，但是整个图表不可见（ps：真机上不可见，电脑模拟器可以正常显示）

### What is expected?
iphone浏览器上能够正常显示

### What is actually happening?
iphone浏览器上不能够正常显示

**Comment by Ovilia** [comment]
一方面，确保子容器在 `echarts.init` 的时候是有宽度和高度的；另一方面，通过 CSS 确保子容器是可见的。不太像 ECharts 的问题，请根据自己的情况仔细 debug 一下。
