### ISSUE TITLE
折线图折点太多，后面的折线不显示，数据是连续的

### ISSUE THREAD

**Issue by xiyanbox** [apache/incubator-echarts#10790]
### Version
4.2.1

### Steps to reproduce
我们的场景是由柱状图和折线图组成的echarts图表，数据有90项，柱状图正常显示，但折线图在40多项时突然消失不见，我确定数据是连续的不为空、不为零。折线图外层为横向滚动容器，不然太挤显示不下。
![图片](https://user-images.githubusercontent.com/18209483/60567778-a975b280-9d9d-11e9-94db-a74776bb952a.png)

### What is expected?
折线图正常显示

### What is actually happening?
折线图断掉了

**Comment by Ovilia** [comment]
请提供最小可运行的例子：https://gallery.echartsjs.com/editor.html

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-line.showAllSymbol 这个值设为 true 试试

**Comment by xiyanbox** [comment]
@Ovilia 谢谢，明天试试，不过我换了dataZoom，感谢！
