### ISSUE TITLE
echarts的toolbox自定义图标如何触发toolbox的事件？

### ISSUE THREAD

**Issue by curryhh** [apache/incubator-echarts#10791]
### What problem does this feature solve?
自定义图标触发toolbox

### What does the proposed API look like?
dispatchAction也没有这个功能

![3696448094-5d1c26fca5c48_articlex](https://user-images.githubusercontent.com/22719549/60567654-39ffc300-9d9d-11e9-94e1-6401add82fcc.png)
如上图自定义的图标怎么去触发toolbox的事件

**Comment by Ovilia** [comment]
如果是想响应 toolbox 自定义图标事件的话，通过 onclick 事件就行 https://echarts.apache.org/zh/option.html#toolbox.feature

**Comment by curryhh** [comment]
> 如果是想响应 toolbox 自定义图标事件的话，通过 onclick 事件就行 https://echarts.apache.org/zh/option.html#toolbox.feature
不是这个哦，你这个是toolbox添加自己的图标做事件，我现在是想不要toolbox，自己来重写toolbox但是功能跟toolbox一样，只是我自己在外层定义

**Comment by curryhh** [comment]
> 如果是想响应 toolbox 自定义图标事件的话，通过 onclick 事件就行 https://echarts.apache.org/zh/option.html#toolbox.feature



> 如果是想响应 toolbox 自定义图标事件的话，通过 onclick 事件就行 https://echarts.apache.org/zh/option.html#toolbox.feature

**Comment by wqzwh** [comment]
希望能自定义方法来触发toolbox里面图标的事件，请问你有实现么 @curryhh
