### ISSUE TITLE
xAxis，yAxis，x轴，y轴的label文字过长时候，name属性被覆盖

### ISSUE THREAD

**Issue by wjhcc2018** [apache/incubator-echarts#10792]
### Version
4.2.1

### Steps to reproduce
xAxis，yAxis，x轴，y轴的label文字过长时候，name属性被覆盖

### What is expected?
x轴，y轴的name和highcharts一样，能够自适应

### What is actually happening?
实际结果是被覆盖了

**Comment by Ovilia** [comment]
做不到自动改位置，但是可以用 https://echarts.apache.org/zh/option.html#xAxis.nameGap 控制和轴线间隔

**Comment by YH-Chen** [comment]
+1  自适应  label会随值改变  nameGap不智能

**Comment by yswang0927** [comment]
是的，被 X轴，Y轴 的 name 会被 label 覆盖问题搞死了，那个 nameGap 啥用都没有，label 长度是动态的，根本无法预测长度。

**Comment by YH-Chen** [comment]
您的来信已经收到，我会尽快查阅！
