### ISSUE TITLE
高版本和低版本X轴为time类型时的样式显示

### ISSUE THREAD

**Issue by lluohuih** [apache/incubator-echarts#10796]
### Version
4.2.1

### Steps to reproduce
高版本和低版本统计图X轴为time类型时的样式显示问题：
1、低版本（2.0）的Echarts统计图X轴为time类型时，时间和日期换行后是紧挨着的。
2、高版本（2以上）的Echarts统计图X轴为time类型时，时间和日期换行后隔的很开，看着没有低版本美观。
请问这个可以优化下吗？还是说源码哪里可以更改一下？

### What is expected?
Echarts统计图X轴为time类型时，时间和日期换行后是紧挨着的，这样看起来比较好看点

### What is actually happening?
Echarts统计图X轴为time类型时，时间和日期换行后隔的很开，看着没有低版本美观

**Comment by Ovilia** [comment]
可以自己通过 formatter 定制

**Comment by lluohuih** [comment]
> 可以自己通过 formatter 定制

定制比较麻烦，能恢复之前的最好，而且在官网上样式都是老版本的。
