### ISSUE TITLE
xAxis.axisLabel.formatter使用函数失效

### ISSUE THREAD

**Issue by jiaqizhang77** [apache/incubator-echarts#10804]
在使用xAxis.axisLabel.formatter时，使用
`formatter: '{value} kg'`可以生效。
但是使用
`formatter: function(value, index){
                return value +“kg” ;
              },`函数会失败

因为需要在函数中处理数据，请问这个是bug吗？
![image](https://user-images.githubusercontent.com/31381135/60653618-f8464980-9e7c-11e9-92b8-9e6642df031c.png)

**Comment by jiaqizhang77** [comment]
自己挖的坑，哎

**Comment by JieWSOFT** [comment]
请问 你解决了吗  我也是遇到这个问题

**Comment by Huxiake** [comment]
。。。挖的啥坑，你就不能明确说吗？

**Comment by byhkl** [comment]
> formatter

我猜测是他JSON.parse拷贝了一下，函数丢失了
