### ISSUE TITLE
为什么sankey图的levels没效果

### ISSUE THREAD

**Issue by Wy38722** [apache/incubator-echarts#10806]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=sankey-product](https://www.echartsjs.com/examples/editor.html?c=sankey-product)

### Steps to reproduce
修改levels属性下等color、border等属性，毫无效果。

### What is expected?
levels正常使用

### What is actually happening?
没效果

**Comment by RunningGrass** [comment]
请问问题解决了，最近也有这个需求

**Comment by mmmhhhlll** [comment]
我也在用这个，同样的Bug出现

**Comment by Holoskevych** [comment]
The same behavior, Levels have no effect.

**Comment by deqingli** [comment]
Sorry, This feature will be released in version 4.4.0. Because it has been completed in last year, so I updated the document ahead of the feature, I am so sorry about this.

**Comment by Holoskevych** [comment]
Hi

> Sorry, This feature will be released in version 4.4.0. Because it has been completed in last year, so I updated the document ahead of the feature, I am so sorry about this.

Are there any information on the version 4.4.0 release date?

**Comment by deqingli** [comment]
It is already released.
![image](https://user-images.githubusercontent.com/13548221/67467966-44abd400-f67c-11e9-879f-5649ee69e866.png)
