### ISSUE TITLE
Graph 中如果只有数据之间的关系，有没有library可以将图关系转换成坐标？

### ISSUE THREAD

**Issue by didiaoshengjianbao** [apache/incubator-echarts#10805]
### What problem does this feature solve?
你好，最近我在使用echarts时，后端获得的数据只有点和边的关系，没有x,y 坐标信息，无法画出graph图，请问有没有类似的library可以根据点和边的关系生成坐标？又或是echarts中有没有自适应布局不需要x，y画graph图呢？

### What does the proposed API look like?
输入：点和边的关系
输出：自动计算 点坐标并画图

**Comment by Ovilia** [comment]
可以的，[layout](https://echarts.apache.org/zh/option.html#series-graph.layout) 设为 `'force'`

**Comment by didiaoshengjianbao** [comment]
但是设置成force，每次的布局都是不同的，请问目前echarts是没有提供将图关系转换成坐标的library是吗？

**Comment by Ovilia** [comment]
是的，force 就会每次不同，要么你就自己计算位置
