### ISSUE TITLE
Add possibility to return HTML mark-up from axisLabel.formatter

### ISSUE THREAD

**Issue by avistheripper** [apache/incubator-echarts#10809]
### What problem does this feature solve?
My case:
There is a need to display tooltip with the full name of the yAxis label, since the formatter only return string it is quite impossible

### What does the proposed API look like?
...
formatter: function(x: string) {
  return `<span title=${x.fullname}>${x.name}</span>`
}
...

**Comment by Ovilia** [comment]
I'm afraid HTML mark-up is not possible, because it uses canvas to render the label. However, [rich](https://echarts.apache.org/en/option.html#yAxis.axisLabel.rich) option provides a flexible way to control the content. Please check if it helps.
