### ISSUE TITLE
折线图visualMap的dimension为0,缩放时视觉映射异常

### ISSUE THREAD

**Issue by x760502527** [apache/incubator-echarts#10808]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xFtAI_YqBQ&v=1](https://gallery.echartsjs.com/editor.html?c=xFtAI_YqBQ&v=1)

### Steps to reproduce
点击区域缩放 缩小到一定程度时，本应outOfRange定义绿色的线变成pieces中定义的红色（重现连接打开加载图表较慢)

### What is expected?
视觉映射数组外的数据在缩小后还是显示outOfRange

### What is actually happening?
视觉映射数组外的数据在缩小后显示 pieces数组中最大值和最小值的差 最大的那个的 样式

---
柱状图好像没有这个问题 
业务场景：根据数据和x轴坐标计算阈值 超过阈值变红，动态添加visualMap的pieces

**Comment by Ovilia** [comment]
无法复现，请问是放大哪部分可以复现出？

**Comment by x760502527** [comment]
这是未缩放之前的
![1562567322(1)](https://user-images.githubusercontent.com/34299830/60787686-3c8f5d80-a18d-11e9-9260-87a355eddc22.jpg)
然后我缩放到较大级别
![1562567343(1)](https://user-images.githubusercontent.com/34299830/60787809-9859e680-a18d-11e9-84b2-c0f1b9eec62e.jpg)
这个时候也没问题，缩放再放大一点
![1562567361(1)](https://user-images.githubusercontent.com/34299830/60787839-af003d80-a18d-11e9-849b-a06fcf8bba55.jpg)
这个线的颜色就变成红色了
