### ISSUE TITLE
Treemap: Labels displayed in treemap not visible because of colour of blocks.

### ISSUE THREAD

**Issue by Monali-ITT** [apache/incubator-echarts#10811]
### Version
4.2.1

### Steps to reproduce
1. Execute treemap.
2. Check the labels in treemap block. Labels not visible because of the color of the block.

### What is expected?
-  Labels text should visible. labels should display in color depends on treemap block color.

### What is actually happening?
1. Labels not visible because of block color.
 - By default, the color of the label text is white.
 - If treemap block color also white or near to white, label text not visible.

- For example, if we change text colour to lighter colour it will cause problem when shade is with white base and on contrast it will be a problem if colour is shade is dark and text too..

**Comment by Monali-ITT** [comment]
@Ovilia 
any updates on this?

**Comment by Ovilia** [comment]
Not sure if I understood. How about setting a different label or block color?

**Comment by Monali-ITT** [comment]
@Ovilia ,
I have created one ppt for this issue. Please find the attachment
[treemapBolckColorIssue.pptx](https://github.com/apache/incubator-echarts/files/3409955/treemapBolckColorIssue.pptx)
.
