### ISSUE TITLE
利用 MathJax 支持  LaTex 公式

### ISSUE THREAD

**Issue by zhouzq-thu** [apache/incubator-echarts#10816]
### What problem does this feature solve?
更完美的现实数学公式

### What does the proposed API look like?
类似 latex("$\sqrt{a b}$")

**Comment by Ovilia** [comment]
暂时没有计划支持，不过可以使用富文本实现复杂的文字效果 https://echarts.apache.org/zh/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE
