### ISSUE TITLE
echarts 中的关系图，如果将link的source和target设置一致时，无法可见。

### ISSUE THREAD

**Issue by Marcnuth** [apache/incubator-echarts#10813]
### Version
4.2.1

### Steps to reproduce
1. 打开demo：https://www.echartsjs.com/examples/editor.html?c=graph-simple
2. 修改其中的第一条link， 将source和target均设置为同一个
3. 观察渲染后的新图，原link消失，但是指向自己的link没有出现

### What is expected?
会有一条线，指向结点自己

### What is actually happening?
不存在该线

**Comment by Ovilia** [comment]
这应该算新功能了~

**Comment by Ovilia** [comment]
Please follow #11260.

**Comment by singlelonghair** [comment]
Has this problem been solved?

**Comment by Ovilia** [comment]
@singlelonghair It's scheduled in 4.6.0 for now, whose deadline is about the end of October.

**Comment by Milley-Milley** [comment]
@Ovilia Has this issue been resolved ? When will you publish 4.6.0 ?

**Comment by dongleizi** [comment]
这个问题解决了吗？

**Comment by wf123537200** [comment]
这个之前有调试过，其实指向自己的循环线是有绘制的，只是弧度太小，看不出来

**Comment by Milley-Milley** [comment]
可以尝试一下这个: https://www.npmjs.com/package/mw-echarts
我改了源码，目前为止感觉能用 https://github.com/Milley-Milley/mw-echarts

**Comment by kilik52** [comment]
@Ovilia 4.8.0了。这个问题还没有解决。请问是否有计划将自指向的问题解决
