### ISSUE TITLE
sankey图的levels和node中depth无效

### ISSUE THREAD

**Issue by RunningGrass** [apache/incubator-echarts#10815]
### Version
4.2.1

### Steps to reproduce
按照官方实例中的代码，仅增加node中的depth或者levels

### What is expected?
预期可以使用levels设置每一层级的样式

### What is actually happening?
没有任何作用

---
难道是文档比代码先发布了？

**Comment by deqingli** [comment]
@RunningGrass Sorry, the version 4.2.1 does not include these features. The next version is available. It is indeed the document first.
