### ISSUE TITLE
windows笔记本下chrome浏览器图形乱码

### ISSUE THREAD

**Issue by starstaysky** [apache/incubator-echarts#10818]
### Version
4.2.1

### Reproduction link
[https://echarts.baidu.com/echarts2/](https://echarts.baidu.com/echarts2/)

### Steps to reproduce
Bug现象：windows笔记本、chrome浏览器下，图表未能正常展示，显示乱码。（官方亦如此）
Bug出现时间:2019.7.8
系统修复时间：2019.7.8 下午6：20左右

期待回复：1 该问题发生的原因
                  2 以后是否还会出现此类问题
                  3 如果会出现，持续时间是多久

### What is expected?
正常展示

### What is actually happening?
乱码

**Comment by Ovilia** [comment]
ECharts 2 的代码已经不再维护，请升级到最新版的 4.x 版本。
