### ISSUE TITLE
桑基图lineStyle颜色渐变左右和上下不一致

### ISSUE THREAD

**Issue by shellyaoo** [apache/incubator-echarts#10822]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x9i4f9uxhP&v=1](https://gallery.echartsjs.com/editor.html?c=x9i4f9uxhP&v=1)

### Steps to reproduce
在给出的gallery链接上，从左往右的颜色渐变基本正确，但是换成从上往下，颜色渐变就有点不对，主要看武汉到香港这个节点的颜色

### What is expected?
希望颜色渐变保持一致

### What is actually happening?
颜色渐变没有保持一致

**Comment by Ovilia** [comment]
期望的效果是什么？是不是横向颜色不改变，纵向地渐变改变？

**Comment by shellyaoo** [comment]
横向的颜色是从左到右渐变的，改成上下以后，希望颜色从上到下渐变



------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 下午5:44
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>; 
抄送: "。逮貓的田鼠-!"<897881129@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] 桑基图lineStyle颜色渐变左右和上下不一致 (#10822)



期望的效果是什么？是不是横向颜色不改变，纵向地渐变改变？

**Comment by Ovilia** [comment]
```
			"x": 0,
			"y": 0,
			"x2": 1,
			"y2": 1,
```
这是左上角到右下角，是斜的
