### ISSUE TITLE
vue中无法监听echarts事件

### ISSUE THREAD

**Issue by itAlvy** [apache/incubator-echarts#10838]
### Version
3.8.5

### Steps to reproduce
```js
<script>
import echarts from 'echarts'
import { debounce } from '@/utils'
require('echarts/theme/macarons') // echarts theme
export default {
  name: 'networkLine',
  data() {
    return {
      chart: null,
      echarts
    }
  },
  mounted() {
    this.initChart()
  },
  methods: {
    initChart() {
      // macarons vintage dark infographic shine roma
      var chart = this.echarts.init(document.querySelector('.outage-container'))

      const options = {.........}
      chart.setOption(options)

      chart.on('mousemove', function(params) {
        console.log(params)
      })
    }
  }
}
</script>
```

### What is expected?
应该如何操作

### What is actually happening?
vue的版本为 **2.5.16** , 打印 **params** 无法获取到任何信息

### has nothing to output
---
![image](https://user-images.githubusercontent.com/34973898/60963142-8cfbec00-a342-11e9-9399-2e7a1e111885.png)

**Comment by itAlvy** [comment]
不好意思,这个报错忽略一下,上面的
this.chart.on('click', function(params) {
      console.log(params)
 })
忘记注释了

**Comment by itAlvy** [comment]
打印无法获取到params的信息

**Comment by itAlvy** [comment]
需要hover去修改折线的颜色.我无法找到支持的方法,想通过事件试图修改options,却没有任何反应

**Comment by Ovilia** [comment]
通用的代码，不用 vue 框架 ok 吗？

**Comment by itAlvy** [comment]
@Ovilia 谢谢您的回答，不过项目已经走了很久了，换框架是不行了。
我也不知道什么原因，看别人的都可以，就我的不行~
我现在已经放弃了zzzzzzzz~~~~~

**Comment by Ovilia** [comment]
不是让你换框架，是看看这个是不是 vue 的问题

**Comment by itAlvy** [comment]
> 不是让你换框架，是看看这个是不是 vue 的问题

现在可以注册事件了，不过只会在 **line** 上出发， **click**和**mousemove**，componentType只会为 **line**，我想在尝试在整个gird区域触发
![image](https://user-images.githubusercontent.com/34973898/61201347-cb185780-a716-11e9-9df5-f2dad8d608d3.png)
![image](https://user-images.githubusercontent.com/34973898/61201364-d79cb000-a716-11e9-888f-c093f0a3906a.png)

**Comment by itAlvy** [comment]
准确的说应该是只有点击或者移动到 **标点** 的时候才会触发

**Comment by itAlvy** [comment]
> > 不是让你换框架，是看看这个是不是 vue 的问题
> 
> 现在可以注册事件了，不过只会在 **line** 上触发， 使用两个事件**click**和**mousemove**，*_componentType_ *都是为 **line** ，我想在尝试在整个 **gird** 区域触发
> ![image](https://user-images.githubusercontent.com/34973898/61201347-cb185780-a716-11e9-9df5-f2dad8d608d3.png)
> ![image](https://user-images.githubusercontent.com/34973898/61201364-d79cb000-a716-11e9-888f-c093f0a3906a.png)

准确的说应该是只有点击或者移动到 标点 的时候才会触发

**Comment by Ovilia** [comment]
这个是符合预期的，ECharts 就是这样的。如果要所有的点击事件，就自己监听 dom 的 onclick。

**Comment by itAlvy** [comment]
> 这个是符合预期的，ECharts 就是这样的。如果要所有的点击事件，就自己监听 dom 的 onclick。

非常感谢您的回答，大概知道怎么做了。
