### ISSUE TITLE
当legend字体大小设置为13时，为line的symbol特别细

### ISSUE THREAD

**Issue by Aeero** [apache/incubator-echarts#10836]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x3s8DaEGoM&v=1](https://gallery.echartsjs.com/editor.html?c=x3s8DaEGoM&v=1)

### Steps to reproduce
设置折线图的symbol为line，legend.textStyle.fontSize为13，可见。

### What is expected?
legend为line的symbol显示正常

### What is actually happening?
legend为line的symbol非常的细

---
浏览器：chrome75

将legend.textStyle.fontSize设置为偶数值显示正常，奇数值显示不正常。

**Comment by Ovilia** [comment]
折线图的 symbol 为 line 的意思是，拐点处用小短线显示，这是一种很奇怪的设置方式，我怀疑不是你要的效果？
如果你要的效果是拐点处不显示圆点的话，正确的设置方式是 [showSymbol](https://echarts.apache.org/zh/option.html#series-line.showSymbol) 设为 false

**Comment by Aeero** [comment]
> 折线图的 symbol 为 line 的意思是，拐点处用小短线显示，这是一种很奇怪的设置方式，我怀疑不是你要的效果？
> 如果你要的效果是拐点处不显示圆点的话，正确的设置方式是 [showSymbol](https://echarts.apache.org/zh/option.html#series-line.showSymbol) 设为 false

感谢回复。

其实问题点在于legend的symbol，设置折线图的 symbol 为 line，legend的symbol也会默认为line（只是为了复现问题的时候尽量简洁，没想到会造成歧义 - -）。

具体的差别如下图

legend字体为奇数：
![thin](https://user-images.githubusercontent.com/13835083/60962146-38577180-a340-11e9-85c3-b0d1cde5ab27.png)

legend字体为偶数：
![thick](https://user-images.githubusercontent.com/13835083/60962130-2f66a000-a340-11e9-8475-b88f24e0a4b3.png)
