### ISSUE TITLE
I have problem. How to make realtime to chart? My data update every 5s, so can i update data without reset chart?

### ISSUE THREAD

**Issue by CuongStf** [apache/incubator-echarts#10848]
### Version
4.2.1

### Steps to reproduce
How to make realtime to chart? 
My data update every 5s.
So can i update data without reset chart?

### What is expected?
So can i update data without reset chart?

### What is actually happening?
How to make realtime to chart? 
My data update every 5s.

**Comment by susiwen8** [comment]
https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2

**Comment by symlons** [comment]
I have tried the demo, that worked so far. But when I am trying to update the data live from a socket.io stream I get the error that setOption should not be called during the main process.

**Comment by hmmftg** [comment]
Hi, I have the same issue and resolved it with adding new handler metric at backend and this setInterval function(Hope this helps someone):

```js
setInterval(function() {
	fetch(
		'/metrics?metricName',
		{
			method: 'GET',
			headers: {
				'X-RapidAPI-Key': '************************************',
				'X-RapidAPI-Host': 'weatherbit-v1-mashape.p.rapidapi.com'
			}
		}
	)
	.then(response => response.json())
	.then(response => {
		const gChart = myChartInstance;
		var options = gChart.getOption();

		for (var seri in response) {
			appendToSeries(options, seri, response);
		}

		gChart.setOption(options);
	})
	.catch(err => console.error(err))
}, 2000);
function appendToSeries(options, id, response) {
	const value = response[id];
	var seriesData = options.series.find(seri=>(seri.name == value.name.split("#")[0])).data;
                      // remove data after 240 nodes
	if(seriesData.length>240){
		seriesData.shift();
	}
	seriesData.push(value);
}
```

**Comment by tanshiyu1999** [comment]
I am having the same problem, will try the solution listed, thank you.
