### ISSUE TITLE
ECharts文档缺陷

### ISSUE THREAD

**Issue by SaltFish-X** [apache/incubator-echarts#10849]
### Version
4.2.1-rc1

### Reproduction link
[https://echarts.baidu.com/option.html#series-gauge](https://echarts.baidu.com/option.html#series-gauge)

### Steps to reproduce
打开网页查看 series[i]-gauge

### What is expected?
应该有series[i]-gauge.data的配置说明

### What is actually happening?
没有series[i]-gauge.data的配置说明

**Comment by Ovilia** [comment]
已修复，文档将在下一次发版的时候上线
