### ISSUE TITLE
标记区域能否下能标记线一样在低于或高于某个值的时候将区域标记

### ISSUE THREAD

**Issue by blackdevil055** [apache/incubator-echarts#10841]
### What problem does this feature solve?
不用再循环遍历几次将需要标记的多个区段找出来，可以提升一定的开发效率

### What does the proposed API look like?
markArea:[
[gt:80,color:green],
[lt:30,color:red]
]

**Comment by Ovilia** [comment]
写一个 for 循环也不是很麻烦吧？
