### ISSUE TITLE
How to config only show tooltip (when hover into data) if data is not null?

### ISSUE THREAD

**Issue by CuongStf** [apache/incubator-echarts#10844]
### Version
4.2.1

### Steps to reproduce
 I have 10 point in data chart, include both number and null type . But i want to hide tooltip if data is null? Please help me? 

### What is expected?
But i want to hide tooltip if data is null?

### What is actually happening?
 I have 10 point in data chart, include both number and null type, tooltip is always display

**Comment by Ovilia** [comment]
Use `trigger: 'item'` and set data to be `'-'` when there is no data.

**Comment by CuongStf** [comment]
when i can set? seriesData or tooltip?

**Comment by CuongStf** [comment]
can i set it 'axis' and config it display or not? because when use 'item', force user must hover every line to see data

**Comment by CuongStf** [comment]
> Use `trigger: 'item'` and set data to be `'-'` when there is no data.

can i set it 'axis' and config it display or not? because when use 'item', force user must hover every line to see data

**Comment by CuongStf** [comment]
yeah, i was finded solution to resolve it. Many Thanks

**Comment by JBLGLN** [comment]
> yeah, i was finded solution to resolve it. Many Thanks

Hey,
is it possible, if you share your solutions?
Struggling with the same problem.
Thanks in advance

**Comment by HY-HY-49** [comment]
> yeah, i was finded solution to resolve it. Many Thanks

Would you like to share your solutions? THX.
