### ISSUE TITLE
如何将折线图导出为放大不失真的矢量图

### ISSUE THREAD

**Issue by eniaclyl** [apache/incubator-echarts#10856]
### What problem does this feature solve?
将折线图导出成矢量图，然后插入到word或者pdf中打印不会使图片失真

### What does the proposed API look like?
saveAsImage： {type: "svg"}

**Comment by Ovilia** [comment]
在 `echarts.init` 的时候就使用 svg，然后 toolbox 这里`type: 'svg'`

**Comment by eniaclyl** [comment]
@Ovilia 多谢大神，就是这个功能在官网的配置文件没写，导致很多人不知道有这个功能

**Comment by eniaclyl** [comment]
@Ovilia 如果想选择多种格式我的这个写法不行saveAsImage: {type: ['svg','png']   能告诉我一个正确的写法吗，多谢。

**Comment by Ovilia** [comment]
没有在配置项写，是因为这不算完全开发完（因为目前只能是 SVG 渲染的就导出 SVG 的图，Canvas 渲染的就导出位图，这个好像不是很完美）。
不支持数组，只能选择一种方式导出。
