### ISSUE TITLE
高频率更新echarts中的数据时,无法使用brush来框选

### ISSUE THREAD

**Issue by 52jc** [apache/incubator-echarts#10859]
### Version
4.2.1

### Steps to reproduce
使用echarts来画频谱图,每秒钟刷20次,在图动的过程中需要使用矩形来框选

### What is expected?
在echarts图在高频率刷新的过程中可以使用brush中的矩形来进行框选

### What is actually happening?
图静止或者刷新速率慢时可以框选,刷新速率快了就不行了

**Comment by 100pah** [comment]
"矩形来框" 的意思是？

我并没有能复现这个问题。可以提供可运行的 option 么？

**Comment by shukeLiang** [comment]
`var dom = document.getElementById('chart-container');
var myChart = echarts.init(dom, null, {
  renderer: 'canvas',
  useDirtyRect: false
});
var app = {};

var option;

let base = +new Date(1988, 9, 3);
let oneDay = 24 * 3600 * 1000;
let data = [[base, Math.random() * 300]];
for (let i = 1; i < 20000; i++) {
  let now = new Date((base += oneDay));
  data.push([+now, Math.round((Math.random() - 0.5) * 20 + data[i - 1][1])]);
}
setInterval(() => {
  data[data.length - 1][1] =  Math.round((Math.random() - 0.5) * 20 + data[19999][1]);
  option = {
  tooltip: {
    trigger: 'axis',
    position: function (pt) {
      return [pt[0], '10%'];
    }
  },
  title: {
    left: 'center',
    text: 'Large Ara Chart'
  },
  toolbox: {
    feature: {
      dataZoom: {
        yAxisIndex: 'none'
      },
      restore: {},
      saveAsImage: {}
    }
  },
  xAxis: {
    type: 'time',
    boundaryGap: false
  },
  yAxis: {
    type: 'value',
    boundaryGap: [0, '100%']
  },
  dataZoom: [
    {
      type: 'inside',
    },
    {
      start: 0,
      end: 20
    }
  ],
  series: [
    {
      name: 'Fake Data',
      type: 'line',
      smooth: true,
      symbol: 'none',
      areaStyle: {},
      data: data
    }
  ]
};

if (option && typeof option === 'object') {
  myChart.setOption(option);
}
}, 200)


window.addEventListener('resize', myChart.resize);`

**Comment by shukeLiang** [comment]
> var dom = document.getElementById('chart-container'); var myChart = echarts.init(dom, null, { renderer: 'canvas', useDirtyRect: false }); var app = {};
> 
> var option;
> 
> let base = +new Date(1988, 9, 3); let oneDay = 24 * 3600 * 1000; let data = [[base, Math.random() * 300]]; for (let i = 1; i < 20000; i++) { let now = new Date((base += oneDay)); data.push([+now, Math.round((Math.random() - 0.5) * 20 + data[i - 1][1])]); } setInterval(() => { data[data.length - 1][1] = Math.round((Math.random() - 0.5) * 20 + data[19999][1]); option = { tooltip: { trigger: 'axis', position: function (pt) { return [pt[0], '10%']; } }, title: { left: 'center', text: 'Large Ara Chart' }, toolbox: { feature: { dataZoom: { yAxisIndex: 'none' }, restore: {}, saveAsImage: {} } }, xAxis: { type: 'time', boundaryGap: false }, yAxis: { type: 'value', boundaryGap: [0, '100%'] }, dataZoom: [ { type: 'inside', }, { start: 0, end: 20 } ], series: [ { name: 'Fake Data', type: 'line', smooth: true, symbol: 'none', areaStyle: {}, data: data } ] };
> 
> if (option && typeof option === 'object') { myChart.setOption(option); } }, 200)
> 
> window.addEventListener('resize', myChart.resize);
在这个官方示例里面修改js为这个就可以复现了, 麻烦帮忙看看有没有办法解决, 我也遇到了
https://echarts.apache.org/examples/zh/editor.html?c=area-time-axis
