### ISSUE TITLE
如何让echarts导出图片为emf或wmf格式，插入到word中

### ISSUE THREAD

**Issue by eniaclyl** [apache/incubator-echarts#10858]
### What problem does this feature solve?
将导出的图片作为矢量图插入到word中，可以无损缩放

### What does the proposed API look like?
saveAsImage:{ type: "emf" }

**Comment by Ovilia** [comment]
这种小众的需求不太可能实现，还是考虑导出 SVG（#10856）然后自己转其他格式

**Comment by eniaclyl** [comment]
@Ovilia 因为导出的矢量图需要插入到word中，但是低版本的word不支持svg图，按理说这应该不算小众需求，有大量的用户在使用低版本的word办公

**Comment by Ovilia** [comment]
为什么不导出一个高清版本的位图呢？

**Comment by eniaclyl** [comment]
@Ovilia 因为领导说想用echarts导出矢量图插入到word中，但是word只有2019版本支持插入svg，之前的版本都是只能插入emf或wmf这类矢量图，所以才有我的这个需求，或者echarts能导出其它形式的矢量图也行，只要能直接插入到老版本的word中就行，不能用转换工具，那样出报告时候台麻烦了。所以我才在这里求助

**Comment by eniaclyl** [comment]
@Ovilia 领导说位图尺寸太大了，一个高清位图就好几百K，所以领导喜欢矢量图，说转换为pdf什么的也不会失真

**Comment by Ovilia** [comment]
那你找个 npm 工具转换一下就行了，ECharts 本身不太会提供这样的功能

**Comment by eniaclyl** [comment]
@Ovilia 好吧 那我先用svg给领导用者看吧，实在不行先让他更新office，我之前提问的那个lines在coordinateSystem: 'cartesian2d'模式下不裁剪，你说用hack的方式解决，能给我个例子吗，我不太会，我是搞C++的不知道怎么实现你说的那个功能，多谢了，发我邮箱也行274015160@qq.com
