### ISSUE TITLE
Cannot read property 'appendData' of undefined

### ISSUE THREAD

**Issue by nikezhenji86** [apache/incubator-echarts#10850]
版本 4.2.1
使用动态数据加载报 Cannot read property 'appendData' of undefined
![image](https://user-images.githubusercontent.com/18554738/61097521-37345a80-a48e-11e9-9e23-f9612e817207.png)

**Comment by JedidiahY** [comment]
同问？？？

**Comment by yyz945947732** [comment]
同问,解决了么？
