### ISSUE TITLE
Comma separator for thousand cannot shown on bar chart data.

### ISSUE THREAD

**Issue by unogang** [apache/incubator-echarts#10854]
### Version
4.2.1

### Steps to reproduce
{
        name: '2019',
        type: 'bar',
        barGap: 0,
        label: labelOption,
        data: [200, 2,911]
      }

### What is expected?
data is in currency, need comma separator for thousand.

### What is actually happening?
Data cannot shown, it blank for data = 2,911

**Comment by Ovilia** [comment]
`2,911` is treated as two numbers in JavaScript, and ECharts can do nothing with it. Please use `2911` instead. You may use [formatter](https://echarts.apache.org/en/option.html#series-bar.label.formatter) to change the display of value, but when in input, it should be a number in the form of `2911`.

**Comment by unogang** [comment]
Noted with thanks.

**Comment by toddtsic** [comment]
I'm having the same problem, and I believe my data is in the correct format...

bar chart options:
```
{
  "title": {
    "text": "Payments By Year-Month"
  },
  "tooltip": {
    "trigger": "axis"
  },
  "grid": {
    "left": "3%",
    "right": "4%",
    "containLabel": true
  },
  "toolbox": {
    "feature": {
      "saveAsImage": true
    }
  },
  "xAxis": {
    "type": "category",
    "axisTick": {
      "alignWithLabel": true
    },
    "data": [
      "2019-07",
      "2019-08",
      "2019-09",
      "2019-10",
      "2019-11",
      "2019-12",
      "2020-01"
    ]
  },
  "yAxis": {
    "type": "value",
    "axisLabel": {
      "formatter": "${value}"
    }
  },
  "series": [
    {
      "type": "bar",
      "data": [
        41700,
        39106.15,
        8322.9,
        52273.65,
        11095.4,
        5049.85,
        37690.22
      ],
      "label": {
        "normal": {
          "show": true,
          "formatter": "${c}"
        }
      }
    }
  ]
}

Resulting image:
![image](https://user-images.githubusercontent.com/9937583/75121232-55cb1880-564f-11ea-9561-56b142fdea50.png)

the formatter for y-axis works fine, and formatter for bar label does add "$", but no commas in bar label number.

**Comment by ahadihadi** [comment]
use this:
```
{
   ...
   series: [
      {
         label: {
           formatter: function(d) { return d.data.value.toLocaleString() }
         }
     }
}
```
also can use:
```
           formatter: function(d) { return d.data.value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',') }
```

**Comment by HugoBarjot** [comment]
i am searching how to remove separators, i don't figure how to use formatter parameter to make this
![image](https://user-images.githubusercontent.com/61101040/180230153-8892ab81-a281-4e3c-8343-539eec0dc54c.png)

i try this adviced by @ahadihadi but didn't change anything to my chart :s i have no clue how to do this
![image](https://user-images.githubusercontent.com/61101040/180230283-7342af91-da74-4552-8955-8946197b38a0.png)

**Comment by SavvyEngineer** [comment]
> i am searching how to remove separators, i don't figure how to use formatter parameter to make this ![image](https://user-images.githubusercontent.com/61101040/180230153-8892ab81-a281-4e3c-8343-539eec0dc54c.png)
> 
> i try this adviced by @ahadihadi but didn't change anything to my chart :s i have no clue how to do this ![image](https://user-images.githubusercontent.com/61101040/180230283-7342af91-da74-4552-8955-8946197b38a0.png)

did you find anything?

**Comment by MlsCf** [comment]
Under "tooltip" you can set 
``` valueFormatter: val => `${val.toLocaleString()}` ```

Note: use backticks, not quotes
