### ISSUE TITLE
How to show all point in xAxis and data in chart?

### ISSUE THREAD

**Issue by CuongStf** [apache/incubator-echarts#10860]
### Version
4.2.1

### Steps to reproduce
I have 1440 point in chart compatible width 1440 point in xAxis. But when render in chart, chart auto hide some point, example time axis by each minutes ( 06:01, 06:02, 06:03...) it hide point 06:02 and only when i use dataZoom property, it's displayed. 
I want show all and not hide any point. What's solution for me? Thanks

### What is expected?
I want show all and not hide any point

### What is actually happening?
I have 1440 point in chart compatible width 1440 point in xAxis. But when render in chart, chart auto hide some point, example time axis by each minutes ( 06:01, 06:02, 06:03...) it hide point 06:02 and only when i use dataZoom property, it's displayed.

**Comment by Ovilia** [comment]
Please set [axis label interval](https://echarts.apache.org/en/option.html#xAxis.axisLabel.interval) to be 0 to display all data labels.
I think the document should be improved by adding more details.

**Comment by CuongStf** [comment]
sorry but it's not work.
```
xAxis: {
        interval: 0,
        data: data.categoryData,
        axisLabel: {
        formatter: function (value, idx) {
          var time = value.toString().split(':');
          if (time[0] === '23' && time[1] === '59') { return value; }
          if(idx === 0) { return value; }
          switch (time[1]) {
            case '00':
            case '10':
            case '20':
            case '30':
            case '40':
            case '50':
              return value;
          }
        }
        // interval: 180
      },
      boundaryGap: false,
      axisTick: {
        inside: false,
        // interval: 180,
        alignWithLabel: true
      },
      silent: false,
      splitLine: {
        show: false
      },
      splitArea: {
        show: false
      }
    }
```
`When i hover, it still lost point, 01:01 to 01:03

**Comment by luguokong** [comment]
@CuongStf  
Set the series[i].showAllSymbol with true

**Comment by CuongStf** [comment]
> @CuongStf
> Set the series[i].showAllSymbol with true

it's not work

**Comment by Ovilia** [comment]
@CuongStf Create a demo here: https://gallery.echartsjs.com/editor.html

**Comment by chenxiaochun** [comment]
> @CuongStf Create a demo here: https://gallery.echartsjs.com/editor.html

地址已经无效了😂

**Comment by chenxiaochun** [comment]
> @CuongStf
> Set the series[i].showAllSymbol with true

It is great, thanks!

**Comment by rangesh-gupta** [comment]
Facing the same issue. How to solve this? Tried showAllSymbol, but it shows the label ( 06:01, 06:03, 06:05...). 

But what I want is on mouseover It should show all the data points(06:01, 06:02, 06:03...)
