### ISSUE TITLE
series-map 怎么叠加在 echarts 的 bmap上

### ISSUE THREAD

**Issue by zss1004504439** [apache/incubator-echarts#10864]
### Version
4.2.1

### Steps to reproduce
series-map 怎么叠加在 echarts 的 bmap上？
series-map 怎么实现 coordinateSystem:bmap
求解！！！
![61202679-c0f85800-a71a-11e9-9ad5-6d35dd5922e3](https://user-images.githubusercontent.com/24915880/61203367-c0f95780-a71c-11e9-936d-3613cc79fa53.png)

### What is expected?
series-map  叠加到  bmap 

### What is actually happening?
series-map  不能叠加到  bmap 不能同时缩放

**Comment by deyihu** [comment]
@zss1004504439 

series-map 本质还是 geo组件  https://echarts.baidu.com/option.html#series-map.geoIndex

bmap和geo同样属于地理信息组件，他们是同一类别的东西，将geo叠加到bmap并保持他们之间的同步，估计echarts目前不支持（个人猜测的  ）

不过可以利用 series-custom来解决这个问题  https://gallery.echartsjs.com/editor.html?c=xeIVGA1kdQ&v=1

我也有过类似的想法的😄，**不过后来仔细的思考了一下，bmap和geo同属于组件，他们之间不该有交集，他们的作用为支持各种series** ，其实我希望 echarts 里能添加一个新的 series-polygon的，这样就可以在各种坐标系下快乐的进行 多边形的绘制了，而且也能和gl中的polygon3D对应起来，
https://echarts.baidu.com/option-gl.html#series-polygons3D
我认为这应该是echarts的 feature（虽然利用custom 可以解决这个问题）
我做的这个例子相当于利用 custom 做了一个 新的polygon series

ps: 目前echarts目前处理 地理信息的时候有个bug, 详情  https://github.com/ecomfe/zrender/pull/451

**Comment by Ovilia** [comment]
@deyihu 可以用自定义系列实现 polygon 的想法。
这两个组件的确不建议一起用。

**Comment by zss1004504439** [comment]
@deyihu 感谢
