### ISSUE TITLE
Series not always rendered

### ISSUE THREAD

**Issue by martin31821** [apache/incubator-echarts#10867]
### Version
4.2.1

### Steps to reproduce
When I use setOption to update stuff while the rendering is in progress or during the finished event, the chart won't draw/update the series. In my concrete bug the chart updates the y-axis range to the correct value but does not render the series itself.
When I issue another setOption call, the animation looks like the update animation even though the series wasn't visible.

### What is expected?
I expect the chart lib to display the series.

### What is actually happening?
No series is displayed, only the axis ranges update

![echarts](https://user-images.githubusercontent.com/5557633/61212226-e62c9c80-a701-11e9-99de-50bed7299de0.gif)

**Comment by martin31821** [comment]
After some further debugging, I figured out it works like intended when disabling animations, but I can't reproduce it in a fiddle or sth.

**Comment by Ovilia** [comment]
OK. Please provide a demo if you need further help.

**Comment by martin31821** [comment]
I found the problem.
When having series with parts of the data set to `null` or `-Infinity` or `Infinity` the animation breaks. 
My workaround was to not use null or infinity values as placeholder and filter these values before sending them to echarts. 

Maybe it would be good to either throw an exception or document somewhere that you shouldn't send null/infinity.
