### ISSUE TITLE
怎么打包修改后的源码? 

### ISSUE THREAD

**Issue by dengshenkk** [apache/incubator-echarts#10877]
### Version
4.2.1

### Steps to reproduce
修改源码实现功能后怎么添加到静态资源中? 
vue-cli 脚手架

### What is expected?
修改源码后打包后可以从当成静态资源引用,而不用在node_modules中引用

### What is actually happening?
把修改后的整个echarts从node_modules中复制到myLib后 组件引用会报错.

---
修改后编译打包成静态资源 可以给vue组件引用,
就是这个pr所解决的问题, 请问一下什么时候会合并发布呢? https://github.com/apache/incubator-echarts/pull/10508

**Comment by Ovilia** [comment]
#10508 的修改感觉不太对，很可能不会 review，求 @100pah review。
如果自己编译的话，应该是 https://github.com/apache/incubator-echarts/blob/master/.github/CONTRIBUTING.md#2-install-dependencies 做完这个之后，运行 `node build/build.js --release`，生成的文件在 `dist` 下。

**Comment by dengshenkk** [comment]
@Ovilia 打包后dist中的文件怎么使用呢? 直接在vue组件中使用require引用dist文件中的echarts.js会报错呢

1.添加依赖

yarn
yarn install v1.15.2
warning package.json: License should be a valid SPDX license expression
info No lockfile found.
warning echarts@4.2.1: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
$ node build/build.js --prepublish
D:\yongyou\code\mobile\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:313
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 
'xxx\_echarts@4.2.1@echarts\lib\chart'
    at Object.fs.rmdirSync (fs.js:846:18)
    at rmkidsSync 
xxx\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync 
xxx\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync 
xxx\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:304:9)
    at 
xxx\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync 
xxx\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync 
xxx\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:334:7)
    at Function.rimrafSync [as sync] (
xxx\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:304:9)
    at Object.removeSync 
xxx\_echarts@4.2.1@echarts\node_modules\fs-extra\lib\remove\index.js:4:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.



2.组件使用 my.vue
require('libs/echarts.js')

3.浏览器报错信息
echarts.js?f2f4:4 Uncaught TypeError: Cannot set property 'echarts' of undefined
    at eval (echarts.js?f2f4:4)
    at Module.eval (echarts.js?f2f4:1)
    at eval (echarts.js:22940)
    at Module../libs/echarts.js (main.js:915)

**Comment by dengshenkk** [comment]
@Ovilia 
1. 打包后DIST中的文件怎么使用呢？
2. 直接在VUE组件中使用需要引用DIST文件中的echarts.js会报错呢

- 我的打包使用步骤

1. 添加依赖
```
yarn
yarn install v1.15.2
warning package.json: License should be a valid SPDX license expression
info No lockfile found.
warning echarts@4.2.1: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
$ node build/build.js --prepublish

xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:313
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir '
xxx\node_modules\_echarts@4.2.1@echarts\lib\chart'
    at Object.fs.rmdirSync (fs.js:846:18)
    at rmkidsSync (
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:304:9)
    at 
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:334:7)
    at Function.rimrafSync [as sync] (
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\rimraf\rimraf.js:304:9)
    at Object.removeSync (
xxx\node_modules\_echarts@4.2.1@echarts\node_modules\fs-extra\lib\remove\index.js:4:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

2. 组件使用my.vue 
```
require（'libs / echarts.js'）
```

3. 浏览器报错信息

```
echarts.js?f2f4:4 Uncaught TypeError: Cannot set property 'echarts' of undefined
    at eval (echarts.js?f2f4:4)
    at Module.eval (echarts.js?f2f4:1)
    at eval (echarts.js:22940)
    at Module../libs/echarts.js (main.js:915)
    at __webpack_require__ (main.js:767)
    at fn (main.js:130)
    at eval (index.vue?e0f2:826)
```

**Comment by Ovilia** [comment]
打包成功了吗？
使用的话，如果是 require，就是 require('./libs/echarts') 确保当前目录的相对位置。
如果是 import，就是 `import * as echarts from './libs/echarts'`

**Comment by dengshenkk** [comment]
@Ovilia 打包成功了 但是没法引用
完整复现步骤
```
1. vue create testecharts
2. npm i echarts --save
3. cd node_modules/echarts
4. npm i
5. node build/build.js --release
6. mkdir src/lib 创建一个文件夹
7. 把node_modules/echarts/dist移动到lib文件夹中
8. 在APP.vue中引入lib/echarts.js  import * as echarts from './lib/echarts'
```

**Comment by Ovilia** [comment]
少了 zrender 部分的操作，zrender 需要和 echarts 同级文件夹

```sh
git clone git@github.com:ecomfe/zrender.git
cd ~/workspace/zrender
npm install
```
