### ISSUE TITLE
Refused to execute script from '.../dist/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by Ms-Yan** [apache/incubator-echarts#10872]
### Version
4.2.1

### Steps to reproduce
在node搭建的项目中， 安装echarts依赖包 在页面引入  本地开发不会出现标题中的问题  推到测试坏境就会出现

### What is expected?
可以完整访问

### What is actually happening?
提示 Refused to execute script from 'http://.../dist/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by Ovilia** [comment]
引用方式应为 `import * as echarts from 'echarts'`，你是怎么用的？
