### ISSUE TITLE
axisPointer实现连续的hover line

### ISSUE THREAD

**Issue by wadrn** [apache/incubator-echarts#10875]
### Version
4.2.1

### Steps to reproduce
想实现多个图connect 之后， 通过一条hover line 可以显示所有图的信息，hover line 是连续的而不是基于点

### What is expected?
希望hover line 不粘着于点，而可以连续出现

### What is actually happening?
多图connect 可以联动，因为某个图的点比较少，可能hover line 到一半就会消失。

**Comment by Ovilia** [comment]
这个跟联动没有关系吧？tooltip trigger: 'axis' 可以吗？
