### ISSUE TITLE
无法粘贴代码，退格键按一次会直接删除两个字符（chrome和Edge均出现此问题）

### ISSUE THREAD

**Issue by Milo-F** [apache/incubator-echarts#10886]
### Version
4.2.1-rc1

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=line-simple](https://www.echartsjs.com/examples/editor.html?c=line-simple)

### Steps to reproduce
进入ehcarts首页；点击实例-官方实例-BasicLineChart；编辑代码时出现编辑功能的错误；无法粘贴代码，粘贴时会只粘贴一个点，退格键按一次会直接删除两个字符,Del键会直接删除光标一前一后共两个字符

### What is expected?
代码编辑区能够正常编辑

### What is actually happening?
代码编辑区编辑功能出错，无法正常删除粘贴

---
通过修改官方实例中折线图代码时出错

**Comment by cuijian-dexter** [comment]
Hello，this bug not reappeared, please provide browser version number.  thank you

**Comment by Ovilia** [comment]
无法复现，是不是输入法的问题？

**Comment by Milo-F** [comment]
Google Chrome version
版本 75.0.3770.142（正式版本） （64 位）
输入法是win10自带的输入法，中英输入均有此问题。

**Comment by Milo-F** [comment]
> 无法复现，是不是输入法的问题？
Google Chrome version
版本 75.0.3770.142（正式版本） （64 位）
输入法是win10自带的输入法，中英输入均有此问题。已录制视频邮箱回复

**Comment by Milo-F** [comment]
Google Chrome version
版本 75.0.3770.142（正式版本） （64 位）
win10自带输入法
 Echarts-issue.mp4
<https://drive.google.com/file/d/1GMiA_LNznOchA5F1CC0xKkzELlYwy762/view?usp=drive_web>


Ovilia <notifications@github.com> 于2019年7月22日周一 下午4:12写道：
