### ISSUE TITLE
Now i using attribute connectNulls to append the points in chart. So can i don't allow append 2 point which between them is the count of null value greater 5? and vice versa, still allow append null 

### ISSUE THREAD

**Issue by CuongStf** [apache/incubator-echarts#10883]
### Version
4.2.1

### Steps to reproduce
Now i using attribute connectNulls to append the points in chart. 
So can i don't allow append 2 point which between them is the count of null value greater 5? 
and vice versa, still allow append null 

### What is expected?
So can i don't allow append 2 point which between them is the count of null value greater 5? 

### What is actually happening?
Now i using attribute connectNulls to append the points in chart.

**Comment by Ovilia** [comment]
Not sure what you mean. Perhaps you may use Chinese to describe your question...
Most likely, you need to check the data before setOption.
