### ISSUE TITLE
geo地图结合散点图，点击地图上的散点，tooltip框没有保持显示

### ISSUE THREAD

**Issue by DorisOu** [apache/incubator-echarts#10889]
### Version
3.7.0

### Steps to reproduce
series: [{
    type: 'scatter',
    coordinateSystem: 'geo',
    symbol: 'pin',
    symbolSize: 8,
    hoverAnimation: true,
    data: handleEventsResource.initSeriesData(opt.data),
    tooltip: {
        enterable: true, //开启鼠标可点击事件
        trigger: 'item',
        alwaysShowContent: true, //永远显示提示框的内容
        backgroundColor: 'rgba(20,0,93,0.9)',
        triggerOn: 'click',
        position: ['50%', '50%'],
        formatter: function(params, ticket, callback) {
            return '公司名称：'   params.data.company   '<br/>'  
                '所在位置：'   params.data.position   '<br/>'  
                '<a href="details.html?id='   params.data.id   '" target="_brank">查看详情</a>'

        }
    },
}, {
    type: 'map',
    mapType: 'guangdong',
    geoIndex: 0,
    data: dataResource,
    tooltip: {
        trigger: "item",
        triggerOn: "mousemove",
        show: true,
        formatter: function(params) {
            return params.name
        }
    }
}]

### What is expected?
鼠标移进地图，显示提示框tooltip（已实现）
鼠标点击散点，显示提示框tooltip，并保持提示框不消失

### What is actually happening?
鼠标移进地图，显示提示框tooltip（已实现）
鼠标点击散点，显示提示框tooltip，鼠标移动后tooltip消失了

**Comment by Ovilia** [comment]
https://gallery.echartsjs.com/editor.html 请提供一个可复现的例子

**Comment by DorisOu** [comment]
@Ovilia https://gallery.echartsjs.com/editor.html
请查看复现的链接，当tooltip的鼠标事件改为'click'后（散点可以点击），鼠标移进地图'mousemove'不起作用

**Comment by Ovilia** [comment]
@DorisOu 你得保存图表，然后把地址发给我

**Comment by DorisOu** [comment]
@Ovilia sorry,pls check this link: https://gallery.echartsjs.com/editor.html?c=xGP0i3jM-M&v=1
tks.

**Comment by Ovilia** [comment]
我看到的效果就是「鼠标点击散点，显示提示框tooltip，并保持提示框不消失」
