### ISSUE TITLE
4.2.1版本， singleAxis中最后一列字体和xAxis字体的显示是粗体的问题；4.1.0版本中， xAxis轴不显示的问题

### ISSUE THREAD

**Issue by pwj126** [apache/incubator-echarts#10896]
### Version
4.2.1

### Steps to reproduce
option 是一个多维的设置，太大提交不成功

将这个option进行绘制即可在4.2.1版本和4.1.0版本中重现相应的问题

### What is expected?
期望singleAxis和xAxis能正常显示

### What is actually happening?
4.2.1版本中singleAxis最后一列字体和xAxis字体都为粗体显示；4.1.0版本中xAxis不显示

**Comment by Ovilia** [comment]
提供一个最小可复现的代码，把不需要的部分删去，数据量最少 
https://gallery.echartsjs.com/editor.html

**Comment by pwj126** [comment]
> 提供一个最小可复现的代码，把不需要的部分删去，数据量最少
> https://gallery.echartsjs.com/editor.html

https://gallery.echartsjs.com/editor.html?c=xHu5k6AzNc&v=1

**Comment by pwj126** [comment]
> > 提供一个最小可复现的代码，把不需要的部分删去，数据量最少
> > https://gallery.echartsjs.com/editor.html
> 
> https://gallery.echartsjs.com/editor.html?c=xHu5k6AzNc&v=1

![image](https://user-images.githubusercontent.com/8382753/61779128-afa5fe80-ae32-11e9-9e51-3147682d4d82.png)

**Comment by pwj126** [comment]
![image](https://user-images.githubusercontent.com/8382753/61779154-be8cb100-ae32-11e9-9723-4eb49995ae32.png)

**Comment by Ovilia** [comment]
https://github.com/apache/incubator-echarts/issues/10304 和这个 issue 是同一个问题吗（最好一个 label 粗体）
已经修复但还没发版
