### ISSUE TITLE
Y-Axis Min & Max are not calculated automatically

### ISSUE THREAD

**Issue by HMubaireek** [apache/incubator-echarts#10899]
### Version
4.2.1

### Reproduction link
[https://stackblitz.com/edit/angular-ngx-echarts-v6hdqm](https://stackblitz.com/edit/angular-ngx-echarts-v6hdqm)

### Steps to reproduce
Try the provided example.

### What is expected?
I expect that the min and max values of each y axis to be calculated automatically and y-axis label are displayed as it is mentioned in the document.

### What is actually happening?
It does only show values for the first y-axis. It only shows values when I set min and max explicitly which I don't want.

**Comment by Ovilia** [comment]
I didn't see any data in the chart. Did the option be set correctly?

**Comment by HMubaireek** [comment]
@Ovilia Actually there's data. There's only one data point though and that should be sufficient. I've updated the link with two more data points.

**Comment by Ovilia** [comment]
You didn't set [yAxisIndex](https://echarts.apache.org/en/option.html#series-line.yAxisIndex) in your series, which makes both of the series to be at the first y axis (on the left side). So there is no data in the right y axis, and thus showing no min max value.

**Comment by HMubaireek** [comment]
I figured that couple of days ago but forgot to update here. Thanks @Ovilia
