### ISSUE TITLE
饼图的连接线可以设置成箭头吗，我想通过label自定义加一个背景图箭头，但是怎样区分连接线和文字的左右位置呢

### ISSUE THREAD

**Issue by mj132** [apache/incubator-echarts#10897]
### What problem does this feature solve?
饼图的连接线可以设置成箭头或者可以区分连接线和文字的左右位置

### What does the proposed API look like?
最好是可以设置连接线的形状，如symbol：‘arrow’

**Comment by Ovilia** [comment]
不支持，这个需求比较奇怪，为什么要加箭头？

**Comment by mj132** [comment]
> 不支持，为什么有加箭头的需求？

![image](https://user-images.githubusercontent.com/22369529/61775579-c9901300-ae2b-11e9-938b-6004c6427bb3.png)
UI的审美，哈哈。有参数可以知道连接线在圆的哪一侧吗

**Comment by Ovilia** [comment]
没有，这个需求直接改 echarts 源码吧

**Comment by mj132** [comment]
> 没有，这个需求直接改 echarts 源码吧

ok
