### ISSUE TITLE
4.2.1版本中toolbox渲染有问题，同样的配置4.1.0版本是正常的

### ISSUE THREAD

**Issue by pwj126** [apache/incubator-echarts#10898]
### Version
4.2.1

### Steps to reproduce
```js
option = "{"series":[{"name":"cb","data":[{"name":"Amaretto","itemStyle":{},"value":89},{"name":"Caffe Mocha","itemStyle":{},"value":191},{"name":"Columbian","itemStyle":{},"value":83},{"name":"Darjeeling","itemStyle":{},"value":45},{"name":"Decaf Irish Cream","itemStyle":{},"value":95},{"name":"Green Tea","itemStyle":{},"value":102}],"type":"bar"}],"yAxis":[{"type":"value"}],"toolbox":{"show":true,"feature":{"magicType":{"title":{"line":"折线图","bar":"柱状图"},"show":true,"type":["line","bar"]},"dataView":{"title":"数据视图","optionToContent":"$$$function(){ return '<table style=\"width:100%;text-align:center\"><tbody><tr><td>productName</td><td>cb</td></tr><tr><td>Amaretto</td><td>89</td></tr><tr><td>Caffe Mocha</td><td>191</td></tr><tr><td>Columbian</td><td>83</td></tr><tr><td>Darjeeling</td><td>45</td></tr><tr><td>Decaf Irish Cream</td><td>95</td></tr><tr><td>Green Tea</td><td>102</td></tr></tbody></table>'}$$$","readOnly":false,"show":true,"lang":["数据视图","关闭","刷新"]},"myrefresh":{"show":true,"icon":"path://M18.233,81.666l-0.016,0.003c0.006,0.012,0.01,0.022,0.016,0.036c0.008,0.101,0.026,0.195,0.04,0.293   c0.002,0.017,0,0.029,0.002,0.045l3.929,25.514c0.476,3.098,3.374,5.221,6.47,4.743c3.098-0.476,5.222-3.372,4.746-6.471   l-0.611-3.965c0.712,0.587,1.43,1.169,2.175,1.714c10.106,7.42,23.111,10.987,36.486,8.926c13.372-2.056,24.702-9.37,32.109-19.487   c3.662-4.988,6.353-10.695,7.922-16.793l-15.479-4.262c-1.044,4.191-2.882,8.109-5.405,11.552   c-5.012,6.824-12.566,11.713-21.593,13.105c-9.027,1.388-17.705-1.002-24.536-6.004c-0.841-0.616-1.645-1.282-2.424-1.976   l4.488,0.435c2.872,0.276,5.445-2.025,5.748-5.144c0.3-3.12-1.783-5.873-4.655-6.15l-23.659-2.291   c-2.568-0.248-4.884,1.572-5.564,4.188c-0.05,0.185-0.076,0.374-0.109,0.565c-0.021,0.132-0.061,0.255-0.074,0.39   c-0.004,0.041,0.002,0.077-0.001,0.114c-0.013,0.174-0.004,0.351-0.002,0.528C18.235,81.406,18.224,81.539,18.233,81.666z\" fill=\"#232323\"/><path d=\"M109.767,46.334l0.015-0.002c-0.006-0.013-0.01-0.024-0.016-0.037c-0.008-0.1-0.027-0.195-0.04-0.293   c-0.002-0.015,0-0.029-0.002-0.044l-3.928-25.513c-0.477-3.097-3.373-5.221-6.472-4.744c-3.097,0.477-5.221,3.373-4.744,6.47   l0.612,3.967c-0.715-0.587-1.433-1.169-2.177-1.715c-10.106-7.419-23.112-10.989-36.484-8.926   c-13.374,2.055-24.703,9.371-32.109,19.487c-3.664,4.989-6.355,10.696-7.922,16.794l15.479,4.26   c1.042-4.19,2.882-8.108,5.403-11.551c5.012-6.824,12.569-11.712,21.595-13.105c9.027-1.386,17.703,1.002,24.536,6.002   c0.841,0.618,1.645,1.284,2.423,1.976l-4.487-0.434c-2.872-0.278-5.445,2.026-5.747,5.144c-0.303,3.119,1.782,5.873,4.653,6.15   l23.659,2.291c2.568,0.248,4.884-1.572,5.564-4.188c0.05-0.184,0.076-0.374,0.107-0.565c0.022-0.132,0.063-0.255,0.075-0.391   c0.006-0.038-0.003-0.075,0-0.112c0.014-0.175,0.007-0.353,0.003-0.53C109.764,46.595,109.774,46.462,109.767,46.334z","title":"还原"}},"right":25},"legend":{"data":["cb"]},"xAxis":[{"position":"bottom","data":["Amaretto","Caffe Mocha","Columbian","Darjeeling","Decaf Irish Cream","Green Tea"],"type":"category"}],"tooltip":{"formatter":"{b}<br>{a0}: {c0}","trigger":"axis"},"title":{"show":false,"text":"","left":"5%","top":"0","textStyle":{"color":"#333","fontFamily":"sans-serif","fontSize":"18"}},"color":["#c23531","#2f4554","#61a0a8","#d48265","#91c7ae","#749f83","#ca8622","#bda29a","#6e7074","#546570","#c4ccd3"]}"
```
对该option进行渲染非正常显示,如果将option中的myrefresh对象去掉或去掉其icon可以正常显示
### What is expected?
toolbox靠右正常显示

![非正常显示](https://user-images.githubusercontent.com/8382753/61687918-215c4a80-ad56-11e9-8cf8-197c7b7569aa.png)
![正常显示](https://user-images.githubusercontent.com/8382753/61687919-215c4a80-ad56-11e9-9f55-84bd77d79f0d.png)

### What is actually happening?
toolbox左上角显示且被容易边缘覆盖显示

### What is actually happening?
toolbox左上角显示且被容易边缘覆盖显示

**Comment by pwj126** [comment]
option = {"yAxis":[{"type":"value"}],"xAxis":[{"data":["Amaretto","Caffe Mocha","Columbian","Darjeeling","Decaf Irish Cream","Green Tea"],"type":"category"}],"legend":{"data":["cb"]},"series":[{"data":[{"name":"Amaretto","itemStyle":{},"value":89},{"name":"Caffe Mocha","itemStyle":{},"value":191},{"name":"Columbian","itemStyle":{},"value":83},{"name":"Darjeeling","itemStyle":{},"value":45},{"name":"Decaf Irish Cream","itemStyle":{},"value":95},{"name":"Green Tea","itemStyle":{},"value":102}],"name":"cb","type":"bar"}],"toolbox":{"feature":{"magicType":{"show":true,"title":{"bar":"柱状图","line":"折线图"},"type":["line","bar"]},"myrefresh":{"show":true,"icon":"path://M18.233,81.666l-0.016,0.003c0.006,0.012,0.01,0.022,0.016,0.036c0.008,0.101,0.026,0.195,0.04,0.293   c0.002,0.017,0,0.029,0.002,0.045l3.929,25.514c0.476,3.098,3.374,5.221,6.47,4.743c3.098-0.476,5.222-3.372,4.746-6.471   l-0.611-3.965c0.712,0.587,1.43,1.169,2.175,1.714c10.106,7.42,23.111,10.987,36.486,8.926c13.372-2.056,24.702-9.37,32.109-19.487   c3.662-4.988,6.353-10.695,7.922-16.793l-15.479-4.262c-1.044,4.191-2.882,8.109-5.405,11.552   c-5.012,6.824-12.566,11.713-21.593,13.105c-9.027,1.388-17.705-1.002-24.536-6.004c-0.841-0.616-1.645-1.282-2.424-1.976   l4.488,0.435c2.872,0.276,5.445-2.025,5.748-5.144c0.3-3.12-1.783-5.873-4.655-6.15l-23.659-2.291   c-2.568-0.248-4.884,1.572-5.564,4.188c-0.05,0.185-0.076,0.374-0.109,0.565c-0.021,0.132-0.061,0.255-0.074,0.39   c-0.004,0.041,0.002,0.077-0.001,0.114c-0.013,0.174-0.004,0.351-0.002,0.528C18.235,81.406,18.224,81.539,18.233,81.666z\" fill=\"#232323\"/><path d=\"M109.767,46.334l0.015-0.002c-0.006-0.013-0.01-0.024-0.016-0.037c-0.008-0.1-0.027-0.195-0.04-0.293   c-0.002-0.015,0-0.029-0.002-0.044l-3.928-25.513c-0.477-3.097-3.373-5.221-6.472-4.744c-3.097,0.477-5.221,3.373-4.744,6.47   l0.612,3.967c-0.715-0.587-1.433-1.169-2.177-1.715c-10.106-7.419-23.112-10.989-36.484-8.926   c-13.374,2.055-24.703,9.371-32.109,19.487c-3.664,4.989-6.355,10.696-7.922,16.794l15.479,4.26   c1.042-4.19,2.882-8.108,5.403-11.551c5.012-6.824,12.569-11.712,21.595-13.105c9.027-1.386,17.703,1.002,24.536,6.002   c0.841,0.618,1.645,1.284,2.423,1.976l-4.487-0.434c-2.872-0.278-5.445,2.026-5.747,5.144c-0.303,3.119,1.782,5.873,4.653,6.15   l23.659,2.291c2.568,0.248,4.884-1.572,5.564-4.188c0.05-0.184,0.076-0.374,0.107-0.565c0.022-0.132,0.063-0.255,0.075-0.391   c0.006-0.038-0.003-0.075,0-0.112c0.014-0.175,0.007-0.353,0.003-0.53C109.764,46.595,109.774,46.462,109.767,46.334z","title":"还原"}},"show":true,"right":25},"tooltip":{"formatter":"{b}<br>{a0}: {c0}","trigger":"axis","confine":"true"},"title":{"show":false,"text":"","left":"5%","top":"0","textStyle":{"color":"#333","fontFamily":"sans-serif","fontSize":"18"}},"color":["#c23531","#2f4554","#61a0a8","#d48265","#91c7ae","#749f83","#ca8622","#bda29a","#6e7074","#546570","#c4ccd3"]};

**Comment by Ovilia** [comment]
https://gallery.echartsjs.com/editor.html 提供一下可复现的 demo

**Comment by pwj126** [comment]
> https://gallery.echartsjs.com/editor.html 提供一下可复现的 demo

https://gallery.echartsjs.com/editor.html?c=xxXL_iJCM9&v=1

**Comment by pwj126** [comment]
![image](https://user-images.githubusercontent.com/8382753/61779334-11feff00-ae33-11e9-99c8-b0f5b3e5b9be.png)
红框内是渲染有问题的toolbox

**Comment by pwj126** [comment]
> https://gallery.echartsjs.com/editor.html 提供一下可复现的 demo

我今天调试了下，发现是toolbox中我们自定义的myrefresh的icon有问题，去掉
![image](https://user-images.githubusercontent.com/8382753/61779567-7cb03a80-ae33-11e9-9cbd-fd02e9f58446.png) 红框中的代码，4.2.1版本是可以正常渲染的

**Comment by pwj126** [comment]
![image](https://user-images.githubusercontent.com/8382753/61779730-cb5dd480-ae33-11e9-8f5d-885bb0be0b2f.png)

**Comment by Ovilia** [comment]
所以现在没问题了？
