### ISSUE TITLE
请求开发使用用户界面(GUI)进行图表制作的功能

### ISSUE THREAD

**Issue by RuikangSun** [apache/incubator-echarts#10907]
### What problem does this feature solve?
ECharts对于不是Web前端开发者的科研人员同样具有较大用途。
然而科研人员对js语言使用较少，难以使用js语言进行科学绘图。
希望能开发用户界面，减少用户在图表制作过程中对JavaScript的依赖性。

### What does the proposed API look like?
通过图形界面(GUI)制作图表，使该项目能更简单地应用于科学数据图表绘制。

**Comment by cuijian-dexter** [comment]
https://tushuo.baidu.com/https://tushuo.baidu.com/

**Comment by Ovilia** [comment]
ECharts 作为可视化工具的开源库，为类似的 GUI 工具提供底层支持，至于基于这个之上开发，欢迎整个开源社区贡献力量。和本项目本身无关，先关了。
