### ISSUE TITLE
Is there any feature to move cursor on chart from code 

### ISSUE THREAD

**Issue by awinashjaiswal** [apache/incubator-echarts#10900]
### What problem does this feature solve?
compare two charts

### What does the proposed API look like?
Api should consume x axis hovered value from one chart and move the cursor in another chart to same value 
There is some thing saying connect api but that api connect the chart and all its property together which is not the requirement

**Comment by Ovilia** [comment]
Is this what you want? https://echarts.apache.org/zh/api.html#echarts.connect

**Comment by awinashjaiswal** [comment]
Yes but i don't want to show the tooltip in all the charts except the hovered one.
Is there any way?
