### ISSUE TITLE
There doesent appear to be an option to have two linear (numeric) axes on a graph

### ISSUE THREAD

**Issue by mihoci10** [apache/incubator-echarts#10904]
### Version
4.1.0-release

### Steps to reproduce
Create a bar chart with both axis set to type: 'value'

### What is expected?
I want to do a FFT analyzer bar chart with input data in the format of data: [[frequency,amplitude], ...]

### What is actually happening?
When I first try it out it works great, but that is with an ordinal type for the X axis. When I want to use a log type for the X axis I run into strange issues.

**Comment by Ovilia** [comment]
@mihoci10 Can you provide a demo about the strange issues?

**Comment by mihoci10** [comment]
Thank you for your response, but my issue has been resolved here: https://stackoverflow.com/questions/57164067/is-it-possible-to-have-both-axes-linear-in-bar-char
