### ISSUE TITLE
使用setOption()更新geo.boundingCoords属性，ui会闪烁

### ISSUE THREAD

**Issue by xxxxst** [apache/incubator-echarts#10915]
### Version
4.1.0-release

### Reproduction link
[https://codepen.io/xxxxst/pen/MNevPd](https://codepen.io/xxxxst/pen/MNevPd)

### Steps to reproduce
拖拽地图

### What is expected?
更新echart地图，ui不闪烁

### What is actually happening?
使用setOption更新geo.boundingCoords属性，ui会闪烁

---
想做的效果是第三方地图和echart地图叠加联动，echart用来显示一些特效。

目前的实现方式是监听第三方地图的事件，然后使用echart.setOption()更新geo.boundingCoords。

这样会导致每次更新的时候echart特效一直在闪烁。

**Comment by Ovilia** [comment]
这个问题无法优化，闪烁的原因是，这样的效果需要多帧渲染实现，而拖曳之后需要重绘，所以看到的效果就会像现在这样。

**Comment by xxxxst** [comment]
感谢回答，目前看来只能这样了，我试过用三维地图geo3D，但是坐标没有办法和二维地图很好的匹配。
