### ISSUE TITLE
多折线图下使用time作为日期横坐标

### ISSUE THREAD

**Issue by linrong** [apache/incubator-echarts#10929]
### Version
4.1.0-rc.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xVN3csGN9l&v=1](https://gallery.echartsjs.com/editor.html?c=xVN3csGN9l&v=1)

### Steps to reproduce
使用time作为xAxis的type，并且创建大约7组折线图数据，每组大概存储10000条数据，数据的组成为['日期字符串'，value],把数组添加到图中

### What is expected?
可以灵活查看数据，支持dataZoom

### What is actually happening?
浏览器内存消耗过大，导致浏览失败

---
option的配置和重现连接中的一致，使用场景一样
1.我尝试使用xAxis的category类目项作为横坐标的类型，在其他方面可以满足我的需求，但使用category时会导致三个数据之间即使横坐标的时间间隔大小不一致，但在折线图上它们在横坐标的间隔却是一样的，例如三个横坐标01：00，02：00，08：00，他们之间的间隔分别为1和6，但它们在折线图上却的横轴显示一样的大小，这个是不符合我的需求的，是否有配置可以修改？
2.由于第一点的问题，我选择了使用time作为xAxis的type，但这个会导致每一条折线都会要添加多一份date对应而不像category一样拥有data属性，只要添加一次即可，多折线图时会造成不必要的浪费，是否可以优化这个xAxis的添加？我对比感觉导致内存消耗过大可能是由于此原因

**Comment by Ovilia** [comment]
几个可以优化的方式：
https://echarts.apache.org/zh/option.html#series-line.showSymbol 设为 false
https://echarts.apache.org/zh/option.html#series-line.sampling 设为 average

**Comment by linrong** [comment]
已查看[xAxis.type='time' + zoomData时卡顿问题](https://github.com/apache/incubator-echarts/issues/8277)进行优化，基本能够解决问题
