### ISSUE TITLE
请问有些hide、remove方法能加上非空判断么？

### ISSUE THREAD

**Issue by qunlee** [apache/incubator-echarts#10926]
### What problem does this feature solve?
react框架使用echarts => echarts-for-react，编译后的项目，在返回或者跳转页面会报‘hide’ of undefined错误，之前改echarts-for-react源码没效果，今天改了一下echarts就好了。
谢谢。

### What does the proposed API look like?
无。

**Comment by qunlee** [comment]
@pissang 您好，请问能更新一下这部分内容么？关于hide方法的非空判断。

**Comment by pissang** [comment]
这个可能是因为 chart 实例已经被 dispose 了

**Comment by qunlee** [comment]
> 这个可能是因为 chart 实例已经被 dispose 了

请问这个问题有什么办法处理么？需要在生命周期里进行判断么？React萌新，不晓得咋处理。谢谢。

**Comment by qunlee** [comment]
> > 这个可能是因为 chart 实例已经被 dispose 了
> 
> 请问这个问题有什么办法处理么？需要在生命周期里进行判断么？React萌新，不晓得咋处理。谢谢。

请问需要等到更新下个版本么？我本地卸载重装之后，看源码，您提交的代码没有更新下来。谢谢。

**Comment by qunlee** [comment]
@Ovilia 
您好，我将您提交的代码直接替换到我本地的依赖之后，编译测试了一下，还是报这样的错误。
请问能overview一遍源码，将调用hide方法的地方加上非空判断么？
我本地将源码中hide方法调用的地方都加了非空判断，编译测试是不报错的。
谢谢。

**Comment by Ovilia** [comment]
抱歉回复晚了。需要到下版本才发布。
本地运行的话参见 https://github.com/apache/incubator-echarts/blob/master/.github/CONTRIBUTING.md#how-to-debug-echarts
