### ISSUE TITLE
Customizing Gauge pointer color

### ISSUE THREAD

**Issue by skhachoum** [apache/incubator-echarts#10934]
### Version
4.0.4

### Steps to reproduce
hello everybody.
I'm trying to customize gauge pointer color but it doesn't work!!
<pre>
pointer: { 
   color: '#000',
},
</pre>

### What is expected?
changing gauge pointer color

### What is actually happening?
gauge pointer color remind auto

**Comment by k-bruneau** [comment]
Use this :
`series:[
{
itemStyle: {
               color: '#318CE7',
                                },
}
]`

**Comment by skhachoum** [comment]
Thank you so much @k-bruneau you helped me a lot with your answer.
Have a nice week  :)

<pre>
data: [{
   value:40,
   itemStyle: { color: '#000', }
}]
</pre>
