### ISSUE TITLE
Zrender Dependency

### ISSUE THREAD

**Issue by 82antu** [apache/incubator-echarts#10939]
### Version
4.2.1

### Steps to reproduce
mine is just a question:

Zrender is set as DEPENDENCY; but, in my application based on SystemJS environment (with a systemjs.config.js configuration file) I'm able to use Echarts without configuring zrender in my systemjs.config.js nor having zrender.js in my outputfolder. My understandig was that Dependencies (and not devDependencies) were mandatory for running a library.

### What is expected?
I expect to add a specific entry for zreder and copy it in my otput folder

### What is actually happening?
no need to use zrender at all

**Comment by pissang** [comment]
You can use the bundled file in `dist` folder
