### ISSUE TITLE
Sankey - custom link tooltip

### ISSUE THREAD

**Issue by anwfr** [apache/incubator-echarts#10931]
### What problem does this feature solve?
Hello, I would like to customize link tooltip in Sankey.
Currently link hover produces the following tooltip: "{source} -- {target} : {value}"

### What does the proposed API look like?
Custom link tooltip could be set as a link property:
{
          source: "source",
          target: "target",
          tooltip: {
            formatter: "custom link tooltip"
          }
}

**Comment by Ovilia** [comment]
Please follow the [doc](https://echarts.apache.org/en/option.html#tooltip.formatter), where formatter can be a callback function. Return the source and value.

**Comment by anwfr** [comment]
awesome, thank you
