### ISSUE TITLE
Graph力导向图中linestyle设置与visualMap不兼容

### ISSUE THREAD

**Issue by sjtuzwj** [apache/incubator-echarts#10946]
### Version
4.2.1

### Steps to reproduce
我在linestyle里设置了color为source，visualmap设置了color的映射区间。 然后绘制

### What is expected?
边的颜色符合来源的颜色

### What is actually happening?
边的颜色为默认的红色，而不是visualmap的颜色
![捕获1](https://user-images.githubusercontent.com/32933716/62261957-9102c180-b449-11e9-9d5f-68533fe769d3.JPG)
![捕获](https://user-images.githubusercontent.com/32933716/62261960-9233ee80-b449-11e9-9fbe-3bff9cc32449.JPG)

---
怀疑可能是渲染顺序的问题？

**Comment by deqingli** [comment]
Please provide the whole echarts `option`, for us to debug.
