### ISSUE TITLE
color of splitArea is in the wrong position

### ISSUE THREAD

**Issue by chezhe** [apache/incubator-echarts#10948]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xLpHI9LzcD&v=1](https://gallery.echartsjs.com/editor.html?c=xLpHI9LzcD&v=1)

### Steps to reproduce
不需要执行任何操作

### What is expected?
期望第7列有背景色

### What is actually happening?
第6列有背景色

**Comment by deqingli** [comment]
In my computer, the grid background color is in the seven columns, see the below picture:
![image](https://user-images.githubusercontent.com/13548221/62526210-63fc4780-b86b-11e9-8b31-c799ff9e9db3.png)
so, I don't understand what's your problem is? Please provide more detailed message.

**Comment by chezhe** [comment]
![Screen Shot 2019-08-07 at 09 53 42](https://user-images.githubusercontent.com/2902414/62588705-4bd30980-b8f9-11e9-9fbc-0ff38367f15b.png)

Try resize the window, pull it width enough and refresh the page.

**Comment by deqingli** [comment]
@chezhe, I have reproduced this problem, thank you for your feedback.

**Comment by chezhe** [comment]
> @chezhe, I have reproduced this problem, thank you for your feedback.

I met this problem on different mobile devices too, especial on some Android.

**Comment by pissang** [comment]
Hi, I think it has been fixed in the PR https://github.com/apache/incubator-echarts/pull/11186 . It will be included in the version 4.5.0
