### ISSUE TITLE
series的legend在该series所在grid中显示

### ISSUE THREAD

**Issue by keepuse** [apache/incubator-echarts#10949]
问题简述 (One-line summary)
希望series的legend在该series所在grid中显示

版本及环境 (Version & Environment)
ECharts 版本 : v4.2.1.rc1

重现步骤 (Steps to reproduce)
无

期望结果 (Expected behaviour)
当前版本是series的全部legend集合在某个地方，希望可以提供一种配置方式，使存在于不同grid的series的legend分别出现在对应的grid位置

**Comment by deqingli** [comment]
Please give the example link in echarts [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), or provide echarts `option`, and any other more detailed message for us to debug.
