### ISSUE TITLE
如何让折线图按照时间顺序连线而不是按照数据顺序连线？

### ISSUE THREAD

**Issue by sjtuzwj** [apache/incubator-echarts#10941]
### Version
4.2.1

### Steps to reproduce
我使用了一个line time的折线图，横坐标是时间
![捕获](https://user-images.githubusercontent.com/32933716/62117335-53d5ec80-b2ee-11e9-8584-678440324ba4.JPG)

### What is expected?
按照时间顺序连线

### What is actually happening?
按照数据顺序连线

---
因为我们后端分页，所以时间是乱序的，后面插入的数据可能时间更早，结果有些连线就往前连接

**Comment by pissang** [comment]
可以把数据按照时间排序一下

**Comment by velocity10yrs** [comment]
后台出数据前order by一下，或者你这边用流程控制加数据前排个序、试试sort( )。
