### ISSUE TITLE
graph关系图links存在，线不存在

### ISSUE THREAD

**Issue by wangdi244** [apache/incubator-echarts#10957]
### Version
4.2.1

### Steps to reproduce
只能上传截图

### What is expected?
希望点与点之间有连线

### What is actually happening?
有的点有，有的没有

![image](https://user-images.githubusercontent.com/13075509/62360323-1c17b080-b54b-11e9-8975-62730799ade8.png)

**Comment by deqingli** [comment]
Please give the example link in echarts [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), or provide echarts `option`, and any other more detailed message for us to debug.

**Comment by wangdi244** [comment]
I used the Gallery example to solve the problem. Thank you.
