### ISSUE TITLE
设定yAxis的max,min和splitNumber之后变成双y轴

### ISSUE THREAD

**Issue by xiaoswaii** [apache/incubator-echarts#10953]
### Version
4.2.1

### Steps to reproduce
设定yAxis的max,min和splitNumber之后变成双y轴，但是不要使用双轴，请问是为什么会这样？

### What is expected?
设定之后还是单轴

### What is actually happening?
设定yAxis的max,min和splitNumber之后变成双y轴

**Comment by deqingli** [comment]
Please give the example link in echarts [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), or provide echarts `option`, and any other more detailed message for us to debug.
