### ISSUE TITLE
Custom axis ticks min

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/incubator-echarts#10950]
### What problem does this feature solve?
We want to start rendering the axis ticks (and axis lines) after a specific value.
This is useful because we render charts with custom x axis that is formatted as month year (MMM YYYY) format 
and we would like to show the axis ticks/lines only on the start of the year e.g. Jan 2018.

e.g. In our dataset an x value of 434 represents Feb 2006, 435 represents Mar 2006 and so on and so forth.

### What does the proposed API look like?
A new field should be added as 
xAxis.minAxisTick which will be the minimum value where the axis ticks/lines will start rendering in the grid.
This option shouldn't affect the axis tick on the start of the axis.

![LineChartMonthError](https://user-images.githubusercontent.com/890368/62299094-f4f2ad80-b47c-11e9-8257-65c293995bfd.png)

e.g. in the screenshot you can see the labels are on the following positions
 Feb 2006, Feb 2007, Feb 2008, Feb 2009, Feb 2010.
and the desired labels should be as follows :
 Feb 2006, Jan 2007, Jan 2008, Jan 2009, Jan 2010.
This should be achieved by setting xAxis.minAxisTick to e.g. 445 which represents the value for Jan 2007. Or to 11, to indicate how many axis ticks/lines to skip, before starting drawing them.

**Comment by deqingli** [comment]
You can use [xAxis.min](https://www.echartsjs.com/option.html#xAxis.min), just like this [example](https://www.echartsjs.com/examples/editor.html?c=custom-profile).

**Comment by MINDoSOFT** [comment]
Hi there,

using xAxis.min will hide the data before xAxis.min.
I would like the data to appear, but the ticks to start rendering exactly on xAxis.min.

Is that possible ?

**Comment by Ovilia** [comment]
@MINDoSOFT Hi. I didn't quite understand this requirement. Why would you want *the data to appear, but the ticks to start rendering exactly on xAxis.min*? The viewer may get confused because they would expect the data on the left side to be with the minimum x value.

**Comment by MINDoSOFT** [comment]
Basically I want to I achieve what is shown in this screenshot.

![EchartsXAxisFeature](https://user-images.githubusercontent.com/890368/64018980-9a5d7780-cb36-11e9-8776-19e5bb63f422.png)

Data starts from Feb 2006 (or any month except January) but I want to render the next x axis tick on Jan 2007 because it makes more sense for someone looking at a chart where the x axis represents months, for the axis ticks/lines to appear when the year changes (e.g. January).

I hope that helps !

**Comment by Ovilia** [comment]
Sorry for the late reply.
I didn't quite get the idea since it seems a little strange for me to see the gap between `Feb 2006` and `Jan 2007` is not the same as others.

**Comment by mtuzinskiy** [comment]
This was a perfectly valid request. @MINDoSOFT  wanted to show the ticks with interval of 1 year, at certain date annually.  
@MINDoSOFT  what was the workaround for you?

**Comment by MINDoSOFT** [comment]
Hi there!

I switched jobs in the mean time. I think I couldn't come up with a
solution then.

Sorry I can't be of any help.
