### ISSUE TITLE
Stacking not working properly in bar chart when dataZoom toolbox is active

### ISSUE THREAD

**Issue by beda42** [apache/incubator-echarts#10972]
### Version
4.2.1

### Reproduction link
[http://jsfiddle.net/t51qgve2/1/](http://jsfiddle.net/t51qgve2/1/)

### Steps to reproduce
The fiddle shows it all. Just create a bar chart with stacked series and add a toolbox with the dataZoom feature. In this case, the columns will overflow the top of the Y axis. It seems the range for Y is not recalculated after stacking the data.

### What is expected?
The Y axis to have the range of the stacked data

### What is actually happening?
The Y axis has the range of the unstacked data

---
This was already reported here but was closed due to inactivity: #10193

**Comment by deqingli** [comment]
#8520

**Comment by deqingli** [comment]
#8069

**Comment by Ovilia** [comment]
Many similar issues here. If someone is going to fix this, please make sure test the related issues.

**Comment by akenverus** [comment]
This issue still exists.

**Comment by akenverus** [comment]
This happens when dataZoom toolbox is active and acuto-scaling is `true`.

**Comment by akenverus** [comment]
Here is a reproducible example:
https://codesandbox.io/p/sandbox/stacked-area-chart-gywk93

Try to zoom-in/zoom-out
