### ISSUE TITLE
在uni小程序中如何使用精简版echarts.js

### ISSUE THREAD

**Issue by DickLicha** [apache/incubator-echarts#10974]
### Version
4.2.1

### Steps to reproduce
我把npm 安装的echart    import * as echarts from 'echarts'库换成精简版的echarts.min.js在启动的时候抛出-----》文件查找失败：'echarts'

### What is expected?
vue正确引用精简版 echarts.min.js

### What is actually happening?
抛出   文件查找失败：'echarts'

**Comment by Ovilia** [comment]
试一下 `import * as echarts from 'echarts/dist/echarts.min'`？
