### ISSUE TITLE
Lack of Y axis label notation in Stacked bar when reducing browser window

### ISSUE THREAD

**Issue by biue8765** [apache/incubator-echarts#10973]
### Version
4.1.0-release

### Steps to reproduce
If you reduce or expand the height of the chrome browser window, the Y-axis label notation of the stacked bar chart may appear and disappear. For example, if there are six label notation with a bar chart, if you reduce the browser window, the label information will be displayed by suddenly showing three existing label notation or disappearing the middle bar chart label notation. Each time I reduce the height of the browser window and expand it, the label display information changes.

### What is expected?
All Y-axis label should be appeared

### What is actually happening?
Some of Y-axis label is disappeared

**Comment by deqingli** [comment]
Please give the example link in echarts [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), or provide echarts `option`, and any other more detailed message for us to debug, Thank you.
