### ISSUE TITLE
echarts中使用bmap时候showTip无效

### ISSUE THREAD

**Issue by chaofan-rensheng** [apache/incubator-echarts#10985]
### Version
4.2.1

### Steps to reproduce
this.myEacharts.dispatchAction({
        type: 'showTip'
      })

### What is expected?
showtTip能够控制toolip的显示隐藏

### What is actually happening?
showTip无效

**Comment by deyihu** [comment]
@chaofan-rensheng  

https://gallery.echartsjs.com/editor.html?c=xBFQwX0MJp&v=3

**Comment by chaofan-rensheng** [comment]
@deyihu 
`
data() {
    return {
      myEacharts: null,
      geoCoordMap: {
        '杭州': [120.19, 30.26]
      }
    }
  },
  mounted() {
    this.initEcharts()
  },

  methods: {
    initEcharts() {
      this.myEacharts = echarts.init(document.getElementById(this.id))
      this.setOptions()
    },

    convertData(data) {
      var res = []
      for (var i = 0; i < data.length; i++) {
        var geoCoord = this.geoCoordMap[data[i].name]
        if (geoCoord) {
          res.push({
            name: data[i].name,
            value: geoCoord.concat(data[i].value)
          })
        }
      }

      return res
    },

    setOptions() {
      var option = {
        // backgroundColor: 'red',
        tooltip: {
          trigger: 'item',
          padding: 0,
          enterable: true,
          triggerOn: 'none',
          transitionDuration: 1,
          textStyle: {
            color: 'red',
            decoration: 'none'
          },
          formatter: function(params) {
            var tipHtml = '<div class="tipHtml">' + '000000' + '</div>'
            return tipHtml
          }

        },

        bmap: {
          center: this.mapData,
          zoom: 12,
          roam: true,
          background: '#33345F',
          mapStyle: {
            styleJson: [
              {
                'featureType': 'water',
                'elementType': 'all',
                'stylers': {
                  'color': '#031628'
                }
              },
              {
                'featureType': 'land',
                'elementType': 'geometry',
                'stylers': {
                  'color': '#000102'
                }
              },
              {
                'featureType': 'highway',
                'elementType': 'all',
                'stylers': {
                  'visibility': 'off'
                }
              },
              {
                'featureType': 'arterial',
                'elementType': 'geometry.fill',
                'stylers': {
                  'color': '#000000'
                }
              },
              {
                'featureType': 'arterial',
                'elementType': 'geometry.stroke',
                'stylers': {
                  'color': '#0b3d51'
                }
              },
              {
                'featureType': 'local',
                'elementType': 'geometry',
                'stylers': {
                  'color': '#000000'
                }
              },
              {
                'featureType': 'railway',
                'elementType': 'geometry.fill',
                'stylers': {
                  'color': '#000000'
                }
              },
              {
                'featureType': 'railway',
                'elementType': 'geometry.stroke',
                'stylers': {
                  'color': '#08304b'
                }
              },
              {
                'featureType': 'subway',
                'elementType': 'geometry',
                'stylers': {
                  'lightness': -70
                }
              },
              {
                'featureType': 'building',
                'elementType': 'geometry.fill',
                'stylers': {
                  'color': '#000000'
                }
              },
              {
                'featureType': 'all',
                'elementType': 'labels.text.fill',
                'stylers': {
                  'color': '#857f7f'
                }
              },
              {
                'featureType': 'all',
                'elementType': 'labels.text.stroke',
                'stylers': {
                  'color': '#000000'
                }
              },
              {
                'featureType': 'building',
                'elementType': 'geometry',
                'stylers': {
                  'color': '#022338'
                }
              },
              {
                'featureType': 'green',
                'elementType': 'geometry',
                'stylers': {
                  'color': '#062032'
                  // 'visibility': 'off'
                }
              },
              {
                'featureType': 'boundary',
                'elementType': 'all',
                'stylers': {
                  'color': '#465b6c'
                }
              },
              {
                'featureType': 'manmade',
                'elementType': 'all',
                'stylers': {
                  'color': '#022338'
                }
              },
              {
                'featureType': 'label',
                'elementType': 'all',
                'stylers': {
                  // 'visibility': 'off'
                }
              },
              {
                'featureType': 'poi',
                'elementType': 'all',
                'stylers': {
                  'color': '#022338'
                  // 'visibility': 'off'
                }
              }
            ]
          }
        },

        series: [
          {
            name: '',
            type: 'scatter',
            coordinateSystem: 'bmap',
            // data: this.convertData(this.mapData),
            symbolSize: function(val) {
              return val[2] / 10
            },
            label: {
              normal: {
                formatter: '{b}',
                position: 'right',
                show: false
              },
              emphasis: {
                show: true
              }
            },
            itemStyle: {
              normal: {
                color: 'purple'
              }
            }
          },
          {
            name: '',
            type: 'effectScatter',
            coordinateSystem: 'bmap',
            data: this.convertData([{ 'name': '杭州' }]),
            symbolSize: function(val) {
              return 20
            },
            showEffectOn: 'render',
            rippleEffect: {
              brushType: 'stroke'
            },
            hoverAnimation: true,
            label: {
              normal: {
                formatter: '{b}',
                position: 'right',
                show: true
              }
            },
            itemStyle: {
              normal: {
                color: '#50E3C2',
                shadowBlur: 10,
                shadowColor: '#333'
              }
            },
            zlevel: 1
          }
        ]
      }

      this.myEacharts.setOption(option)
      var bmap = this.myEacharts.getModel().getComponent('bmap').getBMap()
    },

    click() {
      console.log('click click click')
      this.myEacharts.dispatchAction({
        type: 'showTip'
      })
    }
`

**Comment by chaofan-rensheng** [comment]
@deyihu   我这个就是点着没反应

**Comment by deyihu** [comment]
@chaofan-rensheng 

https://codepen.io/deyihu/full/MNXdXX

你给的这个代码不完整的吧 :cry:

**Comment by Ovilia** [comment]
代码跑起来没问题，这个 issue 的问题是什么？

**Comment by chaofan-rensheng** [comment]
@Ovilia  @deyihu   这个好像是我代码的问题    现在ok了
