### ISSUE TITLE
X-axis value does not appear if first item in y-dimension of 'line' series' dataset is null or a string.

### ISSUE THREAD

**Issue by awallace689** [apache/incubator-echarts#10988]
### Version
4.2.1

### Steps to reproduce
Create dataset used in a line series where the first y-value is either a string or null.
Y-axis type is 'value,' x-axis type is 'category'. 

### What is expected?
The x-value is still included in the chart with no y-output.

### What is actually happening?
The x-value is not graphed in the chart.

If the dataset looks like: 
[["8/1/19", null],
["8/2/19", 27.4],
["8/3/19", 27.4],
["8/4/19", 27.4],
["8/5/19", 27.4]],
only points at index 1-4 will be included. 

If it looked like:
[["8/1/19", 27.4],
["8/2/19", 27.4],
["8/3/19", null],
["8/4/19", 27.4],
["8/5/19", 27.4]],
all points would be graphed, including "8/3/19" on the x-axis despite not having a corresponding point.

To re-iterate: In the first case, only 4 points are graphed with the x-axis label "8/1/19" not appearing. In the second case, 5 points are still 'graphed,' although there is no y-output for x-axis value '8/3/19.' This should be the same behavior in the first case.

---
If there is a workaround, please let me know. Thanks!

**Comment by Ovilia** [comment]
Can you provide a demo?
