### ISSUE TITLE
Resize / ratio symbolSize

### ISSUE THREAD

**Issue by KonradHolubek** [apache/incubator-echarts#10980]
### What problem does this feature solve?
Hi, 

I am using a "graph" type. In "data", I'm specifying the symbolSize. The problem is when I have a high number for the symbolSize. In that case, the bubble is bigger than the graph area. I would like to automatically resize/adapt the bubble to the graph area. Is that possible ? 

Screenshot of my issue: 
https://divers-konrad.s3.amazonaws.com/graph_symbolize_too_big.png

**Comment by deqingli** [comment]
sorry, currently we don't support this feature.

**Comment by Ovilia** [comment]
@KonradHolubek What's the expected effect?

**Comment by tomislavbegic** [comment]
Do you now support this feature?
