### ISSUE TITLE
4.2.0版本，使用svg渲染的地图。谷歌浏览器下，阴影显示有条纹；鼠标移动上坐标之后，鼠标有文字提示，移出鼠标之后，提示的数据不会自动清除。ie浏览器、火狐浏览器，没有显示文字。

### ISSUE THREAD

**Issue by sikynet** [apache/incubator-echarts#10996]
### Version
4.2.0-rc.1

### Steps to reproduce
1：echarts创建一个map的地图，并且使用svg渲染。
2：在ie浏览器、火狐浏览器、谷歌浏览器上，分别查看。

### What is expected?
修复svg渲染的地图在各个浏览器下正常显示。

### What is actually happening?
svg地图在各个浏览器下显示不一致，ie、火狐、edge下不响应事件。谷歌下鼠标提示没有自动清除。

**Comment by Ovilia** [comment]
Duplicate of #11019

**Comment by sikynet** [comment]
关系图例子：
https://www.echartsjs.com/examples/editor.html?c=graph-webkit-dep&renderer=svg

**Comment by Ovilia** [comment]
近期会修复一下 SVG 文字相关的问题

**Comment by pissang** [comment]
Hi, map shadow issue has been fixed in 4.4.0

I created a new issue for tracking the label won't disappear issue https://github.com/apache/incubator-echarts/issues/11543

Closing this one.
