### ISSUE TITLE
网页引用echart地图时无法显示

### ISSUE THREAD

**Issue by weizihahaha** [apache/incubator-echarts#10999]
### Version
4.2.1

### Steps to reproduce
运行程序后报错，提示：Map china not exists. You can download map file on http://echarts.baidu.com/download-map.html
对应网站提示暂停地图下载功能。

### What is expected?
请问什么大概过多久可以恢复地图的使用？

### What is actually happening?
地图无法显示。

**Comment by GFwer** [comment]
echarts 其实内置了中国地图和世界地图，引入`echarts/map/js/china.js`即可

**Comment by weizihahaha** [comment]
我已经引入了china.js文件，但是会提示这个错误，并且官网上写出了暂停地图使用功能。我想请问报这个错误是不是和咱们官网暂停使用地图功能有关？如果是请问什么时候能恢复？

**Comment by weizihahaha** [comment]
我已经引入了china.js文件，但是会提示这个错误，并且点击错误链接跳转到官网，上面写出了暂停地图使用功能。我想请问报这个错误是不是和咱们官网暂停使用地图功能有关？如果是请问什么时候能恢复？



------------------ 原始邮件 ------------------
发件人: "Fawen"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 晚上6:36
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "平凡的快乐不廉价"<sas_0@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/incubator-echarts] 网页引用echart地图时无法显示 (#10999)




echarts 其实内置了中国地图和世界地图，引入echarts/map/js/china.js即可

**Comment by GFwer** [comment]
这个错误就是所需的地图数据没有引入的时候提示的，官网上下载的地图数据就是map文件夹中的文件，肯定是你没有正确引入，你可以先试试在 codepen 或者 codesandbox 上排除其他因素，引入 echarts 和china.js尝试一下，应该就可以的

**Comment by weizihahaha** [comment]
您说的两个js文件我都已经引入了，这个问题和网络状态有关系吗？我刷新十几次，里面就会有一次两次能显示出来，没有任何错误。这种有时行有时不行的情况是为什么？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Fawen <notifications@github.com>
发送时间: 2019年8月13日 14:52
收件人: apache/incubator-echarts <incubator-echarts@noreply.github.com>
抄送: weizihahaha <sas_0@qq.com>, Author <author@noreply.github.com>
主题: 回复：[apache/incubator-echarts] 网页引用echart地图时无法显示 (#10999)




这个错误就是所需的地图数据没有引入的时候提示的，官网上下载的地图数据就是map文件夹中的文件，肯定是你没有正确引入，你可以先试试在 codepen 或者 codesandbox 上排除其他因素，引入 echarts 和china.js尝试一下，应该就可以的

**Comment by pissang** [comment]
@weizihahaha 应该是你引入的方式有问题。跟网络没关系，echarts 现在也没限制地图的使用（只是官网上不显示提供地图数据了）
