### ISSUE TITLE
将渲染完成的图表代码复制粘贴在其他页面上，不显示图表

### ISSUE THREAD

**Issue by zpf96126** [apache/incubator-echarts#10990]
### Version
4.2.1

### Steps to reproduce
1、在A页面初始化并创建图表，将图表的代码保存到本地的js文件中
2、在B页面读取js文件，加载该图表

### What is expected?
能显示出图表

### What is actually happening?
图表代码加载成功，但是不显示图表

**Comment by deqingli** [comment]
Please give the example link in echarts [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), or provide echarts `option`, and any other more detailed message for us to debug.

**Comment by deqingli** [comment]
Since the A page has been rendered, it means that ECharts itself has no problem. The B page fails to load the chart, It may be some other mistake in the project. You can check it.

**Comment by zpf96126** [comment]
在A页面渲染图表，将其对应的代码`<div _echarts_instance_="ec_1565318300904" style="height: 100%; -webkit-tap-highlight-color: transparent; user-select: none; position: relative;" class="echart" id="_2"><div style="position: relative; overflow: hidden; width: 100px; height: 100px; padding: 0px; margin: 0px; border-width: 0px;"><canvas style="position: absolute; left: 0px; top: 0px; width: 100px; height: 100px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;" height="100" width="100" data-zr-dom-id="zr_0"></canvas></div><div></div></div>`加载到B页面上，B页面不显示图表
