### ISSUE TITLE
Some of the tree charts haven't been generated successfully.

### ISSUE THREAD

**Issue by megstar** [apache/incubator-echarts#10997]
### Version
4.2.1

### Steps to reproduce
1. Download in ZIP format from [GitHub](https://github.com/apache/incubator-echarts).
2. Unzip the ZIP file.
3. Open the following files.
  * /incubator-echarts-master/test/tree-basic.html
  * /incubator-echarts-master/test/tree-image.html
  * /incubator-echarts-master/test/tree-orient-right-left.html
  * /incubator-echarts-master/test/tree-orient-top-bottom.html
  * /incubator-echarts-master/test/tree-radial.html
  * /incubator-echarts-master/test/tree-roam.html
  * /incubator-echarts-master/test/tree-vertical.html

### What is expected?
The tree chart has been generated successfully.

### What is actually happening?
A white screen appears and tree chart hasn't been generated successfully.

**Comment by deqingli** [comment]
You must install the dependencies through `npm` and build `echarts`, then you can see the results. There must be some error in your Chrome.
