### ISSUE TITLE
Can't change `scroll` type legend to `plain` type legend

### ISSUE THREAD

**Issue by LiuLingyang** [apache/incubator-echarts#11000]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xp9j1rfiOF&v=1](https://gallery.echartsjs.com/editor.html?c=xp9j1rfiOF&v=1)

### Steps to reproduce
见链接

### What is expected?
分页图例切回普通图例时生效

### What is actually happening?
分页图例切回普通图例时不生效

**Comment by deqingli** [comment]
Hi, it's work on my computer, see the following picture.
![image](https://user-images.githubusercontent.com/13548221/62990152-7be05680-be7d-11e9-812d-46311d756037.png)

**Comment by deqingli** [comment]
So I don't understand what your problem is? Please provide a more detailed message.

**Comment by LiuLingyang** [comment]
例子最下方我写了个定时器来更改legend，但似乎并不生效

**Comment by pissang** [comment]
应该是个 bug

**Comment by pissang** [comment]
Fixed in https://github.com/apache/incubator-echarts/pulls?q=is%3Apr+is%3Aclosed
