### ISSUE TITLE
地图纹理填充

### ISSUE THREAD

**Issue by cn-xufei** [apache/incubator-echarts#11015]
### What problem does this feature solve?
满足地图的背景图纹理填充的效果

### What does the proposed API look like?
geo.itemStyle.areaColor
{
     image: img
},

尝试用HTMLImageElement纹理填充，结果很不理想，背景很虚幻。。。
https://gallery.echartsjs.com/editor.html?c=xPEkeMSf48&v=2

**Comment by cn-xufei** [comment]
![image](https://user-images.githubusercontent.com/14144811/62943095-47808200-be0c-11e9-9e06-a78c200caaab.png)
想要达成这种效果

**Comment by cn-xufei** [comment]
没有这个功能的话，echarts很难做出好看的地图效果

**Comment by Ovilia** [comment]
Fixed in https://github.com/apache/incubator-echarts/pull/11272 . It is going to be released in v4.4.0.

**Comment by cn-xufei** [comment]
关闭的还能回复吗😂
@Ovilia 你好羡澈，填充效果已经出来了，but
![image](https://user-images.githubusercontent.com/14144811/65474648-3c128300-deaf-11e9-90c6-24ec53be4616.png)
我想实线这种效果
然后用了sketch里一样的填充
![image](https://user-images.githubusercontent.com/14144811/65474682-5f3d3280-deaf-11e9-9a9f-05c8e701a8c4.png)
尺寸是200x200
得到的结果是👇
![image](https://user-images.githubusercontent.com/14144811/65474718-7aa83d80-deaf-11e9-865e-5125f6f911b8.png)
请问目前能做到效果图那样的填充吗？

**Comment by pissang** [comment]
@cn-xufei 包含这个修复的新版本还没发布，你是用的 master 最新代码吗？

**Comment by cn-xufei** [comment]
@pissang是的，我看到close了所以赶紧merge看了下效果

**Comment by Ovilia** [comment]
@cn-xufei 提供一下贴图，我试一下

**Comment by cn-xufei** [comment]
@Ovilia 
```
data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAyIiBoZWlnaHQ9IjIwMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+PGRlZnM+PHBhdHRlcm4gaWQ9ImIiIHdpZHRoPSI3OCIgaGVpZ2h0PSI3OCIgeD0iNDE4IiB5PSIxMTAiIHBhdHRlcm5Vbml0cz0idXNlclNwYWNlT25Vc2UiPjx1c2UgeGxpbms6aHJlZj0iI2EiLz48L3BhdHRlcm4+PGltYWdlIGlkPSJhIiB3aWR0aD0iNzgiIGhlaWdodD0iNzgiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBRTRBQUFCT0NBWUFBQUNPcWlBZEFBQUFCR2RCVFVFQUFMR041ZklBS1FBQUFSNUpSRUZVZUFIdDJyRUp3MEFBQkVIWkRhai9HbDJFM01Od2dlRFgrWXBuL2xCZ2RGM0QzLzE3bnVIanBvOWFuKzA3UGQxQkR3c09MenU0NEZBQXN4WVhIQXBnMXVLQ1F3SE1XbHh3S0lCWml3c09CVEJyY2NHaEFHWXRMamdVd0t6RkJZY0NtSDNXZnluak9jN08zbndKNjdQMWpzT3RCeGNjQ21EVzRvSkRBY3hhWEhBb2dGbUxDdzRGTUd0eHdhRUFaaTB1T0JUQXJNVUZod0tZdGJqZ1VBQ3pGaGNjQ21EVzRvSkRBY3hhWEhBb2dGbUxDdzRGTUd0eHdhRUFaaTB1T0JUQXJNVUZod0tZdGJqZ1VBQ3pGaGNjQ21EVzRvSkRBY3o2WEIvaHB0bjZrL2psNGRabjZ4Mkh0eE5jY0NpQVdZc0xEZ1V3YTNIQm9RQm1MUzQ0Rk1Dc3hRV0hBcGkxdU9CUUFMTVdGeHdLWU5iaWdrTUJ6Rm9jd3YwQlFZWVlWZGJJakNRQUFBQUFTVVZPUks1Q1lJST0iLz48L2RlZnM+PHBhdGggZD0iTTQ5NiAxODhoMjAwdjIwMEg0OTZ6IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtNDk1IC0xODcpIiBmaWxsPSJ1cmwoI2IpIiBzdHJva2U9IiM0RUY3RkYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgc3Ryb2tlLW9wYWNpdHk9Ii42Ii8+PC9zdmc+
```
