### ISSUE TITLE
4.2.0版本 一个页面里，谷歌浏览器显示多个同一类型的柱图，如果有1个是canvas渲染，其他图是svg渲染，那么svg渲染的图形的renderer是svg，但是显示的效果却是模糊的。如果全部柱图都使用svg渲染，又可以看到是清晰的。

### ISSUE THREAD

**Issue by sikynet** [apache/incubator-echarts#11019]
### Version
4.2.0-rc.1

### Steps to reproduce
一个页面里，放置多个柱图，其中一个柱图使用canvas渲染，其他柱图使用svg渲染，那么所有柱图看到的都是模糊的，但是如果全部柱图都使用svg渲染，又可以看到是清晰的。

### What is expected?
svg显示可以在一个页面根据自己图形的设置显示。

### What is actually happening?
设置了svg还是一样模糊。

**Comment by Ovilia** [comment]
请检查自己的代码

**Comment by sikynet** [comment]
鼠标悬浮文字有残留例子：
https://www.echartsjs.com/examples/editor.html?c=graph-webkit-dep&renderer=svg

**Comment by Ovilia** [comment]
残影和这个 issue 有什么关系？

**Comment by sikynet** [comment]
你把我提的另一个残影的issues关了 ，说与这个重复。。 #10996

**Comment by Ovilia** [comment]
不好意思，标题比较像，我以为是一个问题

**Comment by Ovilia** [comment]
那么，这个问题怎么复现？
https://jsfiddle.net/xkavcjd9/ 我测试了一下，没有复现
