### ISSUE TITLE
I use the custom symbol in 'candlestick' chart，click the lenged 

### ISSUE THREAD

**Issue by ahonghong** [apache/incubator-echarts#11018]
### Version
3.4.0

### Steps to reproduce
设置symbol属性，使用自定义图标，然后生成图标

### What is expected?
图标和折现都正常显示

### What is actually happening?
图标没有正常显示

---
设置中的symbol使用 `image://data.....`赋值或者`image://https.........`

**Comment by ahonghong** [comment]
当我点击length上的图标时，下面图表中的线和点可以正确隐藏，但是当我再次点击时，只有线重新出现，我自定义的点不会出现。

**Comment by Ovilia** [comment]
请提供代码 https://gallery.echartsjs.com/editor.html

**Comment by webstermobile** [comment]
同样的问题，请问解决了吗

**Comment by pissang** [comment]
Same issue with #11018 . Closed
