### ISSUE TITLE
柱状图markArea覆盖不全

### ISSUE THREAD

**Issue by Cyycl** [apache/incubator-echarts#11017]
### What problem does this feature solve?
- markArea在柱状图下，覆盖不到区域内 第一个柱子的前半部分 和 最后一个柱子的后半部分

- 期望效果如下：

![](https://s2.ax1x.com/2019/08/14/miKeD1.jpg)

- 代码链接：

[https://codepen.io/AliJser/pen/vYBLzoY](https://codepen.io/AliJser/pen/vYBLzoY)

### What does the proposed API look like?
- 可以覆盖整个区域

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#graphic.elements-rect 可以自己画矩形，位置根据 grid 的来，然后乘个百分比就是横坐标的位置

**Comment by Cyycl** [comment]
> https://echarts.apache.org/zh/option.html#graphic.elements-rect 可以自己画矩形，位置根据 grid 的来，然后乘个百分比就是横坐标的位置

----------
@Ovilia ，怎么获取x轴和y轴基于grid偏移量？

**Comment by Cyycl** [comment]
> https://echarts.apache.org/zh/option.html#graphic.elements-rect 可以自己画矩形，位置根据 grid 的来，然后乘个百分比就是横坐标的位置

---------

@Ovilia , 怎么获取 x轴 和 y轴 基于grid 的偏移量？

**Comment by natee** [comment]
@Ovilia 
graphic来解决这个问题是不是过于复杂，且rect.shape.width只能设置number，不支持百分比，当图形随浏览器变化时显示会错误
