### ISSUE TITLE
Tooltip中设置了enterable:true   但是不能复制提示框浮层的文本内容

### ISSUE THREAD

**Issue by ahahaah** [apache/incubator-echarts#11012]
### Version
4.2.1

### Steps to reproduce
在tooltip中，已经设置了enterable:true   但仅仅只能鼠标进入，文本信息不能被选中，也不能被复制

### What is expected?
选中，复制tooltip中的文本信息

### What is actually happening?
文本信息不能被选中，也不能被复制

**Comment by ahahaah** [comment]
@pissang

**Comment by ahahaah** [comment]
已解决，修改了echarts源码，在div中添加了contenteditable属性

**Comment by fashiontai** [comment]
源码是在创建的echarts的dom上加了user-select: none;你可以在你的fommater里面的dom修改user-select:text
