### ISSUE TITLE
feat: Pie expansion animation behavior 

### ISSUE THREAD

**Issue by MohammadYounes** [apache/incubator-echarts#11029]
### Version
4.2.1

### Steps to reproduce
When loading Pie series along with data, the expansion animation is continues,

![continues](https://user-images.githubusercontent.com/4712046/63129101-55c2cf80-bfbf-11e9-95d5-df17b2058904.gif)

Code Sample:
```js
var data = [
    {"name":"A1B·1","value":92386},
    {"name":"BB1·","value":90611},
    {"name":"1BB","value":12596},
    {"name":"2BA·1","value":9438},
    {"name":"1BA","value":10049}
]
    
option = {
    series : [
        {
            type: 'pie',
            animationType:'expansion',
            animationDuration:5000,
            startAngle:0,
            endAngle:360,
            radius : ['50%','80%'],
            center: ['40%', '50%'],
            data: data // set along with series
        }
    ]
};
```

But when setting the data while the series has already been added, the expansion animation becomes discrete (per pie piece).

![discrete](https://user-images.githubusercontent.com/4712046/63129138-73903480-bfbf-11e9-80e7-7af65d575166.gif)

Code Sample:
```js
var data = [
    {"name":"A1B·1","value":92386},
    {"name":"BB1·","value":90611},
    {"name":"1BB","value":12596},
    {"name":"2BA·1","value":9438},
    {"name":"1BA","value":10049}
]
    
option = {
    series : [
        {
            type: 'pie',
            animationType:'expansion',
            animationDuration:5000,
            animationDurationUpdate:5000,
            startAngle:0,
            endAngle:360,
            radius : ['50%','80%'],
            center: ['40%', '50%']
        }
    ]
};

//set after rendering
setTimeout(function() {
   myChart.setOption({
       series:[
           {
            data: data
           }
        ]
   })
}, 500);
```

Is there away to force continues animation even if data is added later?

### What is expected?
Continues Pie Chart Animation

### What is actually happening?
Discrete Pie Chart Animation

**Comment by pissang** [comment]
It's the difference between entry animation and transition animation.

+ The first one is entry animation, it is used when series is first created.

+ The second one is transition animation, it is used when series already exists but the data is changed.

**Comment by MohammadYounes** [comment]
@pissang I understand. However, This is a simulation of the issue. In my case I want to replace the whole data and the discrete animation looks odd. Is there a way to force the entry animation without recreating the whole series ?

**Comment by pissang** [comment]
@MohammadYounes  Sorry, currently the only way to use the first animation type is creating a new series. But it's a good idea to add a new config to specify the animation type.
