### ISSUE TITLE
chrome浏览器下3d图使用特效会报错，请问如何解决？

### ISSUE THREAD

**Issue by Mrzhangqc** [apache/incubator-echarts#11021]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=bar3d-voxelize-image&gl=1](https://www.echartsjs.com/examples/editor.html?c=bar3d-voxelize-image&gl=1)

### Steps to reproduce
1.echarts官网实例选项
2.选GL实例
3.3D 柱状图
4.点击Voxelize image

### What is expected?
chrome浏览器下可以正常使用

### What is actually happening?
 chrome 会报错 editor.js:434 Error: ERROR: 0:377: 'GL_EXT_shader_texture_lod' : extension is not supported

**Comment by Ovilia** [comment]
https://stackoverflow.com/questions/40912060/how-to-enable-opengl-extension-gl-ext-shader-framebuffer-fetch-on-android

**Comment by Mrzhangqc** [comment]
> https://stackoverflow.com/questions/40912060/how-to-enable-opengl-extension-gl-ext-shader-framebuffer-fetch-on-android

thanks
