### ISSUE TITLE
发现bug:横纵坐标系类的图表的刻度标签显示样式不一致

### ISSUE THREAD

**Issue by comvir** [apache/incubator-echarts#11035]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=bar-tick-align](https://www.echartsjs.com/examples/editor.html?c=bar-tick-align)

### Steps to reproduce
设置xAxis[0].axisLabel.interval=0
如下所示
```
xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            },
            axisLabel:{
                interval:0
            }
        }
    ]
```

### What is expected?
刻度标签显示样式一致

### What is actually happening?
轴刻度标签的最后一个文字样式明显被加粗了

---
所有需要横纵轴的图表均存在此问题
问题截图
![效果对比_前](https://user-images.githubusercontent.com/7907986/63156650-bbf33500-c047-11e9-9117-c0622fe086d9.jpg)
![效果对比_后](https://user-images.githubusercontent.com/7907986/63156694-d2998c00-c047-11e9-8cbe-2f1d1f13b5fb.jpg)

**Comment by pissang** [comment]
没有发现该问题，可以截图看下么，估计是浏览器渲染的问题

**Comment by comvir** [comment]
已在问题中给出前后对比截图，浏览器是chrome

> 没有发现该问题，可以截图看下么，估计是浏览器渲染的问题

**Comment by pissang** [comment]
我这也可复现了，我们看下，谢谢反馈

**Comment by Ovilia** [comment]
同 #10304，这个问题 https://github.com/apache/incubator-echarts/commit/46a895101cf7af6b2d0fcf1f99b740ae1f42339a 修复了
