### ISSUE TITLE
How to Change the size of dot and how to start graph from zero?

### ISSUE THREAD

**Issue by rameezcubet** [apache/incubator-echarts#11045]
### Version
4.2.1

### Steps to reproduce
How to Change the size of the dot in line graph?
How to change the size of line graph dots and graph need to start from the left end of the chart?

https://user-images.githubusercontent.com/41043647/63245390-bed76b00-c27d-11e9-8ce6-47c8e4face23.png

### What is expected?
Need to change the size of line graph dots and graph need to start from the left end of the chart

### What is actually happening?
cant change the dot size checked in docs

---
https://user-images.githubusercontent.com/41043647/63245390-bed76b00-c27d-11e9-8ce6-47c8e4face23.png

**Comment by Ovilia** [comment]
To change the dot start position, please use [xAxis.boundaryGap](https://echarts.apache.org/en/option.html#xAxis.boundaryGap) if you want it to display at the beginning of the axis.
To change the dot size, please use [symbolSize](https://echarts.apache.org/en/option.html#series-scatter.symbolSize).
