### ISSUE TITLE
MarkLine消失问题

### ISSUE THREAD

**Issue by hou18103912159** [apache/incubator-echarts#11048]
### Steps to reproduce
当做动态图表的时候，MarkLine的值大于当前Y轴范围，导致MarkLine消失于图表上

### What is expected?
MarkLine存在于图表上

### What is actually happening?
MarkLine消失

---
建议MarkLine的值和当前Y轴最大值做对比，来定义Y轴的最终范围，从而避免MarkLine消失的情况出现。

**Comment by topvis** [comment]
参见：https://github.com/apache/incubator-echarts/issues/3637， 试试 `filterMode: 'disabled'` 是否能解决问题。
还有可以试试用line chart，而不是用markLine.

**Comment by hou18103912159** [comment]
好的，谢谢。 很抱歉，这么晚才回复，我们用 line chart 处理的。
