### ISSUE TITLE
堆叠折线图画线错乱

### ISSUE THREAD

**Issue by shiayoung** [apache/incubator-echarts#11043]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xhP6Krkq-3&v=3](https://gallery.echartsjs.com/editor.html?c=xhP6Krkq-3&v=3)

### Steps to reproduce
运行即可

### What is expected?
`联盟广告` 的在周日的值是 1 ，画出的点应该也是 1，但实际的点在 22 的位置

### What is actually happening?
`联盟广告` 的最后一个点在 1 的位置

**Comment by pissang** [comment]
去掉 stack
