### ISSUE TITLE
How to draw a vertical line using markline at specific X-axis value in a stacked bar graph

### ISSUE THREAD

**Issue by DhananjayaR** [apache/incubator-echarts#11059]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/xko8cvy6/2/](https://jsfiddle.net/xko8cvy6/2/)

### Steps to reproduce
Open the reproduction link (https://jsfiddle.net/xko8cvy6/2/).
![image](https://user-images.githubusercontent.com/5243795/63331724-ebf64d00-c353-11e9-936d-fdeac1ba4cf1.png)

It is not clear from the documentation about how to use the markline when Y-axis is of category type.

### What is expected?
I tried using using bellow code but it produced a horizontal line

`          markLine: {
            data: [
            {name: 'start', xAxis: 2000, yAxis: '0'},
            {name: 'end', xAxis: 2000, yAxis: '1'},
            ]
`

### What is actually happening?
Vertical line from xAxis value 2000

**Comment by pissang** [comment]
markLine data should be 2d, Try 

```js
markLine: {
            data: [   [
              {name: 'start', xAxis: 2000, yAxis: 0},
              {name: 'end', xAxis: 2000, yAxis: 1},
            ]   ]
          }
```

But in your case, there is no '0' in yAxis categories. So the markLine wont appear.

**Comment by DhananjayaR** [comment]
Thanks for the quick response @pissang. In a situation where I need to create a reference line (vertical line) from a certain x value when there's only one data set, how can I do it? 
 
https://user-images.githubusercontent.com/5243795/63331724-ebf64d00-c353-11e9-936d-fdeac1ba4cf1.png

**Comment by pissang** [comment]
You can simply do it like:

```js
markLine: {
   data: [ { name: 'xxxx', xAxis: 2000 } ]
}
```

Notice that in this case you don't need two value to specify start point and end point.

**Comment by DhananjayaR** [comment]
@pissang thank you very much

**Comment by SundayDelight** [comment]
> You can simply do it like:
> 
> ```js
> markLine: {
>    data: [ { name: 'xxxx', xAxis: 2000 } ]
> }
> ```
> 
> Notice that in this case you don't need two value to specify start point and end point.

Hi, I'm using this to draw a line as shown in the example, specifying only one value in 'xAxis' field. However, the console throws an error :
ngx-echarts.js:162 TypeError: Cannot read property 'coord' of undefined
    at markLineFilter (MarkLineView.js:125)
    at util.js:439
    at Array.filter (<anonymous>)
    at Object.filter (util.js:381)
    at createList (MarkLineView.js:346)
    at ExtendedClass.renderSeries (MarkLineView.js:249)
    at ExtendedClass.<anonymous> (MarkerView.js:61)
    at ExtendedClass.<anonymous> (Global.js:517)
    at Array.forEach (<anonymous>)
    at each (util.js:300)

Function markLineFilter is as follows :

```
function markLineFilter(coordSys, item) {
  if (coordSys.type === 'cartesian2d') {
    var fromCoord = item[0].coord;
    var toCoord = item[1].coord; // In case
    // {
    //  markLine: {
    //    data: [{ yAxis: 2 }]
    //  }
    // }

    if (fromCoord && toCoord && (ifMarkLineHasOnlyDim(1, fromCoord, toCoord, coordSys) || ifMarkLineHasOnlyDim(0, fromCoord, toCoord, coordSys))) {
      return true;
    }
  }

  return markerHelper.dataFilter(coordSys, item[0]) && markerHelper.dataFilter(coordSys, item[1]);
}
```

The line throwing an error is obviously the `var toCoord = item[1].coord; // In case` one, since I only pass one value. The markline still works as expected, so that's good, but is there a way to get rid of the error cluttering the console ? Thanks.

**Comment by dherault** [comment]
Also, don't forget to import the `MarkLineComponent`.

**Comment by micktg** [comment]
> Also, don't forget to import the `MarkLineComponent`.

Thanks. Interestingly, there wasn't a warning or error in the logs. Usually, there are messages if you forgot to import a component.

**Comment by ermaugustinas** [comment]
> > You can simply do it like:
> > ```js
> > markLine: {
> >    data: [ { name: 'xxxx', xAxis: 2000 } ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Notice that in this case you don't need two value to specify start point and end point.
> 
> Hi, I'm using this to draw a line as shown in the example, specifying only one value in 'xAxis' field. However, the console throws an error : ngx-echarts.js:162 TypeError: Cannot read property 'coord' of undefined at markLineFilter (MarkLineView.js:125) at util.js:439 at Array.filter () at Object.filter (util.js:381) at createList (MarkLineView.js:346) at ExtendedClass.renderSeries (MarkLineView.js:249) at ExtendedClass. (MarkerView.js:61) at ExtendedClass. (Global.js:517) at Array.forEach () at each (util.js:300)
> 
> Function markLineFilter is as follows :
> 
> ```
> function markLineFilter(coordSys, item) {
>   if (coordSys.type === 'cartesian2d') {
>     var fromCoord = item[0].coord;
>     var toCoord = item[1].coord; // In case
>     // {
>     //  markLine: {
>     //    data: [{ yAxis: 2 }]
>     //  }
>     // }
> 
>     if (fromCoord && toCoord && (ifMarkLineHasOnlyDim(1, fromCoord, toCoord, coordSys) || ifMarkLineHasOnlyDim(0, fromCoord, toCoord, coordSys))) {
>       return true;
>     }
>   }
> 
>   return markerHelper.dataFilter(coordSys, item[0]) && markerHelper.dataFilter(coordSys, item[1]);
> }
> ```
> 
> The line throwing an error is obviously the `var toCoord = item[1].coord; // In case` one, since I only pass one value. The markline still works as expected, so that's good, but is there a way to get rid of the error cluttering the console ? Thanks.

I'm getting the same error when using xAxis of type "time" has anyone found a fix?
