### ISSUE TITLE
[Found in test: map.html] SVG shadow error

### ISSUE THREAD

**Issue by Ovilia** [apache/incubator-echarts#11055]
### Version
4.2.1

### Steps to reproduce
Run `test/map.html` with SVG. Hover on the map.

### What is expected?
The SVG shadow is the same as Canvas.

Canvas (correct): 
![image](https://user-images.githubusercontent.com/779050/63314278-ad539900-c339-11e9-9f8e-cec60185c952.png)

### What is actually happening?
The SVG shadow is not the same as Canvas.

SVG (wrong):
![image](https://user-images.githubusercontent.com/779050/63314242-96ad4200-c339-11e9-8ac6-1a5b1f3abb61.png)

**Comment by pissang** [comment]
https://github.com/apache/incubator-echarts/issues/5429 Map with pattern also have a similar issue. Both are caused because map group has a very large scale value. I think they can be fixed together.
