### ISSUE TITLE
datazoom的slider在网页中不显示

### ISSUE THREAD

**Issue by gty1998** [apache/incubator-echarts#11063]
### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xe8K4EEG3M&v=1](https://gallery.echartsjs.com/editor.html?c=xe8K4EEG3M&v=1)

### Steps to reproduce
如gallery显示，开发过程中不会显示slider 但是在gallery中运行相同option会显示 

### What is expected?
显示slider

### What is actually happening?
不显示

---
只能在gallery中显示 在实际开发中不显示

**Comment by gty1998** [comment]
想请问一下，是不是我的option中有些配置会冲突呢？但是看文档暂时没有发现 echarts版本是3.1.10 感谢🙏

**Comment by pissang** [comment]
是不是没引入 dataZoom 组件

**Comment by gty1998** [comment]
> 是不是没引入 dataZoom 组件

你好 感谢回复 我看了一下 项目的echarts是在html页面的script标签全局引入 应该不涉及按需加载的问题  consolelog出的版本是2.2.7 好像该版本也支持datazoom 想请问下还可能有别的原因吗？

**Comment by pissang** [comment]
版本太老了，建议升级到 3.0+ 的版本
