### ISSUE TITLE
无法显示 dataZoom

### ISSUE THREAD

**Issue by seconemouse** [apache/incubator-echarts#11066]
### Version
4.2.1

### Steps to reproduce
我的目录是 <script src="js/echarts/dist/echarts.js"></script>  下载的4.2.1完全版本
https://github.com/apache/incubator-echarts/releases/tag/4.2.1

使用示例里面的candlestick无法显示dataZoom
https://www.echartsjs.com/option.html#series-candlestick

使用5分钟上手的示例可以显示dataZoom  https://www.echartsjs.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts

### What is expected?
candlestick不显示dataZoom

### What is actually happening?
candlestick显示dataZoom

**Comment by pissang** [comment]
排查一下是不是没引入 dataZoom 组件

**Comment by pissang** [comment]
有没有可以复现的代码或者例子

**Comment by seconemouse** [comment]
http://47.101.61.6:8081/index.php
user:demo
password:demo
选Graphic,点击show会出现上面的图,这个显示不了dataZoom
是这样配置的:
dataZoom: [                
        {                  
            type: 'inside',
            start: 0,      
            end: 100       
        },                 
        {                  
            show: true,    
            type: 'slider',
            start: 0,      
            xAxisIndex: 0, 
            end: 100       
        }                  
    ],                     


下面一个示例可以显示

**Comment by Ovilia** [comment]
请将最简单的例子放在 https://gallery.echartsjs.com/editor.html 复现
