### ISSUE TITLE
地图缩小至最小后，无法重新放大

### ISSUE THREAD

**Issue by FesonX** [apache/incubator-echarts#11069]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xryHrMdE2M](https://gallery.echartsjs.com/editor.html?c=xryHrMdE2M)

### Steps to reproduce
使用coordinateSystem为 geo 的图表，**操作鼠标滚轮缩小到最小**为一个点后，**无法再通过鼠标滚轮放大**，在Gallery中找到一个使用geo的图表，可复现该问题

### What is expected?
期望缩小至最小后，可以通过鼠标滚轮再次放大

### What is actually happening?
期望缩小至最小后，无法通过鼠标滚轮再次放大

**Comment by FesonX** [comment]
补充链接->https://echarts.baidu.com/examples/editor.html?c=map-parallel-prices

**Comment by pissang** [comment]
目前的逻辑是在地图可视区域上才会触发 zoom，如果缩得很小可能导致鼠标很难在这个可视区域上
