### ISSUE TITLE
xAxis.minInterval docs typo

### ISSUE THREAD

**Issue by Drapegnik** [apache/incubator-echarts#11079]
### Version
4.2.1

### Steps to reproduce
https://echarts.apache.org/en/option.html#xAxis.minInterval

### What is expected?
proper `minInterval` & `maxInterval` docs

### What is actually happening?
wrong description & example, missing `maxInterval`

<img width="858" alt="Screen Shot 2019-08-22 at 19 06 40" src="https://user-images.githubusercontent.com/11758660/63531615-8bad0a00-c511-11e9-9fd8-0a33982a741e.png">

***

I didn't find where I could fix it.

**Comment by yufeng04** [comment]
Error of document @Ovilia

**Comment by Ovilia** [comment]
Thanks for reporting. I've just fixed it in https://github.com/apache/incubator-echarts-doc/commit/9acfca83120209068df65adbff97f2d056482159 .
