### ISSUE TITLE
香港地图不准确，相差太离谱了

### ISSUE THREAD

**Issue by mofengfs** [apache/incubator-echarts#11083]
### Version
4.2.1

### Steps to reproduce
import "echarts/map/js/province/xianggang";

### What is expected?
应该和这个链接的图出入不大。
https://en.wikipedia.org/wiki/Districts_of_Hong_Kong#/media/File:Map_of_Hong_Kong_18_Districts_en.svg

![image](https://user-images.githubusercontent.com/16655229/63563939-97daab00-c595-11e9-8761-61232419ebd6.png)

### What is actually happening?
实际结果差太多，行政划分太离谱了，完全就是不切实际，完全用不了，其他地方也是相差甚远，比如地图有些实际上是分离的，但是echarts提供的地图是挨着的，这太离谱了。
![image](https://user-images.githubusercontent.com/16655229/63563884-46322080-c595-11e9-9a46-c8bbc185dd4e.png)

**Comment by pissang** [comment]
因为一些法规上的原因，我们不再提供地图数据，如果需要建议在其它地方寻找使用合适的地图数据
