### ISSUE TITLE
Echarts 的 dataZoom 能否监听变化后，canvas 可视区域的数据？

### ISSUE THREAD

**Issue by hoosin** [apache/incubator-echarts#11084]
### Version
4.2.1

### Steps to reproduce
散点图， 能否在 缩放/放大 后拿到当前画布的所有点的数据？

### What is expected?
缩放/放大 后拿到当前画布可视区域所有点

### What is actually happening?
没有找到类似 API

**Comment by hoosin** [comment]
找到了解决方案 通过监听 ```dataZoom```调用 ```getOption``` ，获取到 ```startValue, endValue ``` 的值，去过滤

**Comment by ningwy** [comment]
> 找到了解决方案 通过监听 `dataZoom`调用 `getOption()` ，获取到 `startValue, endValue ` 的值，去过滤

请问是具体怎么监听dataZoom调用getOption()的

**Comment by hoosin** [comment]
@ningwy 

```js
      const {dataZoom} =echarts.getOption();
```
然后到 dataZoom 去取

**Comment by IIAT-MR-LHL** [comment]
@hoosin 这里的events应该是echarts实例吧

**Comment by hoosin** [comment]
@IIAT-MR-LHL 是的

**Comment by pupuwu** [comment]
> @ningwy
> 
> ```js
>     events.on('dataZoom', () => {
>         const {dataZoom} =echarts.getOption();
>     });
> ```
> 
> 然后到 dataZoom 去取

但是这个方面拖动的时候会一直回调，有没有拖动结束后的呢

**Comment by ghostcode** [comment]
> > [@ningwy](https://github.com/ningwy)
> >     events.on('dataZoom', () => {
> >         const {dataZoom} =echarts.getOption();
> >     });
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后到 dataZoom 去取
> 
> 但是这个方面拖动的时候会一直回调，有没有拖动结束后的呢

自己加个防抖功能。
