### ISSUE TITLE
4.2.0版本  3d柱图、3d散点图、3d地图 不支持svg渲染

### ISSUE THREAD

**Issue by sikynet** [apache/incubator-echarts#11096]
### Version
4.2.0-rc.1

### Steps to reproduce
echarts类型设置为：echarts_bar3D、echarts_scatter3D、echarts_lines3D  用svg渲染时，直接报错。

### What is expected?
希望3d柱图、3d散点图、3d地图能够支持svg渲染

### What is actually happening?
使用svg渲染时，直接报错，没有图形

**Comment by yufeng04** [comment]
@pissang

**Comment by Ovilia** [comment]
3D charts are using WebGL, which means they cannot render with SVG.
