### ISSUE TITLE
目标issues已close，但是源代码没有fix该问题

### ISSUE THREAD

**Issue by yuanyuanyuan** [apache/incubator-echarts#11094]
### Version
4.2.1-rc.3

### Steps to reproduce
参考：https://github.com/apache/incubator-echarts/issues/10896
https://github.com/apache/incubator-echarts/issues/10304

### What is expected?
https://github.com/apache/incubator-echarts/issues/10896
https://github.com/apache/incubator-echarts/issues/10304

### What is actually happening?
问题已存在

**Comment by yufeng04** [comment]
#10896 中提供的[复现代码](https://gallery.echartsjs.com/editor.html?c=xHu5k6AzNc&v=1)在gallery和使用4.2.1本地调试均未复现！

**Comment by Ovilia** [comment]
This problem has been fixed in https://github.com/apache/incubator-echarts/commit/58d2dcee6fa206a0d547974b49ca3c43ef3d17f7 . It's not released yet. Sorry that we've been quite delayed in releasing time. We are releasing a candidate release this week.
