### ISSUE TITLE
希望折线图实现X轴为类目轴时让我指定两个数据点间横向间距，而不是像现在一样只能自动调整

### ISSUE THREAD

**Issue by houfb** [apache/incubator-echarts#11099]
### What problem does this feature solve?
我在做一个遗传病的质控图，X轴是实验次序编号，Y轴是检测值，但是，Y轴上的刻度显示和网格线要受两个基准（靶值和标准差）影响，但是，Y轴上的实际刻度值却是一样的(同样的值要等高)，因为靶值和标准差随时间推移，可能会不定时地改变，这就导致我需要按实际情况，当靶值和标准差改变时，重新画一道Y轴放上去，同时，将网络线的高度重新调整，最终，我使用3.0版本上的新功能，在同一个图表中绘制多个网格的形式来实现这个需求，至少，让它们从表面看起来是同一张图，但是，新问题来了，放到这两个网格中的数据点之间的横向间距不统一，为了统一，我现在只能手动计算一下数据量的多少，然后为网格设置定量的宽度，最后让echarts自已再自动调整间距，这一整套过程相当麻烦，我不知道是我走错路了还是有更好的方法我不知道，但是，我搜了很多资料，都没有体现出echarts对类目轴上数据点的横向间距的设置的实现，希望能实现这样一个功能，毕竟在这样的场景下，虽然是折线图，但是，客户看的重点却是图上的点而不是线的走势。

### What does the proposed API look like?
希望折线图能实现X轴为类目轴时，两个数据点间的横向间距能由我自行设置，那怕当图的宽度不够了自行舍去，这样可以让我在多个网格坐标系组合图时，让两个网格看起来更像是统一的一张图，而不再是简单粗暴的强硬拼接。

**Comment by Ovilia** [comment]
It's advised to use [custom series](https://echarts.apache.org/en/option.html#series-custom) to make this. A similar example may be https://echarts.apache.org/examples/en/editor.html?c=custom-profit .
You can see more examples [here](https://echarts.apache.org/examples/en/#chart-type-custom).
