### ISSUE TITLE
为什么折线图（任何图）在数据没有变化的情况下占CPU，如何解决？

### ISSUE THREAD

**Issue by alexmlhe** [apache/incubator-echarts#11091]
### Version
4.1.0-release

### Steps to reproduce
任何直线图界面，没有任何数据改变，观察CPU占用率在 10%   

### What is expected?
不占CPU

### What is actually happening?
CPU占用率在 10%

**Comment by Ovilia** [comment]
You should probably provide a demo to show the problem. https://gallery.echartsjs.com/editor.html

**Comment by xushimin** [comment]
> You should probably provide a demo to show the problem. https://gallery.echartsjs.com/editor.html

https://gallery.echartsjs.com/editor.html 就是页面，cpu占用如下
![image](https://user-images.githubusercontent.com/14247567/84021442-30240e00-a9b7-11ea-9081-ded10a9a2703.png)

**Comment by xushimin** [comment]
@Ovilia

**Comment by pissang** [comment]
@xushimin gallery 编辑器里不只是在运行 echarts，左边还有一个代码编辑器。

你可以再关注下在自己项目里集成 echarts 之后所带来的额外的 CPU 开销
