### ISSUE TITLE
Set `options.polar.radius` to an `Array` wouldn't work

### ISSUE THREAD

**Issue by liyachun01** [apache/incubator-echarts#11104]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xlZxa6gTOR&v=1](https://gallery.echartsjs.com/editor.html?c=xlZxa6gTOR&v=1)

### Steps to reproduce
open the reproduction link, uncomment the lines under `options.polar.radius` to see consequences

### What is expected?
get a polar chart with an inner radius and an outer  radius 

### What is actually happening?
the canvas gets blank without an error in the browser console

---
Trying to use the polar component with both an inner radius and an outer radius set. Everything was correctly set except when setting `options.polar.radius` to an `Array` would just stop the chart from showing, no error in the browser console is reported.

**Comment by Ovilia** [comment]
The polar radius shouldn't be an array. This is a document error which has just been fixed.
