### ISSUE TITLE
谷歌版本 52.0.2743.6  echarts版本4.2.1  ，使用svg渲染的地图  鼠标悬浮提示不生效。谷歌48版本，76版本正常。

### ISSUE THREAD

**Issue by sikynet** [apache/incubator-echarts#11105]
### Version
4.2.0-rc.1

### Steps to reproduce
1：下载52.0.2743.6版本的谷歌浏览器。
2：打开带有鼠标悬浮提示的地图。
3：会发现无法显示提示。

### What is expected?
支持48版本和76版本的谷歌浏览器，也希望支持52的。

### What is actually happening?
没有鼠标提示。

**Comment by Ovilia** [comment]
Where can I find a Chrome browser with version 52? This seems a little too old to find.
