### ISSUE TITLE
bug(candlestick): data not render after NaN

### ISSUE THREAD

**Issue by pheart** [apache/incubator-echarts#11101]
### Version
4.2.1

### Reproduction link
[https://jsbin.com/jenekay/edit?html,js,output](https://jsbin.com/jenekay/edit?html,js,output)

### Steps to reproduce
Use the candlestick of offical example
使用了官方的股票示例图
Set the number from 800th to 820th to be `NaN`
第800到820个数据的数值设置为NaN
Then the previous 800 numbers can be rendered, while the data after 820th cannot be rendered, but the tooltip is available.
此时只显示前800个数据可以绘制图形，820个数据之后的图形没有绘制，但tooltip可见。

### What is expected?
Data is visible.
k线图应该要可见

### What is actually happening?
The later half part of the data is not visible.
后半截k线图不可见

**Comment by yufeng04** [comment]
It's a bug!
![image](https://user-images.githubusercontent.com/22974511/63689387-62a3b680-c83c-11e9-921c-71d8690a9765.png)

**Comment by pheart** [comment]
@yufeng04   yeah
