### ISSUE TITLE
饼状图计算的百分比如何通过API获取？

### ISSUE THREAD

**Issue by robin1892** [apache/incubator-echarts#11107]
### What problem does this feature solve?
饼状图会自动计算百分比，但是计算的值和手动计算的结果不一致。造成的结果就是：实际数据和图形显示的结果不一致

### What does the proposed API look like?
希望能获得自动计算的百分比，以便做到数据统一。

**Comment by Ovilia** [comment]
Sorry, we do not provide such an API.
The algorithm is [Largest remainder method](https://en.wikipedia.org/wiki/Largest_remainder_method). [This post](http://zhangwenli.com/blog/2017/06/13/pie-percentage/) helps you to understand.

**Comment by yufeng04** [comment]
Echarts doesn't have such API.
