### ISSUE TITLE
custom item's fill color error when mouse leave item

### ISSUE THREAD

**Issue by icksky** [apache/incubator-echarts#11103]
### Version
4.2.1

### Reproduction link
[https://codepen.io/icksky/pen/KKPWQrp](https://codepen.io/icksky/pen/KKPWQrp)

### Steps to reproduce
1. mouse hover the item (name as A);
2. unselected the items which color same as A;
3. mouse enter A and mouse leave;

### What is expected?
the color of A is transparent when mouse leave

### What is actually happening?
the color of A is not transparent

---
a gif of operations
![echarts_bug_report](https://user-images.githubusercontent.com/13565030/63673839-cbc50300-c817-11e9-8fa5-7d0118783ac3.gif)

___
I guess it is caused by function `cacheElementStl` in file `echarts\lib\util\graphic.js`.

**Comment by yufeng04** [comment]
#11102

**Comment by Ovilia** [comment]
Seems to be a bug. Thanks for reporting.
