### ISSUE TITLE
option中textStyle的作用范围

### ISSUE THREAD

**Issue by zpf96126** [apache/incubator-echarts#11106]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xnzdxqQYKY&v=1](https://gallery.echartsjs.com/editor.html?c=xnzdxqQYKY&v=1)

### Steps to reproduce
在option中使用全局textStyle设置文字格式

### What is expected?
文字均能按照textStyle中的样式展示

### What is actually happening?
标题、图例等中的文字仍是默认样式

**Comment by yufeng04** [comment]
[series.itemStyle.color](https://echarts.baidu.com/option.html#series-bar.itemStyle.color) and 
[title.textStyle.color](https://echarts.baidu.com/option.html#title.textStyle.color) have different way to deal with the default color!

**Comment by zpf96126** [comment]
但是教程里不是说textStyle可以设置全局字体吗

**Comment by Ovilia** [comment]
@zpf96126 It's overrided by that in series.
