### ISSUE TITLE
Zoom events too slow on line char when have a serie with 43200 points

### ISSUE THREAD

**Issue by fjserrano** [apache/incubator-echarts#11118]
### Version
4.1.0-release

### Reproduction link
[https://jsfiddle.net/Redhunt/spb81Lxh](https://jsfiddle.net/Redhunt/spb81Lxh)

### Steps to reproduce
1. Create a chart line with 3 Series (with 1 serie have the same behaviour but a little bit quickly)
2. On each serie include 43200 points
3. Load the chart
4. Do zoom in and zoom out on chart

### What is expected?
I expected do events of zoom quickly on chart when make the zoom in or zoom out.

### What is actually happening?
When I have a zoom in and zoom out viewing all the data the events of zoom out are too slow

---
I changed the echarts from Flot chart. With Flot Chart I load the same amount of data and have events quickly. I changed to echarts because I saw this library more powerfull but with this amount of data I saw echarts more slowly.

I know your library uses openGL for some charts, Are there any posibility to accelerate the line chart with openGL??.

I test the library with I7 7700k and 16GB of RAM. I tested this behaviour on Firefox, Chrome and Edge.

**Comment by fjserrano** [comment]
With `sampling: 'average'` on series improve the performance with a lot of data. I don't know if library has other option for improve more the performance.

**Comment by Ovilia** [comment]
@fjserrano `sampling: 'average'` is the correct way to do the job.

**Comment by alfredxinglkey** [comment]
> 
what if the `graph` chart, please.
