### ISSUE TITLE
柱状图 xAxis.boundaryGap 为 true 时影响了 xAxis.splitLine 的显示效果

### ISSUE THREAD

**Issue by CosSalt** [apache/incubator-echarts#11110]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xpgxqPCfzz&v=1](https://gallery.echartsjs.com/editor.html?c=xpgxqPCfzz&v=1)

### Steps to reproduce
xAxis.boundaryGap 设置为 false 可以正常显示，xAxis.boundaryGap 设置为 true 则显示错误

### What is expected?
xAxis.boundaryGap 设置为 true，和 xAxis.boundaryGap 设置为 false 时一样

### What is actually happening?
重现链接中，虚线消失不见了，在实际项目中由于 x 轴分类较多，显示错位了

**Comment by yufeng04** [comment]
it seems to be a bug.

**Comment by Ovilia** [comment]
This is the expected behavior. @CosSalt What do you want with `boundaryGap: false`?

**Comment by CosSalt** [comment]
@Ovilia `boundaryGap：false` 是正常的显示效果，`splitLine` 属性正常工作，有一条红色虚线垂直于  x 轴，并过  x 轴上的 `2013` 这个点；
但只改变 `boundaryGap：true` 后  x 轴 2013 处没有红色的虚线了

**Comment by CosSalt** [comment]
正常：[boundaryGap：false](https://gallery.echartsjs.com/editor.html?c=xgK5RtoHOV)
消失：[boundaryGap：true](https://gallery.echartsjs.com/editor.html?c=xpgxqPCfzz&v=1)

**Comment by Ovilia** [comment]
[splitLine.interval](https://echarts.apache.org/en/option.html#xAxis.splitLine.interval) should be a number or a function that returns a number. In your demos, the function returns a boolean. I don't think `splitLine` should be used to do the job. Maybe you should try with a vertical [markLine](https://echarts.apache.org/en/option.html#series-bar.markLine)?

**Comment by CosSalt** [comment]
@Ovilia [splitLine.interval](https://echarts.apache.org/zh/option.html#xAxis.splitLine.interval) 函数返回的是布尔值，上面的正常例子是和预期结果一样的

**Comment by Ovilia** [comment]
As I said, I don't think `splitLine` should be used to do the job.
