### ISSUE TITLE
使用dataZoom横向滚动图表y轴数值保持不变

### ISSUE THREAD

**Issue by ppjjzz** [apache/incubator-echarts#11113]
### What problem does this feature solve?
每滚动一屏y轴的最大值都会根据当前可视区域的最大值来进行计算，这样就看不出总体数据的趋势。
例如在第一屏的10有可能跟第二屏的5的柱子一样高

### What does the proposed API look like?
能够在使用dataZoom滚动时y轴数值固定且为整个数据集的最大值去自适应

**Comment by yufeng04** [comment]
[yAxis.max](https://www.echartsjs.com/option.html#yAxis.max) maybe work！

**Comment by ppjjzz** [comment]
> [yAxis.max](https://www.echartsjs.com/option.html#yAxis.max) maybe work！

但是限定max值后y轴的刻度分布不是均匀等分的，会多出来一条特别的刻度线很不美观

**Comment by Ovilia** [comment]
@yufeng04 is right about `yAxis.max`.
As for nice max axis with a given max value, that would be an enhancement of another topic. You may open another issue if you wish.
