### ISSUE TITLE
Axis labels disappears

### ISSUE THREAD

**Issue by AndreyAndreyevich** [apache/incubator-echarts#11112]
### Version
4.2.1

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=bar-negative](https://echarts.apache.org/examples/en/editor.html?c=bar-negative)

### Steps to reproduce
Keep minimizing window vertically until some of the Y-axis labels will be hidden. Then maximize the window back. Previously hidden labels won't appear.

### What is expected?
It is expected that labels non-overlapping behavior depends on window current size.

### What is actually happening?
Axis labels visualization corresponds to the minimum window size even if the window is maximized back.

---
The same issue is for X-axis.

I'm concerned that axisLabel has an 'interval' option, which can be set to 0 and labels will be shown constantly. But this is not a solution and automatic behavior is required.

This behavior may be reproduced on almost every chart of https://echarts.apache.org/examples/en/

**Comment by yufeng04** [comment]
It seems to be a bug.
