### ISSUE TITLE
提供时间序列轴保持连续的选项

### ISSUE THREAD

**Issue by jacktang** [apache/incubator-echarts#11124]
### What problem does this feature solve?
常见二维坐标，x是时间坐标，如果提供的数据是不连续的，如: `{"2019-04-01": 23, "2019-04-03": 24, "2019-05-07": 30}`，那么应该可以选择是否保持时间连续，如果保持时间连续，中间的时间点用0数值(缺省值)补充，否则显示非0数值

### What does the proposed API look like?
1. 提供时间序列轴保持连续的选项
2. 提供缺省值选项

**Comment by Ovilia** [comment]
This is a problem that should be fixed when generating data on the user side.
It is not appropriate for ECharts to automatically insert 0 values into the data. Because it's unclear the interval of the duration of time series.
