### ISSUE TITLE
BUG: TypeError: Cannot read property 'coord' of undefined

### ISSUE THREAD

**Issue by eniaclyl** [apache/incubator-echarts#11139]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xx1QGUPT7I&v=1](https://gallery.echartsjs.com/editor.html?c=xx1QGUPT7I&v=1)

### Steps to reproduce
单击标注，控制台弹出TypeError: Cannot read property 'coord' of undefined

### What is expected?
单击标注修改 标注文本

### What is actually happening?
TypeError: Cannot read property 'coord' of undefined

---
如何正确的修改标注文本

**Comment by yufeng04** [comment]
You may need to add coordinates. For example,
```
    markLine: {
                data: [[{
                    id: '1',
                    label: {
                        formatter: '1111111'
                    },
                    xAxis: -30,
                    yAxis: 30
                },
                {
                    xAxis: 50,
                    yAxis: 50
                }]]
            }
```
