### ISSUE TITLE
CONTRIBUTING.md has an error 

### ISSUE THREAD

**Issue by foolzhang** [apache/incubator-echarts#11138]
### Version
4.2.1

### Reproduction link
[https://github.com/apache/incubator-echarts/blob/master/.github/CONTRIBUTING.md](https://github.com/apache/incubator-echarts/blob/master/.github/CONTRIBUTING.md)

### Steps to reproduce
run second npm link directly will get "ENOENT: no such file or directory, rename '/Users/X/fe/echarts/incubator-echarts/node_modules/.staging/zrender-5b9c5f88/node_modules/@babel/code-frame' -> '/Users/X/fe/echarts/incubator-echarts/node_modules/.staging/@babel/code-frame-e54879b1'"

### What is expected?
cd ~/workspace/zrender </br>
npm link </br>
cd ~/workspace/echarts </br>
npm link zrender </br>

### What is actually happening?
cd ~/workspace/zrender </br>
npm link </br>
cd ~/workspace/echarts </br>
npm link </br>

**Comment by Ovilia** [comment]
Thanks for reporting. Do you mind creating a pull request to fix this?
