### ISSUE TITLE
Render-independent test cases fail to run

### ISSUE THREAD

**Issue by pearson-g** [apache/incubator-echarts#11134]
### Version
4.2.1

### Steps to reproduce
Open ./ut.html files in Web Browsers.（Running inside tomcat）

### What is expected?

Test case pass

### What is actually happening?
111 specs, 20 failures

---
1、If you don't run in tomcat, there will be cross-domain issues.
2、tips：
“Component topologicalTravel topologicalTravel_base”
“Component topologicalTravel topologicalTravel_a1IsAbsent”
“Component topologicalTravel topologicalTravel_isolate”
“Component topologicalTravel topologicalTravel_diamond”
“Component topologicalTravel topologicalTravel_multipleEchartsInstance”
“Component topologicalTravel topologicalTravel_missingSomeNodeButHasDependencies”
“Component topologicalTravel topologicalTravel_subType”
“scale_interval extreme ticks_small_value”
“List Data Manipulation Stacked data”
“List Data Manipulation getRawValue”
“List Data Manipulation indexOfRawIndex”
“completeDimensions namesMoreThanDimCount”
“completeDimensions differentData”
“completeDimensions differentSysDims”
“completeDimensions dimsDef”
"completeDimensions encodeDef"
"graphic_setOption groupLRTB getAndGet"
"graphic_setOption groupLRTB modifyAndCenter"
"graphic_setOption groupLRTB resize"

**Comment by yufeng04** [comment]
Issue already exists. #11116

**Comment by Ovilia** [comment]
Unit tests should be fixed in v4.4.0. Please follow #11116 for updates.
