### ISSUE TITLE
dataset映射，value是字符串格式时，丢失第一个类目

### ISSUE THREAD

**Issue by ximijia** [apache/incubator-echarts#11157]
### Version
4.1.0-release

### Reproduction link
[http://jsrun.pro/5GbKp/edit/](http://jsrun.pro/5GbKp/edit)

### Steps to reproduce

option={"dataset":{"dimensions":["_x_","农业物联网基地","全国农业信息化示范基地"],"source":[["陕","8","1"],["西安市","11","5"],["咸阳市","7","4"],["铜川市","3","1"],["宝鸡市","10","2"],["渭南市","3","2"],["榆林市","12","1"],["延安市","9","1"],["汉中市","5","2"],["安康市","4","2"],["商洛市","6","1"]]},"tooltip":{"trigger":"axis"},"color":["#c23531","#2f4554","#61a0a8","#d48265","#91c7ae","#749f83","#ca8622","#bda29a","#6e7074","#546570","#c4ccd3"],"textStyle":{"fontFamily":"sans-serif","color":"#fff","fontStyle":"normal","fontSize":12},"grid":{"top":"60","right":"10%","bottom":"60","left":"10%"},"legend":{"show":true,"orient":"horizontal","top":"top","type":"plain","textStyle":{"color":"#fff"}},"xAxis":{"show":true,"position":"bottom","type":"category","name":"","axisLine":{"show":true,"lineStyle":{"color":"#fff"}},"axisLabel":{"show":true,"fontFamily":"sans-serif","color":"#fff","fontStyle":"normal","fontWeight":"normal","fontSize":16}},"yAxis":{"show":true,"position":"left","type":"value","name":"","axisLine":{"show":true,"lineStyle":{"color":"#fff"}},"axisLabel":{"show":true,"fontFamily":"sans-serif","color":"#fff","fontStyle":"normal","fontWeight":"normal","fontSize":16},"splitLine":{"type":"dashed","lineStyle":{"color":"#36648B"}}},"series":[{"type":"bar"},{"type":"bar"}]}

### What is expected?
所有x轴类目正常显示

### What is actually happening?
丢失x轴第一个类目
![image](https://user-images.githubusercontent.com/22970441/64149519-ad36bb80-ce58-11e9-8edb-01ed6a9e5f7f.png)

**Comment by Ovilia** [comment]
Please add [sourceHeader: false](https://echarts.apache.org/en/option.html#dataset.sourceHeader) in the dataset option.
