### ISSUE TITLE
add reverse  in legend

### ISSUE THREAD

**Issue by foolzhang** [apache/incubator-echarts#11150]
### What problem does this feature solve?
easy to UI show

### What does the proposed API look like?
```json
{
   legend:{
       reverse:true
   }
}
```

**Comment by pissang** [comment]
We have implemented legend reverse selection in the latest code of master branch. It will be included in the 4.4.0 release. Which is planned to be release at the end of this month.

**Comment by foolzhang** [comment]
Thinks
