### ISSUE TITLE
图例项的 icon，使用'path://'设置填充颜色不起作用

### ISSUE THREAD

**Issue by lbm526** [apache/incubator-echarts#11161]
### Version
3.8.4

### Steps to reproduce
legend: {
                data: [{
                    name: '环比增长率',
                    // icon: 'path://M0 0 L0 30 L60 30 L60 0 Z fill="#333333 stroke="blue" stroke-width="3"'
                    icon: 'path://d="M 100 100 L 300 100 L 200 300 z" fill="blue" stroke="blue" stroke-width="13"'
                },'单产电耗(kWh/吨)'],
                bottom: 0,
            },

### What is expected?
柱形图颜色不变情况下，自定义图例形状和颜色

### What is actually happening?
自定义形状渲染成功，颜色自定义失败，渲染的是默认颜色

**Comment by pissang** [comment]
You can't change the color of legend because it's connect to the series. You can use an image with specified color if really wan't to
