### ISSUE TITLE
series[i]-line.markPoint.symbol当其值为函数时, 参数1恒为undefined

### ISSUE THREAD

**Issue by xiaomocqk** [apache/incubator-echarts#11179]
### Version
4.3.0-rc.1

### Steps to reproduce
series[i]-line.markPoint.symbol当其值为函数时, 参数1恒为undefined

### What is expected?
value值为当前数据

### What is actually happening?
undefined

**Comment by deqingli** [comment]
Please provide echarts `option` or demo for us to debug.
