### ISSUE TITLE
xAxis.axisTick.interval appears different between echart4 and echart3.8

### ISSUE THREAD

**Issue by li3081934** [apache/incubator-echarts#11176]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xy5OQBi9fa&comment=0](https://gallery.echartsjs.com/editor.html?c=xy5OQBi9fa&comment=0)

### Steps to reproduce
echart4  https://gallery.echartsjs.com/editor.html?c=xy5OQBi9fa&comment=0      
echart3.8 https://gallery.echartsjs.com/editor.html?c=xG60Tajuaz&v=3

### What is expected?
希望echart4 和 echart3.8的效果一样

### What is actually happening?
echart4 的 interval 无法隐藏第二个刻度线

**Comment by foolzhang** [comment]
@pissang  [PR 11186](https://github.com/apache/incubator-echarts/pull/11186/files)
