### ISSUE TITLE
开源协议相关问题

### ISSUE THREAD

**Issue by baizhenzheng** [apache/incubator-echarts#11197]
### What problem does this feature solve?
您好，如果我们公司使用 echarts的开源产品去开发产品，做出来的产品需要开源吗？另外在使用
 echart的时候在开源协议需要哪些注意事项？
顺祝万事如意

### What does the proposed API look like?
开源协议

**Comment by pissang** [comment]
Hi @baizhenzheng 

You don't need to open source your project. 

ECharts is open sourced under Apache License. Please check more detail and limitation in https://en.wikipedia.org/wiki/Apache_License
