### ISSUE TITLE
请问如何制作 Parallel - Nutrients 的图表

### ISSUE THREAD

**Issue by JJack77** [apache/incubator-echarts#11202]
### Version
4.2.1

### Steps to reproduce
请问如何制作 Parallel - Nutrients 的图表

### What is expected?
想知道如何制作这图表
( https://echarts.apache.org/examples/zh/editor.html?c=parallel-nutrients&theme=dark )

### What is actually happening?
我下载了你们的Example (source code 和 资料)，改了资料的途径
可是还是显示不出来这图表。
我好奇如何制作这图表。

**Comment by deqingli** [comment]
![image](https://user-images.githubusercontent.com/13548221/64947557-dcf9b080-d8a7-11e9-8832-0306f2008bf3.png)

You should include the data correctly.
