### ISSUE TITLE
Line points are changing style (or changing series data reference) when itemStyle is dynamically added into series data

### ISSUE THREAD

**Issue by nunesd** [apache/incubator-echarts#11217]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/3zmvuqyh/1/](https://jsfiddle.net/3zmvuqyh/1/)

### Steps to reproduce
 I tried to use two different type charts with the same data object and add itemStyle to only one of them (column type), but itemStyle was added to both charts, thus changing the line point colors in the line chart.

### What is expected?
that the chart does not change the reference value and two charts have different data

### What is actually happening?
Apparently the data reference is changing when added to a chart. The line chart is with the itemStyle property. It doesn't ignore the if statment, it just seems that the `graphicData` reference is changing.
![Captura de tela de 2019-09-10 17-02-53](https://user-images.githubusercontent.com/44625231/64649033-86e1c480-d3f2-11e9-85ba-13d08f2141b5.png)
![Captura de tela de 2019-09-10 17-09-24](https://user-images.githubusercontent.com/44625231/64649039-89441e80-d3f2-11e9-9b4d-1570b3cc3acd.png)
![Captura de tela de 2019-09-10 17-12-15](https://user-images.githubusercontent.com/44625231/64649047-8c3f0f00-d3f2-11e9-93bc-312976c717c9.png)
![Captura de tela de 2019-09-10 17-12-04](https://user-images.githubusercontent.com/44625231/64649054-8f39ff80-d3f2-11e9-8377-84ce36c9469b.png)

**Comment by deqingli** [comment]
Sorry I don't quite understand what you mean. Besides, in echarts there is no series named `column`, so the if statement maybe not work as you expected.
