### ISSUE TITLE
官网示例出现 Uncaught ReferenceError: $ is not defined     at tree-vertical.html:23

### ISSUE THREAD

**Issue by OpenWaygate** [apache/incubator-echarts#11218]
### Version
4.2.1

### Steps to reproduce
并不清楚所用的echarts版本, 但代码是官方的
从官网下载示例 https://echarts.apache.org/examples/en/editor.html?c=tree-vertical, 换用自己的ak, 出现错误

![image](https://user-images.githubusercontent.com/27287694/64675992-18127300-d4a7-11e9-92dc-6a063853cdda.png)

```
Uncaught ReferenceError: $ is not defined
    at tree-vertical.html:23
```

### What is expected?
期望出现官网的效果

### What is actually happening?
一直loading

**Comment by JoseFYG** [comment]
@OpenWaygate how do you resolve?
