### ISSUE TITLE
自定义拐点图片,在点击图例隐藏后,再点击显示,拐点消失

### ISSUE THREAD

**Issue by CGnavvv** [apache/incubator-echarts#11210]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by CGnavvv** [comment]
series: [
                    {
                        name:'在线率',
                        type:'line',
                        smooth: true,
                        data: onlineList,
                        symbol: 'image://data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAJ1BMVEX///9gxp5gxZ5hxp5hxp5gxZ09fXATKDoCBCMlTVBhxp5hxp08fG/ABjLUAAAAAXRSTlMAQObYZgAAAF1JREFUGNN1j1ESgCAIREkMULz/eUMko2l6X8sKuAA4hwEPBZ0SZcXN6YYJYhEmE9HfxGlryt4loNnSEfk2GLFPQzZ/xnvksxQ0f6sRbMxgI4Ll6DWu0VVqurcbS10xdgRe2PjCbQAAAABJRU5ErkJggg==',
                        symbolSize: 10,
                        markLine: {
                            symbol: 'none',
                            lineStyle: {
                                color: '#F5C507',
                            },
                            data: [{
                                yAxis: '100',
                                label: {
                                    normal:{
                                        fontSize:12,
                                        formatter: '{c}%'
                                    }
                                },
                            }]
                        }
                    },

**Comment by micherwa** [comment]
我也遇到的这个问题。

当前版本号 v4.3。

现状是：
只要将symbol 设置为 base64 或者 一个http的外链。

那么在点击图例中的某个项之后，该项对应的那条线消失。再次点击，那条线又出现了，但这时 symbol 上的自定义Icon 就不见了。
