### ISSUE TITLE
柱状图中series指定的dataset定位错误

### ISSUE THREAD

**Issue by icetimidus** [apache/incubator-echarts#11226]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xZQjtEQlY7&v=1](https://gallery.echartsjs.com/editor.html?c=xZQjtEQlY7&v=1)

### Steps to reproduce
详见链接

### What is expected?
指定的dataset数据定位正确

### What is actually happening?
其中“ECM”与“公司业务系统”均显示成了“ECM”的数据

**Comment by deqingli** [comment]
![image](https://user-images.githubusercontent.com/13548221/64942495-c64d5c80-d89b-11e9-94e3-dad31f1e3370.png)
I have added `legend` in your demo and the two series you specified is separated. so I don't quite understand what your problem is?

```js
legend: {
        data: ['ECM', '报表系统', 'E校园', '新内网', 'DOMAIN-PRD', '生产运维平台', '内容管理系统', '集中营运', 'BBOS/BBIP EDGE', 'ATMP', '联网核查系统','客户管理', '个人业务系统', 'GUIP', 'ATMV','JRT', '未知', '公司业务系统']
}
```

**Comment by icetimidus** [comment]
<img width="671" alt="屏幕快照 2019-09-16 18 42 16" src="https://user-images.githubusercontent.com/2377333/64952002-c22c3980-d8b1-11e9-8bdd-c8109c20fb71.png">
<img width="419" alt="屏幕快照 2019-09-16 18 45 31" src="https://user-images.githubusercontent.com/2377333/64952208-51d1e800-d8b2-11e9-8a58-481fd7017e00.png">

The problem is the data of "公司业务系统" in bar chart is wrong. Use screenshots to illustrate, in row three, the data of "公司业务系统" should be 1332.5333333333333. But it is 1666775.3333333333, as same as "ECM".

**Comment by icetimidus** [comment]
@deqingli 
Hi, I want to know is there anyone following up this issue?

**Comment by icetimidus** [comment]
I have created a new issue #11322 , so that, cloes this.
