### ISSUE TITLE
setOption 的 notMerge 不足以满足某些场景

### ISSUE THREAD

**Issue by B1gF4ceC4t** [apache/incubator-echarts#11238]
### What problem does this feature solve?
在图形切换的场景使用setOption，如从柱图切换到饼图，传入参数为想要更新的option配置。
但效果是坐标轴依然存在，查看文档是因为notMerge默认false。
如果设置notMerge为true，即只会使用传入的option，又会丢失一部分原有的option。

### What does the proposed API look like?
希望不只有merge一种行为，因为是merge所以传入如{xAxis:null}也不能替换掉原有的xAxis（notMerge为false）。
期望setOption可以有replace的行为，如果有其他方式可以实现也请告知，谢谢。

**Comment by Ovilia** [comment]
`notMerge: true` 然后把你要保留下的部分 option 放在新的 option 中。

**Comment by B1gF4ceC4t** [comment]
如果通过```getOption()```获取当前option，手动把需要更新的配置项替换掉，再```setOption()```可以吗？
我看官方不推荐这样处理，但如dataZoom我只知道初始默认状态，如果用户有拖动过在某些场景下我们重绘图形时是不希望dataZoom位置有变化的。以现在的情况，我只能通过```getOption()```去取再更新了。

**Comment by Ovilia** [comment]
嗯，一般如果没有你说的 dataZoom 的这个状态需求的话，建议直接根据传入的 option 修改（而不是提供 `getOption` 获得），如果有 dataZoom 的话，只能提供 getOption 获得了。

**Comment by B1gF4ceC4t** [comment]
好的 谢谢
