### ISSUE TITLE
(Line Datetime series graph) How to set panning area zoom as by default cursor in Echarts?  

### ISSUE THREAD

**Issue by rajushun** [apache/incubator-echarts#11233]
### Version
4.3.0-rc.2

### Steps to reproduce
aa

### What is expected?
Need Panning area zoom as default cursor for graph

### What is actually happening?
no controls found to set the area zooming as by default cursor. It is found in toolbox but couldn't trigger as default

**Comment by deqingli** [comment]
You can set `dataZoom` in you echarts `option`.
