### ISSUE TITLE
Stack icon doesn't toggle

### ISSUE THREAD

**Issue by mlibbey** [apache/incubator-echarts#11236]
### Version
4.2.1

### Reproduction link
[https://echarts.apache.org/en/option.html#series-line.stack](https://echarts.apache.org/en/option.html#series-line.stack)

### Steps to reproduce
1. Click the stack icon. The chart changed to stacked.
2. Click the stack icon again. The chart does not unstack. The icon does not 'unselect'

### What is expected?
When clicking on the 'selected' version of the stack icon, 
1) the icon should toggle back to the original state
2) the graph should toggle back to the original state

### What is actually happening?
once the stack icon is selected, it can not be unselected.

**Comment by Ovilia** [comment]
This seems to be a bug. Thanks for reporting.

**Comment by alex2wong** [comment]
IMO, I suppose it is not really a bug, since there's an unstack button besides. And the doc does not claim stack button has toggle effect, right ? btw, if the unstack functionality does not work, you can simple click reset button at bottom of the chart container..

![image](https://user-images.githubusercontent.com/10528482/65198314-3daa0880-dab5-11e9-9997-8d4b22eec620.png)

btw, @Ovilia though the doc content has i18 multi-language, but the demo chart's toolbox tooltips do NOT have. if we can enhance the built-in tooltips with multi-language, that may help the Echarts more widely spread oversea. Thanks.

**Comment by Ovilia** [comment]
The reset button is not part of ECharts, but a button of our demo platform. So it should work with the unstack toolbox without clicking the reset button.

**Comment by pissang** [comment]
@mlibbey Hi, the stack is not a toggle button. As @alex2wong says, you should click the button beside the stack button to toggle back to the original state.

**Comment by Ovilia** [comment]
Oh, I see...

**Comment by mlibbey** [comment]
Thank you. The integration site I was using has the english version labeled as "tiled." I thought that would show each line on different graph or needed special data to activate, as its non-functional in the initial view.

I think making the stack toggle between stack and unstack would be more discoverable. If that's not the direction you want to go, I'd suggest translating unstack icon to "un-stack" instead of "tiled".

**Comment by Ovilia** [comment]
@mlibbey I think you are quite right. We should remove the tiled button and change the text of the current stack button to be "Stack" for the un-stacked state and to be "Un-stack" for the stack state.

@mlibbey @alex2wong Is any of you interested in making a pull request about this?
Here are some suggested files to change:
https://github.com/apache/incubator-echarts/blob/master/src/component/toolbox/feature/MagicType.js#L90
https://github.com/apache/incubator-echarts/blob/master/src/langEN.js#L53

**Comment by alex2wong** [comment]
Hi @Ovilia  do we really need this design change ? Since it would break the previous behavior, make it inconsistent. Maybe the users have get used to seperate toolbox buttons for 'stack' and 'tiled'.

 If this change is still needed. I would like to make a PR : )

**Comment by Ovilia** [comment]
@alex2wong I think the new design would help improve the user experience. We may set the icon and text to be "tile" after clicking "stack" so that it won't make confusion for old users.
We would appreciate it very much if you could make this PR. :)

**Comment by alex2wong** [comment]
OMG, found duplicate fix in https://github.com/apache/incubator-echarts/pull/10670

**Comment by susiwen8** [comment]
Yours is much better. Good job.

**Comment by alex2wong** [comment]
> Yours is much better. Good job.

Thanks~ but I thought your fix is much simpler and should work as well.
