### ISSUE TITLE
bug with quantityExponent

### ISSUE THREAD

**Issue by GEMINI5516** [apache/incubator-echarts#11249]
### Version
4.3.0

### Reproduction link
[https://github.com/apache/incubator-echarts/blob/7041103fb91cf5aeacf934bc990a023dfd3c5dfa/src/util/number.js#L390](https://github.com/apache/incubator-echarts/blob/7041103fb91cf5aeacf934bc990a023dfd3c5dfa/src/util/number.js#L390)

### Steps to reproduce
quantityExponent has bug with `quantityExponent(1000)`

### What is expected?
`quantityExponent(1000)` is expected to be 3 

### What is actually happening?
`quantityExponent(1000) = 2`

I recommend using Math.log10(val) instead.

**Comment by Ovilia** [comment]
@GEMINI-SYSU Thanks for reporting! Do you mind making a pull request to fix it?

**Comment by GEMINI-SYSU** [comment]
> @GEMINI-SYSU Thanks for reporting! Do you mind making a pull request to fix it?

I recommend using Math.log10(val) instead.

**Comment by GEMINI-SYSU** [comment]
> @GEMINI-SYSU Thanks for reporting! Do you mind making a pull request to fix it?

I recommend using Math.log10(val) instead.

**Comment by Ovilia** [comment]
@100pah What's the consideration of current implementation?

**Comment by pissang** [comment]
@GEMINI5516 Math.log10 may have compatibility issue in some browsers, like IE

**Comment by Ovilia** [comment]
@GEMINI5516 Here's some instructions about how to make pull requests. Looking forward to your first pull requests.

**Comment by 100pah** [comment]
A possible solution might be: 

```js
function quantityExponent(val) {
    var exp = Math.floor(Math.log(val) / Math.LN10);
    if (val / Math.pow(10, exp) >= 10) {
        exp++;
    }
    return exp;
}
```

BTW, we also need to consider `quantityExponent(0)`.
And write test cases for this util.

**Comment by GEMINI5516** [comment]
@100pah what about using String.length instead?

**Comment by GEMINI5516** [comment]
@100pah what about using String.length instead?

And I think it's not necessary to consider `quantityExponent(0)`, cause this function was used with Math.pow, as `Math.pow(10, quantityExponent(val))` . If val is 0, then `Math.pow(10, quantityExponent(val)) = 0`

**Comment by Ovilia** [comment]
I'm going to write some test cases. Then, if @GEMINI5516 is interested, you are very welcomed to make a pull request.

**Comment by Ovilia** [comment]
@GEMINI5516 Hi, I've added unit tests for this function. Please check `test/ut/ut.html` before making a pull request. You may comment the files other than `number.js` in `test/ut/ut.js` to only test the number util.

This issue is scheduled in [v4.5.0](https://github.com/apache/incubator-echarts/milestone/14), which closes for testing on 25th Oct. If you don't have time for it, please let me know in advance.
Please comment here if you have any questions.

**Comment by Ovilia** [comment]
@GEMINI5516 Hi, I'd like to make sure if you have time to make a pull request in two weeks because 4.5.0 is scheduled to be tested from 25th Oct. Please let me know if you need help. Thanks!

**Comment by Ovilia** [comment]
@GEMINI5516 Hi, I made a PR about this since I got no reply from you.
You are welcomed to offer help next time. 😄
