### ISSUE TITLE
饼图数据显示问题

### ISSUE THREAD

**Issue by Duzx5517** [apache/incubator-echarts#11247]
### Version
4.3.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xbRFTNETY-&v=1](https://gallery.echartsjs.com/editor.html?c=xbRFTNETY-&v=1)

### Steps to reproduce
饼图是支持输入数组数据，但并没有处理数组数据

### What is expected?
希望饼图能将数组的中数据求和，在鼠标悬停时，显示详细的数据

### What is actually happening?
在数据为数组时，饼图只讲其中一个数据进行计算

**Comment by Ovilia** [comment]
I think we should add a new feature to provide the sum value in label/tooltip formatter because I've seen several requirements like this.
@Duzx5517 Thanks for reporting. Do you wish to make a pull request about it?

**Comment by karma2014** [comment]
I am trying to fix the bug.

**Comment by karma2014** [comment]
@Duzx5517 hi，想问下你的真实需求是想让饼图支持数组数据，然后鼠标悬停显示详细数据？还是你想要一个在tootip/label的formatter中可以拿到数据总和的模版变量，然后在formatter中显示详细数据。
因为有部分同学提出想在formatter中获取整个饼图的数据，所以我想能不能你的需求和其他需求整合在一起，找一个更加通用合理的解决方案。
期待你的回复～
