### ISSUE TITLE
echart可以用在winform程序上吗？

### ISSUE THREAD

**Issue by SOSOBEN** [apache/incubator-echarts#11256]
### What problem does this feature solve?
如题，想用echart代替自带的chart控件，实现图表显示。

### What does the proposed  look like?
最好是可以有.net控件,或者有例程教我们怎么做？

**Comment by pissang** [comment]
ECharts can only run on the browser like platforms, which contain JavaScript Engine and Canvas API. Like browser and node.js

**Comment by quillblue** [comment]
You can use some addins such as [CefSharp](https://github.com/cefsharp/CefSharp) to embed browser control in .NET WinForm and use ECharts if you do want to, though not recommended practice.
