### ISSUE TITLE
官方实例打开后， 提示编辑器错误 右侧无法展示实例

### ISSUE THREAD

**Issue by usernamema** [apache/incubator-echarts#11265]
### Version
4.3.0-rc.1

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap](https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap)

### Steps to reproduce
官方实例打开后， 提示编辑器错误 右侧无法展示实例
地理坐标/地图 模块下 好几个实例都没法正常打开

### What is expected?
正常打开

### What is actually happening?
不能正常打开

**Comment by Ovilia** [comment]
Cannot reproduce. Please try to clean the cache and run again.
