### ISSUE TITLE
如何获取echarts官网的全国地区json文件

### ISSUE THREAD

**Issue by sunshineTY** [apache/incubator-echarts#11269]
如何获取echarts官网的全国地区json文件，我看官网中大家都使用
https://gallery.echartsjs.com/asset/get/s/data-1513915836999-BkHTS-qfz.json
这种方法获取json。

我不知道这个s文件夹下的json是哪些，希望有知道的给已给文件名列表。谢谢

**Comment by chfw** [comment]
非官方地图集：https://github.com/orgs/echarts-maps/dashboard
