### ISSUE TITLE
appendData报undefined？？

### ISSUE THREAD

**Issue by JedidiahY** [apache/incubator-echarts#11263]
### Version
4.1.0-rc.0

### Reproduction link
[https://www.echartsjs.com/zh/api.html#echartsInstance.appendData](https://www.echartsjs.com/zh/api.html#echartsInstance.appendData)

### Steps to reproduce
appendData报undefined？？

### What is expected?
实现增量渲染技术

### What is actually happening?
找不到appendData方法

---
"echarts": "^4.1.0",

**Comment by Ovilia** [comment]
Hello. Please provide the code.
