### ISSUE TITLE
主题构建工具需要添加关于渐变色的全局配置项

### ISSUE THREAD

**Issue by MarxZhou** [apache/incubator-echarts#11278]
### What problem does this feature solve?
我们的设计图中，折线图要求相关区域使用线性渐变色。
主要是在纵向调整颜色的透明度。
目前在series.areaStyle可以单独配置，但是这在面对大量的图表时十分痛苦，尤其是在面对自定义主题和动态生成图表Option时，基本无法便捷的控制颜色变化。
我在自定义主题中设置了8个主题色，我不想在动态生成图表Option中根据数据索引重新设置一遍主题色。
我希望能够在主题构建工具中提供一个配置项，能够开启或关闭主题色的渐变显示功能，同时还能够提供基本的渐变坐标等统一配置功能。

### What does the proposed API look like?
我希望在主题构建文件中提供类似这样的配置：
```js
{
  gradient: [
      {
        // series.areaStyle中的属性可以覆盖这里的全局配置
        type: 'linear', // 渐变类型
        x: 0,
        y: 0,
        x2: 0,
        y2: 1,
        colorStops: [
          {
            offset: 0, color: 'red', // 0% 处的颜色
          }, {
            offset: 1, color: 'blue', // 100% 处的颜色
          }],
        global: false, // 缺省为 false
        range: ['line'], // 适用于哪些图表类型
      },
  ],
}
```

**Comment by Ovilia** [comment]
把你写的这个 gradient 值作为一个变量存着，其他地方也使用这个变量，会有什么不方便吗？

**Comment by MarxZhou** [comment]
> 把你写的这个 gradient 值作为一个变量存着，其他地方也使用这个变量，会有什么不方便吗？

没有，可以随意处理。

**Comment by Ovilia** [comment]
那这个问题就解决了？

**Comment by MarxZhou** [comment]
> 那这个问题就解决了？

我认为是的，我最初的目的只是希望在引用主题构建工具生成的js文件时能够提供一个是否开启渐变色的开关。因为我前两天引入js文件的时候，折线图中的渐变色只能通过Option.series.areaStyle.color进行逐个设置。如果有这么一个开关的话，我就不必再写代码遍历了

**Comment by Ovilia** [comment]
为什么是「开关」？其实就是你把传入的 option 记录一下，下次在这个基础上改就行了。

**Comment by MarxZhou** [comment]
> 为什么是「开关」？其实就是你把传入的 option 记录一下，下次在这个基础上改就行了。

我可能没有描述清楚。

**Comment by MarxZhou** [comment]
> 为什么是「开关」？其实就是你把传入的 option 记录一下，下次在这个基础上改就行了。

我之前没有描述清楚。
我希望这里既可以传入自定义配置，也可以支持布尔值。

**Comment by MarxZhou** [comment]
> 为什么是「开关」？其实就是你把传入的 option 记录一下，下次在这个基础上改就行了。

我之前没有描述清楚。
我希望这里既可以传入自定义配置，也可以支持布尔值。

例如传入一个truthy后，可以自动实现类似下图中的简单渐变色效果。
也就是说希望echarts可以内置一些简单的效果，毕竟我的审美不是很好。

![360截图20190920135109919](https://user-images.githubusercontent.com/39861054/65302482-e9368400-dbad-11e9-86e1-a2aa50b9dad8.jpg)

**Comment by Ovilia** [comment]
这个需要在应用层由用户自己去做。
