### ISSUE TITLE
X轴的  文字能否紧贴刻度线布局

### ISSUE THREAD

**Issue by author-fuyf** [apache/incubator-echarts#11284]
### Version
4.3.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x-RDAbBZtw&v=1](https://gallery.echartsjs.com/editor.html?c=x-RDAbBZtw&v=1)

### Steps to reproduce
正常出现

### What is expected?
X轴label文字能够紧贴刻度线左侧 || 右侧

### What is actually happening?
通过align达不到预期结果

---
查找官网  没有找到属性或者方法 align left || right  也无法达到预期结果

**Comment by fuyunfeng961010** [comment]
目前的创建的例子链接与本地实际效果不一致  可能是版本的原因  正常是底部是第二条X轴控制刻度线显隐从而做大类的区分  目前的想要解决问题是描述中的那样 期望标红的文字能紧贴左侧刻度线  自定义居中的效果

**Comment by fuyunfeng961010** [comment]
![1568883889](https://user-images.githubusercontent.com/31279101/65235201-bdad8e00-db08-11e9-9a8f-c0f9bbdbb294.png)
实际是这样的效果  我现在的问题是标红文字处在 偶数列类型时   判断就无法居中  所以期望能让文字紧右侧贴刻度线 自定义拼接出居中效果  或者能有其他办法

**Comment by Ovilia** [comment]
https://echarts.apache.org/en/option.html#xAxis.axisLabel.align

**Comment by fuyunfeng961010** [comment]
@Ovilia align属性貌似并达不到我预期的效果  期望的是文字能够紧贴刻度线  如图   
![image](https://user-images.githubusercontent.com/31279101/65293033-50dbd780-db8c-11e9-81d1-d38ff2eabcc2.png)
我的设想是将需要居中显示的标红字体拆分成左右两段   标注线左侧右对齐 右侧左对齐达到居中效果  但align属性无法满足  或许我的思路就有问题  不止这样是否能够实现

**Comment by Ovilia** [comment]
可以试试富文本，可以实现比较复杂的文字效果：https://echarts.apache.org/zh/option.html#xAxis.axisLabel.rich

**Comment by fuyunfeng961010** [comment]
@Ovilia 谢谢  但rich属性中貌似也并没有能解决当前问题的属性  我早已尝试过 或许是我没有找到正确的方法

**Comment by dadaguai-git** [comment]
> @Ovilia align属性貌似并达不到我预期的效果 期望的是文字能够紧贴刻度线 如图 ![image](https://user-images.githubusercontent.com/31279101/65293033-50dbd780-db8c-11e9-81d1-d38ff2eabcc2.png) 我的设想是将需要居中显示的标红字体拆分成左右两段 标注线左侧右对齐 右侧左对齐达到居中效果 但align属性无法满足 或许我的思路就有问题 不知这样是否能够实现 同时图表是需要适应性缩放的

大佬 你这y轴向下扩展是如何实现的

**Comment by author-fuyf** [comment]
@dadaguai-git 
https://www.makeapie.cn/echarts_content/xryk_0DRml.html 
你可以参照这个双x轴实现

**Comment by author-fuyf** [comment]
@dadaguai-git 
https://www.makeapie.cn/echarts_content/xryk_0DRml.html
你可以参照这个 双x轴实现

**Comment by dadaguai-git** [comment]
> @dadaguai-git https://www.makeapie.cn/echarts_content/xryk_0DRml.html 你可以参照这个双x轴实现

再次感谢大佬 已经实现了
