### ISSUE TITLE
AxisPointer make a hidden symbol display in line chart

### ISSUE THREAD

**Issue by 100pah** [apache/incubator-echarts#11288]
### Version
4.1.0-release

### Reproduction link
[fill:///echarts/test/dataZoom-clip.html](fill:///echarts/test/dataZoom-clip.html)

### Steps to reproduce
In the first chart in `echarts/test/dataZoom-clip.html`,
do not zoom, hover mouse on the right edge of the `grid`,
a hidden cycle, which overflows the grid, will display.
And the `axisPointer` is not in the correct position.

It still happens in 4.3.0 and even probably 4.4.0.

![image](https://user-images.githubusercontent.com/1956569/65257763-50175700-db34-11e9-994a-dc4cc9a3157b.png)

### What is expected?
Normal

### What is actually happening?
hidden symbol display unexpected.

**Comment by Ovilia** [comment]
Please provide a demo based on https://jsfiddle.net/ovilia/n6xc4df3/
