### ISSUE TITLE
Radar with Log Axis throws error

### ISSUE THREAD

**Issue by zifix** [apache/incubator-echarts#11298]
### Version
4.3.0

### Steps to reproduce
1. Set up a radar chart
1. Add to options:
   ```
   radiusAxis: {
      type: 'log'
    }
    ```

### What is expected?
The same chart to render with log10-axis

### What is actually happening?
Got an exception:
```
ERROR TypeError: "radiusAxis is null"
    render RadiusAxisView.js:61
    renderComponents echarts.js:1369
    each util.js:298
    renderComponents echarts.js:1367
    render echarts.js:1353
    update echarts.js:805
    setOption echarts.js:398
```

**Comment by Ovilia** [comment]
`radiusAxis` is for bar/line charts in polar system, which is not for radar charts.

**Comment by zifix** [comment]
Hi @Ovilia, 
thanks for the clarification. I think the feature can be useful and I'm proficient in javascript, a total noob at charts though as you can see in my mix-up of the terminology 👅 
If you think that's good enough to handle the complexity of this feature, then I'm willing to give it shot.
BR
Zifix

**Comment by Ovilia** [comment]
@zifix Great!
@100pah Please give some advice on how to make this possible.

**Comment by pissang** [comment]
Hi @zifix, really appreciate your passion!

In ECharts, axis type like `'log'` is abstracted as [Scale](https://github.com/apache/incubator-echarts/blob/master/src/scale/Scale.js). There are different kinds of scales:

+ Ordinal
+ Interval
+ Log
+ Time

Ordinal scale and interval scale are the most commonly used. Ordinal is for category data, while the interval is for the `number` like data. 

We fixed the scale to be `interval` in the radar chart. https://github.com/apache/incubator-echarts/blob/master/src/coord/radar/Radar.js#L43 But as you mentioned. It's better to support `log` scale.

About how to create the `scale` from the given option. https://github.com/apache/incubator-echarts/blob/master/src/coord/axisHelper.js#L248 may be an example you can reference.

Please let us know if you have any more questions. Looking forward to your fix:)

**Comment by zifix** [comment]
@pissang Not sure if it was as easy as I think it was, but you are surely going to tell me :P
