### ISSUE TITLE
APP内嵌vue项目引入echarts，OPPOR9m手机不兼容，Android版本5.1

### ISSUE THREAD

**Issue by haidaxian** [apache/incubator-echarts#11293]
### Version
4.2.1

### Steps to reproduce
APP内嵌vue项目（webview）引入echarts，OPPOR9m(Android版本5.1)手机不兼容，只要引入echarts就打不开页面，其他高版本手机正常

### What is expected?
echarts兼容Android版本5.1

### What is actually happening?
echarts不兼容Android版本5.1

**Comment by Ovilia** [comment]
报什么错？

**Comment by haidaxian** [comment]
------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 上午10:26
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "867968023"<867968023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/incubator-echarts] APP内嵌vue项目引入echarts，OPPOR9m手机不兼容，Android版本5.1 (#11293)




报什么错？
