### ISSUE TITLE
柱状图dataZoom和markPoint同时使用,dataZoom放大到只显示某一个柱的时候,所有的markPoint同时出现在这个柱上

### ISSUE THREAD

**Issue by codeInCat** [apache/incubator-echarts#11300]
### Version
4.3.0

### Reproduction link
[https://jsfiddle.net/v8r3dx02/2/](https://jsfiddle.net/v8r3dx02/2/)

### Steps to reproduce
放大dataZoom到视图只显示一个柱

### What is expected?
markPoint正常显示

### What is actually happening?
所有的markPoint全部出现

**Comment by susiwen8** [comment]
I may have identified the problem,

**Comment by susiwen8** [comment]
Problem comes from here
https://github.com/apache/incubator-echarts/blob/master/src/util/number.js#L88
