### ISSUE TITLE
配置项文档中没有某些标签的介绍

### ISSUE THREAD

**Issue by zmheang** [apache/incubator-echarts#11307]
### Version
4.3.0

### Steps to reproduce
在配置项文档中，并没有boundaryGap的介绍，但是在某些需求上，这个属性确实可以解决我们的问题，如果是被废弃的属性，那么应当有对应的解决方案，需求是   将x轴上的标签从原点开始显示

### What is expected?
能够解决上述需求的方案

### What is actually happening?
我能尝试的只有boundaryGap可以解决

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#xAxis.boundaryGap
