### ISSUE TITLE
iphone 6/8 plus，改边dom宽度导致白屏

### ISSUE THREAD

**Issue by 13588936722** [apache/incubator-echarts#11309]
### Version
4.3.0

### Reproduction link
[https://dev.mhealth100.com/patient/cstmr-demo/test/test8.html](https://dev.mhealth100.com/patient/cstmr-demo/test/test8.html)

### Steps to reproduce
打开，发现闪一下，就白屏了

### What is expected?
不白屏，正常显示

### What is actually happening?
白屏

---
是因为改变的container的宽度导致的。我需要根据接口返回的数据来改变宽度。
我试过先渲染后改变（触发resize），试过先改变后初始化渲染（init setOption）。

**Comment by 13588936722** [comment]
真机才会出现这个bug。

**Comment by 13588936722** [comment]
再次尝试，先改变dom宽度，后续使用点击“显示图表”，图表也不显示，还是白屏。是页面渲染完成以后，再点击触发的。

**Comment by Ovilia** [comment]
4000px 在 2 倍 dpi 的情况下，宽度有 8000 了，这个内存很可能吃不消。
建议使用 dataZoom 之类的方法实现滚动 https://gallery.echartsjs.com/editor.html?c=x88x_kzcqy
或者使用 SVG 对内存消耗更少：https://echarts.apache.org/zh/tutorial.html#使用%20Canvas%20或者%20SVG%20渲染

**Comment by 13588936722** [comment]
好的，谢谢
