### ISSUE TITLE
旭日图点击其中的一层下钻后，可否支持用当前的父级替换返回的位置

### ISSUE THREAD

**Issue by 18124772589** [apache/incubator-echarts#11327]
当点击一层下钻后，中间的返回位置有点大，无法分层去设置radius: ['0%', '80%']，想要在当前父级位置点击后即可以返回上一层

**Comment by Ovilia** [comment]
当前父元素是什么意思？可否提供一个例子？

**Comment by 18124772589** [comment]
想实现的功能附件图


var item1 = {
    color: '#F54F4A'
};
var item2 = {
    color: '#FF8C75'
};
var item3 = {
    color: '#FFB499'
};


var data = [{
    children: [{
        value: 5,
        children: [{
            value: 1,
            itemStyle: item1
        }, {
            value: 2,
            children: [{
                value: 1,
                itemStyle: item2
            }]
        }, {
            children: [{
                value: 1
            }]
        }],
        itemStyle: item1
    }, {
        value: 10,
        children: [{
            value: 6,
            children: [{
                value: 1,
                itemStyle: item1
            }, {
                value: 1
            }, {
                value: 1,
                itemStyle: item2
            }, {
                value: 1
            }],
            itemStyle: item3
        }, {
            value: 2,
            children: [{
                value: 1
            }],
            itemStyle: item3
        }, {
            children: [{
                value: 1,
                itemStyle: item2
            }]
        }],
        itemStyle: item1
    }],
    itemStyle: item1
}, {
    value: 9,
    children: [{
        value: 4,
        children: [{
            value: 2,
            itemStyle: item2
        }, {
            children: [{
                value: 1,
                itemStyle: item1
            }]
        }],
        itemStyle: item1
    }, {
        children: [{
            value: 3,
            children: [{
                value: 1
            }, {
                value: 1,
                itemStyle: item2
            }]
        }],
        itemStyle: item3
    }],
    itemStyle: item2
}, {
    value: 7,
    children: [{
        children: [{
            value: 1,
            itemStyle: item3
        }, {
            value: 3,
            children: [{
                value: 1,
                itemStyle: item2
            }, {
                value: 1
            }],
            itemStyle: item2
        }, {
            value: 2,
            children: [{
                value: 1
            }, {
                value: 1,
                itemStyle: item1
            }],
            itemStyle: item1
        }],
        itemStyle: item3
    }],
    itemStyle: item1
}, {
    children: [{
        value: 6,
        children: [{
            value: 1,
            itemStyle: item2
        }, {
            value: 2,
            children: [{
                value: 2,
                itemStyle: item2
            }],
            itemStyle: item1
        }, {
            value: 1,
            itemStyle: item3
        }],
        itemStyle: item3
    }, {
        value: 3,
        children: [{
            value: 1,
        }, {
            children: [{
                value: 1,
                itemStyle: item2
            }]
        }, {
            value: 1
        }],
        itemStyle: item3
    }],
    itemStyle: item1
}];






option = {
    series: {
        radius: ['0%', '80%'],
        type: 'sunburst',
        sort: null,
        highlightPolicy: 'ancestor',
        data: data,
        label: {
            rotate: 'radial'
        },
        levels: [
            {},{},{}],
        itemStyle: {
            color: '#ddd',
            borderWidth: 2
        }
    }
};


   myChart.on('click', (params) => {
        console.log(params) 
       
      })







------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 下午4:27
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送：  “ 594725475” <594725475@qq.com>;“作者” <author@noreply.github.com>;
主题: Re: [apache/incubator-echarts] 旭日图点击其中的一层下钻后，可否支持用当前的父级替换返回的位置 (#11327)




当前父元素是什么意思？可否提供一个例子？
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或使该线程静音。

**Comment by 18124772589** [comment]
`var item1 = {
    color: '#F54F4A'
};
var item2 = {
    color: '#FF8C75'
};
var item3 = {
    color: '#FFB499'
};

var data = [{
    children: [{
        value: 5,
        children: [{
            value: 1,
            itemStyle: item1
        }, {
            value: 2,
            children: [{
                value: 1,
                itemStyle: item2
            }]
        }, {
            children: [{
                value: 1
            }]
        }],
        itemStyle: item1
    }, {
        value: 10,
        children: [{
            value: 6,
            children: [{
                value: 1,
                itemStyle: item1
            }, {
                value: 1
            }, {
                value: 1,
                itemStyle: item2
            }, {
                value: 1
            }],
            itemStyle: item3
        }, {
            value: 2,
            children: [{
                value: 1
            }],
            itemStyle: item3
        }, {
            children: [{
                value: 1,
                itemStyle: item2
            }]
        }],
        itemStyle: item1
    }],
    itemStyle: item1
}, {
    value: 9,
    children: [{
        value: 4,
        children: [{
            value: 2,
            itemStyle: item2
        }, {
            children: [{
                value: 1,
                itemStyle: item1
            }]
        }],
        itemStyle: item1
    }, {
        children: [{
            value: 3,
            children: [{
                value: 1
            }, {
                value: 1,
                itemStyle: item2
            }]
        }],
        itemStyle: item3
    }],
    itemStyle: item2
}, {
    value: 7,
    children: [{
        children: [{
            value: 1,
            itemStyle: item3
        }, {
            value: 3,
            children: [{
                value: 1,
                itemStyle: item2
            }, {
                value: 1
            }],
            itemStyle: item2
        }, {
            value: 2,
            children: [{
                value: 1
            }, {
                value: 1,
                itemStyle: item1
            }],
            itemStyle: item1
        }],
        itemStyle: item3
    }],
    itemStyle: item1
}, {
    children: [{
        value: 6,
        children: [{
            value: 1,
            itemStyle: item2
        }, {
            value: 2,
            children: [{
                value: 2,
                itemStyle: item2
            }],
            itemStyle: item1
        }, {
            value: 1,
            itemStyle: item3
        }],
        itemStyle: item3
    }, {
        value: 3,
        children: [{
            value: 1,
        }, {
            children: [{
                value: 1,
                itemStyle: item2
            }]
        }, {
            value: 1
        }],
        itemStyle: item3
    }],
    itemStyle: item1
}];



option = {
    series: {
        radius: ['0%', '80%'],
        type: 'sunburst',
        sort: null,
        highlightPolicy: 'ancestor',
        data: data,
        label: {
            rotate: 'radial'
        },
        levels: [
            {},{},{}],
        itemStyle: {
            color: '#ddd',
            borderWidth: 2
        }
    }
};

   myChart.on('click', (params) => {
        console.log(params) 
       
      })


###想实现的功能：
点击第一级的图表后，以点击的第一级为父节点图表，将中间返回的图表隐藏，并再次点击父节点图表，可返回上一级

**Comment by 18124772589** [comment]
这个功能是目前没有的吗？

**Comment by Ovilia** [comment]
不太理解「点击第一级的图表后，以点击的第一级为父节点图表，将中间返回的图表隐藏，并再次点击父节点图表，可返回上一级」，能画个示意图吗？

**Comment by 18124772589** [comment]
http://testm.jianzaogong.com/figure_01.png
http://testm.jianzaogong.com/figure_02.png

以上图片链接是示意图

**Comment by Ovilia** [comment]
看起来并没有真正「下钻」，如果外层节点位置都没变，怎么表示更多数据呢？

**Comment by 18124772589** [comment]
那可以改变中间的样式吗？像如下图中的样式，加个返回或者写个文字，让用户知道是可以点击返回的，有可以配置的地方吗？http://testm.jianzaogong.com/figure_03.png

**Comment by Ovilia** [comment]
@18124772589 可以通过 graphic.elements 画这个返回按钮，以及处理事件
