### ISSUE TITLE
鼠标移出图表后symbol和tooltip残留

### ISSUE THREAD

**Issue by chillyond** [apache/incubator-echarts#11329]
### Version
3.5.3

### Steps to reproduce
创建一个小尺寸的折线图表，开启tooltip功能，鼠标快速在图表上来回移入移出几次，很容易出现这个问题：
![image](https://user-images.githubusercontent.com/11400674/65666909-3fee0300-e071-11e9-854d-2a927f905f21.png)

### What is expected?
鼠标移出图表后，symbol和tooltip应该消失

### What is actually happening?
鼠标移出图表后，symbol和tooltip经常不消失

**Comment by Ovilia** [comment]
Please provide a demo on [jsfiddle](https://jsfiddle.net/ovilia/n6xc4df3/).

**Comment by tech-poor** [comment]
请问这个问题解决了吗？我在移动端使用时有类似问题，在图表外点击，但是tooltip一直存在（这个是偶然性发生的）

**Comment by chillyond** [comment]
> 请问这个问题解决了吗？我在移动端使用时有类似问题，在图表外点击，但是tooltip一直存在（这个是偶然性发生的）

你可以试试在id容器上绑定一个`mouseleave`事件，在处理程序里面给canvas手动dispatch一个`mouseout`事件。
