### ISSUE TITLE
在mouseover的时候，使用setoption设置radar的indicator的时候，数据会无限叠加

### ISSUE THREAD

**Issue by IIIIIIIIF** [apache/incubator-echarts#11331]
在mouseover的时候，使用setoption设置radar的indicator的时候，数据会无限叠加

**Comment by IIIIIIIIF** [comment]
设置radar的indicator中经过的字体名称的颜色的时候，数据一直叠加

			options = {
					 radar: [{
						 indicator: setindicator
						 }],	
			}
			radarEchartsBox.setOption(options)

**Comment by Ovilia** [comment]
Please use [issue template](https://ecomfe.github.io/echarts-issue-helper/) to create an issue and provide an online demo from [jsfiddle](https://jsfiddle.net/ovilia/n6xc4df3/).
