### ISSUE TITLE
Bar series is bar width is not adjusted when xAxis is time and min/max is defined

### ISSUE THREAD

**Issue by gajus** [apache/incubator-echarts#11333]
### Version
4.3.0

### Reproduction link
[https://codesandbox.io/s/echarts-showhide-labels-in-bars-e6y1x](https://codesandbox.io/s/echarts-showhide-labels-in-bars-e6y1x)

### Steps to reproduce
1. xAxis must be time and define min/ max that are greater than the series date range

### What is expected?
I expect the series bar width to be adjusted based on the min/ max constraints.

### What is actually happening?
The bars are not resized and overlap each other.

**Comment by yufeng04** [comment]
This issue has been planed to fix in [milesstone 4.5.0](https://github.com/apache/incubator-echarts/milestone/14)

**Comment by gajus** [comment]
Invalid issue. That is not the codesandbox I intended to share.
