### ISSUE TITLE
angular 6 打包完之后echarts 图表不显示

### ISSUE THREAD

**Issue by fashiontai** [apache/incubator-echarts#11330]
我引用的echarts4.1.0版本的js，在用angular 6 打包完之后 echarts不报错但是图表不显示，有tooltip，不知道什么原因

**Comment by Ovilia** [comment]
你好，请检查第三方项目相关问题，这个问题应该与 ECharts 无关。

**Comment by yimingsue** [comment]
angular8打包完，一样不渲染图表，有什么解决方案吗
