### ISSUE TITLE
echarts自动resize之后直角坐标系X轴的标签有部分无法正常显示出来

### ISSUE THREAD

**Issue by somsne** [apache/incubator-echarts#11340]
### Version
4.3.0

### Reproduction link
[https://www.echartsjs.com/examples/zh/editor.html?c=bar-waterfall](https://www.echartsjs.com/examples/zh/editor.html?c=bar-waterfall)

### Steps to reproduce
将窗口宽度拖动到550px以下，此时作为分类轴的X轴部分标签会隐藏来防止标签互相覆盖。
再将窗口拖动回正常大小，如1900px，此时作为分类轴的X轴标签因为不再会互相覆盖，应该要全部显示出来，但并没有正常显示。
保持窗口大小，刷新页面后隐藏的标签正常显示。

### What is expected?
X轴标签应该在互相不会覆盖时全部正常显示

### What is actually happening?
调整到不覆盖情况下时，依旧无法显示

**Comment by Ovilia** [comment]
同 #11112，这个问题会在 4.5.0 修复。
