### ISSUE TITLE
toolTip的formatter属性里，用function自定义时，打印出params.seriesName不能跟配置的系列名对应

### ISSUE THREAD

**Issue by yc111** [apache/incubator-echarts#11347]
### Version
4.3.0

### Steps to reproduce
鼠标悬浮到地图，观察分组名，全都是第一个系列的名称

### What is expected?
跟系列名对应起来

### What is actually happening?
全部是第一个系列名称

**Comment by yufeng04** [comment]
Could you provide a reproducible demo?

**Comment by yc111** [comment]
gallery.echartsjs.com 提交不了，我开了个repo作为demo：http://champyin.com/echarts-issues/

**Comment by zhouxin860114** [comment]
你点点图例试试，把「分组1」隐藏了试试：

是不是都是「分组2」了？

你这两个 series 是罗在一起的地图啊～

**Comment by zhouxin860114** [comment]
你点下图例试试：

把「分组1」隐藏，是不是都是「分组2」了？

你这两个 series 是两个罗在一起的中国地图啊= =

**Comment by zhouxin860114** [comment]
你点下图例试试：

把「分组1」隐藏，是不是都是「分组2」了？

你这两个 series 是两个罗在一起的两张中国地图啊= =

**Comment by yc111** [comment]
嗯，但是不使用formatter自定义的时候，是可以区分「分组1」和 「分组2」的，你可以拉一下我的demo源码，把formatter注释掉看看效果。

所以echarts应该是支持地图罗在一起的时候区分分组的。

**Comment by yc111** [comment]
我更新了问题复现demo：http://champyin.com/echarts-issues/
加入了效果对比。

**Comment by zhouxin860114** [comment]
额，在原楼层改了好几回……

**Comment by yc111** [comment]
@zhouxin860114 因为我需要展示图例，所以需要使用多个series。如果像你建议的那样，我的图例没法展示了。

**Comment by zhouxin860114** [comment]
说得有点乱，总结一下，我估计是这么回事：
1、你的两个 map series 是重叠的，最上层的 series 是「分组1」
2、「分组1」显示时，鼠标事件被「分组1」的图形捕获，params 里的 series 是「分组1」，所以自定义的 formatter 只能显示「分组1」的属性
3、 默认的 formatter 似乎会遍历所有 series，把有数据的 series 都显示出来，并把数值相加，如下图：
![image](https://user-images.githubusercontent.com/8022228/66546429-92e6b080-eb6f-11e9-92cd-944811701d08.png)
![image](https://user-images.githubusercontent.com/8022228/66546769-46e83b80-eb70-11e9-8a47-c98df094017b.png)

```
formatTooltip: function(dataIndex) {
    // FIXME orignalData and data is a bit confusing
    var data = this.getData();
    var formattedValue = addCommas(this.getRawValue(dataIndex));
    var name = data.getName(dataIndex);

    var seriesGroup = this.seriesGroup;
    var seriesNames = [];
    for (var i = 0; i < seriesGroup.length; i++) {
        var otherIndex = seriesGroup[i].originalData.indexOfName(name);
        var valueDim = data.mapDimension('value');
        if (!isNaN(seriesGroup[i].originalData.get(valueDim, otherIndex))) {
            seriesNames.push(
                encodeHTML(seriesGroup[i].name)
            );
        }
    }

    return seriesNames.join(', ') + '<br />' +
        encodeHTML(name + ' : ' + formattedValue);
},
```
——————————————————
图例可以自定义，第一个回答里，我后来贴上的那段代码，就是包含自定义图例的

**Comment by zhouxin860114** [comment]
还有一个思路，就是 formatter 的回调函数里，只通过 params.name 确定省份，然后通过省份去原始数据中查询分组信息、数值等；

这样你就可以用多个 series[i]-map 了

**Comment by yc111** [comment]
@zhouxin860114 分析的很有道理，按照你的方式可以实现我想要的效果，3Q～

**Comment by zhouxin860114** [comment]
> @zhouxin860114 分析的很有道理，按照你的方式可以实现我想要的效果，3Q～

不客气 ：D
