### ISSUE TITLE
Y轴刻度线部分隐藏的问题

### ISSUE THREAD

**Issue by Rychou** [apache/incubator-echarts#11349]
![image](https://user-images.githubusercontent.com/25195267/65825066-ed952800-e2a4-11e9-9c40-00e1af1aeaf2.png)
如上图，控制了Y轴label显示，现在想把那些没有显示label的刻度线隐藏起来要怎么实现呢？

**Comment by yufeng04** [comment]
Maybe you can set `yAxis.type` to `category`.
