### ISSUE TITLE
xaxis type=time labels do not reflect series data

### ISSUE THREAD

**Issue by gajus** [apache/incubator-echarts#11341]
### Version
4.3.0

### Reproduction link
[https://codesandbox.io/s/echarts-xaxis-time-ef3e3](https://codesandbox.io/s/echarts-xaxis-time-ef3e3)

### Steps to reproduce
1. create xaxis type=time
2. populate series with date range from 2019-10-01 to 2019-10-31

### What is expected?

I expect labels to be dates from "2019-10-01 00:00" to "2019-10-31 00:00".

### What is actually happening?

Last label is "2019-10-30 23:00" instead of "2019-10-31 00:00".

**Comment by susiwen8** [comment]
![Screen Shot 2019-09-27 at 18 34 19](https://user-images.githubusercontent.com/20318608/65763228-8157de80-e155-11e9-9e97-17f51d74b51e.png)
Last label is "2019-10-31 00:00"

**Comment by gajus** [comment]
Not when I view it.

<img width="748" alt="Screenshot 2019-09-27 at 15 36 56" src="https://user-images.githubusercontent.com/973543/65769625-ad1a9a80-e13c-11e9-9d8f-1a6000f47b0c.png">

Using Chrome latest version on macos.

**Comment by Ovilia** [comment]
This may be a bug related to time-zone. @gajus Could you tell us what your time-zone is?

**Comment by gajus** [comment]
Eastern European Summer Time

**Comment by gajus** [comment]
This shouldn't say waiting-for: author anymore.

**Comment by Ovilia** [comment]
Thanks for your update. Let's see if we can get this fixed in 4.6.0.

**Comment by devyumao** [comment]
Eastern European Summer Time is a daylight saving time zone with which different browsers handle in different ways, e.g., the timestamp 1572472800000 in Firefox is equivalent to '2019-10-31 00:00', but in Chrome it is '2019-10-30 23:00'.
I'm not sure whether this is a bug. Hereby to let you know. @100pah

**Comment by 100pah** [comment]
@devyumao Chrome and Firefox are the same in my computer for `new Date(1572469200000)`,
they are both `Wed Oct 30 2019 23:00:00 GMT+0200 (Eastern European Standard Time)`

**Comment by 100pah** [comment]
@gajus 
By default, echarts uses local timezone to formate time labels.
But if we set timezone to Eastern European, there would be 
`Eastern European Summer Time` issue, as @devyumao said.

The boundary of `Eastern European Summer Time` and `Eastern European Standard Time` is:
```
new Date(1572137999999)
Sun Oct 27 2019 03:59:59 GMT+0300 (Eastern European Summer Time)
new Date(1572137999999 + 1)
Sun Oct 27 2019 03:00:00 GMT+0200 (Eastern European Standard Time)
```

In your case, the time axis is from Oct 1 to Oct 31, which crosses the boundary (about Oct 27),
so the time labels look weird.

So, the option [useUTC](http://echarts.apache.org/en/option.html#useUTC) is recommended in your case:
```js
option = {
    useUTC: true,
    xAxis: {...},
    yAxis: {...}
    series: {
        ...
    }
}
```
If you are using string-formatted time in data (for example, `"2019-10-01"`),
we do not need to convert the time to UTC, it's OK to keep the current time data.
The `useUTC` just make sure all of the string time formatted in consistent way.

**Comment by Ovilia** [comment]
Closed due to not-a-bug.
