### ISSUE TITLE
配置项手册 dataZoom-inside.preventDefaultMouseMove 文档错误

### ISSUE THREAD

**Issue by lyklinse** [apache/incubator-echarts#11342]
### Version
4.3.0

### Reproduction link
[https://echarts.apache.org/zh/option.html#dataZoom-inside.preventDefaultMouseMove](https://echarts.apache.org/zh/option.html#dataZoom-inside.preventDefaultMouseMove)

### Steps to reproduce
1. 访问配置项文档地址https://echarts.apache.org/zh/option.html#dataZoom-inside.preventDefaultMouseMove
2. false：表示鼠标滚轮不能触发平移。 --> 应修改为  false：表示鼠标移动不能触发平移。

### What is expected?
应修改为  false：表示鼠标移动不能触发平移。

### What is actually happening?
 false：表示鼠标滚轮不能触发平移。

**Comment by Ovilia** [comment]
Thanks for reporting. It has been fixed and will be updated to the Website soon.
