### ISSUE TITLE
tooltip中的trigger问题

### ISSUE THREAD

**Issue by 1ET** [apache/incubator-echarts#11353]
如果当前数据配置的series为十个,鼠标移动到图表上会显示10条数据的值,再把新的series数据更改为三个的话，鼠标移动到图表上还是会显示10条数据的值,只有前三条是正确的，其余7条为上条数据的值，如果每次更新     option=》tooltip=》trigger 的值 axis 则不会出现问题，但是会导致数据无法连线

**Comment by yufeng04** [comment]
Could you provide a reproducible demo?

**Comment by Ovilia** [comment]
请使用 [issue 模板](https://ecomfe.github.io/echarts-issue-helper/)创建问题
