### ISSUE TITLE
echarts4.3.0渐进渲染

### ISSUE THREAD

**Issue by syanling** [apache/incubator-echarts#11350]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.
echarts4.3.0版本在geo地图上绘制散点，使用progressiveThreshold属性，并且data数量达到该阈值后，geo缩放或者平移，这些散点都不跟随坐标移动。

**Comment by syanling** [comment]
在geo地图上绘制散点，使用progressiveThreshold属性，并且data数量达到该阈值后，当geo缩放或者平移时，在echarts4.3.0版本中这些散点都不跟随坐标移动，在低于4.3.0版本中，这些散点跟随坐标移动，但每次移动或者鼠标覆盖到散点上时，所以散点又会重新渲染一遍。

**Comment by Ovilia** [comment]
请使用 issue 模板创建问题。
