### ISSUE TITLE
Parrallel Nutrients Chart 的 Legend 能不能换成 scrollable

### ISSUE THREAD

**Issue by JJack77** [apache/incubator-echarts#11366]
### Version
4.2.1

### Steps to reproduce
要如何制作 scrollable 的 Legend.
由于我的item有200多个  我不能同时间把全部的item展示出来
我尝试过把 Legend type 换成 scroll 可是没效果 反而跳出另外一个 legend 出来

### What is expected?
能 scroll 的 Legend

### What is actually happening?
Legend 跟之前一样什么都没变

**Comment by yufeng04** [comment]
The scrollable legend works in this [example](https://echarts.apache.org/examples/zh/editor.html?c=pie-legend&edit=1&reset=1). if you are sure that the your option is correct, please provide a reproducible demo.

**Comment by JJack77** [comment]
![image](https://user-images.githubusercontent.com/51741408/66279831-450b4780-e8e6-11e9-91d5-9bdf7e7920d0.png)
I just copy and paste your legend option into this chart and it pop out another legend.

**Comment by yufeng04** [comment]
Please provide a reproducible demo.
