### ISSUE TITLE
datazoom event not detected from roam mousewheel or toolbox

### ISSUE THREAD

**Issue by amygroshek** [apache/incubator-echarts#11361]
### Version
4.3.0

### Reproduction link
[https://www.echartsjs.com/examples/en/editor.html?c=graph](https://www.echartsjs.com/examples/en/editor.html?c=graph)

### Steps to reproduce
1. Edit example code to be this (adding datazoom event listener at very bottom): 

```
myChart.showLoading();
$.get(ROOT_PATH   'data/asset/data/les-miserables.gexf', function (xml) {
    myChart.hideLoading();

    var graph = echarts.dataTool.gexf.parse(xml);
    var categories = [];
    for (var i = 0; i < 9; i  ) {
        categories[i] = {
            name: '类目'   i
        };
    }
    graph.nodes.forEach(function (node) {
        node.itemStyle = null;
        node.value = node.symbolSize;
        node.symbolSize /= 1.5;
        node.label = {
            normal: {
                show: node.symbolSize > 30
            }
        };
        node.category = node.attributes.modularity_class;
    });
    option = {
        title: {
            text: 'Les Miserables',
            subtext: 'Default layout',
            top: 'bottom',
            left: 'right'
        },
        tooltip: {},
        legend: [{
            // selectedMode: 'single',
            data: categories.map(function (a) {
                return a.name;
            })
        }],
        animationDuration: 1500,
        animationEasingUpdate: 'quinticInOut',
        series : [
            {
                name: 'Les Miserables',
                type: 'graph',
                layout: 'none',
                data: graph.nodes,
                links: graph.links,
                categories: categories,
                roam: true,
                focusNodeAdjacency: true,
                itemStyle: {
                    normal: {
                        borderColor: '#fff',
                        borderWidth: 1,
                        shadowBlur: 10,
                        shadowColor: 'rgba(0, 0, 0, 0.3)'
                    }
                },
                label: {
                    position: 'right',
                    formatter: '{b}'
                },
                lineStyle: {
                    color: 'source',
                    curveness: 0.3
                },
                emphasis: {
                    lineStyle: {
                        width: 10
                    }
                }
            }
        ]
    };

    myChart.setOption(option);
    
   // Add this to sample 
    myChart.on('datazoom', function(e) {
        console.log('zoom');
    });
   // End add this
}, 'xml');
```

2. Zoom with mouse action (or add toolbox zoom controls and zoom that way). 

3. No zoom event is detected.

### What is expected?
A zoom event is detected. 

### What is actually happening?
Nothing.

---
Options from my own similar project: 

```
setup.options = {
  title: {
    top: 'bottom',
    left: 'right'
  },
  animation: false,
  tooltip: {
    trigger: 'item',
    position: 'right',
    confine: true,
    backgroundColor: 'transparent',
    padding: [40, 0, 0, 0],
    enterable: false,
    formatter: function(item) {
      return 'Click for more';
    }
  },
  series : [
    {
      name: '###',
      type: 'graph',
      layout: 'force',
      force: {
        repulsion: 95,
        gravity: 0.015,
        edgeLength: 40,
        layoutAnimation: false
      },
      roam: true,
      draggable: true,
      data: setup.nodes,
      links: setup.links,
      focusNodeAdjacency: true,
      itemStyle: {
        normal: {
          borderColor: '#fff',
          borderWidth: 1,
          shadowBlur: 10,
          shadowColor: 'rgba(0, 0, 0, 0.3)'
        }
      },
      lineStyle: {
        color: 'source',
        curveness: 0.3
      },
      emphasis: {
        lineStyle: {
          width: 10
        }
      }
    }
  ]
};
```

**Comment by amygroshek** [comment]
@yufeng04 I don't even know how to respond to that. That example has a completely different kind of series. I'm talking about a chart with a graph-type series... I have clearly demonstrated that the event is not detected when applied to *the eCharts example which most closely resembles my project*. I have provided very clear instructions for replication.

**Comment by yufeng04** [comment]
Sorry, I made a mistake to take `option.dataZoom` into consideration just now.
According to the [code](https://github.com/apache/incubator-echarts/blob/master/src/chart/graph/GraphView.js#L349)， maybe you can use:
```
myChart.on('graphRoam', function(e) {
        console.log('zoom');
});
```
Hope it helps you!

**Comment by amygroshek** [comment]
@yufeng04 `graphRoam` works! Thank you! I can't get zoom start and end, but I am able to detect the event and see whether it's zoom in or out.

**Comment by Gokulakannanaj** [comment]
@amygroshek @Ovilia @yufeng04 @devyumao @SuperZDev  - Can you help me to sort out from this issue?
I'm missing some dependency. So it's showing $ not a function and here is my code

`<html>
	<head>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/4.1.0/echarts-en.common.min.js"></script>
	</head>
	<body>
		<div id="canvas" style="width: 100%; height: 359px"/>
		<script type="text/javascript">
			let myChart = echarts.init(document.querySelector('#canvas'));

			myChart.showLoading();
			$(this).get('https://ecomfe.github.io/echarts-examples/public/data/asset/data/les-miserables.gexf', function (xml) {
			    myChart.hideLoading();

			    var graph = echarts.dataTool.gexf.parse(xml);
			    var categories = [];
			    for (var i = 0; i < 9; i++) {
				categories[i] = {
				    name: '类目' + i
				};
			    }
			    graph.nodes.forEach(function (node) {
				node.itemStyle = null;
				node.value = node.symbolSize;
				node.symbolSize /= 1.5;
				node.label = {
				    normal: {
					show: node.symbolSize > 30
				    }
				};
				node.category = node.attributes.modularity_class;
			    });
			    option = {
				title: {
				    text: 'Les Miserables',
				    subtext: 'Default layout',
				    top: 'bottom',
				    left: 'right'
				},
				tooltip: {},
				legend: [{
				    // selectedMode: 'single',
				    data: categories.map(function (a) {
					return a.name;
				    })
				}],
				animationDuration: 1500,
				animationEasingUpdate: 'quinticInOut',
				series : [
				    {
					name: 'Les Miserables',
					type: 'graph',
					layout: 'none',
					data: graph.nodes,
					links: graph.links,
					categories: categories,
					roam: true,
					focusNodeAdjacency: true,
					itemStyle: {
					    normal: {
						borderColor: '#fff',
						borderWidth: 1,
						shadowBlur: 10,
						shadowColor: 'rgba(0, 0, 0, 0.3)'
					    }
					},
					label: {
					    position: 'right',
					    formatter: '{b}'
					},
					lineStyle: {
					    color: 'source',
					    curveness: 0.3
					},
					emphasis: {
					    lineStyle: {
						width: 10
					    }
					}
				    }
				]
			    };

			    myChart.setOption(option);
			}, 'xml');
		</script>
	</body>
</html>`

**Comment by feishi20** [comment]
```
// source: ./node_modules/echarts/src/chart/map/MapView.js  (echarts@4.6.0)
 this.chart.on('geoRoam', (event: any) => {
    if (event) {
      const { type, zoom } = event;

      if (type === 'georoam' && zoom) {
        // zoom value may changed with roam
        const chartInfo = this.chart.getModel().getComponent('geo');
        if (chartInfo) {
          const currentZoom = chartInfo.coordinateSystem._zoom;
          ...
        }
      }
    }
  });
```

**Comment by lougroshek** [comment]
@Gokulakannanaj
