### ISSUE TITLE
axis pointer highlights data outside of chart

### ISSUE THREAD

**Issue by tmtron** [apache/incubator-echarts#11360]
### Version
4.4.0-rc.1

### Reproduction link
[https://jsfiddle.net/tmtron/f8pwxe63/](https://jsfiddle.net/tmtron/f8pwxe63/)

### Steps to reproduce
when we use clip='true', the axis pointer will show data that is outside of the chart grid  
* note, that we have set `max` for the y-Axis
* this is maybe related to #11240

![image](https://user-images.githubusercontent.com/20422904/65861288-424fa600-e36c-11e9-9c98-5db8900934bb.png)  

### What is expected?
when clip='true' the data outside of the chart grid should be hidden

### What is actually happening?
when clip='true' the data outside of the chart grid is shown

**Comment by yufeng04** [comment]
It seems to be a bug. But the reason may be `yAxis.max`.

**Comment by SnailSword** [comment]
fixed in #11548 .
