### ISSUE TITLE
Bar chart: Log y-Axis not working

### ISSUE THREAD

**Issue by tmtron** [apache/incubator-echarts#11364]
### Version
4.4.0-rc.1

### Reproduction link
[https://jsfiddle.net/tmtron/4fguo0wn/5/](https://jsfiddle.net/tmtron/4fguo0wn/5/)

### Steps to reproduce
Just execute the jsfiddle example: it does not show any bars  
![image](https://user-images.githubusercontent.com/20422904/66051177-be91e700-e52e-11e9-9129-4050d6e5c61d.png)

### What is expected?
It should show bars on the logarithmic y-axis.  
![image](https://user-images.githubusercontent.com/20422904/66051203-c8b3e580-e52e-11e9-9c03-20cb428195b4.png)

### What is actually happening?
No bars are shown

---
The same options worked fine in version 4.3.0: see this [js-fiddle example](https://jsfiddle.net/tmtron/4fguo0wn/4/):

**Comment by Ovilia** [comment]
Thanks for reporting. This seems to be a bug.

**Comment by susiwen8** [comment]
Duplicate with #11403, fix with #11472.

**Comment by tmtron** [comment]
works with 4.9.0 - see https://jsfiddle.net/tmtron/aktdey3f/1/
