### ISSUE TITLE
Too Large Bundle size

### ISSUE THREAD

**Issue by top-dev830** [apache/incubator-echarts#11375]
### Version
4.3.0

### Steps to reproduce
I'm using echarts on my vue app. After install this module and I build this, but the bundle size was too big. The parsed file size was 630 KB.
I noticed that it loads all components and charts and so on.

### What is expected?
I only want to load one or two chart like line, bar charts.
So that I can reduce my bundle size.

### What is actually happening?
The bundle size was too big.

**Comment by top-dev830** [comment]
![echarts](https://user-images.githubusercontent.com/35139226/66442550-ce00bb00-ea6d-11e9-9921-33c472e532ff.png)

I want to import only used charts

**Comment by Ovilia** [comment]
[This](https://echarts.apache.org/en/builder.html) is a tool to build with the components you need.
We are considering doing a more aggressive bundle size reduction job with v5.0, but for now, the builder tool is all you can do.

**Comment by top-dev830** [comment]
ok, thanks. I will wait for the new version.

**Comment by Ovilia** [comment]
I'm going to close this for now.

**Comment by railsstudent** [comment]
I have the same issue, when is the scheduled release date of v5?

**Comment by johannesjo** [comment]
The situation hasn't much improved as far as I am aware:
https://bundlephobia.com/package/echarts@5.5.0
