### ISSUE TITLE
same excel can't be  upload in different charts

### ISSUE THREAD

**Issue by CNzxy0820** [apache/incubator-echarts#11370]
### Version
4.3.0-rc.2

### Steps to reproduce
import the excel to ECharts, press "F12" key,you will see “Uncaught TypeError: Cannot read property 'type' of undefined”，I debugged my code, I found when I set second option,which is setOption, the process ended.

### What is expected?
I want use one excel import four charts.

### What is actually happening?
an error.

---
Reproduce link is my local server 192.168.101.72,it can't be wrote in reprodece link,and,it not sure online,so I explain my problem angin,I want set second option,which is setOption for my second chart.but when I imported the excel,the error appeared,I debugged my code and I found the process ended before my second Option.

**Comment by CNzxy0820** [comment]
I also want to know,whether the globe can use the events.geoselected,I want use some interaction in my  globe.

**Comment by CNzxy0820** [comment]
I found some new problem,my four charts,only two charts were erroring,I am checking my code

**Comment by CNzxy0820** [comment]
I solve my problem.... haha^$^

**Comment by Ovilia** [comment]
Close due to problem fixed.
