### ISSUE TITLE
IE浏览器下graphic.style.font属性中使用em像素单位导致onclick方法失效

### ISSUE THREAD

**Issue by FuckAName** [apache/incubator-echarts#11384]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by FuckAName** [comment]
option = {
    graphic: {
        "type": "text",
        top: 10,
        "style": {
            "text": "Read Throughput",
            "fill": "#38a8ff",
            "font": "bolder 0.875em \"Microsoft Yahei\"",
            "textBaseline": null,
            "textVerticalAlign": null,
            "textFill": "#38a8ff"
        },
        onclick: function () {
            console.log("aaa");
        }
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
            data: [820, 932, 901, 934, 1290, 1330, 1320],
            type: 'line'
        }
    ]
};

**Comment by FuckAName** [comment]
What is expected?
IE浏览器下onclick方法正常使用

What is actually happening?
IE浏览器下onclick方法失效，大概定位了下，graphic style font属性一旦使用em就会出现此问题

**Comment by FuckAName** [comment]
![image](https://user-images.githubusercontent.com/49164323/66640989-78363980-ec4c-11e9-805d-90dc40f15f0b.png)
如图，点击标题“Read”文字，无任何反应，IE版本见下图
![image](https://user-images.githubusercontent.com/49164323/66641067-9734cb80-ec4c-11e9-9e3d-8b0bbb5067bd.png)

**Comment by Ovilia** [comment]
`em` is not supported currently. There is a PR to support `rem`. @100pah @pissang Please help review that PR when you have time.
@FuckAName Could you consider using `px` instead of `em`?

**Comment by FuckAName** [comment]
现在用px规避问题了，如果浏览器兼容性有差异，建议配置项手册进行说明
![image](https://user-images.githubusercontent.com/49164323/66793879-d9525b80-ef31-11e9-85fb-67e7b310e7de.png)
