### ISSUE TITLE
Label enhancement on pie.

### ISSUE THREAD

**Issue by coderLuow** [apache/incubator-echarts#11381]
设计给的效果图如下，引导线处增加圆点，这个如何实现呢？

![pie](https://user-images.githubusercontent.com/25339986/66620420-fbd33480-ec12-11e9-9794-9e9545fd0f7e.png)

This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by Ovilia** [comment]
There have been several similar requirements. I think we should support this, along with aligning labels on the left side and right side. This can also help solve the problem of text being outside of the Canvas.

**Comment by ydostyle** [comment]
没有增加圆点啊
