### ISSUE TITLE
Disabling zoom function by scrolling in 3Dbar

### ISSUE THREAD

**Issue by ahmadordi** [apache/incubator-echarts#11398]
Hi, 
I am trying to disable zoom function by scrolling on 3Dbar graph. I have done it with other graphs, but the same way doesn't work fpr 3Dbar. Unfortunetely there is also no information in documentation about 3Dbar types.

**Comment by deqingli** [comment]
please provide the way how you disable this.

**Comment by pissang** [comment]
Hi, you can set `viewControl.zoomSensitivity` to `0` to disable the zoom function

**Comment by ahmadordi** [comment]
> please provide the way how you disable this.

I only set an empty dataZoom inside the options and it disables the zoom function in chart. It works for all charts, but as soon as I add dataZoom in 3D chart, chart itself doesn't works.

**Comment by ahmadordi** [comment]
> Hi, you can set `viewControl.zoomSensitivity` to `0` to disable the zoom function

Thanks for the answer. Where should I add this ? can you give me an example?

**Comment by ahmadordi** [comment]
I want to these in this chart. 
https://echarts.apache.org/examples/en/editor.html?c=bar3d-punch-card&gl=1

**Comment by janto** [comment]
@ahmadordi  I see there is a globe.viewControl option. maybe there?
https://github.com/apache/echarts/issues/13140#issuecomment-676843007
