### ISSUE TITLE
对数轴在柱状图上无法显示

### ISSUE THREAD

**Issue by gongtiexin** [apache/incubator-echarts#11403]
### Version
4.4.0-rc.1

### Steps to reproduce
修改[官网例子](https://www.echartsjs.com/examples/zh/editor.html?c=line-simple)中的配置项`series type`和`yAxis type`为以下：

```
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'log'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'bar'
    }]
};
```

### What is expected?
柱状图正常显示

### What is actually happening?
柱状图的bar没有绘制

**Comment by zdd2018** [comment]
我也遇见了这个bug，之前是没问题的，把node_modules删了重装了就出现这个问题了，有没有解决办法

**Comment by susiwen8** [comment]
Fixed by #11472, duplicate with #11364
