### ISSUE TITLE
TypeError Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by yuexing0921** [apache/incubator-echarts#11401]
### Version
4.3.0

### Reproduction link
[https://sentry.xiaoheiban.cn/share/issue/eece8831595641629c40acec6bf729f5/](https://sentry.xiaoheiban.cn/share/issue/eece8831595641629c40acec6bf729f5/)

### Steps to reproduce
https://sentry.xiaoheiban.cn/share/issue/eece8831595641629c40acec6bf729f5/
Look at this link specifically

### What is expected?
If the corresponding dom is undefined, it should throw out

### What is actually happening?
Reported directly

---
If you don't have time, I can mention a pr

**Comment by deqingli** [comment]
It would be great if you can mention a pr

**Comment by yuexing0921** [comment]
https://github.com/apache/incubator-echarts/pull/11414

I submitted pr, but I don't know why I didn't pass it. I was submitting pr for the first time. I don't know the rules. Sorry.

**Comment by pissang** [comment]
I think it's not an echarts related issue. Please make sure the dom is not null when initializing echarts
