### ISSUE TITLE
代理服务器挂掉了

### ISSUE THREAD

**Issue by nomeLruoS** [apache/incubator-echarts#11417]
![%I2__4A`VIK~7EQ1F3QPZ)4](https://user-images.githubusercontent.com/49858464/66884819-f6a42a00-f004-11e9-99c0-48d9a0ea1b10.png)

**Comment by Ovilia** [comment]
什么代理服务器？

**Comment by nomeLruoS** [comment]
我也不知道是哪个，我现在的谷歌浏览器访问不了http://echarts.baidu.com/gallery/vendors/echarts/echarts.min.js,换火狐的就能访问；之前我的谷歌浏览器是可以访问的。

------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 中午11:24
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "无阙ζ"<983842706@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/incubator-echarts] 代理服务器挂掉了 (#11417)




什么代理服务器？

**Comment by nomeLruoS** [comment]
------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 中午11:24
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "无阙ζ"<983842706@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/incubator-echarts] 代理服务器挂掉了 (#11417)




什么代理服务器？

**Comment by pissang** [comment]
自己项目中建议使用 CDN

https://www.jsdelivr.com/package/npm/echarts

官网上的 echarts.js 是示例使用的，不能保证链接不会变化

**Comment by nomeLruoS** [comment]
好的




------------------ 原始邮件 ------------------
发件人: "Yi Shen"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 中午11:57
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>; 
抄送: "无阙ζ"<983842706@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] 代理服务器挂掉了 (#11417)




自己项目中建议使用 CDN
 
https://www.jsdelivr.com/package/npm/echarts
 
官网上的 echarts.js 是示例使用的，不能保证链接不会变化
