### ISSUE TITLE
New append series data to append chart, but subtract series data to subtract chart failed in react !

### ISSUE THREAD

**Issue by CeleKing** [apache/incubator-echarts#11415]
### Version
4.3.0

### Reproduction link
[https://jsfiddle.net/afzs8go9/](https://jsfiddle.net/afzs8go9/)

### Steps to reproduce
set series to empyt array and reset data but can't subtract series data in getOption result

### What is expected?
subtract series data can subtract  chart

### What is actually happening?
subtract chart failed

**Comment by Ovilia** [comment]
You should set the seconds parameter of `setOption` to be `true` to remove series.

**Comment by CeleKing** [comment]
thank you
