### ISSUE TITLE
dataset 有bug

### ISSUE THREAD

**Issue by jiangyh1024** [apache/incubator-echarts#11419]
![image](https://user-images.githubusercontent.com/34930870/66904583-e73dd480-f036-11e9-9cd4-2e17f84c9287.png)

![image](https://user-images.githubusercontent.com/34930870/66904603-eefd7900-f036-11e9-903f-85b753b9a9ef.png)

![image](https://user-images.githubusercontent.com/34930870/66904695-1c4a2700-f037-11e9-9f49-223f88bf1342.png)

如果 字符串是个数字 后面的数据不会被显示

**Comment by Ovilia** [comment]
Set [sourceHeader](https://echarts.apache.org/zh/option.html#dataset.sourceHeader) to be `false`.

**Comment by deqingli** [comment]
@Ovilia  Set `sourceHeader` doesn't solve the problem, here the first column is the dimension msg.
