### ISSUE TITLE
关系图，能否给连线添加一种类型，使之不受力引导的影响

### ISSUE THREAD

**Issue by TYzzt** [apache/incubator-echarts#11422]
### What problem does this feature solve?
当在关系图中标明一种额外关系的时候，而且不希望原关系图重绘
尝试使用graphic实现时，关系图会无意义的乱动 https://gallery.echartsjs.com/editor.html?c=xSxErcPoB

### What does the proposed API look like?
line增加可选参数，使之不受力引导的影响

**Comment by Ovilia** [comment]
@TYzzt Do you mind making a pull request about this?

**Comment by pissang** [comment]
Similar to https://github.com/apache/incubator-echarts/issues/11024

**Comment by TYzzt** [comment]
> @TYzzt Do you mind making a pull request about this?

https://github.com/apache/incubator-echarts/pull/11445

**Comment by TYzzt** [comment]
> Similar to #11024

it can solve some problems, but not what I want

**Comment by Ovilia** [comment]
@TYzzt Thanks for your contribution! We will review it soon.
