### ISSUE TITLE
数据量过多时，sunburst旭日图显示有溢出

### ISSUE THREAD

**Issue by 18124772589** [apache/incubator-echarts#11424]
数据量过多时，sunburst旭日图显示有溢出
数据只有3层，但是在第4层的地方出现了,如图
http://testm.jianzaogong.com/h5/test.png
数据：
http://testm.jianzaogong.com/h5/test.json

请问这是bug还是有地方可以选择配置的？

希望可以隐藏显示不了的，不要出现这种溢出

**Comment by Ovilia** [comment]
@18124772589 请提供一下完整的配置项 https://gallery.echartsjs.com/editor.html

**Comment by 18124772589** [comment]
let myChart = echarts.init(this.$refs.sunburstWarp)
            let option = {
                // 是否开启动画的阈值，当单个系列显示的图形数量大于这个阈值时会关闭动画。
                animationThreshold: 5000,
                tooltip: {
                    padding: [6, 7, 7, 8],
                    position: function (point, params, dom, rect, size) {
                        // console.log(point, params, dom, rect, size)
                        return [point[0] + 15, point[1] - 30]
                    },
                    extraCssText: 'box-shadow: 0 2px 8px 0px rgba(0, 0, 0, 0.15);background: rgba(0, 0, 0, 0.75)',
                    formatter: function (params) {
                        // console.log(params)
                        if (!params.data.name) return ''
                        return `${params.data.name}：${params.data.count}人`
                    },
                },
                series: {
                    radius: ['0%', '92%'],
                    center: ['49%', '50%'],
                    type: 'sunburst',
                    sort: null,
                    highlightPolicy: 'none',
                    nodeClick: 'rootToNode',
                    data: this.projectRelationList,
                    levels: [
                        {
                            itemStyle: {
                                color: 'rgb(232, 236, 239)'
                            },
                        }
                    ],
                    emphasis: {
                        itemStyle: {
                            color: 'rgb(252, 184, 19)'
                        }
                    },
                    label: {
                        show: false
                    },
                    itemStyle: {
                        borderWidth: 0.5
                    }
                }
            }
            myChart.setOption(option, {isvisible: true})

**Comment by 18124772589** [comment]
在案例中是可以的，但在真实的项目中，却是存在的，似乎是由于宽度引起的

**Comment by Ovilia** [comment]
@18124772589 还是需要复习一下哈 https://gallery.echartsjs.com/editor.html 然后告诉我一个有问题的宽度

**Comment by 18124772589** [comment]
我在这个案例中复现不了了
