### ISSUE TITLE
.resize() with map not displaying correctly the map

### ISSUE THREAD

**Issue by bcpelletier** [apache/incubator-echarts#11421]
### Version
4.4.0-rc.1

### Steps to reproduce
Create a map with geo and data tow data series: map & scatter.

Call to Chart.resize(), when container size changes, breaks map and correct zoom is restored only when user clicks and moves the map.

### What is expected?
To resize correctly and adapt to a container (4.3.0 was OK!)

### What is actually happening?
The map is showing and incorrect zoom and placement and is not adapted to a container.

**Comment by deqingli** [comment]
Please provide a demo for us to debug.

**Comment by bcpelletier** [comment]
If we have these styles

map {
    width: calc(100% - 650px);
    height: 100%;
    float: left;
  }

map--expanded {
    width: 100% !important;
    height: 100%;
  }

And this div

<div class="map" id="chart">

</div>

and then change the div to 

<div class="map map--expanded" id="chart">

</div>

and call resize() so that the chart resizes the map displays incorrectly and only shows itself correctly if the user clicks on the map and makes some movement.

inf echarts 4.3 this work perfect, in 4.4 it works incorrectly (as I have described).

**Comment by bcpelletier** [comment]
Can someone point out whereabouts (in the code) this be fixed?

Thank you.

**Comment by Ovilia** [comment]
@bcpelletier I cannot reproduce from https://echarts.apache.org/examples/en/editor.html?c=map-polygon
Can you provide an online demo for this? https://jsfiddle.net/ovilia/n6xc4df3/

**Comment by grishnyakov** [comment]
Same problem
https://github.com/apache/incubator-echarts/issues/11670
