### ISSUE TITLE
echarts  数据渲染好了，想两个tooltip共存能拖动标线

### ISSUE THREAD

**Issue by cr-ruirui** [apache/incubator-echarts#11426]
### Version
4.1.0-rc.2

### Steps to reproduce
现在一个tooltip是可以的，2个还不知道怎么实现

### What is expected?
2个tooltop共存

### What is actually happening?
只有一个tooltip

---
现在一个tooltip是可以的，2个还不知道怎么实现

**Comment by Ovilia** [comment]
Duplicate of #11382
请到 #11382 具体说一下，什么样的场景下有这样的需求。
