### ISSUE TITLE
echarts  两个tooltip共存可以不

### ISSUE THREAD

**Issue by cr-ruirui** [apache/incubator-echarts#11427]
### Version
4.1.0-rc.2

### Steps to reproduce
现在一个tooltip是可以的，2个还不知道怎么实现

### What is expected?
2个tooltop共存

### What is actually happening?
只有一个tooltip

---
现在一个tooltip是可以的，2个还不知道怎么实现

**Comment by Ovilia** [comment]
Duplicate of #11382
