### ISSUE TITLE
柱状图 splitArea areaStye color 未按数组颜色顺序进行渲染

### ISSUE THREAD

**Issue by JiangYuCoder** [apache/incubator-echarts#11438]
```js
app.title = '坐标轴刻度与标签对齐';

option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['1', '2', '3', '4', '5', '6', '7','8'],
            axisTick: {
                alignWithLabel: true
            },
            splitArea:{
                show:true,
                areaStyle:{
                    color:['green','red','red','red','red','red','red','black']
                }
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220,100]
        }
    ]
};
```

**Comment by JiangYuCoder** [comment]
`app.title = '坐标轴刻度与标签对齐';

option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['1', '2', '3', '4', '5', '6', '7','8'],
            axisTick: {
                alignWithLabel: true
            },
            splitArea:{
                show:true,
                areaStyle:{
                    color:['green','red','red','red','red','red','red','black']
                }
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220,100]
        }
    ]
};
`

**Comment by pissang** [comment]
Same with https://github.com/apache/incubator-echarts/issues/10948#issuecomment-544813382
