### ISSUE TITLE
yAxis and markLine series

### ISSUE THREAD

**Issue by bymagnum** [apache/incubator-echarts#11440]
Good day! 

There was a very interesting problem with the behavior of yAxis and markLine series

With numeric values, the axis works fine, more than 1 (one), and with numbers less than 1, there is a "cut" of numeric values to hundredths of units of calculation. 

Here's the code:
https://codepen.io/pavlok2008/pen/bGGBzKo

Why is this behavior at the axis and not visible markLine ? 

Then, when I put value more than 1 and above - the markLine appears - the line is very clearly visible.

What is the best way to build data in this case? The fact is that the data must be strictly in one array, you can not divide the data, and the graph can not reproduce fractional parts...

**Comment by POILover** [comment]
I have a similar problem like this, probably echarts cuts the rest number with rounding at third decimal place .Maybe understandable, however, bad user experience.

**Comment by nngocan412** [comment]
@bymagnum, I have the same issue. How do you resolve this?

**Comment by POILover** [comment]
@nngocan412 I opened a similar issue #11517 after this comment and got an effective solution, although they may have added another enhancement. You can use 'precision' option, like 'precision:3', to custom the precision you want.
Complete option:
`option = { xAxis: { type: 'category', boundaryGap: false, data: ['周一','周二','周三','周四','周五','周六','周日'] }, yAxis: { type: 'value', }, series: [ { type:'line', data:[.01, -.02,.02, .05, .03, .002, 0], markLine: { data: [ { yAxis:0.005 } ], precision: 3 } } ] };`

**Comment by nngocan412** [comment]
@POILover thanks a lot. It works perfectly ^_^
