### ISSUE TITLE
多个echarts的tooltip如何实现联动效果？

### ISSUE THREAD

**Issue by fengc7** [apache/incubator-echarts#11449]
效果图入下：
![image](https://user-images.githubusercontent.com/46257934/67255345-2d21ef00-f4b4-11e9-9ced-5ec1342417f3.png)

同时，echarts是否支持查看数据时鼠标滑动，能否获取x轴时间并发起请求？

**Comment by fengc7** [comment]
同时，echarts是否支持查看数据时鼠标滑动时，能否获取x轴时间并发起请求？

**Comment by Ovilia** [comment]
Duplicate of #11382. Please continue discussing it there.

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/api.html#echarts.connect

**Comment by fengc7** [comment]
> https://echarts.apache.org/zh/api.html#echarts.connect

好的谢谢
