### ISSUE TITLE
ie10，11中echart地图图表显示为空白

### ISSUE THREAD

**Issue by NecisDJ** [apache/incubator-echarts#11451]
### Version
4.4.0

### Steps to reproduce
引用的呼和浩特市地图，在ie11，10中，ie报错“对象不支持slice属性”，然而在ie9中却可以正常显示地图

### What is expected?
ie11，10中正常显示echart地图组件

### What is actually happening?
在ie11，10中显示为空白

---
项目使用的是vuecli3脚手架，将地图部分单独作为组件编写了

**Comment by pissang** [comment]
Hi, can you send a reproduce demo to us?

**Comment by NecisDJ** [comment]
因为公司是内网环境的，不太方便传代码出来，这是一个测试的demo地址，里面就是引了一个地图控件，现在测试下来，如果是edge的话是不会报错的，但是旧版本ie就会报如图所示的错误，谷歌火狐测试是没有问题的，实在是摸不着头绪，麻烦了
https://h5.tzjjtech.cn/tnz/testEcharts/index.html#/












------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi Shen"<notifications@github.com&gt;; 
发送时间: 2019年10月23日(星期三) 中午1:25
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "怀念曾经的ID"<407635975@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] ie10，11中echart地图图表显示为空白 (#11451)




Hi, can you send a reproduce demo to us?

**Comment by Ovilia** [comment]
请使用没有压缩过的代码，然后看下 slice 是什么对象上的方法，如果是 ECharts 的再告诉我们一下。如果是 vuecli3 相关的，请到相关项目下报错。

**Comment by hyfdemo** [comment]
![image](https://user-images.githubusercontent.com/23278722/70037570-bc610d00-15f1-11ea-91f1-fb2c96a28af4.png)
![image](https://user-images.githubusercontent.com/23278722/70037628-d69aeb00-15f1-11ea-85d7-7dea8b6c9457.png)
我也遇到这种情况了，IE11里地图数据如图一所示，后面就报错了。

**Comment by hyfdemo** [comment]
@Ovilia

**Comment by Jimco** [comment]
碰到类似的问题，发现是 TypedArray 的 slice 方法在 IE 中不兼容 @Ovilia 
 
![image](https://user-images.githubusercontent.com/1623161/71228264-a4d99200-231c-11ea-920c-3e087ea179e8.png)

<https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice>

**Comment by oneTracer** [comment]
我也碰到一样的问题，ie11不兼容TypedArray.prototype.slice()方法 @Ovilia
