### ISSUE TITLE
希望提供地铁图功能

### ISSUE THREAD

**Issue by 709343767** [apache/incubator-echarts#11454]
对地铁图的需求比较强烈，希望能提供echarts地铁图功能！谢谢！

**Comment by pissang** [comment]
https://gallery.echartsjs.com/editor.html?c=x7cxD71fIE

**Comment by 709343767** [comment]
谢谢
&nbsp;

乘风破浪会有时，直挂云帆济沧海。


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi Shen"<notifications@github.com&gt;; 
发送时间: 2019年10月22日(星期二) 中午12:57
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "乘风破浪"<709343767@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] 希望提供地铁图功能 (#11454)



https://gallery.echartsjs.com/editor.html?c=x7cxD71fIE
