### ISSUE TITLE
When I am trying to give a category data with a big string in x-axis other category data gets hidden. 

### ISSUE THREAD

**Issue by rkvignesh** [apache/incubator-echarts#11465]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.
![ECHARTS](https://user-images.githubusercontent.com/53811429/67360164-d33c2a80-f582-11e9-8e80-9ab32ae98c9a.PNG)

**Comment by pissang** [comment]
Set https://echarts.apache.org/en/option.html#xAxis.interval to 0 to force display all the labels

**Comment by rkvignesh** [comment]
Hi, Thanks for the quick response.
I still cant able to see.
Pls check attachment.
![Echart-Interval](https://user-images.githubusercontent.com/53811429/67371817-97ad5a80-f59a-11e9-9044-8a591d0fec18.PNG)

**Comment by pissang** [comment]
Sorry I attached the wrong link. It should be axisTick.interval https://echarts.apache.org/en/option.html#xAxis.axisTick.interval

**Comment by rkvignesh** [comment]
Hi, Thanks for the kind response. But still i cant find label visible. Pls guide me to overcome this.
![Echarts-Interval](https://user-images.githubusercontent.com/53811429/67377470-55d4e200-f5a3-11e9-8d75-b49480cf9339.PNG)

**Comment by pissang** [comment]
Ahhhhhh, so sorry about that. 

https://echarts.apache.org/en/option.html#xAxis.axisLabel.interval will definitely work!

**Comment by rkvignesh** [comment]
Thanks Yi Shen.. I got what i requested for.. But the label gets overlap with one another..
![Echart-label](https://user-images.githubusercontent.com/53811429/67461237-82980080-f65a-11e9-97b1-9c42088c9490.PNG)
I have check out and in one of the chart i can see they have did like this.
![Other- Label](https://user-images.githubusercontent.com/53811429/67461327-afe4ae80-f65a-11e9-8e88-98ad26cdfe44.PNG).
The label which are long are ended with ...(three dots). Is there any possible way to show all the label efficeintly without overlapping.
Awaiting your response. Pls Guide.

**Comment by pissang** [comment]
There are a couple of ways to optimize this overlapping.

1. Use [xAxis.axisLabel.rotate](https://echarts.apache.org/en/option.html#xAxis.axisLabel.rotate) to rotate the labels.

2. Truncate the label string in the [xAxis.axisLabel.formatter](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter)

**Comment by rkvignesh** [comment]
Thank you so much bro.. Issue fixed.
