### ISSUE TITLE
部分经纬度无法被正确解析

### ISSUE THREAD

**Issue by Jiujiale** [apache/incubator-echarts#11466]
### Version
4.4.0

### Reproduction link
[https://codepen.io/jiujiale/pen/RwwpGvE](https://codepen.io/jiujiale/pen/RwwpGvE)

### Steps to reproduce
直接打开链接就会出现 worldGeo.getRegionByCoord 解析不出 region，应该[-74, 40.743]经度在前在New York 地区

### What is expected?
getRegionByCoord 可以正确解析出 region

### What is actually happening?
部分经纬度无法被解析出正确的region 
example : [-74, 40.743] 经度在前

**Comment by pissang** [comment]
I think it's because the precision of GeoJSON is not enough. 

![image](https://user-images.githubusercontent.com/841551/67551816-5ce32800-f73c-11e9-891f-89e44d77f00f.png)

I drew the point `[-74, 40.743]` on the geo component. It's outside the region.

**Comment by Jiujiale** [comment]
OK. I see.
Will this situation be improved in later versions?

**Comment by pissang** [comment]
I'm afraid it can't be easily fixed because world GeoJSON don't have this high precision. 

You can describe your purpose and let's see if we can work around .it

**Comment by pissang** [comment]
You can try to search the neighbor points by adding a small offset. I think it will raise the success possibility.

**Comment by Jiujiale** [comment]
uh, that's a good plan B.
Thanks for your help~
