### ISSUE TITLE
dark主题下的axisPointer label背景颜色过淡导致无法看清

### ISSUE THREAD

**Issue by yimelia** [apache/incubator-echarts#11476]
### Version
4.3.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis&theme=dark](https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis&theme=dark)

### Steps to reproduce
设置了
```js
axisPointer: {
            type: 'cross'
        }
```
之后，在生成图标时选择dark theme，会发现十字型的坐标轴指示器背景颜色与axisLine.lineStyle:中设定的颜色一致，在dark主题下默认是灰白色，几乎看不清文字信息。
请参考链接中的X轴的效果。

### What is expected?
最好是能够独立设置坐标轴指示器的文字颜色

### What is actually happening?
在dark主题下默认是灰白色，几乎看不清文字信息。
![image](https://user-images.githubusercontent.com/6896468/67459939-4cfc1300-f66c-11e9-9e07-33bd79e645ca.png)

**Comment by pissang** [comment]
Thanks for the report. Can you create a pull request to fix this?
