### ISSUE TITLE
折线图分段显示颜色出错

### ISSUE THREAD

**Issue by xdlee** [apache/incubator-echarts#11499]
在性能较好的系统下，当图中的数据过多时（>500），折线图显示有问题，颜色显示错误。

**Comment by Ovilia** [comment]
Please provide a demo for this.
https://gallery.echartsjs.com/editor.html

**Comment by xdlee** [comment]
抱歉，我现在无法登录gmail，pc没有办法获取到验证码进行登录

**Comment by xdlee1** [comment]
test

**Comment by xdlee1** [comment]
@Ovilia 你好，我是xdlee，是在数据量比较多的情况下，比如3000条以上，折线间点的连线，颜色和设定的不一致。

**Comment by Ovilia** [comment]
@xdlee 请提供一个复现的例子
