### ISSUE TITLE
Content in doc on 'series[i]-treemap.silent' seems to be part of 'series[i]-treemap.data'

### ISSUE THREAD

**Issue by zhly05** [apache/incubator-echarts#11494]
### Version
4.4.0

### Steps to reproduce
Content in doc on 'series[i]-treemap.silent' seems to be part of 'series[i]-treemap.data'

### What is expected?
Content in doc on 'series[i]-treemap.silent' seems to be part of 'series[i]-treemap.data'

### What is actually happening?
Content in doc on 'series[i]-treemap.silent' seems to be part of 'series[i]-treemap.data'

---
Content in doc on 'series[i]-treemap.silent' seems to be part of 'series[i]-treemap.data'

**Comment by pissang** [comment]
Fixed in https://github.com/apache/incubator-echarts-doc/commit/da43f18e9fc2cddf9ff128ce5049356c9a21b802
