### ISSUE TITLE
隐藏所有legend

### ISSUE THREAD

**Issue by c625473164** [apache/incubator-echarts#11501]
如何手动触发隐藏所有legend
如果for循环依次触发legendUnSelect，线比较多时会卡顿，消耗比较长的时间
```
dispatchAction({
              type: 'legendUnSelect',
              name: data[k],
            }
```

**Comment by cuijian-dexter** [comment]
@c625473164 Do you want to hide or unselect?

**Comment by pissang** [comment]
You can use [selected](https://echarts.apache.org/en/option.html#legend.selected) to unselect all the legends.
