### ISSUE TITLE
图表如何整体缩放？

### ISSUE THREAD

**Issue by ymli1981** [apache/incubator-echarts#11502]
我弄了个笛卡尔坐标系的图表，现在想实现整个图表的缩放，平移，貌似实现不了？（用datazoom不行，因为我希望实现的是，缩小时整个图表还有它里面的图形都缩放）

**Comment by pissang** [comment]
可以描述下需要实现这个功能的场景吗？

**Comment by ymli1981** [comment]
> 可以描述下需要实现这个功能的具体场景吗？

希望能实现的是：画布无限大，可以在上面呈现多个图表（每个图表都比较大，可以编辑）

**Comment by ymli1981** [comment]
具体场景就是用echart做了个类似画脑图的程序，可以在一张画布上画多个脑图（不完全是脑图，就是类似的东西）

**Comment by ymli1981** [comment]
echarts目前给我的感觉，主要是用于数据可视化，就是数据的图形呈现
希望后续能多支持对图形的直接编辑，比如图形的增/删/拖动，及图片/文字块的增/删/拖动等

**Comment by ymli1981** [comment]
> 可以描述下需要实现这个功能的具体场景吗？
你可以在微信小程序中搜索 简易yun盘，我用echarts做的画各种图的小程序

**Comment by Ovilia** [comment]
这个应用场景可能能 ECharts 比较偏离，目前没有支持的打算。
