### ISSUE TITLE
【Pie饼图】使用dataset配置时，维度列的值如果存在Number类型，图表渲染残缺

### ISSUE THREAD

**Issue by fxxjdedd** [apache/incubator-echarts#11509]
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/v1k7jz85/2/](https://jsfiddle.net/v1k7jz85/2/)

### Steps to reproduce
```js

const source = [
  // 如果存在这种type: '123'，维度值为数字类型，图标渲染就会出问题
  { type: '123', value: 110,  },
  { type: 'Hive', value: 117,  },
  { type: 'MySQL', value: 122,  },
]

```

### What is expected?
图表的渲染，比如legend、tooltip应该正常

### What is actually happening?
legend缺失，tooltip缺失

**Comment by Ovilia** [comment]
This is a bug. Duplicate to #11419. Please follow that issue.
