### ISSUE TITLE
图表怎么根据时间来给白天和黑夜两个时间段加不同的背景色(How does the chart add different background colors to the day and night time periods according to time?)

### ISSUE THREAD

**Issue by J-DuYa** [apache/incubator-echarts#11503]
请问 图表怎么根据时间来给白天和黑夜两个时间段加不同的背景色？如果有这个api配置项，请问这个配置项是什么？谢谢
(How does the chart add different background colors to the day and night time periods based on time? If there is this api configuration item, what is this configuration item? Thank you)

**Comment by pissang** [comment]
You can just set the [backgroundColor](https://echarts.apache.org/en/option.html#backgroundColor). Or init the chart with different [theme](https://echarts.apache.org/en/api.html#echarts.init)

**Comment by J-DuYa** [comment]
> You can just set the [backgroundColor](https://echarts.apache.org/en/option.html#backgroundColor). Or init the chart with different [theme](https://echarts.apache.org/en/api.html#echarts.init)

**Comment by J-DuYa** [comment]
> You can just set the [backgroundColor](https://echarts.apache.org/en/option.html#backgroundColor). Or init the chart with different [theme](https://echarts.apache.org/en/api.html#echarts.init)
现在，我想要的效果是x轴是时间轴 首先 根据白天（比如说8点到18点）和黑夜（18点到次日凌晨8点）然后根据这种规则划分 其次是根据x轴的坐标来给图表上色不是线条的颜色而是图表的背景的颜色（就像是那种柱状的颜色）

**Comment by J-DuYa** [comment]
> You can just set the [backgroundColor](https://echarts.apache.org/en/option.html#backgroundColor). Or init the chart with different [theme](https://echarts.apache.org/en/api.html#echarts.init)

大体知道往那个方向去探究了 谢谢
