### ISSUE TITLE
3d地球 type为scatter3D这个是的时候 只能使用label去显示提示，但是如果label超过1000条提示之后就报错

### ISSUE THREAD

**Issue by SummerHair** [apache/incubator-echarts#11510]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by yufeng04** [comment]
Please use the  [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) to create issue and provide a reproducible demo.

**Comment by Ovilia** [comment]
Please provide more information, or this issue will be closed.
