### ISSUE TITLE
线图中，将tooltip绑定到axis上，无法获取此点击事件

### ISSUE THREAD

**Issue by dagundejuzi** [apache/incubator-echarts#11518]
### Version
4.3.0

### Steps to reproduce
配置是：
tooltip: {
                    show:true,
                    confine: true,
                    trigger: 'axis',
                    triggerOn: 'click',
                    axisPointer: {
                        type: 'none'
                    },
                   ……
             },

然后监听了点击事件：
myChart.on('click',function (param) {
         ……
}

### What is expected?
能监听到点击事件，并获取到对应轴所在位置的数据点的数据。

### What is actually happening?
监听不到此点击事件。但是如果改成监听数据点trigger: 'item'，就能监听到点击事件了。

**Comment by Ovilia** [comment]
Please provide a complete demo https://gallery.echartsjs.com/editor.html

**Comment by dagundejuzi** [comment]
你好，这是一个简单的例子：
https://gallery.echartsjs.com/editor.html?c=xWwhbfffQ&v=1

**Comment by Ovilia** [comment]
点击折线上的原点的时候是有事件的，预期的效果是什么？

**Comment by dagundejuzi** [comment]
我是将事件绑定到了axis上，所以希望点击轴线能被myChart.on('click',function (param) {  } 这个方法监听到。
