### ISSUE TITLE
Time axis chart is not plotting all series while using dataSet

### ISSUE THREAD

**Issue by dileepyelleti** [apache/incubator-echarts#11526]
### Version
4.4.0

### Reproduction link
[https://codepen.io/dileep_yelleti/pen/KKKXoZN](https://codepen.io/dileep_yelleti/pen/KKKXoZN)

### Steps to reproduce
If x-axis type is time and we specify data set as array of objects. Then chart is not not showing all series. Refer to codepen sample.

### What is expected?
Should work same way as category axis chart

### What is actually happening?
Working fine if type is category but not working as expected if xaxis type is time

**Comment by dileepyelleti** [comment]
@Ovilia 
Can you please help me in fixing this issue. It is sort of urgent for us.
We need to show multiple series in time axis chart from dataSet. Please refer https://codepen.io/dileep_yelleti/pen/KKKXoZN

**Comment by Ovilia** [comment]
This is not a bug. The correct way to use is:

```js
var option = {
    legend: {},
    tooltip: {},
    dataset: {
        source: [
            {date: '2017-10-31', 'first': 43.3, 'second': 85.8},
            {date: '2017-11-30', 'first': 83.1, 'second': 73.4},
            {date: '2017-12-31', 'first': 86.4, 'second': 65.2},
            {date: '2018-01-31', 'first': 72.4, 'second': 53.9}
        ]
    },
    xAxis: {type: 'time'}, // xAxis: {type: 'category'} works fine
    yAxis: {},
    series: [
        {
            type: 'line',
            dimensions: ['date', 'first']
        },
        {
            type: 'line',
            dimensions: ['date', 'second']
        }
    ],
    dataZoom: [{
        type: 'inside'
    }, {
    }],
};
```

**Comment by dileepyelleti** [comment]
@Ovilia 
Thank you for your inputs. I just can't figure why there is difference in usage between type: 'category' and type: 'time'. Also in above sample tooltip is also showing differently for two series.

**Comment by Ovilia** [comment]
I don't think this is a bug with time axis, but probably a coincidence where category axis works.
The difference between time and category axis is that, the time axis could be more complicated. For example, the axis label may should hours when the data is within a day, while being dates when the data is not within a day.
