### ISSUE TITLE
浏览器缩放时地图位置跑偏，需要刷新浏览器才会和数据坐标对应上

### ISSUE THREAD

**Issue by Evin-An** [apache/incubator-echarts#11522]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

先附上在线链接：https://gallery.echartsjs.com/editor.html?c=xDO1NEGdk&v=1
第一次init完成后数据在地图上的点没问题，缩放浏览器后，地图位置跑偏了，这时候刷新浏览器后会变正常，并且刷新的时候数据和地图缩放时机不一致。这个问题有人遇到过吗

**Comment by Evin-An** [comment]
`
myChart = echarts.init(this.divRef.current, null, {
      renderer: 'svg'
});
echarts.registerMap('world', worldChinaMap);
myChart.setOption(option, true);
window.addEventListener('resize', function() {
    myChart.resize('100%', '100%');
});
`
监听浏览器resize也没用

**Comment by yufeng04** [comment]
I have reproduced in the [example](https://echarts.apache.org/examples/zh/editor.html?c=map-polygon) of official website.
![image](https://user-images.githubusercontent.com/22974511/67997054-3c135900-fc8d-11e9-9859-a312a59d9e58.png)

**Comment by chaegumi** [comment]
需要类似这样调用，先clear后，再设置就有效果了
myChart.clear()
myChart.setOption(opt)

**Comment by Evin-An** [comment]
好的，了解了，谢谢
