### ISSUE TITLE
堆叠条形图tooltip显示问题

### ISSUE THREAD

**Issue by wangshengkun** [apache/incubator-echarts#11533]
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/Gatsby/2kp1d4qh/7/](https://jsfiddle.net/Gatsby/2kp1d4qh/7/)

### Steps to reproduce
1.鼠标悬浮周五/周六任意一行
2.鼠标下移，滑动至周一/周二/周三任意一行后停留
3.该行的tooltip显示的是周四的tooltip内容

### What is expected?
由于周一/周二/周三无数据，故鼠标悬浮在周一/周二/周三中任意一行时，tooltip亦因同无数据的周日/周六一致，都不显示数据。

### What is actually happening?
下方无数据的tooltip显示了上方距离最近的有数据的tooltip内容。

**Comment by Ovilia** [comment]
It seems that the highlighted data is not correctly calculated.

**Comment by pissang** [comment]
Seems similar to https://github.com/apache/incubator-echarts/issues/11533

**Comment by 100pah** [comment]
Fixed in c8c5a15eea7233f99c489c9273d4dff8ce525c56
