### ISSUE TITLE
如何使一个轴既是类目轴，又是数据轴

### ISSUE THREAD

**Issue by moonlitusun** [apache/incubator-echarts#11537]
### What problem does this feature solve?
现在有一个需求是，需要画两条线，一个显示是显示价格列表下成交量有多少，还有一个显示是多少时间内价格是多少，现在想把价格这个轴共用，想问下是否有可能实现，我试了自定义图表，那个自定义图表的文档我感觉不怎么好懂，3q

### What does the proposed API look like?
HELP

**Comment by Ovilia** [comment]
Can you provide a design picture?

**Comment by moonlitusun** [comment]
例如：第一组数据为 y是类目轴 x是数据轴
y: {
name: 价格
 type: 'category'
data: [ 73， 74，75]
}
x: {
 name: 成交量
type: value,
data: [1000, 200, 3000]
}
这样可以汇出一条线，代表在某一价格的成交量为多少

现在的问题是第二条线
x为类目轴，y为数据轴
x: {
 type: category
name: 时间
data: [10:00, 11: 00]
}

y: {
data: [73, 74]
}

这样如果单独画两条线没问题，但是想要吧这两个价格线合成一根，就是当第一条线的类目轴，第二条线的数据轴，是否有可能

**Comment by moonlitusun** [comment]
现在我的做法是第一条线照常画， 第二条线用自定义series，获取到当前价格在价格类目轴上的物理位置，echartsInstance.convertToPixel({ yAxisIndex: 0 }, 'price')，但是发现返回的值并不是正确的位置，而且containPixel也显示false，第二条线的价格是肯定包含在第一条线的价格之中的，所以不太明白

**Comment by Ovilia** [comment]
我不太能想象「把这两个价格线合成一根，就是当第一条线的类目轴，第二条线的数据轴」的效果是什么，所以能不能画个示意图？
