### ISSUE TITLE
Label won't disappear when mouse out of the element with SVG rendering

### ISSUE THREAD

**Issue by pissang** [apache/incubator-echarts#11543]
Case to reproduce:

https://www.echartsjs.com/examples/zh/editor.html?c=graph-webkit-dep&renderer=svg

Original issue: https://github.com/apache/incubator-echarts/issues/10996

**Comment by Ovilia** [comment]
I checked current master and test with `dist` or build then test with the `dist`, neither of which can reproduce this.
But it's strange that https://www.echartsjs.com/examples/zh/editor.html?c=graph-webkit-dep&renderer=svg alse is echarts-4.5.0.
