### ISSUE TITLE
geo3D  regions regionHeight is not working

### ISSUE THREAD

**Issue by headgreen** [apache/incubator-echarts#11544]
geo3D  regions.regionHeight is not working, but regions.itemStyle can setting

**Comment by yufeng04** [comment]
Please provide a reproducible demo， and I found the `regionHeight` work in this [example](https://echarts.apache.org/examples/zh/editor.html?c=bar3d-global-population&gl=1). Maybe it's the error of doc.

**Comment by headgreen** [comment]
geo3D: {
regions: [{
            name: '成都市',
            regionHeight: 5,
            itemStyle: {
              borderWidth: 0,
              borderColor: '#469BF1',
              opacity: 0.8
            }
          }, {
            name: '广安市',
            regionHeight: 10,
            itemStyle: {
              borderWidth: 1,
              borderColor: '#fff'
            }
          }]
}
this is my regions setting , regionHeight is not working

**Comment by pissang** [comment]
Hi @headgreen 

In the `regions` property it should be `height` insteadof `regionHeight`

**Comment by headgreen** [comment]
@pissang thanks , it's the error of doc.
