### ISSUE TITLE
Plugin suppport for e-Charts

### ISSUE THREAD

**Issue by samavedulark** [apache/incubator-echarts#11560]
### Version
4.4.0

### Steps to reproduce
Hi,

It would be nice to support plugins, so that any custom features can be added easily. Please let me know if i miss anything.

Thanks

### What is expected?
Plugin Support

### What is actually happening?
Plugin are not support.

**Comment by Ovilia** [comment]
Hi @samavedulark .
What kind of plugin do you mean? What type of charts do you wish to make?

**Comment by samavedulark** [comment]
Hi,

Plugin support if for adding labels inside the plots or bar charts by user actions.

Thanks

**Comment by Ovilia** [comment]
We are improving the ability of labeling, but I'm a afraid it won't be in the form of plugin.
Currently, it's hard to provide such plugin functions.

**Comment by samavedulark** [comment]
Thanks
