### ISSUE TITLE
超过2个图表，使用resize()会不正常

### ISSUE THREAD

**Issue by yamateH-ch** [apache/incubator-echarts#11577]
### Version
4.1.0-release

### Steps to reproduce
使用flex布局，
在多个图表里面组件监听
```js
 window.addEventListener('resize', () => {
        this.$nextTick(() => {
          xx.resize()
        })
      }, false)
```
当数量超过2个时，窗口从大缩小不正常，从小放大就可以，
试过，在一个页面监听
```js
 window.addEventListener('resize', () => {
        this.$nextTick(() => {
          xx.resize()
          xx2.resize()
          xx3.resize()
        })
      }, false)
```
还是不正常

### What is expected?
多个图表rezise()可以正常

**Comment by yamateH-ch** [comment]
补上在线地址，可以用这个重现，缩小可以，缩小再放大缩小就不正常了
http://jsrun.pro/caWKp/edit

**Comment by alonglive** [comment]
> 补上在线地址，可以用这个重现，缩小可以，缩小再放大缩小就不正常了
> http://jsrun.pro/caWKp/edit

请问是怎么解决的 我同样遇到了这个问题
