### ISSUE TITLE
Echarts is not defined in jsp file

### ISSUE THREAD

**Issue by ankitagrahari** [apache/incubator-echarts#11573]
### Version
4.4.0

### Steps to reproduce
I am trying to use echarts for some pie charts and bar charts. After adding the 
<script type="text/javascript" src="/dma/js/echarts.min.js"></script>

<div id="bar" style="width: 600px;height:400px;"></div>

The first line 
var myChart = echarts.init(document.getElementById('bar'));

is failing with error "Uncaught ReferenceError: echarts is not defined"

I have checked the location of the js file and it exists, even on the developer tools the path to the js file is coming correctly.

Can someone please help on what I am doing wrong here ?

### What is expected?
It should be able to detect the echarts.init() method if the js file is present.

### What is actually happening?
It is throwing error "echarts is not defined"

---
I am using a Struts project with jsp pages for view. I am running this application on rhel 7 machine through a tomcat (version: 7.0.69 ) server.

**Comment by Ovilia** [comment]
Try using a relative path?
This doesn't seem to relate ECharts.

**Comment by ankitagrahari** [comment]
Hi Olivia, 

It is using the relative path. Actually I have tried with the relative path, complete path and even using the cdn url. But it is not working.

If the echarts.min.js file is existing the echarts should not throw error "echarts is not defined". Refer to the images below, where the it can get the echarts.min.js file but still throwing the error.

![image](https://user-images.githubusercontent.com/4497558/68417648-ccd1c380-01bc-11ea-99ed-c2669210be2d.png)

![image](https://user-images.githubusercontent.com/4497558/68417864-3356e180-01bd-11ea-9164-a40e6c73f5c1.png)

**Comment by Ovilia** [comment]
Perhaps the `var myChart = echarts.init(document.getElementById('bar'));` is called before ECharts `<script>` tag? This is a pure JS problem and ECharts won't give this error if `echarts` variable is there. Please have a carefully check.

**Comment by ankitagrahari** [comment]
I double checked and the call is proper, first the inclusion of echarts library via script tag and then the call to echarts is happening. Even I am not sure, why this is happening and that's why raised this ticket.

Kindly let me know if there is anything else to look.

**Comment by ankitagrahari** [comment]
Thanks for helping. Got the issue, closing it.
