### ISSUE TITLE
全选反选功能

### ISSUE THREAD

**Issue by T-OneSoul** [apache/incubator-echarts#11582]
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/c5y6dgr2/6/](https://jsfiddle.net/c5y6dgr2/6/)

### Steps to reproduce
https://segmentfault.com/q/1010000020932185

### What is expected?
每次切换都有全选反选

### What is actually happening?
切换后全选丢失了

**Comment by SnailSword** [comment]
你提供的复现链接中没有切换tab的逻辑呢

**Comment by T-OneSoul** [comment]
调用resize方法后全选反选按钮也会消失
call resize function cause the selector button will lost

**Comment by T-OneSoul** [comment]
@SnailSword 没，哪里好像写不了，你可以复制一下代码，然后加一个可以切换的TAB，基本代码就那些

**Comment by Ovilia** [comment]
如果是 Tab 切换的问题，应该是父容器被移除了，建议 tab 移出的时候 dispose 掉，进入的时候重新 init。
如果是 resize 后全选按钮的问题，请提供一个可复现的例子。

**Comment by T-OneSoul** [comment]
dispose掉了，还是这样，好吧，在jsfiddle无法复现，我自己手写一个全选反选，问题关了

**Comment by T-OneSoul** [comment]
dispose掉了，还是这样，好吧，在jsfiddle无法复现，我自己手写一个全选反选，问题关了

**Comment by T-OneSoul** [comment]
dispose掉了，还是这样，好吧，在jsfiddle无法复现，我自己手写一个全选反选，问题关了
