### ISSUE TITLE
移动应用手势缩放无效

### ISSUE THREAD

**Issue by luckmonkey** [apache/incubator-echarts#11580]
### Version
4.2.1

### Steps to reproduce
移动应用手势缩放无效

### What is expected?
4.1.0有效

### What is actually happening?
无效

---
4.1.0有效

**Comment by luckmonkey** [comment]
processGesture: function (event, stage)
    TO
    processGesture: function (proxy, event, stage)

**Comment by Ovilia** [comment]
This problem may have been fixed in the next version. Please checkout the master branch and run `build/build.js` to get the latest `dist/echarts.js`. Or please wait for the next release.
