### ISSUE TITLE
Is it possible to put the y-axis both left and right?

### ISSUE THREAD

**Issue by mglimmerveen** [apache/incubator-echarts#11589]
### What problem does this feature solve?
We would like to have the y-axis of a chart (with only 1 y-axis) on both left and right. This way, the user would have more context about the value of the chart on the far end of the chart. 

I have tried some workarounds, looked in the documentation and asked a [question on StackOverflow](https://stackoverflow.com/questions/58662577/is-it-possible-to-duplicate-a-y-axis-in-echarts-and-print-it-left-and-right) , but I haven't been able to achieve this, other then completely duplicating the entire series, which is undesirable of course.

Hence, I think this is a feature request.

### What does the proposed API look like?
The y-axis configuration already has a [position property](https://echarts.apache.org/en/option.html#yAxis.position), which has the options 'left' and 'right'. Please add option 'both'.

**Comment by Ovilia** [comment]
So you want two axes on two sides, and they are the same?
You can set `yAxis` to be an array of y axes and max value should be set to make sure they are the same. Then, hide `splitLine` of the right axis.

**Comment by mglimmerveen** [comment]
> So you want two axes on two sides, and they are the same?
> You can set `yAxis` to be an array of y axes and max value should be set to make sure they are the same. Then, hide `splitLine` of the right axis.

@Ovilia thanks for your quick reply!

I had previously tried something like this, but ran into problems with deviating values, as you mentioned. I thought that was because the min & max was automatically deducted from the series, but on second thought, I think I overlooked something.  I will try again and get back shortly...

**Comment by mglimmerveen** [comment]
I can't seem to get it working. We are using "dataMin" and "dataMax" to set the scale of the y-axis, but when I duplicate the y-axis, this isn't working. 

Aside from that, I would say that it would be more robust to just declare that you want the y-axis printed twice, rather than duplicating it manually.  Wouldn't you agree?

**Comment by Ovilia** [comment]
You need an extra series binding to the second y axis and keep the two series and axes the same.

**Comment by mglimmerveen** [comment]
As I pointed out in the first post, I did try duplicating the entire series. So, yeah, that would certainly work. And I guess it might be doable in case of a small chart, but does have a negative performance impact on rendering larger data sets. 

I would personally argue that this is a suboptimal solution/workaround.

**Comment by Ovilia** [comment]
Set the second series to be `show: false`

**Comment by mglimmerveen** [comment]
I'm sorry, I kind of forgot about this. 

Nevertheless, I still do not understand why you would want me to duplicate an entire series, and then set it to show: false. It makes the code ugly, less descriptive and (most probably) also perform much less.
