### ISSUE TITLE
图表区域不能单独滚动。

### ISSUE THREAD

**Issue by dagundejuzi** [apache/incubator-echarts#11595]
### Version
4.3.0

### Steps to reproduce
当数据比较多的时候，图表原来的宽度不够展示所有数据，需要滚动图表。但是图表并不会扩大范围从而可滚动，只会在一屏之下更密集的排布。

### What is expected?
希望数据比较多时，图表可以滚动，可以让每个数据有间距的展示。

### What is actually happening?
数据只在原来的面积内，更密集的排布。

---
如下图，我只是在官方基本折线示例图上加了些数据。
https://www.echartsjs.com/examples/zh/editor.html?c=line-simple

![Snip20191108_2](https://user-images.githubusercontent.com/16382880/68453223-e829e680-022f-11ea-9489-e8f37fd0ff6d.png)
![Snip20191108_1](https://user-images.githubusercontent.com/16382880/68453229-ed873100-022f-11ea-9df4-93ffda841e59.png)

在datazoom的实例中看到图表可以滚动，但是需求不用缩放，数据平铺展示的，只要能滑动就行。
var dom = myChart.getDom();
dom.style.width='1000px'; 
myChart.resize({silent:true});
这样写在手机上是可以滚动了，但是连带Y轴也滚走了，这样是滚动了图表的外层容器，用户体验也不好。
所以请问有什么方法可以让图表内容滚动而Y轴固定？

**Comment by dagundejuzi** [comment]
现在想就滚动外层容器可以 ，y轴另外覆盖一个，充当固定不动的y轴。所以能告知一下y轴label位置的计算方式吗？

**Comment by Ovilia** [comment]
You can use dataZoom and set a min/max value to y axis.

**Comment by dagundejuzi** [comment]
> You can use dataZoom and set a min/max value to y axis.
我的XY轴都是分类轴，固定的值，缩放的是x轴。采用这种方式
![image](https://user-images.githubusercontent.com/16382880/70964202-ef150600-20c5-11ea-82b5-795e678a577f.png)
实现了图表内部滚动，且不会缩放的效果。但是有其他问题：1、滑动动画不流畅，手机上会有滑动后的减速滑动效果，echart没有，对比就显得echart滑起来一顿一顿的。数据点在滑完后还有个从小到大的慢速放大动画；滑动是还能看到残影。 2、双指缩放手势，虽然不会导致缩放，但依然响应其中一个手指的滑动，会往前滑或后滑。

另外，当xAxis的 boundaryGap: true,时，折线在边缘是截断的
![Snip20191217_1](https://user-images.githubusercontent.com/16382880/70964378-9d20b000-20c6-11ea-8dfd-1fcd4df9ef2c.png)
![Snip20191217_2](https://user-images.githubusercontent.com/16382880/70964384-a14ccd80-20c6-11ea-9766-cdd232232a56.png)

[这是一个示例](https://gallery.echartsjs.com/editor.html?c=xDHD5FFyZ&v=1)

**Comment by Ovilia** [comment]
你想要什么效果？这个示例看起来没有问题
