### ISSUE TITLE
桑基图links中source和target值相同出现错误

### ISSUE THREAD

**Issue by pwj126** [apache/incubator-echarts#11594]
### Version
4.1.0-release

### Steps to reproduce
比如source=‘上海’  target = '上海'  时

### What is expected?
可以出现闭环

### What is actually happening?
出现问题： Sankey is a DAG, the original data has cycle!

**Comment by deqingli** [comment]
Hi, this is the strategy we adopted. I just want to know why you want the `source` and `target` is the same.

**Comment by 462937186** [comment]
如果 
想让桑基图links中source和target值相同 你可以从数据源下手 循环一下然后加上索引

https://gallery.echartsjs.com/editor.html?c=xvJYS-Nge&comment=0

**Comment by charleiWang** [comment]
links: [{
				"source": "Venezuela",
				"value": 3,
				"target": "Bahamas"
			}, {
				"source": "Venezuela",
				"value": 1,
				"target": "Japan"
			}, {
				"source": "Iraq",
				"value": 1,
				"target": "Spain"
			}, {
				"source": "Iraq",
				"value": 327,
				"target": "India"
			}, {
				"source": "India",
				"value": 32,
				"target": "Iraq"
			}]

这种，source!=target,  但是Iraq 和 India 是有循环的，这个也也会报错。
