### ISSUE TITLE
ios13.2系统safari浏览器上查看统计图，手指点击图元，出现的tooltip有很大概率被图元遮挡

### ISSUE THREAD

**Issue by dengsilong** [apache/incubator-echarts#11599]
### Version
4.2.0-rc.2

### Steps to reproduce
iphone手机safari浏览器浏览网页，查看基本echarts饼状图，手指点击饼块，显示tooltip，tooltip被图形遮盖

### What is expected?
tooltip正常显示不被遮盖
![TIM截图20191108144335](https://user-images.githubusercontent.com/57519055/68457204-aeaaa880-023a-11ea-8a20-de5ee7fcc5ff.jpg)

### What is actually happening?
tooltip被遮盖

---
ios12.4系统上显示正常，ios13.2系统上被遮挡

**Comment by dengsilong** [comment]
采用echarts-for-react开发的统计图展示

**Comment by lp007lp** [comment]
@dengsilong Hello! How do you solve this issue?

**Comment by dengsilong** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tooltip&nbsp;=&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;position:&nbsp;(point,&nbsp;params,&nbsp;dom,&nbsp;rect,&nbsp;size)&nbsp;=&gt;&nbsp;{&nbsp;dom.style.transform&nbsp;=&nbsp;"translateZ(0)";&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lp007lp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 晚上6:58
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"邓四龙"<dengsilong@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] ios13.2系统safari浏览器上查看统计图，手指点击图元，出现的tooltip有很大概率被图元遮挡 (#11599)




@dengsilong Hello! How do you solve this issue?

**Comment by lp007lp** [comment]
@dengsilong ok, thank you very much!
