### ISSUE TITLE
显示折线上任意一点数据(而不是整个坐标系)

### ISSUE THREAD

**Issue by wjdnlg** [apache/incubator-echarts#11592]
### What problem does this feature solve?
当有两条折线他们数据很相近,但有差异 比如速度时间图 两条折线对比但是只能对比传入点的数据 两个传入点之间的数据获取不到,希望可以传入x轴数据能够根据y=......这样一个函数来计算出y轴的值 实现实时对比功能 

### What does the proposed API look like?
Echarts已经实现了获取整个坐标系任意一点的像素转化为坐标convertFromPixel 方法,希望可以只获得折线上的坐标,(当datazoom缩放时,横坐标改变了但是他们的纵坐标并没有变化,也就是说不是显示对应x坐标点的y轴的值 如下图
![3aa2869835559ec8c60426d584e688c](https://user-images.githubusercontent.com/53259799/68444075-bead9280-0210-11ea-8d0b-c1bad6f59526.png)
![eb680905628d060a02c8e2f984bb8b1](https://user-images.githubusercontent.com/53259799/68444081-c3724680-0210-11ea-8074-cd31c753fc36.png)

)

**Comment by wjdnlg** [comment]
第一张图(5.72,70),第二张(5.39,70)他们的横坐标变化了但是Y轴并没有 这不合理,左边显示的是鼠标所在位置的y坐标,这是已经实现的  这是整个坐标系上而非折线图上

**Comment by Ovilia** [comment]
不太理解描述，是希望传入一个 `y = x * 2` 这样的函数，然后生成一个系列吗？
你可以自己根据这样的方法计算出一个 y 值的数组，然后传入。

**Comment by wjdnlg** [comment]
> 该问题标记为`waiting-for: author`。
> @wjdnlg请提供更多信息以获得社区帮助，或者如果您认为问题已解决，请关闭此问题。

![1573182134(1)](https://user-images.githubusercontent.com/53259799/68446340-6037e280-0217-11ea-9b80-f88e98d53c96.jpg)
这张图的两条线  x轴的坐标只显示了对应的一条y轴的数值(下面那条) 但是上面那条并没显示,实际上它显示的也不是当前位置的数值 而是传入点data[x,y] (相邻的)  当鼠标在data[x,y]和data[x+1,y+1]之间时并没有数据 也就是说只能显示出传入点的值,两个传入点之间的数值显示不出来

**Comment by wjdnlg** [comment]
@Ovilia 实际上我是想让data[x,y]和data[x+1,y+1]之间的数据也能通过tooltip显示出来

**Comment by Ovilia** [comment]
@wjdnlg 能再清楚地描述一下你的需求到底是什么吗？

**Comment by wjdnlg** [comment]
@Ovilia 
![image](https://user-images.githubusercontent.com/53259799/68555241-a2576300-0467-11ea-9ac6-e6c54cddefc4.png)
![image](https://user-images.githubusercontent.com/53259799/68555361-5d7ffc00-0468-11ea-86e8-b5850c400e24.png)
当鼠标移到横坐标1时tooltip会显示test1和test2分别对应的数值,
![image](https://user-images.githubusercontent.com/53259799/68555383-80aaab80-0468-11ea-9117-406c67301eea.png)
当鼠标移动到横坐标2时只显示了test2的值没有显示test1的值
![image](https://user-images.githubusercontent.com/53259799/68555411-a3d55b00-0468-11ea-8035-284576ba2593.png)
当鼠标移动到2.5时只显示了test1的值没有显示test2的值
![image](https://user-images.githubusercontent.com/53259799/68555442-c36c8380-0468-11ea-8afa-25eaa81124f9.png)
当鼠标移到3时test1和test2都显示

test1在横坐标为2时和test2在2.5时没有显示对应数值 (看第二第三张坐标图) 是因为data数组没有这个数值 (可以看看赋值的那张图片) ,我想的是既然这个折线图已经画出来了 只要知道横坐标  那他对应的纵坐标也应该显示出来  我这样说不知道明不明白  不明白我再补充

**Comment by Ovilia** [comment]
[convertToPixel](https://echarts.apache.org/zh/api.html#echartsInstance.convertToPixel) 获得的结果符合预期吗？

**Comment by wjdnlg** [comment]
@Ovilia 
![image](https://user-images.githubusercontent.com/53259799/68557461-da16d880-0470-11ea-9952-bdb4fa891c4b.png)
![image](https://user-images.githubusercontent.com/53259799/68557508-04689600-0471-11ea-8c4a-495750c86700.png)
使用convertToPixel取到的像素坐标是一样的  即使test1没有(2,30)这一点  
![image](https://user-images.githubusercontent.com/53259799/68557670-848efb80-0471-11ea-8d73-ae2f229fc60a.png)
![image](https://user-images.githubusercontent.com/53259799/68557981-90c78880-0472-11ea-9994-fd901da20931.png)


若果只传横坐标  test1和test2纵坐标都返回空 
如果能传横坐标,直接返回纵坐标就好了

**Comment by Ovilia** [comment]
你是想知道根据 smooth 插值后的 y？这个不支持的。
根据自己的 data 数组从 x 计算出 y，然后再传到 convert

**Comment by wjdnlg** [comment]
@Ovilia 
![image](https://user-images.githubusercontent.com/53259799/68573296-6d1c3680-04a2-11ea-8694-d85672d58409.png)
A B 两点之间折线图上的数值能获取到吗?

**Comment by wjdnlg** [comment]
@Ovilia 
![image](https://user-images.githubusercontent.com/53259799/68635617-195a2d80-0534-11ea-94ad-2e6f425c2dd6.png)
指示线与折线图的交点的y值能获取的到吗

**Comment by Ovilia** [comment]
不能的

**Comment by wjdnlg** [comment]
@Ovilia 好的 感谢

**Comment by wjdnlg** [comment]
@Ovilia 这个功能你们准备增加吗

**Comment by alex2wong** [comment]
> 你是想知道根据 smooth 插值后的 y？这个不支持的。
> 根据自己的 data 数组从 x 计算出 y，然后再传到 convert

我同意Ovilia 的说法，这个功能不应该由Echart 去承担，可能用的人并不多，反倒增加了复杂度。你可以在hover事件的handler 里面拿到 x，自己根据data 里面的数据，构建线性函数，去推算当时的y，然后标注到图表上。

这个特定的需求可以自己实现下

**Comment by Ovilia** [comment]
@wjdnlg 我的意见和 @alex2wong 一致
