### ISSUE TITLE
splitArea 横纵坐标不能同时设置颜色  

### ISSUE THREAD

**Issue by dauberc** [apache/incubator-echarts#11602]
![image](https://user-images.githubusercontent.com/55323120/68460879-e0743d00-0243-11ea-8252-324181ff8da3.png)
想实现类似效果 ,但是设置了x轴的颜色后 ,y轴就设置不了,会被覆盖掉
![image](https://user-images.githubusercontent.com/55323120/68461482-47462600-0245-11ea-899c-b4f0b5c7edd5.png)

**Comment by shuizhongxiong** [comment]
我也遇到同样的问题，不过我在 ` yAxis` 里面加上  `z: 1` 就可以了，具体可以参考[文档](https://echarts.apache.org/zh/option.html#xAxis.z)，希望帮到你。
