### ISSUE TITLE
dataZoom的文字出现显示不全的现象

### ISSUE THREAD

**Issue by chenweihuan** [apache/incubator-echarts#11601]
### Version
4.0.4

### Steps to reproduce
设置type:slider的dataZoom，hover在dataZoom后，文字会显示不全

### What is expected?
hover之后，可以设置文字的显示位置。

### What is actually happening?
如果在边界，文字会显示不全。
![1573200929596](https://user-images.githubusercontent.com/29496079/68461276-c8e98400-0244-11ea-8b7e-f8bc9fcc7d06.jpg)

**Comment by Ovilia** [comment]
Please set grid.left and right to be a large number.

**Comment by chenweihuan** [comment]
![20191111145400](https://user-images.githubusercontent.com/29496079/68567313-b022dd80-0493-11ea-90a5-6d740599fdcc.png)

当文字较长时，需要设置很大的grid.left and right才可以显示完全，这样处理不够灵活。如果可以添加偏移量或出现位置属性，让使用者决定文字显示在哪里就完美了。

**Comment by Ovilia** [comment]
这个不太可能智能处理，手动设置一下吧

**Comment by chenweihuan** [comment]
👌，感谢您的回复~~~
