### ISSUE TITLE
treemap中data父级结构发生变化，自动添加到了children子集

### ISSUE THREAD

**Issue by ybj6118** [apache/incubator-echarts#11619]
### Version
4.3.0

### Steps to reproduce
this.ec.option.series[0].data = arrayData
在formatter函数中打印出来的data中出现一个children子集并且arrayData在其中

### What is expected?
在使用treemap时，只有一级结构的数据能按照一级结构绘制

### What is actually happening?
一级结构数据被自动添加到children二级结构中去了

---
 this.ec1.option.series[0].data = newVal
 let gainChart = this.$echarts.init(document.getElementById('gain_chart'))
 gainChart.setOption(this.ec1.option)

**Comment by deqingli** [comment]
Sorry, I don't understand what your problem is? Please provide a demo to illustrate it.

**Comment by ybj6118** [comment]
> Sorry, I don't understand what your problem is? Please provide a demo to illustrate it.

its ok, i get this answer,I found that my data have negative value,thx your reply!
