### ISSUE TITLE
an issue of scroll type's legend

### ISSUE THREAD

**Issue by zyjwsg** [apache/incubator-echarts#11610]
### Version
4.3.0

### Steps to reproduce
1. get enough legends to show pagination, suggest making a 2 or 3 pages legends
2. scroll to last page
3. keep zooming in window, until pagination disappear

then you can see the issue: the pagination disappeared ! and only shows the last page of legends, parts of legends disappeared as well!

### What is expected?
correct pagination and correct legends are expected.

### What is actually happening?
pagination disappeared, parts of legends disappeared.

---
According to my observation, legends pagination disappeared when there is enough space to show all legends,  but current page number was not been re-calculate and legends were not been repaint during calculating space

### Sample
this is from official demo: [pie-legend](https://echarts.apache.org/examples/zh/editor.html?c=pie-legend), i changed legends count from 50 to 20, for easier test this issue
![image](https://user-images.githubusercontent.com/7666606/68482658-01a15180-0275-11ea-8842-5dd30312f64d.png)

while i kept zooming in window, pagination dissapeared:
![image](https://user-images.githubusercontent.com/7666606/68482739-28f81e80-0275-11ea-9f67-f0032f783b11.png)

**Comment by Ovilia** [comment]
Hi, @zyjwsg .
What do you mean by "zooming in window"?

**Comment by zyjwsg** [comment]
> Hi, @zyjwsg .
> What do you mean by "zooming in window"?

Hi, Ovilia.
it means some actions making window bigger, such as dragging to enlarge browser
like this gif:
![issue_echarts_11610](https://user-images.githubusercontent.com/7666606/68558679-2e23bc00-0475-11ea-9c64-9b894bad3ea1.gif)

**Comment by Ovilia** [comment]
Thanks for reporting. This seems to be a bug.

**Comment by SnailSword** [comment]
What is expected, should it turn to page 1, or turn to page which has first visible legend before changing, or any others?

**Comment by karma2014** [comment]
I am trying to fix the bug.
