### ISSUE TITLE
IOS 一个页面切换地理坐标图时报错：TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')

### ISSUE THREAD

**Issue by szkissyh** [apache/incubator-echarts#11615]
### Version
4.4.0

### Steps to reproduce
1、系统支持多个地理坐标图，但是当前只显示一个。
2、第一个地理坐标图显示正常
3、切换时，使用过clear或dispose方法
4、均报错，TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')
5、跟踪代码 this.dom.getContext('2d')为null
6、但是绘制地图的div存在，也没有隐藏

### What is expected?
IOS能够同时正常渲染地理坐标

### What is actually happening?
不能正常渲染

**Comment by Ovilia** [comment]
`dispose` 之后需要 `chart = null` 然后重新 `chart = echarts.init(...)`

**Comment by szkissyh** [comment]
> `dispose` 之后需要 `chart = null` 然后重新 `chart = echarts.init(...)`

修改了 还是报TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')

**Comment by pissang** [comment]
一般这种错误是 dispose 后继续使用 chart 实例造成的，@szkissyh 建议再排查一下，同时也可以整理一个可以最小复现的 demo 发给我们

**Comment by szkissyh** [comment]
> 一般这种错误是 dispose 后继续使用 chart 实例造成的，@szkissyh 建议再排查一下，同时也可以整理一个可以最小复现的 demo 发给我们

我发现了问题，并且可以复现，问题的核心是同样一个世界地图模型，在横屏和竖屏模式下占用的内存相差很多。
横屏模式占用内存较少，**为18M**
![image](https://user-images.githubusercontent.com/31839257/68581680-d9ebfc80-04b3-11ea-899c-c0d2fb66be30.png)
竖屏模式占用内存较多，**为49M**
![image](https://user-images.githubusercontent.com/31839257/68581720-f1c38080-04b3-11ea-896e-e9b8159b7d25.png)

而我们操作多为竖屏操作，多次操作后出现total canvas memory use exceeds the maximum limit，超出了safari支持的最大canvas内存支持（我的为384MB）

**Comment by pissang** [comment]
从截图来看你竖屏时候的分辨率太高了，对于 canvas 来说内存占用跟分辨率是正比的

**Comment by szkissyh** [comment]
> 从截图来看你竖屏时候的分辨率太高了，对于 canvas 来说内存占用跟分辨率是正比的

是分辨率太高了，调整以后就好了，谢谢

**Comment by kkkkkkxser** [comment]
> > 从截图来看你竖屏时候的分辨率太高了，对于 canvas 来说内存占用跟分辨率是正比的
> 
> 是分辨率太高了，调整以后就好了，谢谢

请问咋调分辨率呢

**Comment by szkissyh** [comment]
我们是定宽、定高 ，按比例修改了宽高
 


 
 
发件人： LittleJoke
发送时间： 2023-02-13 08:10
收件人： apache/echarts
抄送： szkissyh; State change
主题： Re: [apache/echarts] IOS 一个页面切换地理坐标图时报错：TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr') (#11615)
从截图来看你竖屏时候的分辨率太高了，对于 canvas 来说内存占用跟分辨率是正比的
是分辨率太高了，调整以后就好了，谢谢
请问咋调分辨率呢

**Comment by kkkkkkxser** [comment]
> 我们是定宽、定高 ，按比例修改了宽高 发件人： LittleJoke 发送时间： 2023-02-13 08:10 收件人： apache/echarts 抄送： szkissyh; State change 主题： Re: [apache/echarts] IOS 一个页面切换地理坐标图时报错：TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr') (#11615) 从截图来看你竖屏时候的分辨率太高了，对于 canvas 来说内存占用跟分辨率是正比的 是分辨率太高了，调整以后就好了，谢谢 请问咋调分辨率呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

好的 谢谢 ，我们这个好像不太适合调分辨率 刚才看到了一个方案 把renderer设置为svg好像不错
