### ISSUE TITLE
type of line does not display as expected with focusNodeAdjacency in graph

### ISSUE THREAD

**Issue by TYzzt** [apache/incubator-echarts#11627]
### Version
4.4.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xtpRvTtZD&v=2](https://gallery.echartsjs.com/editor.html?c=xtpRvTtZD&v=2)

### Steps to reproduce
click node '张三'

### What is expected?
line types  should show 3 solids and 3 dasheds 

### What is actually happening?
 only solids

**Comment by deqingli** [comment]
The value of [series-graph.emphasis.lineStyle.type](https://www.echartsjs.com/zh/option.html#series-graph.emphasis.lineStyle.type) is default to `solid`, if you want `dashed`, you can change the emphasis line type of related edge.
