### ISSUE TITLE
世界地图引用报错

### ISSUE THREAD

**Issue by bigshow23** [apache/incubator-echarts#11626]
### Version
3.8.2

### Reproduction link
[https://www.echartsjs.com/examples/vendors/](https://www.echartsjs.com/examples/vendors/)

### Steps to reproduce
我司网站调用了一款百度Echart世界地图的控件（下图红框）：
![37C43230@71FEA77E DF23C15D jpg](https://user-images.githubusercontent.com/23071000/68641013-7067fe80-0544-11ea-84cf-2333239d6b83.jpeg)

近期访问时发现地图已不显示：
![625B378D@D9FAA63C DF23C15D jpg](https://user-images.githubusercontent.com/23071000/68641045-942b4480-0544-11ea-93ab-b30eb2b4cc51.jpeg)

经排查，发现调用的脚本地址已无法访问：

调用的脚本地址：https://www.echartsjs.com/examples/vendors/
<img width="320" alt="CD3C4379@D4FC8E39 DF23C15D" src="https://user-images.githubusercontent.com/23071000/68641062-a1483380-0544-11ea-9ba3-d14bf3274ee7.png">

### What is expected?
能够告知正确的访问地址

### What is actually happening?
依然无法访问

**Comment by SnailSword** [comment]
你是想找这个世界地图文件的意思么
https://github.com/apache/incubator-echarts/blob/master/map/js/world.js
