### ISSUE TITLE
Treemap - SVG - Downloaded svg labels are not displayed into respective blocks.

### ISSUE THREAD

**Issue by Monali-ITT** [apache/incubator-echarts#11620]
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/hemantss/dnsrmezy/2/](https://jsfiddle.net/hemantss/dnsrmezy/2/)

### Steps to reproduce
1. Create treemap with svg render. 
2.  Click on download button (refer - https://jsfiddle.net/hemantss/dnsrmezy/2/).
3. Once image is downloaded open it.

### What is expected?
Labels should be display in all blocks in exported image.

### What is actually happening?
 Labels are not displayed in all blocks in exported image.

**Comment by Ovilia** [comment]
The rendering result of both Canvas and SVG are:
![image](https://user-images.githubusercontent.com/779050/68646775-11f84b80-0557-11ea-8662-867f38f7ff79.png)

After downloading the SVG image, it's also the same.
@Monali-ITT What's the expected output?

**Comment by Monali-ITT** [comment]
Yes,but  expected is all labels should be visible if someone is downloading and using it.

**Comment by Ovilia** [comment]
Why? Download result should be the same as rendering.

**Comment by Monali-ITT** [comment]
When we click on a block it expands and show label.but after download entire map as image user can not see the labels then how it will be useful for users?

**Comment by Ovilia** [comment]
This is the design of Treemap, where if the text is overflowing, it will not display at all. I think you can make a PR to improve this behavior. But I don't think it's reasonable to change the download logic.
