### ISSUE TITLE
selectorLabel 是否支持 修改emphasis样式?

### ISSUE THREAD

**Issue by 0x018** [apache/incubator-echarts#11623]
### Version
4.4.0

### Steps to reproduce
echarts自带的 selector: [
                {
                    type: 'all',
                    title: '全选',
                },
                {
                    type: 'inverse',
                    title: '反选'
                }
            ],
修改selectorLabel样式, 但是鼠标悬浮时,会有灰色的背景色, 无法更改

### What is expected?
目前是否支持修改selectorLabel在鼠标悬浮状态下的样式?
是否有相关说明?

### What is actually happening?
尝试过修改emphasis等属性,均未实现修改背景色样式.

**Comment by deqingli** [comment]
#11480

**Comment by 0x018** [comment]
> Is your problem the same as #11480?

no, different problems.

**Comment by deqingli** [comment]
It supports, you can modify it like below:
```js
legend: {
    selector: true,
    selectorLabel: {
        color: 'yellow',
        borderColor: 'green',
        backgroundColor: 'blue'                  
    },
    emphasis: {
         selectorLabel: {
             backgroundColor: 'red'
         }
    },
}                    
```
I am so sorry, I forget to add it to the doc.
