### ISSUE TITLE
<br/> tag does not work on label emphasis formatter

### ISSUE THREAD

**Issue by daniellycosta** [apache/incubator-echarts#11638]
### Version
4.3.0

### Reproduction link
[https://codepen.io/daniellycosta/pen/MWWqxPr](https://codepen.io/daniellycosta/pen/MWWqxPr)

### Steps to reproduce
It's just put a formatter using `<br/>` outside `tooltip` like in the example below

```
label: { 
    normal: {
        show: false,
        position: 'center'
     },
     emphasis: {
        show: true,
        formatter: "{b} <br/> {d}%",
        textStyle: {
        fontSize: '30',
        fontWeight: 'bold',
                        
         }
      }
 }
```

### What is expected?
break line

### What is actually happening?
show `<br/>` tag

---
I tested using my application and using apache site example

**Comment by SnailSword** [comment]
https://www.echartsjs.com/zh/option.html#series-pie.emphasis.label.formatter
这里可以用`\n`进行换行。
