### ISSUE TITLE
Latest ECharts 4.4/3/2 is not working with script tag, while Echarts 2.2.7 is working

### ISSUE THREAD

**Issue by ankitagrahari** [apache/incubator-echarts#11641]
### Version
4.4.0

### Steps to reproduce
I am using the latest echarts.min.js file and trying to use it by script tag in my jsp page. The application is able to get the js file, but on call to echarts, it is throwing error "echarts is undefined". This is happening with echarts 4.4 or 4.3 or 4.2. But the same is working with 2.2.7 version.

Usage for 4.4:
<script type="text/javascript" src="/js/echarts.min.js"></script>
<div id="container" style="width: 600px; height: 250px;"></div>
<script type="text/javascript">
          var myChart = echarts.init(document.getElementById("main"));
</script> 

Usage for 2.2.7
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/echarts/2.2.7/echarts-all.js"></script>
<div id="container" style="width: 600px; height: 250px;"></div>
<script type="text/javascript">
          var myChart = echarts.init(document.getElementById("main"));
</script>

### What is expected?
latest echarts 4.4 should work with script tag in jsp page

### What is actually happening?
echarts.min.js is throwing error on calling echarts.init()
echarts is undefined

---
I have raised a previous ticket #11573, but since I got the echarts2.2.7 working I closed it. But with the echarts 2.2.7 version, I got it from cdn and there is no license information, and i cannot find a link for echarts 2.2.7 on echarts.apache.org site. Kindly let me know following:
1. how the echarts 2.2.7 different from echarts 4.4 which is not working with script tag ?
2. If I am using echarts 2.2.7, are there any licence information and a link from echarts website to use ?

Thanks

**Comment by 100pah** [comment]
It probably be some basic "HTML/JS" developing issue, but not related to echarts.

**Comment by ankitagrahari** [comment]
How the echarts 2.2.7 different from 4.4, because when integrated with echarts2.2.7, I am able to get the object, but with 4.4, the echarts object is not present and throwing error "echarts is undefined". Is there any change needs to be done apart from adding the echarts in the script tag ?

Apart from that, do you still support echarts 2.2.7 and can I get a link for echarts 2.2.7 js files on echarts website?

NOTE: the browser is able to the js file, I can confirm this as I am seeing it in Network tab of my browser.

Thanks

**Comment by Ovilia** [comment]
You can get the global `echarts` variable. Here's an example: https://jsfiddle.net/ovilia/n6xc4df3/
Please check your HTML to make sure it is including the JavaScript correctly.

**Comment by ankitagrahari** [comment]
Hi Olivia, 

I was not able to access the echarts variable because the echarts variable is not exported in the echarts.js file. I made the following highlighted change in the echarts.js file, after which I could access the echarts in my jsp page.
![image](https://user-images.githubusercontent.com/4497558/69122001-b0d6f780-0ac3-11ea-9380-0cdcae2e2af8.png)

I am closing the ticket now as I can create charts using echarts, but with a limitation that I have to change the echarts.js file to access echarts variable.

Thanks for the help.
