### ISSUE TITLE
Multi-colored line charts

### ISSUE THREAD

**Issue by rajpatelukyahoo** [apache/incubator-echarts#11647]
### What problem does this feature solve?
Please see the example below.

![image](https://user-images.githubusercontent.com/30202450/68869971-aed5f880-06bf-11ea-9033-c0c328e37632.png)

https://www.benlcollins.com/wp-content/uploads/2017/05/multi-colored-line-chart.png

### What does the proposed API look like?
..

**Comment by deqingli** [comment]
You can do this with three different series.
