### ISSUE TITLE
Add property to define size of a node in Sankey Chart

### ISSUE THREAD

**Issue by peterviergutz** [apache/incubator-echarts#11644]
### What problem does this feature solve?
In the current implementation the node size in a Sankey chart is determined by the bigger number of incoming or outgoing edges. Our case involves a node size that is actually bigger than the connections between the nodes:

![expected](https://user-images.githubusercontent.com/568682/68852007-4bf05b80-06d7-11ea-9b0f-f18b10120181.png)

### What does the proposed API look like?
An optional new property `size` on the nodes' properties could offer a clean option to define the node's size

```json
{
  "nodes": [
    {
      "name": "a1",
      "size": 100
    }
...
```

To get the node's size in the chart could then be determined by whatever is bigger: the sum of incoming and outgoing edges or the node's defined size in 

https://github.com/apache/incubator-echarts/blob/fcfa95012ca561becab607b065a62b5f87220801/src/chart/sankey/sankeyLayout.js#L86

```js

function computeNodeValues(nodes) {
  zrUtil.each(nodes, function (node) {
    var value1 = sum(node.outEdges, getEdgeValue);
    var value2 = sum(node.inEdges, getEdgeValue);
    var value = Math.max(value1, value2, node.size); // <-- node.size here
    node.setLayout({
      value: value
    }, true);
  });
}
```

**Comment by deqingli** [comment]
Maybe I can add new property `value` of each node, to keep consistent with graph series.
```js
nodes: [{
    name: 'aaa',
    value: '100', // the same effect as size
    depth: 3
}]
```

**Comment by peterviergutz** [comment]
I agree `value` would have been the right name in the first place. Thanks for your consideration. 

PS I guess just a typo, but `100` should be an integer.

**Comment by ChibahAbdelwahab** [comment]
Hi,

**Comment by deqingli** [comment]
> I agree `value` would have been the right name in the first place. Thanks for your consideration.
> 
> PS I guess just a typo, but `100` should be an integer.

Yeah, it is an integer,  thanks.
