### ISSUE TITLE
柱状图  x轴显示问题  ，版本我没看是多少 我是从官方实例直接下载的html，随便选了一个

### ISSUE THREAD

**Issue by heqiang** [apache/incubator-echarts#11640]
### Version
4.5.0-rc.2

### Steps to reproduce
我是下载后应用于本地网站的搭建 如果可以 我想截图的  x轴的data 有十个 对应的y的值  但是反复刷新后就显示了只有一半的值了，还有一般的值 字体消失 鼠标指向消失字体的柱状时仍有对应的正确提示

### What is expected?
显示完全

### What is actually happening?
多刷新几次就只有几个了

**Comment by heqiang** [comment]
I don't know what's the reason. When I just refreshed, there was no problem, but there was no problem with the background value transfer. I was wondering if there was any cache reason in the front end that the South could not refresh too fast

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"echarts-bot[bot]"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 下午2:15
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"1422127065"<1422127065@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] 柱状图  x轴显示问题  ，版本我没看是多少 我是从官方实例直接下载的html，随便选了一个 (#11640)




Hi! We've received your issue and please be patient to get responded. 
 The average response time is expected to be within one day for weekdays.
 
In the meanwhile, please make sure that you have posted enough image to demo your request. You may also check out the API and chart option to get the answer.
 
If you don't get helped for a long time (over a week) or have an urgent question to ask, you may also send an email to dev@echarts.apache.org. Please attach the issue link if it's a technical questions.
 
If you are interested in the project, you may also subscribe our mail list.
 
Have a nice day!

**Comment by deqingli** [comment]
Please provide more detailed message for us to debug, for example, a picture or a demo in echarts [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all).

**Comment by cdll** [comment]
same issue here
