### ISSUE TITLE
x轴显示位置错乱

### ISSUE THREAD

**Issue by TideDlrow** [apache/incubator-echarts#11654]
### Version
4.5.0-rc.2

### Steps to reproduce
这是我的option
```
option = {xAxis: [{
        name:'月份',
        type: 'value',
        position:'bottom',
        min:0,max:10
      },{
        name:'值',
        type: 'value',
        show: true,
        position:'top',
        min:0,
        max: 10,
      }],
      yAxis: [{
        type: 'value',
        position:'left',
        min:0,max:10
      },{
        type: 'value',
        show: true,
        min: 0,
        max: 10,
        position:'right'
      }],
    }
```

### What is expected?
我期望是name='值'显示在图表的右上角

### What is actually happening?
但是实际上两个x轴的名字重叠在一起了

---
如果我把y轴的第二个配置删除掉，x轴的显示就是正常的。请问是我的配置存在问题吗？

**Comment by karma2014** [comment]
@TideDlrow My option is ：
`option = {
    xAxis: [
        {
            type: 'category',
            name:'月份',
            nameLocation:'start',
            data: ["2016-1", "2016-2", "2016-3", "2016-4", "2016-5", "2016-6", "2016-7", "2016-8", "2016-9", "2016-10", "2016-11", "2016-12"]
        },
        {
            type: 'category',
            name:'值',
            nameLocation:'start',
            axisLine: {
                onZero: false,
            },
            data: ["2015-1", "2015-2", "2015-3", "2015-4", "2015-5", "2015-6", "2015-7", "2015-8", "2015-9", "2015-10", "2015-11", "2015-12"]
        }
    ],
    yAxis: [
        {
        type: 'value',
        xAxisIndex: 1,
        position:'left',
        min:0,
        max:10
      },{
        type: 'value',
        xAxisIndex: 0,
        show: true,
        min: 0,
        max: 10,
        position:'right'
      }
    ],
};`
关键是这个属性xAxis.axisLine.onZero，官方文档解释：“X 轴或者 Y 轴的轴线是否在另一个轴的 0 刻度上，只有在另一个轴为数值轴且包含 0 刻度时有效。”

**Comment by TideDlrow** [comment]
@karma2014  
确实如此，谢谢！！
