### ISSUE TITLE
How can I get max of value y axis?

### ISSUE THREAD

**Issue by tv-dm** [apache/incubator-echarts#11655]
### What problem does this feature solve?
I have some series. I would like to have vertical separator in the chart and I need to know max value of y axis.

### What does the proposed API look like?
https://api.highcharts.com/highstock/yAxis.max

**Comment by deqingli** [comment]
The `API` in `highcharts` used to set the `max` value of yAxis, echarts also has the same [API](https://www.echartsjs.com/zh/option.html#yAxis.max).
