### ISSUE TITLE
Legend filtering not working correctly with pie chart selection?

### ISSUE THREAD

**Issue by mariamtsartsidze** [apache/incubator-echarts#11658]
### Version
4.4.0

### Steps to reproduce
Use legend to filter out selected sector from pie chart - next sector becomes selected

### What is expected?
Right behaviour would be that selected sector just to became hidden and next sector remained unselected.

### What is actually happening?
When filtering out selected sector from pie chart, next sector becomes selected instead

---
If it is not a bug, can anyone tell me how to avoid this behaviour?

**Comment by mariamtsartsidze** [comment]
This is the behaviour right now:

![image](https://user-images.githubusercontent.com/41511058/68971740-a7b80300-0803-11ea-942d-5255db7574bc.png)

![image](https://user-images.githubusercontent.com/41511058/68971762-b4d4f200-0803-11ea-95cb-d20df21d052a.png)

**Comment by Ovilia** [comment]
@mariamtsartsidze Can you provide a demo? https://jsfiddle.net/ovilia/n6xc4df3/
I cannot reproduce from https://echarts.apache.org/examples/en/editor.html?c=pie-simple

**Comment by mariamtsartsidze** [comment]
Demo provided by you does not support selection for pie chart.

Use this demo:
https://www.echartsjs.com/examples/en/editor.html?c=pie-rich-text

Select a sector and then filter out that selected sector using the legend.

**Comment by alex2wong** [comment]
o, I see.  You mean, after the previous selected item has been removed, the selected state would be applied to next slice.. It seems a bug ? @Ovilia . 
I guess the selected state is bind to index of item in data array, not item ID,  which cause this to happen.

**Comment by Ovilia** [comment]
Yes. This is a bug. I think @alex2wong 's guess is promising. Do you wish to make a pull request? Thanks!

**Comment by daming-lu** [comment]
@Ovilia : I am working on this issue and got a question:

Even I set all the legends in selectedMap to be false, there is still one pie chart that gets selected. I doubt it might not be a bug in legend, but in pie chart.

<img width="1675" alt="Screen Shot 2019-12-27 at 2 30 08 PM" src="https://user-images.githubusercontent.com/5635322/71534730-990a4480-28b5-11ea-84ab-ab6dd7a6bb44.png">

**Comment by alex2wong** [comment]
@daming-lu  that's it ! the data `name` should be passed into seriesModal.isSelected to get the selected state instead of `idx`. idx is the newIdx of data after piePiece.updateData. Thanks ~
