### ISSUE TITLE
ECharts 关系图设置legendHoverLink:true,图例不能联动节点高亮

### ISSUE THREAD

**Issue by journey-wen** [apache/incubator-echarts#11663]
### Version
4.3.0

### Steps to reproduce
关系图设置了legendHoverLink:true，也配置了节点的高亮状态，但是图例hover并不能联动节点高亮

### What is expected?
折线图，饼图，雷达图等等都可以实现图例联动高亮，希望关系图也可以实现图例联动节点高亮

### What is actually happening?
关系图不能实现鼠标hover图例时联动节点高亮

**Comment by Ovilia** [comment]
Hi. Please provide a demo https://gallery.echartsjs.com/editor.html

**Comment by novayoung** [comment]
The demo is :
https://echarts.apache.org/zh/option.html#series-graph.legendHoverLink

**Comment by eahom2** [comment]
Hi @Ovilia, 当lineChart，series数组长度大于45时， `legendHoverLink:true` 会失效！我的echarts版本为5.5.0
