### ISSUE TITLE
Request a feature to customize the interval length among the axis labels for category axis

### ISSUE THREAD

**Issue by marcus-aurelianus** [apache/incubator-echarts#11669]
### What problem does this feature solve?
Then the category axis label interval can be customized.

### What does the proposed API look like?
Like xAxis.categoryinterval
Function(param)
{
return param.seq%someval/someval}

[0,1] scale the distance among the axis labels.

**Comment by marcus-aurelianus** [comment]
[https://www.pinterest.com/pin/657384876842441305](url)

**Comment by Ovilia** [comment]
What's the rule for your x axis labels?

**Comment by marcus-aurelianus** [comment]
> What's the rule for your x axis labels?

the distance between labels can be customized with call back function ranged from [0,1],
where 0 means very close. 1 means relative far.
So I can adjust the distance netween labels from callback funtion easily. Example are,

the above graphs the distance among '12h' '1h' '30mins' are, lets said 0.3
and distance between '12h' '1h' '30mins' and another '12h' '1h' '30mins' are, lets said 0.9

If it is still hard for you to visualize, reply me again and I will draw a graph for you.

**Comment by Ovilia** [comment]
Can you explain in which cases this feature is helpful? For example, Why are there multiple `'12h'`s in the graph and what the x axis mean?

**Comment by marcus-aurelianus** [comment]
> Can you explain in which cases this feature is helpful? For example, Why are there multiple `'12h'`s in the graph and what the x axis means?

The x axis is a category axis, which means time frame in this case.
The currency name is on the bubble. For different currencies, there are time frames for them to compare upon.

Why is it needed to adjust the interval distance?

Because if same group of currencies are nearer. And different currencies are separated as shown in the graph. It will be much easier to visualize them.

Or if this function is not supported, everything item on the category axis have same distance. I cannot tell the currencies when I glance at the intersection areas of the currencies.

**Comment by Ovilia** [comment]
So the distance is for grouping? `12h`, `1h`, `30m` should be each a series, and `usd`, `eur` should be x values.

**Comment by marcus-aurelianus** [comment]
> So the distance is for grouping? `12h`, `1h`, `30m` should be each a series, and `usd`, `eur` should be x values.

Yes. If there is a callback function for me to adjust the distance between category labels, the problem can be solved.

The `usd`, `eur` are not technically x values, the are name of the series. Each series contains 3 value with x values `12h`, `1h`, `30m`.

**Comment by Ovilia** [comment]
I cannot imagine a more general required scenario of this requirement. So I'm afraid I'd say won't fix for now.

**Comment by marcus-aurelianus** [comment]
imagine bubbles here instead of bar here, but the color can be customized for each items here. Is there any way to do it?
[Example you can imagine the bar chart become bubble chart](https://www.echartsjs.com/examples/en/editor.html?c=bar-label-rotation)

**Comment by Alizwell** [comment]
I have a similar requirement to custom the interval. In my business scenario, I need to statistics the product data by day. Usually, I think one day is 24 hours, so I set the interval as 24 hours, but in some areas(like the US), one day maybe 25 hours or 23 hours due to the Daylight  Saving Time. So I can't just set the interval as 24 hours. But there is no way for me to custom the interval.

**Comment by Ovilia** [comment]
@Alizwell Can you use https://echarts.apache.org/en/option.html#yAxis.interval ?
