### ISSUE TITLE
dataZoom with rangeMode: 'value' is broken

### ISSUE THREAD

**Issue by dr-itz** [apache/incubator-echarts#11679]
### Version
4.5.0

### Steps to reproduce
When dataZoom is used with rangeMode: 'value', zoom gets reset immediately when data is added or changed. When rangeMode is left to the default value, it works. But rangeMode: 'value' is required since we need the chart to stay still when zoomed in and new data is added. This worked correctly in v4.2.1.

This is a slight adaptation of the dynamic data example that shows the problem. Just execute in the try editor, zoom in with the mouse wheel. When the next data updated is added, zoom, resets immediately.

```
function randomData() {
    now = new Date(+now + oneDay);
    value = value + Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
            Math.round(value)
        ]
    }
}

var data = [];
var now =  new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
    data.push(randomData());
}

option = {
    xAxis: {
        type: 'time',
    },
    yAxis: {
        type: 'value',
    },
    series: [{
        name: 'test',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data
    }],
    dataZoom: [{
        type: 'inside',
        rangeMode: 'value'
    }]
};

setInterval(function () {
    for (var i = 0; i < 5; i++) {
        data.shift();
        data.push(randomData());
    }
    myChart.setOption({ series: [{ data: data }] });
}, 1000);
```

### What is expected?
current zoom should remain unchanged

### What is actually happening?
zoom is reset when data is added/changed

**Comment by Ovilia** [comment]
Thanks for reporting. Does the PR #8490 fix this problem?

**Comment by dr-itz** [comment]
@Ovilia no, #8490 is unrelated. It's just that is problem is blocking me from testing if #8490 is fixed (which I believe it is)

**Comment by Ovilia** [comment]
Can you provide a working demo at https://gallery.echartsjs.com/editor.html ?

**Comment by dr-itz** [comment]
Sorry, I haven't realized how broken the example in the initial comment was. Turns out that creating an issue using https://ecomfe.github.io/echarts-issue-helper removes all  `+` in the code, replaced by ` `. Fixed now

**Comment by 100pah** [comment]
@dr-itz 

I think `rangeMode: 'value'` is not broken, but is a break change that I didn't noticed. The previous behavior supports your usage but it is buggy in some cases. So I fixed it in the subsequent version, and clarified the definition of [dataZoom.rangeMode](https://echarts.apache.org/en/option.html#dataZoom-inside.rangeMode). That makes your code work in the previous version but probably logically incorrect in the current definition.

Please try this code. I hope it can match your requirement:

```js

var myChart = echarts.init(document.getElementById('main0'));

function randomData() {
    now = new Date(+now + oneDay);
    value = base++;
    return {
        name: now.toString(),
        value: [now, value]
    }
}

var data = [];
var base = 10;
var now = new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
for (var i = 0; i < 100; i++) {
    data.push(randomData());
}

option = {
    tooltip: {
        confine: true
    },
    xAxis: {
        type: 'time',
    },
    yAxis: {
        type: 'value',
        scale: true
    },
    series: [{
        name: 'test',
        type: 'line',
        hoverAnimation: false,
        data: data
    }],
    dataZoom: [{
        type: 'inside'
        // Do not set rangeMode here
    }]
};

setInterval(function () {
    for (var i = 0; i < 5; i++) {
        data.shift();
        data.push(randomData());
    }
    myChart.setOption({
        series: [{ data: data }]
    });
}, 1000);

// Listen to dataZoom event, and set `startValue` and `endValue` to 
// fix the data window if zoomed.
myChart.on('dataZoom', function (event) {
    var dzCurrOpt = myChart.getOption().dataZoom[0];

    var dzOpt = {};
    dzCurrOpt.start > 0 ? (dzOpt.startValue = dzCurrOpt.startValue) : (dzOpt.start = 0);
    dzCurrOpt.end < 100 ? (dzOpt.endValue = dzCurrOpt.endValue) : (dzOpt.end = 100);

    myChart.setOption({
        dataZoom: dzOpt
    }, {lazyUpdate: true});
});

myChart.setOption(option);
```

And next, we should think of whether to add an option to support your case instead of the code above.

**Comment by dr-itz** [comment]
Thanks. I'll see if I can integrate those suggestions into our code and report back. We already do some special cases in the datazoom handler so that might actually fit nicely.
