### ISSUE TITLE
calendar not displaying ranges properly

### ISSUE THREAD

**Issue by macthestack** [apache/incubator-echarts#11677]
### Version
4.5.0

### Reproduction link
[https://codesandbox.io/s/wizardly-pascal-jcom3](https://codesandbox.io/s/wizardly-pascal-jcom3)

### Steps to reproduce

see link

I can only reproduce it with UK timezone set

### What is expected?
A contiguous calendar.

### What is actually happening?
Days jumbled all over.

![Screenshot 2019-11-20 at 17 03 43](https://user-images.githubusercontent.com/10058934/69260436-cd545c00-0bb7-11ea-95be-ebf3c9ddcf79.png)

**Comment by macthestack** [comment]
Added images since the bug seem to depend on what timezone you are in which may not be obvious.

**Comment by Ovilia** [comment]
Reproduced with UK timezone.

**Comment by macthestack** [comment]
Any updates on this?

**Comment by Ovilia** [comment]
@macthestack Sorry. Let me put it to a higher priority.

**Comment by macthestack** [comment]
Thank you.

**Comment by yafengstark** [comment]
The situation gets wrong result because of DST.

**Comment by 100pah** [comment]
Fixed in #12172
