### ISSUE TITLE
将svg模式 的图表保存到剪贴板

### ISSUE THREAD

**Issue by eniaclyl** [apache/incubator-echarts#11676]
### What problem does this feature solve?
需要将svg图表保存到剪贴板，然后粘贴到word2019，写报告用。

### What does the proposed API look like?
            toolbox: {
                feature: {
                    saveAsClipboard: { type: 'svg' }
                 } }

**Comment by eniaclyl** [comment]
@Ovilia @pissang  help me！！！Thank you！！！

**Comment by Ovilia** [comment]
I don't think saving to clipboard is a common need for chart viewers. But you can save the SVG file by setting [saveAsImage](https://echarts.apache.org/en/option.html#toolbox.feature.saveAsImage) and `type` should be `'svg'`.

**Comment by eniaclyl** [comment]
@Ovilia But I want to know this method

**Comment by eniaclyl** [comment]
@Ovilia help me！

**Comment by Ovilia** [comment]
What do you want to know? How to make it possible to provide such a new toolbox feature?

**Comment by eniaclyl** [comment]
@Ovilia 1、能否提供这种功能
2、如果不能提供这种功能，我该如何实现将svg保存到剪贴板的这个功能。
求教

**Comment by eniaclyl** [comment]
![微信图片_20191119163817](https://user-images.githubusercontent.com/42328995/69130480-8f8a0180-0aeb-11ea-914f-f5015174a8aa.png)
@Ovilia @pissang  How can this function be implemented?

**Comment by Ovilia** [comment]
1. No. But you can change the code and use the build from it.
2. See the code [here](https://github.com/apache/incubator-echarts/tree/master/src/component/toolbox/feature). As for clipboard, you probably need something like [clipboard.js](https://clipboardjs.com/).

**Comment by eniaclyl** [comment]
@Ovilia 我不太懂web所以无法修改源代码，clipboard.js我研究半天发现只能将文本存入剪贴板，无法将svg存入剪贴板能否给个思路，谢谢。

**Comment by Ovilia** [comment]
没法修改源代码的话，是没法实现你的需求的。不明白为什么你不能把 SVG 下载到本地以后打开 SVG 文件复制？
复制文本的话，SVG 内容也可以变成文本，不懂 Web 的不太能实现……

**Comment by eniaclyl** [comment]
@Ovilia 是这样的，我做的这个项目是用Qt嵌入Echarts显示图表，首先从本地文件中解析数据信息然后传给Echarts显示，然后领导需要用这个图写相关的文档，那么就需要提供一个按钮将图保存到剪贴板，然后Ctrl+V就拷贝到word中了，这样操作比较方便，你说的那种先保存到本地，然后再从word插入也可以实现这个功能，但是操作上就麻烦很多，所以我想实现这个功能，我觉得Echarts也应该提供一个这样的功能，毕竟剪贴板也是一个小平台，有的时候不是都要保存到本地的，再比如直接保存到剪贴板然后粘贴到qq发送等等，希望你们可以考虑下这个需求真的很实用，谢谢

**Comment by eniaclyl** [comment]
@Ovilia 我搞定了用  document.querySelector('svg').outerHTML  获取svg的文本串，然后传给Qt，用Qt实现保存到剪贴板功能，但是我刚才提的那个需求真的很使用，希望你们考虑下，另外能否帮我看看#11675，谢谢

**Comment by mitchjb2008** [comment]
Any chance this could be reconsidered as a feature?
