### ISSUE TITLE
echarts4 中 series[i]-graph 下设置 zoom有效，但我没有在任何地方找到这个属性的说明

### ISSUE THREAD

**Issue by liuy666** [apache/incubator-echarts#11688]
### Version
4.4.0

### Steps to reproduce
我知道4.x版本支持大多数配置的向下兼容,但series[i]-graph下的zoom属性(控制整体缩放)在现在的文档中没有提及，在版本记录中也找不到相关改动说明

### What is expected?
了解这个配置以及更多“隐藏”的配置

### What is actually happening?
无

**Comment by Ovilia** [comment]
Please provide a simple demo https://gallery.echartsjs.com/editor.html
