### ISSUE TITLE
X Axis Label的interval设为0时，x轴最后一个label变成粗体

### ISSUE THREAD

**Issue by lvybriage** [apache/incubator-echarts#11685]
### Version
4.1.0-release

### Steps to reproduce
option = {
"xAxis": {
"type": "category",
"data": ["水电费撒旦", "这一行为什么会变粗"],
"axisTick": {
"show": false
},
"axisLabel": {
"fontSize": 14,
"fontWeight": 'normal',
"interval": 0,
"rotate": 0,
}
},
"yAxis": {
"type": "value",
},
"series": [{
"data": [2, 3],
"type": "bar",
"name": "水电费",
}, {
"data": [3, 4],
"type": "bar",
"name": "大师傅",
}]
}

### What is expected?
X轴字体正常

### What is actually happening?
X轴最后一个文本字体变粗

---
This issue is duplicated with #10304. This question is not resolved but #10304 is closed. It's confused.

**Comment by Ovilia** [comment]
This should have been fixed in previous releases. Please use 4.5.0 to test. You may re-open this issue if you find it doesn't work.
