### ISSUE TITLE
Split area style does not apply to single axis graphs

### ISSUE THREAD

**Issue by BertrandDungan** [apache/incubator-echarts#11690]
### Version
4.5.0

### Reproduction link
[https://jsfiddle.net/jq1dnfs2/1/](https://jsfiddle.net/jq1dnfs2/1/)

### Steps to reproduce
Create single axis graph and attempt to use areaStyle to set the colour of the splitArea.

### What is expected?
The split area will be coloured according to the area style.

### What is actually happening?
The area is not styled.

**Comment by Ovilia** [comment]
Thanks for reporting. This seems to be a bug.
