### ISSUE TITLE
setOption时页面卡顿

### ISSUE THREAD

**Issue by liyunying** [apache/incubator-echarts#11691]
### Version
4.3.0

### Steps to reproduce
地图攻击线：（从后台一次性获取到数据，大概500条，需求是攻击线一条一条打出，不是一次性全部打出）
1. 获取到每次打出的一条数据（1条）。
2 .定时任务，每2秒钟通过setOption改变每次要打出的数据。

### What is expected?
页面不会出现卡顿

### What is actually happening?
不只是地图攻击线卡顿，现在整个页面的（包括地图以外的模块）动态效果都收到影响，出现卡顿。卡顿的间隔就是每次setOption的时候。

---
1. setOption时是否占用浏览器内存过高导致？
2. 能否后期出现配置项，每次只有一条攻击数据攻击，而不是同时进行攻击（或者叫路线、轨迹）？

**Comment by liyunying** [comment]
尝试过appendData不会卡顿，但是没有相关的方法去removeData，这样数据越来越多，导致攻击线也会越来越多。

**Comment by Ovilia** [comment]
https://gallery.echartsjs.com/editor.html 请在这里复现一个**最简单**的例子

**Comment by liyunying** [comment]
这个问题已经解决：不要把lines和map他们放在一起，提出来单独画。

**Comment by colorfulSunday** [comment]
你好，我也遇到了同样的需求和问题，请问一下，你说的提出来单独画是指，创建2个echart实例，每个实例分别对地图和lines来setOption吗。2个echart实例的dom元素是同一个dom吗，怎么保证它们的坐标是一致的？
