### ISSUE TITLE
堆叠柱状图，各个category中的bar支持其他排序方式

### ISSUE THREAD

**Issue by wonderjar** [apache/incubator-echarts#11702]
### What problem does this feature solve?
堆叠柱状图里多个series比如A,B,C三个series，使用同一个stack，每个series的bar总是以固定的顺序堆叠上去，每个category的bar都是A-B-C的顺序。希望有方式能更改这个排序方式，能根据在一个category里各自的数值，比如从大到小排序

### What does the proposed API look like?
不知道最佳方案是如何，也许是在options顶层，增加属性，stack
```
{
  stack: [
    {
      name: "stack1",
      order: "default" | "asc" | "desc" | sort_func 
    }
  ]
}
```

**Comment by Ovilia** [comment]
堆叠顺序是按系列顺序排的，如果按从大到小排，就会出现每个柱子中每个系列的顺序不一致的情况，这不是一个好的设计。请问有什么合理的情况需要这样的需求吗？

**Comment by wonderjar** [comment]
这个是 阿里云控制台首页的账单统计，各个柱子是各类比如服务器类，数据库类，文件存储类等的花费，能一眼看出，1. 在每个月花费最多的是哪几类 2. 最多的几类顺序是否发生了变化

我老板特别想要这样的图，不过我现在更广泛地调研了一下，诸如g2, amchat, google chart, high chart，看起来也没有提供层叠柱状图的自定义排序功能，所以可能确实这不是一个强需求吧，你们也觉得不是强需求就close吧

<img width="705" alt="389609EF-EDCB-4F09-93CD-977FDE9F2051" src="https://user-images.githubusercontent.com/8806004/69595310-2863d400-103a-11ea-87fb-800c7334e7d2.png">

**Comment by SnailSword** [comment]
你的这个截图貌似也不是按花费的顺序排列的，最下面的绿色的那条看起来比它上面那条要高。
如果要实现：

> 1. 在每个月花费最多的是哪几类 2. 最多的几类顺序是否发生了变化

这个两个效果的话，是不是这种图更能表达清楚：https://www.echartsjs.com/examples/zh/editor.html?c=bar-label-rotation

**Comment by wonderjar** [comment]
> 你的这个截图貌似也不是按花费的顺序排列的，最下面的绿色的那条看起来比它上面那条要高。
> 如果要实现：
> 
> > 1. 在每个月花费最多的是哪几类 2. 最多的几类顺序是否发生了变化
> 
> 这个两个效果的话，是不是这种图更能表达清楚：https://www.echartsjs.com/examples/zh/editor.html?c=bar-label-rotation

最下面的绿条是把过多的小项整合为其他，所以才会看起来数值比上边的大，思路还是按数值排序吧。分组柱状图支持的分组数量比较少吧，分组稍微多一些感觉空间就不够。

**Comment by SnailSword** [comment]
> 最下面的绿条是把过多的小项整合为其他，所以才会看起来数值比上边的大。

原来是这样，我刚才没get到最下面的绿条是把过多的小项整合为其他的意思。

**Comment by Ovilia** [comment]
整合的话就比较定制化了，建议还是自己处理数据之后再传入。如果有比较通用的应用场景的话，再考虑支持这类功能。

**Comment by sdtazhanghe** [comment]
我这边也接到了相应的 series内部排序 希望考虑支持。

**Comment by hks2002** [comment]
可参见#17455

**Comment by hks2002** [comment]
对数据进行正常排序(前后端均可), 然后将json数组里面的每一个json对象作为一个序列, Sorted the data first! then set each json object as a serial.
```
    forEach(dataBySite[site], (json) => {
      dataset.push({ source: [json] })
      series.push({
        name: json['NCCAT'],
        type: 'bar',
        datasetIndex: dataset.length - 1,
        xAxisIndex: 0,
        yAxisIndex: 0,
        label: {
          show: true,
          position: 'bottom',
          formatter: '{@PCT}'
        },
        emphasis: {
          focus: 'series'
        },
        tooltip: {
          trigger: 'item',
          formatter: multiLineFormatter
        },
        encode: {
          x: 'target',
          y: 'PCT'
        },
        stack: site,
        label: {
          show: true,
          verticalAlign: 'middle',
          position: '',
          formatter: '{@catCnt}'
        }
      })
    })
```
关键代码core code:
此例中原始数据进行了分组，按分组进行堆叠。
```
forEach(dataBySite[site], (json) => {
      dataset.push({ source: [json] })
      series.push({
        name: json['NCCAT'],
        stack: site,
```
效果如下Result as bellow：
![image](https://github.com/user-attachments/assets/abf188b5-fc66-4377-9028-65ef9b5af946)
@Ovilia 这个需求应该还是很广泛的，看我的这个例子，每个月的不良统计， 质量QC都希望将主要的原因进行排序，然后找到主要的原因80%以内的，可以进行排序的话，那就很容易找到主要原因，很直观。
