### ISSUE TITLE
山东省地图中须删除莱芜市

### ISSUE THREAD

**Issue by WJXingLC** [apache/incubator-echarts#11709]
### Version
4.5.0

### Reproduction link
[https://github.com/apache/incubator-echarts/blob/master/map/js/province/shandong.js](https://github.com/apache/incubator-echarts/blob/master/map/js/province/shandong.js)

### Steps to reproduce
在echarts官网“https://github.com/apache/incubator-echarts/blob/master/map/js/province/shandong.js”，可以搜到莱芜市相关字样；

### What is expected?
山东省莱芜市已于2019年1月正式撤销，其所辖区域划归济南市管辖；山东省地图中应只有16地市；须将莱芜市地图土地并入济南市地图中

### What is actually happening?
山东省地图中依然有莱芜市

---
将莱芜市删除，土地区域归入济南市

**Comment by pissang** [comment]
You can get latest map data from https://github.com/echarts-maps
