### ISSUE TITLE
When using xAxis type 'time' chart is not optimised and shows all data points, which makes performance very slow.

### ISSUE THREAD

**Issue by jaworek** [apache/incubator-echarts#11704]
### Version
4.5.0

### Steps to reproduce
1. Have big series of data. (In my case it's over 8000 elements) e.g. series: [{data: [date, value]}]
2. Set xAxis type to 'category'. Chart will be smooth and performant.
![Screenshot 2019-11-22 at 14 11 51](https://user-images.githubusercontent.com/22678765/69429128-28f72480-0d33-11ea-855c-eda8d9aa47b3.png)

3. Set xAxis type to 'time'. Chart will display all data point separately and perform very poorly.
![Screenshot 2019-11-22 at 14 11 29](https://user-images.githubusercontent.com/22678765/69429097-167ceb00-0d33-11ea-97d9-558e35c55c6d.png)

### What is expected?
I expect type: 'time' to optimise amount of data it shows in the same way type: 'category' works.

### What is actually happening?
All data points are shown.

---
I tried setting different properties such as 'interval', but none of them had any effect on chart rendering. I could not find any examples that show 'time' series with large amount of data.

**Comment by Ovilia** [comment]
@jaworek Please provide a demo of your example. https://jsfiddle.net/ovilia/n6xc4df3/

**Comment by jaworek** [comment]
Slow version with type "time": https://jsfiddle.net/7tkfcdjr/6/

Fast version with type "category": https://jsfiddle.net/7tkfcdjr/8/

**Comment by Ovilia** [comment]
Can we provide sampling for time axis? @100pah @pissang

**Comment by pissang** [comment]
@jaworek Hi, you can set `symbol: 'none'` to improve draw performance.

**Comment by jaworek** [comment]
@pissang Thank you!

**Comment by tkappenman** [comment]
I am also experiencing this problem when trying to log temperatures over time of several (50+) devices on one graph. Performance improves drastically by setting symbol to 'none', but then I am unable to hover over individual points to check the value. This example uses tooltip type axis, but I need it to work with tooltip type item to check individual points on the graph. Is there a way to get around this performance issue and still be able to use tooltip type 'item'?

**Comment by tchaton** [comment]
Yes, same issue. I have 10k dataset points and it takes 10 seconds on my Mac M1 to re-render this is insane...
