### ISSUE TITLE
SaveAsImage Function cannot save image with full legend when legend has several pages

### ISSUE THREAD

**Issue by hhqq0416** [apache/incubator-echarts#11714]
### Version
4.5.0

### Reproduction link
[https://jsfiddle.net/hhqq0416/q9uw3ob4/3/](https://jsfiddle.net/hhqq0416/q9uw3ob4/3/)

### Steps to reproduce
click download button at the top-right. The downloaded picture file only contains the first page legend. Same result when using getDataURL and generate a pic url and download.

### What is expected?
all legend should be shown.

### What is actually happening?
only legend of current page is shown.

**Comment by pissang** [comment]
Basically the function save image will keep all the current states. If you want to display all legend when doing snapshoting. You can add a custom icon which do following steps.

1. Switch the `legend` type to `plain`
2. Download the image as what https://github.com/apache/incubator-echarts/blob/master/src/component/toolbox/feature/SaveAsImage.js#L54 did.
3. Switch the `legend` type back to `scroll`

**Comment by hhqq0416** [comment]
@pissang Thanks for your suggest. Since there are too many legend items in the canvas, expanding the legend (aka switching to 'plain') will expand the div or add a scroll bar to the canvas. Is there any good alternatives?

**Comment by pissang** [comment]
@hhqq0416 You mean in the HTML page or in the static image. For the previous one, you can use a html `select` element to simulate the `legend`.  For the static image, the only way I can think of is enlarging the canvas.

**Comment by hhqq0416** [comment]
I mean the static image. Thanks @pissang . No further questions, closing this issue.

**Comment by hhqq0416** [comment]
my way of solving this issue: make the wrapper resizable and listen to the resize event. Let the enduser enlarge the pic, show all the legends, and then download
