### ISSUE TITLE
https：//www.echartsjs.com/examples/vendors/ 403 为什么访问不了了 

### ISSUE THREAD

**Issue by dingling001** [apache/incubator-echarts#11720]
### Version
4.0.4

### Steps to reproduce
https：//www.echartsjs.com/examples/vendors/ 403 为什么访问不了了 

### What is expected?
https：//www.echartsjs.com/examples/vendors/ 403 为什么访问不了了 

### What is actually happening?
https：//www.echartsjs.com/examples/vendors/ 403 为什么访问不了了 

---
https：//www.echartsjs.com/examples/vendors/ 403 为什么访问不了了

**Comment by pissang** [comment]
We suggested using CDN links. https://www.jsdelivr.com/package/npm/echarts
