### ISSUE TITLE
data is missing  when rendering pie using dataset format

### ISSUE THREAD

**Issue by greedy747** [apache/incubator-echarts#11735]
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/hq120901/2rfo8vn0/7/](https://jsfiddle.net/hq120901/2rfo8vn0/7/)

### Steps to reproduce
using the following option:
```js
var option = {
          dataset: {
            source: [
              ['日期', '下载量'],
              ['1', 1],
              ['2', 1],
              ['3', 1],
              ['3次以上', 1]
            ]
          },

          series: [{
            type: 'pie'
          }]
        }
```
### What is expected?
the pie should contain 4 items, including '3次以上‘

### What is actually happening?
‘3次以上‘ is not rendered in the pie ，see a demo (https://jsfiddle.net/hq120901/2rfo8vn0/7/)

**Comment by pissang** [comment]
Seems similar to #11419 . @100pah is working on fixing it.
