### ISSUE TITLE
图例自定义icon时能否自动或可设置居中

### ISSUE THREAD

**Issue by B1gF4ceC4t** [apache/incubator-echarts#11734]
### What problem does this feature solve?
图例自定义icon这里设置为一条竖线 `path://M443.733333 0h145.066667v1024H443.733333z` ，显示的时候是明显靠左的，能否自动或者可以配置成居中？

示例：https://gallery.echartsjs.com/editor.html?c=xgxczLxKi&v=3

### What does the proposed API look like?
图例自定义icon居中显示

**Comment by SnailSword** [comment]
可以通过修改path来实现，比如你这里，可以修改成：
`path://M0 0M443.733333 0 h145.066667 v1024 H443.733333z`

**Comment by B1gF4ceC4t** [comment]
好的！感谢！ @SnailSword
