### ISSUE TITLE
Echarts 官网上的例子中wheater(天气)这个单词拼错了（应该是weather）

### ISSUE THREAD

**Issue by hyh888** [apache/incubator-echarts#11741]
### Version
4.5.0

### Steps to reproduce
no reproduce

### What is expected?
https://www.echartsjs.com/examples/zh/editor.html?c=bar-rich-text
Echarts 官网上的例子中wheater(天气)这个单词拼错了（应该是weather）

### What is actually happening?
wheater(天气)这个单词拼错了

**Comment by susiwen8** [comment]
Thanks, could you make a PR to correct it?

**Comment by hyh888** [comment]
10天了，还没有改，如果要是修改代码不知道要多久。公司太大了。

**Comment by pissang** [comment]
谢谢反馈，https://github.com/ecomfe/echarts-examples/commit/bb77d290a01eb60fbf733f36c1c9d642efd41282 已修复

PS：ECharts 是正在 Apache 基金会下孵化的开源项目，不是公司产品
