### ISSUE TITLE
geo world版地图，中国区域没有圈出南沙群岛，地图需要更新

### ISSUE THREAD

**Issue by chenxi1991chenxi** [apache/incubator-echarts#11750]
### Version
4.5.0

### Steps to reproduce
热力图，迁徙图等，任何需要用到地图geo  map= 'world'的图表，查看中国区域，没有圈出南沙群岛

### What is expected?
希望地图能更新，map= 'world' 时，中国区域能圈出南沙群岛

### What is actually happening?
map= 'world' 时的地图，中国区域没有圈出南沙群岛

**Comment by yufeng04** [comment]
Sorry, we no longer maintain the data of map. You are welcome to submit PR for maintenance!
