### ISSUE TITLE
Stacked bar chart is not showing all  series

### ISSUE THREAD

**Issue by kaljak** [apache/incubator-echarts#11762]
### Version
4.5.0

### Steps to reproduce
Go to  https://echarts.apache.org/examples/en/editor.html and use this options:
```
option = {
    "legend": {
        "data": ["Geschlossen","Neu","Zugewiesen"]
        
    },
    "xAxis": {
        "type":"value"
        
    },
    "yAxis": {
        "type": "category"
        
    },
    "series": [
        {
            "name": "Geschlossen",
            "stack": "stack",
            "type": "bar", 
            "data": [4]
        },
        {
            "name": "Neu",
            "stack": "stack",
            "type": "bar", 
            "data": [2]
        },
        {
            "name": "Zugewiesen",
            "stack": "stack",
            "type":"bar",
            "data":[4]
        }
    ]
};

```
### What is expected?
There should be a stacked bar that shows the 3 series with the values 4 - 2 - 4

### What is actually happening?
There is only one stacked bar with the value 4

**Comment by susiwen8** [comment]
It seems that you need to set yAxis data value, and it's length cannot be 0.
`data: ['']`

I'm not sure that data of yAixs is necessary for stack. Let me check.

For the time being, you can use this workaround to solve this problem.

**Comment by yufeng04** [comment]
It's not very clear what you expected！May you can add `yAxis.data: ["Geschlossen","Neu","Zugewiesen"]` and hope this [example](https://www.echartsjs.com/examples/zh/editor.html?c=bar-y-category-stack) helps you!

**Comment by susiwen8** [comment]
@yufeng04 The example Kaljak provides was clearly wrong. Does yAixs.data is needed for stacked charts?

**Comment by yufeng04** [comment]
@susiwen8 Because the type of yAxis is `category`, the `yAixs.data` is needed.

**Comment by susiwen8** [comment]
@yufeng04 Thanks.

**Comment by kaljak** [comment]
Thank you very much
