### ISSUE TITLE
echarts结合高德报错，Cannot read property 'getAMap' of undefined"

### ISSUE THREAD

**Issue by SeanSunPeng** [apache/incubator-echarts#11768]
### Version
3.8.5

### Steps to reproduce

this.echartObj = this.$echarts.init(document.getElementById(this.id));
      this.echartObj.setOption(option);
      console.log(this.echartObj.getModel(),"图层")
      var amap = this.echartObj
        .getModel()
        .getComponent("amap")
        .getAMap();

### What is expected?
bug消失

### What is actually happening?
我始终无法获this.echartObj.getModel().getComponent("amap")，一直为null

---
代码如上，实例化后获取地图实例，之前这个功能我是做完了也没问题，但今日突然报错，我以为是高德KEY过期，但更换后依然存在，之后我将版本回退到之前正常时，依然无法正常显示，我可以确定echarts的版本和高德1.4.4版并无更改，

**Comment by yufeng04** [comment]
Is the `amap` component provided by the plug-in? Could you provide a reproducible demo？
