### ISSUE TITLE
cartesian heatmap not exists

### ISSUE THREAD

**Issue by suraj740** [apache/incubator-echarts#11771]
<img width="598" alt="Screenshot 2019-12-02 at 10 09 17 PM" src="https://user-images.githubusercontent.com/24958883/69977481-e282a080-1550-11ea-885c-330f92575e65.png">
### Version
4.4.0

### Steps to reproduce
i have updated echarts from version 4.1.0 to 4.4.0, but now cartesianHeatmap is not present in heatmap type and i am getting error as series.cartesianHeatmap not exists.

### What is expected?
cartesianHeatmap was present in version 4.1.0

### What is actually happening?
Component series.cartesianHeatmap not exists

**Comment by yufeng04** [comment]
I didn't find `series.cartesianHeatmap` on the document. Could you provide a reproducible demo?
