### ISSUE TITLE
Time axis chart issue with data zoom and updating data

### ISSUE THREAD

**Issue by dileepyelleti** [apache/incubator-echarts#11787]
### Version
4.5.0

### Reproduction link
[https://jsfiddle.net/6q287hak/3/](https://jsfiddle.net/6q287hak/3/)

### Steps to reproduce
Click 'source 1' button to load first set of data in chart
Change only starting point of chart by zooming using slider (Can also click on 'Change Time' button)
Click on 'Source 2' button to load second set of data
Chart will get messy at end. (On zooming using slider again it will get rectified)

### What is expected?
Chart should plot as expected even after zooming and loading another data source

### What is actually happening?
Chart is becoming messy

**Comment by dileepyelleti** [comment]
@yufeng04 
Is it a real bug with echarts or is there some workaround to solve this?

**Comment by dileepyelleti** [comment]
@Ovilia @yufeng04 
Hi
Can you please let me know if there is any quick fix or workaround for this issue. We are struck with this. So please let me know if there is any.

**Comment by pissang** [comment]
Hi @dileepyelleti 

We are trying to solve the issue. You can disable `animation` temporary. https://jsfiddle.net/pissang/b65ufgn8/1/

**Comment by dileepyelleti** [comment]
Hi @pissang 
Thank you for your suggestion. This solves my issue for now without animation.

**Comment by dileepyelleti** [comment]
@Ovilia 
It is still an issue that needs a fix if we need animation
