### ISSUE TITLE
Bug: download svg image with toolbox

### ISSUE THREAD

**Issue by ISBN9527** [apache/incubator-echarts#11781]
### Version
4.5.0

### Steps to reproduce
随便一个示例，用SVG渲染，下载图片格式为.PNG无法打开

### What is expected?
我希望打开

### What is actually happening?
但是实际无法打开

**Comment by ISBN9527** [comment]
打开svg格式报错

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/70196597-36091000-1744-11ea-870e-75c5438e5a16.png)

**Comment by pissang** [comment]
@ISBN9527 我们会在后面版本支持 svg 的下载

**Comment by Ovilia** [comment]
Fixed.
