### ISSUE TITLE
桑基图 单个节点数值过大会导致溢出

### ISSUE THREAD

**Issue by 462937186** [apache/incubator-echarts#11784]
### Version
4.5.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xvJYS-Nge&comment=0](https://gallery.echartsjs.com/editor.html?c=xvJYS-Nge&comment=0)

### Steps to reproduce
设置多个target指向单个节点造成单个节点value变大

### What is expected?
不会溢出，或者提供设置节点显示最大高度的api

### What is actually happening?
溢出

**Comment by SnailSword** [comment]
我没太理解你说的溢出的意思，如果溢出指的是显示不全的话，把容器调大点就可以显示全了~

![image](https://user-images.githubusercontent.com/19756301/70144018-06bcb980-16d8-11ea-8f1e-d95b96101ebb.png)

**Comment by 462937186** [comment]
但是如果宽高是固定的情况呢，目前单个节点的高度是按数值的大小计算的，在数值不确定的情况下是会出现显示不全的

**Comment by deqingli** [comment]
@462937186  Do you mean overlapping of the nodes? I think this issue may be the same problem with #6792
