### ISSUE TITLE
showLoading align center

### ISSUE THREAD

**Issue by fox19920726** [apache/incubator-echarts#11790]
### Version
4.5.0

### Reproduction link
[https://jsfiddle.net/mqbaj76r/2/](https://jsfiddle.net/mqbaj76r/2/)

### Steps to reproduce
直接就能看到调用showLoading的时候文字没有左右居中

### What is expected?
希望showLoading的文字左右居中

### What is actually happening?
调用showLoading时候的文字没有左右居中

---
没有了

**Comment by yufeng04** [comment]
The color you set is '#ffffff', so you can not see the loading animation！

**Comment by pissang** [comment]
@fox19920726 @yufeng04 现在是图形居中，可能在文字长的时候效果并不是很好，我们在下个版本中优化一下

**Comment by fox19920726** [comment]
啊啊啊啊啊啊啊啊！！！！！这个问题啥时候能优化呀！！！！！等得焦急，哈哈哈哈哈哈哈

**Comment by fox19920726** [comment]
> @fox19920726 @yufeng04 现在是图形居中，可能在文字长的时候效果并不是很好，我们在下个版本中优化一下

啊啊啊啊啊啊啊啊！！！！！这个问题啥时候能优化呀！！！！！等得焦急，哈哈哈哈哈哈哈

**Comment by fox19920726** [comment]
@pissang 啊啊啊啊啊啊啊啊！！！！！这个问题啥时候能优化呀！！！！！等得焦急，哈哈哈哈哈哈哈

**Comment by yufeng04** [comment]
@fox19920726 会在最近的4.8.0优化
