### ISSUE TITLE
Does EChartOption.backgroundColor only support string?

### ISSUE THREAD

**Issue by lizhongzhen11** [apache/incubator-echarts#11795]
### Version
4.5.0

### Steps to reproduce
I use typescript with echarts. I want to copy this case: https://gallery.echartsjs.com/editor.html?c=xEyDk1hwBx，however,  it throws error. I lookup the index.d.ts,  the backgroundColor only support string！But, in the https://www.echartsjs.com/zh/option.html#backgroundColor，tells me also support object to achieve gradient color. How can i use gradient color?

### What is expected?
How can i use gradient color?

### What is actually happening?
I don't know how to do

**Comment by yufeng04** [comment]
Maybe you can refer to this [article](https://www.cnblogs.com/catherinezyr/p/10768399.html) to solve this issue!

**Comment by lizhongzhen11** [comment]
@yufeng04 
Thankyou very much! It does effect!
But, in order to solve this issue, i have to add type assertion in many places. 
Ok, Let's do that first.
