### ISSUE TITLE
axisLabel.align issue

### ISSUE THREAD

**Issue by naydog** [apache/incubator-echarts#11805]
### Version
4.2.1

### Steps to reproduce
1. Create a chart with any type cartesian coordinate system
2. Set xAxis.axisLabel.align to left

### What is expected?
Axis labels are to the left of axis ticks.

### What is actually happening?
It looks that axis labels are to the right of axis ticks.

---
it's more intuitive if "align:left" means labels are to the left of axis ticks. Our testers and po have raised defects about this.

**Comment by susiwen8** [comment]
Yes, I have identified the bug

**Comment by pissang** [comment]
I can't reproduce on the lastest version 4.5.0

@susiwen8 

The calculation in the zrender has no problem. By default the text is set to align left. If the align is changed to right. It should be moved to left by `width` pixels.
