### ISSUE TITLE
[DRAFT] ECharts v5.0 Feature Discussion

### ISSUE THREAD

**Issue by Ovilia** [apache/incubator-echarts#11814]
ECharts v5.0 is the next major version that is going to be released in 2020.

Here is the list of the primary features that we are going to provide or fix in this release.

## Flexibility and Customization

- [ ] Support mouse events on components @Ovilia 
- [ ] Enhancement of custom series @100pah #11869 #11870
- [ ] More states in addition to current normal / emphasis

## Interaction

- [ ] Enhancing selection interaction and API  @pissang 
- [ ] Fade out other series when one is highlighted

## Components

- [ ] Auto layout for labels for better display @pissang 
- [ ] Auto layout for components to avoid overlapping @Ovilia 
- [ ] Enhance time axis @100pah 

## New Series

- [ ] Area range charts

## Other Enhancement

- [ ] fontSize support `rem`

**Comment by GaspardC** [comment]
would be nice to have the possibility to add custom and mutliple html "tooltips"

**Comment by pissang** [comment]
https://github.com/apache/incubator-echarts/projects/6
