### ISSUE TITLE
折线图series中是否可以添加large属性，开启大数据优化

### ISSUE THREAD

**Issue by fanlinhao0811** [apache/incubator-echarts#11810]
### What problem does this feature solve?
折线图series中是否像散点图一样添加large属性，开启大数据优化，当折线图渲染百万级数据时，使用datazoom，会很卡顿，散点图中有一个large属性，这边折线图是否可以也加上

### What does the proposed API look like?
series:[{
type: 'line',
large: false
}]

**Comment by zimutao** [comment]
看现在api，折线没有large，有采样。
