### ISSUE TITLE
 Calendar coordinate system seem to does not support dataset

### ISSUE THREAD

**Issue by luguokong** [apache/incubator-echarts#11812]
### Version
4.5.0

### Steps to reproduce
data format like this  [{data:'2019-12-14', value:111}]  seem to can not display in  Calendar coordinate system

### What is expected?
 Calendar coordinate system support dataset

### What is actually happening?
 Calendar coordinate system seem to does not support dataset

**Comment by Ovilia** [comment]
Please provide a full demo of your requirement: https://jsfiddle.net/ovilia/n6xc4df3/
