### ISSUE TITLE
希望地图增加瓦片服务支持

### ISSUE THREAD

**Issue by yuanqiangxie** [apache/incubator-echarts#11816]
### What problem does this feature solve?
如果有的地图数据很大的话，加载很慢，如果能支持瓦片服务的话就可以避免这个问题。

### What does the proposed API look like?
.registerMap('tilesMap', tilesMap, options);

**Comment by pissang** [comment]
瓦片地图可以使用第三方地图服务的扩展，比如百度地图，leaflet 等等
