### ISSUE TITLE
How can i get the "grid" gap distance when i set "containLabel" is true?

### ISSUE THREAD

**Issue by moonlitusun** [apache/incubator-echarts#11824]
### What problem does this feature solve?
When I need two or more grids to overlap, there will always be a misalignment, because I don't know how wide the grid's dynamic distance is when i set "containLabel" is true ,  I am sure I need this distance value very much。

### What does the proposed API look like?
work

**Comment by Ovilia** [comment]
What do you mean by grid? If it's [grid](https://echarts.apache.org/en/option.html#grid), then it's [grid.left](https://echarts.apache.org/en/option.html#grid.left), [grid.right](https://echarts.apache.org/en/option.html#grid.right), [grid.top](https://echarts.apache.org/en/option.html#grid.top), [grid.bottom](https://echarts.apache.org/en/option.html#grid.bottom).

**Comment by moonlitusun** [comment]
Oh.Thank you for your reply, and then give an example. . . I mean I set grid.right = 100 for the first grid. Then I set containlabel = true. This is fine, but I have a second grid. I want to align with the first grid, but first The distance of the grid is actually not 100. I set the containlabel, so how much should I set, and can I get this accurate value?


            
            
                
                    
                            
                                
                            
                            
                                Roc Sun
                            
                    
                        
                            
                                    邮箱：moonlitusun@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 12/13/2019 11:15, Ovilia wrote: What do you mean by grid? If it's grid, then it's grid.left, grid.right, grid.top, grid.bottom.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-echarts/issues/11824?email_source=notifications\u0026email_token=AFPAWNXC2D37REC3FBXXHJTQYL46BA5CNFSM4JY2OCXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGYYRVQ#issuecomment-565283030",
"url": "https://github.com/apache/incubator-echarts/issues/11824?email_source=notifications\u0026email_token=AFPAWNXC2D37REC3FBXXHJTQYL46BA5CNFSM4JY2OCXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGYYRVQ#issuecomment-565283030",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by karma2014** [comment]
@moonlitusun Please show me your code in CodePen or gallery。

**Comment by moonlitusun** [comment]
https://codesandbox.io/s/echarts-vjgm7

Yeah, this is a demo, I just want to know how much the left of grid2 should be set to align with grid1, because grid1 has containLabel, the distance is uncertain and I cannot get. thx

**Comment by moonlitusun** [comment]
@Ovilia
