### ISSUE TITLE
设置label的position定位问题：数据值有正有负，如何实现正值position设置为top，负值设置为bottom.求教

### ISSUE THREAD

**Issue by lishaoh** [apache/incubator-echarts#11826]
### What problem does this feature solve?
label的position可以根据柱状图高度自动显示在合适位置，否则当柱状图高度较低时，label显示不完美

### What does the proposed API look like?
```js
{
name: '柱状图',
type: 'bar',
barWidth: 40,
z: 10,
data: [1,2,43]
itemStyle: {
color: '#00a0e9',
},
label: {
show: true,
color: '#666',
position:  val => 1>0? 'top' : 'bottom'
}
}
```

**Comment by karma2014** [comment]
@lishaoh Please show your problem in Gallery and show the Gallery url，thank you.

**Comment by SnailSword** [comment]
参考这个：https://www.echartsjs.com/examples/zh/editor.html?c=bar-negative2
可以在自己的代码里动态生成position。
