### ISSUE TITLE
饼图的Label中的position设置为“inner”时，设置rotate属性为90度时，label是沿着沿着圆心线向外扩展

### ISSUE THREAD

**Issue by ISBN9527** [apache/incubator-echarts#11834]
### What problem does this feature solve?
饼图legend特别多以及视觉样式上的美观

### What does the proposed API look like?
期望修改他的基准定位

**Comment by ISBN9527** [comment]
我希望他的label是沿着箭头方向

![image](https://user-images.githubusercontent.com/30942709/70602900-65ca8300-1c30-11ea-9da5-01593a38dd87.png)

**Comment by ISBN9527** [comment]
@pissang 期待大佬的回复

**Comment by ISBN9527** [comment]
不好意思，自己看了下文档，已解决，sorry，打扰了

**Comment by Youmyin** [comment]
> 不好意思，自己看了下文档，已解决，sorry，打扰了

同样的需求，请问是怎样解决的呀？
