### ISSUE TITLE
Radar chart: some point are outside of chart

### ISSUE THREAD

**Issue by susiwen8** [apache/incubator-echarts#11832]
### Version
4.5.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xzSzF77sg&v=1](https://gallery.echartsjs.com/editor.html?c=xzSzF77sg&v=1)

### Steps to reproduce
Open gallery

### What is expected?
All points is inside of chart

### What is actually happening?
Some point are outside of chart

**Comment by susiwen8** [comment]
I think we should use `Math.ceil` instead of `Math.round` at [here](https://github.com/apache/incubator-echarts/blob/master/src/coord/radar/Radar.js#L234)

**Comment by pissang** [comment]
@susiwen8 Thanks! Schedule this into version 4.7.0. Will review the code ASAP
