### ISSUE TITLE
Tree JSON format

### ISSUE THREAD

**Issue by al1020119** [apache/incubator-echarts#11835]
![image](https://user-images.githubusercontent.com/9606161/70605077-c065de00-1c34-11ea-8957-e57f699ac5b8.png)

Excuse me, where can I get this JSON, or the return format of this JSON

**Comment by ed2050** [comment]
I have same problem.  This issue is still open.

**Comment by fersrm** [comment]
Para obtener los JSON hagan un "console.log(ROOT_PATH)," y a la ruta que les da en consola le agregan lo que está en el +.
por lo general está en la ruta de ROOT_PATH : https://echarts.apache.org/examples
