### ISSUE TITLE
Where can I get echarts installation and demo with typescript?

### ISSUE THREAD

**Issue by Monali-ITT** [apache/incubator-echarts#11848]
### Version
4.4.0

### Steps to reproduce
NA

### What is expected?
Can anyone provide echarts installation and  demo created with  typescript?

### What is actually happening?
I am trying  to install echarts typescript version  from  below link https://www.npmjs.com/package/@types/echarts/v/4.1.5.
(with npm ).
But it is not available in node modules directory.It is present in package.json

**Comment by ghaefele** [comment]
There is no echarts-TypeScript version. Your link points to [type definitions](https://definitelytyped.org/) for echarts. If you install these types with `npm install --save-dev @types/echarts` then you should see `"@types/echarts": "^4.4.1",` (4.4.1 = current version at the moment) in your package.json and you can see the echart-types within the @types folder of the node modules.
If you search the internet for echarts and TypeScript you will get some good starting points (react, angular, vue...).

**Comment by susiwen8** [comment]
@ghaefele current version is 4.4.2 now, just update 2 days ago.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40984

**Comment by Ovilia** [comment]
If you use ECharts in TypeScript project, try this:
```js
npm install typings echarts --global
npm install @types/echarts --save
```
Then import in the files you wish to use ECharts:
```js
import * as echarts from 'echarts';
```
Here's a Chinese blog post about it: http://zhangwenli.com/blog/2017/08/29/echarts-with-ionic/#%E5%9C%A8-typescript-%E4%B8%AD%E5%BC%95%E5%85%A5-echarts

**Comment by Monali-ITT** [comment]
Thank you for reply. Can you please provide working demo of treemap in typescript?

**Comment by Ovilia** [comment]
@Monali-ITT JavaScript demo should work fine with ts: https://echarts.apache.org/examples/zh/index.html#chart-type-treemap

**Comment by Monali-ITT** [comment]
Thank you

**Comment by tmtron** [comment]
Hint: the [typed-install package](https://www.npmjs.com/package/typed-install) makes installing js libs that have typescript-definitions easier

**Comment by Ovilia** [comment]
@Monali-ITT If this solves your problem. Please close the issue. Thanks.

**Comment by Monali-ITT** [comment]
Yes.resolved.Thank you.

**Comment by brt-han-mai** [comment]
> If you use ECharts in TypeScript project, try this:
> 
> ```js
> npm install typings echarts --global
> npm install @types/echarts --save
> ```
> 
> Then import in the files you wish to use ECharts:
> 
> ```js
> import * as echarts from 'echarts';
> ```
> 
> Here's a Chinese blog post about it: http://zhangwenli.com/blog/2017/08/29/echarts-with-ionic/#%E5%9C%A8-typescript-%E4%B8%AD%E5%BC%95%E5%85%A5-echarts

This totally defeat the advantage of the typescript. Down voted
