### ISSUE TITLE
河流图x轴与数据不对应

### ISSUE THREAD

**Issue by ISBN9527** [apache/incubator-echarts#11846]
### Version
4.5.0

### Steps to reproduce
河流图--->x轴时间不连续的情况下-->tooltip

### What is expected?
希望对应上

### What is actually happening?
没对应

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/70786204-1074aa00-1dc7-11ea-908c-3b9527fdd2a5.png)

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/70786255-2da97880-1dc7-11ea-8e42-d4a6c00e0d25.png)

**Comment by karma2014** [comment]
@ISBN9527  Please show your code in gallery ，like https://gallery.echartsjs.com/editor.html?c=xhmv-1o6XS

**Comment by ISBN9527** [comment]
@karma2014 [demo链接](https://gallery.echartsjs.com/editor.html?c=xaFP7rcNQ&v=1)

**Comment by ISBN9527** [comment]
请大佬解惑

**Comment by ISBN9527** [comment]
@Ovilia

**Comment by Ovilia** [comment]
怎么看是有问题？

**Comment by ISBN9527** [comment]
我希望多余的时间不要出现，只出现series里data中的想对应的时间

**Comment by ISBN9527** [comment]
@Ovilia

**Comment by deqingli** [comment]
![image](https://user-images.githubusercontent.com/13548221/71437934-9b8e6200-272e-11ea-9c60-4da114cacc84.png)

hi @ISBN9527, from the picture I can't understand what is the extra time you mean?

**Comment by deqingli** [comment]
Do you mean that you only want to show the series data which you hovered on?

**Comment by ISBN9527** [comment]
图中打箭头的两根线，其中2019/04/04在我的数据中并没有提供，这样会给用户带来歧义。

![image](https://user-images.githubusercontent.com/30942709/71459987-ed91bf00-27e4-11ea-992f-076a1cdd909f.png)

**Comment by 100pah** [comment]
请设置：
```js
splitLine: {
    show: false,
    ...
}
```
则 2019/04/04 对应的那条纵向的虚线不会再出现。

**Comment by ISBN9527** [comment]
我尝试用type: ” category "以及data解决了，谢谢大佬们！
