### ISSUE TITLE
在横向栏数据动态渲染 排序中，设置barBorderRadius，由于排序了，数据变动会影响各个柱子错位！ 

### ISSUE THREAD

**Issue by wangzoyang** [apache/incubator-echarts#11851]
### Version
3.7.1

### Steps to reproduce
在横向栏数据动态渲染 排序中，设置barBorderRadius，由于排序了，数据变动会影响各个柱子错位！ 

### What is expected?
数据变动不会影响各个柱子位置！ 

### What is actually happening?
数据变动后，各个柱子错位！

**Comment by wangzoyang** [comment]
将barBorderRadius属性删除就不会发生此现象，此属性加上动态数据的渲染会出现渲染有误

**Comment by Ovilia** [comment]
Please provide a simple demo https://gallery.echartsjs.com/editor.html
