### ISSUE TITLE
Nulls are connected when using sampling

### ISSUE THREAD

**Issue by kevinvde** [apache/incubator-echarts#11857]
### Version
4.4.0

### Steps to reproduce
Turn sampling on for a line serie.
Do not connect nulls

### What is expected?
Nulls are never connected

### What is actually happening?
Nulls are connected until you zoom in far enough
![image](https://user-images.githubusercontent.com/829822/70897630-4dbd7f80-1ff3-11ea-9bff-d7be277c3162.png)
![image](https://user-images.githubusercontent.com/829822/70897652-59a94180-1ff3-11ea-81e6-b720711847bb.png)

**Comment by pissang** [comment]
Can't reproduce your issue. Can you provide your option?

**Comment by kevinvde** [comment]
[anomalychart.txt](https://github.com/apache/incubator-echarts/files/3972825/anomalychart.txt)

Hi, i've added my option in attachment. I can reproduce it by adding it into the editor: https://echarts.apache.org/examples/en/editor.html

**Comment by deqingli** [comment]
@kevinvde  I can't reproduce with your txt file, please provide a demo link in our [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), or codepen, jsfiddle, thanks.
