### ISSUE TITLE
在arcgis js里使用echarts遇到coordinateSystem的问题

### ISSUE THREAD

**Issue by heroghost** [apache/incubator-echarts#11861]
### Version
4.5.0

### Steps to reproduce
var options={
        	grid: [
        		{lat:35,lon:103, width: '38px', height: '38px'}
        	],
        	xAxis: [
        		{gridIndex: 0, type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']},
        		{gridIndex: 1, type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']},
        		{gridIndex: 4, min: 0, max: 20}
        	],
        	yAxis: [
        		{gridIndex: 0, type: 'value'},
        		{gridIndex: 1, type: 'value'},
        		{gridIndex: 4, min: 0, max: 15}
        	],
          coordinateSystem: "cartesian2d",
        	series: [
        		{
        			name: 'bar-simple',
        			type: 'bar',
        			xAxisIndex: 0,
        			yAxisIndex: 0,
        			data: [120, 200, 150, 80, 70, 110, 130],
        		}
        	]
      }；
     var barchart = echarts.init(document.getElementById("chartId_1"));
     barchart.setOption(option);

### What is expected?
显示出条状图

### What is actually happening?
报错：
Uncaught TypeError: Cannot read property 'coordinateSystem' of undefined
    at Object.layout (cartesianAxisHelper.js?e31a:54)
    at ExtendedClass.render (CartesianAxisView.js?b38f:76)
    at eval (echarts.js?21c7:1427)
    at Array.forEach (<anonymous>)
    at each (util.js?fe0c:300)
    at renderComponents (echarts.js?21c7:1425)
    at render (echarts.js?21c7:1411)
    at ECharts.update (echarts.js?21c7:838)
    at ECharts.echartsProto.setOption (echarts.js?21c7:411)

**Comment by susiwen8** [comment]
I assume you want to draw multiple charts, instead of one.

This example may help you

https://www.echartsjs.com/examples/en/editor.html?c=scatter-anscombe-quartet

**Comment by susiwen8** [comment]
Due to inactive of this issue, close it first.
