### ISSUE TITLE
title.backgroundColor 设置标题背景色不起作用

### ISSUE THREAD

**Issue by Ryan-Keith** [apache/incubator-echarts#11874]
### Version
4.1.0-rc.0

### Steps to reproduce
https://www.echartsjs.com/examples/zh/editor.html?c=pie-legend  在官网示例下，title下设置backgroundColor:'#000'

### What is expected?
标题栏背景变为黑色

### What is actually happening?
无颜色变化

---
亲试了很多示例，这个属性设置不生效，忘查看修改

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/blob/master/src/component/title.js#L229

`subPixelOptimize` is been set as `true`,

**Comment by susiwen8** [comment]
Is necessary to set `subPixelOptimize ` true in `title`? @pissang @100pah
