### ISSUE TITLE
X轴不会均匀分布

### ISSUE THREAD

**Issue by gongfuxiaocai** [apache/incubator-echarts#11873]
### Version
4.4.0

### Steps to reproduce
配置项如下：
option = {
    xAxis: {
        type: 'category',
        scale: true,
        data: [1, 2, 5, 10, 11, 13, 20]
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};

### What is expected?
期望X轴能像Y轴一样自动分布

### What is actually happening?
实际展示的一个X对应一个点，X轴展示的没达到均匀分布

![image](https://user-images.githubusercontent.com/20085964/71144017-88275680-2257-11ea-95d8-39641dbd8a8c.png)

**Comment by yanheSu** [comment]
```
option = {
xAxis: {
type: 'value',
scale: true,
},
yAxis: {
type: 'value'
},
series: [{
data: [[1, 820], [2, 932], [5, 901], [10, 934], [11, 1290], [13, 1330], [20, 1320]],
type: 'line'
}]
};
```
这个意思？

**Comment by gongfuxiaocai** [comment]
不是的哦，x轴的type是category哦；如果x轴的type是value，y轴的position会把文字定位到右边，但是刻度还在左边；

代码如下`option = {
xAxis: {
type: 'value',

scale: true,

splitLine: {
    show: false,
},
},
yAxis: {
type: 'value',
splitLine: {
    show: false,
},
position: 'right',
axisTick: {
    inside: false,
},
},
series: [{
data: [[1, 820], [2, 932], [5, 901], [10, 934], [11, 1290], [13, 1330], [20, 1320]],
type: 'line'
}]
};`

效果图如下
![image](https://user-images.githubusercontent.com/20085964/71152961-d9910f00-2272-11ea-95c8-8df03bc0912e.png)

**Comment by yanheSu** [comment]
一定要保持轴类型是category么
由于将x轴类型设置为了数值轴，使y轴的轴线及刻度跟随x轴的零点位置了
如果不希望y轴轴线与刻度跟随零点，可设置`yAxis.axisLine.onZero=false`。
试一试下面的
```
var option = {
    xAxis: {
        type: 'value',
        
        scale: true,
        
        splitLine: {
        show: false,
        },
        onZero: false
    },
    yAxis: [
        {
            type: 'value',
            position: 'right',
            axisLine: {
                onZero: false
            }
        }],
    series: [{
        data: [[1, 820], [2, 932], [5, 901], [10, 934], [11, 1290], [13, 1330], [20, 1320]],
        type: 'line'
    }]
}
```

**Comment by gongfuxiaocai** [comment]
> 一定要保持轴类型是category么
> 由于将x轴类型设置为了数值轴，使y轴的轴线及刻度跟随x轴的零点位置了
> 如果不希望y轴轴线与刻度跟随零点，可设置`yAxis.axisLine.onZero=false`。
> 试一试下面的
> 
> ```
> var option = {
>     xAxis: {
>         type: 'value',
>         
>         scale: true,
>         
>         splitLine: {
>         show: false,
>         },
>         onZero: false
>     },
>     yAxis: [
>         {
>             type: 'value',
>             position: 'right',
>             axisLine: {
>                 onZero: false
>             }
>         }],
>     series: [{
>         data: [[1, 820], [2, 932], [5, 901], [10, 934], [11, 1290], [13, 1330], [20, 1320]],
>         type: 'line'
>     }]
> }
> ```

谢谢🙏，可以了
