### ISSUE TITLE
希望能够支持name相同的两个图例

### ISSUE THREAD

**Issue by brohan1705** [apache/incubator-echarts#11884]
### What problem does this feature solve?
在涉及手机号等需要做用户隐私保护业务场景下，可能会存在重复的name值。
例如 123-4567-8900 和 123-7654-8900两个不同手机号，为避免用户个人信息泄露，后台接口返回给浏览器的结果已被处理为123-****-8900这种格式，这种情况会出现重复的name值，此时图表无法正常显示。

### What does the proposed API look like?
对legend.data[i]增加id或其他作为可key的属性，默认值为legend.data[i].name，  
同事series[i].data[i]也增加对应的属性。  
期望使用legend配置格式如下:  
```
legend: {
    data: [{
        name: 'Name1',
        id: 'key1'
    }]
}
```

**Comment by 100pah** [comment]
可以看到您的图表的大概样子么？

**Comment by sunui** [comment]
自己生成唯一 id 作为 name，然后用 legend.formatter 可以达到你想要的效果哦

**Comment by brohan1705** [comment]
> 自己生成唯一 id 作为 name，然后用 legend.formatter 可以达到你想要的效果哦

多谢，我想应该是可以，我试一下
