### ISSUE TITLE
datazoom component will trigger brushselected event.

### ISSUE THREAD

**Issue by HHHui** [apache/incubator-echarts#11898]
### Version
4.5.0

### Reproduction link
[https://codepen.io/Cabage/pen/mdyweXX](https://codepen.io/Cabage/pen/mdyweXX)

### Steps to reproduce
1. click ‘lineX’ brush
2. use brush on chart. 在图上框一下

### What is expected?
datazoom will not trigger brushselected event.

### What is actually happening?
datazoom will brushselected event.

---
我想实现的是用brush来框选想要的数据，然后dispatch datazoom event，完成数据过滤.
但是datazoom自己会触发brushselected event. 然后就死循环了.
datazoom是故意这样设计的吗？ 有什么其他办法能让让我.

I want to use brush to implement data filter on line chart.

So i use brushselected event to get coordRange, then dispatch datazoom event to filter data.

Then i get Maximum call stack size exceeded error. because datazoom will dispatch brushselected event itself.

So brushselected -> datazoom -> brushselected. I don't know is this by design or a bug.

**Comment by 100pah** [comment]
Yes it's by design.

`brushselected` will be triggered when dispatchAction called, or use do brush behavior. But this event will not be triggered in setOption. [1]

Probably you can use `toolbox.dataZoom` to meet your requirement.

[1] https://echarts.apache.org/en/api.html#events.brushselected

**Comment by HHHui** [comment]
toolbox.dataZoom跟我想实现的东西完全一样，是我看文档没注意。
> 框选型数据区域缩放组件（dataZoomSelect）：提供一个选框进行数据区域缩放。即 toolbox.feature.dataZoom，配置项在 toolbox 中。
