### ISSUE TITLE
Error when zoom geo programatically

### ISSUE THREAD

**Issue by JasonSubMara** [apache/incubator-echarts#11895]
### Version
4.5.0

### Steps to reproduce
主要关联代码：
```js
geo: {
  zoom: 1,
  roam: 'move'
}
```
之后通过修改geo里面的zoom ,
地图上的散点实时渲染至对应缩放区域，而背景地图需要在地图上移动一下才渲染至对应位置

### What is expected?
解决该问题并告知原因

### What is actually happening?
地图上的散点实时渲染至对应缩放区域，而背景地图需要在地图上移动一下才渲染至对应位置

**Comment by JasonSubMara** [comment]
贴图描述:
![反馈1](https://user-images.githubusercontent.com/30927318/71344184-d19bdc80-259c-11ea-9e25-9dc7ad6135d5.png)
![反馈2](https://user-images.githubusercontent.com/30927318/71344185-d2347300-259c-11ea-90e1-9714caf13889.png)

**Comment by 100pah** [comment]
It is a bug.

**Comment by 21paradox** [comment]
目前可以通过手动设置dirty暂时解决，期待官方尽快修复
echartInstance._componentsViews[index]._mapDraw._controllerHost.target.__dirty = true;

**Comment by JasonSubMara** [comment]
> 目前可以通过手动设置dirty暂时解决，期待官方尽快修复
> echartInstance._componentsViews[index]._mapDraw._controllerHost.target.__dirty = true;

此项设置是在外层修改还是在series内设置？

**Comment by 21paradox** [comment]
> > 目前可以通过手动设置dirty暂时解决，期待官方尽快修复
> > echartInstance._componentsViews[index]._mapDraw._controllerHost.target.__dirty = true;
> 
> 此项设置是在外层修改还是在series内设置？

就是在setOption之前手动改下__dirty变量

**Comment by JasonSubMara** [comment]
> > > 目前可以通过手动设置dirty暂时解决，期待官方尽快修复
> > > echartInstance._componentsViews[index]._mapDraw._controllerHost.target.__dirty = true;
> > 
> > 
> > 此项设置是在外层修改还是在series内设置？
> 
> 在外层修改。就是在setOption之前手动改下__dirty变量
![image](https://user-images.githubusercontent.com/30927318/71703926-51823c00-2e12-11ea-984e-ae094c434b5a.png)

**Comment by JasonSubMara** [comment]
对的吧？

**Comment by 21paradox** [comment]
> 对的吧？

index要改成你对应的geo组件的那个...

**Comment by alex2wong** [comment]
I will take a look this issue later.

**Comment by alex2wong** [comment]
fixed in https://github.com/apache/incubator-echarts/pull/12340 by @Ovilia
