### ISSUE TITLE
缩放地图时散点位置不变

### ISSUE THREAD

**Issue by xiao11lang** [apache/incubator-echarts#11932]
### Version
4.5.0

### Steps to reproduce
1.在地理坐标系中绘制城市位置散点图
2.使用webpack打包，并将打包后的资源托管在服务器上
3.打开地图缩放地图

### What is expected?
散点位置会随着缩放改变

### What is actually happening?
散点的位置相对屏幕始终不变，而不是在地图上某个位置固定

**Comment by xiao11lang** [comment]
补充一点，打包之前的表现是正常的，打包之后就不正常

**Comment by 100pah** [comment]
Could we have more info: the executable `option`, the echarts packed by `webpack` to reproduce the issue?

**Comment by xiao11lang** [comment]
> Could we have more info: the executable `option`, the echarts packed by `webpack` to reproduce the issue?

抱歉，之前描述的重现步骤是有问题的，今天重新看了下是因为散点图中的节点数目太多导致在缩放时位置不同步

**Comment by pissang** [comment]
@xiao11lang Hi, you can try to disable the animation.

**Comment by xiao11lang** [comment]
> @xiao11lang Hi, you can try to disable the animation.

I tried, but it does not work. I tested it, only when the number of nodes exceeds 3000 , the problem will appear

**Comment by susiwen8** [comment]
> > @xiao11lang Hi, you can try to disable the animation.
> 
> I tried, but it does not work. I tested it, only when the number of nodes exceeds 3000 , the problem will appear

3000? Sounds like `progressiveThreshold` problem

**Comment by xiao11lang** [comment]
I didn't set progressiveThreshold, finally I solve this problem by set the value of the large option to true

**Comment by xiao11lang** [comment]
> > > @xiao11lang Hi, you can try to disable the animation.
> > 
> > 
> > I tried, but it does not work. I tested it, only when the number of nodes exceeds 3000 , the problem will appear
> 
> 3000? Sounds like `progressiveThreshold` problem

I didn't set progressiveThreshold, finally I solve this problem by set the value of the large option to true
