### ISSUE TITLE
graph force 设置指定坐标

### ISSUE THREAD

**Issue by sj15652194049** [apache/incubator-echarts#11930]
### What problem does this feature solve?
想自己开发一个流程图，发现咱们的force的坐标设置了和没设置一样，希望可以设置xy之后他始终在这个位置上，而不是添加一个节点别的节点位置全都变了。

### What does the proposed API look like?
怎么样都可以

**Comment by 100pah** [comment]
`force layout` calculate the positions automatically. 
If specify `x,y`, probably we should not use force layout.

**Comment by sj15652194049** [comment]
> `force layout`自动计算位置。
> 如果指定`x,y`，则可能不应该使用强制布局。

那怎么布局呢？指定布局，还要可以拖拽，关系连线。echarts能做到吗？

**Comment by alex2wong** [comment]
力导向图，本身就是模拟电荷之间的运动，最后稳定下来。是全自动计算的，拖拽会重新进行自动计算，会影响其他节点的布局。参考：
https://www.echartsjs.com/zh/option.html#series-graph.layout

如果制作流程图，应该用 layout: 'none', 这样设置的 xy 才有用。Echarts graph 内置的节点拖拽只对 force layout 管用（https://www.echartsjs.com/zh/option.html#series-graph.draggable）。你得自己监听鼠标拖拽事件，重新计算节点的 xy，修改赋值即可 @sj15652194049
