### ISSUE TITLE
series.lines.label.backgroundColor stop working after setting lineHeight

### ISSUE THREAD

**Issue by myshzzx** [apache/incubator-echarts#11940]
### Version
4.5.0

### Steps to reproduce
see this 
https://gallery.echartsjs.com/editor.html?c=x0318RjWm&v=1

### What is expected?
lines label has yellow background

### What is actually happening?
lines label has transparent background

**Comment by susiwen8** [comment]
This is not a bug, because lineHeight's value you have set was too small.  Try bigger number like 10 or 20.
