### ISSUE TITLE
Axis label being outside of the canvas

### ISSUE THREAD

**Issue by wuwenyuan111** [apache/incubator-echarts#11944]
### Version
4.6.0

### Steps to reproduce
关键配置：
```
grid: {
		// 网格容器距离上下左右侧的距离
		top: 30,
		right: 5,
		bottom: 30,
		left: 10,
		containLabel: true,
	},
axisLabel: {
            interval: 400, // 坐标轴刻度标签的显示间隔。
            showMinLabel: true,
            showMaxLabel: true,
            align: 'left'
            }   
```
![avatar](https://segmentfault.com/img/bVbB6BL)

### What is expected?
只需要显示最大和最小的标签，同时标签不溢出。
不希望通过rotate或是换行的方式来全显，毕竟只要显示两个标签而已。

### What is actually happening?
axisLabel.align设为left，则右边标签溢出；设为right，则左边标签溢出；设为center，则两个标签都有溢出部分。

**Comment by Ovilia** [comment]
I found that there is an option [xAxis.data.textStyle.align](https://echarts.apache.org/zh/option.html#xAxis.data.textStyle.align) that can set the align of a single axis data label. So there are two options:

1. For users who have such requirement, they can set the align value of the last element to be `'right'`:
```
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', {
            value: 'Satxxxxxxxxxxxxxxxxxxxxxxxy',
            textStyle: {
                align: 'right'
            }
        }],
        axisLabel: {
            interval: 4,
            showMinLabel: true,
            showMaxLabel: true,
            align: 'left'
        }
    },
```

2. We change the source code and set the last label to be `'right'` for all cases, or if the last label is larger than the given space.

Apparently, setting the last label to be `'right'` for all cases is a bad solution for simple cases like:
<img width="830" alt="屏幕快照 2020-03-02 13 52 09" src="https://user-images.githubusercontent.com/779050/75649357-d3190d80-5c8d-11ea-989b-8d9b57939360.png">


I would suggest that we remain the logic simple and let the user decide whether they need to align the last label to right.

**Comment by Ovilia** [comment]
@wuwenyuan111 Please use the above option to align the last label to right and we will see if this can be improved more automatically in v5.0.

**Comment by wuwenyuan111** [comment]
您这个方案是没法使用在大数据量上同时具有datazoom属性上的，在我对图表进行横向移动的时候，就又会出现同样的问题了(最右边的数据就不是最后一个数据了)。您的这个建议我已经尝试过了。
希望能在V5.0见到能自动更新的。
