### ISSUE TITLE
label normal rotate设置无效

### ISSUE THREAD

**Issue by Ellen0604** [apache/incubator-echarts#11946]
### Version
3.6.1

### Steps to reproduce
```js
series: {
        type: 'bar',
        barGap: 0,
        data: [],
        label: {
          normal: {
            show: true,
            position: 'top',
            rotate: 90,
            formatter: '{c}万'
          }
        }
      }
```
### What is expected?
label本该旋转90°

### What is actually happening?
label无变化
![image](https://user-images.githubusercontent.com/24667299/71570707-8e4beb80-2b11-11ea-978f-7d8f0223c60c.png)

**Comment by pissang** [comment]
https://echarts.apache.org/zh/changelog.html#v3-7-0

echarts 在 3.7.0 后才开始支持标签旋转
