### ISSUE TITLE
After scroll legend to second page or other page (not first page), change the data in legned (the data only can dispaly in one page). and the legend will not render.

### ISSUE THREAD

**Issue by zhangjianrencai** [apache/incubator-echarts#11950]
### Version
4.6.0

### Steps to reproduce
1. scroll legend to second page or other page (not first page)
2. change the data(nameList) in legned (the data only can dispaly in one page)

### What is expected?
legend will display correctly

### What is actually happening?
legend is not dislpay

---
**Here is the option about legend part**

      `  legend: {
            type: 'scroll',
            orient: 'horizontal',
            scrollDataIndex : scrollDataIndex,
            bottom: '5%',
            data: nameList
        }`

**Comment by pissang** [comment]
I think it has been fixed in https://github.com/apache/incubator-echarts/pull/11952

**Comment by zhangjianrencai** [comment]
@pissang Will it be included in the next release?

**Comment by pissang** [comment]
@zhangjianrencai Yes
