### ISSUE TITLE
Add readme to the compressed package content downloaded by online customization tool

### ISSUE THREAD

**Issue by xuzhengrong** [apache/incubator-echarts#11966]
### What problem does this feature solve?
After I use the online custom download tool, I often can't remember which items/options/components I chose, so if I download it into a compressed package, it is better to have a readme file describing what projects were selected at that time, which will be better.

### What does the proposed API look like?
https://www.echartsjs.com/zh/builder.html

**Comment by pissang** [comment]
Thanks for the suggestion. It's related to website so I created a JIRA ticket to track this improvement.

https://issues.apache.org/jira/projects/ECHARTS/issues/ECHARTS-14

**Comment by xuzhengrong** [comment]
> Thanks for the suggestion. It's related to website so I created a JIRA ticket to track this issue. This one will be closed
> 
> https://issues.apache.org/jira/projects/ECHARTS/issues/ECHARTS-14

Thank you
