### ISSUE TITLE
echarts4.6.0导致４.4.0下饼状图左偏移

### ISSUE THREAD

**Issue by gxjcoo** [apache/incubator-echarts#11974]
### Version
4.6.0

### Steps to reproduce
先使用4.4.0换一个饼图，删除package-lock.json后重新npm install ecahrts@4.6.0,就可以发现echart饼图左偏移了。望解决，谢谢

### What is expected?
希望写过的代码在 echarts每个版本中都能通用

### What is actually happening?
echarts 4.6.0不兼容4.4.0的饼图

**Comment by pissang** [comment]
能否提供下完整的复现例子

**Comment by gxjcoo** [comment]
非常抱歉 我也复现不了了 。 就公司的项目是这样的，自己写一样的demo。也没能够复现。可能是别的地方有一些冲突把。

**Comment by Ovilia** [comment]
@gxjcoo 请提供可复现的例子，不然我们没法帮助你。如果实在无法复现，请关闭这个 issue。
