### ISSUE TITLE
官网示例中的字段为什么与文档中的不一致？

### ISSUE THREAD

**Issue by caopengfei** [apache/incubator-echarts#11971]
### What problem does this feature solve?
如以下链接中的示例：
https://www.echartsjs.com/examples/zh/editor.html?c=pie-doughnut
series.label下包含normal和emphasis对象，但是在官网文档中（https://www.echartsjs.com/zh/option.html#series-pie.type），label和emphasis是平级关系，而且label并没有normal对象，emphasis中也没有textStyle对象，搞的好迷糊。

### What does the proposed API look like?
希望文档和示例的字段能够统一

**Comment by pissang** [comment]
谢谢反馈，示例部分老的代码已经改掉，这两天就可以上线
