### ISSUE TITLE
echarts如何有实现对应功能的配置项吗？

### ISSUE THREAD

**Issue by ackemaneva** [apache/incubator-echarts#11992]
### Version
4.6.0

### Steps to reproduce
我想要实现如图一样的功能。
先用折线图和markline来完成线的绘制。
我想通过markarea来完成折线和markline相交的区域的颜色渲染。
根据官方markarea配置项，我需要知道相交点的x坐标。
但是我没有找到获取到相交点的x坐标的方法，
并且这个横轴是个类目轴，横轴是日期；纵轴是非类目轴，纵轴是是温度值。
请问有对应的api吗？

### What is expected?
https://i.ibb.co/xFkfr1B/QQ-20200108112230.png

### What is actually happening?
echarts gallery：
https://gallery.echartsjs.com/editor.html?c=x5q6HiTHj&v=1
手机上的实际效果：
https://i.ibb.co/9rXZ6Rr/QQ-20200108112203.png

---
请教echarts支持这个功能吗？如果支持，请指出相关api，多谢

**Comment by yufeng04** [comment]
Sorry, this api is not supported yet.

**Comment by 100pah** [comment]
@ackemaneva 

Does this example meet your requirement?
https://gallery.echartsjs.com/editor.html?c=xH5avuYBz&v=1

**Comment by ackemaneva** [comment]
> @ackemaneva
> 
> Does this example meet your requirement?
> https://gallery.echartsjs.com/editor.html?c=xH5avuYBz&v=1
不符合我的需求。你给出的示例中，markarea的起始x坐标和结束x坐标都是类目轴上已经存在的点，而我的并不是。我的场景是，一条横向的markline与折线相交后产生的2个点，分别为起始和结束点。通过起始和结束点的x坐标，来绘制相应的markarea。
所以，markarea的x轴起始和结束坐标如何获取。这才是我关注的问题，也是我提问的原因。

**Comment by ackemaneva** [comment]
> > @ackemaneva
> > Does this example meet your requirement?
> > https://gallery.echartsjs.com/editor.html?c=xH5avuYBz&v=1
> > 不符合我的需求。你给出的示例中，markarea的起始x坐标和结束x坐标都是类目轴上已经存在的点，而我的并不是。我的场景是，一条横向的markline与折线相交后产生的2个点，分别为起始和结束点。通过起始和结束点的x坐标，来绘制相应的markarea。
> > 所以，markarea的x轴起始和结束坐标如何获取。这才是我关注的问题，也是我提问的原因。

@100pah

**Comment by ackemaneva** [comment]
@100pah 谢谢你提供的示例。现在我的实际需求有变更，不需要获取这2个相交点的坐标了。
不过，这个需求，我认为应该需要考虑在实际api中。
