### ISSUE TITLE
定制的js文件中含有将要废弃的接口

### ISSUE THREAD

**Issue by xuebaogai** [apache/incubator-echarts#12002]
### Version
4.6.0

### Steps to reproduce
直接使用js 查看小程序体验评分的时候

### What is expected?
换成不用废弃的接口

### What is actually happening?
换成不用废弃的接口

**Comment by xuebaogai** [comment]
function getOption(xData, data_cur, name) {
  var option = {
    backgroundColor: "#fff",
    color: ["#37A2DA"],
    legend: {
      data: [name],
    },
    
    grid: {
      top: '15%',
      left: '10rpx',
      right: '0rpx',
      bottom: '50rpx',
      containLabel: false
    },
    tooltip: {
      show: true,
      trigger: 'axis',
    },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: xData || [],
      splitLine: {
        show: true, lineStyle: {
          color: ['#f0f0f0'],
          width: 1,
          type: 'solid'
        }
      },
      splitArea: { show: false },
      axisLabel: {
        textStyle: {
          color: '#BBBBBB',
          fontSize: 10,
          fontStyle: 'normal',
        }
      },
    },
    yAxis: {
      x: 'center',
      axisTick: {
        show: false
      },
      splitArea: { show: false },
      axisLine: {
        show: false, lineStyle: {
          color: ['#FFFFFF'],
          width: 1,
          type: 'solid'
        }
      },
      type: 'value',
      splitLine: {
        axisLine : {show: false,lineStyle:{
                    color: ['#f0f0f0'],
                    width: 1,
                    type: 'solid'
                }},
        lineStyle: {
          type: 'solid',
          color: ['#f0f0f0'],
          width: 1,
        }
      }, axisLabel: {
        margin: -20,
        textStyle: {
          color: '#BBBBBB',
          fontSize: 10,
          fontStyle: 'normal',
        }
      },
    },
    series: [{
      name: name,
      type: 'line',
      smooth: true,
      symbol: "none",
      data: data_cur || [],
      areaStyle: {
        normal: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
            offset: 0, color: 'rgba(88,160,253,1)'
          }, {
            offset: 0.5, color: 'rgba(88,160,253,0.7)'
          }, {
            offset: 1, color: 'rgba(88,160,253,0)'
          }], false)
        }
      }

    }]
  };
  return option;
};
定制了折线图 直角坐标系  标题 图例 提示框 标注 标线 标域 时间轴

**Comment by xuebaogai** [comment]
使用即将废弃或已废弃接口，可能导致小程序运行不正常。一般而言，接口不会立即去掉，但保险起见，建议不要使用，避免后续小程序突然运行异常

createCanvasContext.setFillStyle
createCanvasContext.setLineCap
createCanvasContext.setLineJoin
createCanvasContext.setMiterLimit
createCanvasContext.setStrokeStyle
createCanvasContext.setGlobalAlpha
createCanvasContext.setLineWidth
createCanvasContext.setGlobalAlpha
createCanvasContext.setFillStyle
createCanvasContext.setFillStyle
createCanvasContext.setFillStyle
createCanvasContext.setFillStyle

**Comment by xuebaogai** [comment]
那这有什么解决办法

**Comment by Ovilia** [comment]
是指微信小程序版 ECharts 吗？这部分功能正在等待重构，之后会用新版本的小程序接口，就不存在这个问题。
