### ISSUE TITLE
扇形玫瑰图

### ISSUE THREAD

**Issue by luguanrui** [apache/incubator-echarts#12025]
### Version
4.6.0

### Steps to reproduce
极坐标实现不了 扇形玫瑰图，像g2的 南丁格尔玫瑰图，玫瑰图-限定角度范围

### What is expected?
极坐标如何实现 扇形玫瑰图，像g2的 南丁格尔玫瑰图，玫瑰图-限定角度范围

### What is actually happening?
极坐标实现不了 扇形玫瑰图，像g2的 南丁格尔玫瑰图，玫瑰图-限定角度范围

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=pie-roseType
