### ISSUE TITLE
热力图使用渲染完成监测事件on.finished, 当热力图不在浏览器得可视范围内时，回调函数不执行 

### ISSUE THREAD

**Issue by Bugman-Philip** [apache/incubator-echarts#12036]
### Version
4.6.0

### Steps to reproduce
 热力图使用渲染完成监测事件on.finished, 当该页面高度较大，热力图不在当前界面可视范围内时，回调函数不执行 ，只有在热力图位于可视范围内是才执行回调。

### What is expected?
 热力图使用渲染完成监测事件on.finished，当热力图不在浏览器的可视范围内时，热力图也应该执行。散点图和盒须图并未出现此类问题

### What is actually happening?
回调未执行

**Comment by Ovilia** [comment]
请提供一个复现的例子 https://gallery.echartsjs.com/editor.html

**Comment by zacisco** [comment]
> 请提供一个复现的例子 https://gallery.echartsjs.com/editor.html
check this,plz
https://gallery.echartsjs.com/editor.html?c=xio6wC1EuA&v=1
ECharts v4.7.0
