### ISSUE TITLE
桑基图不能缩放，当最后一级节点太多的时候（比如一百多）页面显示很不友好

### ISSUE THREAD

**Issue by shuanghewuyanzu** [apache/incubator-echarts#12031]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by shuanghewuyanzu** [comment]
![2222](https://user-images.githubusercontent.com/38081886/72244956-51601880-362a-11ea-998d-5ad0818d3298.png)

**Comment by shuanghewuyanzu** [comment]
![2222](https://user-images.githubusercontent.com/38081886/72244977-5cb34400-362a-11ea-91e4-637879cb460e.png)

**Comment by apgk** [comment]
有没有解决方案。
