### ISSUE TITLE
react 使用ref获取了echart后如何使用dispatchAction

### ISSUE THREAD

**Issue by jtc23** [apache/incubator-echarts#12032]
### What problem does this feature solve?
我在echart的ref中没有找到dispatchAction的function

### What does the proposed API look like?
dispatchAction

**Comment by Ovilia** [comment]
ref 是 dom 实例吗？dom 实例上是没有这个方法的，需要获得 echarts.init 返回的图表实例。
建议在 react 插件的社区咨询这个问题。

**Comment by Zaynex** [comment]
@jtc23  请帖一下代码。
