### ISSUE TITLE
Set English as default language by switching Lang.js with LangEn.js

### ISSUE THREAD

**Issue by ahmadalibaloch** [apache/incubator-echarts#12037]
### What problem does this feature solve?
At the moment default langauge file Lang.js contains chinese as language. If we rename the file Lang.js to LangCh.js and LangEn.js to Lang.js, then English will become the default language.

### What does the proposed API look like?
This is a code change. No API change needed.

**Comment by Ovilia** [comment]
Please use `echarts-en.js` under [dist](https://github.com/apache/incubator-echarts/tree/master/dist) directory.

**Comment by ahmadalibaloch** [comment]
yes but how can I import it using es module like this
`import 'echarts' from 'echarts'`
should I use 
`import 'echarts' from 'echarts-en'  // this doesn't work`

**Comment by Ovilia** [comment]
Try with `import echarts from 'echarts/dist/echarts-en'`.
