### ISSUE TITLE
Line chart trends and data do not match when switching series display in line chart

### ISSUE THREAD

**Issue by wangyahui6** [apache/incubator-echarts#12033]
### Version
4.5.0

### Reproduction link
[https://codepen.io/huiweiwudi/pen/YzPpXoO?editors=1010](https://codepen.io/huiweiwudi/pen/YzPpXoO?editors=1010)

### Steps to reproduce
when toggole the series 1128, the 1180 line trend display different

The example is as follow: https://codepen.io/huiweiwudi/pen/YzPpXoO?editors=1010

### What is expected?
when toggole the series 1128, the 1180 line trend display same

### What is actually happening?
when toggole the series 1128, the 1180 line trend display different

**Comment by Ovilia** [comment]
This is because you have set `stack`, which makes 1180 lies on top of 1128. When 1128 is hidden, 1180 lies on the empty line. A quick fix would be removing all `stack` for three series.
