### ISSUE TITLE
Flashing tooltip when mousemove event

### ISSUE THREAD

**Issue by borodovisin** [apache/incubator-echarts#12049]
### Version
4.6.0

### Steps to reproduce
Inside the dist/echarts.js file starting in line 2353 in the mousemove event

This validation is in line: 2376

// Mouse out on previous hovered element
        if (lastHoveredTarget && hoveredTarget !== lastHoveredTarget) {
            this.dispatchToElement(lastHovered, 'mouseout', event);
        }

### What is expected?
Not dispatch mouseout event when user are moving the cursor over the same item.

### What is actually happening?
The hoveredTarget is undefined and dispatch the mouseout when it doesn't need to do that.

**Comment by Ovilia** [comment]
Can you provide a demo https://jsfiddle.net/ovilia/n6xc4df3/ ? You may use gif to record the problem if you wish.

**Comment by borodovisin** [comment]
`option = {
  "tooltip": [
    {
      "trigger": "item",
      "position": "inside",
      "confine": true,
      "show": true,
      "showContent": true
    }
  ],
  "yAxis": [
    {
      "type": "category",
      "show": true,
      "data": [
        "Hyundai Tuscon",
        "Ford Edge",
        "GMC Acadia",
        "Toyota 4Runner",
        "Honda Pilot",
        "Chevrolet Traverse",
        "Jeep Compass",
        "Mazda CX-5",
        "Subaru Forester",
        "Subaru Outback",
        "Jeep Cherokee",
        "Jeep Wrangler",
        "Toyota Highlander",
        "Jeep Grand Cherokee",
        "Ford Escape",
        "Ford Explorer",
        "Toyota RAV4",
        "Honda CR-V",
        "Chevrolet Equinox",
        "Nissan Rogue"
      ]
    }
  ],
  "xAxis": [
    {
      "position": "top",
      "type": "value",
      "nameRotate": null,
      "axisLabel": {
        "show": true,
        "margin": 5,
        "inside": false,
        "showMinLabel": null,
        "showMaxLabel": null,
        "fontSize": 12
      },
      "name": null,
      "nameLocation": "middle",
      "nameGap": 25,
      "nameTextStyle": {
        "color": "black",
        "fontWeight": "bold",
        "fontSize": "12"
      },
      "axisLine": {
        "lineStyle": {
          "color": "black",
          "width": 1,
          "type": "solid"
        },
        "show": true,
        "onZero": true,
        "onZeroAxisIndex": null,
        "symbol": [
          "none",
          "none"
        ],
        "symbolSize": [
          10,
          15
        ]
      },
      "show": true,
      "min": null,
      "max": 450000,
      "boundaryGap": [
        0,
        0
      ],
      "splitNumber": 5
    }
  ],
  "series": [
    {
      "name": "Sales(sum)",
      "type": "bar",
      "data": [
        {
          "name": "Hyundai Tuscon",
          "value": 28831,
          "category": "Hyundai Tuscon"
        },
        {
          "name": "Ford Edge",
          "value": 30920,
          "category": "Ford Edge"
        },
        {
          "name": "GMC Acadia",
          "value": 31200,
          "category": "GMC Acadia",
          "current": {
            "group": [
              "GMC Acadia"
            ]
          }
        },
        {
          "name": "Toyota 4Runner",
          "value": 32829,
          "category": "Toyota 4Runner"
        },
        {
          "name": "Honda Pilot",
          "value": 32957,
          "category": "Honda Pilot",
        },
        {
          "name": "Chevrolet Traverse",
          "value": 34223,
          "category": "Chevrolet Traverse",
        },
        {
          "name": "Jeep Compass",
          "value": 37306,
          "category": "Jeep Compass"
        },
        {
          "name": "Mazda CX-5",
          "value": 37494,
          "category": "Mazda CX-5"
        },
        {
          "name": "Subaru Forester",
          "value": 40656,
          "category": "Subaru Forester"
        },
        {
          "name": "Subaru Outback",
          "value": 41808,
          "category": "Subaru Outback"
        },
        {
          "name": "Jeep Cherokee",
          "value": 49420,
          "category": "Jeep Cherokee"
        },
        {
          "name": "Jeep Wrangler",
          "value": 49988,
          "category": "Jeep Wrangler"
        },
        {
          "name": "Toyota Highlander",
          "value": 52621,
          "category": "Toyota Highlander"
        },
        {
          "name": "Jeep Grand Cherokee",
          "value": 57749,
          "category": "Jeep Grand Cherokee"
        },
        {
          "name": "Ford Escape",
          "value": 60702,
          "category": "Ford Escape"
        },
        {
          "name": "Ford Explorer",
          "value": 61922,
          "category": "Ford Explorer"
        },
        {
          "name": "Toyota RAV4",
          "value": 83820,
          "category": "Toyota RAV4"
        },
        {
          "name": "Honda CR-V",
          "value": 87280,
          "category": "Honda CR-V"
        },
        {
          "name": "Chevrolet Equinox",
          "value": 88500,
          "category": "Chevrolet Equinox"
        },
        {
          "name": "Nissan Rogue",
          "value": 93814,
          "category": "Nissan Rogue"
        }
      ],
      "coordinateSystem": "cartesian2d",
      "legendHoverLink": true,
      "large": false,
      "largeThreshold": 400,
      "progressive": 3000
    }
  ]
}`

Here is the option object, tested using echarts example version 4.6.0

**Comment by borodovisin** [comment]
Share avideo: https://youtu.be/VYU_ZvJ2y8w

**Comment by Ovilia** [comment]
You probably don't need the `"position": "inside",` for tooltip.

**Comment by borodovisin** [comment]
Thanks @Ovilia. I remove the `"position": "inside", ` and works fine.
