### ISSUE TITLE
Does not display value on single column with stacking.

### ISSUE THREAD

**Issue by dimunidze** [apache/incubator-echarts#12056]
### Version
4.6.0

### Reproduction link
[https://codepen.io/dimunidze/pen/vYEazvP?editors=0010](https://codepen.io/dimunidze/pen/vYEazvP?editors=0010)

### Steps to reproduce
I attached a link to CodePen, in version 4.2.1 this problem was not observed. The problem is that in the first stacked bar chart, the value is not displayed, but in the rest.

### What is expected?
At the top of all stacked bars, the expected value.

### What is actually happening?
At the top of the first column with accumulation there is no value, and in the rest there is.

---
In version 4.2.1, everything worked well.

**Comment by Ovilia** [comment]
Please provide a simpler demo and remove unnecessary options.

**Comment by dimunidze** [comment]
I fixed the comment, see the same link, please. Thanks.

**Comment by Ovilia** [comment]
Seems to be a bug.

**Comment by sikazhang** [comment]
https://gallery.echartsjs.com/editor.html?c=xqfJ6FSWb&v=1
seems not a bug. The user set the top stack as 0,  so the label display 0 on the top.@Ovilia

**Comment by dimunidze** [comment]
@Ovilia after how much will this problem be resolved?

**Comment by Ovilia** [comment]
@sikazhang Your demo uses ECharts 4.4.0 and it works fine with @dimunidze 's demo, which uses ECharts 4.6.0. So this is probably a bug raised after 4.4.0.

@dimunidze It depends on the community contributors. If it's urgent, you may consider trying debugging yourself.

**Comment by hoangv** [comment]
@dimunidze try adding `"clip": false` like this: 
```
"type": "bar",
"stack": "defaultStack",
"clip": false,            
"data": [0, 0, 0],
...
```
Does that produce the output you expect?  You'll notice in @sikazhang example, if you enter [0,0,0], the bar is not shown.  This was introduced on [4.4.0-rc.1](https://github.com/apache/incubator-echarts/commit/3c78e9681e8da1b5402c8f5178f6930808b2961b) and documented [here](https://www.echartsjs.com/en/option.html#series-bar.clip).

**Comment by dimunidze** [comment]
@hoangv, thanks, it helped
