### ISSUE TITLE
地图经纬度坐标转换成为像素坐标方法convertToPixel未按实际zoom值进行转换

### ISSUE THREAD

**Issue by LZHbb** [apache/incubator-echarts#12053]
### Version
4.5.0

### Steps to reproduce
1 地图实现放大缩小效果，但是地图上有一层业务层，遮住了地图，所以无法用地图的roam:true的方法实现
2 通过setOption改变zoom、top和left值，实现放大缩小和拖拽的功能，业务层通过convertToPixel经纬度坐标转换成为像素坐标方法获取x，y绘制
3 现象是：初始zoom为1，改变top和left值后，通过convertToPixel转换出来的x和y是正确的
                 只改变zoom，不改变top和left，通过convertToPixel转换出来的x和y是正确的
                 改变zoom后，改变top和left值，convertToPixel转换的值是按zoom为1时转换的

### What is expected?
改变zoom后，改变top和left值，convertToPixel转换的值是按zoom的实际值进行转换x和y坐标

### What is actually happening?
改变zoom后，改变top和left值，convertToPixel转换的值是按zoom为1进行转换x和y坐标

**Comment by Ovilia** [comment]
可以 fork 一下[这个图](https://gallery.echartsjs.com/editor.html?c=map-china-dataRange)然后提供一个可复现的例子
