### ISSUE TITLE
Incorrect display of the transposed bar chart.

### ISSUE THREAD

**Issue by dimunidze** [apache/incubator-echarts#12057]
### Version
4.6.0

### Reproduction link
[https://codepen.io/dimunidze/pen/VwYBGEq?editors=0010](https://codepen.io/dimunidze/pen/VwYBGEq?editors=0010)

### Steps to reproduce
I attached a link to CodePen, the problem is that in the transposed bar chart, all columns merge with each other, in version 4.2.1 there was no such problem.

### What is expected?
Transposed Bar Chart.

### What is actually happening?
In a transposed bar chart, all columns merge together

---
In version 4.2.1, everything worked well.

**Comment by Ovilia** [comment]
The demo contains errors. Please consider making simpler demos based on https://jsfiddle.net/ovilia/n6xc4df3/

**Comment by dimunidze** [comment]
Removed unnecessary, removed errors, follow the same link, please. Thanks.

**Comment by Ovilia** [comment]
There is no `'custom'` type in ECharts. Change it to `'bar'` and it should work.

**Comment by dimunidze** [comment]
@Ovilia thanks for the answer, the problem is resolved.
