### ISSUE TITLE
在https下，树图的自定义图标地址是http的就会显示不出来

### ISSUE THREAD

**Issue by Ostask** [apache/incubator-echarts#12051]
### Version
4.6.0

### Steps to reproduce
1.网页地址为 https://xxxxxxxxx
2.tree的图标地址为 http://xxxxxxx
3.该图标会无法显示
4.在4.2.1版本没有这个问题

### What is expected?
希望能够正常显示图标

### What is actually happening?
1.网页地址为 https://xxxxxxxxx
2.tree的图标地址为 http://xxxxxxx
3.该图标会无法显示
4.在4.2.1版本没有这个问题

**Comment by Ovilia** [comment]
请提供一个简单的例子 https://gallery.echartsjs.com/editor.html

**Comment by alex2wong** [comment]
close it since inactivity
