### ISSUE TITLE
在geo中放入2层地图，地图监听georoam 缩放拖拽地图，下层地图跟随上层位置变化

### ISSUE THREAD

**Issue by Li-YanMing** [apache/incubator-echarts#12055]
### Version
4.5.0

### Steps to reproduce
我在geo中添加了2个地图，通过layoutCenter设置错开了一点距离，监听georoam事件，想要在缩放和拖拽上层地图时，底层也跟随着位置变化。代码如下
```js
this.myChart.on("georoam",params=>{
                    //console.log(params)
                    let option = this.myChart.getOption();
                    //console.log(option)
                    if(params.zoom!=null&&params.zoom!=undefined){ //捕捉到缩放时
                        option.geo[1].zoom=option.geo[0].zoom;//下层geo的缩放等级跟着上层的geo一起改变
                        option.geo[1].center=option.geo[0].center;//下层的geo的中心位置随着上层geo一起改变
                    }else{//捕捉到拖曳时                       
                        option.geo[1].center=option.geo[0].center;//下层的geo的中心位置随着上层geo一起改变
                    }
                    
                    this.myChart.setOption(option,true);//设置option
                    //this.myChart.resize();
                    
            })
```
### What is expected?
缩放和拖拽上层，下层地图跟随变化

### What is actually happening?
缩放时下层随上层的位置变化正确了，但是拖拽没有效果

---
另外有一点想请教拖拽触发georoam事件中的dx dy分别代表什么

**Comment by Ovilia** [comment]
Please provide a demo for the issue either with https://jsfiddle.net/ovilia/n6xc4df3/ or https://gallery.echartsjs.com/editor.html.

**Comment by mingzichongfu** [comment]
> 请通过https://jsfiddle.net/ovilia/n6xc4df3/或https://gallery.echartsjs.com/editor.html提供该问题的演示。

https://gallery.echartsjs.com/editor.html?c=xKJP6isHj&v=1

**Comment by Ovilia** [comment]
首先不是很明白为什么你需要两层地图？
然后虽然我不清楚为什么不能得到预期的效果，但是如果点击了下面一层地图，是会绘制正确的，所以不知道是不是没有重绘正确引起的。@100pah @pissang 有什么建议？

**Comment by mingzichongfu** [comment]
2层地图是想模拟着地图的3D边框。  那这个问题没有绘制成功是什么原因呢？

**Comment by pissang** [comment]
这个映像中好像是某一个版本改出的问题，先标记为 bug 吧

**Comment by alex2wong** [comment]
在最新版 4.7.0 中两层地图，已经修复，https://jsfiddle.net/xdnp805w/  @Li-YanMing  看看是否解决了你的问题
