### ISSUE TITLE
旭日图关于itemStyle.borderColor得建议

### ISSUE THREAD

**Issue by mumu1349562746** [apache/incubator-echarts#12067]
### Version
4.6.0

### Reproduction link
[https://worldcoffeeresearch.org/work/sensory-lexicon/](https://worldcoffeeresearch.org/work/sensory-lexicon/)

### Steps to reproduce
现有得功能是在原有得图基础上覆盖了一层,这样得体验并不是很好,因为我得背景颜色是不确定得,我希望能够使用borderColor为transparent来实现,边框透明能看到背景得同时,还会留有链接地址得效果,因为如果用现有版本得覆盖方法,在我下载图片得时候会受到影响,比如我现有得图是黑色背景,扩大框得图背景始终是白色,因为borderColor已经设置了黑色,就会导致图很难看.

### What is expected?
希望borderColor不再是覆盖,而是占有相应得位置,然后可以设置为透明属性看到下面得背景颜色

### What is actually happening?
实际结果在给出得链接里面

**Comment by Ovilia** [comment]
是不是和这个是一个意思？https://github.com/apache/incubator-echarts/issues/12054

**Comment by mumu1349562746** [comment]
不是,你可以自己设置一下itemStyle.borderColor这个属性,如果颜色和背景颜色一致的话,看起来就是官方给的例子那样,但是如果设置成透明的话就不行,所以我推断这个边框并不是扇形容器的一部分,而是在上面覆盖了一层而已;
希望的结果就是,当我设置成透明属性的时候,依旧能保持官方案例的效果,并且是可以看到背景颜色的;

**Comment by Ovilia** [comment]
@mumu1349562746 不太明白你说的「不行」是什么意思，创建一个例子吧
