### ISSUE TITLE
在 Echarts 版本4.2.0-rc.2 升级到 Echarts 版本4.2.1 后 地图 geo 和 series 属性的 zoom 参数改变无法重绘到正确位置

### ISSUE THREAD

**Issue by BoxiTon** [apache/incubator-echarts#12074]
### Version
4.6.0

### Steps to reproduce
参数如下：

    geo: {
        show: true,
        map: this.config.geo.map,
        zoom: this.config.geo.zoom,
        layoutCenter: layoutCenter,
        layoutSize: layoutSize,
        itemStyle: {
            normal: {
                borderWidth: 1,
                shadowColor: this.config.geo.itemStyle.normal.shadowColor,
                shadowBlur: 20,
            }
        }

    },
    series: [{
        type: "map",
        layoutCenter: layoutCenter,
        layoutSize: layoutSize,
        map: this.config.geo.map,
        name: this.config.geo.name,
        zoom: this.config.geo.zoom,
        label: this.config.geo.label,
        itemStyle: {
            "areaColor": this.config.geo.itemStyle.normal.areaColor,
            "color": this.config.geo.itemStyle.normal.color,
            "borderColor": this.config.geo.itemStyle.normal.borderColor,
        },
        tooltip: {
            show: false
        }

    }]
}

### What is expected?
修复这个问题

### What is actually happening?
修复这个问题

---
我们在配置可视化大屏，会去配置 geo 和 series 中的 zoom 属性值，初始化时显示正常，但调整参数系数后就变成大小不一的 地图效果（底图 geo 和 series 中地图 无法重叠在一起 ）

**Comment by huyansheng3** [comment]
遇到一样的问题了

**Comment by LRH5354** [comment]
geoIndex或许可以解决这种问题
