### ISSUE TITLE
visualMap图例个数太多的情况下加入滚动展示的功能（类似legend的scroll模式）

### ISSUE THREAD

**Issue by haojay5** [apache/incubator-echarts#12072]
### What problem does this feature solve?
兼容visualMap图例个数太多的情况下，图例溢出被切割的问题

### What does the proposed API look like?
{
legendMode: 'scroll'
}

**Comment by 100pah** [comment]
Could we have more info about this scenario (for example, some picture or some more description) to determine the necessity and priority of this proposed feature?
