### ISSUE TITLE
玫瑰图在数据差异较大的情况下显示异常

### ISSUE THREAD

**Issue by haojay5** [apache/incubator-echarts#12071]
### Version
4.6.0

### Steps to reproduce
{
  "series": [
    {
      "type": "pie",
      "radius": [
        80.16,
        167.835
      ],
      "name": "可开放容量",
      "data": [
        {
          "name": "市中心区",
          "value": [
            -232.9
          ]
        },
        {
          "name": "农村",
          "value": [
            -233.745,
          ]
        },
        {
          "name": "市区",
          "value": [
            -820.295
          ],
        },
        {
          "name": "城镇",
          "value": [
            -2863.53
          ]
        }
      ],
      "roseType": "radius",
    }
  ]
}

### What is expected?
不管数值差异有多大，图形上都要有显示面积上限的控制

### What is actually happening?
数值差异过大，会导致较大的部分直接撑满整个容器，较小的部分会直接无图形显示

---
跟饼图保持一致即可（增加配置有最小显示的控制）

**Comment by haojay5** [comment]
补上demo
https://gallery.echartsjs.com/editor.html?c=xSByeyXUh&v=1

**Comment by Ovilia** [comment]
饼图（包括玫瑰图）都是不允许负值的数据的

**Comment by haojay5** [comment]
demo中使用了负值，其实我想表达的意思是数据差异大，数据差异大就会存在这种问题

**Comment by Ovilia** [comment]
负值是不允许的，所以有问题
