### ISSUE TITLE
Rounded bar chart

### ISSUE THREAD

**Issue by akvaliya** [apache/incubator-echarts#12079]
### What problem does this feature solve?
I need to display rounded bar at the top in simple bar chart. roundCap feature exist for polar. Need something similar for basic bar chart

### What does the proposed API look like?
roundCap option for simple bar

![](https://content.screencast.com/users/Akvaliya/folders/Jing/media/85a6f04b-1f72-40f3-84eb-0952f8eb31e0/2020-01-18_1258.png)

**Comment by Ovilia** [comment]
https://echarts.apache.org/en/option.html#series-bar.itemStyle.barBorderRadius
