### ISSUE TITLE
使用svg渲染，rich不能使用

### ISSUE THREAD

**Issue by mingzichongfu** [apache/incubator-echarts#12073]
### Version
4.5.0

### Steps to reproduce
var rich={
                                aaa:{
                                    fontSize: 12,
                                    color: '#1A879E'
                                },
                                bbb:{
                                    fontSize: 12,
                                    color: '#fff'
                                }
                            }
                    obj.label={
                        normal: {
                            //formatter:'{aaa|{b}}\n{yellow|{d}}%',
                            color:"#fff",
                            rich:rich,
                            formatter: function(params){
                                //console.log("params.name=" params.name ",value=" params.value ",percent=" params.percent);
                                if(params!=null&&params.name!=""){
                                    return params.name   '\n {aaa|'   params.percent   '%}';
                                }else{
                                    return "";
                                }
                                
                            },
                        }
                    }

### What is expected?
期望饼状图的信息，例如名称和百分比，能用不同的颜色展示

### What is actually happening?
rich没起作用，最终发现是canvas渲染可以

---
svg渲染，什么时候可以支持rich

**Comment by Ovilia** [comment]
SVG 不支持富文本，这在[文档](https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20Canvas%20%E6%88%96%E8%80%85%20SVG%20%E6%B8%B2%E6%9F%93)里已经说明了。短期内不会修复，需要 5.0 调整底层架构后再考虑。

**Comment by Ovilia** [comment]
Duplicate of #10259.

**Comment by panhuajian** [comment]
现在5.0出来了，我看svg还是不支持富文本

**Comment by pissang** [comment]
@panhuajian 支持了
