### ISSUE TITLE
Echarts关系图graph是否支持单向

### ISSUE THREAD

**Issue by 19Qingfeng** [apache/incubator-echarts#12083]
### What problem does this feature solve?
请问关于Echarts圆形关系图数据在鼠标移入图表的时候是否支持单向关系link(查阅文档并没有发现对应API)。也就是说graph图，在鼠标移入图表的时候，link连线仅展现soure->target的关系连线而并不指向target->source的连线。请问echarts是否支持此功能。

在鼠标移入对应图表时候，仅仅展示link中source->target的link连线（并不是展示所有和当前节点有关系的连线）

### What does the proposed API look like?
series.emphasis.lineStyle.onlySource/series.emphasis.lineStyle.onlyTarget

**Comment by Ovilia** [comment]
通过[监听移动到数据的事件](https://echarts.apache.org/en/api.html#events.Mouse%20events.mouseover)，再用 `setOption` 改变内容（去掉某些箭头）。

**Comment by 19Qingfeng** [comment]
> 通过[监听移动到数据的事件](https://echarts.apache.org/en/api.html#events.Mouse%20events.mouseover)，再用`setOption`改变内容（去掉某些箭头）。

监听移动到数据的事件，在用setOption改变内容，是否相当于每次都需要重新绘制一遍图形？
还有是关于底图的疑惑，echarts官方鼠标移入图中的某个图标元素，存在关系连线高亮展示，不存在关系link连线也会显示(只是相对暗淡)。
通过监听移动到数据的事件好像是无法实现的吧

**Comment by Ovilia** [comment]
> 是否相当于每次都需要重新绘制一遍图形？
是的

> 存在关系连线高亮展示，不存在关系link连线也会显示(只是相对暗淡)。通过监听移动到数据的事件好像是无法实现的吧
有没有连线这个事是需要通过你把数据自己保存着，然后根据这个数据判断的

**Comment by lampda** [comment]
这个问题似乎不是问题了吧。
