### ISSUE TITLE
ThemeRiver Render Problem While Dragging DataZoomSlider Bar

### ISSUE THREAD

**Issue by tfcx-th** [apache/incubator-echarts#12084]
### Version
4.4.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xnxEvkE_h&v=1](https://gallery.echartsjs.com/editor.html?c=xnxEvkE_h&v=1)

### Steps to reproduce
Select a small area of a themeRiver chart with 10000  data, dragging dataZoom component

### What is expected?
The chart can be rendered smoothly

### What is actually happening?
there would be some white area in the chart

![截屏2020-01-1911 32 26](https://user-images.githubusercontent.com/37952767/72674501-57367d80-3ab2-11ea-8cc8-829fb30f7ed7.png)

**Comment by Ovilia** [comment]
Please provide a demo with minimum data.

**Comment by tfcx-th** [comment]
My chart has seven rivers, and the bug appears when each river contains at  least 290 data

[https://gallery.echartsjs.com/editor.html?c=xnxEvkE_h&v=5](url)

![290](https://user-images.githubusercontent.com/37952767/72697660-967cd100-3b7b-11ea-948c-c2fab18c1cae.png)

**Comment by tfcx-th** [comment]
I found that setting a smaller initial dataZoom endValue(about 10%) rather than using the default value(100%) might avoid this problem

[https://gallery.echartsjs.com/editor.html?c=xnxEvkE_h&v=8](https://gallery.echartsjs.com/editor.html?c=xnxEvkE_h&v=8)

**Comment by Ovilia** [comment]
@tfc-th As I said, you have to simplify your data for others to help you debug. There is no way to find the problem with so many data items. Just include the minimum data to reproduce the problem.

**Comment by tfcx-th** [comment]
Actually this bug won't appear with fewer data items
