### ISSUE TITLE
Donut chart with centered dynamic text

### ISSUE THREAD

**Issue by akvaliya** [apache/incubator-echarts#12080]
### What problem does this feature solve?
Is it possible to create pie chart with centered dynamic text based on data? I have requirement to display text based to some calculation(dynamic) after drawing donut chart in it's center 

### What does the proposed API look like?
text option for centered text

![](http://i.stack.imgur.com/oMuaa.png)

**Comment by alex2wong** [comment]
Do you mean `pie.label.position='center'` ?  Echarts already have this option to render data label at center of donut chart. as follow:

![图片](https://user-images.githubusercontent.com/10528482/72666331-0429df80-3a4c-11ea-96e5-64edb74d41bd.png)

reference: https://echarts.apache.org/en/option.html#series-pie.label.position

**Comment by akvaliya** [comment]
@alex2wong I want custom dynamic text at center.

**Comment by alex2wong** [comment]
> @alex2wong I want custom dynamic text at center.

sure, the label could be customized by string formatter or callback function based on data 

```
label: {
    normal: {
        show: false,
        position: 'center',
        formatter: function(params) {  // callback function 
                        if (params.dataIndex === 0) {
                            return params.data[params.dataIndex];
                        } else { return '' }
                    }
    },
    emphasis: {
        show: true,
        formatter: `customized {a}\n {b}: {c}`  // string formatter
    }
},
```

please refer to doc: https://echarts.apache.org/en/option.html#series-pie.label.formatter 
and try in this demo: https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut

**Comment by akvaliya** [comment]
@alex2wong Still doesn't solve my problem. It only displays on hover of donut section & It changes based on section. My requirement is doing some calculation based on data & put final number with some text at the center of donut like i displayed in  image in my question.

**Comment by Ovilia** [comment]
@akvaliya If you wish the text is shown all the time without mouse interaction, then you should probably use [title](https://echarts.apache.org/en/option.html#title) or [graphic.text](https://echarts.apache.org/en/option.html#graphic.elements-text.type) to display the information. Note that the `title` could be an array for multiple text.

**Comment by akvaliya** [comment]
@Ovilia Can you provide options example like @alex2wong to display custom text at the center of donut chart. Thanks.

**Comment by alex2wong** [comment]
@akvaliya  I believe Ovilia has given quite straightforward answer.
```
title: {
        text: `${data[0].name} count: ${data[0].value}`,
        left: 'center',
        top: 'center',
        textStyle: {
            color: '#ccc'
        }
    },

```

try demo : https://gallery.echartsjs.com/editor.html?c=xY55c6SEV&v=5

**Comment by alex2wong** [comment]
close it since inactivity

**Comment by alex2wong** [comment]
close it since inactivity

**Comment by ankit-ghl** [comment]
> @akvaliya I believe Ovilia has given quite straightforward answer.
> 
> ```
> title: {
>         text: `${data[0].name} count: ${data[0].value}`,
>         left: 'center',
>         top: 'center',
>         textStyle: {
>             color: '#ccc'
>         }
>     },
> ```
> 
> try demo : https://gallery.echartsjs.com/editor.html?c=xY55c6SEV&v=5

This solution does not work the centre of the doughnut chart is shifted to a different position. How do we make sure, it is always in the centre of the doughnut chart?
