### ISSUE TITLE
Overlapping bar chart

### ISSUE THREAD

**Issue by akvaliya** [apache/incubator-echarts#12096]
### What problem does this feature solve?
I want to create bar chart with multiple series overlapping each other.

Stack bar chart places bar on top of another bar.

### What does the proposed API look like?
I want all bar to start from the bottom like below example.
![](https://i.stack.imgur.com/rSUBO.png)

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/en/editor.html?c=area-stack This is an example of stacking line charts. For bar charts, it's almost the same, only that the series type should be `bar`.

**Comment by akvaliya** [comment]
@Ovilia I don't want to stack it. I want to overlap it. Stack would place one on another. I want all bars to start from bottom axis.

**Comment by alex2wong** [comment]
I  don't think this design deliver info effectively, since in common case bars stands side by side or stack. It is easy to recognize which series the item belong to, the color and tooltips would denote the item's series when using the existing design. 

However, technically speaking, your proposal is not easy to recognize the item belonging. items overlapping each other with alpha color would cause color mixing, producing some other colors not expected. If you apply palette with alpha=1, low value bar would be hidden in high value ones sometimes.. so, we'd better not do this.
> ![](https://camo.githubusercontent.com/bc78ac6c81f45643847f968b5df322470ba96a99/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f725355424f2e706e67)

**Comment by MeetzhDing** [comment]
> I don't think this design deliver info effectively, since in common case bars stands side by side or stack. It is easy to recognize which series the item belong to, the color and tooltips would denote the item's series when using the existing design.
> 
> However, technically speaking, your proposal is not easy to recognize the item belonging. items overlapping each other with alpha color would cause color mixing, producing some other colors not expected. If you apply palette with alpha=1, low value bar would be hidden in high value ones sometimes.. so, we'd better not do this.
> 
> > ![](https://camo.githubusercontent.com/bc78ac6c81f45643847f968b5df322470ba96a99/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f725355424f2e706e67)

If apply palette with alpha=1，can we draw low value after high value by `type: custom` ?
when data length is large, bar chart with `barGap: -100%` will be prettier

**Comment by brunotourinho** [comment]
I'm also looking for a solution to this issue! My goal is to achieve something like this...
![2023-04-04 14 13 33](https://user-images.githubusercontent.com/12257968/229881918-17615e25-17cf-4795-b04f-39f8d35b40fc.png)

**Comment by jkbngl** [comment]
We managed to solve this issue y using a bargab of -75% to move the gap slightly to the left while giving the inner bar the exact half width of the outer bar, then it matches perfectly in the middle, we also had the requirement to add a target line same as by @brunotourinho 
this is the result:
![image](https://github.com/apache/echarts/assets/32094260/a9c4557b-a8c2-4bed-9190-9410d0d46ea0)

And attached also the config:
```
option = {
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow'
    }
  },
  legend: {
    data: ['Series 1', 'Series 2', 'Series 3']
  },
  xAxis: {
    type: 'category',
    data: ['Category 1', 'Category 2', 'Category 3', 'Category 4', 'Category 5']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      name: 'Series 1',
      type: 'bar',
      data: [120, 200, 150, 80, 70],
      barWidth: 80,
      itemStyle: {
        color: '#BFBFC2aa'
      }
    },
    {
      name: 'Series 2',
      type: 'bar',
      data: [100, 180, 130, 90, 60],
      barWidth: 40,
      itemStyle: {
        color: '#7E94B5aa'
      },
      barGap: '-75%'
    },
    {
      name: 'Series 3',
      type: 'scatter',
      symbol: 'line',
      symbolSize: 30,
      symbolOffset: [10, 0],
      data: [20, 80, 40, 120, 70],
      itemStyle: {
        color: '#262C36'
      }
    }
  ]
};

```

**Comment by archiewood** [comment]
Sharing my code in case it helps people in the future

[Link to example](https://echarts.apache.org/examples/en/editor.html?code=lZDPS8MwFMfv-yseiGRChSZt2ax48ORNkB08jB7iFjTQLSWLuiL9330vy5p2MMZe6eP7eD8_MY3TZgtP8DcBtP3zXu_KEJC5tlElsJV06tPYliV9Zi2dLGHJRCpyeOMsgSBFlFmUeZBFrEV5rEWZscrP7g4r2jOX_Mj6W7Fh5U5ZrbB02ZfGJrKt3FDjwpcBh-m7Xqu7Aclg-oe0J4mAyUWaAH8gV6Cb4z-jgJPL0mrchGNwifsqIU_HGe3UZuHaGpeNryRbmdpYvOJGpfQdKI_W9VHgvkQqYPoqrTW_17MWCEWInBjnPAEP7lnFeVZ8otPMi2xw0_2suB3DRBavqkn3-A8&enc=deflate)

I did not find a good solution to reduce the gap between bars. barCategoryGap appears to have no impact when barWidth is specified
```
option = {
    xAxis: {
        type: 'category',
        data: ['2024 Q1', '2024 Q2', '2024 Q3', '2024 Q4', '2025 Q1', '2025 Q2', '2025 Q3']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name: 'Series 1 (Wide)',
            type: 'bar',
            data: [120, 190, 150, 80, 70, 110, 130],
            barWidth: 40,
            itemStyle: {
                color: '#e0e0e0'
            }
        },
        {
            name: 'Series 2 (Narrow)',
            type: 'bar',
            data: [125, 180, 170, 81, 90, 110, 120],
            barWidth: 20,
            barGap: '-75%'
            
        }
    ]
};
```

<img width="1626" height="1700" alt="Image" src="https://github.com/user-attachments/assets/b675e378-ce99-4224-a0dd-f4eda5bdd952" />
