### ISSUE TITLE
Android手机上不显示markline，其余图形都能够正常显示，请问怎么回事？

### ISSUE THREAD

**Issue by xiaobai1035** [apache/incubator-echarts#12091]
### Version
4.6.0

### Steps to reproduce
series : [
{
    type:'line',
    smooth: true,
    sampling: 'average',
    itemStyle: {
        normal: {
        color: '#388DED'
    }
  },
  areaStyle: {
      normal: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
              offset: 0,
              color: '#388DED'
          }, {
              offset: 1,
              color: '#FFFFFF'
        }])
    }
},
markLine: {
         silent: true,
         lineStyle: {
             color: 'green'
         },
         symbol: 'none',
         label: {
               show: false
          },
        data: [
           {
                yAxis: BODY_RANGE.NORMAL[0]
           }, {
                yAxis: BODY_RANGE.NORMAL[1]
          }
       ]
    }
}]

### What is expected?
基于webview的安卓手机app能够正常显示markline

### What is actually happening?
基于webview的安卓手机app中不显示markline，其余图形都正常显示

**Comment by xiaobai1035** [comment]
@echarts-bot About my demo,please check this link https://gallery.echartsjs.com/editor.html?c=xeEGnimQk&v=1 .Thanks.

**Comment by deqingli** [comment]
你好，我这边测试小米8是可以显示的

**Comment by xiaobai1035** [comment]
> 你好，我这边测试小米8是可以显示的

好的，谢谢，安卓找到问题了，但同样的配置在ios上开发版显示markline，压缩版不显示，不知道是怎么回事

**Comment by xiaobai1035** [comment]
知道是怎么回事了，原来是app本地有静态资源加载，默认加载的本地的echarts，而不是服务器上的，所以才会显示不出来
