### ISSUE TITLE
how can i use Mapbox with echarts on React

### ISSUE THREAD

**Issue by prrrcl** [apache/incubator-echarts#12098]
### What problem does this feature solve?
I couldn't find any info about that... how can i use mapbox gl with echarts on React?

### What does the proposed API look like?
I would like use mapbox with these library

**Comment by Ovilia** [comment]
https://github.com/lzxue/echartsLayer This is a third-party library that may help. We cannot offer more help here. If you have further questions, please consider asking for help in that repo.
