### ISSUE TITLE
Graph layout hierarchical option

### ISSUE THREAD

**Issue by telco2011** [apache/incubator-echarts#12100]
### What problem does this feature solve?
I would like another option for your Graph layout chart type to use an hierarchical layout instead of calculating all the x, y positions.

I am writing a widget for an application that shows a network topology in a hierarchical layout and it is easier to manage the data using the graph data option instead of using your Tree chart type.

All the application is using Echarts for drawing all charts and we would appreciate to have this new feature for your Graph types to manage the data inside network topology graph.

Thanks

### What does the proposed API look like?
I have found another library that works with network charts and I am asking for the possibility to include something similar in your awesome library.

Example: https://visjs.github.io/vis-network/examples/network/layout/hierarchicalLayout.html

**Comment by Ovilia** [comment]
Hi @telco2011 . Could you give more information about why not using tree chart type?

**Comment by telco2011** [comment]
Hi @Ovilia, thanks for your answer. 

I give you more information about why I want this feature.

I want to show a network topology tree that has nodes with different levels in a hierarchy way, like a tree. To do this, I am using a graph DB ([ArangoDB](https://www.arangodb.com/)) to store the data. This DB, like other graphs DBs, stores the data into nodes and links structure, similar to Echarts graph data structure. I want to continue using this data structure instead of parsing the data and creates a new one following the parent -> children structure that the tree chart type requires. I think it is extra logic that is not necessary and even it could have better performance if Echarts has this layout instead of calculating the node coordinates by myself.

The library (vis.js), that I have told above, has this feature to configure the graph in a hierarchy layout and even it has the possibility to configure the space between nodes, either horizontal and vertical.

It would be awesome if Echarts had similar features for its graph chart type as well.

**Comment by pissang** [comment]
Hi @telco2011 

There is an extension https://github.com/ecomfe/echarts-dagre for DAG layout on the graph series. I'm not sure if it can meet your request.

**Comment by telco2011** [comment]
Hi @pissang 

This library looks good. I'm doing some tests to check if the behavior is as expected and I back here with the results later.

Also, I've found some bugs that I'll try to generate a pull request to you review the changes.

Thanks

**Comment by telco2011** [comment]
Hi @pissang 

I've been doing some test with your library and I've forked and adapted it to accomplish to my application necessities.

Thanks a lot for your suggestion ;-)

**Comment by pissang** [comment]
@telco2011 Great. Pull request is welcomed :)

**Comment by surabande** [comment]
@pissang I am getting error 'Cannot read properties of undefined (reading '_in')'. Seems it need to handle some null / undefined conditions. Would love to see how it works. Thanks!

@telco2011 Did you get this error by any chance?

**Comment by telco2011** [comment]
Hi @surabande 

No. I haven't seen this error.
