### ISSUE TITLE
Customizing the charts with css

### ISSUE THREAD

**Issue by mybouhssina** [apache/incubator-echarts#12108]
### What problem does this feature solve?
Allow customizing charts with css

### What does the proposed API look like?
add CSS classes to elements so we can customize them

**Comment by Ovilia** [comment]
Hi. ECharts uses Canvas and SVG to render the chart so it's not possible to use CSS to custom all options. But we do support CSS for the tooltip because it's an HTML DOM. Please check [the tooltip doc](https://echarts.apache.org/en/option.html#tooltip.extraCssText).

**Comment by mybouhssina** [comment]
Ok, thank you
