### ISSUE TITLE
Several countries have wrong locations in the world map

### ISSUE THREAD

**Issue by Dreamer945** [apache/incubator-echarts#12119]
![WX20200131-170603](https://user-images.githubusercontent.com/60501376/73522538-ff9df780-444b-11ea-8d3d-4637b20bd5cc.png)

### Version
4.6.0

### Steps to reproduce
No need to use code.

### What is expected?
The label location of countries' name is correct in your world map on the Echarts website

### What is actually happening?
 Several countries such as New Zealand and Fiji have wrong locations

---
I find that several countries such as New Zealand and Fiji have wrong locations in the world map when I use Echarts. Please look at the attached picture then you will know the mistake.

Finally, I hope your team can correct this mistake quickly :)

**Comment by Dreamer945** [comment]
The label location of countries' name is incorrect in your world map on the Echarts website

**Comment by 100pah** [comment]
Could I have the page link of the "wrong location website" ? 
Because there is not such kind of demo on <https://echarts.apache.org/examples/en/index.html#chart-type-map>, I can not reproduce your issue yet.
