### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by afrinnusrat** [apache/incubator-echarts#12112]
### Version
4.6.0

### Steps to reproduce
i tried using npm install in my project and i got following issue and its not allowing further, please help.

npm WARN tarball tarball data for echarts@4.6.0 (sha512-xKkcr6v9UVOSF PMuj7Ngt3bnzLwN1sSXWCvpvX jYb3mePYsZnABq7wGkPac/m0nV653uGHXoHK8DCKCprdNg==) seems to be corrupted. Trying one more time.

### What is expected?
npm install

### What is actually happening?
not working

**Comment by 100pah** [comment]
I can install echarts successfully by
```shell
npm i echarts@4.6.0
```

Is it network issue?

**Comment by sgurin** [comment]
Got the same issue on v4.8.0  https://prnt.sc/tyenix
