### ISSUE TITLE
Add support for width for Bar series graph

### ISSUE THREAD

**Issue by sreetamdas** [apache/incubator-echarts#12128]
### What problem does this feature solve?
Currently, there is no option that allows to set the width of the bar graph, whereas this is available for almost every other series type.

The aim here is to allow the user to explicitly define the width of the bar graph, in order to remove the excessive padding in the bar graph, which is just unused space.
This also removes the inconsistency existing when a datazoom component is added, since we can customise the width of the datazoom slider, but the same cannot be done with the bar graph.

### What does the proposed API look like?
We need to use a `width` prop.

**Comment by pissang** [comment]
Hi @sreetamdas 

Bar is used on top of [grid](https://echarts.apache.org/en/option.html#grid.width) component. And you can use width/height/left/right/top/bottom layout properties in the [grid](https://echarts.apache.org/en/option.html#grid.width) component to control the padding.

**Comment by sreetamdas** [comment]
@pissang thanks a lot! Sorry but I just hadn't thoroughly gone through the documentation and missed this. This solves my use-case perfectly. Thanks a lot again!
