### ISSUE TITLE
Does the pie chart support default set one of them to enlarge, like the hover enlarge style

### ISSUE THREAD

**Issue by nieyt** [apache/incubator-echarts#12125]
### What problem does this feature solve?
I know that { selected: true} may like this, but it just protruding, not enlarge

### What does the proposed API look like?
   data: [
                {value: 335, name: '直接访问', enlarge: true},
                {value: 310, name: '邮件营销'},]

**Comment by alex2wong** [comment]
@nieyt do you mean: https://www.echartsjs.com/examples/en/editor.html?c=doc-example/pie-highlight

you can highlight one item by dispatching 'highlight' event

**Comment by alex2wong** [comment]
close it since inactivity

**Comment by pnk0006** [comment]
pieChart.dispatchAction({type:'highlight',seriesIndex: 0,dataIndex: 0});

// PieChart Highlight the Large Value
    pieChart.on('mouseover',function(e){
    pieChart.dispatchAction({type:'downplay',seriesIndex: 0,dataIndex:0}); 
        if(e.dataIndex != index){            
            pieChart.dispatchAction({type:'downplay', seriesIndex: 0, dataIndex: index });     
        }
        if(e.dataIndex == 0){
            pieChart.dispatchAction({type:'highlight',seriesIndex: 0,dataIndex:e.dataIndex});
        }
    });
    //When the mouse leaves, set the current item as selected 
    pieChart.on('mouseout',function(e){
        index = e.dataIndex;
        pieChart.dispatchAction({type:'highlight',seriesIndex: 0,dataIndex: e.dataIndex});    
    });
