### ISSUE TITLE
Would like to know which version added the data index to data value of Boxplot tooltip

### ISSUE THREAD

**Issue by tanjianyong** [apache/incubator-echarts#12127]
### What problem does this feature solve?
Sorry to bother, I would like to ask for the change in the new version of echarts(don't know which version). I improved the echart version from v3.4 to v4.4 and I found a change in the new version but not found in the echart official website.
In the v4.4 the data of Boxplot tooltip would add the index as default.
Just like the data below:
data:[5,0,200,400,600,800,400]

But in v3.4 it is shown below:
data:[0,200,400,600,800,400]

5 is the array index of  the tooltip data

I want to know in whick version do you make the change and why to do that.Thanks a lot.

### What does the proposed API look like?
I've tried on the offical website, it wiil also show the array index.

**Comment by Even-Lau** [comment]
I came across the same issue. Echarts version 4.2.1
It always put dataIndex to the beginning of the data array.
The demo is here: [https://jsfiddle.net/dmLc587n/1/](url)
