### ISSUE TITLE
Bar chart null value

### ISSUE THREAD

**Issue by prrrcl** [apache/incubator-echarts#12130]
### What problem does this feature solve?
I want to have a graph like this: https://pasteboard.co/ITePcdc.png, there are 2 devices (each device has a property, not common between devices). Now series data is like: ["12","30", null, null] (first device), and [null, null, "40","50"] null item is a "blank" bar, how can i hidden that?

### What does the proposed API look like?
....

**Comment by pissang** [comment]
`null` data will be ignored in echarts
