### ISSUE TITLE
Graph lines are truncated

### ISSUE THREAD

**Issue by wilcorrea** [apache/incubator-echarts#12136]
### Version
4.6.0

### Reproduction link
[https://jsbin.com/zagaqivoye/1/edit?html,output](https://jsbin.com/zagaqivoye/1/edit?html,output)

### Steps to reproduce
Open the link and check the line is not filling all the are area visible

### What is expected?
The line fill all the are area visible

### What is actually happening?
The line is not filling all the are area visible

**Comment by pissang** [comment]
Hi @wilcorrea 

You can set [filterMode](https://echarts.apache.org/en/option.html#dataZoom-slider.filterMode) to 'none' 

<img width="1246" alt="MacHi 2020-02-09 17-58-59" src="https://user-images.githubusercontent.com/841551/74100089-e0971800-4b65-11ea-8a06-3f169a6ecfd5.png">

**Comment by wilcorrea** [comment]
Thanks @pissang I did something wrong before. What you show works perfect. I am closing the issue
