### ISSUE TITLE
Documents-tutorial-Dataset-Q&A, the answer does not correspond to the question

### ISSUE THREAD

**Issue by Shannon-Zhang** [apache/incubator-echarts#12135]
### Version
4.6.0

### Steps to reproduce
1. click into this page https://echarts.apache.org/en/tutorial.html#Dataset , find the Q&A section, and find the sixth question.
2. the question says: 'How to encode the fourth column in bubble size in bubble plot?'  but the code below sets the 'dimension: 2', besides, there is no fourth column in the dataset. source.

### What is expected?
the question should be changed to  'How to encode the third column in bubble size in bubble plot?'

### What is actually happening?
the question now is: ' How to encode the fourth column in bubble size in bubble plot?'

**Comment by Ovilia** [comment]
Thanks for reporting. It has been fixed now.
But we still need a few more days to update the online document.

It should be `the third column`, whose index in the array is `2`.
