### ISSUE TITLE
scatter在地图中的颜色和设置的颜色不符

### ISSUE THREAD

**Issue by AN-535** [apache/incubator-echarts#12138]
### Version
4.3.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xUhovyiwR&v=1](https://gallery.echartsjs.com/editor.html?c=xUhovyiwR&v=1)

### Steps to reproduce
直接打开

### What is expected?
scatter颜色为自己设置的颜色

### What is actually happening?
scatter颜色不对

**Comment by alex2wong** [comment]
@AN-535  Since you've config visualMap. In series that controlled by visualMap, if a data item needs to escape from controlled by visualMap, you can set like this:
```
data: [{
       name: '拉萨',
       visualMap: false,
       value: geoCoordMap['拉萨'].concat([100]),
}],
```

**Comment by alex2wong** [comment]
close it since inactivity
