### ISSUE TITLE
Calendar months overlapping

### ISSUE THREAD

**Issue by mikeyshing88** [apache/incubator-echarts#12143]
### Version
4.6.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=calendar-effectscatter](https://echarts.apache.org/examples/en/editor.html?c=calendar-effectscatter)

### Steps to reproduce
Using the calendar chart, set.a range of ['2016-07-01', '2016-12-31'] (as example) and notice that December overlaps November. (This also renders the split lines for these  months incorrectly).

The reproduction is from the official example

### What is expected?
December and November should not overlap

### What is actually happening?
December and November are overlapping

**Comment by damiangreen** [comment]
![image](https://user-images.githubusercontent.com/1592820/74432963-69a89a80-4e57-11ea-82b1-8320fea36821.png)
****

**Comment by yufeng04** [comment]
I set the range of ['2016-07-01', '2016-12-31'], but it behaves normally.
![image](https://user-images.githubusercontent.com/22974511/74524730-95607900-4f5a-11ea-8ad9-4ce3397f0ed3.png)

**Comment by damiangreen** [comment]
Is your Timezone set to GMT / UTC?

**Comment by mikeyshing88** [comment]
Seems to be due to day light savings - possibly related to this PR  https://github.com/apache/incubator-echarts/pull/12081

**Comment by Ovilia** [comment]
@mikeyshing88 Thanks for reporting. We will see to it and find if we can make a PR based on #10430 's solution. You are welcomed to make a PR if you wish.
