### ISSUE TITLE
Is there any way to stack bars in the waterfall chart as in the below picture?

### ISSUE THREAD

**Issue by pratik227** [apache/incubator-echarts#12152]
### What problem does this feature solve?
Is there any way to stack bars in the waterfall chart as in the below picture?

![Screenshot from 2020-02-15 14-00-06](https://user-images.githubusercontent.com/34883558/74584908-4a4b7200-4ffd-11ea-824c-c43cea2e7cc9.png)

### What does the proposed API look like?

So far I have achieved this.

**Options**

option = {
    title: {
        text: '阶梯瀑布图',
        subtext: 'From ExcelHome',
        sublink: 'http://e.weibo.com/1341556070/Aj1J2x5a5'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        },
        formatter: function (params) {
            var tar;
            if (params[1].value != '-') {
                tar = params[1];
            }
            else {
                tar = params[0];
            }
            return tar.name   '<br/>'   tar.seriesName   ' : '   tar.value;
        }
    },
    legend: {
        data:['支出','收入']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type : 'category',
        splitLine: {show:false},
        data :  function (){
            var list = [];
            for (var i = 1; i <= 11; i  ) {
                list.push('11月'   i   '日');
            }
            return list;
        }()
    },
    yAxis: {
        type : 'value'
    },
    series: [
        {
            name: '辅助',
            type: 'bar',
            stack: '总量',
            z:10,
            itemStyle: {
                normal: {
                    barBorderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                },
                emphasis: {
                    barBorderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                }
            },
            data: [0, 900, 1245, 1530, 1376, 1376, 1511, 1689, 1856, 1495, 1292]
        },
        {
            name: '收入',
            type: 'bar',
            stack: '总量',
            z:10,
            label: {
                normal: {
                    show: true,
                    position: 'top'
                }
            },
            data: [{
                value: 900,
                itemStyle: {color: 'blue'},
            }, 345, {
                value: 393,
                itemStyle: {color: 'blue'},
            }, '-', '-', 135, 178, 286, '-', '-', '-']
        },
        {
            name: '支出',
            type: 'bar',
            stack: '总量',
            z:10,
            label: {
                normal: {
                    show: true,
                    position: 'bottom'
                }
            },
            data: ['-', '-', '-', 108, 154, '-', '-', '-', 119, 361, 203]
        },
        {
            name:'test',
            type:'line',
            symbol:'none',
            z:1,
            lineStyle:{
              type:'dotted'  
            },
            step:'start',
            data:[0,900,1245,1638,1530,1376,1511,1689,1975,1856,1495]
        }
    ]
};

**Comment by Ovilia** [comment]
I made a demo for you: https://gallery.echartsjs.com/editor.html?c=xCKVqTIrT

But the order of negative bars seems to be different from your design. I'm afraid you have to use custom series if you insist on that order. Here's the document for custom series: https://echarts.apache.org/en/tutorial.html#Custom%20Series

**Comment by pratik227** [comment]
Ok Thanks for support
