### ISSUE TITLE
一旦将 geo.show = false, 再设置为 true 就不生效了

### ISSUE THREAD

**Issue by yft** [apache/incubator-echarts#12154]
### Version
4.6.0

### Steps to reproduce
1. open online editor (example: https://www.echartsjs.com/examples/zh/editor.html?c=line-simple)
2. paste the following code
3. open console tab

```js
option = {
    "geo": {
        "show": true,
        "map": "china"
    }
};

setInterval(function() {
    option.geo.show = !option.geo.show;
    myChart.setOption(option);
    console.log(JSON.stringify(option));
}, 2000);
```

### What is expected?
能够正常根据设置进行展示

### What is actually happening?
一旦 geo.show 设置过 false ，再设置为 true 就不生效了

**Comment by susiwen8** [comment]
Follow up in #13830
