### ISSUE TITLE
How to disable auto scale/transform in graph ?

### ISSUE THREAD

**Issue by kibbon** [apache/incubator-echarts#12150]
### Version
4.6.0

### Steps to reproduce
1. 创建一个graph类型的series图，layout选项设置为none，使用数据自身的坐标信息进行渲染
2. 添加或修改一部分数据

### What is expected?
更改数据后，渲染的图不会自适应窗口而改变其scale和transform

### What is actually happening?
图发生了自适应的改变，且没有办法移除此优化

---
我尝试尝试更改该series的坐标系统：
 coordinateSystem: 'cartesian2d'
重新刷新页面后触发了如下错误：
GraphView.js?9704:202 Uncaught TypeError: Cannot read property '__focusNodeAdjacency' of undefined
    at eval (GraphView.js?9704:202)
    at Graph.graphProto.eachEdge (Graph.js?7368:291)
    at ExtendedClass.render (GraphView.js?9704:200)
    at Task.progress (Chart.js?e887:276)
    at doProgress (task.js?f47d:217)
    at Task.taskProto.perform (task.js?f47d:157)
    at eval (echarts.js?3eba:1374)
    at ExtendedClass.eval (Global.js?7e63:517)
    at Array.forEach (<anonymous>)
    at each (util.js?6d8b:298)
文档完全没有说明更改至此坐标系需要哪些额外配置，目前我仅在xAxis和yAxis中添加了id, min, max和scale的设置

**Comment by kibbon** [comment]
注：此问题等价于，需要将graph的coordinateSystems的position和zoom分别强制置为[0, 0]和[1, 1]，无论是否重新渲染或数据坐标有无变化

**Comment by Ovilia** [comment]
@kibbon 现在的情况是 scale和transform 自适应改为了什么？请提供一下完整的代码

**Comment by kibbon** [comment]
Here is Simple Repo:
https://gallery.echartsjs.com/editor.html?c=xAWeB4ROg&v=1
之所以存在这个需求，是希望可以动态在视窗内添加新的信息，但不触发视窗改动，当用户拖拽视窗时可动态渲染原视窗外的节点，但现在这个过程被echarts所做的优化干扰了

**Comment by Ovilia** [comment]
@kibbon Please check your demo and make sure it works. You may try jsfiddle if there is CORS problem.

**Comment by kibbon** [comment]
https://gallery.echartsjs.com/editor.html?c=xAWeB4ROg&v=4
updated

**Comment by kibbon** [comment]
@Ovilia any progress or suggestions?

**Comment by Ovilia** [comment]
Sorry, I'm afraid it's not possible.

**Comment by kibbon** [comment]
Wait! I tried to read source code of echarts and make it possible.
See this commit:
https://github.com/kibbon/incubator-echarts/commit/d92bf705e52e75799fb455f8476a913a816f969d

@Ovilia , could it be supported in feature ? It's necessary for graphView customization.
