### ISSUE TITLE
动画开启时减少数据量，折线图绘图错误

### ISSUE THREAD

**Issue by Aeero** [apache/incubator-echarts#12169]
### Version
4.6.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xKQ6Yhjby&v=2](https://gallery.echartsjs.com/editor.html?c=xKQ6Yhjby&v=2)

### Steps to reproduce
1. 点击重现链接里的“减少数据”按钮
未重现可以多刷新几次，重现率极高

### What is expected?
折线图正常展示

### What is actually happening?
折线图显示错误，出现了不应出现的点

![image](https://user-images.githubusercontent.com/13835083/74803397-af61d900-5317-11ea-9796-e197ba596066.png)

---
业务场景：默认展示全部的3000 条数据，点击按钮后展示最新的20 条数据。

**Comment by Ovilia** [comment]
不该出现的点具体是指？另外建议简化一下例子，把初始数据的 3000 条改为最少能复现问题的大小，不然 3000 很难定位的。
