### ISSUE TITLE
如何把坐标写到options 里面去

### ISSUE THREAD

**Issue by travis1111** [apache/incubator-echarts#12163]
### What problem does this feature solve?
提供方法把力矢量布局后的x y 坐标写到 options 里面去。

我的project 里面需要保存布局好了x y 坐标。这个issue 里面提供了参考：

https://github.com/apache/incubator-echarts/issues/11807

https://github.com/apache/incubator-echarts/blob/master/src/chart/graph/forceLayout.js#L116 

现在我能拿到x y 坐标，但是不知道怎么才能把坐标写到options 里面。

谢谢！

### What does the proposed API look like?
暂时没有

**Comment by Ovilia** [comment]
Set [layout](https://echarts.apache.org/zh/option.html#series-graph.layout) to be `'none'` and pass `x` and `y` in [data](https://echarts.apache.org/zh/option.html#series-graph.data.x).

**Comment by travis1111** [comment]
谢谢。

`forceLayout.js` 里面的这里吗？https://github.com/apache/incubator-echarts/blob/da128eb116f47bb10e31bbdc075605be4f3616b8/src/chart/graph/forceLayout.js#L36

**Comment by Ovilia** [comment]
@travis1111 我说的是你调用的时候设置的，跟源码没关系。看这个例子https://echarts.apache.org/examples/zh/editor.html?c=graph-simple

**Comment by travis1111** [comment]
@Ovilia 可能我没有说明白。调用的时候我不知道布局后的坐标，只能靠echarts 做布局。在源码这里：

https://github.com/apache/incubator-echarts/blob/master/src/chart/graph/forceLayout.js#L116

我可以知道动态布局后的坐标，但是我想知道的是怎么把这个布局好以后的坐标传到 option 里面去，这样，我可以把坐标保存下来，下次再显示的时候我就有坐标了。

谢谢

**Comment by Ovilia** [comment]
可以通过 getOption 获得计算后的坐标吗？

**Comment by travis1111** [comment]
Thanks

通过这个可以知道

```sh
var series = chart.getModel().getSeriesByIndex(0);
    var itemLayouts = series.getData()._itemLayouts;
```
