### ISSUE TITLE
can not zoom map with touch event in phone browser

### ISSUE THREAD

**Issue by yft** [apache/incubator-echarts#12179]
### Version
4.4.0

### Reproduction link
[https://gallery.echartsjs.com/preview.html?c=xR6S3bwrg&v=1](https://gallery.echartsjs.com/preview.html?c=xR6S3bwrg&v=1)

### Steps to reproduce
1. open the url in phone browser: https://gallery.echartsjs.com/preview.html?c=xR6S3bwrg&v=1
2. zoom with two fingers

### What is expected?
zoom smoothly

### What is actually happening?
can not zoom map

**Comment by Ovilia** [comment]
You need to set `roam: true` in `geo`.

**Comment by yft** [comment]
@Ovilia I tried `roam: true`, but it seems that only works on pc.

**Comment by Ovilia** [comment]
Please make sure to use 4.6.0 version.

**Comment by yft** [comment]
@Ovilia Thank you very much for your help . It works in 4.6.0 .
