### ISSUE TITLE
（Graph，force）力矢量布局完毕后的事件（Event）？

### ISSUE THREAD

**Issue by travis1111** [apache/incubator-echarts#12173]
### What problem does this feature solve?
我需要把力矢量布局完毕后的node 的坐标x y 写到option 里面，参考  https://github.com/apache/incubator-echarts/issues/12163

有没有什么callbak/event 我能检测到布局完成的事件？

谢谢

### What does the proposed API look like?
none

**Comment by Ovilia** [comment]
Duplicated of #12163.

**Comment by travis1111** [comment]
@Ovilia 这个和 #12163 不一样。那个是问怎么把布局好的坐标写到 Option 里面去。这个问题是问有没有布局完成后的Event 我可以监听，是两个不同的问题。

谢谢
