### ISSUE TITLE
Y-axis labelling issue on charts

### ISSUE THREAD

**Issue by petrishchev** [apache/incubator-echarts#12174]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/b7cgzh2j/2](https://jsfiddle.net/b7cgzh2j/2)

### Steps to reproduce
Please create any chart and set yAxis name for example 'Value' (like an attached link).

### What is expected?
The letters 'a' and 'l' are displayed without overlapping in Y-axis label

### What is actually happening?
The letters 'a' and 'l' are displayed with overlapping in Y-axis label

---
It reproduced in chrome 79.0.3945.130 on OS windows 10

**Comment by Ovilia** [comment]
I don't have a windows to test right now. Is this effect on Mac the expected result?
<img width="68" alt="屏幕快照 2020-02-21 12 16 38" src="https://user-images.githubusercontent.com/779050/75003904-63906a80-54a4-11ea-9d28-9aac5267efba.png">

**Comment by petrishchev** [comment]
Yes, on the Mac os it works fine. But on Win10 it works like this:
![screenshot](https://user-images.githubusercontent.com/2372259/75018764-bc5e0400-54a0-11ea-8ad1-2a124987bf7a.png)

**Comment by Ovilia** [comment]
@petrishchev This is probably due to the font. Try to change a font.
