### ISSUE TITLE
Resizing or zooming sankey diagram

### ISSUE THREAD

**Issue by lbois** [apache/incubator-echarts#12203]
### What problem does this feature solve?
Hello I have a sankey diagrams with 200 nodes coming from a graph database.

The properties for most of the nodes are unreadable in the chart.
I wanted to know if possible there is something to do around the chart layout size or if it is possible to add a feature to zoom the chart (with the mouse)
Thanks

### What does the proposed API look like?
It could be a feature added in the options

**Comment by Ovilia** [comment]
@lbois sankey chart doesn't support zooming. What do you expect from zooming?

**Comment by Deohgu** [comment]
Adding to this, I would expect the zooming to work similarly to the existing `dataZoom` functionality.  
In the example above, you would be able to only show part of the horizontal axis, say 10 nodes, and then move left or right to traverse the data.

Personally, it would be useful for me to understand the flow of something that is quite long.

**Comment by dberardo-com** [comment]
zooming would mean:

- zoom-in --> double-click on a node --> the graph now displays only the node and all its children
- zoom-out --> double-click outside a node --> the graph now displays the complete sankey tree again

this would be quite helpful indeed. is there any quick way to implement this ?
