### ISSUE TITLE
Are there any breaking changes log

### ISSUE THREAD

**Issue by rdkmaster** [apache/incubator-echarts#12209]
### Version
4.1.0-release

### Steps to reproduce
We are going to upgrade echarts from 4.1 to 4.5 or higher, are there any breaking changes log that can guide us to evaluate the risk of the upgrading operation? Thanks for help.

### What is expected?
a breaking change log

### What is actually happening?
breaking change log not found

**Comment by Ovilia** [comment]
Upgrading from 4.1.0 to 4.5 or other higher versions with 4.x should be compatible and you can upgrade without too much consideration.

**Comment by rdkmaster** [comment]
Ok thanks, I will try to upgrade to 4.6 the newest version.
