### ISSUE TITLE
试了一下 在手机浏览器跑echarts GL的案例，都是黑屏

### ISSUE THREAD

**Issue by hugetiny** [apache/incubator-echarts#12200]
### Version
4.6.0

### Steps to reproduce
手机chrome浏览器，UC浏览器， 小米浏览器 （都是最新版）打开
https://www.echartsjs.com/examples/zh/index.html#chart-type-globe
中的案例都是黑屏。
打开测试webgl的网站： 
https://get.webgl.org
https://webglreport.com
中都说是支持webgl 的

### What is expected?
手机浏览器正常跑官方地球一些列的GL案例

### What is actually happening?
都是黑屏

**Comment by panbindev** [comment]
现在试了一下，在手机浏览器跑echarts GL的案例，是正常的。
我的手机：iPhone XR
浏览器：Safair、Chrome

手头没有安卓手机。暂未复现问题。

**Comment by hugetiny** [comment]
我发现不同浏览器打开https://webglreport.com 支持的特性基本都有细微差别，哪几项属性是echarts必须的呢？

**Comment by hugetiny** [comment]
补充:那几个地球的案例都不行，下面的3d图表大多数都行

**Comment by pissang** [comment]
@hugetiny 应该是不能设置 ambientCubemap 和 postEffect，安卓机的很多浏览器上会缺失一些扩展

**Comment by hugetiny** [comment]
用light.ambient的确兼容性有所提升 但是有的浏览器还是不能渲染light.ambient
