### ISSUE TITLE
flutter版的EChart是否会被提上议程？

### ISSUE THREAD

**Issue by qzcsfchh** [apache/incubator-echarts#12213]
### What problem does this feature solve?
目前flutter平台好用的图标库非常稀缺，flutter的开发者数量又呈井喷之势，在图片方面的需求成为flutter项目落地的一大瓶颈，非常希望EChart项目后期能提供flutter版本

### What does the proposed API look like?
较为完整的图表类型支持

**Comment by susiwen8** [comment]
https://github.com/entronad/flutter_echarts

**Comment by qzcsfchh** [comment]
is this project maintianed by the echart official group?

**Comment by susiwen8** [comment]
No, ECharts teams focus only on JS,  Other language support rely on community contribution.
You can find bunch of support in here
https://github.com/ecomfe/awesome-echarts

**Comment by qzcsfchh** [comment]
Thank you for your answer, problem solved.
