### ISSUE TITLE
官网demo中有一处写错了

### ISSUE THREAD

**Issue by this-spring** [apache/incubator-echarts#12222]
### Version
4.6.0

### Reproduction link
[https://www.echartsjs.com/examples/zh/editor.html?c=dynamic-data2](https://www.echartsjs.com/examples/zh/editor.html?c=dynamic-data2)

### Steps to reproduce
官网demo代码：
```
    myChart.setOption( {
        series: [{
            data: data
        }]
    });
```
实际应为：
```
    myChart.setOption(option, {
        series: [{
            data: data
        }]
    });
```

### What is expected?
修改为：
```
    myChart.setOption(option, {
        series: [{
            data: data
        }]
    });
```
即可

### What is actually happening?
可能别人copy这个demo会运行不通

---
这个demo我copy下来后运行跑不通，自己看了一下才发现，如果demo文档有错后面的人会同样遇到这个问题。

感谢 :)

**Comment by 100pah** [comment]
setOption 第一个参数，就是一个新的 option。
copy 下来没有跑通，可能是别的问题。
