### ISSUE TITLE
timeline map在react中无法使用

### ISSUE THREAD

**Issue by limm33** [apache/incubator-echarts#12224]
### Version
4.1.0-release

### Steps to reproduce
react中创建地图 时间轴图表，使用如下option
option = {
    "baseOption":{
        "timeline":{
            "data":[
                "2018-10-01",
                "2018-12-01"
            ],
            "axisType":"category",
            "show":true,
            "autoPlay":true
        },
        "geo":{
            "map":"china",
            "label":{
                "normal":{
                    "show":false
                }
            },
            "roam":false
        },
        "visualMap":{
            "show":true,
            "min":0,
            "max":87,
            "calculable":true,
            "inRange":{
                "color":[
                    "#509af2",
                    "#ffa223"
                ]
            },
            "left":"left",
            "top":"bottom",
            "itemWidth":20,
            "itemHeight":150,
            "textStyle":{
                "fontFamily":"PingFang SC",
                "fontSize":"12"
            },
            "orient":"vertical"
        }
    },
    "options":[
        {
            "series":[
                {
                    "name":"地图",
                    "type":"map",
                    "mapType":"china",
                    "roam":false,
                    "data":[
                        {
                            "name":"河南",
                            "value":[
                                113.48680405753,
                                34.157183767956,
                                86
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "series":[
                {
                    "name":"地图",
                    "type":"map",
                    "mapType":"china",
                    "roam":false,
                    "data":[
                        {
                            "name":"河南",
                            "value":[
                                113.48680405753,
                                34.157183767956,
                                47
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

### What is expected?
设置option后显示时间轴和地图的复合图表

### What is actually happening?
EChartOption只显示一张空地图，没有数据和时间轴。且setOption时提示option中字段baseOption和options在EChartOption没有对应的属性的错误。将上面的option负责到echarts官网例子中可以正常显示。

**Comment by 100pah** [comment]
Could you check is there other issue in your project, or provide more info to reproduce this issue.
I have no your project, can not reproduce it.

**Comment by xieying** [comment]
问题复现：
1.react项目中添加echarts包：“echarts”: “^4.1.0”
2.新建Echarts测试组件，见附件
3.在项目中引用Echarts测试组件
[EchartsTest.tsx.txt](https://github.com/apache/incubator-echarts/files/4284743/EchartsTest.tsx.txt)

**Comment by xieying** [comment]
附件中是echarts包中的ts文件，下载后去掉后缀.txt即可，在452行定义了EChartOption接口，里面没有baseoption及options属性，导致设置时间轴图表时提示option格式不正确，不知道咱们这边是否有解决方法或者有没有补丁包可以解决这个问题
[index.d.ts.txt](https://github.com/apache/incubator-echarts/files/4284782/index.d.ts.txt)

**Comment by Ovilia** [comment]
如果使用了 react echart 相关项目，请到那个项目下报错。如果是 ECharts 本身的问题，请提供一个不包括 react 环境的 demo。
