### ISSUE TITLE
Crashing Safari and reload page

### ISSUE THREAD

**Issue by qipkiller** [apache/incubator-echarts#12229]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/qipkiller/amxhrcs9](https://jsfiddle.net/qipkiller/amxhrcs9)

### Steps to reproduce
Open the link and wait for updating the new data

### What is expected?
Normal work and update new data to chart

### What is actually happening?
Safari version 12.1 crushing and try to reload the page.

**Comment by 100pah** [comment]
I can not reproduce it yet.
How long will be waiting for the reload in Safari?

**Comment by qipkiller** [comment]
The bug is triggered about 70%, I use browserstack.com fo test it, OS: Mojave, Safari: 12.1.
Can I record a video?

**Comment by 100pah** [comment]
It is probably a Safari issue:
When both using gradient color and shadow to in HTML Canvas rendering at the first time, the memory will increase to over 1GB instantly, which might crash the Safari.

I'm not sure how to avoid this defect yet. Need to investigate for a while.
But, @qipkiller , to temporarily avoid this issue, please do not use **gradient color** and **shadow** at the same time. That is, in your demo, do not use `echarts.graphic.LinearGradient` and `shadowColor`/`shadowBlue` at the same time.

Other info:

I have simplified it to a minimal case for this issue:

```html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/echarts@4.6.0/dist/echarts.min.js"></script>
    </head>
    <body>
        <style>
            .title {
                font-size: 18px;
                padding: 5px;
            }
            .strong {
                color:red;
            }
        </style>

        <div class="title">
            1. Open the page in <span class="strong">Safari</span>.</h2><br>
            2. Open Safari web inspector - Timeline panel. Start record. Watch "Memory" timeline.<br>
            3. Click "Add Data" button. Check whether memory timeline appears a peak <span class="strong">over 1G MB</span>.
            <br>
        </div>
        <button id="addData">Add Data</button>
        <br>
        <br>
        <div id="main0" style="width: 700px; height: 270px;"></div>

        <script type="text/javascript">
        var FIXED_IDX = -1;

        var xAxisDataRaw = ['05:15:43', '05:15:46', '05:15:48'];
        var seriesDataRaw0 = [3547546, 3903750, 1628242];
        var seriesDataRaw1 = [-167033, -2092606, -1622461];

        var xAxisData = ['05:15:41'];
        var seriesData0 = [0];
        var seriesData1 = [0];

        init(echarts);

        function init(echarts) {
            var option = {
                legend: {},
                xAxis: [{
                    data: xAxisData
                }],
                yAxis: {},
                series: [{
                    name: 'A',
                    type: 'line',
                    areaStyle: {
                        color: {
                            type: 'linear', x: 0, y: 0, x2: 0, y2: 1,
                            colorStops: [{offset: 0, color: 'green'}, {offset: 1, color: 'yellow'}],
                            global: false
                        },
                        shadowColor: 'green',
                        shadowBlur: 10
                    },
                    data: seriesData0
                }, {
                    name: 'B',
                    type: 'line',
                    areaStyle: {
                        color: {
                            type: 'linear', x: 0, y: 0, x2: 0, y2: 1,
                            colorStops: [{offset: 0, color: 'green'}, {offset: 1, color: 'yellow'}],
                            global: false
                        },
                        shadowColor: 'green',
                        shadowBlur: 10
                    },
                    data: seriesData1
                }]
            };

            function addData() {
                FIXED_IDX++;
                if (FIXED_IDX >= xAxisDataRaw.length) {
                    return;
                }

                xAxisData.push(xAxisDataRaw[FIXED_IDX]);
                seriesData0.push(seriesDataRaw0[FIXED_IDX]);
                seriesData1.push(seriesDataRaw1[FIXED_IDX]);

                chart.setOption({
                    xAxis: {
                        data: xAxisData
                    },
                    series: [{
                        data: seriesData0
                    }, {
                        data: seriesData1
                    }]
                });
            }

            var chart = echarts.init(document.getElementById('main0'));
            chart.setOption(option);

            document.getElementById('addData').onclick = function () {
                addData();
            };
        }

        </script>


    </body>
</html>
```

And the record of the memory timeline:

![image](https://user-images.githubusercontent.com/1956569/76129845-99f0ec80-6043-11ea-9984-22858f098047.png)

Notice picture above that the memory is over 1GB and the single JS task takes over 2 second.

**Comment by 100pah** [comment]
The reason of this issue:

When the `animation` is enabled (by default) and add data item to a line chart, the coordinate of the new added data item will be calculated based on the old coordinate system, and the result coordinate will be used as the begin point of the animation. See <https://github.com/apache/incubator-echarts/blob/4.6.0/src/chart/line/lineAnimationDiff.js#L121>
See the demo code I give above, when there is only one data in the chart, the Y extent might be only be `[0, 1]`. When add a new data item `3547546` to the chart, the coordinate based on the previous Y extent `[0, 1]` is `-993312512`, which is a huge number. Even so, in most cases it works normally. But if we use both `createLinearGradient` and `shadow` in Safari with that huge size, the browser have a chance to crash.

@pissang Do you have any idea about it? Limit the result of the "previous coord calculation"?

**Comment by pissang** [comment]
@100pah Perhaps We can disable animation automatically if the diff between calculated coordinate of previous data and current data is too large.

**Comment by qipkiller** [comment]
Temporarily solved the problem simplification echarts.graphic.LinearGradient to color : 'rgba()', anddisable shadow for this, Thx
