### ISSUE TITLE
旭日图 levels层级标签formatter不生效

### ISSUE THREAD

**Issue by Lidozh** [apache/incubator-echarts#12223]
### Version
4.6.0

### Steps to reproduce
想通过为旭日图是某一级设置label设置formatter格式，设置位置在series.levels.label.formatter时不生效，尝试过设置series.label.formatter生效，不过是针对所有层级的，这个是否是bug。

### What is expected?
series.levels.lebel.formatter 设置某个level层级的标签格式

### What is actually happening?
不生效

**Comment by Ovilia** [comment]
`levels[0]` 是针对返回上级的按钮的，第一级应该是 `levels[1]`.

**Comment by Lidozh** [comment]
https://gallery.echartsjs.com/editor.html?c=xsOJVxFUj&v=1
如案例所示,分别为levels[1],levels[2]设置label.formatter不生效

**Comment by Ovilia** [comment]
谢谢反馈，应该是 bug

**Comment by 100pah** [comment]
Similar to #12227
