### ISSUE TITLE
Overlapping labels in scatter plot

### ISSUE THREAD

**Issue by dileepyelleti** [apache/incubator-echarts#12235]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/bwm2p06v/3/](https://jsfiddle.net/bwm2p06v/3/)

### Steps to reproduce
Scatter plot with labels which overlaps

### What is expected?
Is there any way to specify not to overlap labels.
Similar behaviours: https://walkingtree.tech/d3-quadrant-chart-collision-in-angular2-application/
https://medium.com/@adarshlilha/removing-label-overlapping-from-pretty-charts-8dd2e3581b71

### What is actually happening?
In scatter plot if we are showing labels there are chances of them overlapping.

**Comment by Ovilia** [comment]
Hi, this will be improved in the next major release. Please refer to https://github.com/apache/incubator-echarts/issues/11497.
