### ISSUE TITLE
桑基图每列等高

### ISSUE THREAD

**Issue by Cyycl** [apache/incubator-echarts#12241]
### What problem does this feature solve?
桑基图每列等高。如下图，桑基图每列人数的总是相同的，但是却不等高，看上去很变扭。
![示例](https://s2.ax1x.com/2020/03/06/3b6tbt.jpg)

### What does the proposed API look like?
equalHeight: true | false

**Comment by Ovilia** [comment]
这是由于中间有间隙导致的，如果要一样高，就看不出数据的分叉了。不知道想要的效果是怎么样的？有没有示意图？

**Comment by Cyycl** [comment]
> 这是由于中间有间隙导致的，如果要一样高，就看不出数据的分叉了。不知道想要的效果是怎么样的？有没有示意图？

顶部对齐

**Comment by 100pah** [comment]
@Cyycl 尝试设置 
[layoutIterations](https://echarts.apache.org/en/option.html#series-sankey.layoutIterations)
为 `0` 呢？

**Comment by HealthyZhang** [comment]
> @Cyycl 尝试设置 [layoutIterations](https://echarts.apache.org/en/option.html#series-sankey.layoutIterations) 为 `0` 呢？

请问有没有上下对齐的方式呢

**Comment by HealthyZhang** [comment]
> 这是由于中间有间隙导致的，如果要一样高，就看不出数据的分叉了。不知道想要的效果是怎么样的？有没有示意图？

两边都有多个子项的时候，有办法上下对齐吗？
