### ISSUE TITLE
官方webgl地球案例中为什么Z坐标要只取正的而且要取平方根？

### ISSUE THREAD

**Issue by hugetiny** [apache/incubator-echarts#12240]
### Version
4.6.0

### Steps to reproduce
官方案例：https://www.echartsjs.com/examples/zh/editor.html?c=scatter3d-globe-population&gl=1
```
    data = data.filter(function (dataItem) {
        return dataItem[2] > 0;
    }).map(function (dataItem) {
        return [dataItem[0], dataItem[1], Math.sqrt(dataItem[2])];
    });
```
为什么Z坐标要只取正的而且要取平方根？来源数据X,Y轴有正负，Z都是正数

### What is expected?
请回答一下

### What is actually happening?
应该是XYZ轴都有正负，对应一个三维坐标系，如果是百度自己的标准
希望告知一下经纬度转坐标系的js写法

**Comment by Ovilia** [comment]
负值的问题大概是因为负值表示海平面以下，而这里不准备表现海面以下的细节。

**Comment by hugetiny** [comment]
我的理解是这个并不是三维坐标系，而是地球坐标系，X,Y表示贴图平面的坐标系
Z表示从圆心出发的距离，并没有负值。海平面以下只是数字比较小。
问题就在于 普通的经纬度怎么转成这个坐标系

**Comment by hugetiny** [comment]
我想做一个全球covid-19的散点地球图，就卡在这里。官网找不到解释

**Comment by pissang** [comment]
@hugetiny 这里的 x，y 对应了经纬度，z 值是任意的数据（比如人口数量等等），echarts 会把 z 值线性映射到半径值（映射范围参考 https://www.echartsjs.com/zh/option-gl.html#globe.globeOuterRadius），用来表示数的大小。例子里去平方根只是对这个数据做了下特殊处理，不会让数据的对比太过夸张（类似 log 轴）。可以不需要考虑这个

**Comment by hugetiny** [comment]
谢谢 了解了
