### ISSUE TITLE
How to show Months name with one One Gap in xAxis?

### ISSUE THREAD

**Issue by nafeeur10** [apache/incubator-echarts#12258]
I want to show a bar chart with Months Name in` x-axis` and Value in `y-axis`. But value of every months will show.

```
Mar 20        May 20     Jul 20     Sep 20
```

But value of each months will show serially.

https://echarts.apache.org/examples/en/editor.html?c=multiple-y-axis

I am following this example.
How can I get my result?

**Comment by pissang** [comment]
Hi, I can't get your request. Can you provide your current demo and a shot to describe what you wan't

**Comment by nafeeur10** [comment]
Just give me the solution with my given example. In x-axis I want 1 3 5 7 ........

But result of the hidden number will remain.

Just label of Co-ordinate will hide one after another.

**Comment by Ovilia** [comment]
If you use time axis, there is no good solution for this right now.
You can use category axis and set interval.
