### ISSUE TITLE
使用graph关系图，symbol采用自定义图片，然后itemStyle中设置borderWidth属性会失效

### ISSUE THREAD

**Issue by liudid** [apache/incubator-echarts#12254]
![企业微信截图_15837436539249](https://user-images.githubusercontent.com/31311845/76196769-c6fcf500-6225-11ea-90ee-204cd9eee3ac.png)

**Comment by liudid** [comment]
![企业微信截图_15837437433718](https://user-images.githubusercontent.com/31311845/76196867-fe6ba180-6225-11ea-933c-273110901f09.png)

**Comment by liudid** [comment]
使用关系图，symbol采用自定义图片，然而eCharts中的itemStyle中的border相关属性就失效了，求大神解决一下，求大神解决一下，求大神解决一下，求大神解决一下。

**Comment by liudid** [comment]
![symbol](https://user-images.githubusercontent.com/31311845/76197842-ded57880-6227-11ea-8695-eb8da1cc019c.png)

**Comment by liudid** [comment]
![111](https://user-images.githubusercontent.com/31311845/76198828-b64e7e00-6229-11ea-98c3-f3951d74412e.png)

**Comment by liudid** [comment]
![111](https://user-images.githubusercontent.com/31311845/76199725-5ce74e80-622b-11ea-9233-edf2fd52e244.png)

**Comment by liudid** [comment]
![222](https://user-images.githubusercontent.com/31311845/76199983-cb2c1100-622b-11ea-8118-43455626361f.png)

**Comment by liudid** [comment]
### 请问是eCharts不支持graph自定义图片设置边框，还是Bug？

**Comment by pissang** [comment]
echarts 中图片类型 symbol 不支持边框
