### ISSUE TITLE
关于“抗击肺炎”中世界地图的两个“几内亚”问题

### ISSUE THREAD

**Issue by niyuanwen1983** [apache/incubator-echarts#12256]
### Version
4.7.0-rc.1

### Reproduction link
[https://voice.baidu.com/act/newpneumonia/newpneumonia/?from=osari_pc_1](https://voice.baidu.com/act/newpneumonia/newpneumonia/?from=osari_pc_1)

### Steps to reproduce
1.打开https://voice.baidu.com/act/newpneumonia/newpneumonia/?from=osari_pc_1
2.移动到国外疫情（世界地图）
3.将鼠标移到非洲的几内亚，会出现两个“几内亚”的title提示。

### What is expected?
北面的是几内亚，南面的是赤道几内亚。

### What is actually happening?
两个国家变成了一个国家。

---
上面的版本不清楚，只能随便选一个。
这个页面是从百度首页点击“抗击肺炎”进去的，不知道是不是echarts团队还是其他开发团队的问题。请看一下。谢谢！

**Comment by pissang** [comment]
谢谢反馈，这个不是 echarts 提供的地图数据，相关团队正在处理该问题
