### ISSUE TITLE
引入echarts-gl后，普通图表会报错

### ISSUE THREAD

**Issue by ghtao666** [apache/incubator-echarts#12253]
version 4.6.0
![image](https://user-images.githubusercontent.com/30283095/76193065-2c4ce800-621e-11ea-8976-d123f96c2d55.png)
![image](https://user-images.githubusercontent.com/30283095/76193096-3a026d80-621e-11ea-9068-6d16e92e973e.png)

**Comment by ghtao666** [comment]
![image](https://user-images.githubusercontent.com/30283095/76193513-23a8e180-621f-11ea-8f9d-f8e65426c8fe.png)
注掉之后普通2D图表就会显示，并且不报错

**Comment by pissang** [comment]
方便提供下可以复现的配置项或者 demo么？

**Comment by ghtao666** [comment]
抱歉，是我代码写的有问题，已经解决了
