### ISSUE TITLE
文档描述有误

### ISSUE THREAD

**Issue by SmileLifeIven** [apache/incubator-echarts#12251]
### Version
4.7.0-rc.1

### Steps to reproduce
以下位置文档有误
ECharts 基础概念概览 -> 组件的定位

"或者基于 echarts 容器高宽的百分比（例如 right: '20%' 表示：距离 echarts 容器右边界的距离是 echarts 容器高度的 20%）"

### What is expected?
容器宽度的20%

### What is actually happening?
容器高度的 20%

**Comment by Ovilia** [comment]
谢谢，已修复，上线还需要一段时间。
以后也欢迎直接给 apache/incubator-echarts-doc 提 PR。
