### ISSUE TITLE
echarts的柱状图，移入到半空就会触发高亮行为

### ISSUE THREAD

**Issue by youweihaoshuai** [apache/incubator-echarts#12263]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by youweihaoshuai** [comment]
发现了一个问题，就是柱状图的移入高亮行为，是由柱状图中最高的一个决定的，而不是当前的柱状图，你这个明显有问题

**Comment by alex2wong** [comment]
请提供一个可运行的 demo，请用 https://ecomfe.github.io/echarts-issue-helper  发起 issue， 注明版本，并提供在线 demo
