### ISSUE TITLE
请问在uni-app中h5页面使用renderjs来写echarts提示框tooltip不显示 

### ISSUE THREAD

**Issue by shangxzn** [apache/incubator-echarts#12276]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by pissang** [comment]
试试把 tooltip 的 renderMode 设置成 richText

**Comment by febiven-wsc** [comment]
我也碰到这个问题了，改成richText还是没有用

**Comment by febiven-wsc** [comment]
不好意思时间太久了忘记后来怎么做的了。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 请问在uni-app中h5页面使用renderjs来写echarts提示框tooltip不显示  (#12276)





   
我也有这个问题，有解决的吗

**Comment by shangxzn** [comment]
解决了好像，留个微信方便联系




╭ァ謀踵楒埝ヘ謀踵痛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 请问在uni-app中h5页面使用renderjs来写echarts提示框tooltip不显示  (#12276)





   
我也有这个问题，有解决的吗

**Comment by febiven-wsc** [comment]
嗯。 13028804643




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 请问在uni-app中h5页面使用renderjs来写echarts提示框tooltip不显示  (#12276)





 解决了好像，留个微信方便联系 
 
 
 
 
 ╭ァ謀踵楒埝ヘ謀踵痛 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月3日(星期五) 上午10:47 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [apache/echarts] 请问在uni-app中h5页面使用renderjs来写echarts提示框tooltip不显示  (#12276) 
 
 
 
 
 
     
 我也有这个问题，有解决的吗

**Comment by xiaogaofudao** [comment]
https://github.com/ecomfe/zrender/issues/1024
很简单的一个问题。没想到现在都没沟通 zrender 开发解决。还是 zrender Env 环境判断问题bug 导致。uniApp 打包h5 会注入 wx 全局变量。导致 zrender 判断认为是 微信环境。echarts 又依赖 zrender导致bug。建议官方沟通 zrender 修复解决。并更新zrender 依赖版本。
