### ISSUE TITLE
树图上的的文字添加点击事件

### ISSUE THREAD

**Issue by ycshill** [apache/incubator-echarts#12278]
![A36F7906-2EC0-4B50-93A5-058BA5926B71](https://user-images.githubusercontent.com/16410254/76607253-a21ebf80-654e-11ea-8333-38c2f487f65f.jpg)

1、文字添加点击事件，
2、文字鼠标滑过有对应的一个关于信息展示的pop

**Comment by Ovilia** [comment]
请参见[相关 issue](https://github.com/apache/incubator-echarts/issues?q=is%3Aissue+is%3Aopen+%E6%A0%91%E5%9B%BE+%E7%82%B9%E5%87%BB)
