### ISSUE TITLE
极坐标下的 polar. radius设置成数组后（例如[100，300]，图表就不显示了

### ISSUE THREAD

**Issue by Imagine-Michael** [apache/incubator-echarts#12275]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by pissang** [comment]
无法复现你的问题

**Comment by li1753846989** [comment]
@Imagine-Michael 您好，解决了吗，我也遇到了这个问题
