### ISSUE TITLE
symbol 设置图片以后  加载树形图 点击节点后才会加载图片

### ISSUE THREAD

**Issue by swdcode** [apache/incubator-echarts#12279]
刷新页面,都不会显示自定义的图片,点击节点后才会显示

**Comment by karma2014** [comment]
@swdcode 请在([gallery](https://gallery.echartsjs.com/editor.html))上提供一个可以运行的demo，并且参考他人的issue规范提供尽可能详细的问题描述，并提供使用版本号。
