### ISSUE TITLE
EchartOption<EchartOption.SeriesGauge>

### ISSUE THREAD

**Issue by visyone** [apache/incubator-echarts#12282]
### Version
4.6.0

### Steps to reproduce
In combination with @types/echarts => 4.4.3
I define the Gauge options in this way:

<pre>
export const GAUGE_DEFAULT_OPTIONS: EChartOption&lt;EChartOption.SeriesGauge&gt; = {
  series: [
    {
      type: 'gauge',
      data: [ { value: Math.floor(Math.random() * 100), name: "GAUGE" } ],
      radius: "90%",
      animation: true,
      name: '',
      detail: {
        fontSize: 30,
        offsetCenter: [0, "80%"]
      },
      min: 0,
      max: 100,
      splitNumber: 10,
      axisLine: {
        lineStyle: {
          color: [[0.2, '#91c7ae'], [0.8, '#63869e'], [1, '#c23531']],
          width: 15
        }
      },
      axisTick: {
        show: false,
      },
      axisLabel: {
        formatter: value => {
          value = Math.round(value * 100) / 100;
          return value;
        },
        fontSize: 15
      },
      splitLine: {
        show: false,
      },
      pointer: {
        length: "90%",
        width: 6
      },
      title: {
        show: true,
        offsetCenter: [0, '-30%'],
        fontSize: 15
      },
    }
  ]
}
</pre>

### What is expected?
Field data is recognized

### What is actually happening?
The object filed 'data' is not recognized.
Seams that is not exported from the SeriesGauge object

---
The way I use for define the Gauge options with series is not compliant whit the EChartOption<EChartOption.SeriesGauge> definition, but the in the [documentation](https://echarts.apache.org/en/option.html#series-gauge) there is.
Where is the issue?

Thanks a lot

**Comment by Ovilia** [comment]
The correct place to change and report bug is https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/echarts .
