### ISSUE TITLE
graphic extendshape event

### ISSUE THREAD

**Issue by wxyer** [apache/incubator-echarts#12288]
when create a new shape,the methods i found are shape and buildpath,how we get the event and override, so it has default action when used as  graphics component.

**Comment by Ovilia** [comment]
Where do you wish to use it? Can you give a demo?

**Comment by wxyer** [comment]
i get another idea access it,use a warpper function  for graphic, i can  drag control points to pan
and scale,thanks
![QQ截图20200323112655](https://user-images.githubusercontent.com/11608947/77278197-b0609e80-6cf9-11ea-96db-6687faff2970.jpg)
