### ISSUE TITLE
echarts同类折线图切换

### ISSUE THREAD

**Issue by LYWH** [apache/incubator-echarts#12289]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.
请问一下：在一个echarts实例中，不同类的图形很好切换，比如折线图和柱状图，但是不同类型的则线图怎么切换呢？比如基本面积图和基本折线图之间怎么切换呢？十分感谢！

**Comment by pissang** [comment]
面积图是在折线图的基础上设置 areaStyle

**Comment by LYWH** [comment]
已经找到解决方法了，十分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yi Shen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 晚上9:10
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"吴济良"<1821930891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] echarts同类折线图切换 (#12289)





 
面积图是在折线图的基础上设置 areaStyle
