### ISSUE TITLE
formatter函数的使用方式并不统一

### ISSUE THREAD

**Issue by zl7261** [apache/incubator-echarts#12294]
### Version
4.1.0-release

### Steps to reproduce
tooltip.formatter的回调函数支持使用html元素与样式,可以实现比较复杂的样式

legend的formatter函数仅支持文本,

而legend.tooltip.formatter函数又与tooltip.formatter的使用是一致的

### What is expected?
formatter的回调函数写法都能使用html元素

### What is actually happening?
legend的formatter函数仅支持文本

https://gallery.echartsjs.com/editor.html?c=x9H_sU1Mw&v=1

**Comment by zl7261** [comment]
已解决
formatter 返回textStyle需要的格式
```javascript
return (
            `{name|${name}} {percent|${percent}%} {value|${targetValue}}`
)
```
再在textStyle.rich中设置宽度
可实现对齐的效果
```json
textStyle: {
            rich: {
              name: {
                color: '#333333',
                width: 60
              },
              percent: {
                color: '#333333',
                width: 60
              },
              value: {
                fontSize: 18
              }
            }
          }
```

**Comment by pissang** [comment]
只有 tooltip 支持 html 格式的 formatter，其它的都只支持 echarts 内置的富文本格式化
