### ISSUE TITLE
When the value of polar.radius is a Array,the bar can't show correct

### ISSUE THREAD

**Issue by lieyankui** [apache/incubator-echarts#12299]
When polar.radius option for round corners on bar series is a Array, the bar can't show correct;
example:
let option={
     polar: {
          radius: [30,300]
     }
}
中文：当极坐标下的堆叠柱状图的option.polar.radius的值是一个数组时，例如：[30,300]，图形不能正确显示，在vue项目中通过npm安装的方式引入echarts，经过多次测试 4.6.0和4.7.0都是不行的，而官方实例是可以的，希望可以解决一下，邮箱：1181354012@qq.com

**Comment by yufeng04** [comment]
Is it convenient to provide a reproducible demo？
