### ISSUE TITLE
fixfox svg not displayed

### ISSUE THREAD

**Issue by freedyc** [apache/incubator-echarts#12297]
{
    type: 'group',
    children: [
        {
            type: 'image',
            position: [item.x, item.y],
            invisible: isVisible,
            draggable: false,
            style: {
                x: -14,
                y: -3,
                width: 28,
                height: 28,
                image: svg
            },
        },
    ]
}

**Comment by pissang** [comment]
Please provide a more detailed demo for us to preproduce

**Comment by freedyc** [comment]
View the underlying implementatio 
`drawImage(Image, 0, 0) `  when the image is SVG，Official document prompt
“SVG images must specify a width and height in the root <svg> element.”

**Comment by freedyc** [comment]
resolved, please close
