### ISSUE TITLE
Using auto cellSize with calendar coordinate system leaves no room for some components

### ISSUE THREAD

**Issue by a5hk** [apache/incubator-echarts#12298]
### Version
4.7.0

### Steps to reproduce
1. Open [this example](https://www.echartsjs.com/examples/en/editor.html?c=calendar-pie)
2. Replace line 71 with `margin: 0,`
3. Replace line 63 with `cellSize: ["auto", "auto"],`

### What is expected?
When using `cellSize: ["auto", "auto"]`, I expect it to account for additional components of the chart and leave some free space for them (the amount they need considering margins or positions). 

### What is actually happening?
There is no space left for some components for example `dayLabel`. To bring back `dayLabel` you need to use a negative margin (line 71) which places labels inside calendar cell.

**Comment by pissang** [comment]
Hi @a5hk . You can use left/right/top/bottom/width/height properties to location the calendar.

For example:
```js
    calendar: {
        // It will leave 100px gap for each side
        left: 100,
        right: 100,
        top: 100,
        bottom: 100,

        orient: 'vertical',
        // cellSize is auto
        cellSize: ['auto', 'auto'],
        .... 
    },
```
