### ISSUE TITLE
当单页折线图数量5个起时，如何提高性能避免页面卡顿

### ISSUE THREAD

**Issue by panbinchn** [apache/incubator-echarts#12300]
当单页折线图数量5个起时，如何提高性能避免页面卡顿？
我单页渲染数量超过10个时，页面进入时出现明显卡顿，如何提高多图表渲染的页面性能呢

**Comment by pissang** [comment]
@panbinchn 卡顿的原因可能有很多，方便发我们可以复现的 case 么

**Comment by panbinchn** [comment]
> @panbinchn卡顿的原因可能有很多，方便发我们可以复现的case么

我的需求是根据请求回来的曲线数据（曲线配置参数和源数据）显示多组不同样式折线图，每组折线图数量不定，在页面初始渲染时会卡顿1-3秒才把曲线渲染出来。因此想请教一下，当出现我这种多曲线渲染的场景下，有没有提高曲线渲染性能的方法？希望能够得到您的指教，非常感谢！

`<div
            v-for="(item1, index1) in chartData"
            :key="index1"
            class="chartBox"
            :id="item1.chartType"
            :class="item1.chartType"
            v-show="isChartType==item1.chartType"
          >
            <lineChart
              v-for="(item2, index2) in item1.chartList"
              :key="index2"
              :chartIndex="index2"
              :chartConfig="item1.chartConfig"
              :chartSeries="item2.data"
            ></lineChart>
          </div>`

**Comment by Ovilia** [comment]
提供一个不包含 vue 环境的多图表的 demo，看看是不是 ECharts 层面的问题
