### ISSUE TITLE
echarts分钟即数据更新导致内存和cpu不断上升

### ISSUE THREAD

**Issue by lizjiang** [apache/incubator-echarts#12303]
每次在echarts  setOption时候都会进行chart.dispose()和clear操作，但是尽管如此在数显每次加载后内存还是会一直上升，请问这个要怎么处理才能避免内存和cpu的飙升的问题

This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by pissang** [comment]
方便发我们可以复现的 case 么
