### ISSUE TITLE
双行X轴，类目如何分别对应显示？

### ISSUE THREAD

**Issue by zifreestyle** [apache/incubator-echarts#12306]
echarts 设置双行X轴，默认是等比分布的，如何实现对应不同数量呢？

![Snipaste_2020-03-20_16-16-12](https://user-images.githubusercontent.com/38197090/77151347-af98f400-6ad0-11ea-82d0-bd5a80e00dd8.png)

> 看不到图片的话将就看下

——————————————————————————————————> X轴
|&emsp;O1&emsp;|&emsp;O2&emsp;|&emsp;O3&emsp;|&emsp;O4&emsp;|&emsp;O5&emsp;|&emsp;O6&emsp;|&emsp;O7&emsp;|&emsp;O8&emsp;|&emsp;O9&emsp;|
|&emsp;&emsp;&emsp;I1&emsp;&emsp;&emsp;|&ensp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;I2&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;|&emsp;&emsp;&emsp;&emsp;&emsp;I3&emsp;&emsp;&emsp;&emsp;&ensp; |

**Comment by Ovilia** [comment]
参考：https://gallery.echartsjs.com/editor.html?c=xBk7TY_hWx 但是每项数量不同或许不行

**Comment by zifreestyle** [comment]
> 参考：https://gallery.echartsjs.com/editor.html?c=xBk7TY_hWx 但是每项数量不同或许不行

谢谢，我已在社区上传了我的一种解决方案。
[https://gallery.echartsjs.com/editor.html?c=xnUHWTiDTY](https://gallery.echartsjs.com/editor.html?c=xnUHWTiDTY)
