### ISSUE TITLE
环图修改top不生效问题

### ISSUE THREAD

**Issue by PandaJJ5286** [apache/incubator-echarts#12307]
### Version
4.2.1

### Reproduction link
[https://codepen.io/PandaJJ5286/pen/VwLByGe](https://codepen.io/PandaJJ5286/pen/VwLByGe)

### Steps to reproduce
环图配置信息如codepen链接所以
在官网中，修改series-top值，环图大小会变化，本地不生效，echart版本4.2.1

### What is expected?
修改series-top值，环图大小会变化，跟官网保持一致

### What is actually happening?
修改series-top值，环图大小不变

**Comment by Ovilia** [comment]
codepen 的 echarts.min.js 404 了，请使用最新代码，然后看还有没有这个问题

**Comment by PandaJJ5286** [comment]
codepen的只是示例，我本地的这个文件肯定是有的，问题肯定也是存在的，是在官网下载的，如附件。

原始邮件
发件人:Ovilianotifications@github.com
收件人:apache/incubator-echartsincubator-echarts@noreply.github.com
抄送:Panda Zhanghjzhang89@126.com; Mentionmention@noreply.github.com
发送时间:2020年3月23日(周一) 10:24
主题:Re: [apache/incubator-echarts] 环图修改top不生效问题 (#12307)


codepen 的 echarts.min.js 404 了，请使用最新代码，然后看还有没有这个问题

**Comment by PandaJJ5286** [comment]
> @PandaJJ5286 Please provide a demo for the issue either with https://jsfiddle.net/ovilia/n6xc4df3/ or https://gallery.echartsjs.com/editor.html.

jsfiddle.net网络我打不开
https://gallery.echartsjs.com/editor.html gallery上是没有生效的，官网示例上是可以生效的，建议试一下。codepen的示例的echarts.min.js 文件已邮件发送，是在官网下载的4.2.1版本的文件

**Comment by Ovilia** [comment]
保存一个在 https://gallery.echartsjs.com/editor.html 贴一下地址我看下

**Comment by Ovilia** [comment]
保存一个在 https://gallery.echartsjs.com/editor.html 贴一下地址我看下

**Comment by Ovilia** [comment]
保存一个在 https://gallery.echartsjs.com/editor.html 贴一下地址我看下

**Comment by PandaJJ5286** [comment]
https://gallery.echartsjs.com/editor.html?c=xzdxAmZnakv=1谢谢


原始邮件
发件人:Ovilianotifications@github.com
收件人:apache/incubator-echartsincubator-echarts@noreply.github.com
抄送:Panda Zhanghjzhang89@126.com; Mentionmention@noreply.github.com
发送时间:2020年3月25日(周三) 11:21
主题:Re: [apache/incubator-echarts] 环图修改top不生效问题 (#12307)


保存一个在 https://gallery.echartsjs.com/editor.html 贴一下地址我看下

**Comment by PandaJJ5286** [comment]
> 保存一个在 https://gallery.echartsjs.com/editor.html 贴一下地址我看下

谢谢 https://gallery.echartsjs.com/editor.html?c=xzdxAmZnak&v=1

**Comment by Ovilia** [comment]
看这个例子的表现，我似乎没有发现不符合预期的地方。
对于饼图而言，series.top 控制的是绘图区域的位置，然后 series.center 的位置是相对这个绘图区域而言的。至于你说饼图的大小，这是因为 series.radius 如果是百分比的话，也是相对于绘图区域（长宽中较小的一项）而言的。所以，top 本身并不能直接控制饼图的大小，如果想控制大小，应该修改 series.radius，看你的需求是用绝对的像素值还是相对的百分比。
如果和官网表现不一样，一个是检查一下 echarts.version 用最新的。另一个是保证你是在图表大小一致的情况下做的测试。
如果还有问题的话，并且最新版本不符合预期，可以在这里说明。

**Comment by PandaJJ5286** [comment]
> 看这个例子的表现，我似乎没有发现不符合预期的地方。
> 对于饼图而言，series.top 控制的是绘图区域的位置，然后 series.center 的位置是相对这个绘图区域而言的。至于你说饼图的大小，这是因为 series.radius 如果是百分比的话，也是相对于绘图区域（长宽中较小的一项）而言的。所以，top 本身并不能直接控制饼图的大小，如果想控制大小，应该修改 series.radius，看你的需求是用绝对的像素值还是相对的百分比。
> 如果和官网表现不一样，一个是检查一下 echarts.version 用最新的。另一个是保证你是在图表大小一致的情况下做的测试。
> 如果还有问题的话，并且最新版本不符合预期，可以在这里说明。

更新最新版 4.7.0 已生效，谢谢～
