### ISSUE TITLE
Add to superset ?

### ISSUE THREAD

**Issue by KonradHolubek** [apache/incubator-echarts#12310]
Hi, 

I see [here](https://github.com/apache/incubator-superset/issues/6883) that it should be possible to add echarts charts to apache superset (https://superset.apache.org/). Is that correct ? If so, can someone give me a step by step explanation how I can use echarts in superset ? 

Thank you

**Comment by pissang** [comment]
Hi, @KonradHolubek  Does this repo help? https://github.com/huandzh/superset-ui-plugins-echarts-basic
