### ISSUE TITLE
RoundCap for stacked BarChart

### ISSUE THREAD

**Issue by gehringf** [apache/incubator-echarts#12319]
### What problem does this feature solve?
For bar charts it is possible to use rounded corners for individual series. There is no way to round the cap for the topmost series only. This matters for cases where the value of a series can be 0 for some X-values. See the stack on the very right in my example.

![image](https://user-images.githubusercontent.com/56080149/77303860-ed299700-6cf3-11ea-8ef8-9b05b453d6e5.png)

### What does the proposed API look like?
options: {
…
stackBorderRadius: [8, 8, 0, 0]
…
}

**Comment by Ovilia** [comment]
Yes, I'm afraid so. You can loop the series data and add `itemStyle.barBorderRadius` to those top-most data.

**Comment by gehringf** [comment]
Thanks for your answer.

My problem is, that the same series won't always be at the top. In other words, if series A (green) is 0, I'd like Series B to be rounded in that stack. 
I don't know if there's a way to tell echarts to do that. 

What's the preferred way for examples here ? codepen/jsfiddle/jsbin…

**Comment by Ovilia** [comment]
@gehringf The top-most series is the last series with data. So technically, you do know what's on the top.

**Comment by gehringf** [comment]
Here's a demo. https://jsfiddle.net/8a9du6n4/

I haven't been able to figure out how I could do that.

**Comment by 100pah** [comment]
@gehringf

**Comment by gehringf** [comment]
@100pah  Yes, this works for me 👏  Thank you so much!

**Comment by anthony-bt** [comment]
Hi @gehringf,

I was trying to find a solution to this same problem and I would like to share with you a workaround here: https://jsfiddle.net/zha1fgw2/1/
I hope we won't have to wait for long for this feature.

Have a good day.

**Comment by man-trackunit** [comment]
The method with manually adding rounded corners to the last series does not work if one hides a series by licking the legend.

**Comment by gehringf** [comment]
It's also not perfect if the top most series onlymakesup a couple of pixels in height. A mask for the whole stack/bar would be helpful.

**Comment by mathias22osterhagen22** [comment]
Any news ? this could still be useful natively...
