### ISSUE TITLE
When dose e-charts support related features on feishu platform?

### ISSUE THREAD

**Issue by poplp** [apache/incubator-echarts#12315]
### What problem does this feature solve?
Our team want to develop applet of feishu and want to use e-charts to be components in our chart part.
Please let me know about the developing plan on feishu.
Thanks

### What does the proposed API look like?
The same as the ones for applet from Wechat is enough

**Comment by Ovilia** [comment]
I'm not sure about feishu applet environment. Based on the experience with Wechat and Baidu applet, most of the work relies on mapping the canvas provided by the applet with normal canvas API. 

No official support plan for feishu. If you want to use, please refer to Wechat applet [source code](https://github.com/ecomfe/echarts-for-weixin/tree/master/ec-canvas) and try to make similar things for feishu.

**Comment by poplp** [comment]
Thanks. We will look into it.
