### ISSUE TITLE
Tooltip 使用 richText 模式后, Tooltip的边框宽度和边框颜色失效了

### ISSUE THREAD

**Issue by autukill** [apache/incubator-echarts#12318]
### Version
4.7.0

### Steps to reproduce
tooltip: {
        renderMode: 'richText',
        borderColor: "red",
        borderWidth: 1
    }

### What is expected?
tooltip 开启 richText 模式后,配置的边框的颜色和宽度能生效

### What is actually happening?
tooltip 开启 richText 模式后,配置的边框的颜色和宽度无法生效

**Comment by autukill** [comment]
![TIM截图20200323162517](https://user-images.githubusercontent.com/5186639/77296598-ee25ed00-6d22-11ea-8b07-395f7b0dc473.png)

**Comment by autukill** [comment]
![TIM截图20200323162517](https://user-images.githubusercontent.com/5186639/77296947-84f2a980-6d23-11ea-8ee1-d202dab8e26d.png)

**Comment by hyungkiShin** [comment]
test

**Comment by autukill** [comment]
@Ovilia 
查看tooltip的源码后,发现边框的颜色和宽度没有实现, 但查看 zrender 的文档后,发现实现这个功能还是很容易实现的:

https://ecomfe.github.io/zrender-doc/public/api.html#zrenderdisplayable
- opts.style.textBackgroundColor 文字包围盒颜色。
- opts.style.textBorderColor 文字包围盒描边颜色。

修改源码 lib/component/tooltip/TooltipRichContent.js 第126行为以下
``` javascript
this.el = new Text({
      style: {
        rich: markers,
        text: content,
        textLineHeight: 20,
        textBackgroundColor: tooltipModel.get('backgroundColor'),
        textBorderRadius: tooltipModel.get('borderRadius'),
        textFill: tooltipModel.get('textStyle.color'),
        textPadding: tooltipModel.get('padding'),
        textBorderWidth: tooltipModel.get('borderWidth'),
        textBorderColor: tooltipModel.get('borderColor')
      },
      z: tooltipModel.get('z')
});
``` 
修改新增了下面两行
- textBorderWidth: tooltipModel.get('borderWidth'),
- textBorderColor: tooltipModel.get('borderColor')

tooltip 的富文本还有一些可配置的没有给出来, 比如 textLineHeight 行高被写死为 20.

**Comment by Ovilia** [comment]
@autukill 赞，要不你提个 PR？

**Comment by autukill** [comment]
> @autukill 赞，要不你提个 PR？

提了 #12383
