### ISSUE TITLE
自定义toolbox点中状态，再次点击去掉状态

### ISSUE THREAD

**Issue by yanwencheng** [apache/incubator-echarts#12329]
### What problem does this feature solve?
自定义一个toolbox工具
myTool2: {
                                show: true,
                                title: '自定义扩展方法',
                                icon: this_.realRefreshIcon[this_.realRefresh],
                                onclick: function (ecModel, api, type){
                                    console.log(
                                        ecModel, api, type
                                    )

                                }
                            },
点击后保持点中状态怎么处理？

### What does the proposed API look like?
能改显示点中后状态，再次点击失去状态，

**Comment by Ovilia** [comment]
在你的业务逻辑中记录下这个状态，然后通过 setOption 改变样式

**Comment by yanwencheng** [comment]
> setOption

是的，我使用echart.setOption({
                        toolbox: {
                            feature: {
                                myReal: {
                                    iconStyle: {
                                        borderColor: '#337ab7'
                                    }

                                }
                            }
                        }
                    })
