### ISSUE TITLE
echarts gallery打开跳转会覆盖本网页，建议打开新的标签页进行打开，避免覆盖返回重置问题

### ISSUE THREAD

**Issue by cqhejing** [apache/incubator-echarts#12334]
### Version
4.7.0

### Steps to reproduce
echarts gallery打开跳转会覆盖本网页，建议打开新的标签页进行打开，避免覆盖返回重置问题

### What is expected?
打开新的标签页进行打开，避免覆盖返回重置问题

### What is actually happening?
覆盖本网页

**Comment by Ovilia** [comment]
如果有需要，可以右键新建标签打开。

**Comment by Ovilia** [comment]
关闭本 issue 因为这个项目只关于 ECharts，和 Gallery 无关。
