### ISSUE TITLE
因为点击顶部图例筛选时会监听finished事件，有没有只在setoption后执行的finished方法

### ISSUE THREAD

**Issue by jtc23** [apache/incubator-echarts#12346]
### What problem does this feature solve?
有没有只有第一次setoption后执行的finished方法

### What does the proposed API look like?
on.（‘finished’）

**Comment by 100pah** [comment]
这样是否可以满足。

```js
var finishedListenerEnabled = false;
chart.on('finished', function () {
    if (!finishedListenerEnabled) {
        return;
    }
    // ...
});

chart.setOption({...});
finishedListenerEnabled = true;
```

**Comment by jtc23** [comment]
> 这样是否可以满足。
> 
> ```js
> var finishedListenerEnabled = false;
> chart.on('finished', function () {
>     if (!finishedListenerEnabled) {
>         return;
>     }
>     // ...
> });
> 
> chart.setOption({...});
> finishedListenerEnabled = true;
> ```

暂时也是用这种方法解决的

**Comment by zacisco** [comment]
answer on top don't help

check this,plz
on('finished', () => ch.hideLoading()); not working
https://gallery.echartsjs.com/editor.html?c=xio6wC1EuA&v=1
ECharts v4.7.0
