### ISSUE TITLE
Tree中节点的symbol，是否可以不拉伸？默认好像是会将图标拉伸显示

### ISSUE THREAD

**Issue by 10229428** [apache/incubator-echarts#12356]
### Version
4.7.0

### Reproduction link
[https://jsfiddle.net/tianhen0527/roh3uw0a/6/](https://jsfiddle.net/tianhen0527/roh3uw0a/6/)

### Steps to reproduce
在tree中，使用symbol动态设置某个节点的图标，我希望显示一个 `...` 的省略号图标，但是图标却被拉伸显示了，如下图所示：
![bbb](https://user-images.githubusercontent.com/42016535/78002579-083a7d80-736a-11ea-9da4-ceebd70580e1.png)

我在配置手册中，也没有找到可以配置symbol尺寸的设置。

而我期望的效果大概是这样的：
![aaaa](https://user-images.githubusercontent.com/42016535/78002451-d75a4880-7369-11ea-8bf4-9065212d77e8.png)

另外，是否可以设置将节点和两侧的连线之间，留一些空白，而不是完全连接在一起。

### What is expected?
期望图标本身可以保持原来的样子而不被拉伸

### What is actually happening?
看起来图标是被拉伸了

**Comment by plainheart** [comment]
我认为是可以的，使用functional symbolSize，参考 https://www.echartsjs.com/zh/option.html#series-tree.symbolSize
示例：
```js
symbolSize: (value, params) => {
    if(params.data.more) {
        return [8, 2]
    }
    return 10
}
```

**Comment by 10229428** [comment]
@plainheart 谢谢！
还想再请教一个问题，就是图标跟两侧的连线，是否有办法设置一定的间距？

**Comment by 100pah** [comment]
当前确实没有想到方便的方法，在两边设置 “间距”。
@pissang 有什么好想法么？

**Comment by pissang** [comment]
@100pah @10229428 一般这种边距可以用一个比较粗的白色的描边模拟，不过我看看图里已经有一条红色描边了，如果可以的话可以把这个红色描边改成白色，然后改粗一点

**Comment by 10229428** [comment]
@pissang 谢谢！
