### ISSUE TITLE
力引导布局 series.getData()._itemLayouts 和 position 的关系

### ISSUE THREAD

**Issue by travis1111** [apache/incubator-echarts#12352]
### What problem does this feature solve?
现在我是通过下面的代码知道布局后的坐标：

·series.getData()._itemLayouts·

但是似乎这个不是节点的x y 坐标，因为我用mouseDown，mouseUp 查看节点挪动前后的 `params.data.item.x` 和 `params.data.item.y`， 在拖动前后没有变化，不过我在 ·GraphView.js· 中，·drag· 事件里面有 ·el.position·，而这个在我拖拽前后是不一样的。

我需要知道计算出节点挪动的x y 然后保存下来，存在options 文件里面，下次直接load options 到 echarts 里面。怎么做？

谢谢

### What does the proposed API look like?
NA

**Comment by 100pah** [comment]
Duplicated with #12357
