### ISSUE TITLE
click事件与georoam事件不能同时使用

### ISSUE THREAD

**Issue by SmileLifeIven** [apache/incubator-echarts#12364]
chart.on('georoam', (params) => {
    ...
})
chart.on('click',(params)=>{
    ...
})
开启click事件，可以触发，之后开发georoam事件，georoam事件可以触发，click事件不能触发。使用chart.off('georoam')关闭事件后，click事件可以继续使用。
请问怎么处理

**Comment by JinGuiMin** [comment]
遇到了同样的问题
