### ISSUE TITLE
实例-全国主要城市空气质量 toolitip中的数值显示为维度, 应显示为pm2.5的值

### ISSUE THREAD

**Issue by p9527** [apache/incubator-echarts#12370]
### Version
4.7.0

### Steps to reproduce
https://www.echartsjs.com/examples/zh/editor.html?c=effectScatter-bmap

### What is expected?
里面toolitip显示为pm2.5的值

### What is actually happening?
里面toolitip显示为纬度的值

**Comment by plainheart** [comment]
这确实是一个示例的Bug，在#10023中有提到如何解决。
See #10023 for solutions. This is a bug of this example. Would you mind helping to correct it please? @Ovilia

**Comment by Ovilia** [comment]
已修复
