### ISSUE TITLE
Symbol rotate for markLine dose not work on line chart

### ISSUE THREAD

**Issue by YiYingWu1302** [apache/incubator-echarts#12388]
### Version
4.7.0

### Reproduction link
[https://www.echartsjs.com/examples/zh/editor.html?c=line-aqi](https://www.echartsjs.com/examples/zh/editor.html?c=line-aqi)

### Steps to reproduce
I just add the following code in `markLine` and it doesn't work,
```
symbol: 'triangle',
symbolRotate: 90,
```
Since this option is listed in the document, I suppose it should work.

### What is expected?
The symbol will rotate.

### What is actually happening?
The symbol dose not rotate.

**Comment by plainheart** [comment]
From the document, we can see that `markLine`  has no option `symbolRotate`. But I think this feature can be supported.
![image](https://user-images.githubusercontent.com/26999792/78619317-9bfed300-78af-11ea-8686-3f8892a71c94.png)

**Comment by YiYingWu1302** [comment]
That would be nice thanks!
'
Btw I said so cuz it's listed in `markLine.data` as showed below.
![](https://user-images.githubusercontent.com/54794351/78626091-4ed72d00-78c0-11ea-91bd-2755f0f47b66.png)

**Comment by plainheart** [comment]
OK. But as document said, `when symbol is set to be 'arrow' in markLine, symbolRotate value will be ignored, and compulsively use tangent angle.`, now the symbol for markLine is `arrow`, so the value of  `symbolRotate` is not valid. Refer to https://www.echartsjs.com/en/option.html#series-line.markLine.data.0.symbolRotate for details.

**Comment by plainheart** [comment]
I've tried to fix this bug. Could you refer to https://github.com/apache/incubator-echarts/pull/12392 for details and provide some idea at will?
