### ISSUE TITLE
version

### ISSUE THREAD

**Issue by bingyubing** [apache/incubator-echarts#12395]
### Version
4.7.0

### Steps to reproduce

I've created a 3D chart with an error reporting version that's too old. I've tried it from 4.1 to 4.7

Uncaught Error: echarts version is too old, needs 4.1.0 or higher #12394

### What is expected?
Can display

### What is actually happening?
A piece of white

**Comment by pissang** [comment]
Hi @bingyubing 

Can you provide a reproducible demo? I can't reproduce it in my environment or in the [examples](https://www.echartsjs.com/examples/zh/editor.html?c=bar3d-dataset&gl=1) page.
