### ISSUE TITLE
Graph options : TypeError: el is undefined

### ISSUE THREAD

**Issue by Jayesh23** [apache/incubator-echarts#12407]
### Version
4.7.0

### Steps to reproduce
import ReactEchartsCore from "echarts-for-react/lib/core";

<ReactEchartsCore
							ref={refRef}
							echarts={echarts}
							style={{ height: "100vh", left: 0, top: 0, width: "100%" }}
							option={/* a function which returns an Echarts option to generate a timseries graph */}
							onEvents={{
								click: propertyTable,
								// contextmenu: Playground
							}}
						/>
When i try to set series.fixed : true
i get an error :- TypeError: el is undefined

its working fine when fixed is set to false.

However when i push the output of the code manually to the ReactEchartsCore option it renders the graph, 
I have cross checked by replacing the option in the apache echarts site also it renders the graph there as well.

### What is expected?
A timeseries graph i.e i have a let's say data of 10 timestamps and for each timestamp i have data for 11 nodes, i just want to fix the position of all the nodes for each time stamp.

### What is actually happening?
Not able to get the timeseries graph when trying to directly pass option through a function to the ReactEchartsCore option.

error in line main.bundle.js 83143:7
 var el = edge.getGraphicEl();
 el[FOCUS_ADJACENCY] && el.off('mouseover', el[FOCUS_ADJACENCY]);
 el[UNFOCUS_ADJACENCY] && el.off('mouseout', el[UNFOCUS_ADJACENCY]);

![Screenshot from 2020-04-08 18-05-38 (copy)](https://user-images.githubusercontent.com/20610884/78880381-f3996c00-7a72-11ea-9083-902e4a466ffb.png)

**Comment by Jayesh23** [comment]
https://gallery.echartsjs.com/editor.html?c=xZ9kqwdwb4&v=1

I have added my option object in this link.

But just to clarify :-
If i pass the option object stored in a variable directly to echarts it works,
but what I basically need to do is, an api data is passed to a function, which modifies that data according to the charts input and generated an option object which i am passing directly to echarts option, This is where I get the error.

Also the echarts object attached in the above link is the exact output of the function which modifies the api data for me.

**Comment by Ovilia** [comment]
@Jayesh23 Could you please simplifier with minimum data your demo so that it's easier to debug?

**Comment by Ovilia** [comment]
ECharts doesn't have such API as `var el = edge.getGraphicEl();`. Where do you find it?
Perhaps it's provided from thiry-party libraries such as the react echarts framework you are using? If this is the case, please ask in there project's issue.

**Comment by zd5043039119** [comment]
Hi @Ovilia 
I believe Jayesh23 means the code in GraphView.js, line 181
```javascript
 data.graph.eachEdge(function (edge) {
            var el = edge.getGraphicEl();

            el[FOCUS_ADJACENCY] && el.off('mouseover', el[FOCUS_ADJACENCY]);
            el[UNFOCUS_ADJACENCY] && el.off('mouseout', el[UNFOCUS_ADJACENCY]);

            if (edge.getModel().get('focusNodeAdjacency')) {
                el.on('mouseover', el[FOCUS_ADJACENCY] = function () {
                    graphView._clearTimer();
                    api.dispatchAction({
                        type: 'focusNodeAdjacency',
                        seriesId: seriesModel.id,
                        edgeDataIndex: edge.dataIndex
                    });
                });
                el.on('mouseout', el[UNFOCUS_ADJACENCY] = function () {
                    graphView._dispatchUnfocus(api);
                });
            }
        });
```

When set the node property fixed = true, it will happens when use the demo
https://echarts.apache.org/examples/zh/editor.html?c=graph-force
and change add 1 line like 
```javascript
    graph.nodes.forEach(function (node) {
        node.itemStyle = null;
        node.symbolSize = 10;
        node.value = node.symbolSize;
        node.category = node.attributes.modularity_class;
        // Use random x, y
        node.x = node.y = null;
        node.draggable = true;
        node.fixed = true;    // add this line 
    });
```
it will throw the exception
```
VM186 echarts.min.js:22 Uncaught TypeError: Cannot read property '__focusNodeAdjacency' of undefined
    at VM186 echarts.min.js:22
    at $_.J_.eachEdge (VM186 echarts.min.js:22)
    at e.render (VM186 echarts.min.js:22)
    at jh.progress (VM186 echarts.min.js:22)
    at ac (VM186 echarts.min.js:22)
    at jh.qh.perform (VM186 echarts.min.js:22)
    at VM186 echarts.min.js:22
    at e.<anonymous> (VM186 echarts.min.js:22)
    at Array.forEach (<anonymous>)
    at R (VM186 echarts.min.js:22)
```

**Comment by alexresolute** [comment]
I am having this same issue for the record. Any thoughts from anyone? Seems to be specific to usage with react...

**Comment by pissang** [comment]
It should have been fixed in the latest version
