### ISSUE TITLE
Missing files from distro

### ISSUE THREAD

**Issue by thanatos11** [apache/incubator-echarts#12440]
### Version
4.7.0

### Steps to reproduce
bower install / bower build will not work properly because of missing bower.json

### What is expected?
work with bower auto-compile

### What is actually happening?
skipping all echarts scripts and not rendering echarts inside the system for angular

---
I created a new file in the root called: bower.json, and added the following, this seems to fix it:

{
"name": "echarts",
"version": "4.7.0",
"keywords": ["echarts"],
"main": "dist/echarts.js",
"ignore": [
"**/.*",
"Gruntfile.js",
"src",
"node_modules",
"bower_components"
]
}

**Comment by Ovilia** [comment]
This is not a bower project.

**Comment by thanatos11** [comment]
I also gave the instruction how to fix it. It will work in bower. Just one missing file in root.

**Comment by Ovilia** [comment]
We do not intend to support bower.
