### ISSUE TITLE
折线图横坐标不等间距绘制

### ISSUE THREAD

**Issue by a521king** [apache/incubator-echarts#12441]
### What problem does this feature solve?
需求：想绘制一个航路高度剖面图，横坐标是不等间距的航路点

### What does the proposed API look like?
希望根据当前航路点到下一个航路点的距离，绘制不等间距的坐标轴，并自定义标签显示

**Comment by yufeng04** [comment]
Do `xAxis. axisTick` and `xAxis. axisLabel` meet your need?

**Comment by a521king** [comment]
There's another problem：
xAxis. splitLine Cannot display only at the scale location where the label is located
设定X轴刻度xAxis. interval=1，通过xAxis.axisLabel. formatter隐藏某些标签，但坐标轴在 grid 区域中的分隔线无法只显示标签所在的刻度位置

**Comment by wf123537200** [comment]
@a521king This is the same as  #12456 , I submitted a pr, added a configuration for placing grids with unequal spacing axis
这个和 #12456 一样吧，我提交了一个pr，增加了一个配置，用于绘制不等间距坐标轴的grid
