### ISSUE TITLE
Please Enable use of ECharts with Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [apache/incubator-echarts#12458]
### What problem does this feature solve?

I am a user of [Panel](https://panel.holoviz.org/) which is a framework for creating awesome analytics apps in Python.

I think ECharts is awesome too and would like to be able to use it with Panel.

#### Solution

Contribute an ECharts pane to Panel.

If possible also enable support of PyeCharts to Panel.

### What does the proposed API look like?

Well I've actually already developed and contributed it in this Pull Request. https://github.com/holoviz/panel/pull/1286/

Would just like to let you know that you can very soon use ECharts with Panel in Python to create awesome analytics apps. 

Very useful for domain experts like analysts, engineers and scientists as well as data engineers and data scientists.

![echarts](https://user-images.githubusercontent.com/42288570/79696969-3bdd3900-8280-11ea-9208-dca690442514.gif)

**Comment by MarcSkovMadsen** [comment]
I also have tweet about it. Feel free to share if you like.

https://twitter.com/MarcSkovMadsen/status/1251950184839483395?s=20

**Comment by Ovilia** [comment]
@MarcSkovMadsen Thanks for your contribution. That seems really cool! 🎊 
I've retweeted using ECharts's account. 
You may also consider adding it to [awesome-echarts](https://github.com/ecomfe/awesome-echarts) once the PR has been merged.
Thanks!
