### ISSUE TITLE
点击某个图表选中，其他图表的选中状态会被取消，即axisPointer里面的shadow效果消失了

### ISSUE THREAD

**Issue by walker-design** [apache/incubator-echarts#12451]
### Version
4.6.0

### Reproduction link
[https://0gv53.csb.app/](https://0gv53.csb.app/)

### Steps to reproduce
在移动端页面多图表出现，点击某个图表，其他图表的选中状态会被取消，即axisPointer里面的shadow效果消失了
1、随便点击选中第一个图表，
2、在点击选中第二个图表，上一个图表的选中的状态会被取消。

### What is expected?
因为一个页面需要实现多表联动，用户需要看到他之前的状态选中，每个图表的选中状态能保留，相互不影响

### What is actually happening?
当前图表的选中状态会被其他图表点击取消

**Comment by yufeng04** [comment]
请问一下，多表联动是如何实现的呢？可以在[gallery](https://gallery.echartsjs.com/editor.html)提供一个简单的可复现demo吗？

**Comment by walker-design** [comment]
> 请问一下，多表联动是如何实现的呢？可以在[gallery](https://gallery.echartsjs.com/editor.html)提供一个简单的可复现demo吗？

你提供的地址，只能实例生成一个图表，不能在页面中生成多个图表，可以点击打开我上面提供的地址https://0gv53.csb.app/

**Comment by Ovilia** [comment]
把最简单的代码在这里贴一下

**Comment by walker-design** [comment]
<template>
  <div class="test">
    <div class="line-bar-1"></div>
    <div class="line-bar-2"></div>
  </div>
</template>

<script>
import echarts from "echarts";
export default {
  data() {
    return {
      chartInstance1: null,
      chartInstance2: null
    };
  },
  mounted() {
    this.initLineBar1();
    this.initLineBar2();
  },
  methods: {
    initLineBar1() {
      let element = document.querySelector(".line-bar-1");
      if (!element) return;
      this.chartInstance1 = echarts.init(element);
      let option = {
        tooltip: {
          show: true,
          trigger: "axis",
          showContent: false,
          axisPointer: {
            type: "shadow",
            shadowStyle: {
              color: "#000000",
              opacity: 0.1
            }
          }
        },
        xAxis: [
          {
            type: "category",
            data: ["标签", "标签2", "标签3", "标签4", "标签5"],
          }
        ],
        yAxis: [
          {
            max: 1500,
            name: "(万)",
            nameLocation: "end",
            nameGap: 2,
            type: "value",
            min: null,
            minInterval: 0
          },
          {
            name: "(%)",
            min: -1290,
            nameGap: 2,
            position: "right",
            type: "value",
            scale: true
          }
        ],
        series: [
          {
            type: "bar",
            yAxisIndex: 0,
            data: [544,423, 345, 556, 657],
          },
          {
            type: "line",
            yAxisIndex: 1,
            data: ["51.3", "100.0", "71.6", "100.0", "-455.7"],
          }
        ],
      };
      this.chartInstance1.setOption(option, true);
    },
    initLineBar2() {
      let element = document.querySelector(".line-bar-2");
      if (!element) return;
      this.chartInstance2 = echarts.init(element);
      let option = {
        tooltip: {
          show: true,
          trigger: "axis",
          showContent: false,
          axisPointer: {
            type: "shadow",
            shadowStyle: {
              color: "#000000",
              opacity: 0.1
            }
          }
        },
        xAxis: [
          {
            type: "category",
            data: ["标签", "标签2", "标签3", "标签4", "标签5"],
          }
        ],
        yAxis: [
          {
            max: 1500,
            name: "(万)",
            nameLocation: "end",
            nameGap: 2,
            type: "value",
            min: null,
            minInterval: 0
          },
          {
            name: "(%)",
            min: -1290,
            nameGap: 2,
            position: "right",
            type: "value",
            scale: true
          }
        ],
        series: [
          {
            type: "bar",
            yAxisIndex: 0,
            data: [544,423, 345, 556, 657],
          },
          {
            type: "line",
            yAxisIndex: 1,
            data: ["51.3", "100.0", "71.6", "100.0", "-455.7"],
          }
        ],
      };
      this.chartInstance2.setOption(option, true);
    }
  }
};
</script>

**Comment by walker-design** [comment]
`js
    initLineBar1() {
      let element = document.querySelector(".line-bar-1");
      if (!element) return;
      this.chartInstance1 = echarts.init(element);
      let option = {
        tooltip: {
          show: true,
          trigger: "axis",
          showContent: false,
          axisPointer: {
            type: "shadow",
            shadowStyle: {
              color: "#000000",
              opacity: 0.1
            }
          }
        },
        xAxis: [
          {
            type: "category",
            data: ["标签", "标签2", "标签3", "标签4", "标签5"],
          }
        ],
        yAxis: [
          {
            max: 1500,
            name: "(万)",
            nameLocation: "end",
            nameGap: 2,
            type: "value",
            min: null,
            minInterval: 0
          },
          {
            name: "(%)",
            min: -1290,
            nameGap: 2,
            position: "right",
            type: "value",
            scale: true
          }
        ],
        series: [
          {
            type: "bar",
            yAxisIndex: 0,
            data: [544,423, 345, 556, 657],
          },
          {
            type: "line",
            yAxisIndex: 1,
            data: ["51.3", "100.0", "71.6", "100.0", "-455.7"],
          }
        ],
      };
      this.chartInstance1.setOption(option, true);
    }
`

**Comment by walker-design** [comment]
https://gallery.echartsjs.com/editor.html?c=xvjll5ln10&v=1 
已在gallery贴入最简代码。如果页面中绘制几个这种的图表。在安卓端点击某个图表的柱子，会取消其他图表的axisPointer效果。
![Screen20200422-143409](https://user-images.githubusercontent.com/17542576/79948476-850ed200-84a6-11ea-9480-80930260e126.png)

**Comment by Ovilia** [comment]
这是符合预期的，不是 bug。如果想要保持，就记录下点击的数据，然后通过 setOption 设置一个灰色的背景（比如用 https://echarts.apache.org/zh/option.html#series-bar.showBackground）
