### ISSUE TITLE
xAxis. splitLine Cannot display only at the scale location where the label is located实现坐标轴在 grid 区域中的分隔线只显示在标签的位置

### ISSUE THREAD

**Issue by a521king** [apache/incubator-echarts#12456]
### What problem does this feature solve?
功能：起初是想绘制一个飞行航路高度剖面图，横坐标是不等间距的航路点标签（根据航路点间的距离绘制不等间距的刻度），纵坐标是高度。
实现原理：设定X轴刻度xAxis. interval=1，通过xAxis.axisLabel. formatter隐藏某些标签
问题1：坐标轴在 grid 区域中的分隔线无法只显示横坐标标签所在的刻度位置
问题2：希望纵坐标的0刻度线在横坐标的上方

### What does the proposed API look like?
希望能有一个根据横坐标动态数据绘制刻度标签的API

**Comment by a521king** [comment]
demo:   https://gallery.echartsjs.com/editor.html?c=x4dpi8YWK2&v=1

**Comment by wf123537200** [comment]
问题1没太看明白，要干啥，
问题2：是不是可以通过设置，把x轴向下偏一点
![image](https://user-images.githubusercontent.com/5130528/80049349-33695480-8545-11ea-9afa-9f7c73d472c1.png)
来实现
![image](https://user-images.githubusercontent.com/5130528/80049364-3d8b5300-8545-11ea-9080-78c27ee1f6b4.png)

**Comment by a521king** [comment]
第一个问题，如果设置xAxis.splitLine 为true，坐标轴在 grid 区域中的分隔线会铺满整个grid。我想实现只在横坐标轴有标签的位置显示分隔线

第二个问题，加offset意思是对的，但是样式不好看啊，横坐标和纵坐标轴不连在一起了

新的demo:   https://gallery.echartsjs.com/editor.html?c=x4dpi8YWK2&v=3

**Comment by wf123537200** [comment]
恕我愚钝，确认下，第一个问题：是想要红框位置没有分割线？
![image](https://user-images.githubusercontent.com/5130528/80066057-d0d87e80-856d-11ea-8a9e-4b3223edab2d.png)
第二个问题，诉求是啥，为啥要偏离那么多，我感觉偏离两个px把 0 的标线露出来就行 ：P

**Comment by a521king** [comment]
![image](https://user-images.githubusercontent.com/48672417/80067206-ffefef80-856f-11ea-9871-548866add31c.jpg)
实现上述设计。电脑上不能发图片，刚发现手机可以。
回答第一个问题：是的，只在数据点的位置显示分隔线

**Comment by wf123537200** [comment]
明白了，这个问题不在于说没有展示对，应该是配置问题，导致x轴少了
![image](https://user-images.githubusercontent.com/5130528/80071872-f36f9500-8577-11ea-8297-7dd67e212e4b.png)
这样试试
![image](https://user-images.githubusercontent.com/5130528/80071897-02564780-8578-11ea-854b-b2decf74c7bf.png)

**Comment by a521king** [comment]
你说的这个问题不是我上面提问的，不过我都没发现还有这个问题。
其实我最终目的就是想实现上面那个设计图。
![image](https://user-images.githubusercontent.com/48672417/80077194-be674080-857f-11ea-8f1c-5a724b10a756.jpg)

**Comment by a521king** [comment]
都是根据数据来动态展示的

**Comment by wf123537200** [comment]
解决了上面那个问题以后，用函数处理[interval](https://echarts.apache.org/zh/option.html#xAxis.splitLine.interval)
就可以搞定吧？

**Comment by a521king** [comment]
你是说 xAxis.splitLine. interval 的 回调函数吗 (index:number, value: string) => boolean ？这个不是只对类目轴有用吗

**Comment by a521king** [comment]
我显示标签还是用的 axisLabel.formatter 而不是interval ,是我用错了？

**Comment by wf123537200** [comment]
我觉得没错，我理解你的意思是要把x轴的grid也稀疏分布？
这个我还真没找到好办法，可以@下大佬看看？

**Comment by a521king** [comment]
好的，谢谢

**Comment by a521king** [comment]
下载此处的代码示例https://github.com/wf123537200/incubator-echarts/tree/2c35a29e1de87d2d1f0a19cd01f790f8c6a9c06d  ，查看test / axis-interval-splitLine.html

，发现效果没有变化，showAsAxis: true,没有起到作用？？

**Comment by wf123537200** [comment]
要进入开发模式，npm run watch，编译出dist目录下的echart.js，只改动了源码，没有提交echart.js，另外是在 feat-12456 分支下

**Comment by a521king** [comment]
ok,非常感谢！

**Comment by wf123537200** [comment]
如果紧急需要的话，可以先直接拿那段代码用

**Comment by a521king** [comment]
好的
