### ISSUE TITLE
官方文档中英文描述不一致

### ISSUE THREAD

**Issue by hejun200613224** [apache/incubator-echarts#12460]
### Version
4.7.0

### Steps to reproduce
中文版文档#series-map.nameMap.selectedMode
https://echarts.apache.org/zh/option.html#series-map.nameMap.selectedMode

英文版#series-map. selectedMode
https://echarts.apache.org/en/option.html#series-map.selectedMode

两处关于series-map下selectedMode参数的位置描述不一致，经过测试确认中文版文档有误。

### What is expected?
selectedMode参数位于
series-map.selectedMode

### What is actually happening?
selectedMode位于
series-map.nameMap.selectedMode

---
geo.selectedMode参数在中英文文档下有相似错误。
英文版
https://echarts.apache.org/en/option.html#geo.selectedMode
中文版
https://echarts.apache.org/zh/option.html#geo.nameMap.selectedMode

**Comment by susiwen8** [comment]
@hejun200613224 Thanks for pointing out, Could you make a PR for this?

**Comment by hejun200613224** [comment]
Yeah, I did. Please check it
https://github.com/apache/incubator-echarts-doc/pull/93

**Comment by Ovilia** [comment]
Thanks for your contribution. I've merged the PR. The document on the Website will be updated later.
