### ISSUE TITLE
visualMap.calculable 拖拽的手柄为什么是三角形的？可以更改样式吗？

### ISSUE THREAD

**Issue by Jazxc** [apache/incubator-echarts#12470]
visualMap.calculable 拖拽的手柄为什么是三角形的？
手柄可以像dataZoom-slider. handleIcon    ###那样更改样式吗？找不到可以配置项😂

**Comment by susiwen8** [comment]
如果没有配置项那应该就是不支持，有兴趣的话可以尝试自己解决下？

**Comment by Jazxc** [comment]
> 如果没有配置项那应该就是不支持，有兴趣的话可以尝试自己解决下？

@susiwen8 你好，请问自己尝试解决的方式是？我的需求是做成一般滑块的样式，不需要矩形外边的三角形

**Comment by susiwen8** [comment]
@Jazxc 我的意思是你可以尝试改源码，提个PR

**Comment by Jazxc** [comment]
> @Jazxc 我的意思是你可以尝试改源码，提个PR

😂好的 ，谢谢你
