### ISSUE TITLE
当series存在多个飞线图时，不同lines下effect中的trailLength(尾迹长度)会互相影响

### ISSUE THREAD

**Issue by znn0105** [apache/incubator-echarts#12479]
### Version
4.2.1
### Steps to reproduce
series里同时存在多个type为lines的对象，effect里的trailLength(尾迹长度)会被共用

### What is expected?
多个lines同时存在时，可以分别设置不同的trailLength尾迹长度

### What is actually happening?
只要其中一个lines的trailLength不为0，其他lines的trailLength 即使设置为0也无效

**Comment by znn0105** [comment]
https://gallery.echartsjs.com/editor.html?c=xK85XdQJZO&v=2

**Comment by alex2wong** [comment]
修改配置即可： https://gallery.echartsjs.com/editor.html?c=xK85XdQJZO&v=3 
参考文档：https://echarts.apache.org/zh/option.html#series-lines.effect
所有带有尾迹特效的图表需要单独放在一个层，也就是需要单独设置 zlevel。当然如果不同的 trailLength Effect lines 系列，需要设置不同的 zlevel，以方便 canvas 去做不同的 trailLength 渲染。

```
{
            type:"lines",
            coordinateSystem: "cartesian2d",
            lineStyle:{
              width:0
            },
            zlevel:3,   // 与第一个 Effect 系列不同的 zlevel 即可
            effect:{
              show:true,
              symbol:"circle",
              symbolSize:4,
              color:"#23E0FF",
              trailLength:0.4
            },
            data:[
              {name:"lyxtLine1",coords:[[73,48],[73,75]]},
              {name:"lyxtLine2",coords:[[75,38],[75,65]]},
              {name:"lyxtLine3",coords:[[95,23],[95,50]]},
              {name:"lyxtLine4",coords:[[135,35],[135,75]]},
              {name:"lyxtLine5",coords:[[120,55],[120,83]]},
              {name:"lyxtLine6",coords:[[142,45],[142,65]]},
            ]
          }
```
具体源代码参考：
https://github.com/apache/incubator-echarts/blob/master/src/chart/lines/LinesView.js#L67

**Comment by alex2wong** [comment]
由于一段时间不活跃，关闭此 issue，有问题请随时重开 @znn0105
