### ISSUE TITLE
angular项目使用dataZoom后鼠标在图标中时页面无法滚动

### ISSUE THREAD

**Issue by oldYan** [apache/incubator-echarts#12486]
angular： 8.2.x
echarts：4.6.0
ngx-echarts: 4.2.2

一个有四个echarts实例，进行了图表联动。
每个echarts都设置了如下属性：
 dataZoom : {
    {
        type: 'inside',
        realtime: true,
        start: 0,
        end: 100,
        zoomOnMouseWheel: 'ctrl',
        moveOnMouseMove: 'ctrl',
        moveOnMouseWheel: 'ctrl',
        preventDefaultMouseMove: false
      }
}
这种情况下，当鼠标置于图表中进行滚轮滚动时，页面无法滚动，已经设置'ctrl' + 鼠标滚轮滚动才触发缩放事件（可正产触发），是否阻止了鼠标滚轮的事件冒泡。请问应该如何处理呢？

**Comment by XUKEZXZ** [comment]
你好，你有解决这个问题吗
