### ISSUE TITLE
xAxis.axisLabel 长度过长怎么控制？可以限制宽度吗？

### ISSUE THREAD

**Issue by Jazxc** [apache/incubator-echarts#12483]
可以设定一定宽度显示么？
类似 legend 文字很多的时候对文字做裁剪并且开启 tooltip 或者 限制图例的整体宽度
不知道xAxis.axisLabel 是否可以限制宽度呢？

**Comment by agnij** [comment]
长度过长你可以自己去截取换行或者用旋转lable角度
