### ISSUE TITLE
https://echarts.apache.org/ 网址的访问实在是太慢了！

### ISSUE THREAD

**Issue by MrZWH** [apache/incubator-echarts#12488]
### What problem does this feature solve?
中国区访问官网的体验。

### What does the proposed API look like?
访问快一点就行了。

**Comment by pissang** [comment]
可以提供下你所在的城市以及使用的网络服务商么？

**Comment by Ovilia** [comment]
请问是经常很慢吗？

**Comment by housemecn** [comment]
The ssl certificate has also expired. Please update it as soon as possible.

**Comment by plainheart** [comment]
相较于几乎可以秒开的 https://www.echartsjs.com ，https://echarts.apache.org 的访问速度确实很慢。
我这里的网络环境是200M电信，公司的千兆联通网络也依然不快，所属地为河南郑州。
如果可以，还是希望可以优化下~

**Comment by 544751779** [comment]
实在是太慢 了 到了几乎大不开的地步了  


山东电信 200M带宽  访问百度秒开的
