### ISSUE TITLE
https://echarts.apache.org/ 示例网站 SSL 证书已过期

### ISSUE THREAD

**Issue by iamapig120** [apache/incubator-echarts#12502]
### Version
4.7.0

### Steps to reproduce
1. 访问 https://echarts.apache.org/
2. 提示证书已在 2020 年 4 月 24 日过期

### What is expected?
SSL 证书已过期

### What is actually happening?
应使用未过期的证书

**Comment by pissang** [comment]
谢谢反馈，问题正在跟进中 https://issues.apache.org/jira/browse/INFRA-20185

**Comment by iamapig120** [comment]
> 谢谢反馈，问题正在跟进中 https://issues.apache.org/jira/browse/INFRA-20185

已修复，或许可以 close 了
