### ISSUE TITLE
text-block-fragment fail to load

### ISSUE THREAD

**Issue by antimonyGu** [apache/incubator-echarts#12514]
### Version
4.7.0

### Reproduction link
[https://www.echartsjs.com/examples/en/editor.html?c=doc-example/text-block-fragment](https://www.echartsjs.com/examples/en/editor.html?c=doc-example/text-block-fragment)

### Steps to reproduce
In chinese document click the link [link](https://www.echartsjs.com/examples/en/editor.html?c=doc-example/text-block-fragment). An error occurs 
```
/examples/data/doc-example/text-block-fragment.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)```

### What is expected?
can see and edit example

### What is actually happening?
404 error

<!-- This issue is generated by echarts-issue-helper. DO NOT REMOVE -->
<!-- This issue is in English. DO NOT REMOVE -->

**Comment by 100pah** [comment]
A typo to:
https://www.echartsjs.com/examples/en/editor.html?c=doc-example/text-block-fregment
