### ISSUE TITLE
Echart Public Gallery website is down

### ISSUE THREAD

**Issue by rushtokunal** [apache/incubator-echarts#12520]
### Version
4.7.0

### Steps to reproduce
try to open https://gallery.echartsjs.com/explore.html

### What is expected?
should display all the community examples

### What is actually happening?
the website is down

---
community gallery website is down

**Comment by susiwen8** [comment]
Don't have this problem for me

**Comment by wf123537200** [comment]
@susiwen8 May be the picture server hangs？
![image](https://user-images.githubusercontent.com/5130528/80552978-cfd69f80-89fa-11ea-95b4-d4323af46258.png)

**Comment by rushtokunal** [comment]
I am not even able to load the webpage for public gallery
![image](https://user-images.githubusercontent.com/10759449/80553286-da5b4f80-898e-11ea-97eb-dceabe6bac59.png)

**Comment by susiwen8** [comment]
@rushtokunal Could you add galleray.echartsjs.com ip to your host?

**Comment by Ovilia** [comment]
@rushtokunal Not reproducible on my side. Do you still have this problem?

**Comment by rushtokunal** [comment]
@Ovilia yes i still have this issue, the domain https://www.echartsjs.com/ is un reachable. i'm trying to access from USA, i have tried from multiple devices, but im able to access the apache domain https://echarts.apache.org/

**Comment by Ovilia** [comment]
@rushtokunal Thanks for reporting. We will check it out.
Please use Apache domain as ECharts website. If you need to provide an online demo, you can use this [codepen template](https://codepen.io/Ovilia/pen/dyYWXWM) for now.

**Comment by 100pah** [comment]
Recovered. Sorry for that incident. Could you try it again?

**Comment by rushtokunal** [comment]
Thank you im able to access the public gallery now. Just curious to know what had happened

**Comment by 100pah** [comment]
@rushtokunal An idiot mistake, the domain expired at that time.

**Comment by rushtokunal** [comment]
the domain has expired again

**Comment by thomaspessato** [comment]
Not working again.
