### ISSUE TITLE
The site gallery.echartsjs.com can’t be reached

### ISSUE THREAD

**Issue by JavaTMP** [apache/incubator-echarts#12542]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all)

### Steps to reproduce
Go to https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all

### What is expected?
a gallery site containing great demo and examples

### What is actually happening?
The site gallery.echartsjs.com can’t be reached

---
Does the site moved or in a maintenance ?

**Comment by susiwen8** [comment]
Thanks for reporting, we were informed by #12520

**Comment by JavaTMP** [comment]
We can now access the gallery.echartsjs.com
 #12520
