### ISSUE TITLE
动态数据 时间坐标轴，以秒为最小单位时，每分钟的前10秒数据未被绘制

### ISSUE THREAD

**Issue by zpf96126** [apache/incubator-echarts#12545]
### Version
4.7.0

### Reproduction link
[https://www.echartsjs.com/examples/zh/editor.html?c=dynamic-data2](https://www.echartsjs.com/examples/zh/editor.html?c=dynamic-data2)

### Steps to reproduce
将随机数值函数修改为
function randomData() {
    now = new Date();
    value = value   Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth()   1, now.getDate()].join('/') " " [now.getHours(), now.getMinutes(), now.getSeconds()].join(':'),
            Math.round(value)
        ]
    };
}
将格式化日期修改为
    tooltip: {
        trigger: 'axis',
        formatter: function (params) {
            params = params[0];
            var date = new Date(params.name);
            return date.getDate()   '/'   (date.getMonth()   1)   '/'   date.getFullYear() ' ' date.getHours()   ':'   date.getMinutes()   ':'   date.getSeconds()   ' : '   params.value[1];
        },
        axisPointer: {
            animation: false
        }
    },

### What is expected?
能够按秒显示动态数据折线

### What is actually happening?
每分钟的前10秒会卡住，然后不绘制这段时间内的折线

**Comment by 100pah** [comment]
`randomData` 里使用的是 new Date()
所得到的值是不确定的值。所以并不确定形成的数据在哪个时间点上。

**Comment by zpf96126** [comment]
我把function randomData() {
now = new Date();
value = value Math.random() * 21 - 10;
return {
name: now.toString(),
value: [
[now.getFullYear(), now.getMonth() 1, now.getDate()].join('/') +" "+ [now.getHours(), now.getMinutes(), now.getSeconds()].join(':'),
Math.round(value)
]
};
}
改成
function randomData() {
now = new Date();
value = value Math.random() * 21 - 10;
var ds;
if (now.getSeconds()< 10) {
      ds = "0" + now.getSeconds().toString();
 } else {
      ds = now.getSeconds().toString();
 }
return {
name: now.toString(),
value: [
[now.getFullYear(), now.getMonth() 1, now.getDate()].join('/')+ " "+ [now.getHours(), now.getMinutes(), ds].join(':'),
Math.round(value)
]
};后正常了
}
