### ISSUE TITLE
Dataview 编辑数据之后重新渲染出错

### ISSUE THREAD

**Issue by xkKevin** [apache/incubator-echarts#12560]
### Version
4.3.0

### Steps to reproduce
点击数据视图删除某一行（如删除“美国	15276”）之后，重新绘制的pie chart把最后一行的name（即“其他”）删除了，“美国”还在，所有的数据也都错乱了（国家与数值没有对应），

### What is expected?
在删除某一行之后，重新绘制图形，如 删除“美国	15276”这一行之后，饼图中不出现美国。

### What is actually happening?
删除“美国	15276”这一行数据之后，只是删除了15276这个数据，但美国还在，而且其他国家的数据已经错乱了。

---
// my Code

var data = [{"name": "美国", "value": 15276.0}, {"name": "英国", "value": 4855.0}, {"name": "法国", "value": 3291.0}, {"name": "意大利", "value": 3157.0}, {"name": "西班牙", "value": 2859.0}, {"name": "巴西", "value": 1662.0}, {"name": "其他", "value": 5152.0}];
let name = "各国累计死亡人数"; 

option = {
	toolbox: {
		feature: {
		    dataView:{
		      readOnly: false  
		    },
		    restore:{},
			saveAsImage: {
				name: name
			}
		}
	},

	tooltip: {
		trigger: 'item',
		formatter: '{a} <br/>{b} : {c} ({d}%)'
	},
	series: [{
		name: name,
		type: 'pie',
		data: data,
		radius: '50%',
		clockwise: false, // 逆时针排序
		label: {
			formatter: "{b} : {num|{c}} | {rate|{d}%}",
			color: "black",
			fontSize: 20,
			rich: {
				num: {
					fontSize: 22,
					fontWeight: 'bold',
					color: "black"
				},
				rate: {
					fontSize: 22,
					fontWeight: 'bold',
					color: "black"
				},
				symbol: {
					fontSize: 22,
					color: "black"
				}
			}
		},
		emphasis: {
			itemStyle: {
				shadowBlur: 10,
				shadowOffsetX: 0,
				shadowColor: 'rgba(0, 0, 0, 0.5)'
			}
		}
	}]
};

**Comment by plainheart** [comment]
Hi~, It seems to be a bug, you can refer to #12561 for details.
