### ISSUE TITLE
多语言切换

### ISSUE THREAD

**Issue by jearay** [apache/incubator-echarts#12566]
### What problem does this feature solve?
无刷新，快速切换图形语言。
现在多数项目都已国际化，存在多国语言切换场景。
目前ECharts从脚本源码看，目前可以通过自定义打包支持5种语言。 官方封装的是中文和英文两种语言。
但是，从API等手册上，无法查阅到，Echarts内部是否有封装多语言切换的函数。
目前，只能通过其他的方式，曲线救国，达到多语言切换。
所以，想知道一下，Echarts现在是否已经存在多语言切换的内置功能？只是没有开放出来，或者是没有？是否可以封装一下？或者告知一个比较高效间接的方式。

### What does the proposed API look like?
可以通过url参数或者toolbox工具或者其他的任何方式，可以高效快速实现，网页内无刷新动态切换多语言。
实在不行，刷新的也OK！

**Comment by susiwen8** [comment]
Sorry, we cannot switch language, but this has been planned to implement in 5.0
Similar to #7451
