### ISSUE TITLE
scatter with geo map positioning error after zooming

### ISSUE THREAD

**Issue by blacksider** [apache/incubator-echarts#12579]
### Version
4.6.0 

### Reproduction link
[https://codepen.io/macarro59200001/pen/GRpQGay](https://codepen.io/macarro59200001/pen/GRpQGay)

### Steps to reproduce
Im using scatter with geo map, with all settings i set in given codepen link above.
There are two bugs i found(maybe i didn't use it properly).

### What is expected?
scatter and scale should set correctly

### What is actually happening?
1:  If I change geo->zoom with a button, and call echartsInstance.setOption(opts...), scatter is zooming, but not the geo map.  

2:  After i zoom the view, the scatter is not  re-rendered with  correct position

**Comment by blacksider** [comment]
I just try 4.7.0, looks like that version is working, any idea what should i do with 4.6.0 ? or i just have to upgrade to 4.7.0?

**Comment by Ovilia** [comment]
If 4.7.0 works fine, you should definitely upgrade. Please close this issue if 4.7.0 is ok.
Thanks!
