### ISSUE TITLE
Graph does not support Datazoom?

### ISSUE THREAD

**Issue by 2675569545** [apache/incubator-echarts#12570]
### Version
4.7.0

### Reproduction link
[https://codepen.io/David_Guan/pen/WNQdqqr](https://codepen.io/David_Guan/pen/WNQdqqr)

### Steps to reproduce
//中文描述
如果你将代码第66行的"scatter"更换为"graph"，页面将会一片空白
// English problem description
If you replace the scatterer in line 66 with graph, the page will be empty

### What is expected?
// English problem description
I have nearly 10,000 elements to show their relationships, and I can't see anything if I just use the “graph” type. I want to control the display of the data by using the Datazoom.Or provide a way to show relationships clearly while keeping the volume of data
//中文描述
我有将近一万个元素要展示他们之间的关系，如果只用关系图将会什么也看不清，我想通过datazoom来控制数据的显示。或者在保持数据量的前提下提供一种清晰展示关系的方法

### What is actually happening?
// English problem description
The page doesn't show anything
//中文描述
页面什么也不显示

**Comment by Ovilia** [comment]
`dataZoom` is not supposed to be used with graph. I think #12567 may have solved your request.

**Comment by 2675569545** [comment]
> `dataZoom` is not supposed to be used with graph. I think #12567 may have solved your request.

Hello,I want to ask you set `series.zoom` and `series.center`,Are they new features that are not yet supported or do they already support no documentation.If it's just a lack of documentation, can you tell me how it should be used in my example

**Comment by Ovilia** [comment]
They are missing in the document. It's available here: https://github.com/apache/incubator-echarts-doc/commit/8d001e86a2190b9ebdc2f344a7820a563ed9299a

**Comment by 2675569545** [comment]
> 它们在文档中丢失。在此处可用：[apache / incubator-echarts-doc @ 8d001e8](https://github.com/apache/incubator-echarts-doc/commit/8d001e86a2190b9ebdc2f344a7820a563ed9299a)

I'm sorry. Is that it
option={
...
	series: [{
	            type: 'graph',
	            layout: 'force',
	            .......
	            zoom:[3.97,3.71],
	            ......}]
}
If this is the case, the page will not display

**Comment by Ovilia** [comment]
Yes, but `zoom` should be a number rather than an array.

**Comment by 2675569545** [comment]
> 是的，但是`zoom`应该是数字而不是数组。

Excuse me, there are a lot of nodes on the page, what is the API to get the coordinate axis information of an element? I found this, but the new version seems to be gone。https://github.com/apache/incubator-echarts/issues/225

**Comment by 2675569545** [comment]
> Yes, but `zoom` should be a number rather than an array.

Excuse me, there are a lot of nodes on the page, what is the API to get the coordinate axis information of an element? I found this, but the new version seems to be gone.
https://github.com/apache/incubator-echarts/issues/225

**Comment by Ovilia** [comment]
@2675569545 https://echarts.apache.org/zh/api.html#echartsInstance.convertToPixel

**Comment by 2675569545** [comment]
> @2675569545 https://echarts.apache.org/zh/api.html#echartsInstance.convertToPixel

Thank you .Have a good day~
