### ISSUE TITLE
A false label on tutorial

### ISSUE THREAD

**Issue by OrangeSAM** [apache/incubator-echarts#12572]
### Version
4.7.0

### Reproduction link
[https://echarts.apache.org/en/tutorial.html#ECharts%20Basic%20Concepts%20Overview](https://echarts.apache.org/en/tutorial.html#ECharts%20Basic%20Concepts%20Overview)

### Steps to reproduce
open the link, and slide the page to component section, you'll find there two tooltip component on the image, i think one of them should be toolbox component. 
see also in this image https://sm.ms/image/9PQT1Ulu3JL4Ytz

### What is expected?
i think  the right 'tooltip component' should rename to 'toolbox component'. 

### What is actually happening?
display 'tooltip component'

**Comment by plainheart** [comment]
Fixed in https://github.com/apache/incubator-echarts-doc/commit/2caef3177a5c67381db471acd29e372a8f8761af
