### ISSUE TITLE
graph preview component

### ISSUE THREAD

**Issue by 2675569545** [apache/incubator-echarts#12578]
### What problem does this feature solve?
//English desc 
As the amount of data increases, the number of elements in the page increases. When the screen is filled with DOTS, there is no way to begin with so many elements. I want to define a list component on the left side of the Echarts, which is the same as the echarts graph data source. When you click on a piece of data in a list component, the corresponding element in echarts moves to the center or highlights, etc. . Now I need a corresponding echarts method to move an element to the center or highlight it (preferably the echarts screen moves over and highlights it, because of the amount of data, rendering again should be slow)
//中文描述
随着数据量的加大，页面中元素越来越多。当屏幕中充满着小圆点的时候，对于这么多元素无从下手。我想在echarts左侧定义一个列表组件，数据源和echarts图形数据源一样。当点击列表组件中的某条数据时，echarts中对应的元素移动到中央或者高亮显示等。现在我需要一个对应的echarts方法可以将某个元素移动到中央或者高亮显示（最好是echarts屏幕移动过去，高亮显示，因为数据量大，再次渲染应该会很慢）

### What does the proposed API look like?
//English desc 
I want API to be able to locate and select one of the tens of thousands of nodes in Ecars, highlight it or have something else I can see at a glance 
//中文描述 
我希望他可以定位选中将echars中数万个的节点的某一个节点，可以高亮显示或者有其他让我一眼看到的效果

**Comment by Ovilia** [comment]
@2675569545 This feature is currently not supported and we do not have plan to support in a short term. Keep this open if the community wants to contribute.

**Comment by 2675569545** [comment]
> @2675569545 This feature is currently not supported and we do not have plan to support in a short term. Keep this open if the community wants to contribute.

Thanks for your reply.Have a good day at work.
