### ISSUE TITLE
Error transforming bundle with 'uglify' plugin: Unexpected token: keyword «const»

### ISSUE THREAD

**Issue by everygit** [apache/incubator-echarts#12603]
### Version
4.7.0

### Steps to reproduce
yarn build --release

### What is expected?
可以生产echarts.min.js

### What is actually happening?
Bundles  D:\sunbt\incubator-echarts\echarts.all.js => D:\sunbt\incubator-echarts\dist\echarts.min.js  ...
Error: Error transforming bundle with 'uglify' plugin: Unexpected token: keyword «const»

**Comment by plainheart** [comment]
You can replace it manually at now. It has been fixed in `release` branch. Related commit is https://github.com/apache/incubator-echarts/commit/0f9f38b68793b1d225e07b4fbfb082446454367e
, may will be merged into `master` branch soon.

**Comment by everygit** [comment]
> You can replace it manually at now. It has been fixed in `release` branch.
> Related commit is [0f9f38b](https://github.com/apache/incubator-echarts/commit/0f9f38b68793b1d225e07b4fbfb082446454367e), may will be merged into `master` branch soon.

thanks
