### ISSUE TITLE
Plot the variance of signals

### ISSUE THREAD

**Issue by mkersche17** [apache/incubator-echarts#12605]
Hello, 

I want to plot the variance of multiple signals in a chart.
Is that possible to create such kind of charts?

![image](https://user-images.githubusercontent.com/10856645/81534009-888bcf80-9367-11ea-90af-50a356e9f38c.png)

I saw the confidence-band example, however this seems to work only for one signal in a chart. 
Another solution would be to draw thousands of small rectangles using markArea around the signals but this slows down the performance of the chart (e.g. when scrolling the x-axisis) and doesnt look very smooth.

**Comment by tomsoftware** [comment]
this is not supported yet - see: #12592
