### ISSUE TITLE
Tooltip renderMode richText doesn't have dispose

### ISSUE THREAD

**Issue by IndProgo** [apache/incubator-echarts#12607]
### Version
4.7.0

### Reproduction link
[https://codesandbox.io/s/echarts-tooltip-richtext-dispose-2u1y4](https://codesandbox.io/s/echarts-tooltip-richtext-dispose-2u1y4)

### Steps to reproduce
Press Dispose chart button

### What is expected?
No error

### What is actually happening?
Disposing chart which uses renderMode richText for Tooltip will throw  TypeError this._tooltipContent.dispose is not a function

**Comment by plainheart** [comment]
Yes. It can be confirmed that `TooltipRichContent` doesn't have `dispose` method. I'm trying to add it.
