### ISSUE TITLE
 when renderItem return a line item and set stroke, the stroke color will cover line series lineStyle.color setting

### ISSUE THREAD

**Issue by llcat** [apache/incubator-echarts#12612]
### Version
4.1.0-release

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xxSlx3B-Op&v=1](https://gallery.echartsjs.com/editor.html?c=xxSlx3B-Op&v=1)

### Steps to reproduce
please see reproduct link。
1. when not add custom series, the line series lineStyle.color is as mine setting.
2. add custom series and return a line item, and set stroke color, the line series use the stroke color

### What is expected?
the line series lineStyle.color not effect by the stroke color

### What is actually happening?
the line series lineStyle.color use the custom series stroke color

**Comment by plainheart** [comment]
Sorry, there is a typo in you first series (not `rbg` but should be `rgb`) and that's why you have got an unexpected result.

**Comment by llcat** [comment]
@plainheart sorry!, I really careless!
