### ISSUE TITLE
What is the standard for echarts to draw mapsOr based on what data is drawn? Thanks

### ISSUE THREAD

**Issue by MuXinCoder** [apache/incubator-echarts#12623]
### What problem does this feature solve?
Hi,Now I want to use echarts to draw a map of China,But the drawing standard of the map is relatively high,High accuracy is required.

### What does the proposed API look like?
Under unnecessary conditions, do not want to make any changes to the existing API.

**Comment by pissang** [comment]
Hi @MuXinCoder I will suggest you using Baidu Map extension if you have a very strict standard.
