### ISSUE TITLE
极坐标系  堆叠柱状图  标签无法显示

### ISSUE THREAD

**Issue by cysgbrlc** [apache/incubator-echarts#12632]
### Version
3.8.3

### Steps to reproduce
option = {
    tooltip:{},
    angleAxis: {
        type: 'category',
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
    },
    radiusAxis: {
    },
    polar: {
    },
    series: [{
        type: 'bar',
        data: [1, 2, 3, 4, 3, 5, 1],
        coordinateSystem: 'polar',
        label:{
            normal:{
                show:true,
                position:"inside"
            }
        },
        name: 'A',
        stack: 'a'
    }, {
        type: 'bar',
        data: [2, 4, 6, 1, 3, 2, 1],
        coordinateSystem: 'polar',
        name: 'B',
         label:{
            normal:{
                show:true,
                position:"inside"
            }
        },
        stack: 'a'
    }, {
        type: 'bar',
        data: [1, 2, 3, 4, 1, 2, 5],
        coordinateSystem: 'polar',
         label:{
            normal:{
                show:true,
                position:"inside"
            }
        },
        name: 'C',
        stack: 'a'
    }],
    legend: {
        show: true,
        data: ['A', 'B', 'C']
    }
};

### What is expected?
希望堆叠的柱子内部出现标签

### What is actually happening?
没用一个柱子内部出现标签

**Comment by yufeng04** [comment]
According to the [document](https://echarts.apache.org/zh/option.html#series-bar.coordinateSystem), polar coordinates are not supported.
