### ISSUE TITLE
Colorize the line between categories

### ISSUE THREAD

**Issue by RomanOlegovich** [apache/incubator-echarts#12635]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xMxKcaockv&v=1](https://gallery.echartsjs.com/editor.html?c=xMxKcaockv&v=1)

### Steps to reproduce
```
option = {
    xAxis: {
        type: 'category'
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [[0,0,100],[1,3,101],[2,2,102], [5,2,105], [10,5,110]],
        type: 'line',
        itemStyle: {color: "black"}
    }],
    visualMap:{
        type: 'piecewise',
        inRange: {color: "red", symbolSize:10},
        outOfRange: {color: "black"},
        min: 102,
        max: 105,
        dimension: 2,
    }
};

```

### What is expected?
Highlight the line between categories.

I need to draw data on the x-axis at the same distance regardless of the value, so I use the "category" axis. I also need to highlight the line between the data. The axis type of the "value" allows to do this, but it does not display data at the same distance.

### What is actually happening?
Highlight points only.

**Comment by yufeng04** [comment]
Could you try this [example](https://echarts.apache.org/examples/zh/editor.html?c=line-aqi)?

**Comment by plainheart** [comment]
Could I know the meaning of each dimension of data in line series?

**Comment by RomanOlegovich** [comment]
@plainheart 
1) category
2) value
3) ordered values ​​(index).
I want to highlight a line from a category with index X to a category with index Y

**Comment by RomanOlegovich** [comment]
@yufeng04 
Of course. There is a selection along the Y axis. And I need to select a line between specific categories

**Comment by RomanOlegovich** [comment]
> Could I know the meaning of each dimension of data in line series?

1. category
2. value
3. ordered values ​​(index).
I want to highlight a line from a category with index X to a category with index Y

**Comment by RomanOlegovich** [comment]
> Could you try this [example](https://echarts.apache.org/examples/zh/editor.html?c=line-aqi)?

@yufeng04
Of course. There is a selection along the Y axis. And I need to select a line between specific categories

**Comment by RomanOlegovich** [comment]
Data:
data: [[0,1], [1,1], [2,1], [3,1], [4,1], [5,1]]
Filtered via zoom:
data: [[0,1], [2,1], [4,1]].
I can’t use "dimension: 0" because if select {min:1, max:2}, then the wrong categories will be highlighted in the filtered data:
expected highlighted data: [[0,1], **[1,1], [2,1],** [3,1], [4,1], [5,1]]
actually highlighted data: [[0,1], **[2,1], [4,1]**].

**Comment by plainheart** [comment]
Maybe this is a new feature but not a bug.
From the source code, we can get a tip in `getVisualGradient` method at [line 163](https://github.com/apache/incubator-echarts/blob/master/src/chart/line/LineView.js#L132)  below
https://github.com/apache/incubator-echarts/blob/baa6ea6e77e40359e70f094f87c28fb618e26897/src/chart/line/LineView.js#L132-L166
```js
Visual map on line style only support x or y dimension.
```
The dimension is `value` in you case, so the right result has gone.
Currently, it seems that data can only be [x, y] or [value...] but not [x, y, another dimension...]
Just Like the [example](https://echarts.apache.org/examples/zh/editor.html?c=line-aqi) above.

**Comment by Ovilia** [comment]
If you wish to colorize it using x series data. The `dimension` of should be `0` rather than `2` in your demo. See https://gallery.echartsjs.com/editor.html?c=xMxKcaockv&v=4 .

**Comment by RomanOlegovich** [comment]
Thanks, I realized that the only way is to use dimension 0.
