### ISSUE TITLE
how to solve this !!

### ISSUE THREAD

**Issue by Rranjansolenoid** [apache/incubator-echarts#12649]
Suppose you have a piece of paper in the shape of a circle, with a circumference of 8 feet. (It’s a pretty large piece of paper!) Now you fold the circle in half to produce a semi-circle; then fold that over to produce a quarter-circle; then fold that to produce an eight-size wedge of a circle; and so forth. How many folds (assuming, counterfactually, that the paper could withstand this) would it take before the edge of the remaining wedge is less than 0.01 inch?

**Comment by plainheart** [comment]
@Rranjansolenoid Hi, I'm not sure whether this issue is related to `echarts` or not and it was closed for not using [issue template](https://ecomfe.github.io/echarts-issue-helper/).
It seems to be a mathematical problem. There are some example codes for you.
```js
// circumference of the circle
let c = 8 * 12; // feet to inch

// the radius of circle
let r = c / (2 * Math.PI);

// target arc length we want to get
let targetArcLength = 0.01;

// the arc length of circle
let arcLength = c;

// fold count
let foldCount = 0;

// the center angle of circle
let circleCenterAngle = 360;

// loop until the arc length is less than 0.01
while(arcLength >= 0.01) {
	// calculate the center angle of circle by foldCount
	circleCenterAngle = 360 * Math.pow(2, -foldCount);
	// calculate the arc length(arcLength = nπr / 180)
	arcLength = circleCenterAngle * Math.PI * r / 180.0;
	// increases the foldCount
	++foldCount;
}

console.log('foldCount', foldCount)
```
Run it and then we can get the result `foldCount 15`. Is it expected?

**Comment by SajjadNawaz** [comment]
14 folds.

Step-by-step explanation:

1 fold will cut the 8 feet to 4 feet.

2. 2 feet

3. 1 feet

4. 6 inch

5. 3 inch

.

.

.

14. 0.005 inch which is less than 0.01 inch
