### ISSUE TITLE
tooltip.axisPointer.label 设置 lineHeight 无效果

### ISSUE THREAD

**Issue by 214132049** [apache/incubator-echarts#12642]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xkb87pE09r&v=1](https://gallery.echartsjs.com/editor.html?c=xkb87pE09r&v=1)

### Steps to reproduce
tooltip.axisPointer.label 设置 lineHeight 

### What is expected?
设置 lineHeight 生效

### What is actually happening?
tooltip.axisPointer.label 设置 lineHeight 无效

**Comment by susiwen8** [comment]
@214132049 Why closing this issue?

**Comment by 214132049** [comment]
@susiwen8  I did it by mistake
