### ISSUE TITLE
vs本地测试map可以正常展示，部署到iis后一直loading

### ISSUE THREAD

**Issue by cocoyzs** [apache/incubator-echarts#12652]
### Version
4.7.0

### Steps to reproduce

本地调试柱状图，折线图，地图均能正常显示，放到iis发布后只有折线图和柱状图可以正常显示，唯独map一直loading状态，没有任何报错，实在不知什么原因了，请教各位大神有谁碰到这个情况？

### What is expected?
map在iis下正常显示

### What is actually happening?
map在iis下一直显示loading

---
开发环境：vs2012
echars：官网下载最新echars.js
iis是win2008上面的iis7，.net4.0经典模式

**Comment by plainheart** [comment]
Map是不是引入了一些geoJSON文件？如果是请确保引用的资源地址没有跨域。

**Comment by cocoyzs** [comment]
已经找到原因，是引入的geojson文件在iis中无法访问得到，iis对json整个目录都无法访问，包括该目录下的html文件，别的目录没有问题，不懂为什么，
system.webserver中添加节点
<staticContent>
   <mimeMap fileExtension=".json" mimeType="application/json" />
</staticContent>
之后就正常显示了。
