### ISSUE TITLE
自定义柱状图每个category的series顺序

### ISSUE THREAD

**Issue by Chellhooo** [apache/incubator-echarts#12660]
### What problem does this feature solve?
你好~ 我想问一下柱状图可以提供在每个横坐标定义不同series顺序吗？现在从文档看来，柱状图上每个横坐标上的bar顺序都是相同。

使用情景：比如柱状图的横坐标是日期且有多个legend，希望每个横坐标(即每天)上的柱状图都能按从大到小排列，这样子可以让用户能更快找到每一天的最大值是哪个legend。

如果是文档上已经有实现方法，麻烦希望能告诉我解决方法，非常谢谢~  
(希望我有表达清楚了我的问题~)

hi~ I'm finding a way to custom series order in in each xAxis category, which may help user to find out the legend of maximum/minimum in each category.
In bar chart, it seems that the order set in `series` will be apply to each xAxis category.
If I miss something in document, i'm so sorry and hope you to show me the way.

### What does the proposed API look like?
1. 如果需要为echarts提供已经排好序的数据，可能提供一个更为直接的dataset？e.g. `[ {columns:[], rows:[]}, {} ]`
2. 或者提供类似 dataOrder 的选项，使每个category 的bar 都以相应的顺序展示

暂时没有更好的想法

**Comment by Ovilia** [comment]
不支持这一功能，暂时也没有计划支持。如果一定需要的话，比较简单的做法是，自己 hack 一下，实际传入的 data 是排好序的不同系列的，并且每个柱子用对应真实的系列颜色设置。

**Comment by Chellhooo** [comment]
好的谢谢~
