### ISSUE TITLE
教程有个小错误

### ISSUE THREAD

**Issue by pg-cat** [apache/incubator-echarts#12675]
ECharts 4 以前，数据只能声明在各个“系列（series）”中，例如：
===========================
在此句的下面的例子中 yAxis: {} 后面掉了一个英文逗号 ,
如果有可能的话，option: 这里后面应该是 = 吧，而不是 : ，虽然也可以
===========================
地址：
https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE

**Comment by plainheart** [comment]
感谢反馈，有兴趣提个PR修复下吗？
这里对应的项目是：[incubator-echarts-doc](https://github.com/apache/incubator-echarts-doc)

**Comment by Wdingding** [comment]
感谢反馈，我已提交了一个修复：
https://github.com/apache/incubator-echarts-doc/commit/019995d660dff8d523a8ad7f21c659f5285d8c6b
