### ISSUE TITLE
教程例子缺失标点

### ISSUE THREAD

**Issue by pg-cat** [apache/incubator-echarts#12683]
https://echarts.apache.org/zh/tutorial.html#%E6%95%B0%E6%8D%AE%E7%9A%84%E8%A7%86%E8%A7%89%E6%98%A0%E5%B0%84

视觉映射方式的配置 的 例一 中 type: 'piecewise' 后面掉了一个英文逗号 ,

**Comment by plainheart** [comment]
欢迎PR~

**Comment by Wdingding** [comment]
感谢反馈，我已提交了一个修复：
https://github.com/apache/incubator-echarts-doc/commit/c3eb74dadba2b1a228531974609c0df743b4fef8

**Comment by plainheart** [comment]
@Wdingding 同样在被关闭的 #12675 中他也反馈了一些文档错误，可以一并修改下。

**Comment by Wdingding** [comment]
已修复：
https://github.com/apache/incubator-echarts-doc/commit/019995d660dff8d523a8ad7f21c659f5285d8c6b
