### ISSUE TITLE
Support for inline charts - 'sparklines'

### ISSUE THREAD

**Issue by softwords** [apache/incubator-echarts#12714]
### What problem does this feature solve?
The term 'sparkline' was first used by Edward Tufte, who defined a sparkline in this way:

_A sparkline is a small intense, simple, word-sized graphic with typographic resolution.
Sparklines mean that graphics are no longer cartoonish special occasions with captions and boxes,
but rather sparkline graphics can be everywhere a word or number can be: embedded in a sentence,
table, headline, map, spreadsheet, graphic. Data graphics should have the resolution of typography._

see https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR

In html, for a chart to be embedded as Tufte describes, then that chart must be **inline**; that is, it should have css style

`display:inline`

So in order to make a genuine sparkline with echarts, we need to be able to make the echart inline.

To attempt this, we can build the echart on an inline element - e.g. `<span>` instead of `<div>`
The first complication this creates is that an inline element cannot be given height or width; so a sparkline created with echarts will need to get its height and width from the config; e.g (using svg):

```
echarts.init(element, null, {renderer: 'svg', height: 20, width 80})
```

When echarts generates the chart, we see this in the generated html:

```
<div style="overflow: hidden; position: relative; width: 80px; height: 20px; background: transparent; cursor: pointer;">
	<svg xmlns="http://www.w3.org/2000/svg" version="1.1" baseProfile="full" width="80" height="20" style="user-select: none; position: absolute; left: 0px; top: 0px;">
```

This object is not inline, because the generated `<div>` has `display:block` by default, and the generated `<svg>` has `position:absolute`

We can use css to reach into this generated html and change it, like this:

```
<style>
.sparkline div {
	display: inline
}
.sparkline svg {
	position:relative !important
}
```

where the echart is created on a span with class sparkline:
```<span class="sparkline"/>```

In echarts 4.7, this workaround will give an inline chart. But it would be preferable to have this functionality available in echarts by configuration.

### What does the proposed API look like?

Add a new member `display` to the configuration object passed to `echarts.init()`

display : 'block' or 'inline' - default is 'block'

This setting causes the appropriate changes to the `style` attributes of the generated `<div>` and `<svg>`

e.g. sample use:

```
let config = {
	renderer: "svg",
	height: 40,
	width: 100,
	display: 'inline'
}
```

In html it will look like
```
<p>Here is my embedded<span id="mySparkline"/> echart</p>
```

where the echart is instantiated on the `<span>` _mySparkline_.

**Comment by plainheart** [comment]
Have you tried to set `display` of echarts container(element)? I think it's practical.
There is [An example on CodePen](https://codepen.io/plainheart/pen/ZEbdRdr)

**Comment by plainheart** [comment]
I think it's practical to set `display` of echarts container(element).
There is [An example on CodePen](https://codepen.io/plainheart/pen/ZEbdRdr)

Is it necessary to be supported by ECharts?

![image](https://user-images.githubusercontent.com/26999792/83210440-71354a80-a18d-11ea-937f-2b5d5e0ec4fa.png)

**Comment by softwords** [comment]
@plainheart : thankyou for your quick reply. You are totally right , this is much easier than I was making it out to be. The secret in your solution is the use of `display:inline-block`, not `display:inline` which I was trying to make work. @pissang , maybe this does not deserve a new feature after all - I'm satisfied with the method from @plainheart ....

**Comment by softwords** [comment]
I am closing this issue because the solution from @plainheart does everything needed to generate inline sparklines without any modification required to echarts.

**Comment by xavimarquez** [comment]
This is not a viable solution. If you try to insert 50 charts in a html table, you will get a very poor performance. In my case, it takes 4 seconds to load the page.
Sparkline is defined as  "sparkline is a very small line chart, typically drawn without axes or coordinates. It presents the general shape of the variation (typically over time) in some measurement"

The idea is to show a simple chart, and using the "normal" charts, with advanced features, even you do not use them, it is not viable because of the performance.

See the support for sparklines for Highcharts: https://www.highcharts.com/demo/sparkline and try to do the same with echarts.

**Comment by lublak** [comment]
@xavimarquez i think it is required to create a new issue for this.
I am also looking for this feature.
But I will still look if you can not deactivate all elements/features individually.
Another library that supports it:
https://apexcharts.com/javascript-chart-demos/sparklines/basic/

**Comment by baharmf93** [comment]
@xavimarquez @lublak 
How does this site use the Apache echarts and is it a sparkline type?
https://app.uptrace.dev/metrics/1/730563672086151186?time_dur=3600&sort_by=gc_pause_max&sort_desc=1

**Comment by ignaaaam** [comment]
> @xavimarquez @lublak How does this site use the Apache echarts and is it a sparkline type? https://app.uptrace.dev/metrics/1/730563672086151186?time_dur=3600&sort_by=gc_pause_max&sort_desc=1

Can the creator of this tell how it's done the small chart in that way?

Thanks!

**Comment by helgasoft** [comment]
@SardarDelha, @ignaaaam, these sparklines are indeed made with ECharts:
https://github.com/uptrace/uptrace/blob/master/vue/src/components/SparklineChart.vue
