### ISSUE TITLE
Chinese text in english tutorial

### ISSUE THREAD

**Issue by maximesong** [apache/incubator-echarts#12712]
### Version
4.8.0

### Steps to reproduce
https://echarts.apache.org/en/tutorial.html#Overview%20of%20Style%20Customization

Theme section

### What is expected?
text between code block should be “Or”

### What is actually happening?
it's “或者”

**Comment by maximesong** [comment]
And

https://echarts.apache.org/en/tutorial.html#Dataset

second paragraph

More importantly, is enables data encoding

I think "is" here should be "it"

**Comment by plainheart** [comment]
Thanks for reporting~ Would you like create a PR for this?
For the first: https://github.com/apache/incubator-echarts-doc/blob/master/en/tutorial/style-overview.md
For the second: https://github.com/apache/incubator-echarts-doc/blob/master/en/tutorial/dataset.md

**Comment by maximesong** [comment]
Sure. https://github.com/apache/incubator-echarts-doc/pull/103

**Comment by susiwen8** [comment]
@maximesong Thanks for your contribution
