### ISSUE TITLE
API Docmentation for 'action.graph. focusNodeAdjacency'

### ISSUE THREAD

**Issue by gorgiaxx** [apache/incubator-echarts#12718]
### Version
4.8.0

### Steps to reproduce
I want to highlight an edge in a graph. When I configure the param for the myChart.dispatchAction({type: 'focusNodeAdjacency', dataIndex: 19}), it always highlight the Node rather than the Edge. I stepped into the 'focusNodeAdjacency', and I found the 'edgeDataIndex' property. But it doesn't be mentioned in the documentation.
https://echarts.apache.org/en/api.html#action.graph.focusNodeAdjacency

### What is expected?
Description for the 'edgeDataIndex'.

### What is actually happening?
The 'edgeDataIndex' is only in the codes. It's too hard to find.

**Comment by susiwen8** [comment]
@gorgiaxx Sorry about this, Could you make a PR for it?
