### ISSUE TITLE
折线图的单击放大以及单击缩小问题

### ISSUE THREAD

**Issue by CodeFly16** [apache/incubator-echarts#12725]
### What problem does this feature solve?
以折线图为例，点击折线图上面某处，可以实现，以该处为中心 整个折线图放大一倍或者缩小一倍，无需使用滑轮进行缩小和放大，可以实现精准的查看某处附近的数据

### What does the proposed API look like?
点击某处，获取某处坐标，以该坐标为中心，相应改变x轴和y轴最小值和最大值，实现放大效果，类似于geo.roam

**Comment by Ovilia** [comment]
点击放大的话，什么时候缩小？

**Comment by CodeFly16** [comment]
@Ovilia 可以有两种模式，点击放大和点击缩小模式，点击放大后通过滑轮缩小，点击缩小 通过滑轮放大 ，这样子就可以避免使用滑轮后，在拖拽表到想要的范围了

**Comment by Ovilia** [comment]
这种特定业务需求，自己通过监听和触发事件解决吧

**Comment by CodeFly16** [comment]
@Ovilia 好的 多谢
