### ISSUE TITLE
markPoint data symbolRotate 失效

### ISSUE THREAD

**Issue by icexxxxxx** [apache/incubator-echarts#12731]
### Version
4.8.0

### Steps to reproduce
1. series.type = 'candlestick'
2. markPoint.data = [ ..., [ {  type: 'min',  valueDim: 'lowest', symbolRotate: 180 } ] ]

### What is expected?
如v4.6一样正常旋转

### What is actually happening?
data中单独设置的symbolRotate无效

**Comment by plainheart** [comment]
Related to #12388.
Thanks for your reporting. It has been fixed by #12392. This fixing will be included in v4.9.0.

**Comment by plainheart** [comment]
Sorry for this, it is not related to `markLine` but related to `markPoint`. I will creat a PR for fixing the `symbolRotate` bug in `markPoint`.

**Comment by icexxxxxx** [comment]
@Ovilia Pls reopen this till this is fixed. 😀

**Comment by Ovilia** [comment]
@icexxxxxx It's been fixed in #12737 but not released. We close issues after PR is merged. If you think your problem has not been fixed, feel welcomed to reopen it.

**Comment by icexxxxxx** [comment]
👏
