### ISSUE TITLE
Missing interface for Axis name positioning.

### ISSUE THREAD

**Issue by dvago** [apache/incubator-echarts#12738]
### What problem does this feature solve?
Given the current option: `yAxis.nameLocation = 'end'`, I'm able to set the vertical position of the label, however there is nothing that permits to set the horizontal position of the label. 

Unfortunately having the label in the middle (x) of the axis does conflict with markPoints. 
see example below:
![Screenshot 2020-06-02 at 17 39 12](https://user-images.githubusercontent.com/5074033/83547114-a7f6c200-a4f9-11ea-9cb2-bb5615cae821.png)

### What does the proposed API look like?
I would extend the options to include the horizontal space or eventually (for retro-compatibility) add a new option e.g. ```namePosition: 'left'  // 'center', 'right'```

**Comment by plainheart** [comment]
Consider using `nameGap` or `nameRotate` to prevent yAxis label overlapping?

**Comment by dvago** [comment]
thanks @plainheart nameTextStyle.align does cover the issue
