### ISSUE TITLE
获取dataset中指定行指定列的某一个值

### ISSUE THREAD

**Issue by peterwinners** [apache/incubator-echarts#12730]
### What problem does this feature solve?
需求：通过formatter或其他方式获取到dataset指定行指定列某一个值。
场景：option中设计与数据完全分离，所有数据存放于dataset中，从后台接口中获取，便于全局数据控制。数据中包含单个统计数字，在页面上展示方式为：“单位数量：1000”，其中数量1000也希望从dataset中获取到，在设计option时，只用填入模板即可

### What does the proposed API look like?
series: {
    label: {
        // `'{@score}'` 表示 “名为 score” 的维度里的值。
        // `'{@[score[0]}'` 表示"名为score"的维度里第一个值。
        formatter: '{@score[0]}'
    }
}

**Comment by plainheart** [comment]
formatter的回调函数不能满足你的需求吗？

**Comment by peterwinners** [comment]
> formatter的回调函数不能满足你的需求吗？

请问一下title里的text支持formatter方式不？我需要title里的标题也自定义formatter该怎么写呢？

**Comment by peterwinners** [comment]
> formatter的回调函数不能满足你的需求吗？

在title里，我用rich可以实现了，非常感谢！dataset的[0][0]方式还会有别的适用场景吧。
