### ISSUE TITLE
label font style not updated in pictorialBar when calling the api `setOption`  to update it 

### ISSUE THREAD

**Issue by cheqianxiao** [apache/incubator-echarts#12743]
### Version
4.8.0

### Reproduction link
[  https://codepen.io/oobakoyo/pen/GRoRmvd](  https://codepen.io/oobakoyo/pen/GRoRmvd)

### Steps to reproduce
use `setOption` to update the label font style 

### What is expected?
label font style should be updated after calling `setOption` with new style

### What is actually happening?
only label color refreshed

**Comment by plainheart** [comment]
Thanks for reporting! It seems to be a bug.
