### ISSUE TITLE
tree树图，收缩节点后再展开，带图片的子节点不显示内容，必须点击一次才能显示

### ISSUE THREAD

**Issue by TIMJAMES** [apache/incubator-echarts#12740]
### Version
4.8.0

### Steps to reproduce
1.打开官方实例  https://echarts.apache.org/examples/zh/editor.html?c=tree-vertical

2.把下面代码贴到实例运行

    myChart.setOption(option = {
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series:[
            {
                type: 'tree',

                data: [
{
    name: '根节点',
    symbol: 'image://https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1591164166038&di=5b0b2af6585752e3876e82f33d59cfe0&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201709%2F10%2F20170910110429_5J8jt.jpeg',
    children: [
                {
                    name: '节点',
                    symbol: 'image://head.png',
                        children: [
                                    {
                                        name: '节点',
                                        symbol: 'image://https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1591164166038&di=5b0b2af6585752e3876e82f33d59cfe0&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201709%2F10%2F20170910110429_5J8jt.jpeg'
                                    },
                                    {
                                        name: '节点',
                                        //symbol: 'image://https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1591164166038&di=5b0b2af6585752e3876e82f33d59cfe0&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201709%2F10%2F20170910110429_5J8jt.jpeg'
                                    }
                                ]
                            }
                        ]
                  }
               ],

                left: '2%',
                right: '2%',
                top: '8%',
                bottom: '20%',

                symbol: 'rect',
                symbolSize: [40, 40],
                orient: 'vertical',

                expandAndCollapse: true,

                label: {
                    position: 'top',
                    rotate: -90,
                    verticalAlign: 'middle',
                    align: 'right',
                    fontSize: 9
                },

                leaves: {
                    label: {
                        position: 'bottom',
                        rotate: -90,
                        verticalAlign: 'middle',
                        align: 'left'
                    }
                },

                animationDurationUpdate: 750
            }
        ]
    });

3.点击根节点收缩，再点击根节点展开

### What is expected?
TIM

### What is actually happening?
没办法正常使用展开收缩节点的功能。

**Comment by plainheart** [comment]
已在 #12367 修复，会包含在4.9版本中。

**Comment by TIMJAMES** [comment]
> 已在 #12367 修复，会包含在4.9版本中。

我能提前下载这个修复的版本做测试吗？需要怎么操作呢？

**Comment by plainheart** [comment]
@TIMJAMES 可以下载ECharts的源码，运行 `npm install` 安装依赖，然后按照 https://github.com/apache/incubator-echarts/pull/12367/files 所显示的变更修改 ` src/chart/helper/Symbol.js` 文件，修改后使用 `npm run release` 重新构建，构建完成后到`dist`目录找到自己需要的js文件即可。

**Comment by TIMJAMES** [comment]
> @TIMJAMES 可以下载ECharts的源码，运行 `npm install` 安装依赖，然后按照 https://github.com/apache/incubator-echarts/pull/12367/files 所显示的变更修改 ` src/chart/helper/Symbol.js` 文件，修改后使用 `npm run release` 重新构建，构建完成后到`dist`目录找到自己需要的js文件即可。

可以的，非常感谢！
