### ISSUE TITLE
我需要扩展异形图版,需要提供坐标轴的绘制支持

### ISSUE THREAD

**Issue by peach5460** [apache/incubator-echarts#12757]
### What problem does this feature solve?
我有一个新的需求，需要绘制一个三角形的散点图。他有三个轴X,Y,Z。在图面上三个轴构成了一个三角形。
有一组数据，每一个数据都有XYZ的数值属性。
显示时，通过XYZ轴的值，落点到坐标轴上以后，经过一系列点线求交的计算，计算出点在三角形内的位置，然后进行绘制。

### What does the proposed API look like?
支持这种斜着的轴落点计算应该是很复杂的。
在桌面版程序中，我是通过两个图层，底图建立一个直角坐标系，但是不显示底图的任何元素。
然后顶图上手绘一个三角形的坐标轴，然后将计算出来的三角形的点通过DP位置映射到底图的直角坐标系中换算成底图坐标系的LP坐标来实现的。

所以我希望能得到EChart手绘图元的API支持。

**Comment by Ovilia** [comment]
参考自定义系列的例子 https://echarts.apache.org/examples/en/index.html#chart-type-custom

**Comment by peach5460** [comment]
3Q，我觉得我可能需要尝试一下GEO属性

**Comment by Ovilia** [comment]
是否需要关闭此 issue？

**Comment by peach5460** [comment]
是的,谢谢
我已经能近似实现我要的效果了
