### ISSUE TITLE
Human body charts for bioscience researchers using ECharts.

### ISSUE THREAD

**Issue by chunjie-sam-liu** [apache/incubator-echarts#12765]
### What problem does this feature solve?
I am a Ph.D. in genetic research, I found ECharts very helpful for the presenting statistics of metadata of clinical and biological data.
I am wondering whether ECharts could provide features like human body, organs charts for presenting genetic big data. I know it's not a common feature enough for now, as human sequencing data increases, visualizing these big data on human body could be intuitive for researchers and doctors in their study.

### What does the proposed API look like?
The URL is the GDC portal, https://portal.gdc.cancer.gov/, presenting human body and cancer organs.

![human-body](https://user-images.githubusercontent.com/16101520/83963497-288e3780-a8d9-11ea-98a0-40f6ce13cbaf.png)

**Comment by plainheart** [comment]
It may be possible to draw such human body charts by using [`custom series`](https://echarts.apache.org/en/option.html#series-custom), but it will be a bit hard to realize completely, after all, the structure of human body is so complicated.

**Comment by Ovilia** [comment]
Yes, it's suggested to implement using custom series. Using [renderItem.image](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_image.style.image) to draw each organ.

**Comment by pissang** [comment]
Perhaps SVG component which @100pah is implementing can do this kind of things.

**Comment by chunjie-sam-liu** [comment]
Thanks very much, I get it.

**Comment by liuyigh** [comment]
Has anyone successfully reproduced this NCI illustration using echarts? Is the NCI svg code free to use? Thanks!

**Comment by chunjie-sam-liu** [comment]
I surprisedly found this human organ link today, [](https://echarts.apache.org/examples/en/editor.html?c=geo-organ).
