### ISSUE TITLE
折线图出现断开的问题

### ISSUE THREAD

**Issue by YouthShouting** [apache/incubator-echarts#12771]
在使用echarts的折线图有时候会出现点与点之间并没有连接起来而是断开的，请问这是一个bug吗，一下我提供一下这个情况的图片
![image](https://user-images.githubusercontent.com/47060588/84101359-5641c080-aa40-11ea-8b19-871245108b28.png)

**Comment by YouthShouting** [comment]
怎么样才能让每个点都连接起来成一条线呢

**Comment by susiwen8** [comment]
@YouthShouting 可能你的数据存在 null 值，看下之前的评论

**Comment by YouthShouting** [comment]
是有null的值啊，现在就是要把点连接起来
