### ISSUE TITLE
折线图没有连接是会断开是怎么回事？？？

### ISSUE THREAD

**Issue by YouthShouting** [apache/incubator-echarts#12770]
![image](https://user-images.githubusercontent.com/47060588/84100884-5ab9a980-aa3f-11ea-88d5-c6a027a0a1b2.png)

**Comment by susiwen8** [comment]
应该是有 null 值
https://echarts.apache.org/zh/option.html#series-line.connectNulls

**Comment by susiwen8** [comment]
@YouthShouting 评论在这里

**Comment by YouthShouting** [comment]
@susiwen8 好的
