### ISSUE TITLE
tooltip无法自动关闭

### ISSUE THREAD

**Issue by 0x018** [apache/incubator-echarts#12778]
### Version
4.5.0

### Steps to reproduce

代码:
```
option = {
    tooltip: {
        trigger: 'item',
        formatter: `<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-向左水平移动鼠标<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-向左水平移动鼠标<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-向左水平移动鼠标<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-<-`,
        enterable:true,
        position:['-30%','50%']
    },
    legend: {
        orient: 'vertical',
        left: 10,
        data: ['直接访问']
    },
    series: [
        {
            name: '访问来源',
            type: 'pie',
            avoidLabelOverlap: false,
            label: {
                show: false,
                position: 'center'
            },
            emphasis: {
                label: {
                    show: true,
                    fontSize: '30',
                    fontWeight: 'bold'
                }
            },
            labelLine: {
                show: false,
            },
            data: [
                {value: 335, name: '直接访问'}
            ]
        }
    ]
};
```

步骤: 

1. 鼠标移动到圆圈上,出现tooltip

2. 鼠标移动到tooltip上

3. 鼠标沿着tooltip水平向左移动, 直到移出tooltip

4. tooltip不会消失

初步猜测原因:

tooltip超出echarts时, 鼠标在tooltip上直接移出时,不会触发tooltip的消失事件. 必须先移动到echarts上,再移出才会触发.

### What is expected?
tooltip在 enterable:true的情况下,鼠标移出后,tooltip不一定会消失

### What is actually happening?
鼠标不在echarts及他的tooltip上时, tooltip能正常消失

**Comment by 0x018** [comment]
场景: 本身echarts比较小,tooltip在外面,移动到tooltip上再移出,经常无法自动关闭tooltip.

上面代码用了超长的tooltip模拟这种情况. 鼠标移出后, 只要不移动回echarts, tooltip就不会消失

**Comment by plainheart** [comment]
`enterable` 为 `true` 的时候，代表用户可以进入`tooltip`区域中进行操作，又由于你这个`tooltip`非常长，在`tooltip`上移动鼠标直到移出去应该没有侦测你是移出图表了，所以并未隐藏。考虑设置 `enterable` 为 `false` 或者手动派发Action隐藏
```js
dispatchAction({
    type: 'hideTip'
})
```

**Comment by 0x018** [comment]
> `enterable` 为 `true` 的时候，代表用户可以进入`tooltip`区域中进行操作，又由于你这个`tooltip`非常长，在`tooltip`上移动鼠标直到移出去应该没有侦测你是移出图表了，所以并未隐藏。考虑设置 `enterable` 为 `false` 或者手动派发Action隐藏
> 
> ```js
> dispatchAction({
>     type: 'hideTip'
> })
> ```

1. 调用dispatchAction  hideTip, 我也不知道什么时候移出
2. 有临时解决方案
3. 提issue是因为你们用这个bug坑了我,所以我用这个issue坑回来
------------------------------------------------------------------------------

临时方案:
1. tooltip设置: `enterable: false,hideDelay:2000 `
2. 全局css添加:
```
.echarts>div[style]:nth-child(2){
  pointer-events: all !important; /*强制tooltip响应事件*/
}
.echarts>div[style]:nth-child(2):hover {
  display: block !important; /*强制鼠标在时tooltip不消失*/
}

```

**Comment by plainheart** [comment]
多次测试了下，感觉是有点问题，源代码中在处理 tooltip `onmouseleave` 事件时，设置 `_inContent` 的时机错了，应该在隐藏tooltip的逻辑之前，目前是在隐藏tooltip的逻辑之后，而隐藏tooltip的逻辑中会判断 `_inContent` 的值，由于此时 `_inContent` 为 还是 `true`，代码逻辑就不会往下执行，从而导致无法隐藏。稍后会通过PR修复下，感谢反馈！

**Comment by gaofanni** [comment]
> > `enterable` 为 `true` 的时候，代表用户可以进入`tooltip`区域中进行操作，又由于你这个`tooltip`非常长，在`tooltip`上移动鼠标直到移出去应该没有侦测你是移出图表了，所以并未隐藏。考虑设置 `enterable` 为 `false` 或者手动派发Action隐藏
> > ```js
> > dispatchAction({
> >     type: 'hideTip'
> > })
> > ```
> 
> 1. 调用dispatchAction  hideTip, 我也不知道什么时候移出
> 2. 有临时解决方案
> 3. 提issue是因为你们用这个bug坑了我,所以我用这个issue坑回来
> 
> 临时方案:
> 
> 1. tooltip设置: `enterable: false,hideDelay:2000 `
> 2. 全局css添加:
> 
> ```
> .echarts>div[style]:nth-child(2){
>   pointer-events: all !important; /*强制tooltip响应事件*/
> }
> .echarts>div[style]:nth-child(2):hover {
>   display: block !important; /*强制鼠标在时tooltip不消失*/
> }
> ```

对appendToBody=true的用echarts类名会找不到
可以在tooltip.position的函数回调内拿到tooltip的dom节点，进行监听隐藏
chartOptions.tooltip.position = (point, params, dom: HTMLElement) => {
      dom.onmouseleave = () => {
        dom.style.display = 'none'
      }
    }

**Comment by wsz7777** [comment]
很糟心的是，现在这个bug依然有~~~ "echarts": "^4.9.0", 什么时候更新？

**Comment by plainheart** [comment]
@wsz7777 这个问题应该在5.0版本修复，可以尝试一下。#13382

**Comment by ViavaCos** [comment]
@wsz7777 我在移动端使用Echarts时碰到了无法字段关闭tooltip的情况
找了不少方法，最后用这个方法解决的，可以试试，不知道是否有什么隐患否？@plainheart 

`
dispatchAction({
        type: 'showTip',
        x: 0,
        y: 0
      })
`

**Comment by jinjiaxing** [comment]
> @wsz7777 这个问题应该在5.0版本修复，可以尝试一下。#13382

5.0也是有这个问题呀，我提了issue 说是在5.0.1 fix，但现在还是没有 fix

**Comment by gui-killer** [comment]
5.0依然有这个问题。
并且，监听图表DOM的mouseout事件，事件触发后通过dispatchAction派发一个hideTip，也没法关闭。
后来想了下，估计是源码里面设置的时机不对。然后把dispatchAction放到timeout里面，延迟1s再做，就没问题了。

**Comment by plainheart** [comment]
Hi, @gui-killer 请问你使用的是 5.0.2 吗？从 5.0.1 版本开始应该已经修复了这个问题。

**Comment by gui-killer** [comment]
> Hi, @gui-killer 请问你使用的是 5.0.2 吗？从 5.0.1 版本开始应该已经修复了这个问题。

是从官网上生成的一个自定义的，只有线图、饼图、图例等基础组件。源码里看到的zrender的版本是5.0.3，echarts的版本是5.0.1。
![image](https://user-images.githubusercontent.com/50569424/110567793-06d61f80-818d-11eb-9893-9dc35d7fcdea.png)

**Comment by gui-killer** [comment]
> @gui-killer 建议先试试 5.0.2 是否还有此问题，如果有可以提个 issue 带上能复现的例子。

OK

**Comment by chjssg** [comment]
哪个版本解决了？

**Comment by gui-killer** [comment]
> 哪个版本解决了？

我也不知道，我是在图表的外部dom上，绑定了一个鼠标离开的事件，一旦触发就调用图表暴露的方法去强制关闭tooltip（需要延时一点时间，否则不成功）。

**Comment by plainheart** [comment]
请用最新版本进行测试，旧版本基本上不再可能会有更新。如果最新版本依然存在此问题，请再另外开一个 issue。

**Comment by mahoushoujoarale** [comment]
@plainheart 这个问题应该是在移出tooltip后需要派发globalout事件，现在是没有的，修复一下吧
