### ISSUE TITLE
Echarts Sankey 对数据一直提示Sankey is a DAG, the original data has cycle!请问这个如何解决

### ISSUE THREAD

**Issue by babyvip229** [apache/incubator-echarts#12787]
他一直提示数据“原始数据有周期”。请问这个原始数据有周期是什么原因呢？

示例地址：https://gallery.echartsjs.com/editor.html?c=xr3LI5lPST&v=4

示例代码：
let json2 = [
	{"name":"【企业微信功能测试组】"},
	{"name":"业务团队"},
	{"name":"职能总部"},
	{"name":"产品中心"},
	{"name":"线上业务体系"},
	{"name":"AI出版中心"},
	{"name":"业务总部"},
	{"name":"研发中心"},
	{"name":"【服务保障联合小组】"},
	{"name":"东西北战区"},
	{"name":"西南战区"},
	{"name":"华北战区"},
	{"name":"慧学空间事业部"},
	{"name":"华南战区"},
	{"name":"华东战区"},
	{"name":"华中战区"},
	{"name":"服务保障中心"}
]
let json3 = [
	{
		"source":"【企业微信功能测试组】",
		"target":"产品中心",
		"value":74
	},
	{
		"source":"【企业微信功能测试组】",
		"target":"业务总部",
		"value":339
	},
	{
		"source":"【企业微信功能测试组】",
		"target":"华北战区",
		"value":171
	},
	{
		"source":"【企业微信功能测试组】",
		"target":"西南战区",
		"value":26
	},
	{
		"source":"业务团队",
		"target":"职能总部",
		"value":416
	},
	{
		"source":"业务团队",
		"target":"华南战区",
		"value":28
	},
	{
		"source":"业务团队",
		"target":"业务总部",
		"value":681
	},
	{
		"source":"职能总部",
		"target":"产品中心",
		"value":74
	},
	{
		"source":"职能总部",
		"target":"【企业微信功能测试组】",
		"value":268
	},
	{
		"source":"产品中心",
		"target":"研发中心",
		"value":272
	},
	{
		"source":"产品中心",
		"target":"【服务保障联合小组】",
		"value":25
	},
	{
		"source":"产品中心",
		"target":"AI出版中心",
		"value":142
	},
	{
		"source":"产品中心",
		"target":"业务团队",
		"value":114
	},
	{
		"source":"线上业务体系",
		"target":"【企业微信功能测试组】",
		"value":653
	},
	{
		"source":"线上业务体系",
		"target":"AI出版中心",
		"value":71
	},
	{
		"source":"线上业务体系",
		"target":"职能总部",
		"value":399
	},
	{
		"source":"线上业务体系",
		"target":"业务团队",
		"value":114
	},
	{
		"source":"AI出版中心",
		"target":"【企业微信功能测试组】",
		"value":205
	},
	{
		"source":"业务总部",
		"target":"产品中心",
		"value":74
	},
	{
		"source":"业务总部",
		"target":"职能总部",
		"value":207
	},
	{
		"source":"业务总部",
		"target":"华南战区",
		"value":28
	},
	{
		"source":"研发中心",
		"target":"职能总部",
		"value":94
	},
	{
		"source":"研发中心",
		"target":"服务保障中心",
		"value":13
	},
	{
		"source":"东西北战区",
		"target":"【企业微信功能测试组】",
		"value":134
	},
	{
		"source":"东西北战区",
		"target":"产品中心",
		"value":74
	},
	{
		"source":"西南战区",
		"target":"华北战区",
		"value":57
	},
	{
		"source":"华北战区",
		"target":"业务总部",
		"value":113
	},
	{
		"source":"华北战区",
		"target":"服务保障中心",
		"value":39
	},
	{
		"source":"华北战区",
		"target":"东西北战区",
		"value":200
	},
	{
		"source":"慧学空间事业部",
		"target":"职能总部",
		"value":105
	},
	{
		"source":"华南战区",
		"target":"【企业微信功能测试组】",
		"value":162
	},
	{
		"source":"华南战区",
		"target":"华北战区",
		"value":57
	},
	{
		"source":"华东战区",
		"target":"【企业微信功能测试组】",
		"value":268
	},
	{
		"source":"华东战区",
		"target":"业务总部",
		"value":113
	},
	{
		"source":"华东战区",
		"target":"东西北战区",
		"value":43
	},
	{
		"source":"华东战区",
		"target":"华北战区",
		"value":114
	},
	{
		"source":"华中战区",
		"target":"【企业微信功能测试组】",
		"value":268
	},
	{
		"source":"华中战区",
		"target":"业务总部",
		"value":226
	},
	{
		"source":"华中战区",
		"target":"东西北战区",
		"value":114
	},
	{
		"source":"华中战区",
		"target":"华北战区",
		"value":114
	},
	{
		"source":"华中战区",
		"target":"华东战区",
		"value":44
	},
	{
		"source":"华中战区",
		"target":"服务保障中心",
		"value":13
	}
]
option  = {
    tooltip: {
        trigger: 'item',
        triggerOn: 'mousemove'
    },
    series: {
        type: 'sankey',
        layout:'none',
        focusNodeAdjacency: 'allEdges',
        itemStyle: {
            borderWidth: 1,
            borderColor: '#aaa'
        },
        lineStyle: {
            color: 'source',
            curveness: 0.5
        },
        data: json2,
        links: json3
    }
}

**Comment by dorasong** [comment]
遇到同样问题，求解

**Comment by walkingzmz** [comment]
遇到同样问题，求解

**Comment by dorasong** [comment]
服务端返回的数据有回流，即一个数据作为出发源数据，又作为目的源数据，数据形成闭环，请自查。


| |
songwen
|
|
邮箱：sw_hero2008@126.com
|

Signature is customized by Netease Mail Master

在2020年12月22日 17:45，walkingzmz 写道：

遇到同样问题，求解

**Comment by dorasong** [comment]
echarts桑基图不允许数据出现闭环


| |
songwen
|
|
邮箱：sw_hero2008@126.com
|

Signature is customized by Netease Mail Master

在2020年12月22日 17:55，songwen 写道：
服务端返回的数据有回流，即一个数据作为出发源数据，又作为目的源数据，数据形成闭环，请自查。


| |
songwen
|
|
邮箱：sw_hero2008@126.com
|

Signature is customized by Netease Mail Master

在2020年12月22日 17:45，walkingzmz 写道：

遇到同样问题，求解
