### ISSUE TITLE
Stacked Bar: Label would be covered by next series

### ISSUE THREAD

**Issue by Benshakalaka** [apache/incubator-echarts#12786]
### Version
4.8.0

### Steps to reproduce
Use official example to test: https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category-stack
When I set position as right for each series, only last series' label would be displayed
Other label would be covered. This could be seen when animating

### What is expected?
I want to display label not covered by other series.

### What is actually happening?
Label is coverd by next series

**Comment by Ovilia** [comment]
Label levels are higher than item elements in v5.0. So this is fixed in the `next` branch.
<img width="713" alt="屏幕快照 2020-06-11 12 06 49" src="https://user-images.githubusercontent.com/779050/84344035-4bbc2e00-abdc-11ea-9e2b-6a424b9bb860.png">
