### ISSUE TITLE
热力图的series.data中设置二维数组，x，y轴效果被互换

### ISSUE THREAD

**Issue by JC-Ge** [apache/incubator-echarts#12784]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=heatmap-cartesian](https://echarts.apache.org/examples/zh/editor.html?c=heatmap-cartesian)

### Steps to reproduce
使用官方的热力图案例就可发现

### What is expected?
数组第一列对应x轴，第二列对应y轴

### What is actually happening?
第一列对应y轴，第二列对应x轴

---
官方文档周关于series-heatmap.data中的说明是二维数组中第一列代表x轴，但在热力图中第一列代表y轴

**Comment by Ovilia** [comment]
代码里有
```js
data = data.map(function (item) {
    return [item[1], item[0], item[2] || '-'];
});
```
所以并没有问题

**Comment by JC-Ge** [comment]
ok!Thank you!I ignored this part and i will close issue.
