### ISSUE TITLE
Keep graph offset/zoom when updating option

### ISSUE THREAD

**Issue by ilovepumpkin** [apache/incubator-echarts#12799]
### Version
4.8.0

### Steps to reproduce
1. create a chart with option (type='graph', layout='none') and roam is set to true.
2. move and zoom the chart
3. update the  node style properties in option

### What is expected?
Only the node style is updated but the chart offset/zoom keeps what I changed before

### What is actually happening?
The chart offset/zoom is reset to the initial state

---
Is there any way that I update node/edge styles without updating the whole option object? Like what dispatchAction (type='highlight') did, is it possiible that I get each node/edge handler and dynamically set their styles? The problem for me now is that dispatchAction - highlight can not support edge so it does not meet my needs fully.

**Comment by sudheer9047** [comment]
any solution for the above issue ??

**Comment by tomasdelima** [comment]
I'm facing the same issue. Whenever I add data to my series, the zoom resets
