### ISSUE TITLE
点击节点，使该节点成为中心节点，也就是在视角中心

### ISSUE THREAD

**Issue by zhaoyingli** [apache/incubator-echarts#12791]
### What problem does this feature solve?
点击节点，使该节点成为中心节点，也就是在视角中心

### What does the proposed API look like?
点击节点，使该节点成为中心节点，也就是在视角中心

**Comment by Ovilia** [comment]
可以通过监听点击实践，然后设置 [graphic.center](https://github.com/apache/incubator-echarts-doc/commit/8d001e86a2190b9ebdc2f344a7820a563ed9299a) 实现。
