### ISSUE TITLE
lines 高亮配置无效

### ISSUE THREAD

**Issue by myshzzx** [apache/incubator-echarts#12801]
### Version
4.8.0

### Steps to reproduce
https://echarts.apache.org/zh/option.html#series-lines.emphasis
lines 的高亮样式在鼠标移动到上面时未生效

### What is expected?
高亮样式生效

### What is actually happening?
高亮样式未生效, 与未配置 emphasis 一样

**Comment by plainheart** [comment]
没能复现你说的问题。对于 `emphasis.lineStyle` 高亮状态正常生效，如果你说的是 `label` 与 `emphasis.label` 则只有在 `polyline` 为 `false` 时生效。不过很抱歉，这一点文档似乎并未提及。

**Comment by myshzzx** [comment]
不好意思, 我配置写错了.
