### ISSUE TITLE
折线图数据项为0时，并未显示在0处

### ISSUE THREAD

**Issue by t-sinbo** [apache/incubator-echarts#12807]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-stack](https://echarts.apache.org/examples/zh/editor.html?c=line-stack)

### Steps to reproduce
将左侧数据’视频广告‘数组最后一个数据修改为0

### What is expected?
数据点及连线在0处

### What is actually happening?
数据点及连线与下方数组最后一个值重合

**Comment by plainheart** [comment]
我认为是这可能没有问题，因为示例用了`stack`开启了堆叠视图，如果你想要将其显示在0处，可以将`视频广告`移动至`series`数组中的第一位，使其成为第一个系列。
https://gallery.echartsjs.com/editor.html?c=xe11dFbRq-&v=1

**Comment by t-sinbo** [comment]
sorry,i get it,thank you!
