### ISSUE TITLE
Wrong line color with line chart and visualmap with dimension >= 2

### ISSUE THREAD

**Issue by jaortegalal** [apache/incubator-echarts#12818]
### Version
4.8.0

### Reproduction link
[https://jsfiddle.net/wdsytchL/](https://jsfiddle.net/wdsytchL/)

### Steps to reproduce
The bug reproduces in the jsfiddle. The lines appear with red color instead of the color from the visualmap. This doesn't happen if dimension is set to 0 or 1.

### What is expected?
The red line should be colored in the same way as the markers, using the visualmap colors.

### What is actually happening?
The lines are colored in red.

**Comment by susiwen8** [comment]
![Screen Shot 2020-06-22 at 18 17 18](https://user-images.githubusercontent.com/20318608/85276590-a7c46380-b4b4-11ea-8e5b-ec07ac268275.png)
![Screen Shot 2020-06-22 at 18 19 03](https://user-images.githubusercontent.com/20318608/85276742-e35f2d80-b4b4-11ea-949f-72f8a57ecf6d.png)
@jaortegalal visualMap for line only support `x` and `y`
