### ISSUE TITLE
RangeArea Chart

### ISSUE THREAD

**Issue by harkiratsinghsethi** [apache/incubator-echarts#12810]
### What problem does this feature solve?
Hi team, 

I am glad that I am contacting you and using Echart for React into my projects. I am using this for plotting various types of graphs(Line, Scatter, Area) and now we are looking for a RangeArea type graph which I was not able to find in the Docs. Could you please let me know how can I achieve that using the current type. I am looking forward to hearing from you.

Thanks and regards

### What does the proposed API look like?
Attaching the problem which can be solved
https://ibb.co/nsQvSBT

**Comment by plainheart** [comment]
Hi, I think you may use [`series-line.stack`](https://echarts.apache.org/en/option.html#series-line.stack) and [`series-line.areaStyle`](https://echarts.apache.org/en/option.html#series-line.areaStyle) to achieve such a chart.
Here is a demo on ECharts Gallery: https://gallery.echartsjs.com/editor.html?c=xuhc-jNNJ0&v=1

**Comment by harkiratsinghsethi** [comment]
Thanks, you saved my day.
