### ISSUE TITLE
2.x中的refresh函数在4.x中改成什么了？

### ISSUE THREAD

**Issue by fsql** [apache/incubator-echarts#12822]
### Version
4.0.0

### Steps to reproduce
在树形图中，想点击节点时通过on("click", clickFun)绑定点击事件，再由ajax加载子节点数据，但是返回的数据只有节点的数据，之前的refresh函数只改节点数据就可以，现在4.x版本中这个函数改为什么了？

### What is expected?
·

### What is actually happening?
·

**Comment by Ovilia** [comment]
统一由 `setOption` 处理了，如果有数据改变，就把改变的数据放在参数里。

**Comment by fsql** [comment]
> 统一由 `setOption` 处理了，如果有数据改变，就把改变的数据放在参数里。

`
myChart.on("click", reloadTree);
function reloadTree(params)
{
	var addData = getTreeData(params.data.uid);
	if(param.data.children)
	{
            param.data.children.push(addData);
	}else{
			param.data.children = [addData];
	}
	
	
	myChart.setOption();
}

function getTreeData(userId)
{
	$.ajax(.........);
	return data;
}
`
params中没有返回其他节点数据，应该怎么写才能定位params在setOption()参数里的位置？

**Comment by Ovilia** [comment]
建议把之前的 option 保留下来，params 里会有 seriesIndex 之类的可以判断出改哪里的数据。

**Comment by fsql** [comment]
> 建议把之前的 option 保留下来，params 里会有 seriesIndex 之类的可以判断出改哪里的数据。

按照dataIndex修改数据用哪个函数？文档里没找到

**Comment by Ovilia** [comment]
就是直接改你的 option，dataIndex 对应的是系列中的第 dataIndex 个数据

**Comment by fsql** [comment]
> 就是直接改你的 option，dataIndex 对应的是系列中的第 dataIndex 个数据。如果需要进一步帮助，可以创建一个在线 demo。

https://gallery.echartsjs.com/editor.html?c=xBUPEVpczO&v=1 
贴上demo了，82行往后的怎么写？

**Comment by fsql** [comment]
@Ovilia  可以帮忙解答一下吗？

**Comment by Ovilia** [comment]
`option.series[0]....` 之类的

**Comment by fsql** [comment]
> `option.series[0]....` 之类的

@Ovilia 
怎么获取要插入的数据在option.series[0].data中的具体下标呢？用dataIndex来插入吗？能在demo中写一下吗？

**Comment by fsql** [comment]
算了，用element自带的tree了虽然丑爆了
