### ISSUE TITLE
edgeLabel.formatter: "{@name}" doesn't work

### ISSUE THREAD

**Issue by zhuqingguang** [apache/incubator-echarts#12835]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x0oOjNDyl-&v=1](https://gallery.echartsjs.com/editor.html?c=x0oOjNDyl-&v=1)

### Steps to reproduce
Just  see the demo in my question:    https://gallery.echartsjs.com/editor.html?c=x0oOjNDyl-&v=1

### What is expected?
It's should show the value of specified key in my data

### What is actually happening?
it shows undefined

**Comment by plainheart** [comment]
To use named dimension, you may need to use [`dataset`](https://echarts.apache.org/en/tutorial.html#Dataset).
For the example you provided, if you don't want to use `dataset`,
- `label.formatter: '{@name}'` can be replaced by 
```js
formatter: '{b}'
```
- `edgeLabel.formatter: {@sideDesc}` can be replaced by 
```js
formatter: function(params) {
    return params.data.sideDesc
}
```

**Comment by zhuqingguang** [comment]
Thank you very muck. A formatter function is ok,  and the reason i open an issue is that i don't realize it must be used in dataset.
Maybe the docs could add a description.
Thanks . It can be closed.

**Comment by plainheart** [comment]
Thanks for your advice!
