### ISSUE TITLE
echartsInstance. on事件中的参数query不生效

### ISSUE THREAD

**Issue by Ropynn** [apache/incubator-echarts#12831]
### Version
4.8.0

### Steps to reproduce
```js
option = {
    title: {
        text: 'ECharts 入门示例'
    },
    tooltip: {},
    legend: {
        data: ['销量']
    },
    xAxis: {
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
    },
    yAxis: {},
    series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
    }]
};

myChart.on('click', 'legend', function (params) {
    console.log(123);
    console.log(params);
});
```

### What is expected?
打印 123 和 params

### What is actually happening?
无任何反应

**Comment by wf123537200** [comment]
if you want watch the ```legend``` click event may be use [legendselectchanged](https://echarts.apache.org/zh/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA)?
![image](https://user-images.githubusercontent.com/5130528/85241938-1501d580-b470-11ea-868b-f3e6fbda2f5c.png)

**Comment by Ropynn** [comment]
> if you want watch the `legend` click event may be use [legendselectchanged](https://echarts.apache.org/zh/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA)?
> ![image](https://user-images.githubusercontent.com/5130528/85241938-1501d580-b470-11ea-868b-f3e6fbda2f5c.png)

谢谢你的回答,但是我想要的是其他的鼠标事件,不一定只是点击事件.

**Comment by zhouxin860114** [comment]
> > if you want watch the `legend` click event may be use [legendselectchanged](https://echarts.apache.org/zh/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA)?
> > ![image](https://user-images.githubusercontent.com/5130528/85241938-1501d580-b470-11ea-868b-f3e6fbda2f5c.png)
> 
> 谢谢你的回答,但是我想要的是其他的鼠标事件,不一定只是点击事件.

拿柱图自己做一个图例是不是可以？做了个简易的示例：
[](https://gallery.echartsjs.com/editor.html?c=xeyxqD5RPy&v=1)
![image](https://user-images.githubusercontent.com/8022228/85386144-ce969e80-b575-11ea-97f3-2b4cb0979e18.png)
![image](https://user-images.githubusercontent.com/8022228/85386181-d9513380-b575-11ea-9f25-c6ebab50962f.png)
```myChart.on('click', {
    seriesName: 'myLegend'
}, function(params) {
    console.log(123);
    console.log(params);

    if (params.color === '#CCC') {
        myChart.dispatchAction({
            type: 'legendSelect',
            // 图例名称
            name: params.name
        });
        option.series[params.seriesIndex].data[params.dataIndex].itemStyle.color = colorList[params.dataIndex];
        myChart.setOption(option);

    } else {
        myChart.dispatchAction({
            type: 'legendUnSelect',
            // 图例名称
            name: params.name
        });
        option.series[params.seriesIndex].data[params.dataIndex].itemStyle.color = '#CCC';
        myChart.setOption(option);

    }
});```

**Comment by Ropynn** [comment]
> > > if you want watch the `legend` click event may be use [legendselectchanged](https://echarts.apache.org/zh/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA)?
> > > ![image](https://user-images.githubusercontent.com/5130528/85241938-1501d580-b470-11ea-868b-f3e6fbda2f5c.png)
> > 
> > 
> > 谢谢你的回答,但是我想要的是其他的鼠标事件,不一定只是点击事件.
> 
> 拿柱图自己做一个图例是不是可以？做了个简易的示例：
> https://gallery.echartsjs.com/editor.html?c=xeyxqD5RPy&v=1
> 
> ![image](https://user-images.githubusercontent.com/8022228/85386467-39e07080-b576-11ea-996f-0c494e43fa3d.png)
> 
> ![image](https://user-images.githubusercontent.com/8022228/85386440-3220cc00-b576-11ea-8ab2-75192ae64bb5.png)

可以的,谢谢
