### ISSUE TITLE
Chart race template

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#12830]
### What problem does this feature solve?
Hello, just wondering whether it is possible to implement a chart race template in echarts, something along these lines: https://flourish.studio/2019/07/15/line-chart-race/
Some of this can be implemented by the timeline, however, it's not as smooth, axis wouldn't move etc. 
Any thoughts welcome!

### What does the proposed API look like?
Not sure at this stage

**Comment by plainheart** [comment]
We can expect it in 5.0. See #12484

**Comment by jarben** [comment]
Awesome!
