### ISSUE TITLE
myChart.setOption({}) 时 lines.data 丢失

### ISSUE THREAD

**Issue by myshzzx** [apache/incubator-echarts#12836]
### Version
4.8.0

### Steps to reproduce
myChart.setOption({}) 时, lines类型的线数据会丢失, 其他类型的数据(如line)依然存在.
这个方法的行为是不是应该统一?

https://gallery.echartsjs.com/editor.html?c=xeqTwJtMgx&v=1

- before:
![image](https://user-images.githubusercontent.com/2025090/85202526-7f642a00-b339-11ea-82e9-784ca4aa1523.png)

- after:
![image](https://user-images.githubusercontent.com/2025090/85202536-8854fb80-b339-11ea-96f4-0b65541a068c.png)

### What is expected?
myChart.setOption({}) 要么数据全丢, 要么全保留

### What is actually happening?
lines类型的线数据丢失

**Comment by liulinboyi** [comment]
@myshzzx 
代码，在本地运行，如图所示，可以显示lines类型的线数据
![image](https://user-images.githubusercontent.com/41336612/85302280-89259300-b4db-11ea-9b0b-a898070bab68.png)
![image](https://user-images.githubusercontent.com/41336612/85302124-54194080-b4db-11ea-92a6-b37d72f70342.png)
