### ISSUE TITLE
Stacked Line Chart BUG

### ISSUE THREAD

**Issue by Gaoshengyue** [apache/incubator-echarts#12849]
When the value of index = 0 of a label exceeds the value of index = 0 of other labels by several orders of magnitude, the icon display will have problems
![Screenshot from 2020-06-23 11-21-09](https://user-images.githubusercontent.com/33923224/85357408-cde51480-b543-11ea-9241-1440329ed094.png)

**Comment by plainheart** [comment]
I'm sorry for closing this issue. Please recreate another issue with a specific description and tidy format as the echarts-bot said.
It would be better if some examples can be provided on https://gallery.echartsjs.com/editor.html or https://codepen.io/.
