### ISSUE TITLE
How to use custom fonts?

### ISSUE THREAD

**Issue by xxxs** [apache/incubator-echarts#12843]
### Version
4.1.0-rc.1

### Steps to reproduce
option = {
   title:{
          text: "XXXXX",
          textStyle: {
            color: "#00d094",
            fontSize: 30,
            fontWeight: "bold",
           fontFamily: 'yjsz',
          },
          left: "center",
          bottom: "42%",
          top: "40%"
        }
}
@font-face {
  font-family: yjsz;
  src: url("./assets/fonts/yjsz.ttf");
}
     

### What is expected?
Custom fonts can take effect

### What is actually happening?
Show default font

**Comment by plainheart** [comment]
There is a demo on CodePen: https://codepen.io/plainheart/pen/JjGWeav
It's working well, I can't reproduce it.

**Comment by xxxs** [comment]
3Q
