### ISSUE TITLE
Is there a release cycle or development plan available publicly? 

### ISSUE THREAD

**Issue by albacoretuna** [apache/incubator-echarts#12846]
### What problem does this feature solve?
Hello, I'd like to know when version 5 might be released? Or generally, is there any release plan? 

### What does the proposed API look like?
A roadmap, or release plan would be very useful for planning a big project based on Echarts :)

**Comment by Ovilia** [comment]
@albacoretuna Thanks for asking. We are discussing these kind of things on the mailing list.
For 5.0, it's available at [here](https://lists.apache.org/thread.html/r0cc1ead9c131031fc18fc10ff7a7a7ffa0718c5bd5b226d70e9ee192%40%3Cdev.echarts.apache.org%3E).
You may participate by sending an email reply.

If you are interested in this kind of discussions, please [subscribe the mailing list](https://echarts.apache.org/en/maillist.html) for future topics.

**Comment by albacoretuna** [comment]
I tried to search in the mailing list archives but I failed to find that one. Thanks a lot.

**Comment by urgrund** [comment]
Any updates with this?   It would be great to know, even in broad strokes (quarterly?) what the Apache team is up to with eCharts so that devs can plan (or mitigate) accordingly.
