### ISSUE TITLE
showTip/hideTip events on mouseover

### ISSUE THREAD

**Issue by pierrebonny** [apache/incubator-echarts#12844]
### Version
4.8.0

### Reproduction link
[https://jsfiddle.net/q6hjn8ud/](https://jsfiddle.net/q6hjn8ud/)

### Steps to reproduce
Set triggerEvent: true and silent: false to the axis you want to get mouseover and mouseout events from.
Set tooltip.show to true.
Set listeners to axis mouseover and mouseout events and show/hide tip inside

### What is expected?
Tooltip should be visible while user is hovering any xAxis label

### What is actually happening?
tooltip appears and disappears unexpectedly. It should stay visible

---
For an easier demo i provided a reproduction link where hovering any xAxis label shows tooltip for the first item. In my real case every xAxis label hover highlight it's corresponding item

**Comment by plainheart** [comment]
Have you tried [`triggerOn: none`](https://echarts.apache.org/en/option.html#tooltip.triggerOn)?

**Comment by pierrebonny** [comment]
Thanks, it's working well ! According to me it might be explained in a clearer way in the doc because I though that this option will only trigger tooltip with "showTip" and "hideTip" methods call and I wanted to trigger tooltip by methods and by mouse events also.
Anyway thanks for the answer
