### ISSUE TITLE
The rich tag is not supported by SVG

### ISSUE THREAD

**Issue by Ztachi** [apache/incubator-echarts#12853]
### Version
4.8.0

### Steps to reproduce
set "renderer: 'svg'" when initializing.
use  label: {
                        formatter: '{b|{b}}\n{d}',
                        rich: {
                            b:{
                                color:'#6EAEFF'
                            }
                        }
                    }

### What is expected?
ability to output text with label.rich style.
eg:xxxxx

### What is actually happening?
final result output string instead of compiled template,styled text
eg:{b|xxxxx}

**Comment by pissang** [comment]
We've refact the text rendering module in 5.0. It will be supported then:)
