### ISSUE TITLE
雷达图三星S8手机点击事件不灵敏

### ISSUE THREAD

**Issue by adu8419** [apache/incubator-echarts#12863]
### Version
4.8.0

### Steps to reproduce
配置项：
 silent: false,
 triggerEvent: true, 

//点击事件代码
this.charts.on('click', function (params) {
             console.log(123)    
  });

### What is expected?
每次点击雷达图指示器文字都能执行console.log(123)

### What is actually happening?
偶尔执行， 偶尔不执行 ，有时候点击一次就执行，有时候需要多次点击才执行。

**Comment by adu8419** [comment]
我测试了echarts 3.6 以上的 所有版本都有这个问题   （ 三星S8手机）

**Comment by plainheart** [comment]
谢谢反馈，不过你已经在#12854中报告过该问题，无需重新创建新的issue，后续请在#12854中讨论。
