### ISSUE TITLE
timeline controlStyle *Icon配置base64图片导致游览器卡死

### ISSUE THREAD

**Issue by 249118256** [apache/incubator-echarts#12867]
timeline controlStyle *Icon配置base64图片导致游览器卡死

**Comment by 249118256** [comment]
版本4.8.0

**Comment by plainheart** [comment]
能否提供一个可复现的demo？出现卡死的是什么浏览器？

**Comment by GiserDu** [comment]
版本 4.1.0 遇到同样的问题，以'image://url' 或 dataURI加载自定义图片都会使页面卡死，demo如下 https://gallery.echartsjs.com/editor.html?c=xc2uz1u2Jo&v=2

**Comment by GiserDu** [comment]
> 能否提供一个可复现的demo？出现卡死的是什么浏览器？

demo已提供，麻烦看一下

**Comment by plainheart** [comment]
@GiserDu 已复现，感谢反馈，后续会修复这个问题。
