### ISSUE TITLE
visualMap dimension参数使用异常

### ISSUE THREAD

**Issue by linwei-yoh** [apache/incubator-echarts#12860]
### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xhXjIxXGPw&comment=0](https://gallery.echartsjs.com/editor.html?c=xhXjIxXGPw&comment=0)

### Steps to reproduce
1.直接运行能看到一个连线断开的效果.
2.将visualMap.dimension从0改为2,再运行. 

### What is expected?
dimension等于0或2时候,因为对应维度下的值一致,期望得到的效果也一致

### What is actually happening?
dimension = 2时,点变色单连线没断开

---
因为在二维数据情况下,希望某两个点之间的连线不显示.  根据文档描述,期望通过增加一个存储序号的维度数据,使用visualMap来进行显示筛选.
但是实际测试发现,修改用例的dimension在0和1的时候才能,根据配置的pieces达到预期效果.
而无法通过额外增加的维度数据来筛选.

**Comment by susiwen8** [comment]
Same with #12818

**Comment by linwei-yoh** [comment]
thanks...
