### ISSUE TITLE
bar的emphasis的Color为CallBack函数时候，颜色设定混乱

### ISSUE THREAD

**Issue by magicdict** [apache/incubator-echarts#12881]
### Version
4.8.0

### Steps to reproduce
网络重现：http://datavisualization.club:8081/basic/bar

代码：https://github.com/magicdict/VisLab/blob/master/src/app/Bar/bar_basic.component.ts

    this.RainbowSample = BarOption.CreateBar(category, value);
    this.RainbowSample.xAxis["show"] = false;
    let normal: Bar_itemStyle = {
      color: this.getColor,
      opacity: 0.5
    };
    let emphasis: Bar_itemStyle = {
      color: this.getColor,
      opacity: 1
    };
    BarOption.SetItemStyle(this.RainbowSample.series[0], normal, emphasis);

BarOption是自己封装的方法。
发现emphasis的Color是一个固定的颜色字符的时候，没有问题。

### What is expected?
彩虹柱状图在平时是透明的，鼠标悬停是不透明的

### What is actually happening?
鼠标悬停时候，不透明，但是颜色不对。
好像CallBack函数没有被执行到。如果不支持CallBack，文档请注明，谢谢。

**Comment by magicdict** [comment]
![image](https://user-images.githubusercontent.com/897796/86224251-37f06000-bbbb-11ea-822a-8413a869a047.png)
鼠标悬停之后，颜色都变成了不透明的紫色了。

**Comment by plainheart** [comment]
Hi, 能否在 https://gallery.echartsjs.com/editor.html 上提供一个简单的示例以便复现？

**Comment by magicdict** [comment]
@plainheart 
https://gallery.echartsjs.com/editor.html?c=x4lQvQ-reM&v=1

问题原因我找到了。

```json
  emphasis:{
            itemStyle:{
                color:getColor,
                opacity: 1
            }
        }
```

itemStyle节去掉就好了，改成这样子就好了

```json
  emphasis:{
                color:getColor,
                opacity: 1
        }
```

**Comment by plainheart** [comment]
似乎是不生效，暂时可以先通过对每个data设置emphasis样式来解决。
https://gallery.echartsjs.com/editor.html?c=x4lQvQ-reM&v=2

**Comment by magicdict** [comment]
@plainheart 
其实只要不去设置高亮的时候的颜色，只设置透明度为1就可以达到效果了，这里只是想知道CallBack是否生效。如果不改这个问题，就把文档改了吧，直接写明不支持CallBack函数即可。

**Comment by plainheart** [comment]
好的，感谢反馈，后续会考虑支持更多回调函数。
