### ISSUE TITLE
Is there a way to show labels using a line in word map

### ISSUE THREAD

**Issue by TharinduMoraDs** [apache/incubator-echarts#12888]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/28983127/86238888-f9a77080-bbbb-11ea-9f24-ed7ec7ec289f.png)
### What problem does this feature solve?
Can we point out a location on a world map using a line?  And the end of the line should be the label. 

### What does the proposed API look like?
For example, in the pie chart, we can put the label outside and point the potion using a line

**Comment by plainheart** [comment]
Closed. Duplicate with #12887.
