### ISSUE TITLE
Page indicator on Legend does not respect theme value

### ISSUE THREAD

**Issue by ilueckel** [apache/incubator-echarts#12885]
### Version
4.8.0

### Steps to reproduce
Open this demo chart: https://echarts.apache.org/examples/en/editor.html?c=pie-legend&theme=dark

Focus on the page indicator of the legend.

### What is expected?
I expect the text, showing on which page you are, to have the same font-color as legend-items.
The activated caret to click either page-up or page-down should also easily distinguishable from the background

### What is actually happening?
The page indicator (the textual ones, that show on which page you are) is not readable (due to font-color). 
Also the dark caret icon is barely noticeable.

![image](https://user-images.githubusercontent.com/1216059/86229391-f1d1d700-bb8f-11ea-82cc-36f1030304cb.png)

**Comment by susiwen8** [comment]
@ilueckel Hi, you can use this https://echarts.apache.org/en/option.html#legend.pageTextStyle
