### ISSUE TITLE
想通过dataset配置数据，但是地图上没有显示出来！

### ISSUE THREAD

**Issue by HoseaGuo** [apache/incubator-echarts#12883]
### Version
4.8.0

### Steps to reproduce
想要在地图上显示数据，如果在series里面data配置数据，是可以有数据显示出来的，
```
{
        geo: {
          map: 'china',
        },
        series: [
          {
            type: 'scatter',
            coordinateSystem: 'geo',
            data: convertData(data),
          }
        ],
      }
```

但是如果在dataset的source配置，就显示不出来了，是什么原因？
```
{
        geo: {
          map: 'china',
        },
        series: [
          {
            type: 'scatter',
            coordinateSystem: 'geo', 
            // data: convertData(data),
          }
        ],

        dataset: {
          source: convertData(data),
        }

      }
```

### What is expected?
想在dataset里面配置source可以显示数据出来

### What is actually happening?
没有显示数据出来

**Comment by plainheart** [comment]
建议仔细阅读 [教程：使用 dataset 管理数据](https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE) 后再尝试一下。
