### ISSUE TITLE
series-tree. edgeForkPosition文档描述有误

### ISSUE THREAD

**Issue by ldc-37** [apache/incubator-echarts#12896]
### Version
\-

### Steps to reproduce
series-tree. edgeForkPosition的文档中说明，要求series-tree. edgeShape = 'curve' 
此处应该有误，curve是指曲线，而前文说需要是折线。
中英文文档都是如此

### What is expected?
要求series-tree. edgeShape = 'polyline' 

### What is actually happening?
series-tree. edgeShape = 'curve' 

---
https://echarts.apache.org/en/option.html#series-tree.edgeForkPosition

**Comment by plainheart** [comment]
感谢反馈，按照源码来看，应该是文档的错误，稍后会修正下。

**Comment by plainheart** [comment]
Fixed in https://github.com/apache/incubator-echarts-doc/commit/d5df68e5f674a6b1f5b63bcf2d801431a1502159
