### ISSUE TITLE
echart legend.borderRadius 设置无效

### ISSUE THREAD

**Issue by zhaosheng808** [apache/incubator-echarts#12899]
### Version
4.8.0

### Steps to reproduce
按照官网配置项配置legend 的圆角 设置后圆角效果无效，在官网给出的demo中配置也无效
单独设置和分别设置都无效
[https://echarts.apache.org/zh/option.html#legend.borderRadius](https://echarts.apache.org/zh/option.html#legend.borderRadius)
```
// 单独设置
legend: {
    borderRadius: 14
  },
// 分别设置
legend: {
    borderRadius: [14, 14, 14, 14]
  },
```

### What is expected?
圆角效果需要根据传递的值发生变化

### What is actually happening?
圆角效果未发生变化

官网配置项截图
![image](https://user-images.githubusercontent.com/26834525/86423811-4e113400-bd13-11ea-8bb4-b5982f738c09.png)

**Comment by pissang** [comment]
legend 的 borderRadius 是用在背景上的，需要先设置 backgroundColor

**Comment by zhaosheng808** [comment]
> legend 的 borderRadius 是用在背景上的，需要先设置 backgroundColor

非常感谢，这边试了一下，确实这个是设置顶部整体背景的圆角的，设置单个legend的样式 是 通过`icon`来设置的。
// ECharts 提供的标记类型包括 'circle', 'rect', 'roundRect', 'triangle', 'diamond', 'pin', 'arrow', 'none'可以通过 'image://url' 设置为图片，其中 URL 为图片的链接，或者 dataURI。
```
icon: "circle",  
```
![image](https://user-images.githubusercontent.com/26834525/86425680-60da3780-bd18-11ea-8b09-ac1b6fc43774.png)

// borderRadius 和 backgroundColor 效果
![image](https://user-images.githubusercontent.com/26834525/86425853-cfb79080-bd18-11ea-8d41-6749de6016ee.png)

**Comment by EquinoxFlowerJG** [comment]
为什么不能直接设置图例图形的圆角呢？难道用到圆角时非得整张图片上去？实现个圆角就那么难吗？希望能加上这个功能！Why can not set borderRadius of the legend's icon directly? Must I use a picture when I want to set icon's borderRadius?? How difficult to add the feature? Hope the feature can be added!
