### ISSUE TITLE
Heatmap parts are not visible when you zoom in on the borders

### ISSUE THREAD

**Issue by GaspardC** [apache/incubator-echarts#12898]
### Version
4.7.0

### Steps to reproduce
Implement a chart with a heatmap and a datazoom

then zoom in to the borders

example : https://imgur.com/a/cd009hN

### What is expected?
The heatmap "rectangles" that cannot be displayed entirely are white (not visible)

### What is actually happening?
It would be nice to display them even partially.

**Comment by plainheart** [comment]
Could you please provide an online demo? Thank you!

**Comment by GaspardC** [comment]
Hello for sure here it is [https://codepen.io/gaspc/pen/eYJyMxb](https://codepen.io/gaspc/pen/eYJyMxb),

Then try to zoom in.

**Comment by GaspardC** [comment]
I found the solution if it can help someone else : 
it's pretty easy actually but not very clear in the documentation, you need just to add `filerMode: 'none'` to your **dataZoom** objects

**Comment by plainheart** [comment]
Oh... Sorry for my late note. Though it can be solved by `filterMode: 'none'`, I think personally it's a flaw of `dataZoom` component. Maybe there is still something to be done. @pissang What do you think of this case?
