### ISSUE TITLE
Sankey: Nodes are not within visible canvas if height is 100%

### ISSUE THREAD

**Issue by dominic-simplan** [apache/incubator-echarts#12895]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/en/option.html#series-sankey.height](https://echarts.apache.org/en/option.html#series-sankey.height)

### Steps to reproduce
Go here: https://echarts.apache.org/en/option.html#series-sankey.height, select "Try it" and change height to 100%. 
"Oil reserves" and "Biofuel Imports" are not within the visible area anymore.

### What is expected?
All nodes should be within the visible area at height = 100%

### What is actually happening?
Some nodes are outside of the visible area at height = 100%

**Comment by plainheart** [comment]
You can set [`series-sankey.top`](https://echarts.apache.org/en/option.html#series-sankey.top) as `0` when `height` is `100%`. The default value of `top` is `5%`. The example provided in `Try it` panel doesn't set this option, so the chart may be overflow.

**Comment by dominic-simplan** [comment]
Okay so when setting the height i need to consider the current "top" value. Do I also need to consider the "bottom" value? Actually it seems like the "bottom" value doesn't have any effect. At least if I change it using "Try it", nothing in the diagram changes?
