### ISSUE TITLE
直角坐标系，两条Y轴，一条type为value,另一条type为category

### ISSUE THREAD

**Issue by ZzzNoName** [apache/incubator-echarts#12892]
直角坐标系，定义好了两条Y轴（对应关系），初始加载时刻度线对齐，缩放功能使用放大，刻度线不对齐
![image](https://user-images.githubusercontent.com/46550504/86308383-a5e46800-bc4b-11ea-8ffe-58b010a1da8b.png)
放大之后
![image](https://user-images.githubusercontent.com/46550504/86308449-d0cebc00-bc4b-11ea-8aad-2b21d3c9d2ac.png)

Y轴刻度出现不对齐

**Comment by ZzzNoName** [comment]
问题没有解决怎么被关了呢

**Comment by plainheart** [comment]
与 #12893 问题重复，相关截图和信息已经合并至 #12893
