### ISSUE TITLE
ECHARTS is not friendly to RGBA support

### ISSUE THREAD

**Issue by JsDeng** [apache/incubator-echarts#12910]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xGAcmLY-q9&v=2](https://gallery.echartsjs.com/editor.html?c=xGAcmLY-q9&v=2)

### Steps to reproduce
The mouse slides in several bars to reproduce

### What is expected?
The mouse hovers over the liability column and the bar chart is displayed normally

### What is actually happening?
Hover over the liability column, the bar chart does not show

---
The problem will occur with RGBA color values

**Comment by plainheart** [comment]
Hi, I'm afraid that there is an incorrect usage of the color of `rgba` and `rgb`.
If `rgba` is used, it should be like `rgba(158, 208, 255, 1)`, that is, four parameters should be provided.
If `rgb` is used, it should be like `rgb(158, 208, 255)`, that is, three parameters should be provided.

Please have a try again according to this.

**Comment by JsDeng** [comment]
> ### Version
> 4.8.0
> 
> ### Reproduction link
> https://gallery.echartsjs.com/editor.html?c=xGAcmLY-q9&v=2
> 
> ### Steps to reproduce
> The mouse slides in several bars to reproduce
> 
> ### What is expected?
> The mouse hovers over the liability column and the bar chart is displayed normally
> 
> ### What is actually happening?
> Hover over the liability column, the bar chart does not show
> 
> The problem will occur with RGBA color values



> Hi, I'm afraid that there is an incorrect usage of the color of `rgba` and `rgb`.
> If `rgba` is used, it should be like `rgba(158, 208, 255, 1)`, that is, four parameters should be provided.
> If `rgb` is used, it should be like `rgb(158, 208, 255)`, that is, three parameters should be provided.
> 
> Please have a try again according to this.

Thank you for being busy to demystify me.
