### ISSUE TITLE
Progress of Next Major Version: 5.0

### ISSUE THREAD

**Issue by pissang** [apache/incubator-echarts#12926]
# Progress of Next 5.0

This issue is about tracking our development progress of the next version 5.0.

Some notes before we start the review of 5.0 progress:

#### Development branch of 5.0:
https://github.com/apache/incubator-echarts/tree/next

#### How to run the branch

```shell
# Goto zrender folder and switch to next branch
cd ${ZRENDER_FOLDER}
git checkout next

# Switch to next branch in echarts
cd ${ECHARTS_FOLDER}
git checkout next
npm install

# Delete the installed zrender and soft link the local zrender folder
# Notice: must do the soft link after npm install. 
rm -r node_modules/zrender
ln -s ${ZRENDER_FOLDER} node_modules/zrender
# For Windows CMD
# Notice: must run as administrator
rd /s node_modules/zrender
mklink /D "node_modules/zrender" "${ZRENDER_FOLDER}"

npm run dev:fast
```

The distribution file is `dist/echarts.js`.

#### Releasing schedule:
5.0-alpha will be available in the late July. And the stable release will be published in the late of September.

## 1. Migrate Code Base to TypeScript

We migrated our codebase to TypeScript. It's not an easy job, but we are glad we've made this tough decision at the beginning. And now we benefit a lot from it when refacting codes to add new features.

## 2. Animation Improvement for Storytelling

This topic includes several animation features for having better experiences in storytelling.

### 1) Bar Chart Race

This feature introduces the fancy racing animation in the bar series.

#### Assignee

[Ovilia](https://github.com/Ovilia/)

#### Related pull request

https://github.com/apache/incubator-echarts/pull/12484

### 2) Line Chart Race

This feature introduces the fancy racing animation in line series.

#### Assignee

[Ovilia](https://github.com/Ovilia/)

### 3) Animation in Custom Series

This feature introduces a flexible animation configuration in custom series.

#### Assignee

[100pah](https://github.com/100pah/)

#### Related pull request

https://github.com/apache/incubator-echarts/pull/12775

### 4) Shape morphing

Shape morphing provides the ability to transit between different shapes. Like sector in pie and rectangle in bar.

#### Assignee
[Ovilia](https://github.com/Ovilia/)

#### Assignee

[pissang](https://github.com/pissang/)

#### Related pull request

https://github.com/apache/incubator-echarts/pull/12911

#### Assignee

[100pah](https://github.com/100pah/)

#### Assignee

[Ovilia](https://github.com/Ovilia/)

#### Related pull request

https://github.com/apache/incubator-echarts/pull/12859

## 6. Provide More States in User Interaction

This feature introduces blur/select states and related user interactions in ECharts.

#### Assignee

[pissang](https://github.com/pissang/)

#### Related pull request

https://github.com/apache/incubator-echarts/pull/12925

#### Assignee

[Ovilia](https://github.com/Ovilia/)

#### Related pull request

https://github.com/ecomfe/zrender/pull/570

## 8. Accessibility

Support pattern settings and provide a few themes for accessibility @Ovilia

## 9. i18n

###Assignee
[Zakwu](https://github.com/wf123537200)

#### Related pull request
#13038 

- [x] Provide language packages in the form of extensions
- [] Time formatter for different languages

## 10. Misc

More issues can be found in https://github.com/apache/incubator-echarts/milestone/10

#### Assignee

[Ovilia](https://github.com/Ovilia/)

#### Related pull request

https://github.com/apache/incubator-echarts/pull/11684

#### Assignee

[pissang](https://github.com/pissang/)

### 5) Enable to partial remove components

#6202 #4356 #4033 #8246 #3002

[discuss](https://lists.apache.org/thread.html/r5b22dbf848080b5d5842f9c423ca5a2034e015bc107531bd0071bc0a%40%3Cdev.echarts.apache.org%3E)

#### Assignee

[100pah](https://github.com/100pah/)

#### Related pull request

https://github.com/apache/incubator-echarts/pull/13008

### 7) SVG background

#12765 #4537
Enable the example like book seat in cinema, flight, ...

**Comment by susiwen8** [comment]
I can't successfully build `next` branch and throw `Could not resolve zrender`.

**Comment by plainheart** [comment]
@susiwen8 `zrender` also should be switched to `next` branch.

**Comment by susiwen8** [comment]
@plainheart Thanks, maybe this should be added

**Comment by pissang** [comment]
@susiwen8 Added how to link zrender. Sorry for missing it.

**Comment by plainheart** [comment]
Added how to create a soft link to `zrender` for those developers who are using Windows CMD.

**Comment by Ovilia** [comment]
@plainheart Thanks. Where did you make the changes? I didn't see that in [wiki history](https://github.com/apache/incubator-echarts/wiki/How-to-setup-the-dev-environment/_history).

**Comment by plainheart** [comment]
> Where did you make the changes? I didn't see that in [wiki history](https://github.com/apache/incubator-echarts/wiki/How-to-setup-the-dev-environment/_history).

Just added it into `How to run the branch
` area for this issue. Is it needed to add to Wiki?

**Comment by plainheart** [comment]
@Ovilia Done. I think it might be a little beneficial to developers who are using Windows.

**Comment by Ovilia** [comment]
@plainheart Thanks!

**Comment by Ovilia** [comment]
Please follow https://github.com/apache/incubator-echarts/projects/6 for 5.0 status updates.

**Comment by JinxCarry9527** [comment]
之前官网是有一个网友写的图表demo怎么没有了呢

**Comment by pissang** [comment]
@JinxCarry9527 https://gallery.echartsjs.com/
