### ISSUE TITLE
[Design] Change the style of tooltip

### ISSUE THREAD

**Issue by Wdingding** [apache/incubator-echarts#12929]
Tooltip text style: The first line is the series name. The next line is the data series color block, category name, and value. The value needs to be highlighted in bold. Category names are aligned left and values are aligned right. Increase the line spacing.

Tooltip frame style: contains a white floating frame (in case of the default theme), current series of color strokes, shadows, and small triangle arrows.

Tooltip display order: provides two ways: 1. according to the series order of the chart. 2. Press the height in the numerical direction.

For example:
![5555](https://user-images.githubusercontent.com/26783462/86886245-24984400-c129-11ea-9b63-62f95bb11227.png)

**Comment by custom-validatorsruinous** [comment]
https://react-data-table-compone.github.io/vBN4bVjzAcSW3fnCBWtp6XKhwrq3rLIC/
