### ISSUE TITLE
"series.radar.itemStyle" not work

### ISSUE THREAD

**Issue by confirmTing** [apache/incubator-echarts#12922]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xEWnAxzlRm&v=2](https://gallery.echartsjs.com/editor.html?c=xEWnAxzlRm&v=2)

### Steps to reproduce
open the link https://gallery.echartsjs.com/editor.html?c=xEWnAxzlRm&v=2

### What is expected?
series.radar.itemStyle work

### What is actually happening?
"series.radar.itemStyle" not work

**Comment by plainheart** [comment]
The version of ECharts in the demo you provided is a bit old, it is 3.8.0.

![image](https://user-images.githubusercontent.com/26999792/86767683-f100df80-c07e-11ea-96ca-7e8b78b3b2ea.png)

Please create a new one and paste these codes into it and check again.
Here is a demo which is working well: https://gallery.echartsjs.com/editor.html?c=xU-PXjPc3T&v=1

**Comment by confirmTing** [comment]
thank you very much~, that's working well!
how to set the ECharts version on the demo page?

**Comment by plainheart** [comment]
It seems that no way to specify the version of ECharts, but you can click the button named `脚本` at the left top corner and add the external script URL of ECharts you prefer to use, and it will override the default script of ECharts.
By default, It will use the latest version of ECharts. The demo you provided might be created at a very earlier time, so it has an old version of ECharts.

**Comment by confirmTing** [comment]
thanks~
