### ISSUE TITLE
希望直角坐标系新增单位字段显示在轴的顶部

### ISSUE THREAD

**Issue by liyangyangi** [apache/incubator-echarts#12920]
### What problem does this feature solve?
title显示在左侧的同时 顶部能够显示单位

### What does the proposed API look like?
yAxis:{
  unit:{
    show:false,
    label:'',
  },
  unitTestStyle:{
    color:'',
    fontSize:12,
  }
}

**Comment by yufeng04** [comment]
```
 yAxis:[
    {
        type: 'value',
        name: 'title',
        nameLocation: 'middle',
         position:'left'
    },
    {
        type: 'value',
        name: 'unit',
        nameLocation: 'end',
        position:'left'
    }
   ]
```
这样可以满足需求吗？

**Comment by liyangyangi** [comment]
就是新增一条空的Y轴只定义单位吗，好像可以，我怎么没想到呢哈哈我晚会试试，谢谢你
