### ISSUE TITLE
[Design] text font support "em" unit

### ISSUE THREAD

**Issue by Wdingding** [apache/incubator-echarts#12927]
When adjusting the size of the chart page, the size of the text percentage is supported.

<img width="1597" alt="4444" src="https://user-images.githubusercontent.com/26783462/86874642-59010580-c113-11ea-806d-d81bf6a87ca6.png">

**Comment by susiwen8** [comment]
This might be solved by https://github.com/ecomfe/zrender/pull/470

**Comment by pissang** [comment]
@susiwen8 Wow! didn't notice that. Can you make a PR to the next branch?

**Comment by susiwen8** [comment]
@pissang with pleasure!

**Comment by susiwen8** [comment]
@pissang done
https://github.com/ecomfe/zrender/pull/612

**Comment by susiwen8** [comment]
@pissang done

**Comment by pissang** [comment]
Great job!
