### ISSUE TITLE
折线图的线出现交叉

### ISSUE THREAD

**Issue by thelastto** [apache/incubator-echarts#12932]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xlnrHfUliT&v=2](https://gallery.echartsjs.com/editor.html?c=xlnrHfUliT&v=2)

### Steps to reproduce
1. 打开重现链接

### What is expected?
折线不出现交叉

### What is actually happening?
折线有交叉

**Comment by plainheart** [comment]
应该不是个Bug，可以考虑设置 [`smoothMonotone: 'x'`](https://echarts.apache.org/zh/option.html#series-line.smoothMonotone) 使其在x轴保持单调性。

**Comment by thelastto** [comment]
> 应该不是个Bug，可以考虑设置 [`smoothMonotone: 'x'`](https://echarts.apache.org/zh/option.html#series-line.smoothMonotone) 使其在x轴保持单调性。

可以了～十分感谢
