### ISSUE TITLE
[Design] The distance between individual columns is set to 1/2 of the width of the column itself.

### ISSUE THREAD

**Issue by Wdingding** [apache/incubator-echarts#12935]
By default, the distance between individual columns is set to 1/2 of the width of the column itself.

![8888](https://user-images.githubusercontent.com/26783462/86891204-0cc4be00-c131-11ea-9900-bfdbc500ae15.png)

**Comment by quillblue** [comment]
@Wdingding I'm trying to help on this, do you have any guidance on bar gap for multiple bar series on same coord grid?

**Comment by pissang** [comment]
@quillblue Ahhhhh, just noticed your comment after I committed this improvement

**Comment by quillblue** [comment]
@pissang never mind. I can learn from your code and work on others:)
