### ISSUE TITLE
minimum example for world map in echart

### ISSUE THREAD

**Issue by luisenriqueramos1977** [apache/incubator-echarts#12930]
### Version
4.8.0

### Steps to reproduce
I have reproduced some of the examples listed in the tutorial, following the steps indicated in this examples:

https://echarts.apache.org/en/tutorial.html#Create%20Custom%20Build%20of%20ECharts, 

for the case of maps, I added the line 

import 'echarts/src/chart/map';

in the echarts.custom.js, and generate the file echarts.custom.min.js. 

However when I try to render the map of world, I get a blank page, 

for me it is okay a blank map, because I am learning the basic yet, but I was not able to get the result here, while I get it with the others, the full code i s here, what am I missing?

*******************************************************code **********************************************************************

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="lib/echarts.custom.min.js"></script>
</head>
<body>
    
    <div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">

    require('echarts/map/js/world');

        // based on prepared DOM, initialize echarts instance
        var myChart = echarts.init(document.getElementById('main'));

        // specify chart configuration item and data
        var option = {
                geo: {
                map: "world",
                },
            series : [
                {
                type: 'scatter',
                coordinateSystem: 'geo',
                data: []
            }
        ]
    };

        // use configuration item and data specified to show chart
        myChart.setOption(option);
    </script>
</body>
</html>

### What is expected?
map of world

### What is actually happening?
blank page

---
I am not sure if I am importing the map properly, I would like to have  a minimum example, with a blank map

**Comment by plainheart** [comment]
`echarts/map/js/world` may need to be packaged to `echarts.custom.min.js` or just import it with a script tag after importing `echarts.custom.min.js`.

**Comment by luisenriqueramos1977** [comment]
thanks, I followed the second option, and the final code that worked for me was this:

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="lib/echarts.custom.min.js"></script>
    <script src="node_modules/echarts/map/js/world.js"></script>

</head>
<body>  
    
    <div id="main" style="width: 1600px;height:1400px;"></div>
 
    <script type="text/javascript">
        
            // based on prepared DOM, initialize echarts instance
            var myChart = echarts.init(document.getElementById('main'));
        
            // specify chart configuration item and data
            var option = {
                series: [{
            type: 'map',
            map: 'world'
        }]
        };
        
            // use configuration item and data specified to show chart
            myChart.setOption(option);
        </script>

</body>
</html>

**Comment by plainheart** [comment]
OK, I'm glad that helped you.
