### ISSUE TITLE
Converting JSON file to GEXF file format

### ISSUE THREAD

**Issue by felicia-lim2503** [apache/incubator-echarts#12946]
### What problem does this feature solve?
I'm currently using Javascript to implement the circular layout graph (https://echarts.apache.org/examples/en/editor.html?c=graph-circular-layout).

The input data used in the sample codes uses JSON file and it is converted to GEXF file. However, there is no available JSON file to GEXF file converter available over the internet.

Really hope there is a solution for this as I can't find any other solutions.

Thank you!

### What does the proposed API look like?
A JSON file to GEXF file converter - converts JSON file to GEXF file to insert data into echarts circular layout graph.

**Comment by plainheart** [comment]
What does the JSON file look like?

**Comment by felicia-lim2503** [comment]
@plainheart this is how the JSON file looks like -> https://github.com/hecore/echart_demo/blob/master/data/hecore.json

**Comment by plainheart** [comment]
I saw the content format of JSON file you provided is just right for graph and no need to parse JSON to GEXF, you may use it directly.

**Comment by felicia-lim2503** [comment]
@plainheart but if you look at the sample codes of the graph, it is using gexf file format for the input data -> https://echarts.apache.org/examples/en/editor.html?c=graph-circular-layout

**Comment by plainheart** [comment]
Yes, I see. In fact, you may remove these codes about fetching the GEXF file by Ajax, and use your JSON format data as the graph data.

**Comment by felicia-lim2503** [comment]
@plainheart oh yes it's working now. thanks! :)
