### ISSUE TITLE
Echarts线图支持将两点之间的线段断开吗

### ISSUE THREAD

**Issue by xiaobaiha** [apache/incubator-echarts#12942]
### What problem does this feature solve?
Echarts线图支持将两点之间的线段断开吗，使用category轴，默认点都是连接起来的，有什么办法或者配置可以将某两点的线抹除或者隐藏吗

### What does the proposed API look like?
series data disconnectPreviousPoint

**Comment by plainheart** [comment]
可以考虑设置需要断开那项数据为 `null` 或 `-`，并且不要设置 `connectNulls` 为 `true`。

**Comment by xiaobaiha** [comment]
> 可以考虑设置需要断开那项数据为 `null` 或 `-`，并且不要设置 `connectNulls` 为 `true`。

谢谢回复，目前需要的数据是每个点都有有效数据，只是把两个点之间的线条取消，，如果置为null的话是两条线都消失了，而且丢失了一个点的数据

**Comment by yufeng04** [comment]
```
lineStyle:{
      opacity: 0
}
```
@xiaobaiha  这样可以吗？

**Comment by huanglp3368** [comment]
看下这个例子 https://echarts.apache.org/examples/zh/editor.html?c=line-sections 使用visualMap 把需要断开的两点间的线颜色设置为"transparent“; 试一下吧 获取可以的，我用过类似的

**Comment by xiaobaiha** [comment]
> 看下这个例子 https://echarts.apache.org/examples/zh/editor.html?c=line-sections 使用visualMap 把需要断开的两点间的线颜色设置为"transparent“; 试一下吧 获取可以的，我用过类似的

感谢，这就是我想要的效果
