### ISSUE TITLE
希望可以支持堆叠图正序，或者倒序的配置

### ISSUE THREAD

**Issue by confirmTing** [apache/incubator-echarts#12944]
### What problem does this feature solve?
希望可以获得从上至下的一致性效果，而不是默认的从下至上

### What does the proposed API look like?
无

希望的顺序
![image](https://user-images.githubusercontent.com/17754892/87023042-dad35a80-c209-11ea-89b0-682540940b3e.png)

实际的顺序
![image](https://user-images.githubusercontent.com/17754892/87023129-efafee00-c209-11ea-8573-2526f9988824.png)

**Comment by confirmTing** [comment]
期望效果： 张三是紫色，李四是青色，王五是绿色.. 依次类推

**Comment by plainheart** [comment]
和 #12929 的部分需求有些相关，不过这个目前通过调整 legend 顺序和使用 tooltip formatter 暂时也可以实现，示例：https://gallery.echartsjs.com/editor.html?c=x2f1uPXMSK&v=1

**Comment by confirmTing** [comment]
@plainheart  非常感谢！
