### ISSUE TITLE
ToolTip远离图表

### ISSUE THREAD

**Issue by magicdict** [apache/incubator-echarts#12966]
### Version
4.8.0

### Steps to reproduce
        this.Sample.tooltip = {
            show: true,
            position: 'inside',
            trigger: 'item',
            confine:true
        };

### What is expected?
ToolTIp在图表附近

### What is actually happening?
ToolTip远离图表

**Comment by magicdict** [comment]
![image](https://user-images.githubusercontent.com/897796/87502068-3fbc0400-c693-11ea-8b0c-0fef2c36ca91.png)

**Comment by magicdict** [comment]
![image](https://user-images.githubusercontent.com/897796/87502104-51051080-c693-11ea-934f-58798a09693f.png)

**Comment by magicdict** [comment]
不是很理解ToolTip的表示位置是如何确定的，能否说明一下。按照道理说，应该表示在chart范围内部才是。

**Comment by plainheart** [comment]
这应该不是bug，请检查下是否为样式设置问题，如果你确认是bug，最好能提供一个可复现的示例。示例可以在 [ECharts Gallery](https://gallery.echartsjs.com/editor.html) 或者 [Code Pen](https://codepen.io/Ovilia/pen/dyYWXWM) 上提供。

**Comment by magicdict** [comment]
@plainheart 虽然看了源代码，无奈没有看懂计算过程。
好在发现只要把上层div的position改成relative就可以了。（我这个case，root层有个margin-left，所以导致了charts组件层x方向计算的时候多加了margin-left的值，改为relative之后，应该是和顶层独立开来计算了。。）

**Comment by magicdict** [comment]
追记一下，echarts上层的div，最好都加上position: relative;这句，不然，tooltips就可能乱飞出图表界限
