### ISSUE TITLE
about /scatter-visualMap-piecewise

### ISSUE THREAD

**Issue by Famine-Life** [apache/incubator-echarts#12975]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=doc-example/scatter-visualMap-piecewise](https://echarts.apache.org/examples/zh/editor.html?c=doc-example/scatter-visualMap-piecewise)

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=doc-example/scatter-visualMap-piecewise

### What is expected?
鼠标悬浮到地图上的每一个点上的时候应该显示的是他们对应的值

### What is actually happening?
实际上是他们地点的维度

---
鼠标悬浮到地图上的每一个点上的时候应该显示的是他们对于的值，而不是他们的维度。

**Comment by ZhouXiaoL** [comment]
这个可以查找配置解决label.emphasis

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#visualMap-continuous.dimension

**Comment by plainheart** [comment]
这个与先前的 #12370, #8973, #10023, #12475 应该属于同一类问题，曾经在 #11973 中讨论过修复方法，不过似乎还未有定论和修复计划，暂时可以通过以下2种方式规避：
1) 使用 [`tooltip.formatter`](https://echarts.apache.org/zh/option.html#tooltip.formatter)
2) 使用 [`series.encode`](https://echarts.apache.org/zh/option.html#series-scatter.encode)，这个解决方案之前有提过PR，可以参考 ecomfe/echarts-examples#20。
```js
encode: {
  value: 2
}
```
或者
```js
encode: {
  tooltip: [2]
}
```
