### ISSUE TITLE
Echarts Bmap当在地图标点时散点坐标更新时地图会发生闪烁现象

### ISSUE THREAD

**Issue by 804180863** [apache/incubator-echarts#12978]
What problem does this feature solve?
问题：Bmap的散点图数据是用socket获取的 然后获取最新更新在图表上 我使用了myChart.setOption(newOption,true);
然后当数据更新时 地图也会闪烁
问题示例: https://github.com/804180863/echartssimpo/blob/master/1.html
双击打开即可看到
What does the proposed API look like?
我能使用什么 代替这个功能呢?
thank you

**Comment by plainheart** [comment]
建议去掉setOption的第二个参数，合并option，而不是覆盖option。

**Comment by 804180863** [comment]
> 建议去掉setOption的第二个参数，合并选项，而不是覆盖option。

但是 这个只是 例子 当我 将 散点根据型号分类的时候是series:[{第一类散点},{第二类散点},{第三类散点},{第四类散点}](颜色不同的点)
然后将分类取消 就变成了 series:[{所有散点}]  然后不加true 历史数据就会遗留在上面 加了true就会地图闪烁

**Comment by 804180863** [comment]
> 建议去掉setOption的第二个参数，合并option，而不是覆盖option。
就是我看了里面的数据 是series:[[所有散点],{第二类散点},{第三类散点},{第四类散点}] 就导致 234 在图表残留了

**Comment by plainheart** [comment]
可以把想去掉的那一类的散点series的data置为 `[]`，例如
```js
var option = chart.getOption();
option.series[2].data = [];
chart.setOption(option);
```

**Comment by 804180863** [comment]
> 可以把想去掉的那一类的散点series的data置为 `[]`，例如
> 
> ```js
> var option = chart.getOption();
> option.series[2].data = [];
> chart.setOption(option);
> ```

不行啊  这个数据有的时候会 几千条是实时的  除了这个还有什么推荐吗

**Comment by plainheart** [comment]
你是指 series 特别多吗？

**Comment by 804180863** [comment]
> 你是指 series 特别多吗？
对的 特别多 而且还是动态的 虽然我想到了使用遍历 将 内容清空  但是想问下还有更好的解决办法吗
为什么 true 会触发地图图层刷新呢?

**Comment by plainheart** [comment]
`notMerge` 为 `true` 意思是不合并配置项，整个图表将重新渲染，百度地图也会被重新创建，由于百度地图底图是瓦片，刷新的时候会重新请求瓦片数据，看起来会比较明显。

**Comment by 804180863** [comment]
> `notMerge` 为 `true` 意思是不合并配置项，整个图表将重新渲染，百度地图也会被重新创建，由于百度地图底图是瓦片，刷新的时候会重新请求瓦片数据，看起来会比较明显。

那就是 只能用清空的办法了.但是历史数据的问题 感觉会很麻烦 
感谢回答我的问题 ^_^
