### ISSUE TITLE
环形图标签居中重叠

### ISSUE THREAD

**Issue by ZhouXiaoL** [apache/incubator-echarts#12976]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x9Og7OYc_D&comment=0](https://gallery.echartsjs.com/editor.html?c=x9Og7OYc_D&comment=0)

### Steps to reproduce
设置label:{
     show: true,
       position: 'center'
}

### What is expected?
环形图标签和4.3版本一样不重叠

### What is actually happening?
环形图标签居中重叠

**Comment by plainheart** [comment]
与 #12875 问题重复。
