### ISSUE TITLE
I am

### ISSUE THREAD

**Issue by foliage11111** [apache/incubator-echarts#13027]
I know I want to use English, but I cant use English for my problem.
Is there a pie chart missing, or is there a problem with my description?
For example, we assess a persons condition in 8 (or N) dimensions.
The following list was obtained with a score of 10
Occupation |7
Finance | 7
Friends | 6
Networking | 5
FAMILY |7
Body | 8
Interest | 6
Personal Growth | 7
Self-actualization | 7

The table has 8 dimensions, each of which accounts for 12.5% of the pie chart, but the area saturation of the patties in each dimension is calculated on the basis of scores.
Its like a pizza where you slice 8 (or N) parts, and you bites every parts a little（not eat the whole parts）。

知道希望使用英语，但是我的问题无法使用英语
是否缺失了一种饼图，还是说我的描述有问题？
比如我们从8个（或者n个）方面评估一个人的状况。
得出了以下列表，得分满分为10分

职业 | 7
财务 | 7
朋友 | 6
人脉 | 5
家庭 | 7
身体 | 8
兴趣 | 6
个人成长 | 7
自我实现 | 7

这个表格有8个维度，每个维度占饼图的12.%的区域，但是每个维度下，的小饼块的面积饱和度则是根据得分来计算。
好比一个披萨大家切了8（或组合N）等分，每一份可能被咬了几口？
这种饼图似乎在echart里面没有

**Comment by foliage11111** [comment]
I think I have describ it very clear

**Comment by foliage11111** [comment]
a special pie charts 一种特殊的饼图 #13027
@susiwen8  没看懂为啥关掉，之前保存的有问题么？

**Comment by susiwen8** [comment]
Please use issue template. @foliage11111

**Comment by plainheart** [comment]
从文字描述上不太能明确你的需求，如果可以，能否提供一下示意图？
（建议按照bot提供的issue模板再开一个issue，详细描述下~）
