### ISSUE TITLE
Zoom in Chrome Browser, mouse event running wrong in svg > foreignObject

### ISSUE THREAD

**Issue by DoonPort0422** [apache/incubator-echarts#13028]
### Version
4.8.0

### Steps to reproduce
https://codepen.io/doonport0422/pen/vYLMabM

Open the above sample in Chrome, zoom your browser (e.g. 80%)

There are 2 charts: 
- 1st chart runs in root element.
- 2nd chart runs under a svg > g > foreignObject element.

On the 2nd chart: 
- Try to click on their bars, you will find that the mouse event will return unexpected offset X/Y.
- Or, just mouse over on the bar, you may find that bar may not be highlighted

PS: 1st chart has no problem.

### What is expected?
2nd chart's mouse events should be same as 1st chart

### What is actually happening?
2nd chart's mouse events is wrongly adjusted due to browser's zoom ratio.

**Comment by DoonPort0422** [comment]
FYI, the problem exists no matter echarts renders in 'svg' or not. 
```
echarts.init(container, null, {renderer: 'svg', ...size})
echarts.init(container)
```
_I mean the above 2 cases both can repeat the problem._

**Comment by MercusChan** [comment]
I got similar issue when browse with a 4K (hidpi) monitor.

**Comment by DoonPort0422** [comment]
FYI, this problem should be a chrome's bug. Besides the mouse's offset, the element size may be wrong too.
https://bugs.chromium.org/p/chromium/issues/detail?id=738022
https://bugs.chromium.org/p/chromium/issues/detail?id=976224

**Comment by j5272000** [comment]
We have the same problem

**Comment by DoonPort0422** [comment]
This problem is fixed in Chrome 87. Thanks.
