### ISSUE TITLE
怎么离线下载官网文档呢，中文版本的文档有一部分打不开了

### ISSUE THREAD

**Issue by ocian** [apache/incubator-echarts#13029]
### Version
4.8.0-rc.1

### Reproduction link
[https://echarts.apache.org/zh/option.html#series-bar](https://echarts.apache.org/zh/option.html#series-bar)

### Steps to reproduce
其他的地方可以打开，但是柱图这部分的打不开
配置项 -- series -- type: bar

### What is expected?
我希望看文档的时候不用等，这个文档的打开速度是使用 echarts 最大的障碍

### What is actually happening?
网速慢也就算了，现在直接看不了了

---
希望可以离线下载，就像其他前端库，比如 react，antd 那样，这样的打开速度是最快的  
期待您的回复

**Comment by plainheart** [comment]
抱歉，我们会尽快修复，感谢反馈。

**Comment by plainheart** [comment]
问题已修复。
