### ISSUE TITLE
获取地图空白处点击事件

### ISSUE THREAD

**Issue by gh-ray** [apache/incubator-echarts#13036]
### What problem does this feature solve?
点击地图空白处，清除地图选中，添加自定义逻辑

### What does the proposed API look like?
暂无

**Comment by gh-ray** [comment]
> 可参考如下逻辑实现。
> 
> ```js
> myChart.getZr().on('click', function(e) {
>    if (!e.target) {
>       // clicked empty area
>    }
> })
> ```

你好，请问你下，但是如果点击了地图，如何能获取到地图数据呢，原来点击可以直接返回 p 相关信息

**Comment by plainheart** [comment]
点击空白处为什么会需要获取地图数据？

**Comment by gh-ray** [comment]
已经解决，点击地图时候，拿到 target dataIndex，再去获取地图数据。感谢感谢！
