### ISSUE TITLE
配置项手册无内容

### ISSUE THREAD

**Issue by songlingxi** [apache/incubator-echarts#13050]
https://echarts.apache.org/zh/option.html#xAxis
https://echarts.apache.org/zh/option.html#xAxis

**Comment by plainheart** [comment]
未发现无法访问的情况，内容正常显示。请清除缓存或多次刷新再试试。

![image](https://user-images.githubusercontent.com/26999792/88911949-2620dc00-d291-11ea-9cca-e1f7af62c27c.png)

**Comment by plainheart** [comment]
问题应该已经被解决，请再试试看是否仍有问题。
