### ISSUE TITLE
关于Echarts突然不能正常绘图的问题

### ISSUE THREAD

**Issue by jnt9999** [apache/incubator-echarts#13069]
使用贵司的echarts在jupyter notebook里绘图，上周5还正常显示的好几个代码，昨天就不能显示了。
![image](https://user-images.githubusercontent.com/69127734/89135906-53a4a880-d563-11ea-99a8-aaf0737b4633.png)
![image](https://user-images.githubusercontent.com/69127734/89135916-5f906a80-d563-11ea-9e0f-99336c3bb0eb.png)

请问这问题该怎么解决？谢谢。

**Comment by plainheart** [comment]
从输出日志来看，未看到 ECharts 相关信息，请按照 bot 提供的建议，使用 [issue 模板](https://ecomfe.github.io/echarts-issue-helper/?lang=zh-cn) 重新提一个 issue，并附带更详细、明确的信息以供定位问题。
