### ISSUE TITLE
配置项手册无内容

### ISSUE THREAD

**Issue by vincentzxt** [apache/incubator-echarts#13061]
配置项手册 -> series -> graph各项属性点击后无内容

**Comment by plainheart** [comment]
未发现无法查看的问题，请查看控制台是否有错误输出，并清除缓存/多次刷新试试。

![image](https://user-images.githubusercontent.com/26999792/89019275-a4dc4e80-d34f-11ea-8429-faedb0764042.png)

**Comment by vincentzxt** [comment]
控制台输出跨域不能访问，其他界面都是OK的










在 2020-07-31 17:03:10，"Zhongxiang.Wang" <notifications@github.com> 写道：

未发现无法查看的问题，请查看控制台是否有错误输出，并清除缓存/多次刷新试试。

**Comment by plainheart** [comment]
有尝试过清除缓存吗？

**Comment by vincentzxt** [comment]
清楚过，浏览器也换了也不行，用手机访问也不行发自我的华为手机-------- 原始邮件 --------发件人： "Zhongxiang.Wang" <notifications@github.com>日期： 2020年7月31日周五 傍晚5:45收件人： apache/incubator-echarts <incubator-echarts@noreply.github.com>抄送： vincentzxt <vincent_zxt@163.com>, Author <author@noreply.github.com>主    题： Re: [apache/incubator-echarts] 配置项手册无内容 (#13061)

有尝试过清除缓存吗？

**Comment by wahoro** [comment]
我查看文档时也有这个问题，望能尽快解决

**Comment by plainheart** [comment]
@vincentzxt @wahoro 问题应该已经被解决，请再试试看验证下是否仍有问题。

**Comment by vincentzxt** [comment]
可以正常访问了
















在 2020-08-06 12:49:34，"Zhongxiang.Wang" <notifications@github.com> 写道：

@vincentzxt@wahoro 问题应该已经被解决，请再试试看验证下是否仍有问题。
