### ISSUE TITLE
echartsjs 下社区示例所有图片都失效，大部分例子出现错误

### ISSUE THREAD

**Issue by jummyliu** [apache/incubator-echarts#13075]
### Version
4.8.0

### Steps to reproduce
访问 https://gallery.echartsjs.com/ 域名，页面所有图片均无法访问；
原因是关闭了 https://www.echartsjs.com 下的域名，导致资源无法访问

### What is expected?
希望示例能正常访问，迁移到新域名，或者保留旧域名

### What is actually happening?
无法访问社区示例

**Comment by pissang** [comment]
谢谢反馈，正在修复

**Comment by pissang** [comment]
Fixed
