### ISSUE TITLE
wrong timestamp parser when xAxis type is 'time'

### ISSUE THREAD

**Issue by wlbksy** [apache/incubator-echarts#13073]
### Version
4.8.0

### Steps to reproduce
following timestamp is around ``2020-08-04 10:11:00``

```javascript
option = {
    xAxis: {
        data: [1596507060, 1596507160, 1596507260], // second
        type : 'time'
    },
    yAxis: {},
    series: [{
        type: 'line',
        data:[220, 182, 191]
    }]
};
```

```javascript
option = {
    xAxis: {
        data: [1596507060000, 1596507160000, 1596507260000], // micro second
        type : 'time'
    },
    yAxis: {},
    series: [{
        type: 'line',
        data:[220, 182, 191]
    }]
};
```

```javascript
option = {
    xAxis: {
        data: [1596507060.000, 1596507160.000, 1596507260.000], // second with decimal
        type : 'time'
    },
    yAxis: {},
    series: [{
        type: 'line',
        data:[220, 182, 191]
    }]
};
```

### What is expected?
According to [https://echarts.apache.org/en/option.html#series-line.data](https://echarts.apache.org/en/option.html#series-line.data), timestamp can be used as axis value when type is 'time'.
![image](https://user-images.githubusercontent.com/2433806/89245884-70f97580-d63c-11ea-9a6f-1a565d988b3c.png)

right parsing of x axis timestamp, timestamp is around ``2020-08-04 10:11:00``

### What is actually happening?
1. timestamp displays ``08:00:00``
2. wrong xaxis interval
3. wrong y axis value trending
![image](https://user-images.githubusercontent.com/2433806/89245594-bbc6bd80-d63b-11ea-8ef1-3832ba5fbc09.png)

**Comment by plainheart** [comment]
It may be not a bug but an incorrect usage. `xAxis.data` is just for the type of `category`. If the type is `time`, it can't be specified.
> [Category data, available in type: 'category' axis.](https://echarts.apache.org/en/option.html#xAxis.data)

When the type of xAxis is `time`, the time should be specified as a dimension in the `series.data`.

**Example:**

```js
option = {
    xAxis: {
        type : 'time'
    },
    yAxis: {},
    series: [{
        type: 'line',
        data:[
            [1596507060000, 220],
            [1596507160000, 182],
            [1596507260000, 191]
        ]
    }]
};
```

**Comment by wlbksy** [comment]
thanks.

**Comment by wlbksy** [comment]
@plainheart One more question, could we use Standard Unit like seconds as default timestamp unit, instead of javascript's milliseconds?

**Comment by plainheart** [comment]
@wlbksy I'm afraid we can't. For a numerical timestamp, ECharts will parse it to a Date object by `new Date(timestamp)`.

**Comment by akenverus** [comment]
There is no information in the docs about that for type 'time' of X axis the data should be formatted as a tuple, where the first element is actual time and second is value for that time: `[1596507060000, 12345]`
