### ISSUE TITLE
截断Y轴 / cut off yAxis

### ISSUE THREAD

**Issue by Nathan2020-0126** [apache/incubator-echarts#13071]
### What problem does this feature solve?
一个系列里的数据差异很大，最大的超过1000，最小的小于10，图表中小的柱子就很小，可否设置成Y轴变成两段，类似于这个https://upload-images.jianshu.io/upload_images/2077826-41fe06f658733647.png?imageMogr2/auto-orient/strip|imageView2/2。
The data size in one series were different, for example, biggest one could bigger than 1000, samllest one could less then 10, is it possible to cut off yAxis into two range. 0 ~ 50. 1000~1500.

### What does the proposed API look like?
{
cutoff:true,
range:[
[0,50],
[1000,1500]
]
}

**Comment by susiwen8** [comment]
Duplicate with #12790
