### ISSUE TITLE
实时动态曲线的动画不平滑，有顿挫感

### ISSUE THREAD

**Issue by wwwyyyccc123** [apache/incubator-echarts#13072]
### What problem does this feature solve?
让实时监测的结果更加美观的呈现。
目前在echarts图表库能找到的例子：
https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data，
实现的动态曲线动画是一顿一顿的，可否如下面这个例子一样，实现得更平滑一些？（即：每次更新数据动画不要停顿一下）
https://bost.ocks.org/mike/path/

### What does the proposed API look like?
如果现有的API，加上一些js可以实现就太好了。能否给一点建议或者提示？
`
animation: smooth,
`

**Comment by pissang** [comment]
可以试试把 animationEasing 改成 'linear'

然后你更新数据的频率也要控制成跟动画时长一样

**Comment by wwwyyyccc123** [comment]
> 可以试试把 animationEasing 改成 'linear'
> 
> 然后你更新数据的频率也要控制成跟动画时长一样

有效。非常感谢！！！

**Comment by clarkhillm** [comment]
我找到了一个比较好的解决办法，就是把x轴的数据和y轴的数据搞到一起。类似这样：
```
_.each(_.range(60), function (i) {
                state.cpu.series[0].data.shift();
                state.cpu.series[0].data.push(["00." + i, "-"]);
              ##});
```
这种情况下图形就是连续的，不会跳动了。
