### ISSUE TITLE
平滑曲线控制点的选择问题

### ISSUE THREAD

**Issue by xiaobaiha** [apache/incubator-echarts#13096]
### What problem does this feature solve?
现有的平滑控制点选择还会比较坐标的最大值和最小值，这个比较的必要性是什么呢

### What does the proposed API look like?
smoothMonotone

**Comment by xiaobaiha** [comment]
https://github.com/apache/incubator-echarts/issues/7158#issuecomment-364828528

**Comment by Ovilia** [comment]
[#7158 (comment)](https://github.com/apache/incubator-echarts/issues/7158#issuecomment-364828528) 的算法有点问题，已经被 revert 掉了。你这边具体是觉得什么时候有问题？可否提供一个例子？

**Comment by xiaobaiha** [comment]
> [#7158 (comment)](https://github.com/apache/incubator-echarts/issues/7158#issuecomment-364828528) 的算法有点问题，已经被 revert 掉了。你这边具体是觉得什么时候有问题？可否提供一个例子？

感谢回复，我是在学习echarts平滑算法时看到这里 https://github.com/apache/incubator-echarts/blob/450ee942587f51616a55feffc470eea20642831d/src/chart/line/poly.js#L239 做了对最大最小值的处理，想问下为什么要做一个这样的限制，是出于哪方面的考量？

**Comment by pissang** [comment]
@xiaobaiha 这个是为了保证 smooth 后的曲线不会超过一些极值，比如分数最高分是 100，但是如果不做这个约束的话，smooth 后有可能部分曲线就会超出 100
