### ISSUE TITLE
Install echarts using github link

### ISSUE THREAD

**Issue by sgurin** [apache/incubator-echarts#13091]
### Version
4.8.0

### Steps to reproduce
I was trying to install echarts using GitHub link https://github.com/apache/incubator-echarts#4.8.0 and there is no any lib folder. Also, missing main directive for NPM.

### What is expected?
Ok

### What is actually happening?
ERROR Failed to compile with 49 errors
These relative modules were not found:

./lib/chart/bar in ./node_modules/echarts/index.js
./lib/chart/boxplot in ./node_modules/echarts/index.js
./lib/chart/candlestick in ./node_modules/echarts/index.js
./lib/chart/custom in ./node_modules/echarts/index.js
./lib/chart/effectScatter in ./node_modules/echarts/index.js
./lib/chart/funnel in ./node_modules/echarts/index.js
./lib/chart/gauge in ./node_modules/echarts/index.js
./lib/chart/graph in ./node_modules/echarts/index.js

---
If package was downloaded via NPM it has lib folder. Unfortunately I cannot use NPM. What I am doing wrong?

**Comment by HHHui** [comment]
npm install echarts --save
maybe you can check the [tutorial](https://echarts.apache.org/en/tutorial.html#Get%20Started%20with%20ECharts%20in%205%20minutes).

**Comment by sgurin** [comment]
Unfortunately I cannot use NPM Package. Is there any way to install plugin thrown link? For example npm install https://github.com/apache/incubator-echarts#4.8.0

**Comment by HHHui** [comment]
maybe just use dist/echarts.min.js or use cdn https://cdnjs.cloudflare.com/ajax/libs/echarts/4.8.0/echarts.min.js ?

**Comment by sgurin** [comment]
So, there is no way to install echarts via NPM by direct link to the GitHub repo?

`npm install https://github.com/apache/incubator-echarts#4.8.0`

**Comment by plainheart** [comment]
@sgurin It can be installed as follows.
```shell
npm install https://github.com/apache/incubator-echarts.git#4.8.0
```

**Comment by sgurin** [comment]
Ok. Why the packages are different?

There is lib folder if I install echarts `npm install echarts `https://prnt.sc/tvhazs but via GitHub link it is not there https://prnt.sc/tvhbiz

**Comment by plainheart** [comment]
The `lib` folder is generated after building.
InstallIng from Github link is just to clone the repository without a release building, so this is different from NPM.
But you are still able to run the release command in the root of echarts to generate the `lib` folder.
```shell
npm run release
```
Hope that helps.

**Comment by sgurin** [comment]
Yeap, That exactly what I asked for.
