### ISSUE TITLE
The data point item style [borderColor] should has higher priority than series item style [borderColor]

### ISSUE THREAD

**Issue by katherinebai** [apache/incubator-echarts#13099]
### Version
4.7.0

### Steps to reproduce
Please use this option as following to reproduce the issue.
![image](https://user-images.githubusercontent.com/36399340/89629993-4bd16500-d8d1-11ea-8d2a-4bd3ab489f54.png)

-----------------------------------------------------------------------

option = {
	"animation": true,
	"backgroundColor": "#FFFFFF",
	"tooltip": {
		"trigger": "item"
	},
	"title": null,
	"legend": {
		"show": true,
		"orient": "vertical",
		"align": "left",
		"backgroundColor": "transparent",
		"borderColor": "transparent",
		"borderWidth": 1,
		"borderType": "solid",
		"textStyle": {
			"color": "#000000",
			"fontFamily": "'Microsoft YaHei'",
			"fontSize": 14.67,
			"fontStyle": "Normal",
			"fontWeight": 400
		},
		"data": [{
			"name": "整数",
			"icon": "roundRect"
		}],
		"right": 5,
		"top": "center",
		"itemWidth": 14,
		"itemGap": 11.73599853515625
	},
	"series": [{
		"name": "整数",
		"z": 2,
		"type": "bar",
		"data": [{
			"value": 12,
			"itemStyle": {
				"color": "lightgreen",
				"borderColor": "red",
				"borderWidth": 2,
				"borderType": "solid"
			}
		}, {
			"value": 34
		}, {
			"value": 45
		}, {
			"value": 56
		}, {
			"value": 23
		}, {
			"value": 45
		}, {
			"value": 67
		}],
		"label": {
			"show": false
		},
		"itemStyle": {
			"color": "lightblue",
			"opacity": 1,
			"borderColor": "blue",
			"borderWidth": 1,
			"borderType": "solid"
		},
		"barGap": 0,
		"barCategoryGap": "30%"
	}],
	"xAxis": {
		"show": true,
		"type": "value",
		"axisLine": {
			"show": true,
			"lineStyle": {
				"color": "#000000",
				"width": 1,
				"type": "solid"
			}
		},
		"axisTick": {
			"show": true,
			"inside": false,
			"length": 7,
			"lineStyle": {
				"color": "#000000",
				"width": 1
			}
		},
		"axisLabel": {
			"show": true,
			"rotate": 0,
			"textStyle": {
				"color": "#000000",
				"fontFamily": "'Microsoft YaHei'",
				"fontSize": 14.67,
				"fontStyle": "Normal",
				"fontWeight": 400
			}
		},
		"splitLine": {
			"show": true,
			"lineStyle": {
				"color": "#868686",
				"width": 0.5,
				"type": "solid"
			}
		},
		"max": 80,
		"min": 0,
		"splitNumber": 8,
		"boundaryGap": true
	},
	"yAxis": {
		"show": true,
		"type": "category",
		"axisLine": {
			"show": true,
			"lineStyle": {
				"color": "#000000",
				"width": 1,
				"type": "solid"
			}
		},
		"axisTick": {
			"show": true,
			"inside": false,
			"length": 7,
			"lineStyle": {
				"color": "#000000",
				"width": 1
			}
		},
		"axisLabel": {
			"show": true,
			"rotate": 0,
			"textStyle": {
				"color": "#000000",
				"fontFamily": "'Microsoft YaHei'",
				"fontSize": 14.67,
				"fontStyle": "Normal",
				"fontWeight": 400
			}
		},
		"splitLine": {
			"show": false
		},
		"data": ["A", "B", "C", "D", "E", "F", "G"]
	},
	"grid": {
		"left": 26.1744,
		"top": 15.335,
		"right": 68.34,
		"bottom": 29.67,
		"backgroundColor": "transparent",
		"borderWidth": 1,
		"borderColor": "transparent",
		"borderType": "solid",
		"show": true
	},
	"color": null
};

### What is expected?
The data point A should has red border

### What is actually happening?
The data point A has blue border

**Comment by plainheart** [comment]
This has been fixed in 5.0.

**Comment by katherinebai** [comment]
> This has been fixed in 5.0.

Could you provide that when will release v5.0? Thank you very much.

**Comment by plainheart** [comment]
5.0-alpha is now available, you can refer to the GitHub release page. And the stable release will be published in the late of September.

**Comment by li-zhixin** [comment]
@plainheart   This is very helpful to me, but charts is a basic library for us, and the release date doesn't allow us to wait until the end of September to change libraries.Can you tell us the commit or source file of this bug fix so that we can make manual changes, thank you very much !

**Comment by plainheart** [comment]
@li-zhixin Of course, I'm sorry for this. It can be fixed easily, just modify [this line of code](https://github.com/apache/incubator-echarts/blob/master/src/chart/bar/BarView.js#L508) as follows.
```js
var stroke = data.getItemVisual(dataIndex, 'borderColor');
```
