### ISSUE TITLE
Cannot get min max value yAxis when trigger event dataZoom

### ISSUE THREAD

**Issue by duloc2708** [apache/incubator-echarts#13111]
Default when i load data
<img width="182" alt="Screen Shot 2020-08-12 at 2 23 32 PM" src="https://user-images.githubusercontent.com/27728232/89987422-4052b500-dca8-11ea-8a2c-086d662588a3.png">

And when i zoom then it value change,   u can see start is 11358 , end is 11368: 
<img width="197" alt="Screen Shot 2020-08-12 at 2 26 06 PM" src="https://user-images.githubusercontent.com/27728232/89987294-01bcfa80-dca8-11ea-92b5-d2f1d014553b.png">

How i get min max value yAxis when trigger event dataZoom? I use  `myChart.getModel().option.yAxis[0]`. but can't found

**Comment by plainheart** [comment]
You can get the scale extent as follows.
```js
myChart.getModel().getComponent('yAxis').axis.scale.getExtent();
```

**Comment by duloc2708** [comment]
> You can get the scale extent as follows.
> 
> ```js
> myChart.getModel().getComponent('yAxis').axis.scale.getExtent();
> ```

Thanks a lot @plainheart
