### ISSUE TITLE
4.8.0下series-line.markPoint.symbolRotate无效果

### ISSUE THREAD

**Issue by fffsnc999** [apache/incubator-echarts#13118]
### Version
4.8.0

### Steps to reproduce
4.7.0版本可以使用，更换成4.8.0后无效果。

### What is expected?
None.

### What is actually happening?
None.

---
希望尽快修复，在线定制使用的也是4.8.0。

**Comment by plainheart** [comment]
4.9.0 应该已经解决这个问题，可先下载使用 [4.9.0-rc.1](https://github.com/apache/incubator-echarts/releases/tag/4.9.0-rc.1)
