### ISSUE TITLE
How add background Image for label of markLine

### ISSUE THREAD

**Issue by duloc2708** [apache/incubator-echarts#13116]
Current I handled label of markLine as here:

```
{
            symbol: "none",
            lineStyle:{
              opacity:0.5,
              color: {
                type: 'linear',
                colorStops: [{
                    offset: 0, color: 'white'
                }]
            }},
            yAxis: lastRecord[0],
            label:{
              color:'black',
              fontSize:17,
              backgroundColor:'white',
              formatter:function(obj){
                return Helper._formatMoney(obj.data.yAxis)
              }
            }
}
```

<img width="159" alt="Screen Shot 2020-08-13 at 11 05 27 AM" src="https://user-images.githubusercontent.com/27728232/90093495-ef999580-dd55-11ea-8935-cbb3d401de00.png">

How add background Image for the label ? this is an example from other chart libraries.

<img width="200" alt="Screen Shot 2020-08-13 at 11 08 50 AM" src="https://user-images.githubusercontent.com/27728232/90093499-f1635900-dd55-11ea-9692-8ec20c4b6917.png">

**Comment by plainheart** [comment]
You could configure like [`series.label.backgroundColor`](https://echarts.apache.org/en/option.html#series-line.label.backgroundColor).
Although `markerLine.label.backgroundColor` is missing in the documentation, it still works.

**Comment by duloc2708** [comment]
Thanks, it worked
