### ISSUE TITLE
series.data  有0的数据时showTip不显示

### ISSUE THREAD

**Issue by luoye111** [apache/incubator-echarts#13132]
### Version
4.5.0

### Steps to reproduce
` echart.dispatchAction({
            type: 'showTip',
            seriesIndex: 0,
            dataIndex: index,
        });`

### What is expected?
 echart.dispatchAction({
            type: 'showTip',
            seriesIndex: 0,
            dataIndex: index,
        });  数据为不为0都显示

### What is actually happening?
为0 调用不显示

**Comment by luoye111** [comment]
抱歉 ，经排查，是设置grid 影响了，

**Comment by woowalker** [comment]
@luoye111 嗯哼？ grid 有什么影响？我设置自动轮播 tooltip 的时候，series data 中有数据为 0 的时候，他就是不显示呀？想咨询下怎么解决？

**Comment by luoye111** [comment]
就是设置grid&nbsp; 影响了，就调整了下grid&nbsp; 里面 left&nbsp; 和top 就出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "woowalker"<notifications@github.com&gt;; 
发送时间: 2020年10月30日(星期五) 上午9:08
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "酷我小子"<1219699521@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] series.data  有0的数据时showTip不显示 (#13132)





 
@luoye111 嗯哼？ grid 有什么影响？我设置自动轮播 tooltip 的时候，series data 中有数据为 0 的时候，他就是不显示呀？想咨询下怎么解决？

**Comment by woowalker** [comment]
太诡异了，微调一下确实可以，在我这边，f11 全屏也能显示，调整下窗口宽高也能显示出来

**Comment by HibernatingBear** [comment]
我也碰到了这个问题，的确调整grid就可以了，但是不知道原因
