### ISSUE TITLE
tooltip的触发点能否作用的树节点的文字块上, 而不是只在symbol

### ISSUE THREAD

**Issue by Victoriacsl** [apache/incubator-echarts#13135]
### Version
4.4

### Steps to reproduce
// tooltip的配置
   tooltip: {
        show: true,
        enterable: true,
        confine: true,
        trigger: 'item',
}

### What is expected?
鼠标作用再树节点的文字块上, 显示提示框

### What is actually happening?
鼠标只有作用再树节点的symbol上,才可以 显示提示框

**Comment by Ovilia** [comment]
Similar to #13105 . Please follow that issue.
