### ISSUE TITLE
5.0的Alpha版本地图上的labelLine被地图色块遮挡

### ISSUE THREAD

**Issue by Guanrui1** [apache/incubator-echarts#13130]
### Version
5.0.0-alpha.1

![map.png](https://i.loli.net/2020/08/14/CxcG1oATm4kdvKM.png)

### Steps to reproduce
地图加上labelLine即可

### What is expected?
地图上的labelLine被地图色块不被遮挡

### What is actually happening?
地图上的labelLine被地图色块遮挡

**Comment by susiwen8** [comment]
Problem is labelLline 's `z`

**Comment by pissang** [comment]
It's because in cases like `scatter`, `pie`. We want the labelLine is on bottom of the circle, sectors. But in this case, indeed, it should be on the top. I think we should make it configurable

**Comment by qiaoxiayu** [comment]
> Problem is labelLline 's `z`

issue template cant open
