### ISSUE TITLE
Item missing in scatter chart

### ISSUE THREAD

**Issue by namannehra** [apache/incubator-echarts#13146]
### Version
4.8.0

### Reproduction link
[https://jsfiddle.net/f0ampunx/](https://jsfiddle.net/f0ampunx/)

### Steps to reproduce
Look at the chart. 2 items should be rendering. 1 red and 1 blue. Red item is not rendering.

### What is expected?
2 items render. 1 red and 1 blue.

### What is actually happening?
Red item is not rendering.

---
Removing `type: 'log'` fixes the issue. Removing `max: 'dataMax'` also fixes the issue.

**Comment by namannehra** [comment]
https://jsfiddle.net/dcugq34e/
This also doesn't render properly and is fixed by removing `"type": "log"`

**Comment by susiwen8** [comment]
Fix in 5.0, please try it

**Comment by namannehra** [comment]
Not working with 5.0.0-alpha.2

https://jsfiddle.net/tno245vd/7/
https://jsfiddle.net/cLvx6p19/3/

**Comment by susiwen8** [comment]
```js


 // 基于准备好的dom，初始化echarts实例


 // 基于准备好的dom，初始化echarts实例
 var myChart = echarts.init(document.getElementById('main'));

 var option = {
     xAxis: {
         type: 'time',
         min: 1588270000000,
         max: 1588300000000,
     },
     yAxis: {
         type: 'log',
         logBase: 2,
         min: 'dataMin',
         max: 'dataMax',
     },
     series: [
         {
             type: 'scatter',
             name: 'Error',
             itemStyle: {
                 color: 'red',
             },
             data: [
                 [1588286609000, 55.939322435],
             ],
         },
         {
             type: 'scatter',
             name: 'Throughput',
             itemStyle: {
                 color: 'blue',
             },
             data: [
                 [1588286609000, 54],
             ],
         },
     ],
 };
 
 myChart.setOption(option);
 
         // 使用刚指定的配置项和数据显示图表。
       //  myChart.setOption(option);
```

I was using this option

**Comment by namannehra** [comment]
Ok. I'll open another issue the other example
