### ISSUE TITLE
Stack in bar chart,  some serie's label will be hidden when each label set into top positon

### ISSUE THREAD

**Issue by jay0815** [apache/incubator-echarts#13148]
### Version
4.8.0

### Reproduction link
[https://jsfiddle.net/ge6937tu/10/](https://jsfiddle.net/ge6937tu/10/)

### Steps to reproduce
Look at the chart. 
first and second items' label should be rendering. 
member A and member B.
But only member C's label dispaly

### What is expected?
label in series all can be display

### What is actually happening?
only last item's label can be display

**Comment by susiwen8** [comment]
Fix in 5.0, right now 5.0 is in alpha, you can try it.
