### ISSUE TITLE
关于折现堆叠图Stacked Line Chart显示问题

### ISSUE THREAD

**Issue by Talonshaw** [apache/incubator-echarts#13152]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-stack](https://echarts.apache.org/examples/zh/editor.html?c=line-stack)

### Steps to reproduce
请观察“搜索引擎”、“直接访问”的数值，数值与Y轴是不对应的。据我观察，只有数值最小的折线是对应的，其他均不对应。

### What is expected?
Y轴坐标应对应

### What is actually happening?
Y轴坐标显示有较大偏差

**Comment by susiwen8** [comment]
@Talonshaw  Did you mean stacked value is not correct????

**Comment by Talonshaw** [comment]
As shown in the figure, the search engine value is 932, but the Y-axis coordinate corresponding to the figure is greater than 1500.

[cid:e556c55e-2f49-4cc3-bce3-9d76535f505d]
________________________________
发件人: susiwen8 <notifications@github.com>
发送时间: 2020年8月19日 1:53
收件人: apache/incubator-echarts <incubator-echarts@noreply.github.com>
抄送: Talon Shaw <talonshaw@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [apache/incubator-echarts] 关于折现堆叠图Stacked Line Chart显示问题 (#13152)


@Talonshaw<https://github.com/Talonshaw> Did you mean stacked value is not correct????

―

**Comment by susiwen8** [comment]
That's not a bug. Please understand the meaning of `stack chart`.

**Comment by Talonshaw** [comment]
> That's not a bug. Please understand the meaning of `stack chart`.

OK, I understand now. Thanks.
