### ISSUE TITLE
Show title only on print

### ISSUE THREAD

**Issue by sgurin** [apache/incubator-echarts#13156]
### Version
4.8.0

### Steps to reproduce
How to show title https://echarts.apache.org/en/option.html#title only on print view throw https://echarts.apache.org/en/api.html#echarts

### What is expected?
Ok

### What is actually happening?
Title is hidden on print version

**Comment by plainheart** [comment]
Maybe you can do it like this

```js
function print() {
    // show the title temporarily
    myChart.setOption({
        title: {
            show: true
        }
    });
    // export to data URL
    var exportImage = myChart.getDataURL();
    // hide the title
    myChart.setOption({
        title: {
            show: false
        }
    });
}
```
