### ISSUE TITLE
How to get children nodes data on click of bottom lables

### ISSUE THREAD

**Issue by aadgithub** [apache/incubator-echarts#13157]
### Version
4.4.2

### Reproduction link
[https://jsfiddle.net/yxtn0gwd/1/](https://jsfiddle.net/yxtn0gwd/1/)

### Steps to reproduce
On tree map at bottom it shows hierarchy of levels.
on click of parent level want all children level nodes data. 
in attached demo 
   click on    Disk Usage => Gold

### What is expected?
in demo  on click of 'Gold' from top left corner in map it gives all children data in click event.

 on click  Disk Usage =>Gold from bottom hierarchy it should give all children data of Gold.

### What is actually happening?
It is not returning children data of Gold in click event.
![Screenshot from 2020-08-20 00-43-41](https://user-images.githubusercontent.com/24888088/90679796-53541f00-e27e-11ea-928d-dc51b3e4d61a.png)

**Comment by plainheart** [comment]
It seems that there is no direct and simple way to get the children nodes of clicked level node in the breadcrumb.
There is a workaround for your reference.

```js
myChart.on('click', function(e) {
    var series = myChart.getModel().getSeriesByName('Disk Usage')[0]; // or use getSeriesByIndex(index)
    var allNodes = [];
    flattenNodes(series.getViewRoot(), allNodes);
    var clickedNode = allNodes.find(function(t) {
        return t.dataIndex === e.nodeData.dataIndex;
    });
    var children = clickedNode.children;
    console.log('clicked', e.nodeData.dataIndex, e.nodeData.name, 'children nodes', children);
})

function flattenNodes(root, nodes) {
    nodes.push(root);
    if (root.children) {
        root.children.forEach(function(c) {
            flattenNodes(c, nodes);
        });
    }
}
```

**Comment by aadgithub** [comment]
Thank you @plainheart 
Working as expected.
