### ISSUE TITLE
Echarts keeps rendering white blanks with large datasets on single canvas mode.

### ISSUE THREAD

**Issue by CarterLi** [apache/incubator-echarts#13164]
### Version
4.8.0

### Reproduction link
[https://github.com/CarterLi/echarts-bug](https://github.com/CarterLi/echarts-bug)

### Steps to reproduce
1. View the rendered page <https://carterli.github.io/echarts-bug/>
1. Move mouse on the chart

### What is expected?
The chart should work as normal, tooltip should be shown

### What is actually happening?
The chart renders white blank

---
Originally found when testing my repo: https://github.com/CarterLi/echarts-with-offscreencanvas

I tested several chart types and found only line chart worked as expected. I have been trying to debug this issue for 2 days and only found the issue happens here:

```js
    _startLoop: function () {
        var self = this;

        this._running = true;

        function step() {
            if (self._running) {

                requestAnimationFrame(step);

                !self._paused && self._update();
            }
        }

        requestAnimationFrame(step);
    },
```

Of course it was not true, so I gave up.

The issue is rather important to our company, please help

**Comment by CarterLi** [comment]
Related issue: https://github.com/apache/incubator-echarts/issues/9232

This issue is the only blocking issue that enabling echarts working in web worker, because in a worker echarts can only be running in single canvas mode.

**Comment by 100pah** [comment]
@CarterLi 
```js
option = {
    // Set this to avoid the issue.
    hoverLayerThreshold: Infinity,
    ...     
};
```

---

And it needs to be fixed that: 
1. Disable the feature of hover layer in when the root dom is canvas
2. Make worker case into the `test/**`.

**Comment by CarterLi** [comment]
It works! Thanks @100pah

**Comment by englianhu** [comment]
> @CarterLi
> 
> ```js
> option = {
>     // Set this to avoid the issue.
>     hoverLayerThreshold: Infinity,
>     ...     
> };
> ```
> 
> And echarts needs to fix that:
> 
> 1. Disable the feature of hover layer in when the root dom is canvas
> 2. Make worker case into the `test/**`.

using `echarts4r` r package on rmarkdown rstudio, how to tune it to display as normal?
