### ISSUE TITLE
saveAsImage 当div高度过低时，导出的图片底部有一条横线

### ISSUE THREAD

**Issue by InfinityMo** [apache/incubator-echarts#13204]
### Version
4.8.0

### Steps to reproduce
saveAsImage 当div高度过低时，导出的图片底部有一条横线

**Comment by quillblue** [comment]
Hi, please be kind to provide reproduceable link via any online editor and necessary screenshot for the community to better understand your issue,

**Comment by InfinityMo** [comment]
![img](https://user-images.githubusercontent.com/68720016/91519402-14306880-e925-11ea-8a26-57a9e48a1e19.png)


<div id="chart" style="width:100%;height:151px"></div>
option = {
        tooltip: {
          show: true
        },
        toolbox: {
          feature: {
            saveAsImage: {
              name: '词云图',
              backgroundColor: '#fff',
              connectedBackgroundColor: '#fff'
            }
          }
        },
        series: [{
          type: 'wordCloud',
          gridSize: 3, // 字体间的间距
          sizeRange: [20,50], // 最小字体和最大字体
          rotationRange: [0,0], // 字体旋转角度的范围
          shape: 'circle', 
          textStyle: {
            normal: '#6E6E6E',
            emphasis:'bold'
          },
          data: [
  {
    name: '多少钱',
    value: 41
  }, {
    name: '价格',
    value: 36
  }, {
    name: '贵',
    value: 29
  }, {
    name: '便宜',
    value: 19
  }, {
    name: '折扣',
    value: 7
  }, {
    name: '赠品',
    value: 7
  }, {
    name: '心痛',
    value: 7
  }, {
    name: '信用卡',
    value: 7
  }, {
    name: '银子',
    value: 6
  }, {
    name: '退税',
    value: 6
  }, {
    name: '太贵',
    value: 4
  }, {
    name: 'RMB',
    value: 4
  }, {
    name: '汇率',
    value: 4
  }, {
    name: '最贵',
    value: 2
  }, {
    name: '没钱',
    value: 2
  }
]
        }]
      }

**Comment by plainheart** [comment]
@InfinityMo 刚试了一下，没有复现，是否漏掉了一些配置？
https://codepen.io/plainheart/pen/Vwabgdd

**Comment by InfinityMo** [comment]
> @InfinityMo 刚试了一下，没有复现，是否漏掉了一些配置？
> https://codepen.io/plainheart/pen/Vwabgdd

抱歉，我后来又查看了下，是因为win10自带的照片查看器出现的横线。抱歉，是我的问题
