### ISSUE TITLE
社区点击问题

### ISSUE THREAD

**Issue by AnAloneJaver** [apache/incubator-echarts#13207]
社区的作品能不能设置为新开窗口，翻页翻好久，找到一个合适的点开备用来着，想接着往下找，还得重新翻页，虽然自己知道浏览器自带有新开窗口，有时候真就管不住我这只手啊。T.T

**Comment by plainheart** [comment]
已有开发者提过相关需求：https://github.com/ecomfe/echarts-gallery-feedback/issues/63
后续有 Gallery 社区相关问题请移步至 [echarts-gallery-feedback](https://github.com/ecomfe/echarts-gallery-feedback/issues) 项目进行报告。
