### ISSUE TITLE
The Baidu map personalization style does not work.

### ISSUE THREAD

**Issue by biubiuKill** [apache/incubator-echarts#13213]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=map-polygon](https://echarts.apache.org/examples/zh/editor.html?c=map-polygon)

### Steps to reproduce
The Baidu map in the example now has the same problem.

### What is expected?
The map background should be blue and so on.

### What is actually happening?
The map is no style.

**Comment by plainheart** [comment]
Thanks for your reporting. This is a bug brought by a typo. You can use the bmap extension of 4.8.0 or modify the variable name `newMapStyle2` in [line 105](https://github.com/apache/incubator-echarts/blob/master/extension-src/bmap/BMapView.js#L105) to `newMapStyle`.
