### ISSUE TITLE
请问echarts以后会不会接入今日头条小程序？

### ISSUE THREAD

**Issue by xiesp123** [apache/incubator-echarts#13220]
### What problem does this feature solve?
在百度智能小程序中，有echarts提供的动态库，可以很好的帮助用户制作图标，但是现在我想在今日头条上做图标，并且想做成和百度智能小程序一样的效果，并没有看到相关的echarts接入头条的小程序信息，然后选用其他的画图插件并不能很好的达成和ehacrts一样的效果，因此希望echarts接入今日头条小程序

### What does the proposed API look like?
我对这个功能的期望希望是引入echarts相关的js后，能够和百度小程序一样来使用画图功能。

**Comment by Ovilia** [comment]
欢迎社区贡献，Apache ECharts (incubating) 官方没有计划支持。
