### ISSUE TITLE
折线图问题，折线图Y周数据，总是无法正常和实际数据匹配。官网实例中也无法匹配

### ISSUE THREAD

**Issue by BingzhangGithub** [apache/incubator-echarts#13229]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-stack](https://echarts.apache.org/examples/zh/editor.html?c=line-stack)

### Steps to reproduce
官网实例

鼠标移入周一数据
y轴最大数据为820
坐标轴展示在1000以上
数据无法匹配

### What is expected?
实际数据等于y轴数据

### What is actually happening?
always

**Comment by plainheart** [comment]
示例使用了 `stack` 开启了堆叠模式[1]，如需实际数据等于y轴数据，可将示例中的 `stack: '总量'` 全部删除。

[1] https://echarts.apache.org/zh/option.html#series-line.stack

**Comment by BingzhangGithub** [comment]
> 示例使用了 `stack` 开启了堆叠模式[1]，如需实际数据等于y轴数据，可将示例中的 `stack: '总量'` 全部删除。
> 
> [1] https://echarts.apache.org/zh/option.html#series-line.stack

感谢，才疏学浅，多谢指教，置空stack类型后恢复
