### ISSUE TITLE
图表中添加emphasis时设置其他项的样式

### ISSUE THREAD

**Issue by victorting** [apache/incubator-echarts#13235]
### What problem does this feature solve?
解决数据项多的时候emphasis不够醒目的问题

### What does the proposed API look like?
{
   legend: {
      emphasis: {  ...   },
      unemphasis: { ... }
   },
   series: [
        {
            ...
            emphasis: {
                ...
            },
            unemphasis: {
               ...
            }
        }
    ]

}

类似于这种效果：
  
![image](https://user-images.githubusercontent.com/14315278/92212166-229df780-eec4-11ea-913c-38eef77eaeeb.png)
![image](https://user-images.githubusercontent.com/14315278/92212181-2893d880-eec4-11ea-9280-47286a1bb325.png)
![image](https://user-images.githubusercontent.com/14315278/92212192-2cbff600-eec4-11ea-8b2d-f175e3c70ac1.png)

**Comment by plainheart** [comment]
示例图当中的高亮选中系列，虚化其他系列的特性在 5.0 版本中提供了，Alpha版本已经发布，可以先行使用下，不过相关文档还没有上线。

**Comment by victorting** [comment]
> 示例图当中的高亮选中系列，虚化其他系列的特性在 5.0 版本中提供了，Alpha版本已经发布，可以先行使用下，不过相关文档还没有上线。

好的，感谢！

**Comment by plainheart** [comment]
5.0 已经发布，可按照文档说明尝试一下。
