### ISSUE TITLE
echarts + bmap百度地图样式修改失效

### ISSUE THREAD

**Issue by sunshinapril** [apache/incubator-echarts#13245]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by sunshinapril** [comment]
将mapStyle改成mapStyleV2，主要原因：百度地图API又偷偷的改了，真是难用

**Comment by plainheart** [comment]
十分抱歉，是因为 4.9.0 的一个 typo 导致此问题，暂时可以先用4.8.0的百度地图扩展，或者按照您的办法手动修改下，下个版本 5.0 会修复。
