### ISSUE TITLE
Tooltip.Formatter return string or DOM Element

### ISSUE THREAD

**Issue by Ghostbird** [apache/incubator-echarts#13250]
### What problem does this feature solve?
I'm using echarts in an Angular application and I imagine the same applies to other frameworks too.
My framework has a built in mechanism to render templates as DOM Elements with lots of extra framework functionality such as live model-binding.

Currently I have to manually craft an HTML string and pass it to echarts for use as a tooltip, and echarts will insert that HTML into the DOM. I would instead like to create the DOM elements myself and pass _that_ to echarts for use in the tooltip. In my opinion the only required functionality is that echarts moves the given DOM elements into it's template root DOM element insertion when it is passed an array of DOM elements.

### What does the proposed API look like?
In TypeScript notation the current Formatter interface is:
```typescript
interface Formatter {
    (
        params: Format | Format[],
        ticket: string,
        callback: (ticket: string, html: string) => void,
    ): string;
}
```
The proposed interface would look like this:
```typescript
interface Formatter {
    (
        params: Format | Format[],
        ticket: string,
        callback: (ticket: string, html: string) => void,
    ): string | any[];
}
```
The caller of the Formatter would check whether the return is a string:

- If so, use the current behaviour
- If not, assume it is an array of DOM Elements and move those elements into the tooltip root element.

It might be desirable to add an OnDestroy callback that can be called to clean up the rendered templates. In that case the API would look like:

```typescript
interface Formatter {
    (
        params: Format | Format[],
        ticket: string,
        callback: (ticket: string, html: string) => void,
    ): string | { domNodes: any[], destroyCallback: () => void }
}
```

**Comment by Ghostbird** [comment]
@plainheart: Can you give any comment on the status of this issue? Is it clear, or do you need more info? Is it being considered, or just a plain bad idea?

**Comment by Ghostbird** [comment]
After looking this over again, I've found that I've not included any change of the `callback` function. I haven't used it, so I'm not sure about it's usage. but I can imagine that it would be desirable that `callback`'s second argument is of the same type as the return type of the `Formatter`

**Comment by plainheart** [comment]
Hi @Ghostbird, sorry for my late response.
Thank you for so detailed description.
I think this is a great idea and it's possible to add this helpful feature. I've added this to the [TBD](https://github.com/apache/incubator-echarts/milestone/13) milestone.

@pissang What do you think of it? It may be very helpful for using live model-binding, such as Vue and Angular.

**Comment by Ghostbird** [comment]
I've proposed an implementation that works for me.

**Comment by Ghostbird** [comment]
Functionality can be found in `echarts 5.0.0-beta.2`
