### ISSUE TITLE
feat: Decals support

### ISSUE THREAD

**Issue by Ovilia** [apache/incubator-echarts#13263]
## Background

Decals in charts can be served as an extra hint for data along with colors, and it can help with [accessibility](https://www.highcharts.com/demo/accessible-pie) and better artistic expression.

In ECharts 5.0, we are going to support decals.

> We borrowed the concept of *[decal](https://en.wikipedia.org/wiki/Decal)* from computer graphics to avoid confusing with *[pattern](https://echarts.apache.org/examples/en/editor.html?c=pie-pattern)*, which ECharts already used. The difference between a decal and a pattern in ECharts is that, a decal is a parametric configuration that generates repeating images while a pattern takes an image to repeat.

## Proposed APIs

```js
option = {
    decal: [decalA, decalB], // A list of decals which would be adopted sequentially and circularly from this list. Similar to https://echarts.apache.org/option.html#color
    series: [{
        itemStyle: {
            decal: decalC,     // Decal for the series
        },
        data: [{
            itemStyle: { decal: decalD }      // Decal for one data item
        }]
    }]
};
```

(This list may not be the final one. It may be adjusted when implementing.)

```js
interface DecalObject {
    // 'image', 'triangle', 'diamond', 'pin', 'arrow', 'line', 'rect', 'roundRect', 'square', 'circle'
    symbol?: string

    // size relative to the dash bounding box; valued from 0 to 1
    symbolSize?: number
    // keep the aspect ratio and use the smaller one of width and height as bounding box size
    symbolKeepAspect?: boolean

    // foreground color of the pattern
    color?: string
    // background color of the pattern; default value is 'none' (same as 'transparent') so that the underlying series color is displayed
    backgroundColor?: string

    // dash-gap pattern on x
    dashArrayX?: DecalDashArrayX
    // dash-gap pattern on y
    dashArrayY?: DecalDashArrayY

    // in radians; valued from -Math.PI to Math.PI
    rotation?: number,

    // boundary of largest tile width
    maxTileWidth?: number,
    // boundary of largest tile height
    maxTileHeight?: number
};
```

`dashArrayX` and `dataArrayY` are inspired from [SVG stroke-dasharray](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray), which either be a number (for the same dash and gap) or an array of numbers (for the dash-gap pattern) or an array of a number array (for the dash-gap decal of each line). This will be better explained in the doc later.

Decals can be expressed with parameters so that they are more understandable and changeable than SVG path, although you can still use SVG path if you wish. And we may even have an opportunity to use the document preview tool to generate the decal.

## ARIA

If `aria.decal.show` is set to be true, a default list of decals will be used.

![image](https://user-images.githubusercontent.com/779050/96989474-4c84a980-1558-11eb-93f1-c4e7d73cefae.png)

**Comment by woliwa1** [comment]
May I ask, when will version 5.0 be released

**Comment by pissang** [comment]
@woliwa1 Next month if everything goes well

**Comment by woliwa1** [comment]
Really looking forward to

**Comment by Komal-Patil1996** [comment]
I am trying to use decal pattern for markarea in Line chart. But Somehow it doesn't work. So decal pattern does not work for markarea??

**Comment by thebrownfox** [comment]
> I am trying to use decal pattern for markarea in Line chart. But Somehow it doesn't work. So decal pattern does not work for markarea??

I guess it doesn't. I've been trying for a few hours now. Even LLMs are confused by this.
