### ISSUE TITLE
散点图,气泡图以及面积图中渐变色失效.(官网的例子也是)

### ISSUE THREAD

**Issue by mgsod** [apache/incubator-echarts#13266]
### Version
4.7.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=scatter-logarithmic-regression](https://echarts.apache.org/examples/zh/editor.html?c=scatter-logarithmic-regression)

### Steps to reproduce
项目中用npm安装的包.package.json设置为"ecahrts:^4.70."
之前都是正确的,今天另一台机子上发现散点图/气泡图中的渐变失效.点变成了黑色(图例部分正确显示).
随即将option贴到官网示例中,发现demo中的例子也是不正确的.如下图
![local.png](https://i.loli.net/2020/09/11/413Zz6r72YJFIQo.png)

![scatter.png](https://i.loli.net/2020/09/11/dQWsePUtuI6XNmZ.png)

### What is expected?
正确显示

### What is actually happening?
无法显示渐变

**Comment by plainheart** [comment]
我使用你提供的官网例子，没能复现，是否是其他地方导致的错误？

![image](https://user-images.githubusercontent.com/26999792/92876617-ea0a9a80-f43c-11ea-9f1c-b0306453ede9.png)

**Comment by plainheart** [comment]
与 #13323 应该是一类问题。
