### ISSUE TITLE
xAxis type为'time'时，minInterval无效

### ISSUE THREAD

**Issue by agnij** [apache/incubator-echarts#13288]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xgnZ49t0KQ&v=2](https://gallery.echartsjs.com/editor.html?c=xgnZ49t0KQ&v=2)

### Steps to reproduce
* xAxis type设置为time
* 设置minInterval无用，但maxInterval和interval有用

### What is expected?
横坐标显示不重复我设置最小间隔为3个月，不采取interval设置死的原因是，有些情况区间跨度大，横坐标的lable会重叠，不想使用datazoom，想通过echarts自动分割区间

### What is actually happening?
实际无用 设置无效

**Comment by 100pah** [comment]
是否可以设置：
```js
xAxis: {
}
```

**Comment by agnij** [comment]
> > 横坐标显示不重
> 
> 是否可以设置：
> 
> ```js
> xAxis：{
> 
>     axisLabel：{ 
>             showMinLabel：false ，
>             showMaxLabel：false ，
>             ...
>     } 
> }
> ```
> 
> 来解决问题？

![image](https://user-images.githubusercontent.com/31338195/94090110-60e56180-fe47-11ea-9d72-5bbdfdd7b373.png)
没有作用

**Comment by supermaverickws** [comment]
我也遇到。现在也没用

**Comment by supermaverickws** [comment]
@agnij 你有解决方法？

**Comment by supermaverickws** [comment]
发现 最小 间隔 3个小时才生效
 minInterval: 3600 * 3 * 1000,
