### ISSUE TITLE
Update echarts on cdnjs.com

### ISSUE THREAD

**Issue by piotrzarzycki21** [apache/incubator-echarts#13290]
### Version
4.9.0

### Steps to reproduce
Echarts is not updated to the latest released version on cdnjs.com. In order to check go to https://cdnjs.com/libraries/echarts/4.8.0 and open drop down list "Version"

### What is expected?
Expected is to have update to latest official release 4.9.0

### What is actually happening?
Currently we can see version 4.9.0-rc.1

**Comment by piotrzarzycki21** [comment]
Any update on this ? We would like to use newest version of Echarts, but now it's impossible trough cdnjs, unless there is different place where framework is updated.

**Comment by plainheart** [comment]
@piotrzarzycki21 Sorry for the late reply. I've opened an issue (see cdnjs/packages#442) to request an update of 4.9.0 several days ago, a member said that both 4.9.0 and 4.9.0-rc.1 are from the same commit in git, so they picked up the initial 4.9.0-rc.1 version. That is, you can use the version of 4.9.0-rc.1 in cdnjs, which is the same as 4.9.0.

**Comment by plainheart** [comment]
BTW, echarts 4.9.0 is available on https://www.jsdelivr.com/package/npm/echarts?path=dist

**Comment by piotrzarzycki21** [comment]
@plainheart Thanks! I will use jsdelivr link to update ECharst in our app and get back to you if that's resolve our issue. :)

**Comment by piotrzarzycki21** [comment]
Provided link works for us. Thanks - you can close this issue.
