### ISSUE TITLE
Can change an option value in a dynamic parallel coordinate plot after rendering for the first time, but not for the next time

### ISSUE THREAD

**Issue by chudur-budur** [apache/incubator-echarts#13302]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/ramgorur/zswuac4b/latest](https://jsfiddle.net/ramgorur/zswuac4b/latest)

### Steps to reproduce
Just follow the [`JSFiddle` link](https://jsfiddle.net/ramgorur/zswuac4b/latest) and run the code. No setup required.

### What is expected?
Once an `option` for a dynamic parallel coordinate plot is set and the plot is rendered, I should be able to change option parameters and the changes should be reflected on the plot on the fly.

### What is actually happening?
I'm trying to make a dynamic parallel coordinate plot, where a user should be able to choose if the lines will be straight or `smooth`. In my case, I have a plot and a toggle button. 

<img src="https://i.postimg.cc/d3VpHYpJ/Screen-Shot-2020-09-17-at-7-03-46-AM.png" width="400px"/>

The idea is every time when a user clicks the button, the lines of the parallel plot should become smooth from straight, and it should toggle every time when a user clicks it.

<img src="https://i.postimg.cc/d3NXgfcr/Screen-Shot-2020-09-17-at-7-04-03-AM.png" width="400px"/>

The problem is the option values changes only for the first time only, but not on the next click. What I mean, if I make it smooth from straight, next click doesn't turn it back to straight from smooth (or vice-versa). The change in the `option` is done this way:

```javascirpt
function toggleSmooth(){
  console.log("Toggling smooth");
  // get the current option
  option = myChart.getOption();
  console.log("Previous myChart.option.series[0].smooth = " + option.series[0].smooth);

  // change and set it
  option.series[0].smooth = !option.series[0].smooth;
  myChart.setOption(option);
  
  // check it again
  option = myChart.getOption();
  console.log("Current myChart.option.series[0].smooth = " + option.series[0].smooth);
}
```

On the `console.log`, I'm seeing the value `option.series[0].smooth` is changing but the change is not being reflected on the plot.

---
Not sure if it's a bug or I'm not doing it in a correct way.

**Comment by 100pah** [comment]
It seems to be a bug.
Before it fixed, perhaps we can only work around with `chart.setOption(option, { notMerge: true })`.

**Comment by chudur-budur** [comment]
> It seems to be a bug.
> Before it fixed, perhaps we can only work around with `chart.setOption(option, { notMerge: true })`.

Thanks for the follow-up. But still no luck. Appreciate your help.
