### ISSUE TITLE
areaStyle区域填充无法使用渐变色

### ISSUE THREAD

**Issue by xss751309229** [apache/incubator-echarts#13323]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=area-simple](https://echarts.apache.org/examples/zh/editor.html?c=area-simple)

### Steps to reproduce
```js
var base =  new Date(1968, 9, 3);
var oneDay = 24 * 3600 * 1000;
var date = [];

var data = [Math.random() * 300];

for (var i = 1; i < 20000; i++) {
    var now = new Date(base += oneDay);
    date.push([now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'));
    data.push(Math.round((Math.random() - 0.5) * 20 + data[i - 1]));
}

option = {
    tooltip: {
        trigger: 'axis',
        position: function (pt) {
            return [pt[0], '10%'];
        }
    },
    title: {
        left: 'center',
        text: '大数据量面积图',
    },
    toolbox: {
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: date
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%']
    },
    dataZoom: [{
        type: 'inside',
        start: 0,
        end: 10
    }, {
        start: 0,
        end: 10,
        handleIcon: 'M10.7,11.9v-1.3H9.3v1.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4v1.3h1.3v-1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
        handleSize: '80%',
        handleStyle: {
            color: '#fff',
            shadowBlur: 3,
            shadowColor: 'rgba(0, 0, 0, 0.6)',
            shadowOffsetX: 2,
            shadowOffsetY: 2
        }
    }],
    series: [
        {
            name: '模拟数据',
            type: 'line',
            smooth: true,
            symbol: 'none',
            sampling: 'average',
            itemStyle: {
                color: 'rgb(255, 70, 131)'
            },
            areaStyle: {
                color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                    offset: 0,
                    color: 'rgb(255, 158, 68)'
                }, {
                    offset: 1,
                    color: 'rgb(255, 70, 131)'
                }])
            },
            data: data
        }
    ]
};
```

### What is expected?
区域填充渐变色

### What is actually happening?
区域未填充渐变色

---
实例中就有这个问题，只能填充纯色，如果设置渐变色后，就不显示填充颜色。

**Comment by plainheart** [comment]
根据提供的例子没能复现问题，你在使用的是什么浏览器？

![image](https://user-images.githubusercontent.com/26999792/93841094-1b009000-fcc5-11ea-9fe5-df12f67f3c1d.png)

**Comment by xss751309229** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 中午11:18
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"薛松松"<751309229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] areaStyle区域填充无法使用渐变色 (#13323)





 
根据提供的例子没能复现问题，你在使用的是什么浏览器？

**Comment by xss751309229** [comment]
我记着以前在谷歌浏览器上是没问题的，不知道是不是因为谷歌浏览器版本升级导致不兼容了嘛？
我在360浏览器上看了看没问题。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 中午11:18
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"薛松松"<751309229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] areaStyle区域填充无法使用渐变色 (#13323)





 
根据提供的例子没能复现问题，你在使用的是什么浏览器？

**Comment by plainheart** [comment]
我使用最新版本的谷歌浏览器(85.0.4183.121)也未复现。

**Comment by czzonet** [comment]
文档里面现在用对象格式[Documentation - Apache ECharts(incubating)](https://echarts.apache.org/zh/option.html#series-line.areaStyle.color)

```js
color: {
    type: 'linear',
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [{
        offset: 0, color: 'red' // 0% 处的颜色
    }, {
        offset: 1, color: 'blue' // 100% 处的颜色
    }],
    global: false // 缺省为 false
}
```

**Comment by xss751309229** [comment]
好吧，那可能是我浏览器的问题把





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 下午2:33
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"薛松松"<751309229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] areaStyle区域填充无法使用渐变色 (#13323)





 
我使用最新版本的谷歌浏览器(85.0.4183.121)也未复现。

**Comment by plainheart** [comment]
@xss751309229 在Windows 7 系统的谷歌浏览器上复现了。似乎是浏览器自身原因，可以看看Chrome后续版本是否会修复这个问题。

临时发现禁用加速之后可以正常显示。
> 1、浏览器地址栏输入：chrome://flags/#disable-accelerated-2d-canvas
> 2、选择“Disabled”
> 3、重启浏览器。

**Comment by xss751309229** [comment]
嗯嗯，我的就是 Windows 7 系统
好的谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 下午4:07
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"薛松松"<751309229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] areaStyle区域填充无法使用渐变色 (#13323)





 
@xss751309229 在Windows 7 系统的谷歌浏览器上复现了。似乎是浏览器自身原因，可以看看Chrome后续版本是否会修复这个问题。
 
临时发现禁用加速之后可以正常显示。
  
1、浏览器地址栏输入：chrome://flags/#disable-accelerated-2d-canvas
 2、选择“Disabled”
 3、重启浏览器。

**Comment by plainheart** [comment]
新版 Chrome 似乎不存在这个问题了，可以升级验证下。

**Comment by xss751309229** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 中午12:53
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"薛松松"<751309229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] areaStyle区域填充无法使用渐变色 (#13323)





 
Closed #13323.

**Comment by xss751309229** [comment]
您好，咱们的echart有如图这种Y轴中间中断的配置吗？
&nbsp; &nbsp; &nbsp; &nbsp; 有如图这种问题的解决办法吗？

**Comment by plainheart** [comment]
Y轴中断目前暂不支持，不过已经列到需求列表里了，后续有可能支持。
