### ISSUE TITLE
bmap 无法setMapStyle

### ISSUE THREAD

**Issue by aiyoudiao** [apache/incubator-echarts#13331]
### Version
4.9.0

### Steps to reproduce
1. 在vue中使用echarts的bmap扩展包。
2. 设置bmap的mapStyle属性，添加了styleJson无效。

### What is expected?
可以setMapStyle。

### What is actually happening?
echarts/extension/bmap/BMapView.js文件代码有问题。
代码位置在120行
```js
if (!isEmptyObject(newMapStyle2)) {
```
这段代码中newMapStyle2应该改成newMapStyle

---
我弄了好久，看了半天官网，各种测试都无效。看了源码之后，发现居然是一个变量错误的问题噢。尴尬。

**Comment by aiyoudiao** [comment]
`<template>
  <div class="bmap">
    <vue-echarts :options="options"></vue-echarts>
  </div>
</template>

<script>
import 'echarts/extension/bmap/bmap'

export default {
  data () {
    return {
      options: {}
    }
  },
  mounted () {
    this.options = {
      bmap: {
        key: 'G1LFyjrNGIkns5OfpZnrCGAKxpycPLwb',
        center: [104.114129, 37.550339], /* 中心点 */
        zoom: 5, /* 缩放比例，焦距 */
        roam: false, /* 是否允许缩放 */
        mapStyle: {
          // styleId: 'ae2291f853c26c030656ffe33e6fbc4d',
          styleJson: [{
            featureType: 'water',
            elementType: 'all',
            stylers: {
              color: '#044161'
            }
          }, {
            featureType: 'land',
            elementType: 'all',
            stylers: {
              color: '#091934'
            }
          }, {
            featureType: 'boundary',
            elementType: 'geometry',
            stylers: {
              color: '#064f85'
            }
          }, {
            featureType: 'railway',
            elementType: 'all',
            stylers: {
              visibility: 'off'
            }
          }, {
            featureType: 'highway',
            elementType: 'geometry',
            stylers: {
              color: '#004981'
            }
          }, {
            featureType: 'highway',
            elementType: 'geometry.fill',
            stylers: {
              color: '#005b96',
              lightness: 1
            }
          }, {
            featureType: 'highway',
            elementType: 'labels',
            stylers: {
              visibility: 'on'
            }
          }, {
            featureType: 'arterial',
            elementType: 'geometry',
            stylers: {
              color: '#004981',
              lightness: -39
            }
          }, {
            featureType: 'arterial',
            elementType: 'geometry.fill',
            stylers: {
              color: '#00508b'
            }
          }, {
            featureType: 'poi',
            elementType: 'all',
            stylers: {
              visibility: 'off'
            }
          }, {
            featureType: 'green',
            elementType: 'all',
            stylers: {
              color: '#056197',
              visibility: 'off'
            }
          }, {
            featureType: 'subway',
            elementType: 'all',
            stylers: {
              visibility: 'off'
            }
          }, {
            featureType: 'manmade',
            elementType: 'all',
            stylers: {
              visibility: 'off'
            }
          }, {
            featureType: 'local',
            elementType: 'all',
            stylers: {
              visibility: 'off'
            }
          }, {
            featureType: 'arterial',
            elementType: 'labels',
            stylers: {
              visibility: 'off'
            }
          }, {
            featureType: 'boundary',
            elementType: 'geometry.fill',
            stylers: {
              color: '#029fd4'
            }
          }, {
            featureType: 'building',
            elementType: 'all',
            stylers: {
              color: '#1a5787'
            }
          }, {
            featureType: 'label',
            elementType: 'all',
            stylers: {
              visibility: 'off'
            }
          }, {
            featureType: 'poi',
            elementType: 'labels.text.fill',
            stylers: {
              color: '#ffffff'
            }
          }, {
            featureType: 'poi',
            elementType: 'labels.text.stroke',
            stylers: {
              color: '#1e1c1c'
            }
          }, {
            featureType: 'administrative',
            elementType: 'labels',
            stylers: {
              visibility: 'on'
            }
          }, {
            featureType: 'road',
            elementType: 'labels',
            stylers: {
              visibility: 'off'
            }
          }]

        }
      }

    }
  }
}
</script>

<style lang="scss" scoped>
.bmap {
  height: 100%;
  width: 100%;
}
</style>
`

**Comment by aiyoudiao** [comment]
```vue
```

**Comment by plainheart** [comment]
抱歉，给您带来不便了。该问题已经发现并且被修复，会在接下来的 5.0 版本中修复。可先使用 4.8.0 的 bmap 扩展库，或者手动修改源码。
