### ISSUE TITLE
Typed array as series data

### ISSUE THREAD

**Issue by lukasberbuer** [apache/incubator-echarts#13335]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/cwp4o571/](https://jsfiddle.net/cwp4o571/)

### Steps to reproduce
Comment out line 21 in the code example to see the issue.
It seems like there is a bug with typed arrays as series data in combination with categorical xAxis data.

### What is expected?
Same output as with arrays

### What is actually happening?
Axes ranges are ok but the line plot is messed up (I don't see any logic)

---
Workaround: `Array.from(yTypedArray)`, if the input is a typed array. But this will lead to memory overhead, especially for large plots.

**Comment by pissang** [comment]
Hi @lukasberbuer . We treat TypedArray as a special multidimensional data storage to speed up the data process.

Here is the right way to use TypedArray. https://jsfiddle.net/aqjxko1e/

Or you can still use the normal array

**Comment by lukasberbuer** [comment]
Hi @pissang. Thank you for that clarification.

Is there any possibility to use typed arrays just as the y-axis values without transforming it into the interleaved format first?
The datasets are quite huge and I would like to save some memory.

**Comment by pissang** [comment]
@lukasberbuer Sorry but it's not in the plan.

I've tested a dataset with millions of data. The memory is not a big issue since 5.0

**Comment by lukasberbuer** [comment]
@pissang: Thank you. I'll try version 5.0
