### ISSUE TITLE
柱状图当x轴为时间轴时出现问题

### ISSUE THREAD

**Issue by jiazhuangzhexiaozhang** [apache/incubator-echarts#13359]
let start=+new Date("2020-09-18 00:00:00");
let end=+new Date("2020-09-18 23:59:00");
let dur=(end-start)/72;
let  sereis=[];
for(let i=0;i<4;i++){
    let data=[];
    for(let j=0;j<72;j++){
        data[j]=[start+j*dur+dur,j+i]
    }
    sereis.push({
        name:i,
        type:"bar",
        stack:"aaa",
        data
    })
}
console.log(sereis)
option = {
    
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type: 'time',
        min:start,
        max:end,
        interval:(end-start)/11
    },
    yAxis:{
        type:"value"
    },
    series:sereis
};

**Comment by cuijiudai** [comment]
@shiyabin 解决了吗？
