### ISSUE TITLE
Echarts能否实现subtext显示<sub>下标？

### ISSUE THREAD

**Issue by nwb5233** [apache/incubator-echarts#13363]
### What problem does this feature solve?
可以解决显示气体、离子、平方等，如CO2，我想显示CO<sub>2</sub>
注：tooltip可以显示，其他都无法显示

### What does the proposed API look like?
无

**Comment by plainheart** [comment]
目前不能，不过可以直接输入符号：₂

Subscript     ₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉ 
Superscript  ⁰ ¹ ² ³ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹

**Comment by nwb5233** [comment]
好的，谢谢，那我关闭了

**Comment by susiwen8** [comment]
Actually, you can use `unicode` or `<sup>``<sub>`
<img width="1286" alt="d96432da8f61c347af80ebc05" src="https://user-images.githubusercontent.com/20318608/94516471-76e48f00-0258-11eb-9703-d52250c0db2a.png">
Here is an example written by @pissang
