### ISSUE TITLE
Labels behind nodes for graph charts

### ISSUE THREAD

**Issue by telco2011** [apache/incubator-echarts#13392]
### Version
4.2.1

### Steps to reproduce
I attach a options.js file with the options to reproduce the issue inside a graph chart like https://echarts.apache.org/examples/en/editor.html?c=graph-simple

### What is expected?
The labels should show above the nodes.

### What is actually happening?
The labels are shown under the nodes

---
To see this behaviour, it is needed to do zoom into the graph.

[options.js.txt](https://github.com/apache/incubator-echarts/files/5332776/options.js.txt)

**Comment by plainheart** [comment]
Hi, the version 5.0 has fixed it, you could have a try.

![image](https://user-images.githubusercontent.com/26999792/95208420-a62c6a80-081b-11eb-9543-4cd8b839b53f.png)

**Comment by telco2011** [comment]
Hi, @plainheart 

I'm seeing that the last echarts version is 4.9.0 and v5 still in alpha version. I'm using echarts in a production application and I'd prefer to use a stable version. Do you know when the v5 will be released?

Meanwhile, is there an option to fix the problem in the current stable version?

Thanks

**Comment by plainheart** [comment]
> Do you know when the v5 will be released?

The 5.0.0 stable version should be released this month as planned.

> Meanwhile, is there an option to fix the problem in the current stable version?

I'm afraid no.

Thanks.

**Comment by telco2011** [comment]
So, I'll wait for the v5 release to check the problem.

Thanks @plainheart.
