### ISSUE TITLE
Why doesn't eCharts fill the available space?

### ISSUE THREAD

**Issue by Bilge** [apache/incubator-echarts#13395]
### Version
4.9.0

### Reproduction link
[https://codepen.io/bilge-the-encoder/pen/wvWvgdN](https://codepen.io/bilge-the-encoder/pen/wvWvgdN)

### Steps to reproduce
See [link](https://codepen.io/bilge-the-encoder/pen/wvWvgdN).

### What is expected?
Chart should extend to the full size of the DOM element.

### What is actually happening?
Chart leaves a large margin around the chart within the available bounds of the DOM element.

**Comment by smeinecke** [comment]
The problem still persists. Is there any fix to disable margin/padding for line charts?

**Comment by smeinecke** [comment]
After 4 hours of search, just found the solutions. You have to change the settings (top, bottom, left, right) for the "grid" component to change the padding/spacing - see https://echarts.apache.org/en/option.html#grid

**Comment by laurmurclar** [comment]
This is still an issue as far as I can see @Bilge - there doesn't seem to be a particularly nice way to do this. For example, if you have a simple line graph with labelled axis (x,y), setting the grid positions to 0 will mean the axis labels are cut off.

**Comment by laurmurclar** [comment]
Tthe `containLabel: true` option mostly solves the problem but you can see that the y-axis label gets cut off here:
![CleanShot 2024-01-22 at 13 58 57](https://github.com/apache/echarts/assets/9434500/bfe9180a-0400-439a-8104-24ca2378dd44)

https://codepen.io/laurmurclar/pen/JjzJqJy

**Comment by Bilge** [comment]
> After 4 hours of search, just found the solutions. You have to change the settings (top, bottom, left, right) for the "grid" component to change the padding/spacing - see https://echarts.apache.org/en/option.html#grid

☝🏻 Stop pinging me.
