### ISSUE TITLE
关于magicType切换图表类型的bug

### ISSUE THREAD

**Issue by 1234scarecrow** [apache/incubator-echarts#13400]
### Version
5.0.0-alpha.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-simple](https://echarts.apache.org/examples/zh/editor.html?c=line-simple)

### Steps to reproduce
1. 在官方实例中，配置toolbox.feature. magicType中的type为['line', 'bar']
2. 点击运行后点击图表右上角的折线图图标，Mon项会从左边原点靠右一点的位置移动到原点位置，Sun项同理移动到x轴最右，其余项自适应扩散一点
3. 切换柱状图与折线图时也可以看到x轴坐标移动

### What is expected?
切换图表类型时x轴坐标不移动

### What is actually happening?
切换图表类型时，x轴左边会发生移动

**Comment by plainheart** [comment]
目前通过 `toolbox` 切换到 `bar` 时会默认将 `boundaryGap` 设置为 `true`，`line` 则为 `false`，所以切换时会看到 x 轴坐标移动。
不过不太清楚这么做的具体原因。
相关代码逻辑：https://github.com/apache/incubator-echarts/blob/next/src/component/toolbox/feature/MagicType.ts#L116-L132

**Comment by 1234scarecrow** [comment]
哦哦知道了，折线图和柱状图似乎是类目轴和非类目轴，所以他们的展现方式不一样
