### ISSUE TITLE
[5.0] The state of `toolbox` will be changed to `normal` after the series leaves emphasis.

### ISSUE THREAD

**Issue by plainheart** [apache/incubator-echarts#13417]
### Version
The current next branch

### Steps to reproduce
Any cases with `toolbox`.
For example, `test/toolbox-stack-custom.html`

### What is actually happening?
The state of the `toolbox` component was changed to `normal`.

![unexpected](https://user-images.githubusercontent.com/26999792/95652088-3ff85e00-0b21-11eb-898e-d5c95317f8b7.gif)

### What is expected?
The emphasis state of the `toolbox` component should be kept.

![expected](https://user-images.githubusercontent.com/26999792/95652087-3bcc4080-0b21-11eb-92d8-adcfb14e4583.gif)

### Others

I looked around and found it might be caused by the following code.
https://github.com/apache/incubator-echarts/blob/next/src/util/states.ts#L367-L378

According to the PR #12925, I think the `blur` state is supported in all series. But is it also supported in all components?
If not, perhaps we should only traverse the series and exclude the components like `toolbox`, `axis` etc..

**Proposed changes**
```js

// Before
// model.eachComponent(function (componentType, componentModel) {
//     const view = componentType === 'series'
//         ? ecIns.getViewOfSeriesModel(componentModel as SeriesModel)
//         : ecIns.getViewOfComponentModel(componentModel);
//     // Leave blur anyway
//     view.group.traverse(function (child) {
//         singleLeaveBlur(child);
//     });
// });

// After
model.eachSeries(function (seriesModel) {
    const view = ecIns.getViewOfSeriesModel(seriesModel);
    // Leave blur anyway
    view.group.traverse(function (child) {
        singleLeaveBlur(child);
    });
});
```

I'm not sure, these are only my simple thoughts.
Thanks.

**Comment by plainheart** [comment]
@pissang I've left some thoughts on this bug. Please help to check and fix it if possible. Thank you!

**Comment by pissang** [comment]
@plainheart Noticed that too.  Some components like `geo` have `blur` and `select` states. So the code is to apply these states if component support. But toolbox is not supposed to be affected. I will look into it and fix it.

**Comment by plainheart** [comment]
It works well now. Thank you for the fix.
