### ISSUE TITLE
官网示例中动态折线图示例失效

### ISSUE THREAD

**Issue by mineralres** [apache/incubator-echarts#13427]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2](https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2)

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2

### What is expected?
期望修复示例

### What is actually happening?
示例链接无效

**Comment by plainheart** [comment]
测试下未能复现，能否提供失效的更多信息？比如是网页打不开还是控制台有任何报错？

![image](https://user-images.githubusercontent.com/26999792/95935725-85a97500-0e06-11eb-8301-b4ef80195c7e.png)

**Comment by mineralres** [comment]
控制台显示应该是cors跨域请求权限问题
Access to XMLHttpRequest at 'https://echarts-www.cdn.bcebos.com/examples/data/dynamic-data2.js?_v_=20200710_1' from origin 'https://echarts.apache.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by plainheart** [comment]
是哪个运营商网络？移动、联通、电信？

**Comment by plainheart** [comment]
可能是CDN的问题，如果始终不行，尝试切换为EN英文版本，用apache的CDN试一下。

**Comment by mineralres** [comment]
电信的网络。
切换为EN版本可以了！
