### ISSUE TITLE
How to Use/ Add different colours to a TREE graph

### ISSUE THREAD

**Issue by manjureddy7** [apache/incubator-echarts#13420]
### Version
4.7.0

### Steps to reproduce
Select any tree Graph, right now we can only add single colour at a time using lineStyle:{color: 'red'} property. How to make this dynamic so that each tree leaf will contain different colours.

### What is expected?
Different Dynamic colors

### What is actually happening?
Single colour

**Comment by manjureddy7** [comment]
How to create dynamic colors for tree graph, right now i can add only single colour.

![image](https://user-images.githubusercontent.com/22653056/95715679-e52d4680-0c87-11eb-9133-d9281c3ef616.png)

**Comment by plainheart** [comment]
Hi, we could specify the `lineStyle` for each item through `dataItem.lineStyle`. But sorry that it's not listed in the documentation.

See this demo on ECharts Gallery https://gallery.echartsjs.com/editor.html?c=xkt1G2flES&v=1

**Comment by plainheart** [comment]
@pissang I think this useful option was probably forgotten. Whether it should be listed on documentation? Is there any other consideration or purpose?

**Comment by pissang** [comment]
@plainheart I think it's just forgotten

**Comment by manjureddy7** [comment]
Super, we just did that, passing lineStyle as part of children data from backend. Thank you so much guys for your time.

**Comment by Abhishekautointel** [comment]
How to chage circle to another icon

**Comment by plainheart** [comment]
@Abhishekautointel You can also set a different `symbol` for each data item.

**Comment by KawtharAlakri** [comment]
I'm trying to set the node color based on specific condition (based on node type which is a property in node), tried to look-up at this but links doesn't work. any idea how to achieve that ? 

> Hi, we could specify the `lineStyle` for each item through `dataItem.lineStyle`. But sorry that it's not listed in the documentation.
> 
> See this demo on ECharts Gallery https://gallery.echartsjs.com/editor.html?c=xkt1G2flES&v=1
> 
> Screenshot

**Comment by Abhishekautointel** [comment]
Go through the below reactjs code you will find the solution and integrate
it into backend json

import ReactECharts from "echarts-for-react"
import OthersSkill from "./OthersSkills"
function BSMsummary() {
//   const [name, setName] = useState("")
  const data = {
    itemStyle:{color:'#228B22', borderColor:'#DC143C'},
    symbol: "roundRect",
    symbolSize:30,
    name: "Front End Web Development",
      children: [
      {
         name:"HTML",
         position: "top",
         symbol: "circle",
         itemStyle:{color:'#228B22', borderColor:'#228B22'},
          lineStyle: {color: '#228B22', opacity:1},
          backgroundColor: '#95cb03',
           children: [
           {
            symbol: "pin",
            name: "WEBSRV1",
            itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
            children: [

              {
                 symbol: "diamond",
                 itemStyle:{color:'#228B22', borderColor:'#228B22'},
                 lineStyle: {color: '#228B22', opacity:1},
                 name: "Service Status" },
              {
                symbol: "diamond",
                itemStyle:{color:'#228B22', borderColor:'#228B22'},
                lineStyle: {color: '#228B22', opacity:1},
                name: "Response Time" }
            ]
          },
          {
            symbol: "pin",
            name: "WEBSRV2",
            itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
            // value: 3322
            children: [
              {
                symbol: "diamond",
                itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
                name: "Service Status"},
              { symbol: "diamond",
              itemStyle:{color:'#228B22', borderColor:'#228B22'},
              lineStyle: {color: '#228B22', opacity:1},
                name: "Response Time" }
            ]
          },
          {
            symbol: "pin",
            name: "WEBSRV3",
            itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
            // value: 3322
            children: [
              {
                symbol: "diamond",
                itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
                name: "Service Status"},
              { symbol: "diamond",
              itemStyle:{color:'#228B22', borderColor:'#228B22'},
              lineStyle: {color: '#228B22', opacity:1},
                name: "Response Time" }
            ]
          }
        ]
    },
      {
        name: "CSS",
        position: "bottom",
        symbol: "circle",
        itemStyle:{color:'#228B22', borderColor:'#228B22'},
        lineStyle: {color: '#228B22', opacity:1},

        children: [
          {
            symbol: "pin",
            itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
            name: "APPSRV1",
            children: [

            { symbol: "diamond",
              itemStyle:{color:'#228B22', borderColor:'#228B22'},
              lineStyle: {color: '#228B22', opacity:1},
              name: "API statics"},

            { symbol: "diamond",
            itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
              name: "API Reachab"}
          ]
          },
          {
            symbol: "pin",
            itemStyle:{color:'#228B22', borderColor:'#228B22'},
            lineStyle: {color: '#228B22', opacity:1},
            name: "APPSRV2",
            children: [
              { symbol: "diamond",
              itemStyle:{color:'#228B22', borderColor:'#228B22'},
              lineStyle: {color: '#228B22', opacity:1},
                name: "API statics"},

              { symbol: "diamond",
              itemStyle:{color:'#228B22', borderColor:'#228B22'},
              lineStyle: {color: '#228B22', opacity:1},
                name: "API Reachab"}
            ]
          }
        ]
      },
      {
          name:"Javascript",
          position: "bottom",
          distance: 10,
          symbol: "circle",
          itemStyle:{color:'#228B22', borderColor:'#DC143C'},
          lineStyle: {color: '#DC143C', opacity:1},
           backgroundColor: '#95cb03',
       },
       {
        name:"Reactjs",
        position: "bottom",
        distance: 10,
        symbol: "circle",
        itemStyle:{color:'#228B22', borderColor:'#DC143C'},
        lineStyle: {color: '#DC143C', opacity:1},
         backgroundColor: '#95cb03',
     }
    ]
  }
  return (
    <div>


      <ReactECharts
          style={{ height: "70vh" }}
                    option = {{
                        tooltip: {
                          trigger: 'item',
                          triggerOn: 'mousemove'
                        },
                        series: [
                          {
                            type: 'tree',
                            data: [data],
                            top: '1%',
                            left: '25%',
                            bottom: '1%',
                            right: '33%',
                            symbolSize: 18,
                            label: {
                              position: 'left',
                              verticalAlign: 'middle',
                              align: 'right',
                              fontSize: 12
                            },
                            leaves: {
                              label: {
                                position: 'right',
                                verticalAlign: 'middle',
                                align: 'left'
                              }
                            },
                            initialTreeDepth:1,
                            emphasis: {
                              focus: 'descendant'
                            },
                            roam:true,
                            expandAndCollapse: true,
                            animationDuration: 550,
                            animationDurationUpdate: 750
                          }
                        ]
                      }}
      />
      {/* <OthersSkill/> */}
</div>
  )
}

export default BSMsummary
