### ISSUE TITLE
label点击问题

### ISSUE THREAD

**Issue by GoldWood2000** [apache/incubator-echarts#13426]
### Version
4.8

### Steps to reproduce
您好，请问label如何设置鼠标单击事件

### What is expected?
label可以设置鼠标单击事件

### What is actually happening?
无法设置label的单击事件

**Comment by susiwen8** [comment]
Duplicate with #10969. But we have schedule this feature in 5.0

**Comment by mansion-sun** [comment]
https://echarts.apache.org/zh/option.html#xAxis.triggerEvent
