### ISSUE TITLE
MarkArea With color container alpha blink

### ISSUE THREAD

**Issue by mam-ijinus** [apache/incubator-echarts#13433]
### Version
4.9.0

### Steps to reproduce
 1. open open https://echarts.apache.org/examples/en/editor.html?c=line-sections
 2. insert "itemStyle: { color: '#5e5e5e5e' }," to line 64
 3. RUN
 4. pass the mouse over the grey mark area

### What is expected?
the color is changing et only one mouse over occur and not mouseout

### What is actually happening?
the color blinking and there is multiple mouseover/mouseout

**Comment by plainheart** [comment]
The hex color with 8-digit notation is not supported yet. You could use `rgba` instead. Use some tools to convert your hex color to rgba color.

**Comment by plainheart** [comment]
Closed by ecomfe/zrender#645.
