### ISSUE TITLE
fontSize中rem/em的设置失效

### ISSUE THREAD

**Issue by paradox010** [apache/incubator-echarts#13446]
### Version
4.9.0

### Steps to reproduce
以前版本我记得是可以的，直接在官网示例中测的时候发现rem/em都会渲染成12px

### What is expected?
5.0.0版本解决了这个问题吗

### What is actually happening?
rem/em渲染失效

**Comment by susiwen8** [comment]
Yes, 5.0 supports `rem` and `em`, you can try it now.

**Comment by luozejian** [comment]
> Yes, 5.0 supports `rem` and `em`, you can try it now.
Will  the 'vw' be supported ?
可以支持vw单位吗

**Comment by susiwen8** [comment]
目前不支持，字体大小是由 zrender 控制，要加也挺好加，可以去 zrender 提 PR
@luozejian

**Comment by little-sean** [comment]
> Yes, 5.0 supports `rem` and `em`, you can try it now.

IE 11 not support rem and em

**Comment by little-sean** [comment]
> Yes, 5.0 supports `rem` and `em`, you can try it now.

IE 11 not support rem and em

**Comment by kainchow** [comment]
> Yes, 5.0 supports `rem` and `em`, you can try it now.

图例的itemWidth、itemHeight、itemGap这些还是不支持rem呢
