### ISSUE TITLE
Cannot make y-axis not starting at 0

### ISSUE THREAD

**Issue by Lanove** [apache/incubator-echarts#13442]
### Version
4.9.0

### Steps to reproduce
Changing chart config to
yAxis: {
          type: "value",
          axisLabel: {
            fontSize: 14,
            fontFamily: '"Poppins", sans-serif',
          },
          axisLine: {
            onZero: 0,
            onZeroAxisIndex:0,
            lineStyle: {
              color: "#e9e9e9",
            },
          },
        },

### What is expected?
Chart y-axis not starting at 0

### What is actually happening?
Chart y-axis still starting at 0

**Comment by pissang** [comment]
You can set `yAxis.scale` to `true`

**Comment by Lanove** [comment]
Well, that was quick. thanks for pointing that out, i guess i had wrong settings before.
