### ISSUE TITLE
地理实例，没有JSON文件

### ISSUE THREAD

**Issue by i700S** [apache/incubator-echarts#13458]
地理坐标/地图 Map/GEO 的实例《Bus Lines of Beijing》北京公交
实例地址：https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-bus
实例代码，有一行：

“ROOT_PATH + '/data/asset/data/lines-bus.json',”

点“下载”按钮，不带这个JSON文件。 
在线看，也找不到 JSON文件。

希望能 让我看到JSON文件

**Comment by pissang** [comment]
`console.log(ROOT_PATH + '/data/asset/data/lines-bus.json')` 就可以看到这个文件地址

**Comment by i700S** [comment]
> `console.log(ROOT_PATH + '/data/asset/data/lines-bus.json')` 就可以看到这个文件地址

Tank you! :D 多谢！
