### ISSUE TITLE
scale设置为true时，barMinHeight失效

### ISSUE THREAD

**Issue by GangLx** [apache/incubator-echarts#13461]
scale设置为true时，barMinHeight失效，该功能在4.1版本正常。

**Comment by GangLx** [comment]
{
        xAxis: {
            type: "category",
            data: ["2020-10-31"]
        },
        yAxis: {
            type: "value",
            scale: true
        },
        series: [{
            data: [66],
            type: "bar",
            itemStyle: {
                color: "blue"
            },
            barMinHeight: 1
        },{
            data: [72],
            type: "bar",
            itemStyle: {
                color: "red"
            },
            barMinHeight: 1
        }],
        tooltip: {
            trigger: "axis"
        }
    }

**Comment by susiwen8** [comment]
感觉这不是 bug，scale了，y轴起点在 66，所以第一个 series没有出现。

**Comment by GangLx** [comment]
> 感觉这不是 bug，scale了，y轴起点在 66，所以第一个 series没有出现。

可是我设置了barMinHeight高度为1，应该第一个 series应该显示一点点

**Comment by GangLx** [comment]
目前看来这个方法不对
function getValueAxisStart(baseAxis, valueAxis, stacked) {
    return valueAxis.toGlobalCoord(valueAxis.dataToCoord(valueAxis.type === 'log' ? 1 : 0));
}

4.1版本是这么写的
function getValueAxisStart(baseAxis, valueAxis, stacked) {
    return (
        indexOf(baseAxis.getAxesOnZeroOf(), valueAxis) >= 0
        || stacked
    )
    ? valueAxis.toGlobalCoord(valueAxis.dataToCoord(0))
    : valueAxis.getGlobalExtent()[0];
}

**Comment by GangLx** [comment]
4.1版本就会显示一点点高度
