### ISSUE TITLE
如何解决Echarts在小程序中滑不动 出现i Invoke event touchMove？

### ISSUE THREAD

**Issue by hljc** [apache/incubator-echarts#13473]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by hljc** [comment]
&nbsp;Can you tell me exactly what it means




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhongxiang.Wang"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午3:15
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "看见留念 "<825596010@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] 如何解决Echarts在小程序中滑不动 出现i Invoke event touchMove？ (#13473)





 
Closed #13473.

**Comment by hljc** [comment]
&nbsp;Can you speak Chinese




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhongxiang.Wang"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午3:15
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "看见留念 "<825596010@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] 如何解决Echarts在小程序中滑不动 出现i Invoke event touchMove？ (#13473)





 
Closed #13473.

**Comment by plainheart** [comment]
我看见你已经提了一个issue了 这个重复的暂且关了。#13472

**Comment by hljc** [comment]
&nbsp;Can you speak Chinese


我是用echarts中dataZoom，可是没有任何反应，是否是在微信小程序中不兼容呢？
------------------ 原始邮件 ------------------
发件人: "Zhongxiang.Wang"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午3:15
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "看见留念 "<825596010@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] 如何解决Echarts在小程序中滑不动 出现i Invoke event touchMove？ (#13473)





 
Closed #13473.

**Comment by hljc** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhongxiang.Wang"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午3:22
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "看见留念 "<825596010@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] 如何解决Echarts在小程序中滑不动 出现i Invoke event touchMove？ (#13473)





 
我看见你已经提了一个issue了 这个重复的暂且关了。#13472

**Comment by plainheart** [comment]
echarts-for-weixin 是第三方扩展，建议到 https://github.com/ecomfe/echarts-for-weixin 这个仓库反馈问题。

**Comment by hljc** [comment]
好的谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午3:24
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"看见留念 "<825596010@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] 如何解决Echarts在小程序中滑不动 出现i Invoke event touchMove？ (#13473)





 
echarts-for-weixin 是第三方扩展，建议到 https://github.com/ecomfe/echarts-for-weixin 这个仓库反馈问题。

**Comment by hljc** [comment]
关于微信小程序滑动报‘

i Invoke event touchMove？
’这个是什么原因啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午3:24
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"看见留念 "<825596010@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] 如何解决Echarts在小程序中滑不动 出现i Invoke event touchMove？ (#13473)





 
echarts-for-weixin 是第三方扩展，建议到 https://github.com/ecomfe/echarts-for-weixin 这个仓库反馈问题。
