### ISSUE TITLE
折线图图例中的图标，如何能去掉两边的横线

### ISSUE THREAD

**Issue by genggs** [apache/incubator-echarts#13494]
如下图，谢谢

![Image 142](https://user-images.githubusercontent.com/11642621/97381497-2b2f0f00-1904-11eb-9196-cf5ffa27db66.png)

**Comment by plainheart** [comment]
设置 `legend.icon` 为 `emptyCircle` 即可。

**Comment by genggs** [comment]
收到，非常感谢
