### ISSUE TITLE
how to display additional information in the sankey chart tooltips

### ISSUE THREAD

**Issue by Vignesvar-ap** [apache/incubator-echarts#13492]
### Version
4.8.0

### Steps to reproduce
There are no details in the documentation about to display the additional information in the tooltips. Can you please help us to display the additional information in the report. Please find the data format below. 

[sample-sankey-code.txt](https://github.com/apache/incubator-echarts/files/5443314/sample-sankey-code.txt)

### What is expected?
I would like to display additional information like Average sales,  total sales value between the edges. 

### What is actually happening?
Chart displays the source and destination node and value properly.

**Comment by plainheart** [comment]
I'd like to suggest using  formatter callback function to get the data of node and assemble and return your information.

```js
(params: Object|Array, ticket: string, callback: (ticket: string, html: string)) => string
```

**Comment by Vignesvar-ap** [comment]
Hi, 
Thanks for your response, I have tried the callback function parameter but the tooltip is not visible in the front-end chart now. It has display earlier. Please find the sample code I have used in the JS file. 

formatter: function(param, ticket, callback){
			// console.log("param"+JSON.parse(param.dta.source[0]));
			//	return `${param.source} -> ${param.target} : ${value}`;
				for(var i=0; i<param.length; i++){
				console.log("param -> "+param[i].value);
					return param[i].value;
				}
				
			}
Please let me know where I did a mistake here.

**Comment by plainheart** [comment]
@Vignesvar-ap Hi, I suppose that the information you need is all in the first parameter in the callback function.
Here is a demo. https://gallery.echartsjs.com/editor.html?c=x-2oD3M18w&v=1

**Comment by Vignesvar-ap** [comment]
Dear @plainheart, 
Thank you very much for your support that the given sample code is working for me.

**Comment by YusufcanY** [comment]
> @Vignesvar-ap Hi, I suppose that the information you need is all in the first parameter in the callback function. Here is a demo. https://gallery.echartsjs.com/editor.html?c=x-2oD3M18w&v=1

Link is broken, can you provide a new link please?
