### ISSUE TITLE
树图点击label文字不能收起和展开，只能点击小圆圈

### ISSUE THREAD

**Issue by ghostjzf** [apache/incubator-echarts#13500]
### Version
4.8.0

### Steps to reproduce
树图点击label文字不能收起和展开，只能点击小圆圈

### What is expected?
希望可以点击

### What is actually happening?
点击不能收起和展开

**Comment by plainheart** [comment]
即将发布的 5.0 已经实现了此特性，预计下月初会发布稳定版，目前可以先试用 beta 版本。

**Comment by ghostjzf** [comment]
> 即将发布的 5.0 已经实现了此特性，预计下月初会发布稳定版，目前可以先试用 beta 版本。

具体几号有计划吗

**Comment by plainheart** [comment]
大致时间为下月初，暂无具体时间。
