### ISSUE TITLE
tooltip trigger 'axis' | Show tooltip with intersecting data points only

### ISSUE THREAD

**Issue by vikashpisces** [apache/incubator-echarts#13512]
### Version
4.1.0-release

### Reproduction link
[http://jsfiddle.net/vikashvickyssec/vLosyz1p/1/](http://jsfiddle.net/vikashvickyssec/vLosyz1p/1/)

### Steps to reproduce
Multiple series of lines having same value at any one x-axis point shows all the series value at that point.

### What is expected?
There should have been an option to display only intersecting data points

### What is actually happening?
Currently if tooltip triggered by 'axis' shows all the series value at that point

---
If multiple series have same value at any x-axis point, tooltip triggered by 'axis' shows all the series value at that point. Is there way, only intersecting points can be displayed in the tooltip.

Even with triggered set to 'item', the series with higher z-index is only shown in the tooltip.

For me I need to display all the overlapping data points in the tooltip.

**Comment by susiwen8** [comment]
Sorry, this was by design
