### ISSUE TITLE
漏斗图  orient:'horizontal' 失效

### ISSUE THREAD

**Issue by li-0813** [apache/incubator-echarts#13524]
![111](https://user-images.githubusercontent.com/54049031/97835701-bc8fee00-1d15-11eb-823e-95114d14383c.png)

**Comment by plainheart** [comment]
感谢反馈。`orient` 是 4.9.0 新加的特性，建议使用 4.9.0 及更新版本，文档目前引用的 ECharts 版本是 4.8.0。
