### ISSUE TITLE
Overlapping legend and title

### ISSUE THREAD

**Issue by azhang** [apache/incubator-echarts#13529]
### Version
5.0.0-beta.2

### Steps to reproduce
Legend and title enabled. Small window

### What is expected?
Option to not have legend and title overlap

### What is actually happening?
Legend and title overlaps

---
Am I missing something obvious?

**Comment by helgasoft** [comment]
try [this](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxEksByTxUjVQrFF-ZFhoRgBbGloAGwhoKlgALyTklNSk3iDBYTEARgBWAAYeWAAmAGYi0pKAFmKSnIAOYpyyvObqgHY6gDYC60dSdApqOhi42iDPQfR3UIiCaNj4gCNVtfWM6dghMBEAwuKKutrYRsO22E7i3v7MskoaWTHlSZJb9Ci2KmgBAndPgBmYAW1QKAFJaB5iiRIGBPn88ApliwMMDol8fmQIHDIsVsVQwgBxRggAiVIysbRo3oQuwoOwAbiAA)
