### ISSUE TITLE
echarts 澳门地图花王堂区、望德堂区边界有缝隙

### ISSUE THREAD

**Issue by xxeen** [apache/incubator-echarts#13555]
### Version
4.9.0

### Steps to reproduce
绘制澳门地图

### What is expected?
区之间不要有缝隙

### What is actually happening?
区之间有缝隙
![image](https://user-images.githubusercontent.com/15999606/98341745-4e676600-204a-11eb-8810-85f67a4a3e75.png)

**Comment by pissang** [comment]
我们不再更新和提供地图数据，你可以试试从 http://datav.aliyun.com/tools/atlas/#&lat=22.16015433719617&lng=113.56859349999998&zoom=13.5
