### ISSUE TITLE
set polyline-tree's option symbol = 'none' lead to echart  disappear

### ISSUE THREAD

**Issue by DBSDs** [apache/incubator-echarts#13560]
### Version
5.0.0-beta.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=tree-polyline](https://echarts.apache.org/examples/zh/editor.html?c=tree-polyline)

### Steps to reproduce
1.open https://echarts.apache.org/examples/zh/editor.html?c=tree-polyline
2.add
symbol = 'none',
to this echart option

### What is expected?
in my opinion, set symbol = 'none' to make symbol disappear,but   chart work well

### What is actually happening?
echart disappear

**Comment by susiwen8** [comment]
Fix in incoming 5.0
