### ISSUE TITLE
line chart怎么能在x轴是"value"的时候使用 stack

### ISSUE THREAD

**Issue by Derek-Xiang** [apache/incubator-echarts#13578]
line chart中，series里面的stack属性，只对category的x轴数据好用，其实value也可以，但她加的是series里面data的第一个数据，比如数据是[(1,2), (2,4)] 每次都是把 index是0的1，和2 与对应同stack的series数据相加，但我需要的是加在y轴上

This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by wzc11227** [comment]
很关键的问题

**Comment by wzc11227** [comment]
找到解决方法了，把y轴数据和x轴数据位置对换，然后用encode指定x轴和y轴
