### ISSUE TITLE
Allow to select and copy text of legend items.

### ISSUE THREAD

**Issue by lesovsky** [apache/incubator-echarts#13585]
### What problem does this feature solve?
Currently it's impossible to select text of legend items and copy it into buffer (and then paste somewhere).

### What does the proposed API look like?
Legend component could be extended with extra property, like 'selectable' with values 'true', 'false'. Such property switches ability of the legend items to be selectable.

**Comment by plainheart** [comment]
Unless we provide an HTML renderer for `legend` component,  we can only use SVG renderer and set the SVG container's style by CSS `user-select: auto` to enable text selection. In canvas, it may be quite complicated and not very practical.

Here is a demo for SVG renderer https://codepen.io/plainheart/pen/abZRgRM

**Comment by lesovsky** [comment]
Is it possible to achieve this without SVG but using events (like 'legendselected') ?

**Comment by plainheart** [comment]
Maybe you can use a third-party library like [clipboardjs](https://clipboardjs.com/), in the callback of `legendselected` event, set the text into system clipboard manually by its API.

**Comment by lesovsky** [comment]
Thanks for help, will try to make something )))
