### ISSUE TITLE
Numeric category values explicitly specified in the axis do not render

### ISSUE THREAD

**Issue by dirslashls** [apache/incubator-echarts#13598]
### Version
5.0.0-beta.2

### Steps to reproduce
Use the following in the editor

```
option = {
    tooltip: {},
    xAxis: { type: 'category',  data: [10,15,20] },
    yAxis: { type: 'value', min: 0, max: 20 },
    series: [{
        symbolSize: 20,
        encode: { x: 0, y: 1 },
        data: [
            [10,8], [20,15], [15,10]
        ],
        type: 'scatter'
    }]
};
```

### What is expected?
Scatter plot should render.

### What is actually happening?
It doesn't show the data.

---
If I remove "data" in the xAxis options or if I use index into this data array as the x value in the series data it renders. Note that if I remove the data in the xAxis, then I can't control the order in which the xAxis labels are rendered.

**Comment by Ovilia** [comment]
`encode: { x: 0, y: 1 }` makes the first value of data to be used as x axis value, but in your code, the xAxis is typed in category, so there is a conflict with `10`, `20`, `15` in your data.
See if this is what you want:

```js
option = {
    tooltip: {},
    xAxis: { type: 'category',  data: ['10','15','20'] },
    yAxis: { type: 'value', min: 0, max: 20 },
    series: [{
        symbolSize: 20,
        encode: { x: 0, y: 1 },
        data: [
            ['10',8], ['20',15], ['15',10]
        ],
        type: 'scatter'
    }]
};
```

**Comment by dirslashls** [comment]
I was hoping to use numeric values for category axis but seems like it's not supported. Note that, this type of requirement comes for discrete numeric values that are just a handful. Like the number of Cylinders in the cars data set.
