### ISSUE TITLE
echarts-issue-helper is down

### ISSUE THREAD

**Issue by jianzhongli** [apache/incubator-echarts#13619]
The issue template prompted us to create issue with [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper), but the URL: https://ecomfe.github.io/echarts-issue-helper is not accessable.

**Comment by plainheart** [comment]
The helper won't never be down. If you can't access it, it is mainly for your network environment. Please update your hosts file to specify manually the IP of `*.github.io`.
