### ISSUE TITLE
echarts的树图在iphone xs max下，宽度过宽会导致canvas不渲染，白屏问题 

### ISSUE THREAD

**Issue by itsxt** [apache/incubator-echarts#13626]
### Version
4.2.1

### Steps to reproduce
新建一个树图，树图的子节点为170个以上，宽度为720%以上。需要在iphone xs max屏幕下

### What is expected?
宽度在720%以上时，canvas正常渲染

### What is actually happening?
宽度在720%以上时，canvas不渲染，页面白屏

**Comment by pissang** [comment]
试试用 svg 渲染模式

**Comment by itsxt** [comment]
> 试试用 svg 渲染模式

页面上要渲染img和一些标签，不能用svg

**Comment by pissang** [comment]
没理解为什么渲染 img 和标签不能用 svg？是用了富文本标签？

**Comment by itsxt** [comment]
> 没理解为什么渲染 img 和标签不能用 svg？是用了富文本标签？

是的，标签文字用的富文本

**Comment by itsxt** [comment]
动态修改宽度到720%以上时，xs max就会出现不渲染的问题，其余情况下是正常的

**Comment by pissang** [comment]
5.0 SVG 也支持富文本了，这种情况应该只能通过切换 SVG 模式解决，因为移动端内存限制，Canvas 的尺寸也是有限制的

**Comment by itsxt** [comment]
> 5.0 SVG 也支持富文本了，这种情况应该只能通过切换 SVG 模式解决，因为移动端内存限制，Canvas 的尺寸也是有限制的

了解了，感谢回复解答~
