### ISSUE TITLE
Pictorialbar: left side of the svg overflow the yAxis

### ISSUE THREAD

**Issue by dmzc** [apache/incubator-echarts#13642]
### Version
5.0.0

### Steps to reproduce
The example of pictorialbar on echarts official website: https://echarts.apache.org/examples/en/editor.html?c=pictorialBar-velocity
1.change the yAxis.axisLine.show=true;
2.click the "RUN" to update instace.

### What is expected?
The left side of svg does not overflow the yAixs

### What is actually happening?
 The left side of svg overflow the yAixs.axisLine

**Comment by Ovilia** [comment]
Tested with 5.0 and it seem to be fixed. Feel free to reopen this if not.

**Comment by dmzc** [comment]
In website you given,follow your instructions,the problem still exists.
The reproduce steps:
1.Open  https://echarts.apache.org/next/examples/en/editor.html?c=line-simple
2.Copy the option on https://echarts.apache.org/examples/en/editor.html?c=pictorialBar-velocity
3.Change the renderer as SVG
4.Set yAxis.axisLine as true and click run
@Ovilia Thanks for your help.
![捕获](https://user-images.githubusercontent.com/25882839/100061028-63c0fa80-2e68-11eb-84a8-3af1ec7b48fe.PNG)
