### ISSUE TITLE
On the compatibility of echarts in the old version of edge browser

### ISSUE THREAD

**Issue by HappyXuan** [apache/incubator-echarts#13652]
In the practice of using echart for visualization, we found that in the histogram, if the abscissa axislabel font is rotated to 50% and the font color is white, it still shows black in the old version of edge browser.

This problem is not found in Google browser (version 87.0) and browsers such as Firefox, everything is displayed normally.
`
xAxis: [{
    type: 'category',
    data: this.mark,
    axisLine: {
        show: true,
        lineStyle: {
            color: "rgba(255,255,255)",
            width: 1,
            type: "solid"
        },
    },
    axisTick: {
        show: false,
    },
    axisLabel: {
       interval: 0,
       rotate: 50,
       show: true,
       splitNumber: 15,
       textStyle: {
           color: "rgba(255,255,255)",
           fontSize: '12',
        },
     },
}],
`

**Comment by plainheart** [comment]
`rgba(255,255,255)` seems not be a standard expression.
Please try again with `rgba(255, 255, 255, 1)` or `rgb(255, 255, 255)`.
If the problem still exists, please give us another feedback with the issue template. Otherwise, it will be still closed immediately by the bot. Thanks!

**Comment by plainheart** [comment]
And could you let me know what version of ECharts are you using?
