### ISSUE TITLE
配置项 富文本标签rich.<style_name>.padding 为四位数字时，实际展现结果为下、右、上、左

### ISSUE THREAD

**Issue by LiZhaji** [apache/incubator-echarts#13658]
### Version
4.9.0

### Steps to reproduce
设置富文本标签下，每个样式的`padding` 为四个项的数组，比如[10, 20, 30, 40]

### What is expected?
该样式下的标签上右下左的内边距分别为10、20、30、40

### What is actually happening?
上下位置反了，即该样式下的标签上右下左的内边距分别为30、20、10、40

**Comment by susiwen8** [comment]
Fix in 5.0, please wait for 5.0 release
