### ISSUE TITLE
svg image save bug on svg render with external symbol image

### ISSUE THREAD

**Issue by partitect** [apache/incubator-echarts#13655]
### Version
4.9.0

### Steps to reproduce
When i use save as image with type 'svg' on svg render, image dowloading but not showing. because i m using external image 

**Svg error message : namespace prefix xlink for href on use is not defined**

```javascript
symbol: "image://assets/img/tictoc.png"
```
or
```javascript
symbol: "image://assets/img/tictoc.svg"
```

![Line Chart](https://i.ibb.co/8c6QCZt/Ekran-Resmi-2020-11-21-00-23-31.png)

![Svg Error](https://i.ibb.co/wpmkZCV/Ekran-Resmi-2020-11-21-00-23-04.png)

![Svg Error Lines](https://i.ibb.co/LZLx3sy/Ekran-Resmi-2020-11-21-00-23-56.png)

### What is expected?
External images can be convert to path image or data image

### What is actually happening?
Svg images not showing

**Comment by plainheart** [comment]
Could you provide us with a demo? Especially the broken SVG file.

**Comment by plainheart** [comment]
Well, thanks for your feedback! I've reproduced this bug. Will fix it later.

**Comment by partitect** [comment]
my chart code is

images tested on local assets and remote url

<pre>var myChart = echarts.init(document.getElementById("myChart"), null, {renderer: 'svg'});
var toolbox ={
top: 10,
right: 10,
show: true,
feature: {
mark: { show: false },
dataView: { show: false, readOnly: false },
magicType: { show: true, type: ["stack", "tiled"], title: "Change" },
restore: { show: true, title: "Refresh" },
saveAsImage: { show: true, title: "Save As Image",pixelRatio:2,type:'svg' }
}
}
myChart.setOption({
tooltip: {
trigger: "axis"
},
legend: {
data: ["Tictoc", "Whatsapp", "Snapchat"],
itemGap: 30,
itemWidth: 40,
itemHeight: 40
},
toolbox: toolbox,
grid: {
show: false,
containLabel: true,
left: "10",
right: "30",
top: "70",
bottom: "10"
},
color: ["#5ea9dd", "#54cc61", "#fffa04"],

calculable: true,
xAxis: [
	{
		type: "category",
		boundaryGap: false,
		data: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
	}
],
yAxis: [
	{
		type: "value"
	}
],
series: [
	{
		name: "Tictoc",
		type: "line",
		smooth: true,
		itemStyle: {
			normal: {
				areaStyle: { type: "default", shadowColor: "rgba(0, 0, 0, 0.9)", shadowBlur: 30, opacity: 0.8 },
				lineStyle: { opacity: 0 }
			}
		},
		data: [1320, 1132, 601, 234, 120, 90, 1680],
		symbol: "image://https://marka-logo.com/wp-content/uploads/2020/04/TikTok-Logo.png",
		symbolSize: 40
	},
	{
		name: "Whatsapp",
		type: "line",
		smooth: true,
		itemStyle: {
			normal: {
				areaStyle: { type: "default", shadowColor: "rgba(0, 0, 0, 0.9)", shadowBlur: 30, opacity: 0.8 },
				lineStyle: { opacity: 0 }
			}
		},
		data: [520, 182, 434, 1420, 390, 30, 1480],
		symbol: "image://https://marka-logo.com/wp-content/uploads/2020/04/TikTok-Logo.png",
		symbolSize: 40
	},
	{
		name: "Snapchat",
		type: "line",
		smooth: true,
		itemStyle: {
			normal: {
				areaStyle: { type: "default", shadowColor: "rgba(0, 0, 0, 0.9)", shadowBlur: 30, opacity: 0.8 },
				lineStyle: { opacity: 0 }
			}
		},

		data: [10, 12, 21, 54, 260, 830, 710],
		symbol: "image://https://marka-logo.com/wp-content/uploads/2020/04/TikTok-Logo.png",
		symbolSize: 40
	}
]
});</pre>
