### ISSUE TITLE
When can I install 5.0.0-rc.3 on npm?

### ISSUE THREAD

**Issue by ppbl** [apache/incubator-echarts#13663]
### What problem does this feature solve?

Notice that GitHub has released 5.0.0-rc.3. Can it be released to npm?

### What does the proposed API look like?
released 5.0.0-rc.3 on npm

**Comment by plainheart** [comment]
5.0.0-rc.3 won't be published on npm. The formal version 5.0.0 will be published later.

**Comment by ppbl** [comment]
Thank you for your reply
