### ISSUE TITLE
官方文档链接错误

### ISSUE THREAD

**Issue by yeyuguo** [apache/incubator-echarts#13667]
官网错误： https://echarts.apache.org/zh/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts

链接错误

可以按需引入的模块列表见 https://github.com/apache/incubator-echarts/blob/master/index.js

**Comment by plainheart** [comment]
感谢反馈，5.0 对目录结构做了较大的改动，后续会修复。
