### ISSUE TITLE
echarts.util is undefined

### ISSUE THREAD

**Issue by cheqianxiao** [apache/incubator-echarts#13701]
### Version
5.0.0

### Reproduction link
[https://codesandbox.io/s/wizardly-ride-umxfn](https://codesandbox.io/s/wizardly-ride-umxfn)

### Steps to reproduce
```js
import echarts from 'echarts/lib/echarts'  
console.log(ehcarts.util)  
```

### What is expected?
console an object

### What is actually happening?
console undefined

---
seems  in 5.x , the export.js is not mounted to echarts.js anymore when build . is it  expected ?

![image](https://user-images.githubusercontent.com/16025751/100317458-5be39080-2ff7-11eb-88f9-fed0bb13f707.png)

**Comment by pissang** [comment]
Hi @cheqianxiao 

It's expected. We don't mount the util/graphic..etc on the `echarts/lib/echarts` by default now. You can replace it with 

```js
import * as echarts from 'echarts/index.blank'  
```

**Comment by cheqianxiao** [comment]
ok, thx ~
