### ISSUE TITLE
世界地图在固定长宽后，精细度不够，中国的南海诸岛无法显示，需要缩放后才能显示，有没有参数可以设置强制显示

### ISSUE THREAD

**Issue by weiwFu** [apache/incubator-echarts#13716]
### Version
5.0.0

### Steps to reproduce
世界地图在固定长宽后，精细度不够，中国的南海诸岛无法显示，需要缩放后才能显示，有没有参数可以设置强制显示

### What is expected?
世界地图在固定长宽后，精细度不够，中国的南海诸岛无法显示，需要缩放后才能显示，有没有参数可以设置强制显示

### What is actually happening?
世界地图在固定长宽后，精细度不够，中国的南海诸岛无法显示，需要缩放后才能显示，有没有参数可以设置强制显示

**Comment by Ovilia** [comment]
Apache ECharts 不提供地图下载，建议使用百度地图等第三方地图，配合 ECharts 地图插件使用，参见：https://echarts.apache.org/zh/download-extension.html
