### ISSUE TITLE
series.type: 'lines' 且配置了  effect 动画的都不能正常被  clear() 清除掉

### ISSUE THREAD

**Issue by dev-Hanjing** [apache/incubator-echarts#13724]
https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-effect
此示例中的 effect 在调用 myChart.clear() 时，并不能清除掉已经画上去的线。而且只要是用到了  series.type: 'lines' 且配置了  effect 动画的都不能正常被  clear() 清除掉。

**Comment by dev-Hanjing** [comment]
模板打不开啊

**Comment by chj-damon** [comment]
我也遇到这个问题了，请问你解决了吗
