### ISSUE TITLE
如何选择显示中国地图中的某几个省份

### ISSUE THREAD

**Issue by GalaxyTrain** [apache/incubator-echarts#13729]
### Version
4.9.0

### Steps to reproduce
1.如果只有china.json，怎么选择显示其中的某几个省份，比如京津冀
2.如果有各个分省的json，怎么合并到一起显示

### What is expected?
有可以直接设定的参数，而非再编程

### What is actually happening?
现在还没有实现

**Comment by Ovilia** [comment]
ECharts 官方不提供地图文件下载，请自行查找合并后的 json 文件。
