### ISSUE TITLE
柱状图lable 在 堆积图情况下被覆盖的问题

### ISSUE THREAD

**Issue by LuffyChan888** [apache/incubator-echarts#1373]
官网http://echarts.baidu.com/doc/example/line3.html
修改 itemStyle: {normal: {areaStyle: {type: 'default'},
                                     label : {show : true,position : 'top'}}},
通过toolbox显示成柱状堆积图时，下面两个条目的lable被覆盖了，能否调整一下canvas的渲染顺序，让其都能正常显示？

![line3_bar](https://cloud.githubusercontent.com/assets/10646771/6659529/7e02489a-cbc2-11e4-9119-518f6b890360.png)
![line3_bar_tile](https://cloud.githubusercontent.com/assets/10646771/6659531/89196038-cbc2-11e4-957c-fcab52b04b01.png)

**Comment by wuyazi** [comment]
我也遇到这个问题了，有解决方案吗？

**Comment by IlovedJoey** [comment]
@wuyazi 暂时还没找到完美的解决办法，没有去深入研究。等 官方的解决方案吧
