### ISSUE TITLE
Is the official document v5? 

### ISSUE THREAD

**Issue by wenfangdu** [apache/incubator-echarts#13737]
### What problem does this feature solve?
If so, where do we find documents of previous versions? If not, when will v5 document be online?

### What does the proposed API look like?
None

**Comment by susiwen8** [comment]
https://echarts.apache.org/next/zh/option.html#title
![Screen Shot 2020-12-03 at 09 21 03](https://user-images.githubusercontent.com/20318608/100951128-e6247b00-3548-11eb-9857-59012b2b7261.png)
