### ISSUE TITLE
文档页链接丢失

### ISSUE THREAD

**Issue by xjhjzxh** [apache/incubator-echarts#13749]
在文档https://echarts.apache.org/zh/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts
页面中, 页面底部的按需引入列表链接失效了:
https://github.com/apache/incubator-echarts/blob/master/index.js
请问目前在哪里看按需引入列表?
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by susiwen8** [comment]
Thanks for reporting, we just finished merge `next` branch into `master`. This will be fixed soon
