### ISSUE TITLE
Export `ECharts` class in TypeScript

### ISSUE THREAD

**Issue by ilueckel** [apache/incubator-echarts#13755]
### Version
5.0

### What problem does this feature solve?
The `init` function returns a class of type `ECharts`. This works fine as long as you use the chart variable right after initalization.
```ts
import {init, EChartsOption} from "echarts";
...
export class BaseChart {
  initChart() {
    const chart = init(nativeElement);
    // do something else with the chart.
  }
}
```

But all typings get lost, when you want to pass the chart around (e.g. for updating data later on)
```ts
import {init, EChartsOption} from "echarts";
...
export class BaseChart {
  const chart: ECharts; // <--- This does not work. You can it make `any`, but then all typings are lost;
  initChart() {
    this.chart = init(nativeElement);
    // do something else with the chart.
  }
}
```

The TypeScript definitions do not export the `ECharts` class
```ts
import {ECharts} from "echarts" // <---- This is not possible
```

**Edit**
Using `EChartsType` which is extending `ECharts` does not work too.

```ts
import {init, EChartsOption} from "echarts";
import {EChartsType} from "echarts/lib/echarts";
...
export class BaseChart {
  initChart() {
    const chart: EChartsType = init(nativeElement);
    // This doesn't work too
    // TS2322: Type 'ECharts' is not assignable to type 'EChartsType'.
    // Types have separate declarations of a private property '_zr'.
  }
}
```

### What does the proposed API look like?
Extend the exports in TypeScript. Something like this:

```
export { ECharts, EChartsFullOption as EChartsOption, connect, disConnect, dispose, getInstanceByDom, getInstanceById, getMap, init, registerLocale, registerMap, registerTheme };
```

**Comment by hesamat** [comment]
Further to your comment, we are relying on other types like BarSeriesOption, ChartDataset, etc. This change in v5 will result in losing all of the typings in our code base. Why don't you export those?

**Comment by fxxjdedd** [comment]
Same problem, the only way now I can import the type I want is like:

`import {CartesianAxisOption} from'echarts/lib/coord/cartesian/AxisModel'`

This is really confusing.

**Comment by pissang** [comment]
@ilueckel Hi, we will plan to export more types 

before that, you can use 
```ts
type EChartsInstance = ReturnType<init>;
```
as a workaround.

**Comment by ThomasBower** [comment]
+1 to this issue.

**Comment by ThomasBower** [comment]
A bigger issue I'm having is defining a `renderItem` function for custom series. This is because the return type, `CustomElementOption`, isn't actually exported from the type definitions.

**Comment by pissang** [comment]
@ThomasBower Hi, this issue is already in the 5.0.1 milestone https://github.com/apache/incubator-echarts/milestone/21

**Comment by peder1001** [comment]
> Same problem, the only way now I can import the type that I want is like:
> 
> `import {CartesianAxisOption} from 'echarts/lib/coord/cartesian/AxisModel'`
> 
> This is really confusing.

Same for me. Took a lot of work to get my 4.9 implementation to work with 5.0. I will wait until a later version and also when ngx-echarts officially supports v5.x

**Comment by Emeryao** [comment]
> @ilueckel Hi, we will plan to export more types
> 
> before that, you can use
> 
> ```ts
> type EChartsInstance = ReturnType<init>;
> ```
> 
> as a workaround.


In my case the workaround above does not work but the codes below worked around

```typescript
import * as echarts from 'echarts';
type ECharts = ReturnType<typeof echarts.init>;
let chart = echarts.init(someElement);
```

echarts@v5.0.0
TypeScript@v4.0.5

**Comment by pissang** [comment]
Sorry for the mistake. You are right. It should be `ReturnType<typeof echarts.init>;`
