### ISSUE TITLE
Baidu map extension link is broken

### ISSUE THREAD

**Issue by wenfangdu** [apache/incubator-echarts#13750]
### Version
5.0.0

### Reproduction link
[https://echarts.apache.org/en/download-extension.html](https://echarts.apache.org/en/download-extension.html)

### Steps to reproduce
Visit the above link, click baidu map extension.

### What is expected?
Go to baidu map extension github repo.

### What is actually happening?
Link was broken.

---
Where's the new one?

**Comment by wenfangdu** [comment]
I think I've found it: https://github.com/apache/incubator-echarts/tree/master/extension-src/bmap

**Comment by pissang** [comment]
Thanks for the feedback!

**Comment by pissang** [comment]
Fixed in https://github.com/apache/incubator-echarts-www/commit/ac37153e798557b9c6dac8a480ffef6428025fa5
