### ISSUE TITLE
SVG renderer 下 graph 图 Image 的 symbol opacity 无效

### ISSUE THREAD

**Issue by cenzhongman** [apache/incubator-echarts#13762]
### Version
4.9.0

### Steps to reproduce
echarts.init(ele, null, {renderer: 'svg'});

...
{
      name: "System",
      symbol: "image://http://localhost:8801/path/xxx.png",
      opacity: 0.1
}
...

### What is expected?
透明度属性生效

### What is actually happening?
透明度属性无效

**Comment by cenzhongman** [comment]
同样的代码 使用canvas透明度正常

**Comment by plainheart** [comment]
感谢反馈，似乎是个 bug，稍后会进行修复！
