### ISSUE TITLE
在线构建5.0.0版本卡在Loaded module: "/zrender@5.0.1/src/svg/svg.js"上

### ISSUE THREAD

**Issue by LanjianNUll** [apache/incubator-echarts#13761]
### Version
5.0.0

### Steps to reproduce
1， 打开 https://echarts.apache.org/zh/builder.html  在线构建网站 

2，图表，组件，坐标系默认勾选，其他选项增加勾选svg

3，点击下载，跳转到 https://echarts.apache.org/zh/builder/echarts.htmlcharts=bar,line,pie,funnel&components=gridSimple,title,legendScroll,tooltip&svg=true&version=5.0.0

4，等待一会卡住在 Loaded module: "/zrender@5.0.1/src/svg/svg.js"上

5， f12 查看 cdn.jsdelivr.net/npm//zrender@5.0.1/src/svg/svg.js?__v__=1607164211752:1 Failed to load resource: the server responded with a status of 404 

### What is expected?
下载成功

### What is actually happening?
是否svg的 5.0.0 不支持在线构建

**Comment by pissang** [comment]
@LanjianNUll 已经修复上线
