### ISSUE TITLE
5.0 broken when using demand import

### ISSUE THREAD

**Issue by fxxjdedd** [apache/incubator-echarts#13764]
### Version
5.0.0

### Steps to reproduce
```
import echarts from 'echarts/lib/echarts'
import 'echarts/lib/component/dataset'
import 'echarts/lib/chart/line'
import 'echarts/lib/component/axis'
import 'echarts/lib/component/title'

const ins = echarts.init(document.getElementById('chart'))
ins.setOption({
  title: {
    text: 123
  },
  yAxis: [{}],
  xAxis: [{type: 'category'}],
  dataset: {
    dimensions: ['date', 'pv'],
    source: [
      { date: '1', pv: 123 }
    ]
  }, 
  series: [{
    type: 'line'
  }]
}) 

```

### What is expected?
work

### What is actually happening?
broken
![image](https://user-images.githubusercontent.com/13739947/101258200-e8aaee80-375b-11eb-97ee-42cc58ed00f4.png)

**Comment by fxxjdedd** [comment]
reproduce demo:
https://codesandbox.io/s/objective-architecture-p36kq?file=/src/index.js

**Comment by pissang** [comment]
After some test. Seems the demo works after importing bar chart
```js
import "echarts/lib/chart/bar";
```
Going to find out why.

**Comment by tyfoan** [comment]
> After some test. Seems the demo works after importing bar chart
> 
> ```js
> import "echarts/lib/chart/bar";
> ```
> 
> Going to find out why.

worked for me
import 'echarts/lib/coord/cartesian/Grid';
import 'echarts/lib/coord/cartesian/Axis2D';
