### ISSUE TITLE
5.0 broken with TypeScript@3.9.2+

### ISSUE THREAD

**Issue by fxxjdedd** [apache/incubator-echarts#13763]
### Version
5.0.0

### Steps to reproduce
build echarts@5.0 with TypeScript@3.9.2+

### What is expected?

I am using echarts5.0 in my own typescript@3.9.2+ project, and an error will be reported when compiling. Now, if I want to use echarts5.0, I must downgrade typescript to 3.8.3 in order to compile.

### What is actually happening?
broken
![image](https://user-images.githubusercontent.com/13739947/101256917-7d145180-375a-11eb-9689-7e1758e2ef1a.png)

**Comment by pissang** [comment]
Hi @fxxjdedd . Thanks for the feedback. Do you mind providing a reproduce demo t us?

**Comment by fxxjdedd** [comment]
After a long time of debugging, I finally found the problem:

write code:
```
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/bar'
```

test case1: ok
- typescript@3.8.3
- tsconfig -> skipLibCheck: true

test case2: ok
- typescript@3.8.3
- tsconfig -> skipLibCheck: false

test case3: ok
- typescript@3.9.2
- tsconfig -> skipLibCheck: true

test case4: **failed**
- typescript@3.9.2
- tsconfig -> skipLibCheck: false

test case5: ok
- typescript@4.1.2
- tsconfig -> skipLibCheck: true

test case6: **failed with more errors!**
- typescript@4.1.2
- tsconfig -> skipLibCheck: false

---- 
demo project: 
1. git clone https://github.com/fxxjdedd/temp-repo-echarts-issue -b master
1.  yarn
1. test the above use cases in turn
1. check `npx tsc -v` and run `npx tsc`

**Comment by pissang** [comment]
The current version doesn't have a convenient type export for partially importing. We are planning for a better API.

```js
import { init, use } from 'echarts/core'
import {LineSeries, BarSeries, LineSeriesOption, BarSeriesOption} from 'echarts/charts'
use([LineSeries, BarSeries]);
```

It will avoid exporting too many inner types. Which may be broken on other ts versions.

**Comment by Ky6uk** [comment]
@pissang is there any way to import only needed chart types, tooltips, etc. at the moment?

**Comment by pissang** [comment]
@Ky6uk In the current version it can't. But we will implement it in 5.0.1. Which will be released soon.
