### ISSUE TITLE
Length of edges  in different graph with simple layout are not the same even source and target have same coordinates

### ISSUE THREAD

**Issue by flycash** [apache/incubator-echarts#13779]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/n7t6Lqgj/11/](https://jsfiddle.net/n7t6Lqgj/11/)

### Steps to reproduce
Open the link and you could see that the length are different even they use the same options because the divs are different.

![image](https://user-images.githubusercontent.com/9923838/101450678-e0be9a80-3965-11eb-8bd2-a31d8a5675c1.png)

![image](https://user-images.githubusercontent.com/9923838/101450613-c5538f80-3965-11eb-9e63-4d0099f72122.png)

### What is expected?
I want to make those edges have the same length.

### What is actually happening?
Length is different

**Comment by 100pah** [comment]
It's by design. The length is based on the size of the container.
