### ISSUE TITLE
[question] How to find the default tooltip formatter

### ISSUE THREAD

**Issue by wenfangdu** [apache/incubator-echarts#13778]
### What problem does this feature solve?
I wanted to customize gauge tooltip to display percentage instead of number based on the original tooltip formatter, but couldn't find the source code for it, does anyone know where to look for?
![image](https://user-images.githubusercontent.com/28700378/101432786-7812f600-3944-11eb-9bb3-90461d35d77e.png)

### What does the proposed API look like?
none

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/blob/master/src/component/tooltip/TooltipView.ts#L688

**Comment by pissang** [comment]
If you are looking for the default formatter
https://github.com/apache/incubator-echarts/blob/master/src/component/tooltip/seriesFormatTooltip.ts#L33
