### ISSUE TITLE
矢量场图点击事件无法获取正确的params，里面没有data，且无法触发mouseover事件

### ISSUE THREAD

**Issue by zhangiser** [apache/incubator-echarts#13791]
### Version
5.0.0

### Steps to reproduce
Echats normal geo map, after adding click events,
```js 
myChart.on('click', function (params) {
    console.log(params);
});
```
You can get the correct params, which includes a data option, as you can see detail in  [https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap](url)
```js
{componentType: "series", componentSubType: "lines", componentIndex: 0, seriesType: "lines", seriesIndex: 0, …}
$vars: (3) ["seriesName", "name", "value"]
borderColor: undefined
color: "purple"
componentIndex: 0
componentSubType: "lines"
componentType: "series"
data: {coords: Array(290)}
dataIndex: 23
dataType: undefined
dimensionNames: ["value"]
encode: {value: Array(1)}
event: {type: "click", event: MouseEvent, target: t, topTarget: t, cancelBubble: false, …}
marker: "<span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:purple;"></span>"
name: ""
seriesId: "series00"
seriesIndex: 0
seriesName: "series0"
seriesType: "lines"
type: "click"
value: undefined
__proto__: Object
```

However, vector field diagram, such as wind field diagram, will not work. Click the event can take effect, but there is no data option in params object, see details in
[https://echarts.apache.org/examples/zh/editor.html?c=global-wind-visualization&gl=1](url)
```js
{type: "click", event: MouseEvent, target: undefined, topTarget: undefined, cancelBubble: false, …}
cancelBubble: false
event: MouseEvent {isTrusted: true, zrX: 221, zrY: 187, zrDelta: -0.3333333333333333, screenX: 623, …}
gestureEvent: undefined
offsetX: 221
offsetY: 187
pinchScale: undefined
pinchX: undefined
pinchY: undefined
stop: ƒ Jt()
target: undefined
topTarget: undefined
type: "click"
wheelDelta: -0.3333333333333333
which: 1
zrByTouch: undefined
__proto__: Object
```

### What is expected?
Get the correct params，It contains data

### What is actually happening?
Get the wrong params, which does not contain data

**Comment by pissang** [comment]
矢量场流图无法获取每个数据的具体信息。如果要获取的话可以考虑这个例子

**Comment by zhangiser** [comment]
> 矢量场流图无法获取每个数据的具体信息。如果要获取的话可以考虑使用这个例子
> https://echarts.apache.org/examples/zh/editor.html?c=custom-wind

**Comment by zhangiser** [comment]
> 矢量场流图无法获取每个数据的具体信息。如果要获取的话可以考虑使用这个例子
> https://echarts.apache.org/examples/zh/editor.html?c=custom-wind

@pissang 这个例子里好像没有方向，您的意思是把这两种demo整合一下？

**Comment by pissang** [comment]
@zhangiser 方向可以在自定义图形里加上箭头
