### ISSUE TITLE
5.0 pie下 tooltip 的textStyle.color 设置无效

### ISSUE THREAD

**Issue by hlbj105** [apache/incubator-echarts#13797]
### Version
5.0.0

### Steps to reproduce
5.0 pie下 tooltip 的textStyle.color 设置无效，官方网站中的试一试也无效。

Chrome 86.0.4240.111
OS: deepin 20.1Beta

### What is expected?
What is expected?

### What is actually happening?
What is actually happening?

**Comment by FateTestrossa** [comment]
![image](https://user-images.githubusercontent.com/44409271/101875519-b8cd7200-3bc5-11eb-9c19-b23699297a25.png)
Yes, I had this problem too. I changed the font color, but it didn't work

**Comment by susiwen8** [comment]
Thanks for report, I'will take a look
