### ISSUE TITLE
sankey 图当画布高度较小，数据量较多时，对齐会超出画布，图显示不全，建议nodeAlign增加中轴线对齐方式，截图如下

### ISSUE THREAD

**Issue by isbaselvy** [apache/incubator-echarts#13794]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.
![image](https://user-images.githubusercontent.com/23418528/101870075-da296080-3bbb-11eb-8fdd-0918d285e778.png)

**Comment by qq2575896094** [comment]
这个bug就这么给关啦???
