### ISSUE TITLE
The third-party sample website examples are gone, and many of your own examples are not found. Please fix it quickly.

### ISSUE THREAD

**Issue by jozhi** [apache/incubator-echarts#13805]
### Version
4.9.0

### Reproduction link
[https://www.makeapie.com/explore.html#sort=rank~timeframe=all~author=all](https://www.makeapie.com/explore.html#sort=rank~timeframe=all~author=all)

### Steps to reproduce
open is
https://www.makeapie.com/explore.html#sort=rank~timeframe=all~author=all

### What is expected?
The normal display

### What is actually happening?
Improper display

**Comment by plainheart** [comment]
Now the website has recoverd.

**Comment by helgasoft** [comment]
Down again... what a pity. Any chance of recovering ?
