### ISSUE TITLE
echarts5 支持关系图animation 属性， echarts4的关系图示例 animation：false不起作用；

### ISSUE THREAD

**Issue by hongyanwang9120** [apache/incubator-echarts#13810]
### Version
4.5.0

### Reproduction link
[https://www.makeapie.com/editor.html?c=xpOcBPPF7N ](https://www.makeapie.com/editor.html?c=xpOcBPPF7N )

### Steps to reproduce
echarts5 支持关系图animation 属性， echarts4的关系图示例 animation：false不起作用；
比如 https://www.makeapie.com/editor.html?c=xpOcBPPF7N 官方给的实例里面 animation 不起作用，求大神解释，怎么可以关系图一上来无默认初始化动画

### What is expected?
解决初始化  拥有默认动画

### What is actually happening?
不想拥有初始化时默认动画

**Comment by pissang** [comment]
layoutAnimation: false

**Comment by hongyanwang9120** [comment]
> layoutAnimation：错误

十分谢谢，已解决
