### ISSUE TITLE
Type error on number smooth value for "line" type

### ISSUE THREAD

**Issue by Ky6uk** [apache/incubator-echarts#13815]
### Version
5.0.0

### Reproduction link
[https://github.com/apache/incubator-echarts/blob/ddf832776bb60e7c26152cf2a696227bef79d938/src/chart/line/LineSeries.ts#L105](https://github.com/apache/incubator-echarts/blob/ddf832776bb60e7c26152cf2a696227bef79d938/src/chart/line/LineSeries.ts#L105)

### Steps to reproduce
[According to documentation](https://echarts.apache.org/next/en/option.html#series-line.smooth), it's possible to use a number from `0` to `1` for smooth value, and it works on `v4.x` of the library.  `v5.0` [doesn't allow numbers](https://github.com/apache/incubator-echarts/blob/ddf832776bb60e7c26152cf2a696227bef79d938/src/chart/line/LineSeries.ts#L105) anymore

### What is expected?
Number value in `smooth` for `line` type charts.

### What is actually happening?
Only boolean or undefined is possible.

**Comment by plainheart** [comment]
Thanks for your feedback! I think this is a mistake. It can be a `number` for specifying the smoothness of the line.
