### ISSUE TITLE
webGL does not work with 5.0

### ISSUE THREAD

**Issue by anoosurf** [apache/incubator-echarts#13847]
### Version
5.0.0

### Steps to reproduce
the latest echarts-gl.js gives error

Cannot read property 'util' of undefined
    at Object.<anonymous> (echarts-gl.js:195)
    at __webpack_require__ (echarts-gl.js:30)

### What is expected?
it should load like in previous versions

### What is actually happening?
it gives error and does not load any 3D series

**Comment by susiwen8** [comment]
I suppose you had done this:  `import echarts from 'echarts'`
It should be `import * as echarts from 'echarts'`

**Comment by anoosurf** [comment]
we are just using plain vanilla HTML, CSS, Javascript ... and a direct <script> reference to the .js file & no "import" command . 
is there a direct file for the echarts-gl.min.js which we can directly use ?

**Comment by pissang** [comment]
@anoosurf ECharts GL 2.0.0-rc.1 works for ECharts 5.0 https://www.jsdelivr.com/package/npm/echarts-gl?version=2.0.0-rc.1

**Comment by anoosurf** [comment]
thanks pissang :) 

its now showing the 3D chart .. but one bug .. it seems to be not showing the name on the axis
i tries changing all the settings of namegap etc. but not showing still 
thanks for your prompt help :)
![image](https://user-images.githubusercontent.com/4696146/102780145-753fe880-43bb-11eb-8a28-8749b02cb119.png)

xAxis3D: {
            name: 'test',
            nameGap:0,
            type: 'value'

        },
        yAxis3D: {
            name: fldy
        },
        zAxis3D: {
            name: fldz
        },

**Comment by anoosurf** [comment]
i also checked on the new 5.0 webGL demos.. same bug of missing axis Names

also the moment we do some filtering of data via visualmap selection.. 
it gives an error as shown in the pic below in the console.log -->

![image](https://user-images.githubusercontent.com/4696146/102791952-c527ab00-43cd-11eb-9d7e-a24bd5003545.png)

**Comment by anoosurf** [comment]
any temporary quickfix solution to this axis names .. which i could use ? 
thanks a lot in advance 👍 
u guys rock !! a world class amazing tool u've created :) 
hats off!

**Comment by pissang** [comment]
@anoosurf Thanks! I just published 2.0.0-rc.2 to fix these issues.
https://www.jsdelivr.com/package/npm/echarts-gl?version=2.0.0-rc.2

**Comment by anoosurf** [comment]
thanks a ton !!! 
u guys are simply amazing !
just love the spirit of continuing to keep improving and making a wonderful product better & better 
best wishes to your entire team :)
