### ISSUE TITLE
百度地图 作为底图时经纬度坐标转换为像素坐标，目前的echarts实例convertToPixel 方法不管用

### ISSUE THREAD

**Issue by minren118** [apache/incubator-echarts#13851]
### Version
5.0.0

### Steps to reproduce
在作以百度地图为底图的散点地图，想在散点基础上加上饼图，饼图需要定位像素坐标，只找到geo的经纬度坐标转像素坐标的方法。没有找到百度地图转像素坐标的实现方式 。
最终用echarts实例方法convertToPixel去转时提示以下错误。

echarts.js:30281 No coordinate system that supports convertToPixel found by the given finder.

### What is expected?
百度地图 作为底图时经纬度坐标转换为像素坐标，能够在ECharts绘图中使用。

### What is actually happening?
未找到百度地图 作为底图时经纬度坐标转换为像素坐标的方法

**Comment by plainheart** [comment]
目前可以使用

```js
chart.getModel().getComponent('bmap').coordinateSystem.dataToPoint([120, 30])
```

将经纬度转为像素坐标。
或者拿到百度地图实例之后，自行调用其提供的 `pointToOverlayPixel` 或 `pointToPixel` API 转换。

**Comment by minren118** [comment]
非常感谢，再咨询下，我怎样可以拿到百度地图实例？chart.getModel().getComponent('bmap')这个方法吗？我也想拿到它的实例，打开放大缩小控件之类的。

**Comment by plainheart** [comment]
```js
chart.getModel().getComponent('bmap').getBMap();
```

**Comment by joel785454405** [comment]
昨天晚上刚好遇到相同的问题，要用到这个方法，谢谢楼主
