### ISSUE TITLE
tooltip borderColor is invalid

### ISSUE THREAD

**Issue by Anti-Liu** [apache/incubator-echarts#13860]
### Version
5.0.0

### Steps to reproduce
const option = {
  tooltip: {},
  legend: {},
  xAxis: {
    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  },
  yAxis: {},
  series: [{
    name: "Sale",
    type: "bar",
    data: [5, 20, 36, 10, 10, 20, 4],
    tooltip: {
      borderColor: "red",
      borderWidth: 1.5
    }
  }]
};

### What is expected?
tooltip borderColor is red

### What is actually happening?
tooltip borderColor is not red

**Comment by susiwen8** [comment]
This issue has been fixed
