### ISSUE TITLE
[bug] heatmap in geo

### ISSUE THREAD

**Issue by alphabetabc** [apache/incubator-echarts#13894]
### Version
5.0.0

### Steps to reproduce
基于geo坐标系的热力图
```json
{
  "geo": {
    "map": "china",
    "roam": true
  },
  "visualMap": {
    "show": false,
    "min": 0,
    "max": 5,
    "inRange": {
      "color": [
        "blue",
        "blue",
        "green",
        "yellow",
        "red"
      ]
    }
  },
  "series": [
    {
      "type": "heatmap",
      "coordinateSystem": "geo",
      "geoIndex": 0,
      "data": [
        [
          120.14322240845,
          30.236064370321,
          1
        ],
        [
          120.14280555506,
          30.23633761213,
          1
        ],
        [
          120.14307598649,
          30.236125905084,
          1
        ],
        [
          120.14301682797,
          30.236035316745,
          1
        ],
        [
          120.1428734612,
          30.236160551632,
          1
        ],
        [
          120.14200215328,
          30.23595702204,
          1
        ],
        [
          120.14138577045,
          30.236113748704,
          1
        ],
        [
          120.1400398833,
          30.235973050702,
          1
        ],
        [
          120.13893453465,
          30.23517220446,
          1
        ],
        [
          120.1382899739,
          30.234062922977,
          1
        ]
      ],
      "pointSize": 5,
      "blurSize": 6
    }
  ]
}
```

### What is expected?
正常展示

### What is actually happening?
在4.9.0中正常展示
在5.0.0中报错  
![image](https://user-images.githubusercontent.com/29876424/103263551-27426a80-49e3-11eb-89e8-ce7a46bdd0e2.png)
Uncaught TypeError: coordSys.dataToRect is not a function
    at HeatmapView._renderOnCartesianAndCalendar (echarts.js:59155)  
    at HeatmapView.incrementalRender (echarts.js:59085)

**Comment by plainheart** [comment]
我测试了下，并未发现有报错的情况，https://www.makeapie.com/editor.html?c=x0-0jU_YJG&v=1
请检查是否正在使用按需引入导致少引了部分组件。

**Comment by alphabetabc** [comment]
> 我测试了下，并未发现有报错的情况，https://www.makeapie.com/editor.html?c=x0-0jU_YJG&v=1
> 请检查是否正在使用按需引入导致少引了部分组件。

---
这块是不是对数据长度有限制，我用了3200条数据，导致的报错，2999条都不会

**Comment by nelsonbbarriento23** [comment]
UOSLEN

**Comment by kirincc** [comment]
> > 我测试了下，并未发现有报错的情况，https://www.makeapie.com/editor.html?c=x0-0jU_YJG&v=1
> > 请检查是否正在使用按需引入导致少引了部分组件。
> 
> 这块是不是对数据长度有限制，我用了3200条数据，导致的报错，2999条都不会 @plainheart ![image](https://user-images.githubusercontent.com/29876424/103275123-692cda00-49fe-11eb-870f-f8e00d6dcc20.png)

你好，不知可否分享一下这个demo的源码？我使用v5版本，一直提示 There is a chart instance already initialized on the dom. 然后界面上未渲染出地图

**Comment by plainheart** [comment]
@kirincc  好像没加载 ECharts 的百度地图插件。这是为什么坐标系为 null 的原因。
```ts
import 'echarts/extension/bmap/bmap'
```
