### ISSUE TITLE
getDataURL not working on tree

### ISSUE THREAD

**Issue by kuige** [apache/incubator-echarts#13891]
### Version
5.0.0

### Reproduction link
[https://codepen.io/sange/pen/eYdygMX](https://codepen.io/sange/pen/eYdygMX)

### Steps to reproduce
Open the minimal reproduction link, scroll down and see a blank image.

### What is expected?
The image which src is the result of `getDataURL`, should not be blank.

### What is actually happening?
The image which src is the result of `getDataURL` is blank.

**Comment by plainheart** [comment]
It shouldn't call `getDataURL` immediately after `setOption` for the rendering is asynchronized.
Instead, we should listen to the [`finished`](https://echarts.apache.org/next/en/api.html#events.finished) event like this,
```js
myChart.on('finished', function() {
    img.src = myChart.getDataURL();
});
```
