### ISSUE TITLE
 Can you add contour map

### ISSUE THREAD

**Issue by Alexander-txj** [apache/incubator-echarts#13908]
### What problem does this feature solve?
Recently, I am doing industrial drawings, and I need to realize the contour map of the polar coordinate system. Finally, only d3-contour can be used. I think the application of contour map is still very extensive and can be put in echarts.

### What does the proposed API look like?
You can refer to Python Matplotlib

### like this
![image](https://user-images.githubusercontent.com/25924952/103340027-00a53200-4abe-11eb-8757-c0f789b154c6.png)
![image](https://user-images.githubusercontent.com/25924952/103340048-174b8900-4abe-11eb-88b1-e425a1c06cf1.png)
![image](https://user-images.githubusercontent.com/25924952/103340062-26323b80-4abe-11eb-8641-8f887d63aab6.png)

**Comment by nelsonbbarriento23** [comment]
🙏 🦾
