### ISSUE TITLE
Is there any way to import all the type definition of echarts5.0, etc, type definiation of TitleOption , SeriesOption$1? 

### ISSUE THREAD

**Issue by lcoder** [apache/incubator-echarts#13900]
### What problem does this feature solve?
I want to create my own echart component。It has some convenient feature. for example, simple series, simple title options。And the user don't need to care all the options which echarts provide。so the custom component need some type definition which the same with echarts。

We will copy the type definition in the echarts at the current version of echart(v5.0.0). Is any develop progress with these?

### What does the proposed API look like?
```jsx
import { EChartsOption, SeriesOption$1, GridOption } from 'echarts';

```

**Comment by plainheart** [comment]
Coming soon! See #13890 for more information.

**Comment by lcoder** [comment]
That's cool! I will close this issue.
