### ISSUE TITLE
【series-pie Issue】About setting top then radius changed

### ISSUE THREAD

**Issue by Deliti** [apache/incubator-echarts#13911]
### Version
4.7.0

### Steps to reproduce
```
series: [{
  type: 'pie',
  top: 'middle', 
  radius: ['50%', '70%']
}]
```

### What is expected?
render normal

### What is actually happening?
echarts will render pie smaller than before when set top to 'middle'

**Comment by pissang** [comment]
Try remove `top: 'middle'`

**Comment by Deliti** [comment]
> Remove `top: 'middle'`. It will affect the layout

But i want to change chart position, it worked on '4.2.1' version. How can i do that if removed top?

**Comment by pissang** [comment]
@Deliti `center` is designed to do this job. `top / right / bottom / left` is used to specify the viewport where the pie is put.

**Comment by Deliti** [comment]
> @Deliti `center` is designed to do this job. `top / right / bottom / left` is used to specify the viewport where the pie is put.

it worked, thank you very much.
