### ISSUE TITLE
3D曲面中关于列数必须是质数的现象

### ISSUE THREAD

**Issue by gaopengpian** [apache/incubator-echarts#13939]
我的目的是为了创建一个三维中的时间切片曲线。代码如下：
`
option = {
    tooltip: {},
    xAxis3D: {
        type: 'time'
    },
    yAxis3D: {
        type: 'value'
    },
    zAxis3D: {
        type: 'value'
    },
    grid3D: {
        viewControl: {
            // projection: 'orthographic'
        }
    },
    series: [{
        type: 'surface',
        data:[
            // 经测验，每行列数 17, 13，11，7，5，4，3，2 才能正常显示。
             // 第一行
              [Date.now(),0,0],
              [Date.now(),1,0],
              [Date.now(),2,0],
              [Date.now(),3,0],
              [Date.now(),4,0],
              [Date.now(),5,0],
              [Date.now(),6,0],
              [Date.now(),7,0],
              [Date.now(),8,0],
              [Date.now(),9,0],
              [Date.now(),10,0],
              [Date.now(),11,0],
              [Date.now(),12,0],
             
            // 第二行  
              [Date.now(),0,10],
              [Date.now(),1,1],
              [Date.now(),2,5],
              [Date.now(),3,10],
              [Date.now(),4,10],
              [Date.now(),5,12],
              [Date.now(),6,8],
              [Date.now(),7,10],
              [Date.now(),8,20],
              [Date.now(),9,10],
              [Date.now(),10,10],
              [Date.now(),11,30],
              [Date.now(),12,10],
        ]
    }
]
}

`
经测验，每行列数 17, 13，11，7，5，4，3，2 才能正常显示，其他列数都会出现异常重叠的情况，这是为什么。

**Comment by helgasoft** [comment]
bug confirmed in v.2.0.9, comment out two lines to go from 13 to 12 columns - surface becomes **deformed**.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=scatter3D-dataset&gl=1&code=PYBwLglsB2C8DeBYAUAAlQIgM4FMBOEOWGAXKgNorrpJrXoZgCeIOpmWArngGYCGAYzYAaKvUwATPmD7tKdcagD0S1Dwh4sYVHmAB3MeQAi0nADpo-gBQBKYQAYHAXVF1jpi9bsBGZ6_TuYOaWerbCAEx-hiZBnqF2AMzCqPYu0R4hYQAsUW4xwV7CAKy5AflxYQBspRTlmXYA7M6o_rUZhQAcNYEF8cIAnN11hd6Oqa09FT6-4-mx9cLekePoKqgCwAC2mzjQ2sCc2mAAFhBYqAA2ENA4qADE3gli9Gu4G9ASOvpzvWGOo2k8u0-r5vICysCwpEiuC2vNCkkARNhn0ckiflNiotwrDJgtqh1cSiwk10UD4X0uuFZuTfnZBmSIRSwqNFjSmXTFr4Euy4ZylmyXKtVBttrt9odUCczpdrrcHk8FNRYegAL5iWEYAAeAEEtWcEkY5BQnOhNUw9QajWRyCaza0MAAvS1YQ3G8im1CagDmBAkbptAU9ThQqqAA)
![image](https://user-images.githubusercontent.com/13038071/211142061-37d6b123-fcaa-455c-8bf0-127536645c8b.png)
