### ISSUE TITLE
echart5.0  tooltip内文字样式配置不生效了吗？例如：textStyle.color配置后不生效

### ISSUE THREAD

**Issue by lxynice** [apache/incubator-echarts#13934]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by bigbigqiang** [comment]
5.0 has bugs，Recommend to return 4.9

**Comment by susiwen8** [comment]
@bigbigqiang it has been fixed, will be released in 5.0.1.

**Comment by lxynice** [comment]
Well, when will version 5.0.1 be released

发送自 Windows 10 版邮件应用

发件人: susiwen8
发送时间: 2021年1月12日 17:01
收件人: apache/echarts
抄送: lxynice; Author
主题: Re: [apache/echarts] echart5.0 tooltip内文字样式配置不生效了吗？例如：textStyle.color配置后不生效 (#13934)

@bigbigqiang it has been fixed, will be released in 5.0.1.

**Comment by susiwen8** [comment]
@lxynice 5.0.1-rc  just  released this afternoon.
