### ISSUE TITLE
Stack-Bar handle exception with negative zero

### ISSUE THREAD

**Issue by xiaojia117** [apache/incubator-echarts#13944]
### Version
4.9.0

### Steps to reproduce
0. Use the official compiler to reproduce this problem ( It's still reproduce in version 4.9.0) ：https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category-stack

1. code with this:
option = {
    tooltip: {
        trigger: 'axis',
        axisPointer: {            // 坐标轴指示器，坐标轴触发有效
            type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data: ['bar1', 'bar2']
    },
    grid: {
        left: '0',
        right: '0',
        bottom: '3%',
        top: '50',
        containLabel: true,
    },
    xAxis: {
        type: 'category',
        data: ["type1", "type2", "type3", "type4", "type5"],
    },
    yAxis: [
        {
            name: '次',
            type: 'value',
        },
    ],
    series: [
        {
            name: 'bar1',
            type: 'bar',
            stack: '总量',
            barWidth: '18',
            label: {
                show: true,
                position: 'top',
                fontSize: 30,
            },
            data: [8, 6, 3, 0, 0],
        },
        {
            name: 'bar2',
            type: 'bar',
            stack: '总量',
            barWidth: 18,
            label: {
                show: true,
                position: 'bottom',
                fontSize: 30,
            },
            data: [-0, -2, -3, -5, -0],
        },
    ]
};

2. The leftmost bar chart will handle exception: negative zero will appear in the top half of y-axis

### What is expected?
negative zero will appear in the Lower half of y-axis

### What is actually happening?
negative zero is considered as zero and stuck to the top.

**Comment by SnailSword** [comment]
You can put the negative data in front of the positive data in series:

```
series: [
  {
    name: 'bar2',
    type: 'bar',
    stack: '总量',
    barWidth: 18,
    label: {
      show: true,
      position: 'bottom',
      fontSize: 30,
    },
    data: [0, -2, -3, -5, -0],
  },
  {
    name: 'bar1',
    type: 'bar',
    stack: '总量',
    barWidth: '18',
    label: {
      show: true,
      position: 'top',
      fontSize: 30,
    },
    data: [8, 6, 3, 0, 0],
  }
]
```

![image](https://user-images.githubusercontent.com/19756301/103666305-6eb29300-4faf-11eb-9778-2f15e2fde84c.png)

**Comment by xiaojia117** [comment]
> You can put the negative data in front of the positive data in series:
> 
> ```
> series: [
>   {
>     name: 'bar2',
>     type: 'bar',
>     stack: '总量',
>     barWidth: 18,
>     label: {
>       show: true,
>       position: 'bottom',
>       fontSize: 30,
>     },
>     data: [0, -2, -3, -5, -0],
>   },
>   {
>     name: 'bar1',
>     type: 'bar',
>     stack: '总量',
>     barWidth: '18',
>     label: {
>       show: true,
>       position: 'top',
>       fontSize: 30,
>     },
>     data: [8, 6, 3, 0, 0],
>   }
> ]
> ```
> 
> ![image](https://user-images.githubusercontent.com/19756301/103666305-6eb29300-4faf-11eb-9778-2f15e2fde84c.png)

solved，thanks
