### ISSUE TITLE
tooltip不消失，在快速滑动的情况下

### ISSUE THREAD

**Issue by jinjiaxing** [apache/incubator-echarts#13958]
### Version
5.0.0

### Steps to reproduce
在页面配置多个图形，鼠标快速左右滑动，tooltip不消失

### What is expected?
在鼠标离开图形区域应该自动消失

### What is actually happening?
tooltip不消失

**Comment by plainheart** [comment]
可以考虑监听 ECharts DOM 的 `mouseleave` 事件，手动派发 Action 隐藏。
```js
chart.dispatchAction({ type: 'hideTip' })
```

**Comment by jinjiaxing** [comment]
> 可以考虑监听 ECharts DOM 的 `mouseleave` 事件，手动派发 Action 隐藏。
> 
> ```js
> chart.dispatchAction({ type: 'hideTip' })
> ```

这类应该是比较通用的问题，最好能在库本身去解决比较好吧

**Comment by plainheart** [comment]
@pissang 好像看到好几个类似 `tooltip` 不消失的问题了，感觉应该是没有监听 `globalout` 事件导致的，是不是可以 enhance 一下？

**Comment by pissang** [comment]
@plainheart 嗯，在 5.0.1 里了

**Comment by jinjiaxing** [comment]
> @plainheart 嗯，在 5.0.1 里了

5.0.1 什么时间发布呢？
