### ISSUE TITLE
node build/build.js --watch  -> error: unknown option `--watch'

### ISSUE THREAD

**Issue by KrzysztofMadejski** [apache/incubator-echarts#13975]
### Version
5.0.0

### Steps to reproduce
https://github.com/apache/incubator-echarts/wiki/How-to-setup-the-dev-environment

### What is expected?
Project will build

### What is actually happening?
```
$node build/build.js --watch 
error: unknown option `--watch'
```

---
Was introduced during last two days, see https://github.com/apache/incubator-echarts/issues/13974

**Comment by pissang** [comment]
Sorry, it was just been replaced with `npm run dev` in https://github.com/apache/incubator-echarts/pull/13949. Thanks for the feedback
