### ISSUE TITLE
data/Source.ts  normalizeDimensionsOption 方法直接使用全局 name, 在微信小程序中报错 

### ISSUE THREAD

**Issue by ppbl** [apache/incubator-echarts#13983]
### Version
5.0.0

### Reproduction link
[https://github.com/apache/incubator-echarts/blob/master/src/data/Source.ts#L474](https://github.com/apache/incubator-echarts/blob/master/src/data/Source.ts#L474)

### Steps to reproduce
查看 data/source.ts 第474 行的代码，使用了全局的name（函数内部没有声明 name 变量）

### What is expected?
在微信小程序中使用不报错

### What is actually happening?
报错，name is not defined

---
这个 name 是不是不小心写错了？😂看起来也不像是要故意用全局的 name

**Comment by plainheart** [comment]
对比先前代码，感觉应该是 `item.name`。请 @100pah 帮助确认并修复一下。相关的 commit 是 https://github.com/apache/incubator-echarts/commit/bc1f8a0133b9b49ae24fab713c29350a271ad44f

**Comment by pissang** [comment]
@plainheart 我刚提交了修复，可以帮忙 review 一下
