### ISSUE TITLE
本地搭建echarts环境

### ISSUE THREAD

**Issue by chenleyiduo** [apache/incubator-echarts#13980]
### What problem does this feature solve?
没有网络或者网络较差的情况下能够流畅访问echart查看文档等。(目前未找到此解决方法，官网下载的都是echart包，本地启动不能看到页面）

### What does the proposed API look like?
期望能够有教程来说明怎么本地搭建。

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts-website

**Comment by chenleyiduo** [comment]
> https://github.com/apache/incubator-echarts-website

可以解决问题，谢谢

**Comment by mxy2316868975javascript** [comment]
> > https://github.com/apache/incubator-echarts-website
> 
> 可以解决问题，谢谢

如何在本地跑起来的, 可以加微信交流一下嘛
