### ISSUE TITLE
Safari浏览器中的Echarts5实例编辑框显示问题

### ISSUE THREAD

**Issue by KiviLin** [apache/incubator-echarts#13990]
### Version
5.0.0

### Steps to reproduce
官方示例中，Echarts5在Safari浏览器中随意打开一个，发现左侧示例编辑框中只能显示一行代码

### What is expected?
正常的左侧不应限制高度，在屏幕大小范围内，主题内容超过的时候显示滚动条

### What is actually happening?
内容最多只显示一行，超过的部分显示滚动条

**Comment by pissang** [comment]
谢谢反馈，已修复
