### ISSUE TITLE
echarts master分支源代码，执行npm run dev报错

### ISSUE THREAD

**Issue by fajiaopaopao** [apache/incubator-echarts#13995]
### Version
5.0.0

### Steps to reproduce
master 代码，执行npm run dev就能复现

### What is expected?
npm run dev正常

### What is actually happening?
控制台报错“Could not resolve "zrender/src/tool/parseXML"，所依赖的zrender 5.0.1 未导出该模块

**Comment by susiwen8** [comment]
please follow the wiki https://github.com/apache/incubator-echarts/wiki/How-to-setup-the-dev-environment
most likely you didn't use master branch of `zrender`
