### ISSUE TITLE
dataZoom后如何获取当前x轴0坐标对应的数据?

### ISSUE THREAD

**Issue by RuralHunter** [apache/incubator-echarts#1488]
当用户操作zoom后，如何能获取到当前x轴0坐标的数据的值，例如横坐标是日期，如何获得0点所代表的日期？现在的事件里没有这些数据，这个控件也没有提供相应的方法。

**Comment by longFeiLi** [comment]
拖动滚动条 。 试一试 mychart.component.xAxis.option.xAxis[0].data;   看是不是 你想要滴。

**Comment by RuralHunter** [comment]
可以了，的确是，多谢

**Comment by RuralHunter** [comment]
这个在3.0里应该怎么操作？mychart.component报“undefined”
