### ISSUE TITLE
Google Map integration

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#1666]
I've seen your Baidu map extension and was thinking if anyone has written extension for Google maps? If not, I can have a look on that..

**Comment by diysimon** [comment]
It's great if you can help us.

**Comment by mzy2240** [comment]
Any updates on this topic? I have seen echarts with mapbox/leaflet, it will be awesome if the google maps/earth/openstreetmap can be integrated.

**Comment by byezgi-esq** [comment]
I see that this issue is closed without an explanation. Could you please answer the original query?

**Comment by plainheart** [comment]
Hi all, here is an extension package for integrating google maps. [echarts-extension-gmap](https://github.com/plainheart/echarts-extension-gmap)
