### ISSUE TITLE
如何通过事件控制markpoints的显示和隐藏？

### ISSUE THREAD

**Issue by seifer08ms** [apache/incubator-echarts#1886]
如何通过事件控制地图series下markpoints的显示和隐藏？
还有如何在地图上显示省的时候，名称是另外自己指定的名称，比如省会城市？谢谢！

**Comment by Ovilia** [comment]
在事件处理的函数里用 `setOption` 设置 `markPoint` 为 `undefined` 试试。

名字可以通过 `label` 的 [`formatter`](http://echarts.baidu.com/doc/option.html#title~series-i(line).itemStyle.normal.label.formatter) 实现。具体思路是，定义一个键值对的对象，键是默认的名称如“广东”，值是你要指定的名称如“广州”。`formatter` 例子参见 http://echarts.baidu.com/doc/example/tooltip.html

**Comment by longFeiLi** [comment]
1.可以动态去addMarkPoint  和 delMarkPoint

**Comment by seifer08ms** [comment]
谢谢，label显示省会已经搞定了，但如果还想用省会的数据显示在省上面呢？我找了半天没发现一个合适的属性调用函数 @Ovilia

**Comment by jackchoumine** [comment]
> 谢谢，label显示省会已经搞定了，但如果还想用省会的数据显示在省上面呢？我找了半天没发现一个合适的属性调用函数 [@Ovilia](https://github.com/Ovilia)

<img width="1193" height="600" alt="Image" src="https://github.com/user-attachments/assets/babcdab6-093b-4798-9a6c-91e1c38a3468" />


我的图表原型，折线上的 markPoint 太密了，希望横坐标的滑块滑动到一个小范围时，才显示 markPoint，使用的是 echart 5.x.x 版本，如何实现呢？
