### ISSUE TITLE
希望提供各类图形在数据装载完成，并完成初始化动态效果后的，统一触发事件

### ISSUE THREAD

**Issue by rufushuang** [apache/incubator-echarts#1906]
目前用来做批量截为静态图片等需求的时候，需要有一个在页面已经完全静止的时间点，去截图
是否有能有这个统一触发事件？

现在貌似力导向图有
on FORCE_LAYOUT_END
能不能实现所有图形种类的
on RENDER_END
?

**Comment by rufushuang** [comment]
https://github.com/ecomfe/echarts/issues/429
之前被关闭的类似issue，但实际上并没有这个issue中提到的on 'finish' 这个事件

**Comment by whyer11** [comment]
+1
