### ISSUE TITLE
echarts 生成的图表，在使用wkhtmltoimage 转换成图片的问题

### ISSUE THREAD

**Issue by greatmoon** [apache/incubator-echarts#2006]
echarts 生成的图表 ，无法用wkhtmltoimage 转换成图片
wkhtmltoimage  --enable-javascript   --debug-javascript --javascript-delay 1200 'http://echarts.baidu.com/doc/about.html' a.jpg   生成的图片是 是空白页；

而其他的js 插件例如ichart 就可以
wkhtmltoimage  --enable-javascript   --debug-javascript --javascript-delay 1200 'http://www.ichartjs.com/samples/index.html?page=column2d_01.html&pageno=2' a.jpg

应用场景是服务端自动生成图表的快照。
开发人员能帮看看吗？

**Comment by stanleyxu2005** [comment]
你得确保wkhtmltoimage支持网页中的canvas。Echarts是画在canvas上的。

**Comment by greatmoon** [comment]
多谢回复。
同样基于canvas之上的ichart（ http://www.ichartjs.com/ ）可以。
之前是基于echart做的

**Comment by lnmpzkang** [comment]
@greatmoon 我也遇到了跟你同样的问题，echarts的页面wkhtmltoimage转化的图片为空白图，请问你的问题解决了么？
