### ISSUE TITLE
有echarts的渲染load成功的回调函数接口吗？如何判断数据展示图load完毕？官方的load例子用的时间控制？

### ISSUE THREAD

**Issue by longzhiwuing** [apache/incubator-echarts#2035]

**Comment by pissang** [comment]
大部分图表 setOption 后就直接绘制出来了。但是有几个例外，1. 图表中有需要异步加载的图片，这个没有事件。2. 力导向图的布局是需要多帧内完成，这个有一个布局完成的事件 `FORCE_LAYOUT_END`。

如果你说的是异步加载的数据的话，这个异步加载是你自己控制的，load 事件你也可以自己监听
