### ISSUE TITLE
雷达图极坐标的axisLable问题

### ISSUE THREAD

**Issue by coralbells** [apache/incubator-echarts#2201]
对单个indicator item设置axisLabel 的show 为true， 整个图都不显示了
option = {
    title : {
        text: '罗纳尔多 vs 舍普琴科',
        subtext: '完全实况球员数据'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        x : 'center',
        data:['罗纳尔多','舍普琴科']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,

```
polar : [
    {
        indicator : [
            {text : '1', max: 100,
                axisLabel: {
                       show: true,
                       color: '#ccc'
                  }
            },
            {text : '5', max: 100},
            {text : '4', max: 100},
            {text : '3', max: 100},
            {text : '2', max: 100}
        ]
    }
],
series : [
    {
        name: '完全实况球员数据',
        type: 'radar',
        itemStyle: {
            normal: {
                areaStyle: {
                    type: 'default'
                }
            }
        },
        data : [
            {
                value : [36,85, 47, 60, 12],
                name : '舍普琴科',
              symbol: 'star5',
                symbolSize: 0        // 可计算特性参数，空数据拖拽提示图形大小

            }]
    },
  {
      name: '完全实况球员数据2',
        type: 'radar',
    data:[
            {
                value : [47, 29, 6, 26, 85],
                name : '罗纳尔多'
            }
        ]
    }
]
```

};

**Comment by coralbells** [comment]
如果设成false， 图表显示没问题

**Comment by R-River** [comment]
同问此情况
请问楼主解决问题了吗？

**Comment by liuzetan314** [comment]
axisLabel没有color属性 ，有textStyle可以设置颜色。
axisLabel:{
  show: true,
  textStyle:{
   color: '#ccc'
 }
}
可以写成这样

**Comment by zhyc18123** [comment]
还是不行，报错了。TypeError: axisModel.getCategories is not a function
