### ISSUE TITLE
Get a axis values when data zoomed

### ISSUE THREAD

**Issue by Yurius-tokyo** [apache/incubator-echarts#2210]
I'm using Echarts with dataZoom option. I want to get a start and end Xaxis value when user zoomed chart Xaxis in bar chart.

It seems I should use "valueAxis" and "getExtremum" function but I couldn't get how exactly use it. I hope to show me how I should write the code.

``` js
require.config({
    paths: {
        echarts: 'assets/global/plugins/echarts/'
    }
});
require(
    [
        'echarts',
        'echarts/chart/bar'
    ],
var chart = ec.init(document.getElementById('chart'));
chart.setOption({...});
```

**Comment by talatbaig** [comment]
Hi,
Did you figure this out, I'm also interested in working out how to do this
