### ISSUE TITLE
类目型的 y 轴在配置 name 的情况下会出现第一个和最后一个刻度标签向内挤的问题

### ISSUE THREAD

**Issue by WeiFei365** [apache/incubator-echarts#2221]
比如，这个官网的案例：[http://echarts.baidu.com/doc/example/bar3.html](http://echarts.baidu.com/doc/example/bar3.html)

在 yAxis 中加 name，比如这样：

``` js
yAxis: [
    {
        type : 'category',
        name: '类别',
        data : ['巴西','印尼','美国','印度','中国','世界人口(万)']
    }
]
```

那么，世界人口（万）就会向下偏移、巴西会向上偏移

**Comment by WeiFei365** [comment]
研究了下，发现echarts之所以偏移的意图是：
* 当刻度标签和刻度线在同一水平线时（也就是 boundaryGap=true），可以保证第一个和最后一个标签在刻度线的内侧，
* 但是当他们不在同一水平线时（也就是 boundaryGap=false），那这种偏移就不应该再需要了

**Comment by chen-xiao-yu** [comment]
额，也遇到了这个问题，关键作为用户来说，不想让他偏移，有解决办法么

**Comment by chen-xiao-yu** [comment]
axisLabel:{
                                textStyle:{
                                    baseline:'middle'
                                }
                            },
尝试设置了一下这个值， 这样是不会挤在一起了，但是都是向上偏移，不会居中， 感觉baseline没效果一样，设置为bottom,top,middle效果都一样
