### ISSUE TITLE
Line chart的y轴支持相同的双轴吗

### ISSUE THREAD

**Issue by stanleyxu2005** [apache/incubator-echarts#2315]
我就一组数据，但就是想同时在左右两侧各显示一根y轴，可以做到吗？

**Comment by pissang** [comment]
可以的，但是得强制设定 `min` 和 `max`

**Comment by stanleyxu2005** [comment]
Got it. Can it be more easy to support dual y-axis in 3.0?

**Comment by pissang** [comment]
这个逻辑 3.0 和 2.0 一样，是否有更好的建议 :)

**Comment by stanleyxu2005** [comment]
我是希望options里面可以直接设置类似yAxis[0].position = ['left', 'right']; 
如果不用数组的话，可以提供left/right/both作为选择。

我记得之前有个讨论是不止2根y轴，是一个做电影院项目的兄弟发起的。当时好像是说做不了。如果每个yAxis是可以设置position了，那么也就合理了。

一般我们最多会放2根不同的y轴。我们可以理解成：
yAxis[0].position = ['left'];
yAxis[1].position = ['right'];

**Comment by pissang** [comment]
现在是单个 yAxis 组件只显示一个轴，感觉设成 `position: both` 还挺容易混淆的。

现在如果要单个系列双轴比较麻烦的应该是在左边轴的刻度是自动计算的时候很难通过设置 `min` `max` 来保证右边轴的刻度同步？

**Comment by mmzhi** [comment]
@stanleyxu2005 @pissang 按照之前你建议的方法，我已经自己构建出多轴功能了，效果如下图：
<img width="1049" alt="2015-12-31 11 18 43" src="https://cloud.githubusercontent.com/assets/1845381/12060702/66c17b92-afb0-11e5-9ace-3809fd16e336.png">

不过关于题主的问题，我也有同样的问题的
<img width="535" alt="2015-12-31 11 21 08" src="https://cloud.githubusercontent.com/assets/1845381/12060721/be9a6d2e-afb0-11e5-8b2c-01cfbfb95419.png">
比如上图中，右边的Y轴其实就是左边的占比，但不能同时显示两条轴，所以我只能单独画一条线

**Comment by stanleyxu2005** [comment]
谢谢提供通过min/max方式计算的思路。
我觉得这个不应该是计算上的问题，而在echart的渲染上。因为需求是希望左右对称，显示相同的内容。
