### ISSUE TITLE
echart 3 热力图如何使用直角坐标系

### ISSUE THREAD

**Issue by Pengran** [apache/incubator-echarts#2378]
请问最新echarts 3 的热力图如何使用直角坐标系。
例子里面没有。能不能给个一个？谢谢。

在另外一个帖子里面，说 3 里新加了笛卡尔坐标系上的热力图
https://github.com/ecomfe/echarts/issues/2273

**Comment by pissang** [comment]
http://echarts.baidu.com/demo.html#heatmap-cartesian

**Comment by Pengran** [comment]
我看到这个了，但是我要的不是这样的网状图。是模糊边界的热力图＋直角坐标系。
比如这样
![image](https://cloud.githubusercontent.com/assets/1345951/12320275/1489bdb4-baa8-11e5-872b-e8d04bf24b42.png)

**Comment by pissang** [comment]
那暂时还不支持
