### ISSUE TITLE
迁徙图多地迁到同一个地方，数值无法改为显示在出发地

### ISSUE THREAD

**Issue by Henrietta** [apache/incubator-echarts#2395]
请教下
   想做一个迁入图，如 各地到北京 ，数值显示在出发地如何处理，目前数值都只能显示在目的地，无法转移显示到出发地。
![image](https://cloud.githubusercontent.com/assets/7380126/12325883/2b6c2926-bb08-11e5-9d1b-95532fd34003.png)

**Comment by momo898821** [comment]
markline箭头指向北京，用它的value值显示数据，效果这样的
![image](https://cloud.githubusercontent.com/assets/14818687/12776039/a426463c-ca8d-11e5-8940-85614ef2ae5f.png)

**Comment by lidongpengde** [comment]
问题解决了吗，我也遇到了这个问题
