### ISSUE TITLE
echarts 3.0 如何使用svg

### ISSUE THREAD

**Issue by sztinq** [apache/incubator-echarts#2398]
在2.0下通过如下使用自建的svg图：
require('echarts/util/mapData/params').params.line = {
                        getGeoJson: function (callback) {
                            $.ajax({
                                url: "/static/echarts/svg/line.svg",
                                dataType: 'xml',
                                success: function (xml) {
                                    callback(xml)
                                }
                            });
                        }
                    };
以上，在3.0下如何使用，请指教，谢谢！

**Comment by shanjixiaboss** [comment]
不明觉厉，我现在用svg还是用path去弄的。。。

**Comment by kevin830222** [comment]
找不到 +1 , 請指教！

**Comment by yangpu** [comment]
+1
