### ISSUE TITLE
地图多组数据但没有累计

### ISSUE THREAD

**Issue by AngusFu** [apache/incubator-echarts#2480]
以这个为例[http://echarts.baidu.com/demo.html#map-china-dataRange](http://echarts.baidu.com/demo.html#map-china-dataRange)。左侧标注的iPhone3、4、5同时选中，但省份tooltip的数据，却并不是这个三种的总和。

**Comment by SuperZDev** [comment]
@AngusFu 这个应该是个BUG。
@pissang 并附上2.x的示例：http://echarts.baidu.com/echarts2/doc/example/map1.html
