### ISSUE TITLE
the first series bar label will be cut by the second series bar if the label is very long

### ISSUE THREAD

**Issue by Jessie-feng** [apache/incubator-echarts#2490]
![Uploading cove.png…]()

**Comment by Jessie-feng** [comment]
1.  new a charts, 2 bar;
2.  let the first bar's label show=true, let the first series value have many character, and the value < second bar;
3. check the first bar's label, found part of the label was cut by the second bar.

**Comment by SuperZDev** [comment]
@Jessie-feng 方便提供一下option吗？还有这里可以用中文。

**Comment by Jessie-feng** [comment]
哇，有人回应了，您稍等，我马上把option 抽出来

**Comment by Jessie-feng** [comment]
[bugOptions.txt](https://github.com/ecomfe/echarts/files/101858/bugOptions.txt)

**Comment by Jessie-feng** [comment]
[bugOptionsUpdated.txt](https://github.com/ecomfe/echarts/files/101861/bugOptionsUpdated.txt)

**Comment by Jessie-feng** [comment]
@SuperZDev 天使您好，option已经提供，不确定这是不是bug, 但是暂时没有找到解决方法, 希望能得到您的帮助，谢谢。

**Comment by SuperZDev** [comment]
@Jessie-feng  确实有这样的问题，不过你可以通过调整【barGap:10】柱间间距来规避这个问题，目前估计不会去修改这个事情。

**Comment by Jessie-feng** [comment]
@SuperZDev , 设了barGap以后， 如果类目比较多，柱子太分散，影响分组的效果，并且barGap的值是固定的，如果label value 很大的话还是有可能被盖住。 不知还有没有其他的好方法。

**Comment by SuperZDev** [comment]
据我所知，应该没了。不过，这种数据比较长的不应该是移动上去让tooltip帮他显示吗？明天我帮你看看能不能扩展一下，还有你试过用3.x版本可以吗？

**Comment by Jessie-feng** [comment]
@SuperZDev ,3.x的我还没试过，我试下看看

**Comment by Jessie-feng** [comment]
@SuperZDev， 数据比较长是相对来说的，如果类目比较多，bar 的宽度就自动变窄，所以数据相对bar width很容易显得比较长

**Comment by Jessie-feng** [comment]
@SuperZDev， 试了下用这里下载的包没有加载成功，对js模块引用不熟悉，明天问下其他同事怎么用3.x

**Comment by Jessie-feng** [comment]
@SuperZDev， 请教：
原来我这边html页面加载echarts是安装百度文档里说的“模块化单文件引入”方式， 例如最简单的Bar chart 只用到了echarts.js, bar.js 。
用3.x的话，是直接用这里zip包里的dist/echarts.js, src/chart.bar.js替换就可以了吗？我直接替换后html display error: require is not defined.  希望能指点1，2， 谢谢！

**Comment by SuperZDev** [comment]
https://github.com/ecomfe/echarts/issues/2505

**Comment by Jessie-feng** [comment]
@SuperZDev，您好，3.x版本运行成功，但是这个问题依然存在。

**Comment by Jessie-feng** [comment]
![echarts3x](https://cloud.githubusercontent.com/assets/8412537/12577766/956e9bb2-c457-11e5-8268-6ce11fc89afe.png)

**Comment by pissang** [comment]
label 的 position 设置成 `'insideRight'` 试试

**Comment by SuperZDev** [comment]
@pissang 这几个属性都不可以。

**Comment by Jessie-feng** [comment]
@pissang ， position： 'insideRight' 试过了，没有变化。

**Comment by Jessie-feng** [comment]
![birtchart](https://cloud.githubusercontent.com/assets/8412537/12601406/c2fb143c-c4db-11e5-94ac-4c1e12b90028.png)

**Comment by Jessie-feng** [comment]
期望的效果大概是这样的，不知能否做到。

**Comment by pissang** [comment]
好像是有这问题，后续优化

**Comment by Jessie-feng** [comment]
@pissang ，好，谢谢，期待......

**Comment by Ovilia** [comment]
http://echarts.baidu.com/examples/editor.html?c=bar-label-rotation 目前已支持 `label.rotate`。
