### ISSUE TITLE
当在一个区域显示多个省份的地图的时候，缩放以及拖动，会卡住不动

### ISSUE THREAD

**Issue by fws407296762** [apache/incubator-echarts#2502]
![map](https://cloud.githubusercontent.com/assets/2639476/12545059/fde99bc6-c379-11e5-8832-66bff8e090a1.png)
像上面图片中，省份地图，缩放+拖动的时候，会有很大的几率出现卡顿，不管怎么动都动不了了。

**Comment by zhump** [comment]
是的
