### ISSUE TITLE
为什么ECharts 3的示例中都没有动态交互效果,visualMap和Legend都没有交互动作和筛选反应呢？

### ISSUE THREAD

**Issue by hanhui** [apache/incubator-echarts#2547]

**Comment by pissang** [comment]
麻烦具体描述一下环境，怎么复现这个问题

**Comment by yangpu** [comment]
#2528 WIN10下面Chrome下面Echarts 3.0有BUG。

**Comment by hanhui** [comment]
为方便起见以下相同回复在GITHUB中同样给出：
操作系统为WIN10，64位。使用WIN的Edge浏览器、IE11浏览器和Chrome浏览器都没有交互动作和反应，另外也发现在最新火狐浏览器下有交互动作和反应但是下载图片（toolbox）无效。





在 2016-01-31 11:45:20，"Yi Shen" <notifications@github.com> 写道：


麻烦具体描述一下环境，怎么复现这个问题
