### ISSUE TITLE
how i do wordCloud in echarts 3.0.2 ?

### ISSUE THREAD

**Issue by HedCET** [apache/incubator-echarts#2573]
i tried echarts 2.\* example with echarts 3.0.2 gives me this error

`Component series.wordCloud not exists`

how i do [this](http://echarts.baidu.com/echarts2/doc/example/wordCloud.html) using echarts 3.0.2 ?

pls help

**Comment by sujith3g** [comment]
:+1:

**Comment by HedCET** [comment]
@sujith3g did u find any alternatives ?

**Comment by pissang** [comment]
Sorry, wordCloud is not supported yet in v3.0.2

**Comment by qianxinxu** [comment]
error：Component series.wordCloud not exists.  How can i do?
