### ISSUE TITLE
散点地图的tooltip中显示地理坐标和数据，怎样不显示地理坐标

### ISSUE THREAD

**Issue by silver329** [apache/incubator-echarts#2590]
在http://echarts.baidu.com/demo.html#scatter-map 这个例子里的tooltip中。。。显示了地理坐标，和数据。我想只显示城市名和数据就好。。。该怎么解决？我试了些方法。。。但因为我是个代码小白。。。并有解决= =
所以求大神帮帮忙哈O(∩_∩)O

**Comment by chaegumi** [comment]
#2583 同这个

**Comment by wangjunji** [comment]
同问，试了
`
 tooltip: {
            formatter: '{b}:{c2}'
 }
`
不管用

**Comment by chaegumi** [comment]
@wangjunji 大写的服，http://echarts.baidu.com/demo.html#scatter-map 现在这个示例里边不就是只显示城市名和数据了吗。

```javascript

    tooltip: {
        trigger: 'item',
        formatter: function (params) {
            return params.name + ' : ' + params.value[2];
        }
    },

```
