### ISSUE TITLE
如何在chrome插件中使用

### ISSUE THREAD

**Issue by ganzhexiaowangzi** [apache/incubator-echarts#2628]
我将实例放在自己开发的chrome插件中，无法显示出来。
下载了echarts.min.js，包含所有组件。popup.html中为实例的代码。permission中添加了echarts.baidu.com

**Comment by pissang** [comment]
请描述具体点

**Comment by hanyangecho** [comment]
我感觉他说的是timeline.js被一些广告过滤插件禁止下载了

**Comment by ganzhexiaowangzi** [comment]
我想问题应该是出在require(['echarts', 'echarts/chart/force', 'echarts/chart/chord'], ...)，无法正常加载进来，添加content_security_policy也不行。
