### ISSUE TITLE
3.1.1版本lengend有title属性吗？或者鼠标移动事件？

### ISSUE THREAD

**Issue by jeatime6** [apache/incubator-echarts#2636]
如果没有，可以考虑添加吗？TKS

**Comment by 100pah** [comment]
直接使用 <http://echarts.baidu.com/option.html#title> 不知是否能解决你的问题。
如果不行的话，请描述具体点您的需求是啥

**Comment by jeatime6** [comment]
@100pah 非常感谢你的回答，我想要的title不是图例的title；
其实就是legend上加备注信息，鼠标移上去显示备注信息；和div的title属性一样。

**Comment by 100pah** [comment]
目前 `legend` 没有支持 `tooltip`。
鼠标移动到legend上时会触发的事件只有 `highlight` 事件。
但是其中没有位置信息，所以可以实现『hover到legend上时，在某个固定位置显示提示信息』。

```javascript
chart.on('highlight', function () {
    console.log('asdf');
})
```

**Comment by jeatime6** [comment]
@100pah 非常感谢！
