### ISSUE TITLE
toolbox 重置icon，显示异常，排版错乱，icon没有出现

### ISSUE THREAD

**Issue by BruceCham** [apache/incubator-echarts#2646]
toolbox 重置icon，显示异常，排版错乱，icon没有出现

**Comment by zhump** [comment]
有简单的例子吗？发一下配置，v3还是v2请描述清楚。

**Comment by brucecham** [comment]
@zhump 
![qq 20160225164909](https://cloud.githubusercontent.com/assets/7899194/13314360/c4d1ee0a-dbdf-11e5-9665-d988f14a0582.png)
![qq 20160225164915](https://cloud.githubusercontent.com/assets/7899194/13314361/c5fab47e-dbdf-11e5-9494-9b0365c329b2.png)

**Comment by zhump** [comment]
Icon 的 path 字符串，ECharts 3 中支持使用自定义的 svg path 作为 icon
http://echarts.baidu.com/option.html#toolbox.feature.restore.icon

**Comment by brucecham** [comment]
@zhump 
2.x里面有个扩展的myTool功能，现在是去掉了么？
漏斗与饼图的图形切换也去掉了吗？
