### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by macing** [apache/incubator-echarts#2661]
<img width="381" alt="2016-02-25 13 04 41" src="https://cloud.githubusercontent.com/assets/14910958/13310360/5f47e022-dbc0-11e5-8197-5617a34bcda0.png">

知道各位开发人员很忙，所以这些需求权当用户的一点心声。
没有没事，如果有，相信可以造福全球的用户。

http://www.highcharts.com/demo/gauge-activity/dark-unica
http://www.highcharts.com/demo/pyramid
http://www.highcharts.com/demo/funnel
http://www.highcharts.com/demo/polar-spider

**Comment by pissang** [comment]
后面三个 echarts 里都有

**Comment by macing** [comment]
谢谢 @pissang ，下面说一些我的一些看法。

后面的三种我也都有尝试配置，但是落脚点略有不同。

1.金字塔图：这里的想法是塔的形状不变，通过改变每一层的厚度（or 面积？）来达到相关目的的视觉呈现。金字塔是两层作用：高低层级和每一层级的数量。如果仅是象征性显示层级，没有数量显示，那可能用图表的方式就没有优势了，因为 Keynote 或者 Pages 就可以做了。

2. 漏斗图：跟上面差不多，不过这里就不一定跟金字塔图那样要求多。目前的方式是调整上边缘的宽度，也不错；漏斗形状不变，改变厚度（or 面积？）来表明过滤这一视觉特征也是一种选择。

3. ECharts 3 雷达图的坐标线是全圆形（需要多边形）的，这样做会造成无法看到相邻值是否大于还是小于标准轴线（因为是弧线，是不准的）。

**Comment by pissang** [comment]
了解了，谢谢建议

**Comment by rain-yu** [comment]
@pissang 你好我想知道echarts怎么配置pyramid图表
