### ISSUE TITLE
tooltip的trigger设置为‘item’时，只能显示label对应的点

### ISSUE THREAD

**Issue by orisnas** [apache/incubator-echarts#2666]
trigger设置为‘axis’，可平滑取点显示。设置为‘item’，则只能显示label处对应的点。
当有多组数据时，‘axis’会显示该横坐标处所有纵坐标的值，我只希望取鼠标所在点的值，如何做到？
谢谢

**Comment by haoflynet** [comment]
有人解决了吗？
