### ISSUE TITLE
当xAxis为value时，yAxis为category时visualMap失效

### ISSUE THREAD

**Issue by orisnas** [apache/incubator-echarts#2674]

**Comment by pissang** [comment]
能否具体描述问题？

**Comment by orisnas** [comment]
`option = {
    xAxis : [
        {
            type : 'category',
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    visualMap:{min:300,max:400},
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            type:'bar',
            data:[320, 332, 301, 334, 390, 330, 320]
        }
    ]
};
`
这样可以显示颜色渐变效果
![image](https://cloud.githubusercontent.com/assets/17471583/13346411/08c60b16-dca1-11e5-9265-f9262a5ad299.png)

`option = {
    yAxis : [
        {
            type : 'category',
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    visualMap:{min:300,max:400},
    xAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            type:'bar',
            data:[320, 332, 301, 334, 390, 330, 320]
        }
    ]
};
`
这样则不可以
![image](https://cloud.githubusercontent.com/assets/17471583/13346432/245ab714-dca1-11e5-8c76-859daea14b33.png)

**Comment by pissang** [comment]
设置 visualMap 的 dimension

**Comment by dreamerhammer** [comment]
如果同时存在map和bar两个series，设置dimension无法同时满足两个要求怎么处理？
