### ISSUE TITLE
markLine的颜色如何自定义？

### ISSUE THREAD

**Issue by liekkas** [apache/incubator-echarts#2679]
我看文档[markLine](http://echarts.baidu.com/option.html#series-line.markLine.lineStyle.normal.color)下有lineStyle>normal>color 来设置线条颜色，但是我设置了颜色没起作用，请教如何更改线条颜色呢？
可以用官方的[例子](http://echarts.baidu.com/demo.html#bar-stack)快速实验下

**Comment by zhump** [comment]
好好的 没有问题。
![eeeee](https://cloud.githubusercontent.com/assets/7962067/13371168/83de3922-dd5a-11e5-8365-e090faae6228.png)

**Comment by liekkas** [comment]
晕了~放错位置了，多谢

**Comment by liekkas** [comment]
还是有问题，线的两端颜色怎么设置？
