### ISSUE TITLE
Chrome50 创建多个图标和缩放时会有奇怪的错误

### ISSUE THREAD

**Issue by simon300000** [apache/incubator-echarts#2682]
## 发现官方demo也有这个问题, 原因应该是我升级Chrome造成的

![screen shot 2016-02-28 at am6 4 6](https://cloud.githubusercontent.com/assets/12656264/13375692/437b838a-dde1-11e5-921f-0894b26c396e.png)
### 原因发现: 不知道Chrome新版本改了啥...

亲测Safari就没事

50.0.2661.0 (Official Build) canary (64-bit)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.0 Safari/537.36
会出现这个问题
## 原内容

创建第四个图表的时候console会这样报错
![screen shot 2016-02-28 at am4 40 5](https://cloud.githubusercontent.com/assets/12656264/13375241/817e32a6-ddd5-11e5-9ad8-2a8fab5a3534.png)

然后每次创建就会有如下错误
我也不知道怎么回事...

![screen shot 2016-02-28 at am4 45 26](https://cloud.githubusercontent.com/assets/12656264/13375321/db920208-ddd6-11e5-90e4-46bf7367f0e2.png)

这是我的用来创建的代码

```
{
    "title": {
        "text": "历史在线"
    },
    "toolbox": {
        "feature": {
            "dataZoom": {
                "yAxisIndex": false
            },
            "saveAsImage": {
                "pixelRatio": 4
            }
        }
    },
    "tooltip": {
        "trigger": "axis",
        "hideDelay": 500,
        "formatter": "{b}<br>{c}"
    },
    "xAxis": {
        "data": ["测试", "测试", "测试", "测试", "测试", ]
    },
    "yAxis": {},
    "dataZoom": [{
        "type": "slider",
        "start": 0,
        "end": 100
    }, {
        "type": "inside",
        "start": 0,
        "end": 100
    }],
    "series": {
        "name": "玩家",
        "type": "line",
        "data": [1, 2, 3, 4, 5],
        "smooth": true,
        "markLine": {
            "data": [{
                "name": '平均',
                "type": 'average'
            }],
            "animationEasing": 'cubicInOut'
        }
    },
    "animationEasing": 'backInOut'
}
```

有时第四个报错如下图,然后剩下的第五个是最上面的图,第六个以及之后的又是第二个图
![screen shot 2016-02-28 at am4 58 53](https://cloud.githubusercontent.com/assets/12656264/13375365/1bc67664-ddd8-11e5-86cc-a3b89c11a541.png)

只有重新载入一下
比如

```
var element = document.createElement("script");
element.src = "js/echarts.min.js";
document.body.appendChild(element);
```

才可以继续正常使用

还有的时候放大缩小什么的,也会出问题(鼠标滚轮)
![screen shot 2016-02-28 at am5 49 10](https://cloud.githubusercontent.com/assets/12656264/13375601/222c3bf4-dddf-11e5-8b0b-77d4651260be.png)

**Comment by pissang** [comment]
谢谢反馈，目前测下来猜测应该是新版本的 chrome canary 在优化 for in 的代码是出现了错误，导致坐标系创建失败了。

**Comment by 100pah** [comment]
应该是chrome canary 中 function optimize 的问题。
已向chromium提issue，参见：
<https://bugs.chromium.org/p/chromium/issues/detail?id=590989>

**Comment by insekkei** [comment]
なるほど。。。。。。

**Comment by simon300000** [comment]
www

发自我的 iPhone
