### ISSUE TITLE
环图在ie8上显示及实时刷新的问题

### ISSUE THREAD

**Issue by oNexiaoyao** [apache/incubator-echarts#2718]
要做的效果
![image](https://cloud.githubusercontent.com/assets/17607868/13485015/28ebc894-e13e-11e5-8e84-23f3ecc711b9.png)
在ie8上出现的情况
![image](https://cloud.githubusercontent.com/assets/17607868/13485026/4075f2c8-e13e-11e5-888e-50ebd729335e.png)
 在ie8上获取实时数据刷新的结果
![image](https://cloud.githubusercontent.com/assets/17607868/13485056/79e35780-e13e-11e5-8da1-4856d6562482.png)
而且ie8上提示框没有效果了 背景是透明的

**Comment by Hongmei225** [comment]
最近的echart （v3.1.10 on 19/05/2016）已经解决这个问题了。
