### ISSUE TITLE
希望增加特性，当dataZoom控制多个折线图的x轴时，鼠标移动可同时显示这些x轴所属grid的tooltip

### ISSUE THREAD

**Issue by netwww1** [apache/incubator-echarts#2723]
效果类似echarts2里，通过connect方法连接后的多图联动，但connect方法需要多个div实现多图，而3的话，原本就能做到单个div中多图联动，但问题在于tooltip只显示在当前鼠标移动所在的grid中。

**Comment by caizhenxing** [comment]
这个特性很实用啊，什么时候能合并啊
