### ISSUE TITLE
关系图中，两点之间不能画不同曲度的划线，都重叠在一起了

### ISSUE THREAD

**Issue by dragonsayok** [apache/incubator-echarts#2729]
http://echarts.baidu.com/demo.html#graph
关系图中，两点之间不能画不同曲度的划线，都重叠在一起了。制造两个点之间有多条线，显得曲度不同，但是没有分别画出

**Comment by pissang** [comment]
可以每个数据分别设置 `lineStyle.normal.curveness`

**Comment by dragonsayok** [comment]
我是每个数据分别设置的，例如：
var p = {
        label: '北京',
        topoid: '1',
		id:'1',
        x:112.1265,
        y:23.5822,
        size:10
    };
    var p1 = {
        label: '南京',
        topoid: '0',
		id:'0',
        x:120.4651,
        y: 36.3373,
        size:10
    };
	var p2 = {
        label: '上海',
        topoid: '2',
		id:'2',
        x:220.4651,
        y: 136.3373,
        size:10
    };
 
graph.nodes.push(p);
graph.nodes.push(p1);
graph.nodes.push(p2);

    var xxl={
        id:'0',
        source:'1',
        target:'2',
		 lineStyle: {
						normal: {
							color:'#ffff',
							width:10,
							curveness: 0.9
						}
					}
    };
graph.links.push(xxl);
 var xx2={
        id:'1',
        source:'1',
        target:'2',
		 lineStyle: {
						normal: {
							color:'#ffff',
							width:10,
							curveness: 0.1
						}
					}
    };
graph.links.push(xx2);
var xx3={
        id:'1',
        source:'0',
        target:'2',
		 lineStyle: {
						normal: {
							color:'#ffff',
							width:10,
							curveness: 0.9
						}
					}
    };
graph.links.push(xx3);

**Comment by xiaobao143** [comment]
同求，希望高手解答

**Comment by heboliufengjie** [comment]
https://github.com/apache/incubator-echarts/issues/5688

**Comment by DismalSnail** [comment]
同求
