### ISSUE TITLE
Errorbar Chart

### ISSUE THREAD

**Issue by wdc1010** [apache/incubator-echarts#2742]
希望能够加入errorbar的symbol，感谢。
![image](https://cloud.githubusercontent.com/assets/6700882/13552048/6b56fb1e-e38b-11e5-8d2b-f43b8af5cfcf.png)

![image](https://cloud.githubusercontent.com/assets/6700882/13552047/5cc7b30e-e38b-11e5-83ba-799178097df3.png)

图片来自https://github.com/CAYdenberg/Chart.js-ErrorBars

**Comment by Ovilia** [comment]
请通过自定义系列实现效果
