### ISSUE TITLE
能够给图形的label以及legend加上tooltip？

### ISSUE THREAD

**Issue by WebsonLeo** [apache/incubator-echarts#2766]
#### 问题简述 (One-line summary)

有时候会出现legend或者坐标轴的label名称过长的问题，希望能够截断展示，但是目前这两个组件都没有tooltip展示，截断之后就无法知道完整的名称了，希望工程师们辛苦点，可以在这两个组件上加上tooltip展示的功能。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (3.1.2):
- 浏览器类型和版本 (Chrome，版本 48.0.2564.116 m):
- 操作系统类型和版本 (windows7 专业版):
#### 期望结果 (Expected behaviour)

通过设置tooltip可以在鼠标放在坐标轴的label或者legend上时，能够展现出完整的名称

**Comment by pissang** [comment]
谢谢反馈，我们考虑下怎么在 option 中配置 legend 等组件的 tooltip，如果你有建议的话也可以提出。

**Comment by LXVC** [comment]
@pissang 请问现在有了吗
