### ISSUE TITLE
当属于一个y轴的系列在legend中都关闭时，该y轴不会自动隐藏

### ISSUE THREAD

**Issue by netwww1** [apache/incubator-echarts#2785]
#### 问题简述 (One-line summary)

当属于一个y轴的系列在legend中都关闭时，该y轴不会自动隐藏，而是显示为范围为0~1的标尺。
在echarts2中，y轴会自动隐藏。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.x.x
- 浏览器类型和版本 (Browser version): 49.0.2623.87 m
- 操作系统类型和版本 (OS Version): win7 64bit
#### 重现步骤 (Steps to reproduce)
1. 使用如下的option，“邮件营销”属于左y轴，“搜索引擎”属于右y轴，在legend中点击其中一个标签，则对应的曲线隐藏了，但对应的y轴没有隐藏。
2. echarts2实例：[http://echarts.baidu.com/echarts2/doc/example/line6.html](http://echarts.baidu.com/echarts2/doc/example/line6.html)
#### 期望结果 (Expected behaviour)

和2一样，当y轴关联的所有系列都在legend中隐藏时，y轴也应当隐藏。
#### ECharts配置项 (ECharts option)

``` javascript
option = {
        title: {
            text: '堆叠区域图'
        },
        tooltip : {
            trigger: 'axis'
        },
        legend: {
            data:['邮件营销','搜索引擎']
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis : [
            {
                type : 'category',
                data : ['周一','周二','周三','周四','周五','周六','周日']
            }
        ],
        yAxis : [
            {
                type : 'value'
            },
            {
                type : 'value'
            }
        ],
        series : [
            {
                name:'邮件营销',
                type:'line',
                data:[120, 132, 101, 134, 90, 230, 210]
            },
            {
                name:'搜索引擎',
                type:'line',
                yAxisIndex:1,
                data:[820, 932, 901, 934, 600, 1330, 1320]
            }
        ]
}

```
#### 其他信息 (Other comments)

![e3](https://cloud.githubusercontent.com/assets/17537636/13663566/3c287098-e6dd-11e5-8a16-3e1bc6986cfd.png)

![e2](https://cloud.githubusercontent.com/assets/17537636/13663573/46098f2a-e6dd-11e5-85f5-dc2ae3ba14ec.png)

**Comment by TpClark** [comment]
i meet similar question, my situation is multi y axis (more than 2), i need execute same action (the line and y axis, disappear all or display all) where i click someone of the legend, so , how did you do it ?

**Comment by zhans1099** [comment]
4里怎么实现同时隐藏纵坐标？
