### ISSUE TITLE
Any chance to get the new website on github pages? 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#2808]
Hi ECharts team!
there are some performance issues when accessing ECharts website from outside of China, is there any chance to place it on Github pages similar to what you did with 2.x version here: http://ecomfe.github.io/echarts/index-en.html

Or do you have your website somewhere on GitHub? 

Would make loading docs much quicker:)

**Comment by pissang** [comment]
Hi jarben, we are translating the new 3.0 doc to english. It will be released in the middle of April and then we will put our new website on the github pages. Before that i think it's better to keep the old english website on the github pages.  Thanks for the support and waiting.

**Comment by jarben** [comment]
That sounds great, thanks for your answer!

**Comment by gabrielenosso** [comment]
Hi guys! Is the ETA confirmed?
I can't wait anymore to start using this amazing lib!!! :D

**Comment by jarben** [comment]
Any update on this? :) I'm often struggling to load this page: http://echarts.baidu.com/option.html#title

Takes few minutes to load and sometimes it even doesn't load. 

Would it be possible to put it somewhere as a github repo so I can run it locally?

Looking forward for the 3.x EN release!

**Comment by pissang** [comment]
Hi @jarben, @gabrielenosso . We have finished the doc translation, and it will be released in the end of this month. Sorry for the delay.

**Comment by jarben** [comment]
Sounds good, no worries about delay, quality work like this takes time!

**Comment by jossef** [comment]
@pissang 
Where can i find the new docs?

**Comment by jossef** [comment]
@pissang - any news?

**Comment by pissang** [comment]
@jossef Sorry still working on it :)

**Comment by gabrielenosso** [comment]
Are you still working on it? 
Can't wait!!! :D

**Comment by jarben** [comment]
Here is a link to API docs: https://ecomfe.github.io/echarts-doc/public/api-en.html

**Comment by stuta** [comment]
English homepage is showing echarts 3, not echarts 4.
