### ISSUE TITLE
 legend 选中时能否更改样式，文档配置项里没有看到

### ISSUE THREAD

**Issue by xwartz** [apache/incubator-echarts#2811]
#### 问题简述 (One-line summary)

![image](https://cloud.githubusercontent.com/assets/4149827/13720429/6ae31d40-e843-11e5-85c5-79a834bd800e.png)

![image](https://cloud.githubusercontent.com/assets/4149827/13720416/1258b4f0-e843-11e5-8f50-a29339db712f.png)

我看2.0版本是 legend 鼠标移过，是会有对应效果的，比如图形放大了，字体颜色变了，但是在3.0中并没有，而且文档的配置项里，好像也没有查到，请问下
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version): chrome
- 操作系统类型和版本 (OS Version): OSX
#### 重现步骤 (Steps to reproduce)

http://echarts.baidu.com/echarts2/doc/example/pie2.html

http://echarts.baidu.com/demo.html#pie-doughnut
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

http://echarts.baidu.com/echarts2/doc/example/pie2.html

http://echarts.baidu.com/demo.html#pie-doughnut

**Comment by pissang** [comment]
3 也有啊

**Comment by xwartz** [comment]
@pissang 配置项手册里还是没有找到，难道我打开方式不对

**Comment by pissang** [comment]
默认就有颜色高亮

**Comment by xwartz** [comment]
@pissang  好的，谢谢回复

**Comment by xwartz** [comment]
@pissang 顺便问下，你们开发环境下怎么运行调试代码的，都用 test 吗？在看源码，想自己增加点功能

**Comment by pissang** [comment]
把 echarts 和 zrender 放在一个目录下，test 里的是测试示例
