### ISSUE TITLE
地图怎样设置只有数据的省份才有鼠标交互效果？ 

### ISSUE THREAD

**Issue by liekkas** [apache/incubator-echarts#2825]
比如只有北京市有数据，当鼠标悬浮在其他省时没有效果，只有北京有。这里的交互效果包括鼠标滑进滑出、点击等。相当于地图是张图片，只有北京可以有交互效果。

想过设置两张map，第一张map当底图，设置normal和emphasis样式一致，就看不出效果了，第二张只有北京市，但是当只有北京市时，地图的尺寸变大，导致整个北京和全国一样大，没法看。

请教有人解决过这样的情形吗？多谢！

**Comment by giscafer** [comment]
和tooltip属性一样吧，通过方法，判断是不是北京市，如果是，显示tooltip，不是就return;
使用鼠标事件也可以
```
mapChart.on('mouseover', function(e){
  if(e.name==='北京市'){
  console.log('北京市');
}
});
```
