### ISSUE TITLE
GeoCordMap from geojson? 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#2832]
One thing that would make creating mark points on the map easier is to automatically get centroids of polygons from geojson. For instance, this example: http://echarts.baidu.com/demo.html#scatter-world-population

wouldn't need latitude/longitude data as it would calculated it from the 'word' map. 

Would this be possible?

**Comment by pissang** [comment]
It is available to get the centroid of any regions in the map by following code

```js
var geo = chart.getModel().getComponent('geo').coordinateSystem;
console.log(geo.getRegion('china').center);
```

These methods are all not documented yet.

**Comment by jarben** [comment]
This is awesome - thanks for your answer pissang!

**Comment by jarben** [comment]
Thanks again @pissang for the trick. One issue with this is that you need to have access to the chart model which seems to be only available after the chart is already rendered. For example: 

option = {
   geo: {
        map: "world",
    },
    series : [
        {
            type: 'scatter',
            coordinateSystem: 'geo',
            data: []
        }
    ]
};

chart.setOption(option);

// now model is available
var model = chart.getModel();
var geo = model.getComponent('geo').coordinateSystem;
var data = mapData.map(function (itemOpt) {
        var region = geo.getRegion(itemOpt.name);
        var latlong = region.center;

        return {
            name: itemOpt.name,
            value: [
                latlong[0],
                latlong[1],
                itemOpt.value
            ]
        }
    };
});
    
option.series[0].data = data;
chart.setOption(option);


Is there any way to do this as one run? Potentially instantiating the geo component without a chart? I'd say that this feature would be pretty useful considering there are quite a few samples in your gallery that use geo cord map that can be retrieved from geojson anyway? 

What if type of data item is a "geoCord" or similar which means that the map chart would handle it as a point, rather than an area? 

Would be great to hear your thoughts on this, thanks as usually!

**Comment by bhtabor** [comment]
> ```js
> console.log(geo.getRegion('china').center);
> ```

Looks like it is `getCenter()` instead of `center` now. https://github.com/apache/echarts/blob/fd9e62d7fdd88e95ddaf3c371353e8f6ca7d9e6a/src/coord/geo/Region.ts#L101
