### ISSUE TITLE
条形图 resize 重影

### ISSUE THREAD

**Issue by HuanxinHu** [apache/incubator-echarts#2836]
#### 问题简述 (One-line summary)

用bar chart，改变chart container size, echart resize 时会出现条形跳变并且重影问题。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0.2
- 浏览器类型和版本 (Browser version): Chrome Version 49.0.2623.87 (64-bit)
- 操作系统类型和版本 (OS Version): OSX 10.11.2 
#### 其他信息 (Other comments)

![screen shot 2016-03-16 at 12 26 37 am](https://cloud.githubusercontent.com/assets/7131790/13805257/9f229fa2-eb10-11e5-8c0c-3935addd80d8.png)

**Comment by pissang** [comment]
最新版本是否有这个问题？
