### ISSUE TITLE
snakey data=[]时，js报错

### ISSUE THREAD

**Issue by 276509842** [apache/incubator-echarts#2867]
#### 问题简述 (One-line summary)

snakey data=[]时，js报错
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):

echart3.1.3
#### 重现步骤 (Steps to reproduce)

sankey图，无节点的时候，报js错误

威客java 2016/3/21 14:03:03
{
                type: 'sankey',
                layout:'none',
                data: [],
                links: [],
}

js报错误日志：
echarts-all-3.js:30 Uncaught TypeError: Cannot read property 'getLayout' of undefined(anonymous function) @ echarts-all-3.js:30(anonymous function) @ echarts-all-3.js:23p @ echarts-all-3.js:1f.extend.eachSeriesByType @ echarts-all-3.js:23t.exports @ echarts-all-3.js:30(anonymous function) @ echarts-all-3.js:1p @ echarts-all-3.js:1(anonymous function) @ echarts-all-3.js:1p @ echarts-all-3.js:1d @ echarts-all-3.js:1E.update @ echarts-all-3.js:10E.prepareAndUpdate @ echarts-all-3.js:10z.setOption @

**Comment by brucewar** [comment]
官方为啥不解决

**Comment by deqingli** [comment]
不好意思，我们每天有很多 issue，有时候会有遗留，请见谅。这个问题我现在在跟

**Comment by deqingli** [comment]
您好，这个问题解决了，会随下个版本一起发布。感谢给我们提意见，祝好～

**Comment by yzhang921** [comment]
请问3.x哪个版本解决的, 我现在使用的3.6.2依旧存在问题
