### ISSUE TITLE
这个问题还是要提，坐标轴的name位置不能自动适应，感觉有点弱

### ISSUE THREAD

**Issue by luxueyan** [apache/incubator-echarts#2914]
#### 问题简述 (One-line summary)

坐标轴的name的位置，就是要自己手动设置 namegap，这个感觉太弱了，图表目前是有交互的，数据会随时刷新，就是用户的行为会频繁的使用setOption去更新数据，坐标轴的数据格式也是有长有短，不可能每次都去调位置，还有就是grid的设置不能全部auto，所有的位置都是需要自己根据当前情况去调整。。。。
![image](https://cloud.githubusercontent.com/assets/1555552/14099295/c217c220-f5b6-11e5-9822-010c3fdbb2b3.png)

**Comment by pissang** [comment]
谢谢建议，后续优化

**Comment by luxueyan** [comment]
@pissang 赞！希望位置也可以多一些定义
