### ISSUE TITLE
myChart.resize()时能不能避免回滚到页面开头

### ISSUE THREAD

**Issue by Anstinus** [apache/incubator-echarts#2915]
如里chart放在页面比较靠下的位置，myChart.resize()后整个页面会回滚到页面顶端。能不能避免这种情况，保持滚动条位置不变？

（3.1.4版）

**Comment by pissang** [comment]
你确定是 echarts 造成的问题？

**Comment by Anstinus** [comment]
注释掉myChart.resize()这一行就不会有问题。
或者象下面这样自己去resize里面的canvas就不会有问题。但效果当然是不对的……
hostElement.find('canvas').width(newWidth);
hostElement.find('canvas').height(newHeight);

**Comment by Anstinus** [comment]
仔细测了一下。我最开始的描述有一点错误。resize的时候不会跳到页面最顶端，而是往上跳一小段。chart是我的页面的最后一个元素。resize的时候效果是这个chart好像先被移除了，于是整个页面往下滚动到底端，然后chart又出现了，但页面不会再动了。于是整个效果就是往上跳一小段。

**Comment by pissang** [comment]
resize 不会移除 chart，只会调整 canvas 大小，然后重绘

**Comment by Anstinus** [comment]
我不是说真的移除了。只是说行为看起来像是那样。

**Comment by pissang** [comment]
有示例可以看么？
