### ISSUE TITLE
Echarts 2.2.7版本IE下内存增长无法释放

### ISSUE THREAD

**Issue by lwh04** [apache/incubator-echarts#2923]
#### 问题简述 (One-line summary)

IE 下定时调用setOption 更新数据内存增长没有释放，调用dispose方法也没有效果。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
  Echarts 2.2.7
  IE11/10
  操作系统 win8
#### 重现步骤 (Steps to reproduce)
1. js 通过 setInterval 定时5秒获取数据 
2. 通过setOption 函数 设置图表组件的数据。
3. 过段时间内存增加10几M没有降下来。
#### 期望结果 (Expected behaviour)

通过定期调用dispose释放资源，也没有效果。
#### 可能哪里有问题 (What went wrong)

注释掉setOption 内存正常。
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
升级到 echarts 3 试试

**Comment by lwh04** [comment]
没有效果，调用clear、dispose后，重新echarts.init，内存反倒是有所增长。
