### ISSUE TITLE
平行坐标系无法显示tooltip

### ISSUE THREAD

**Issue by qingyunwhu** [apache/incubator-echarts#2924]
#### 问题简述 (One-line summary)

平行坐标系无法显示tooltip，鼠标滑过没有提示框
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):Firefox
- 操作系统类型和版本 (OS Version):Ubuntu
#### 重现步骤 (Steps to reproduce)

1.鼠标移动到图上无信息提示
2.
#### 期望结果 (Expected behaviour)

有tooltip响应结果显示
#### 可能哪里有问题 (What went wrong)

官网示例也没有提示，但是官网代码里有tooltip的配置启用
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by yzh0304** [comment]
这个问题后来你有自己解决吗？

**Comment by qingyunwhu** [comment]
没，我后来没弄这个了

**Comment by llsshh1985** [comment]
我想在平行坐标上加click事件，也是没有效果。其他柱状图饼状都是可以的

**Comment by llsshh1985** [comment]
我找到一个了曲折的方法，用点击坐标轴来代替，就是设置parallelAxis的triggerEvent属性为true,再使用click事件获取params

**Comment by es3154** [comment]
好曲折

**Comment by lkbtt** [comment]
@llsshh1985  params里面也没啥东西啊，如何显示tooltip呢？
