### ISSUE TITLE
请问visualMap中的手柄可否精确控制位置

### ISSUE THREAD

**Issue by unsee** [apache/incubator-echarts#2940]
背景：项目的热力图中，visualMap的min和max是动态变化的。

问题：动态值使用setOption设定以后发现，手柄的位置不会变化，例如min和max初始值为(1,10),变化为（2,20)，调用setOption以后,右边手柄的位置仍然在10的位置上
   在echarts3.0中，visualMap的手柄可以用鼠标拖动，控制颜色的现实。但是在文档中只有visualMap[i]-continuous.handlePosition属性，属性值也只有left等几项，控制的很粗糙，不知道是不是有别的方法能控制手柄的位置。
多谢答复

**Comment by 100pah** [comment]
如果想用程序改变手柄的位置，可以设置：
