### ISSUE TITLE
visual map的那个把手，没法调整位置

### ISSUE THREAD

**Issue by superddr** [apache/incubator-echarts#2962]
总是在地图左边，有时候需要调到右边去。。

**Comment by pissang** [comment]
?

**Comment by superddr** [comment]
visual map，caclulable:true，在地图的左边会出现一个筛选用的把手，有上下限选择器。而有时候需要它出现在地图的右边。。。目前貌似没有选项可以调整他的位置

**Comment by pissang** [comment]
可以画个示意图么？把手在地图右边还是整个组件在地图右边

**Comment by superddr** [comment]
[https://raw.githubusercontent.com/superddr/OpenTLD/master/QQ%E6%88%AA%E5%9B%BE20160411102410.png](url)
就像这样，整个组件在右边

**Comment by 100pah** [comment]
你给的图片不能打开。
visualMap 放在地图右边，
参见 <http://echarts.baidu.com/option.html#visualMap-continuous.right>
