### ISSUE TITLE
关系图数据点过多时报错

### ISSUE THREAD

**Issue by gxma** [apache/incubator-echarts#2965]
[index - 副本 (2).zip](https://github.com/ecomfe/echarts/files/209544/index.-.2.zip)

#### 问题简述 (One-line summary)

关系图数据点过多时报错
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.1.5
- 浏览器类型和版本 (Browser version):chrome 49.0.2623.110 m
- 操作系统类型和版本 (OS Version):win 8
#### 重现步骤 (Steps to reproduce)

1.点数据19798个，太多无法贴出代码。（见附件）
2.点数据少时无问题。
#### 可能哪里有问题 (What went wrong)

echarts.min.js:32 Uncaught TypeError: Cannot set property 'dataIndex' of undefined
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

其他问题：2.x版使用useWorker：true绘制无问题，在3.x版本中经常会页面无响应。

**Comment by liaicheng** [comment]
哥们，最后你是咋解决的？我看是数据本身的问题。

**Comment by pvis** [comment]
您好 这个是好几个月前的问题 我记得当时在2.x下没问题 在3.x下会出现 我知道是什么原因 没有深究 我后来用分批绘制的办法解决的。

**Comment by LeoHuang2015** [comment]
我跑了一下，超过10个就报错，咋解决的？

**Comment by pvis** [comment]
@LeoHuang2015 不能吧 是不是代码错了 贴出来 看看。

**Comment by LeoHuang2015** [comment]
@pvis  写了一个demo，这样也报错的。
Uncaught TypeError: Cannot set property 'dataIndex' of undefined
`    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));
    option = {
        title : {
            text: 'QQ群关系：21605735',
            subtext: '数据来自2010年的QQ群信息',
            x:'left',
            y:'top'
        },
        tooltip : {
            trigger: 'item',
            formatter: '{a} : {b}'
        },
        toolbox: {
            show : true,
            feature : {
                restore : {show: true},
                magicType: {show: true, type: ['force', 'chord']},
                saveAsImage : {show: true}
            }
        },

        legend: {
            x: 'middle',
            data:['QQ','QQ群', '其他QQ']
        },
        series : [
            {
                name : "QQ群关系",
                type:'graph',
                layout: 'force',
                //ribbonType: false,
                force: {
                    repulsion: 1000
                },
                categories : [
                    {
                        name: 'QQ'
                    },
                    {
                        name: 'QQ群'
                    },
                    {
                        name: '其他QQ'
                    },
                ],
                itemStyle: {
                    normal: {
                        label: {
                            show: true,
                            textStyle: {
                                color: '#333'
                            }
                        },
                        nodeStyle : {
                            brushType : 'both',
                            borderColor : 'rgba(255,215,0,0.4)',
                            borderWidth : 1
                        },
                        linkStyle: {
                            type: 'curve'
                        }
                    },
                    emphasis: {
                        label: {
                            show: false
                            // textStyle: null      // 默认使用全局文本样式，详见TEXTSTYLE
                        },
                        nodeStyle : {
                            //r: 30
                        },
                        linkStyle : {}
                    }
                },
                useWorker: false,
                minRadius : 15,
                maxRadius : 25,
                gravity: 1.5,
                scaling: 1.1,
                roam: true,
                label: {
                    normal: {
                        position:'right'
                    }
                },
                nodes:[
                        {category:0, name: '21605735', value : 100, label: 'QQ号\n（主要）'}, 
                        {category:1, name: '100100', value: 20,  },
                         {category:2, name: '21605735', value:10, },
                         {category:2, name: '32507773', value:10, },
                        
                        
                        {category:1, name: '800000', value: 20,  },
                        
                        
                        {category:1, name: '1193390', value: 20,  },
                         {category:2, name: '153195012', value:10, },
                         {category:2, name: '17125310', value:10, },
                        
                        
                        {category:1, name: '1319340', value: 20,  },
                         {category:2, name: '525000016', value:10, },
                         {category:2, name: '450000030', value:10, },
                        
                        
                        {category:1, name: '1674197', value: 20,  },
                         {category:2, name: '44033125', value:10, },
                         {category:2, name: '1002000033', value:10, },
                        
                        
                        {category:1, name: '1674708', value: 20,  },
                         {category:2, name: '13588458', value:10, },
                         {category:2, name: '32507773', value:10, },
                        
                        
                        {category:1, name: '3271816', value: 20,  },
                         {category:2, name: '30105455', value:10, },
                         {category:2, name: '611090796', value:10, },
                        
                        
                        {category:1, name: '3714581', value: 20,  },
                         {category:2, name: '704554789', value:10, },
                         {category:2, name: '795019406', value:10, },
                        
                        
                        {category:1, name: '5465084', value: 20,  },
                         {category:2, name: '182237372', value:10, },
                         {category:2, name: '10560343', value:10, },
                        
                          ],
                links : [
                        
                        {source : '21605735', target : '100100', weight : 2, name: '群'},
                        
                            {source : '100100', target : '21605735', weight : 1, name: '群成员'},
                        
                            {source : '100100', target : '32507773', weight : 1, name: '群成员'},
                        
                        
                        {source : '21605735', target : '800000', weight : 2, name: '群'},
                        
                        
                        {source : '21605735', target : '1193390', weight : 2, name: '群'},
                        
                            {source : '1193390', target : '153195012', weight : 1, name: '群成员'},
                        
                            {source : '1193390', target : '17125310', weight : 1, name: '群成员'},
                        
                        
                        {source : '21605735', target : '1319340', weight : 2, name: '群'},
                        
                            {source : '1319340', target : '525000016', weight : 1, name: '群成员'},
                        
                            {source : '1319340', target : '450000030', weight : 1, name: '群成员'},
                        
                        
                        {source : '21605735', target : '1674197', weight : 2, name: '群'},
                        
                            {source : '1674197', target : '44033125', weight : 1, name: '群成员'},
                        
                            {source : '1674197', target : '1002000033', weight : 1, name: '群成员'},
                        
                        
                        {source : '21605735', target : '1674708', weight : 2, name: '群'},
                        
                            {source : '1674708', target : '13588458', weight : 1, name: '群成员'},
                        
                            {source : '1674708', target : '32507773', weight : 1, name: '群成员'},
                        
                        
                        {source : '21605735', target : '3271816', weight : 2, name: '群'},
                        
                            {source : '3271816', target : '30105455', weight : 1, name: '群成员'},
                        
                            {source : '3271816', target : '611090796', weight : 1, name: '群成员'},
                        
                        
                        {source : '21605735', target : '3714581', weight : 2, name: '群'},
                        
                            {source : '3714581', target : '704554789', weight : 1, name: '群成员'},
                        
                            {source : '3714581', target : '795019406', weight : 1, name: '群成员'},
                        
                        
                        {source : '21605735', target : '5465084', weight : 2, name: '群'},
                        
                            {source : '5465084', target : '182237372', weight : 1, name: '群成员'},
                        
                            {source : '5465084', target : '10560343', weight : 1, name: '群成员'},
                        
                        
                ]
            }
        ]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);`

**Comment by pvis** [comment]
@LeoHuang2015 代码有问题。
{category:0, name: '21605735', value : 100, label: 'QQ号\n（主要）'},
{category:1, name: '21605735', value:10, },
name 一样的出现了两次。相同name只能有一个category和value。

**Comment by LeoHuang2015** [comment]
@pvis  厉害，谢谢！
