### ISSUE TITLE
grid配置中，width一旦定义后无法修改，导致无法达到自适应效果

### ISSUE THREAD

**Issue by struggling-bird** [apache/incubator-echarts#2994]
#### 问题简述 (One-line summary)

grid配置中，width一旦设置之后，就再也无法修改，通过setOption或者resize方法都不好使。
下面说一下我为什么会有重置grid的width的需求。
最初是因为Y轴的axisLabel文本如果过长的话，或者数字过大，使用默认配置就会导致文字溢出可视区域。那为了解决这个问题呢，我是采用了设置grid中left值的方法，即在setOption之前，我会预先算出合适的left值，保证显示的正常，如此就有了下一个问题，left值设置之后grid的宽度也就需要重新计算一下，也需要设置一下，否则grid可能就会部分不可见，溢出可视区域了，因此也设置了grid的width值。
如此下来之后，初次访问时候页面是没有什么问题的，可是一旦窗口发生变化，悲剧就发生了，grid宽度不会自适应了，我即便按照上面的方式重新setOption都不好使了。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0的最新版本
- 浏览器类型和版本 (Browser version):chrome最新版
- 操作系统类型和版本 (OS Version):mac
#### 重现步骤 (Steps to reproduce)

1.setOption中设置grid的width值
2.改变窗口大小重置grid的width值
#### 期望结果 (Expected behaviour)

最理想的情况是echarts本身能做到宽度的自适应，即Y轴的axisLabel的文本不管是多长都能够自动计算grid的left值，避免y轴文本溢出。
如果不行的话，最次也要通过setOption之类的手段能够修改grid的配置（目前发现的是width值，其它未测试还）
#### ECharts配置项 (ECharts option)

``` javascript
option = {
。。。
}

```

**Comment by pissang** [comment]
文本溢出可以通过配置 containLabel 配置项解决

**Comment by struggling-bird** [comment]
感谢回复，可以了 @pissang ,如果自己设置grid的边距（top,left,right,bottom）的话，如果不增减相应的grid的宽度或者高度，图像会被挤出去么？因为产品觉得默认的边距有点太大，想调整
