### ISSUE TITLE
datazoom拖动滑块，松开鼠标后两端label不显示。

### ISSUE THREAD

**Issue by sdhhqb** [apache/incubator-echarts#3006]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3
- 浏览器类型和版本 (Browser version): chrome 48.0.2564.97
- 操作系统类型和版本 (OS Version): windows
#### 重现步骤 (Steps to reproduce)

1.鼠标移入滑块，此时label正常显示，按下鼠标拖动滑块，保持鼠标不要移出滑块。
2.拖动一段距离后松开鼠标，两端的label不显示了。
3.此时按下鼠标继续拖动，label也没有显示。
#### 期望结果 (Expected behaviour)

拖动滑块时始终显示两端的label，方便观察当前位置两端的数值。
#### 可能哪里有问题 (What went wrong)

可能是鼠标事件处理的问题
#### ECharts配置项 (ECharts option)

官方实例 折线图-雨量流量关系图上可以出现：[http://echarts.baidu.com/demo.html#area-rainfall](http://echarts.baidu.com/demo.html#area-rainfall)

``` javascript
```

**Comment by pissang** [comment]
这里处理是有瑕疵，鼠标移出滑块再移入会重新显示 label
