### ISSUE TITLE
legend都为隐藏的情况，点击某一个后，对应的折线没有显示出来

### ISSUE THREAD

**Issue by liumanwei** [apache/incubator-echarts#3013]
#### 问题简述 (One-line summary)

yAxis设置了max、min。
现在点击legend的时候，我需要调整yAxis的最大值、最小值，现在使用的方法是在点击legend的时候，重新计算一下最大值、最小值，再通过setOption设置。
当所有的legend的值为false的情况下，我点击某一个legend后，yAxis的最大值、最小值变化了，但是对应的线不出来。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 2
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):mac
#### 重现步骤 (Steps to reproduce)

1.点击legend影响所有折线
2.点击某一个后，对应的折线没有显示出来
#### 期望结果 (Expected behaviour)

在legend全部隐藏的情况下，点击某一个后，对应的折线也可以出来
#### ECharts配置项 (ECharts option)

``` js
var legendHandler = function (res) {
    var curLegend = res.selected;
    var curSeries = this.getSeries();
    var seriesItem = null;
    var tempData = [];
    for (var i = 0, len = curSeries.length; i < len; i++) {
        seriesItem = curSeries[i];
        if (curLegend[seriesItem.name]) {
            tempData = tempData.concat(seriesItem.data);
        }
    }
    var max = Math.max.apply(window, tempData);
    var min = Math.min.apply(window, tempData);
    this.setOption({
        yAxis: [
            {
                max: max,
                min: min
            }
        ]
    }, false);
    this.refresh();
};
```

**Comment by pissang** [comment]
试试 3

**Comment by liumanwei** [comment]
@pissang 3可以实现我想要的效果，但是在隐藏折线后，
![image](https://cloud.githubusercontent.com/assets/736202/14601611/a96be17c-0595-11e6-8453-284738493ccb.png)
