### ISSUE TITLE
2.x版本不维护了么？如果出现错误怎么办

### ISSUE THREAD

**Issue by dukai** [apache/incubator-echarts#3019]
#### 我现在使用2.x版本，折线的type:'dashed'不生效

在3.x版本中是生效的，但是2.x版本中dashed不生效，但是旧有项目无法升级到3.x版本
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):2.2.7
- 浏览器类型和版本 (Browser version):chrome 49.0.2623.87 
- 操作系统类型和版本 (OS Version):windows 7 
#### 重现步骤 (Steps to reproduce)

1.一直重现，使用官方的demo查看也存在这个问题
#### 期望结果 (Expected behaviour)

lineStyle: {type: 'dashed'}设置后显示虚线段
#### 可能哪里有问题 (What went wrong)

是不是没有把参数mix进去
#### ECharts配置项 (ECharts option)

``` javascript
option = {
series : [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            },
          itemStyle:{
            normal: {
              lineStyle: {
                  color:'#ff0000',
                  type: 'dashed',
                width: 10
              }
            }
          }
        }
    ]
}

```
#### 其他信息 (Other comments)

![20160419105701](https://cloud.githubusercontent.com/assets/405129/14626391/82bff562-061d-11e6-8f01-3f278f44458d.png)

**Comment by pissang** [comment]
升级到 3
