### ISSUE TITLE
温度计式图表中柱子高度过低，数值显示异常

### ISSUE THREAD

**Issue by huguangju** [apache/incubator-echarts#3020]
#### 问题简述 (One-line summary)

如果温度计式图表中柱子高度过低，本应该显示在柱子中的数值，显示在了x轴下方。v2和v3表现一样。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 2 && 3
- 浏览器类型和版本 (Browser version): Chrome 49.0.2623.112 (64-bit)
- 操作系统类型和版本 (OS Version): Mac OS 10.10.5 
#### 重现步骤 (Steps to reproduce)
1. http://echarts.baidu.com/echarts2/doc/example/bar10.html 中将series中第一个data改为`[260, 200, 220, 120, 20, 8]`
2. 点击刷新
#### 期望结果 (Expected behaviour)

如果柱子过低容纳不下数值显示，可以隐藏数值
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/6972433/14626493/827a1c1c-061e-11e6-958f-c411603d87e4.png)

**Comment by pissang** [comment]
可以设置每个数据的 label 属性，然后根据需要决定是否隐藏
