### ISSUE TITLE
当option中设置了legend后，地图省份选中之后不显示label。

### ISSUE THREAD

**Issue by sdhhqb** [apache/incubator-echarts#3021]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3
- 浏览器类型和版本 (Browser version): 50.0.2661.75 m
- 操作系统类型和版本 (OS Version): win7
#### 重现步骤 (Steps to reproduce)

1.配置一个地图的option，设置legend属性
2.data中添加几个省份的数据
#### 期望结果 (Expected behaviour)

点击选中一个省份时，显示省份名label
#### 可能哪里有问题 (What went wrong)

legend配置影响到label了
#### ECharts配置项 (ECharts option)

``` javascript
option = {
    tooltip: {
        trigger: 'item',
        formatter: '{b}:{c}'
    },
    legend: {},
    series: [
        {
            name: '中国',
            type: 'map',
            mapType: 'china',
            selectedMode : 'single',
            label: {
                normal: {
                    show: false
                },
                emphasis: {
                    show: true
                }
            },
            data:[
                {name:'广东', value:1},
                {name:'新疆', value:2}, 
                {name:'四川', value:3}
            ]
        }
    ]
};

```
#### 其他信息 (Other comments)

因为需要在地图上绘制省份数据和散点图，散点图要设置legend，这个问题希望官方后面能解决一下。

**Comment by Nickcoins** [comment]
请问问题解决了吗?
