### ISSUE TITLE
graph->force图不能控制迭代次数

### ISSUE THREAD

**Issue by SpiritBreaker** [apache/incubator-echarts#3026]
#### 问题简述 (One-line summary)

力导图没办法在option设置迭代次数，导致较长时间里，节点一直在改变position
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):**3.1.6**
- 浏览器类型和版本 (Browser version):chrome49.0
- 操作系统类型和版本 (OS Version):windos7
#### 重现步骤 (Steps to reproduce)

1.力导图加载200个点，较长时间里节点的position频繁移动
2.
#### 期望结果 (Expected behaviour)

能否客户端设置option参数，控制力导的迭代次数
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
不建议手动修改，减少迭代次数很可能导致布局结果不理想

**Comment by SpiritBreaker** [comment]
如果节点较多，可能冷却时间稍长。

PS：@pissang，Echarts3的力导，貌似节点大小只能在option中设置symbosize，能否实现原来2中的自适应，根据节点value来自动设置大小呢？？

**Comment by pissang** [comment]
节点时间多布局时间长是无法避免的，后面会引入 2 中那个性能更好的布局器。

可以用 visualMap 组件映射到 symbolSize，见 http://echarts.baidu.com/option.html#visualMap-continuous.inRange

**Comment by SpiritBreaker** [comment]
OK，期待优化版本。visualMap映射symbolSize已经满足。thanks
