### ISSUE TITLE
echart3中 设置markPoint 若数据为空，会导致浏览器卡死

### ISSUE THREAD

**Issue by lh4111** [apache/incubator-echarts#3035]
#### 问题简述 (One-line summary)

echart3中 设置markPoint 若数据为空，会导致浏览器卡死。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.1.4
- 浏览器类型和版本 (Browser version):Chrome 49、Safari 
- 操作系统类型和版本 (OS Version):OSX 10.11.4
#### 重现步骤 (Steps to reproduce)

1.设置 markPoint: {data: [{type: "max", name: "最大值"}, {type: "min", name: "最小值"}]}
2.设置 data:[]
#### 期望结果 (Expected behaviour)

表格无数据，无标记点
#### ECharts配置项 (ECharts option)

``` javascript
option = {
   series: [
                    {
                        name: "我",
                        type: "line",
                        data:[],
                        smooth: true,
                        markPoint: {data: [{type: "max", name: "最大值"}, {type: "min", name: "最小值"}]},
                        symbol: "circle",
                        symbolSize: 15,
                        itemStyle: {
                            normal: {
                                color: "rgb(86, 170, 255)"
                            }
                        }
                    }
                ],
}

```

**Comment by pissang** [comment]
最新版本测试没有这个问题
