### ISSUE TITLE
Treemap label doesn't seem to support formatter

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3037]
Version: 3.1.6

Would be nice if treemap label can be formatted similarly to other labels. Doesn't seem to work now and I haven't found it in docs either.

**Comment by pissang** [comment]
Thanks for the feedback, added it and #3036 to the fix list of 3.1.8

**Comment by jarben** [comment]
Perfect, thanks pissang

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#series-treemap.levels.label.normal.position>

**Comment by shlice** [comment]
@pissang @jarben it still not work in version 3.2.3. please check label formatter config in Treemap, thanks.

**Comment by jarben** [comment]
Yeah, #3036 seems to fix the label position issue (which is great!) although it's still not possible to format treemap label:

Treemap:
![image](https://cloud.githubusercontent.com/assets/561365/17799944/66953664-65df-11e6-990e-178550f5df30.png)

Line:
![image](https://cloud.githubusercontent.com/assets/561365/17799932/5042b31e-65df-11e6-9d41-5e8f8962fb42.png)


Would be great if treemap->label config has a formatter:) 

Is it possible to reopen this?

**Comment by iSoir** [comment]
Any news?

**Comment by soundtina** [comment]
3.5.3 doesn't support the label formatter,
