### ISSUE TITLE
使用canvas创建画布时的小问题

### ISSUE THREAD

**Issue by xlgray** [apache/incubator-echarts#3052]
#### 问题简述 (One-line summary)

在html中创建画布时，一开始使用canvas，能够画出图形，但是不能显示tooltip，而在option中明明已经设置了。

在所有设置及其他代码均不变的情况下，改用教程中说的div创建画布，tooltip能够正常显示。

很多时候画图用的都是canvas，不知道为什么用在这里会有小问题。应该算是一个bug吧。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):ECharts 3.1.6
- 浏览器类型和版本 (Browser version): Chrome, IE8
- 操作系统类型和版本 (OS Version):Windows
#### 重现步骤 (Steps to reproduce)

1.
2.

**Comment by pissang** [comment]
需要 tooltip 的时候用 div 就行，内部会创建 canvas，只有在无法创建 div 的时候可以用 canvas，比如 node 端，或者需要生成静态图片的时候，但是这种时候也不需要 tooltip
