### ISSUE TITLE
series.label.normal.show设置为true(显示图形上文本标签)时，当数据过多时，会出现重叠

### ISSUE THREAD

**Issue by godkillCK** [apache/incubator-echarts#3054]
series.label.normal.show设置为true(显示图形上文本标签)时，当数据过多时，会出现重叠
如图：
![image](https://cloud.githubusercontent.com/assets/8386256/14735528/dd94ec3a-08a3-11e6-87cc-84ecfacf6362.png)

期望文本标签的值能跟随坐标的刻度自适应显示

**Comment by busyShadow** [comment]
楼上大哥，最后有解决方法吗？series-bar.label里的with只能固定写一个数值，不能设置百分比
