### ISSUE TITLE
echarts3 在微信浏览器，qq浏览器下配置legend的data下的icon为circle 不显示圆

### ISSUE THREAD

**Issue by yangjunwu** [apache/incubator-echarts#3055]
#### 问题简述 (One-line summary)

echarts3 在微信浏览器，qq浏览器下配置legend的data下的icon为circle 不显示圆图标。 在折线图的拐点也同样，涉及到圆在这两个浏览器下均不显示，在移动chrome测试没问题。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3
- 浏览器类型和版本 (Browser version):微信浏览器 qq浏览器 移动chrome
- 操作系统类型和版本 (OS Version): android4.4
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

期望显示无差别
#### 可能哪里有问题 (What went wrong)

可能移动浏览器不支持border-radius：50% 或者需要加前缀-webkit
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
具体配置项，是否只在微信浏览器下是这样

**Comment by TooBug** [comment]
碰到同样问题
