### ISSUE TITLE
Automatic Date Format

### ISSUE THREAD

**Issue by talatbaig** [apache/incubator-echarts#3056]
Hi,

For xAxis type:time I want to change the format of the date to YYYY-MM-DD or DD-MM-YYYY

Is there an option for this?

Thanks

**Comment by pissang** [comment]
`xAxis.axisLabel.formatter`

**Comment by talatbaig** [comment]
but how can I get this to work when using datazoom
I would like it to be exactly the same as the current one, so when you zoom out you only see date but when you zoom in you can also see the time

**Comment by acrogenesis** [comment]
@talatbaig were you able to solve this?

**Comment by sorenhoyer** [comment]
+1

**Comment by nickelmatt** [comment]
+1

**Comment by JasonXDDD** [comment]
+1

**Comment by camaraldo7** [comment]
Hello I have the same problem. Did you solve it? How, if yes?...
