### ISSUE TITLE
好像无法支持绘制棱锥图

### ISSUE THREAD

**Issue by justdark** [apache/incubator-echarts#3057]
棱锥图是ppt里的概念，长得和金字塔图（漏斗图）差不多，但是有可能会出现两头大中间小的情况，echarts的漏斗图貌似必须有sort，没法画出这样的图来

**Comment by justdark** [comment]
手动改代码实现了，funnel的sort你们应该加个不排序的参数~~~~

**Comment by youmin0** [comment]
同意：手动改代码实现了，funnel的sort你们应该加个不排序的参数~~~~

**Comment by cuijian-dexter** [comment]
@Ovilia is this issues already supported? `sort` have `none` option.

**Comment by Ovilia** [comment]
Yes. Please set `sort` to be `'none'` if you don't wish to sort items.
