### ISSUE TITLE
echart 3.x 的地图中textFixed和geoCoord都没了，改如何修正文字位置。

### ISSUE THREAD

**Issue by ebbgithub** [apache/incubator-echarts#3066]
#### 问题简述 (One-line summary)

echart 3.x 的地图中textFixed和geoCoord都没了，新版该如何修正文字位置。
在2.x中可以正常使用的两个配置。
series[i](map).textFixed
series[i](map).geoCoord
#### 版本及环境 (Version & Environment)

echart 3.x
#### 重现步骤 (Steps to reproduce)

官方文档
#### 期望结果 (Expected behaviour)

希望能够解答疑惑，不管改成其他的还是取消了都就说一下，
我们因为某个地名不能正确定位到地图内部，正在全面把3.x的大量图表用2.x重写，
希望能够尽快得到正确处理方法。
#### 可能哪里有问题 (What went wrong)

版本调整
#### ECharts配置项 (ECharts option)

``` javascript
option = {
   ******
    series : [
        {
            ******
            // 文本位置修正
            textFixed : {
                'Yau Tsim Mong' : [-10, 0]
            },
            // 文本直接经纬度定位
            geoCoord : {
                'Islands' : [113.95, 22.26]
            }
        }
    ]
}

```

**Comment by fredwei** [comment]
案例中有看到文本修整，但是配置手册里却找不到，可能是版本更新去掉了

**Comment by pissang** [comment]
嗯，可以暂时通过修改（添加） geoJson 中的 properties.cp 配置文字的位置
