### ISSUE TITLE
markPoint top/left/right/bottom

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3098]
Would it be possible to have top/left/right/bottom properties for the mark point? I'm using markPoint to show text or image on the chart but can't find a way to position it relatively to the bottom of the chart so it adapts when resizing.

**Comment by pissang** [comment]
markPoint `x` and `y`  property support percent value. For example:
```js
// Bottom center
{
  x: '50%',
  y: '100%'
}
```

**Comment by jarben** [comment]
I'm getting: Uncaught TypeError: i.getOtherAxis is not a functionc @ echarts.min.js:23u

when trying to set these on "effectScatter" series (geo coord)

+ it might be hard to set padding from a side, for instance bottom:"20px" would need to be set as y:"90%" which is not ideal.

**Comment by pissang** [comment]
It seems to be a bug. And for the padding, you can use symbolOffset to get the same result.
```js
{
  symbolOffset: [0, -20]
}
```

**Comment by jarben** [comment]
> you can use symbolOffset to get the same result.
nice! Thanks

**Comment by AlaaFK** [comment]
> It seems to be a bug. And for the padding, you can use symbolOffset to get the same result.
> 
> ```js
> {
>   symbolOffset: [0, -20]
> }
> ```

Thanks a lot. That works
