### ISSUE TITLE
Incorrect get width of chart when container element' width is specified by %;

### ISSUE THREAD

**Issue by thangbn** [apache/incubator-echarts#3118]
#### 问题简述 (One-line summary)

Incorrect get width of chart container when width is specified by %;
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): latest
- 浏览器类型和版本 (Browser version): Chrome
- 操作系统类型和版本 (OS Version): Windows
#### 重现步骤 (Steps to reproduce)

1.Create a chart container have width = 100% of parent container,
2. ECharts incorrectly parse the width to 100 px instead of 100% width of parent container div.
Pls take a look at the getWidth function:

``` javascript
 _getWidth: function () {
                var root = this.root;
                var stl = document.defaultView.getComputedStyle(root);
                // FIXME Better way to get the width and height when element has not been append to the document
                return ((root.clientWidth || parseInt10(stl.width) || root(root.style.width))
                        - (parseInt10(stl.paddingLeft) || 0)
                        - (parseInt10(stl.paddingRight) || 0)) | 0;
            },
```
#### 期望结果 (Expected behaviour)

The width of chart container should be calculated from % of parent container div.
I think it's better to give a default width > 0. 0 is useless make it's hard to troubleshoot problem while nothing is displayed.
Thx.
#### ECharts配置项 (ECharts option)

``` javascript

```

**Comment by pissang** [comment]
echarts needs to know the actually dom width when initializing. It's a fallback solution in case dom has not been attached and get width 0. 

Parse percent value may solve some case when parent width is specified. But we suggest always do resize when:

1. Window or container resized
2. Dom attached to the document
3. Dom switched from hidden to visible

**Comment by robinsoncrus0e** [comment]
This still seems to be an issue.  Has there been a fix implemented?

**Comment by AgentJay** [comment]
I would also like to see this fixed
