### ISSUE TITLE
Echarts的饼图绘制的时候，不能根据宽度和高度自适应内部的显示线条么？

### ISSUE THREAD

**Issue by flyingQuQu** [apache/incubator-echarts#3126]
#### 问题简述 (One-line summary)

Echarts的饼图绘制的时候，不能根据宽度和高度自适应内部的显示线条么？
![image](https://cloud.githubusercontent.com/assets/12640805/14950178/58a55c30-1082-11e6-917a-77db95e545b4.png)
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 2.2.7
- 浏览器类型和版本 (Browser version): IE8
- 操作系统类型和版本 (OS Version): Windows 10 企业版 64位 +CPU: Intel(R) Core(TM) i7-4790K CPU @4.00GHz 4.00GHz +内存: 16GB RAM
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by realeve** [comment]
[echarts.resize()](http://echarts.baidu.com/api.html#echartsInstance.resize)

**Comment by flyingQuQu** [comment]
@realeve 
resize是在画布大小改变时，重新绘制吧。
现在的问题是，画布原始大小是固定的，但是饼图中显示的线条超出了画布。

**Comment by realeve** [comment]
画布的大小，饼图的大小这些是事前知道的，在设置线长度的时候就应该由开发者确保这个值不要超过边缘。
