### ISSUE TITLE
echarts3.0 echarts.registerMap使用问题，急！！

### ISSUE THREAD

**Issue by langzixin** [apache/incubator-echarts#3139]
请问，基于中国地图（geo组件），如何使用echarts.registerMap将大陆地区比例调小，台湾地区比例调大些，请给个代码示例

缩放比例调整后，lines能够正常使用吧，因为要在调整比例后的地图上，进行大陆和台湾地区之间连线

谢谢

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/gallery/editor.html?c=map-usa 这个美国地图的示例

**Comment by langzixin** [comment]
已经根据示例代码完成大陆、台湾地区比例调整，但是在调整后的地图上使用lines时，点的位置不正确，请问是否调整后的地图geocoord变化了，新的geocoord如何得到，谢谢
