### ISSUE TITLE
雷达图点击及鼠标提示信息是整个序列的

### ISSUE THREAD

**Issue by nighthun** [apache/incubator-echarts#3141]
#### 问题简述 (One-line summary)

雷达图鼠标移到每个点上的鼠标提示信息都是一样的，dataIndex都是0，为何要这样设计呢？希望能像其它图形一样，每个点不一样。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):ECharts3.1.7
- 浏览器类型和版本 (Browser version):IE11
- 操作系统类型和版本 (OS Version):WINDOWS
#### 重现步骤 (Steps to reproduce)

1.http://echarts.baidu.com/demo.html#radar-custom
2.直接在option中添加 tooltip:{formatter:function(params){
        debugger;
    }},
3\可以发现鼠标移动到每个点上，params的值都是相同的，，
#### 期望结果 (Expected behaviour)

鼠标移动到每个点上，params的值是不同的
#### 可能哪里有问题 (What went wrong)

现在雷达图所有点的提示信息相同，并且无法做扩展。。点击每个点也一样。
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/10071831/15014980/cd3b849c-123b-11e6-96f8-a5581a3f77b6.png)

**Comment by riyuuli** [comment]
貌似没有回应么，解决了没？

**Comment by nighthun** [comment]
没解决，难道是雷达图就想做成这样么？为何所有点的提示信息都是全部指标信息呢？

**Comment by zxhfighter** [comment]
同类似的需求，echart2是可以的，echart3不行

**Comment by dash-love** [comment]
也是相同问题，用回echart2的话多很多k
