### ISSUE TITLE
mouse events on markPoint labels are not fired

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3142]
I have a markPoint which renders like this: 

![image](https://cloud.githubusercontent.com/assets/561365/15017650/b6e38728-1216-11e6-9bf7-0a4fb20a8d90.png)

But it seems like mouse events are completely swallowed over the label. When I try to do:
chart.on("mousedown", function(ev){});.. 
nothing seems to be fired. 

Also, it seems like emphasis style only works when hovering over symbol where it should work when hovering over labels as well.

Why are mouse events swallowed on labels?

**Comment by pissang** [comment]
Labels on symbol can't trigger mouse event currently.
