### ISSUE TITLE
echart3使用百度地图扩展，地图切片显示不全，有空白

### ISSUE THREAD

**Issue by yangguichun** [apache/incubator-echarts#3164]
#### 问题简述 (One-line summary)

使用echart3官方的bmap扩展显示地图，地图切片显示不全，有空白。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.1.7
- 浏览器类型和版本 (Browser version):chrome, 47.0.2526.106
- 操作系统类型和版本 (OS Version): win7 sp1 旗舰版
#### 重现步骤 (Steps to reproduce)

1.直接打开echart源码路径下的bmap 例子： test/bmap.html
2.放大或者拖拽之后会出现地图切片显示不全，局部有空白，见下图。
![image](https://cloud.githubusercontent.com/assets/14036683/15103720/59e26412-15e1-11e6-9eb4-148ee589eacc.png)
#### 期望结果 (Expected behaviour)
1. 正常情况不应该出现空白，所有切片都应该可以加载出来。
#### 可能哪里有问题 (What went wrong)
1. 尝试把\extension\bmap\BMapView.js的77行的setMapStyle注释了，则同样区域的地图就可以加载全。可见应该和该setMapStyle有些关系；
2. 然后试着在单独的页面中调用BMap的setMapStyle
   ，代码如下
   `<html>
   <head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
   <style type="text/css">
       body, html,#allmap {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";}
   </style>
   <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=oeK86DZIYjG81FPqxcDFS5GfFZfWuZFw"></script>
   <title>鼠标滚轮缩放地图</title>
   </head>
   <body>
   <div id="allmap"></div>
   <script type="text/javascript">
   // 百度地图API功能
   var map = new BMap.Map("allmap");            
   map.centerAndZoom("重庆",12);                
   map.enableScrollWheelZoom();   //启用滚轮放大缩小，默认禁用
   map.enableContinuousZoom();    //启用地图惯性拖拽，默认禁用
   var option = '{"styleJson":[{"featureType":"water","elementType":"all","stylers":{"color":"#044161"}}]}';   
   map.setMapStyle(option);
   alert(map.getZoom());
   </script>
   </body>
   </html>
   `

发现同样存在问题，如下：
![image](https://cloud.githubusercontent.com/assets/14036683/15103737/9fc166c2-15e1-11e6-9654-70e480a01c5d.png)

**Comment by yangguichun** [comment]
![image](https://cloud.githubusercontent.com/assets/14036683/15103720/59e26412-15e1-11e6-9eb4-148ee589eacc.png)

![image](https://cloud.githubusercontent.com/assets/14036683/15103737/9fc166c2-15e1-11e6-9654-70e480a01c5d.png)

**Comment by woshijiangjialin** [comment]
哥们你那个bmap.html是在哪找到的，我也想做echarts3与百度地图结合，能不能发我一份？我邮箱：
jjlin2015@163.com
万分感谢

**Comment by hlwxyuan** [comment]
是由于百度地图v2.0添加了个性化样式设置（给option.bmap中添加了styleJson配置）造成的。详见https://www.cnblogs.com/bky419/p/16385972.html
