### ISSUE TITLE
添加标线数据格式，支持无x轴只有y轴值的数据标线

### ISSUE THREAD

**Issue by xubuild** [apache/incubator-echarts#3168]
#### 问题简述 (One-line summary)

在不知道x轴坐标范围时，无法通过markLine 标注y轴的值
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.1.7
- 浏览器类型和版本 (Browser version): 
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

markLine标线的数据数组现在有三种，但是当x轴数据是未知范围时，无法简单标注y轴。
例如，x轴为人名，y轴为分数，目的是添加60分的标线。当x轴数据为动态生成时，无法使用坐标的方法添加标线。
#### 期望结果 (Expected behaviour)

添加一种标线数据，例如：
{
        name: '及格',
        // 除 'average', 'min', 'max'外，添加type ‘value’
        type: 'value',
        value: 60
    },
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by netwww1** [comment]
对于这个仅与y轴值关联的水平线markline，我目前是通过添加一个由js填充y轴值数据的serie，然后设置样式为虚线，来模拟这个功能，如果需要改变这个markline值，则需要重新填充这个serie数组，然后setOption。楼主可参考下。
希望以后能在xAxis、yAxis里直接设置轴关联的markline。
