### ISSUE TITLE
Support symbol image as SVG

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3180]
I can use link to an image as: 
symbol:"image://xxx.png"

But can't use:
symbol:"image://xxx.svg"

Is there any reason for that or another way to use SVG links? As far as I know, canvas should render images in SVG format (different than path://)

**Comment by icarusion** [comment]
where should i put the image file?I set a image symbol,but can not show.?

**Comment by jarben** [comment]
You can use:
symbol:"image://your-image-url.png"

to show an image, note that this was shortly broken in 3.1.8
