### ISSUE TITLE
Sankey: emphasis on all links when node is hovered

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3187]
Currently, link highlights when hovered. It would be great if all node's links highlight when node is hovered. 

Current: 
![image](https://cloud.githubusercontent.com/assets/561365/15184705/9433fa8e-1796-11e6-96ca-b832669e62e0.png)

Highlighted links when Business & Productivity node is hovered: 
![image](https://cloud.githubusercontent.com/assets/561365/15184740/c0925ae4-1796-11e6-80cc-246136951c74.png)

**Comment by deqingli** [comment]
hi @jarben, Thank you for the suggestion, I will add this feature as soon as possible.

**Comment by jarben** [comment]
Awesome thanks @deqingli for looking at it!

**Comment by deqingli** [comment]
Hi @jarben,  I have added this feature, which will be released after 4.1.0, sorry for waiting so long.

best regards,
Deqing

**Comment by jarben** [comment]
That great new @deqingli , thanks for looking at it!

**Comment by SuperAL** [comment]
Is there any demo about this feature, my current echarts version is 4.1.0 yet I cannot see this effect, when I hover on node, only the node highlights. @deqingli

**Comment by deqingli** [comment]
hi @SuperAL, I have added the `focusNodeAdjacency` parameter in sankey series,  you can set the parameter with value `allEdges`,  `inEdges` and `outEdges`, you can try it. If you have any question you can reopen this issue.
