### ISSUE TITLE
当X轴的点只有1个或者2个时，以Y轴为基准的markline线画不出来

### ISSUE THREAD

**Issue by ryanypm** [apache/incubator-echarts#3191]
#### 问题简述 (One-line summary)

当X轴的点只有1个或者2个时，以Y轴为基准的markline线画不出来，
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):os x
#### 重现步骤 (Steps tmproduce)

1.
2.
#### 期望结果 (Expected behaviour)

markline x轴的起点位置和终点位置可以用像素来设置，或者自适应容器的left right
markline y轴用实际数据来确定位置
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/commit/1b25ac99c78644b78a2da58f855c87df98dd7300 提交中解决了这个问题，要在 x 轴上显示整条 markLine 可以写成：

```js
// 只设置整条线的数值
data: [{
  yAxis: 10
}]
// 或者讲 x 轴的两个端点设为无穷大
data: [ [{
  xAxis: -Infinity,
  yAxis: 10
}, {
  xAxis: Infinity,
  yAxis: 10
}] ] 
```
