### ISSUE TITLE
legend能否设置最多开启数量

### ISSUE THREAD

**Issue by wwj559** [apache/incubator-echarts#3206]
#### 问题简述 (One-line summary)

譬如折线图，可能series会很多，经常会有最多现实几个的需求，比如最多三个，最多五个，等等，能否在legend里面加入设置项

**Comment by pissang** [comment]
使用 http://echarts.baidu.com/option.html#legend.selected

**Comment by wwj559** [comment]
不，我的意思不是初始化三个on的， 而是一直限制最大on的数量。

譬如限制最大现实数量为3： 大娃-on 二娃-on 三娃-on 四娃-off 五娃-off 六娃-off 七娃-off

我现在点击四娃， 不能让四娃从off变成on。 我得先点一下大娃， 让大娃-off， 才能点击四娃，让它为on

**Comment by pissang** [comment]
目前没有相关配置项，只能监听图例筛选事件手动设置`legend.selected`
