### ISSUE TITLE
希望可以有直方图

### ISSUE THREAD

**Issue by ChenDanni** [apache/incubator-echarts#3207]
#### 问题简述 (One-line summary)

希望可以有直方图。找了半天没有找到，只有柱状图，如果有的话希望告知怎么画Orz
#### 其他信息 (Other comments)

谢谢

**Comment by realeve** [comment]
最近我也在做这部分的内容，初步打算是直接输入原始数据出直方图，其中柱形的宽度设宽一些，对应的分组和频率数据自己计算。

**Comment by cccccdn** [comment]
请问现在有什么方法能实现直方图的效果吗

**Comment by realeve** [comment]
maxBarWidth
