### ISSUE TITLE
折线(面积)图能不能根据横轴不同区间显示不同颜色区域

### ISSUE THREAD

**Issue by ZhuyuAndCoder** [apache/incubator-echarts#3209]
现在需求是这样的,我用折现面积图展示一天各时间点的用电信息,然后需要如:将12:00-15:00,20:00-23:00这些时间段的区域颜色展示成不同的如红色,请问该怎么做，效果如下
![image](https://cloud.githubusercontent.com/assets/17719076/15285583/a4dd5fb8-1b8a-11e6-8807-ce7208344e57.png)

**Comment by BaoShaoLiWJ** [comment]
我也有相同的需求，同问。

**Comment by Ovilia** [comment]
http://echarts.baidu.com/gallery/editor.html?c=area-simple

**Comment by ziloLiang** [comment]
`xAxis: {
  splitArea: {
   areaStyle: {
     color: ['rgba(0,0,0,1)', 'rgba(255,255,255,1)']
   }
 }
}`

color是个数组可以按你自己的需求修改颜色就好了

**Comment by ziloLiang** [comment]
如我有四个区域  希望第二个是红色背景 其他为白色

**Comment by ziloLiang** [comment]
`xAxis: { 
  splitArea: { 
   areaStyle: { 
    color: ['rgba(0,0,0,1)', 'rgba(255,255,255,1)'] 
   }
  }
 }`

color是个数组可以按你自己的需求修改颜色就好了

如我有四个区域 希望第二个是红色背景 其他为白色

color: ['rgba(255,255,255,1)', 'rgba(235,97,95,1)', 'rgba(255,255,255,1)', 'rgba(255,255,255,1)']

**Comment by ZhuyuAndCoder** [comment]
xAxis: { splitArea: { areaStyle: { color: ['rgba(0,0,0,1)', 'rgba(255,255,255,1)'] } } } 这样设置是可以得到不同的颜色区域，但是我需要的是在特定的时间区域内颜色指定。现在问题应该在splitArea的interval上，我怎么样能够把时间轴按自己的需求分隔区间，如01:00-07:00,07:00-15:00,15:00-23:00。

**Comment by ZhuyuAndCoder** [comment]
@ziloLiang xAxis: { splitArea: { areaStyle: { color: ['rgba(0,0,0,1)', 'rgba(255,255,255,1)'] } } } 这样设置是可以得到不同的颜色区域，但是我需要的是在特定的时间区域内颜色指定。现在问题应该在splitArea的interval上，我怎么样能够把时间轴按自己的需求分隔区间，如01:00-07:00,07:00-15:00,15:00-23:00。

**Comment by mirari** [comment]
我也有同样的需求，不知楼主现在是如何处理的？

**Comment by ZhuyuAndCoder** [comment]
@mirari 只用echarts并没有解决，加了自己写的div作为背景区域拼凑起来了。。。。

**Comment by mirari** [comment]
@ZhuyuAndCoder 自己写DIV……怎么确定区域大小的，尺寸不固定的话这工作量不小吧

**Comment by ZhuyuAndCoder** [comment]
@mirari 对，js取出图形区域宽高，然后百分比形式去偏移、定大小。

**Comment by mirari** [comment]
@ZhuyuAndCoder 我现在的做法是加了`
splitArea : {
                show : true,
                interval : 0,//显示所有分隔
                areaStyle : {
                    color: []
                }
            }
`
然后，遍历数据时，有多少条数据，就往color数组里加多少个颜色。

**Comment by ZhuyuAndCoder** [comment]
@mirari 每个区域的宽度好像不能自定义吧

**Comment by pissang** [comment]
马上发布的新版本可以实现折线图分段显示不同颜色，也支持通过 markArea 标记不同区间

**Comment by ZhuyuAndCoder** [comment]
这样问题就解决了

**Comment by pissang** [comment]
来一张效果图

![default](https://cloud.githubusercontent.com/assets/841551/16405296/153bcf22-3d39-11e6-880b-92bc03a09d79.png)

**Comment by mirari** [comment]
@ZhuyuAndCoder 分隔区域数量跟横坐标节点数量一致的时候，分隔区域宽度跟节点宽度就一样了。
![qq 20160628140747](https://cloud.githubusercontent.com/assets/4995159/16405370/bc3f4a10-3d39-11e6-9b05-b4e4cb7eb36f.jpg)
不过还是等新版本吧，我觉得这种做法可能大数据下性能会低，而且没法像上图这样给区域标注出文字

**Comment by ZhuyuAndCoder** [comment]
@mirari 新版本可以完美解决现在的问题。。。

**Comment by waitinghope** [comment]
@ZhuyuAndCoder 新版本指的是？我看现在最新的版本是用折线图做例子，可是如果想在柱状图标示背景区域呢？如果依然根据柱状图中心标记的话，就不对了。另外markArea有可以设置颜色的属性吗？thank you.

**Comment by mirari** [comment]
新版本的markArea使用了左开右闭的起止范围定义的方式，某些场合使用起来是比较方便的。
但是，以我的需求为例，如果我要高亮横坐标中的节假日，就需要将节假日区段的第一个点定义为起点，将节假日之后的第一个非节假日点定义为终点。但这个逻辑处理起来就非常复杂了，因为我的日期数据并非连续的，要考虑最后一个点就是节假日等等特例，在一个非连续的日期数组中计算出所有节假日标记的起点和终点非常繁琐，如果能直接用数组的形式标记所有节假日就会方便很多。

**Comment by Kevin170113664** [comment]
> 来一张效果图
> 
> ![default](https://cloud.githubusercontent.com/assets/841551/16405296/153bcf22-3d39-11e6-880b-92bc03a09d79.png)

@pissang 求问一下你的效果图里晚高峰markArea是怎么取到20:00和22:30这两个点的中间点的。
求相应的echarts option

**Comment by Kevin170113664** [comment]
> > 来一张效果图
> > ![default](https://cloud.githubusercontent.com/assets/841551/16405296/153bcf22-3d39-11e6-880b-92bc03a09d79.png)
> 
> @pissang 求问一下你的效果图里晚高峰markArea是怎么取到20:00和22:30这两个点的中间点的。
> 求相应的echarts option

噢噢我找到了，这个example在这里：http://www.echartsjs.com/examples/editor.html?c=line-sections
如果能帮到有需要的人，就好了……

**Comment by jimStyle88** [comment]
![image](https://user-images.githubusercontent.com/20588608/56197238-fa152380-606a-11e9-8a7a-984f54e282bc.png)
如上图所示，怎么把曲线以上的markarea 去掉。
