### ISSUE TITLE
地图上部分城市名称显示位置重叠。

### ISSUE THREAD

**Issue by tianr1190** [apache/incubator-echarts#3230]
#### 问题简述 (One-line summary)

3.19地图上部分城市的名称重叠在一起。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.19
- 浏览器类型和版本 (Browser version): ie11
- 操作系统类型和版本 (OS Version): win8.1
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/19337143/15344264/313bc064-1cd8-11e6-8909-3d3dbdb60639.png)

![image](https://cloud.githubusercontent.com/assets/19337143/15344484/f60a463a-1cd9-11e6-9dc8-5ade82a28942.png)

上海：
![image](https://cloud.githubusercontent.com/assets/19337143/15349581/69b24aca-1d06-11e6-8a55-b05f1e304f3b.png)

**Comment by pissang** [comment]
建议移上去的时候才显示城市名称

**Comment by tianr1190** [comment]
鼠标移上去比较没那么直观， 有些对地理位置比较小白的要找一下才能找到想要的地区在哪。2.0的时候，可以显示得很漂亮的呀， 3.0怎么就显示成这样了呢。

**Comment by fredwei** [comment]
同样遇到这个问题，但是修改json文件无效，后来在加载了json之后，直接修改地区名称坐标来达到修改地区名称位置目的，办法比较low

**Comment by tianr1190** [comment]
原本还以为是地图json文件的问题呢， 这么看来，不仅仅是json配置的问题那么简单了。

**Comment by Gyyi** [comment]
同遇到这个问题，官方有计划解决吗？

**Comment by tianr1190** [comment]
好像现在官方还是没有解决这个问题， 2.0 的版本能显示得很漂亮啊， 怎么到了3就显示得这么奇怪了呢？ 一直在期待官方能解决这个问题。

**Comment by pissang** [comment]
3 默认是按照省会的位置来显示名称的，省会位置定义在 geo 文件中，如果不需要的话按照下面代码去掉定义的省会，默认会采用地理位置的重点，注意需要在地图注册之后， setOption 之前使用

```js
myChart.getMap('china').geoJson.features.forEach(function (feature) {
  // Remove cp
  feature.properties.cp = null;
});
```

**Comment by EnhengBenben** [comment]
怎么让省市名称消失，划过的时候再显示？

**Comment by aaronwang062441** [comment]
我们也想问同样的问题，如何让“广东省”，显示成“广东”，“XXXX自治州”只显示成“XXXX”？

**Comment by zds-xiaoxianyu** [comment]
@aaronwang062441 暂时使用的是修改对应json数据的名称，如guangdong.json里的XXXX自治州改为XXXX，
而XXXX自治州.json文件名改为XXXX.json，这样再显示广东地图对应区域的名称已改，方法比较low，我是通过Json加载地图的

**Comment by gaolian1025** [comment]
这个怎么在项目中实现，为什么我的会重叠
