### ISSUE TITLE
鼠标放到图表上去如何获得鼠标对应x轴y轴的的值？

### ISSUE THREAD

**Issue by kcl2430** [apache/incubator-echarts#3251]
#### 问题简述 (One-line summary)

鼠标放到图表上去如何获得鼠标对应x轴y轴的的值？
#### 期望结果 (Expected behaviour)

![image](https://cloud.githubusercontent.com/assets/14937225/15416908/d2e614e0-1e82-11e6-9706-8a0eb586c4ee.png)

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/2540#issuecomment-176534872 参考这个，https://github.com/ecomfe/echarts/issues/3250 跟这个相同，先关闭了

**Comment by kcl2430** [comment]
谢谢

**Comment by kcl2430** [comment]
请问dataToPoint这个函数中的[lng, lat]是对应当前点x轴和y轴的值吗
// 获取系列
var seriesModel = myChart.getModel().getSeriesByIndex(0)
// 获取地理坐标系实例
var coordSys = seriesModel.coordinateSystem;
// dataToPoint 相当于 getPosByGeo
var point = coordSys.dataToPoint([lng, lat]);
// pointToData 相当于 getGeoByPos
var coord = coordSys.dataToPoint(point);

**Comment by pissang** [comment]
是的
