### ISSUE TITLE
请问，可否实现echarts与qt quick的qml的canvas集成？

### ISSUE THREAD

**Issue by fsdajlkl** [apache/incubator-echarts#3252]
我现在使用qtquick做一个项目，发现echarts效果很炫，就想集成到项目里面，但是不知道如何使用echarts在canvas里面直接绘制我想要的图表呢

**Comment by pissang** [comment]
需要兼容 html canvas 的接口

**Comment by toby20130333** [comment]
@pissang 是兼容html和canvas大部分接口，有个charts.js是可以移植到qt上面的
