### ISSUE TITLE
在地图标线中如何让data中的数据按列表的先后顺序显示？

### ISSUE THREAD

**Issue by benywon** [apache/incubator-echarts#3254]
#### 问题简述 (One-line summary)

您好！
我现在想做一个“旅游足迹”类似的图片，已经有了按时间排列的经纬度信息，但是现在的 地图标线应用（如下图：）
![image](https://cloud.githubusercontent.com/assets/8955304/15423790/bc59cd46-1eb1-11e6-8299-8156bf2022e9.png)
请问如何让两条线中的动态圆点按先后顺序出现啊，我想从北京到兰州，再从兰州到广州。

谢谢！！
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.10
- 浏览器类型和版本 (Browser version): chrome
- 操作系统类型和版本 (OS Version): windows

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/gallery/editor.html?c=graph-life-expectancy
