### ISSUE TITLE
time类型的X轴如何让label按照固定的间隔展示

### ISSUE THREAD

**Issue by WebsonLeo** [apache/incubator-echarts#3260]
#### 问题简述 (One-line summary)

当X轴的类型为time时，我想还是延用echarts本身的根据数据内容确定X轴label的展示格式，但是echarts本身的X轴的label展示间隔不太符合项目的展示需求，我想对label的展示间隔进行设置，请问需要如何处理？如果暂时没有方法处理的，可否提供可行性方案？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts 3.1.7):
- 浏览器类型和版本 (Chrome 50.0.2661.102 m):
- 操作系统类型和版本 (windows7 专业版):
#### 期望结果 (Expected behaviour)

期望能够自己设置展示的方式或者间隔

**Comment by pissang** [comment]
设置 xAxis.interval

**Comment by Malphite** [comment]
我有同样的问题需求，请问在echarts v2.2.7中如何解决呢，谢谢

**Comment by Sijiu** [comment]
xAxis.interval :'auto'的时候，不是均匀分割的情况下怎么右侧grid的border消失了，echart2的时候没有这个问题的。官网的demo中也存在这个问题。
![Uploading R0`$}JMAC{7)IB_L{J`}_84.png…]()

**Comment by pissang** [comment]
3 里默认是不显示 grid 的

**Comment by Sijiu** [comment]
应该是我描述有问题，就是右边的边线没有了，感觉图表好像不完整(其实是完整的)这个很影响外观。[实例图](https://github.com/Sijiu/mes-board/blob/master/imgs/no-right-border.jpg)

**Comment by pissang** [comment]
我就是这个意思，因为间隔显示的原因导致有可能导致 x 轴的分隔线最后一条不显示，但是因为 2 的 grid 是默认显示的，所以右边看着还是有边线，3 里的 grid 默认不显示，你设成 grid: { show: true } 就行了

**Comment by Sijiu** [comment]
刚设置成功了，谢谢您的回答，好快。还有一个小问题怎么让最后的日期显示，不是全部设置让x轴显示，就是这种下能设置让最有的总是显示吗？[示例](https://github.com/Sijiu/mes-board/blob/master/imgs/2016-06-22.png)

**Comment by pissang** [comment]
没有特别方便的方法，x 轴是 category 类型的话，xAxis.axisLabel.interval 可以是一个决定每个刻度是否显示的回调函数，可以判断一下是否是最后一个刻度然后返回 true 强制显示

**Comment by Sijiu** [comment]
好的，感谢点拨。

**Comment by BLinL** [comment]
我有一个办法，就是不要设置x轴为‘time’,而是设置为‘category’，然后设置xAxis.axisLabel.interval
