### ISSUE TITLE
散点图的坐标轴以及toolTips或legend

### ISSUE THREAD

**Issue by hxxgy** [apache/incubator-echarts#3265]
#### 问题简述 (One-line summary)
1. 请问坐标轴怎么改成有箭头的方式，我type改成value后，好像还是没效果。
2. 然后坐标轴的position只有bottom和top，我想让轴上的标点紧贴着坐标轴线，就像平常我们画坐标轴那样的形式，怎么实现？
3. 关于坐标轴里的每个散点，我想让每个点旁边都有和legend一样的值，而不仅仅是通过legend上的颜色来区分，怎样实现？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):  3.0
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/16161308/15472511/17542baa-212e-11e6-89db-f6575a3f618f.png)

**Comment by pissang** [comment]
1. 暂时不行
2. 
3. 通过 [label.normal.tooltip](http://echarts.baidu.com/option.html#series-scatter.label)

**Comment by hxxgy** [comment]
谢谢解答。
需求就和我上传的那张图一样， X、Y坐标轴上的每个单位数字都是紧贴着坐标轴的
第三点也是同图片一样，每个点都有自己的文字说明

**Comment by pissang** [comment]
那第二点也暂时无法实现
