### ISSUE TITLE
如何主动调用saveAsImage事件

### ISSUE THREAD

**Issue by r4nqian** [apache/incubator-echarts#3272]
我想通过外部的一个button按钮触发保存图片的事件，该如何写？

**Comment by cappuccima** [comment]
先把图表转成图片，通过官方的api获得一个base64地址。

`var img = new Image();
img.src = mentionTrend.getDataURL({
	pixelRatio: 2,
	backgroundColor: '#fff'
});`

参见官方api [http://echarts.baidu.com/api.html#echartsInstance.getDataURL](http://echarts.baidu.com/api.html#echartsInstance.getDataURL)

**Comment by CR7LOVE** [comment]
@cappuccima  我这样写了以后，network中可以看到，但是用户看不到下载，这个怎样做啊？

**Comment by chfw** [comment]
https://github.com/eligrey/FileSaver.js
