### ISSUE TITLE
echarts3如何实现2.0版本里地图标注的效果

### ISSUE THREAD

**Issue by zzm305305** [apache/incubator-echarts#3289]
我用3.0版本的echarts
如何实现2.0里地图标注的效果
http://echarts.baidu.com/echarts2/doc/example/map15.html

ECharts 版本 最新版:
chrome 最新版
win7 64位
借助3.0版本里的散点图即effectScatter想实现城市VV统计，圆点呼吸闪动效果。但貌似现在支持涟漪特效。请问有什么办法吗？
参考了：http://echarts.baidu.com/demo.html#effectScatter-map

**Comment by pissang** [comment]
暂时只支持涟漪特效，后续可以考虑加回呼吸特效

**Comment by zzm305305** [comment]
感谢，期待后续支持

**Comment by jun58** [comment]
@pissang 现在echarts3支持呼吸效果了吗？
