### ISSUE TITLE
echarts2如何添加一条平行于x轴的标示线

### ISSUE THREAD

**Issue by a1314xu** [apache/incubator-echarts#3294]
#### 问题简述 (One-line summary)

echarts2 我手动控制x轴终点，然后添加一条平行于x轴的标示线，但是当移动timeline时，markline标示线就会消失
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):2
- 浏览器类型和版本 (Browser version):chrome39
- 操作系统类型和版本 (OS Version):win7
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

生成一个平行于X轴的标示线方法
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by territoryfan** [comment]
@a1314xu  https://github.com/territoryfan/echarts 图三效果不知道是否能帮到你
