### ISSUE TITLE
力导向图节点拖曳事件会与click事件同时触发

### ISSUE THREAD

**Issue by ds205615** [apache/incubator-echarts#3315]
力导向图节点拖曳事件会与click事件同时触发

**Comment by giscafer** [comment]
看到我也补充一点。我的统计图map在拖拽也会触发click，这个我再地图拖拽的时候也会触发地图的点击事件，但是我点击事件绑定了处理函数，拖拽的时候需要避免点击，看怎么处理这个问题。。。。。

**Comment by imingyu** [comment]
这个问题我也遇到了，使用map图表，拖拽时click也是触发的，如果在click中判断是否是拖拽就好说了。

**Comment by itDjango** [comment]
这个问题解决了吗 拖拽关系图 会触发点击事件？
