### ISSUE TITLE
如何实现不规则统计表

### ISSUE THREAD

**Issue by cakey90** [apache/incubator-echarts#3316]
#### 问题简述 (One-line summary)

当前的柱状图统计表分类都是固定的,比如分类为谷歌和百度,年份为2010年至2016年,那么统计图里从2010年至2016年必定都有谷歌和百度的份额.然而现在有挺多行业,需要一些不规律的统计,比如多个柱状图的结果放在同一个统计表中,但是分类又不是固定的,如现在有分类香烟(子分类为A,B),名酒(子类A,B,C),这样的情况下,X轴只是作为父标签和子标签的显示,Y轴是作为数据的显示,现在的,现在的柱状图很难实现,勉强实现后,分类间隔还会因为子分类数量不同而空出
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3
- 浏览器类型和版本 (Browser version):谷歌浏览器50.0.2661.94 m
- 操作系统类型和版本 (OS Version):win10
#### 重现步骤 (Steps to reproduce)

1.现在有分类香烟(子分类为A,B),名酒(子类A,B,C),这样的情况下,X轴只是作为父标签和子标签的显示,Y轴是作为数据的显示
2.如何从左到右将父子分类同时展示其数据
#### 期望结果 (Expected behaviour)

希望能出一个柱状图的不规则分类统计图
## 
#### ECharts配置项 (ECharts option)

``` javascript
option = {
--
}

```
#### 其他信息 (Other comments)

![qq 20160531175738](https://cloud.githubusercontent.com/assets/6037403/15670673/35f50058-2759-11e6-8ab8-8fff8ae66193.png)

**Comment by dongkang1993** [comment]
最后怎么解决的？
