### ISSUE TITLE
关于Echarts官网平行坐标的示例tooltip不显示的问题

### ISSUE THREAD

**Issue by zjx1195688876** [apache/incubator-echarts#3357]
#### 版本及环境 (Version & Environment)
- ECharts版本： ECharts3.1.10
- 浏览器及版本：Chrome 44.0.2403.155 m
- 操作系统Windows8.1
#### 重现步骤 (Steps to reproduce)

1.访问Echarts官网示例：http://echarts.baidu.com/demo.html#parallel-aqi
#### 期望结果 (Expected behaviour)

1.tooltip正常显示
#### ECharts配置项 (ECharts option)

配置项同官方平行坐标示例

**Comment by wuyungen1996** [comment]
同问

**Comment by lkbtt** [comment]
真坑，百度团队居然解决不了这问题

**Comment by wuyungen1996** [comment]
> 真坑，百度团队居然解决不了这问题

后来改用highchart解决了这个问题

**Comment by lkbtt** [comment]
> > 真坑，百度团队居然解决不了这问题
> 
> 后来改用highchart解决了这个问题

可以分享一下么？

**Comment by wuyungen1996** [comment]
> > > 真坑，百度团队居然解决不了这问题
> > 
> > 
> > 后来改用highchart解决了这个问题
> 
> 可以分享一下么？

https://www.highcharts.com.cn/demo/highcharts/parallel-coordinates/sand-signika
highcharts的平行坐标轴支持tooltip
