### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by tapia** [apache/incubator-echarts#3369]
I've been browsing the [ECharts3 example page](http://echarts.baidu.com/examples.html), and I'm absolutely astonished about how powerful this library looks. It looks much more powerful than highcharts, fusioncharts or google charts. But, as long as it's only documented in chinese, it's really hard for any non-chinese developer to use it. It's a pitty, because all the comments in the source code, and even the commit messages are in english. 

Are there any plans of publishing english documentation? I'm sure that it would become the de facto web charting library in no time.

**Comment by Ovilia** [comment]
Thanks for your favor upon ECharts. 😄 
We are working hard on the English documentation, along with English tutorial, and so on. 
We do hope more people around the world have access to ECharts. You may follow our twitter https://twitter.com/EChartsJs for upcoming news.

**Comment by grafa** [comment]
Hi there guys,

I have to say echarts are really big gun ;) The only downside is lack of english docs. Event the builder on website is (almost) in chinese.

Can you please give us any updates how is it going with english docs?
Thanks!

**Comment by Ovilia** [comment]
@grafa Thank you grafa, here's the English document. Tell me if you need anything else. :)

https://ecomfe.github.io/echarts-doc/public/en/option.html
https://ecomfe.github.io/echarts-doc/public/en/tutorial.html
