### ISSUE TITLE
Sankey diagram gets reordered on resize/legend change/map roam

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3390]
I have a sankey diagram in a map like this: 

![image](https://cloud.githubusercontent.com/assets/561365/15895004/39b9181a-2d89-11e6-90d8-15f0774f35cc.png)

nodes and links are sorted on load, however, when window is resized, legend changed or map roamed, it changes into this: 

![image](https://cloud.githubusercontent.com/assets/561365/15895026/5e729820-2d89-11e6-8784-fc4b2ea15c5e.png)

You can reproduce this issue by resizing chart view in this example: http://echarts.baidu.com/demo.html#sankey-energy

Version: 3.1.10

**Comment by deqingli** [comment]
Hi @jarben, I have fixed this problem, which will be released next version. Now nodes sort by the order in series.data and will not be changed when you resize the diagram. Thanks for your suggestions!

**Comment by deqingli** [comment]
If there any problem after you try the new version, please reopen this issue.

**Comment by jarben** [comment]
Hi @deqingli , this is great news! Thanks for looking at it! Will test once the release is out:) 

Thanks, 
Jaro

**Comment by Chandru1427** [comment]
Hi @deqingli , is it possible to use zoom-in and zoom-out options in toolbox icon view, instead of using in world map  , series --> roam with scaleLimit.

Thanks, 
chandru
