### ISSUE TITLE
Area with different background in Line charts

### ISSUE THREAD

**Issue by gabrielenosso** [apache/incubator-echarts#3395]
Hi, I would like to have an area of my chart with a different background, to highlight that part of the graph.
I tried to use splitArea, but there is no way to configure it in the way I want (it loops intervals).

Is there a way to do it?
I found in the code something about a "markArea", but I couldn't find any documentation about it.

I attach an image with an example:
![iwas cc event odds](https://cloud.githubusercontent.com/assets/4018887/15965554/df235b12-2f1e-11e6-9c28-a171b2731ee4.png)

**Comment by 100pah** [comment]
`markArea` will be published in next version a few days later. Stay tuned!

**Comment by gabrielenosso** [comment]
Is there any ETA? more or less.. (days, weeks, months..)
