### ISSUE TITLE
Line chart with disconnected points

### ISSUE THREAD

**Issue by gabrielenosso** [apache/incubator-echarts#3416]
Is it possible to have a line chart but with only some points connected?
For example, I want to connect only the points which are close (in the graph)
or which have a short time distance between each other (considering that I have a X axis that works as a timeline).

Example:
![iwas cc event odds](https://cloud.githubusercontent.com/assets/4018887/16002535/7a9f41b0-3158-11e6-9d7c-ba2b0dd47cb9.png)

**Comment by pissang** [comment]
null data or '-' data can be used if you don't want two adjacent data connected

**Comment by gabrielenosso** [comment]
It's not the same thing: if you use '-' you won't get the Symbol.
But I want the Symbol, and I would like to have some of them not connected between each other :)

**Comment by pissang** [comment]
In this case maybe `graph` chart is a better choice than line. Here is an example http://echarts.baidu.com/gallery/editor.html?c=graph-life-expectancy

But it's usage is a bit more complicated. You need to use a `links` property to define the connected points by your own.

**Comment by eljefedelrodeodeljefe** [comment]
I think this should be reopened as a feature (if not already done). Graph doesn't really work for this and the intermittent should just be filled as you would expect from any, say, python data viz lirbary.

**Comment by pasch82-code** [comment]
I think it should be reopened as a feature. Im my queries I can't automatically add null points.
If I display the graph with a line, I should be able to choose whether or not to connect/disconnect the line, at least with which timespan. Grafana is doing something similar https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/time-series/#disconnect-values
