### ISSUE TITLE
[bug]饼图 -> toolbox -> 数据视图编辑数据功能的bug

### ISSUE THREAD

**Issue by ww-k** [apache/incubator-echarts#3425]
#### 问题简述 (One-line summary)

数据数据中编辑数据功能，不能修改已经存在的data的name，只能修改value。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):  3.1.10
- 浏览器类型和版本 (Browser version): chrome 51
- 操作系统类型和版本 (OS Version): window10
#### 重现步骤 (Steps to reproduce)

访问： http://echarts.baidu.com/demo.html#pie-roseType
点击数据视图, 修改为以下数据
`
半径模式
rose1   10
rose2   5
rose3   15
rose4   25
rose5   20
rose6   35
rose7   30
rose8   40

---

面积模式
roseTest    10
`
点击刷新，面积模式饼图依然显示rose1。
#### 期望结果 (Expected behaviour)

点击刷新，面积模式饼图依然显示roseTest。

**Comment by kevinwon1985** [comment]
###更多的测试例子：

重现步骤 (Steps to reproduce)

访问： http://echarts.baidu.com/demo.html#pie-roseType
点击数据视图, 修改为以下数据
`
半径模式
rose1 10
rose2 5
rose3 15
rose4 25
rose5 20
rose6 35
rose7 30
rose8 40

面积模式
rose1	10
rose9	40
rose2	5
rose3	15
rose4	25
rose5	20
rose6	35
rose7	30
rose8	40
`
点击刷新，面积模式饼图，data分别为
`
rose1	10
rose2	40
rose3	5
rose4	15
rose5	25
rose6	20
rose7	35
rose8	30
rose8	40
`
