### ISSUE TITLE
Y轴能否不均匀分布

### ISSUE THREAD

**Issue by Leesson** [apache/incubator-echarts#3430]
#### 问题简述 (One-line summary)

对于散点图（我用的是scatter），能否实现Y轴分布根据数据正态分布调整，而不是均匀的几个像素代表固定数据区间。我的数据分布相对比较集中，但是数据区间范围又比较大，初始化后图表上的点在y轴某个刻度比较集中，成线状分布，影响图表识别和美观度。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):*
- 操作系统类型和版本 (OS Version):*
#### 期望结果 (Expected behaviour)

初始化时y轴的刻度划分根据数据的正态分布调整，不均匀划分，使图表看起来更美观，避免当数据比较集中时图表中的点堆积在一起，而其他区域比较空旷。
#### 可能哪里有问题 (What went wrong)

配置项中没有找到相关设置参数，不确定是否有此功能
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
可以配置为 log 类型

**Comment by Leesson** [comment]
谢谢，但是配置为log类型之后并不能根据数据的分布对Y轴数据区间范围的长短进行调整，只是固定的根据对数公式进行划分，对于数据范围大但密集分布在小区段内的数据拉伸效果并不明显

**Comment by pissang** [comment]
那可以考虑下根据自己需要映射数据到小范围后传入，然后使用 formatter 将坐标轴的刻度值映射回原来的值

**Comment by shikelong** [comment]
请问楼主你最后怎么解决这个问题的？

**Comment by Leesson** [comment]
感谢 pissang。最近有点事情需要处理，没注意这里，不好意思。
to shikelong，目前还没解决。等有时间了根据pissang的建议试试再回复

**Comment by lcoder** [comment]
我也遇到了，百分比的柱状图，max最多为100%，但是数据都是99.99多的，区别不是很明显，想让差别大点？有什么办法么？log我看了下是对数，应该不是这个解决方案吧。

**Comment by woshixixi** [comment]
这个方法能解决吗 怎么样能映射数据到指定的分布后，在formatter回来呢？formatter只能给定y位置的进行改造，并不能增加y轴的刻度呢？
比如我想显示 log值的刻度为：0 0.001 0.005 0.008 0.01 0.05 0.08 0.1 0.5 0.8 1 这种怎么显示呢
@pissang

**Comment by CathyZYF** [comment]
> 考虑下根据自己需要映射数据到指定的分布后传入，然后使用 formatter 将坐标轴的刻度值映射回原来的值

我遇到一个类似的问题，需要建立一个分布不均匀的数值轴（y轴），请问“根据自己需要映射数据到指定的分布后传入”这句话是什么意思？能举例说明吗？
