### ISSUE TITLE
echarts3.x地图geojson是否支持绘制线linestring类型

### ISSUE THREAD

**Issue by weiletian28** [apache/incubator-echarts#3432]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行，可以考虑支持

**Comment by qingyunwhu** [comment]
强烈建议支持点和线绘制，目前貌似就只能多边形

**Comment by IdenPin** [comment]
@pissang    请问linestring现在支持了吗？
