### ISSUE TITLE
echarts lines effect loop报错(急)

### ISSUE THREAD

**Issue by oneroundseven** [apache/incubator-echarts#3450]
#### 问题简述 (One-line summary)

1、使用未公示的配置loop 

``` javascript
                effect : {
                    symbol: 'arrow',
                    symbolSize: 2,
                    show: true,
                    period: 2,
                    loop: false,
                    callback: null,
                    trailLength: 0.1
                }
```

2、第一次往data里面添加数据是没有问题的，但是清空完数据，再次添加数据的时候，会报错

``` javascript
        symbol.setStyle('shadowColor', color);
```

这里直接报symbol为undefined 初步猜测是因为使用了loop的原因
因为loop:false后会在动画结束后移除symbol对象

``` javascript
                animator.done(function () {
                    self.remove(symbol);
                });
```

还发现有另外一个问题，就是 animator.done的回调不是每次都调用，当数据清空后，再次添加数据的时候，第一次会不走回调；

求解决办法

**Comment by oneroundseven** [comment]
找到部分问题所在；
当lines的data默认有一条数据，然后通过setOption动态添加会导致animator.done异常；
结果只执行一次回调，有一次会被忽略；

**Comment by oneroundseven** [comment]
@pissang  还有一个2个动画回调执行一次的问题没有解决 仍然存在 报错那个已经OK

**Comment by pissang** [comment]
第二个问题不太清楚你的意思，我这照你的描述试了下没什么问题，不过在有残影的时候不循环是可能会造成动画结束后部分残影不会被清除的问题

**Comment by oneroundseven** [comment]
@pissang   
我再描述一次， 我这边默认地图上是没有线的
1、通过按钮点击，执行setOption方法忘lines的data里面随机增加一条线的数据，具体lines  options如下
````javascript
            {
                type: 'lines',
                zlevel:1,
                effect : {
                    symbol: 'arrow',
                    symbolSize: 2,
                    show: true,
                    period: 2,
                    loop: false,
                    callback: null,
                    trailLength: 0.1
                },
                lineStyle: {
                    normal: {
                        width: 0,
                        color: '#FFF',
                        curveness: 0.1
                    }
                },
                animation: false,
                animationUpdateDuration: 0,
                data: [/*[ { coord : [-117.24, 34.45] }, { coord : [121.48, 31, 20] } ]*/]
            }
````
2、这种配置下，默认lines应该只是有动画效果；
3、我这边动画循环设置的false，然后自己在源码里面加了一个回调函数 EffectLine.js中增加的；
````javascript
            if (!loop) {
                var self = this;
                animator.done(function () {
                    console.log(idx, animator._doneList);
                    callback && callback(lineData.getRawDataItem(idx));
                    self.remove(symbol);
                });
            }
````
4、在地图上增加一条线，这个时候动画执行是有时间的，当第一条线的动画还没有执行结束的时候，再次增加一条线，这个时候观察回调函数的回调次数，你会发现，2条线，只调用了第一条线的回调函数，第二条线的回调函数有执行；
5、我本地是给每个数据加了一个随机的数据戳，所以看起来很明显，数据格式如下；
````javascript
[ { coord : [-117.24, 34.45], tag:'唯一不重复的戳' }, { coord : [121.48, 31, 20], tag:'唯一不重复的戳' } ]
`````
6、给你附上一张戳的截图;
![20160620112207](https://cloud.githubusercontent.com/assets/1825295/16182469/4aaa65e4-36d9-11e6-9fa2-3bd09172cb19.jpg)
7、今天把echarts换成开发调试模式，看到报错信息了；

不知道这样能否明白；

**Comment by pissang** [comment]
关键的复现步骤是第四步？我这还是无法复现，你把有错误的项目打包发我看下？

**Comment by oneroundseven** [comment]
@pissang  是的 关键是第四步 那我写个demo发你吧 应该本地就可以调试出来的 稍等啊

**Comment by oneroundseven** [comment]
@pissang  收到邮件了吧~

**Comment by pissang** [comment]
收到了，应该就是因为这个报错的原因导致没进入到动画结束的回调，你改成 continue 也是无法进入

**Comment by oneroundseven** [comment]
@pissang  你哪里编译完执行是2次回调么？ 我代码全部还原 重新搞还是只有一次。。。。
你可以把你编译好的发我一份？

**Comment by oneroundseven** [comment]
@pissang  按照你说的全部编译后 直接调用echarts.js 会直接报错的
错误内容： echarts.js:18260 Uncaught TypeError: Cannot read property '_needsRemove' of undefined

**Comment by pissang** [comment]
我这也是每次都会执行.....

**Comment by oneroundseven** [comment]
@pissang  问个问题 我发你那个demo上 你连续点击添加多个点， 停止后，最后地图上是空的么？
你可不可以把你生成的发我一份 ....

**Comment by pissang** [comment]
![bug](https://cloud.githubusercontent.com/assets/841551/16187600/d53b2ebc-3703-11e6-94ac-67ebc424a653.gif)

**Comment by oneroundseven** [comment]
@pissang  我测了下不重置linee data数据的情况下 确实可以回调正常， 但是当回调函数里面重置data数据的时候就不行了；就会导致回调调用异常

**Comment by pissang** [comment]
重置有可能会导致之前的动画被移除

**Comment by oneroundseven** [comment]
@pissang  问题就在这里，我就是要在回调里面移除数据，呃，总算沟通好了，谢谢支持！~，期待改进

**Comment by flash59** [comment]
loop为false时，在有残影的时候，动画播放完，但残影不会被消除，如何能解决？我也遇到了这个问题，有没有好的办法？

**Comment by flash59** [comment]
@pissang loop为false时，在有残影的时候，动画播放完，但残影不会被消除，如何能解决？我也遇到了这个问题，有没有好的办法？

**Comment by 2690596991** [comment]
我想问问那个effect执行完的回调是需要写到源码中吗?我看echarts官方文档里面seires中的effect好像没有callback
