### ISSUE TITLE
x轴为时间轴的断点间隔

### ISSUE THREAD

**Issue by ramsaylee** [apache/incubator-echarts#3454]
请教一个问题，echarts可不可以在`xAxis`的`type`为`time`的情况下设置断点间隔？
例如，我有从早上`01:00`开始到晚上`23:00`结束的数据，但是`09:00`到`10:00`这一个小时是没有数据的（或者这一个小时的数据我不想显示在图上），我想把这部分在`xAxis`上隐藏（折叠）掉，可以做到吗？
类似于`highcharts`的`xAxis.breaks` http://api.highcharts.com/highcharts#xAxis.breaks 这个配置项。
我看了文档跟github上的issue没有找到类似的配置项或相关问题。对于这种需求，在echarts中一定要用`type`为`category`的类目轴来实现吗？

谢谢。

**Comment by ramsaylee** [comment]
请问一下这个需求有办法实现吗？我测试过在`xAxis`的`type`为`time`的情况下，如果中间一段时间（例如`09:00-10:00`）没有数据的话，就会把`08:59`跟`10:01`这两个点连起来，但是中间间隔还是在的。有办法实现像我上面提到的`highcharts`的`xAxis.breaks`这样的功能吗？
谢谢。

**Comment by ramsaylee** [comment]
这个需求最后还是把时间轴换成了类目轴实现的，但是换成类目轴之后性能比（同样多的20000+点）时间轴要弱（主要表现在tooltip基本上不跟鼠标），不知道为什么，不过暂时这样可以实现需求。
@pissang 请问一下除了用类目轴之外，如果一定要用时间轴的话，能否实现这个需求呢，或者有没有什么建议？如果不行的话，```echarts```有没有计划增加这个```xAxis.breaks```功能？这个需求应该是蛮常见的，例如画股票分时图的时候，```11:30```-```13:00```的数据就是不要的。
谢谢。

**Comment by pissang** [comment]
tooltip 不跟鼠标是因为动画的原因

**Comment by ramsaylee** [comment]
@pissang 多谢回复，我之前是把```option```配置项最外一层的```animation```设为```false```了，明天试试看您的建议，顺便确定一下```animation```配置的优先级。
不过还是希望```echarts```能考虑在后续增加```breaks```，在很多应用场景下会更方便一些。
非常感谢。

**Comment by pissang** [comment]
嗯，我们考虑下这个需求，谢谢建议

**Comment by ZTjack** [comment]
遇到和ramsaylee一样的问题，请问现在有什么更好的解决方案吗，谢谢？ @pissang

**Comment by ZTjack** [comment]
类似于这个gapSize的配置项，http://api.highcharts.com/highstock/series%3Cline%3E.gapSize

**Comment by Seeley** [comment]
@ramsaylee 用类目轴.. 不会把所有的9:30 到下午3点的时间段都枚举出来了吧 还是用别的上面方法 碰到同样问题 请教一下

**Comment by LiuXiaoJie** [comment]
股票…时间坐标轴遇到同样问题，希望能考虑这个需求 @pissang

**Comment by xoptimal** [comment]
@ramsaylee  请问这个问题怎么解决的~

**Comment by xoptimal** [comment]
在xAxis type = time 的情况下, 如果直接跳过11:30-13:00 这个时间段  @pissang

**Comment by 100pah** [comment]
https://www.echartsjs.com/option.html#series-line.connectNulls

**Comment by xoptimal** [comment]
@100pah  这个不是的， 这个只是不相连， 我是想直接跳过，直接不要这段，看看上证指数的走势图就知道了

**Comment by superduke** [comment]
同此需求，可有除类目轴以外的更好的方法？

**Comment by MinutesSneezer** [comment]
同样遇到了这个问题，也是在显示类似「五日分时图」这样的图表时遇到的。不知除了枚举类目还有别的方法吗？

**Comment by kentio** [comment]
It has been 8 years and this issue still hasn't been resolved.

**Comment by helgasoft** [comment]
@kentio, I think the issue has been resolved 8 years ago with the alternative axis type 'category'. See mentioned [official example](https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh).
The above referenced Highcharts options are:
- [xAxis.breaks](http://api.highcharts.com/highcharts#xAxis.breaks) - how is this a good idea when gaps are **explicitly** defined in code as an array?
- [series.gapSize](https://api.highcharts.com/highstock/series.line.gapSize) - makes more sense, but it's to actually **show the gaps**, not to hide them. Could be done in ECharts by inserting empty data where the gaps are.

Axis type _time_ has nice formatting, but it is for _"continuous time series data"_. Once the data has gaps it becomes _'discrete category data'_ suitable for _category_ axis.
