### ISSUE TITLE
饼图默认label

### ISSUE THREAD

**Issue by wanzhou** [apache/incubator-echarts#3465]
#### 问题简述 (One-line summary)

饼图没有方法添加默认的label（饼图中间显示默认一直显示某个label），我看了api和option介绍，好像没有提到，是不是要通过其他方式来实现，怎么弄？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.1.10
- 浏览器类型和版本 (Browser version): chrome 51.0
- 操作系统类型和版本 (OS Version): mac osx 10.11.5
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
饼图中间显示的 label 可以通过一个 title 组件做到

```js
title: {
  text: '某个标签'
  left: 'center',
  top: 'center'
}
```
