### ISSUE TITLE
xAxis time with different labels

### ISSUE THREAD

**Issue by gabrielenosso** [apache/incubator-echarts#3476]
Hi, I have a set of records where each record has two values: 'date' (timestamp) and 'status' (number).

I would like to use the xAxis of type time, so that the values are shown on a timeline.
But I want to show as labels of the axis the correspondent 'status' values.

Is there a way to achieve that?

Record example: { date: new Date(), status: 42, value: 1.2 }

**Comment by pissang** [comment]
You can use formatter to add custom text in label.
```js
xAxis: {
  axisLabl: {
    formatter: function (timestamp) { return ''; }
  }
}

**Comment by gabrielenosso** [comment]
The problem is that I don't have access to the other values of the record in the formatter function.
Moreover, using the xAxis as a "time" axis, it can take any time value, not just the ones that have data.

Example: if you have 2 timestamps corresponding to the 2 dates 01/06/2016 10:00 and 01/06/2016 11:00  (so only the time is different), it can show a label with 10:30 in the middle...
