### ISSUE TITLE
地图上添加图片mark能否实现

### ISSUE THREAD

**Issue by giscafer** [apache/incubator-echarts#3477]
现在有个需求，需要在map统计图上添加一个mark（在map上用一张小图标展示一个已知经纬度的点）
echarts能否支持？

或者zrender是否可以实现，或者给个实现思路？3q
@pissang

**Comment by pissang** [comment]
试试用 markPoint：
```js
series: [{
  type: 'map',
  markPoint: {
    // 设置 symbol 为图片，url是图片链接
    symbol: 'image://url'
    data: [ { coord: [lng, lat] } ]
  }
}]
```

**Comment by zhutai** [comment]
@pissang 不是说在echarts3.0中已经把markPoint在map的功能取消掉了吗？

**Comment by zhutai** [comment]
在线等呀！还请帮帮忙！

**Comment by pissang** [comment]
支持的

**Comment by zhutai** [comment]
markPoint: {          
                        name:"China",
                        symbol:"images/colorgreen.png",
                        symbolSize: 12,},
 geoCoord: {
                        'China': [124.753192,46.034159],},

能帮忙看下为什么出不来吗？今天钻了一天了

**Comment by zhutai** [comment]
![qq 20160630194233](https://cloud.githubusercontent.com/assets/19645584/16487066/203ceba4-3efb-11e6-8659-073ce3ee4c9a.png)


@pissang  能帮忙看下为什么出不来吗？今天钻了一天了

**Comment by pissang** [comment]
看我上面评论里的代码，geoCoord 改成 coord

**Comment by zhutai** [comment]
![qq 20160630194233](https://cloud.githubusercontent.com/assets/19645584/16487090/42372198-3efb-11e6-9d5e-9811d7e6cf2c.png)

**Comment by giscafer** [comment]
@zhutai 没任何问题，支持的。

**Comment by giscafer** [comment]
@pissang 还有个疑问，我现在有gesjson格式的点图层数据，但是配置到地图上看不出来，因为颜色和面图层都一样，所以我想问的是，点图层能不能使用
`
series: [{
  type: 'map',
 mapType: '点图层名称',


}]

`
然后又没有方式通过图片直接渲染，类似下边（只不过markPoint的坐标点需要在coord给出）
  markPoint: {
    // 设置 symbol 为图片，url是图片链接
    symbol: 'image://url'
    data: [ { coord: [lng, lat] } ]
  }

**Comment by pissang** [comment]
@giscafer 不太理解你的问题，下边那种方式跟前面提到的区别是？
