### ISSUE TITLE
lines 能否使用平面矩形内的像素点作为定位，而不只是使用经纬度定位？

### ISSUE THREAD

**Issue by luozhihua** [apache/incubator-echarts#3491]
#### 问题简述 (One-line summary)

我看到迁徙图里面的飞机轨迹非常棒，但是不知道能不能在一个平面矩形内的任意两点间也使用这种动态的线性轨迹，而不一定要使用地图坐标系的经纬度来定位，比如我要生成一张关系图，关系图之间的连线我想做成类似迁徙图中飞形轨迹的动态效果。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by zenglincient** [comment]
所以还是没支持？
