### ISSUE TITLE
在图表外层添加了css的zoom属性后鼠标移动或点击触发的事件的位置都发生了偏移

### ISSUE THREAD

**Issue by ZeroBinbin** [apache/incubator-echarts#3511]
#### 问题简述 (One-line summary)

在图表外层添加了css的zoom属性后鼠标移动或点击触发的事件的位置都发生了偏移
#### 版本及环境 (Version & Environment)
- ECharts 版本 (3.x):
- 浏览器类型和版本 (Chrome/46.0.2490.80 m):
- 操作系统类型和版本 (windows7):
#### 重现步骤 (Steps to reproduce)

例如：在柱状图外层div中添加zoom属性0.8
当鼠标移至其中一个柱子上时不显示tooltip,略微往右移动鼠标时才显示，
zoom的值越小，偏移量越大

**Comment by derekhe** [comment]
+1

**Comment by fengmiaosen** [comment]
+1

**Comment by fengmiaosen** [comment]
@ZeroBinbin 请问“图表外层添加了css的zoom属性后鼠标移动或点击触发的事件的位置都发生了偏移” 这个问题解决了么？

**Comment by tylerrrkd** [comment]
+1 ！！

**Comment by xiaobinwu** [comment]
+1

**Comment by cn-xufei** [comment]
+1

**Comment by 582324763** [comment]
+11

**Comment by tylerrrkd** [comment]
Emmm, 居然`closed`了都没解决。

**Comment by cn-xufei** [comment]
@tylerrrkd 
这块改的是zrender底层，官方还没releases，目前只能靠自己clone，再改zrender版本解决

**Comment by tylerrrkd** [comment]
@cn-xufei thanks
