### ISSUE TITLE
map存在多个系列时，tooltip.formatter的回调函数params只有第一个系列

### ISSUE THREAD

**Issue by imhzx** [apache/incubator-echarts#3522]
#### 问题简述 (One-line summary)

map存在多个系列时，tooltip.formatter的回调函数params只有第一个系列，无法针对多个系列作定制tip
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): v3.1.10
- 浏览器类型和版本 (Browser version): Chrome 36.0.1985.125 m
- 操作系统类型和版本 (OS Version): WIN7
#### 期望结果 (Expected behaviour)

params能包含目标地区所有系列

**Comment by ZhuyuAndCoder** [comment]
同样期望params能包含目标地区所有系列。

**Comment by halower** [comment]
同样期望params能包含目标地区所有系列。

**Comment by antstrong** [comment]
期望params能包含目标地区所有系列，并且希望mapValueCalculation的取值除了：

- 'sum' 取和。
- 'average' 取平均值。
- 'max' 取最大值。
- 'min' 取最小值。
能支持回调函数的形式
