### ISSUE TITLE
lines 实现动态添加迁徙线，此 series 会全部刷新重画的问题。

### ISSUE THREAD

**Issue by ChellsChen** [apache/incubator-echarts#3539]
#### 问题简述 (One-line summary)

在 setInterval 中 用 setOption 增加一个条线时，前一次的还没绘制完，本次重新绘制的时候，前一次的绘制过程取消了
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
  3.2.0
- 浏览器类型和版本 (Browser version):
  chrome
- 操作系统类型和版本 (OS Version):
  xos
#### 期望结果 (Expected behaviour)

可实现在 setInterval 中每次添加一条或多条迁徙线，而原来线图的状态不变
#### 可能哪里有问题 (What went wrong)
1. 用 setInterval 和 setOption 方式实现动态添加迁徙线的方式是否可行。
2. 是否有配置可实现这种效果
#### ECharts配置项 (ECharts option)

``` javascript
option = {
    series:[{
        type: 'lines',
        zlevel: 110,
        effect:{
            show: true,
                period: 2,
                trailLength: 0.2,
                color: '#FF6633',
                symbolSize: 8,
                loop: false,
        },
        lineStyle: {
            normal: {
                color: "#FF6633",
                width: 0,
                curveness: 0.2
            }
        },
      data: data,
    }],
}

```

**Comment by sunshinev** [comment]
你可以仿照柱形图的实时过程，将多条数据push到一个array中，达到array的长度阈值后，进行array.shift()，将过时的数据从array中删除掉，然后再重新setOption。这样会在阈值的范围内进行正常的绘制，但是超过阈值后，使用动画效果的话，会出现变形绘制（这个动画效果很让我纠结）

**Comment by PrivateRyanChengdu** [comment]
@sunshinev ，被array.shift()掉的数据就不会出现在图上了，是吗？

**Comment by sunshinev** [comment]
@PrivateRyanChengdu 成都的小伙伴呀，通过shift之后重新进行setOption会重新渲染，这样会固定展示阈值数量限制的lines，不然数据累计会导致浏览器内存不足，卡顿。

**Comment by 18910063011** [comment]
@sunshinev 我实现了相关功能但是动画效果老是有一个重新绘制的过程显得折现很是不稳，有什么方法关闭动画么？

**Comment by nocmk2** [comment]
这个问题有没有解决方案？

**Comment by Ovilia** [comment]
lines 效果是根据前几帧的采样进行叠加的，因此没法避免这个问题。
