### ISSUE TITLE
force节点name中有“（）“或者”()”,手机端无法显示，android和ios都不行

### ISSUE THREAD

**Issue by feng5125214** [apache/incubator-echarts#3566]
# 问题简述 (One-line summary)

节点name中有（）或者(),手机端无法显示，电脑端可以显示。android和ios都不行

版本及环境 (Version & Environment)

ECharts 版本 (ECharts version):echarts3.0
浏览器类型和版本 (Browser version):微信公众号，android和ios都试了
操作系统类型和版本 (OS Version):android和ios
重现步骤 (Steps to reproduce)

1.获取json数据
{
"type": "graph",
"layout": "force",
"categories": [
{
"name": "法人代表",
"keyword": {},
"base": "法人代表关系"
},
{
"name": "股东",
"keyword": {},
"base": "股东关系"
},
{
"name": "高管",
"keyword": {},
"base": "高管关系"
}
],
"nodes": [
{"name":"孙高梁","category":1},
{"corpid":"3301852003000699","name":" 嘉兴泰一指尚投资合伙企业（有限合伙）","category":2},
{"name":"陈枫","category":1},
{"corpid":"3301850000088925","name":"杭州临安佰汇信息有限公司","category":0},
{"corpid":"3301060001114195","name":"杭州树源贸易有限公司","category":2}
],
"links": [

```
    {"source":"陈枫","target":"孙高梁"},

     {"source":" 嘉兴泰一指尚投资合伙企业（有限合伙）","target":"孙高梁"}
```

]
}
2.ajax请求获取

期望结果 (Expected behaviour)

关系图显示出来

可能哪里有问题 (What went wrong)

是不是用公众号，微信内置浏览器不支持啊

ECharts配置项 (ECharts option)

 option = {
                         legend: {
                             data: ['HTMLElement', 'WebGL', 'SVG', 'CSS', 'Other']
                         },
                         series: [{
                             type: 'graph',
                             layout: 'force',
                             edgeSymbol: ['circle', 'arrow'],
                             edgeSymbolSize: [4, 10],
                             roam: true,
                             animation: false,

```
                         label: {
                             normal: {

                                 formatter: '{b}'
                             }
                         },


                         draggable: true,
                         data: datajson.nodes.map(function (node, idx) {
                            // node.id = idx;  
                              node.itemStyle = null;
                                node.symbolSize = 40;

                                // Use random x, y
                                node.x = node.y = null;
                                node.draggable = true;
                             return node;
                         }),
                         categories: datajson.categories,
                         force: {
                             // initLayout: 'circular'
                             // gravity: 0
                             // repulsion: 20,
                             edgeLength: 500,
                             repulsion:800
                         },
                         edges: datajson.links
                     }]
                 };
              myChart.setOption(option);
```

**Comment by pissang** [comment]
去掉括号呢？

**Comment by feng5125214** [comment]
去掉括号就可以显示，所以我们只能把名称中带括号的全部去掉了
