### ISSUE TITLE
折线图的显示中，多条折线当其中一条的y轴数据全为null时在我本地调试时鼠标悬停在某条线上的所有点的时间点的x轴数据都是显示的一样的

### ISSUE THREAD

**Issue by chunhanRyan** [apache/incubator-echarts#3584]
#### 问题简述 (One-line summary)

折线图的显示中，多条折线当其中一条的y轴数据全为null时在我本地调试时鼠标悬停在某条线上的所有点的时间点的x轴数据都是显示的一样的，但在官方页面上没发现该问题，请问echarts3是不是有其他的相关依赖，怀疑是不是其他相关依赖的js与官方不一致
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
  echarts3
- 浏览器类型和版本 (Browser version):
  chrome 46.0.24
- 操作系统类型和版本 (OS Version):
  win7 64bit
#### 重现步骤 (Steps to reproduce)

1.将折线中的某一条先得y轴数据全赋值为null，x轴数据相同
2.
#### 期望结果 (Expected behaviour)

鼠标移动到不同的点悬停显示的数据中x轴数据应该是变化的
#### 可能哪里有问题 (What went wrong)

是不是JQuery等相关依赖的js版本不一致？图中两个不同时间点的数据提示框中的显示时间确实一样的
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
你看下本地的版本是不是最新的
