### ISSUE TITLE
Is custom SVG map still supported in ECharts 3.x? 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3619]
In ECharts 2.x, it was possible to load custom SVG as a map: 
https://ecomfe.github.io/echarts/doc/example/map16.html#-en

Is this still supported in 3.x?

Anyway, awesome to have 3.2, so exciting!

**Comment by pissang** [comment]
Not supported yet. But i think it can be provided as a extension

**Comment by jarben** [comment]
That would be great, it allows to make very specific charts such as this one: 

![image](https://cloud.githubusercontent.com/assets/561365/16806276/25d2d10a-4914-11e6-8e26-adba73f3837a.png)

**Comment by pissang** [comment]
Agreed. And we have just released wordCloud extension. https://github.com/ecomfe/echarts-wordcloud

**Comment by jarben** [comment]
This world cloud extension looks awesome! I was dreaming of the maskImage feature more than often:) Also great example of the extension mechanism. Thanks heaps for your hard work @pissang!

**Comment by pissang** [comment]
@jarben Thanks for the compliment! We will keep improve the extension mechanism and expose more interfaces to help other developers to develop echarts extension conveniently

**Comment by jarben** [comment]
Just wondering whether this is still on the list @pissang? I think it would be so useful to bring 2.x SVG maps to 3.x!

**Comment by jarben** [comment]
Another example of custom SVG generated by Echarts 2.x:

![image](https://cloud.githubusercontent.com/assets/561365/24500236/de2edd32-1544-11e7-82fb-ea0162996f2d.png)

Maybe this could also be a new dot matrix series type:
![image](https://cloud.githubusercontent.com/assets/561365/24500300/1d46f31a-1545-11e7-9dd1-acfea67654cd.png)

Ideally with some layout options that allows to render items radially?
