### ISSUE TITLE
Declarative access to zrender? 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3620]
I think it would be really useful to formalize access to zrender. For instance, this example: 
http://echarts.baidu.com/demo.html#map-province

can be defined as: 

![image](https://cloud.githubusercontent.com/assets/561365/16773720/36536d98-4859-11e6-9a36-9cf3e6fb3433.png)

Ideally, it should be possible to use positioning relative to the visualization such as "50%", right:50 and so on. 

EChart instance would then take care of creating / destroying these layers. 

What do you think?

**Comment by pissang** [comment]
Yes this suggestion sounds really useful and practical. I think it will be a promising feature in the future versions and thanks again jarben:)

**Comment by psumstr** [comment]
Wish zrender got some love with docs in English too :). Currently, waiting on the options translation so I can stop using Google Translate

**Comment by jarben** [comment]
That's great to hear @pissang, another useful feature would be providing some docs or formalized access to low level API such as getting region's centroid, calculating x/y for given geo coordinates etc. This would make charts customization super powerful!
