### ISSUE TITLE
韦恩图

### ISSUE THREAD

**Issue by WLswert** [apache/incubator-echarts#3639]
想咨询下，ECHART 什么时候可以画多个项目构成的韦恩图。在2.0时可以画2个项目的韦恩图，在3.0都没见到示例了。因为最近项目需要，而且我个人觉得多个项目构成的韦恩图更需要，最近也一直在找，有一个venn.js可以画，但是很不友好，希望echart可以封装下。类似下图：

![image](https://cloud.githubusercontent.com/assets/12693684/16839436/99d4f9fa-4a01-11e6-96f8-e2ae575fb6f6.png)

**Comment by wangchong19940101** [comment]
强烈建议大佬们加上维恩图++++1
