### ISSUE TITLE
折线图中最大最小值显示不正确

### ISSUE THREAD

**Issue by swbuild1988** [apache/incubator-echarts#3646]
#### 问题简述 (One-line summary)

折线图中加载了大概超过7,8k的数据，当添加markPoint的时候，直接调用了'max'和'min'，现在折线图中标记的最大点最小点，在原数据中就没有这个值，感觉是经过拟合计算出来的一个极值。

ps:加载的数值都是2位小数的

求教怎样才能显示真实的最大最小值
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.2
- 浏览器类型和版本 (Browser version):Chrome
- 操作系统类型和版本 (OS Version):win7/win10
#### 期望结果 (Expected behaviour)

极值显示为正常的值
#### 可能哪里有问题 (What went wrong)

图上的并没有加载所有的数据，而是经过计算拟合的部分数据
#### ECharts配置项 (ECharts option)

``` javascript
option = {
            xAxis: {
                data: labels
            },
            yAxis: {
                min: avg - 10,
                max: avg + 10
            },
            series: [{
                name: '数据',
                data: datas,
                markPoint: {
                    symbolSize: 80,
                    data: [
                        { type: 'min', name: '最小值' },
                        { type: 'max', name: '最大值'}
                    ]
                },
                markLine: {
                    data: [
                        { type: 'average', name: '平均值' }
                    ]
                }
            }]
}

```
#### 其他信息 (Other comments)

![echartbug](https://cloud.githubusercontent.com/assets/20470515/16864502/b44d384a-4a8f-11e6-9faf-6f5a63fc443a.png)

**Comment by shaohualiang** [comment]
根据数据显示的样式，数据进行呈现的时候，最好只保留2到3位小数。

**Comment by pissang** [comment]
可以 formatter 里调整精度

**Comment by swbuild1988** [comment]
1.所有的数据都是两位的了
2.是否在markPoint中有特殊的样式设定（2位小数），在文档中没有找到对应的说明

**Comment by zhangming8691** [comment]
请问最大最小值这个倒水滴的样式可以改吗，想设置程横条样式，方便显示数据。 @shaohualiang ，谢谢。
