### ISSUE TITLE
如何实现e-charts3中radar使用axis来触发事件？？

### ISSUE THREAD

**Issue by shine11lyj** [apache/incubator-echarts#3651]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):e-charts3
- 浏览器类型和版本 (Browser version):Chrome 50
- 操作系统类型和版本 (OS Version): win10
#### ECharts配置项 (ECharts option)

使用echarts3 

``` javascript
tooltip : {
        trigger: 'item'

    },
            indicator : [          
                { text: '指标1',max:100},
                { text: '指标2',max:100},
                { text: '指标3',max:100},
                { text: '指标4',max:100},
                { text: '指标5',max:100},
                { text: '指标6',max:100},
                { text: '指标7',max:100},
                { text: '指标8',max:100},
                { text: '指标9',max:100}
            ],
```

结果：
![image](https://cloud.githubusercontent.com/assets/18047305/16870987/fe2c33f4-4ab6-11e6-8fd9-34dc02d293af.png)

通过**axis来触发**，tooltips就不能显示了
结果如下：
![image](https://cloud.githubusercontent.com/assets/18047305/16870968/e9e0bfd2-4ab6-11e6-8939-2aecfe692f70.png)

但是**e-chart2中trigger:"axis" 能支持的很好**，效果如下：

![image](https://cloud.githubusercontent.com/assets/18047305/16871007/0c95496c-4ab7-11e6-82d2-2106830711d9.png)

e-chart3中手册中有如下说明：
![image](https://cloud.githubusercontent.com/assets/18047305/16871042/2e98d7ea-4ab7-11e6-82bc-6c91008fbec1.png)

但是，实际中通过axis中的触发实现上就效果了；
源码中：

``` javascript
formatTooltip: function (dataIndex) {
                    var data=this._data;
                    var name = data.getName(dataIndex);
                    var seriesName = this.name;
                     var value = this.getRawValue(dataIndex);
                    var coordSys = this.coordinateSystem;
                    var indicatorAxes = coordSys.getIndicatorAxes();
                    return this._data.getName(dataIndex) + '<br />'
                        + zrUtil.map(indicatorAxes, function (axis, idx) {
                            return axis.name + ' : ' + value[idx];
                        }).join('<br />');
                },
```

这里面的实现就是返回通过item触发返回的数据？怎样实现通过鼠标移动到单个极坐标轴上触发对应轴上的数据展示呢？

期待，大家的帮忙~~~ 谢谢啦~~

**Comment by ccrzz** [comment]
同问
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: chrome 55.0.2883.75 (64-bit)
+ OS Version [操作系统类型和版本]: win10 14393.576

**Comment by AHuskyWithRockSoul** [comment]
如果我没理解错误的话，你这个问题我刚刚改动了一下echarts.js，你看看能不能实现你想要的效果
链接：[http://blog.csdn.net/agax0312/article/details/54927263](url)
Echarts ： 3.0
Browser version：chrome51.0.2704.106（64-bit）
OS version：Windows Server 2008 R2 Enterprise

**Comment by AHuskyWithRockSoul** [comment]
@shine11lyj @ccrzz

**Comment by xuqingkuang** [comment]
@AHuskyWithRockSoul 兄弟你改好了直接 fork 一份 ECharts 把代码发一个 pull request 回来啊。

**Comment by AHuskyWithRockSoul** [comment]
https://github.com/AHuskyWithRockSoul/echarts/pull/1/files
@xuqingkuang

**Comment by xuqingkuang** [comment]
@AHuskyWithRockSoul 基于你的代码改了一下，在 3.4 上通过了，不过你的代码没用上 trigger: 'axis'，这可能会导致不能合并进主线分枝，如果能解决这点就能发 pull request 了。

另外你的代码有两点小问题：一是会导致别的折线图的 [Tooltip 无法显示](https://github.com/xuqingkuang/echarts/commit/4ab67477c98ba7cc69202f39fa329f57effdcf65#diff-d5fbb7185a3802482df65d3d3a345c70R619)，第二个是雷达图里[只能显示一组数据的 Tooltip](https://github.com/xuqingkuang/echarts/commit/4ab67477c98ba7cc69202f39fa329f57effdcf65#diff-94439c827b90ec944559ae274fce0da7R96)，这两块我改进了一下。

这 bug 从 ECharts 3 开始就一直存在，感谢你让我总算可以跟 PM 交差了。 ;-)

![screen shot 2017-02-09 at 8 20 28 pm](https://cloud.githubusercontent.com/assets/32739/22783268/07a64458-ef06-11e6-909c-bf7eac4d18bd.png)

**Comment by AHuskyWithRockSoul** [comment]
@xuqingkuang 嗯嗯，应该会有影响其他图展现的情况，您改进了就好，我刚学js，改这个纯属瞎猫碰死耗子，您说的不能合并主线分支是什么意思呢？

**Comment by xuqingkuang** [comment]
@AHuskyWithRockSoul 小伙子牛啊，有没有兴趣来鹅厂？我帮你内推。

不能合并进主线是因为这个 patch 是个 workaround 不是个 solution，它改掉了 trigger: "item" 的行为而不是修复了 trigger: "axis" 的行为，你要有功夫可以继续研究一下 axis 的定位。

**Comment by AHuskyWithRockSoul** [comment]
@xuqingkuang  谢谢肯定，您过奖了，不瞒您说去年九月份才接触   html，css ，js这些东西，哈哈，水平很low，不过写着写着感觉非常有兴趣，您那里要是招人，我很想试一下！！

**Comment by AHuskyWithRockSoul** [comment]
@xuqingkuang  如果有机会的话，我微信Jerry_agax ，大写J  ，嘿嘿

**Comment by chengwubin** [comment]
解决了吗？我下最新版的还是不行呢

**Comment by songkai2012** [comment]
我最新版现在也不行。。

**Comment by AHuskyWithRockSoul** [comment]
@songkai2012 @chengwubin https://github.com/AHuskyWithRockSoul/echarts_radar/blob/master/echarts_radar_change_axis

**Comment by Dafrok** [comment]
ping

**Comment by stouch** [comment]
Duplicate of #10537 ?

**Comment by vxhly** [comment]
？一脸懵逼，没看懂，我只想只知道有没有不引用三方的代码实现的方式

**Comment by web-oop** [comment]
> @AHuskyWithRockSoul 基于你的代码改了一下，在 3.4 上通过了，不过你的代码没用上 trigger: 'axis'，这可能会导致不能合并进主线分枝，如果能解决这点就能发 pull request 了。
> 
> 另外你的代码有两点小问题：一是会导致别的折线图的 [Tooltip 无法显示](https://github.com/xuqingkuang/echarts/commit/4ab67477c98ba7cc69202f39fa329f57effdcf65#diff-d5fbb7185a3802482df65d3d3a345c70R619)，第二个是雷达图里[只能显示一组数据的 Tooltip](https://github.com/xuqingkuang/echarts/commit/4ab67477c98ba7cc69202f39fa329f57effdcf65#diff-94439c827b90ec944559ae274fce0da7R96)，这两块我改进了一下。
> 
> 这 bug 从 ECharts 3 开始就一直存在，感谢你让我总算可以跟 PM 交差了。 ;-)
> 
> ![screen shot 2017-02-09 at 8 20 28 pm](https://cloud.githubusercontent.com/assets/32739/22783268/07a64458-ef06-11e6-909c-bf7eac4d18bd.png)

别想交差，问题还存在呢  "echarts": "^4.9.0",
