### ISSUE TITLE
折线图X轴及Y轴axisLabel的设置

### ISSUE THREAD

**Issue by luzhq** [apache/incubator-echarts#3666]
#### 问题简述 (One-line summary)

X轴的axisLabel应该支持设置与Y轴的位置关系
Y轴的axisLabel应该支持设置与X轴的位置关系
目前axisLabel的margin属性只能设置它所在的轴线
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/20197088/16910791/2c684bb0-4d0d-11e6-864d-8655b335923f.png)
@pissang

**Comment by pissang** [comment]
为什么 X 轴的 label 要跟 Y 轴对齐？

**Comment by LuZhQ** [comment]
图一
![image](https://cloud.githubusercontent.com/assets/20197088/16911530/985f4d10-4d11-11e6-92cf-c719ba7168bf.png)

图二
![image](https://cloud.githubusercontent.com/assets/20197088/16911551/abe2de06-4d11-11e6-8d8a-f32a483510b3.png)

为了实现类似图二的效果，09:30及15:00两个标签没有凸出来，更加美观方便浏览。
图一中09:30及15:00两个X轴的标签凸出在Y轴外，以及Y轴的15.53和-1.15两个标签设置成inside的话会压在X轴线上。 @pissang

**Comment by pissang** [comment]
如果是类目轴的话可以单独设置文本的 align http://echarts.baidu.com/option.html#xAxis.data.textStyle.align

**Comment by LuZhQ** [comment]
value轴的话目前是设置不了吧？ @pissang

**Comment by pissang** [comment]
嗯，value 轴暂时不行
