### ISSUE TITLE
视觉映射组件和Force图的配合及若干其他问题

### ISSUE THREAD

**Issue by hejiheji001** [apache/incubator-echarts#3703]
#### 问题简述 (One-line summary)

在Force图中使用2个连续性视觉映射组件 出现了如下2个问题：
1. 2个组件均可正常工作 但是对于仅仅作用于节点 节点之间的连线link还在 是否有好办法可以一并随着节点隐藏/显示
2. 节点颜色会被更后(或者更前)一个组件的range颜色覆盖 例如：我A组件设置默认颜色 枣红至鹅黄，B组件设置天蓝至橙红，最终节点会和某一个组件吻合 而希望实现组件颜色均分节点（节点X左边有A组件的鹅黄 右边有B组件的天蓝）

关于edgeLabel的问题
1. 能否设置edgeLabel的文字能够在节点上面呢，用css形容就是z-index 要大一些，而不是被节点盖住一部分
2. 不知为何 emphasis下无法设置文字位于线段中间 position:'middle' 并没有用处, 改成normal后无此问题（但是图形绘制会很慢且不好看 所以不能采用normal形式）
3. 颜色设置的黑色 实际上带了透明度 实测中发现 force图稳定前确实是黑色的 稳定后颜色就淡了 focusNodeAdjacency: false 后没有这个问题 但是我必须要使用此功能

性能问题
1. 开启 edgeSymbol: ['none', 'arrow'] 和 edgeSymbolSize: [0, 8] 后 图像绘制特慢（约有200个节点）画布闪烁严重 试过animationThreshold:100 无效，layoutAnimation: false 后依然不是很理想 且edgeLabel的颜色更加淡到几乎看不清了 focusNodeAdjacency: false 后edgeLabel可以看清楚 但是绘图依旧很慢
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.2
- 浏览器类型和版本 (Browser version): Chrome 51 64bit
- 操作系统类型和版本 (OS Version): OSX 10.11.5
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

期待结局这些bug们
#### 可能哪里有问题 (What went wrong)

focusNodeAdjacency

edgeLabel:{emphasis}

edgeSymbol和edgeSymbolSize的性能
#### ECharts配置项 (ECharts option)

``` javascript

// 视觉组件部分
graph.setOption({
                    visualMap: [{
                                type: 'continuous',
                                min: 0,
                                max: 50,
                                dimension: 1,
                                text:['Outdegree',''],
                                realtime: false,
                                calculable : true
                            }
                   ,{
                            type: 'continuous',
                            min: 0,
                            max: 1000,
                            bottom: 200,
                            dimension: 0,
                            text:['Indegree',''],
                            realtime: false,
                            calculable : true,
                            color: ['orangered','yellow','lightskyblue']
                        }
                    ]
                })


//edgeLabel部分
edgeLabel: {
                    emphasis: {
                        show: true,
                        position: 'middle',
                        textStyle: {
                            color: 'black',
                            fontSize: 16,
                            fontWeight: 'bold'
                        }
                    }
                },
                lineStyle: {
                    normal: {
                        width: 1,
                        // curveness: 0.3,
                        color: 'target'
                    },
                    emphasis: {
                        width: 5,
                        color: 'red'
                    }
                }
```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/4100130/17081036/cd8da550-513e-11e6-949b-641bd8d4f72f.png)

![image](https://cloud.githubusercontent.com/assets/4100130/17080953/0a45b526-513c-11e6-9691-261b4a4d7b14.png)

![image](https://cloud.githubusercontent.com/assets/4100130/17081031/a6ae93fe-513e-11e6-9c59-ce1f0927d04b.png)

**Comment by hejiheji001** [comment]
关于edgeLabel的文字居中问题 我采用了如下方案 但是觉得很傻。。。。

｀｀
edgeLabel: {
			emphasis: {
				show: true,
				position: 'middle',
				textStyle: {
					color: 'red',
					fontSize: 18,
					fontWeight: 'bold'
				}
			},
			normal: {
				show: true,
				position: 'middle',
				textStyle: {
					color: 'transparent'
				}
			}
		}
｀｀

**Comment by pissang** [comment]
关于 visualMap 的 1. 暂时不行，visualMap 的其实不是筛选的功能。2. 所有颜色编码中 visualMap 的优先级经次于 brush 组件，会覆盖所有其它设置的颜色。

关于 edgeLabel 的，position 必须在 normal 里设置，但是可以 normal 设置 show: false， emphasis 设置 show: true 只在 hover 的时候显示。

其它的能否给一份完整的 option 方便我们复现

**Comment by hejiheji001** [comment]
我把项目打包一份 请直接用 index.html 看效果吧

完整的数据和配置在 js/main.js 里面

[web.zip](https://github.com/ecomfe/echarts/files/381011/web.zip)

**Comment by hejiheji001** [comment]
顶一下0.。0

**Comment by hejiheji001** [comment]
请问有一些进展了么 还需要我提供什么资料吗？
