### ISSUE TITLE
DrillDown feature in ECharts

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [apache/incubator-echarts#3721]
Hi,

I like the features and the usability of this plugin a lot. I am stuck in a point where I need to have drill down in charts. Now I am doing it by capturing the click event in the points and then using that to get the data from API and the bind it to the chart again.

1) Is there a better way to do it?
2) How can we go back to the previous data after the new data is overwritten. So is there a predefined method to do the drillable charts.

**Comment by pissang** [comment]
1) Listening to the click event and use `setOption` to show the subset of data is currently the best way to do drill down. 
2) You manage the data by yourself. ECharts doesn't care much about the source of data.

**Comment by VigneshVaidyanathan** [comment]
Thanks for the comment. Still it would be better to have a drillable feature as an option in the reports.

**Comment by VigneshVaidyanathan** [comment]
I tried using the events and getting the data. But the params available in the callback for event click and hover are not sufficient to filter the data or get new set of data from API. I want to know if there is any way to add extra custom data to the series objects, that can be got when the event is triggered.

Please help.

**Comment by pissang** [comment]
each data item can be an object with `name` and `value` property. Any other custom properties can also be added. And all will be exist in `param.data`

**Comment by dadhichaditya** [comment]
How do we go back to the previous graph after drilldown? I'm changing SetOption after click on bar series.

Mycode : 

` bargraph.on('click',function(params){
            if(params.componentType == 'series'&& params.name =='shirt')
            setInterval(function(){
                    bargraph.setOption(baroption2)
                },200);
        })`

**Comment by leogariba** [comment]
You could maintain an array with your chart options object. After a drill you push the old chart options to the array. To go back you pop that options from the array.
