### ISSUE TITLE
showAllSymbol时，能否不显示label

### ISSUE THREAD

**Issue by Coffcer** [apache/incubator-echarts#3757]
#### 问题简述 (One-line summary)

数据太大时，echarts会自动间隔显示label和坐标轴。但是被隐藏的部分不太明显，希望设置showAllSymbol后显示所有小圆点。但是showAllSymbol又会把所有的label都被显示出来。

有什么办法即可以显示所有的symbol，又自动间隔显示label吗？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行

**Comment by Coffcer** [comment]
那就得手动实现一个跟echarts interval一模一样的算法，还是挺麻烦的，以后的版本有没可能分开symbol和label呢

**Comment by pissang** [comment]
暂时没有该打算
