### ISSUE TITLE
Treemap无法显示top level的label

### ISSUE THREAD

**Issue by luzx02** [apache/incubator-echarts#3760]
#### 问题简述 (One-line summary)

Treemap无法显示top level的label
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.2
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)
1. 打开http://echarts.baidu.com/gallery/editor.html?c=treemap-disk&edit=1&reset=1
2. 哪怕是修改levels设置，加入label如下，也没效果：

``` javascript
function getLevelOption() {
        return [
            {
                itemStyle: {
                    normal: {
                        borderWidth: 0,
                        gapWidth: 5
                    }
                },
                label:{
                    normal:{
                        show: true,
                        position: 'insideTopLeft'
                    }
                }
            },
            {
                itemStyle: {
                    normal: {
                        gapWidth: 1
                    }
                }

            },
            {
                colorSaturation: [0.35, 0.5],
                itemStyle: {
                    normal: {
                        gapWidth: 1,
                        borderColorSaturation: 0.6
                    }
                }
            }
        ];
    }

```
#### 期望结果 (Expected behaviour)

如果有两层数据的话，希望同时能显示第1和第2层的label。目前只能显示第2层的label
#### 可能哪里有问题 (What went wrong)

应该是第2层遮挡住了第1层的label
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by psumstr** [comment]
I'm experiencing the same issue. Is there a way we can put labels on Level 1 on a 2 level Treemap?
