### ISSUE TITLE
echarts和avalon冲突

### ISSUE THREAD

**Issue by crazyfengpeiyao** [apache/incubator-echarts#3797]
#### 问题简述 (One-line summary)

操作系统是win7 家庭版的，浏览器是chrome 51.0.2704.106 ，echarts版本应该3.x ，因为这个js文件是同事找的，上面没有显示版本号
#### 重现步骤 (Steps to reproduce)

1.页面加载echarts.js正常，然后把avalon加进来就出问题，浏览器一直显示require.js,gauge.js,pie.js,bar.js正在加载

希望能让正常加载
#### 可能哪里有问题 (What went wrong)

感觉可能是require问题

**Comment by pissang** [comment]
请确认下 echarts 版本
