### ISSUE TITLE
‘setOption’ should not be called during main process

### ISSUE THREAD

**Issue by newUser12138** [apache/incubator-echarts#3806]
#### 问题简述 (One-line summary)

在选项卡（easyui-tabs）中创建定时刷新的图表后切换到其他选项卡，报错某某方法 should not be called during main process.
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version): 火狐 47.0.1
- 操作系统类型和版本 (OS Version): window 7 旗舰版 64位
#### 重现步骤 (Steps to reproduce)

1.在main.jsp中使用easyui-tabs和iframe创建多个选项卡。
2.在其中一个选项卡中绘制图表，并设置定时刷新数据，重绘图表。
3.切换到其他选项卡，观察浏览器控制台（火狐的firebug）。
4.绘制图表时报错，‘setOption’ should not be called during main process.。
5.重新切换回到该选项卡，报错依旧存在，并且定时刷新不再生效，手动点击也不再生效。
#### 可能哪里有问题 (What went wrong)

切换到其他选项卡后可能DOM对象获取失败，我想问问有什么办法解决吗？
或者Echarts在绘图的时候能判断一下是否能够绘制？
刚接触Echarts，有许多地方不懂，如果误报了BUG请见谅。
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
有可以复现的代码么？

**Comment by newUser12138** [comment]
@pissang 抱歉，我简化代码后，原先的报错没能重现，而是报了一个新的问题（NS_ERROR_FAILURE: ctx.font = font;）。我再查查代码，有进展再联系。

**Comment by newUser12138** [comment]
@pissang 已经将能够重现问题的程序发你gmail邮箱了，请查收。

**Comment by daoyuanjiao** [comment]
我的是在每个选项卡中的ECharts在初始化的时候，设置不同的名字！一开始每个tab中的名字都一样的时候就会出错！

**Comment by pissang** [comment]
@newUser12138 shenyi.914@gmail.com 这个邮箱？我好像没收到

**Comment by newUser12138** [comment]
@pissang 是的，我刚才又重新向这个邮箱发了一份，你看看有没有收到。
@daoyuanjiao 我目前的解决办法是，在切换选项卡的时候，通过easyui-tab的onselect和onunselect方法进行判断，切出页面时关闭定时器，切入页面时开启定时器。不过还存在瑕疵，就是如果定时器间隔较小（比如1秒），有几率来不及关闭定时器，然后报错。

**Comment by wu11106** [comment]
好時光酒店在七夕情人節：
恭祝Google支持團隊：有情人終成眷屬！闔家幸福！


2016年8月9日星期二，newUser12138 <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3Dy9vRhZgYU8q7dg04mnneLLJVhNurs8gwlUk8YocQWnU%253D%26token%3DEawhTF3xeLizbBh7EHUWSesEoVcV24u04FbhgztQALXQuOuHGo%252FBEUICsKSCjbub4CgNomMXXAaHc9eyoQxrnUaIfxc7%252FeGZ0kWNaXhdCe8tJc1dHqaxrgu9FSQlUdcwSw7Wib6HDJbWYkbojO%252FF3w%253D%253D&tc_serial=26372468249&tc_rand=2011132913&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26372468249&tc_rand=2011132913&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>


-- 
http://plus.google.com

**Comment by newUser12138** [comment]
@wu11106 什么？

**Comment by BigDuck** [comment]
不知道你们有没有解决这个问题，我也遇到这个报错但是不是你们的应用场景，我和定时器没关系就算设置再小也是没问题的，我是在websocket中当接收到数据的时候去setOption时出现。`websocket.onmessage=function(evt){
myChart.setOption({
series:[{
data:JSON.parse(evt.data)
}]
})
}`

**Comment by BigDuck** [comment]
好像是我数据...但是不应该这个错误....

**Comment by dreamllq** [comment]
我这解决这个问题是因为页面中渲染图表的容器css设置成display:none了，修改为 position:fixed; top:-9999px;left:-9999px;解决了此问题。猜测firefox中隐藏的canvas操作会报异常

**Comment by cuijiayu1** [comment]
> 我这解决这个问题是因为页面中渲染图表的容器css设置成display:none了，修改为 position:fixed; top:-9999px;left:-9999px;解决了此问题。猜测firefox中隐藏的canvas操作会报异常

太给力了 我成功了
