### ISSUE TITLE
python生成pygexf文件无法直接被echarts处理 

### ISSUE THREAD

**Issue by sumujie** [apache/incubator-echarts#3812]
#### 问题简述 (One-line summary)

Python2.7 pygexf0.2.2 echarts3 
用pygexf生成的gexf文件中只能设置id,label,color，没有<viz>position</viz>,导入echarts3中的关系图里无法处理显示，用gephi导入gexf运行并再次导出gexf，的确有position与size信息，但有没有不用gephi在python后端中生成完整的可直接使用的gexf文件的方式，因为考虑到gephi只有javadoc的api，用Python会更复杂。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):ECharts3
- 浏览器类型和版本 (Browser version):Google Chrome
- 操作系统类型和版本 (OS Version):Windows 7
#### python代码：

from gexf import Gexf
gexf = Gexf("Paul Girard","A hello world! file")
graph=gexf.addGraph("directed","static","a hello world graph")
tmp=graph.addNode("0","hello","","","","235","81","72")
graph.addNode("1","World","","","","236","81","72")
graph.addEdge("0","0","1","4")
output_file=open("helloworld1.gexf","w")
gexf.write(output_file)  
#### python直接生成的gexf文件：

<gexf xmlns:viz="http://www.gexf.net/1.1draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.gephi.org/gexf/1.1draft" xmlns:ns0="xsi" version="1.1" ns0:schemaLocation="http://www.gephi.org/gexf/1.1draft http://gephi.org/gexf/1.1draft.xsd">
  <meta lastmodified="2016-08-08T12:46:29.317000">
    <creator>Paul Girard</creator>
    <description>A hello world! file</description>
  </meta>
  <graph defaultedgetype="directed" label="a hello world graph" mode="static">
    <attributes class="node" mode="dynamic"/>
    <attributes class="node" mode="static">
      <attribute id="0" title="size" type="float">
        <default>true</default>
      </attribute>
    </attributes>
    <attributes class="edge" mode="dynamic"/>
    <attributes class="edge" mode="static"/>
    <nodes>
      <node id="1" label="World">
        <attvalues/>
        <viz:color r="236" g="81" b="72"/>
      </node>
      <node id="0" label="hello">
        <attvalues/>
          <viz:color r="235" g="81" b="72"/>
      </node>
    </nodes>
    <edges>
      <edge id="0" source="0" target="1" weight="4">
        <attvalues/>
      </edge>
    </edges>
  </graph>
</gexf>
#### 需要的gexf文件（即Gephi生成的gexf文件）：

<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.3" version="1.3" xmlns:viz="http://www.gexf.net/1.3/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.3 http://www.gexf.net/1.3/gexf.xsd">
  <meta lastmodifieddate="2016-08-08">
    <creator>Gephi 0.9</creator>
    <description></description>
  </meta>
  <graph defaultedgetype="directed" timeformat="double" timerepresentation="interval" mode="dynamic">
    <attributes class="node" mode="static">
      <attribute id="0" title="size" type="float"></attribute>
    </attributes>
    <nodes>
      <node id="1" label="World" >
        <attvalues></attvalues>
        <viz:size value="10.0">/viz:size
        <viz:position x="258.70508" y="318.54987">/viz:position
        <viz:color r="236" g="81" b="72">/viz:color
      </node>
      <node id="0" label="hello" >
        <attvalues></attvalues>
        <viz:size value="10.0">/viz:size
        <viz:position x="-22.695984" y="-335.1161">/viz:position
        <viz:color r="235" g="81" b="72">/viz:color
      </node>
    </nodes>
    <edges>
      <edge id="0" source="0" target="1" weight="4.0"></edge>
    </edges>
  </graph>
</gexf>

**Comment by tonyupstar** [comment]
我也遇到同样的问题，请问你当时的问题解决了吗？最后还是需要自己增加viz属性？

**Comment by WMLHUST** [comment]
@tonyupstar 请问你解决了吗，我也遇到了同样的问题。。。最后viz属性怎么搞

**Comment by pissang** [comment]
position 属性是要布局后才有的，对于还没有布局的关系图 echarts 提供了力引导布局，设置 layout: 'force'

**Comment by WMLHUST** [comment]
明白了，谢谢，也可以用 layout: 'circular'
