### ISSUE TITLE
是否有选择grid的事件

### ISSUE THREAD

**Issue by LeoZeda** [apache/incubator-echarts#3818]
是否有选择grid的事件，如点击下图的框框部分，触发某个事件，高亮该区域.  我试着添加click事件，然后点击这个区域没有反应，点击数据点是有触发的。
![image](https://cloud.githubusercontent.com/assets/8565999/17515138/40efe698-5e69-11e6-92b9-dc262db20a64.png)

![image](https://cloud.githubusercontent.com/assets/8565999/17515207/9e6bae6a-5e69-11e6-8038-ac6d5dfaee9f.png)

这里事件好像没有看到有：
[http://echarts.baidu.com/api.html#events.%E9%BC%A0%E6%A0%87%E4%BA%8B%E4%BB%B6](http://echarts.baidu.com/api.html#events.%E9%BC%A0%E6%A0%87%E4%BA%8B%E4%BB%B6)

参考代码：
[http://echarts.baidu.com/demo.html#line-marker](http://echarts.baidu.com/demo.html#line-marker)
option = {
    title: {
        text: '未来一周气温变化',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'item',
        triggerOn: 'click'
    },
    legend: {
        data:['最高气温','最低气温']
    },
    toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            dataView: {readOnly: false},
            magicType: {type: ['line', 'bar']},
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis:  {
        type: 'category',
        boundaryGap: true,
        data: ['周一','周二','周三','周四','周五','周六','周日'],
        nameLocation: 'middle',
        splitLine: {
            show: true,  
          lineStyle: {
            width: 1,
            color: '#6f8ba8'
          }
        },
        axisTick: {
          show: false
        },
        axisLine: {
          lineStyle: {
            width: 1,
            color: '#6f8ba8'
          }
        },
        axisLabel: {
          textStyle: {
            color: '#6f8ba8'
          }
        }
    },
    yAxis: {
        type: 'value',
        axisLabel: {
            formatter: '{value} °C'
        },
        splitLine: {
          show: false
        },
        axisTick: {
          show: false
        },
        axisLine: {
          lineStyle: {
            width: 1,
            color: '#6f8ba8'
          }
        }
    },
    series: [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10],
            markPoint: {
                data: [
                    {type: 'max', name: '最大值'},
                    {type: 'min', name: '最小值'}
                ]
            },
            markLine: {
                data: [
                    {type: 'average', name: '平均值'}
                ]
            }
        },
        {
            name:'最低气温',
            type:'line',
            data:[1, -2, 2, 5, 3, 2, 0],
            markPoint: {
                data: [
                    {name: '周最低', value: -2, xAxis: 1, yAxis: -1.5}
                ]
            },
            markLine: {
                data: [
                    {type: 'average', name: '平均值'},
                    [{
                        symbol: 'none',
                        x: '90%',
                        yAxis: 'max'
                    }, {
                        symbol: 'circle',
                        label: {
                            normal: {
                                position: 'start',
                                formatter: '最大值'
                            }
                        },
                        type: 'max',
                        name: '最高点'
                    }]
                ]
            }
        }
    ]
};

**Comment by LeoZeda** [comment]
发现tooltip有类似功能， 设置 tooltip的 trigger： ‘axis’， axisPointer: { type: 'shadow'}.
但是好像没有事件回调，就是不能自己处理点击事件

**Comment by LeoZeda** [comment]
tooltip 的position 如何获取数据点的位置， 现在有鼠标点击位置

**Comment by mu-yu** [comment]
有解决这个问题吗？

**Comment by LeoZeda** [comment]
之前看echart源码看到，可以监听图表上的mousemove事件：
echart.getZr().on('mousemove', this._onChartEvent)

于是就自己实现了类似功能，就是拿到鼠标位置后，判断该位置在那一个grid里面
