### ISSUE TITLE
可否控制取消标线markLine与series[i].name的关联

### ISSUE THREAD

**Issue by zhouboluo** [apache/incubator-echarts#3824]
#### 问题简述 (One-line summary)

需要绘制多个图形时，图形title不同，但是series含义是相同的，所以名字也相同，这时候使用markLine，只会在最后一个图形上添加标线。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

可否取消series[i].name和markLine的关联，根据series或者grids对应markLine，即不管命名如何，每个图形有单独的标线；或者使用一个标志位，控制标线是否与series[i].name关联
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
你说的关联是指？

**Comment by zhouboluo** [comment]
就是多个图的时候，series[i].name的值一样，给每个series[i]添加markLine，结果只有最后一个图显示标线 @pissang
