### ISSUE TITLE
x轴可以强制显示最后一个类目名吗？

### ISSUE THREAD

**Issue by aCodeBaby** [apache/incubator-echarts#3830]
#### 问题简述 (One-line summary)

x轴 type选择默认的category，然后数据量非常多的情况下，会自动间隔显示类目名，现在想把第一和最后一个都显示，然后其他的均匀显示，有没有办法？（目前看效果第一是会强制显示，数据过多，最后几个都会不显示，文档里没找到类似的说明）
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
axisLabel.interval 可以是个回调函数，在这个函数里你可以判断是否是最后一个类目然后强制显示

**Comment by aCodeBaby** [comment]
可以贴一下echart自动排列类目的那个函数名吗？我想看下具体的算法实现，参考一下~

**Comment by evilbdef** [comment]
interval是auto计算不重叠的时候，能否增加考虑下文字倾斜的是情况？倾斜文字时可以显示得密集点

**Comment by Bobby90622** [comment]
axisLabel: {
      showMaxLabel: true
 }
