### ISSUE TITLE
echarts y轴双坐标轴，其中一个包含负刻度时的，坐标轴刻度显示问题

### ISSUE THREAD

**Issue by yk125123** [apache/incubator-echarts#3846]
#### 问题简述 (One-line summary)

echarts 在yAxis双y轴y1,y2时，如果两个y轴中有一个存在负刻度y2时，显示存在问题，无法自动将y2的0刻度显示在x轴上
是否可以提供简单的配置方式来实现，目前我的做法是通过更改yAxis的min、max来实现的；
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.2
- 浏览器类型和版本 (Browser version): chrome
- 操作系统类型和版本 (OS Version): win8
#### 重现步骤 (Steps to reproduce)

1.直接运行option即可
#### 期望结果 (Expected behaviour)

1.y1的0刻度在x轴上，y2的0刻度在x轴上，y2负刻度在x轴下方

#### ECharts配置项 (ECharts option)

``` javascript
option = {
color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        },
        {
            type: 'value',
            axisLabel: {
                formatter: '{value} %'
            }
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[1000, 520, 2000, 3340, 3900, 330, 5220]
        },
        {
            name:'同比增幅',
            type:'line',
            lineStyle:{
                normal:{
                    color:'red'
                }  
            },
            yAxisIndex:1,
            data:[10, 52, -40, 34, 39, 50, 22]
        }
    ]
}

```

**Comment by KinoshitaHanson** [comment]
同样的问题，困扰已久，期待高人解答！

**Comment by yk125123** [comment]
目前这个问题我通过设定坐标轴刻度最大值、最小值来做的解决：
                yAxis[0].min = targe1[0];
                yAxis[0].max = targe1[1];
                yAxis[1].min = targe2[0];
                yAxis[1].max = targe2[1];
                curChart.setOption({
                    yAxis: yAxis
                });
但是出来后的刻度，两个y轴就只有最大值和做小值。
期待高人给予解答。

**Comment by 349989153** [comment]
可是靠设置min和max，也不能做到两y轴的0刻度都在x轴上吧？
我这边的情况是，设置了min和max的话，x轴会按照第二条y轴的min来生成

**Comment by yk125123** [comment]
我是是按照偏离0刻线最大的比例去同时计算出两个y周的最大值，最小值来做的解决。
我这边只有y2有正负，按照它的比例计算出来y1的min（负数），设置后就可以了。


发自网易邮箱大师


在2017年05月8日 17:30，WebBug<notifications@github.com> 写道：

可是靠设置min和max，也不能做到两y轴的0刻度都在x轴上吧？
我这边的情况是，设置了min和max的话，x轴会按照第二条y轴的min来生成

**Comment by 349989153** [comment]
@yk125123 
hi，能否把解决方案的option放一下
感激不尽

**Comment by maxid** [comment]
唉，0 都不对齐，太奇葩了

**Comment by shenyubao** [comment]
同样问题, 求解

**Comment by baixiaoji** [comment]
同样的问题！

**Comment by yk125123** [comment]
![image](https://user-images.githubusercontent.com/3381518/35431804-f551fb86-02b8-11e8-9a12-6e9c2ab77d10.png)
我只显示了两个轴的最大值和最小值以及0；效果如上图  option没什么好贴的  因为是需要根据返回结果的数据去动态计算的  根据两个轴的最大值和最小值，计算一下  比如  y1轴上max: 500  min -100  y2轴 max: 100  min: -100  那么  会按照y2（正负绝对值比接近1的那个轴）的比例去计算y1（另一个轴） 应该显示的max  min

**Comment by peter-wang-wsl** [comment]
可以配合xAxis和yAxis的interval进行配置
