### ISSUE TITLE
timeline的axisType为'time'问题

### ISSUE THREAD

**Issue by wang1127502020** [apache/incubator-echarts#3872]
#### 问题简述 (One-line summary)

在进行个人GPS轨迹数据的时候，想将时间轴结合到地图上来，文档中axisType：‘time’比较时间连续的数据，但尝试后无效，请问该如何设置timeline.data，从而与series对应？有没有案例提供？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.1
- 浏览器类型和版本 (Browser version):firfox
- 操作系统类型和版本 (OS Version):win10
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by fengjidly** [comment]
你好，请问你的timeline前后台怎么交互的啊？
