### ISSUE TITLE
仪表盘问题

### ISSUE THREAD

**Issue by wind108369** [apache/incubator-echarts#3876]
Gauge类型通过 axisLine.lineStyle.color 使用echarts.graphic.LinearGradient 设置渐变后，数字（detail设置的数字）就不会显示了

**Comment by Sammiu** [comment]
我先问问楼主的 Gauge 渐变是怎么实现的么？

**Comment by wind108369** [comment]
echarts.graphic.LinearGradient

**Comment by Sammiu** [comment]
![image](https://cloud.githubusercontent.com/assets/15193698/17798005/41cfc904-6600-11e6-8755-747151d132e2.png)
用了这个函数  运行没效果

**Comment by JackyXiong** [comment]
@wind108369 请问仪表盘的渐变是怎么实现的？

**Comment by RicoLiu** [comment]
请问这个问题解决了吗？

**Comment by zlpcrmm** [comment]
请问这个问题解决了吗？
