### ISSUE TITLE
【建议】建议可以控制series[i]-bar.label字的层级类似z-index的值

### ISSUE THREAD

**Issue by semmy2010** [apache/incubator-echarts#3890]
#### 问题简述 (One-line summary)

建议可以控制series[i]-bar.label字的层级类似z-index的值，不然字会被条形给挡住，可以设置字的类似css里面的z-index值，字号必须要那么大时的需求。场景如下面的图所示。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

![123](https://cloud.githubusercontent.com/assets/4402907/17817650/1891807e-6672-11e6-9468-384310704a03.jpg)

**Comment by yaowei9363** [comment]
赞成,我也遇到这个问题
