### ISSUE TITLE
建议：dataZoom的鼠标拖拽事件通过window监听

### ISSUE THREAD

**Issue by k8w** [apache/incubator-echarts#3897]
#### 问题简述 (One-line summary)

当浏览器窗口非全屏时，或在多屏环境下：
执行一些拖拽操作（如dataZoom），当鼠标拖出浏览器窗口后，便无法继续拖动；
同时，当鼠标按键在窗口外被释放后，重新移回窗口内，却仍然保持了鼠标未释放的状态。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version): Chrome
- 操作系统类型和版本 (OS Version): Win7
#### 重现步骤 (Steps to reproduce)

1.将浏览器窗口调整到非全屏
2.在dataZoom里拖拽，直到鼠标移出窗口
3.在窗口外继续拖拽，然后松开鼠标
4.将鼠标移回浏览器
#### 期望结果 (Expected behaviour)

即便鼠标移出浏览器，也能保持拖拽动作
#### 可能哪里有问题 (What went wrong)

拖拽的鼠标事件，是通过document来监听的
如果通过window来监听，则无此问题
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by autukill** [comment]
如何解决"当鼠标按键在窗口外被释放后，重新移回窗口内，却仍然保持了鼠标未释放的状态"?

**Comment by autukill** [comment]
> 如何解决"当鼠标按键在窗口外被释放后，重新移回窗口内，却仍然保持了鼠标未释放的状态"?

#7428
