### ISSUE TITLE
ECharts.connect在多grid或多dataZoom场景下联动出错

### ISSUE THREAD

**Issue by k8w** [apache/incubator-echarts#3898]
#### 问题简述 (One-line summary)

**ECharts.connect**
1. 当被联动的图表有多个dataZoom时，只有第一个dataZoom能正常联动
1. 当connect的图表对象中，包含多个grid，那么只有第一个grid能正常联动。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):Chrome
- 操作系统类型和版本 (OS Version):Win7
#### 重现步骤 (Steps to reproduce)

1.http://echarts.baidu.com/demo.html#grid-multiple
#### 期望结果 (Expected behaviour)

单图内也可以像ECharts.connect一样联动

**Comment by twoeo** [comment]
同时，如果被connect的图表对象中，包含多个grid，那么只有第一个grid能正常联动。

**Comment by pissang** [comment]
不行，只能多个实例间联动

**Comment by twoeo** [comment]
**多实例间的情况：**
1. 当被联动的图表有多个dataZoom时，只有第一个dataZoom能正常联动
1. 当connect的图表对象中，包含多个grid，那么只有第一个grid能正常联动。

**Comment by Bukoo** [comment]
同样遇到：当connect的图标中有多个grid，只有第一个grid能联动。希望能解决，echarts超好用！感谢！
