### ISSUE TITLE
数据产生错位，当数据无法横轴（category）对应时，使用[{name:'xx',value:'ss'}]无法生效

### ISSUE THREAD

**Issue by umi-soft** [apache/incubator-echarts#3933]
#### 问题简述 (One-line summary)

当横轴为category，纵轴为value的情况下，两个series，其中一个是完整的，与横轴完整对应，另一个存在缺失，也就是无法完整对应的时候，echarts却按照数组的顺序进行布局，这是个错误的结果，使用下面的option进行演示，2015年1月份，应该是没有值的才对，但是，却显示了2月份的值，并且，2015年的数据缺产生了错位
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
option = {
        legend: {
            data:['2015','2016'],
        },
        color: ['#c23531','#2f4554', '#61a0a8', '#d48265', '#91c7ae','#749f83',  '#ca8622', '#bda29a','#6e7074', '#546570', '#c4ccd3'],
            title : {
                show: true,
                text:'历史月度现金净流量分析(万元)',
                z:2,
                top:'top',
                left:'8%',
                textStyle:{
                    fontSize:'14'
                }
            },
        tooltip : {
            trigger: 'axis',
            enterable:true,
            axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
            },
            formatter:'{b}<br />{a0}:{c0}<br />{a1}:{c1}<br />{a2}:{c2}'
        },
        grid: {
                top:'8%',
            left: '5%',
            right: '5%',
            bottom: '15%',
            containLabel: true
        },
        xAxis : [
            {
                type : 'category',
                data : ['01','02','03','04','05','06','07','08','09','10','11','12'],
                axisTick: {
                    alignWithLabel: true
                },
                axisLabel: {
                    formatter: '{value}'
                }
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : [
            {
                name:'2015',
                type:'bar',
                yAxisIndex: 0,
                data:[{name:"02",value:"2222"},{name:"03",value:"2222"}]
            },
            {
                name:'2016',
                type:'bar',
                yAxisIndex: 0,
                data:[{name:"01",value:"2222"},{name:"02",value:"2222"},{name:"03",value:"2222"}]
            }
        ],
        dataZoom:[{
            type:'slider',
            xAxisIndex:[0],
            start:50,
            end:100,
            filterMode: 'filter',
            orient:'horizontal'
        }]
    };
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
name 和 category 轴没有关系，3 里你可以在数据里指定自己的类目：
```js
{
   data: [ ['类目1', 1], ['类目2', 2] ]
}
```

**Comment by me-who** [comment]
我也碰上同样的问题，由于多种类型的数据长度不一致，echart并不会自动匹配相同的横轴数据，导致横轴错乱，请问这个问题有好的解决方案吗？ @umi-soft
