### ISSUE TITLE
Position of outlier dots in boxplot

### ISSUE THREAD

**Issue by shujuwen2013** [apache/incubator-echarts#3944]
#### 问题简述 (One-line summary)

Outlier dots cannot be displayed properly when there are multiple categories.
All dots locate along with the central line of the panel, rather than their respective boxes.

It's OK when only one category
<img src=http://imgur.com/bNLSRUU.png>

But problem comes when more than one category
<img src=http://imgur.com/KscSJdX.png>

`series[i]-scatter.symbolOffset` can adjust the position of those dots somehow. But it's complicated and not elegant. More importantly it doesn't work when the plot has no access to the size of the canvas. 
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): ECharts 3
#### 期望结果 (Expected behaviour)

Outlier dots should automatically go along with their respective boxes.
I suggest this behavior be wrapped into boxplot.

**Comment by smihuc** [comment]
Hi, I was wondering if you ever plan to change this?

It's still happening in version 4.7.0.

![image](https://user-images.githubusercontent.com/45431828/81611486-5f376780-9398-11ea-8bc8-8800e76758c6.png)

It would be really nice if the outliers could line up with the boxes. Looking through old issues it looks like it did work in the past in [these screenshots](https://github.com/apache/incubator-echarts/issues/9017). (Maybe I just don't know how to set it up correctly, but I've tried everything I can think of and there's nothing in the documentation)

**Comment by eye8** [comment]
v5.0.1 仍然存在这个问题，多个series的箱型图自动生成的outlier scatter plot总是在中线上而不和相应的boxplot对其。麻烦修复一下，非常感谢！

Problem still exists in v5.0.1. The outlier scatter plot generated from mutl-series boxplots are aligned at the center instead of the corresponding boxplot. Please fix, thank you!

![Screen Shot 2021-06-22 at 8 51 23 PM](https://user-images.githubusercontent.com/1659798/122927645-a9f92080-d39b-11eb-9157-383dce684002.png)

**Comment by connor-hanson** [comment]
It would be really nice if this were implemented natively. 

However, you can workaround this issue by using the `renderItem` key for custom series. This function here has the math which echarts uses to calculate the bases of their boxplots. https://github.com/apache/echarts/blob/13c2d062e6bcd49ab6da87eb4032ac01ec9fe467/src/chart/boxplot/boxplotLayout.ts#L125-L137

Essentially what you want to do is copy the math that they do, and then multiply by the index of whichever scatter series in the plot you are rendering. Then add it to your output's `api.coord()` result on the x-axis. 

Here is a codesandbox link for how to solve this: https://codesandbox.io/s/example-echarts-outliers-alignment-5jp3jt

**Comment by ningyuv** [comment]
Thanks to [@connor-hanson](https://github.com/connor-hanson)'s solution in [codesandbox](https://codesandbox.io/s/example-echarts-outliers-alignment-5jp3jt), it helps me a lot.
Besides, here is a way to calculate `NUM_BOXPLOTS_IN_COL` and fit the legend toggle with some extra code.
```js
function moveOutliers(api, seriesIndexInCol) {
    const numBoxplotsInCol = api.currentSeriesIndices().length / 2;
    seriesIndexInCol = api.currentSeriesIndices().findIndex((value) => value === seriesIndexInCol);
...
    return {
        type: "circle",
...
        transition: "all"
    };
}
```
Here is the codesandbox: [https://codesandbox.io/s/example-echarts-outliers-alignment-forked-tbyhck](https://codesandbox.io/s/example-echarts-outliers-alignment-forked-tbyhck?file=/src/index.js).

**Comment by ddt313** [comment]
@connor-hanson @ningyuv  Do you know the meaning of 0.8, 2, and 0.3 in the code
``` js
const availableWidth = bandWidth * 0.8 - 2; 
const boxGap = availableWidth / seriesCount * 0.3; 
```

**Comment by youranreus** [comment]
> Thanks to @connor-hanson's solution in [codesandbox](https://codesandbox.io/s/example-echarts-outliers-alignment-5jp3jt), it helps me a lot. Besides, here is a way to calculate `NUM_BOXPLOTS_IN_COL` and fit the legend toggle with some extra code.
> 
> ```js
> function moveOutliers(api, seriesIndexInCol) {
>     const numBoxplotsInCol = api.currentSeriesIndices().length / 2;
>     seriesIndexInCol = api.currentSeriesIndices().findIndex((value) => value === seriesIndexInCol);
> ...
>     return {
>         type: "circle",
> ...
>         transition: "all"
>     };
> }
> ```
> 
> Here is the codesandbox: [https://codesandbox.io/s/example-echarts-outliers-alignment-forked-tbyhck](https://codesandbox.io/s/example-echarts-outliers-alignment-forked-tbyhck?file=/src/index.js).

this comment really helps a lot (0.0)b

**Comment by EddyHaigh** [comment]
Unless I'm missing something this seems to still be an issue with boxplots that requires an overly complicated hack. It does feel like outliers were an after thought.
