### ISSUE TITLE
Map zoom / move event missing

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3958]
Version: 3.2.3
Would be great if there are "mapzoom" and "mapmove" events. 

An example is a custom map showing pie charts: 

![image](https://cloud.githubusercontent.com/assets/561365/18056679/341b6a1a-6e0d-11e6-9d18-b12b4da65b29.png)

I'd like to update position of pie charts when user zooms or moves the map:) 

Or is there any workaround to this?

**Comment by jarben** [comment]
Actually - I was browsing the code and found the "geoRoam" event which does the job:) Is this an official event that can be added to docs?

**Comment by pissang** [comment]
Yes you can use `geoRoam` event. We didn't put it on the doc because it's event parameters are not that easy to use

**Comment by iamindian** [comment]
geoRoam zoom data is wrong?
