### ISSUE TITLE
dataZoom的filterMode为"empty"且在缩放到只显示一个柱状图的时候,该柱状图的tooltip以及高度绘制错误

### ISSUE THREAD

**Issue by ruizhen** [apache/incubator-echarts#3983]
#### 问题简述 (One-line summary)

dataZoom的filterMode为"empty"且在缩放到只显示一个柱状图的时候,该柱状图的tooltip显示的数据以及高度绘制错误.
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):  3.23
- 浏览器类型和版本 (Browser version): chrome 52.0.2743.116m
- 操作系统类型和版本 (OS Version): window7
#### 重现步骤 (Steps to reproduce)
1. 设置一个柱状图demo,柱状图的series的data数组大于1,并且每个data成员值不一样.
2. 设置dataZoom,type为slider或者inside都可以,但设置filterMode为 "empty",
   3.缩放图表,让柱状图最终只显示一个数值最小的
3. 当缩放到当前视口柱状图个数大于1的时候,最小的柱状图的高度正确.但当缩放到当前视口柱状图个数为1的时候,且该柱状图不为最大数值的(最好是和最大值的柱状图差别大的),该柱状图的高度变成了data数组里最大的值的高度.
   5.tooltip会显示最高的那个柱状图的tooltip,而不是当前所指的柱状图的tooltip
#### 期望结果 (Expected behaviour)

缩放到只有一个柱状图的时候,当前所见柱状图的高度应该正确.
并且tooltip应该显示当前所指的柱状图的tooltip
#### 可能哪里有问题 (What went wrong)

不太清楚
#### ECharts配置项 (ECharts option)

``` javascript
    option = {
        tooltip : {
            trigger: 'item'
        },
        legend: {
            data: ["A", "B", "C", "D"],
            itemGap: 5
        },
        grid: {
            top: '12%',
            left: '1%',
            right: '10%',
            containLabel: true
        },
        xAxis: [
            {
                type : 'category',
                data : ["A", "B", "C", "D"]
            }
        ],
        yAxis: [
            {
                type : 'value',
                name : 'Budget',
            }
        ],
        dataZoom: [
            {
                type: 'slider',
                show: true,
                startValue: 0,
                endValue: 0,
                filterMode: 'empty',
                handleSize: 8
            },
            {
                type: 'inside',
                filterMode: 'empty',
                startValue: 0,
                endValue: 0,
            }
        ],
        series : [
            {
                name: 'test',
                type: 'bar',
                data: [100, 200, 300, 400]
            }
        ]
    };

```

**Comment by z3rog** [comment]
damn it. i ran into the same problem. and this issue was opened in almost 3 yrs ago ???
