### ISSUE TITLE
datazoom 缩略图能响应 xAxis设置的max , min值吗，以及只能映射一个serie的数据吗

### ISSUE THREAD

**Issue by jincui** [apache/incubator-echarts#3986]
#### 问题简述 (One-line summary)

datazoom 的缩略图始终与xAxis(type="time")未设置max,min即默认状态下的趋势保持一致，能否和设置max,min之后的整体趋势一样。
series中设置了多组数据，但datazoom的趋势缩略图始终只映射了series[0]对应数据
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.2
- 浏览器类型和版本 (Browser version):Chrome
- 操作系统类型和版本 (OS Version):win10
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by shikelong** [comment]
> series中设置了多组数据，但datazoom的趋势缩略图始终只映射了series[0]对应数据

这条问题 +1
