### ISSUE TITLE
每2秒刷 -》如果  series 数量里面 是{id:XX,name:XX ,value:22222}这样形式 ，图形显示错乱，

### ISSUE THREAD

**Issue by tsw424** [apache/incubator-echarts#3991]
#### 问题简述 (One-line summary)

面板的点点 错乱
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
  win10    echarts 3
#### 重现步骤 (Steps to reproduce)
1.  属性

``` js
 var  option =   {
            title: {
                text: '平均方法曲线',
                left: 'center'
            }   ,
           legend: {
               data: legend
           }  ,
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            xAxis: {
                type: 'category',
                name: '时间',
                splitLine: {show: false},
                data: flushArray(xAxisMain ,queueLen)
            },
            yAxis: {
                type: 'value',
                name: 'AVG-Cost'
            },
            tooltip: {
                trigger: 'axis',
                formatter: '{a} <br/>{b} : {c}'
            } ,
            series:  makeData(  allfn  )
        } ;
```

2.数据如下是对象，而不是数字，如果是数字没有错
({
                            times:  dataarr[1]
                            ,type:"line"
                            , step: 'start'
                            ,name:"调用次数:"+  dataarr[1]
                            , value: parseInt(dataarr[0] )
                            ,id:dataarr[2]+""
                        }
#### 期望结果 (Expected behaviour)

不会出现   错乱的点点。
#### 可能哪里有问题 (What went wrong)

可能绘制 传入对象，和 数字的区别到时问题， 速度也明显变慢。。。
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
请描述具体问题

**Comment by tsw424** [comment]
找到了一个可能的原因：如果定时绘制图形，  方面里面重新生存一次队形，就会重绘画布
 myChart   = echarts.init(document.getElementById('mainInner'));

如果不在方法里面重新生成一个对象，直接  myChart.setOption(   option     ); 

 就会吧原来的元素的一些点点保留着，  我的 数据是 递增了 比如原来是一个数据一直增加到50个点数据，绘制成折线；
没把贴图可惜了。。。

**Comment by tsw424** [comment]
同时发现 chrome的 cpu占用降低到10% 之前是16%  ，  

现在性能分析：第一行21.42 %，之前应该确定是 26% 左右

chrome 性能分析：
32388.6 ms	32388.6 ms	(idle)	
1401.7 ms21.42 %	1401.7 ms21.42 %	(program)	
814.8 ms12.45 %	814.8 ms12.45 %	(anonymous function)	
446.2 ms6.82 %	446.2 ms6.82 %	fillText	
312.8 ms4.78 %	312.8 ms4.78 %	requestAnimationFrame	
191.4 ms2.92 %	2332.2 ms35.64 %	echarts.min.js:25s._update	
170.9 ms2.61 %	170.9 ms2.61 %	(garbage collector)


firefox:  不好复制分析结果 。

排在第一位耗时：   是GC，  39%   第二位是 图形绘制： 10.3%
