### ISSUE TITLE
多个饼图共用一个legend时，怎样在legend hover时多个图的数据都显示放大效果

### ISSUE THREAD

**Issue by iamwelk** [apache/incubator-echarts#4002]
#### 问题简述 (One-line summary)

目前两个饼图在使用同一个legend时，只有第一个图会在legend hover时半径变大。怎样让其他饼图的对应的数据的半径也一起变大？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by BlazerYang** [comment]
同问

**Comment by DukeGJ** [comment]
看起来高亮只支持多个图表中的第一个，我试过在series中调整lengedHoverLink但是并不行，echarts2中效果是存在的：http://echarts.baidu.com/echarts2/doc/example/pie.html#

**Comment by 100pah** [comment]
legend 是靠 name 来引用多个图的。比如，多个系列，设置相同的 `series.name`，就可以被同时高亮。

**Comment by BlazerYang** [comment]
@100pah 我的series.name不一致，改成一样就可以了，感谢！
@DukeGJ 你可以按楼上方法试一试

**Comment by JackZhouMine** [comment]
请教一个问题，一个图表里有多个饼图时，需要给每个饼图一个标题，比如第一个饼图时2018年1月好的数据产生的，在饼图下方显示2018年01月03号，第二饼图的数据是2018年1月4号产生的，在下方显示2018年01月04号。请问如何显示这样的效果呢？
