### ISSUE TITLE
dispatchAction不能操作data以外的数据项&tooltip在Graph组件中显示错误

### ISSUE THREAD

**Issue by JustPlay1994** [apache/incubator-echarts#4006]
#### 问题简述 (One-line summary)

mainQuestion:
        在使用关系图graph组件时，通过外部点击事件想要触发echarts中showTip和highlight的事件时，发现只能使用data作为目标，而不能够使用links作为目标数据项。
others:
       1.当关系图放大后，鼠标选中线段，tooltip的显示在屏幕之外。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts 3):
- 浏览器类型和版本 (Browser chrome 51.0.2704.106 m):
- 操作系统类型和版本 (OS windows7):
#### 重现步骤 (Steps to reproduce)

dispatchAction({
    type: 'highlight',
    // 可选，系列 index，可以是一个数组指定多个系列
    seriesIndex?: number|Array,
    // 可选，系列名称，可以是一个数组指定多个系列
    seriesName?: string|Array,
    // 可选，数据的 index
    dataIndex?: number,
    // 可选，数据的 名称
    name?: string
})
#### 期望结果 (Expected behaviour)

dispatchAction只能针对data当中的数据。
通过dispatchAction无法高亮关系图中links的数据。
#### 可能哪里有问题 (What went wrong)

main:DispatchAction是否能增加对除了data以外的数据项的支持。
常用的是highlight、showTip。
other:对于关系图中links的tooltip没有进行重定位。
#### ECharts配置项 (ECharts option)

``` javascript
myOption1 = {
        tooltip:{
            trigger:"item",
            position:"top",
            hideDelay:100,
            showDelay:200,
            enterable:true
        },
        //animation:false,
        series:[
            {
                backgroundColor: "transparent",
                type: "graph",
                //symbolSize:50, 
                name: 'Les Miserables',
                layout: 'force',   
                force:{
                    repulsion:1000,
                    edgeLength:100
                },
                roam: true,
                label: {emphasis: {show: false}},  
                draggable: true,     
                data:myData,
                links:myLinks
            }
        ]
    };

```
#### 其他信息 (Other comments)

放大之前tooltip可见
![image](https://cloud.githubusercontent.com/assets/21258024/18235225/ade3b3e2-734a-11e6-9892-a22d3bb93ed3.png)
放大之后tooltip不可见
![image](https://cloud.githubusercontent.com/assets/21258024/18235189/4578363e-734a-11e6-9735-326920b41c31.png)

**Comment by chengwubin** [comment]
mark，望可支持markpoint等的showTIp
