### ISSUE TITLE
在不改变其它option的情况下重设series

### ISSUE THREAD

**Issue by k8w** [apache/incubator-echarts#4010]
#### 问题简述 (One-line summary)

这个问题已经困扰多日
想要在不改变其它 option 的情况下重设 `series`

**例如**
series中目前有5条线，现在想重设为另外3条线；
但是由于merge的关系，多出的两条线不能被清除。
如果用 `notMerge` 的形式 `setOption`，则会重置 `dataZoom` 的缩放范围，并且也不是很方便（只是想重设 `series`，并不想重新设置其它option）
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.3
- 浏览器类型和版本 (Browser version): Chrome
- 操作系统类型和版本 (OS Version): Win7
#### 重现步骤 (Steps to reproduce)
1. `chart.setOption({series:[ { Series1 },  { Series2 },  { Series3 }  ] })`
2. `chart.setOption({series:[ { Series1 },  { Series2 } ] })`
#### 期望结果 (Expected behaviour)

此时屏幕上只有2根线
#### 可能哪里有问题 (What went wrong)

除merge和整体notMerge的setOption方式之外，
需要一种“局部重设”的setOption机制，
如整体重设series，直接赋值的形式，而非merge。
对于动态的图表，这个场景应该是比较普遍的。

**Comment by pissang** [comment]
在当前的逻辑下没想到特别好的清除 series 的方法，你觉得方便的从 5 个系列变为 3 个系列的接口应该是怎么样的？

**Comment by twoeo** [comment]
@pissang 
例如目前的 `setOption` 是 `setOption(option, notMerge, lazyUpdate)`
其中第二个参数改成 `setMethod` (setOption的方式)，可能的值包括 `replace` `assign`  `merge`
当为 `replace` 时，等同于之前 `notMerge` 为 `true` 的情况；
当为 `merge` 时，等同于之前 `notMerge` 为 `false` 的情况；
当为 `assign` 时，等同于 `newOption = Object.assign( oldOption, option )`。
默认情况下是 `merge`， 当为 `true` 时当做replace以向前兼容。

**Comment by RBowind** [comment]
现在这个问题现在有解决方法吗？正好遇上。

**Comment by k8w** [comment]
@RBowind 我是先get再set 可以临时解决一下

**Comment by RBowind** [comment]
@k8w 多谢啦，回头试试。朋友推荐了下HighCharts，感觉也不错。

**Comment by HadesTang** [comment]
@k8w 请问下先get再set具体如何操作？
