### ISSUE TITLE
resize方法无法让坐标轴的label对区域的大小做自适应

### ISSUE THREAD

**Issue by WebsonLeo** [apache/incubator-echarts#4012]
#### 问题简述 (One-line summary)

在图形所在的div变小时，对图形进行resize，但已有折线图的X轴label数量并不会随着div的变小而变少来保证label不重叠
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts 3.2.2):
- 浏览器类型和版本 (Chrome 52.0.2743.116 m):
- 操作系统类型和版本 (windows7 专业版):
#### 重现步骤 (Steps to reproduce)

1.在一个可变的div中绘制一张时间轴的折线图
2.当div变化时，调用resize方法
#### 期望结果 (Expected behaviour)

div变小时，如果label的数量过多，resize方法绘制的图应该适量减少label的数量来保证label不会重叠影响展示
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/17735331/18239242/8eb2fa60-7376-11e6-864e-c377d46cb109.png)
![image](https://cloud.githubusercontent.com/assets/17735331/18239261/b62f697a-7376-11e6-93e3-b3e48ccdd854.png)

**Comment by EyrebaLeo** [comment]
各位大神求帮忙。。难道要根据div实时计算能够容纳几个label，再计算interval吗，我们的div是可放大缩小的，那样做的话，在数据量比较打的时候，缩放会变得非常卡顿

**Comment by EyrebaLeo** [comment]
@pissang 麻烦看一下还有优化的空间吗？或者有没有什么好方法来解决这个问题呢
