### ISSUE TITLE
关系图表如何禁止画布可拖拽？

### ISSUE THREAD

**Issue by kaixin3946** [apache/incubator-echarts#4013]
#### 问题简述 (One-line summary)

画出的关系图表 type=graph 不希望它在拖拽画布的时候可移动，设置draggable:false;不好使，是不是由其他方式禁止？
同时发现网站示例中 effectScatter，treemap，lines有同样的问题
而 pie、line、bar 没有这样的问题~

求解答~谢谢~
#### 版本及环境 (Version & Environment)
- ECharts 版本( ECharts 3.2.2):
- 操作系统类型和版本 (windows 7):
#### ECharts配置项 (ECharts option)

![image](https://cloud.githubusercontent.com/assets/13850484/18240956/39b9cdee-7381-11e6-8f14-bd95f15046a6.png)

**Comment by pissang** [comment]
`roam: false`
