### ISSUE TITLE
OPPO部分手机运行官网例子会出现图表重复的情况

### ISSUE THREAD

**Issue by xmchyabi** [apache/incubator-echarts#4015]
#### 问题简述 (One-line summary)

我手机浏览器打开官网的例子
http://echarts.baidu.com/demo.html#confidence-band

当chart.resize后，或者更新setOption后，图表里就会显示出两个折线
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.3
- 浏览器类型和版本 (Browser version): 
- 操作系统类型和版本 (OS Version):
  OPPO手机  型号 R7007
  OS： ColorOS V1.4.0
  Android版本：4.3
  自带浏览器版本：V2.0_0955_140515

```


```

**Comment by xmchyabi** [comment]
我想添加附件，老是上传不成功

**Comment by wu11106** [comment]
不见有P7007，看到是R7s与R7Plus

2016年9月5日星期一，xmchyabi <notifications@github.com> 写道：
