### ISSUE TITLE
自定义geojson的多边形，部分简单多边形渲染不出来

### ISSUE THREAD

**Issue by weiletian28** [apache/incubator-echarts#4017]
#### 问题简述 (One-line summary)

我自己生成了一个geojson面数据，格式是没问题的，已经确认过。现在发现有些简单的多边形，比如说面积较小的矩形，能画出边线，但是填充的渲染出不来。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):最新版本
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {
series: [
            {
                name: '测试geojson',
                type: 'map',
                mapType: 'HK', // 自定义扩展图表类型
                itemStyle:{
                    normal:{label:{show:false},areaColor:'orangered'},
                    emphasis:{label:{show:true}}
                },
                data:[]
            }
        ]
}

```
#### 其他信息 (Other comments)

我是在线上示例测试的：http://echarts.baidu.com/demo.html#map-HK
如下图所示，橘红色是能正常渲染的，空心的多边形是渲染不了的。
![image](https://cloud.githubusercontent.com/assets/3360892/18243750/2bd6c192-738f-11e6-984a-d88b4646be2e.png)

**Comment by pissang** [comment]
发下自定义的 geoJson 呗

**Comment by weiletian28** [comment]
以下是自定义的geojson
[mygeojson.txt](https://github.com/ecomfe/echarts/files/455763/mygeojson.txt)

**Comment by weiletian28** [comment]
用谷歌出问题，用ie没问题，如下图是ie的效果：
![image](https://cloud.githubusercontent.com/assets/3360892/18266600/09b18c2c-744e-11e6-896f-f42fd3a91645.png)

**Comment by pissang** [comment]
可能是 chrome 下精度的问题，可以试试坐标都乘上 100

**Comment by weiletian28** [comment]
嗯，我试下。
不过这个问题还是得解决才行，因为我的系统会按月更新千万级别的点数据，在地图上定位展示，那么所有点都需要乘以100，这个处理起来不太合理。

**Comment by weiletian28** [comment]
坐标乘以100后显示正常了。不过因为地图上叠加的业务数据较多，不太可能都乘100，希望能解决这个问题，谢谢！

**Comment by jarben** [comment]
Just found the same issue (Chrome only, highlighted areas are not colored for some reason): 

![image](https://user-images.githubusercontent.com/561365/37203283-774c934a-238d-11e8-9ea4-9f3148218b2b.png)

GEO: [brno_geo.json.gz](https://github.com/ecomfe/echarts/files/1796491/brno_geo.json.gz)

Sorry I didn't get the workaround, should I regenerate the JSON with each point * 100? Wouldn't it be non lat long format then? Any other workaround? 

Also noticed these areas change when zooming, maybe the precision fix can be solved in the geo layer? 

Thanks!
