### ISSUE TITLE
能否设置Axis中label和指示线的上下偏移量？

### ISSUE THREAD

**Issue by Nataila** [apache/incubator-echarts#4030]

**Comment by pissang** [comment]
什么意思？

**Comment by Nataila** [comment]
比如Y轴的label，相对默认位置向上调整10px，支持这样吗

**Comment by 100pah** [comment]
可以试试 <http://echarts.baidu.com/option.html#yAxis.nameGap> 或 <http://echarts.baidu.com/option.html#yAxis.axisLabel.margin>

**Comment by jinphen** [comment]
@100pah  试了这个方法，行不通。在移动端这个需求蛮强烈的，如图
 ![](https://img.yzcdn.cn/public_files/2017/03/02/9c10f727c8df6ffd72f7487cd2b2ea7f.png)

**Comment by zuoez02** [comment]
@jinphen 可以试试yAxis.axisLabel.formatter，输出的时候前面加个‘\n“,方法作弊了点但是有效
