### ISSUE TITLE
echarts3版本中对应地图获取经纬度方式？

### ISSUE THREAD

**Issue by liyangli** [apache/incubator-echarts#4036]
#### 问题简述 (One-line summary)

1、公司项目中原先为echarts2.2.7现在统一升级到echarts3.2.3版本。发现对应之前获取地图的经纬度方式是无法生效，找echarts3.2.3中相关文档中没有说明怎么获取经纬度，目前获取经纬度方式是什么？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.3
- 浏览器类型和版本 (Browser version): Chrome
- 操作系统类型和版本 (OS Version): win7
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
是否可以描述下具体想怎么获取经纬度。

**Comment by liyangli** [comment]
之前获取在div上获取经纬度方式
`var graphValArr=self.mychart.chart.map.getGeoByPos(MAPTYPE,[_x,_y]);`
echart3中有没有类似方式获取地图展示上精确的经纬度？
