### ISSUE TITLE
关系图Series数组 重叠错位

### ISSUE THREAD

**Issue by ConlenLi** [apache/incubator-echarts#4044]
#### 问题简述 (One-line summary)

series[{series1},{series2}] 里面date 用坐标定位  1和2 会叠在一起 显现两个不同的图层，怎么让他们在一个图层 处在一个坐标系里面？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version):google
- 操作系统类型和版本 (OS Version):windows8
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

series[{series1},{series2}] 里面date 用坐标定位  不干扰 出现在一个坐标系里面 
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
没有看懂你的描述。series 的 type 是什么，什么坐标系。

如果是直角坐标系，那么 xAxis 都引用同一个 grid，就在一个坐标系中。

**Comment by 100pah** [comment]
为何要使用两个 series？关系图最好使用一个 series。

**Comment by pissang** [comment]
建议在一个 series 用不同 category 区分

**Comment by ConlenLi** [comment]
用category 区分 自定义symbol的时候  设为图片 显示不出来  在echarts2版本中可用

**Comment by ConlenLi** [comment]
![qq 20160919103046](https://cloud.githubusercontent.com/assets/22068809/18621335/31e7293a-7e54-11e6-937f-2962f66cda10.png)
![qq 20160919103057](https://cloud.githubusercontent.com/assets/22068809/18621337/3c59a97e-7e54-11e6-9592-49194abec7f3.png)
![qq 20160919103052](https://cloud.githubusercontent.com/assets/22068809/18621340/49f42dc0-7e54-11e6-8f71-ab4316c3d05d.png)

**Comment by ConlenLi** [comment]
分类只改变了颜色 没有改变symbol  设置大小也改变不了
