### ISSUE TITLE
Click 怎么实现像本身鼠标移入一样的效果

### ISSUE THREAD

**Issue by ConlenLi** [apache/incubator-echarts#4045]
#### 问题简述 (One-line summary)

有许多相同的点 当点击某一个节点的的时候 需要改变其内容 没有类选择器 应该如何实现？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

同一种节点（以图片设置的symbel） 点击某一个 切换图片 其他的也可以 实现这个功能 不重复写那么多方法
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
监听鼠标事件，在里面 setOption，是否能达到你的效果。

**Comment by ConlenLi** [comment]
需要的是多个 可以实现 param  参数里面 应该获取什么？

**Comment by 100pah** [comment]
param 里有被点击的 data 项信息，参见文档。
