### ISSUE TITLE
雷达图有null值时显示不正常

### ISSUE THREAD

**Issue by nighthun** [apache/incubator-echarts#4047]
#### 问题简述 (One-line summary)

普通雷达图数据中有null值时，数据无法正常连线，如果鼠标移动到某个数据点上，则显示正常
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.3
- 浏览器类型和版本 (Browser version): chrome51
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.直接使用下面的option在官网中查看效果
2.
![image](https://cloud.githubusercontent.com/assets/10071831/18372027/c0f9c3c6-766b-11e6-9e36-1e31ed9ddfdd.png)
#### 期望结果 (Expected behaviour)

![image](https://cloud.githubusercontent.com/assets/10071831/18372033/cb57d9ca-766b-11e6-9594-02588ccaf2fb.png)
#### ECharts配置项 (ECharts option)

``` javascript
option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）']
    },
    radar: {
        // shape: 'circle',
        indicator: [
           { name: '销售（sales）', max: 6500},
           { name: '管理（Administration）', max: 16000},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, null, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            }
        ]
    }]
};

```

**Comment by nighthun** [comment]
没人理我，，这个问题会修改么？

**Comment by 100pah** [comment]
若要暂时解决这个问题，缺失数据时，可以手动设成 0（或者最小值之类）。

**Comment by nighthun** [comment]
您好，处理成0，显示效果是不一样的，意义也不同，先处理0，等更新吧。

**Comment by Ovilia** [comment]
Fixed in #8962
