### ISSUE TITLE
K线图无法禁用tooltip

### ISSUE THREAD

**Issue by firstsko** [apache/incubator-echarts#4049]
name: code,
285                  type: 'candlestick',
286                  data: [],
287                  itemStyle: {
288                      normal: {
289                          color: '#C50000',
290                          color0: '#1AB667',
291                          borderColor: null,
292                          borderColor0: null
293                      }
294                  },
295                  tooltip: {
296                      show: false,
297                      formatter: function(param) {
298                          var param = param[0];
299                          return [
300                              '日期: ' + param.name + '<hr size=1 style="margin: 3px 0">',
301                              '开盘: ' + param.data[0] + '<br/>',
302                              '收盘: ' + param.data[1] + '<br/>',
303                              '最低: ' + param.data[2] + '<br/>',
304                              '最高: ' + param.data[3] + '<br/>'
305                          ].join('');
306                      }
307                  },
}

false以后照样显示，而且formatter 无效

**Comment by pissang** [comment]
什么版本？
