### ISSUE TITLE
动态添加数据，每次添加数据，都会把dataZoom初始化？

### ISSUE THREAD

**Issue by Nataila** [apache/incubator-echarts#4055]
#### 问题简述 (One-line summary)

动态添加数据的时候，每次添加数据，dataZoom都会恢复到最初始的值，这有解决办法吗？
#### 期望结果 (Expected behaviour)

动态添加数据的时候不影响dataZoom的使用（即不会把滚动条缩放到初始值）

http://echarts.baidu.com/demo.html#dynamic-data

该示例，修改dataZoom.show=true, start=50%;即可重现，拉宽dataZoom,添加数据之后又恢复原来的样子了

**Comment by pissang** [comment]
setOption 第二个参数不要传 true 就不会

**Comment by Nataila** [comment]
@pissang  示例并没有传true?

**Comment by Nataila** [comment]
@pissang  改了也不行  我写了个demo  
http://jsbin.com/jamuzayaxo/edit?html,js,output 
dataZoom默认开始在50%的位置
先把dataZoom拉到0%位置，数据更新后，dataZoom的开始位置又回到了50%

**Comment by pissang** [comment]
你新设置的 option 里还带着 dataZoom 的 start，end，当然会重置

**Comment by lany9527** [comment]
http://jsbin.com/jamuzayaxo/edit?html,js,output

我试试了 真的不得 随着数据的增加 图比例会变
