### ISSUE TITLE
请问坐标轴 label 小数精度 问题怎么解决？

### ISSUE THREAD

**Issue by wn0112** [apache/incubator-echarts#4059]
#### 问题简述 (One-line summary)

请问坐标轴 label 小数精度 问题怎么解决？ 如下图：
![image](https://cloud.githubusercontent.com/assets/14155504/18407622/8927945e-7748-11e6-88c1-b9f5fc7a97d6.png)

Y 轴刻度变成了 1.00000000000003 这种。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):  3.2.3
- 浏览器类型和版本 (Browser version): chrome v51.xxx
- 操作系统类型和版本 (OS Version): Windows 7

**Comment by 100pah** [comment]
可使用 <http://echarts.baidu.com/option.html#yAxis.axisLabel.formatter>
