### ISSUE TITLE
图表刷新问题

### ISSUE THREAD

**Issue by jiangdragon** [apache/incubator-echarts#4065]
#### 问题简述 (One-line summary)

想要局部更新图表内容（能否支持）。
如：要用到地图，想让每个区块的色彩据后台时实数据变化而发生变化，不想让整个地图重绘，只想针对当前更改的区域进行重绘。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
现在所有重绘有性能问题？
