### ISSUE TITLE
viewport 缩放0.5 dpr如何设置，目前显示图表文字过小

### ISSUE THREAD

**Issue by gfel** [apache/incubator-echarts#4072]
viewport 缩放0.5 dpr如何设置，目前显示图表文字过小

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#textStyle.fontSize 不建议设置 dpr，会导致显示模糊

**Comment by shangxinbo** [comment]
模糊不模糊的是次要，关键要协调啊，一个force图，缩小了，只剩下文字了，感觉很不和谐

**Comment by shangxinbo** [comment]
可以接受文字缩小到一定程度就隐藏
