### ISSUE TITLE
Geo.dataToPoint() question

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4076]
Version: 3.2.2

I'm generating a map with stacked column charts: 
![image](https://cloud.githubusercontent.com/assets/561365/18464093/0e687622-798f-11e6-9a33-2a6450803547.png)

where column charts are positioned using unofficial geo coordinate system API: 
var xy = geo.dataToPoint(latlong);

It roams perfectly fine when there is no geo center specified:
![datatopoint1](https://cloud.githubusercontent.com/assets/561365/18464162/ad2ef5ec-798f-11e6-9d12-8c93c1dbd2c5.gif)

However, if I set center:[] such as this:
![image](https://cloud.githubusercontent.com/assets/561365/18464181/c28e432a-798f-11e6-89d7-ec52bc51422c.png)

roaming is not working as expected (column chart jumps):
![datatopoint2](https://cloud.githubusercontent.com/assets/561365/18464271/3a2f98c0-7990-11e6-9519-2b8174705889.gif)

What is interesting is that those green triangles (scatter symbols) work without any issues. However I wasn't able to find whether there is another method I could use to get XY correctly from geo coordinates. 

Is there any way to retrieve correct XY from geo coordinate @pissang? Or is this a possible bug? 

Thanks for any info!

**Comment by pissang** [comment]
It seems to be a bug of echarts. Can I have more detailed code?

**Comment by jarben** [comment]
Hi @pissang , here is a code example that can be pasted into your examples code editor at http://echarts.baidu.com/examples.html

[zoom-issue-geo.zip](https://github.com/ecomfe/echarts/files/482423/zoom-issue-geo.zip)

You can see this result when zoomed: 
![zoom-geo-issue](https://cloud.githubusercontent.com/assets/561365/18668795/e97638e6-7f37-11e6-8c38-8327e72c0f47.gif)

See that scatter is updating correctly where xy position of the grid is not. 

If you remove center:
![image](https://cloud.githubusercontent.com/assets/561365/18668843/2899b3ea-7f38-11e6-983f-1d8650cdfd4c.png)

 it works as expected..

Thanks for looking at it!

**Comment by 100pah** [comment]
Check this <http://gallery.echartsjs.com/editor.html?c=xH1er8rGT&v=1> please.

The `update` function is modified as follows and all correct:
```js
var update = function(){
    var model = myChart.getModel();
    var geo = model.getComponent('geo').coordinateSystem;
    var latlong = ["14.550072", "47.516231"];
    var xy = geo.dataToPoint(latlong);

    var grid = option.grid[0];
    grid.left = xy[0];
    grid.top = xy[1]-grid.height;

    myChart.setOption({
        grid: {
            left: xy[0],
            top: xy[1] - grid.height
        }
    });
}                    
```

**Comment by jarben** [comment]
I see, thanks heaps @100pah! Your gallery looks awesome btw!
