### ISSUE TITLE
仪表盘浮点数字显示bug。即便指定小数位数，仪表盘也会将内存中的浮点位显示出来

### ISSUE THREAD

**Issue by Wall-ee** [apache/incubator-echarts#4095]
#### 问题简述 (One-line summary)

仪表盘显示数据的时候，即使在js当中指定了小数位数，也还是会在图片当中，将浮点类型的浮点数字显示出来。
例如：
数字为:13.899
但是图片中显示为 13.8999999999997
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
- echart: 3
- 浏览器: chrom  firefix safari
#### 重现步骤 (Steps to reproduce)
1. 用angularjs  设置小数位数 x.toPrecision(2)
2. detail:{formatter:'{value}%'},data:[{value:priceShock,name:'价格冲击'}]
#### 期望结果 (Expected behaviour)

不要再有浮点数字的出现。即能正确显示出截取的小数位数
#### 可能哪里有问题 (What went wrong)

{%value}
这个部分出现了问题
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

参考链接:
http://www.worisk.com/risk-engine/product-profile/stock/002466.html

**Comment by pissang** [comment]
在 formatter 里处理下吧

**Comment by Wall-ee** [comment]
好的  ，那有没有相关设置小数位数的说明 API 或者示例代码呢？  谢谢谢谢啦，我在手册里好像没找到

**Comment by pissang** [comment]
`detail.formatter` 文档里貌似漏了，抱歉

**Comment by Wall-ee** [comment]
OK 已经搞定

**Comment by feichangtutu** [comment]
怎么解决的？

**Comment by Wall-ee** [comment]
用javascript 原生方法
