### ISSUE TITLE
桑基图可以旋转为上下结构么？能不能加入桑基图的边添加流动的效果？

### ISSUE THREAD

**Issue by hejingjing0822** [apache/incubator-echarts#4098]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts 3):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
你们是什么样的场景，需要『上下结构的桑基图』？

**Comment by hejingjing0822** [comment]
类似于网络流量的 原型和UI都设计成了上下结构的 而且流出的边还需要有动态的效果

**Comment by 100pah** [comment]
现在还不支持上下结构的桑基图

**Comment by hejingjing0822** [comment]
恩 好的 谢谢，那我想问一下有别的方式实现类似于这种效果的吗？
