### ISSUE TITLE
地图上添加热力图，如何设置图层分界效果

### ISSUE THREAD

**Issue by guananny2** [apache/incubator-echarts#4106]
#### 问题简述 (One-line summary)

[http://blog.csdn.net/yc_1993/article/details/52432005?mType=Group#reply](url)
如这个页面时最后2个图片显示的，可以清晰的显示出不同颜色的层次效果，类似色斑图的效果，eCharts的热力图可以设置成这样吗？？（网页上的效果是问了作者本人，图片质量变差才出现的），非常感谢，如果能够恢复的话~
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/demo.html#heatmap-large-piecewise

**Comment by guananny2** [comment]
你的回复是直角坐标系的热力图展示，我想在地图页面添加热力图，而且数值的点是离散的，这种情况可以使用吗？

**Comment by 100pah** [comment]
你可能想要的是类似于等高线图，现在还不支持。

**Comment by guananny2** [comment]
谢谢你的回复，这条路行不通，只能另辟他径了~
