### ISSUE TITLE
关于echarts的dataview功能

### ISSUE THREAD

**Issue by Tairr** [apache/incubator-echarts#4114]
#### 问题简述 (One-line summary)

请教两个问题：
1). echarts带有的dataview功能，刷新 关闭按钮的样式(位置)怎么设置？在页面写的style不生效;
2). echarts带有的dataview功能，用optionToContent将数据展示到table一个内，能否将数据导出(保存到excel)(以文本或图片形式);
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):ie9
- 操作系统类型和版本 (OS Version):win7
#### ECharts配置项 (ECharts option)

``` javascript

                var option = {
                noDataLoadingOption: {
                        text: ${year}+'年1-'+${month}+'月外贸接卸量暂无数据',
                        effect : 'whirling',
                        effectOption: {
                            effect: {
                                n: 0
                            }
                        },
                        textStyle : {
                        fontSize : 18,
                         fontWeight: 'bold'
                    }
                },
        title : {
                text: ${year}+'年1-'+${month}+'月各港口外贸船接卸货量',
                x:'center'
            },
            tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c}万吨 ({d}%)"
            },
            legend: {
               show:false,
                orient : 'vertical',
                x : 'right',
                y : "bottom",
                data:${legend} //['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']//注意legend数据跟series里面的名称匹配
            },
            toolbox: {
                show : true,
                padding:45,
                feature : {
                    mark : {show: false},
                    dataView : {show: true, 
                  readOnly: true,
                    optionToContent: function(opt) {

                                    var table = '<table class="data_tab" style="width:100%;text-align:center"><tbody>';
                            table +='<tr><td ></td>';
                                   table += '<td >'+${year}+'年</td>';
                                   table += '<td >'+(${year}-1)+'年</td>';
                                    table +='<td >同比增减</td>';
                                   table +='<td >同比增幅</td></tr>';
                                   table +='<tr><td >外贸全部港口</td>';
                                   table += '<td >'+${arg1}+'</td>';
                                   table += '<td >'+${arg2}+'</td>';
                                   table +='<td >'+(${arg1}-${arg2}).toFixed(2)+'</td>';
                                    table += '<td >'+((${arg1}-${arg2})*100/${arg2}).toFixed(2)+'%</td></tr>';
                                    for( var i = 0; i < mydata.length; i++ ) {
                                table +='<tr><td>'+mydata[i].name+'</td>';
                                table +='<td>'+mydata[i].value+'</td>';
                                table +='<td>'+mydata1[i].value+'</td>';
                                table +='<td>'+(mydata[i].value-mydata1[i].value).toFixed(2)+'</td>';
                                if(mydata1[i].value != 0){
                                    table +='<td>'+((mydata[i].value-mydata1[i].value)*100/mydata1[i].value).toFixed(2)+'%</td>';
                                }else{
                                    table +='<td>100%</td>';
                                    }
                            }
                            table +='<tr><td>内贸全部港口</td><td>'+${arg3}+'</td><td>'+${arg4}+'</td>';
                                   table +='<td>'+(${arg3}-${arg4})+'</td><td>'+((${arg3}-${arg4})*100/${arg4}).toFixed(2)+'%</td></tr>';
                                    for( var i = 0; i < mydata2.length; i++ ) {
                                table +='<tr><td>'+mydata2[i].name+'</td>';
                                table +='<td>'+mydata2[i].value+'</td>';
                                table +='<td>'+mydata3[i].value+'</td>';
                                table +='<td>'+(mydata2[i].value-mydata3[i].value).toFixed(2)+'</td>';
                                if(mydata3[i].value != 0){
                                    table +='<td>'+((mydata2[i].value-mydata3[i].value)*100/mydata3[i].value).toFixed(2)+'%</td>';
                                }else{
                                    table +='<td>100%</td>';
                                    }
                            }
                                   table += '</tbody></table>';
                                   return table;
                }
                        },
                    saveAsImage : {show: true}
                }
            },
            series : [
                {
                    name:${seriesName},//'访问来源',
                    type:'pie',
                    radius : '60%',
                    center: ['50%', '60%'],
                    data:mydata//[
                        //{value:335, name:'直接访问'},
                        //{value:310, name:'邮件营销'},
                        //{value:234, name:'联盟广告'},
                        //{value:135, name:'视频广告'},
                        //{value:1548, name:'搜索引擎'}
                    //]
                }
            ]
        };

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/22310038/18655286/1ab0fe64-7f1a-11e6-833b-86d7b8528690.png)

**Comment by LancCJ** [comment]
大哥 你解决了么？

**Comment by phping1** [comment]
楼主，问题二找到解决办法了吗？

**Comment by Tairr** [comment]
@LancCJ  @phping1   均未解决

**Comment by Kirazxyun** [comment]
这封功能以后会提供吗，将数据导出为excel？@pissang

**Comment by fanslin** [comment]
如何导出Excel，解决了么 @Tairr

**Comment by crendy** [comment]
通过自定义tool来解决导出excel。
关键步骤：读取chart里面的x/y轴数据--拼装成html格式--定义按钮打开链接
举例：

myTool1: {
--
  | show: true,
  | title: '导出Excel',
  | icon: 'path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444z M421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876z M421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062,591.891,421.146,591.891L421.146,591.891zM421.146,591.891',
  | onclick: function (mychart){
  | var option = mychart.getOption();
  | var title = option.title[0].text;
  | var tmp = title.split("-");
  | var dateTemp = tmp[1]+"-"+tmp[2]+"-"+tmp[3]+" ";
  | var series = option.series;
  | var axisData = option.xAxis[0].data;
  |  
  | var excel = '<table>';
  | //设置表头
  | var row = "<tr>"+ '<td>时间</td>'
  | + '<td>' + series[0].name + '</td>'
  | + '<td>' + series[1].name + '</td>'
  | + '</tr>';
  | excel+=row;
  | for (var i = 0, l = axisData.length; i < l; i++) {
  | excel += '<tr>'
  | + '<td>' + dateTemp+axisData[i] + '</td>'
  | + '<td>' + series[0].data[i] + '</td>'
  | + '<td>' + series[1].data[i] + '</td>'
  | + '</tr>';
  | }
  | excel += '</table>';
  | var excelFile = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:x='urn:schemas-microsoft-com:office:excel' xmlns='http://www.w3.org/TR/REC-html40'>";
  | excelFile += '<meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">';
  | excelFile += '<meta http-equiv="content-type" content="application/vnd.ms-excel';
  | excelFile += '; charset=UTF-8">';
  | excelFile += "<head>";
  | excelFile += "";
  | excelFile += "</head>";
  | excelFile += "<body>";
  | excelFile += excel;
  | excelFile += "</body>";
  | excelFile += "</html>";
  |  
  | var uri = 'data:application/vnd.ms-excel;charset=utf-8,' + encodeURIComponent(excelFile);
  |  
  | var link = document.createElement("a");
  | link.href = uri;
  |  
  | link.style = "visibility:hidden";
  | link.download =  title+"data.xls";
  |  
  | document.body.appendChild(link);
  | link.click();
  | document.body.removeChild(link);
  |  
  | }
  |  
  | },

**Comment by crendy** [comment]
通过自定义tool来解决导出excel。
关键步骤：读取chart里面的x/y轴数据--拼装成html格式--定义按钮打开链接
举例：
`

myTool1: {
--
  | show: true,
  | title: '导出Excel',
  | icon: 'path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444z M421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876z M421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062,591.891,421.146,591.891L421.146,591.891zM421.146,591.891',
  | onclick: function (mychart){
  | var option = mychart.getOption();
  | var title = option.title[0].text;
  | var tmp = title.split("-");
  | var dateTemp = tmp[1]+"-"+tmp[2]+"-"+tmp[3]+" ";
  | var series = option.series;
  | var axisData = option.xAxis[0].data;
  |  
  | var excel = '<table>';
  | //设置表头
  | var row = "<tr>"+ '<td>时间</td>'
  | + '<td>' + series[0].name + '</td>'
  | + '<td>' + series[1].name + '</td>'
  | + '</tr>';
  | excel+=row;
  | for (var i = 0, l = axisData.length; i < l; i++) {
  | excel += '<tr>'
  | + '<td>' + dateTemp+axisData[i] + '</td>'
  | + '<td>' + series[0].data[i] + '</td>'
  | + '<td>' + series[1].data[i] + '</td>'
  | + '</tr>';
  | }
  | excel += '</table>';
  | var excelFile = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:x='urn:schemas-microsoft-com:office:excel' xmlns='http://www.w3.org/TR/REC-html40'>";
  | excelFile += '<meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">';
  | excelFile += '<meta http-equiv="content-type" content="application/vnd.ms-excel';
  | excelFile += '; charset=UTF-8">';
  | excelFile += "<head>";
  | excelFile += "";
  | excelFile += "</head>";
  | excelFile += "<body>";
  | excelFile += excel;
  | excelFile += "</body>";
  | excelFile += "</html>";
  |  
  | var uri = 'data:application/vnd.ms-excel;charset=utf-8,' + encodeURIComponent(excelFile);
  |  
  | var link = document.createElement("a");
  | link.href = uri;
  |  
  | link.style = "visibility:hidden";
  | link.download =  title+"data.xls";
  |  
  | document.body.appendChild(link);
  | link.click();
  | document.body.removeChild(link);
  |  
  | }
  |  
  | },

`
