### ISSUE TITLE
echarts怎么加入一些额外的信息，比如加一段话或者表格

### ISSUE THREAD

**Issue by shengxinjing** [apache/incubator-echarts#4134]
#### 问题简述 (One-line summary)

echarts怎么加入一些额外的信息，比如加一段话或者表格
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
如果要在 echarts 里面加一段话，可以使用 <http://echarts.baidu.com/option.html#title>。

**Comment by hkj2011yz** [comment]
@ 100pah 怎么添加表格呢
