### ISSUE TITLE
width:100%;在ionic上解析不出来

### ISSUE THREAD

**Issue by 13hua** [apache/incubator-echarts#4135]
#### 问题简述 (One-line summary)

width:100%;在ionic上解析不出来
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

width:100%;在ionic上解析不出来，希望可以自适应移动端
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
出不来是因为没办法获取 clientWidth 和 clientHeight
