### ISSUE TITLE
热力图直角坐标系的离散映射形式可以加载到地图上吗

### ISSUE THREAD

**Issue by guananny2** [apache/incubator-echarts#4137]
#### 问题简述 (One-line summary)

热力图直角坐标系的离散映射形式可以加载到地图上吗？
我们需要在地图上生成类似色斑图效果的功能，热力图的 直角坐标系-颜色离散映射可以应用在地图上吗，我的单个的点如何计算出其它点，有没有这个算法？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
不好意思暂时还不支持『色斑图在地里坐标系上』。

**Comment by mirari** [comment]
类似的需求在百度地图开源库mapv上有实现
http://mapv.baidu.com/gallery.html
