### ISSUE TITLE
webpack 引入的时候报错

### ISSUE THREAD

**Issue by holidaying** [apache/incubator-echarts#4149]
barGrid.js?d23e:158 Uncaught TypeError: Cannot read property '__ec_stack_0' of undefined

**Comment by 100pah** [comment]
请提供 option

**Comment by holidaying** [comment]
// 指定图表的配置项和数据
        var option = {
            color: ['#3398DB'],
            tooltip: {
                trigger: 'axis',
                axisPointer: { // 坐标轴指示器，坐标轴触发有效
                    type: 'shadow' // 默认为直线，可选为：'line' | 'shadow'
                }
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            xAxis: [{
                type: 'category',
                data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                axisTick: {
                    alignWithLabel: true
                }
            }],
            yAxis: [{
                type: 'value',
                // data: [10, 52, 200, 334, 390, 330, 220]
            }],
            series: [{
                name: '直接访问',
                type: 'bar',
                barWidth: '60%',
                data: [10, 52, 200, 334, 390, 330, 220]
            }]
        };
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

**Comment by holidaying** [comment]
目前只有柱状图会报错

**Comment by 100pah** [comment]
用你给的option，我这边并没有报错

**Comment by holidaying** [comment]
加个好友，我给你直播，麻烦了

**Comment by nannanwu** [comment]
不知道哪里冲突了，我这也是，单引入版本3就可以，在项目里把版本2换成版本3就出现在这个问题。。请问，你解决了吗

**Comment by holidaying** [comment]
没有，用的是echart2

**Comment by nannanwu** [comment]
那个问题，后来找到原因了，是页面其他地方写的js方法影响的。类似这种，prototype的定义，会影响到

**Comment by holidaying** [comment]
你能贴你修改js文件名字和代码吗？

**Comment by nannanwu** [comment]
![image](https://cloud.githubusercontent.com/assets/13672976/22914249/76aa0946-f2aa-11e6-97a1-c6a7313a14a2.png)
就是扩展了indexOf这个方法影响的，你想办法把这个方法放到那个页面引不到的地方。。

**Comment by holidaying** [comment]
不是吧，你试着用vue+webpack+vue router+vue resource搭一个框架，试试？

**Comment by nannanwu** [comment]
并没有用vue，用的angular

**Comment by holidaying** [comment]
抛异常的代码用严格模式写的，也没看清楚哪有问题
