### ISSUE TITLE
Echarts引入世界地图的国家不全

### ISSUE THREAD

**Issue by kanestrife** [apache/incubator-echarts#4159]
#### 问题简述 (One-line summary)

稍微比对了下，暂时发现以下国家在世界地图无法显示（可能不限于此）：
新加坡
列支敦士登
马耳他
安圭拉
安提瓜和巴布达
巴林
多米尼克
法属波利尼西亚
格鲁吉亚
瓜德罗普
关岛
科特迪瓦
留尼汪
马尔代夫
马提尼克
马约特
毛里求斯
休达

另外希望把中国台湾（香港澳门）地区也加进去
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):win7
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by zxzybin** [comment]
怎么办？这个问题最后怎么处理的呢
