### ISSUE TITLE
请问echarts是否支持置信区间的显示？

### ISSUE THREAD

**Issue by NickyPan** [apache/incubator-echarts#4165]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version): chrome
- 操作系统类型和版本 (OS Version): OSX 10.11.16
#### 重现步骤 (Steps to reproduce)

1.请问echarts是否支持置信区间，比如显示error bar之类的？
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#series-line.markArea>
