### ISSUE TITLE
提示层div在父元素设置了position:relative;overflow:hidden时会被隐藏

### ISSUE THREAD

**Issue by mfkwgi** [apache/incubator-echarts#4168]
#### 问题简述 (One-line summary)

最外层容器设置了overflow:hidden，此时鼠标移入echarts图形中，如果提示信息层超出了父容器，那么超出的部分会被隐藏，尽管echarts将其z-index设置成为9999999
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.3.2
- 浏览器类型和版本 (Browser version):Chrome 52.0.2743.82 m
- 操作系统类型和版本 (OS Version):Windows 10
#### 重现步骤 (Steps to reproduce)

1.创建一个有一定高度的头部div，比如60px
2.再创建一个内容容器div，设置其position:relative;overflow:hidden
3.在内容容器div中创建一个div，设置其position:absolute;z-index:9999999;height:40px;width:100px;top:-30px;
#### 期望结果 (Expected behaviour)

内容容器中的div能正常显示
#### 可能哪里有问题 (What went wrong)

echarts中提示信息层div是放在创建图形的父div下的，所以只要其所在父元素(不一定是创建echarts用的父div)设置了position:relative;overflow:hidden，那么超出的部分就无法显示。
如果将提示信息层直接放到body中，就可以避免这种问题
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by elelvenliu** [comment]
我也遇到这个问题了，我在表格所在的div层级，新建了一个div，里面放了一下输入框和下拉列表，展开的下拉列表被表格遮住了，但是只有IE8有问题，chrome是好的

**Comment by truechuan** [comment]
通用遇到了这个问题呢
