### ISSUE TITLE
1.为什么series.data没有name属性，某一个legend 控制某一个数据，目前只能控制某一个数据样式，2.如何伪实现这个legend 控制数据效果

### ISSUE THREAD

**Issue by mysad** [apache/incubator-echarts#4172]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

1.为什么series.data没有name属性，某一个legend 控制某一个数据，目前只能控制某一个数据样式，
2.如何伪实现这个legend 控制数据效果
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
没看懂您的描述
