### ISSUE TITLE
刚学echarts,想请问下各位大神下载完echarts.min.js完整版文件后怎么引用呢？为什么打开文件时，一直显示缺少“）”的错误呢？还有编辑代码时是直接在实例图中将原数据修改麽？可是这样操作很不方便，总觉得哪里错了

### ISSUE THREAD

**Issue by mokin1** [apache/incubator-echarts#4181]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by Zhangcanpu** [comment]
是不是 你浏览器的问题 禁用了什么东西
