### ISSUE TITLE
lines中如何设置label始终水平显示

### ISSUE THREAD

**Issue by zhangking** [apache/incubator-echarts#4190]
#### 问题简述 (One-line summary)

lines现在的label是沿切线方向现实，如何始终水平显示
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
什么场景下需要始终水平显示？

**Comment by zhangking** [comment]
文字比较多，做了换行，如果是斜的 看起来很累

**Comment by SCWR** [comment]
我想请教下那个怎么在lines上展示label 展示数据  一直显示NaN
