### ISSUE TITLE
echarts  逻辑上可以和google地图整合嘛,百度地图有bug

### ISSUE THREAD

**Issue by wflmax** [apache/incubator-echarts#4191]
#### 问题简述 (One-line summary)

由于百度地图本身自己的bug 弃用,但是ec的效果不错 想整合到 google地图里面,不知道支不支持
是不是只要复写一个类似bmap的方法就行,主要是 飞行航线跨美洲问题

**Comment by 100pah** [comment]
是的，可以自己写类似 bmap 的扩展。
