### ISSUE TITLE
echart 字体小于12px 的实现

### ISSUE THREAD

**Issue by chenxiangguicxg** [apache/incubator-echarts#4193]
#### 问题简述 (One-line summary)

echart 怎么实现让字体小于12px？？？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
浏览器限制最小字体为 12px

**Comment by chenxiangguicxg** [comment]
那怎样才能让它实现小于12px，因为我的这个图表在整个页面的占比也比较小，所以12px的字体在图表里显得占比太大，影响视觉，希望在整体布局上能好看一些。有什么办法可以让他的字体变小吗在echart里？？？
