### ISSUE TITLE
希望lines在配置series.data时支持传递value值，实现线条的视觉映射

### ISSUE THREAD

**Issue by mirari** [apache/incubator-echarts#4195]
我想结合百度地图绘制线热力图，原本的打算是用lines画线，然后用vituralMap做视觉映射。
但是lines的coords竟然只能传路径，不能附加value，也就是说lines只能画线，无法再对线条做进一步的定制操作了。而heatmap和scatter能设置value，却只能传递点的坐标。
官网的所有地图画线的例子都只是对线条加了随机色或者透明度叠加，没有与vituralMap搭配使用的例子，希望能在后续版本中加入这个功能。

**Comment by mirari** [comment]
试了下发现vituralMap可以从lines的data.value中取值然后映射线条颜色，只是文档里没写……

**Comment by warlock-lv** [comment]
文档有写，请看 http://echarts.baidu.com/option.html#series-map.data
鼠标点一下左边的 > data: [{...}],
原文如下：
如果需要在数据中加入其它维度给 visualMap 组件用来映射到颜色等其它图形属性。每个数据项也可以是数组，如：

[[12, 14], [34, 50], [56, 30], [10, 15], [23, 10]]

这时候可以将每项数组中的第二个值指定给 visualMap 组件。

更多时候我们需要指定每个数据项的名称，这时候需要每个项为一个对象：

[{
    // 数据项的名称
    name: '数据1',
    // 数据项值8
    value: 10
}, {
    name: '数据2',
    value: 20
}]

**Comment by warlock-lv** [comment]
HI  ，你好  我最近也在搞这个 echarts 的图形相关的工作， 能留下联系方式吗？
 一起讨论、分享一下经验怎么样？
或者  另我 QQ 457880341，   加好友时  请注明   github echarts.
多谢。

**Comment by ppker** [comment]
666 我是做数据可视化的  也玩的是echarts 我QQ 3089440172   一起交流啊

**Comment by ppker** [comment]
666 我是做数据可视化的  也玩的是echarts 我QQ 3089440172   一起交流啊

**Comment by ppker** [comment]
666 我是做数据可视化的  也玩的是echarts 我QQ 3089440172   一起交流啊

**Comment by ppker** [comment]
666 我是做数据可视化的  也玩的是echarts 我QQ 3089440172   一起交流啊

**Comment by ppker** [comment]
666 我是做数据可视化的  也玩的是echarts 我QQ 3089440172   一起交流啊

**Comment by ppker** [comment]
666 我是做数据可视化的  也玩的是echarts 我QQ 3089440172   一起交流啊

**Comment by PandaTsui** [comment]
不错，感谢楼主
