### ISSUE TITLE
% 百分号数据无法识别

### ISSUE THREAD

**Issue by cqcn1991** [apache/incubator-echarts#4197]
#### 问题简述 (One-line summary)

带%号数据无法识别
![qq](https://cloud.githubusercontent.com/assets/2425141/19219156/7cf5e746-8e3e-11e6-84ce-a0a9643c0019.png)
#### 版本及环境 (Version & Environment)

百度图说 （http://tushuo.baidu.com）
#### 重现步骤 (Steps to reproduce)
1. 选择插入折线图
2. 复制入%数据。会识别不出
#### 期望结果 (Expected behaviour)

像Excel一样，如下
![qq 2](https://cloud.githubusercontent.com/assets/2425141/19219167/c0c9492c-8e3e-11e6-8e8a-17498bbc2f5c.png)

**Comment by 100pah** [comment]
可以这样设置：

<img width="1261" alt="2016-10-16 4 42 43" src="https://cloud.githubusercontent.com/assets/1956569/19416285/9ff2e290-93bf-11e6-8d69-187d07285c14.png">
<img width="670" alt="2016-10-16 4 42 13" src="https://cloud.githubusercontent.com/assets/1956569/19416286/a4696448-93bf-11e6-9ed8-5b4c523f0068.png">
