### ISSUE TITLE
堆叠饼状图能像hcharts一样在顶部显示和的值吗？

### ISSUE THREAD

**Issue by dhy1994** [apache/incubator-echarts#4198]
#### 问题简述 (One-line summary)

不知道后续会开发这个功能还是只能自己通过tooltip来实现？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
不了解想要的是什么效果
