### ISSUE TITLE
禁止滚轮滚动 

### ISSUE THREAD

**Issue by xinde** [apache/incubator-echarts#4199]
echarts3是不是不可以设置禁止滚轮滚动了，2中有的，找遍了api也没有

**Comment by 100pah** [comment]
什么图？roam 缩放时可以禁止的。

**Comment by StevenYuysy** [comment]
http://echarts.baidu.com/option.html#dataZoom-inside

`dataZoom[i]-inside.disabled` 设置成 `true` 就可以了
