### ISSUE TITLE
动画效果没有随clear进行完全清除

### ISSUE THREAD

**Issue by wxqqq** [apache/incubator-echarts#4206]
#### 问题简述 (One-line summary)

 与百度地图结合的例子　北京地铁　线特效，执行claer()方法后，元素不能完全清楚，动画效果停止但还会存留在页面上。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
  3
- 浏览器类型和版本 (Browser version):
  chrome 53
- 操作系统类型和版本 (OS Version):
  window
#### 重现步骤 (Steps to reproduce)
1. 打开例子http://echarts.baidu.com/demo.html#lines-bmap-effect
2. 在代码编辑界面输入
   setTimeout(function() {
   myChart.clear()
   console.log(myChart.getOption())

}, 3000);
#### 期望结果 (Expected behaviour)

页面完全清除
#### 可能哪里有问题 (What went wrong)

动画没有进行回收
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by liujiusheng** [comment]
这个问题解决没有啊？我也遇到了
