### ISSUE TITLE
堆叠条形图值为0时图形上数字叠加的问题

### ISSUE THREAD

**Issue by chenxiwei7** [apache/incubator-echarts#4207]
#### 问题简述 (One-line summary)

堆叠条形图值为0时图形上数字叠加看不清楚
示例：
http://echarts.baidu.com/gallery/editor.html?c=bar-y-category-stack
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):win10
#### 重现步骤 (Steps to reproduce)

1.http://echarts.baidu.com/gallery/editor.html?c=bar-y-category-stack
2.更改data值为0，数字和0叠加
#### 期望结果 (Expected behaviour)

值为0时，不显示0，或者不叠加
#### ECharts配置项 (ECharts option)

``` javascript
option = {
{
            name: '视频广告',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideRight'
                }
            },
            data:[153, 212, 201, 154, 192, 333, 417]
        },
        {
            name: '搜索引擎',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideRight'
                }
            },
            data: [500, 0, 0, 0, 0, 0, 0]
        }
}

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/22286044/19231971/ad06c15e-8f0f-11e6-99b5-1d15bc0d1304.png)

**Comment by 100pah** [comment]
暂时可以这样设置来改善一下：

<http://gallery.echartsjs.com/editor.html?c=xrJmRZTgkg&v=1>

**Comment by Fairyshi** [comment]
remove the key 'stack'

**Comment by pnjgyl** [comment]
十分感谢 @100pah 的解决办法, 解决了我的大难题

**Comment by yyccQQu** [comment]
> 暂时可以这样设置来改善一下：
> 
> http://gallery.echartsjs.com/editor.html?c=xrJmRZTgkg&v=1

![image](https://user-images.githubusercontent.com/32674176/56706787-77622780-6740-11e9-8515-b362643274ad.png)
还是有这种问题v
