### ISSUE TITLE
can I set multiple tooltip for different chart ( eg .line , bar)

### ISSUE THREAD

**Issue by jincui** [apache/incubator-echarts#4217]
i mean in the same echart instance

#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
It is able to give different settings for tooltip in different chart, 

```js
option = {
    tooltip: { ... } // setting in echartInstance level
    series: [
        {type: 'line', tooltip: { ... }},  // chart 1
        {type: 'pie', tooltip: { ... }},   // chart 2
        ...
    ]
}
```

But only one tooltip content can be shown at the same time.

**Comment by finalion** [comment]
@100pah The same quesiton, but your answer doesn't work.
