### ISSUE TITLE
echarts 地图上图标被鼠标悬浮效果遮挡问题

### ISSUE THREAD

**Issue by Andy178** [apache/incubator-echarts#4219]
#### 问题简述 (One-line summary)

1、echarts地图上图标遮挡区域名字问题
2、echarts地图上图标被鼠标悬浮效果遮挡
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):2.2.7
- 浏览器类型和版本 (Browser version):IE11
- 操作系统类型和版本 (OS Version):Win7
#### 重现步骤 (Steps to reproduce)

1.地图标注可能遮挡区域名称，如下：
![image](https://cloud.githubusercontent.com/assets/13285500/19261865/7863cd90-8fc6-11e6-9361-351935f3d5d8.png)
有没有属性或方法可以让图标和文字不遮挡？最好不要手动调图标或区域文字位置，因为地图可点击进入省、市地图每个区域上都会标注有点位，要手动一个个调整的话很麻烦。
2.地图上图标被鼠标悬浮效果遮挡问题，如下图所示，当鼠标悬浮上面时标注点就被遮挡了

![default](https://cloud.githubusercontent.com/assets/13285500/19262377/44555da4-8fc9-11e6-82b4-3fd0412c3e93.png)
#### 期望结果 (Expected behaviour)

（1）图标与区域名字不相互遮挡
（2）鼠标悬浮效果不要遮挡图标

**Comment by panda403** [comment]
在series设置large: true,

**Comment by 100pah** [comment]
（1）是使用的 markPoint 么？
（2）设置 `label.emphasis.show: true` 即可。
