### ISSUE TITLE
地图上的城市名称都偏离所在区域如何解决?

### ISSUE THREAD

**Issue by Realybig** [apache/incubator-echarts#4220]
RT  谢谢
![qq 20161011155721](https://cloud.githubusercontent.com/assets/10878451/19262787/879126aa-8fcb-11e6-9fb1-181a212e0fad.png)

**Comment by 100pah** [comment]
请提供完整能运行的 option

**Comment by gongchao** [comment]
@100pah 不用提供例子啊，官网的文字就是偏移的，看看甘肃的，字和字都重叠了。。。

**Comment by shibandae** [comment]
是啊 同问，甘肃、广东等都重叠了，看起来很糙！但不知道该怎么改！

**Comment by qinghechaoge** [comment]
贵阳也是

**Comment by hl-stone** [comment]
只能手动去修改经纬度？
