### ISSUE TITLE
graph中的图片和位置设置

### ISSUE THREAD

**Issue by baikatian** [apache/incubator-echarts#4222]
#### 问题简述 (One-line summary)

1、关系图中的graph样式，如果我想用图片的话，有没有办法设置为圆形的？
2、在graph中需要设置每个节点的位置，如果节点较多，或者多级关系，位置都要自己计算得出了
请问有什么办法处理吗？谢谢～
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 2.0
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):mac
#### 重现步骤 (Steps to reproduce)

1.直接构建graph的js
2.使用demo
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

demo：http://echarts.baidu.com/demo.html#graph-simple

**Comment by 100pah** [comment]
（1）图片的内容可以是圆形的。
（2）如果不想计算，可使用默认提供的这两个布局：<http://echarts.baidu.com/option.html#series-graph.layout>
