### ISSUE TITLE
在绘制关系图时，旧版本 ECharts中的ignore和flag属性在新版本中被舍弃了么？

### ISSUE THREAD

**Issue by ibcLee** [apache/incubator-echarts#4224]
![image](https://cloud.githubusercontent.com/assets/8722890/19268873/9e977124-8fe9-11e6-8ade-a9a0ec24d61e.png)
在新版本的ECharts的关系图绘制中打印出来的节点是有ignore和flag属性的，但是却不起作用，文档中也没有相关说明，是已经被舍弃了么？如果想在关系图中控制子节点的展开与收起该如何实现呢？

**Comment by 100pah** [comment]
现在没有 ignore。可以尝试下监听 click 事件，在事件中 setOption 改变数据，达到展开收起的效果。
