### ISSUE TITLE
Control area color in line area chart?

### ISSUE THREAD

**Issue by mrcybermac** [apache/incubator-echarts#4227]
#### 问题简述 (One-line summary)

Is there a way to control the area color under a line chart or stacked line chart, horizontally?
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)
1.   The option below creates a chart that looks like this:

![screen shot 2016-10-11 at 2 09 10 pm](https://cloud.githubusercontent.com/assets/6118944/19291904/69b06e70-8fd5-11e6-936e-c306274ce72c.png)
1.  How can I control the colors of the area along the xAxis (horizontal)?  For example, I want blue on the left side, and then red on the right side above a certain x value.  I cannot find a way to do this at all.  I do see the dataRange feature, which would work for me, except it will only let me change the colors vertically along the yAxis like this for example:

![screen shot 2016-10-11 at 4 26 00 pm](https://cloud.githubusercontent.com/assets/6118944/19291959/c510e862-8fd5-11e6-9402-9e8a80b0a83b.png)

I need a way of changing the colors in the other direction, from left to right along the xAxis, not the yAxis.

Thanks for any ideas!
#### ECharts配置项 (ECharts option)

``` javascript
let options = {
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['Orders','Ghost Orders']
    },
    xAxis : [
        {
            type : 'value',
            scale: true
        }
    ],
    yAxis : [
        {
            type : 'value',
            scale: true
        }
    ],
    series : [
        {
            name:'Orders',
            type:'line',
            stack: 'group1',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data: [
                [
                    0.0189,
                    45
                ],
                [
                    0.019,
                    96
                ],
                [
                    0.0191,
                    85
                ],
                [
                    0.0192,
                    50
                ],
                [
                    0.0193,
                    2
                ],
                [
                    0.0194,
                    14
                ],
                [
                    0.0195,
                    79
                ]
            ]
        },
        {
            name:'Ghost Orders',
            type:'line',
            stack: 'group2',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:[
                [
                    0.0189,
                    26
                ],
                [
                    0.019,
                    33
                ],
                [
                    0.0191,
                    58
                ],
                [
                    0.019200000000000002,
                    45
                ],
                [
                    0.0193,
                    94
                ],
                [
                    0.0194,
                    30
                ],
                [
                    0.0195,
                    52
                ]
            ]
        }
    ]
};

```

**Comment by warlock-lv** [comment]
you can use visualMap  , look at the echarts document for detail .

**Comment by warlock-lv** [comment]
you can use visualMap  , look at the echarts document for detail .
http://echarts.baidu.com/option.html#visualMap

**Comment by pissang** [comment]
Yes you can use visualMap( in the older version it is called dataRange). **To change the direction you can set dimension to 0, which means it will encode the color of x value **
