### ISSUE TITLE
关系图link value 错位

### ISSUE THREAD

**Issue by ruoqianfengshao** [apache/incubator-echarts#4233]
#### 问题简述 (One-line summary)

使用关系图时，在多层级的情况下，position为middle时，某一个link的值会显示错位，导致value被节点盖住
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.3
- 浏览器类型和版本 (Browser version): chrome latest
- 操作系统类型和版本 (OS Version): maxos sierra
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

所有link的value都能正确现在是中间
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/2928664/19299440/e389d720-9086-11e6-8350-fa67d725f4ed.png)

**Comment by 100pah** [comment]
请提供 option
