### ISSUE TITLE
Is there any plans for Gantt Chart?

### ISSUE THREAD

**Issue by krisred** [apache/incubator-echarts#4245]
#### 问题简述 (One-line summary)

This is not a issue, did not know where to post or ask about this- I was wondering if there are any plans to add Gantt chart?
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by chfw** [comment]
Here is a good javascript gantt chart: https://github.com/frappe/gantt . It'll be great if someone implement it using echarts.

**Comment by dburucu** [comment]
yes, please implement a gantt chart
