### ISSUE TITLE
多图联动时间范围不一致echart崩溃

### ISSUE THREAD

**Issue by waitinghope** [apache/incubator-echarts#4246]
#### 问题简述 (One-line summary)

两个echarts实例联动，如果其中一个图的时间范围是16年一月，另外一个图是16年二月，那么当鼠标tooltip事件触发后，控制台抛出
echarts.js:22543 Uncaught TypeError: Cannot read property '0' of undefined

同时这个echart实例无法再使用。

![image](https://cloud.githubusercontent.com/assets/3109596/19341350/a7468d06-915f-11e6-8f39-393d0db3429b.png)
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
具体配置项？

**Comment by warlock-lv** [comment]
时间不一致，可以补成一致的。例如两图联动，1图有123时间及数据，2图有456时间及数据，
补数据后1图123456时间及数据，2图123456时间及数据。
QQ457880341 可以一起讨论一下。

**Comment by warlock-lv** [comment]
时间不一致，可以补成一致的。例如两图联动，1图有123时间及数据，2图有456时间及数据，
补数据后1图123456时间及数据，2图123456时间及数据。
QQ457880341 可以一起讨论一下。
