### ISSUE TITLE
在angular2中使用echarts init参数类型错误

### ISSUE THREAD

**Issue by biolee** [apache/incubator-echarts#4254]
#### 问题简述 (One-line summary)

在angular2中使用echarts d.ts是DefinitelyTyped的
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):"3.2.3"
- 浏览器类型和版本 (Browser version):chrome 53.0.2785.143 (64-bit)
- 操作系统类型和版本 (OS Version):mac 10.12
#### 重现步骤 (Steps to reproduce)

1.安装
`npm install typings --global
typings install echarts=github:DefinitelyTyped/DefinitelyTyped/echarts/echarts.d.ts#3305eb6f74a2de17d208dfaaa20d69cfb912f871 --save --global
npm install echarts --save`
2.引用
`var myChart = echarts.init(document.getElementById('test'));
    myChart.setOption({
      title: { text: 'ECharts 入门示例' },
      tooltip: {},
      xAxis: {
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
      },
      yAxis: {},
      series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
      }]
    });`

报错：
`Argument of type 'HTMLElement' is not assignable to parameter of type 'HTMLDivElement | HTMLCanvasElement'.
  Type 'HTMLElement' is not assignable to type 'HTMLCanvasElement'.
    Property 'height' is missing in type 'HTMLElement'.
[default] Checking finished with 1 errors`
#### 可能哪里有问题 (What went wrong)

echarts.init 期望HTMLDivElement，但是document.getElementById('test')返回的却是HTMLElement
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by icssjs** [comment]
解决没，哥们？

**Comment by fsp1yjl** [comment]
我是直接把d.ts中init的声明改了跑的。。。

**Comment by Maroon1** [comment]
你们应该对 `getElementById` 方法返回的对象做显式的转换，因为它返回的不一定都是 `init` 方法所要求的 `HTMLDivElement` 或 `HTMLCanvasElement` 对象，也有可能是其他继承了 `HTMLElement` 的对象。
所以你们的代码中应该做如下的转换：
```javascript
const el = document.getElementById('target') as HTMLDivElement;
````

**Comment by baronvv** [comment]
@Maroon1 is ok thx.

**Comment by KellaTe** [comment]
@maroon1 very cool!
