### ISSUE TITLE
Echart3.0较Echart2的动画变化？

### ISSUE THREAD

**Issue by ivanberry** [apache/incubator-echarts#4255]
#### 问题简述 (One-line summary)

Echart非常好用，使得一个没怎么接触数据处理前端在短时间就能画个饼图出来，很是感谢！
经过迁移至Echart3，效果非常好，但是因为要给问题，产品过不了，就是饼图渲染出来的动画没有Echart2的“顺滑”，或者说Echart3的动画怎么只能定义“顺、逆时针”，没有一个参数可以使用Echart2的动画方式吗？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): EChart 3.0
- 浏览器类型和版本 (Browser version): Chrome 54
#### 期望结果 (Expected behaviour)

是否有参数能使得饼图渲染动画和EChart2一般？

**Comment by 100pah** [comment]
没有。动画方式的『顺滑』『效果好坏』是个比较主观的事情。饼图本质是展示数据，不需要太纠结在初始动画上面。

**Comment by ivanberry** [comment]
@100pah   技术方面没有什么问题，因为想升级echart库，顺利升级后：产品和设计觉得3的动画没有2的动画“顺畅”，所以就回退到2的版本，谢谢回复。

**Comment by ivanberry** [comment]
@100pah 顺便请教一声，2中可以自己布局tooltip吗？谢谢
