### ISSUE TITLE
echarts3如何正确设置平行于y轴的markline

### ISSUE THREAD

**Issue by 54zzb** [apache/incubator-echarts#4262]
#### 问题简述 (One-line summary)

echarts3如何正确设置平行于y轴的markline
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):echarts3.2.3
- 浏览器类型和版本 (Browser version):谷歌浏览器49.0.2623.87 m
- 操作系统类型和版本 (OS Version):win10
#### 重现步骤 (Steps to reproduce)

我现在有个需求，使用echarts3做一条平行于y轴的趋势线，我想到markline，但是我的x轴是类目轴，如果是设置平行于x轴的趋势线我知道怎么做，就是如下做法：

1、加一个单独的序列，这个序列只有一个值，即我们要指定的值
2、然后给这个序列设置均值线，由于序列只有一个值，所以序列均值线的值也就是这个值

但是y轴我就不太清楚了，我能做出个效果，但是y轴的最大刻度我是不清楚的，有什么办法可以拿到y轴刻度的最大值（目前不考虑自己给y轴设置个最大值，想就用echarts自动帮我们设置好的最大值），echarts2以前是说可以用-1或者MAXNUMBER，但是echarts3我没找到这个说明，而且用了也不起作用。

我目前能做到的效果如下，但是顶端会报‘NAN’和y轴的最大值我是写死的，有人知道怎么设置么
#### 期望结果 (Expected behaviour)

能实现一条平行于y轴的趋势线
#### 可能哪里有问题 (What went wrong)

是否echarts不支持设计平行于y周的趋势线
#### ECharts配置项 (ECharts option)

``` js
option = {
    title: {
        text: '未来一周气温变化',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'axis'
    },
    xAxis:  {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value',
        axisLabel: {
            formatter: '{value} °C'
        }
    },
    series: [
        {
            name:'最高气温',
            type:'line',
            data:[6, 8, 11, 10, 12, 13, 10]
        },
        {
            name:'平行于y轴的趋势线',
            type:'line',
            //data:[0],
            markLine: {
                name:'aa',
                data: [[
                    {coord:['周四',0]},
                    {coord:['周四',15]}//如何获取grid上侧最大值，目前是写死的
                ]]
            }
        }
    ]
};
```
#### 其他信息 (Other comments)

http://static.oschina.net/uploads/space/2016/1016/120915_BKX6_941354.png

**Comment by pissang** [comment]
可以写 `'min'`, `'max'` 指明最小值最大值，显示是 value 或者 name 的值：
```js
data: [[
  { coord: [ '周四', 'min' ], name: '一条标线'},
  { coord: [ '周五', 'max' ]}
]]
```

**Comment by 54zzb** [comment]
@pissang 
能用上面的例子给我写个option么，我这边还是不是很理解显示是value或者name的值的做法

**Comment by 54zzb** [comment]
min和max在echarts3里不能被解析

**Comment by monhz** [comment]
遇到了一样的问题, 用 coord 的方法写死y轴的值会显示 NAN
