### ISSUE TITLE
怎么自定义按钮来控制地图的缩放，3.0版本

### ISSUE THREAD

**Issue by liuhaifeng2005** [apache/incubator-echarts#4264]
#### 问题简述 (One-line summary)

怎么自定义按钮来控制地图的缩放呢？比如我新建一个按钮b，点击按钮b实现地图的放大或者缩小功能？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by wuruihua** [comment]
动态改变chart.setOption(otion.geo.zoom)的值可以实现缩放

**Comment by yunyingchen** [comment]
可以给一个详情示例吗？

**Comment by yunyingchen** [comment]
可以给一个实现的示例代码吗？
