### ISSUE TITLE
桑基图可否修改每个节点的宽度？

### ISSUE THREAD

**Issue by huyongdi** [apache/incubator-echarts#4265]
问题简述 ：
桑吉图的宽度是根据分出去的节点数目控制的，value值相同的情况下，节点越多，宽度越宽。
就算改变value值，但是汇总的宽度也绝对会大于等于某一分支的。
现在我想做到的是，节点宽度可以随意定制，这样可以吗？

3.0版本配置如下
![image](https://cloud.githubusercontent.com/assets/16769181/19428183/1dcf2492-947b-11e6-9b88-584253ecb3d6.png)

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#series-sankey.nodeWidth>

**Comment by huyongdi** [comment]
不好意思，我没说清楚，是想知道A假如想设置为10 B设置为20 而不是统一的

**Comment by deqingli** [comment]
你好，你说的是节点的高度吧？是这样的，现在 sankey 图的节点高度是由节点入边之和以及出边之和的最大值决定的，再根据得出的节点高度，计算节点在屏幕中的纵向位置。如果不想 echarts 自动计算，可能就需要用户指定节点的 x, y 位置。

**Comment by yy7054wyq5** [comment]
@deqingli 能详细说明一下如何让用户指定节点的x,y位置吗？

**Comment by deqingli** [comment]
@yy7054wyq5  If the user specifies the x, y location of some node, then the user needs to specify the location of all the nodes. The ECharts framework only responsible for drawing, just like series.graph. Is this strategy acceptable?

**Comment by deqingli** [comment]
@huyongdi Can you tell me why do you want to change the width of each node?

**Comment by yy7054wyq5** [comment]
@deqingli i think it is  not friendly. Can i set min-height or max-height of node?

**Comment by deqingli** [comment]
@yy7054wyq5  I don't know what the problem you met, maybe just like #6365. So please provide more detail message about why you want to specify the height of the node, such as a demo or a picture.

**Comment by yy7054wyq5** [comment]
scene: use Sankey chart instead Graph chart. There's no way out of the boss's demand.

**Comment by maoAmanda** [comment]
> 不好意思，我没说清楚，是想知道A假如想设置为10 B设置为20 而不是统一的

你好，我也遇到相同的需求，请问你这里是怎么解决的？

**Comment by owenfang2553** [comment]
节点数据较小=>节点高度几乎没有=>看不清节点内容  ：希望可以统一设置所有节点的最小高度与最大高度 @deqingli

**Comment by awuming** [comment]
产品出图左右两边节点宽度不一致，有大佬们解决的吗？分开设置节点宽度

**Comment by foolmadao** [comment]
我也遇到了，我用border模拟了一个最小高度，建议echarts还是支持最小节点高度的配置

**Comment by coloryee** [comment]
> 能详细说明一下如何让用户指定节点的x，y位置吗？

您好，请问这个指定节点X，Y的位置您实现了吗？
