### ISSUE TITLE
世界地图中心移到中国后，右边美洲部分没有重复

### ISSUE THREAD

**Issue by dearbird** [apache/incubator-echarts#4269]
#### 问题简述 (One-line summary)

将地图中心设置在中国区域，美洲部分偏移到左边隐藏后，没有在右边出现。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0版本
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 可能哪里有问题 (What went wrong)

世界地图没有支持左右循环，看2.0版本的例子是支持的。
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by lyonru29** [comment]
想问一下在echarts 2.0，怎么把将地图中心设置在中国区域

**Comment by sunshinev** [comment]
同问

**Comment by wcyyo** [comment]
你好 请问问题解决了吗
