### ISSUE TITLE
移动端echarts，手指长按显示tooltip

### ISSUE THREAD

**Issue by meizi0828** [apache/incubator-echarts#4278]
#### 问题简述 (One-line summary)

移动端
1.默认情况下，手指左滑或右滑，异步请求并更新数据
2.手指长按，显示该点的tooltip,此时再左滑右滑显示相应的tooltip,直到手指松开
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by ctocto** [comment]
一样的需求，有解决方案吗？
