### ISSUE TITLE
有没有完整的俄罗斯的图的json或者js文件？（就像中国地图那样的全国地图）世界地图中的俄罗斯地图被分成两块了

### ISSUE THREAD

**Issue by yunqingChang** [apache/incubator-echarts#4290]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by xiaohan2013** [comment]
同样的问题，怎样这两块拼起来。世界地图的js文件有没有压缩混淆的吗？

**Comment by xiaohan2013** [comment]
@yunqingChang 这个问题可以在http://geojson.io/对地图的数据进行重新编辑，然后替换掉原来的数据可以实现。

**Comment by fuxiao82** [comment]
const regisOption: RegisOption = {
    type: 'FeatureCollection',
    crs,
    features: world.map((item) => {
          if (item.properties.name !== '俄罗斯') {
            return item
          }
          item.geometry.coordinates.forEach((detail) => {
            detail[0].forEach((itemDetail) => {
              //地图坐标需要转换，经过分析，经度小于-20度的加上360就可以了！
              if (itemDetail[0] < -20) {
                itemDetail[0] += 360
              }
            })
          })
          return item
        })
  }


world like:
[{
  "geometry": {
      "type": "Polygon",
      "coordinates":[...]
  },
  "properties": {
      "name": "俄罗斯",
      "childNum": 1
  }
},{},{},...]
