### ISSUE TITLE
贵州地图内部子区域轮廓异常

### ISSUE THREAD

**Issue by ryt381375878** [apache/incubator-echarts#4303]
#### 问题简述 (One-line summary)

贵州地图中毕节区域内（威宁和赫章）有一条轮廓。但根据贵州省行政规划，威宁和赫章之间不应该会有一条线隔开
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

希望能去掉威宁和赫章的分割线。希望官方能给个解决方案， 谢谢
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/22972246/19585838/5797be00-9782-11e6-816b-a6f5ce2d103a.png)

**Comment by ryt381375878** [comment]
有谁能知道这条线怎么能去掉？

**Comment by zzl93** [comment]
分割线异常，有什么办法解决呢
![image](https://user-images.githubusercontent.com/15900227/94544555-f6388980-027d-11eb-9271-c2614b99a7c6.png)
