### ISSUE TITLE
echarts可以直接升级到3吗

### ISSUE THREAD

**Issue by jialuoJiang** [apache/incubator-echarts#4307]
#### 问题简述 (One-line summary)

项目中一开始使用的是echarts2，可以直接将echarts.js替换成echarts3.js完成2到3的升级吗？

项目中直接替换ecahrts.js文件之后，在IE8中的tooltip不显示了，IE9是OK的

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/3322#issuecomment-222884451
