### ISSUE TITLE
echarts 地图如何实现实时更新数据时地图不晃动

### ISSUE THREAD

**Issue by Carol1992** [apache/incubator-echarts#4310]
#### 问题简述 (One-line summary)

echarts 地图如何实现实时更新数据时地图不晃动，就是说实时数据通过websocket传递给echarts地图的data参数，这个时候会重新调用函数myChart.setOption()，但是地图也会刷新，这样如果我每秒钟有一万条数据进来，整个地图一直在晃，根本看不清楚地图。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):谷歌浏览器
- 操作系统类型和版本 (OS Version):windows

**Comment by Carol1992** [comment]
因为每次数据更新时我就调用setOption() 函数，因为是重新渲染data中的数组，所以整张地图都在不停慌，最终决定使用setInterval()函数，时间设置为每5秒中刷新一下地图，这样视觉效果会好一点。但是究竟如何实现点的刷新而不是刷新整个放地图的div呢？

**Comment by sunshinev** [comment]
我也遇到一个问题，想实时加载数据，只能使用setOption，而且会出现很多动画效果问题和残影
