### ISSUE TITLE
{series:{type:'map'}}为什么没有coordinateSystem属性？

### ISSUE THREAD

**Issue by lixuesheng83829** [apache/incubator-echarts#4318]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
因为 map 系列只能是地理坐标系

**Comment by lixuesheng83829** [comment]
那如果要进行百度地图扩展，比如将map图标系列叠加在百度地图上进行同步放缩、移动该怎么处理？

**Comment by lixuesheng83829** [comment]
那如果要进行百度地图扩展，比如将map图表系列叠加在百度地图上进行同步放缩、移动该怎么处理？
像scatter系列都是将coordinateSystem赋值为bmap...

**Comment by pissang** [comment]
暂时不行...

**Comment by M69W** [comment]
可以设置 `coordinateSystem: 'geo',`
来源
https://blog.csdn.net/daxxxx123/article/details/106939345
