### ISSUE TITLE
borderRadius support in pie chart

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4325]
Version: 3.2.3

Would be great to have borderRadius support for pie chart (with similar syntax as barBorderRadius) so it is possible to achieve this: 

![image](https://cloud.githubusercontent.com/assets/561365/19682733/420cbd80-9aaf-11e6-8e85-ba6d29a0bfab.png)

Just an idea:)

**Comment by cfxmj2014** [comment]
+1

**Comment by fengmiaosen** [comment]
+1

**Comment by zmzimpl** [comment]
为什么关闭了这个问题呢，目前环形图还不支持borderRadius属性呢
