### ISSUE TITLE
怎么把中国移到世界地图中心，然后美洲部分在右边循环出现

### ISSUE THREAD

**Issue by lyonru29** [apache/incubator-echarts#4339]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by wu11106** [comment]
38为母，还是那个站起来对着公众地方小便的39？

2016年10月27日星期四，lyonru29 <notifications@github.com> 写道：

**Comment by Carol1992** [comment]
bmap: {
            center: [117.0600, 30.0000],
            zoom: 4,
            roam: true,
}

**Comment by sunshinev** [comment]
v3修改center并不会将美洲移动到右侧

**Comment by wcyyo** [comment]
请问解决了吗，遇到了同样的问题

**Comment by ludongsheng** [comment]
同问这个问题，不知道解决了没有？

**Comment by 100pah** [comment]
目前来说，这需要换一份 geoJSON。

**Comment by FengHuangDong** [comment]
这个需要怎么解决？？

**Comment by chfw** [comment]
https://echarts-maps.github.io/echarts-geomapping-book-zh/intermediate/change-world-center/

**Comment by FengHuangDong** [comment]
> https://echarts-maps.github.io/echarts-geomapping-book-zh/intermediate/change-world-center/
@chfw 
I need to add scatter on the map,this solution seems to change the latitude and longitude？maybe need a transformation？
![image](https://user-images.githubusercontent.com/16097344/62835949-a7521e00-bc90-11e9-8f74-c7f31d2cfd1f.png)

**Comment by chfw** [comment]
https://echarts-maps.github.io/echarts-countries-js/preview.html

**Comment by chfw** [comment]
![Screenshot 2019-08-11 at 16 50 50](https://user-images.githubusercontent.com/4280312/62836150-30992e80-bc58-11e9-9d98-f1cbf66ce222.png)

**Comment by FengHuangDong** [comment]
@chfw 我有一份全球的城市经纬度坐标点画在地图上，在eckert3-world图上全乱了，有什么方法把这个经纬度转换成eckert3-world图上吗？
