### ISSUE TITLE
echarts 桑基图 bug

### ISSUE THREAD

**Issue by oomaming** [apache/incubator-echarts#4354]
#### 问题简述 (One-line summary)

echarts 桑基图 当links为300条左右时，浏览器崩溃
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.0
- 浏览器类型和版本 (Browser version):chrome 49
- 操作系统类型和版本 (OS Version): windows xp /windows 7/mac os x
#### 重现步骤 (Steps to reproduce)
1. 浏览器运行页面
   2.崩溃
#### 期望结果 (Expected behaviour)

浏览器崩溃
#### 可能哪里有问题 (What went wrong)

内存
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by yyl447522442** [comment]
同样问题
