### ISSUE TITLE
折线图用setOption更新时会遗留之前的数据

### ISSUE THREAD

**Issue by huangqiz** [apache/incubator-echarts#4356]
#### 问题简述 (One-line summary)

对于折线图，有时使用setOption设置新的seriesData时会有，旧的一些曲线仍然会显示在图标上
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.3
- 浏览器类型和版本 (Browser version): Chrome 53.0.2785.143
- 操作系统类型和版本 (OS Version): Win10
#### 重现步骤 (Steps to reproduce)
1. 使用option1（附件option1.txt）绘制折线图（setOption(option1)）
2. 使用option2（附件option2.txt）绘制折线图（setOption(option2)）
#### 期望结果 (Expected behaviour)

会出现类似截图1中的情况
#### 可能哪里有问题 (What went wrong)

echarts是否会缓存一些cache？
#### ECharts配置项 (ECharts option)

请见附件option1.txt以及option2.txt

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

[option1.txt](https://github.com/ecomfe/echarts/files/559732/option1.txt)
[option2.txt](https://github.com/ecomfe/echarts/files/559733/option2.txt)
![1](https://cloud.githubusercontent.com/assets/7144380/19827101/26e67e68-9dd1-11e6-93f8-fe817e9fd3d8.png)

**Comment by pissang** [comment]
默认 setOption 是跟之前的数据合并的，可以 setOption 第二项设置为 true 选择不合并

**Comment by huangqiz** [comment]
第二个选项设为true的时候，是不是类似会执行clear()的操作？有没有办法在setOption之后仍然保持我用toolbox中设定的缩放比例？

**Comment by jinjiaxing** [comment]
设置true也无效怎么办？
