### ISSUE TITLE
饼图data里文字过长截断

### ISSUE THREAD

**Issue by ubuntugx** [apache/incubator-echarts#4381]
#### 问题简述 (One-line summary)
在使用饼图时，data 里的 name 属性文字过长时，能否判断到边界时截断并在后面加...？
如果在给 name 属性赋值时判断长度并加入...，在鼠标移到饼图上显示 toolTip 时文字也会和 data 里设置的一样（带...）,不符合需求。可否处理这种情况？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.1
+ 浏览器类型和版本 (Browser version): chrome 54.0.2840.71
+ 操作系统类型和版本 (OS Version): OSX 10.10.5

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
EChart 能够自动截断超出图大小的文字，并在后面加 ...
或者 toolTip 可以不只从 data 里面取值，可以从数据源中取值。 

#### ECharts配置项 (ECharts option)

```javascript
option = {
    tooltip: {
       trigger: "item",
       formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    series: [
       {
            name: "",
            type: "pie",
            selectedMode: "single",
            radius: "55%",
            avoidLabelOverlap: true,
            label: {
               normal: {
                   show: true,
                   textStyle: {
                      color: "black"
                    }
               },
               emphasis: {
                    show: true,
                    textStyle: {
                       fontWeight: "bold"
                     }
                }
            },
            labelLine: {
               normal: {
                   lineStyle: {
                     color: "rgb(185,185,185)"
                    },
                    length: 17,
                    length2: 5
               }
            },
            data: state.freq_relate_data
        }
    ],
    color: tools.chartColor
}
```

**Comment by 100pah** [comment]
暂时没有这个功能，这类问题我们会考虑一下。
但是，
> 如果在给 name 属性赋值时判断长度并加入...，在鼠标移到饼图上显示 toolTip 时文字也会和 data 里设置的一样（带...）,不符合需求。

其实 tooltip 中的内容是可以自定义的，
参见：<http://gallery.echartsjs.com/editor.html?c=xH1BpOS_xe&v=1>
