### ISSUE TITLE
饼图的Title显示的问题

### ISSUE THREAD

**Issue by Weiliusd** [apache/incubator-echarts#4389]
#### 问题简述 (One-line summary)

1. 当鼠标移动到某扇区后，发现对应的title描述没有显示出来；
2. 当饼图显示的种类比较多时，颜色有重复；
3. 当显示的种类比较多时，能否增加一个全部反选的功能，一下把所有的item都先去掉，从而有利于用户去对比某两个或者少数几个item数据，现在的情况是需要用户手动把所有的item一个一个的点击去掉，比较麻烦。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
1. 看 label 相关配置。
2. 颜色是默认调色盘循环使用，不够多可以自己添加其它颜色
3. 可以自定义按钮，调用 [dispatchAction](http://echarts.baidu.com/api.html#echartsInstance.dispatchAction) 方法对 legend 选择和取消选择

**Comment by Weiliusd** [comment]
关于第一点，配置没有问题，绝大多数情况下也是可以正常显示出来的，但是在某些情况下鼠标移动到某个扇区的时候会出不来，鼠标移出再移进来后又恢复正常了。

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 贴个例子？然后说明下怎么复现
