### ISSUE TITLE
使用地图联动以后，hover地图弹出的提示框显示在地图下面，而不是跟随鼠标移动

### ISSUE THREAD

**Issue by 3412734542** [apache/incubator-echarts#4394]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
请提供 option
