### ISSUE TITLE
求3.3版本如何在地图添加 markPoint

### ISSUE THREAD

**Issue by evolutionjay** [apache/incubator-echarts#4396]
#### 问题简述 (One-line summary)
其实不知道是不是BUG，
但文档实在太乱了，
2 跟 3 两个版本混来混去。
是这样的，我写了个世界地图
series的type如下
```javascript
type: 'scatter'
```
现在问题是，如何在这里添加 markPoint 最起码给个Demo 啊。 
v2。x 的不能用。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.3
+ 浏览器类型和版本 (Browser version): Chrome 54
+ 操作系统类型和版本 (OS Version): Mac OS 10.12

**Comment by banterise** [comment]
API有关于markpoint的叙述,2和3的确在形式上不太一样,3不再自带类似2的特效,但是依旧保留并新增的部分属性,基本使用逻辑是一样的,可以参考ec3官网案例的模拟迁徙

**Comment by evolutionjay** [comment]
强烈要求更新个Markpoint Demo

**Comment by pissang** [comment]
3 里地图上打点建议用散点图而不是 MarkPoint 了，见例子 http://echarts.baidu.com/gallery/editor.html?c=effectScatter-map 你是需要用 markPoint 做什么

**Comment by fengiming** [comment]
这几天正在做一个类似地图上打标记的项目，试了不少法子，最终摸索出来，我用的是 type: 'map ' ,
  要用到 markPoint 组件
    // 需要打点的坐标
    var geoCoordList = {
            '北京': [116.326027, 40.022889],
            '上海': [121.403681, 31.223344],
            '天津': [117.282686, 39.397664],
            '重庆': [107.329749, 29.869226],
            '黑龙江': [128.302667, 47.176301],
            '辽宁': [122.121175, 41.477915],
            '吉林': [125.230319, 43.920089],
            '河北': [115.277381, 38.478075],
            '山东': [118.000181, 36.662355],
            '河南': [113.069705, 34.13192],
            '安徽': [116.952163, 32.220321],
            '江苏': [119.619143, 33.147058],
            '浙江': [119.9135, 29.548002],
            '湖北': [111.818689, 31.648654],
            '江西': [115.645327, 28.317973],
            '福建': [117.926592, 26.346366],
            '广东': [113.143295, 23.934987],
            '湖南': [111.303565, 28.448142],
            '云南': [101.001079, 24.878454],
            '广西': [108.727943, 24.137757],
            '贵州': [106.612254, 26.693942],
            '四川': [102.178506, 31.143644],
            '西藏': [88.711684, 31.143644],
            '新疆': [85.620938, 41.754043],
            '宁夏': [106.005143, 37.429219],
            '内蒙古': [110.991439, 41.815133],
            '陕西': [108.13923, 34.0707],
            '山西': [112.554581, 38.071982],
            '海南': [109.684603, 19.256502],
            '台湾': [120.870159, 23.731894],
            '香港': [114.188832, 22.355929],
            '澳门': [113.559027, 22.153976],
            '青海': [95.261122, 36.662355],
            '甘肃': [104.018235, 35.527567]
        };
     // 打标记或者删除标记, 参数为要打标记的区域名称,flag为true表示添加， flag为false表示删除
        function toggleMarkPoint(option, name, flag) {
            var markPointData = option.series[0].markPoint.data;
            if (flag === true) {
                markPointData.push({
                    name: name,
                    coord: geoCoordList[name]
                });
            } else {
                for (var i = 0, mark; mark = markPointData[i]; i++) {
                    if (mark.name == name) {
                        break;
                    }
                }
                markPointData.splice(i, 1);
            }
        }
