### ISSUE TITLE
折线图折点文本重叠

### ISSUE THREAD

**Issue by liuyayaya** [apache/incubator-echarts#4409]
#### 问题简述 (One-line summary)
使用x轴为类目轴的折点图，在数据相同连成直线的时候，折点的文本重叠在一起了，有什么解决方法么？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.4

**Comment by wu11106** [comment]
您昨天早上，说六个人“吃”，其中一个很少，那五个人中，还有那三个，“航公”是不是厨师。
我面对很多工作，请告诉我！谢谢！

2016年11月5日星期六，liuya <notifications@github.com> 写道：

**Comment by AymaxLi** [comment]
我也遇到了类似问题 请问你找到解决方法了吗 @liuyayaya
