### ISSUE TITLE
图标可拖拽出画布

### ISSUE THREAD

**Issue by ghost** [apache/incubator-echarts#4415]
#### 版本及环境 (Version & Environment)
+ ECharts 版本3.3.1:
+ 浏览器类型和版本 safari:
+ 操作系统类型和版本 ios10:

#### 重现步骤 (Steps to reproduce)
1. 使用移动设备打开 http://echarts.baidu.com/demo.html#geo-lines
2. 拖拽地图到屏幕外

#### 期望结果 (Expected behaviour)

禁止拖拽地图出画布，或者拖拽画布其它地方可以将地图拖拽回画布内。

#### 可能哪里有问题 (What went wrong)

无法设置可拖拽范围

**Comment by sarazhang123** [comment]
@pissang 请问该问题是还没有修复吗？
