### ISSUE TITLE
Stream graph type

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4419]
Would be nice if there is something like a "stream" series type so it would be possible to generate: 

![image](https://cloud.githubusercontent.com/assets/561365/20062186/091726d8-a503-11e6-92d8-9f54d703c626.png)

![image](https://cloud.githubusercontent.com/assets/561365/20062783/460ac0ca-a505-11e6-800d-5403c502612b.png)

I can imagine that this would be possible to generate with the stacked area chart with additional transparent series although it would be nice to have something dedicated, potentially generating something like this in future?

![image](https://cloud.githubusercontent.com/assets/561365/20062726/09e3dc08-a505-11e6-97e0-71b5f723a101.png)

**Comment by 100pah** [comment]
In fact we already have <https://github.com/ecomfe/echarts/blob/master/test/themeRiver.html>, although not be published yet. I think we should publish it asap ~

**Comment by jarben** [comment]
Wow, what a nice surprise! Very cool, will start testing it asap.. Planning to include it in the build in 3.3.2?
Thanks heaps!

**Comment by jarben** [comment]
I was playing with the theme river chart today, here is some feedback for future versions of this beautiful chart: 
- tooltip doesn't get relevant data in formatter parameters so it's hard to show anything useful. This is probably the biggest showstopper considering there is no Y axis I think..  
![image](https://cloud.githubusercontent.com/assets/561365/20139667/7f6618fa-a687-11e6-88d0-bfb525949f43.png)
- typo in ThemeRiverView.js: 133, “nomral” should be “normal”
- can’t set label color
- not sure whether it's possible to pass itemStyle in data
- this chart seems to be coupled with singleAxis and only works with type:’time’. I haven't found a way to use it with other axes or other types such as 'category'. 
- chart doesn’t respect grid, uses singleAxis position instead
- doesn’t seem to work in “vertical” axis orientation 
- if no inverval in singleAxis is used, it renderers gaps such as: 
![image](https://cloud.githubusercontent.com/assets/561365/20139762/04dcbf0c-a688-11e6-9f9f-97f923603f80.png)

Anyway, here is what I was able to achieve: 
![image](https://cloud.githubusercontent.com/assets/561365/20139549/03eb81d8-a687-11e6-8642-bd24dfec9a5b.png)

That's probably it for now, it's obviously very early version but still very exciting! Any hints how to quickly fix the tooltip parameters? :)
