### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'zrX' of undefined

### ISSUE THREAD

**Issue by hnyashiro** [apache/incubator-echarts#4420]
在使用echarts任意一个图形时在chrome浏览器中出现如标题所示错误！请指教

**Comment by hnyashiro** [comment]
<script src="js/echarts.min.js"></script>

`$(document).ready(function(){
				var totalCharts = echarts.init(document.getElementById('totalCharts'));
	    		
	    		var option = {
		            title: {
		                text: '总能耗统计'
		            },
		            tooltip: {},
		            legend: {
		                data:['电量(万度)','费用(人民币：万元)'],
		                left:120
		            },
		            xAxis: {
		                data: ["2015","2016","2017","2018","2019","2020"]
		            },
		            yAxis: {},
		            series: [{
		                name: '电量(万度)',
		                type: 'bar',
		                data: [5, 26, 36, 127, 47, 68]
		            },{
		                name: '费用(人民币：万元)',
		                type: 'bar',
		                data: [5, 20, 36, 10, 10, 20]
		            }]
		        };
				totalCharts.setOption(option);
			})`

**Comment by hnyashiro** [comment]
`<script src="js/echarts.min.js"></script>`

**Comment by 100pah** [comment]
何版本

**Comment by AoJiaoDeXiaoPinGuo** [comment]
我也遇到这个问题  最后怎么解决的？
