### ISSUE TITLE
为什么echarts v2/v3 的k线都比较模糊（锯齿严重）

### ISSUE THREAD

**Issue by seakk** [apache/incubator-echarts#4421]
为什么echarts v2/v3 的k线都比较模糊，不精致，chrome浏览器，官方上的实例线也是很模糊，
highcharts的线比较平滑精致， 请问有没有参数可调？ 我看文档 试了一些参数都没效果。

**Comment by Ghost-Ge** [comment]
是不是用了canvas 问题导致？

**Comment by 100pah** [comment]
是否可按照 issue 模板，提供您的环境信息以及optoin配置。

**Comment by Ghost-Ge** [comment]
这是echarts v3截图：https://pan.baidu.com/s/1i4ANHyP
这是highcharts截图： https://pan.baidu.com/s/1kVO7htH

请问有什么好的方法改进？谢谢
