### ISSUE TITLE
多重x轴在点击legend去除一组数据时，会导致x轴不能正常显示，官方样例就出这个bug了

### ISSUE THREAD

**Issue by superddr** [apache/incubator-echarts#4422]
http://echarts.baidu.com/demo.html#dynamic-data
默认打开时，x轴有一堆时间。

点击legend里的“最新成交价”，隐藏掉成交价，这时x轴就只有一个标志了

**Comment by 100pah** [comment]
这个例子中，下方的x轴对应于“最新成交价”，而“预购队列”对应的是上方x轴
