### ISSUE TITLE
UC浏览器极速模式下 echarts 切换到其他标签页 过一会再切换到echarts 图表不显示

### ISSUE THREAD

**Issue by cynicgit** [apache/incubator-echarts#4424]
![image](https://cloud.githubusercontent.com/assets/11511900/20087162/036681bc-a5b1-11e6-8bca-529d1a127583.png)
![image](https://cloud.githubusercontent.com/assets/11511900/20087277/06d2f2f8-a5b2-11e6-8d07-66430841cb98.png)

**Comment by pissang** [comment]
切换后调用一下 resize

**Comment by cynicgit** [comment]
@pissang  我指的是切换浏览器的选项卡，UC浏览器极速模式下会出现，兼容模式不会出现，其他浏览器也不会出现

**Comment by pissang** [comment]
试下能否标签切换后监听到 `visibilitychange` 事件

**Comment by cynicgit** [comment]
@pissang 可以监听到，我在事件里调用了 myChart.resize(); 还是会出现
