### ISSUE TITLE
将GPS坐标转换为百度坐标时，采用百度地图接口API的脚本和ECharts自带地图脚本不兼容

### ISSUE THREAD

**Issue by jiaweixian** [apache/incubator-echarts#4425]
#### 问题简述 (One-line summary)
因为GPS采集到的坐标数据直接显示到百度地图上是有偏差的，所以采用了百度地图的坐标转换接口API，如下，http://developer.baidu.com/map/jsdemo.htm#a5_2，这个接口js和ECharts所带的地图js貌似有冲突不兼容，所以没办法进行转换

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
有什么冲突？

**Comment by jiaweixian** [comment]
可能是我写的代码不对，我对JS不太了解，我在样例基础上改了一下
$.getJSON(uploadedDataURL, function(data) {
    var hStep = 300 / (data.length - 1);
    var busLines = [].concat.apply([], data.map(function(busLine, idx) {
        var prevPt;
        var points = [];
        for (var i = 0; i < busLine.length; i += 2) {
            var pt = [busLine[i], busLine[i + 1]];
            if (i > 0) {
                pt = [
                    prevPt[0] + pt[0],
                    prevPt[1] + pt[1]
                ];
                var x = pt[0];
                var y = pt[1];
                var ggPoint = new BMap.Point(x, y);
                var convertor = new BMap.Convertor();
                var pointArr = [];
                pointArr.push(ggPoint);
                BMap.convertor.translate(pointArr, 1, 5, translateCallback)
            }
            prevPt = pt;
            tmp = [pt[1] / 1e4, pt[0] / 1e4];
            points.push([tmp[1], tmp[0]]);

        }
        translateCallback = function(data) {
            if (data.status === 0) {
               // points.push([data]);
            }
        }
然后就不会显示，您能告诉我哪里不对吗？

**Comment by jiaweixian** [comment]
@pissang  我对JS也不太了解，在样例基础上改了一下，可能不太对，您能看一下吗？
$.getJSON(uploadedDataURL, function(data) {
    var hStep = 300 / (data.length - 1);
    var busLines = [].concat.apply([], data.map(function(busLine, idx) {
        var prevPt;
        var points = [];
        for (var i = 0; i < busLine.length; i += 2) {
            var pt = [busLine[i], busLine[i + 1]];
            if (i > 0) {
                pt = [
                    prevPt[0] + pt[0],
                    prevPt[1] + pt[1]
                ];
                var x = pt[0];
                var y = pt[1];
                var ggPoint = new BMap.Point(x, y);
                var convertor = new BMap.Convertor();
                var pointArr = [];
                pointArr.push(ggPoint);
                BMap.convertor.translate(pointArr, 1, 5, translateCallback)
            }
            prevPt = pt;

        }
        translateCallback = function(data) {
            if (data.status === 0) {
               // points.push([data]);
            }
        }

**Comment by jiaweixian** [comment]
@pissang  百度的API转换需要加这个脚本 http://developer.baidu.com/map/jsdemo/demo/convertor.js ，如果添加之后【即使不修改代码】，ECharts原来自带的/dep/echarts/latest/extension/bmap.min.js脚本就不能使用了，地图的显示都出现问题。
