### ISSUE TITLE
Is there any way to optimize or disable anti-aliasing in stepped lines graph? 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4431]
Version: 3.2.2

When many data points are used inside stepped line, it creates something like this: 
![image](https://cloud.githubusercontent.com/assets/561365/20097795/986b0d56-a5b0-11e6-9714-7b10933d5c9f.png)

Feels like it would display nicer if anti-aliasing is not used? Or is there any other reason why it renders a little like it has rounded corners? 

Subpixel values are particularly blured: 
![image](https://cloud.githubusercontent.com/assets/561365/20097854/dc1e8aaa-a5b0-11e6-8c53-7e4809b2c1ba.png)

Is there any way to disable anti-aliasing in echarts/zrender so it snaps to the nearest pixel? Or is this what is rendered by the canvas element?

**Comment by pissang** [comment]
We have added anti-aliasing optimization on some straight line like axis. Maybe we can also try to apply this optimization to step line.

**Comment by jarben** [comment]
That would be great, Thanks for your answer Yi! Possibly related issue, see bottom-left corner of this chart: 

![image](https://cloud.githubusercontent.com/assets/561365/20102279/df699b54-a5c5-11e6-8b6d-293a1317802a.png)

Scaled: 

![image](https://cloud.githubusercontent.com/assets/561365/20102262/c9748818-a5c5-11e6-99b1-2d6f4eae7f3d.png)

Looks like the step is not exactly horizontal for some reason, some steps are also little transparent such as this one against white background:

![image](https://cloud.githubusercontent.com/assets/561365/20102423/5bbbc8ee-a5c6-11e6-94bd-3963dd377ba5.png)

Or this agains dark background: 
![image](https://cloud.githubusercontent.com/assets/561365/20102586/e622b83a-a5c6-11e6-8f52-8e71c71f65da.png)

**Comment by pissang** [comment]
That seems weird. I will have a look at it. Thanks for the detailed test @jarben 👍

**Comment by jarben** [comment]
No worries @pissang , thanks for looking at it. One thing I've noticed is that the non-horizontal effect seems to only happen only with floating values such as: 21.929824561403507. I'm calculating it from values so it can display as 100% height. When I do Math.round(value), it all seems pretty horizontal, although there is still that slightly transparent line.. 

Also, reproducing is not instant, it only happens when the chart is at certain height so you might need to resize your window few times + it often happens only after the tooltip is activated:

![image](https://cloud.githubusercontent.com/assets/561365/20104058/c4813dfe-a5cc-11e6-920b-82cc2b9f3f57.png)

I'm also attaching a sample options JSON which I've pasted into the echarts editor as shown above.. 

[stepped_line_issue.zip](https://github.com/ecomfe/echarts/files/578495/stepped_line_issue.zip)

Let me know if you need more info!
