### ISSUE TITLE
添加自定义的lable

### ISSUE THREAD

**Issue by chensjmail** [apache/incubator-echarts#4436]
#### 问题简述 (One-line summary)
可否在图形中添加自定义的lable
要有有文字和图标文字有字体设置
像这样的效果:
http://chuantu.biz/t5/41/1478654234x1032878060.bmp

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by chensjmail** [comment]
[http://chuantu.biz/t5/41/1478654234x1032878060.bmp](url)

**Comment by chensjmail** [comment]
http://chuantu.biz/t5/41/1478654234x1032878060.bmp

**Comment by chensjmail** [comment]
像这样的效果:
[http://chuantu.biz/t5/41/1478654234x1032878060.bmp](url)

**Comment by 100pah** [comment]
这个可以用 html 自己画

**Comment by chensjmail** [comment]
@100pah 
html自己画?要在图里画,您说的是在图里还是在图外?

**Comment by 100pah** [comment]
我指得是在图外，因为按你给的例子来说，需要自定义的是一整块，可以在图外画。

**Comment by chensjmail** [comment]
@100pah 
我给的例子就是在图外做出来的效果,我是想在图内,因为客户想导出图片,包括这些东西

**Comment by 100pah** [comment]
做了个例子，大体能达到效果，虽然稍有繁琐，
<http://gallery.echartsjs.com/editor.html?c=xrJJ6yOxWx&v=3>

**Comment by chensjmail** [comment]
@100pah 
利害,感谢,不过还有个问题,怎么居中?

**Comment by chensjmail** [comment]
@100pah 
不能居中,有没有别的办法
