### ISSUE TITLE
symbol设置为图片，能否使用gif格式

### ISSUE THREAD

**Issue by zhaoxueyin000** [apache/incubator-echarts#4447]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以使用，但是不会有动画

**Comment by zhaoxueyin000** [comment]
谢谢，那用gif就没有意义了

**Comment by zhaoxueyin000** [comment]
有没有什么方法能实现动画效果
