### ISSUE TITLE
x轴第一个数据变成undefined

### ISSUE THREAD

**Issue by AnAmazingMan** [apache/incubator-echarts#4455]
#### 问题简述 (One-line summary)

在tooltip中用formatter后，x轴的第一个数据变成了undefined

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by mirari** [comment]
#4328 我之前也已经提了这个问题，但是没有被重视啊
