### ISSUE TITLE
echarts3 的雷达图在触发click 事件后，获得的 params 中 无法获取 indicator 信息

### ISSUE THREAD

**Issue by yongnny** [apache/incubator-echarts#4462]
#### 问题简述 (One-line summary)
echarts3 的雷达图在触发click 事件后，获得的 params 中 无法获取 indicator 信息

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.3.1
+ 浏览器类型和版本 (Browser version):  chrome  版本 54.0.2840.71 m
+ 操作系统类型和版本 (OS Version):  win7

#### 重现步骤 (Steps to reproduce)
1. 代码
`option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        indicator: [
           { name: '销售（sales）', max: 6500},
           { name: '管理（Administration）', max: 16000},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            },
             {
                value : [5000, 14000, 28000, 31000, 42000, 21000],
                name : '实际开销（Actual Spending）'
            }
        ]
    }]
};

myChart.on('click', function (params) {
    // 控制台打印数据的名称
    console.log(params);
});`

2.点击 图例上的点，获得如下 params
![image](https://cloud.githubusercontent.com/assets/14834440/20237457/e5360126-a90d-11e6-8456-087d3ce3a682.png)

#### 期望结果 (Expected behaviour)
根据上图，可见：name 中放的 是 legend 信息，而在echarts2 中，name 放的是 indicator 信息。 legend 信息已经存在于  data.name 了，没必要 放在 name 属性中。现在的情况是，无论点击某一个图例上的任何一个点，返回的 params 都是一样的

#### ECharts配置项 (ECharts option)

```javascript
option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        indicator: [
           { name: '销售（sales）', max: 6500},
           { name: '管理（Administration）', max: 16000},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            },
             {
                value : [5000, 14000, 28000, 31000, 42000, 21000],
                name : '实际开销（Actual Spending）'
            }
        ]
    }]
};

```

#### 其他信息 (Other comments)
ehcarts3
![image](https://cloud.githubusercontent.com/assets/14834440/20237457/e5360126-a90d-11e6-8456-087d3ce3a682.png)

echarts2
![image](https://cloud.githubusercontent.com/assets/14834440/20237470/1c4bb386-a90e-11e6-8fe0-a78493a6a00d.png)

**Comment by zyziyun** [comment]
现在解决了么，感觉是个很常见的需求，是否可以解决下呢？

**Comment by shangx335** [comment]
@pissang 希望可以解决一下这个问题

**Comment by songkai2012** [comment]
一年了一年了 官方不管了吗？

**Comment by xuanGetit** [comment]
kpi项目啊

**Comment by EAGLEliuS** [comment]
同樣的問題，有解決麼？

**Comment by feijuncheng** [comment]
很常见的需求，这个不解决下？

**Comment by songkai2012** [comment]
> 很常见的需求，这个不解决下？

用echarts2就好了 3就别指望了
