### ISSUE TITLE
折线图中symbol设置为emptyCircle时，是否可以设置symbol的背景颜色？

### ISSUE THREAD

**Issue by cooljser** [apache/incubator-echarts#4464]
当symbol设置为emptyCircle时，symbol默认的背景颜色是白色，是否有属性可以修改该颜色？

**Comment by xubowenjx** [comment]
兄弟 顶你上去。讲道理可以同自定义节点图片来做,但是如果有个symbolStyle属性多直接。

**Comment by xialvjun** [comment]
为什么就毫无理由的关了啊... 就算 stale 了, 也说下准不准备实现啊... @cooljser , reopen 吧

**Comment by KingJeason** [comment]
+1

**Comment by YogurtQ** [comment]
+1，整体背景为深色的时候，这个空心圆的白色真的很刺眼。。。

**Comment by 1144169197** [comment]
迂回一下实心实现
itemStyle: {
            normal: {
                borderColor: "#24DE9D",
                color: "#222b43",
                lineStyle: {
                    color: "#2ec7c9"
                }
            }
        }

**Comment by YogurtQ** [comment]
> 迂回一下实心实现
> 
> ```
> symbol: "circle",
> itemStyle: {
> 	normal: {
> 		borderColor: "#24DE9D",
> 		color: "#222b43",
> 		lineStyle: {
> 			color: "#2ec7c9"
> 		}
> 	}
> }
> ```

这种方法我试过，把圆点颜色设置成跟背景色相同，但是图例会一并隐藏掉

**Comment by 1144169197** [comment]
> > 迂回一下实心实现
> > ```
> > symbol: "circle",
> > itemStyle: {
> > 	normal: {
> > 		borderColor: "#24DE9D",
> > 		color: "#222b43",
> > 		lineStyle: {
> > 			color: "#2ec7c9"
> > 		}
> > 	}
> > }
> > ```
> 
> 这种方法我试过，把圆点颜色设置成跟背景色相同，但是图例会一并隐藏掉

legend: [
       {
            left: "15%",
            data:[{
                name: "腾讯",
                icon: "circle"
            }],
            itemStyle: {
            	color: "#2ec7c9"
            }
        },{
            left: "25%",
            data:[{
                name: "百度",
                icon: "circle"
            }],
            itemStyle: {
            	color: "#222b43"
            }
        }
    ]
缺点就是需要自己调整位置

**Comment by 1144169197** [comment]
> > > 迂回一下实心实现
> > > ```
> > > symbol: "circle",
> > > itemStyle: {
> > > 	normal: {
> > > 		borderColor: "#24DE9D",
> > > 		color: "#222b43",
> > > 		lineStyle: {
> > > 			color: "#2ec7c9"
> > > 		}
> > > 	}
> > > }
> > > ```
> > 
> > 
> > 这种方法我试过，把圆点颜色设置成跟背景色相同，但是图例会一并隐藏掉
> 
```
legend: [
       {
            left: "15%",
            data:[{
                name: "腾讯",
                icon: "circle"
            }],
            itemStyle: {
            	color: "#C1232B"
            }
        },{
            left: "25%",
            data:[{
                name: "百度",
                icon: "circle"
            }],
            itemStyle: {
            	color: "#B5C334"
            }
        }
    ]
```
缺点就是需要自己调整位置
