### ISSUE TITLE
雷达图无法在折线拐点处触发tooltip，无法为indicator设置样式

### ISSUE THREAD

**Issue by willywang** [apache/incubator-echarts#4482]
#### 问题简述 (One-line summary)
1. 配置tooltip.trigger = 'item'时，鼠标移动到雷达图折线上能触发tooltip，但没有配置支持仅当鼠标移动到折线拐点处时触发tooltip
2. 雷达图的indicator默认是灰色文字，无法更改其样式（文字颜色，大小等）

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.2
+ 浏览器类型和版本 (Browser version):All
+ 操作系统类型和版本 (OS Version):All

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
1. tooltip的能支持在折线拐点触发，同时能在tooltip.formatter回调params中获取到该拐点处多个series的数据，以便于数据对比，而不仅仅是当前series拐点的数据
2. 能配置indicator的样式

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/4462 类似，暂时不支持

**Comment by willywang** [comment]
有支持计划吗

**Comment by Xbantian** [comment]
同问，axis触发会好一点，讲道理，2.x版本是支持的啊 @pissang  求指导
