### ISSUE TITLE
柱形图 y轴 在设置了min之后 显示整数失败

### ISSUE THREAD

**Issue by monvhh** [apache/incubator-echarts#4489]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.3.1 && 3.2.3
+ 浏览器类型和版本 (Browser version): chrome 54.0.2840.87 m
+ 操作系统类型和版本 (OS Version): win10

#### 重现步骤 (Steps to reproduce)
1，柱形图
2，配置如下
yAxis:[
{
     type:'value',
     minInterval:1,
     min:0
}]
3,数据不超过5

#### 期望结果 (Expected behaviour)

柱状图y轴显示正整数。未设置min的时候，能正确显示整数，设置min之后就变成0.5的分隔了。期望y轴只显示正整数。

#### ECharts配置项 (ECharts option)

```javascript
option = {
yAxis:[
{
     type:'value',
     minInterval:1,
     min:0
}]
}

```

**Comment by pissang** [comment]
方便 http://gallery.echartsjs.com/explore.html 建个例子么？

**Comment by monvhh** [comment]
@pissang  http://gallery.echartsjs.com/editor.html?c=xry-Q_65Wl&comment=0

**Comment by partical** [comment]
数值轴设置了最小值或者最大值之后，会根据splitNumber || 5 来分隔数值轴，而没有根据minInterval来分割。见axisHelper.js niceScaleExtent()

**Comment by MrChanLi2013** [comment]
@monvhh 这样设置就是显示整数
```javascript
 yAxis: {
        type: 'value',
        axisLine: {
            show: false
        },
        axisTick: {
            show: false
        },
        min: 0,
        interval: 1 //minInterval不设置这个东西，强制设置坐标轴分割间隔（interval）。

    },
```

**Comment by monvhh** [comment]
@MrChanLi2013  不敢这样做，万一数据量很大，y轴标识会特别多。。

**Comment by WangXiZhu** [comment]
可以当 所有数据都小于某个数字的时候，加一个 max属性。  比如
data: [1, 2, 0, 3, 1, 2, 1]
这样的话 就设置 max: 4
这样就可以避免小数，如果是其余情况下不设置。

http://gallery.echartsjs.com/editor.html?c=xHJWkkQcBx&v=2

**Comment by zealitude** [comment]
我发现问题总是出现在数值 < 3时

**Comment by lxjwlt** [comment]
@WangXiZhu 如果图表有两条线 一条大于4 一条全部0  在legend 我关掉大于4的那条线 只留下全部为0的那一条 这样还是会显示浮点数

**Comment by WangXiZhu** [comment]
@lxjwlt 应该影响不大吧！ 如果一定不要小数的话，就设置 max,min,interval  应该就可以了。

**Comment by aufula** [comment]
这个有计划修复么？
