### ISSUE TITLE
Bar chart color from visual map 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4491]
Version: 3.3.1

I'm unable to find a way how to set colors of individual bars based on visual map settings. In 2.x version, this used to be possible using something like: 

![image](https://cloud.githubusercontent.com/assets/561365/20341897/729564d0-abe8-11e6-8aa8-96e5be7298e3.png)

which generated this: 
![image](https://cloud.githubusercontent.com/assets/561365/20342102/6451994c-abe9-11e6-8dc6-886c82012c15.png)

However, in 3.x, I'm unable to set colors of each bar based on value: 
![image](https://cloud.githubusercontent.com/assets/561365/20341956/b15df5e2-abe8-11e6-98ea-f46d44c1a7b6.png)

As per picture, map gets colors from the visualMap settings, however, bar chart doesn't. 

Is this a bug or am I missing some sort of settings? 

My visualMap setting looks like: 
![image](https://cloud.githubusercontent.com/assets/561365/20342469/cb85d46a-abea-11e6-9321-5388bbe6f423.png)

I've also tried something like: 
![image](https://cloud.githubusercontent.com/assets/561365/20342582/59f690a4-abeb-11e6-8854-23e23640910c.png)

but with no results.. Any thoughts? :)

**Comment by jarben** [comment]
I can actually achieve it by using the new getVisual() API: 

chart.getVisual({dataIndex: i, seriesId:"map"}, 'color');

However, this can be only done when the map chart is already rendered, not when constructed.. 

Anyway, if you know about a nicer way to achieve this please let me know!

**Comment by BorisTB** [comment]
Any update on this? I have the same problem

**Comment by srikanthratvirtusa** [comment]
for you color range is working 
use this for default colors random
 inRange: {
            color: ['#c23531','#2f4554', '#61a0a8', '#d48265', '#91c7ae','#749f83',  '#ca8622', '#bda29a','#6e7074', '#546570', '#c4ccd3'],
        },
