### ISSUE TITLE
how to display months in xAxis and how to dynamically change it to stop on the current month-Line Graph

### ISSUE THREAD

**Issue by JoaoEscobar1** [apache/incubator-echarts#4494]
hello everyone i have no idea how to display months in the xAxis and make it dynamic. i mean if i am in April the chart only displays : January, February, March, April

Thanks and much apprecciate

**Comment by WeiFei365** [comment]
what show in the xAxis is up to you; you can set :

```javascript

xAxis[0].data = ['January', 'February', 'March', 'April'];

```

if your echarts' version > 3.0, you also can set:

```javascript

option = {
    // ...others

    xAxis: [
        {
            data: [
                { value: 'Jan', label: 'January' }
                { value: 'Feb', label: 'February' }
                { value: 'Mar', label: 'March' }
                { value: 'Apr', label: 'April' }
            ],
            axisLabel: {
                formatter: function(d) {
                    return d.label;
                }
            }
        }
    ]

    // ...others
};

```

please open this page to test your option inline: [http://echarts.baidu.com/demo.html#bar-tick-align](http://echarts.baidu.com/demo.html#bar-tick-align)

**Comment by JoaoEscobar1** [comment]
when i try to use your code i get this error SyntaxError: "missing ] after element list
{ value: 'Feb', label: 'Fev' }"

I had issues because it seems that i can't display those 12 months of the year it seems that the default is only 7 values so in this case: [ January,February,March,April,May,June,July] only

	xAxis: [
        {
          type: 'category',
          boundaryGap: false,
          data:[
                { value: 'Jan', label: 'January' }
                { value: 'Feb', label: 'February'}
                { value: 'Mar', label: 'March' }
                { value: 'Apr', label: 'April' }
                { value: 'May', label: 'March' }
                { value: 'Jun', label: 'June' }
                { value: 'Jul', label: 'July' }
                { value: 'Aug', label: 'August' }
                { value: 'Sep', label: 'September'}
                { value: 'Oct', label: 'October' }
                { value: 'Nov', label: 'November' }
                { value: 'Dec', label: 'December' }
            ],
            axisLabel: {
                formatter: function(d) {
                    return d.label;
                }
            } 
        }],
        yAxis: [{
          type: 'value'

**Comment by JoaoEscobar1** [comment]
[cid:463b3f17-864e-4dfa-804f-5f36842615a2]

This is the problem that i am facing i want to display 12 months and it seems it can only display 7 months ending in July. WHat can i do to solve this problem? in data i have data: ["Jan","Feb","Mar","April","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]. But it still only displays the first 7
________________________________

**Comment by WeiFei365** [comment]
Sorry so long time to reply to you!

in my last msg, the option is not completed; please use this:

```javascript


option = {
    color: ['#3398DB'],
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : [
                { key: 'Jan', label: 'January' },
                { key: 'Feb', label: 'February'},
                { key: 'Mar', label: 'March' },
                { key: 'Apr', label: 'April' },
                { key: 'May', label: 'March' },
                { key: 'Jun', label: 'June' },
                { key: 'Jul', label: 'July' },
                { key: 'Aug', label: 'August' },
                { key: 'Sep', label: 'September'},
                { key: 'Oct', label: 'October' },
                { key: 'Nov', label: 'November' },
                { key: 'Dec', label: 'December' }
            ],
            axisLabel: {
                // force to display all labels
                interval: 0,
                formatter: function(d) {
                    return d.label;
                }
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'TEST',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220, 10, 52, 200, 334, 390]
        }
    ]
};


```

<hr>

And please make sure ```option.xAxis[0].data.length === option.series[0].data.length```; because the ```option.xAxis[0].data``` is for the x-axis, the ```option.series[0].data``` is for the bars;

As for your axis only display 7 labels, i guess your ```option.series[0].data.length```is 7;

Also, I made a mistake, in the ```option.xAxis[0].data```, if the data item is a abject, please don't use the *value* key, otherwise, the ```option.xAxis[0].axisLabel.formatter``` function's argument will be a string, not a object
