### ISSUE TITLE
chrome 52.0.2743.116 m 中，e3版本中title的textAlign显示有误，使用x:'center'显示正常，与api说明不符

### ISSUE THREAD

**Issue by dnflove962789** [apache/incubator-echarts#4502]
#### 问题简述 (One-line summary)

chrome 52.0.2743.116 m 中，e3.3.1版本中title的textAlign显示有误，反而使用x:'center'显示正常，与api说明不符，操作系统win10

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by NexusLee** [comment]
同
