### ISSUE TITLE
Echarts3 tooltip的位置问题

### ISSUE THREAD

**Issue by lshbyy** [apache/incubator-echarts#4505]
Echarts3 时，tooltip框的位置，在鼠标所在位置的上方，当tooltip的内容较多时，有部分无法显示

这是什么情况呢、已经排除了overflow时hidden等情况...

**Comment by zhump** [comment]
最好能提供一个可以跑的 例子 或者 一个 可运行的option 数据

**Comment by zhouboluo** [comment]
堆叠图数据很多的话比较明显

**Comment by partical** [comment]
tooltip里面的内容是一段html元素，里面的显示可能会依赖外部div的布局，比如外面的div有overflow : hidden 属性的话，tooltip的内容是可能显示不全的
