### ISSUE TITLE
xAxis为time 的两图数据显示对齐问题

### ISSUE THREAD

**Issue by warlock-lv** [apache/incubator-echarts#4512]
#### 问题简述 (One-line summary)
我有两个坐标系图形（两个option，分别为myChart1, myChart2），xAxis都是time类型， yAxis都是 value类型， 
它们的原始数据分别是：
data1为 [['2016-08-11 06:41:15', -134.0], ['2016-08-11 06:41:17', -104.0], ['2016-08-11 06:41:18', -114.0], ['2016-08-11 06:41:22', -145.0], ['2016-08-11 06:41:29', -115.0]]
data2为  [['2016-08-11 06:41:17', 2],      ['2016-08-11 06:41:18', 1],      ['2016-08-11 06:41:22', 2]]
就是说data2的时间比data1的时间 少，这时echart画出的两个图的开始时间 及 结束时间 都是不同的。 
我试着将data2补数据[['2016-08-11 06:41:15',    '-'], ['2016-08-11 06:41:17', 2],      ['2016-08-11 06:41:18', 1],      ['2016-08-11 06:41:22', 2], ['2016-08-11 06:41:29', '-']]
但是起始时间并没有对齐。   请不要回复将xAxis类型改为category， 这样不行。 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  echart 3
+ 浏览器类型和版本 (Browser version): chrome 38.0
+ 操作系统类型和版本 (OS Version): windows 7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
![image](https://cloud.githubusercontent.com/assets/19185428/20417916/d4a77c84-ad83-11e6-82ca-a6a51396e398.png)

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 贴个例子
