### ISSUE TITLE
echarts结合bmap使用时，无法正常使用brush工具，因为地图会同时响应鼠标拖拽

### ISSUE THREAD

**Issue by mirari** [apache/incubator-echarts#4515]
#### 问题简述 (One-line summary)
在bmap上绘制散点图，开启brush工具，但是无论是矩形还是圈选，都无法正常选择到想要的范围，因为按下鼠标后，地图也会跟随鼠标拖拽而移动。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):目前最新版
+ 浏览器类型和版本 (Browser version):所有浏览器
+ 操作系统类型和版本 (OS Version):所有系统

#### 重现步骤 (Steps to reproduce)
1.点击矩形或者圈选，开启brush功能
2.按下鼠标并拖拽，地图会跟随鼠标移动，无法绘制范围

#### 期望结果 (Expected behaviour)
开启brush功能时，bmap停止地图拖拽，关闭brush功能时，bmap重新启用拖拽

#### 可能哪里有问题 (What went wrong)
bmap未能响应brush工具的状态变化。
我本想在echarts上通过事件响应来控制地图的拖拽功能开闭，但是在文档中没有找到响应的事件。官网文档中与brush相关的只有两个事件，一个是brush一个是brushselected，前者是鼠标拖拽过程中定期触发，后者在brush事件触发后一定会触发，在每次点击工具栏按钮时也都会触发，没有一个事件是表示工具栏的工具本身开闭的。

#### 其他信息 (Other comments)
请直接查看线上实例
http://gallery.echartsjs.com/editor.html?c=xSyoBA1i-l&v=6
在echart结合geo地图使用brush功能时，没有这个问题。
http://gallery.echartsjs.com/editor.html?c=xBJLi4-7bx

**Comment by pissang** [comment]
现在对百度地图扩展中拖拽的处理确实不太好，后续优化

**Comment by danhuan** [comment]
这个问题有办法解决吗，我也遇到了

**Comment by halvee-L** [comment]
我也遇到了类似问题，jq UI拖拽和区域选择冲突了。 我想知道有什么办法可以获取到当前是否处于选择状态么。这样我可以拖动禁用jq UI的拖拽
