### ISSUE TITLE
地图构建 河南 济源市 无法构建

### ISSUE THREAD

**Issue by aoeng** [apache/incubator-echarts#4522]
#### 问题简述 (One-line summary)

地图构建 河南 济源市 无法构建 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.
![image](https://cloud.githubusercontent.com/assets/23565714/20452408/e4aedabc-ae43-11e6-8fbf-3e80d2452919.png)

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by zds-xiaoxianyu** [comment]
@UpGod 
![default](https://cloud.githubusercontent.com/assets/25834106/23246325/a9539144-f9cd-11e6-947e-1b07281dcb22.png)确实有几个县级市的地图构建有问题，我试过了某些县级市需要勾选不包含子区域 subregion，这样才能成功构建，，，，，，，，我在制作地图三级级联遇到这个问题

**Comment by IdenPin** [comment]
@zds-xiaoxianyu   你的地图下钻返回是通过面包屑实现的吗？为什么点击返回河南后选择河南下面的市无法获取到click事件callBack 里面的params.name
