### ISSUE TITLE
在echarts gallery上运行例子总显示 Cannot read property 'cloneShallow' of undefined

### ISSUE THREAD

**Issue by pzljp** [apache/incubator-echarts#4531]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.  打开echarts gallery，点击新建
2. 将自己的数据保存成json文件，点击上传，运行echarts代码
3. 控制台保存：echarts gallery

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
gallery 上有你建的例子么？

**Comment by pzljp** [comment]
我直接把数据拷出来放到变量里了。你看一下http://gallery.echartsjs.com/editor.html?c=xS1kKfQlzl&comment=0。这是我遇到的问题。
