### ISSUE TITLE
时间轴上的柱状图绘制到了X轴之外

### ISSUE THREAD

**Issue by k8w** [apache/incubator-echarts#4532]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
3.0
+ 浏览器类型和版本 (Browser version):
Chrome
+ 操作系统类型和版本 (OS Version):
Win7

#### 重现步骤 (Steps to reproduce)
1. 见下方示例option

#### 期望结果 (Expected behaviour)
正常画出柱状图

#### 可能哪里有问题 (What went wrong)
第一根和最后一根柱，都画到X轴之外了

#### ECharts配置项 (ECharts option)

```javascript
option = {
    xAxis: {type: 'time'},
    yAxis: {},
    dataZoom: [{type: 'inside'}],
    series: [
        {
            type: 'bar',
            data: [
                [1479714808571,10],
                [1479801208571,11],
                [1479887608571,12],
                [1479974008571,13],
                [1480060408571,14]
            ]
        }    
    ]
};

```

**Comment by pissang** [comment]
如果时间间隔固定的话建议用 category 类型的 x 轴，如果必须要用 time 轴的话可以设置 http://echarts.baidu.com/option.html#xAxis.boundaryGap

**Comment by twoeo** [comment]
@pissang 
无论是数字还是百分比，boundaryGap似乎都对时间轴不生效？

```javascript
option = {
    xAxis: {type: 'time', boundaryGap: [200, '100%'] },
    yAxis: {},
    dataZoom: [{type: 'inside'}],
    series: [
        {
            type: 'bar',
            data: [
                [1479714808571,10],
                [1479801208571,11],
                [1479887608571,12],
                [1479974008571,13],
                [1480060408571,14]
            ]
        }    
    ]
};
```

**Comment by pissang** [comment]
@twoeo 时间轴的 `min`, `max` 默认设置为数据的最小最大值了，所以会忽略 boundaryGap，如果需要生效可以设置 `min: null`, `max: null`

**Comment by twoeo** [comment]
@pissang 即便设置`min: null`, `max: null`，虽然在初始化以后不会出现这种情况，但是在dataZoom滚动的时候仍然出现类似的情况。

**Comment by twoeo** [comment]
@pissang 或许可以对第一根和最后一根柱特殊处理一下，例如只画半边？

**Comment by swywanying** [comment]
现在有更好的解决办法了吗？

**Comment by chenjiangshuo** [comment]
@pissang 这个问题解决了吗？
