### ISSUE TITLE
折线图线条高亮时的线条颜色值在哪里改变

### ISSUE THREAD

**Issue by elelvenliu** [apache/incubator-echarts#4539]
鼠标悬浮在图例上，对应折线图的线条会改变颜色，这个颜色在哪里配置？
![default](https://cloud.githubusercontent.com/assets/10057093/20517861/e8d39cc2-b0d7-11e6-9d88-f46f8bc7e564.png)

**Comment by partical** [comment]
系列中的lineStyle -->emphasis --> color

**Comment by partical** [comment]
连接点的颜色能够改变，itemStyle.emphasis.color , 但是线条的颜色好像改不了

**Comment by elelvenliu** [comment]
@partical 线条的常态的颜色是可以改变的，就是鼠标放在图例上，对应的线条会高亮而且颜色变了，这个高亮时的颜色不知道去哪改了。。。
