### ISSUE TITLE
关系图：最多能支持多少个节点多少条边？

### ISSUE THREAD

**Issue by ghost** [apache/incubator-echarts#4542]
因为我所正在做的项目最多可能会有一万个节点，上百万条边，不知道echats的关系图能否支撑，加载时性能怎么样。当然我还没有真正去用这个关系图，目前在用别的插件，就想问一下，谁知道给个大概的数，或是里面有什么属性可以设置，如果性能好的话，我就弃用那个插件用echarts了。谢谢

**Comment by pissang** [comment]
这个数据量 echarts 无法实现实时的绘制

**Comment by jiangxinlei** [comment]
谢谢回答，那最多支持多少呢，关系图应该可以带操作吧，比如增加删除节点和边

**Comment by Yuegg1234** [comment]
@jiangxinlei 请问你说的那个插件是什么？谢谢！

**Comment by jiangxinlei** [comment]
@Yuegg1234 sigmajs
