### ISSUE TITLE
桑基图能保证按层级有序的排列吗？

### ISSUE THREAD

**Issue by pzljp** [apache/incubator-echarts#4547]
#### 问题简述 (One-line summary)

官网提供的例子，桑基图里的终止节点(类似于叶子节点)都是在最后一排。无论是第三级、第四级、第五级，都在最后一排。。。桑基图能保证按层级有序的排列？echarts的布局算法就是让终止节点(类似于叶子节点)都是在最后一排吗？我看了api没有，没有相应的配置啊。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pzljp** [comment]
自己回答一下吧。没有配置。但可以通过修改数据来解决。桑基图的特点是叶子结点(没有后继的结点)强行的放在最后一排。所以在图中插一个空白结点，让原叶子结点指向空白节点，从而变成非叶子节点。这样就实现了效果。

**Comment by gavinguo1987** [comment]
@pzljp 
自己回答一下吧。没有配置。但可以通过修改数据来解决。桑基图的特点是叶子结点(没有后继的结点)强行的放在最后一排。所以在图中插一个空白结点，让原叶子结点指向空白节点，从而变成非叶子节点。这样就实现了效果。
这个你试过成功了吗？如果成功数据能发下看看吗？

**Comment by pzljp** [comment]
@gavinguo1987   我这边已经实现了。数据不方便发，但是你可以用官网给的数据试试。
