### ISSUE TITLE
怎么把toolbox改成hover图表后显示?

### ISSUE THREAD

**Issue by cqcn1991** [apache/incubator-echarts#4567]
想把toolbox改成鼠标进入图表之后再显示，平时自动隐藏
基本效果如下
![echarts_toolbox](https://cloud.githubusercontent.com/assets/2425141/20646505/e90d0ed6-b4b4-11e6-88f7-15f938163890.gif)

但是不知道怎么改，也没看到相应的文档。
不知道有没有前辈可以指点一下的？

本来以为改css就行了，可是看了echarts的源码，好像不是这么回事？

**Comment by kener** [comment]
http://echarts.baidu.com/option.html#toolbox.iconStyle.normal.borderColor
不是完全满足，但我想这样做可以稍微贴近一点，normal的颜色改浅色一点，hover到icon上增强，实在还想trick一点可以用css在toolbox区加个背景元素
