### ISSUE TITLE
Lines series suggestions for implementing flow maps

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4603]
Version: 3.3.1

I'm working on a Flow Map chart similar to this one: 
![image](https://cloud.githubusercontent.com/assets/561365/20760907/93d38fd4-b721-11e6-90bc-52a5d2135bfe.png)

The issue is that I don't think I can do this using echarts at the moment, here is what I've achieved: 

![image](https://cloud.githubusercontent.com/assets/561365/20760954/b5f1f916-b721-11e6-8d04-9812fed5ef8d.png)

The last bit I'm trying to do is to add arrows at the end of each line using the "effect" options but I don't thing there is a way to do this as there doesn't seem to be a way to stop symbol move.. 
![image](https://cloud.githubusercontent.com/assets/561365/20761312/dc0a965c-b722-11e6-8995-988a33527cdd.png)

Can you think of any way to achieve this? Maybe with scatter using arrow symbols and somehow getting the right angle from the lines model? 

Or would this be an interesting & easy to implement new feature? Either using the effect option where it would be possible to set symbol position and disable animation? 

Or startSymbol & endSymbol option on the lines config? Note that an important part of this is an angle of the symbol pointing to where line goes.. 

Another set of suggestions: 
- I couldn't find a way to set width of the line using visualMap, it would be great if one of the channel is "width" so that width of the line is automatically calculated from value. At the moment, I had to calculate it inside data items. 
- It would be great if symbolSize can be set individually inside data items so that each line can have different symbolSize (arrow size on each line) (I haven't tried if this can be changed in the visualMap)
- What would be really awesome is if line can change width along the way, for example, if start is 2px and finish 10px so that the origin country is not covered by a number of lines. 

Anyway, I' having good fun with playing with lines and map!

**Comment by kener** [comment]
Interesting and cool feature~ That would enhance echarts‘ capability of data analytic if the 'line width' can be a visual channel. Classic works below can be realized by echarts, awesome! Think about it and try please~
![59d13d49te390fb57f647 690](https://cloud.githubusercontent.com/assets/1711855/20780997/88c5da54-b7ba-11e6-8a9b-a04393f93319.jpeg)

**Comment by kener** [comment]
ps. The two ending width of a line should be both mapped by data, that would be more elegant~

**Comment by jarben** [comment]
Any updates on this?:)
