### ISSUE TITLE
echarts与bmap的click冲突

### ISSUE THREAD

**Issue by Mr-O2** [apache/incubator-echarts#4608]
如题，如果echarts中要素的与百度地图中的重合的话，点击会只响应百度地图的click事件，弹出信息对话框，而echarts的click事件则被屏蔽

在百度地图的初始化参数中可以关闭底图可点功能，但是echart中调动bmap则没有办法关闭，

可不可以在echarts的bmap参数配置中将这个参数（enableMapClick）加上？

**Comment by lixuesheng83829** [comment]
同问，不过这个应该是bmap要完善的

**Comment by Mr-O2** [comment]
官方怎么没有回复呢？

**Comment by wangweida** [comment]
这个问题还在啊。。。echarts内部new BMap的时候不支持传options吗

**Comment by zhaozhe0831** [comment]
这个问题已经快2年了。。。
