### ISSUE TITLE
Customizable gauge pointer path

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4619]
Version: 3.3.2

It would be nice if the PointerPath can be provided as a symbol, or if it has a property that would allow to set radius of the bottom part similar to this one: 

![image](https://cloud.githubusercontent.com/assets/561365/20825168/9d1faf18-b862-11e6-9ee1-eeea0691cd4d.png)

**Comment by Mignon-han** [comment]
I also have a strong demand for this, in addition to the dashboard can be vertical or horizontal display.
![gauge](https://cloud.githubusercontent.com/assets/16368087/25375186/7e895b80-29d2-11e7-97aa-9aebc3cf1273.png)
