### ISSUE TITLE
echarts自适应的具体设置问题

### ISSUE THREAD

**Issue by joriscai** [apache/incubator-echarts#4623]
#### One-line summary [问题简述]
请问echarts自适应的具体设置是怎样的？官网上一定要用jQuery的draggable插件，但是我所开发的项目不能用jQuery，这样要如何配置才能自适应，是不是只能设置style属性中的width/height才能触发自适应？我试过issue上的方法，监听resize事件并执行myCharts.resize()也是不能自适应

#### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.31
+ Browser version [浏览器类型和版本]:chrome 54
+ OS Version [操作系统类型和版本]: win7 64

#### Expected behaviour [期望结果]
我设置了低于768px的宽度，图形会变小，但是并没有改变

#### ECharts option [ECharts配置项]

```javascript
option = {
       baseOption: {
                series: [
                    {
                        name: name,
                        type: "pie",
                        radius: radius,
                        center : 'center',
                        hoverAnimation: false,
                        itemStyle: labelFromatter,
                        legendHoverLink: false,
                        label: {
                            normal: {
                                show: true,
                                position: 'bottom'
                            }
                        },
                        labelLine: {
                            normal: {
                                show: false
                            }
                        },
                        data: [
                            {value: data, name: name, itemStyle: labelTop},
                            {value: 100 - data, name: " ", itemStyle: labelBottom}
                        ]
                    }
                ],
                color: [color, '#2f4554']
            },
            media: [
                {
                    query: {
                        minWidth: 768
                    },
                    option: {
                        series: [
                            {
                                radius: [radius[0] - 20, radius[1] - 20],
                                center : 'center'
                            }
                        ]
                    }
                },
                {
                    option: {
                        series: [
                            {
                                radius: radius,
                                center : 'center'
                            }
                        ]
                    }
                }
            ]
}

```

#### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/17852005/20839918/626bb5d8-b8e9-11e6-868d-648153335460.png)
有监听resize并执行echarts[1].resize()

![image](https://cloud.githubusercontent.com/assets/17852005/20840007/bd39abe6-b8e9-11e6-846c-2ebbb1a5247e.png)

![image](https://cloud.githubusercontent.com/assets/17852005/20840031/d5b63e46-b8e9-11e6-9497-195d840f2c9a.png)

少于宽度并没有变化

**Comment by pissang** [comment]
跟 jquery 什么的都没关系，在你容器大小的时候 echarts 没办法知道你的容器大小发生了改变，所以需要你调用一下 chart.resize() 方法根据最新的高宽调整画布

**Comment by joriscai** [comment]
@pissang 明白了，现在自适应问题也已经解决了，但是还有一个问题要询问一下。

鼠标悬浮在图上
![image](https://cloud.githubusercontent.com/assets/17852005/20865667/65bf9ed2-ba53-11e6-9c74-deddcf88ec2b.png)

鼠标未悬浮时：
![image](https://cloud.githubusercontent.com/assets/17852005/20865670/825c08f0-ba53-11e6-916c-24ea855f912e.png)

鼠标悬浮在上面，图的颜色已经被加亮了，现在我想设置关掉这个加亮的功能。
我有试过给图设置颜色可以关掉这个功能，但是每个图都要加上对应的颜色，有没有一种设置方法能够统一关掉的呢？
