### ISSUE TITLE
地图组件是否可以直接显示地名与数值，如何使用地图文件中的ID值

### ISSUE THREAD

**Issue by earthpea** [apache/incubator-echarts#4624]
#### One-line summary [问题简述]
近期开始使用地图组件，在使用过程中发现有几个问题，搜索后一直没找到解决方案，只能求助开发团队及各位应用高手。
1、在地图上是否可能直接显示地名与数值：当前地图中仅能够显示出地名，需把鼠标移到某个行政区划上，才会在tooltip上显示出该地区的相关value，是否有哪种方法可以直接tooltip的格式如"{b}：<br />完成率{c}%"直接显示在地图上呢？这样的话较为直观，而且也方便用户有时截图做PPT等。我搜索过一些方法，有一种说可以使用nameMap方式来映射，但因为数据都是从后端ajax过来的，这样还传来的参数就有些难于处理。此外，在省级地图上直接显示到县级数据时，又是否可以不在地区上显示name呢？以免地图太烦杂。
2、查看下载到的地图数据(js和json文件)，对地区的描述，除了name之外，还有一个id值，现阶段是使用居民身份证地区码，我们的系统中对不同的地区也有相应编码，但与标准地区码又有所区别，我想了解一下，现在我只找到使用name值对应数据，是否可以使用地图数据中的id值来进行对应，这样的话可能会更方便一些。

#### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]:chrome 42+
+ OS Version [操作系统类型和版本]:win7/win10/win2008
#### Expected behaviour [期望结果]
1、能找到一种方法，可以在地图上显示地名、指定值或什么也不显示；
2、如何使用地图数据文件中的id来处理或映射后端ajax返回的数据。

#### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by zds-xiaoxianyu** [comment]
好好看官方demo，你会发现惊喜的！！！

**Comment by MisterChangRay** [comment]
楼主现在解决了吗？ 如何访问到文件中的ID值
