### ISSUE TITLE
Echarts3 tooltip 层级问题

### ISSUE THREAD

**Issue by baizn** [apache/incubator-echarts#4627]
### One-line summary [问题简述]
使用echarts绘制地图后，在地图上面动态绘制了一些柱子，如下图：
![image](https://cloud.githubusercontent.com/assets/9443867/20871968/a978c090-bad5-11e6-9095-73ccb2d4fb7e.png)

tooltip被绘制的柱子覆盖了，如何设置 这个层级关系，分别设置了z，zlevel，动态绘制柱子的z-index，extraCssText里面设置z-index等方法，都不起作用。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts3.0
+ Browser version [浏览器类型和版本]: chrome52
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]

tooltip在最上层。

### ECharts option [ECharts配置项]

```javascript
option = {
trigger: 'item',
                                    extraCssText: 'z-index: 10000; opacity: 1; box-shadow: 0 0 3px rgba(0, 0, 0, 0.3);',
                                    z: 100,
                                    textStyle:{
                                        color:"#fff",
                                        fontSize:"50"
                                    },
                                    backgroundColor:"#002864",
}

```

**Comment by pissang** [comment]
你这个柱子是怎么画的？

**Comment by baizn** [comment]
就是一个div，绝对定位上去的。
