### ISSUE TITLE
多个y轴不能全部放大缩小，只能放大缩小第一个y轴

### ISSUE THREAD

**Issue by kasion** [apache/incubator-echarts#4629]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer:{type:'line'},

    },
    legend: {
        data:['邮件营销','联盟广告']
    },
    toolbox: {
        
        feature: {
            restore:{},
            saveAsImage: {},
            dataZoom:{
            show : true,
            title : {
                zoom :'放大',
                back : '缩小'
            }
        }
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        },{
            type : 'value'
        }
        
    ],
    series : [
        {
            name:'邮件营销',
            yAxisIndex:0,
            type:'line',
            stack: '总量',
       
            data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'联盟广告',
            yAxisIndex:1,
            type:'line',
            stack: '总量',
           
            data:[220, 182, 191, 234, 290, 330, 310]
        }
        
    ]
};

**Comment by Ovilia** [comment]
把代码放到这里吧：http://gallery.echartsjs.com/editor.html

**Comment by Lion2017** [comment]
我也发现有这个问题，只能缩放最后一条曲线。
在上面例子中我试了下设置dataZoom.yAxisIndex = [0,1]，还是只能缩放一条曲线，不能同时缩放两条...
Ovilia哥，什么时候解决一下。

**Comment by Ovilia** [comment]
在 [Gallery](http://gallery.echartsjs.com/editor.html?c=xSJZVtMXIg) 上复现了一下，麻烦 @100pah 看一下~

**Comment by yihengli** [comment]
最新版本库中bug应该还是存在，yAxisIndex单独设置为0或者1，可以在对应index上生效，但设置为list [0,1]后无法对两根纵坐标同时生效
