### ISSUE TITLE
toolbox不显示

### ISSUE THREAD

**Issue by pzljp** [apache/incubator-echarts#4633]
### One-line summary [问题简述]
     同样的配置，在gallery里可以显示toolbox，在本地就不可以显示。是不是宽度不够就不显示？还是图标的背景是白色给隐藏了。调试了很长时间都没出来。toolbox会有什么限制吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3= echarts 3
+ Browser version [浏览器类型和版本]:   hybrid应用
+ OS Version [操作系统类型和版本]:   

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by binbinles** [comment]
toolbox: {
		            show: true,
		            feature: {
		            	restore: {},
		                saveAsImage: {
			                    show:true,
			                    excludeComponents :['toolbox'],
			                    pixelRatio: 2,
			                    type:['png'],
			                    title:['保存']
		                	}
            		}
		}


我是这样调用的，不知道你可不可以诶。你改一下相关参数吧

**Comment by chenmoxi** [comment]
你可能引入是定制后的 echarts.min.js (刚好还不包含toolbox)
