### ISSUE TITLE
avalon路由页面后，echarts3 渲染中断

### ISSUE THREAD

**Issue by jwRock** [apache/incubator-echarts#4636]
### One-line summary [问题简述]
通过avalon框架路由单页面，跳转路径后ajax请求数据并setOption渲染页面，打断点看到数据正常获取，渲染方法也正常进行，但在容器中添加div后就中断了，没有添加canvas等内容，延时很长时间执行也不行，但是通过click，change等事件ajax获取数据就可以正常显示。全程无报错。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts 3.3.2
Chrome 54
firefox 50
Win7 / Win10

### Expected behaviour [期望结果]

正常显示图表

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by YYtianqiong** [comment]
楼主，解决没，我也遇到这问题了
