### ISSUE TITLE
Downsample data in long timeseries chart

### ISSUE THREAD

**Issue by akansal1** [apache/incubator-echarts#4639]
I want to dynamically down sample data for long time window for a time series chart. For example, if I am plotting month long duration of data, at the month level, I would like to down sample hourly interval data to day level, but when duration is 48 hours, I would like to stretch it back to normal hourly scale dynamically

Is it possible to achieve in current structure ?

**Comment by akansal1** [comment]
There is sampling option in line chart, are you gonna extend it to other charts like k-line or Bar

**Comment by gkemp94** [comment]
+1 on sampling for bars.

**Comment by pchaganti** [comment]
👍
