### ISSUE TITLE
如何实现两条折线之间颜色填充

### ISSUE THREAD

**Issue by hanbinggan** [apache/incubator-echarts#4643]
### One-line summary [问题简述]

如何实现两条折线之间颜色填充，目前的解决方案是 第一条的数据 areaStyle 填充颜色，第二条数据 areaStyle 填充白色，透明度选项（opacity） 为 1 覆盖掉，但是，负数情况无法打到想要的效果。 

### Expected behaviour [期望结果]

实现两条折线之间颜色填充

### ECharts option [ECharts配置项]
```js
option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['最小值','最大值']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'最小值',
            type:'line',
          //  stack: '总量',
            areaStyle: {normal: {}},
            data:[320, 332, 301, -40, -30, 330, 320]
        },
        {
            name:'最大值',
            type:'line',
         //   stack: '总量',
            label: {
                normal: {
                    show: true
                }
            },
            areaStyle: {normal: {
                color:'#ffffff',
                opacity:1
            }},
            data:[10, 30, 40, -60, -50, 40, 50]
        }
    ]
};

```

**Comment by theSouthSea** [comment]
同问！

**Comment by LiTieTa** [comment]
#6770

**Comment by qfan** [comment]
确实，用opacity砍脚只能在非负数范围内用。负数就不行了。

http://gallery.echartsjs.com/editor.html?c=xSkgxEPmuf&v=1

http://gallery.echartsjs.com/editor.html?c=xSkgxEPmuf&v=2

**Comment by coldJson** [comment]
同问，急求解决方案！

**Comment by guo897654050** [comment]
现在解决了吗，同问

**Comment by hcldadi** [comment]
两年多了都没解决吗？
highChart就有的功能。。https://www.hcharts.cn/demo/highcharts/arearange

**Comment by gugu2012** [comment]
同问

**Comment by songjinlin123** [comment]
> 两年多了都没解决吗？
> highChart就有的功能.. https://www.hcharts.cn/demo/highcharts/arearange

highcharts可以实现两个legend么？

**Comment by songjinlin123** [comment]
> 两年多了都没解决吗？
> highChart就有的功能.. https://www.hcharts.cn/demo/highcharts/arearange

这样子效果highchart可以实现两个legend吗？

**Comment by hyZhang0701** [comment]
> 如果是都是正数，A在B上边填充一个颜色，B在A上边填充另一个颜色，能实现吗？🤕
> 当然肯定是要求和0轴之间没有颜色的

同有这个需求

**Comment by zqy233** [comment]
`option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['最小值','最大值']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'最小值',
            type:'line',
          //  stack: '总量',
             areaStyle: {normal: {
                color:'#8DA2E4',
                opacity:1,
                origin:"start"
            }},
            data:[320, 332, 301, -40, -30, 330, 320]
        },
        {
            name:'最大值',
            type:'line',
         //   stack: '总量',
            label: {
                normal: {
                    show: true
                }
            },
            areaStyle: { 
                color:'#ffffff',
                opacity:1,
                origin:"start"
            },
            data:[10, 30, 40, -60, -50, 40, 50]
        }
    ]
};
`

**Comment by zqy233** [comment]
```
option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['最小值','最大值']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'最小值',
            type:'line',
          //  stack: '总量',
            areaStyle: {normal: {}},
            data:[320, 332, 301, -40, -30, 330, 320]
        },
        {
            name:'最大值',
            type:'line',
         //   stack: '总量',
            label: {
                normal: {
                    show: true
                }
            },
            areaStyle: {normal: {
                color:'#ffffff',
                opacity:1
            }},
            data:[10, 30, 40, -60, -50, 40, 50]
        }
    ]
};
```

**Comment by jockiller** [comment]
这个问题为什么关了？是解决了吗

**Comment by wzc11227** [comment]
我强行用了个笨办法， 把要填充的区域首尾相连，画一个多边形，逻辑需要自己处理

**Comment by andyFang94** [comment]
看样子要自己画了.....

**Comment by jinHua-96** [comment]
<img width="970" alt="image" src="https://github.com/user-attachments/assets/c38b8f9a-c320-4654-a9d6-50c5d508d3c7">
这个颜色怎么填充啊
