### ISSUE TITLE
地图上省份汉字的字体大小和颜色

### ISSUE THREAD

**Issue by KobeJayChou** [apache/incubator-echarts#4648]
您好,首先感谢你们帮我解答了地图汉字位置问题,还有个问题想问的是如何改变地图上省份汉字的大小和颜色,在文档中没有找到。
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-map.label.normal.textStyle

**Comment by cxkobe** [comment]
您好,这种写法是不是不支持扩展地图？我的是扩展地图 ，这样写没有效果
label:{
                normal:{
                textStyle:{
                color:'#FFFFFF',
                fontSize:12
                }
                },
                emphasis:{
                textStyle:{
                color:'#FFFFFF',
                fontSize:12
                }
                }
                }

**Comment by pissang** [comment]
echarts 什么版本？http://gallery.echartsjs.com/ 上贴个例子？

**Comment by wangyano0** [comment]
你好，我想请问一下，如何在迁徙地图上显示起点城市的名字呢
