### ISSUE TITLE
移动端上echarts图表的tooltip超出手机屏幕

### ISSUE THREAD

**Issue by pzljp** [apache/incubator-echarts#4650]
### One-line summary [问题简述]
在手机页面上用echarts，tooltip的trigger是axis。每次点击tooltip都是在axis的左边或右边。由于tooltip比较宽，tooltip会超出手机屏幕，而并不是往中间挤。怎么设置？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
移动端上echarts图标的tooltip超出手机屏幕

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能截个图看下么？
