### ISSUE TITLE
堆叠的柱状图，需要将数据显示到每个柱子的top位置，现在的现象就是两个柱子堆叠的时候，下边那个柱子的数据被遮挡。如何使其不被遮挡，或者可以使得数据显示在最上边按柱子堆叠的顺序显示。

### ISSUE THREAD

**Issue by wuxia510** [apache/incubator-echarts#4652]
### One-line summary [问题简述]
堆叠柱状图的时候每个柱子上都要显示对应数据，现在是下边的柱子的数据被上边的柱子遮挡，其实我们要实现的效果就是两个柱子堆叠显示，且每个柱子的数据又能看见。一个柱子是显示数值的，另一个柱子显示百分比，要求y轴显示的数值。

现在问题是1、如何再柱子堆叠的时候不遮挡柱子上的数据  2、如何让另一个柱子显示百分比？且y轴保持显示数值。找过那个formater  ，没达到效果。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wuxia510** [comment]
现在显示百分比解决了，还有那个堆叠柱状图的时候，数据遮挡问题还没找到解决方法，还有一个问题就是数据和柱子现在感觉是挨得太近了，能不能设置间距的，数值和柱子顶部有点距离？

**Comment by pissang** [comment]
数据和柱子之间可以通过 `label.normal.distance` 设置距离

**Comment by wuxia510** [comment]
谢谢你的回复！你的建议已经采纳了。          我们想让柱子堆叠显示，然后数值 显示在柱子上方，现在就是下边的柱子的数据被上边的柱子遮挡住了，有什么好的解决方案吗？ 还有一个现象是数值显示到x轴下边了，跟x轴标签重叠了，有的数据会这样，不是所有的数据。这个有什么建议吗？

**Comment by pissang** [comment]
下面的柱子建议 `position` 设成 `'inside'`
