### ISSUE TITLE
如何在柱状图给最大值和最小值设置不同的颜色

### ISSUE THREAD

**Issue by angelfreedomv** [apache/incubator-echarts#4667]
### One-line summary [问题简述]

比如在标签itemStyle里面设置type
设置itemStyle{
      normal{
    type:'max',
    color:'red'
}
}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Winodws10

### Expected behaviour [期望结果]

期望柱状图最大值颜色为红色，最小值颜色为绿色，平均值颜色为蓝色

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lichenbuliren** [comment]
楼主找到解决方案了吗
