### ISSUE TITLE
bar图在用相同stack叠加时的严重问题

### ISSUE THREAD

**Issue by jiufengdadi** [apache/incubator-echarts#4679]
### One-line summary [问题简述]
###bar图的叠加
==========
如果对series里面的数据进行操作后，比如data.shift();
这时最后一个类目的图形会重叠在一起，不会叠加，前面去掉的地方会悬空

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome54&&例子中能够重现，实际项目遇到
+ OS Version [操作系统类型和版本]:
win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 发个一个能够复现的例子？

**Comment by jiufengdadi** [comment]
http://gallery.echartsjs.com/editor.html?c=xSy7reoiQg&v=1

**Comment by jiufengdadi** [comment]
把中间的数据空掉后，期望是空掉的地方图形应该挨着xAXis，实际情况是空掉的地方悬空了，而在尾部有相应长度的项重叠在一起了

**Comment by jiufengdadi** [comment]
在数据视图中可以发现，数据并没有因为被处理而自动填充空位，而是将数据从两边或者上下整体平移，这样做好像不太合理
