### ISSUE TITLE
Y轴名称如何和Y轴标签对齐？

### ISSUE THREAD

**Issue by cqcn1991** [apache/incubator-echarts#4686]
比如这样
![qq 2](https://cloud.githubusercontent.com/assets/2425141/21100910/70dc2312-c0b1-11e6-8ebb-8c16e0895142.png)

但我用Echarts只能做到这样，左边好像是多出来的
![qq](https://cloud.githubusercontent.com/assets/2425141/21100896/60a43160-c0b1-11e6-940a-30845079598c.png)

**Comment by pissang** [comment]
```js
grid: {
    containLabel: true,
    left: 0
},
title: {
    left: 0
}
```

**Comment by cqcn1991** [comment]
@pissang 这个不是title, 是axis下面的name

**Comment by pissang** [comment]
哦那就不行了=   =
