### ISSUE TITLE
echarts3 扩展svg的问题？echart3 怎么扩展svg?

### ISSUE THREAD

**Issue by KevinDeveloper** [apache/incubator-echarts#4693]
### One-line summary [问题简述]

echart3 怎么扩展svg?
什么地方有官方的 echarts3扩展 svg 地图的示例?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lixuejiang** [comment]
我也想知道，似乎echarts暂时不支持svg了，想知道echarts2是怎么实现扩展svg的

**Comment by KevinDeveloper** [comment]
可以尝试，将svg转换为geojson,
地址：https://github.com/yuhonyon/svg2geojson

**Comment by Ovilia** [comment]
嗨，我们目前正在打算支持 ECharts SVG 渲染，如果各位有具体的应用场景（在什么样的场景下，会偏向选择 SVG 而非 Canvas 渲染），欢迎告诉我们以帮助我们更好地实现这一特性~

**Comment by gaoxiaoyulinjie** [comment]
希望echarts团队能尽快做出来，我们拭目以待，加油大神们！！

**Comment by zzm3145** [comment]
我们有类似需求，我来反馈一下应用场景：
1. 项目没有外网连接，无法使用baidu或者mapbox之类的服务。
2. echarts给的地图太简单，尤其是县级地图只有一个轮廓。所以选择从Maperitive导出一个SVG地图。

也尝试了用QGIS导出OSM，从shp格式再转geojson。但是从OSM弄来下的shp格式也是太粗略了。

**Comment by Ovilia** [comment]
@zzm3145 了解，后期会增加对 SVG 地图的支持，谢谢反馈！

**Comment by lixuejiang** [comment]
@Ovilia 我们会有一些地图是从autocad导出来的，然后转成svg的场景
