### ISSUE TITLE
设置tooltip后地图不能全屏加载

### ISSUE THREAD

**Issue by shawneezhao** [apache/incubator-echarts#4697]
![_20161214104237](https://cloud.githubusercontent.com/assets/13099488/21167819/1567b142-c1ea-11e6-84e9-8542bdc81529.png)

### One-line summary [问题简述]
原地图加载是在界面全屏展示的，加上tooltip参数之后，地图无法全屏展示，只能在下半部展示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:谷歌浏览器
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
希望使用tooltip后依旧可以使地图全屏加载

### ECharts option [ECharts配置项]

```javascript
option = {
}

```

**Comment by pissang** [comment]
可以检查下 css
