### ISSUE TITLE
markLine.label 无法设置字号

### ISSUE THREAD

**Issue by ShirlyKong** [apache/incubator-echarts#4709]
### One-line summary [问题简述]
在坐标轴的label项可以设置字号，为什么markLine.label、markPoint.label不能设置字号？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jingxiawl** [comment]
label:{
      normal:{
             textStyle: {
                   olor: '#fff',
                   fontStyle: 'normal',
                   fontSize: 11
             }
      }
 },
