### ISSUE TITLE
IE8最大值tooltip显示不全

### ISSUE THREAD

**Issue by elelvenliu** [apache/incubator-echarts#4715]
IE8，echarts2.0
如图，给曲线加了markpoint，max值的tooltip显示不全，貌似被遮住了，有什么办法让它显示全么？
![Uploading image.png…]()

**Comment by elelvenliu** [comment]
![image](https://cloud.githubusercontent.com/assets/10057093/21257284/3ac08bac-c3b2-11e6-8f14-18e9b9bb97ac.png)

**Comment by qiudaoermu** [comment]
为什么不用，3.0

**Comment by elelvenliu** [comment]
3.0不支持IE8，项目要支持IE8。。。说多了都是泪
