### ISSUE TITLE
我发现这个echarts的k线与折现配合，滑动起来好流畅，怎么做到的？

### ISSUE THREAD

**Issue by sin911** [apache/incubator-echarts#4721]
我发现移动端上的echarts如果手指在图表上滑动，会很卡，但是我今天突然看到这个网页(请在手机上访问)
http://stgy.upchinapro.com/mobilepredict/predict.html?market=SH&code=600000&name=%25E6%25B5%25A6%25E5%258F%2591%25E9%2593%25B6%25E8%25A1%258C
位于该网页下方的echarts图表，k线与折现是可以左右滑动的，而且超级流畅。求教是怎么做到的呢？是他自己重新优化了移动端echarts的性能？

如下图所示
http://ww2.sinaimg.cn/large/9ed5c127gw1favwhyctk2j20yi1pcgy3.jpg

**Comment by 100pah** [comment]
你的 echarts 版本是啥？3.3.2 之前的版本确实有些不流畅的情况

**Comment by pissang** [comment]
问下是哪个例子在移动端上滑动会很卡？

**Comment by sin911** [comment]
@100pah 我的应该比3.3.2早的，echart3.0一出来我就用的。改明我换最新的试试。
@pissang http://echarts.baidu.com/demo.html#area-stack 比如这个，手指滑动的时候就会不流畅的。表现为滑动时，tootips显示的时候时断时续。是因为tooltip的地方用了动画的原因吗？
如图http://ww3.sinaimg.cn/large/9ed5c127gw1fawfyvk6ilj20yi1pcn31.jpg

**Comment by sin911** [comment]
@pissang 另外还有一个问题就是如图http://ww2.sinaimg.cn/large/9ed5c127gw1favwhyctk2j20yi1pcgy3.jpg
它这个拖动图表的空白区域，为什么就可以“缩放”，显示不同区域的数据呢？

**Comment by pissang** [comment]
@sin911 嗯那个并不是卡顿，echarts 3 也支持拖拽的滑动缩放，见 http://echarts.baidu.com/gallery/editor.html?c=area-rainfall 这个例子

**Comment by sin911** [comment]
@pissang 多谢这个例子http://echarts.baidu.com/gallery/editor.html?c=area-rainfall
然后我发现一个不同的细节，就是上述这个例子，当手指在屏幕上滑动时，将会把整个数据进行滑动，而不是显示当前屏幕的数据。
因为理想状态是：手指在数据的空白区域滑动才会进行“缩放”，在数据上滑动则显示tooltip
然后我发现配置文档里有dataZoome里有“filterMode”参数，是要设置这个东西吗？

**Comment by Kinka** [comment]
@sin911 http://stgy.upchinapro.com/mobilepredict/predict.html?market=SH&code=600000&name=%25E6%25B5%25A6%25E5%258F%2591%25E9%2593%25B6%25E8%25A1%258C 你所说的这个例子, 并看不出是使用echarts的? echarts 官网的例子在移动终端上拖动的时候是仍然是卡顿的.
