### ISSUE TITLE
陕西省西安市的地图没有杨凌区

### ISSUE THREAD

**Issue by jelon521** [apache/incubator-echarts#4733]
### One-line summary [问题简述]

陕西省西安市的地图没有杨凌区

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:火狐
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以在 http://ecomfe.github.io/echarts-map-tool/ 构建最新的地图

**Comment by shyray** [comment]
杨陵区不属于西安市
