### ISSUE TITLE
legend自定义图例为图片时高度控制

### ISSUE THREAD

**Issue by MrChanLi2013** [apache/incubator-echarts#4739]
### One-line summary [问题简述]

我的legend图例其中一个图例用的是图片，但**itemHeight=15**，这时候所有的图例都收到了这个高度的控制。
请问怎么可以让我使用图片的那一个图例单独设置一个itemHeight？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

**Comment by zhangsanmu** [comment]
同求，我也想知道这个结果
