### ISSUE TITLE
力导图拖拽问题

### ISSUE THREAD

**Issue by ChangingFond** [apache/incubator-echarts#4749]
### One-line summary [问题简述]

力导向图，假如我拖拽了一个节点到某个位置，放开鼠标能否让节点停留在拖拽完成的位置，不让它自动弹回去

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Windows 10

**Comment by itDjango** [comment]
3.0 应该不支持这个吧

**Comment by stillsilly** [comment]
同问……    这个问题后来解决了吗

**Comment by jasperjiang0204** [comment]
想了好久了都没找到答案。。解决了吗
