### ISSUE TITLE
Click event area

### ISSUE THREAD

**Issue by frzgianluca** [apache/incubator-echarts#4763]
### One-line summary [问题简述]

On a line chart I could not find any option to customize the area of the click.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3
+ Browser version [浏览器类型和版本]: chrome, explorer
+ OS Version [操作系统类型和版本]: windows, centos

### Expected behaviour [期望结果]

There should be an option to click on the area around a value, instead of on the exact spot. Points are often too small and the click can be too difficult.

### Other comments [其他信息]
![expected-behaviur](https://cloud.githubusercontent.com/assets/12997891/21434112/14687206-c873-11e6-8695-3f99fb52a78d.png)

**Comment by waitinghope** [comment]
+1.
Especially on stacked chart.

**Comment by hkongm** [comment]
+1

**Comment by berserk5683** [comment]
+1

**Comment by dfonnegra** [comment]
+1

**Comment by hengwangm** [comment]
also +1
