### ISSUE TITLE
echarts3 扩展地图 卡顿

### ISSUE THREAD

**Issue by luoam** [apache/incubator-echarts#4775]
### One-line summary [问题简述]

hello ,我用echars扩展地图做了一个应用，其中地图的geojson是由img矢量化得到的，geojson文件大小约9M，目前出现的问题是在鼠标拖动地图或者放大缩小地图的时候显得非常的卡顿，甚至出现浏览器崩溃的情况，请问官方有没有好的优化办法？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echart 3
+ Browser version [浏览器类型和版本]:ie9,firefox
+ OS Version [操作系统类型和版本]:centos,windows7

### Expected behaviour [期望结果]

找到让扩展地图流畅起来的方法

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
什么版本的 echarts

**Comment by luoam** [comment]
从官网下载的完整版556KB

**Comment by pissang** [comment]
3.几的版本

**Comment by luoam** [comment]
echarts 是最新的 3.3.2。


[f29b4544e01e9e04bd9d14132aa43324.json.zip](https://github.com/ecomfe/echarts/files/672680/f29b4544e01e9e04bd9d14132aa43324.json.zip)

**Comment by luoam** [comment]
我在网站http://mapshaper.org/ 上发现同样的json文件，这个网站就显的流畅许多。

**Comment by pissang** [comment]
刚看了下太卡的原因不是因为点太多，而是因为里面的 feature 太多，因为 echarts 需要去管理这些 feature 以及由这些 feature 创建的图形（比如判断鼠标的 hover 状态以及数据的映射等等），并不是简单的绘制出来，所以卡顿很难避免，mapshaper 的网站绘制部分只需要画出来就行了，所以会很流畅。

所以建议把这么多 feature 合并成少数几个。

**Comment by luoam** [comment]
好的，谢谢， 我试着根据你的建议去调整一下json。
如果echarts能够做成创建这些图形的时候耗费更少的资源，那就更好了。
