### ISSUE TITLE
tooltip的position在使用回调函数时，rect参数的值始终为null

### ISSUE THREAD

**Issue by wangguangis** [apache/incubator-echarts#4780]
### One-line summary [问题简述]
在使用tooltip的position进行定位时，如果使用回调函数，不论鼠标是否在图形上，rect参数的值始终为null

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.2
+ Browser version [浏览器类型和版本]:55.0.2883.75 (64-bit)
+ OS Version [操作系统类型和版本]:windows 10 pro

### Expected behaviour [期望结果]
得到非空的rect参数

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        confine: true,
        axisPointer : {
            type : 'line',
            lineStyle : {
                color: '#4488bb',
                width: 2,
                opacity: 1
            }
        },
        textStyle: {
            fontSize: 12
        },
        position: function (point, params, dom, rect) {
            return [point[0] + 10, '20%'];
            if (rect == null) {
                return [point[0] + 10, '20%'];
            } else {
                console.log(rect);
            }
        }
    }
}

```

**Comment by pissang** [comment]
rect 是图形的 rect，如果 tooltip 触发的时候鼠标没在相应的图形上（比如 trigger 是 axis 的时候），就不会有这个 rect
