### ISSUE TITLE
我想在地图上的高速路上标示出名字，除了bmap还有背的办法吗？

### ISSUE THREAD

**Issue by hezhongfeng** [apache/incubator-echarts#4785]
我的需求是这样的
例如：
长春市有几条高速路
我想在高速上标示出名字和此时的路况，一些文字或者是颜色（深浅表示数值的大小）
想离线使用，百度地图2.0版必须在线
不是用bmap还有别的办法吗

**Comment by pissang** [comment]
你可以试一下用 lines 组件
