### ISSUE TITLE
面积堆积图在数据缺失即“-”情况下，无法正确绘制图形

### ISSUE THREAD

**Issue by Nick-Xu** [apache/incubator-echarts#4792]
### One-line summary [问题简述]
面积堆积图在数据缺失即“-”情况下，无法正确绘制图形

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.1
+ Browser version [浏览器类型和版本]:Chrome
+ OS Version [操作系统类型和版本]:Win 7

### Expected behaviour [期望结果]
能够按照规则正确显示图形

### ECharts option [ECharts配置项]

```javascript
option = {
    "color":[
        "#48bd9b",
        "#f6c143",
        "#dd5f6c",
        "#6694e7",
        "#89c652",
        "#f39652",
        "#69b9c1",
        "#7151ba",
        "#e16a55",
        "#d3a063",
        "#378083",
        "#a960e8",
        "#3ab2bc",
        "#b18250",
        "#ed9974",
        "#71a443",
        "#e3d051",
        "#d75fe5",
        "#5367b4",
        "#377368"
    ],
    "title":{
        "show":false,
        "text":"吸金趋势监控"
    },
    "legend":{
        "show":false,
        "data":[
            "直播视频",
            "电影",
            "电视剧",
            "纪录片",
            "动漫",
            "音乐",
            "综艺",
            "娱乐",
            "教育",
            "少儿",
            "微电影"
        ]
    },
    "grid":{
        "show":false,
        "top":35,
        "left":60,
        "right":60,
        "bottom":75
    },
    "xAxis":[
        {
            "type":"category",
            "data":[
                "2016-12-15",
                "2016-12-16",
                "2016-12-17",
                "2016-12-18",
                "2016-12-19",
                "2016-12-20",
                "2016-12-21",
                "2016-12-22",
                "2016-12-23",
                "2016-12-24",
                "2016-12-25"
            ],
            "boundaryGap":false,
            "axisLine":{
                "show":true
            },
            "axisTick":{
                "show":false
            },
            "splitLine":{
                "show":false
            }
        }
    ],
    "yAxis":[
        {
            "type":"value",
            "axisLine":{
                "show":true
            },
            "axisTick":{
                "show":false
            },
            "splitLine":{
                "show":false
            },
            "splitArea":{
                "show":false
            },
            "axisLabel":{
                "formatter":"{value} %"
            },
            "max":100
        }
    ],
    "tooltip":{
        "show":true,
        "trigger":"axis"
    },
    "series":[
        {
            "name":"直播视频",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.0",
                "-",
                "0.0",
                "-",
                "0.05",
                "0.0",
                "0.0",
                "0.49",
                "0.08"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"电影",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "79.03",
                "80.69",
                "82.45",
                "82.15",
                "82.63",
                "79.07",
                "79.91",
                "81.92",
                "81.54"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"电视剧",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "19.61",
                "17.53",
                "15.84",
                "15.14",
                "14.9",
                "18.18",
                "18.1",
                "15.88",
                "15.63"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"纪录片",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.26",
                "0.3",
                "0.26",
                "0.27",
                "0.29",
                "0.22",
                "0.23",
                "0.29",
                "0.33"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"动漫",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.59",
                "0.49",
                "0.46",
                "0.47",
                "0.51",
                "1.42",
                "0.95",
                "0.69",
                "0.52"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"音乐",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.12",
                "0.12",
                "0.12",
                "0.15",
                "0.21",
                "0.28",
                "0.15",
                "0.22",
                "0.73"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"综艺",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.38",
                "0.87",
                "0.86",
                "0.73",
                "0.6",
                "0.57",
                "0.48",
                "0.42",
                "1.09"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"娱乐",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.01",
                "0.0",
                "0.0",
                "0.0",
                "0.0"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"教育",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.0",
                "0.0",
                "-",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"少儿",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.02",
                "0.02",
                "0.02",
                "0.02",
                "0.02"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        },
        {
            "name":"微电影",
            "type":"line",
            "stack":"trendData",
            "data":[
                "-",
                "-",
                "-",
                "-",
                "-",
                "1.08",
                "0.79",
                "0.24",
                "0.17",
                "0.07",
                "0.05"
            ],
            "areaStyle":{
                "normal":{
                    "opacity":1
                }
            }
        }
    ]
};
```

### Other comments [其他信息]

![Uploading image.png…]()
@pissang @kener @100pah

**Comment by Nick-Xu** [comment]
![image](https://cloud.githubusercontent.com/assets/8415190/21483352/a7c14460-cbbb-11e6-8f6e-8fd47d70c9db.png)

**Comment by pissang** [comment]
这个是正常的，你期望的结果是什么？

**Comment by Nick-Xu** [comment]
将选项option修改为ECharts 2版本后，展示的是正确的图形，因此怀疑是EChart3引入的缺陷。
option = {
    "color":[
        "#48bd9b",
        "#f6c143",
        "#dd5f6c",
        "#6694e7",
        "#89c652",
        "#f39652",
        "#69b9c1",
        "#7151ba",
        "#e16a55",
        "#d3a063",
        "#378083",
        "#a960e8",
        "#3ab2bc",
        "#b18250",
        "#ed9974",
        "#71a443",
        "#e3d051",
        "#d75fe5",
        "#5367b4",
        "#377368"
    ],
    "title":{
        "show":false,
        "text":"吸金趋势监控"
    },
    "legend":{
        "show":false,
        "data":[
            "直播视频",
            "电影",
            "电视剧",
            "纪录片",
            "动漫",
            "音乐",
            "综艺",
            "娱乐",
            "教育",
            "少儿",
            "微电影"
        ]
    },
    "grid":{
        "show":false,
        "top":35,
        "left":60,
        "right":60,
        "bottom":75
    },
    "xAxis":[
        {
            "type":"category",
            "data":[
                "2016-12-15",
                "2016-12-16",
                "2016-12-17",
                "2016-12-18",
                "2016-12-19",
                "2016-12-20",
                "2016-12-21",
                "2016-12-22",
                "2016-12-23",
                "2016-12-24",
                "2016-12-25"
            ],
            "boundaryGap":false,
            "axisLine":{
                "show":true
            },
            "axisTick":{
                "show":false
            },
            "splitLine":{
                "show":false
            }
        }
    ],
    "yAxis":[
        {
            "type":"value",
            "axisLine":{
                "show":true
            },
            "axisTick":{
                "show":false
            },
            "splitLine":{
                "show":false
            },
            "splitArea":{
                "show":false
            },
            "axisLabel":{
                "formatter":"{value} %"
            },
            "max":100
        }
    ],
    "tooltip":{
        "show":true,
        "trigger":"axis"
    },
    "series":[
        {
            "name":"直播视频",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.0",
                "-",
                "0.0",
                "-",
                "0.05",
                "0.0",
                "0.0",
                "0.49",
                "0.08"
            ]
        },
        {
            "name":"电影",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "79.03",
                "80.69",
                "82.45",
                "82.15",
                "82.63",
                "79.07",
                "79.91",
                "81.92",
                "81.54"
            ]
        },
        {
            "name":"电视剧",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "19.61",
                "17.53",
                "15.84",
                "15.14",
                "14.9",
                "18.18",
                "18.1",
                "15.88",
                "15.63"
            ]
        },
        {
            "name":"纪录片",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.26",
                "0.3",
                "0.26",
                "0.27",
                "0.29",
                "0.22",
                "0.23",
                "0.29",
                "0.33"
            ]
        },
        {
            "name":"动漫",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.59",
                "0.49",
                "0.46",
                "0.47",
                "0.51",
                "1.42",
                "0.95",
                "0.69",
                "0.52"
            ]
        },
        {
            "name":"音乐",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.12",
                "0.12",
                "0.12",
                "0.15",
                "0.21",
                "0.28",
                "0.15",
                "0.22",
                "0.73"
            ]
        },
        {
            "name":"综艺",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.38",
                "0.87",
                "0.86",
                "0.73",
                "0.6",
                "0.57",
                "0.48",
                "0.42",
                "1.09"
            ]
        },
        {
            "name":"娱乐",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.01",
                "0.0",
                "0.0",
                "0.0",
                "0.0"
            ]
        },
        {
            "name":"教育",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.0",
                "0.0",
                "-",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0"
            ]
        },
        {
            "name":"少儿",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.02",
                "0.02",
                "0.02",
                "0.02",
                "0.02"
            ]
        },
        {
            "name":"微电影",
            "type":"line",
            "stack":"trendData",
          	"itemStyle": {"normal": {"areaStyle": {"type": "default"}}},
            "data":[
                "-",
                "-",
                "-",
                "-",
                "-",
                "1.08",
                "0.79",
                "0.24",
                "0.17",
                "0.07",
                "0.05"
            ]
        }
    ]
};

![image](https://cloud.githubusercontent.com/assets/8415190/21549315/63bf3b1e-ce2c-11e6-96d2-26c9cb45d681.png)
