### ISSUE TITLE
echarts3的X轴设置为time，series在没有数据的情况下照样会显示数据，貌似取的是它附近的值。

### ISSUE THREAD

**Issue by amei1234** [apache/incubator-echarts#4809]
### One-line summary [问题简述]

echarts3的X轴设置为time，series在没有数据的情况下照样会显示数据，貌似取的是它附近的值。
比如，series的时序数据只有少数几个点，然而鼠标放上去后，提示框里面，每个时刻series都有数值。
如果series是根据时间动态生成的，那么，当前时刻以后的数据还未生成，那么不应该显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts3
+ Browser version [浏览器类型和版本]:Chrome,版本50.0.2661.102m
+ OS Version [操作系统类型和版本]:windows 7

### Expected behaviour [期望结果]

没有数据的时刻不显示数据，不应该取它附近的值作为替代。

### ECharts option [ECharts配置项]

```javascript
option = {
xAxis:{type:'time'}


}

```

**Comment by wllxxxy** [comment]
x轴为时间轴时,X轴的刻度可以自定义吗,我想把一年的时间的自定义显示 譬如 2016-1-1,2016-2-1,2016-3-1,2016-4-1,2016-5-1,2016-6-1,2016-7-1,2016-8-1,2016-9-1,2016-10-1,-2016-11-1,2016-12-1 2016-12-31 也就是说时间显示的都是当年的每月的第一天
