### ISSUE TITLE
ecchart3.0版本当设置x轴为time类型时,X轴以年为维度,X轴分割成12份,刻度显示不能均匀分割,但是2.0可以,是咋回事

### ISSUE THREAD

**Issue by wllxxxy** [apache/incubator-echarts#4810]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 贴个例子？

**Comment by wllxxxy** [comment]
http://gallery.echartsjs.com/editor.html?c=xSyS2aefHl&comment=0主要是这个X轴的问题,简单的例子我贴出来了,echarts3.0版本的 @pissang

**Comment by wllxxxy** [comment]
2.0版本这样写是可以做到刻度分割一年的,不过3.0 传的事时间戳,有点变化
 xAxis : [
                    {
                        splitLine: {
                            show: true
                        },
                        type : 'time',
                        min:new Date(lineYear,0,1),
                        max:new Date(lineYear,12,0),
                        splitNumber:12,
                        axisLine: {show: false}
                    }
                ],

**Comment by pissang** [comment]
如果是固定的要按月统计的话，还是建议用类目轴，时间轴更多的是用来给一个连续的时间范围，我们自动帮你分割刻度

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/wiki/ECharts-2-%E5%8D%87%E7%BA%A7%E5%88%B0-ECharts-3-%E7%9A%84%E6%94%B9%E5%8A%A8
