### ISSUE TITLE
缩放后，柱形图y轴label变得模糊

### ISSUE THREAD

**Issue by benben198805** [apache/incubator-echarts#4813]
### One-line summary [问题简述]
1.使用eachrt绘制柱形图，放大200%后y轴label变得模糊。
2.其次，放大200%后，柱形图的柱子边缘也变得模糊。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.1
+ Browser version [浏览器类型和版本]: chrome 55, ie 11
+ OS Version [操作系统类型和版本]: win 7

### Expected behaviour [期望结果]
放大后，字体和柱子的边缘依然能够清晰。

### ECharts option [ECharts配置项]

```javascript
option = {
    ...,
    yAxis: [
        {
            type: 'category',
            data: newValue.labels,
            axisLabel: {
                interval: 0,
                formatter: function (item) {
                    return item.length > 10 ? item.substring(0, 9) + '…' : item;
                },
                textStyle: {
                    color: fontColor,
                    fontSize: '10px'
                }
            },
            axisLine: {
                lineStyle: {
                    color: lineColor
                }
            },
            axisTick: {
                lineStyle: {
                    color: lineColor
                }
            },
            splitLine: {
                show: false
            }
        }
    ],
    ...
}

```

### Other comments [其他信息]

[ie-100%](http://7xpyct.com1.z0.glb.clouddn.com/old-ie.png)
[ie-200%](http://7xpyct.com1.z0.glb.clouddn.com/old-ie-200.png)
[chrome-100%](http://7xpyct.com1.z0.glb.clouddn.com/old-chrome.png)
[chrome-200%](http://7xpyct.com1.z0.glb.clouddn.com/old-chrome-200.png)

**Comment by pissang** [comment]
你可以缩放后再调用一下 resize 试试

**Comment by benben198805** [comment]
@pissang 缩放后，resize效果不明显

**Comment by yizhengfeng-jj** [comment]
你好这个问题后来解决了么
