### ISSUE TITLE
雷达图 脱离 0

### ISSUE THREAD

**Issue by icssjs** [apache/incubator-echarts#4828]
### One-line summary [问题简述]

雷达图 的scale 好像没效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
嗯雷达图暂时不支持

**Comment by icssjs** [comment]
有解决的办法吗，这样子，两个差值小的时候，雷达图几乎没有意义
