### ISSUE TITLE
关于 #4014  折线图在time轴时，如果某些时间点没有数据，但是tooltip触发为X轴触发时的问题

### ISSUE THREAD

**Issue by amei1234** [apache/incubator-echarts#4830]
### One-line summary [问题简述]

关于 #4014  折线图在time轴时，如果某些时间点没有数据，但是tooltip触发为X轴触发时的问题
的一些解决方案的疑问。

我打算用formatter去解决，计划用横轴的时间和各条线的时间做比较，和横轴时间一致的线条就显示数值，不一致的就不显示。但是不知道如何获取横轴的时间。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts 3 
+ Browser version [浏览器类型和版本]: c hrome
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

期望可以获取横轴的时间，用以比较横轴时间与series数据的时间。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by peterchealse** [comment]
同样的问题

**Comment by nachao** [comment]
同求

**Comment by peterchealse** [comment]
官方已经解决了

**Comment by startMinsk** [comment]
@peterchealse 请问官方在哪儿解决的

**Comment by amei1234** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发的邮件我已成功收到~我会尽快给您回复的~~谢谢^_^
