### ISSUE TITLE
如何实现鼠标滑过某个图表时多个图表标线同步移动

### ISSUE THREAD

**Issue by zfcheng** [apache/incubator-echarts#4832]
### One-line summary [问题简述]
如图 实现功能： 鼠标在图表一种移动时会有标线，希望在其他图标上对应位置显示相应表现

![image](https://cloud.githubusercontent.com/assets/7411450/21577285/a1c536ba-cf90-11e6-9d49-196190f35d14.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]:mac

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echarts.connect

**Comment by zfczoe** [comment]
多谢指导
