### ISSUE TITLE
分割线(splitLine)设置为点线(dotted)时，可以设置点之间的间隔吗？

### ISSUE THREAD

**Issue by panguofeng10** [apache/incubator-echarts#4847]
### One-line summary [问题简述]
如标题
分割线(splitLine)设置为点线(dotted)时，可以设置dotted中各点之间的间隔吗？默认的点之间的间隔太小了。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.2
+ Browser version [浏览器类型和版本]:Chrome 55.0.2883.95
+ OS Version [操作系统类型和版本]:MAC OS

### Expected behaviour [期望结果]
![2017-01-03 4 53 16](https://cloud.githubusercontent.com/assets/17584474/21603157/0264ffae-d1d6-11e6-8733-c14f45ee978a.png)

### ECharts option [ECharts配置项]

                   yAxis: [{
                        axisLine: {
                            show: false
                        },
                        axisTick: {
                            show: false
                        },
                        splitLine: {
                            show: true,
                            lineStyle: {
                                color: ['#979797'],
                                type: 'dotted'
                            }
                        },
                        type: 'value'
                    }],

**Comment by pissang** [comment]
暂时不行
