### ISSUE TITLE
visualMap的inRange属性 只设置colorLightness不设置color页面报错

### ISSUE THREAD

**Issue by yuanyuli** [apache/incubator-echarts#4851]
### One-line summary [问题简述]
visualMap的inRange属性 只设置colorLightness不设置color页面报错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
echarts": "^3.3.2"
+ Browser version [浏览器类型和版本]:
chrome 54.0.2840.87 (64-bit)
+ OS Version [操作系统类型和版本]:
macOS Sierra 10.22

### Expected behaviour [期望结果]
不设置color并不报错

### ECharts option [ECharts配置项]

```javascript
option = {
visualMap: {
        type: 'continuous',
        dimension: 1,
        min: 0,
        max: 1.5,
        text: ['High', 'Low'],
        calculable: true,
        inRange: {
            colorLightness: [0.9, 0.4]
          },
}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 贴个例子？
