### ISSUE TITLE
[feature] Support barBorderRadius on the polar bar chart

### ISSUE THREAD

**Issue by chenxia123** [apache/incubator-echarts#4856]
### One-line summary [问题简述]

想给环形图进度条两端设置圆角，但是好像只有柱状图有barBorderRadius属性。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![image](https://cloud.githubusercontent.com/assets/22878190/21632838/08900108-d285-11e6-93bd-d8fb7eaef798.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不支持，后面可能会推出单独的环形图扩展

**Comment by LeonDWong** [comment]
请问现在支持了吗？

**Comment by confidence68** [comment]
我实现了一下，请看地址：http://www.haorooms.com/post/canvas_yuanjiaohuanx

**Comment by wangmeijian** [comment]
@confidence68 你这个跟echarts没关系

**Comment by zlpcrmm** [comment]
请问现在支持了吗？

**Comment by pandashuai** [comment]
同问

**Comment by Ovilia** [comment]
和 #9085 相似，都需要扇形图支持圆角。既然要求都人多，这个需求就高优支持一下。

**Comment by zlpcrmm** [comment]
@Ovilia 请问现在支持了吗？啥情况了呀

**Comment by Ovilia** [comment]
@cuijian-dexter 是的，需要 zrender 扇形支持圆角。这个需求会高优一下。

**Comment by AaronAlphabet** [comment]
强烈要求或者需求 这个功能的实现，或者单独出一个圆环的type吧，因为用graphic或者custom的时候，入场动画啥的都不好弄

**Comment by zlpcrmm** [comment]
@AaronAlphabet 强烈支持。

**Comment by pandashuai** [comment]
现在还没支持？

**Comment by 100pah** [comment]
@Ovilia  @AaronAlphabet  在 polar bar 里面支持 

```js
itemStyle: {
    barBorderRadius: '50%'
}
```

能解决这个问题么？
（polar bar 是指的类似：<http://echarts.baidu.com/examples/editor.html?c=bar-polar-stack>）

**Comment by zlpcrmm** [comment]
仪表盘、环形能支持吗？楼上说的polar bar好像现在还不支持

**Comment by AaronAlphabet** [comment]
@100pah ,下面是我测试的option，你可以看看，应该是不支持，如果支持，请把你的option 贴一下，谢谢 ^_^，有时候很需要这个功能。
```
app.title = '极坐标系下的堆叠柱状图';

option = {
    angleAxis: {
    },
    radiusAxis: {
        type: 'category',
        data: ['周一', '周二', '周三', '周四'],
        z: 10
    },
    polar: {
    },
    series: [{
        type: 'bar',
        data: [1, 2, 3, 4],
        coordinateSystem: 'polar',
        name: 'A',
        itemStyle:{
            barBorderRadius:'50%'
        }
    }],
    legend: {
        show: true,
        data: ['A']
    }
};
```

**Comment by NickeyLin** [comment]
@Ovilia 请问现在支持了吗？

**Comment by Ovilia** [comment]
还没有，这个功能不是很好实现。

**Comment by Zinc925** [comment]
最近项目也用到了，然后用d3.js画圆形图+圆角很容易，难度是折线对应文字的实现

**Comment by eeve** [comment]
有任何进展？

**Comment by yfzhangCode** [comment]
同问有何进展吗?

**Comment by Richlee2016** [comment]
还没出吗？难受~这个能不能自己画个 canvas集成到ECharts里面~~

**Comment by yzqnf** [comment]
> 不支持，后面可能会推出单独的环形图扩展

什么时候推出环形图？？？

**Comment by zlpcrmm** [comment]
请问最近有进展吗？

**Comment by gaoqiang19514** [comment]
进展如何？

**Comment by tangdaohai** [comment]
> 进展如何？

@gaoqiang19514  #11393

**Comment by ben-wong** [comment]
还不支持吗？

**Comment by shinrabansyou** [comment]
换highcharts了，但是highcharts总感觉卡卡的😂

**Comment by grapetree** [comment]
额，还不支持啊

**Comment by Lykeios** [comment]
关心进度

**Comment by grapetree** [comment]
option = {
    title:{
        text:'hhh'
    },
    angleAxis: {
        max: 10,
        axisLine:{
            show:false
        },
        axisLabel:{
            show:false
        },
        splitLine:{
            show:false
        },
        axisTick:{
            show:false
        }
    },
    radiusAxis: {
        type: 'category',
        axisLine:{
            show:false
        }
    },
    polar: {
    },
    series: [{
        type: 'bar',
        data: [, , , 10],
        coordinateSystem: 'polar',
        roundCap: true,
        legendHoverLink: false,
        name: 'A',
        stack: 'a'
    }, {
        type: 'bar',
        data: [, , , 6],
        roundCap: true,
        legendHoverLink: false,
        coordinateSystem: 'polar',
        name: 'B',
        stack: 'a'
    }],
    legend: {
        show: true,
        data: ['A', 'B']
    }
};
可以试下

**Comment by kakercoco** [comment]
同求

**Comment by shinrabansyou** [comment]
你们楼上还在问的就不看下close的link的吗？
https://github.com/apache/incubator-echarts/pull/11393
请不要只做伸手党
