### ISSUE TITLE
在地图构建中下载下来的城市数据放到echarts中无法渲染，

### ISSUE THREAD

**Issue by since91** [apache/incubator-echarts#4858]
### One-line summary [问题简述]
从http://ecomfe.github.io/echarts-map-tool/上下载下来的地图数据在echarts3中，无法展示
有海南的三亚、四川的成都、云南的曲靖和辽宁的沈阳
操作步骤：
1.只选了省、市，没有勾选县
2.是否包含子区域 subregion（是）
3.是否压缩 compress（是和否都试过）
4.点击生成json按钮

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:chrome-57.0.2950.4 dev(64-bit)
+ OS Version [操作系统类型和版本]:win7 64-bit

### Expected behaviour [期望结果]
能够和杭州市一样，渲染出来

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
怎么放的？

**Comment by since91** [comment]
从网上将这几个城市的地图数据下载下来放到项目里，然后调用以下方法：
```
$.get(contextPath + '/s/common/js/geo/json/' + options.map + '.json', function (mapJson) {
            		echarts.registerMap(options.map, mapJson);
            		if(!$this.chart) {
            			$this.chart = echarts.init(document.getElementById(elemId));
            		}
            		
            		$this.chart.setOption(option,true);
            	});
```
其他城市的地图都能渲染，就这四个不行


对比其他地图的数据，发现这四个城市中，有些区域的coordinates和encodeOffsets是empty array，
怀疑是json数据有误

**Comment by pissang** [comment]
可能是因为这个原因，你注册前先处理下这个 geoJson 把这些空的区域去掉吧，我们后面优化这个问题
