### ISSUE TITLE
折线图 多条数据x轴不等如何显示

### ISSUE THREAD

**Issue by zfcheng** [apache/incubator-echarts#4864]
One-line summary [问题简述]
1、如图 折线图中多条线，但是数据点横坐标不对齐，有办法处理吗

![image](https://cloud.githubusercontent.com/assets/7411450/21648481/240bc27e-d2d9-11e6-8b71-fa19367f1313.png)

2、面积图 （堆叠）同样问题可否实现
如图数据横轴一样，如果每条线的数据x 轴不等，可否实现
![image](https://cloud.githubusercontent.com/assets/7411450/21648575/6d1f4472-d2d9-11e6-997c-aa64997b46da.png)

Version & Environment [版本及环境]

ECharts version [ECharts 版本]: 3.0
Browser version [浏览器类型和版本]: chrome
OS Version [操作系统类型和版本]:mac

**Comment by 100pah** [comment]
1. 可以实现
2. 堆叠就需要对齐了（可以尝试补齐）

**Comment by zfczoe** [comment]
@100pah   可以贴个例子吗 或者 相关 api

**Comment by Zhaokung** [comment]
@zfcheng   你做出来了么？ G2 组件有这个进行X轴对齐，x 轴上的数据不要求必须有点。线条会前后两个点 连接进行平滑
