### ISSUE TITLE
echarts在iphone6plus上的显示问题

### ISSUE THREAD

**Issue by aimaodeyuer** [apache/incubator-echarts#4874]
### One-line summary [问题简述]
移动端适配之后，在iphone 6 plus上图表的提示项显示，但是图表显示不出来

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.2
+ Browser version [浏览器类型和版本]:iphone6 plus上的各浏览器
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

能够渲染图表显示出来

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/12092562/21679633/08381aaa-d380-11e6-9abb-b016034fff99.png)

**Comment by 100pah** [comment]
提供的信息比较少，不好定位问题。option？

**Comment by aimaodeyuer** [comment]
{
                tooltip: {
                    formatter: "{a} <br/>{b} : {c} ({d}%)",
                    show: true,
                    trigger: "item",
                    textStyle: {
                        fontSize: 36,
                    }
                },
                legend: {
                    orient: "horizontal",
                    x: "center",
                    data:[
  {
    "name": "方便"
  },
  {
    "name": "副主任医师"
  },
  {
    "name": "高级专家"
  },
  {
    "name": "急诊"
  },
  {
    "name": "普通"
  },
  {
    "name": "晚夜间门诊"
  },
  {
    "name": "测试1"
  },
  {
    "name": "测试2"
  },
  {
    "name": "测试3"
  },
  {
    "name": "测试4"
  },
  {
    "name": "测试5"
  },
  {
    "name": "测试6"
  },
  {
    "name": "测试7"
  }
],
                    y: "bottom"
                    textStyle: {
                        fontSize: 36,
                    },
                },
                title: {
                    text: ''门诊挂号费别人次',
                    subtext: ‘合计23333人次’,
                    x: 'center',
                    y: 'top',
                    textStyle: {
                        fontSize: 54,
                    },
                    subtextStyle: {
                        fontSize: 36,
                    },
                },
                series: [
                    {
                        name: ‘’,
                        type: 'pie',
                        radius: ['35%', '60%'],
                        itemStyle: {
                            // fontSize: '2.4rem',
                            normal: {
                                label: {
                                    show: true,
                                    position: "outer",//inner
                                    formatter: "{c}",
                                    textStyle: {
                                        fontSize: 36,
                                    },
                                },
                                textStyle: {
                                    fontSize: 36,
                                },
                                labelLine: {
                                    show: true,
                                    fontSize: 36,
                                    lineStyle: {
                                        width: 3,
                                    },
                                }
                            },
                            emphasis: {
                                label: {
                                    show: false,
                                    formatter: "{c}"
                                },
                                labelLine: {
                                    show: false
                                }
                            }
                        },
                        data: [
  {
    "name": "方便",
    "value":"659"
  },
  {
    "name": "副主任医师",
    "value":"77"
  },
  {
    "name": "高级专家",
    "value":"88"
  },
  {
    "name": "急诊",
    "value":"56"
  },
  {
    "name": "普通",
    "value":"92"
  },
  {
    "name": "晚夜间门诊",
    "value":"2333"
  },
  {
    "name": "测试1",
    "value":"23"
  },
  {
    "name": "测试2",
    "value":"87"
  },
  {
    "name": "测试3",
    "value":"22"
  },
  {
    "name": "测试4",
    "value":"1000"
  },
  {
    "name": "测试5",
    "value":"32"
  },
  {
    "name": "测试6",
    "value":"221"
  },
  {
    "name": "测试7",
    "value":"123"
  }
]
                    }
                ],
                color: ["rgb(252, 128, 83)", "rgb(135, 206, 250)", "rgb(218, 112, 214)", "#32cd32", "#6495ed", "#ff69b4", "#ba55d3", "#cd5c5c", "#ffa500", "#40e0d0", "#1e90ff", "#ff6347", "#7b68ee", "#00fa9a", "#ffd700", "#6699FF", "#ff6666", "#3cb371", "#b8860b", "#30e0e0"]
            }

**Comment by aimaodeyuer** [comment]
@100pah option如上

**Comment by aimaodeyuer** [comment]
@100pah 我测试了下，我这边是因为高度影响的，给height8.5rem 在6plus上还能显示，超过了就不能显示了，显示的就是贴的图上的样子。1rem=100px

**Comment by aimaodeyuer** [comment]
@100pah 我先用的饼图测试的，在iphone6plus 微信浏览器打开 还经常出现闪退现象 ，我是用的tab页切换，会渲染出3个饼图。不过闪退不是一定出现的，不知道是不是echarts渲染的问题。

**Comment by dongguaqing** [comment]
@100pah 在微信公众号中，用echarts渲染了30个不同的饼图（测试其他的图也是会崩溃） 微信肯定奔溃，用了IOS10.2  微信6.3  Iphone6 plus，在Iphone6 中没重现这个问题

**Comment by dongguaqing** [comment]
@aimaodeyuer 你的echart在在iphone6plus 微信浏览器打开 还经常出现闪退现象 问题解决了吗 解决了告诉我下 怎么解决的

**Comment by dangduang** [comment]
你好，这个问题解决了吗？

**Comment by yangzhenyin** [comment]
同问,我这边的问题也是这样,当多个 echart 图在 苹果6P上展示的时候,有时候会出现一直重复渲染的问题,客户端给的原因是因为WKWebView占用内存过高导致的,不知道怎么怎么解决?
