### ISSUE TITLE
如何绘制sparkline

### ISSUE THREAD

**Issue by tcllib** [apache/incubator-echarts#4890]
### One-line summary [问题简述]

我希望做一个 sparkline，类似于缩略图的东西，没有x轴y轴。在试用echarts时我将div的高度设为20px，但是line chart没有显示完全。如何能在高度为20px的div中绘制折线图？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.2
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows 10

### Expected behaviour [[期望结果]]
类似sparkline的效果，sparkline为一种独特的图表分类，具体效果可参考此[jquery插件](http://omnipotent.net/jquery.sparkline/#s-about)

### ECharts option [ECharts配置项]

```javascript
option = {
  toolbox: {
    show: false,
  },
  xAxis: [{
    show: false,
    type: 'category',
    data: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
  }],
  yAxis: [{
    show: false,
    type: 'value',
  }],
  calculable: true,
  tooltip: {
    trigger: 'axis',
    formatter: "{b}时 : {c}次"
  },
  series: [{
      name: 'test1',
      type: 'line',
      connectNulls: false,
      itemStyle: {
        normal: {
          lineStyle: {
            shadowColor: 'rgba(0,0,0,0.4)'
          }
        }
      },
      data: [0, 0, 0, 0, 0, 0, 14, 3, 0, null, null]
    },

    {
      name: 'test1',
      type: 'scatter',
      data: [0, 0, 0, 0, 0, 0, '-', '-', '-', '-'],
      itemStyle: {
        normal: {
          color: 'grey',
          opacity: '1'
        }

      }

    }
  ]
};

```

### Other comments [其他信息]

关于我的问题请参考此[jsFiddle实例](https://jsfiddle.net/strpv8ae/1/)

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=line-easing 参考这个例子，需要设置 grid 的定位

**Comment by mycaule** [comment]
你好，

这里有一个代码示例。看我对这个问题的回答。
https://github.com/ecomfe/echarts/issues/5228
