### ISSUE TITLE
5W个地图点位时，会变得很卡，请问有优化配置么

### ISSUE THREAD

**Issue by since91** [apache/incubator-echarts#4898]
5W个地图点位时，浏览器会变得很卡

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]:echarts 3
+ Browser version [浏览器类型和版本]:chrome 54
+ OS Version [操作系统类型和版本]: win7 64bit

### Expected behaviour [期望结果]
估计未来有50W个点，希望到这个数量时，浏览器也不卡

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by voidsteed** [comment]
你可以在series 里面加一个large：true, 这个选项会对大规模散点进行优化, 我自己的程序里显示40W个点毫无压力

`option = {
  series: [
    {large: true}
  ]
}`

具体可以参照这个官方示例:

[http://echarts.baidu.com/gallery/editor.html?c=scatter-weibo](url)

**Comment by since91** [comment]
找到原因了，是将这些字符串，打印出来，导致慢，现已解决

**Comment by midu-liuzhaoping** [comment]
> 找到原因了，是将这些字符串，打印出来，导致慢，现已解决

怎么解决的呀
