### ISSUE TITLE
x轴类型为time时，鼠标移动时，触发series上的symbol问题

### ISSUE THREAD

**Issue by amei1234** [apache/incubator-echarts#4904]
### One-line summary [问题简述]

当xAxis的type为time时，将横轴放大到最细的刻度，鼠标移动时，symbol会被触发，但和指示器的线不在一条线上。如官方示例中，我将刻度轴放大到以天为单位，当鼠标放置在某一天的刻度前后，都能触发symbol，即使鼠标移动时的指示器线不在symbol的那个位置上。如何实现像xAxis为category时，无论刻度轴如何放大，鼠标移动时有吸附symbol的效果呢，使指示器的线和symbol中心点在一条纵线上？
![image](https://cloud.githubusercontent.com/assets/24807099/21839944/920afce0-d815-11e6-8282-aa1a5266578e.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts 3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

当xAxis的type为time时，鼠标移动时，指示器的线对symbol有吸附效果。和x轴为category时的效果一样，鼠标移动时的指示器线都会在symbol中间。

### ECharts option [ECharts配置项]

function randomData() {
    now = new Date(+now + oneDay);
    value = value + Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
            Math.round(value)
        ]
    }
}

var data = [];
var now = +new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
    data.push(randomData());
}

option = {
    title: {
        text: '动态数据 + 时间坐标轴'
    },
    tooltip: {
        trigger: 'axis',
        formatter: function (params) {
            params = params[0];
            var date = new Date(params.name);
            return date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + params.value[1];
        },
        axisPointer: {
            animation: false
        }
    },
     toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            dataView: {readOnly: false},
            magicType: {type: ['line', 'bar']},
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'time',
        splitLine: {
            show: false
        }
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: '模拟数据',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data
    }]
};

setInterval(function () {

    for (var i = 0; i < 5; i++) {
        data.shift();
        data.push(randomData());
    }

    myChart.setOption({
        series: [{
            data: data
        }]
    });
}, 1000);

**Comment by nachao** [comment]
snap设置为false吸附效果仍然在，求原因？
