### ISSUE TITLE
获取dataZoom的准确的起始和结束位置的值

### ISSUE THREAD

**Issue by Cyycl** [apache/incubator-echarts#4906]
### One-line summary [问题简述]
现在echarts的dataZoomChange事件透传出来的参数中关于dataZoom的起始和结束的位置只有百分比的形式，没有办法做到计算出准确的起始和结束位置。
![image](https://cloud.githubusercontent.com/assets/9523185/21849423/ac461862-d840-11e6-92e9-2bb7da67af0f.png)

### Version & Environment [版本及环境]
ECharts version: 3.3.2

### Expected behaviour [期望结果]
希望可以获取dataZoom中准确的起始和结束位置的值，如下图
![image](https://cloud.githubusercontent.com/assets/9523185/21849423/ac461862-d840-11e6-92e9-2bb7da67af0f.png)

### ECharts option [ECharts配置项]
const dataZoom = [{
  type: 'inside',
  start: 0,
  end: 100
  }, {
    start: 0,
    end: 100,
    left: 140,
    right: 90,
    handleIcon: 'M10.7,11.9v-1.3H9.3v1.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4v1.3h1.3v-1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
    handleSize: '80%',
    handleStyle: {
        color: '#fff',
        shadowBlur: 3,
        shadowColor: 'rgba(0, 0, 0, 0.6)',
        shadowOffsetX: 2,
        shadowOffsetY: 2
    }
}];

**Comment by 100pah** [comment]
可使用 `chart.getOption().dataZoom` 可以得到 `startValue` 和 `endValue`。

后续会也把它加到事件的参数中。

**Comment by jiaqing-gu** [comment]
请问这个问题解决了吗 datazoom事件还是没法获得startValue 和 endValue
vue-echarts: ^4.0.3

**Comment by linxiaowu66** [comment]
2023年了还没有加进去呢？

**Comment by k644606347** [comment]
> 可使用 `chart.getOption().dataZoom` 可以得到 `startValue` 和 `endValue`。
> 
> 后续会也把它加到事件的参数中。

666，找了很久，原来通过getOption就能获取，的确是加个事件更容易让人想到
