### ISSUE TITLE
如何实现在同一个echart图表下，实现K线图与柱形图联动

### ISSUE THREAD

**Issue by xiaoma0105** [apache/incubator-echarts#4917]
### One-line summary [问题简述]
目前connect方法可以实现不同echart图表下的联动，但是同一个echart图表却没有找到相对应的功能。

### Expected behaviour [期望结果]
在同一个echart下实现类似connect方法的联动效果

### Other comments [其他信息]

http://echarts.baidu.com/demo.html#candlestick-brush

**Comment by 100pah** [comment]
<http://echarts.baidu.com/demo.html#candlestick-brush>
这是同一图表。不过 tooltip 的联动需要改进一下。

**Comment by xiaoma0105** [comment]
怎么改？

**Comment by BryanLee0202** [comment]
通过datazoom设置xAxisIndex 可以将三个grid联动
