### ISSUE TITLE
面积图补全

### ISSUE THREAD

**Issue by zfcheng** [apache/incubator-echarts#4920]
![image](https://cloud.githubusercontent.com/assets/7411450/21890682/d05c491e-d909-11e6-9b84-4d496dba4fba.png)

例如这种情况 如何补全？

**Comment by pissang** [comment]
横坐标是时间的不建议用堆叠，堆叠是根据数据的顺序来的

**Comment by zfczoe** [comment]
@pissang 您的意思是说 堆叠的话上面线的数据要比下面线的数据大？
