### ISSUE TITLE
yaxis' minInterval setting does not work as expected

### ISSUE THREAD

**Issue by alperyazgan** [apache/incubator-echarts#4934]
As shown below  yAxis' minInterval is set to 1 but axis still shows fractional number labels like 0.2 / 0.4 ...  or 0 / 0.5 / 1.5 / 2.0 / 2.5 when the data range is small, for example min = 0, max = 6 
      
PS. There is no real number in the data set they are all natural numbers and the chart type is bar.

 yAxis : [{
          type        : 'value',
          show        : true,
          name        : 'smth',
          boundaryGap : ['0%', '10%'],
          minInterval : 1,
          axisLine    : {
            show      : true,
            onZero    : true,
            lineStyle : {
              type  : 'solid',
              color : 'rgba(0, 92, 145, 1)'
            }
          },
          min         : 0
        }],

**Comment by alperyazgan** [comment]
For reference, it was working perfectly with early versions of  3.2.x

**Comment by mtamburrano** [comment]
any updates on this? I still having same problem with a `line` type chart and no real values in the dataset
