### ISSUE TITLE
能不能为饼图中被选中的扇形设置额外样式？

### ISSUE THREAD

**Issue by lqm229026** [apache/incubator-echarts#4956]
### One-line summary [问题简述]
在饼图中，默认的选中效果是该扇形以一定的offset离开圆心。但是在下图中，比较不容易看出到底是选中了哪个部分。

![image](https://cloud.githubusercontent.com/assets/15317435/22020775/fd7fd548-dcf4-11e6-8a5f-578b83713946.png)

有没有办法为选中的扇形设置额外的样式来增强直观感受？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4
+ Browser version [浏览器类型和版本]: chrome54
+ OS Version [操作系统类型和版本]:win7

**Comment by IrisZhang** [comment]
饼图可以用 `roseType: 'angle'`
`
 series : [
        {
            name: '访问来源',
            type: 'pie',
            radius : '55%',
            selectedMode: 'single',
            center: ['50%', '60%'],
            roseType: 'angle',
            data:[
                {value:335, name:'直接访问',selected:true},
                {value:310, name:'邮件营销'},
             
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
`

**Comment by lqm229026** [comment]
使用roseType只能通过角度、半径或者面积来表示数据大小或者占比吧？但是我想要的效果是当一个区域被selected时，能够有额外的效果，比如放大或者加框加阴影之类的。好像使用roseType没法做到？
我尝试了您给的配置，当然我把value都改成了310，效果是这样的
![image](https://cloud.githubusercontent.com/assets/15317435/22189742/760b448a-e159-11e6-8bab-905a294cc99f.png)
这样也还是没有办法明显区分到底谁被选中了。

**Comment by mangoZT** [comment]
itemstyle属性进行设置  例如边框，阴影等  勉强可以满足你的效果

**Comment by Xujkstra** [comment]
+1， 希望可以独立设置selected时的样式

**Comment by coderLuow** [comment]
同问，想在扇形区域被选择后，设置一个新的颜色已示意被选中，如何设置？
