### ISSUE TITLE
Stacking with option to re-scale data in relative values

### ISSUE THREAD

**Issue by akansal1** [apache/incubator-echarts#4961]
### One-line summary [问题简述]

Currently Stacking only stacks absolute values by adding them. I wanted to know, if there is a possibility to have stacking in relative form (% or ratio) 

Useful to have comparative representation

**Comment by 100pah** [comment]
I've not understood the meaning of "stacking in relative form (% or ratio)". Could you please supply some examples or detailed explanation?

**Comment by akansal1** [comment]
You can refer to the following stacking example from NVD3 

http://nvd3.org/examples/stackedArea.html

**Comment by 100pah** [comment]
Think you for your example. Although `Expanded` can also be configured by transform data to percent value manually in echarts, it is not convenient. We will think this through.

**Comment by akansal1** [comment]
Thanks, I do not know how to make it configurable via **toolbox**. But, it will definitely be a nice feature addition
