### ISSUE TITLE
关于tooltip的show为false的理解，有没有替代方案

### ISSUE THREAD

**Issue by gitranxu** [apache/incubator-echarts#4962]
### One-line summary [问题简述]
在tooltip中设置show为false的意思是希望有这个tooltip,只不过是一开始的状态是隐藏的，而不是压根就没有这个tooltip的意思。

手机端柱线图，我们打算实现这样的场景，单击时显示tooltip(默认是不显示的)，双击时隐藏tooltip同时显示我们自己定义的一个弹出窗口。现在遇到的问题是，如果一开始tooltip的show设为false的话，后面就不能通过myChart.dispatchAction({ type: 'showTip'});将其显示出来，请问这个问题怎样解决？（如果一开始tooltip的show设为true的话，即使隐藏用户也会看到先显示再隐藏的过程，体验很不好）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:     3.3.1
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
期望实现这样的结果，一开始tooltip是不显示的，鼠标移入也不自动显示，只有用户发生点击事件才会显示。

### ECharts option [ECharts配置项]

```javascript

var myChart = echarts.init(document.getElementById('main'));

		        // 指定图表的配置项和数据
		        var option = {
		            title: {
		                text: 'ECharts 入门示例'
		            },
		            tooltip: {
		            	show: false,
		            	formatter: '<div class="test">{b0}: {c0}<br />{b1}: {c1}</div>'
		            },
		            legend: {
		                data:['销量']
		            },
		            xAxis: {
		                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
		            },
		            yAxis: {},
		            series: [{
		                name: '销量',
		                type: 'bar',
		                data: [5, 20, 36, 10, 10, 20]
		            }]
		        };

		        myChart.setOption(option);
		        myChart.dispatchAction({
						     type: 'showTip'
						 });

```

**Comment by 100pah** [comment]
既然要自定义 `tooltip` 的显示隐藏策略，那么可以设置：
`tooltip.triggerOn: 'none'`，然后在单机和双击的时候 `dispatchAction` 来显示和隐藏 tooltip.

**Comment by gitranxu** [comment]
var option = {
		            title: {
		                text: 'ECharts 入门示例'
		            },
		            tooltip: {
		            	show: true,
		            	triggerOn:'none'
		            },
		            legend: {
		                data:['销量']
		            },
		            xAxis: {
		                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
		            },
		            yAxis: {},
		            series: [{
		                name: '销量',
		                type: 'bar',
		                data: [5, 20, 36, 10, 10, 20]
		            }]
		        };

		        

		        // 使用刚指定的配置项和数据显示图表。
		        myChart.setOption(option);

		        myChart.on('click', function (params) {
		        	console.log('111112333');
				    myChart.dispatchAction({
						     type: 'showTip'
						 });
				});
这样设置后，还是不能显示tooltip，求教是怎么回事儿？能加一下QQ么610944015

**Comment by sevenen** [comment]
myChart.on('click', function (params) {
     var index = params.dataIndex;
     myChart.dispatchAction({
			type: 'showTip',
			seriesIndex:0,
			dataIndex:index
			});
});
