### ISSUE TITLE
Hide zero value record

### ISSUE THREAD

**Issue by srikaranp** [apache/incubator-echarts#4968]
Hi,

Please see the picture i want to hide zero value record. If any possible?

Thanks in advance
![2017-01-19_114247](https://cloud.githubusercontent.com/assets/25217346/22095648/8e81cc2a-de3c-11e6-8998-f3c81028d038.png)

**Comment by 100pah** [comment]
I think you can try <https://ecomfe.github.io/echarts-doc/public/en/option.html#series-bar.label.normal.formatter>, where you can use callback function to `return '';` for zero value.

**Comment by JeffreyRoosendaal** [comment]
When setting the series data, you can use:

	{
		value: (yourValue || '-')
	}

So it sets the value when it's not zero or undefined, and otherwise it sets a `-`, which will *not* be shown as a label.

**Comment by arslan-butt** [comment]
The question is old but if someone is looking for a better solution use this

``` 
 label: {
       show: true, 
       formatter: function(param) {
          return param.data == 0 ? '': param.data;
        }
      }
