### ISSUE TITLE
[改进意见]饼图某个区域面积太小，区域名字inner显示方式重叠

### ISSUE THREAD

**Issue by DeeeFOX** [apache/incubator-echarts#4974]
### One-line summary [问题简述]
* 产生场景  
当饼图存在连续多个区域面积较小的块时出现

* 问题描述
在连续小块区域内，用inner方式显示的区域名字会重叠在一起

* 问题补充
有的人建议用outer方式显示，但是我所用的图是环形内嵌的，类似于这样：

        ——————————
        |   ——    |
        |  |   |  |
        |  |___|  |
        ——————————
    内环是不适用与outer的，但是使用inner就会出现重叠的问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Win7

### Expected behaviour [期望结果]
* 增加选项根据饼图区域面积决定是否显示区域名字

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以利用 http://echarts.baidu.com/option.html#series-pie.label.normal.formatter 当数值小的时候，不显示标签
