### ISSUE TITLE
legend 设置高度不好使 

### ISSUE THREAD

**Issue by zfcheng** [apache/incubator-echarts#4977]
![image](https://cloud.githubusercontent.com/assets/7411450/22130784/7d77871e-dee9-11e6-92c5-5feb9a56126c.png)
如图 legend .设置高度不生效 why?

**Comment by 100pah** [comment]
水平布局的 legend 不能设置高度。
legend 内容过多，高度设小了也容纳不下。

**Comment by zfczoe** [comment]
@100pah   竟然不支持水平设置高度，这是为什么呢？

**Comment by pissang** [comment]
你期望支持设置高度后有怎么样的结果？

**Comment by zfczoe** [comment]
@pissang  图例水平布局，固定高度不变可以接受，目前是设置没有作用； 

可不可以支持自适应，例如min-height 这样，限定最小高度，超出时可以自适应，避免图例覆盖图表

**Comment by zfczoe** [comment]
@pissang    这个问题现在很棘手，产品需要自适应高度，想了解下，目前不支持高度自适应是怎么考虑的？

**Comment by wangx036** [comment]
legend过多遮挡图表的确是个棘手的问题，如果能像highchart一样图例分页显示就好了

**Comment by tanxuewei** [comment]
现在这个问题有解决方案了么

**Comment by 100pah** [comment]
下个版本中会增加『可收起的 legend』

**Comment by kyefe** [comment]
这个问题现在有解决办法了吗
![image](https://user-images.githubusercontent.com/38071042/49693322-5393b000-fbaa-11e8-8550-1b72917aebe0.png)
