### ISSUE TITLE
地图透明度设置无法改变border的透明度

### ISSUE THREAD

**Issue by pslean** [apache/incubator-echarts#4984]
### One-line summary [问题简述]

geo.itemStyle.nornal.opacity值改变了area的透明度，area的border透明度没改，但是整个地图的border透明度被更改了。

### Version & Environment [版本及环境]
+ECharts version：3.4.0
+Browser version：55.0.2883.87 m (64-bit)
+OS Version：windows10

### Expected behaviour [期望结果]

area的border的透明度一起被更改

### ECharts option [ECharts配置项]

```javascript
option = {
geo: {
        type: 'scatter',
        map: this.props.city,
        label: {
          emphasis: {
            show: false
          }
        },
        itemStyle: {
          normal: {
            color: '#004f80',
            borderColor: '#00eeff',
            opacity: 0.4,
            shadowColor: '#66deff',
            shadowBlur: 1
          },
          emphasis: {
            color: '#004f80',
            borderColor: '#00eeff',
            opacity: 0.4,
            shadowColor: '#66deff',
            shadowBlur: 1
          }
        },
        zoom: 1.1
      }
}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/22412030/22143785/4458b906-df36-11e6-909d-2c3c544612f4.png)

**Comment by 100pah** [comment]
可以先暂时 borderColor 使用如 `rgba(xx,xx,xx,0.3)` 来设置透明度

**Comment by pslean** [comment]
@100pah 这个不行，因为整个区域是有透明度的，颜色透明参数达不到我想要的效果，改了后的样子：
![image](https://cloud.githubusercontent.com/assets/22412030/22179451/2f10cea8-e08f-11e6-9322-f1ab81730441.png)

**Comment by pissang** [comment]
这个问题其实不是 border 的透明度没改，border的透明度也改掉了，但是因为区域之间的边框会覆盖加深，所以会造成“透明度没改”的错觉，而中国边界那些的border因为没有覆盖所以显示正确，这个问题我们暂时也没什么解决方案，只能是如果你原先要设 0.5 的不透明度，那么设得更小一点比如 0.25 试试
