### ISSUE TITLE
echarts中，legend的tooltip参数问题

### ISSUE THREAD

**Issue by chenxia123** [apache/incubator-echarts#4989]
### One-line summary [问题简述]
在echarts中，tooltip设置了一套参数，并且在legend的tooltip再次设置了另一套参数，但是只有show起作用，其他参数都没有任何反应？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
麻烦给出具体 option
