### ISSUE TITLE
Legend icon border not working in 3.x

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#4998]
In 2.x version, legend symbol used to reflect border settings:

![image](https://cloud.githubusercontent.com/assets/561365/22243606/5813b780-e228-11e6-9e66-3fe7c25b299a.png)

however, 3.x shows legend as color only: 

![image](https://cloud.githubusercontent.com/assets/561365/22243585/43fc8c86-e228-11e6-871b-2d1ee0c2d7d6.png)

Is there any way to set border width and color on the legend? 

Also, seems like legend data items are not documented in the docs, however it seems to be possible to change icon by 
```
legend:{
    data:[
         {
              name:legendLabel,
              icon:"rectangle"
         }
    ]
}
```

**Comment by sagarey** [comment]
+1
