### ISSUE TITLE
手机上滑动时与页面上下scroll或左右翻页冲突

### ISSUE THREAD

**Issue by peterz3g** [apache/incubator-echarts#5001]
版本3.0
在手机上测试

1，在折线图中，tooltip为mousemove触发，但是在左右移动过程中，会首先导致页面左右翻页。是否可以判断，如果是在图表中，就只是移动tooltip线，而不翻页。（测试机型iPhone6Plus）
2，在datazoom中，水平和垂直滑块条拖动的时候，会导致屏幕翻页或者屏幕上下scroll。
》如果是iPhone，可以双击滑块条再拖动，则页面不会移动，只拖放数据区域
》如果是安卓，无论是否双击滑块，都会导致页面移动，无法安心地查看数据。

备注：页面可以增加一些内容，使页面的上下scroll滚动条出现，在测试拖动上下datazoom滑块。

**Comment by starxiao** [comment]
这个问题解决了吗？？？？
