### ISSUE TITLE
canvas经过css3旋转90deg之后，响应触摸点有问题

### ISSUE THREAD

**Issue by semdy** [apache/incubator-echarts#5009]
canvas经过css3旋转90deg之后，鼠标响应坐标点pageX和pageY没有交换，导致响应触摸点有问题（PC环境下是对的，Mobile环境下有问题）

**Comment by pissang** [comment]
什么版本的 echarts

**Comment by semdy** [comment]
3.3.2

**Comment by semdy** [comment]
我强制交换clientX和clientY, 现在tooltip显示是对的，但是lengend的点击仍然有问题

**Comment by semdy** [comment]
`function defaultGetZrXY(el, e, out) {
        // This well-known method below does not support css transform.
        var box = getBoundingClientRect(el);
        var canvas = e.target;
        if( canvas.width % window.innerHeight == 0 ) {
          out.zrX = e.clientY - box.left;
          out.zrY = e.clientX - box.top;
        } else {
          out.zrX = e.clientX - box.left;
          out.zrY = e.clientY - box.top;
        }
    }`
改造后的代码

**Comment by semdy** [comment]
function defaultGetZrXY(el, e, out) {
        // This well-known method below does not support css transform.
        var box = getBoundingClientRect(el);
        var canvas = e.target;
        if( canvas.width % window.innerHeight == 0 ) {
          out.zrX = e.clientY - box.left;
          out.zrY = e.clientX - box.top;
        } else {
          out.zrX = e.clientX - box.left;
          out.zrY = e.clientY - box.top;
        }
    }
改造后代码

**Comment by godfrey-yin** [comment]
同样有这个需求，但旋转过来各种问题。

**Comment by guojingwen** [comment]
我也有这个需求求解

**Comment by yeyicheng** [comment]
同求

**Comment by hsay** [comment]
+1 ，同样遇到该问题, echarts的父元素旋转90度后，tooltip不能正常显示，legends也不能点击。在pc端没有该问题。话说echarts是不是已经不维护了？

**Comment by yeyicheng** [comment]
我把坐标系旋转后解决了。

**Comment by hsay** [comment]
@semdy 请问这个方法（defaultGetZrXY）是修改源代码还是？

**Comment by zhans1993** [comment]
@yeyicheng  能详细说一下您是怎么解决的么？

**Comment by semdy** [comment]
@hsay 是的

**Comment by cjzhang1230** [comment]
@yeyicheng 你是怎么旋转坐标系的，是改源码吗？

**Comment by yeyicheng** [comment]
@cjzhang1230 是的，我把代码贴给你，你参考一下。

`function defaultGetZrXY(el, e, out) {
    // This well-known method below does not support css transform.
    var box = getBoundingClientRect(el);
	
	var canvas = e.target;
	var orient = (window && window.orientation !== undefined)? window.orientation: screen.orientation.angle;
	var portrait = orient == 0 || orient == 180;

	function rotate_by_origin(x, y, ox, oy, angle) {
		var o = [];
		rotate(o, [-(oy - y), -(ox - x), 0, 0], angle * Math.PI / 180);
		return [ox + o[1], oy + o[0]];
	}	
		
	try {
		if((forceLandscape && portrait) || (forcePortrait && !portrait)) {
			var origin = Math.min($("#main").width(), $("#main").height()) / 2;
			var angle = portrait? -90: 90;
			
			var new_out = rotate_by_origin(e.clientX-box.left, e.clientY-box.top, origin, origin, angle);
			
			out.zrX = new_out[0];
			out.zrY = new_out[1];
		} else {
			out.zrX = e.clientX - box.left;
			out.zrY = e.clientY - box.top;
		}
	} catch (e) {
		alert(e);
	}
}`
