### ISSUE TITLE
echarts 动态特效问题

### ISSUE THREAD

**Issue by chenxia123** [apache/incubator-echarts#5013]
### One-line summary [问题简述]
![image](https://cloud.githubusercontent.com/assets/22878190/22617338/22073f76-eafd-11e6-8298-dba235eedbe5.png)
由图可见，横坐标有多个柱状图，每个柱状图都有一个对应的白色虚点动态效果。但是由于有十多个，所以要写十多遍以下代码吗？有没有什么简洁写法？
![image](https://cloud.githubusercontent.com/assets/22878190/22617531/a8c2d4bc-eb02-11e6-8876-9fefa219848b.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不用创建 10 个系列， lines 系列中有 10 组数据就行了
