### ISSUE TITLE
connect 设置联动，实现tooltip 不联动

### ISSUE THREAD

**Issue by zfcheng** [apache/incubator-echarts#5020]
使用 connect 设置联动，希望 tooltip 不联动 如何实现？

**Comment by pissang** [comment]
可以手动监听事件，判断事件类型然后 dispatchAction 给另外一个图表，

**Comment by zfczoe** [comment]
1、联动的图标比较多，6个-10+  而且数量是动态的，手动的话似乎没有办法处理，connect 应该是不行了吧？
2、connect 怎么没有设计成支持配置的？

**Comment by pissang** [comment]
1. 可以遍历解决
2. 可以考虑加上配置
