### ISSUE TITLE
折线图在重新设置数据后绘制错误

### ISSUE THREAD

**Issue by nekronhuang** [apache/incubator-echarts#5024]
### One-line summary [问题简述]
在重新setOption以后，折线图绘制错误，触发一次重绘以后，比如点一下图例，恢复正常。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.2.3 & 3.4.0（定位问题时也试验过最新的）
+ Browser version [浏览器类型和版本]: Chrome 55.0.2883.95
+ OS Version [操作系统类型和版本]: Mac OS 10.11.6

### Description [情况说明]
之前看到#4654，问题可能是有关联的。排查过程中找到了稳定复现的方式，排除了其他所有干扰项，做了最基本的示例如下：
* https://jsfiddle.net/nekron/t6drzxvj/
* https://github.com/nekronhuang/echarts-bugfix

试验时发现和数据量没有必然联系，目前发现和配置`dataZoom`、`animation`、`xAxis`有关。
* dataZoom配置start非0时，测试时只选取了10%的数据，测试了**5~15**，**50~60**，**90~100**均有bug，**0~10**正常
* animation关了以后正常
* xAxis的data如果不更新是正常的，只有数据导致x和y轴一起更新才会复现该bug

**Comment by MwumLi** [comment]
echarts 实例的 setOption 有一个选项 `notMerge `: 是否不跟之前设置的option进行合并，默认为false，即合并。
你可以试试把它设置为 `true` , 看能不能解决你的问题
具体文档见: <http://echarts.baidu.com/api.html#echartsInstance.setOption>

**Comment by nekronhuang** [comment]
@MwumLi 在jsfiddle上改了配置试验了下，并没有修复~

**Comment by nekronhuang** [comment]
#### 补充说明
我加一些截图来补充说明哈，当点击refresh按钮，会生成一份随机数据，这时候图像是绘制成这样~
![](https://zos.alipayobjects.com/rmsportal/hbATbIHGoyRjSFBUnigk.png)


然后，点击图例里的销量，相当于强制触发了一次重绘，就变成了这样~
![](https://zos.alipayobjects.com/rmsportal/IROYVgowzREsHTtylgbG.png)

之后再重绘都是和第二次结果一样了

**Comment by voidsteed** [comment]
我也遇到setOption的notMerge没有效果的问题。始终是merge数据 我用的是散点图。我的解决方案是getOption后，修改option中的series，然后chartInstance.clear()清除数据，最后setOption

**Comment by xuejingchi** [comment]
i just met an almost problem like this , did U know how to fix it?

**Comment by Panlq** [comment]
@voidsteed  done!  thanks
