### ISSUE TITLE
关于刻度的两个问题

### ISSUE THREAD

**Issue by erroristyun** [apache/incubator-echarts#5032]
### One-line summary [问题简述]

1、如何使 类目轴刻度的长度不一致？(如图的y轴:泊位长度能对应不同的桩位)
2、（第二个问题已解决）
![echarts](https://cloud.githubusercontent.com/assets/14174146/22724509/9c0bda8c-ee01-11e6-8378-338225dca759.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
不好意思没有太理解这句话的意思：
> 如何使 类目轴刻度的长度不一致？(如图的y轴:泊位长度能对应不同的桩位)
