### ISSUE TITLE
鼠标事件不触发

### ISSUE THREAD

**Issue by kuangyunsheng** [apache/incubator-echarts#5045]
我用的是echarts 3.4.0，不知为何鼠标事件不能触发。代码如下：

var myChart = echarts.init(document.getElementById('chart1'))

myChart .on('click', function () {
    console.log('click');
});

**Comment by pissang** [comment]
请具体描述你的环境和代码

**Comment by kuangyunsheng** [comment]
应该是我对文档的理解有误，我以为在图表的任意位置都会触发鼠标事件，但在我写的测试页面中，只有'series'会触发鼠标事件。

我重新看了一下文档，其中对鼠标事件有如下描述：```
    // 当前点击的图形元素所属的组件名称，
    // 其值如 'series'、'markLine'、'markPoint'、'timeLine' 等。
```
因为我的图表需要根据服务端发送的数据实时更新，同时用户有可能会对图表进行交互（例如缩放图表），为了不影响用户的交互，需要在用户交互开始时自动阻止图表的实时刷新，而交互完成后自动恢复实时刷新。例如我想在datazoom组件的mousedown事件中暂停实时刷新，然后在datazoom事件中恢复实时刷新。但在datazoom组件点击鼠标时并不会触发mousedown事件。

看起来，并非图表中的所有组件都触发鼠标事件。

**Comment by 100pah** [comment]
```js
myChart.getZr().on('click', function () {
   ...
});
```
这是在任何地方都可以触发的。

**Comment by kuangyunsheng** [comment]
但这样是没办法判断事件是哪个组件触发的。若是只希望对部分组件响应鼠标事件，通过这种方式没法做到。

**Comment by ZhuGYao** [comment]
我也遇到了同样的问题，timeline中前进以及后退键无法被click键捕获,很麻烦。

**Comment by lihwang** [comment]
我现在使用timeline不希望触发点击。阻止它的点击怎么阻止
