### ISSUE TITLE
tooltip超大显示，样式无法控制

### ISSUE THREAD

**Issue by fangjianming** [apache/incubator-echarts#5046]
### One-line summary [问题简述]
![image](https://cloud.githubusercontent.com/assets/3132005/22818496/7b2a4c74-efa8-11e6-8cfb-44840a80f871.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
"echarts": "3.4.0",
![image](https://cloud.githubusercontent.com/assets/3132005/22818530/ac980396-efa8-11e6-9053-cb841f34aa92.png)
![image](https://cloud.githubusercontent.com/assets/3132005/22818536/b1d13ab2-efa8-11e6-902d-8f06f95c1eb2.png)

### Expected behaviour [期望结果]
![image](https://cloud.githubusercontent.com/assets/3132005/22818572/e61daea4-efa8-11e6-81f1-8516429d465a.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by fangjianming** [comment]
@百度开发者

**Comment by pissang** [comment]
超大显示指的是什么？

**Comment by fangjianming** [comment]
图当中已经指出了，tooltips原本是小框的，现在显示超大范围

**Comment by fangjianming** [comment]
![11](https://cloud.githubusercontent.com/assets/3132005/22917295/d9bec74c-f2be-11e6-9fcb-5b789063d06d.png)

**Comment by lMJl** [comment]
我这边也是同样的问题，而且toolbox.feature.dataview也有问题。
chrome,firefox都出现一样的问题

**Comment by lMJl** [comment]
我知道了，原来是用css的问题，你在div中设置style样式，就可以了。

**Comment by lMJl** [comment]
或者你用类选择器，不要用div选择样式，而是通过id或者class来选择你的div

**Comment by fangjianming** [comment]
酱紫嘛?科比哥

**Comment by 100pah** [comment]
查一下什么 css 设置影响了 tooltip 的展现？
