### ISSUE TITLE
echarts3结合百度地图（全国可缩放）做迁徙图时二次setOption数据会引起部分地图功能失效

### ISSUE THREAD

**Issue by shinyChen** [apache/incubator-echarts#5050]
### One-line summary [问题简述]

地图迁徙图，因为会有城市和城市之间，城区和城区之间等不同粒度的迁徙，所以需要在迁徙图上点击点时缩放到下一级，并重新渲染下一级的迁徙图数据

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.3
+ Browser version [浏览器类型和版本]: chrome 55.0.2883.95
+ OS Version [操作系统类型和版本]: mac OS X 10.12.2

### Expected behaviour [期望结果]

放大地图后，再次迁徙图渲染时地图保持不变，同时百度地图js操作方法（放大、缩小）保持可用。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

demo下载地址
链接: https://pan.baidu.com/s/1c2oXgHE 密码: s37i

**Comment by 100pah** [comment]
我点击你例子中的『点』后，百度地图的缩放功能并没有失效。是否可以再详细提示下问题的点在哪里？

**Comment by shinyChen** [comment]
点击之前，控制台执行myMap.zoomIn()是可以缩放地图的，点击【上地】或者【前门】两个点之后，控制台执行myMap.zoomIn()方法不再生效。

**Comment by shinyChen** [comment]
myChart.on("click", function(params) {
    if(params && (params.componentSubType == 'effectScatter')) {
        setTimeout(function() {
            // bug, 地图会缩回原始，而且不能js操作放大
            myChart.setOption(option2, true);
            myMap.zoomIn();
        }, 1e2);
    }
});

在test.js里面，myMap.zoomIn()是放大地图的方法，可是在重新渲染chart之后，该方法不生效了

**Comment by shinyChen** [comment]
请问问题确认了吗
