### ISSUE TITLE
平潭综合实验区改由福建省直管

### ISSUE THREAD

**Issue by huangy0809** [apache/incubator-echarts#5057]
### One-line summary [问题简述]

ECharts 地图数据在线生成工具：
2013年7月，平潭综合实验区获得行使设区市的管理权限，改由福建省直管。在地图构建中没有平潭综合实验区

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4.0
+ Browser version [浏览器类型和版本]:firefox，ie
+ OS Version [操作系统类型和版本]:window8

### Expected behaviour [期望结果]

平潭综合实验区改由福建省直管

### Other comments [其他信息]

![default](https://cloud.githubusercontent.com/assets/8637050/22869961/4c54d986-f1de-11e6-810c-e36995ce24bb.png)

**Comment by hl-stone** [comment]
可以自己制作地图，我最近也有此需求，自己制作的 [地图制作工具](http://geojson.io/)
![image](https://user-images.githubusercontent.com/26757108/47126327-a2b01980-d2ba-11e8-838a-0afc89801771.png)
