### ISSUE TITLE
chrome浏览器自带打印功能

### ISSUE THREAD

**Issue by Aeero** [apache/incubator-echarts#5062]
### One-line summary [问题简述]

　　　网页显示正常，但是使用chrome浏览器自带的打印功能导出pdf（window.print();），echarts部分会变得模糊。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  2.x 和 3.x 似乎都有
+ Browser version [浏览器类型和版本]:  chrome 50.0.2661.102
+ OS Version [操作系统类型和版本]:  win7

### Expected behaviour [期望结果]

希望能变得清晰

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

下图是网页中的截图：

![image](https://cloud.githubusercontent.com/assets/13835083/22874685/73ca1200-f202-11e6-84bd-37937b45777a.png)

下图是打印成pdf后的截图：

![image](https://cloud.githubusercontent.com/assets/13835083/22874445/05b7df8c-f201-11e6-9858-29b9bb9df244.png)

**Comment by 100pah** [comment]
我打印成 pdf 挺清楚的，有没有什么打印设置？

**Comment by Aeero** [comment]
打印设置都是默认的。似乎是与chrome的版本有关系，55版本的打印正常，50的打印模糊。我再调查一会。

**Comment by chaserstrong** [comment]
@Aeero 你的打印模糊问题现在解决了嘛？我也遇到了相同的问题。

**Comment by Aeero** [comment]
Hi 其实并没有解决，当时是放弃了该功能。可以提供一些线索：
打印模糊主要是出现在使用了canvas，用svg的图表插件代替可以解决。
高版本的chrome是正常的，我们客户端chrome 版本是集成的，升级代价太大。





发自网易邮箱大师
在2017年06月20日 16:22，chaserstrong 写道：

@Aeero 你的打印模糊问题现在解决了嘛？我也遇到了相同的问题。
