### ISSUE TITLE
象形柱图能实现堆叠柱形图的效果吗？

### ISSUE THREAD

**Issue by MissSweety** [apache/incubator-echarts#5064]
### One-line summary [问题简述]
象形柱图如何实现堆叠柱图的效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版本
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

http://echarts.baidu.com/demo.html#pictorialBar-vehicle
在这个例子中尝试用symbolOffset: ['100%', 0]，使蓝黑色图标移到红色图标后面。但是无法知道确定的偏移量。请问有什么其他的思路吗？

[注]：如果只是颜色不同的现在可以用总数据和真数据叠加绘制如：http://echarts.baidu.com/gallery/editor.html?c=doc-example/pictorialBar-clip。
但是如果image都不相同，不知道怎么实现了。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
后面加上stack的支持。

而目前，对于『不同图片』倒是还有一种比较不好看的方法，就是如你所说，总数据和真实数据叠加，总数据在下，真实数据在上，并且在两者之间，另外加一个 series，和真实数据长度相同，其颜色和背景色相同，挡住总数据。

**Comment by MissSweety** [comment]
好的，非常感谢！
希望echarts越做越好！
