### ISSUE TITLE
echarts3好像没有了toolbox-feature-mark功能？

### ISSUE THREAD

**Issue by wwwyyyccc123** [apache/incubator-echarts#5065]
### One-line summary [问题简述]
echarts3好像没有了toolbox-feature-mark功能？可以通过自定义工具按钮实现吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版本
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
以前版本是有的，现在版本可以通过自定义工具按钮实现吗？

### ECharts option [ECharts配置项]

```javascript
option = {
    toolbox: {
			show : true,
			left: '80%',
			feature : {
				mark : {
					show : true,
					title : {
						mark : '辅助线-开关',
						markUndo : '辅助线-删除',
						markClear : '辅助线-清空'
					},
					lineStyle : {
						width : 1,
						color : '#1e90ff',
						type : 'dashed'
					}
				}
			}
		}
}

```

**Comment by 100pah** [comment]
确实可以自定义来实现。
顺便问一下，你们使用 toolbox-feature-mark 的场景是什么呢，如果这个场景比较重要，我们也可以考虑加回去或者做成通用插件。

**Comment by wow14051** [comment]
用来做股票的趋势线标记,能画直线很方便啊,请问怎么自定义实现?

**Comment by wyqnumber** [comment]
同样有这种场景！

**Comment by amberZhaoCN** [comment]
在股票期货这类图表中，用户可能希望做出多种类型的趋势线标记

**Comment by freebuff** [comment]
我的场景是：领导要在图上标记，不一定是辅助线，也可以是圈，然后保存图片发给下属指出问题
