### ISSUE TITLE
多条拆线Y轴刻度显示有问题

### ISSUE THREAD

**Issue by tansj526** [apache/incubator-echarts#5067]
### One-line summary [问题简述]
series : [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            areaStyle: {normal: {}},
            data:[120, 632, 451, 534, 690, 530, 710]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            areaStyle: {normal: {}},
            data:[220, 182, 191, 234, 290, 330, 310]
        }
]
我在公司项目中遇到了这个问题，所以我在官方示例中改了第一组数据，第一根线的数据大，但是拆线显示在第二根的下方

### Version & Environment [版本及环境]
所有浏览器

### Expected behaviour [期望结果]

数据越大应该拆线显示在上方

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            areaStyle: {normal: {}},
            data:[120, 632, 451, 534, 690, 530, 710]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            areaStyle: {normal: {}},
            data:[220, 182, 191, 234, 290, 330, 310]
        }
    ]
};

```

**Comment by jxlwqq** [comment]
我也是，楼主解决这个问题了吗？
<img width="1033" alt="wx20170317-170525 2x" src="https://cloud.githubusercontent.com/assets/2421068/24036305/f025e0be-0b33-11e7-978a-774836ffb1b7.png">

**Comment by tansj526** [comment]
这个问题已经解决了，去掉对象中 stack: '总量'这个字段就好了
