### ISSUE TITLE
关于重庆地图缩放后 指定区县不触发itemHover问题

### ISSUE THREAD

**Issue by yelingfeng** [apache/incubator-echarts#5072]
### One-line summary [问题简述]
当缩放到很近的时候 某些区触发点变小的问题 

![image](https://cloud.githubusercontent.com/assets/1932350/22921630/6bc8f43a-f2d5-11e6-9817-5fdf527a438e.png)

点击左侧区域就可以触发
![image](https://cloud.githubusercontent.com/assets/1932350/22921660/8b66c542-f2d5-11e6-89aa-024c2beba777.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]: 

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://ecomfe.github.io/echarts-map-tool/

**Comment by pissang** [comment]
什么版本的  echarts？

**Comment by yelingfeng** [comment]
最新版 直接官网例子 就可以看到
