### ISSUE TITLE
echarts3结合百度地图（全国可缩放）做迁徙图时二次setOption数据会引起部分地图功能失效

### ISSUE THREAD

**Issue by shinyChen** [apache/incubator-echarts#5106]
具体问题参考：https://github.com/ecomfe/echarts/issues/5050
还请确认下是使用方法不对，还是echarts有bug，谢谢。

**Comment by sevenen** [comment]
当点击上地时，option2--bmap：{
                                  center: 上地的地理位置，
                                  zoom: 12}
这样可以达到你的要求吗？

**Comment by shinyChen** [comment]
可以达到

**Comment by shinyChen** [comment]
myChart.on("click", function(params) {
    if(params && (params.componentSubType == 'effectScatter')) {

            myChart.setOption(option2, true);
            //myMap.zoomIn();
            myMap.setZoom(12); // 似乎不生效？
    }
});

**Comment by sevenen** [comment]
你的myMap在函数内重新赋值一下试试看？

**Comment by shinyChen** [comment]
函数内重新赋值好了！真是谢谢啦！

myMap = myChart.getModel().getComponent('bmap').getBMap();

请教下，地图实例引用怎么断了呢？

**Comment by sevenen** [comment]
因为你option2里面重新设置了bmap属性，所以前面的myMap失效。你可以把option2里面的bmap去掉，那样你原来的代码也可以达到效果。
