### ISSUE TITLE
关于世界地图名称的疑惑，在线等。。。

### ISSUE THREAD

**Issue by vasttian** [apache/incubator-echarts#5108]
请问ECharts使用的世界地图的名称是什么标准？ 怎么感觉有的是使用的简写有的是使用的全称。
按照ISO 3166标准
如：
俄罗斯的 全称是：Russian Federation  简称是：Russia
美国的 全称是：United States of America  简称是：United States
但是ECharts使用的数据俄罗斯是：Russia 美国是：United States of America

为什么有的国家是使用的简称有的是全称？ 还是ECharts 使用的是其他什么标准？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wdnlwzd** [comment]
@100pah  @pissang  求解惑

**Comment by zilingliyu** [comment]
请问您遇到的这个问题解决了吗？

**Comment by chfw** [comment]
请用 name_map
