### ISSUE TITLE
隐藏热力图的边框

### ISSUE THREAD

**Issue by benyanc** [apache/incubator-echarts#5110]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.2
+ Browser version [浏览器类型和版本]: Chrome 54.0
+ OS Version [操作系统类型和版本]: Windows 7

### Expected behaviour [期望结果]

设置grid borderwidth=0时，热力图的内部格子应该完全看不见了，但是隐约有一个白色的边框还能看见。因为我们的数据很多、很密集，所以这个问题给我们带来了一些困难。

### ECharts option [ECharts配置项]

```javascript
data = data.map(function (item) {
     return {
        value:[item[1], item[0], item[2] || '-'],
        itemStyle:{
            normal:{  borderColor: '#000000'
            ,borderWidth:0
            ,borderType:'solid',
          color:'#ffffff'}
        }
    }
});

option = {
    tooltip: {
        position: 'top'
    },
    animation: false,
    grid: {
        height: '50%',
        y: '10%'
    },
    xAxis: {
        type: 'category',
        data: hours,
        splitArea: {
            show: true
        }
    },
    yAxis: {
        type: 'category',
        data: days,
        splitArea: {
            show: true
        }
    },
    visualMap: {
        min: 0,
        max: 10,
        calculable: true,
        orient: 'horizontal',
        left: 'center',
        bottom: '15%'
    },
    series: [{
        name: 'Punch Card',
        type: 'heatmap',
        data: data,
        label: {
            normal: {
                show: true
            }
        },
        itemStyle: {
            emphasis: {
                shadowBlur: 10,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
            }
        }
    }]
};
```

**Comment by 100pah** [comment]
可以麻烦截个图看下效果么？

**Comment by benyanc** [comment]
第一个图显示出隐约的白框：
![simple_heatmap](https://cloud.githubusercontent.com/assets/9326802/23151704/ef41e044-f837-11e6-8587-978df39fcfa9.png)

第二个图比较复杂，是我们的工程里用到的主要图，因为框比较多，所以白边的错误效果比较明显：

![oncoprint_heatmap](https://cloud.githubusercontent.com/assets/9326802/23151737/21fc6108-f838-11e6-9291-5031b1ca08ed.png)

**Comment by langwuzhe** [comment]
![Uploading 1.jpg…]()

**Comment by langwuzhe** [comment]
![qq 20170305205714](https://cloud.githubusercontent.com/assets/24667395/23587539/83ef6918-01e9-11e7-89dd-1a34eda57e20.jpg)
