### ISSUE TITLE
离线地图制作三级省市县地图级联

### ISSUE THREAD

**Issue by zds-xiaoxianyu** [apache/incubator-echarts#5124]
刚级联了两个省份的地图，浙江省显示正常，到了河北省地图时，发现张家口市和
衡水市地图显示不正确，不知是否是地图json数据有问题，其余市级地图均显示无误，
官网对应张家口市.js也是显示异常，多次下载官方Json数据确定还是存在显示错误问题，求确认,是否官网提供的数据有误，还是其他问题？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by zds-xiaoxianyu** [comment]
![default](https://cloud.githubusercontent.com/assets/25834106/23201432/83daa9a2-f914-11e6-86c7-94dae46162b8.png)

**Comment by zds-xiaoxianyu** [comment]
又多了内蒙古鄂尔多斯市地图数据异常

**Comment by zds-xiaoxianyu** [comment]
![default](https://cloud.githubusercontent.com/assets/25834106/23242749/a79ac010-f9b5-11e6-8bbb-a13fa119e71a.png)

**Comment by hl-stone** [comment]
@zds-xiaoxianyu  替换地图数据后，问题解决了还是更换版本？
