### ISSUE TITLE
在开发环境中，vue框架下使用echarts，初始化时ie报错，调用的对象无效，其他浏览器暂时没发现问题

### ISSUE THREAD

**Issue by frankyeyq** [apache/incubator-echarts#5135]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请具体描述问题
