### ISSUE TITLE
Heatmap brush

### ISSUE THREAD

**Issue by 4tuneengineering** [apache/incubator-echarts#5138]
### One-line summary [问题简述]
Heatmap brush selection

Possible to use brush to select different regions at same time in heatmap and get selected data ranges.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by tmtron** [comment]
Can we vote to reopen?
It would be great to have the brush feature to select a region in a Heatmap.

**Comment by sjcobb** [comment]
I agree this would be a very useful feature--something similar to Plotly's [selectable heatmap](https://plotly.com/javascript/heatmaps/).

I'm wondering if one of the selectable Treemap examples could be modified to serve a similar purpose or even this [custom heatmap example](https://echarts.apache.org/examples/en/editor.html?c=calendar-graph).

**Comment by tmtron** [comment]
@Ovilia can you reopen this feature request, or should we create a new issue?
