### ISSUE TITLE
如何能把散点图上重叠的点分开？

### ISSUE THREAD

**Issue by tsauliu** [apache/incubator-echarts#5150]
### One-line summary [问题简述]

如何能把散点图上重叠的点分开？

### Expected behaviour [期望结果]

散点图上重叠的散点 互相之间有一点点的间距，现在的都叠在一起了，看不清

谢谢！

### Other comments [其他信息]

![screen shot 2017-02-28 at 10 53 07](https://cloud.githubusercontent.com/assets/10590746/23389619/27a1be8e-fda4-11e6-91f4-31d13226cf4c.png)

**Comment by Ovilia** [comment]
你期望怎么分开，按什么分开？附上代码
