### ISSUE TITLE
Echarts3在IE8下重新加载图表显示异常

### ISSUE THREAD

**Issue by wowton** [apache/incubator-echarts#5153]
### One-line summary [问题简述]
IE8中在不重新载入页面的情况下，重新加载折线图，除了折线之外不显示图表的其他任何组件。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: IE8
+ OS Version [操作系统类型和版本]: Windows 7

### Expected behaviour [期望结果]
和第一次加载时一样正常显示图表

### ECharts option [ECharts配置项]

```javascript
option = {
  tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['最高气温','最低气温']
    },
    xAxis:  {
        type: 'category',
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10]
        },
        {
            name:'最低气温',
            type:'line',
            data:[1, -2, 2, 5, 3, 2, 0]
        }
    ]
}

```

### Other comments [其他信息]

第一次载入截图：
![image](https://cloud.githubusercontent.com/assets/15208877/23390399/bab91376-fda8-11e6-94ef-4e9825332906.png)
重新加载图表之后的截图：
![image](https://cloud.githubusercontent.com/assets/15208877/23390412/cec4568c-fda8-11e6-9dfa-6c4f7e7e3750.png)

**Comment by pissang** [comment]
重新加载指的是？

**Comment by wowton** [comment]
@pissang 就是重新加载新数据：`chart.setOption(option);`

**Comment by 100pah** [comment]
我在 window XP 下原版的 ie8 中没有发现这种情况。是不是在 ie9/10/11 的兼容模式中出现的这个情况？
