### ISSUE TITLE
时间轴搭配地图，visualMap的itemSymbol设置不生效

### ISSUE THREAD

**Issue by hzzcc** [apache/incubator-echarts#5159]
### One-line summary [问题简述]

时间轴搭配地图，visualMap的itemSymbol设置不生效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts@3.4.0
+ Browser version [浏览器类型和版本]: chrome 56.0.2924.87 (64-bit)
+ OS Version [操作系统类型和版本]: MacOS Sierra 10.12.3 (16D32)

### Expected behaviour [期望结果]

itemSymbol 设置生效

### ECharts option [ECharts配置项]

```javascript
option = {
    baseOption: {
        timeline: {axisType: 'category', autoPlay: true, playInterval: 12000, data: [], show: false},
        visualMap: {type: 'piecewise', textStyle: {color: '#29ABE2'},
          itemSymbol: 'arrow', itemWidth: 12, itemHeight: 8},
        series: [{type: 'map', map: 'china', itemStyle: {normal: {
              areaColor: 'rgba(200, 246, 255, 0.1)', borderColor: '#7EA5C2'}},
          top: '12%', bottom: '8%', silent: true, roam: false, zoom: 1, label: {
            normal: {show: true}}}]
     },
     options: []
};

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/6861655/23442757/88ccb486-fe65-11e6-8016-3850e060e4ee.png)

**Comment by knighthanfei** [comment]
需要设置inRange
