### ISSUE TITLE
散点图中的点的选中状态(颜色)怎么修改，初始化后怎么默认选中指定的点

### ISSUE THREAD

**Issue by wpp5354** [apache/incubator-echarts#5163]
### One-line summary [问题简述]
如下图中，图上的点能不能设置选中状态(修改颜色、大小等)，可以得话怎么设置，怎么让图标初始化完成后默认选中指定的点，谢谢！

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/9841553/23490292/a281625a-ff32-11e6-8202-4ce4305e67ed.png)

**Comment by pissang** [comment]
你可以 click 后 setOption 修改其颜色

**Comment by wpp5354** [comment]
@pissang setOption修改的颜色是所有点的颜色，还是可以单独设置当前选中点的颜色，另外，默认选中指定的点可以实现吗？非常感谢！

**Comment by pissang** [comment]
可以单独设置选中点的颜色，默认选中点就是默认这个点就设置成选中的颜色呗

**Comment by wpp5354** [comment]
@pissang 抱歉，可能我没表达清楚，我是需要在图表加载完成后默认执行指定的点的单击事件，然后ajax请求后在图表外部显示额外的信息

**Comment by pissang** [comment]
这些都是业务逻辑，你的需要就是默认高亮一个指定的点并且加载这个点的外部信息，这个加载外部信息以及高亮都是你程序控制的，并不需要 echarts 有什么特别的支持

**Comment by unzoa** [comment]
> > 可以单独设置选中点的颜色，默认选中点就是默认这个点就设置成选中的颜色呗
> 
> 我们这里有个需求是，地图上俩个点距离比较近，a显示在b的上面，通过option的确改变了b的凸显，但是b依然在a的下面，有什么属性或方法更改

好吧  我画了三层，将点分为两类凸显(b)和非凸显(a), 用zlevel控制图层的显示，但是拖动屏幕后重新渲染会很慢，首次出现也慢了

**Comment by daxianyu** [comment]
> 这些都是业务逻辑，你的需要就是默认高亮一个指定的点并且加载这个点的外部信息，这里面加载外部信息以及高亮都是你程序控制的，并不需要 echarts 有什么特别的支持

他的意思应该是，我原始数据给你了之后，如何去获取echarts中的这个散点对象，然后将其设置高亮，
