### ISSUE TITLE
这算是echarts3.0地图的BUG么？为什么每次都是南海的问题？

### ISSUE THREAD

**Issue by Fdango** [apache/incubator-echarts#5165]
![k3dsw c5e6a7im6p 28vja](https://cloud.githubusercontent.com/assets/17996704/23491184/a40e22b6-ff37-11e6-8071-bfd6480c7490.png)

![image](https://cloud.githubusercontent.com/assets/17996704/23491198/b8288c8c-ff37-11e6-84db-0dc37a88c849.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能具体描述下问题是什么么？

**Comment by Fdango** [comment]
@pissang 我鼠标滑过的时候每个省都有自己自定义的数据，在2.0的时候南海鼠标滑过没有数据是正常的，而我切换到3.0版本的地图时候，鼠标滑过南海就成了上图的样子

**Comment by pissang** [comment]
能否在 http://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all 贴一个可以复现的例子，谢谢
