### ISSUE TITLE
ie8下重新设置echart数据后，会出现多个图表

### ISSUE THREAD

**Issue by Arvin333** [apache/incubator-echarts#5166]
### One-line summary [问题简述]

初始化：
var option = ...；
var total = echarts.init($('#total')[0]);
                total.setOption(option);
正常渲染。
绑定.J_btn click事件 total.setOption(option);
触发.J_btn click事件

ie8会在之前已经渲染好的图表基础之上，再渲染出另外一个一模一样的图表。
其他浏览器正常。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts 3
+ Browser version [浏览器类型和版本]:IE8
+ OS Version [操作系统类型和版本]:winows 7

### Expected behaviour [期望结果]

希望重复触发事件，让ie8跟其他浏览器一样，只渲染一个图表

### ECharts option [ECharts配置项]

```javascript
var option = {
        tooltip: {
            show: false
        },
        color: [
            '#fff', 'rgba(255,255,255,.3)', '#ff7a6c'
        ],
        legend:{
            z : 99
        },
        series: [
            {
                type:'pie',
                radius: ['78%', '90%'],
                avoidLabelOverlap: false,
                label: {
                    normal: {
                        show: false,
                        position: 'center'
                    },
                    emphasis: {
                        show: false,
                        textStyle: {
                            fontSize: '30',
                            fontWeight: 'bold'
                        }
                    }
                },
                labelLine: {
                    normal: {
                        show: false
                    }
                },
                data:[
                    {value:0},
                    {value:100}
                ]
            }
        ]
    };
```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/11606732/23496690/72f1eb04-ff5a-11e6-8954-ac8072f2d3af.png)

**Comment by DimonHo** [comment]
之前我也遇到过，我的做法是重新setOption之前把DIV清空一下，可以暂时解决这个问题。
