### ISSUE TITLE
Bug in themeRiver echarts 3.0: it is not receiving click event

### ISSUE THREAD

**Issue by maziyarpanahi** [apache/incubator-echarts#5173]
Hi,

I am using on('click') event with few charts (line, bar, etc.), but I can't get it working with this example for instance:

https://ecomfe.github.io/echarts-examples/public/editor.html?c=themeRiver-basic

I appreciate any help.

**Comment by maziyarpanahi** [comment]
Unfortunately, it appears this feature is missing from themeRiver chart.

**Comment by Ovilia** [comment]
Duplicate of #5173

**Comment by Ovilia** [comment]
Adding `data.setItemGraphicEl(idx, polygon);` doesn't help. The series name is not correct.
