### ISSUE TITLE
关于缩放事件的监听问题

### ISSUE THREAD

**Issue by DrikFeng** [apache/incubator-echarts#5177]
### One-line summary [问题简述]
需要在关系图(graph)中监听缩放事件，但是并没有在api中发现。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]:  Chrome
+ OS Version [操作系统类型和版本]: win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by tangjinzhou** [comment]
同求
