### ISSUE TITLE
地图用type：scatter，如何控制地图中渲染的圆圈不停的放大缩小

### ISSUE THREAD

**Issue by Just-focus** [apache/incubator-echarts#5179]
### One-line summary [问题简述]

地图用type：scatter，如何控制地图中渲染的圆圈不停的放大缩小

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
option = {
    geo: {
        map: 'china'
    },
    series : [
        {
            type: 'scatter',
            coordinateSystem: 'geo',
            data:[[125.03,46.58]],
            symbolSize: 20
        }
    ]
};
var size = 20;
var increase = true;
setInterval(function(){
    if(size == 50){
        increase = false;
    }
    if(size == 20){
        increase = true;
    }
    if(increase==true){
        size = size+10;
    }else{
        size = size-10;
    }
    myChart.setOption({
            series:{
                symbolSize:size
            }
        });
},300);
不太清楚这样有什么意义，你如果想要这种突出某点的效果的话，可以使用type:effectScatter

**Comment by Just-focus** [comment]
我需要实现的效果是当有一条数据进来的时候，地图中的圈会放大缩小几次，代表有人进来了。。如果用effectScatter，是那种波纹状的。。，不是预想的效果。。。以前echaert2的时候用markpoint自带那种效果，但是e3好像取消这种效果了。。

**Comment by pissang** [comment]
试试 `animationEasing: 'elasticOut'` 来模拟放大缩小几次的效果

**Comment by Just-focus** [comment]
这个效果可以，谢谢啦。。。但是他只会缩放一次。。我想更好的效果是可以缩放几次。。然后我去尝试改那边曲线的参数，但是一直效果不好，可以帮忙写个吗，缩放几次的

**Comment by pissang** [comment]
你可以试一下 animationEasing 携程一个自定义的函数，参考下 elasticOut
```js

        elasticOut: function(k) {
            var s, a = 0.1, p = 0.4;
            if (k === 0) {
                return 0;
            }
            if (k === 1) {
                return 1;
            }
            if (!a || a < 1) {
                a = 1; s = p / 4;
            }
            else{
                s = p * Math.asin(1 / a) / (2 * Math.PI);
            }
            return (a * Math.pow(2, - 10 * k) *
                    Math.sin((k - s) * (2 * Math.PI) / p) + 1);
        }
```

**Comment by Just-focus** [comment]
谢谢回答。。这个我尝试过了。。。但是写不出来..

**Comment by mangoZT** [comment]
通俗的方法用时间器间隔几秒改变option的symbolSize  大小是否适合你用
