### ISSUE TITLE
用折线图和柱状图实现页面展示，根据前台页面年、月、周按钮切从后台获得不同的数据传入图里，但是只有默认的第一组数据有页面效果 ，切换月和周只会展示最简单的图，同样的echars样式代码为啥月和周展示不出相应的效果

### ISSUE THREAD

**Issue by nantingting** [apache/incubator-echarts#5182]
### One-line summary [问题简述]

用折线图和柱状图实现页面展示，根据前台页面年、月、周按钮切从后台获得不同的数据传入图里，但是只有默认的第一组数据有页面效果 ，切换月和周只会展示最简单的图，同样的echars样式代码为啥月和周展示不出相应的效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
你说的页面效果是什么？可不可以给出截图或者代码看看？
