### ISSUE TITLE
Position attributes set as geo coordinates? 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#5191]
It would be nice if position attributes can be set as geo coordinates, not sure about format, maybe something like this:

left:["lat(14.43302)", long("50.079128")]

The point is that these would automatically sync with geo:{} roam, it would allow to position anything on the map. 

It should work for grids, pie centers and any graphics. 

Just an idea! It can be done with Echart utils these days but it needs to be updated on roam..

**Comment by pissang** [comment]
Hi @jarben , you can use `center` property.

And for the new version, which will be released soon. You can use `boundingCoords`, for example:
```js
boundingCoords: [[-180, -90], [180, 90]]
```
Which will show full world map.

Not show if it can satisfy your requirements

**Comment by jarben** [comment]
Thanks @pissang for your reply, sorry my description wasn't very clear, the scenario is more about centering other series types (such as pie chart) on the map. For example: 

![image](https://cloud.githubusercontent.com/assets/561365/24092382/3d59877a-0d4e-11e7-9dbf-cc5b49e39501.png)

This can be achieved by using geo.dataToPoint(latlong), however, this requires a special handler which handles zooming and roaming. 

It would be nice if any position can be specified as lat long which would automatically position it on the map (using geo:{}) settings. 

For pie chart, it would be something along these lines:  

center:["lat(14.43302)", long("50.079128")]

The lat() long() syntax is to differentiate from numbers such as [14.43302,50.079128] which is currenlty handled as pixels. 

It's basically a declarative way to position anything on map.

**Comment by pissang** [comment]
Aha, seems i gave an answer has no relationship at all. 

Yes it will be very useful, and we thinking out a way to put a component, like pie in your example, on a specified coordinate system like geo. For example:
```js
pie: {
    coordinateSystem: 'geo',
    center: [14.43302, 50.079128]
},
```
// Or even further, we can put a coordinate system on another coordinate system.
```js
grid: {
    coordinateSystem: 'geo',
    left: 14.43302,
    top: 50.079128
}
```

But there is still no plan when to add this feature :(

**Comment by jarben** [comment]
Thanks for providing examples @pissang! 

Using coordinateSystem property sounds cleaner than parsing position values, although coordinateSystem property seems to be used in some series to position content, rather that graph itself.  Maybe positioningSystem or simply position similar to CSS?  

Another thing to think about - what if positioning attributes can be set as functions? In that case, using: 

top: function(){
   return geo.dataToPoint(latlong)
}

It would be called anytime layout changes which means no extra handlers when zoom or roam happens.. It would also allow some responsive design rules made easily. 

Going even further, if any attribute can be a function, users would be able to set color and other properties based on value which would work as an alternative to some visualMap scenarios.. 

Anyway, I'm glad this is for discussion!
