### ISSUE TITLE
地图散点图重新设置rippleEffect的scale大小对于当前图例的显示无效

### ISSUE THREAD

**Issue by lfy55** [apache/incubator-echarts#5199]
### rippleEffect值重新设置

地图散点图重新设置rippleEffect的scale大小对于当前图例的显示无效，其他图例可以生效，具体情况看下方在线实例

### Expected behaviour [期望结果]

重新设置scale大小后，图表显示发生变化

### codepen

<p data-height="265" data-theme-id="0" data-slug-hash="yMaQrx" data-default-tab="result" data-user="KIDlfy" data-embed-version="2" data-pen-title="map设置scale无效" class="codepen">See the Pen <a href="http://codepen.io/KIDlfy/pen/yMaQrx/">map设置scale无效</a> by KID (<a href="http://codepen.io/KIDlfy">@KIDlfy</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>

**Comment by kouyuting** [comment]
我也遇到一样的问题，求解答
