### ISSUE TITLE
type是treemap时怎么控制里面矩形的顺序

### ISSUE THREAD

**Issue by heianqishizhisuiyuan** [apache/incubator-echarts#5201]
### One-line summary [问题简述]
type是treemap时
怎么控制里面矩形的顺序

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
在官网刚下的最新版
浏览器是谷歌最新稳定版
操作系统是 w8

### Expected behaviour [期望结果]

期望图形排列顺序可控制

### ECharts option [ECharts配置项]

```javascript
option = {
  tooltip: {
        trigger: 'item',
        formatter: "{b}"  //显示tooltip时，只显示name
    },
    toolbox: {
        show: false,
        feature: {
            mark: {
                show: true
            },
            dataView: {
                show: true,
                readOnly: false
            },
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    calculable: false,
    series: [{
        name: '矩形图',
        type: 'treemap',
        top: 0,
        left: 0,
        width: 600,
        height: 400,
        squareRatio: 1.1,
        itemStyle: {
            normal: {
                label: {
                    show: true,
                    //formatter: "{b}",
                    fontSize: 15
                },

                borderWidth: 1
            },
            emphasis: {
                label: {
                    show: true
                }
            }
        },
        label: {
            normal: {
                textStyle: {
                    fontSize: 15,
                    //formatter: "{b}"
                }
            }
        },
        breadcrumb: {//关闭面包屑路径
            show: false
        },
        roam: false,//关闭平移拖动
        nodeClick: false,//关闭节点点击
        silent: false,//关闭鼠标事件
        data: rawData
    }]
}

```

### Other comments [其他信息]

var rawData = [{
    value: 90,
    children: [{
        name: '1',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d34c0c'
            }
        }
    }, {
        name: '2',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d35c1c'
            }
        }
    }, {
        name: '3',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d36c2c'
            }
        }
    }, {
        name: '4',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d37c3c'
            }
        }
    }, {
        name: '5',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d38c4c'
            }
        }
    }, {
        name: '6',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '7',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '8',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '9',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }]
}];
当数据是上面的时候矩形顺序就会正常排列如图
![image](https://cloud.githubusercontent.com/assets/20060464/23641572/e2b8f1f2-032f-11e7-8b02-bb1a6f64f7a0.png)
当数据比上面多出三个的时候 如下
var rawData = [{
    value: 90,
    children: [{
        name: '1',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d34c0c'
            }
        }
    }, {
        name: '2',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d35c1c'
            }
        }
    }, {
        name: '3',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d36c2c'
            }
        }
    }, {
        name: '4',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d37c3c'
            }
        }
    }, {
        name: '5',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d38c4c'
            }
        }
    }, {
        name: '6',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '7',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '8',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '9',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '10',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '11',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }, {
        name: '12',
        value: 10,
        itemStyle: {
            normal: {
                color: '#d39c5c'
            }
        }
    }]
}];
他的排序就不按规则来了 图片如下

![image](https://cloud.githubusercontent.com/assets/20060464/23641607/2db0278e-0330-11e7-947d-814f19002f1f.png)
  
求作者讲下 是我配置错了  还是bug？？急急急！！！

**Comment by GoldWood2000** [comment]
请问这个问题您解决了吗
