### ISSUE TITLE
echart3 雷达图设置radar.indicator.max报错

### ISSUE THREAD

**Issue by gitsunjie** [apache/incubator-echarts#5210]
// 问题描述在radar.indicator.max设置后面
option = {
    title: {
	        text: '综合税负分析'
	    },
    tooltip: {},
    legend: {
        data: ['行业平均值', '岭南控股','西安旅游']
    },
    radar: {
        // shape: 'circle',
        indicator: [
           { name: '总体税费和现金流入比', max: 0.1168881042631104},//问题所在，把0.1168881042631104改成其他的数值生效
           { name: '综合税费率', max: 0.1208406336373244},
           { name: '增值税税负率', max: 0.08851172426736605},
           { name: '企业所得税税负率', max: 0.2743687761432049},
           { name: '营业税金及附加负担率', max: 0.05157943293312441}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        animation:true,
        // areaStyle: {normal: {}},
        data : [
            {
                value : [0.1168881042631104,0.11763822730349636, 0.036383119395591954, 0.21063568498228286, 0.05157943293312441],
                name : '岭南控股'
            },
             {
                value : [0.1029338013017348,0.1208406336373244, 0.08851172426736605, 0.18274880797860626, 0.03145828549947577],
                name : '行业平均值'
            },
             {
                value : [0.023943843554384885,0.024947021025442384, 0.005508174256742906, 0.2743687761432049, 0.0075607635107787655],
                name : '西安旅游'
            }
        ]
    }]
};

**Comment by ht5230480** [comment]
radar: {
        // shape: 'circle',
        indicator:
                [
                    {
                        "min":0.1,                                               //min值为0.1的时候也会出现这个问题
                        "max":1.88688526,
                        "name":"收益率（ad_syl）"
                    },
                    {"min":0,"max":5.67247539,"name":"发行面积（ln(city_score)）"},
                    {"min":0,"max":0.218,"name":"是否结构性（is_jgx）"},
                    {"min":0,"max":11.70830487,"name":"个人投资起点（ln(gr_tz_qidian)/10）"},
                    {"min":0,"max":134.8875931324911,"name":"投资周期（tz_zhouqi/100）"}
        ]
    },
    series: [{
        name: '理财产品细分图',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {"name":"农村短线局域型","value":[1.88688526,1.2346633,0.001,11.15529083,134.8875931324911]},
            {"name":"多体制普惠保本型","value":[1.39008484,5.06940173,0.2186,10.97740411,122.6733771569433]},
            {"name":"国有普惠全国型","value":[1.18428998,3.36047828,0.0,11.03632193,120.94954449894884]},
            {"name":"城商高险高利型","value":[1.83041575,5.67247539,0.0,11.70830487,123.3475321162948]},
            {"name":"精英高险长线型","value":[1.70489229,0.53199856,0.0,11.19680729,112.39897816999536]}
        ]
    }]

**Comment by ht5230480** [comment]
radar: {
        // shape: 'circle',
        indicator:
                [
                    {
                        "min":0.1,//最小值为0.1的时候也会出问题。
                        "max":1.88688526,
                        "name":"收益率（ad_syl）"
                    },
                    {"min":0,"max":5.67247539,"name":"发行面积（ln(city_score)）"},
                    {"min":0,"max":0.218,"name":"是否结构性（is_jgx）"},
                    {"min":0,"max":11.70830487,"name":"个人投资起点（ln(gr_tz_qidian)/10）"},
                    {"min":0,"max":134.8875931324911,"name":"投资周期（tz_zhouqi/100）"}
        ]
    },
    series: [{
        name: '理财产品细分图',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {"name":"农村短线局域型","value":[1.88688526,1.2346633,0.001,11.15529083,134.8875931324911]},
            {"name":"多体制普惠保本型","value":[1.39008484,5.06940173,0.2186,10.97740411,122.6733771569433]},
            {"name":"国有普惠全国型","value":[1.18428998,3.36047828,0.0,11.03632193,120.94954449894884]},
            {"name":"城商高险高利型","value":[1.83041575,5.67247539,0.0,11.70830487,123.3475321162948]},
            {"name":"精英高险长线型","value":[1.70489229,0.53199856,0.0,11.19680729,112.39897816999536]}
        ]
    }]
