### ISSUE TITLE
在雷达图中data中有两组对比数据，如何显示一组为实线，一组为虚线？

### ISSUE THREAD

**Issue by coolman2135** [apache/incubator-echarts#5217]
### One-line summary [问题简述]
在雷达图中data中有两组对比数据，如何显示一组为实线，一组为虚线？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以设置 data 层级的 lineStyle.normal.type

**Comment by coolman2135** [comment]
能给个例子吗？
我的option如下：
option = {
        title: {
            text: '刘德华',
            subtext: '纯属虚构'
        },
        tooltip: {
            trigger: 'axis'
        },
        legend: {
            orient: 'vertical',
            x: 'right',
            y: 'bottom',
            data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
        },
        toolbox: {
            show: true,
            feature: {
                mark: { show: true },
                dataView: { show: true, readOnly: false },
                restore: { show: true },
                saveAsImage: { show: true }
            }
        },
        polar: [
           {
               indicator: [
                   { text: '销售（sales）', axisLabel: { show: true, textStyle: { fontSize: 18, color: '#333' } }, max: 5 },
                   { text: '管理（Administration）', max: 5 },
                   { text: '信息技术（Information Techology）', max: 5 },
                   { text: '客服（Customer Support）', max: 5 },
                   { text: '研发（Development）', max: 5 },
                   { text: '市场（Marketing）', max: 5 }
               ]
           }
        ],
        calculable: true,
        series: [
            {
                name: '预算 vs 开销（Budget vs spending）',
                type: 'radar',
                data: [
                    {
                        value: [2, 4, 2, 5, 1, 2],
                        name: '预算分配（Allocated Budget）',
                    },
                     {
                         value: [2, 3, 4, 4, 1, 0],
                         name: '实际开销（Actual Spending）'
                     }
                ]
            }
        ]
    };

如何让实际开销这组数据显示为虚线呢？
