### ISSUE TITLE
echarts的折线图动画初始怎样才能从0开始上涨

### ISSUE THREAD

**Issue by fuxinruming** [apache/incubator-echarts#5218]
您好，我想请教个问题，现在echarts3的折线图表怎么样才能像echarts2那样按从下往上的动画出现呢，我看配置里面只有默认动画，我的图表换成echarts2，动画也是从第一个数据开始或从上或从下开始动画的，怎样才能从0开始上涨呢
用的是echarts2,折线动画我想要从0开始往上涨，希望大神能帮忙解答下

**Comment by Ovilia** [comment]
先 setOption 一遍把数字都设为0，然后再 setOption 设为想要的值

**Comment by fuxinruming** [comment]
非常谢谢您的解答，我先myChart1.setOption(option1)让data都是0，然后设了个定时器，data设置成我想要的数据，然后又setoption一次，动画是一下就出来的，没有缓冲，有好的解决办法么

**Comment by Ovilia** [comment]
不用定时器啊，就直接 `myChart1.setOption(option1); myChart1.setOption(option2);`

**Comment by fuxinruming** [comment]
我试过myChart1.setOption(option1)然后再myChart1.setOption(option2);不可以，折线是瞬间就从下上来的，设了animationDuration也不行
