### ISSUE TITLE
IE8下，&符号显示转义符

### ISSUE THREAD

**Issue by SnowWinterMaye** [apache/incubator-echarts#5227]
### One-line summary [问题简述]
今天在测试 图表在 IE8 上的表现，发现 & 会显示为 & amp; 
仔细找了一遍源码 发现了 encodeHtmlAttribute 这个方法
``` javascript
	    var encodeHtmlAttribute = function (s) {
	        return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;');
	    };
```
 * 想问一下为什么这么写？
 * 我想解决这个问题，除了改源码还有别的方式吗？
PS 请原谅还在兼容IE8 ，并且还有这种BUG!! 找了一下午...

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: IE 8(模拟)
+ OS Version [操作系统类型和版本]: Win10

#### IE8效果
![image](https://cloud.githubusercontent.com/assets/10673970/23701175/9bf402aa-0430-11e7-83d3-8ee9b47bcc04.png)
 #### chrome效果
![image](https://cloud.githubusercontent.com/assets/10673970/23701228/f24781a4-0430-11e7-8c39-330ccb6a9588.png)

**Comment by zaiMoe** [comment]
今天也遇到这个问题了， 没错， 都9102年了， 好在兼容IE8
