### ISSUE TITLE
[Feature request] Please implement Bullet and Spakline charts

### ISSUE THREAD

**Issue by hristo-composite** [apache/incubator-echarts#5228]
Please implement Bullet:
https://bl.ocks.org/mbostock/4061961

and Sparkline charts:
http://omnipotent.net/jquery.sparkline/#s-about

**Comment by pissang** [comment]
Check http://echarts.baidu.com/gallery/editor.html?c=line-easing this example for sparkline.

**Comment by hrstoyanov** [comment]
Well,  no .. there is a lot more to bullet and spakline charts. Check out the link I provided and all the details that go with them. it is not just "simple line charts".

**Comment by mycaule** [comment]
Yes it would be great having a set of standard sparklines (see [Wikipedia](https://en.wikipedia.org/wiki/Sparkline))

You can already do _sparklines_ with line charts and small size CSS styling.

See this project where I graph Bitcoin day value https://mycaule.github.io/portfolio/
<img width="1043" alt="screen shot 2017-12-20 at 15 07 17" src="https://user-images.githubusercontent.com/6161385/34210843-83bbef06-e597-11e7-8474-be889c3c81d5.png">

Source code [charts.js](https://github.com/mycaule/portfolio/blob/master/modules/charts.js), [style.css](https://github.com/mycaule/portfolio/blob/master/style.css)

Highcharts has support for **easy** [sparklines](https://www.highcharts.com/demo/sparkline) drawing. It would be great if drawing that can of chart needed less configuration than what I did.

**Comment by mycaule** [comment]
You may need to write an extension like `echarts-sparkline` as you did for [echarts-wordcloud](https://github.com/ecomfe/echarts-wordcloud).

**Comment by kerryj89** [comment]
+1

**Comment by theNotoriousHxc** [comment]
Any news on this one about native sparkline support?

**Comment by pchaganti** [comment]
👍
