### ISSUE TITLE
非常多的legend是否可以做成分页显示的？

### ISSUE THREAD

**Issue by tryIdea** [apache/incubator-echarts#5230]
### One-line summary [问题简述]
数据统计分析时，非常多的legend是否可以做成分页显示的？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows7

### Expected behaviour [期望结果]
如下图legend可以分页显示
![image](https://cloud.githubusercontent.com/assets/6367303/23733361/780820aa-04b3-11e7-80e9-731d2fe1512d.png)

**Comment by daoyuanjiao** [comment]
其实我也遇到过，希望可以提供分页功能！

**Comment by Ovilia** [comment]
不能，暂时只能限定宽度或高度以后变成多行或者多列

**Comment by tryIdea** [comment]
@Ovilia  这个功能什么时候可以加上？有计划没

**Comment by Ovilia** [comment]
@tryIdea 暂时没有开发计划

**Comment by tiger8888** [comment]
自定义颜色,然后隐藏lengend,然后自己显示不就行了嘛

**Comment by Ovilia** [comment]
legend 分页现已支持 http://echarts.baidu.com/option.html#legend.type
