### ISSUE TITLE
noDataLoadingOption 设置没有数据时显示的参数被去掉了吗

### ISSUE THREAD

**Issue by ljxtest** [apache/incubator-echarts#5237]
![image](https://cloud.githubusercontent.com/assets/25787395/23779272/71d29b12-057a-11e7-84df-fdb45089a68a.png)
现在没有数据时留下两个线框没有无数据提示了

**Comment by pissang** [comment]
去掉了

**Comment by 18706745275** [comment]
那有什么替代方案吗？请问
