### ISSUE TITLE
echarts3.0  气泡大小自适应问题

### ISSUE THREAD

**Issue by zhuangdize** [apache/incubator-echarts#5247]
### One-line summary [问题简述]
如图所示数值太大只无法自适应

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
这里是 echarts 2.0 版本的截图 --- 效果正常
![image](https://cloud.githubusercontent.com/assets/10000643/23839774/53163ebe-07db-11e7-9838-c47e65edc688.png)

### Other comments [其他信息]

希望这个气泡的大小能根据气泡当中的数值长度来进行自动变化， 比如说 我输入10000000的值，也希望气泡能包住这个值，echarts2.0版本的正常
（目前文档上没有找到相关配置项, symbolSize选项貌似只能改变固定大小 ）

 
![image](https://cloud.githubusercontent.com/assets/10000643/23839607/3c7bad84-07da-11e7-826c-4cf0ce754bc9.png)

**Comment by pissang** [comment]
label.position 改为 top

**Comment by zhuangdize** [comment]
这一个配置项似乎跟大小无关吗 这个定位的

**Comment by pissang** [comment]
嗯，自适应没法做，建议这么设置保证文本显示全

**Comment by zhuangdize** [comment]
echarts2.0 版本的却可以做到（官方demo）,  这是为什么呢
http://echarts.baidu.com/echarts2/doc/example/line1.html

**Comment by pissang** [comment]
2 也一样啊
