### ISSUE TITLE
echarts3 zrender设置rotation的中心坐标无效

### ISSUE THREAD

**Issue by tonyhao01** [apache/incubator-echarts#5252]
### One-line summary [问题简述]
                       var rect = new Rect({
						id: 'q_rect' + ql_count,
						style: {
							// smoothConstraint: [[-Infinity, -Infinity], [200, Infinity]],
							fill: 'rgba(220, 20, 60, 0)',
							stroke: "rgba(220, 20, 60, 1)",
							lineWidth: 2,

						},

						shape: {
							r: 0,
							x: test.x,
							y: test.y,
							width: test.width,
							height : test.height,
						},
						draggable : true,
						rotation : [0.2,180,120],
						});
						zr.add(rect);

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts3
+ Browser version [浏览器类型和版本]: all
+ OS Version [操作系统类型和版本]: windows

### Expected behaviour [期望结果]
矩形以180,120为中心点旋转0.2,实际页面无效果

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有一个单独的 origin 属性

**Comment by tonyhao01** [comment]
十分感谢，已解决。

**Comment by tonyhao01** [comment]
还有个问题请教下，zrender 2中modshape()这个方法在新版本中还有吗？

**Comment by tonyhao01** [comment]
还有新绘制的旋转矩形框拖动以后消失，是什么原因呢？

**Comment by pissang** [comment]
modShape 去掉了，设置属性统一用图形自己的 attr 方法，消失这个问题有具体代码么？

**Comment by tonyhao01** [comment]
if(typeof target_Obj != 'undefined' && target_Obj != null) { //target_Obj选中的目标对象（矩形边框）
				origin++;//旋转度数
				var coord = zr.storage._elements[target_Obj.id].transformCoordToLocal(target_Obj.shape.x, target_Obj.shape.y);
				zr.remove(zr.storage._elements[target_Obj.id]);//因为没找到之前modshape()这个函数只能先删掉再重新绘制
				var rect = new Rect({
							id : target_Obj.id,
							style: {
								// smoothConstraint: [[-Infinity, -Infinity], [200, Infinity]],
								fill: 'rgba(220, 20, 60, 0)',
								stroke: "rgba(220, 20, 60, 1)",
								lineWidth: 2
							},
							shape: {
								r: 0,
								x: coord[0],
								y: coord[1],
								width: target_Obj.shape.width,
								height : target_Obj.shape.height,
							},
							draggable : true,
							rotation : [origin],
							origin: [target_Obj.shape.x + target_Obj.shape.width/2, target_Obj.shape.y + target_Obj.shape.height/2],
							});
						zr.add(rect);
				}
---------------------------------------------------以上是代码------------------------
当新的矩形框绘制出来以后进行拖拽后，该矩形框像是不未在当前画布上，或者是我没有设置更新后的坐标？发生偏移？

**Comment by ssjtbcf** [comment]
> ```js
> if(typeof target_Obj != 'undefined' && target_Obj != null) { //target_Obj选中的目标对象（矩形边框）
> 				origin++;//旋转度数
> 				var coord = zr.storage._elements[target_Obj.id].transformCoordToLocal(target_Obj.shape.x, target_Obj.shape.y);
> 				zr.remove(zr.storage._elements[target_Obj.id]);//因为没找到之前modshape()这个函数只能先删掉再重新绘制
> 				var rect = new Rect({
> 							id : target_Obj.id,
> 							style: {
> 								// smoothConstraint: [[-Infinity, -Infinity], [200, Infinity]],
> 								fill: 'rgba(220, 20, 60, 0)',
> 								stroke: "rgba(220, 20, 60, 1)",
> 								lineWidth: 2
> 							},
> 							shape: {
> 								r: 0,
> 								x: coord[0],
> 								y: coord[1],
> 								width: target_Obj.shape.width,
> 								height : target_Obj.shape.height,
> 							},
> 							draggable : true,
> 							rotation : [origin],
> 							origin: [target_Obj.shape.x + target_Obj.shape.width/2, target_Obj.shape.y + target_Obj.shape.height/2],
> 							});
> 						zr.add(rect);
> 				}
> ```
> 
> ---------------------------------------------------以上是代码------------------------ 当新的矩形框绘制出来以后进行拖拽后，该矩形框像是不未在当前画布上，或者是我没有设置更新后的坐标？发生偏移？

绘制新的图形后，更新新的origin坐标了吗
