### ISSUE TITLE
click事件参数在移动端无法获取手势点击位置，如何获取

### ISSUE THREAD

**Issue by zxxyyxf** [apache/incubator-echarts#5254]
### One-line summary [问题简述]

click事件参数在移动端无法获取手势点击位置，在web页面我是通过[params.event.event.pageX,params.event.event.pageY]获取的鼠标点击位置。在手机端这个坐标值为0。请问如何在手机端获取手势点击位置的坐标

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.2.2
+ Browser version [浏览器类型和版本]:chromium
+ OS Version [操作系统类型和版本]:android 4.4.2

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

this.myChart.on('click', U.hitch(this, function(params)
            {
              //......
                var mouseEvent = params.event.event;
                this.menu.show(params, [ mouseEvent.pageX, mouseEvent.pageY ]);
            }));

**Comment by pissang** [comment]
e.offsetX, e.offsetY ？
