### ISSUE TITLE
Y轴超出如何隐藏？

### ISSUE THREAD

**Issue by licc779885** [apache/incubator-echarts#5267]
![index_2](https://cloud.githubusercontent.com/assets/26050272/23891684/7ae97134-08d2-11e7-8ac0-b88792a05af6.png)

**Comment by pissang** [comment]
隐藏后反而不好吧？

**Comment by qingming418** [comment]
如果y轴的值很大，比如3.2499340543206746e+38呢？echarts3.0会报错
