### ISSUE TITLE
markLine label position and offset should be same as for markPoint

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#5270]
Version: 3.4.0

Just noticed that: 

```
markLine:{
    label:{
        offset:[10,10]
    }
}
```

doesn't work, where same works for markPoint:label..

Would be also nice if position can be set similarly to markPoint's so it would accept number, % values etc. Currently markLine's label only supports start, middle, end.

**Comment by KevisLuo** [comment]
any update for this?

**Comment by chengwuchao** [comment]
any update for this?
