### ISSUE TITLE
Two questions related to style??

### ISSUE THREAD

**Issue by akkaraman** [apache/incubator-echarts#5272]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: Opera 43
+ OS Version [操作系统类型和版本]: Win10

### Expected behaviour [期望结果]

Hi.
I have two responsibilities.

1- How can Max and min be selected in the map graphs as the number one screen image? It looks bigger than normal.

2- How can I change the color of the info box on the other screen display. I would like to make the background color light gray.

Thank you.

1-
![1](https://cloud.githubusercontent.com/assets/5848790/23929815/2d004754-0931-11e7-886f-fb15fdebc67d.PNG)

2-
![2](https://cloud.githubusercontent.com/assets/5848790/23929816/2d071160-0931-11e7-8b2f-abdee8afb858.PNG)

**Comment by akkaraman** [comment]
ToolTip I can not change the background color. Can you tell me how?
For example ", backgroundColor: {default: '# 234'}"

**Comment by pissang** [comment]
`backgroundColor: '#234'`
