### ISSUE TITLE
关于移动端适配

### ISSUE THREAD

**Issue by u3u** [apache/incubator-echarts#5274]
能否根据 `dpr` 适配？比如使用手淘 `flexible.js` 页面会缩放 `0.5` 倍 就会导致图表比例不正常
``` html
<meta name="viewport" content="initial-scale=0.5, maximum-scale=0.5, minimum-scale=0.5, user-scalable=no">
```

**Comment by YuAoi** [comment]
试了一下，不可以。还是强设为1了！

**Comment by u3u** [comment]
@YuAoi 哎 `flexible.js` 哪都好就是不兼容第三方库 想用第三方库就只能放弃高清解决方案了 目前都是用 `px`

**Comment by lanpangzhi** [comment]
我试过zoom       3倍的时候图表有些模糊

**Comment by lanpangzhi** [comment]
然后 dpr 不等于1的时候   图表那些点击功能都没有了
