### ISSUE TITLE
雷达图加载完成事件

### ISSUE THREAD

**Issue by coolman2135** [apache/incubator-echarts#5291]
### One-line summary [问题简述]

你好，我想请问下，echart中没有渲染图片结束的回掉接口吗？我渲染了一个雷达图以后，怎么才知道已经渲染结束呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
setOption 后就立刻渲染了

**Comment by githubxiaowen** [comment]
@pissang ,官方示例中的图标生成时间是怎么样计算出来的啊，有没有事件回调可以计算？

**Comment by coolman2135** [comment]
但是渲染后，直接保存图片，只有背景，没有数据的图线


发自我的 iPhone

**Comment by pissang** [comment]
你贴下具体代码以及 echarts 的版本号
