### ISSUE TITLE
When using dual y-axis, any way I can keep them same splitNumbers and avoid the double splitLine?

### ISSUE THREAD

**Issue by codTango** [apache/incubator-echarts#5292]
### One-line summary [问题简述]
When using dual y-axis, if the scale of lines are diverged differently, sometimes the left and right y-axis will have different number of ticks and labels, and will display two splitLines for left and right y-axis separately.
<img width="1218" alt="screen shot 2017-03-17 at 9 28 51 am" src="https://cloud.githubusercontent.com/assets/5359697/24047567/81b4f052-0afc-11e7-93ba-b6af60e6c57c.png">

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: latest Chrome
+ OS Version [操作系统类型和版本]: Mac OS

### Expected behaviour [期望结果]
Hope there's a way that I can force the two y-axis having same splitNumber and using the same splitLine.

**Comment by mangoZT** [comment]
Maybe you can use the max and min to control ，What do you think of this method?

**Comment by prempopatia** [comment]
is there any way to do that whats asked in question when data are loaded dynamically and doesnt have same unit on y axis?

**Comment by allanpope** [comment]
I've ran into this situation to. I solved it by removing the line on one axis and keeping it on the other. Would be nice if you could scale it the same

**Comment by susiwen8** [comment]
Actually, this feature is ongoing. #13210
