### ISSUE TITLE
echarts-2.2.7 热力图更改热力值无效

### ISSUE THREAD

**Issue by vasttian** [apache/incubator-echarts#5307]
### One-line summary [问题简述]
echarts2 使用热力图时，更改热力图的heatmap.data某个位置对应的热力值，热力图无变化。
查看源码（L30280）：
var len = data.length;
                        for (var id = 0; id < len; ++id) {
                            data[id] = this.geo2pos(mapType, [
                                geoData[id][0],
                                geoData[id][1]
                            ]);
                        }
好像只取了位置的地理坐标，并没有取相应位置的热力值去渲染。(添加热力值到data里data[id][2] = geoData[id][2];可根据热力值正常渲染)
导致的问题就是两个热力图只要数据的地理坐标完全相同，后面每个位置的热力值不同时，
渲染出来的热力图却是一样的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts-2.2.7
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:
win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/17924984/24099390/e5db1674-0da9-11e7-994f-7cd4173cf32e.png)
![image](https://cloud.githubusercontent.com/assets/17924984/24099393/f1222bee-0da9-11e7-9ead-a9fb967b54ab.png)

**Comment by pissang** [comment]
推荐 3 的热力图
