### ISSUE TITLE
echarts waterfall error 瀑布图示例错误

### ISSUE THREAD

**Issue by kevinABCD** [apache/incubator-echarts#5308]
### One-line summary [问题简述]
![default](https://cloud.githubusercontent.com/assets/26544780/24100927/3ab52d54-0db1-11e7-8fce-0ce48324c3a8.png) 数据源【-200,-120,-100,228,150,135,178,286,-119,-361,-203】无法实现图中效果，【demo中的瀑布图无法适应支出值为负数且绝对值大于辅助值】，正负交叉会出现问题

**Comment by vasu-vvp** [comment]
Trying to achieve the same with echarts, But not able to find the exact way. I tried this with bar chart by hiding the base series but in case when value is falling from 400 position by -800 then how to draw the bar of "800" which is from +400 to -400.

for example refer image. I want somethis similar to this.
![waterfall](https://user-images.githubusercontent.com/30551082/46273715-5358b200-c574-11e8-96a7-d341cee6fb08.png)

**Comment by sjcobb** [comment]
I am having the same issue trying to implement a waterfall chart as well as a floating bar chart where a single bar has to span the origin starting at a negative value and ending at a positive value.
@Ovilia Is there any workaround for this?

**Comment by natee** [comment]
Any ideas on this ? @Ovilia

**Comment by helgasoft** [comment]
working in v.5.4.3 - [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiC8AEDaC0AmADMgNPAjCjnVsUQA41MBWdTAZjNIHYTiA2XTATgyqcwxSoF0A3AChgAZwCuAWxixkQ6JJnIRoCADopIAA4AKAG7RIAPmgBvRdOgBqGPsHRx09doliAFrqUBKBwF9vYWEAe20wAEtggDsjc2FoaAiwABsAUwAuOISEsFSADzBMgHIAdXBUgCcAMxBk5OgAYXcQCrAi-Og_NA68gEE88LFMizAAT20M6CKAY3KAc2CK0aK0aBABsQAZEAAjVOT0sw9ggHd0muSxVL9O7oTR_sHh246rivDUobgOhLMf7KiICkkyKAAVkiBpql3MFksBKit_jlxiCdi1EdlsmIINMANbFAAqwQgyQxmOg4VyUgAymM0sMkdkdot4RUGrDFsUwBUQFExNoWqkom07uSEtMORUuTy-QKKkK2oyuozUlJtM0xE8smKKVTaaN6dqddBmRVWezkpyptzefzBcKycaJZapdaZXb5Q7GQk_ErRZi1CBMk4pP6sTjcbSebk5qNirVSf9lZi_mLAcDioHHdkxhNimiKtmEtjIfipkSSUXFBGo_M41ME1XA8HwCBVoyIXsDkbycczokKhJUmHMdpgpqItFiuE-eF4e0xcnyZTVfrDRZnVbDCZzPKwBIKjF9Op9LUh8ZkNAAPxTfSRNJtaDFRa8uapIp-Jc-jr8YR-QRAA).

![image](https://github.com/apache/echarts/assets/13038071/8e7f3b95-f39a-4ae1-9ad0-8600b5ee6aff)

**Comment by wmb0412** [comment]
> working in v.5.4.3 - [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiC8AEDaC0AmADMgNPAjCjnVsUQA41MBWdTAZjNIHYTiA2XTATgyqcwxSoF0A3AChgAZwCuAWxixkQ6JJnIRoCADopIAA4AKAG7RIAPmgBvRdOgBqGPsHRx09doliAFrqUBKBwF9vYWEAe20wAEtggDsjc2FoaAiwABsAUwAuOISEsFSADzBMgHIAdXBUgCcAMxBk5OgAYXcQCrAi-Og_NA68gEE88LFMizAAT20M6CKAY3KAc2CK0aK0aBABsQAZEAAjVOT0sw9ggHd0muSxVL9O7oTR_sHh246rivDUobgOhLMf7KiICkkyKAAVkiBpql3MFksBKit_jlxiCdi1EdlsmIINMANbFAAqwQgyQxmOg4VyUgAymM0sMkdkdot4RUGrDFsUwBUQFExNoWqkom07uSEtMORUuTy-QKKkK2oyuozUlJtM0xE8smKKVTaaN6dqddBmRVWezkpyptzefzBcKycaJZapdaZXb5Q7GQk_ErRZi1CBMk4pP6sTjcbSebk5qNirVSf9lZi_mLAcDioHHdkxhNimiKtmEtjIfipkSSUXFBGo_M41ME1XA8HwCBVoyIXsDkbycczokKhJUmHMdpgpqItFiuE-eF4e0xcnyZTVfrDRZnVbDCZzPKwBIKjF9Op9LUh8ZkNAAPxTfSRNJtaDFRa8uapIp-Jc-jr8YR-QRAA).使用 v.5.4.3 -[演示代码](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiC8AEDaC0AmADMgNPAjCjnVsUQA41MBWdTAZjNIHYTiA2XTATgyqcwxSoF0A3AChgAZwCuAWxixkQ6JJnIRoCADopIAA4AKAG7RIAPmgBvRdOgBqGPsHRx09doliAFrqUBKBwF9vYWEAe20wAEtggDsjc2FoaAiwABsAUwAuOISEsFSADzBMgHIAdXBUgCcAMxBk5OgAYXcQCrAi-Og_NA68gEE88LFMizAAT20M6CKAY3KAc2CK0aK0aBABsQAZEAAjVOT0sw9ggHd0muSxVL9O7oTR_sHh246rivDUobgOhLMf7KiICkkyKAAVkiBpql3MFksBKit_jlxiCdi1EdlsmIINMANbFAAqwQgyQxmOg4VyUgAymM0sMkdkdot4RUGrDFsUwBUQFExNoWqkom07uSEtMORUuTy-QKKkK2oyuozUlJtM0xE8smKKVTaaN6dqddBmRVWezkpyptzefzBcKycaJZapdaZXb5Q7GQk_ErRZi1CBMk4pP6sTjcbSebk5qNirVSf9lZi_mLAcDioHHdkxhNimiKtmEtjIfipkSSUXFBGo_M41ME1XA8HwCBVoyIXsDkbycczokKhJUmHMdpgpqItFiuE-eF4e0xcnyZTVfrDRZnVbDCZzPKwBIKjF9Op9LUh8ZkNAAPxTfSRNJtaDFRa8uapIp-Jc-jr8YR-QRAA)。
> 
> ![image](https://github.com/apache/echarts/assets/13038071/8e7f3b95-f39a-4ae1-9ad0-8600b5ee6aff)

You are an angel.
