### ISSUE TITLE
用echarts写了一个海南岛的地图，怎么添加南海诸岛到右下角

### ISSUE THREAD

**Issue by 853591143** [apache/incubator-echarts#5313]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ly6cyh** [comment]
弄两个div，分别实现地图功能，第二个div固定在右下角，可以设置背景图片

**Comment by 853591143** [comment]
谢谢！
