### ISSUE TITLE
echarts3官网的成都市地图json和js的都有问题，用不了。

### ISSUE THREAD

**Issue by 18706745275** [apache/incubator-echarts#5329]
### One-line summary [问题简述]
绘制成都市地图时，下载官网提供的成都.json,报错，地图无法显示出来。引入成都js也报错，换成攀枝花的json、西安的json都能正确显示地图。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:google
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
请替换官网给的成都市地图json和js，非常感谢！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by iamziyue** [comment]
看这个：http://www.cnblogs.com/wanglaowu/p/6118553.html
说是官网成都市数据缺少一部分，导致比例不正常。
