### ISSUE TITLE
echarts的地图2版本的params打印出来的结果为： undefined

### ISSUE THREAD

**Issue by 56651971** [apache/incubator-echarts#5330]
echarts的地图2版本的
formatter: 
function(params) {
console.log(params)
}()
打印出来的结果为： undefined，要怎么解决？谢谢！
官方实例：http://echarts.baidu.com/echarts2/doc/example/map11.html

**Comment by pissang** [comment]
换成 3

**Comment by 56651971** [comment]
因为想要2的那种动画效果，不换版本可以解决吗

**Comment by pissang** [comment]
那就没办法了
