### ISSUE TITLE
有没有一篇指导性的文章教大家如何从源码编译打包echarts

### ISSUE THREAD

**Issue by smcdl** [apache/incubator-echarts#5331]
### One-line summary [问题简述]
我在各种网站资源里都没找到如何从源码编译打包一份echarts，我自己从github上clone了一份源码，但用webpack编译各种错误，是否能提供这样的一篇文章让大家学习学习？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
参考这个：https://github.com/ecomfe/echarts-liquidfill/blob/gh-pages/webpack.config.js

**Comment by peter-wang-wsl** [comment]
@Ovilia 请问我把github上的工程下载后，如何在本地dist目录生成基于master的echarts.js?
