### ISSUE TITLE
请问echarts能画出带圆点的引导线饼图吗

### ISSUE THREAD

**Issue by semdy** [apache/incubator-echarts#5335]
如题。
![default](https://cloud.githubusercontent.com/assets/9401913/24235318/a4fe2774-0fd7-11e7-8005-b17f18f4ec4b.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: Chrome 56
+ OS Version [操作系统类型和版本]: win10 x64

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行
