### ISSUE TITLE
如何实现Y轴0-最大值的5等分

### ISSUE THREAD

**Issue by licc779885** [apache/incubator-echarts#5338]
如图，我的0-最大值时最上面的只是会被截掉的感觉，Y轴的数据也根据最大值进行5等分，不需要100的整数
![index_2](https://cloud.githubusercontent.com/assets/26050272/24237383/01cb0446-0fe1-11e7-80fe-2abab1b862e2.png)

**Comment by pissang** [comment]
可以设置 interval
