### ISSUE TITLE
It would be nice if brush has handles similarly to dataZoom

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#5341]
Version: 3.4.0

Since brush sides are active, it would be nice if brush sides can be styled similarly to handles in dataZoom. This is lineX example: 

![image](https://cloud.githubusercontent.com/assets/561365/24245842/d0ffb008-0fc4-11e7-8620-420d1605849a.png)

**Comment by zakjan** [comment]
+1

**Comment by zakjan** [comment]
Closing without feedback? :(

**Comment by Epictek** [comment]
Bump? I would be intrested working on this with a few pointers as someone not too familar with the code base

**Comment by Uular** [comment]
This would be a useful feature UX-wise. Currently there is little to no indication to a user that the brush is draggable from its sides.

**Comment by 14glwu** [comment]
any updates? I also need this feature.

**Comment by armandleopold** [comment]
Up

**Comment by yulafezmesi** [comment]
is anyone achieve this?
