### ISSUE TITLE
y坐标轴标题（name）文字位置不能相对于y轴居左的问题

### ISSUE THREAD

**Issue by BeAce** [apache/incubator-echarts#5346]
### One-line summary [问题简述]
Y轴`yaxis`中`name`的属性只有垂直位置（`nameLocation`）属性，没有水平位置的设置。希望能够文字居左显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: Chrome 版本 56.0.2924.87 (64-bit)
+ OS Version [操作系统类型和版本]: MAC OS 10.12.3

### Expected behaviour [期望结果]

希望到Y轴标题能够相对于坐标轴居左显示。

### ECharts option [ECharts配置项]

```javascript
option = {
  yAxis: {
        min: 0,
        max: 40,
        type: 'value',
        left: 0,
        axisLine: {onZero: false},
        name: "名字很长很长很长很长很长很长很长很长很长很长很长很长",
        nameLoaction: "center"‘
  },
}

```

**Comment by OnlyAttacker** [comment]
分析了一下代码发现axisName的nameRotate属性是不是根据axisName的中心做的旋转，所以使用nameRotate:0.1来做一下旋转就可以使axisName居左显示。
option = {
  yAxis: {
        min: 0,
        max: 40,
        type: 'value',
        left: 0,
        axisLine: {onZero: false},
       **nameRotate:0.1,//使用这个属性**
        name: "名字很长很长很长很长很长很长很长很长很长很长很长很长",
        nameLoaction: "center"
  },
}

**Comment by cwjie0229** [comment]
这个怎么解决？y坐标轴标题（name）文字位置不能相对于y轴居左的问题

**Comment by BeAce** [comment]
都说了旋转0.1

**Comment by 100pah** [comment]
设置为：
`nameLocation: 'middle'`

**Comment by Arguiwu** [comment]
多谢  之前一直使用 grid.left 来让name显示完整

**Comment by github-zhang** [comment]
**nameRotate: -0.1**  我这边是 ~~~

**Comment by surplus-cat** [comment]
nameRotate 的单位不是px吧，而且设置成0.1和1 效果都是一样的，需求是要求和legend 左对齐，发现只能通过加空格对齐。

**Comment by Alen-Huan** [comment]
nameRotate: -0.1 我也是，-0.1有效

**Comment by Abbyyan** [comment]
nameRotate:-0.1之后单位会和纵坐标重叠，请问应该怎么设置呢？多谢
