### ISSUE TITLE
地图数据在线生成工具的问题

### ISSUE THREAD

**Issue by niuniuLYH** [apache/incubator-echarts#5355]
### One-line summary [问题简述]
在地图数据在线生成工具中，海南省的很多市都都只能生成仅包括所选区域的外围轮廓，而不能生成包括所选区域的外围轮廓, 以及内部子区域轮廓 (对于 "区县" 粒度的区域, 默认仅生成外轮廓)，选择是的时候，页面js会报错，导致没有任何响应

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts 3
+ Browser version [浏览器类型和版本]:chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]:windows10 家庭中文版

### Expected behaviour [期望结果]
能够生成海南省各市的地图数据，并且包括所选区域的外围轮廓, 以及内部子区域轮廓 (对于 "区县" 粒度的区域, 默认仅生成外轮廓)。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
报什么错？

**Comment by niuniuLYH** [comment]
![报错信息](http://ongbu23mm.bkt.clouddn.com/error.png)
![选择类型](http://ongbu23mm.bkt.clouddn.com/mapgen.png)
