### ISSUE TITLE
广西壮族自治区贺州市地图显示太小

### ISSUE THREAD

**Issue by 361028096** [apache/incubator-echarts#5359]
### One-line summary [问题简述]
从官网上构建的贺州市地图，构建、下载json文件后，显示出来的地图很小

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: eharts3
+ Browser version [浏览器类型和版本]: chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
正常大小

**Comment by pissang** [comment]
请给出配置项以及“很小”的截图

**Comment by 361028096** [comment]
![hezhou](https://cloud.githubusercontent.com/assets/8761096/24346499/2e6d3d92-1307-11e7-8207-b8543c17c357.jpg)

配置项：
    $.get('../map/hezhou2.json', function (hubeiJson) {
    echarts.registerMap('hezhou2', hubeiJson);
    var chart = echarts.init(document.getElementById('main'));
    chart.setOption({
        series: [{
            type: 'map',
            map: 'hezhou2'
        }]
    });

**Comment by 361028096** [comment]
@pissang
麻烦帮忙看一下，谢谢

**Comment by rubbishquan** [comment]
@pissang 这个问题应该是广西壮族自治区贺州市的某个区地图挂掉了，该区coordinates为空导致整个市的地图都缩得很小，还有遵义市、淮安市发现了这个问题。
