### ISSUE TITLE
Created a few new theme files for ECharts 3.0 - blue, green, red, etc.

### ISSUE THREAD

**Issue by WebCodePro719** [apache/incubator-echarts#5360]
I've created a few new theme files for ECharts 3.0 - There are currently six themes available for download (http://echarts.baidu.com/download-theme.html). I used the themes code from ECharts 2.0 to create these additional themes for ECharts 3.0: blue, gray, green, helianthus, macarons2, mint, red, and sakura.

I've also updated the ECharts JavaScript file so that the title tags are in English. Below is a zip file with default themes, additional themes, and a few example charts for ECharts 3.0. I hope these additional theme files are helpful.

[echarts3-extra-themes.zip](https://github.com/ecomfe/echarts/files/871290/echarts3-extra-themes.zip)

**Comment by pissang** [comment]
Great!  Thanks @WebCodePro719

**Comment by WebCodePro719** [comment]
Here's a few more themes for ECharts 3.0 - Attached is a zip file with theme JS files and example charts (in English). I also created a collection for these custom themes on CodePen: https://codepen.io/collection/AZpNzK/
[echarts-3-custom-themes.zip](https://github.com/ecomfe/echarts/files/888780/echarts-3-custom-themes.zip)
