### ISSUE TITLE
echars3点击按钮怎么实现地图的放大缩小

### ISSUE THREAD

**Issue by SonicAdvan** [apache/incubator-echarts#5366]
### One-line summary [问题简述]
echars2中的roamController配置参数在echar3中具体体现为什么？我怎么在echar3中实现roamController这个方法。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.0
+ Browser version [浏览器类型和版本]:谷歌56
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mangoZT** [comment]
改变zoom属性
