### ISSUE TITLE
使用echarts-all.js绘制页面，定时刷新数据，大半天时间，页面就奔溃了

### ISSUE THREAD

**Issue by princessJoanna** [apache/incubator-echarts#5368]
//随机飞往不同的城市
function changeMap() {
    const Hours = new Date().getHours();
    if (Hours >= 8 && Hours <= 20) {
       
    }
     changeChiaMap(getMaxRandom(1), 1);
    setTimeout('changeMap()', 3000);
}

function changeChiaMap(item, cityNum) {
    var arr = [],
        fromcCity = '',
        cityList = [
            '上海',
            '东莞',
            '东营',
            '中山',
            '临汾',
            '临沂',
            '丹东',
            '丽水',
            '乌鲁木齐',
            '佛山',
            '保定',
            '兰州',
            '包头',
            '北京',
            '北海',
            '南京',
            '南宁',
            '南昌',
            '南通',
            '厦门',
            '台州',
            '合肥',
            '呼和浩特',
            '咸阳',
            '哈尔滨',
            '唐山',
            '嘉兴',
            '大同',
            '大连',
            '天津',
            '太原',
            '威海',
            '宝鸡',
            '宿迁',
            '常州',
            '广州',
            '廊坊',
            '延安',
            '张家口',
            '徐州',
            '德州',
            '惠州',
            '成都',
            '扬州',
            '承德',
            '拉萨',
            '无锡',
            '日照',
            '昆明',
            '杭州',
            '枣庄',
            '柳州',
            '株洲',
            '武汉',
            '汕头',
            '江门',
            '沈阳',
            '沧州',
            '河源',
            '泉州',
            '泰安',
            '泰州',
            '济南',
            '济宁',
            '海口',
            '淄博',
            '淮安',
            '深圳',
            '清远',
            '温州',
            '渭南',
            '湖州',
            '湘潭',
            '滨州',
            '潍坊',
            '烟台',
            '玉溪',
            '珠海',
            '盐城',
            '盘锦',
            '石家庄',
            '福州',
            '秦皇岛',
            '绍兴',
            '聊城',
            '肇庆',
            '舟山',
            '苏州',
            '莱芜',
            '菏泽',
            '营口',
            '葫芦岛',
            '衡水',
            '衢州',
            '西宁',
            '西安',
            '贵阳',
            '连云港',
            '邢台',
            '邯郸',
            '郑州',
            '鄂尔多斯',
            '重庆',
            '金华',
            '铜川',
            '银川',
            '镇江',
            '长春',
            '长沙',
            '长治',
            '阳泉',
            '青岛',
            '韶关',
            '佛山'
        ],
        cityList_length = cityList.length;
    item == 0 ? fromcCity = '宁波' : fromcCity = '佛山';
    optionList.chinaMap.series[0].markLine.data = [];
    optionList.chinaMap.series[1].markLine.data = [];
   

    for (var i = 0; i < cityNum; i++) {
        var value = [{ name: fromcCity, smoothness: Math.random() }, { name: cityList[getMaxRandom(cityList_length)], value: getMaxRandom(100) }];
        arr.push(value);
    }
    optionList.chinaMap.series[item].markLine.data = arr;
     chartList.chinaMap.clear();
    chartList.chinaMap.setOption(optionList.chinaMap,false,false);
}

### One-line summary [问题简述]
隔断时间刷新下数据，每次更新数据前有clear图标，但是从早上9点到下午2点左右，页面就会奔溃。求解！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请定位到具体问题后再反馈，给出具体的版本号，如何复现
