### ISSUE TITLE
china地图散点图，服务器实时向前端推送数据，跑24小时左右，浏览器崩溃了，内存不足

### ISSUE THREAD

**Issue by hookou** [apache/incubator-echarts#5374]
### One-line summary [问题简述]
china地图散点图，服务器实时向前端推送数据，实时更新在地图上，页面一直打开状态，代码跑24小时左右，浏览器就崩溃了，Google chrome在尝试打开页面时内存不足，把内存跑满了，寻求帮助

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: ECharts3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:window

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能具体描述你的环境，问题，及代码么？
