### ISSUE TITLE
Is the value label on axis when using cross type tooltip a new feature?

### ISSUE THREAD

**Issue by codTango** [apache/incubator-echarts#5380]
### One-line summary [问题简述]
I just saw the value label thing on y and x axises on the echarts demos, so I tried the cross type, but it doesn't work for me. Is this a new feature? If so, when I can get it? If not, do I need any special set up? BTW, it's so fancy, exactlly the feature we're looking for.
![screen shot 2017-03-28 at 5 27 51 pm](https://cloud.githubusercontent.com/assets/5359697/24428376/4931ce9c-13dc-11e7-841e-994e71e4c8da.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.5.1
+ Browser version [浏览器类型和版本]: latest Chrome
+ OS Version [操作系统类型和版本]: Mac OS

**Comment by 100pah** [comment]
Ye, it is a new feature since 3.5.0.
If it doesn't work for you, may I have your `option` to diagnose it?

**Comment by codTango** [comment]
OK, thanks. It works, I just need to blow away the whole node_package and reinstall.
