### ISSUE TITLE
如何获取图标组件内动态计算出来的yAxis的最大值

### ISSUE THREAD

**Issue by dodospace** [apache/incubator-echarts#5385]
### One-line summary [问题简述]

根据示例，在柱状图里，我要模拟一个透明的点击区域。但是必须要知道Y轴根据series里的数据算出来的刻度最大值，否则会导致透明区域不饱满。我想知道echarts是否有提供这样的参数，或者是在哪个模块计算实现的。

### Version & Environment [版本及环境]
+ ECharts version [3.5.1]:
+ Browser version [所有]:
+ OS Version [所有]:

**Comment by HeNanBing** [comment]
charts.getModel().getComponent('yAxis', 0).axis.scale.getExtent()
