### ISSUE TITLE
echarts 只能设置图形的hover效果，能设置点击之后的效果吗？

### ISSUE THREAD

**Issue by zhangya5847** [apache/incubator-echarts#5389]
### One-line summary [问题简述]
用itemStyle中emphasis只能设置悬浮状态，能不能设置clicked状态？
在click的事件状态中，改变chart的颜色，有时候能成功，概率极低。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
echart 3.5.1
chrome latest
Mac

### Expected behaviour [期望结果]

期望能够不在click事件中设置，有属性直接设置。

### ECharts option [ECharts配置项]

```javascript
option = {
 tooltip: {},
        xAxis: {
          data: dataAxis,
          axisLabel: {
            textStyle: {
              color: '#000',
            },
          },
          axisTick: {
            show: false,
          },
          axisLine: {
            show: false,
          },
          splitLine: {
            show: false,
          },
          z: 10,
        },
        yAxis: {
          splitLine: {
            show: false,
          },
          axisLine: {
            show: false,
          },
          axisTick: {
            show: false,
          },
          axisLabel: {
            show: false,
          },
        },
        series: [
          {
            type: 'bar',
            itemStyle: {
              normal: {
                color: '#333',
              },
              emphasis: {
                color: '#9b9b9b',
              },
            },
            data: dataBar,
          },
        ],
}

chart.on('click', e => {
        e.color = '#d50000'
        e.event.target.style.fill = '#d50000'
      })

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/15855773/24445851/04fc0ae0-149e-11e7-9bb8-63e80d29c1d1.png)

**Comment by PalaChen** [comment]
chart.on('click', e => {
        e.color = '#d50000'
        e.event.target.style.fill = '#d50000'
      })
这一步只是更改了点击的参数，但是没有改变图表对应的柱子的颜色？请问你是怎么更改？

**Comment by zhangya5847** [comment]
当时查看文档的发现只有hover的效果，没有clicked的效果，所以我就在在点击事件中去手动修改了对应柱体的参数，但是测试下来，这并不是一个好办法。

**Comment by PalaChen** [comment]
我想问问怎么修改的颜色传送给option
然后再执行下面语句
myChat.setOption(option, true);
myChat.resize()

**Comment by zhangya5847** [comment]
没有改option里的颜色

**Comment by BreaBai** [comment]
柱子的颜色通过点击事件之后修改了吗

**Comment by BreaBai** [comment]
请问怎么修改的？

**Comment by zhangya5847** [comment]
触发点击时间之后，可以分发一个highlight的action，达到改变bar的颜色的效果。可以参考这个demo：[http://gallery.echartsjs.com/editor.html](url)

**Comment by peter-wang-wsl** [comment]
@zhangya5847 map3D的highlight不起作用，如何处理
