### ISSUE TITLE
关于世界地图，能否用geo country code？

### ISSUE THREAD

**Issue by hisune** [apache/incubator-echarts#5395]
例如中国，用cn，而不是China

https://zh.wikipedia.org/wiki/%E5%9C%8B%E5%AE%B6%E5%9C%B0%E5%8D%80%E4%BB%A3%E7%A2%BC

这样更加标准化

**Comment by pissang** [comment]
可以用 http://echarts.baidu.com/option.html#series-map.nameMap 属性转换
