### ISSUE TITLE
y轴数值显示bug问题反馈

### ISSUE THREAD

**Issue by lushuan** [apache/incubator-echarts#5403]
### One-line summary [问题简述]

柱状图y轴的数据原本是通过data中的数据按splitNumber划分值的不同，分值区间也不同，例如一组数据，87010,89634,325856,98998,12820最大值
是325856，在splitNumber ：1 时，y轴最大值数据在谷歌浏览器上显示的却是60,0000.000000001，而不是60,0000整数值。
请问这个y轴上方的值需要怎样约束成整数

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: Google Chrome	39.0.2171.71 (正式版本) m
+ OS Version [操作系统类型和版本]:  win7 企业版 64位

### Expected behaviour [期望结果]
希望y轴展示的值为整数，之前有一个数据最大值时468743，和其它小于该值得几个数，Y轴上展示的最大值为80,0000.0000000001通过调节splitNumber分割数
解决了，但发现其他的数据依然会出现这种情况

### ECharts option [ECharts配置项]

```javascript
option = {
  legend : {
				x : "center",
				data : [ ]
			},
//			backgroundColor : ['#00505A'],  
			tooltip : {
				trigger : "item",
				formatter : "{a},{b}：{c} 千伏安"
    		},
			calculable : false,
			xAxis : [{
				type : "category",
				axisTick : {show : false},
				axisLabel : {show : true, textStyle : {color : "#ffffff"}},
				axisLine:{lineStyle:{width:0}},
				data : []
			}],
			yAxis : {
				name : "（千伏安）        ",
				splitNumber : 1,
//				scale : true,  //脱离0值比例，放大聚焦在 _min,_max之间
				offset : 30,
				nameTextStyle : {
					color : '#ffffff'
				},
				axisTick : {show : false},
				axisLine:{lineStyle:{width:0}},
				type : "value",
				//坐标轴文本标签选项
				axisLabel : {
					textStyle : {color : '#ffffff'}
				},
				//分割线
				splitLine : { lineStyle:{color:['#2F335C']}}
			},
			series : [{
				name : "本年",
				type : "bar",
				//类目间柱形距离
				barCategoryGap : '80%',
				barGap : '20%',
				color:['#0F93F5'],  //浅绿
				itemStyle : {	
			            	//初始化效果
			            	normal : {
			        			label:{
			        				show:true,
			        				position:'top',
			        				textStyle:{color:'#FFF'}
			        			}
			            	}
			        	},
				data : []
			}]
}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/20624169/24536731/f45a6110-160e-11e7-8402-d70325bc48a3.png)

**Comment by kevin0614** [comment]
这个小数，时有时无，是不是缺少某个字段的约束了

**Comment by AntiMoron** [comment]
这是IEEE754浮点数表示法的问题。 有的数他是不能精准表示的，只能找能表示的最接近的数。 你应该找找看配置项里的format回调。

**Comment by kevin0614** [comment]
3Q@AntiMoron
