### ISSUE TITLE
echarts为什么resize后多了一个div？

### ISSUE THREAD

**Issue by lerambo** [apache/incubator-echarts#5408]
### One-line summary [问题简述]
我在一个页面中添加了多个div，并把echarts控件（柱形图、饼状图、地图...）放在对应的div中，设置定时轮番播放带有echarts控件的div。当我的窗口放生改变后，echarts控件的外层多出一个div。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:所有浏览器
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
echarts自适应的设置的div大小

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

方便的话，可以远程调试一下。谢谢。

### Other comments [其他信息]

![Uploading QQ图片20170331162530.png…]()

**Comment by pissang** [comment]
不方便，请详细描述你的问题
