### ISSUE TITLE
datazoom没有重置方法和取消选择方法吗？

### ISSUE THREAD

**Issue by zouliming** [apache/incubator-echarts#5411]
当用户选择“区域缩放”模式后，用户通过外部控件重新加载了数据源，这个时候依然是“区域放大后”的情况。
虽然我找了很多资料，可以通过restore的方法来恢复区域，但是依然是“区域缩放”模式，即拖拉依然有方框。

**有没有api支持可以还原区域缩放效果，并且取消区域选择模式呢？？？**

**Comment by cooljser** [comment]
I have the same problem.

**Comment by cooljser** [comment]
https://echarts.apache.org/zh/api.html#action.dataZoom.takeGlobalCursor
