### ISSUE TITLE
Can you please add OHLC chart (similar to Candlestick)?

### ISSUE THREAD

**Issue by mlvn23** [apache/incubator-echarts#5414]
### One-line summary [问题简述]

Please add support for OHLC chart. It's similar to candlestick. Here's a [photo](http://www.finvids.com/Content/Images/ChartPattern/Bar-Chart-Basics/BarChartOHLC.jpg) of how it looks. The left and right ticks can also adjust similar to how the candle body width is calculated. Here's the [Highcharts demo](http://www.highcharts.com/stock/demo/ohlc). Thanks!

**Comment by 100pah** [comment]
Check this please ~ <http://gallery.echartsjs.com/editor.html?c=xBJA0D_Ub-&v=1>

**Comment by mlvn23** [comment]
Yes, this looks great. When you add it in the main lib, maybe you can also add an option for the up and down colors similar to candlestick.
