### ISSUE TITLE
如何通过RequireJS加载使用主题？

### ISSUE THREAD

**Issue by chanwj** [apache/incubator-echarts#5424]
### One-line summary [问题简述]

我在Jupyter Notebook上用Python进行数据处理并生成图表，用内置的RequireJS来使用ECharts，但是不知道如何通过此方式加载使用别的主题，请问具体应该如何配置？

require.config({
         paths:{
            'echarts': 'JS',
            'theme': 'JS/theme'
         }
    });
    require(
            ['echarts','theme'],
            function (ec) {
                var myChart = ec.init(document.getElementById('index_risk'),'macarons');
......

这样配置是无效的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
什么版本的 echarts？

**Comment by chanwj** [comment]
@pissang 2和3都试过，都换不了主题……
不过，从昨天开始，不仅换不了主题，在Jupyter notebook里连基础图表都完全画不出来了，一片空白。不知道如何解决？

**Comment by pissang** [comment]
厄，不太清楚 Jupyter notebook 的使用，https://github.com/napjon/krisk 参考下这个？

**Comment by chanwj** [comment]
@pissang 嗯看过这个，不过封装的功能太少，无法满足需求……
看来还是导出到独立HTML页面比较好

**Comment by wow14051** [comment]
@chanwj notebook里面自带了requirejs, 所以可以用require整合echart3进入到notebook, 已经实现基本所有功能,还可以和Python共享变量,很好用.

**Comment by chanwj** [comment]
@wow14051 谢谢，我用的就是这种方法，可是在本地notebook就是没法画出图表……一样的代码，放到线上的Notebook就没问题，实在不知道怎么回事……
