### ISSUE TITLE
echarts地图内纹理填充

### ISSUE THREAD

**Issue by duanhaowei** [apache/incubator-echarts#5429]
### One-line summary [问题简述]
使用geo进行地图纹理填充，首先使用api里例子
geo.itemStyle.normal.color：new echarts.graphic.Pattern(
  imageDom, // 支持为 HTMLImageElement, HTMLCanvasElement，不支持路径字符串
  'repeat' // 是否平铺, 可以是 repeat-x, repeat-y, no-repeat
)
提示echarts.graphic.Pattern不存在，引入的是最新版的js包。

然后使用json方式可以填充，然而填充后纹理不正常，呈现模糊话，可能是背景没有被repeat造成的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.1
+ Browser version [浏览器类型和版本]: chrome56
+ OS Version [操作系统类型和版本]:w10

### ECharts option [ECharts配置项]

 
var piePatternSrc = 'base64编码太长了，你们自己补一个到这里。';

var piePatternImg = new Image();
piePatternImg.src = piePatternSrc;
var bgPatternImg = new Image();
bgPatternImg.src = bgPatternSrc;

option = {

    geo: {
        map: 'china',
        itemStyle: {
            normal: {
                borderColor: '#000',
                color: {
                        image: piePatternImg,
                        repeat: 'repeat'
                    },
            },

        }
    },
     
};

**Comment by duanhaowei** [comment]
@pissang   大神方便指教一下吗？

**Comment by mangoZT** [comment]
同问，在其他饼图等都是正常显示，在地图中会放大模糊   是需要进行其他设置么@pissang

**Comment by mangoZT** [comment]
@duanhaowei 朋友有研究出来结果么

**Comment by mangoZT** [comment]
![9iw 6v 62lxaiv8s wy n](https://cloud.githubusercontent.com/assets/26948222/24792204/99fb8ed2-1baf-11e7-90dd-ed1fadca1045.png)
![image](https://cloud.githubusercontent.com/assets/26948222/24792210/a29d3f54-1baf-11e7-897e-80a835cd0d17.png)
饼图可以正常设置  地图就会变形模糊@pissang

**Comment by duanhaowei** [comment]
@mangoZT  没有啊兄弟，普通cavans纹理填充是可以的。我怀疑这个要看echarts源码了，应该是处于优化考虑肯定在里面做了处理。

**Comment by dantelife** [comment]
@duanhaowei  哥们, 地图纹理填充解决了吗？

**Comment by duanhaowei** [comment]
@dantelife   没有，无法解决，于是我换了其他的方案。

**Comment by dantelife** [comment]
@duanhaowei 什么方案，方便告知吗？

**Comment by gaojinbo010** [comment]
@duanhaowei  可以分享下么

**Comment by duanhaowei** [comment]
@dantelife  @gaojinbo010   才看到通知，我记得上次的解决方案是放弃背景填充，让他背景透明，然后底下垫上一层DIV假装他有背景。

**Comment by dantelife** [comment]
@pissang 你好，请问这个bug，你们计划什么时候修复？

**Comment by xushimin** [comment]
图片填充是将整个地图都进行填充，不是特定区域，所以看起来是模糊的，但是也不知道整个地图填充的规律是什么

**Comment by eeeqxxtg** [comment]
scatter 纹理填充也是这个模糊的样子

**Comment by nuxio** [comment]
@pissang  4.2 版本也没有修复这个问题呢，有空解决一下吗？

**Comment by LittleBreak** [comment]
遇到同样的问题，很尴尬

**Comment by pearlwang1106** [comment]
遇到同样的问题，很尴尬

**Comment by Ovilia** [comment]
This problem has been fixed in #11272 .
[test/geoScatter.html](https://github.com/apache/incubator-echarts/blob/ef14099e4eb171e61e5d2e043a85aa3cbd0358c6/test/geoScatter.html) shows an example of how to use it.

**Comment by coderxsjah** [comment]
2022年了，地图背景纹理填充解决了吗？有没有人告诉我怎么解决的呀

**Comment by coderxsjah** [comment]
请问，纹理填充时，UV映射规律是怎么样的呀？是像CSS里一样，取同一像素位置的值使用吗

**Comment by coderxsjah** [comment]
实验出来了，其实就是把背景图按照原本大小放在平面上，然后echarts的geo框到哪部分，那部分就作为背景
![image](https://user-images.githubusercontent.com/38942623/173528551-d5642fb8-aee9-4c60-9fd5-4fe21eb84bc7.png)

**Comment by zhouzhili** [comment]
> 实验出来了，其实就是把背景图按照原本大小放在平面上，然后echarts的geo框到哪部分，那部分就作为背景 ![image](https://user-images.githubusercontent.com/38942623/173528551-d5642fb8-aee9-4c60-9fd5-4fe21eb84bc7.png)

这个示例能发下吗？纹理好难配
