### ISSUE TITLE
Toolbox API?

### ISSUE THREAD

**Issue by Nick74k** [apache/incubator-echarts#5431]
How to know/change toolbox mode programmatically?

Something like chart.SetToolBoxActiveMode('zooming') or like chart.SetToolBoxActiveMode('myOwnMode')?

I've added custom tool and at clicking it I need to deactivate other active tool (If exists) and activate (Make it glow) my own. Is it possible? And how to know current active tool?

ECharts 3.50

**Comment by BorisTB** [comment]
+1

**Comment by pchaganti** [comment]
👍
