### ISSUE TITLE
zrender新版中，textColor不起作用

### ISSUE THREAD

**Issue by tonyhao01** [apache/incubator-echarts#5432]
### One-line summary [问题简述]
var circle =new  CircleShape({
						id: c_text,
						z : 100,
                        position: [ params.offsetX ,params.offsetY],
                        scale: [1, 1],
                        shape: {
                            cx: 0,
                            cy: 0,
                            r: point_r
                        },
                        style: {
                            fill: point_fill,
							text :c_text,
							textColor : 'blue',
							textPosition :'top',
							stroke : point_stroke,
                        },
						draggable: true  ,
						//ondrag : updateStaticPoint,
                    });

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
textColor : 'blue',圆点的文本字体颜色是蓝色不起作用

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
用 textFill
