### ISSUE TITLE
markPoint特殊点标注中，支持用不同的标注类型对max和min分别进行标注吗？

### ISSUE THREAD

**Issue by majorcool** [apache/incubator-echarts#5436]
例如在折线图中，我要实现最大值标注显示在折线上方，最小值标注显示在折线下方，有什么好的方案吗？用echart能实现这种效果吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
每个标注都能通过 `symbol`，`symbolSize`, `symbolOffset` 设置自己的类型
