### ISSUE TITLE
新增树形+趋势图支持

### ISSUE THREAD

**Issue by siboli** [apache/incubator-echarts#5439]
### One-line summary [问题简述]
能否支持ROIC Tree或者Profit Tree，实现方式是用树形图配合每个节点的小Chart
在商业咨询行业是一个很好用的反应数据关系的图形
后面有举例一些例子，不一定要那么复杂，如果支持会很有价值

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![default](https://cloud.githubusercontent.com/assets/1142856/24745075/de9b521c-1ae6-11e7-92c9-4db298d0a9fe.png)
![default](https://cloud.githubusercontent.com/assets/1142856/24745141/12dc1f16-1ae7-11e7-8c68-3cdc4e554757.png)
![default](https://cloud.githubusercontent.com/assets/1142856/24745288/b8e64986-1ae7-11e7-9061-7400a1133df0.png)
![default](https://cloud.githubusercontent.com/assets/1142856/24745355/0371d4e8-1ae8-11e7-9462-ec18ea1a0b78.png)

**Comment by itDjango** [comment]
强烈希望 有这个功能

**Comment by crazyzhc98** [comment]
这个功能很有用啊，希望增加。

**Comment by HomeMango0310** [comment]
这个功能好，有的话可以解决很多实际问题了

**Comment by deqingli** [comment]
谢谢给我们反馈，理论上是可以加的，后续会调研下实际的可行性，如果可以，会考虑加上。

**Comment by deqingli** [comment]
你好，可以给一些具体的数据么，因为平时几乎接触不到商业数据，不太清楚数据是什么结构，我们一般基于数据想要表达的信息，设计新的可视化形式。
