### ISSUE TITLE
如何获取某个国家的各地区地图数据包？

### ISSUE THREAD

**Issue by hele10086** [apache/incubator-echarts#5445]
### One-line summary [问题简述]
echart 如何获取某个国家的各地区地图数据包（使用的是geo）？目前有细分地区的貌似只有中国，美国，那么一些小国家的地区地图数据如何能获取到呢？比如越南，朝鲜等小国家的地区地图

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这里有一些资源 https://www.statsilk.com/maps/download-free-shapefile-maps
