### ISSUE TITLE
Enable WebGL in some charts? 

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#5447]
I wonder whether WebGL can be used to accelerate some visualizations such as this one: 
http://metrocosm.com/global-immigration-map ?

Is this something on the list long term? :)

**Comment by pissang** [comment]
Thanks for the suggestion. Glad to tell you that we are developing [echarts-gl](https://github.com/ecomfe/echarts-x/tree/1.0) for 3d plots and WebGL acceleration. And 1.0.0-alpha will be released in this two weeks.

I have some shots on my twitter https://twitter.com/pissang1 . Hope you like it:)

**Comment by jarben** [comment]
WOW, made my day, this is going to be SUPER AWESOME! Really good stuff @pissang!
