### ISSUE TITLE
在设置xAxis的triggerEvent: true时，返回参数能否增加一个dataIndex

### ISSUE THREAD

**Issue by Miderfly** [apache/incubator-echarts#5453]
### One-line summary [问题简述]
在设置了xAxis的triggerEvent: true时，返回参数为中只有xAxisIndex，无法判断点击的是第几个数据，能否像series点击事件返回的参数一样，增加一个dataIndex

![2017](https://cloud.githubusercontent.com/assets/23021763/24794801/951c7f16-1bb9-11e7-96e1-bdb9bf457e70.png)
![201704](https://cloud.githubusercontent.com/assets/23021763/24794803/96b54786-1bb9-11e7-8d6c-093fe0f16129.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.2
+ Browser version [浏览器类型和版本]:Firefox 52.0.1
+ OS Version [操作系统类型和版本]:win10 64

### Expected behaviour [期望结果]

在设置xAxis的triggerEvent: true时, 返回参数增加一个dataIndex

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
            text: '工日合计'
        },
        tooltip: {
            trigger: 'axis'
        },
        legend: {
            data: ['工日合计']
        },
        grid: {
            borderWidth: 0,
            y2: 90
        },
        xAxis: [
            {
                type: 'category',
                data: [],
                rawCode: [],
                triggerEvent: true
            }
        ],
        yAxis: [
            {
                name: '工日合计',
                type: 'value'
            }
        ],
        dataZoom: [
            {
                show: true,
                type: 'inside',
                start: 0,
                end: 100
            }, {
                type: 'slider',
                start: 0,
                end: 100
            }
        ],
        series: [
            {
                name: '工日合计',
                type: 'bar',
                smooth: true,
                areaStyle: {normal: {}},
                data: []
            }
        ]
}

```

**Comment by pissang** [comment]
类目轴你可以用 indexOf 索引

**Comment by Miderfly** [comment]
我是想在点击事件中取类目轴data里数据的索引，通过点击类目轴的标签来判断点击的是第几个数据，能否举个例子，感谢！

**Comment by pissang** [comment]
一般来说你类目的索引就是你数据的索引
