### ISSUE TITLE
ECharts百度地图扩展无法拖拽平移

### ISSUE THREAD

**Issue by mismo** [apache/incubator-echarts#5455]
### One-line summary [问题简述]

在一个页面中引用echarts、bmap以及百度地图api等相关js脚本，再在该页面的一个iframe内的一个元素中渲染出百度地图图形，此时在该地图上无法拖拽平移地图。需要在按下鼠标后不公开并移动到iframe外部才可以平移地图(注：iframe的内容是我的报表内容，可由iframe外部控制内容切换，为了加快报表展现，js脚本引入在iframe外部)。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: Chrome 57
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]

iframe中的百度地图支持平移

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wsxjump** [comment]
bmap拓展确实存在问题,,但并不是无法平移而是平移之后有些效果的展示出现坐标上的异常.
例如:http://echarts.baidu.com/gallery/editor.html?c=effectScatter-bmap
在上面这个例子中如果进行平移拖拽,则每个点鼠标移上去之后的悬浮框的位置会相对平移的量进行变化(而不是仍然在点的附近.)

**Comment by mismo** [comment]
@wsxjump
你说的是鼠标提示在平移后提示框位置不变化的问题。
我说的现象是整个百度底图都平移不了。

**Comment by yqwoe** [comment]
同样的问题

**Comment by yqwoe** [comment]
@mismo 嗨，大佬，你这个问题解决了吗
