### ISSUE TITLE
y-axis in radar-chart

### ISSUE THREAD

**Issue by hyllos7** [apache/incubator-echarts#5467]
### One-line summary [问题简述]
It's obvious how to include an axis to a polar chart, but how is it done for a radar-chart?
Fantastic library, by the way!

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
Thanks, radar chart doesn't have separate axis. Use radar chart only need [radar](https://ecomfe.github.io/echarts-doc/public/en/option.html#radar) component and [radar](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-radar) series

**Comment by hyllos7** [comment]
many thanks, but wouldn't it be an important feature for radar series?
Check out this example
<http://www.scaoo.com/cei/spider-graph_Original/index.html>, which was not
created with echarts. To easily understand the graph, the legend is very
helpful.
Any advice how I could manage to create it?



2017-04-12 10:47 GMT+02:00 Yi Shen <notifications@github.com>:
