### ISSUE TITLE
柱状图样式

### ISSUE THREAD

**Issue by xiaonizi-github** [apache/incubator-echarts#5468]
### One-line summary [问题简述]
你好，我想实现柱状图列表的样式：是当data的value值超过一个数的时候，超过的一部分呈现一个颜色，没有超过默认显示另一个颜色，这个怎么实现啊

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echart3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时做不到

**Comment by mangoZT** [comment]
堆积柱状图是否满足，灵活使用一下好像能达到效果
