### ISSUE TITLE
animation in heatmap missing

### ISSUE THREAD

**Issue by anoosurf** [apache/incubator-echarts#5476]
animation in heatmap missing when series coordinates changes for same data point

it should be like treemap animation

### Version & Environment [版本及环境]
+ ECharts version [ECharts 3.5.2]:
+ Browser version [chrome]:
+ OS Version [windows10]:

/// http://gallery.echartsjs.com/editor.html?c=xrJl-RimTx

var hours = ['12', '1', '2', '3', '4', '5', '6',
            '7', '8', '9','10','11',
            '24', '13', '14', '15', '16', '17',
            '18', '19', '20', '21', '22', '23'];
        var days = ['mon', 'tue', 'wed',
            'thi', 'fri', 'sat', '周日'];

        var data = [[0,1,15],[0,2,-11],[0,2,0],[0,3,0],[0,4,0],[0,5,0],[0,6,-3],[0,7,0],[0,8,0],[0,9,0],[0,10,0],[0,11,2],[0,12,4],[0,13,1],[0,14,1],[0,15,3],[0,16,4],[0,17,6],[0,18,4],[0,19,4],[0,20,3],[0,21,3],[0,22,2],[0,23,5],[1,0,7],[1,1,0],[1,2,0],[1,3,0],[1,4,0],[1,5,0],[1,6,0],[1,7,0],[1,8,0],[1,9,0],[1,10,5],[1,11,2],[1,12,2],[1,13,6],[1,14,9],[1,15,11],[1,16,6],[1,17,7],[1,18,8],[1,19,12],[1,20,5],[1,21,5],[1,22,7],[1,23,2],[2,0,1],[2,1,1],[2,2,0],[2,3,0],[2,4,0],[2,5,0],[2,6,0],[2,7,0],[2,8,0],[2,9,0],[2,10,3],[2,11,2],[2,12,1],[2,13,9],[2,14,8],[2,15,10],[2,16,6],[2,17,5],[2,18,5],[2,19,5],[2,20,7],[2,21,4],[2,22,2],[2,23,4],[3,0,7],[3,1,3],[3,2,0],[3,3,0],[3,4,0],[3,5,0],[3,6,0],[3,7,0],[3,8,1],[3,9,0],[3,10,5],[3,11,4],[3,12,7],[3,13,14],[3,14,13],[3,15,12],[3,16,9],[3,17,5],[3,18,5],[3,19,10],[3,20,6],[3,21,4],[3,22,4],[3,23,1],[4,0,1],[4,1,3],[4,2,0],[4,3,0],[4,4,0],[4,5,1],[4,6,0],[4,7,0],[4,8,0],[4,9,2],[4,10,4],[4,11,4],[4,12,2],[4,13,4],[4,14,4],[4,15,14],[4,16,12],[4,17,1],[4,18,8],[4,19,5],[4,20,3],[4,21,7],[4,22,3],[4,23,0],[5,0,2],[5,1,1],[5,2,0],[5,3,3],[5,4,0],[5,5,0],[5,6,0],[5,7,0],[5,8,2],[5,9,0],[5,10,4],[5,11,1],[5,12,5],[5,13,10],[5,14,5],[5,15,7],[5,16,11],[5,17,6],[5,18,0],[5,19,5],[5,20,3],[5,21,4],[5,22,2],[5,23,0],[6,0,1],[6,1,0],[6,2,0],[6,3,0],[6,4,0],[6,5,0],[6,6,0],[6,7,0],[6,8,0],[6,9,0],[6,10,1],[6,11,0],[6,12,2],[6,13,1],[6,14,3],[6,15,4],[6,16,0],[6,17,0],[6,18,0],[6,19,0],[6,20,1],[6,21,2],[6,22,2],[6,23,6]];
var cnt=0;
        data = data.map(function (item) {
            return {name:cnt++, value: [item[1], item[0], item[2] || '-'], itemStyle:{ normal:{ color:'blue' }}};
        });

        option = {
            title: {
                text: '蓝红',
                subtext: '啊哈哈哈哈'
            },
            tooltip: {
                position: 'top'
            },
            backgroundColor: "#eee",
            animation: true,
            animationDelay: 2000,
            animationDuration: function (idx) {
    // delay for later data is larger
    return idx * 100;
},
            grid: {
                height: '70%',
                y: '10%'
            },
            xAxis: {
                show:false,
                type: 'category',
                data: hours,
                splitArea: {
                    show: false
                }
            },
            yAxis: {
                inverse:true,
                type: 'category',
                data: days,
                splitArea: {
                    show: false
                }
            },
            visualMap: {
                min: -10,
                max: 10,
                calculable: true,
                orient: 'horizontal',
                left: 'center',
                bottom: '15%',
                //只有这里是我改的，啊哈哈哈哈
                inRange: {
                    color: ['red','#fff','green'],
                }
            },
            series: [{
                name: 'Punch Card',
                type: 'heatmap',
                animation:true,
                data: data,
                label: {
                    normal: {
                        show: true,
                         formatter: function (params) {
                           //  console.log(params);
                    return      params.name + '\n' + params.value[2] + '\n';
                },
                    }
                },
                itemStyle: {
                    emphasis: {
                        shadowBlur: 10,
                        shadowColor: 'rgba(0, 0, 0, .5)'
                    }
                }
            }],
        };
        //alert('ok');
  
   myChart.setOption(option);     
   
        setTimeout(function () {

                // option.visualMap.inRange.color = ['blue','white','yellow'];
                 data = [[4,3,5],[0,2,-11],[3,2,10],[0,3,0],[0,7,0],[0,8,0],[0,9,0],[0,10,0],[0,11,2],[0,12,4],[0,13,1],[0,14,1],[0,15,3],[0,16,4],[0,17,6],[0,18,4],[0,19,4],[0,20,3],[0,21,3],[0,22,2],[0,23,5],[1,0,7],[1,1,0],[1,2,0],[1,3,0],[1,4,0],[1,5,0],[1,6,0],[1,7,0],[1,8,0],[1,9,0],[1,10,5],[1,11,2],[1,12,2],[1,13,6],[1,14,9],[1,15,11],[1,16,6],[1,17,7],[1,18,8],[1,19,12],[1,20,5],[1,21,5],[1,22,7],[1,23,2],[2,0,1],[2,1,1],[2,2,0],[2,3,0],[2,4,0],[2,5,0],[2,6,0],[2,7,0],[2,8,0],[2,9,0],[2,10,3],[2,11,2],[2,12,1],[2,13,9],[2,14,8],[2,15,10],[2,16,6],[2,17,5],[2,18,5],[2,19,5],[2,20,7],[2,21,4],[2,22,2],[2,23,4],[3,0,7],[3,1,3],[3,2,0],[3,3,0],[3,4,0],[3,5,0],[3,6,0],[3,7,0],[3,8,1],[3,9,0],[3,10,5],[3,11,4],[3,12,7],[3,13,14],[3,14,13],[3,15,12],[3,16,9],[3,17,5],[3,18,5],[3,19,10],[3,20,6],[3,21,4],[3,22,4],[3,23,1],[4,0,1],[4,1,3],[4,2,0],[4,3,0],[4,4,0],[4,5,1],[4,6,0],[4,7,0],[4,8,0],[4,9,2],[4,10,4],[4,11,4],[4,12,2],[4,13,4],[4,14,4],[4,15,14],[4,16,12],[4,17,1],[4,18,8],[4,19,5],[4,20,3],[4,21,7],[4,22,3],[4,23,0],[5,0,2],[5,1,1],[5,2,0],[5,3,3],[5,4,0],[5,5,0],[5,6,0],[5,7,0],[5,8,2],[5,9,0],[5,10,4],[5,11,1],[5,12,5],[5,13,10],[5,14,5],[5,15,7],[5,16,11],[5,17,6],[5,18,0],[5,19,5],[5,20,3],[5,21,4],[5,22,2],[5,23,0],[6,0,1],[6,1,0],[6,2,0],[6,3,0],[6,4,0],[6,5,0],[6,6,0],[6,7,0],[6,8,0],[6,9,0],[6,10,1],[6,11,0],[6,12,2],[6,13,1],[6,14,3],[6,15,4],[6,16,0],[6,17,0],[6,18,0],[6,19,0],[6,20,1],[6,21,2],[6,22,2],[6,23,6]];
var cnt=0;
         data = data.map(function (item) {
            return {name:cnt++, value: [item[1], item[0], item[2] ]};
        });
                 option.series[0].data=data;
                 myChart.setOption(option,false);     
        }, 2500);

**Comment by pissang** [comment]
Heatmap doesn't have animation

**Comment by anoosurf** [comment]
can u add animation capability like treemap ?
or can i have the treemap flow from left to right with items having equal square blocks and only color to be used for visual mapping ( see attached image ) .. i tried using a visualdimaension with a constant value.. but yet the squares are not exactly equal

![image](https://cloud.githubusercontent.com/assets/4696146/24904105/076c86cc-1ecd-11e7-8b5f-5fceb57fbda3.png)

**Comment by pissang** [comment]
Thanks for the detailed suggestion. We will think about it

**Comment by anoosurf** [comment]
thanks for acknowledging this request
any quickhand idea on how i can keep the size of the treemap items of exact same size & just use colour for visualdimension ?   to achieve this right now i'm trying to form rows & columns for cartesian system in a heatmap & achieve the result .. only thing there is no animation then which really would add to the beauty
thanks once again for hearing me out :) hope u can implement some workaround soon

**Comment by anoosurf** [comment]
now i also tried using treemap with simple data as --> value: {1, percentchange} with visaldimension from column index 1
so now i should ideally get simple square boxes of zero size ( since dimension 0 is set to same data '1' )
but i get some odd items ( despite my data being sorted)  see below image

![image](https://cloud.githubusercontent.com/assets/4696146/24919859/ab95c012-1f02-11e7-974e-1d0ad1f7305d.png)

**Comment by anoosurf** [comment]
i just tried with some more data with constant value for getting same square size .. everytime the first item seems exchanged with another item .. seems like surely a bug  ( and also the size of squares not exact ... ideally they should be for same value if squareratio is 1) ... also is there a way to make logic of display from left to right in sort order rather than top to bottom ?

![image](https://cloud.githubusercontent.com/assets/4696146/24941139/ca15571a-1f65-11e7-898e-6ca3988be51f.png)

**Comment by 100pah** [comment]
The squareRatio is a suggestive parameter. If you would like getting the same square size, not only the squareRatio is set to `1`, but also the `width` and `height` should be set the same:
```js
series: [{
    type: 'treemap',
    width: 300,
    height: 300,
    squareRatio: 1
}]
```
(See this [sample](http://gallery.echartsjs.com/editor.html?c=xH1rmiVoal&v=2))


And, the sorting algorithm of `treemap` does not consider the stability for nodes with the same value yet. But even if it has considered that, the result will be like that:
<img width="379" alt="screen shot 2017-04-12 at 2 04 01 pm" src="https://cloud.githubusercontent.com/assets/1956569/24943883/3773d2d0-1f8b-11e7-9bb1-61ac2d0b9dfd.png">



This result is inevitable by `treemap` layout algorithm, and it may be not your expectation.

So I think `heatmap` may be better solution for your case? I will think this through about animation of `heatmap`.

**Comment by anoosurf** [comment]
HI
thanks once again for getting back
then in that case i guess heatmap would be better option .. but imiss the animation in the same .. any chances that could be done sooner ? 

also if u notice in chrome the top left is giving '50' instead of '0' thats where i think logic going for a toss
but in MS edge browser it seems fine

![image](https://cloud.githubusercontent.com/assets/4696146/24945683/e3ff811a-1f7d-11e7-97df-29c82a3fffb5.png)

**Comment by 100pah** [comment]
> '50' instead of '0' thats where i think logic going for a toss
but in MS edge browser it seems fine
Yes, I have fixed that just now.

For heatmap, I have made a [example](http://gallery.echartsjs.com/editor.html?c=xHk0xr8jpg&v=2). I hope it is able to fit your requirement.

**Comment by anoosurf** [comment]
Hey thanks a ton
can u send me the link for the updated treemap if the bug has got solved ?
also for the animation example .. thanks once again.. but what i was looking for not a zoom/roam animation but more of a transition when the same item relocates its coordinates.. eg. from [x=3,y=5] to say [x=7,y=2] ..so the item would move to the new coordinates  ( & i would then emulate like a treemap to ensure there is not more than one item for a single coordinate x/y pair before updating the options.. so i would get the treemap effect with aniamtion of equal sizes in flowing single direction 
i must really appreciate the efforts to try and resolve my query ... is the a paid plan also for future support ... as u are doing a commendable job of buildig quite an amazing product suite .. cheers & wish ui the very best .. keep up the spirit !

**Comment by anoosurf** [comment]
hey i just figured u using 'scatter' type instead of heatmap & a geo coordinate system .. nice idea that.. i think its give me a clue to implement what im looking for .. using rect symbol for a scatter with size .. nice idea :)
thanks pal :)

**Comment by anoosurf** [comment]
hi i tried using scatter working similar to my liking ! thanks a ton for the help.. but one thing .. in the label display.. the text does not get clipped ( if i use rect symbol option) .. is there a way i can clip or show ellipses so as to show it more cleaner .. see pic -->
![image](https://cloud.githubusercontent.com/assets/4696146/25037973/bbfb2500-2119-11e7-9178-318e96d1cc93.png)
