### ISSUE TITLE
解决x轴显示不完整的一个新建议

### ISSUE THREAD

**Issue by shijistar** [apache/incubator-echarts#5484]
### One-line summary [问题简述]
关于x轴显示不全的问题，已经被问了无数次了，无论是增加空间、还是旋转角度，抑或是增加换行符，都不能彻底解决此类问题。我想提供一个建议，希望能彻底解决此问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: Chrome Version 57.0.2987.133 (64-bit)
+ OS Version [操作系统类型和版本]: Ubuntu 16.04

### Expected behaviour [期望结果]

当x轴的数据过长时，我们可以采取某种策略（取头部或者尾部的前5个字符）截断文字，其余部分显示省略号。但，能否同时给x轴的label上增加类似于dom元素里`title`类似的tooltip，从而可以显示全部文字了。请参照底部的截图（注：这是简陋ps的一张图片，意在说明tooltip的效果）。
我觉得还是在自动截取的基础上，再显示完整的tooltip，这样可以近乎“完美”的解决此问题。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

[示意图](http://staging-udesk.oss-cn-beijing.aliyuncs.com/imgData/1.png)

**Comment by pissang** [comment]
截断后坐标轴没什么存在的意义了，反正 tooltip 中也包括这个刻度的内容
