### ISSUE TITLE
在react-native 下 release 版本中文变为 unicode 但在debug 模式下正常

### ISSUE THREAD

**Issue by Malenconiaprincep** [apache/incubator-echarts#5491]
### One-line summary [问题简述]

在react-native 下 release 版本中文变为 unicode 但在debug 模式下正常

我用的是 formatter
```
formatter: params => {
        const wan = '万';
        let currentIndex = 0;
        if (!params[currentIndex].name) {
          currentIndex = 1;
        }
        return `${params[currentIndex].name},${params[currentIndex].value}${wan}`;
      },
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   3.2.3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:  IOS

### Expected behaviour [期望结果]

希望中文字体不会转为unicode

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

这是debug模式下

![image](https://cloud.githubusercontent.com/assets/6262739/24955013/49503c5e-1fb4-11e7-8739-553a361f9f87.png)

这是release 模式下的截图
![image](https://cloud.githubusercontent.com/assets/6262739/24954982/259bb2ac-1fb4-11e7-96e0-54cdd090d4c5.png)

**Comment by yongqianvip** [comment]
同样的问题
