### ISSUE TITLE
当map引用geo时，showLegendSymbol无效

### ISSUE THREAD

**Issue by imakemyworld** [apache/incubator-echarts#5495]
### One-line summary [问题简述]
当map引用geo时，地图上的小圆点显示设置showLegendSymbol无效，
如果不引用geo是正常的。

### Version & Environment [版本及环境]
+ ECharts version [3.5.2]:
+ Browser version [Google Chrome 57.0.2987.133]:
+ OS Version [window 10]:

### Expected behaviour [期望结果]
showLegendSymbol:true,让它有效果吧。

### Other comments [其他信息]

我在上地六街，看在我经常路过你们公司门口的份上，O(∩_∩)O~

**Comment by mangoZT** [comment]
这关系拉的  能否贴一下代码

**Comment by imakemyworld** [comment]
这个配置的话，北京会有一个红点
------❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀-----------这是一个华丽的❀格线

option = {
    legend: {
        orient: 'vertical',
        left: 'left',
        data:['iphone3']
    },
    series: [
        {
            name: 'iphone3',
            type: 'map',
            mapType: 'china',
            roam: false,
            data:[
                {name: '北京',value: 12 }
            ]
        }
    ]
};

------❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀-----------这是一个华丽的❀格线

如果如此配置的话，北京怎么都红不起来
------❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀-----------这是一个华丽的❀格线

option = {
    legend: {
        orient: 'vertical',
        left: 'left',
        showLegendSymbol:true,//showLegendSymbol在这无效
        data:['iphone3']
    },
    geo:[{
        map:'china'
    }],
    series: [
        {
            name: 'iphone3',
            type: 'map',
            geoIndex: 0,
            showLegendSymbol:true,//showLegendSymbol在这也无效
            roam: false,
            data:[
                {name: '北京',value: 123}
            ]
        }
    ]
};

------❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀-----------这是一个华丽的❀格线

ps：我请你吃海盗虾饭怎么样。

**Comment by mangoZT** [comment]
使用geo需要用到坐标系   代码如下
option = {
legend: {
orient: 'vertical',
left: 'left',
data:['iphone3']
},
geo:[{
map:'china'
}],
series: [
{
      type: 'scatter',
      coordinateSystem: 'geo',
      zlevel: 2,
      rippleEffect: {
        brushType: 'stroke'
      },
      itemStyle: {
        normal: {
          color:"#36FAFF"
        }
      },
      data: [{name:"上海",value:[121.4648,31.2891]}]
    }
]
};

**Comment by imakemyworld** [comment]
我知道已经被散点替代了，但是我只想用一下基础的，简单的显示showLegendSymbol。
如果产品需求定义就这样的话，我就不打搅了。
Thank you。

**Comment by mangoZT** [comment]
这个我不太清楚啊 你可以问下@passing  我只是给你一个解决方案

PS  说好的海盗虾饭呢
