### ISSUE TITLE
嵌套环形图内外圈数据没有关联的问题

### ISSUE THREAD

**Issue by 0726zhangjing** [apache/incubator-echarts#5508]
### One-line summary [问题简述]
嵌套环形图内外圈数据没有关联的问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.2.7
+ Browser version [浏览器类型和版本]:Safari 10.1 (12603.1.30.0.34)
+ OS Version [操作系统类型和版本]:macOS 10.12.4 (16E195)

### Expected behaviour [期望结果]
希望嵌套环形图内外圈的数据是有父子级关系，内外圈数据可以形成联动。即内圈为数据的主要组成部分，外圈数据是内圈中各个数据的细分。若在图例中隐藏掉一个指标项，内外圈的占比都会改变。
目前该图标的效果只是两个各自100%的饼图叠加在一起，隐藏任何一个图例，只会改变该指标所在的那个圈的占比，失去了嵌套展示的意义。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by heguangyong** [comment]
这个功能确实很有价值，强烈建议提供解决方案。
