### ISSUE TITLE
在华为手机上地图“破裂”

### ISSUE THREAD

**Issue by lijunzhou** [apache/incubator-echarts#5514]
问题出现在用dcloud打包的web app上，使用的功能主要是series的map和geo。在浏览器和其他手机上没有任何问题，在华为手机上就出现了地图“破裂”的现象。在app中嵌入官方事例“香港18区人口密度图“也是有这种现象。
比较麻烦的是怀疑是华为原生浏览器的兼容问题，可是使用原生浏览器打开页面却是正常的。由此判断此故障还与dcloud提供的浏览器内核有关。

能否提供一个排查的方向？非常感谢。

这是在浏览器上调试的正常结果
<img width="229" alt="0b066284-f81c-4633-b6dd-64c9210f58f4" src="https://cloud.githubusercontent.com/assets/4168003/25069981/7820d342-22c3-11e7-963a-41b16f1aab60.png">

这是在华为手机上运行app的截图
<img width="306" alt="bc00fa09-0421-45e5-aec9-b90805b986c1" src="https://cloud.githubusercontent.com/assets/4168003/25069988/9c47b10a-22c3-11e7-8fcf-5b948a9504cc.png">

这是在华为手机上运行app显示香港18区人口密度图的截图。
![screenshot_20170416-160614](https://cloud.githubusercontent.com/assets/4168003/25069998/d1ed8b04-22c3-11e7-930d-65da6cb9de97.png)

这是手机的版本信息
![screenshot_20170416-160751](https://cloud.githubusercontent.com/assets/4168003/25069999/db1a8470-22c3-11e7-963e-f1420efdb770.png)

**Comment by lydiafork** [comment]
我在开发过程中遇到的同样的问题， 后来发现是因为官网提供的香港地图的json是简化版的， 经纬度数据保留小数点后7-8位， 我们自己下了一份香港的json, 经纬度保留到小数点后14位，效果就好很多

**Comment by lijunzhou** [comment]
我的问题已经解决了，是因为华为手机的GPU在webkit内核下硬件加速的问题，打包apk的时候使用腾讯的X5内核就不会有这种情况了。
