### ISSUE TITLE
echarts3最多支持多少条线

### ISSUE THREAD

**Issue by Lisa-xyy** [apache/incubator-echarts#5515]
### One-line summary [问题简述]
echarts画图时，在数据量小的时候，可以正常画图；当后端返回180条线，每条线2600多个点，在画图的时候浏览器崩溃。跟代码到setOption里边崩溃

 echartsProto.setOption = function (option, notMerge, notRefreshImmediately) {
	        if (true) {
	            zrUtil.assert(!this[IN_MAIN_PROCESS], '`setOption` should not be called during main process.');
	        }

	        this[IN_MAIN_PROCESS] = true;

	        if (!this._model || notMerge) {
	            var optionManager = new OptionManager(this._api);
	            var theme = this._theme;
	            var ecModel = this._model = new GlobalModel(null, null, theme, optionManager);
	            ecModel.init(null, null, theme, optionManager);
	        }

	        this._model.setOption(option, optionPreprocessorFuncs);

	        **# updateMethods.prepareAndUpdate.call(this);**//走到该行崩溃了

	        this[IN_MAIN_PROCESS] = false;

	        this._flushPendingActions();

	        !notRefreshImmediately && this._zr.refreshImmediately();
	    };

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:版本 47.0.2526.106 m (64-bit)
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

能够正常画出图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by bi-kai** [comment]
@xwx216290 @leeight @firede @chriswong 我也遇到了相同的问题，每条线2000个点左右，echarts3最多支持多少条线呢？有没有性能规格？

**Comment by pissang** [comment]
跟机器，浏览器都有关系，我们也无法给出准确的数据

**Comment by bi-kai** [comment]
@pissang 比如常规的4U4G的计算机，chrome最新版本。
常规来说，100条线的时候，echarts就会很卡了吧。
