### ISSUE TITLE
My Radar chart's tooltip is not triggered when the value is 'axis'. It is similar to the closed bug #1835

### ISSUE THREAD

**Issue by aryakochukrishnan** [apache/incubator-echarts#5519]
Below is my option 

{
	"legend": {
		"data": ["Tickets Available", "Sold", "Cancelled"],
		"orient": "horizontal",
		"x": "center",
		"y": "bottom"
	},
	"color": ["#008000", "#0000FF", "#ff0000"],
	"tooltip": {
		"trigger": "axis"
	},
	"calculable": true,
	"series": [{
		"type": "radar",
		"data": [{
			"name": "Tickets Available",
			"value": [239, 303, 389, 428, 544, 527, 589, 629, 612, 654, 631, 654, 679, 713, 748, 822, 815, 816, 674, 419, 320, 384, 961, 205]
		}, {
			"name": "Sold",
			"value": [40, 29, 34, 49, 86, 94, 100, 107, 98, 143, 136, 140, 113, 128, 96, 95, 82, 102, 83, 67, 27, 35, 70, 27]
		}, {
			"name": "Cancelled",
			"value": [170, 200, 285, 310, 306, 346, 349, 347, 385, 391, 382, 412, 398, 414, 471, 500, 511, 435, 327, 207, 168, 209, 484, 105]
		}]
	}],
	"toolbox": {
		"x": "right",
		"y": "top",
		"orient": "",
		"show": true,
		"feature": {
			"saveAsImage": {
				"show": true,
				"title": "Save"
			},
			"mark": {
				"show": true
			}
		}
	},
	"backgroundColor": "#fff",
	"polar": [{
		"indicator": [{
			"text": "12 AM",
			"max": 1057.1
		}, {
			"text": "11 PM",
			"max": 1057.1
		}, {
			"text": "10 PM",
			"max": 1057.1
		}, {
			"text": "9 PM",
			"max": 1057.1
		}, {
			"text": "8 PM",
			"max": 1057.1
		}, {
			"text": "7 PM",
			"max": 1057.1
		}, {
			"text": "6 PM",
			"max": 1057.1
		}, {
			"text": "5 PM",
			"max": 1057.1
		}, {
			"text": "4 PM",
			"max": 1057.1
		}, {
			"text": "3 PM",
			"max": 1057.1
		}, {
			"text": "2 PM",
			"max": 1057.1
		}, {
			"text": "1 PM",
			"max": 1057.1
		}, {
			"text": "12 PM",
			"max": 1057.1
		}, {
			"text": "11 AM",
			"max": 1057.1
		}, {
			"text": "10 AM",
			"max": 1057.1
		}, {
			"text": "9 AM",
			"max": 1057.1
		}, {
			"text": "8 AM",
			"max": 1057.1
		}, {
			"text": "7 AM",
			"max": 1057.1
		}, {
			"text": "6 AM",
			"max": 1057.1
		}, {
			"text": "5 AM",
			"max": 1057.1
		}, {
			"text": "4 AM",
			"max": 1057.1
		}, {
			"text": "3 AM",
			"max": 1057.1
		}, {
			"text": "2 AM",
			"max": 1057.1
		}, {
			"text": "1 AM",
			"max": 1057.1
		}]
	}],
	"title": {
		"text": "App Visits By Time of Day"
	}
}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 3.4.0]:
+ Browser version [Chrome 57]:
+ OS Version Windows 10:

**Comment by stouch** [comment]
up ! Same problem
