### ISSUE TITLE
echarts 对"type": "LineString"格式的geojson无法绘图

### ISSUE THREAD

**Issue by luoam** [apache/incubator-echarts#5530]
### One-line summary [问题简述]
自己开发中用到了geojson，geojson的内容是有线条构成， 发现echarts不能把这个geojson图形绘制出来。平面显示空白。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新版
+ Browser version [浏览器类型和版本]:ie11，chrome
+ OS Version [操作系统类型和版本]:windows10

### Expected behaviour [期望结果]

能够流畅的绘制各种type的图形

我把用到的geojson文件通过附件上传，希望开发组能够看看能否有解决方案

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

[Uploading rline.zip…]()

**Comment by pissang** [comment]
抱歉 GeoJSON 暂时还不支持 LineString，后续增强

**Comment by SevenTrap** [comment]
现在echarts5.X版本仍然不支持geojson中的LineString属性，这个后续会有解决方案吗？
