### ISSUE TITLE
仪表盘逆时针问题

### ISSUE THREAD

**Issue by flicker85** [apache/incubator-echarts#5542]
仪表盘逆时针，可是指针和刻度还是顺时针，请问该怎么写？
```js
{
  type: 'gauge',
  clockwise: false,
  startAngle: -140,
  endAngle: 140,
  data: [{ value: 30, name: '内存使用率' }]
}
```
![123](https://cloud.githubusercontent.com/assets/5960708/25209781/c43fb3f8-25af-11e7-9d84-156d9467abba.png)

**Comment by ppker** [comment]
当逆时针的时候      startAngle 和 endAngle  （这2个参数的设置要翻转）要设置的和顺时针相反才行
{
            clockwise: false,
            name: '业务指标',
            startAngle: -360,
            endAngle: 180,
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50, name: '完成率'}]
   }

**Comment by flicker85** [comment]
@ppker 我设置得就是反得呀，表盘就是逆时针画得，但是刻度还是顺时针得。
echarts："version": "3.5.3"

**Comment by ppker** [comment]
@flicker85  no no, you can try my option 
like this
{
clockwise: false,
name: '业务指标',
startAngle: -360,
endAngle: 180,
type: 'gauge',
detail: {formatter:'{value}%'},
data: [{value: 50, name: '完成率'}]
}

**Comment by flicker85** [comment]
@ppker 
这是在官网demo页面用你的代码测试得，http://echarts.baidu.com/demo.html#gauge
表盘是逆时针画得，刻度和指针还是顺时针啊~
![222](https://cloud.githubusercontent.com/assets/5960708/25259916/840b74da-267b-11e7-9cb5-2c1120f50d7b.png)

**Comment by sutra** [comment]
其实就是想要这种油表的效果吧：
<img width="123" alt="screen shot 2017-05-07 at 10 17 12 pm" src="https://cloud.githubusercontent.com/assets/18538/25781930/fe86b75c-3372-11e7-9234-1aa713134116.png">

**Comment by sutra** [comment]
A tricky way:
![screen shot 2017-05-07 at 10 48 08 pm](https://cloud.githubusercontent.com/assets/18538/25782150/46f690e4-3377-11e7-870b-82e4b6938c1a.png)

**Comment by sutra** [comment]
这样估计是 @flicker85 想要的效果：
![screen shot 2017-05-07 at 11 04 27 pm](https://cloud.githubusercontent.com/assets/18538/25782250/8f0ea608-3379-11e7-9161-bd08e55fe78f.png)

**Comment by flicker85** [comment]
@sutra 
对，就是这种效果，逆时针时候“刻度”和“数字”颜色不对，我第一张图就是这么配置的

**Comment by wangyahua** [comment]
@flicker85   请问你这个解决了吗？

**Comment by sunday2** [comment]
刻度和数字颜色不对加1，请问如何解决

**Comment by sunday2** [comment]
发现clockwise应该还是设置为true,顺时针递增，然后最小值和最大值取反，就原来min:0,max:100变为min:-100,max:0.然后通过axixLabel方法对刻度进行格式控制，即*-1，这样就能达到逆时针递增的效果。maxAngle和minAngle无需改变。
