### ISSUE TITLE
不靠toolbox，手動切換stack & bar 圖型 問題

### ISSUE THREAD

**Issue by Chiyaoching** [apache/incubator-echarts#5552]
### One-line summary [问题简述]

不靠toolbox，手動切換stack & bar 圖型 問題

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.3
+ Browser version [浏览器类型和版本]: chrome 57.0.2987.133
+ OS Version [操作系统类型和版本]: MAC OS X10.12.4

### Expected behaviour [期望结果]

目前是能透過toolbox提供的功能來切換 stack & bar，但我想藉由 $(window).width() 的條件來動態的切換stack & bar 的圖形，不知道有沒有人實作過？

**Comment by mangoZT** [comment]
setoption？

**Comment by Chiyaoching** [comment]
剛剛試了一下，找到了個辦法
```
seriesData = myChart.getOption().series
seriesData.forEach(function(value, index){
  value.stack = "time"
})

myChart.dispatchAction({
   type: 'changeMagicType',
   currentType : "tiled",
   newOption: {series: seriesData}
});

不過這方法效能似乎不是挺好，有更好的解法嗎？

**Comment by pissang** [comment]
`setOption`就行

**Comment by Chiyaoching** [comment]
指的是我依舊要先將Series中的stack做處理後
```
seriesData = myChart.getOption().series
seriesData.forEach(function(value, index){
  value.stack = "time"
})

&

seriesData = myChart.getOption().series
seriesData.forEach(function(value, index){
  value.stack = ""
})

```
再使用setOption將它重新載入嗎？

**Comment by Chiyaoching** [comment]
我的圖型是multiBar，由五組資料組成
剛剛又爬了一下series

發現照上面的設定方式只會設定到第一組series內的stack

所以我簡易的測試了一下

```
myChart.setOption({
  series: [
     {stack: 'time'},
     {stack: 'time'},
     {stack: 'time'},
     {stack: 'time'},
     {stack: 'time'}
   ]
})
```

這樣的設定方式就可成功work了！

結論是，有幾組data就必須帶幾組的條件進去setOption
