### ISSUE TITLE
group support dragging in graphic component

### ISSUE THREAD

**Issue by hanjiangxue88** [apache/incubator-echarts#5569]
draggable: 'true'，包含几个children，似乎没办法整体拖拽？如何解决呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版本
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
graphic: {
type: 'group',
draggable: 'true',
children: [...]
}

}

```

**Comment by Hero-Xu** [comment]
我也遇到相同的问题，暂时没有找到解决办法

**Comment by fuchunhui** [comment]
同样问题，一直未修复，期望更新解决。

**Comment by ymli1981** [comment]
也是同样问题，快0202年了，还没解决
