### ISSUE TITLE
想要知道echarts折线图加载时渲染的动画如何做到从左到右依次渲染

### ISSUE THREAD

**Issue by ajaxAnnie** [apache/incubator-echarts#5585]
One-line summary [问题简述]

在echarts的配置项中查看animation,并没有找到怎么渲染的动画，遇到的问题是，横坐标从后台获取后动态添加，然后折线图从中间向两端渲染，测试静态坐标数据是可以从左到右依次渲染的。

+ ECharts version [ECharts 版本]:Echarts 2.0
+ Browser version [浏览器类型和版本]:chrom
+ OS Version [操作系统类型和版本]:win7

**Comment by pissang** [comment]
没理解你的意思
