### ISSUE TITLE
Can treemap display as it's already drilled to a level rather than root when set option?

### ISSUE THREAD

**Issue by codTango** [apache/incubator-echarts#5595]
### One-line summary [问题简述]
I would want to set option, then treemap will display as it's already been drilled into certain level and at a specific location/cell, also same for breadcrumb will display it's at certain level.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.3
+ Browser version [浏览器类型和版本]: chrome & firefox
+ OS Version [操作系统类型和版本]: Mac OS

### Expected behaviour [期望结果]
This is all come from the requirement that I need lazy load data for treemap. Thinking about this scenario, I have a treemap which would have 30 levels deep, but I cannot/shouldn't load all data upfront. I can load 3 levels data to display the treemap, when user drills into the 3rd, I can send request to get 4th, 5th and 6th level data. In this case, I need setOption again after I got response, but I also need preserve the current cell location, drill level, and breadcrumb.

**Comment by codTango** [comment]
@100pah any progress on this one? if we will implement it, or there's an existing work around?

**Comment by 100pah** [comment]
We have planned to implement dynamic data loading support for `treemap` in next version.

**Comment by codTango** [comment]
@100pah Could you help me clear it, as next version, you mean 3.5.5? or like ecahrts 4.0?

**Comment by walexz** [comment]
4.0.4的treemap还是会在setoption更新后跳回根节点
