### ISSUE TITLE
如何在tooltip中显示双横轴的内容

### ISSUE THREAD

**Issue by ydjfy** [apache/incubator-echarts#5604]
### One-line summary [问题简述]
xAxis 为双横轴，数据分别为lcarray和qdarray。现在tooltip中想同时显示两个横轴的内容.tooltip中的代码应如何写？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:ECharts 3
+ Browser version [浏览器类型和版本]:google chrome
+ OS Version [操作系统类型和版本]:win7

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
                        trigger: 'axis',
                    },
xAxis: [ 
                    {
                        type: 'category',
                        boundaryGap: false,
                        data: lcarray
                    },
                    {
                        type: 'category',
                        boundaryGap: false,
                        data: qdarray
                    } ],
}

```

**Comment by ZXand618** [comment]
option下加入此代码试试
axisPointer: {
        link: [{xAxisIndex: 'all'}],
        snap: true
},
tooltip:{trigger:'axis'},
