### ISSUE TITLE
visualMap[i]-piecewise.pieces的边界问题

### ISSUE THREAD

**Issue by MrsKey** [apache/incubator-echarts#5634]
### One-line summary [问题简述]
pieces: [
    {gt: 10, lte: 200, label: '10 到 200（自定义label）'},       //表示 (10, 200]
]
注意：有没有这种写法：  {gt: 10, lte: 200, label: '10 到 200（自定义label）'},       //表示 (10, 200] 即10<x<=200,现在要改成：10<x<=200 | | 300<x<=400,主要表达的意思就是两个范围，处理同一个状态

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by MrsKey** [comment]
比如   if(10 <x<=200 || 300<x<=400){
        
}在pieces: [
{gt: 10, lte: 200, label: '10 到 200（自定义label）'}, //表示 (10, 200]
]中有这种写法吗？

**Comment by 100pah** [comment]
现在没有支持这种复杂的范围表达。什么场景下需要这种表达呢，我可以考虑要不要支持。

**Comment by MrsKey** [comment]
@100pah 就是在边界范围外，，一共有两个边界值，，一个头，一个尾。比如象：x<10,是边界头，，，x>200表示边界尾，，这两范围是我们不要的，，表示成一种状态，比如条件（x<10 || x>200）表示同一种状态危险
