### ISSUE TITLE
在开启动画的情况下，如何判断图表渲染结束？

### ISSUE THREAD

**Issue by genggs** [apache/incubator-echarts#5641]
### One-line summary [问题简述]
在开启动画的情况下，如何判断图表渲染结束？

在图表渲染结束后，要对图表渲染的div进行resize监听，div大小变化调用图表的resize方法。

div、图表渲染、div监听都是通过后台java拼的。

现在的问题是，折线图的动画基本看不到了，会直接把所有的线都显示出来，目前的希望是能够在图表渲染结束后在对div进行监听。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没办法，可以用 setTimeout

**Comment by genggs** [comment]
setTimeout可能不太完美，不过感谢您即时的回复，希望echarts后期会有更好的解决办法
