### ISSUE TITLE
黑龙江省-地图 为什么有一小块画到内蒙古去了？

### ISSUE THREAD

**Issue by iahu** [apache/incubator-echarts#5652]
### One-line summary [问题简述]
下载了china.js的geo数据文件，发现黑龙江与内蒙古的地图画得有点小问题，黑龙江有一小块独立出现在了内蒙古里面，而内蒙古最右边多画了一条线，仿佛中国地图上多了一个小省。
我查了下百度地图，维基百科，黑龙江的地图都没有那一部分，内蒙古也没有那条线。不知道这份数据是依据哪个版本的地图出的？

**Comment by TieChi** [comment]
就是那样的，黑龙江就是有一小块在内蒙。你地理没学好。。。

**Comment by iahu** [comment]
@TieChi 说我地理没学好是有可能的，但是得有证据啊
http://www.onegreen.net/maps/m/neimenggu.htm

**Comment by jnie666** [comment]
我也发现问题了，内蒙古的地图求解决 @pissang

**Comment by efbfbd** [comment]
搜下'加格达奇', 百科有相关词条
