### ISSUE TITLE
当graph-force中接受的node和edge数量过多时，渲染会很慢

### ISSUE THREAD

**Issue by Se7enGo** [apache/incubator-echarts#5654]
### One-line summary [问题简述]
为了描述一个大的关系网络，我选择使用了echarts中的graph-force来展示。
有个案例样本是node数量为5000左右，edge数量为30000左右，会使渲染变得很慢。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echarts 3.5.3
+ Browser version [浏览器类型和版本]:IE 11.0.9600.16428
+ OS Version [操作系统类型和版本]:win7 32位

### Expected behaviour [期望结果]
对于echarts的使用并不是很熟练，希望得到官方网的建议
能否给我优化option的建议，比如哪些效果是影响展示效率的。
是否有关于graph-force部分的压力测试数据，多少数据量是可以接受的范围？

### ECharts option [ECharts配置项]

```javascript
option = {
        title: {
		text: '关系网络',
		subtext: 'Default layout',
		top: 'bottom',
		left: 'right'
	},
	tooltip: {
		trigger:"item",
		formatter:function(params){
			var res="";
			if(params.data.source){
				res+='额外信息'+params.data.value;
			}else{
				res = '关系名称'+(params.data.name)
			}
			return res;
		}
	},
	toolbox:{
		left：'right',
		top:'top',
		feature:{
			restore:{},
			saveAsImage:{
				type:'jpeg'
			}
		}
	},
	animation:false,
	series: [{
			type: 'graph',
			layout: 'force',
			draggable:true,
			edgeSymbol:['','arrow'],
			edgeSymbolSize:5,
			data: json.nodes.map(function(node){
				return {
					id:node.id,
					name:node.name,
					value:node.value,
					label:{
						normal:{
							show:true,
							position:'inside'
						}
					},
					symbolSize:6,
					symbol:'circle'
				};
			}),
			links: json.edges.map(function(){
				return {
					source:edge.sourceID,
					target:edge.targetID,
					value:edge.value
				};
			}),
			roam: true,
			label: {
				normal: {
					position: 'right'
				}
			},
			force: {
				repulsion: 100
			},
			focusNodeAdjacency:true
		}
	]
}

```

**Comment by pissang** [comment]
这个量级 echarts 里的 graph 确实会卡，可以尝试使用 ECharts GL 中的 graphGL 系列。

https://ecomfe.github.io/echarts-doc/public/cn/option-gl.html#series-graphGL

**Comment by Se7enGo** [comment]
@pissang 感谢你的回答，另外不好意思，由于是涉密数据，我这边无法提供给你。还有关于你提到的graphGL，我会尝试一下的。

**Comment by KishoDai** [comment]
Hi @pissang 
      也碰到同样渲染慢的问题。
      但我没有找到关于ECharts GL中人graphGL系列的例子，我按文档修改了我的代码，但达不到使用graph的效果，你有示例么？
     谢谢！

**Comment by Se7enGo** [comment]
@KishoDai 在编写例子的过程中参考了 pissang 的官方GALLERY事例 ，graph-gl部分可以参考一下如下例子：
GraphGL GPU Layout  ：http://gallery.echartsjs.com/editor.html?c=xrJchBL9ag  
GraphGL - Large Internet : http://gallery.echartsjs.com/editor.html?c=xSkG498qpx 
以上这些可以在官方网页 GALLERY里找pissang的主页，有更多有趣的实例。

**Comment by KishoDai** [comment]
Hi @Se7enGo
      非常感觉你的回答！
      我试下了，渲染而已是很快了，但无法达到像graph这样的效果：譬如用图标显示结点，显示结点名称，点击/双击节点时的事件处理等。

**Comment by ah-kevin** [comment]
@pissang 我这边之前用的是2,点一多就很卡.更换3.500个点也就不行了.有什么好的方法.更换graphGL么? 那点击节点的事件处理是不是就不行了

**Comment by KishoDai** [comment]
@ah-kevin 
        其实多于1000个节点，对于用户来说已是眼花缭乱了，根本就无法看清是什么东东了。
        所以我想了个办法就是最多只显示1000个节点。

**Comment by ah-kevin** [comment]
@KishoDai 500个节点就不行了,有点有线..一拖动就卡的不行- -你是怎么解决的

**Comment by Se7enGo** [comment]
这个要看具体的业务了，具体情况具体分析。
我能力范围内的解决方案：更换更高版本的echarts，更换更好的适配浏览器，优化option去除掉不必要的渲染，简化逻辑和事件处理，考虑静态的图片是否能够满足业务需要以及等待官方升级版本或者有能力的话可以做一下自己的实现。

**Comment by ah-kevin** [comment]
@Se7enGo 感谢你的回答,因为这边是用的echart2,更换为3,用graph去做,感觉提升不是很明显!用gl的话,展示是好了,但好像交互就没了

**Comment by KishoDai** [comment]
@ah-kevin 
     我是先用布局算法计算出各个点的坐标，不用力导向布局了，这样渲染会快很多。

**Comment by pissang** [comment]
@ah-kevin GL 的交互马上就会加上

**Comment by ah-kevin** [comment]
@pissang 大概时间是在什么时候~~

**Comment by KishoDai** [comment]
@pissang 
    很期待这个功能！！！

**Comment by ah-kevin** [comment]
@pissang 你好,我这边有个Demo,3跟2的布局差很多,而且3碰撞的时候很奇怪..到500个点的时候就卡了.

**Comment by liwenzhusdu** [comment]
@pissang同问graphGL交互功能大概什么时候出？

**Comment by bitqiang** [comment]
我渲染500个data，500个link也卡了。感觉就是力导向布局好像需要计算很久。所以才卡顿吗？
