### ISSUE TITLE
Echarts and scrolling

### ISSUE THREAD

**Issue by vikramrc** [apache/incubator-echarts#5666]
Hi There,

I wanted to know if there is any way to add a horizontal and/or vertical scrollbar to Echarts when faced with a fixed axis ? For example, have a vertical scrollbar when X-Axis is fixed so that scrolling on it moves the chart contents (of Y-Axis) where as keeping the X-Axis fixed.

thanks,
best regards,
Vikram

From Google Translate
-----------------------

你好，

我想知道当面对固定轴时，是否有任何方法可以向Echarts添加水平和/或垂直滚动条？ 例如，当X轴被固定时，有一个垂直的滚动条，以便在其上滚动将图表内容（Y轴）移动到保持X轴固定的位置。

谢谢，
最好的祝福，
维克拉姆

**Comment by sameer05k21a0440** [comment]
Hi, If you solve problem please let me know

**Comment by thanhtoan1196** [comment]
any update?
