### ISSUE TITLE
新版本echart折线图在没有数据时显示问题

### ISSUE THREAD

**Issue by zhaoseen** [apache/incubator-echarts#5685]
在3.1.10版本中没有数据时这样显示：
![3 1 1](https://cloud.githubusercontent.com/assets/28519800/25787451/0de487f4-33d4-11e7-93cb-1c7f699dcd6d.png)
在3.5.4版本中没有数据时这样显示：
![3 5 4](https://cloud.githubusercontent.com/assets/28519800/25787464/1ca7bd56-33d4-11e7-8995-bb53a91b9a73.png)
只有坐标轴没有网格和其他提示，不如原版本合理，如何在3.5.4版本中实现原来的显示样式

**Comment by 100pah** [comment]
攻击次数是整数，原来的版本中强制把 y 轴刻度显示为小数，是不是也不合理。
