### ISSUE TITLE
请教多grid下，定制多种grid.tooltip.formatter的办法

### ISSUE THREAD

**Issue by ZXand618** [apache/incubator-echarts#5686]
### One-line summary [问题简述]
option.tooltip.formatter配置正常，放到option.grid.tooltip.formatter配置不生效……

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.2
+ Browser version [浏览器类型和版本]:IE11
+ OS Version [操作系统类型和版本]:win8.1 x64

### Expected behaviour [期望结果]
不同grid中，按不同规则显示单位
（链接中的代码，为了简明，只做了一个x轴）

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://gallery.echartsjs.com/editor.html?c=xrkZ0cZOJ-&comment=0

**Comment by pissang** [comment]
可以写到 series 下

**Comment by ZXand618** [comment]
@pissang 
谢谢，我试试~
不过series有很多怎么办……一个一个写么？

**Comment by pissang** [comment]
那建议多个实例
