### ISSUE TITLE
echarts 3.5.4版本，使用timeline组件出现的问题（播放动画效果时而正常时而不正常）

### ISSUE THREAD

**Issue by web-smile** [apache/incubator-echarts#5768]
### One-line summary [问题简述]
使用timeline组件实现分页的功能，可是在自动播放时时而有动画效果时而没有

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.54版本
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7,8

### Expected behaviour [期望结果]

希望尽快解决这个问题，谢谢

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

demo地址：https://github.com/web-smile/echarts

### Other comments [其他信息]

@leeight  @cnberg @chriswong

**Comment by pissang** [comment]
在 http://gallery.echartsjs.com/explore.html 上复现一下你的问题？

**Comment by huoyuanyuanweb** [comment]
已经提交，请尽快帮忙解决，谢谢！！！ （要等上一段时间就有复现）
http://gallery.echartsjs.com/editor.html?c=xSJbHu-nl-&v=2

**Comment by huoyuanyuanweb** [comment]
@pissang @leeight @cnberg @firede 请尽快看下这个问题
