### ISSUE TITLE
dispatchAction hideTip 时只隐藏了tooltip的content，没有隐藏axisPointer

### ISSUE THREAD

**Issue by duxinxiao** [apache/incubator-echarts#5782]
One-line summary [问题简述]

dispatchAction({ 'hideTip'}) 的时候，似乎只隐藏了tooltip的content，而没有隐藏axisPointer

Version & Environment [版本及环境]

ECharts version [ECharts 版本]: 3.5.4
Browser version [浏览器类型和版本]: Chrome
OS Version [操作系统类型和版本]: Mac OS

Expected behaviour [期望结果]

ECharts option [ECharts配置项]

Other comments [其他信息]
如果需要我会补充代码以及截图

**Comment by tedpenk** [comment]
@duxinxiao 和你遇到同样的问题
```javascript { .theme-peacock }
var typeObj = type === 'showTip' ? {
       type: type,
       dataIndex: allIdIndex,
       seriesIndex: 0
 } : {
       type: type
};
plan1.dispatchAction(typeObj);
```
type 为 hideTip 时，悬浮框消失了，shadow没有消失：
![image](https://user-images.githubusercontent.com/7235487/27852201-c368574c-6190-11e7-977e-7be7b74e8a9d.png)
->
![image](https://user-images.githubusercontent.com/7235487/27852257-153278b4-6191-11e7-8bbf-13247b485ade.png)

**Comment by tedpenk** [comment]
@duxinxiao 联系了作者，先用以下方法解决：
```javascript { .theme-peacock }
myChart.dispatchAction({
    type: 'hideTip'
});
myChart.dispatchAction({
    type: 'updateAxisPointer',
    currTrigger: 'leave'
})
```

**Comment by duxinxiao** [comment]
@tedpenk 多谢指出，我回去试一下看看

**Comment by JsonShare** [comment]
感谢 我也遇到了，@tedpenk

**Comment by humorHan** [comment]
> ```js
> 
> ```

5.x依然有这个bug。。。

**Comment by SpiritQAQ** [comment]
感谢，用上了
