### ISSUE TITLE
如何获取 axisPointer 的X轴坐标值

### ISSUE THREAD

**Issue by yi-jy** [apache/incubator-echarts#5830]
### One-line summary [问题简述]

![axisPointer](https://thumbnail0.baidupcs.com/thumbnail/78a8a8651d390c9ee29796c7ebbf0cf8?fid=3098163580-250528-227506289971478&time=1495620000&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-ABAxIJYK1ah3CZl38srHwUGuxx0%3d&expires=8h&chkbd=0&chkv=0&dp-logid=3334903197791282066&dp-callid=0&size=c1440_u900&quality=90)

如图，我想根据蓝色线（即 `axisPointer`）的X轴坐标值，来设置灰色透明层（即 `tooltip`）的位置。

目的是，无论鼠标移到什么位置，出现的  `axisPointer` 都与 `tooltip`  保持相同的水平间距，**并且  `tooltip` 的垂直位置不变。**

我看了下 `tooltip` 中的 `position` 属性，发现使用默认的值时，`axisPointer` 与  `tooltip` 的确是保持相同的水平间距（除了最后一项， `tooltip` 会在 `axisPointer` 的左边），但是， `tooltip` 层会根据鼠标位置的上下移动，也就是  `tooltip` 的垂直位置会变化。

所以，我自定义了  `tooltip` 的  `position` 属性，希望获取  `axisPointer` 的 X 轴坐标，来设置  `tooltip` 的位置 。通过使用：

```js
position: function (pos, params, dom, rect, size) {
      
  // point: 鼠标位置，如 [20, 40]。
  // params: 同 formatter 的参数相同。
  // dom: tooltip 的 dom 对象。
  // rect: 只有鼠标在图形上时有效，是一个用x, y, width, height四个属性表达的图形包围盒。
  // size: 包括 dom 的尺寸和 echarts 容器的当前尺寸，例如：{contentSize: [width, height], viewSize: [width, height]}

  // 希望 X 的值是根据   `axisPointer` 的位置来定义
  return [x, 20];
}
```
但发现，这里面与坐标相关的，只有 `point`，并没有与 `axisPointer` 相关的坐标信息。

请问，有什么方法可以解决吗？谢谢！

我是使用 [在线demo](http://echarts.baidu.com/echarts2/doc/example/line3.html) 测试的。

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: 2.0
+ Browser version [浏览器类型和版本]: chrome57
+ OS Version [操作系统类型和版本]: windows7 

### Expected behaviour [期望结果]

灰色透明层 与 蓝色线 保持相同的水平间距，并且，灰色透明层 的垂直位置不变。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by iskWang** [comment]
有类似的问题，希望透过点击事件(Click Event)事件取出 axisPointer 里面的 X, Y 值，用來更改 React setState 的部分

目前参考：[触屏 tooltip 和 dataZoom 示例](http://echarts.baidu.com/demo.html#line-tooltip-touch)
