### ISSUE TITLE
stock chart : Heiken Ashi & Ichimoku

### ISSUE THREAD

**Issue by cogitologue** [apache/incubator-echarts#5862]
I would like to display the Ichimoku kinko hyo indicator with my candlesticks for my stocks charts
How can we display calculated data for an indicator, and display them in the future with an existing dataset ?
I have tried several things, adding empty dates to my initiial dataset...but stocks data are empty...
and I always have some problems with the zoom
If you could add this or give some advice to solve, I would appreciate !

and is there an option to use Heiken Ashi candlesticks ?
eCharts is awesome !

**Comment by 100pah** [comment]
I think that Heiken Ashi candlesticks can be used directly, after processing raw data by Heiken Ashi definitions.
