### ISSUE TITLE
echarts3 地图关于内蒙古和黑龙江的问题，在内蒙古区域内有个小点，滑动到黑龙江，小点也会变色

### ISSUE THREAD

**Issue by KunTian** [apache/incubator-echarts#5910]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by KunTian** [comment]
[http://echarts.baidu.com/demo.html#map-china-dataRange](url)

**Comment by efbfbd** [comment]
搜下'加格达奇', 百科有相关词条

**Comment by hanasakari** [comment]
飞地的问题吧。。这个交汇处是传说中的加格达奇
