### ISSUE TITLE
click 事件与拖动问题

### ISSUE THREAD

**Issue by icode** [apache/incubator-echarts#5919]
鼠标点击事件不对，我拖动一个圆停止后会触发click，拖动后应该就不要触发click了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  最新版本
+ Browser version [浏览器类型和版本]: chrome 最新版本
+ OS Version [操作系统类型和版本]: ubuntu 16

### Expected behaviour [期望结果]

拖动圆圈后不要触发click了，拖动和click要分开

### ECharts option [ECharts配置项]
```javascript
option = {
title: {
        text: ''
    },
    tooltip: {},
    animationDurationUpdate: 1500,
    animationEasingUpdate: 'quinticInOut',
    legend: {
        x: "center",
        show: true,
        data: ["朋友", "战友", '亲戚']
    },
    series: [

        {
            type: 'graph',
            layout: 'force',
            symbolSize: 80,
            focusNodeAdjacency: true,
            edgeSymbolSize: [8, 8],
            roam: true,
            categories: [{
                name: '朋友',
                itemStyle: {
                    normal: {
                        color: "#009800",
                    }
                }
            }, {
                name: '战友',
                itemStyle: {
                    normal: {
                        color: "#4592FF",
                    }
                }
            }, {
                name: '亲戚',
                itemStyle: {
                    normal: {
                        color: "#f592Ff",
                    }
                }
            }],
            label: {
                normal: {
                    show: true,
                    textStyle: {
                        fontSize: 12
                    },
                }
            },
            force: {
                repulsion: 1000
            },
            edgeLabel: {
                normal: {
                    show: true,
                    textStyle: {
                        fontSize: 10
                    },
                    formatter: "{c}"
                }
            },
            data: [{
                name: '徐贱云',
                draggable: true,
                    itemStyle: {
                        normal: {
                            borderWidth: 3,
                            borderColor:"#f592Ff"
                        }
                    }
            }, {
                name: '冯可梁',
                category: 0,
                draggable: true,
            }, {
                name: '邓志荣',
                category: 1,
                draggable: true,
            }, {
                name: '李荣庆',
                category: 2,
                draggable: true,
            }, {
                name: '郑志勇',
                category: 2,
                draggable: true,
            }, {
                name: '赵英杰',
                category: 2,
                draggable: true,
            }, {
                name: '王承军',
                category: 2,
                draggable: true,
            }, {
                name: '陈卫东',
                category: 1,
                draggable: true,
            }, {
                name: '邹劲松',
                category: 1,
                draggable: true,
            }, {
                name: '赵成',
                category: 1,
                draggable: true,
            }, {
                name: '陈现忠',
                category: 1,
                draggable: true,
            }, {
                name: '陶泳',
                category: 1,
                draggable: true,
            }, {
                name: '王德福',
                category: 1,
                draggable: true,
            }],
            links: []
        }
    ]
}


    chart.on('click', function (params) {
        if (params.dataType === 'node') {
            alert(params.data.name)
        }
    });
```

**Comment by xiefangzhenz** [comment]
你好，解决了吗？

**Comment by cuijian-dexter** [comment]
@xiefangzhenz It has been repaired. You can try it.

**Comment by xiefangzhenz** [comment]
@cuijian-dexter 非常感觉，这么快更新了。之前我用鼠标事件解决了，以下是处理方法。
过段时间我再次更新下新版本试试。
chart.on("click", function(param) {
                     currentProvince = param.data.name;
                     chart.dispatchAction({
                                          type: 'downplay'
                                          });
                     chart.dispatchAction({
                                          type: 'highlight',
                                          
                                          name: currentProvince
                                          })
                     if(currentProvince != "") {
                     changeProvince(currentProvince)
                     }
                     });

                              chart.on("mousedown", function(param) {
                                       
                                    
                                       //因为mouseDownFun每次都会调用的，在这里重新初始化这个变量
                                       isDrag = false;
                                       //延迟100ms
                                       timmerHandle = setTimeout(setDragTrue, 200);
                                       });
                                       chart.on("mouseup", function(param) {
                                                
                                                if(!isDrag) {
                                                //先把doMouseDownTimmer清除，不然200毫秒后setGragTrue方法还是会被调用的
                                                clearTimeout(timmerHandle);
                                                console.log("mouse up.");
                                                isClick = true;
                                                
                                                chart.dispatchAction({
                                                                     type: 'downplay'
                                                                     });
                                                chart.dispatchAction({
                                                                     type: 'hideTip'
                                                                     })
                                                
                                                chart.dispatchAction({
                                                                     type: 'highlight',
                                                                     
                                                                     name: currentProvince
                                                                     })
                                                
                                                } else {
                                                isDrag = false;
                                                console.log("draging over.");
                                                isClick = false;
                                                
                                                chart.dispatchAction({
                                                                     type: 'downplay'
                                                                     });
                                                chart.dispatchAction({
                                                                     type: 'hideTip'
                                                                     })
                                                chart.dispatchAction({
                                                                     type: 'highlight',
                                                                     
                                                                     name: currentProvince
                                                                     })
                                                
                                                }
                                                });

**Comment by xiefangzhenz** [comment]
@cuijian-dexter  刚才试了下，按住地图进行上下左右拖动，依然会随着拖动，不停的变化省份。

**Comment by 100pah** [comment]
@xiefangzhenz What is your echarts version? I can not reproduce it in the latest version of echarts.

**Comment by zhangchengshan** [comment]
+1

**Comment by xiefangzhenz** [comment]
@cuijian-dexter  用的最新的版本，在网站下载的，大约在github更新后的3-5天之左右下载的。

**Comment by cuijian-dexter** [comment]
@xiefangzhenz  This issue option is about relational graphs. What do you mean by maps?
If you're talking about maps, I suggest you bring up a new issue with an example.

**Comment by xiefangzhenz** [comment]
@cuijian-dexter  恩 明白了，谢谢
