### ISSUE TITLE
chart的label字体显示有重叠（重影）问题

### ISSUE THREAD

**Issue by Mignon-han** [apache/incubator-echarts#5922]
chart的label字体显示有重叠（重影）问题

+ ECharts version: 3.61
+ Browser version: Chrome
+ OS Version: WIN 10

下面是我录屏的GIF:
![bug](https://cloud.githubusercontent.com/assets/16368087/26825130/796d0a7c-4ae6-11e7-83f7-05ad9b169d38.gif)

当拖动使显示容器变小，调用resize，chart的label会重影，也可以在其他chart类型重现（Bar Chart）

**Comment by xpxs** [comment]
换个浏览器看看，你是不是更新了浏览器版本

**Comment by Mignon-han** [comment]
刚在你们官网试了一下，也有这个问题（chrome）

**Comment by suifengfengye** [comment]
怎么解决的呢？

**Comment by Mignon-han** [comment]
@suifengfengye 依然存在，这是echarts的浏览器兼容性问题，还是得echarts自己解决。

**Comment by pissang** [comment]
我无法在 win 10 的最新版本 chrome 上复现，能否提供更详细的代码和环境信息？

**Comment by suifengfengye** [comment]
我这里是偶发的，很难复现，@Mignon-han，你能提供一定复现的代码不？

**Comment by Mignon-han** [comment]
```
app.title = '坐标轴刻度与标签对齐';

option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLabel:{
                textStyle:{
                    color:'yellow'
                }
            }
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220]
        }
    ]
};

```

在官方实例中打开，把浏览器缩小到 200*200左右，就可以看到了

**Comment by Mignon-han** [comment]
![tt](https://user-images.githubusercontent.com/16368087/27318596-e4254698-55bf-11e7-9eae-d9338015e8d9.png)

**Comment by pissang** [comment]
好吧还真是，我们看下是什么原因

**Comment by Mignon-han** [comment]
@pissang 希望尽快做到这个 #5849 

还有legend能做到自适应，echarts的配置确实很完善，但这些需要自适应的地方，单纯靠配置还是很难适应各种情况的。
# #

**Comment by taipeiwu** [comment]
我也有發生同樣的問題，一開始的預設資料不會，但如果reload就會發生疊字情形，重現步驟如下：
```
chartOption = 預設series(含data資料);
chartOption = Object.assign({}, this.chartOption5);
echarts.setOption(chartOption);
echarts.resize();
```

**Comment by kagol** [comment]
这个重影问题解决了吗？ @pissang

**Comment by kagol** [comment]
我也遇到过这个问题，解决方案是在init方法中加devicePixelRatio参数即可解决：
ECharts.init(el, null, {devicePixelRatio: 2})
@pissang @Mignon-han

**Comment by algoqt** [comment]
现在还是有这个问题啊。 这默认字体 显示很糟糕，调试了几个参数都没用 fontFamily fontWeight
![image](https://github.com/apache/echarts/assets/93410715/5c00223d-b5ef-4d8b-a35c-b9e7557dc209)

**Comment by algoqt** [comment]
![image](https://github.com/apache/echarts/assets/93410715/e2d41b3a-e140-402c-ab5b-2f885f06eb27)
换了dark 主题 就显示正常。。。 哪里参数可以设置
