### ISSUE TITLE
echarts3 地图关于广东和澳门属于同一区域的问题

### ISSUE THREAD

**Issue by lijun007** [apache/incubator-echarts#5934]
### One-line summary [问题简述]
在用echarts3地图时，发现广东的区域范围包括了澳门地区。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:Google Chrome，FireFOx
+ OS Version [操作系统类型和版本]:WIN10

### Expected behaviour [期望结果]
两个区域能够区分开

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
哪个地图？

**Comment by lijun007** [comment]
@pissang 官网上的地图下载里的中国地图

**Comment by pissang** [comment]
台湾地图暂时获取不到区县的数据
