### ISSUE TITLE
echarts官网工具栏里的地图数据在线生成工具，生成新疆下的阿拉尔市和五家渠市的json，（是否包含子区域 subregion，选择是）和（压缩文件，选择否）会报错生成不了json

### ISSUE THREAD

**Issue by yaoduanwu** [apache/incubator-echarts#5940]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by nqdy666** [comment]
同问：新疆下的 石河子市， 阿拉尔市， 图木舒克市， 五家渠市都无法生成json
