### ISSUE TITLE
custom series 里图元不能响应事件

### ISSUE THREAD

**Issue by llvim** [apache/incubator-echarts#5965]
### One-line summary [问题简述]
custom series里添加的图元不会响应鼠标事件，

### Version & Environment [版本及环境]
在option里直接使用图元
http://gallery.echartsjs.com/editor.html?c=xS1V4ky_fb&v=1
在custom series 使用图元
http://gallery.echartsjs.com/editor.html?c=xByItkJdG-&v=1

### Expected behaviour [期望结果]
在里使用能够console.log, 在custom series 使用图元不会调用

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

在option里直接使用图元
http://gallery.echartsjs.com/editor.html?c=xS1V4ky_fb&v=1
在custom series 使用图元
http://gallery.echartsjs.com/editor.html?c=xByItkJdG-&v=1

**Comment by 100pah** [comment]
目前，使用 

```js
chart.on('cilck', function () {
   ...
});
```

是可以监听到图元的事件的。

**Comment by biolee** [comment]
这样也可以，不过这样得到信息的粒度就没有直接监听图元事件那么细，当然一般的需求应该会满足，（如果实在是需要，自己写相交测试也能得到相应信息）

PS，目前设计里graphic层级有计划添加阻止事件bubble的API么
