### ISSUE TITLE
关系图之力导向图配置项中categories配置symbol无效

### ISSUE THREAD

**Issue by funlee** [apache/incubator-echarts#5969]
关系图之力导向图中，想实现目标节点的symbol有两种不同的样式，故配置了categories选项，分别指定了各自类目对应的symbol样式，包含‘rect’，‘roundRect’，在data中对每个数据项指定了category，但渲染后的结果是所有的目标节点的symbol都是‘circle’，没能实现理想的需求。

[实例请戳](http://gallery.echartsjs.com/editor.html?c=xrJY9Ogsf-&v=4)

截图如下：
![示例](http://show.funlee.cn/initblog/source.jpg)

我知道可以通过给每个data数据项指定symbol样式来解决，但我想知道为什么通过categories来指定就不行呢，实际测试了给categories配置itemStyle选项是可以生效的，symbol就不行。

**Comment by xh476645818** [comment]
是的，我也遇到了同样的问题

**Comment by mmryzmr** [comment]
嘻嘻  我也是哟

**Comment by haoLingLing** [comment]
meto ,有什么解决办法么

**Comment by hanwenhui** [comment]
这么巧，我也是

**Comment by AlkalizZ** [comment]
我也遇到了同样的问题
