### ISSUE TITLE
3.6版本中世界地图中，怎么只显示一个国家的地图？

### ISSUE THREAD

**Issue by xwxing4444** [apache/incubator-echarts#5991]
2.2.7 版本中可以使用    mapType: 'world|Zambia',  来显示，但在3.6 版本中不能使用，有没有 world.js  带子区域的地图了？

### One-line summary [问题简述]

2.2.7 版本中可以使用    mapType: 'world|Zambia',  来显示，但在3.6 版本中不能使用，有没有 world.js  带子区域的地图了？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by closertb** [comment]
这个功能扩展了吗？我讲中国地图的数据复制进世界地图，会报错，好像是coordinates数据项不一致的问题
