### ISSUE TITLE
如何通过action触发toolbox里datazoom的区域缩放功能，而不是用鼠标点击

### ISSUE THREAD

**Issue by dodospace** [apache/incubator-echarts#5994]
### One-line summary [问题简述]

如何通过action触发toolbox里datazoom的区域缩放功能，而不是用鼠标点击

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.4
+ Browser version [浏览器类型和版本]: Chrome 54.x
+ OS Version [操作系统类型和版本]: Mac osx

### Expected behaviour [期望结果]

是否有dispatchAction的方法切换toolbox里datazoom的区域缩放打开与关闭功能，翻阅了API以及配置文档，没有发现，必须要通过点击一次区域缩放按钮才能开启此功能，期望是不显示这个工具icon，自动打开数据内框选缩放功能

### ECharts option [ECharts配置项]

```javascript
option = {
  toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            }
        }
    },
}

```

**Comment by bxd602** [comment]
我也想知道 是不是应该有个配置项可以设置这个开关

**Comment by huangwenxuan** [comment]
楼主找到解决方法了吗？我最近也想解决这个小问题，麻烦请教一下~~

**Comment by dodospace** [comment]
还没找到啊，很纠结啊！

**Comment by bxd602** [comment]
@pissang 大神来指导下~~

**Comment by zhouzhili** [comment]
同求

**Comment by Pearnest** [comment]
可以通过dispatchAction触发dataZoom，详见官方文档：
http://echarts.baidu.com/api.html#echartsInstance.dispatchAction
http://echarts.baidu.com/api.html#action.dataZoom.dataZoom

**Comment by FionaFromChina** [comment]
遇到同样问题，查看源码其实现，见：https://github.com/apache/incubator-echarts/blob/master/src/component/toolbox/feature/DataZoom.js
可通过dispatchAction实现。
注：必须先设置了```toolbox.feature.dataZoom.show: true```，后面的dispatchAction才会生效。
代码如下：
```js
this.chart.dispatchAction({
        type: 'takeGlobalCursor',
        key: 'dataZoomSelect',
        dataZoomSelectActive: true // 允许缩放
      })
```
项目要求始终允许缩放，且不显示icon，所以将icon的图标换成了透明色。假装不存在(🤦‍♀️)
