### ISSUE TITLE
地图移动端性能太差（帧率低）

### ISSUE THREAD

**Issue by forprogram** [apache/incubator-echarts#6004]
### One-line summary [问题简述]
在只配置了geo项的情况下在移动端或者pc端浏览器的cpu限制在1/2或者1/5的时候，拖拉以及缩放频繁出现卡顿。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:安卓5.1微信内置浏览器、ios10.3微信内置浏览器、google chrome 59（限cpu调试用）
+ OS Version [操作系统类型和版本]:IOS、安卓、macOS

### Expected behaviour [期望结果]

期望拖拉和缩放的帧率能在30或者40以上

### ECharts option [ECharts配置项]

```javascript
option = {
  geo: {
      map: '广东',
      label: {
        emphasis: {
          show: false
        }
      },
      roam: true,
      silent: true,
      animation: false,
    },
    animation: false,
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/17009417/27213609-94faa23e-529a-11e7-9750-e3d3d881de55.png)
图片为在chrome59下 cpu限制为1/5情况下的运行情况

**Comment by forprogram** [comment]
猜测是touch事件引起的无用渲染导致，如需更多截图或者信息，麻烦告知，感谢。

**Comment by pissang** [comment]
去掉 silent 试试？

**Comment by forprogram** [comment]
@pissang   去掉silent的话，geo会响应mousemove跟touchmove事件，然后在拖拽地图的时候，以这个demo为例，市级地图的轮廓跟背景就会高亮。卡顿没有解决的迹象。而且，去掉silent的话，浏览器要处理的任务更多了，直觉上，只会更慢。请问还有什么方式可以尝试吗？

**Comment by forprogram** [comment]
求回复

**Comment by forprogram** [comment]
@pissang @leeight @cnberg @firede @chriswong

**Comment by gaoshijun1993** [comment]
遇到了同样的问题

**Comment by gaoshijun1993** [comment]
@forprogram  请问你是怎么解决的呢?
