### ISSUE TITLE
【Bug】不断左滑右滑图表，数据点不消失

### ISSUE THREAD

**Issue by JerryMissTom** [apache/incubator-echarts#6016]
### One-line summary [问题简述]
我们使用ionic V3.X版本开发app，将代码打包后的www文件夹放在服务器上，用原生写一个带WebView的壳App，然后通过url访问www中的内容。图表显示后，不断进行左滑右滑操作，会出现之前的数据点不消失的情况

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]:  UserAgent信息：
 Mozilla/5.0 (Linux; Android 6.0; PRO 6 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.146 Mobile Safari/537.36
+ OS Version [操作系统类型和版本]:  魅族Flyme 6.1.0.0A   Android 6.0

### Expected behaviour [期望结果]
可以正常响应手势操作，图表不会出错

### ECharts option [ECharts配置项]
```javascript
option = {
     title: {
        text: '表格',
        left: 'center'
      },
      color: ['#3398DB'],
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      tooltip: {
        trigger: 'item'
      },
      xAxis: [
        {
          type: 'category',
          data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', '1', '2', '3', '4'],
          axisLabel: { interval: 0 }
        }
      ],
      yAxis: [
        {
          type: 'value'
        }
      ],
      series: [
        {
          name: '访问量',
          type: 'line',
          data: [10, 52, 200, 334, 390, 330, 220, 110, 150, 200, 180],
          symbolSize: 16
        }
      ]
}
```

### Other comments [其他信息]
![wechatimg2](https://user-images.githubusercontent.com/15966403/27267441-f7ab2e20-54da-11e7-84e7-062f32c0a433.jpeg)

**Comment by pissang** [comment]
原生浏览器有这个问题么？

**Comment by JerryMissTom** [comment]
我们通过ionic serve指令在本地浏览器中调试，也会发现这样的情况。但是没有在剔除ionic环境，只使用浏览器的条件下验证过，结果未知。
