### ISSUE TITLE
echarts从曲线图切换到柱状图时，柱状图无法显示出来，但是提示还是有的

### ISSUE THREAD

**Issue by zapjone** [apache/incubator-echarts#6044]
### One-line summary [问题简述]
从曲线图转换到柱状图时，柱状图没有显示出来，数据量比较大
这是曲线图：
![image](https://user-images.githubusercontent.com/19503929/27415486-c40259fc-5739-11e7-9bd2-0419adcb0100.png)

这是切换后的柱状图：
![image](https://user-images.githubusercontent.com/19503929/27415565-2d7b712a-573a-11e7-92a8-a508efa0fb6c.png)

数据大约有18000多条

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
具体描述你的配置项和 echarts 版本
