### ISSUE TITLE
饼图标签可否像坐标轴刻度标签一样设置显示间隔

### ISSUE THREAD

**Issue by zhouboluo** [apache/incubator-echarts#6050]
### One-line summary [问题简述]

![qq 20170622141006](https://user-images.githubusercontent.com/7812751/27419692-db483dc8-5754-11e7-90c6-e593dbd4c803.png)

如图，如果饼图的分类非常多，标签会超出视图区域。可否像坐标轴刻度标签一样，自动计算隐藏部分
标签，也可以设置axisLabel.interval指定显示间隔，当然可以强制显示所有标签。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![qq 20170622141201](https://user-images.githubusercontent.com/7812751/27419713-f3162636-5754-11e7-99ed-9f14ef3722ea.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你可以设置每个数据的标签是否显示，可以只显示那些重要的标签
