### ISSUE TITLE
饼状图hover上去的宽度无法修改？

### ISSUE THREAD

**Issue by Rainmen-xia** [apache/incubator-echarts#6076]
### One-line summary [问题简述]

饼状图，hover上去感觉太宽了，目前看来应该是一个比例？无法修改呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

希望能够修改

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没办法修改

**Comment by Rainmen-xia** [comment]
果然。。有办法从源码里面修改吗？

**Comment by Rainmen-xia** [comment]
另外饼状图选中效果失焦之后就取消了。有办法在失焦之后还保持选中么？线形图表的tooltip经常点到其他地方不会自动消失，有啥好的建议让它消失么？
