### ISSUE TITLE
effectScatter 水波效果时如何设置波纹的粗细度？

### ISSUE THREAD

**Issue by hele10086** [apache/incubator-echarts#6108]
### One-line summary [问题简述]
effectScatter 水波效果时如何设置波纹的粗细度？貌似没有配置支持？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
可配置水波波纹的粗细

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by TabEnter** [comment]
同样的问题，在4k屏幕上展示时默认的涟漪宽度太细了，没找到相应的配置项
