### ISSUE TITLE
ECharts 地图数据在线生成工具 崩溃了

### ISSUE THREAD

**Issue by haoLingLing** [apache/incubator-echarts#6112]
### One-line summary [问题简述]
在使用ECharts 地图数据在线生成工具时，一直在报错
![image](https://user-images.githubusercontent.com/25626661/27813706-403e96c4-60aa-11e7-8ad5-5cdbb443112b.png)

在2.0 版本和3.0 版本都在报错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by dogsmall** [comment]
遇到相同问题~

**Comment by 100pah** [comment]
现在应该可以了
