### ISSUE TITLE
图像消失

### ISSUE THREAD

**Issue by Vevinlong** [apache/incubator-echarts#6127]
### 图像消失
正常在浏览器中打开多个页面，当切换不同页面时，会发生图标丢失的情况，此时再次切换到其他页面，然后马上切换回来图像又重新出现

### 官网示例
+ 官网示例: http://echarts.baidu.com/gallery/editor.html?c=doc-example/getting-started
+ UC浏览器:6.1.2716.5  （极速内核：50.0.2661.102  兼容内核：11.0.9600.18698）极速模式下
+ win7旗舰版

### 期望结果
切换tab页后，再回到页面时，图像依然存在

### 截图
![image](https://user-images.githubusercontent.com/19657897/27846017-cd9c3de8-6166-11e7-9568-da6be7939597.png)

**Comment by Vevinlong** [comment]
因为在项目中有这个问题，然后就打开官网示例测试

**Comment by hanfengcan** [comment]
我也遇到这问题.

如果resize被调用就会显示出来.

饼图,鼠标移动过去也会显示出来
