### ISSUE TITLE
echart3，当前最新版本,chrome,win7。福建地区热力图显示不全。 如果 改为散点图则正确显示。

### ISSUE THREAD

**Issue by linbren** [apache/incubator-echarts#6133]
图见下方回复部分，代码已上传，导入福建js底图。

1、echart3，当前最新版本,chrome,win7。福建地区热力图显示不全。
如果 改为散点图则正确显示。

2、tooltip在这里无效。在scatter中又正常。
echart2.0 chrome win7 tooltip又正常。

### ECharts option [ECharts配置项]

var vdata = 
[	[	119.31056159 	,	26.16902447	,	253	]	,
	[	119.30615225 	,	26.15397103	,	73	]	,
	[	119.37128478 	,	26.1205245	,	100	]	,
	[	119.38218096 	,	26.05828769	,	64	]	,
	[	119.54898327 	,	26.08174508	,	0	]	,
	[	119.38746318 	,	26.15578374	,	73	]	,
	[	119.17705059 	,	26.1990197	,	10	]	,
	[	119.55632006 	,	26.27219822	,	25	]	,
	[	119.61374019 	,	26.57202821	,	87	]	,
	[	118.90682573 	,	26.2777418	,	43	]	,
	[	118.94435532 	,	25.93100938	,	8	]	,
	[	119.81663517 	,	25.56266529	,	298	]	,
	[	119.38801141 	,	25.78352415	,	21	]	,
	[	119.58265119 	,	26.05150645	,	50	]	,
	[	118.15556332 	,	24.48730606	,	73	]	,
	[	118.10256740 	,	24.46882516	,	9	]	,
	[	118.04708168 	,	24.55477986	,	53	]	,
	[	118.15075633 	,	24.55439916	,	38	]	,
	[	118.12061348 	,	24.5891261	,	87	]	,
	[	118.22995517 	,	24.79158073	,	69	]	,
	[	118.27806052 	,	24.7010614	,	80	]	,
	[	119.08694747 	,	25.52509028	,	10	]	,
	[	119.02363781 	,	25.48995527	,	41	]	,
	[	119.15003125 	,	25.54481953	,	98	]	,
	[	119.05279339 	,	25.46396116	,	13	]	,
	[	119.14145963 	,	25.32722046	,	7	]	,
	[	118.71831914 	,	25.37937861	,	35	]	,
	[	117.71762545 	,	26.29860661	,	23	]	,
	[	117.72600691 	,	26.31701497	,	51	]	,
	[	117.66971619 	,	26.25439702	,	57	]	,
	[	117.20817079 	,	26.3971626	,	45	]	,
	[	116.91233754 	,	26.26072236	,	75	]	,
	[	116.72344393 	,	26.32668957	,	41	]	,
	[	117.92217202 	,	25.71205423	,	2	]	,
	[	118.26824224 	,	26.25583532	,	2	]	,
	[	117.84723270 	,	26.42646178	,	23	]	,
	[	117.52145102 	,	26.76167506	,	18	]	,
	[	117.24292388 	,	26.96691714	,	65	]	,
	[	116.90224596 	,	26.8739072	,	62	]	,
	[	117.44166091 	,	26.04355555	,	78	]	,
	[	118.75487748 	,	24.89398448	,	96	]	,
	[	118.69316306 	,	25.00688253	,	91	]	,
	[	118.64824563 	,	24.97881219	,	54	]	,
	[	118.72763997 	,	24.95048037	,	60	]	,
	[	118.93183671 	,	25.16047533	,	82	]	,
	[	118.82090639 	,	25.12251624	,	43	]	,
	[	118.26928530 	,	25.13544335	,	78	]	,
	[	118.39611174 	,	25.3701017	,	74	]	,
	[	118.25309496 	,	25.56877668	,	93	]	,
	[	118.37261160 	,	24.49610994	,	15	]	,
	[	118.67918080 	,	24.77339171	,	80	]	,
	[	118.67075962 	,	24.91487474	,	37	]	,
	[	118.44131715 	,	25.05847669	,	68	]	,
	[	117.73193428 	,	24.575044	,	9	]	,
	[	117.65915704 	,	24.55553814	,	62	]	,
	[	117.75449621 	,	24.52430811	,	29	]	,
	[	117.35560500 	,	23.95355189	,	13	]	,
	[	117.64509661 	,	24.1956125	,	13	]	,
	[	117.22673790 	,	23.80400053	,	68	]	,
	[	117.78784037 	,	24.66594184	,	6	]	,
	[	117.48056643 	,	23.73887407	,	26	]	,
	[	117.46971383 	,	24.58450389	,	87	]	,
	[	117.35342447 	,	24.39529232	,	73	]	,
	[	117.59242255 	,	25.1156526	,	0	]	,
	[	117.89141140 	,	24.51797692	,	82	]	,
	[	118.25662254 	,	26.71674563	,	93	]	,
	[	118.20825544 	,	26.65540428	,	28	]	,
	[	117.80891162 	,	26.86206158	,	16	]	,
	[	118.53340315 	,	27.95324673	,	31	]	,
	[	117.35111575 	,	27.62855535	,	85	]	,
	[	118.87564874 	,	27.57082906	,	40	]	,
	[	118.85928620 	,	27.38880041	,	41	]	,
	[	117.56416197 	,	27.41896786	,	7	]	,
	[	118.03030271 	,	27.85696646	,	12	]	,
	[	118.38342795 	,	27.10611356	,	30	]	,
	[	118.19508734 	,	27.39770354	,	75	]	,
	[	117.04808080 	,	25.17120211	,	82	]	,
	[	117.08618339 	,	25.13645094	,	53	]	,
	[	116.36426069 	,	25.87206054	,	80	]	,
	[	116.82637021 	,	24.81176452	,	13	]	,
	[	116.45846501 	,	25.09110239	,	25	]	,
	[	116.13857161 	,	25.18135408	,	100	]	,
	[	116.80395781 	,	25.7634687	,	67	]	,
	[	117.43691524 	,	25.37717284	,	44	]	,
	[	119.56204145 	,	26.71119287	,	85	]	,
	[	119.58938180 	,	26.71593507	,	46	]	,
	[	120.05215296 	,	26.89102793	,	60	]	,
	[	118.81152710 	,	26.60754452	,	39	]	,
	[	119.01119814 	,	26.92950271	,	82	]	,
	[	119.56185968 	,	27.53207419	,	62	]	,
	[	119.35542561 	,	27.19928907	,	37	]	,
	[	119.95222930 	,	27.24040649	,	86	]	,
	[	119.72541238 	,	27.1238428	,	38	]	,
	[	120.23155553 	,	27.40084124	,	67	]	,
	[	117.214839	,	23.876016	,	288	]	]
;

option = {
    title: {
        text: '',
        subtext: '',
        sublink: '',
        left: 'center',
        textStyle: {
            color: '#fff'
        }
    },
    backgroundColor: '#404a59',
    visualMap: {
        min: 0,
        max: 300,
        splitNumber: 5,
        inRange: {
            color: ['red','#d94e5d','#eac736','#50a3ba'].reverse()
        },
        textStyle: {
            color: '#fff'
        }
    },
    geo: {
        map: '福建',
        label: {
            emphasis: {
                show: false
            }
        },
        roam: true,
        itemStyle: {
            normal: {
                areaColor: '#323c48',
                borderColor: 'white'
            },
            emphasis: {
                areaColor: '#2a333d'
            }
        }
    },
       tooltip: {
        show:true,
          trigger:'item',        
          formatter: '大工业用户：150<br>居民用户:5000<br>综合价值分:{c}'
        },
    series: [{
        name: 'AQI',
        type: 'heatmap',
        coordinateSystem: 'geo',
        data:vdata
    }]
};

### Other comments [其他信息]

      把  type: 'heatmap', 改为scatter可看到正常

**Comment by linbren** [comment]
另外，tooltip在这里无效。在scatter中又正常。
echart2.0 chrome win7    tooltip又正常。

**Comment by linbren** [comment]
![image](https://user-images.githubusercontent.com/13880474/27854982-5cc73084-619b-11e7-8196-9ec5b4ab86b1.png)

**Comment by linbren** [comment]
![image](https://user-images.githubusercontent.com/13880474/27855281-7bf97e98-619c-11e7-9fbc-4bd31e45ecb2.png)

**Comment by linbren** [comment]
@leeight @cnberg @firede @chriswong @firedfox 
请问题哪位处理过类似问题？

**Comment by linbren** [comment]
@pissang 帮忙看看

**Comment by 100pah** [comment]
<http://gallery.echartsjs.com/editor.html?c=xSyhwhJMS-&v=1>
这里看可以显示全

**Comment by linbren** [comment]
@100pah 
的确可以。代码跟我的一模一样，放在官方editor中就不行区别在哪里呢？
tooltip应该要支持，而且最好能两种提示都支持，一个是底图的像echart2，一个是热点一定半径内的。

**Comment by linbren** [comment]
@100pah 您好，你的editor能否打个包给个下载地址？

**Comment by 100pah** [comment]
editor 的代码在 github 上：<https://github.com/ecomfe/echarts-examples>

**Comment by linbren** [comment]
![image](https://user-images.githubusercontent.com/13880474/28245061-72ab6710-6a30-11e7-8eff-4d7661a22698.png)
![image](https://user-images.githubusercontent.com/13880474/28245065-7ec90692-6a30-11e7-94fe-52fe0af7d98b.png)

@100pah 我就是从上面下载的,热图有明显确口，显然跟你的不一样。

**Comment by linbren** [comment]
@anyone help...

**Comment by 100pah** [comment]
怎样能使我复现出这个问题呢？

**Comment by linbren** [comment]
官方代码下载后，导入福建js地图就能重现。
http://echarts.baidu.com/demo.html#heatmap-map

**Comment by linbren** [comment]
`<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="./vendors/bootstrap/css/bootstrap.css" />
  
  
  <link rel="stylesheet" type="text/css" href="./stylesheets/main.css?_v_=1497515842063" />
  <title>ECharts Demo</title>
  <script type="text/javascript">window.EC_DEMO_LANG = 'en';
</script>
 </head>
 <body>
  <nav class="navbar navbar-default navbar-fixed-top">
   <div class="container-fluid">
    <div class="navbar-header">
     <button type="button" data-toggle="collapse" data-target="#navbar-collapsed" aria-expanded="false" class="navbar-toggle collapsed"><span class="sr-only">toggle</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
     <a class="navbar-brand">ECharts Demo</a>
    </div>
    <div id="navbar-collapsed" class="collapse navbar-collapse">
     <ul class="nav navbar-nav navbar-left">
      <li id="nav-explore"><a href="./index.html">All Demos</a></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
      <li><a href="javascript:;" onclick="downloadExample()">Download Demo</a></li>
      <li class="highlight"><a href="https://ecomfe.github.io/echarts-doc/public/index.html">ECharts Docs</a></li>
     </ul>
    </div>
   </div>
  </nav>
  <div id="main-container">
   <div id="code-container">
    <div id="control-panel">
     <div id="code-info"></div>
     <div class="control-btn-panel">
      <a href="javascript:;" onclick="disposeAndRun()" class="btn btn-default btn-sm">RUN</a>
     </div>
    </div>
    <div id="code-panel"></div>
   </div>
   <div id="h-handler" class="handler"></div>
   <div class="right-container">
    <div id="chart-panel" class="right-panel"></div>
   </div>
  </div>
  <script>if (window !== top) {
    var nav = document.getElementsByClassName('navbar')[0];
    nav.parentNode.removeChild(nav);
    document.getElementById('main-container').style.top = 0;
}</script>
  <script type="text/javascript" src="./vendors/jquery/jquery.js"></script>
  <script type="text/javascript" src="./vendors/bootstrap/js/bootstrap.js"></script>
  <script type="text/javascript" src="./vendors/lodash.js"></script>
  <script type="text/javascript" src="./vendors/dat.gui.min.js"></script>
  <script type="text/javascript" src="./vendors/echarts/echarts-all-3.js?_v_=1497515842063"></script>
  <script type="text/javascript" src="./vendors/echarts-stat/ecStat.min.js?_v_=1497515842063"></script>
  <script type="text/javascript" src="./vendors/echarts/map/js/china.js?_v_=1497515842063"></script>
  <script type="text/javascript" src="./vendors/echarts/map/js/world.js?_v_=1497515842063"></script>
  <script type="text/javascript" src="./vendors/echarts/map/js/province/fujian1.js?_v_=1497515842063"></script>

  <script type="text/javascript" src="./vendors/echarts/extension/dataTool.js?_v_=1497515842063"></script>
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=ZUONbpqGBsYGXNIYHicvbAbM"></script>
  <script type="text/javascript" src="./vendors/echarts/extension/bmap.js?_v_=1497515842063"></script>
  <script type="text/javascript" src="./vendors/ace/src/ace.js"></script>
  <script type="text/javascript" src="./vendors/ace/src/ext-language_tools.js"></script>
  <script type="text/javascript" src="./javascripts/editor.js?_v_=1497515842063"></script>
  <script type="text/javascript" src="./javascripts/hm.js"></script>
 </body>
</html>`

**Comment by linbren** [comment]
@100pah

**Comment by 100pah** [comment]
浏览器有报错么？或者浏览器有缩放么？我还是不太能复现这个问题。

**Comment by linbren** [comment]
无报错，无缩放。editor2与原件唯一区别是引入福建底图。
chrome和 fox都一样不行。@100pah
