### ISSUE TITLE
 graph 图形 data 和 link  数量太多，能否支持异步加载

### ISSUE THREAD

**Issue by wzwwzx100** [apache/incubator-echarts#6136]
### One-line summary [问题简述]

graph 图形 data 和 link  数量太多，能否支持异步加载
注：所有的link均由上层指向下层，结构更贴近tree

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:Chrome 59.0.3071.115
+ OS Version [操作系统类型和版本]:WIN7专业版SP1

### Expected behaviour [期望结果]

异步加载，通过点击node加载下级节点，类似tree的结构

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以试下监听 node 的点击时间后加载数据然后 setOption
