### ISSUE TITLE
Cannot read property 'dim' of undefined

### ISSUE THREAD

**Issue by TheNightElf** [apache/incubator-echarts#6139]
### Version & Environment [版本及环境] node 6
+ ECharts version [ECharts 版本]: Echarts 3.0
+ Browser version [浏览器类型和版本]: chrome 59
+ OS Version [操作系统类型和版本]: mac os

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有可以复现的代码么？

**Comment by TheNightElf** [comment]
我应该找到问题在哪了，reducer给k线的默认数据格式不对。应该是数据缺失导致的这个问题。今天在研究react+echarts动态加载数据呢。但是echarts每次更新数据都要重新调用一次setOption方法，我试着用改变数据的方式来改变echarts的视图，却没用。
