### ISSUE TITLE
how does it that use Echart create a new map

### ISSUE THREAD

**Issue by elfinYang** [apache/incubator-echarts#6142]
how does it that use Echart create a new map such as station map?

### One-line summary [问题简述]
need compatible IE6 IE7 IE8？

### Version & Environment [版本及环境]
+ ECharts version [2.0]:
+ Browser version [ IE6 IE7 IE8 谷歌 火狐]:
+ OS Version [windows 10]:

### Expected behaviour [期望结果]
是否可以用矩形树图实现

751712567@qq.com  need help

**Comment by pissang** [comment]
没懂，是否有样例图
