### ISSUE TITLE
markline label位置问题

### ISSUE THREAD

**Issue by chaserstrong** [apache/incubator-echarts#6152]
### One-line summary [问题简述]

3.0版本的echarts，在配置项api中
series[i]-line.markLine.label.normal.position 提供修改label位置的选项。
但是这个选项的一个问题是：如果label在图的边缘，且内容较多时，会出现溢出。
要是能右对齐边缘就好了.
下图实际markline的lable文本内容是：
此处dddddddddddddddddddddddddddddd离手

![image](https://user-images.githubusercontent.com/18061322/27903590-6f51b72a-626c-11e7-8277-87a9396dcbfc.png)

**Comment by yangligogogo** [comment]
一样的问题，希望能支持offset
