### ISSUE TITLE
resize动画如何关闭

### ISSUE THREAD

**Issue by kangkang07** [apache/incubator-echarts#6153]
### One-line summary [问题简述]

animation已设为False，调用resize时会有动画效果。如何关闭这个动画？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: chrome 55.0.2883.75
+ OS Version [操作系统类型和版本]: ubuntu 14.4

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 贴一个可以复现的代码？
