### ISSUE TITLE
markArea with calendar

### ISSUE THREAD

**Issue by corradio** [apache/incubator-echarts#6163]
Hello,

I'm trying to use markArea with this demo: https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-horizontal
Unfortunately, it seems like this is not possible. Can anyone help?

Thanks.

**Comment by pissang** [comment]
markArea doesn't support calendar coordinate system yet.

**Comment by corradio** [comment]
Thanks. Let me know when it does!

**Comment by corradio** [comment]
Any news on this?
