### ISSUE TITLE
两表联动+magicType的问题

### ISSUE THREAD

**Issue by chenyaoyi110** [apache/incubator-echarts#6170]
### One-line summary [问题简述]
现有表A表B两表，表B有magicType:['bar',‘line’];
表A的点击事件onclick会触发表B的数据重新加载；表B默认为柱状图
-----------------------------------------------------------
![image](https://user-images.githubusercontent.com/15223779/28000550-f101eed6-6558-11e7-918a-cf66367b2550.png)
无操作时，如图上所示；
1.先将表B切换为折线图展示，
2.触发表A的onclick事件使表B数据重新加载
--->>>这时表B会变为柱状图并且数据超出了坐标系中;（如下图所示）
![image](https://user-images.githubusercontent.com/15223779/28000578-22938e32-6559-11e7-8db0-130d9f2bb6e3.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.6.2
+ Browser version [浏览器类型和版本]:  浏览器：chrome 58.0.3029.110
+ OS Version [操作系统类型和版本]: Win10 64位

### Expected behaviour [期望结果]

正常显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by huoyuanyuanweb** [comment]
我也遇到这个问题了，请问您有解决方法没

**Comment by huoyuanyuanweb** [comment]
请问magicType:切换时，有没有2个图变成一模一样呢
