### ISSUE TITLE
地图可以做到数据聚合效果吗

### ISSUE THREAD

**Issue by HeNanBing** [apache/incubator-echarts#6182]
### One-line summary [问题简述]

想要做一个效果，正常情况下就显示省一级的数据，缩放最后会显示具体每个市级的数据，知道mapv有一个数据聚合的效果，请问echarts可以做吗，没查到有关的资料啊，有前辈知道吗，谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]

地图数据聚合效果

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

mapv上的例子：正常视图下显示聚合数据：
![tim 20170711113902](https://user-images.githubusercontent.com/13029560/28050028-b4a94b2a-662d-11e7-8bd9-f353280deb70.png)
放大之后，显示具体的数据：
![tim 20170711113926](https://user-images.githubusercontent.com/13029560/28050039-c46da5b0-662d-11e7-8e68-f9ec38c20fda.png)

**Comment by 100pah** [comment]
echarts 没有内置『数据聚合』。
但是可以在 echarts 外部计算聚合，在 echarts 中渲染结果。

**Comment by HeNanBing** [comment]
那要怎么做到很自然的切换呢，是不是就是缩放到一定比例换数据源嘛？

**Comment by 100pah** [comment]
恩是的，比如监听 `geoRoam` 事件，缩放到一定比例换数据源。

**Comment by 18144802250** [comment]
@100pah 非常感谢  我找了好久 终于找到这个事件了 给你100个赞
