### ISSUE TITLE
Markline的端点不在当前范围内，线就会消失

### ISSUE THREAD

**Issue by HeatherAda** [apache/incubator-echarts#6184]
### One-line summary [问题简述]

当利用scale缩放时端点不在当前区域内，线也看不见了。有解决方法吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
这确实是这么设定的，目前没有改变的方法。

**Comment by pissang** [comment]
可以试试用自定义系列画 markLine
