### ISSUE TITLE
vue2.0 中使用echarts 在mounted函数中init，但是图表只在第一次加载时显示。

### ISSUE THREAD

**Issue by keysple** [apache/incubator-echarts#6201]
### One-line summary [问题简述]
在vue项目中使用echatrs，npm安装。在一个组件的mounted中init图标，但是图表只在第一次页面加载时显示。重新刷新页面就不显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   Echatrs 3
+ Browser version [浏览器类型和版本]: 谷歌
+ OS Version [操作系统类型和版本]:  win10

` mounted :function (){
        this.drawCharts();
    },
 methods: {
      drawCharts: function () {
        var readNumCharts = echarts.init(document.getElementById('readNum'));
        var readFavorCharts = echarts.init(document.getElementById('readFavor'));
        readNumCharts.setOption({
          itemStyle: {
            normal: {
              color: '#81d4fa',
            }
          },
          textStyle: {},
          title: {text: '阅读本数'},
          xAxis: {
            data: ["我", "团队平均", "团队最高"]
          },
          yAxis: {},
          series: [{
            name: '销量',
            type: 'bar',
            data: [2, 4, 5]
          }]
        });
        readFavorCharts.setOption({
          title:{text:'阅读偏好'},
          legend: {
            orient: 'vertical',
            x: 'right',
            data:['IT','金融','行政','物流','制造']
          },
          series: [
            {
              name:'访问来源',
              type:'pie',
              radius: ['40%', '60%'],
              avoidLabelOverlap: false,
              label: {
                normal: {
                  show: false,
                  position: 'center'
                },
                emphasis: {
                  show: true,
                  textStyle: {
                    fontSize: '30',
                    fontWeight: 'bold'
                  }
                }
              },
              data:[
                {value:2, name:'IT'},
                {value:2, name:'金融'},
                {value:3, name:'行政'},
                {value:4, name:'物流'},
                {value:5, name:'制造'},
              ]
            }
          ]
        });
      },`

**Comment by Rainmen-xia** [comment]
vue没用对？

**Comment by keysple** [comment]
是init放在mounted函数里面了 vue其他部分没问题应该 我其他的组件都使用正常。

**Comment by zhangda47** [comment]
用react也出现了这个问题，echarts.init 计算出了错误了宽高
