### ISSUE TITLE
地图做引用标记

### ISSUE THREAD

**Issue by HeNanBing** [apache/incubator-echarts#6203]
### One-line summary [问题简述]

想要做一个只是标记，不知道如何处理啊

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.1
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]

地图引用标记

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

如图所示的这种效果
![tim 20170713184627](https://user-images.githubusercontent.com/13029560/28162947-a2672750-67fb-11e7-8166-671c9a1ea014.png)

**Comment by 100pah** [comment]
可以使用 [graphic](http://echarts.baidu.com/option.html#graphic) 
配合
[convertToPixel](http://echarts.baidu.com/api.html#echartsInstance.convertToPixel)
做。

**Comment by kongjibai** [comment]
请问您实现了这个功能了吗？是如何是实现的呢？求教！

**Comment by HeNanBing** [comment]
custom series 配合polyline或者polygon
