### ISSUE TITLE
require.config is not a function

### ISSUE THREAD

**Issue by shishuoshuo** [apache/incubator-echarts#6216]
和esri地图一起使用时，先加载地图，然后加载图表。

### One-line summary [问题简述]
报错：Uncaught TypeError: require.config is not a function
esri地图中 也是用了require baseurl是 http://js.arcgis.com/3.15/
导致 echarts 加载文件时所有的路径都是错误的类似
http://js.arcgis.com/3.15/zrender/dep/excanvas.js 
http://js.arcgis.com/3.15/echarts/echarts.js 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.2.7
+ Browser version [浏览器类型和版本]:360浏览器8.1
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

不加载地图没有问题，相反后加载地图，地图的ur就有问题。l

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
用最新版本的 echarts
