### ISSUE TITLE
官网树图在chrome浏览器点击不能下钻

### ISSUE THREAD

**Issue by then0917** [apache/incubator-echarts#6222]
### One-line summary [问题简述]
官网树图在chrome浏览器点击不能下钻，但是在firefox里边点击可以下钻；这是什么问题？是已知的么？
浏览器都是最新版；

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
哪个图在 chrome 不能下钻，请给个链接？

**Comment by then0917** [comment]
继续看了下，问题是不稳定重现；但是有一个状态是稳定的，页面渲染完后，不能立即点击下钻，如果立即点击就会出现不能下钻效果，并且这个时间长短也不稳定；这个情况是因为加载慢或者什么原因？
http://echarts.baidu.com/demo.html#treemap-drill-down

**Comment by then0917** [comment]
请问  树图官网从昨天到今天有更新？我昨天新建的demon，左击可以下钻，右击是自定义事件；怎么今天右击也变成下钻事件了？

**Comment by 100pah** [comment]
右键点击的问题已经修复。参见 5d9f5a4。但是官网不能立刻点击的问题，并没有复现。是否是网速慢导致呢。
