### ISSUE TITLE
dataZoom拖动图形移动时，能否让移动增加惯性？

### ISSUE THREAD

**Issue by bayun2** [apache/incubator-echarts#6230]
One-line summary [问题简述]

dataZoom拖动图形移动时，能否让移动增加惯性？

Version & Environment [版本及环境]

ECharts 版本 (ECharts version):
3.6.2
浏览器类型和版本 (Browser version):
Chrome
操作系统类型和版本 (OS Version):
mac

**Comment by 100pah** [comment]
为何要增加惯性呢？惯性是不是会导致不能精准定位？

**Comment by bayun2** [comment]
增加惯性会显得比较流畅吧，定位的话，应该只是在移动时增加移动的动画效果，可以考虑在move发生时，只有移动距离超过一定距离，才增加这个动画效果，短距离的移动可以不需要。

**Comment by bayun2** [comment]
另外最近在使用异步频繁拉取数据的时候，当每次拉取到数据，代码自动setOption来重绘图表时,如果刚好在移动指示器，会出现指示器卡主的情况。应该是由于移动指示器，和图表重绘同时发生了，所以指示器卡主了。这个场景，有木有什么解决方案。
