### ISSUE TITLE
饼图能不能实现如下形状

### ISSUE THREAD

**Issue by AntoniaQiao** [apache/incubator-echarts#6241]
![default](https://user-images.githubusercontent.com/19327642/28408385-dcc7c72e-6d69-11e7-8044-01fdf94d2ee5.png)

**Comment by 100pah** [comment]
圆角效果目前不支持

**Comment by Younger-Peng** [comment]
http://gallery.echartsjs.com/editor.html?c=xSkT-YuIAl
同问，我看到这个图有添加了一个尖角，但如果宽度小的话看起来就像是圆角一样，问题是，我看了半天也没看到这个是在什么地方配置的

**Comment by Ovilia** [comment]
Duplicate of #7121
