### ISSUE TITLE
setOption使用notMerge=true, lazyUpdate=false时的BUG

### ISSUE THREAD

**Issue by SpeedVan** [apache/incubator-echarts#6250]
### One-line summary [问题简述]
我使用geo配置和geoselectchanged事件，实现地图下钻，某些原因下我不能使用普通的setOption，把notMerge, lazyUpdate设为true, false后，更新后的配置（regions项）要重新触发geoselectchanged后才能生效。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.2和3.6.2 都有
+ Browser version [浏览器类型和版本]:chrome 52.0.2743.116 m
+ OS Version [操作系统类型和版本]:win10 家庭版

### Expected behaviour [期望结果]

配置立即生效，跟普通setOption差别在于自己手动合并

### ECharts option [ECharts配置项]

```javascript


option = {
    tooltip: {},

    geo: {
        map: 'china',
        label: {
            emphasis: {
                show: false
            }
        },
        roam: 'scale',
        selectedMode: 'multiple',
        itemStyle: {
            normal: {
                areaColor: '#323c48',
                borderColor: '#111'
            },
            emphasis: {
                areaColor: '#2a333d'
            }
        },
        
    },
    
};

myChart.on("geoselectchanged", function(params){
    this.setOption({
        geo: {
            map: 'china',
            label: {
                emphasis: {
                    show: false
                }
            },
            roam: 'scale',
            selectedMode: 'multiple',
            itemStyle: {
                normal: {
                    areaColor: '#323c48',
                    borderColor: '#111'
                },
                emphasis: {
                    areaColor: '#2a333d'
                }
            },
            regions:[{name:"广东", selected:true}]
        }
    },true,false)
})

```

### Other comments [其他信息]

使用以上代码在线上测试就行

**Comment by 100pah** [comment]
不好意思没有理解你的『期望』是什么。
参见你的代码的例子：<http://gallery.echartsjs.com/editor.html?c=xHyyP4jyUb&v=1>
点击一个省之后，广东会被自动选中。这是期望的还是不期望的？

**Comment by SpeedVan** [comment]
选中是期望的，但效果延后不是期望的，第一次触发geoselectchanged广东省是没有选中的，再次点击才会出现

**Comment by hunjixin** [comment]
类似的问题在饼图也遇到过，大概是由于动画延迟的问题，连续的动画会把上一次的给踢掉。setoption自身在更新的时候会有一次update，点击也会有一次update。两次一起就可能存在问题。
