### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by Star1122** [apache/incubator-echarts#6251]
### One-line summary [问题简述]
Overlapping issue

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.6.2
+ Browser version [浏览器类型和版本]: Chrome v59.0.3071.115
+ OS Version [操作系统类型和版本]: Mac OS Sierra v10.12.6

### Expected behaviour [期望结果]
I am having some overlapping issues with chart axis labels. When we have long text for axis label, the label values and axis name are overlapping each other. Would you please help me to fix this problem?
Thanks.

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/21158589/28486958-8a24a8fc-6e5e-11e7-9c51-b7c23baec47a.png)

**Comment by 100pah** [comment]
Try [grid.left](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.left), [grid.right](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.right), [yAxis.nameGap](https://ecomfe.github.io/echarts-doc/public/en/option.html#yAxis.nameGap) please.

**Comment by Star1122** [comment]
Hi, @100pah . Thanks for reply.
Can we change the yAxisnameGap dynamically depends on the label of yAxis?
Also how about the datazoom label cutting problem?
