### ISSUE TITLE
请问echart能同时显示100张以上的折线图的数据吗？我的版本是最新的，浏览器用360，win10系统。希望能在一张echart中同时显示447种数据，每一种数据就是一个1413维的向量，这在python代码中容易实现，而且不卡，但是echart浏览器就直接崩溃了，

### ISSUE THREAD

**Issue by zhangda17** [apache/incubator-echarts#6253]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}
![tim 20170722172030](https://user-images.githubusercontent.com/30366631/28490009-f8082c78-6f02-11e7-96ff-4a54001592ea.png)



```

**Comment by 100pah** [comment]
浏览器中放置过多组件确实容易崩溃。
可能的方法一：100 个折线图中放在一个 echarts 实例中。
可能的方法二：每个折线图是一个 echarts 实例，但是做懒加载。

**Comment by mytharcher** [comment]
同时显示这么多折线图有啥意义呢？他们的坐标刻度都一致么？可视化也要考虑人眼所能分辨的图像才有意义啊。
