### ISSUE TITLE
echarts3 设置markpoint时，采用coord 定位产生的问题

### ISSUE THREAD

**Issue by beipiaoyu2011** [apache/incubator-echarts#6258]
### One-line summary [问题简述]

echarts3 设置markpoint时，采用coord 定位点的位置，
如果此时再用 y参数去定义竖直的距离，就会有问题。
问题就是虽在datazoom的伸缩，定位的markpoint点不会超出隐藏，
会一直出现在轴外侧。
例如：
1 该代码下 会出现问题
var equityItem = {
        name: obj,
       coord: [dateData[i], hyPrice[i]],
       y: y_instance + '%'
  };
用y去定位所有的点都在一个水平线上，此时会有问题
2、如果去掉Y 点会落在line上，此时会随线超出隐藏。

### Version & Environment [版本及环境] window
+ ECharts version [ECharts 版本]: echarts 3
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

例1 可以超出隐藏

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

问题1
![t1](https://user-images.githubusercontent.com/11400346/28511432-ca0545d0-707f-11e7-9a0f-ffa99830ac5e.png)
问题2（去掉y， 正常）
![t2](https://user-images.githubusercontent.com/11400346/28511459-df00b0f0-707f-11e7-995b-e26e5446a859.png)

**Comment by mytharcher** [comment]
Duplicated with #6207 .

**Comment by cxytomo** [comment]
我的数据举例如下
"data": [
                {
                    "name": "00",
                    "value": {
                        "value":576,
                        "countLevel":0,
                        "percentLevel":0,
                        "percent": "10"
                    }
                },
                {
                    "name": "01",
                    "value": {
                        "value":384,
                        "countLevel":0,
                        "percentLevel":0,
                        "percent": "10"
                    }
                },
                {
                    "name": "02",
                    "value": {
                        "value":384,
                        "countLevel":1,
                        "percentLevel":1,
                        "percent": "80"
                    }
                }]
我的场景是percentLevel为1的点我需要去标记出来，点上加个自定义的图形。请问要怎么实现呢？
