### ISSUE TITLE
brush 功能除了多个图放在一个对象内用 brushLink 进行绑定，是否有 API 可以支持主图上框选后在其他选择特定的点进行显示？

### ISSUE THREAD

**Issue by mytharcher** [apache/incubator-echarts#6259]
### One-line summary [问题简述]

brushLink 多图联动功能要求散点的集合是同样顺序的，但是实际场景在大数据量下我们对不同的图会做特定的采样优化，这导致不同的图基本不会使用同样的采样后数据集，于是无法使用默认的 brushLink 方式配置联动。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: Chrome 59
+ OS Version [操作系统类型和版本]: macOS

### Expected behaviour [期望结果]

期望通过如下或其他方式调用，使对应图表对象的某些 series 中突出显示设定的数据集合：

~~~javascript
chart.dispatchAction({
  type: 'brushselected',
  batch: [
    selected: [
      dataIndex: [/*...计算出来特定的点集...*/]
      seriesIndex: 0
    ]
  ]
});
~~~

**Comment by 100pah** [comment]
可以尝试在 `brushselected` 事件中，
```js
dispatchAction({
    type: 'highlight',
    batch: [{seriesIndex: 0, dataIndex: 1}, {seriesIndex: 0, dataIndex: 5}, ...]
})
```

**Comment by mytharcher** [comment]
@100pah 感谢回复。不过这个应该只是权宜之计，而且 highlight 的 样式和框选差异较大，虽然可以通过配置调整，但也会影响正常的显示。

不过还是非常感谢提供了个临时解决方案。期待新功能尽早加入，谢谢！

**Comment by helgasoft** [comment]
Renewing this request for enhancement.  
Looks like currently (v.5) there are *action* equivalents [brush](https://echarts.apache.org/en/api.html#action.brush.brush) and [brushEnd](https://echarts.apache.org/en/api.html#action.brush.brushEnd) for *events* [brush](https://echarts.apache.org/en/api.html#events.brush) and [brushEnd](https://echarts.apache.org/en/api.html#events.brushEnd), but **no action brushselected** for event [brushselected](https://echarts.apache.org/en/api.html#events.brushselected).  
It would be helpful to have it with similar format:
```
chart.dispatchAction({ 
   type: 'brushselected', 
   selection: [ 
          { seriesIndex: number,  dataIndex: [] },
          { seriesIndex: 0,  dataIndex: [1,2,3,5] } 
   ] 
});
````
