### ISSUE TITLE
使用 ECharts 导致APP 所有WebView 页面 卡死

### ISSUE THREAD

**Issue by sunO2** [apache/incubator-echarts#6261]
### One-line summary [问题简述]
页面 重复开启关闭 当Echats 正在加载的时候 关闭页面  调用 webView.destroy();
之后再进入页面 会导致 整个APP 中的 WebView 卡死 页面无法加载出来

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
Echarts 3.6v

+ Browser version [浏览器类型和版本]:

+ OS Version [操作系统类型和版本]:
Android 

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
不知『正在加载』是指加载数据，还是加载代码还是什么？

**Comment by hezhihu89** [comment]
数据正在加载过程

**Comment by FxLsoft** [comment]
同样的问题，在oppo r9m上出现卡死现象。只要进入echart页面，导致所有ajax请求卡住

**Comment by FxLsoft** [comment]
![image](https://user-images.githubusercontent.com/13415380/30509754-53fceb96-9aea-11e7-8df4-f01be9c23503.png)  echart3.7版本添加动画完了关闭动画。

**Comment by FxLsoft** [comment]
这是由于echart进行动画时未关闭动画，坑爹啊

**Comment by FxLsoft** [comment]
```
try{
				if(navigator.userAgent.toLowerCase().indexOf('oppo') > -1){
					window.requestAnimationFrame = function (callback) {
		                window.setTimeout(callback, 1000 / 30);
		            };
				}
			}catch (e){
				
			}
```
最后用这个方法解决的
