### ISSUE TITLE
legend selectedMode=false，legendselectchanged就无法触发了

### ISSUE THREAD

**Issue by Necroogre** [apache/incubator-echarts#6266]
### One-line summary [问题简述]

饼图里legend selectedMode=false，legendselectchanged就无法触发了;

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.1
+ Browser version [浏览器类型和版本]:chrome 59.0.3071.115
+ OS Version [操作系统类型和版本]:windows10

### Expected behaviour [期望结果]
其实我只是想要自定义选中legend的事件，并且不想要自带的选中变灰，series相应去掉的效果

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chuhanan** [comment]
I'v same problem
