### ISSUE TITLE
自定义绘制点

### ISSUE THREAD

**Issue by suconghou** [apache/incubator-echarts#6268]
![QQ20170725-124551@2x.png](https://i.loli.net/2017/07/25/5976cd115f7e4.png)

请问echarts是否提供接口自己定制绘制坐标点.  想实现自己绘制透明渐变星光点, 总体效果如上, 但希望做的更加明显.

**Comment by suconghou** [comment]
或者类似的方案提供参考,谢谢!

**Comment by pissang** [comment]
symbol 设置成图片就行吧
