### ISSUE TITLE
无法实现不显示某个类目下的某个系列

### ISSUE THREAD

**Issue by jeoy** [apache/incubator-echarts#6269]
### One-line summary [问题简述]
如图，需要把每个城市都作为系列，一共7个系列， 省份作为类目，一共两个类目。
按照现在的逻辑只能在每个类目下将7个系列全部显示。 
              
![image](https://user-images.githubusercontent.com/6924980/28557704-98ae2abc-7140-11e7-9f90-bab77bf28eb5.png)

而需求在广东省下不需要显示浙江省下的城市，在浙江省下不需要显示广东省的城市，期望的结果是，当数据为null 或非数值时（也就是显示'-'时），隐藏掉该类目下的该系列，如下图。

同样的需求见 https://github.com/ecomfe/echarts/issues/5548 ， 该问题可能因为描述不清被关闭

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: "3.4.0"
+ Browser version [浏览器类型和版本]: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
+ OS Version [操作系统类型和版本]:  macOS sierra 10.12.5 

### Expected behaviour [期望结果]
期望的结果是，当数据为null 或非数值时（也就是显示'-'时），隐藏掉该类目下的该系列，如下图。

![image](https://user-images.githubusercontent.com/6924980/28557657-4d5bef9a-7140-11e7-904c-7faa87cd5ce7.png)

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data:['广州','深圳','珠海','佛山','杭州','舟山','宁波'],
        top: 100,
        right: 0
    },
    xAxis : [
        {
            type : 'category',
            data : ['广东', '浙江'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'广州',
            type:'bar',
            data:[50, null]
        }, {
            name:'深圳',
            type:'bar',
            data:[72, null]
        }, {
            name:'珠海',
            type:'bar',
            data:[30, null]
        }, {
            name:'佛山',
            type:'bar',
            data:[38, null]
        }, {
            name:'杭州',
            type:'bar',
            data:[null, 42]
        }, {
            name:'舟山',
            type:'bar',
            data:[null, 32]
        }, {
            name:'宁波',
            type:'bar',
            data:[null, 52]
        }
    ]
};


```

**Comment by HawkingLan** [comment]
我遇到了同样的问题，主类目下有不同的子类目，但是需要放到同一张图里显示，感觉这种需求还是比较常见的。楼主解决了吗？

**Comment by jeoy** [comment]
@HawkingLan  我还没有解决， 求大神 @100pah  & @pissang  帮忙看下这个问题， 同样的需求见 #5548

**Comment by QPJIANG** [comment]
重写tooltip.formatter     当数据为null 时不显示相关series

**Comment by wenbei20** [comment]
同样的需求！！，找了2天了，估计得跟UI商量换一种方案了

**Comment by wenbei20** [comment]
> 重写tooltip.formatter 当数据为null 时不显示相关series

楼主问的不是tooltip，是某一个柱子没值的时候，就不让这个柱子占空间
