### ISSUE TITLE
多图联动 axisPointer type: 'cross' 展示问题

### ISSUE THREAD

**Issue by amorist** [apache/incubator-echarts#6274]
### One-line summary [问题简述]
多图联动 axisPointer type: 'cross' 
十字线交叉线出现在了其它两个图,正常应该鼠标移到某个图上，才十字交叉，其它只显示竖线
错误实例
![image](https://user-images.githubusercontent.com/14037268/28575757-73ea4c8a-7184-11e7-87fa-5c3be7b3e1ac.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.1
+ Browser version [浏览器类型和版本]:chrome  59.0.3071.115
+ OS Version [操作系统类型和版本]:MAC OS

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/14037268/28575941-fce64e6c-7184-11e7-89c1-1cfe1d473337.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liihuu** [comment]
@amor520 我也遇到这样的问题，目前解决办法是给canvas的容器设置鼠标移入移除事件，手动隐藏y轴上的axisPointer直线和label，请问你有找到更好的解决办法么？

**Comment by amor520** [comment]
@liihuu 没有找到，也是去掉原生，自己实现了一下

**Comment by z-hao** [comment]
请问具体怎么实现呢？这个问题其实只要做K线都会遇到，没有比较好的解决方案吗？
