### ISSUE TITLE
Bar flipped and labels moved in Bar chart when height of echarts instance is smaller than about 83px

### ISSUE THREAD

**Issue by kelvinau** [apache/incubator-echarts#6276]
### One-line summary [问题简述]

Bar flipped and labels moved in Bar chart when height of echarts instance is smaller than about 83px

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: Chrome 59.0.3071
+ OS Version [操作系统类型和版本]: Ubuntu 14.04

This can be reproduced in the official example:
http://gallery.echartsjs.com/editor.html?c=bar-tick-align

![image](https://user-images.githubusercontent.com/5885902/28600270-d6832688-7165-11e7-9582-8c91ea86c9b5.png)

### Expected behaviour [期望结果]
The chart can display correctly without flipping.

**Comment by McPo** [comment]
@susiwen8 was this actually completed as I am still running into such an issue
