### ISSUE TITLE
仪表盘中整体背景设置鼠标样式

### ISSUE THREAD

**Issue by wangyahua** [apache/incubator-echarts#6292]
### One-line summary [问题简述]
一个DIV中  设置整体背景鼠标样式    想修改为pointer样式的   只要鼠标放上DIV上  就是pointer样式   在自定义的div当中设置后不管用  因为echarts中定位后   有层叠关系    自定义的无法使用样式

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome最新版本
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
就是鼠标放上整个背景或者一个整体的DIV中   鼠标样式改变为pointer样式的

### ECharts option [ECharts配置项]

```javascript
option = {
       option = {
    tooltip : {
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            restore: {},
            saveAsImage: {}
        }
    },
    series: [
        {
            name: '业务指标',
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50, name: '完成率'}]
        }
    ]
};
}

```

**Comment by burkeallen** [comment]
I have the same issue, and the onclick event only fires on the pointer.  the cursor is only being set on the pointer.  seems to either be a layering issues or the event and styles are getting applied to only the pointer element within the canvas.
