### ISSUE TITLE
line图，y轴起始值不设置为0，怎么设置成自定义值

### ISSUE THREAD

**Issue by bringpp** [apache/incubator-echarts#6294]
### One-line summary [问题简述]
我的数据范围在正负2000，现实中y轴的数据一般在1000左右，现在想实现y轴以1000为基准，在其上下波动。好像没找到用户可以自行设置y轴起点值的配置项，请问有好的方法实现吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
yAxis.scale: true

**Comment by Lance8931** [comment]
有。可以在后台以1000为基准计算出每个y的值，然后在yAxis中的axisLabel中的formatter中加上基准值，那么y轴显示的就是以1000为基准值的偏移了。`title: {
        text: '售电公司电量偏差率',
        'subtext': 'by andot.org 蚁点工作室'
    },
    xAxis: {
        data: ['A公司', 'B公司', 'C公司', 'D公司', 'E公司', 'F公司']
    },
    grid: {
    	top:'13%',
        left: '3%',
        right: '6%',
        bottom: '3%',
        containLabel: true
    },
    yAxis: [{
        name: '偏差率（%）',
        type: 'value',
        axisLabel: {
            formatter: function(value,index){
                console.info("value: "+value)
                console.info("index: "+index)
                return value+1500
            }
        }
    }],
    series: [{
        name: '偏差率（%）',
        type: 'bar',
        data: [0.5, 7.5, -3, -1, 5, -0.5]
    }]`
