### ISSUE TITLE
关系图layout为none或者geo都没有效果

### ISSUE THREAD

**Issue by zou-mono** [apache/incubator-echarts#6314]
### One-line summary [问题简述]
关系图graph，layout设置没有效果
例如，我在官方实例les-miserables里面修改了x和y的值（各增加500），但是并没有任何变化。
另外，如果设置为geo，经过测试也没有效果，其他类型图的geo好像没这个问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: Chrome 
+ OS Version [操作系统类型和版本]: windows 10

### Expected behaviour [期望结果]
希望graph的layout能够按照预先设置好的坐标来布局，而不是用算法自动化布局

### ECharts option [ECharts配置项]

```javascript
    $.get('data/les-miserables.gexf', function (xml) {
        myChart.hideLoading();

        var graph = echarts.dataTool.gexf.parse(xml);
        var categories = [];
        for (var i = 0; i < 9; i++) {
            categories[i] = {
                name: '类目' + i
            };
        }
        graph.nodes.forEach(function (node) {
            node.itemStyle = null;
            node.value = node.symbolSize;
            node.symbolSize = node.symbolSize;
            node.x = node.x + 500;
            node.y = node.y + 500;
            node.label = {
                normal: {
                    show: node.symbolSize > 30
                }
            };
            node.category = node.attributes.modularity_class;
        });
        option = {
            title: {
                text: 'Les Miserables',
                subtext: 'Default layout',
                top: 'bottom',
                left: 'right'
            },
            tooltip: {},
            legend: [{
                // selectedMode: 'single',
                data: categories.map(function (a) {
                    return a.name;
                })
            }],
            animationDuration: 1500,
            animationEasingUpdate: 'quinticInOut',
            series: [
                {
                    name: 'Les Miserables',
                    type: 'graph',
                    layout: 'none',
                    data: graph.nodes,
                    links: graph.links,
                    categories: categories,
                    roam: true,
                    label: {
                        normal: {
                            position: 'right',
                            formatter: '{b}'
                        }
                    },
                    lineStyle: {
                        normal: {
                            color: 'source',
                            curveness: 0.3
                        }
                    }
                }
            ]
        };

        myChart.setOption(option);
    }, 'xml');

```

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=graph 就是使用的预先布局好的位置

**Comment by zou-mono** [comment]
@pissang 原始les-miserables文件里面的坐标x和y有负数，是按照什么规则布局的
我尝试使用经纬度坐标数据，然后设置coordinateSystem: 'geo'，结果geo地图会显示，但是graph没有显示出来，layout设置是'none'。我实验了scatter，不会出现这个问题
而且如果coordinateSystem设置为默认值'null'，运行会直接报错
geo的option代码如下：
            option = {
                animationDuration: 1500,
                animationEasingUpdate: 'quinticInOut',

                title: {
                    text: 'Les Miserables',
                    subtext: 'Default layout',
                    top: 'bottom',
                    left: 'right'
                },
                tooltip: {},
                legend: {
                    // selectedMode: 'single',
                    data: categories.map(function (a) {
                        return a.name;
                    })
                },

                geo: {
                    map: 'shenzhen',
                    zlevel: 0,
                    aspectScale: 1,
                    show: false,
                    selectedMode: false,
                    label: {
                        emphasis: {
                            show: false
                        }
                    },
                    itemStyle: {
                        normal: {
                            areaColor: '#323c48',
                            borderColor: '#111'
                        },
                        emphasis: {
                            areaColor: '#2a333d'
                        }
                    },
                    roam: true
                },

                series: [{
                    type: 'graph',
                    name: 'geoTest',
                    coordinateSystem: 'geo',
                    zlevel: 1,
                    layout: 'none',
                    data: graph.nodes,
                    links: graph.links,
                    categories: categories,
                    roam: false,
                    label: {
                        show: true,
                        normal: {
                            position: 'right',
                            formatter: '{b}'
                        }
                    },
                    lineStyle: {
                        normal: {
                            color: 'source',
                            curveness: 0.3
                        }
                    }
                }]
            };

**Comment by pissang** [comment]
如果 layout 是 none，则根据现在的坐标系布局，比如 `cartesian2d`, `geo`, `view`，前两者参考 http://echarts.baidu.com/gallery/editor.html?c=graph-life-expectancy 这个例子，后面那个就是默认的，取 x, y 作为坐标。

**Comment by zou-mono** [comment]
@pissang 实例里面的cartesian2d确实没问题，但是换成geo之后就不行了，我查看了最后的option参数，坐标确实是经纬度坐标，我怀疑是设置为geo后并没有进行转换。
我尝试用convertToPixel强制转换成屏幕坐标，结果节点布局是正确的，但是和地图的比例有问题
