### ISSUE TITLE
地图中的type=image的Graphic onclick事件无法被调用

### ISSUE THREAD

**Issue by clicangit** [apache/incubator-echarts#6323]
### One-line summary [问题简述]

type=image类型的graphic的onclick事件无法被正确调用
相同的代码 当我尝试使用type=circle的时候onclick事件就可以被调用了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:Chrome 59.0.3071.115 64位
+ OS Version [操作系统类型和版本]:Windows7

### Expected behaviour [期望结果]
当用户点击图片时onclick事件能被正常调用

### ECharts option [ECharts配置项]

<script type="text/javascript">
		// 基于准备好的dom，初始化echarts实例
		var chart = {
			"map" : {
				"江苏" : [ {
					"name" : "扬州市",
					"value" : "24"
				}, {
					"name" : "南京市",
					"value" : "54"
				}, {
					"name" : "苏州市",
					"value" : "64"
				} ],
				"china" : [ {
					"name" : "上海",
					"value" : "12"
				}, {
					"name" : "北京",
					"value" : "36"
				}, {
					"name" : "浙江",
					"value" : "56"
				}, {
					"name" : "江苏",
					"value" : "76"
				}, {
					"name" : "广东",
					"value" : "26"
				}, {
					"name" : "重庆",
					"value" : "0"
				}, {
					"name" : "新疆",
					"value" : "0"
				}, {
					"name" : "天津",
					"value" : "0"
				}, {
					"name" : "澳门",
					"value" : "0"
				}, {
					"name" : "内蒙古",
					"value" : "0"
				}, {
					"name" : "宁夏",
					"value" : "0"
				}, {
					"name" : "江西",
					"value" : "0"
				}, {
					"name" : "台湾",
					"value" : "0"
				}, {
					"name" : "贵州",
					"value" : "0"
				}, {
					"name" : "安徽",
					"value" : "0"
				}, {
					"name" : "陕西",
					"value" : "0"
				}, {
					"name" : "辽宁",
					"value" : "0"
				}, {
					"name" : "山西",
					"value" : "0"
				}, {
					"name" : "青海",
					"value" : "0"
				}, {
					"name" : "香港",
					"value" : "0"
				}, {
					"name" : "四川",
					"value" : "0"
				}, {
					"name" : "河北",
					"value" : "0"
				}, {
					"name" : "西藏",
					"value" : "0"
				}, {
					"name" : "福建",
					"value" : "0"
				}, {
					"name" : "吉林",
					"value" : "0"
				}, {
					"name" : "湖北",
					"value" : "0"
				}, {
					"name" : "云南",
					"value" : "0"
				}, {
					"name" : "海南",
					"value" : "0"
				}, {
					"name" : "湖南",
					"value" : "0"
				}, {
					"name" : "山东",
					"value" : "0"
				}, {
					"name" : "河南",
					"value" : "0"
				}, {
					"name" : "黑龙江",
					"value" : "0"
				} ]
			}
		};

		var maps = Object.keys(chart.map);
		for ( var ki in maps) {
			var key = maps[ki];
			var map = chart.map[key];
			for ( var di in map) {
				var data = map[di];
				var rate = data.value;
				var color;
				if (rate > 0 && rate < 10) {
					color = "#0759ae";
				} else if (rate >= 10 && rate < 20) {
					color = "#93d5f1";
				} else if (rate >= 20 && rate < 30) {
					color = "#8cc75d";
				} else if (rate >= 30 && rate < 40) {
					color = "#439b12";
				} else if (rate >= 40 && rate < 50) {
					color = "#ffc600";
				} else if (rate >= 50 && rate < 60) {
					color = "#dd8b8b";
				} else if (rate >= 60 && rate < 70) {
					color = "#b82080";
				} else if (rate >= 70) {
					color = "#cc0000";
				} else {
					color = "white";
				}
				if (key == 'china') {
					data.itemStyle = {
						normal : {
							label : {
								show : true
							}
						},
						emphasis : {
							areaColor : color,
							borderColor : 'yellow',
							borderWidth : 1,
							label : {
								show : true
							}
						}
					};
				} else {
					data.itemStyle = {
						normal : {
							label : {
								show : false
							}
						},
						emphasis : {
							areaColor : color,
							borderColor : 'yellow',
							borderWidth : 1,
							label : {
								show : true
							}
						}
					};
				}
			}
		}

		var myChart = echarts.init(document.getElementById('main'));

		myChart.setOption(option = {

			tooltip : {
				trigger : 'item',
				formatter : function(params, ticket, callback) {
					if (params.name != null && params.name.length > 0&&params.value!=null&&params.value>0) {
						return params.name + params.value + '%';
					} else {
						return '';
					}
				},
				textStyle : {
					fontSize : "30"
				},
			},
			textStyle : {
				fontSize : "30"
			},
			visualMap : {
				type : "piecewise",
				orient : "horizontal",
				left : "center",
				textStyle : {
					fontSize : "40"
				},
				pieces : [ {
					gte : 70,
					label : '70%',
					color : '#cc0000'
				}, {
					gte : 60,
					lt : 70,
					label : '60%',
					color : '#b82080'
				}, {
					gte : 50,
					lt : 60,
					label : '50%',
					color : '#dd8b8b'
				}, {
					gte : 40,
					lt : 50,
					label : '40%',
					color : '#ffc600'
				}, {
					gte : 30,
					lt : 40,
					label : '30%',
					color : '#439b12'
				}, {
					gte : 20,
					lt : 30,
					label : '20%',
					color : '#8cc75d'
				}, {
					gte : 10,
					lt : 20,
					label : '10%',
					color : '#93d5f1'
				}, {
					gt : 0,
					lt : 10,
					label : '0%',
					color : '#0759ae'
				}, ]
			},
			series : [ {
				name : '中国',
				type : 'map',
				mapType : 'china', // 自定义扩展图表类型
				roam : false,
				zoom : 1.4,
				itemStyle : {
					normal : {
						areaColor : 'white',
						label : {
							show : true
						}
					},
					emphasis : {
						areaColor : 'white',
						borderColor : 'yellow',
						borderWidth : 1,
						label : {
							show : true
						}
					}
				},
				data : chart.map.china
			} ]
		});

		myChart.on('click', function(params) {
			var seriesName = params.seriesName;
			if (seriesName == '中国') {
				var province = params.name;
				if (chart.map[province] == null
						|| chart.map[province].length == 0) {
					return;
				}
				myChart.setOption(option = {
					series : [ {
						name : province,
						type : 'map',
						mapType : province, // 自定义扩展图表类型
						roam : false,
						zoom : 1.0,
						itemStyle : {
							normal : {
								areaColor : 'white',
								label : {
									show : false
								}
							},
							emphasis : {
								areaColor : 'white',
								borderColor : 'yellow',
								borderWidth : 2,
								label : {
									show : true
								}
							}
						},
						data : chart.map[province]
					} ],
					graphic : [ {
						id : 'left-btn',
						invisible : false,
						type : 'group',
						children:[{
							type : 'image',
							invisible : false,
							z:1,
							left : 25,
							top : 25,
							style : {
								image : 'img/back.png'
							},
						},
						{
							type:'circle',
							invisible : false,
							z:0,
							left : 10,
							top : 10,
							shape:{
								r:30
							},
							style:{
								fill : '#eee'
							},
							onclick : function() {
								myChart.setOption(option = {
									series : [ {
										name : '中国',
										type : 'map',
										mapType : 'china', // 自定义扩展图表类型
										roam : false,
										zoom : 1.4,
										itemStyle : {
											normal : {
												areaColor : 'white',
												label : {
													show : true
												}
											},
											emphasis : {
												areaColor : 'white',
												borderColor : 'yellow',
												borderWidth : 2,
												label : {
													show : true
												}
											}
										},
										data : chart.map.china
									} ],
									graphic : [ {
										id : 'left-btn',
										invisible : true,
										type : 'group',
										children:[{
											type : 'image',
											invisible : true,
										},
										{
											type : 'circle',
											invisible : true,
										}]
									} ]

								});
							}
						}],
						
						
					} ]
				});
			}
		});
	</script>

**Comment by liihuu** [comment]
@100pah 请问这个问题目前有修复么？

**Comment by liihuu** [comment]
onmouseout和onmouseover这两个方法也响应的不是很灵敏，其它方法没有尝试过，不知道具体情况。
