### ISSUE TITLE
markLine值大于坐标轴最大值时会显示不出，应该如何处理这种情况

### ISSUE THREAD

**Issue by liuzngit** [apache/incubator-echarts#6329]
### One-line summary [问题简述]

官方示例 http://echarts.baidu.com/demo.html#bar-tick-align
修改以下代码
series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220],
            markLine : {
                data : [{
                    name : '均线',
                    yAxis : 500
                }]
            }
        }
]

markLine显示不出，该如何处理

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liihuu** [comment]
@liuzngit 是起点或者终点不在显示区域了   整条线就看不到了  请问找到解决办法了么？

**Comment by ghostcode** [comment]
```
    yAxis: {
      max: function (value) {
        return Math.max(value.max, 标线值)
      },
    },
```

**Comment by liihuu** [comment]
I have developed a financial chart, see [KLineChart](https://github.com/klinecharts/KLineChart).
