### ISSUE TITLE
用pie改为环形图后，没有圆角相关的属性，能否增加圆角相关属性？

### ISSUE THREAD

**Issue by jeremy-song** [apache/incubator-echarts#6347]
![](http://www.joycesong.com/wp-content/uploads/2017/08/WX20170803-100451.png)

### One-line summary [问题简述]

用pie改为环形图后，没有圆角相关的属性，能否增加圆角相关属性？

如上图，如果用border，只能得到一个尖角的图形，如果不用border，只用radius，就只能得到一个平角的图形，找遍了文档，没有圆角属性，能否增加圆角属性？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

不限

### Expected behaviour [期望结果]

增加圆角相关属性

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by confidence68** [comment]
请看地址：http://www.haorooms.com/post/canvas_yuanjiaohuanx

**Comment by wangmeijian** [comment]
m

**Comment by libangrui** [comment]
同样需求

**Comment by zmzimpl** [comment]
同样需求+1
