### ISSUE TITLE
Echart 3.0 Map类型地图缩放问题

### ISSUE THREAD

**Issue by bobo159357456** [apache/incubator-echarts#6360]
### One-line summary [问题简述]

Echart 2.0有缩放组件
`roamController: {
        show: true,
        x: 'right',
        mapTypeControl: {
            'china': true
        }
    },`

但是Echart3.0就没有roamController

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:54.0.1 (64 位)
+ OS Version [操作系统类型和版本]: windows 10 64位

### Expected behaviour [期望结果]
Echart3.0中
实现map类型的地图缩放

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by bobo159357456** [comment]
求解决,谢谢

**Comment by zou-mono** [comment]
3.0是在geo的roam属性里面设置
