### ISSUE TITLE
天津市蓟州区坐标数据缺失

### ISSUE THREAD

**Issue by lingxuanhong** [apache/incubator-echarts#6375]
{"id":"120119","type":"Feature","geometry":{"type":"Polygon"# **,"coordinates":[],"encodeOffsets":[]}**,"properties":{"cp":[117.407449,40.045342],"name":"蓟州区","childNum":0}}

### One-line summary [问题简述]
天津市蓟州区坐标数据（或者是图形不显示）缺失
{"id":"120119","type":"Feature","geometry":{"type":"Polygon",**# "coordinates":[],"encodeOffsets":[]**},"properties":{"cp":[117.407449,40.045342],"name":"蓟州区","childNum":0}}

### Version & Environment [版本及环境]
+ ECharts version [3.6.2]:
+ Browser version [chrome 版本 57.0.2970.0   ；IE10]:
+ OS Version [win7 专业版]:

### Expected behaviour [期望结果]
![tianjin](https://user-images.githubusercontent.com/20498039/29018342-513630f6-7b8d-11e7-9520-25f47a723abc.jpg)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![tianjin_error](https://user-images.githubusercontent.com/20498039/29018431-9a59018c-7b8d-11e7-85c1-9c57e3b77423.jpg)

**Comment by bymain** [comment]
刚发现官网的地图，展示用的是png图片，对应的json数据并不完全对应

**Comment by pissang** [comment]
@bymain 展示是用 echarts 实时渲染的

**Comment by bymain** [comment]
@pissang 这个地方是实时渲染的？
![image](https://user-images.githubusercontent.com/11552691/29019529-5e5a4cf0-7b91-11e7-8c3f-ae07fbd5c4bb.png)

**Comment by bymain** [comment]
@pissang 我刷新一次页面，看到请求的是对应的png图片
![image](https://user-images.githubusercontent.com/11552691/29019640-be9e8748-7b91-11e7-8e8f-ffd3d8b52c37.png)

**Comment by pissang** [comment]
奥，这个是预渲染的

**Comment by bymain** [comment]
@pissang 对应的json数据，里面缺少坐标数据怎么办？

**Comment by 1252198830** [comment]
同样遇到了坐标数据缺失   西藏山南地区   反馈不知道是否有效  第一次反馈

**Comment by lingxuanhong** [comment]
@pissang  就是在官网上生成的js和Json，只不过官网展示是想要的正确的，可是js和Json数据中“"coordinates":[],"encodeOffsets":[]”数据时空的，导致蓟州区的图片部分不能展示

**Comment by 1252198830** [comment]
看官方的速度了。 希望尽快解决最近省级json坐标缺失的问题。 我准备明天从baike.baidu.com/court里面的json中往我现有的json文件中导入。  里面的code和echarts里面的id所对应。 都是城市代码。 你也可以试试

**Comment by zichengHe** [comment]
广州及深圳地图包部分区未更新到最新
