### ISSUE TITLE
echarts 西藏省json数据中缺少山南市坐标点集

### ISSUE THREAD

**Issue by FontEndArt** [apache/incubator-echarts#6376]
### One-line summary [问题简述]
  echarts 西藏省json数据中缺少山南市坐标点集 导致地图无法显示山南地区

  **官方实例中同样没有显示该地区的数据**

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  应该是官网现在使用的3.1.1.all.js？
+ Browser version [浏览器类型和版本]:  chrome 最新稳定版
+ OS Version [操作系统类型和版本]:  windows 10

### Expected behaviour [期望结果]

  补充西藏省json数据中缺少的坐标点数据  正常显示山南地区
  并通过官方更新通知或者邮件1252198830@qq.com来通知我知晓

### ECharts option [ECharts配置项]

```javascript
option = {
     请您直接看官方示例  链接附上
     http://echarts.baidu.com/demo.html#map-province
}

```

### Other comments [其他信息]

官方实例链接：
http://echarts.baidu.com/demo.html#map-province

图片链接：
![echarts console](https://user-images.githubusercontent.com/19547121/29021244-7316c460-7b97-11e7-8334-b727f63c90e4.png)
![echarts](https://user-images.githubusercontent.com/19547121/29021245-73464834-7b97-11e7-8731-7a08d4002bd4.png)
![echarts](https://user-images.githubusercontent.com/19547121/29021246-74166dde-7b97-11e7-8ac0-ebdac174e583.png)

**Comment by 1252198830** [comment]
希望尽快完善数据  并回复一下小然子  
在这里谢谢了

**Comment by lingxuanhong** [comment]
@1252198830 我使用天津市地图时出现同样的问题

**Comment by 1252198830** [comment]
这两个地区都是json文件缺少坐标集。 我看了官方的实例。一样缺失。 不知道多长时间可以解决。 如果不能 我只能曲线救国。从其他地方往现有的json内导入了。

**Comment by chfw** [comment]
山南市已经加上了 看我的PR.
