### ISSUE TITLE
图片上的热力图怎么配置visualMap和coordinateSystem

### ISSUE THREAD

**Issue by rain-rain** [apache/incubator-echarts#6388]
### One-line summary [问题简述]
期望实现一个如下demo所示的结果：http://echarts.baidu.com/echarts2/doc/example/heatmap2.html
在图片上显示图片各位置的点击热力图。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

希望可以给我这个demo的option配置，以及demo的echarts版本

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

期望显示结果如下
![image](https://user-images.githubusercontent.com/24270643/29103419-0727ef48-7cf2-11e7-81ce-417d99700a41.png)

**Comment by AllenZhou1996** [comment]
我也有这个需求

**Comment by AllenZhou1996** [comment]
@rain-rain 请问你得到了解决方法了没？
