### ISSUE TITLE
echarts 饼图引导线周围文字位置的改变

### ISSUE THREAD

**Issue by CQ12312** [apache/incubator-echarts#6400]
请问echarts引导线的位置可以放在文字的上方吗？官方是这样。

![1502349019 1](https://user-images.githubusercontent.com/17740750/29158942-794acfda-7ddf-11e7-9483-cc9790c7ccbf.jpg)

我想实现文字在引导线的上方和下方

**Comment by pissang** [comment]
暂时不行

**Comment by dmwin72015** [comment]
能统一方向吗？？？让引导线都指向左边或者右边？？？？
