### ISSUE TITLE
散点图可不可以实现从一段时间到另一段时间连续的选择

### ISSUE THREAD

**Issue by AntoniaQiao** [apache/incubator-echarts#6404]
echarts3散点图可不可以实现从一段时间到另一段时间连续的选择，怎么实现
比如： 总的时间范围是 2016.7.8-2017.7.8
2016.10.1-2016.10.7这段时间的图是连续的
2017.7.1-2017.8.4 这段时间的图是连续的

![bf0ea81c-96cc-41d2-96bc-954d9d8ddd6d](https://user-images.githubusercontent.com/19327642/29169594-58cdf7dc-7e07-11e7-8441-5def66f00f49.png)

**Comment by pissang** [comment]
没理解你的意思
