### ISSUE TITLE
force graph力引导图形移动/缩放相关问题

### ISSUE THREAD

**Issue by antliu2012** [apache/incubator-echarts#6412]
### One-line summary [问题简述]
1.怎么设置力引导图默认的缩放比例和中心位置？（已经开启了roam）
2.怎么动态改变力引导图中的缩放和位置？（比如点击旋转一个节点，定位这个点到图形中心，并放大）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: ECharts 3.x
+ Browser version [浏览器类型和版本]: Chrome 60
+ OS Version [操作系统类型和版本]: 

### Expected behaviour [期望结果]
1.
option:{
    ???
}
2.
chart.???(???);

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by houx15** [comment]
series中设置zoom: 2, center: [x, y]
