### ISSUE TITLE
图片symbol如何显示成圆形

### ISSUE THREAD

**Issue by cloudor126** [apache/incubator-echarts#6413]
### One-line summary [问题简述]
采用image://url方式设置的图片symbol希望能够有办法设置显示成圆形

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: ECharts 3.x
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
增加一个roundimage://url的symbol设置方式，将图片自动按最小宽高为直径、图片中心为圆心的圆。

**Comment by cloudor126** [comment]
另外，再设置一个border也是极为必要的。

**Comment by luoshengheng** [comment]
同求啊，有解决办法了吗

**Comment by GSBL** [comment]
同求
