### ISSUE TITLE
地图各市名字的显示位置

### ISSUE THREAD

**Issue by yueguangjifeng** [apache/incubator-echarts#6414]
### One-line summary [问题简述]
地图上 各市县的名字挤在一起显示了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:chrome 59.0.3071.115
+ OS Version [操作系统类型和版本]:win7 64 位

### Expected behaviour [期望结果] 
地图上个区县名字显示在 合适的位置，不要挤在一起

### ECharts option [ECharts配置项]

```javascript
option = {
            tooltip:{
                trigger:'item',
                formatter:'{b}'
            },
            series:[{
                type:'map',
                map:'南昌市',
                label:{
                    normal:{
                        show:true
                    },
                    emphasis:{
                        show:true
                    }
                }
            }]
       }

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/25240532/29208844-4c312028-7ebe-11e7-9534-26cd1a3cbc6b.png)

**Comment by yakisobapan** [comment]
在地图文件中找到各区县对应的 "properties":{"cp":[xxxx,yyyy],"name":"xx县","childNum":1}，其中xxxx，yyyy就是该区县名的显示位置的具体坐标，可以手动修改调整区县名的显示位置。

**Comment by whirly77cai** [comment]
最近遇到需要用到所有省市的，手动修改的话满满的都是工作量，请问有更加简便的方法吗？(oﾟ▽ﾟ)o
