### ISSUE TITLE
散点图中silent会影响series中定义的tooltip对象的显示

### ISSUE THREAD

**Issue by lemonl2** [apache/incubator-echarts#6416]
### One-line summary [问题简述]

当在散点图中添加tooltip的trigger为item，而且在series中定义tooltip对象，如果silent属性设置为true，直接就影响了tooltip的显示（不显示）。silent虽然是用来禁止响应的，但是tooltip应该不能受到影响吧？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
silent 之后就会禁止交互，包括 tooltip 的显示。你的情况为什么不能不设 silent？

**Comment by lemonl2** [comment]
希望tooltip是可以显示的。点击操作禁止就行。

**Comment by Ovilia** [comment]
那就不要设 silent，然后把 emphasis 的样式设为和 normal 一样的？
