### ISSUE TITLE
双数值轴划分的段数不同

### ISSUE THREAD

**Issue by CherishIt** [apache/incubator-echarts#6424]
### One-line summary [问题简述]
想画一个双数值轴的图，但是因为两个轴划分的段数不同，导致splitLine不能重合会显得很凌乱，不知道有没有比较好的方法能让两个轴的splitLine对齐

### Expected behaviour [期望结果]
两个数值轴被分成相同的段数，splitLine重合

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'axis',
    },
    legend: {
        data:['蒸发量','降水量','平均温度']
    },
    xAxis: [
        {
            type: 'category',
            data: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
        }
    ],
    yAxis: [
        {
            type: 'value',
            name: '水量',
            axisLabel: {
                formatter: '{value} ml'
            }
        },
        {
            type: 'value',
            name: '温度',
            axisLabel: {
                formatter: '{value} °C'
            }
        }
    ],
    series: [
        {
            name:'蒸发量',
            type:'bar',
            data:[2.0, 7.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
        },
        {
            name:'平均温度',
            type:'line',
            yAxisIndex: 1,
            data:[2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]
        }
    ]
}
```

### Other comments [其他信息]

![screen shot 2017-08-14 at 10 03 08 am](https://user-images.githubusercontent.com/14925238/29255862-d148b8a0-80d7-11e7-9386-8053ec056636.png)

**Comment by luguokong** [comment]
源码中niceExtent这个方法最后一行添加
this._interval = (extent[1] - extent[0]) / opt.splitNumber;

不保证不出其他错误

**Comment by zjdschnappi** [comment]
@luguokong   双y轴的是好了，，但是单y轴却长成下面这样

![image](https://user-images.githubusercontent.com/15072751/29352802-b0466f16-829a-11e7-8c3f-621370eb197d.png)
求教，，遇见过吗？
