### ISSUE TITLE
echart 多图联动后，tooltip.axisPoiner.type='cross'显示label的问题

### ISSUE THREAD

**Issue by roy-gan** [apache/incubator-echarts#6434]
### One-line summary [问题简述]
echart 多图联动后，每个图的tooltip设置如下：
```js
 tooltip: {
                show: true,
                trigger: 'axis',
                showContent: false,
                axisPointer: {
                    animation: false,
                    type: 'cross',
                    crossStyle: {
                        type: 'solid',
                        width: 1,
                        opacity: 1
                    },
                    label: {
                        precision: 2
                    }
                }
            }
```

![qq 20170815113312](https://user-images.githubusercontent.com/30861850/29301263-91f5b528-81ad-11e7-9aa1-cb9a77ff8293.png)

当鼠标在某个图表中活动时，如何只显示一个label，而不是三个一起显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![qq 20170815113621](https://user-images.githubusercontent.com/30861850/29301335-009ff510-81ae-11e7-8b16-a2668017605a.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liihuu** [comment]
我也遇到同样的问题，有找到解决办法么？

**Comment by biaowork** [comment]
axisLabel: {
                    show: false        
                },

**Comment by biaowork** [comment]
我有个问题要请教各位。你们的tooltip 有没有做独立的显示，比如页面的 Volumn 和 MACD 的tooltip，如何同时显示在自己的item左上角？

**Comment by DukeGJ** [comment]
http://echarts.baidu.com/option.html#series-line.tooltip @biaowork

**Comment by biaowork** [comment]
@DukeGJ 我这不是定位的问题，是需要同时显示3个item的tooltip。因为我的K线图要全屏的，不同尺寸屏幕下，每个item的大小不一样，所以需要同时显示3个tooltip

**Comment by 100pah** [comment]
也可参考：<http://gallery.echartsjs.com/editor.html?c=xSyqudQB5->

**Comment by z-hao** [comment]
其实这个问题只要做K线图就会遇到，没有比较好的解决方案吗？

**Comment by xiazhujie** [comment]
看来这个问题还没解决,我试过axisPointer.label.formatter,想判断值返回第一个图的label,但是返回的字符串只对x轴有效,y轴坐标为空.同时其余的图的x轴label还是会显示个背景,只有把axisPointer.label.margin和axisPointer.label.padding设置为零才看不到空的label,但是k线的也就跟着不好看了

**Comment by Yinsls** [comment]
怎么样，最后有解决方案了吗，救救孩子吧

**Comment by liihuu** [comment]
不知道现在咋样了，我最后放弃了，自己撸了个图表

**Comment by wick-z** [comment]
测试版本5.5.1
每个坐标轴都有一个axisPointer，它有一个label属性，可以控制是否展示
`
...
xAxis: [
        {
          type: 'category',
          data: data.categoryData,
          boundaryGap: false,
          axisLine: { onZero: false },
          splitLine: { show: false },
          min: 'dataMin',
          max: 'dataMax',
          axisPointer: {
            z: 100,
            label: {
              show: false
            }
          }
        },...`
最后还得在option的`axisPointer`设置联动：
`...
axisPointer: {
        link: [
          {
            xAxisIndex: 'all'
          }
        ],
        label: {
          backgroundColor: '#777'
        }
      }
...`
