### ISSUE TITLE
同时使用echars2.2.7和echars3.3.2时，如何处理版本冲突

### ISSUE THREAD

**Issue by pig2018** [apache/incubator-echarts#6440]
### One-line summary [问题简述]

同时使用echars2.2.7和echars3.3.2时，如何处理版本冲突

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
同时使用echars2.2.7和echars3.3.2时，如何处理版本冲突？有什么好的解决方案，谢谢。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by luguokong** [comment]
把echarts2里的echarts全部替换成echarts2?

**Comment by pig2018** [comment]
能不能想jquery封装一个方法来处理冲突，当然你那种方式是可以的，只不过觉得稍微麻烦一点；例如：
jQuery.noConflict(true)这种
