### ISSUE TITLE
pie 图的数据格式

### ISSUE THREAD

**Issue by bluesh** [apache/incubator-echarts#6441]
### One-line summary [问题简述]
Pie图 饼图的数据格式只能是
```
[{name: , value: }, 
{name: , value: },
{name: , value: }]
```
这种格式吗？
别的都是二维数组，pie图却要加个key值的object

看文档
![image](https://user-images.githubusercontent.com/1687283/29352578-da44fa9a-8299-11e7-9b84-f0e06be7014a.png)
也是支持的，但是不行。

**Comment by pissang** [comment]
奥，抱歉这里文档描述有误
