### ISSUE TITLE
Keep nodes fixed after drag in force-layout graph

### ISSUE THREAD

**Issue by Blipz** [apache/incubator-echarts#6467]
**ECharts version:** 3.6.2
**Chart type**: graph with  `layout: 'force'` and `draggable: true`

Hi,
Perhaps it could be interesting to add an option preventing `setUnfixed()` to be called when the `dragend` event is triggered.
This would allow users to position nodes exactly as they wish.

**Comment by stillsilly** [comment]
这个问题后来解决了吗，怎么让它拖动后不要弹回去？

**Comment by MichaelElliot1999** [comment]
Has anyone ever looked at this?

What I'm looking for is a graph with  `layout: 'none'` then have the ability to set `draggable: true` so that all other nodes do not reshuffle,

The option mentioned above would also be better

**Comment by jayarjo** [comment]
I also look for a functionality like this. Also I do not quite understand why you wouldn't allow to handle the result of dragging node to a new location, when layout is `force` and `draggable` is set to true. It seems that all `dragend` listeners are cleared on purpose.

**Comment by kevinwt95** [comment]
Is there a way to do this these days?
I need exactly this feature, but I have no pre-filled coordinates when using `layout: 'force'` and there is no option to fix the nodes after the first start.
