### ISSUE TITLE
Measuring Text and Series Graphics

### ISSUE THREAD

**Issue by jonavila** [apache/incubator-echarts#6488]
### One-line summary [问题简述]
I'm trying to implement a heat map with dynamic axis and series labels based on whether they fit the width of the item rectangle. Does echarts provide any helper methods to check the width/height of text and also a way to check the serie's graphics width/height?

I envision being able to use these in a formatter function for labels and do a width or height check and dynamically render those. Our applications allows users resize the charts, so it's critical for me to make sure the labels only show when they are legible. 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
Use echarts methods to measure text and graphics of charts.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by psumstr** [comment]
I created a formatter function for series labels that seems to work, though I'm not sure if it's safe to use these APIs:
```
	var seriesLabel = function(params) {
		var labelText = params.value[3];
		var chartModel = chart.getModel();
		var labelRect = chartModel
			.getComponent('xAxis')
			.getModel('axisLabel')
			.getTextRect(labelText);
		var bandWidth = chartModel
			.getComponent('series')
			.coordinateSystem.getAxis('x')
			.getBandWidth();
		return labelRect.width > bandWidth ? ' ' : params.value[3];
	};
```
