### ISSUE TITLE
Label color based on function

### ISSUE THREAD

**Issue by jonavila** [apache/incubator-echarts#6489]
### One-line summary [问题简述]
I'm trying to set the label color for a series based on a calculation. For example, I may want the label color to be based on data values or I may want to set the text color based on the series item background to make it legible. I tried setting a function for label.normal.color, but that didn't work.

Would it be possible to specify a color via function and get params info like we get for the label formatter?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by psumstr** [comment]
I guess a workaround would be to set the label color by specifying it at the data item level. Something like:
```
options.series[0].data = valueData(data);

    function valueData(data) {
        return data.map(function(d) {
            return {
                value: [groupAccessor.raw(d)[0], groupAccessor.raw(d)[1], metricAccessor.raw(d), metricAccessor.formatted(d), d],
                label: {
                    normal: {
                        color: contrastingColor(metricAccessor.color(d))
                    }
                },
                itemStyle: {
                    normal: {
                        color: metricAccessor.color(d)
                    }
                }
            }
        });
    }

    function contrastingColor(color) {
        return (luma(color) >= 165) ? '#000' : '#fff';
    }

    // color can be a hx string or an array of RGB values 0-255
    function luma(color)  {
        var rgb = (typeof color === 'string') ? echarts.color.parse(color) : color;
        return (0.2126 * rgb[0]) + (0.7152 * rgb[1]) + (0.0722 * rgb[2]); // SMPTE C, Rec. 709 weightings
    }
```
