### ISSUE TITLE
升级到最新版后，Echarts实例存放数组后操作不能保持不变

### ISSUE THREAD

**Issue by tanxingw** [apache/incubator-echarts#6508]
### One-line summary [问题简述]
各位大神：你们好！
       我以前使用的是Echarts3.2.3版本，现在更新到最新版本。
       我有这样一个功能，我把一个Echarts实例化并setOption后把整个实例放到一个数组里面,当我基于同一个容器ID重新实例化一个Echarts的时候，数组里面存放的哪个也跟着改变了，我在用3.2.3版本的时候并没有出现这个问题，到最新版本后就出现了上面这张问题,我希望我每次放到数组里面的实例都保持独立，请问我现在怎么写才能实现呢？非常谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

我希望我每次放到数组里面的实例都保持独立，不受后面操作的影响

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
1. 确定是 ECharts 的问题？
2. 怎么复现？提供一个最精简的可复现版本

**Comment by tanxingw** [comment]
@pissang 
![image](https://user-images.githubusercontent.com/31299707/29656234-77857ef4-88e6-11e7-88aa-4d496f60d0a4.png)
![image](https://user-images.githubusercontent.com/31299707/29656252-89d93f14-88e6-11e7-9335-f8a235564b1c.png)
![image](https://user-images.githubusercontent.com/31299707/29656273-95b136e8-88e6-11e7-85ef-0aceefa5f2da.png)

**Comment by tanxingw** [comment]
@pissang 

![image](https://user-images.githubusercontent.com/31299707/29656554-5d67c06c-88e7-11e7-987a-a1412358ef74.png)

**Comment by tanxingw** [comment]
@pissang 
![image](https://user-images.githubusercontent.com/31299707/29656879-616217a2-88e8-11e7-99d9-25c6d0a0c198.png)

**Comment by tanxingw** [comment]
@pissang 大神，你好！
   请问我这个问题能解决吗？ 谢谢
