### ISSUE TITLE
Echarts如何显示No Data To Display这类的提示信息？

### ISSUE THREAD

**Issue by gogo-Lee** [apache/incubator-echarts#6520]
项目中传入的series为空数组，这个时候希望echarts能够显示一些提示信息，比如No Data To Display之类，echarts有提供这样的配置项吗？谢谢

**Comment by Ovilia** [comment]
可以用 http://echarts.baidu.com/option.html#graphic.elements-text.type 加一个文字，等有数据了再把这个去掉，ECharts 没有自动这样做的功能

**Comment by larrykkk** [comment]
https://github.com/apache/incubator-echarts/issues/5833
