### ISSUE TITLE
关于中国地图 区域的问题

### ISSUE THREAD

**Issue by jnie666** [apache/incubator-echarts#6522]
最近有个需求中国地图按照区域划分展示

请问 中国地图有按区域划分的麽？不按照省份，比如按**华北、华东、华南、华中、西南、西北**划分的中国地图么？
求高手详细解答下！谢谢啦

**Comment by Ovilia** [comment]
需要自己寻找并下载相关地图，参考：http://echarts.baidu.com/faq.html#map-chart

**Comment by chfw** [comment]
这样的行吗？还没有找到如何加海南诸岛。

![screen shot 2018-03-07 at 09 59 38](https://user-images.githubusercontent.com/4280312/37086793-5f59ac12-21f0-11e8-88c6-fc7c6d93af3b.png)

**Comment by jnie666** [comment]
@chfw 肿么实现的？大佬

**Comment by chfw** [comment]
等我加上海南诸岛就[公开发布](https://github.com/echarts-maps/echarts-china-misc-js):

步骤是这样的：

1. 把 china.json 才开成各个省市
2. 把各大区的geojson 合并，抹去内部边界
3. 再把各大区合成 china.json.

**Comment by chfw** [comment]
这个我的项目：https://github.com/echarts-maps/echarts-china-misc-js

[戳这里看怎么做的](https://github.com/echarts-maps/echarts-china-misc-js/tree/master/build/tasks)

**Comment by chfw** [comment]
最终版本：

<img width="528" alt="screen shot 2018-03-09 at 22 37 37" src="https://user-images.githubusercontent.com/4280312/37233297-915c0eca-23ea-11e8-8d67-adfa94a045e3.png">
