### ISSUE TITLE
数据区域缩放在选择一部分且改变了x轴的情况下,  数据跟新后图表渲染出错

### ISSUE THREAD

**Issue by MaZhaolin** [apache/incubator-echarts#6533]
### One-line summary [问题简述]
数据区域缩放在选择一部分且改变了x轴的情况下,  数据跟新后图表渲染出错 如下图
![image](https://user-images.githubusercontent.com/13713662/29802106-f0365d06-8ca5-11e7-813e-37617b2ae4da.png)
![image](https://user-images.githubusercontent.com/13713662/29802117-f8b89c28-8ca5-11e7-8dfd-e2f3d4171eaa.png)

### Version & Environment [版本及环境]
+ EChars version [ECharts 版本]:3.7.0
+ Browser version [浏览器类型和版本]:chrome 60.0.3112.101
+ OS Version [操作系统类型和版本]:Mac10.12 

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/13713662/29802122-ffbf2866-8ca5-11e7-92eb-191dab2792ca.png)

### ECharts option [ECharts配置项]

由于这部分写的有点多,不上配置文件了 用了`setOption`来修改数据，配置没问题，触发这个bug需要两个条件，数据区域缩放在选择一部分且更新数据数改变x轴

**Comment by liping1994** [comment]
我的问题和你一样， 也是x轴变了， 给我返回的数据有误， 希望你可以找到解决方法， 然后告诉我一下，我感觉这是框架的原因 ，根本不知道从哪改。
https://github.com/ecomfe/echarts/issues/6531

**Comment by insertSweat** [comment]
我这里暂时的解决方法是，在切换数据前先将数据缩放重置为全选，参考代码如下
```javascript
           optionAttack.dataZoom = [{
                type: 'slider',
                show: true,
                xAxisIndex: [0],
                start: 0,
                end: 100
            }]
            attackCurveChart.setOption(optionAttack, { notMerge: true })
            optionAttack.xAxis[0].data = attackToday.xData;
            optionAttack.series[0].data = attackToday.yData;
            attackCurveChart.setOption(optionAttack, { notMerge: true })
```
