### ISSUE TITLE
下载图片使用getDataURL，必须将animation改成false,体验不太好

### ISSUE THREAD

**Issue by webJing** [apache/incubator-echarts#6539]
### One-line summary [问题简述]

要使用getDataURL 就必须将animation改成false,这个矛盾怎么解决，怎么能知道什么时候动画结束，拿到完整图片了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

all

### Expected behaviour [期望结果]

期望又能下载玩征途，又能保留图的动画

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
目前，我等[0.5 秒](https://github.com/chfw/pyecharts-snapshot#usage-details)之后再取图。有些图需要[等久一点](https://github.com/chfw/pyecharts-snapshot/issues/4).
