### ISSUE TITLE
echarts web页面嵌入到app  在iphone6 plus 上有时数据加载不上 其他都可以

### ISSUE THREAD

**Issue by zjup1989** [apache/incubator-echarts#6540]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
描述一下具体的复现步骤？

**Comment by dangduang** [comment]
你好，这个问题解决了吗？
