### ISSUE TITLE
横向图例滚动，当单条图例内容超过宽度时，左右切换按钮失效

### ISSUE THREAD

**Issue by callcter** [apache/incubator-echarts#6552]
### One-line summary [问题简述]

横向图例滚动，当单条图例内容超过宽度时，左右切换按钮失效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7
+ Browser version [浏览器类型和版本]: chrome 60
+ OS Version [操作系统类型和版本]: macOS sierra 10.12.6

### Expected behaviour [期望结果]

正常左右切换

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有可以复现的配置项么？

**Comment by callcter** [comment]
配置不方便贴出来，我另外做了一个例子，出现了同样的 bug
[bug 复现链接](http://runjs.cn/code/mfsaaolp)

**Comment by callcter** [comment]
@pissang
