### ISSUE TITLE
在IE8下柱状图和曲线图的字体颜色设置无效，设置的白色，显示为黑色；

### ISSUE THREAD

**Issue by XiuMu59** [apache/incubator-echarts#6570]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

#

**Comment by pissang** [comment]
怎么配置的？

**Comment by JustNeedOneMoreStep** [comment]
3.7的话可以试下照这个
https://github.com/ecomfe/zrender/commit/201c2342199af149c860e68b8f8812249cae7952
去修改下源码,  我改了过后IE8显示正常了
