### ISSUE TITLE
Gauge类型的字体大小设置不起作用

### ISSUE THREAD

**Issue by lijh18** [apache/incubator-echarts#6572]
series: [{
			        type: 'gauge',
			        name: '<%=key%>',
			        data: [{value:<%=value%>,name:'<%=key%>'}],
			        detail:{
			        	show:true,
			        	fontStyle: 'normal',
			        	**fontSize: 10**
			        },
代码中已经设置了字体大小为10 ，可视仪表盘显示结果的时候 还是默认值为15，请问这个是一个Bug吗

**Comment by janetwu** [comment]
@lijh18，我也是改了无反应，找了好久无果。奇怪的是在 http://echarts.baidu.com/demo.html#gauge-car 上改是启作用了，后面发现引用的js版本不一样，要起作用的话需要用它的完整版。 还以为参数设置错误，白白浪费了那么多时间。。。/(ㄒoㄒ)/~~
