### ISSUE TITLE
地图添加 roam:true 鼠标缩放后，在chrome版本 60.0.3112.113（正式版本） （64 位）下无法触发选中区域

### ISSUE THREAD

**Issue by qiuyuwu** [apache/incubator-echarts#6574]
### One-line summary [问题简述]

地图添加 roam:true 鼠标缩放后，在chrome版本 60.0.3112.113（正式版本） （64 位）下无法触发选中区域事件。其他浏览器正常。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome版本 60.0.3112.113（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:window7 64位

### Expected behaviour [期望结果]
解决

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'item',
        formatter: '{b}'
    },
    series: [
        {
            name: '中国',
            type: 'map',
            mapType: 'china',
               roam:true,
            selectedMode : 'single',
            label: {
                normal: {
                    show: true
                },
                emphasis: {
                    show: true
                }
            },
            data:[
                {name:'广东', selected:true}
            ]
        }
    ]
};

```

**Comment by pissang** [comment]
我这无法复现

**Comment by WwupengP** [comment]
win10 chrome61 设置系统的放大倍数为非100%的时候 echarts图在series鼠标悬浮时出现的黑色透明背景都会偏移
