### ISSUE TITLE
最新的地图法规定了中国地图的样式，要包含钓鱼岛和藏南地区等，echarts有没有升级的计划？

### ISSUE THREAD

**Issue by liujiliang2008** [apache/incubator-echarts#6584]
### One-line summary [问题简述]
如题，最新的地图法规定了中国地图的样式，要包含钓鱼岛和藏南地区等，echarts有没有升级的计划？

**Comment by pissang** [comment]
echarts 地图中是包含钓鱼岛和藏南地区的

**Comment by liujiliang2008** [comment]
红圈里是没有钓鱼岛的，其他还有地方和最新的国家地图要求不太一样的。

![image](https://user-images.githubusercontent.com/4192239/30015609-f8e7a0b2-9183-11e7-8cc9-c921f6558cb5.png)

不知道百度echarts有没有收到 “问题地图”专项治理 的通知？

![image](https://user-images.githubusercontent.com/4192239/30015384-1828b7aa-9183-11e7-9924-06e8f57c8ee3.png)

[http://chzt.sbsm.gov.cn/article/zxgz/wtdtzxzlxd/qwfb/201106/20110600083784.shtml](url)

**Comment by 100pah** [comment]
![image](https://user-images.githubusercontent.com/1956569/30024240-6f2f0122-91a5-11e7-9576-4abba587cbcb.png)

钓鱼岛在这里，缩放后即可看到。
因为钓鱼岛面积相对较小，所以地图缩小后不容易看到。

**Comment by liujiliang2008** [comment]
藏南地区呢？上面正误对比，2的那个标志

**Comment by liujiliang2008** [comment]
还有南沙...

**Comment by pissang** [comment]
藏南地区哪有问题了？

**Comment by liujiliang2008** [comment]
藏南瞅着不太对，你们看看最新的地图呢？
南沙肯定是不符合的
![image](https://user-images.githubusercontent.com/4192239/30043900-e8cd6b4a-922c-11e7-9920-a318d937294b.png)

国家测绘地理信息局通过标准地图服务网站（ http://bzdt.nasg.
gov.cn/）发布了一系列标准地图，包括中国地图、世界地图、专题
地图并提供自助制图功能。国家测绘地理信息局还通过国家地理信
息公共服务平台“天地图”（ http://www.tianditu.gov.cn）提供权威、
标准、统一的互联网地图综合服务。

**Comment by pissang** [comment]
嗯，南沙的已经在升级计划里了

**Comment by liujiliang2008** [comment]
恩恩，整体都看下吧。里面好多要求，貌似咱们echarts里整个中国地图的轮廓就和要求不太一样，“鸡头” “鸡尾” 都往下偏。
咱们这个升级计划是啥？啥时间会发新版本呢？

**Comment by liujiliang2008** [comment]
还想问一下，钓鱼岛能不能在地图缩小的情况下就标一个点出来？ @pissang  @100pah

**Comment by chfw** [comment]
另一个解决方法是把钓鱼岛另外匡起来，画大图，就像是画南沙群岛一样。

**Comment by liujiliang2008** [comment]
@chfw 那么想过，但是标准地图是只有南沙是框起来的，钓鱼岛如果也框起来不符合标准呀。
感觉钓鱼岛弄个点标出来就行。

**Comment by faxiao** [comment]
目前中国地图放大那个也不是钓鱼的，标注是台湾 @100pah ，能不能先给个修改方法，我们自己先临时调整下源码绘制写南海诸岛的岛屿点图、和钓鱼岛出来呢？`
![image](https://user-images.githubusercontent.com/32259894/30799642-1c6c6ecc-a210-11e7-8d09-d23af9151b70.png)

**Comment by chfw** [comment]
手动再空白处填充了海南诸岛：

全景图：
![screen shot 2018-03-08 at 23 37 04](https://user-images.githubusercontent.com/4280312/37182567-cf09c90e-2329-11e8-9994-582bac884632.png)

放大
![screen shot 2018-03-08 at 23 37 28](https://user-images.githubusercontent.com/4280312/37182609-02226ea4-232a-11e8-9142-d6c0e9023673.png)

再放大
![screen shot 2018-03-08 at 23 37 52](https://user-images.githubusercontent.com/4280312/37182615-0b0a7750-232a-11e8-85d0-c219ee46689b.png)

这样能通过审核么？

**Comment by tobbychen** [comment]
这个问题都这么久了 还没有更新 百度的在线地图居然都没把国境线修改正确。。。

**Comment by qq382724935** [comment]
> 手动再空白处填充了海南诸岛：
> 
> 全景图： ![screen shot 2018-03-08 at 23 37 04](https://user-images.githubusercontent.com/4280312/37182567-cf09c90e-2329-11e8-9994-582bac884632.png)
> 
> 放大 ![screen shot 2018-03-08 at 23 37 28](https://user-images.githubusercontent.com/4280312/37182609-02226ea4-232a-11e8-9142-d6c0e9023673.png)
> 
> 再放大 ![screen shot 2018-03-08 at 23 37 52](https://user-images.githubusercontent.com/4280312/37182615-0b0a7750-232a-11e8-85d0-c219ee46689b.png)
> 
> 这样能通过审核么？

你这个绘制南海诸岛是怎么绘制的呀，修改源码吗
