### ISSUE TITLE
小屏幕下数据显示问题

### ISSUE THREAD

**Issue by yandeqiang** [apache/incubator-echarts#6590]
数据是异步拉去后塞进去的(200 个点）

x 轴type 是 category

小屏幕（1440）下显示情况：
![小屏幕下](https://p2.ssl.qhimg.com/t019e117149f8b96940.jpg)

大屏幕(1920)显示情况：
![大屏幕下](https://p4.ssl.qhimg.com/t016417b5c2b4ae4eb2.jpg) 

帮忙看看，thanks

**Comment by Ovilia** [comment]
数据在 http://gallery.echartsjs.com/editor.html 复现一下，谢谢
