### ISSUE TITLE
设置snap为false仍然有吸附效果。

### ISSUE THREAD

**Issue by nachao** [apache/incubator-echarts#6591]
### One-line summary [问题简述]
设置snap为false仍然有吸附效果。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4（在3.7.1中也测试仍然）
+ Browser version [浏览器类型和版本]:  chrome 55
+ OS Version [操作系统类型和版本]: windows

### Expected behaviour [期望结果]
当设置不吸附时，鼠标放在x轴时间没有数值的地方上，不会吸附最近的一个点。

### ECharts option [ECharts配置项]

```javascript
option = {
	tooltip: {
		axisPointer: {
			snap: false
		}
	},
	axisPointer: {
		snap: false
	},
	xAxis: {
		axisPointer: {
			snap: false
		}
	},
	yAxis: {
		axisPointer: {
			snap: false
		}
	},
}

```

### Other comments [其他信息]

![qq 20170905120222](https://user-images.githubusercontent.com/11830727/30044821-693b823a-9232-11e7-8baa-1b892b84593f.jpg)

**Comment by hiwanz** [comment]
[https://github.com/apache/incubator-echarts/blob/fd064123626c97b36cbd6da1b5fc73385c280abd/src/component/axisPointer/BaseAxisPointer.js#L175](https://github.com/apache/incubator-echarts/blob/fd064123626c97b36cbd6da1b5fc73385c280abd/src/component/axisPointer/BaseAxisPointer.js#L175)

Value axis without snap always do not snap，except category axis
