### ISSUE TITLE
x轴的两个刻度叠加在一起了， 然后看不清楚刻度， showMaxLabel:null 为什么判定失败了

### ISSUE THREAD

**Issue by liping1994** [apache/incubator-echarts#6598]
![image](https://user-images.githubusercontent.com/23331306/30052566-6cd15cd2-9258-11e7-85a6-7e43dc3b9d08.png)

是否显示最大 tick 的 label。可取值 true, false, null。默认自动判定（即如果标签重叠，不会显示最大 tick 的 label）。

**Comment by Ovilia** [comment]
https://github.com/ecomfe/echarts/commit/782a4ebbf1e8bd320d9e36f9d99c89599ec286d6 应该修复了这个问题，等下一个版本上线试一下，或者把 option 代码贴一下
