### ISSUE TITLE
多条数据叠加情况下，数据比较密集时，请问自动吸附的精度如何设置？

### ISSUE THREAD

**Issue by nachao** [apache/incubator-echarts#6600]
### One-line summary [问题简述]
前提：
1、x轴以时间方式显示；
2、两个或多个个参数；

此时对于偏差几十秒的数据，仍然都会选中，请问是否可以设置鼠标吸附的精度？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4
+ Browser version [浏览器类型和版本]:Chrome 55
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
每次只显示指定时间的值。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![default](https://user-images.githubusercontent.com/11830727/30055890-61913558-9263-11e7-8a36-1975527e9afe.png)

**Comment by Ovilia** [comment]
不能，建议使用 dataZoom 放大区域
