### ISSUE TITLE
折线图可以自定义长度么？

### ISSUE THREAD

**Issue by ugvgylkm** [apache/incubator-echarts#6614]
问下是否可以做成第二个图的形式，正常一个点没有数据两边的线都断了，用什么方式可以让这个没有数据的点后面的线断掉，前面的还是连上的？

如下图1
![qq 20170907105020](https://user-images.githubusercontent.com/11737292/30143846-62c03e9e-93ba-11e7-93d2-4437f4a5e288.png)

如下图2
![qq 20170907105233](https://user-images.githubusercontent.com/11737292/30144025-58850e90-93bb-11e7-871d-4a9b49f08b9f.png)

**Comment by pissang** [comment]
`connectNulls`

**Comment by ugvgylkm** [comment]
@pissang  不是全连接上，是连接前面一半，connectNulls这是个boolean类型 ，设置的话都连接上了。

**Comment by Ovilia** [comment]
这个没法实现哦，只能你自己研究下怎么改源代码实现
