### ISSUE TITLE
关系图中设置了主题，option中设置color就不起作用

### ISSUE THREAD

**Issue by node-rookie** [apache/incubator-echarts#6616]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.1
+ Browser version [浏览器类型和版本]:chrome canary
+ OS Version [操作系统类型和版本]:mac

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
设置 series 里的颜色
