### ISSUE TITLE
多个饼图，鼠标移动到图例，放大动画异常

### ISSUE THREAD

**Issue by sumanit** [apache/incubator-echarts#6620]
### One-line summary [问题简述]
多个饼图时图例存在问题，鼠标移动到图例事，只有一个饼图的对应item会有动画放大效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
多个饼图时鼠标放到图例上，所有拥有该图例数据的饼图item均放大，特殊显示
```

```

### ECharts option [ECharts配置项]

```javascript
option = {
    title : {
        text: '某站点用户访问来源',
        subtext: '纯属虚构',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        left: 'left',
        data: ['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series : [
        {
            name: '访问来源1',
            type: 'pie',
            radius : '30%',
            center: ['30%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        },
         {
            name: '访问来源2',
            type: 'pie',
            radius : '30%',
            center: ['80%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};

```

### Other comments [其他信息]

在饼图的 type: 'legend.plain'的renderInner方法中修改如下代码（59475行左右）

```
  itemGroup.on('click', curry(dispatchSelectAction, name, api));
	                                // FIXME Should not specify the series name
	                              //  .on('mouseover', curry(dispatchHighlightAction, seriesModel, name, api))
	                               // .on('mouseout', curry(dispatchDownplayAction, seriesModel, name, api));
								
	                            legendDrawnMap.set(name, true);
								ecModel.eachRawSeries(function (seriesModel1) {

			                        if (seriesModel.legendDataProvider) {
			                            var data = seriesModel.legendDataProvider();
			                            var idx = data.indexOfName(name);
			                            if (idx < 0) {
			                                return;
			                            }

			                            itemGroup
			                                // FIXME Should not specify the series name
			                                .on('mouseover', curry(dispatchHighlightAction, seriesModel1, name, api))
			                                .on('mouseout', curry(dispatchDownplayAction, seriesModel1, name, api));
		
			        
			                        }
			                    }, this);
```

**Comment by llsr** [comment]
怎么把这个该死的邮件退掉？？？？

在 2017-09-07 17:33:32，"苏曼" <notifications@github.com> 写道：

One-line summary [问题简述]

多个饼图时图例存在问题，鼠标移动到图例事，只有一个饼图的对应item会有动画放大效果

Version & Environment [版本及环境]
ECharts version [ECharts 版本]:echarts3
Browser version [浏览器类型和版本]:chrome
OS Version [操作系统类型和版本]:windows
Expected behaviour [期望结果]

多个饼图时鼠标放到图例上，所有拥有该图例数据的饼图item均放大，特殊显示

ECharts option [ECharts配置项]
option = {
    title : {
        text:'某站点用户访问来源',
        subtext:'纯属虚构',
        x:'center'
    },
    tooltip : {
        trigger:'item',
        formatter:"{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient:'vertical',
        left:'left',
        data: ['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series : [
        {
            name:'访问来源1',
            type:'pie',
            radius :'30%',
            center: ['30%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur:10,
                    shadowOffsetX:0,
                    shadowColor:'rgba(0, 0, 0, 0.5)'
                }
            }
        },
         {
            name:'访问来源2',
            type:'pie',
            radius :'30%',
            center: ['80%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur:10,
                    shadowOffsetX:0,
                    shadowColor:'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};

Other comments [其他信息]

在饼图的 type: 'legend.plain'的renderInner方法中修改如下代码（59475行左右）

  itemGroup.on('click', curry(dispatchSelectAction, name, api));
	                                // FIXME Should not specify the series name
	                              //  .on('mouseover', curry(dispatchHighlightAction, seriesModel, name, api))
	                               // .on('mouseout', curry(dispatchDownplayAction, seriesModel, name, api));
								
	                            legendDrawnMap.set(name, true);
								ecModel.eachRawSeries(function (seriesModel1) {

			                        if (seriesModel.legendDataProvider) {
			                            var data = seriesModel.legendDataProvider();
			                            var idx = data.indexOfName(name);
			                            if (idx < 0) {
			                                return;
			                            }

			                            itemGroup
			                                // FIXME Should not specify the series name
			                                .on('mouseover', curry(dispatchHighlightAction, seriesModel1, name, api))
			                                .on('mouseout', curry(dispatchDownplayAction, seriesModel1, name, api));
		
			        
			                        }
			                    }, this);

**Comment by Ovilia** [comment]
复现的例子：http://gallery.echartsjs.com/editor.html?c=xr1oV03m9-&v=1

**Comment by slsyx** [comment]
是的 鼠标放到tu'li图例上，显示存在问题，左侧红框内的item没有放大
![9d3551xi opcb0 qiridwtp](https://user-images.githubusercontent.com/18345372/30263680-82e61378-9708-11e7-973a-c93a2712fbfe.png)
