### ISSUE TITLE
bar图超过超过坐标区域

### ISSUE THREAD

**Issue by hizhengfu** [apache/incubator-echarts#6626]
### One-line summary [问题简述]
显示柱状图时，超过X坐标边界

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.1
+ Browser version [浏览器类型和版本]:chrome 60
+ OS Version [操作系统类型和版本]: sierria

### Expected behaviour [期望结果]

柱状图不要超过坐标区域

### ECharts option [ECharts配置项]

```javascript
function randomData() {
    now = new Date(+now + oneDay);
    value = value + Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
            Math.round(value)
        ]
    }
}

var data = [];
var now = +new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var value = Math.random() * 1000;
for (var i = 0; i < 10; i++) {
    data.push(randomData());
}

option = {
    title: {
        text: '动态数据 + 时间坐标轴'
    },
    tooltip: {
        trigger: 'axis',
        formatter: function (params) {
            params = params[0];
            var date = new Date(params.name);
            return date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + params.value[1];
        },
        axisPointer: {
            animation: false
        }
    },
    xAxis: {
        type: 'time',
        splitLine: {
            show: false
        }
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: '模拟数据',
        type: 'bar',
        showSymbol: false,
        hoverAnimation: false,
        data: data
    }]
};

setInterval(function () {

    for (var i = 0; i < 5; i++) {
        data.shift();
        data.push(randomData());
    }

    myChart.setOption({
        series: [{
            data: data
        }]
    });
}, 1000);
```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/446359/30192072-9d972132-9477-11e7-9dd7-82746d8266e5.png)

**Comment by llsr** [comment]
怎么把这个邮件退掉？？有知道的吗

在 2017-09-08 09:29:52，"hizhengfu" <notifications@github.com> 写道：

One-line summary [问题简述]

显示柱状图时，超过X坐标边界

Version & Environment [版本及环境]
ECharts version [ECharts 版本]:3.7.1
Browser version [浏览器类型和版本]:chrome 60
OS Version [操作系统类型和版本]: sierria
Expected behaviour [期望结果]

柱状图不要超过坐标区域

ECharts option [ECharts配置项]
functionrandomData() {
    now =newDate(+now + oneDay);
    value = value +Math.random() *21-10;
    return {
        name:now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() +1, now.getDate()].join('/'),
            Math.round(value)
        ]
    }
}

var data = [];
var now =+newDate(1997, 9, 3);
var oneDay =24*3600*1000;
var value =Math.random() *1000;
for (var i =0; i <10; i++) {
    data.push(randomData());
}

option = {
    title: {
        text:'动态数据 + 时间坐标轴'
    },
    tooltip: {
        trigger:'axis',
        formatter:function (params) {
            params = params[0];
            var date =newDate(params.name);
            returndate.getDate() +'/'+ (date.getMonth() +1) +'/'+date.getFullYear() +' : '+params.value[1];
        },
        axisPointer: {
            animation:false
        }
    },
    xAxis: {
        type:'time',
        splitLine: {
            show:false
        }
    },
    yAxis: {
        type:'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show:false
        }
    },
    series: [{
        name:'模拟数据',
        type:'bar',
        showSymbol:false,
        hoverAnimation:false,
        data: data
    }]
};

setInterval(function () {

    for (var i =0; i <5; i++) {
        data.shift();
        data.push(randomData());
    }

    myChart.setOption({
        series: [{
            data: data
        }]
    });
}, 1000);
Other comments [其他信息]

**Comment by node-rookie** [comment]
一个折中的解决方案，设置x轴的min和max，用函数
```javascripy (type)
xAxis : [
        {
            type : 'time',
            min: function(value) {
                console.error(value);
                return value.min - 60*60*1000;
            },
            max: function(value) {
                console.error(value);
                return value.max + 60*60*1000;
            }, 
        }
    ]
```

**Comment by hizhengfu** [comment]
@node-rookie 感谢提供方案，这样确实是能解决问题。这个方式可能在多柱状图时还需要在去调整下最大最小值。
