### ISSUE TITLE
candlestick 蜡烛图data数据项设置为object时，图不显示。

### ISSUE THREAD

**Issue by qilerongrong** [apache/incubator-echarts#6633]
参照以下文档设置数据项时，蜡烛图不显示。
{
    value:[open,close,high,low],
    itemStyle:{...}
}
http://echarts.baidu.com/option.html#series-candlestick.data

 { // 数据项也可以是 Object，从而里面能含有对此数据项的特殊设置。
        value: [2300,    2291.3,  2288.26, 2308.38],
        itemStyle: {...}
    },
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/explore.html 上贴出你的例子？

**Comment by qilerongrong** [comment]
你好！
http://gallery.echartsjs.com/editor.html?c=xS1Kj7Tm5b&v=1
这个是我发布的，其实是按照
http://echarts.baidu.com/demo.html#candlestick-brush
这个demo例子改的，只是把蜡烛图的数据格式换了一下。
我标注下改动的地方：
![image](https://user-images.githubusercontent.com/26840864/30264467-5e57fb68-970b-11e7-8393-d60f848e192b.png)
![image](https://user-images.githubusercontent.com/26840864/30264541-92cb2ee2-970b-11e7-8d4b-9cdf277c47d3.png)
麻烦帮忙看一下。谢谢~~

**Comment by qilerongrong** [comment]
@pissang hi，不知道这个问题是否存在，我这里想针对K线的某些数据做一些处理，使用object的时候K线画不出来。

**Comment by lovewuyong** [comment]
我也是遇到这个问题，k线图或者箱线图想单独设置每个图的颜色，按照文档把数组格式换成对象格式，图就出不来了
```
{
value: [2300, 2291.3, 2288.26, 2308.38],
itemStyle: {...}
}
```

**Comment by ccbphi** [comment]
![image](https://user-images.githubusercontent.com/17720550/32777061-b8a68954-c96f-11e7-94fc-da651a969220.png)

downcolori  改成 downcolor
