### ISSUE TITLE
升级到 v 3.7.1 渐进式渲染

### ISSUE THREAD

**Issue by mike-han** [apache/incubator-echarts#6638]
把 progressiveThreshold 设置成1000
当我的 series[0].data的数量超过了1000， chart渲染出来表面会有一层线条
截图：
![echarts](https://user-images.githubusercontent.com/16368087/30257078-2689b3bc-96e2-11e7-9c2b-8920713ac851.png)

**注意：我的配置一直是这样，之前用的 v 3.5.2 是没有这个问题的**

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: Chrome 60.0.3112.113（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:win 10

### ECharts option [ECharts配置项]
```
        option.hoverLayerThreshold = 1000;
        option.progressiveThreshold = 1000;
        option.progressive = 100;
        option.animationThreshold = 1000;
```

**Comment by pissang** [comment]
有完整的配置项么？

**Comment by Mignon-han** [comment]
我把我的配置  粘贴到你们的 gallery 无法重现， 但是一些回调函数粘贴不过去。
在我的工程里，只要取消的这个progressiveThreshold 参数，就没问题。
升级Ecahrts版本之前，一直没问题， 所以感觉还是和升级有关

我看你们的版本记录， 说渲染效率提升了 50%， 会不会是你们优化的过程有什么改变

**Comment by pissang** [comment]
那次优化应该跟渐进式渲染没有关系（但是也不敢完全排除），所以最好可以让我们看下可以复现的代码

**Comment by Mignon-han** [comment]
@pissang 我的代码 粘到 gallery上无法重现， 好像和 我调用两次 `setOption`有点关系
但是升级前确实没问题， 看来问题不是一个原因导致的
我现在在尝试只调用一次setOption渲染
