### ISSUE TITLE
Component series.custom not exists. Load it first.

### ISSUE THREAD

**Issue by chenzhiwei199** [apache/incubator-echarts#6642]
### One-line summary [问题简述]
我通过content.tmp.series[3].type = "custom"; 这种方式设置custom,但是出现了
Component series.custom not exists. Load it first.这个错误。
echart 安装方式为 npm install echarts --save

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by UweWindt** [comment]
I got the same Error

**Comment by xiaomao996688** [comment]
怎么回事啊，我也遇到了这个错误，有啥办法解决了？

**Comment by zuoq** [comment]
Some versions do not support the custom type, take a look at the source code
