### ISSUE TITLE
svg自身没有虚边，但是放到toolbox里作为自定义icon就有虚边了

### ISSUE THREAD

**Issue by liping1994** [apache/incubator-echarts#6651]
配置如下图
![image](https://user-images.githubusercontent.com/23331306/30307657-429b1e58-97b2-11e7-8446-29a20c0da080.png)

链接
http://gallery.echartsjs.com/editor.html?c=xSkgajR45W&comment=0

**Comment by Ovilia** [comment]
这个应该是描边粗细的问题，你看看这样行不行：
http://gallery.echartsjs.com/editor.html?c=xSkgajR45W&v=3

**Comment by liping1994** [comment]
@Ovilia  还是有虚边   这样不能放到线上

**Comment by Ovilia** [comment]
你把 SVG 里的截图，和 ECharts 里的效果图放上来一下？
