### ISSUE TITLE
关于单轴散点图的markLine

### ISSUE THREAD

**Issue by cling330** [apache/incubator-echarts#6657]
### One-line summary [问题简述]
如下图所示，单轴散点图的markLine能否做到垂直于X轴。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
现在我的做法是通过分别指定起止点坐标的方式，但是这样不够精确。
echartsInstance.convertToPixel()貌似也不支持单轴图。
不知是否有好的方案？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/29942125/30315576-0731aa60-97d7-11e7-8c33-fefa8864fcf7.png)

**Comment by pissang** [comment]
可以试试用 [custom](http://echarts.baidu.com/option.html#series-custom) 系列组件
