### ISSUE TITLE
Echarts地图上能否复合上柱图

### ISSUE THREAD

**Issue by jim8757** [apache/incubator-echarts#6672]
我尝试着在地图上绘制柱图，但是不能成功，Bar必须要在直角坐标系上，但是Geo坐标系与直角坐标系放在同一个Option就报错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echarts 3
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]:Win 7 

### ECharts option [ECharts配置项]

```javascript
option = {
{
                geo: {
                    map: 'china',
                    regions: [{
                        name: '广东',
                        itemStyle: {
                            normal: {
                                areaColor: 'blue',
                                color: 'blue'
                            }
                        }
                    }],
                    itemStyle: {                    // 定义样式
                        normal: {                   // 普通状态下的样式
                            areaColor: '#323c48',
                            borderColor: '#111'
                        },
                        emphasis: {                 // 高亮状态下的样式
                            areaColor: '#2a333d'
                        }
                    }
                },
                backgroundColor: '#404a59',
                series: [
                    {
                        name: 'GDP', // series名称
                        type: 'bar', // series图表类型
                        coordinateSystem: 'cartesian2d', // series坐标系类型
                        data:myData,
                    }
                ]
            };

}

```

**Comment by pissang** [comment]
能否具体描述你的问题？

**Comment by jim8757** [comment]
您好，我的需求是在中国地图的区域上绘制柱图，例如，我需要在地图上展示各省份的GDP的数据，通过柱的高度来表示GDP的大小。我用官网的map + scatter的模式，但是发现柱图必须要有在直角坐标系中，然后地图又必须是在地理坐标系中。两个配置到同一个Option就会报错。

**Comment by jim8757** [comment]
具体的代码如下：
`var chart = echarts.init(document.getElementById('main'));
            var myData = [
                    {name: '海门', value: [121.15, 31.89, 90]},
                    {name: '鄂尔多斯', value: [109.781327, 39.608266, 120]},
                    {name: '招远', value: [120.38, 37.35, 142]},
                    {name: '舟山', value: [122.207216, 29.985295, 123]},
            ];

            var option = {
                geo: {
                    map: 'china',
                    regions: [{
                        name: '广东',
                        itemStyle: {
                            normal: {
                                areaColor: 'blue',
                                color: 'blue'
                            }
                        }
                    }],
                    itemStyle: {                    // 定义样式
                        normal: {                   // 普通状态下的样式
                            areaColor: '#323c48',
                            borderColor: '#111'
                        },
                        emphasis: {                 // 高亮状态下的样式
                            areaColor: '#2a333d'
                        }
                    }
                },
                backgroundColor: '#404a59',
                series: [
                    {
                        name: 'GDP', // series名称
                        type: 'bar', // series图表类型
                        coordinateSystem: 'cartesian2d', // series坐标系类型
                        data:myData,
                    }
                ]
            };

            chart.setOption(option); `

**Comment by Ovilia** [comment]
应该有两个系列，一个用来显示地图数据，一个用来显示柱图？
