### ISSUE TITLE
echarts是否提供类似dispatchEvent的触发事件的API

### ISSUE THREAD

**Issue by liajoy** [apache/incubator-echarts#6679]
### One-line summary [问题简述]
API当中已有dispatchAction，但是它只能触发action事件，对于鼠标事件的触发是否存在相应的API？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望有类似这样的用法
myChart.dispatchEvent({
type:'click'
})
或者
myChart.dispatchAction({
type:'click'
})

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mrmengjun** [comment]
@liajoy 你可以设置click:()=>{}

**Comment by yeahe83** [comment]
没看懂

**Comment by liajoy** [comment]
@mrmengjun 
不是想监听click事件，而是想触发echart的click事件
以柱状图为例，我想触发柱状图里的第二个柱子的点击事件
我可以去通过途径去找那个柱子所对应的pageX和pageY，然后再通过dispatchEvent进行触发，但是这样太麻烦了

**Comment by a10309989** [comment]
@liajoy 这个问题解决了吗

**Comment by liajoy** [comment]
@a10309989 并没有 只能通过上述hack的方式解决
