### ISSUE TITLE
关于“问题地图”清查工作

### ISSUE THREAD

**Issue by BallisticStone** [apache/incubator-echarts#6687]
### One-line summary [问题简述]
首先，非常感谢诸位大神的付出，Echarts现在已经是我可视化开发必不可少的工作，已经集成到最近的几个项目中，效果非常好，再次感谢！
开始说问题，最近单位接到通知，响应国家关于“问题地图”的清查工作，发现Echarts官方提供的版本中存在如下问题：
1、漏绘我国钓鱼岛、赤尾屿；
2、漏绘我国南海诸岛；
因其敏感性，不得已被迫关掉访问入口，请问各位大神核实一下，如确实存在能否对应更新一下？
不胜感激

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   3.7
+ Browser version [浏览器类型和版本]:  Chrome最新浏览器
+ OS Version [操作系统类型和版本]:    Linux x64

### Expected behaviour [期望结果]
期待您的回复！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by yake12333** [comment]
大神，请问问题地图怎么解决的？

**Comment by BallisticStone** [comment]
暂时还没有解决，先给停掉了，等着官方更新吧

**Comment by faxiao** [comment]
急需盼解决啊。。。。。

**Comment by yake12333** [comment]
耐心等
