### ISSUE TITLE
bmap初始化坐标点没有对准，拖动地图之后会对准

### ISSUE THREAD

**Issue by haibaradc** [apache/incubator-echarts#6694]
### One-line summary [问题简述]
中心点天津
![image](https://user-images.githubusercontent.com/8393644/30511743-03f4df78-9b12-11e7-9828-c659df4936e7.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html 复现一下

**Comment by xianxingg** [comment]
@Ovilia 遇到了同样的问题

在官方示例 http://echarts.baidu.com/examples/editor.html?c=effectScatter-bmap 中，首次运行代码后，沈阳市的scatter点出现在代表城市的红点的右侧，先放大再缩小之后，scatter点与红点重合！

浏览器类型及版本： Chrome 63.0.3239.132 32位
OS Version： Win8 家庭版
