### ISSUE TITLE
用360浏览器打开初始化地图会有白线，拖动之后偶尔出现偶尔消失

### ISSUE THREAD

**Issue by haibaradc** [apache/incubator-echarts#6697]
![image](https://user-images.githubusercontent.com/8393644/30517537-4ad5659c-9b95-11e7-98fe-dd69a8e6e271.png)

### One-line summary [问题简述]
用360浏览器打开初始化地图会有白线，拖动之后偶尔出现偶尔消失

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by haibaradc** [comment]
请问怎么能让初始化时候白线消失呢？

**Comment by DukeGJ** [comment]
我觉得2个原因：
1.你在初始化的过程中添加了其他东西
2.浏览器原因，用其他浏览器打开试试

**Comment by Ovilia** [comment]
所有地图吗？能否给个可运行的例子？
