### ISSUE TITLE
echarts如何适用于移动端   求大佬帮助

### ISSUE THREAD

**Issue by LYSheng** [apache/incubator-echarts#6698]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jnie666** [comment]
你说的是哪一种图 适配移动端?

**Comment by Ovilia** [comment]
http://echarts.baidu.com/tutorial.html#%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%87%AA%E9%80%82%E5%BA%94

**Comment by Ovilia** [comment]
@LYSheng 请明确描述你的问题，谢谢
