### ISSUE TITLE
pictorialBar 的 label emphasis 无效

### ISSUE THREAD

**Issue by wm370857724** [apache/incubator-echarts#6699]
### One-line summary [问题简述]
pictorialBar 的 label emphasis 无效

### Version & Environment [版本及环境]
+ ECharts version [3.7.1]:
+ Browser version [Chrome latest]:
+ OS Version [macOS latest]:

### Expected behaviour [期望结果]
修复问题
pictorialBar 的 label emphasis 所有属性可以使用

### ECharts option [ECharts配置项]

```javascript


var labelSetting = {
    normal: {
        show: true,
        position: 'outside',
        offset: [10, 0],
        textStyle: {
            fontSize: 16
        }
    },
    emphasis:{
        show: false
    }
};



```

**Comment by Ovilia** [comment]
你是想实现鼠标移动上去的时候不显示 label？
