### ISSUE TITLE
请教地图叠加热力关系图

### ISSUE THREAD

**Issue by lituotju** [apache/incubator-echarts#6717]
One-line summary [问题简述]

希望在中国某省地图中显示出某个不良客户和其他不良客户的关系图 ，关系之间不需要连线，表示成有颜色热力圆圈即可（不同的不良客户依照程度不同给予不同的深度），请问这种图echart可以实现吗？如果是否可以给出示例代码
Version & Environment [版本及环境]

ECharts version [ECharts 版本]:3.6.0
Browser version [浏览器类型和版本]: chrome49
OS Version [操作系统类型和版本]:win7
Expected behaviour [期望结果]
地图叠加热力关系图效果

**Comment by Ovilia** [comment]
你这个需求应该是地图叠加散点图，然后修改散点图的颜色和半径，参考：http://gallery.echartsjs.com/editor.html?c=xrJiNae2-x
