### ISSUE TITLE
调用myChart.getDataURL后，effectScatter的涟漪动画消失

### ISSUE THREAD

**Issue by holmium** [apache/incubator-echarts#6723]
### One-line summary [问题简述]
调用

myChart.getDataURL({type:"png", backgroundColor:backgroundcolor});

后，effectScatter的涟漪动画消失。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.1
+ Browser version [浏览器类型和版本]:Opera 47.0.2631.80
+ OS Version [操作系统类型和版本]:Win10

### Expected behaviour [期望结果]
保持涟漪动画。

### ECharts option [ECharts配置项]

option与http://echarts.baidu.com/gallery/editor.html?c=effectScatter-map一致

**Comment by DukeGJ** [comment]
是不是图上的点太小，我试了一下，假如symbolSize太小的显示不出涟漪效果

**Comment by holmium** [comment]
不是，因为调用getDataURL前后有明显区别。

**Comment by Ovilia** [comment]
先 `animation: false`。我怀疑是保存的时候点还没扩散出来。

**Comment by holmium** [comment]
不是保存的图片出现问题，是生成图片后，原来的canvas会出现问题
