### ISSUE TITLE
请问，关系图的位置可以固定吗，可以的话是需要调整哪个API？盼答复.

### ISSUE THREAD

**Issue by joker-xc** [apache/incubator-echarts#6724]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-graph.data.x
