### ISSUE TITLE
请问怎么实现移动端，按住时显示提示框，松开时提示框消失？

### ISSUE THREAD

**Issue by H5DevHoward** [apache/incubator-echarts#6726]
### One-line summary [问题简述]
tooltip.triggerOn目前只有'mousemove|click'几种吗？
能否实现按住时显示提示框，松开时提示框消失？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
监听事件，并触发 http://echarts.baidu.com/api.html#action.tooltip
