### ISSUE TITLE
无法选择dark 主题

### ISSUE THREAD

**Issue by hehanbo1990** [apache/incubator-echarts#6730]
### One-line summary [问题简述]

无法选择主题，无限loading

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:macos

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/6762674/30675026-a4f66224-9eb0-11e7-81ae-251befde3c97.png)

**Comment by DukeGJ** [comment]
你再试试，我的都可以切换主题

**Comment by hehanbo1990** [comment]
具体某个图里面可以切换，点进有个专门的主题选择页xuan'ze'ye选择才这样的。。。

**Comment by Ovilia** [comment]
这是 ECharts 2 吗？2 已经不提供维护了，建议切换成 3
