### ISSUE TITLE
axisPointer下K线图tooltip 如何 独立显示; bar固定间隔并靠边对齐

### ISSUE THREAD

**Issue by biaowork** [apache/incubator-echarts#6748]
### One-line summary [问题简述]
K 线图 多个item的tooltip 如何独立显示，而不是综合到一起。

[官方demo:](http://echarts.baidu.com/gallery/editor.html?c=doc-example/candlestick-axisPointer) tooltip 是所有item 的tooltip 综合到一起了
希望 kline和 Volumn的tooltip 同时显示到自己item里

2/ 当K线数据较少时（比如只有3条），K线能不能实现 固定间隔，靠一边对齐（靠左或右，而不是当前的平均了整个坐标系的宽度）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:Chrome 60.0.3112.78（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:windows 10

### Expected behaviour [期望结果]

1、希望在trigger: 'axis'下 kline和 Volumn的tooltip 同时显示到自己item上（多个tooltip同时存在）
比如页面的 Volumn 和 MACD 的tooltip，像其他交易网站那样 同时显示在自己的item左上角？

2/ 当K线数据较少时（比如只有3条），K线实现 固定间隔，靠一边对齐（candlestick && bar)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
目前只能用多个 echarts 实例实现这个功能。
