### ISSUE TITLE
dataZoom minValueSpan 无效!!

### ISSUE THREAD

**Issue by liwenda122** [apache/incubator-echarts#6750]
### One-line summary [问题简述]
xAxis.type =time 时 dataZoom组件的minValueSpan 无效
设置1000（1秒）后 依然可以用滚轮无限放大图表

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.0
+ Browser version [浏览器类型和版本]:chrome 61.0.3163.100
+ OS Version [操作系统类型和版本]:windows 7 64

### Expected behaviour [期望结果]
minValueSpan设置后 可以限制最大缩放等级（现在设置1000毫秒后依然可以使用滚轮无限扩大)

### ECharts option [ECharts配置项]

参见 http://gallery.echartsjs.com/editor.html?c=xryos9eIi-&v=1

```javascript
option = {

}

```

### Other comments [其他信息]

参见 http://gallery.echartsjs.com/editor.html?c=xryos9eIi-&v=1

**Comment by DukeGJ** [comment]
没有无限放大啊，到达秒级的缩小之后再也缩小不了了，鼠标滑动会导致进度条往后移动
