### ISSUE TITLE
在使用 bmap 时标记信息取消显示经纬度值

### ISSUE THREAD

**Issue by dowhilenet** [apache/incubator-echarts#6761]
### One-line summary [问题简述]

在使用 bmap 时标记信息取消显示经纬度值。bmap 示例标记的数据显示会显示经纬度值，然后才是真正想要的值。

### Version & Environment [版本及环境]
+ ECharts version [3.0]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/10379476/30905656-03c5b5f6-a3a8-11e7-9667-40044036acf4.png)

只显示我真正需要的数据，不现实定位所需要的经纬度值

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/10379476/30905611-e98c0c44-a3a7-11e7-930d-6fbd36b5f9e4.png)

期望不显示经纬度值

**Comment by 100pah** [comment]
tooltip.formatter 中可自己定制。

**Comment by dowhilenet** [comment]
@100pah 
```
            tooltip:{
            	formatter:'{b}:{c}'
            	}
	}
```

参考[http://echarts.baidu.com/option.html#series-scatter.tooltip.formatter](http://echarts.baidu.com/option.html#series-scatter.tooltip.formatter)

经纬度依然存在。

**Comment by dowhilenet** [comment]
@100pah 
在 bmap 的 readme 中

```
    series: [{
        type: 'scatter',
        // 使用百度地图坐标系
        coordinateSystem: 'bmap',
        // 数据格式跟在 geo 坐标系上一样，每一项都是 [经度，纬度，数值大小，其它维度...]
        data: [ [120, 30, 1] ]
    }]
```
这里的 data 中，好像 经纬度和我的数据就是一个整体。
当我设置

```
tooltip:{
            	formatter:'{b}'
            	}
	}
```
经纬度和我需要的值一同都不显示了。
