### ISSUE TITLE
[Feature Request]漏斗图每一行能设置为长方形吗？

### ISSUE THREAD

**Issue by DanielWLam** [apache/incubator-echarts#6762]
目前的漏斗图，在关闭了排序后，每一行数据的宽度受下一行数据量的影响，实际呈现的效果具有比较大的误导性，比如

![image](https://user-images.githubusercontent.com/8369212/30915954-ca345162-a3ca-11e7-8230-3e551da95bcb.png)
如图所示，点击只有2%，展示数据量较大的情况下，让人误以为点击的数据可观，这在数据呈现上是违反了客观性原则的，如果改成柱形图，根据百分比进行排列的话，会更加合理

**Comment by 100pah** [comment]
为何要关闭排序呢，这样就不是漏斗了。

**Comment by DukeGJ** [comment]
echarts提供了堆叠的柱形图，你可以查看一下
另外data中的value都相同你可以看一下是什么效果 @DanielWLam

**Comment by DanielWLam** [comment]
![image](https://user-images.githubusercontent.com/8369212/30954074-61f6b5a8-a461-11e7-946a-6884e1c25e9f.png)

看了一下堆叠柱形图的demo，还是不是很符合想象中的模型，理想中的模型，应该柱形图支持position为center就能满足，而目前的position似乎要么左，要么右。理想中的漏斗模型，应该用宽度来表示每个环节的数据情况，上面的漏斗图如果每一行是长方形的话，也就是我说的那种居中柱形图就挺好的，不知道这样的需求是否有实现的难点，

**Comment by Ayana7** [comment]
![image](https://user-images.githubusercontent.com/31950477/32541324-53187710-c4aa-11e7-8a73-679af0a0965e.png)
请问这种需要怎么处理

**Comment by Ovilia** [comment]
@Ayana7 http://echarts.baidu.com/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E5%88%97 可以尝试使用自定义系列实现
