### ISSUE TITLE
Uncaught TypeError: Cannot read property 'calculable' of null

### ISSUE THREAD

**Issue by yhw601071569** [apache/incubator-echarts#6766]
### One-line summary [问题简述]
出现Uncaught TypeError: Cannot read property 'calculable' of null， 但是我的series中data有值，

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 2.27
+ Browser version [浏览器类型和版本]: 59.0.3071.115
+ OS Version [操作系统类型和版本]: win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
@yhw601071569 贴一下代码
