### ISSUE TITLE
对于数据差值较大，导致显示图形很丑的问题

### ISSUE THREAD

**Issue by yliu1993** [apache/incubator-echarts#6767]
比如柱形图，当差值过大时会出现一柱擎天的感觉，

请问什么适合做数据值差距很大的图例呢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
@@@你可以做比例缩放，比如你的一个柱形图1000，另一个1，你可以把柱形图1000的缩放在值保持为100，提示工具还显示1000

**Comment by yliu1993** [comment]
@DukeGJ 首先非常感谢，其实柱形图只是例子，如果换成是饼图呢，应该怎么解决

**Comment by DukeGJ** [comment]
图表只是直观的对比数据，对于差距过大的数据，本身就应该在图表里反应出来，反应的结果就是一个部分非常小，一个部分非常大。拿饼图来讲，只有2部分，一部分占比99.9999%,另一个占比0.0001%，任意一个图表都会表现出相差过大，如果你调整了显示的比例，那么查看图表的人就会想当然的认为这两个其实相差也不大。所以面对这种情况，要么直接在图表上标注出来，要么在其他位置上标注出来。 @yliu1993

**Comment by jiehwa** [comment]
@Ovilia Hi,Echarts针对这个普遍的共性问题有什么解决方案吗？

**Comment by Ovilia** [comment]
如果是柱状图、折线图之类的，推荐 log 轴（通过 [yAxis.type](http://echarts.baidu.com/option.html#yAxis.type) 设置为 `'log'`）；如果是饼图，赞同 @DukeGJ 的说法，ECharts 可以通过 [minAngle](http://echarts.baidu.com/option.html#series-pie.minAngle) 设置最小的扇形角度。

**Comment by xingaa** [comment]
> 如果是柱状图、折线图之类的，推荐 log 轴（通过 [yAxis.type](http://echarts.baidu.com/option.html#yAxis.type) 设置为 `'log'`）；如果是饼图，赞同 @DukeGJ 的说法，ECharts 可以通过 [minAngle](http://echarts.baidu.com/option.html#series-pie.minAngle) 设置最小的扇形角度。

如果使用log，值为1或小于1时会直接无高度，非常影响美观

**Comment by illust** [comment]
柱图可以试试barMinHeight

**Comment by xzt246679** [comment]
@Ovilia 折线图如果带负数的话，那么无法使用对数轴，这种情况应该怎么处理，{8000，8000，8000，8000},{100，100，100},{-5，-15，-9} 例如3条数据，如何像对数轴一样可看出差距？
