### ISSUE TITLE
发现Echarts绘制的折线图虚化严重，应该是设置的抗锯齿功能引起的，如何关闭抗锯齿的功能呢？

### ISSUE THREAD

**Issue by dongsir** [apache/incubator-echarts#6770]
### One-line summary [问题简述]

Echarts绘制的折线图虚化严重，应该是设置的抗锯齿功能引起的，如何关闭抗锯齿的功能呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

能有开关关闭抗锯齿的功能

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

https://pan.baidu.com/s/1i4ANHyP

**Comment by dongsir** [comment]
@pissang  你好!
anti-aliasing 这个是如何设置的呢？ 没找到对应的设置属性
这里提到过： #4431   https://github.com/ecomfe/echarts/issues/4431

**Comment by Ovilia** [comment]
请在 http://gallery.echartsjs.com/editor.html 复现下，并说明什么情况下发现虚化？
