### ISSUE TITLE
一个页面绘制多个图表，加载速度太慢

### ISSUE THREAD

**Issue by zhang122622623** [apache/incubator-echarts#6773]
### One-line summary [问题简述]
    在一个页面中绘制14个图表，每个图表中最多720个点，绘图时间太长，每次初始化在chrome或firefox中都需要4-5秒；连续切换页面浏览器还会卡死，崩溃；
     想知道有什么办法能够减少绘图时间。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版
+ Browser version [浏览器类型和版本]:  chrome、firefox
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
  减少绘图时间， 在1到2秒间完成图表的绘制

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能否给出具体的版本，浏览器，操作系统环境？

**Comment by zhang122622623** [comment]
echarts: 3.6.2;
浏览器：chrome 51/firefox 55；
操作系统：win7;
  ps:  在另外一个页面只展示一个图表，图表中最多七条线（散点图），每条最多720个点；七条线完全加载也要3-4秒，已经关闭了动画，配置与上面相同；
