### ISSUE TITLE
y轴axisLabel的showMinLabel问题

### ISSUE THREAD

**Issue by liihuu** [apache/incubator-echarts#6783]
### One-line summary [问题简述]
echarts从3.7.1升级到3.7.2后，y轴的axisLabel showMinLabel属性设置为false，发现y轴最小值的那个tick线没有了，3.7.1的版本是显示的，请问本意就是这样设计么？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
最大最小值的那个tick线自己控制显示隐藏

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
是有意设计的，不显示标签文字的时候就不显示 tick
