### ISSUE TITLE
yaxis not showing full text 

### ISSUE THREAD

**Issue by aladdinfyp** [apache/incubator-echarts#6785]
### One-line summary [问题简述]
![githubqn]

我用了e'charts的bar，但我的graph, yaxis 好奇怪，yaxis 的名字被裁剪.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

javascript, java & echarts

### Expected behaviour [期望结果]

yaxis 的名字应该不会被裁剪啊

### ECharts option [ECharts配置项]

```javascript
option = {

}

```
  var myChartBar = echarts.init(document.getElementById('echart_bar_horizontal'), theme);
            
            var referralName = [];
            var referralDataList = [];
            <%  ReferralDAO referraldao = new ReferralDAO();
                List<Referral> referralList = referraldao.retrieveAllReferral();

                //ArrayList<String> redemptionTest= new ArrayList<String>();
                HashMap<String, Integer> referralMap = new HashMap<>();
                for (Referral referral : referralList) {
                    String referralName = referral.getEmail();
                    Integer val = referralMap.get(referralName);
                    if (val != null) {
                        val = val + 1;
                        referralMap.put(referralName, val);
                    } else {
                        referralMap.put(referralName, 1);
                    }
                }

                //keys
                Set referralKeySet = referralMap.keySet();
                int numOfReferral = referralKeySet.toArray().length;
                //create the array
                String[] referralName = new String[numOfReferral];
                int[] referralDataList = new int[numOfReferral];
                String referralname = "";
                int counter = 0;
                Iterator iterator = referralKeySet.iterator();
                while (iterator.hasNext()) {
                    referralname = (String) iterator.next();
            %>

            referralName.push("<%= referralname%>");
            referralDataList.push("<%= referralMap.get(referralname)%>");

            <%
                    counter++;
                }

            %>

            myChartBar.setOption({
                tooltip: {
                    trigger: "axis"
                },
                legend: {
                    data: ["Number of Referrals"]
                        
                },
                toolbox: {
                    show: !0,
                    feature: {
                        saveAsImage: {
                            show: !0
                        }
                    }
                },
                calculable: !0,
                xAxis: [{
                        type: "value",
                        boundaryGap: [0, .1]
                    }],
                yAxis: [
                    {
                        type: "category",
                        data: referralName
                        
                    }],
                series: [
                    {
                        name: "Number Of Referral",
                        type: "bar",
                        data: referralDataList
                  }]
            });

### Other comments [其他信息]

![githubqn](https://user-images.githubusercontent.com/29227309/31023984-2c41477e-a570-11e7-9c28-0b7381e30877.PNG)

**Comment by jqwang521** [comment]
试试设置**grid.containLabel: true**
或调整**grid.left**
参考[http://echarts.baidu.com/option.html#grid.containLabel](url)

**Comment by DukeGJ** [comment]
y轴文字太长了，你可以调整y轴text的大小来规避，或者可以考虑text换行，再不然可以缩小一下图表大小
或者参考这个：http://echarts.baidu.com/option.html#yAxis.nameGap
