### ISSUE TITLE
Gradient Line DEMO – How to to hide one of them? 

### ISSUE THREAD

**Issue by zilahir** [apache/incubator-echarts#6790]
I am trying to use the gradien line chart demo was provided in the documentation. 

Why does it show 2 chars?? Gradients X and Y axes.

I just want one, but somehow this options defines 2: 

`var optionForLineChart = {

                  // Make gradient line here
                  visualMap: [{
                      show: false,
                      type: 'continuous',
                      seriesIndex: 0,
                      min: 0,
                      max: 400
                  }, {
                      show: false,
                      type: 'continuous',
                      seriesIndex: 1,
                      dimension: 0,
                      min: 0,
                      max: dateList.length - 1
                  }],

                  title: [{
                      left: 'center',
                      text: 'Gradient along the y axis'
                  }, {
                      top: '55%',
                      left: 'center',
                      text: 'Gradient along the x axis'
                  }],
                  tooltip: {
                      trigger: 'axis'
                  },
                  xAxis: [{
                      data: dateList
                  }, {
                      data: dateList,
                      gridIndex: 1
                  }],
                  yAxis: [{
                      splitLine: {show: false}
                  }, {
                      splitLine: {show: false},
                      gridIndex: 1
                  }],
                  grid: [{
                      bottom: '60%'
                  }, {
                      top: '60%'
                  }],
                  series: [{
                      type: 'line',
                      showSymbol: false,
                      data: valueList
                  }]
              };`

i wasnt able to find what declares the second chart? 

<img width="660" alt="screen shot 2017-10-02 at 2 35 17" src="https://user-images.githubusercontent.com/6687149/31060332-630db26e-a71a-11e7-9d98-620d91506f99.png">

as the screenshot show, i have to charts, the upper one gets the data correctly., how can i hide the 2nd one? thats totally useless, i dont want 2 charts for the same data set. 

Could anyone help me out? Thanks!

**Comment by Ovilia** [comment]
You can set the `gridIndex` to be `1` for another series.
