### ISSUE TITLE
brush选框能否自定义删除其中一个选框

### ISSUE THREAD

**Issue by chaserstrong** [apache/incubator-echarts#6807]
echarts本身似乎只提供了一个全部清除的clear功能。 想问代码中能否实现，对某个选框，进行删除，修改样式的功能？

**Comment by chaserstrong** [comment]
另外我用的是最新的版本。发现已经能支持line的很多功能了。 但是就像
Duplicate of #4021 这提到的，似乎line图里还无法获取选框的内容。

**Comment by chaserstrong** [comment]
@pissang 麻烦看下，谢谢~

**Comment by 100pah** [comment]
其实是可以控制的，参见：<http://echarts.baidu.com/api.html#action.brush.brush>

**Comment by chaserstrong** [comment]
@100pah 谢谢，链接确实能实现删除或者添加某个选框的需求，只是似乎每次都要对全部选框进行修改~
ps：line图似乎就是无法获取到当前鼠标点击到哪个选框的，brushselected事件中返回的dataIndex值是空的，bar图我试了下可以。 
![image](https://user-images.githubusercontent.com/18061322/31424156-4c2d49ba-ae8b-11e7-83f6-a7b6b27b5df8.png)
我尝试看了下源码，图中默认直接设置了dataIndex值为[]，但是我一直无法定位到bar是走的那个方法。
![image](https://user-images.githubusercontent.com/18061322/31424294-f53ca230-ae8b-11e7-827e-d1de0133836a.png)

**Comment by 100pah** [comment]
line 图暂时没有支持brush。这个 `brush` action 确实是个全量更新接口，每次都要设置所有的选框。

**Comment by chaserstrong** [comment]
嗯嗯，我就是想说，能提供一点思路我自己修改下源码嘛？
