### ISSUE TITLE
series中多个 tooltip 的 触发类型与内容能否实现 自定义？

### ISSUE THREAD

**Issue by zhang122622623** [apache/incubator-echarts#6814]
### One-line summary [问题简述]
 在一个series中有多个tooltip, 想对每一个tooltip进行触发类型和内容的自定义；
 内容的自定义没有问题，但是series.tooltip触发类型无法设置为'axis'；
  echarts官方文档中显示：
       “ 注意：series.tooltip 仅在 tooltip.trigger 为 'item' 时有效。”

 如果在setOption里的tooltip中设置为‘axis’，则会应用在所有的数据中，并且也没办法实现内容的自定义；这样的问题该怎么处理呢？

  

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts: 3.6.2;
浏览器：chrome 51/firefox 55；
操作系统：win7;

### Expected behaviour [期望结果]

    series中每一个tooltip都能自定义触发类型和内容

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
在坐标系层级，也可以定义 `tooltip.trigger`，`grid.tooltip.trigger = 'axis'`

**Comment by zhang122622623** [comment]
@100pah      在grid里面定义的tooltip也是应用在series里面所有的tooltip上面啊，这和在setOption里设置是一样的效果啊；有办法对series的每一个tooltip设置它自己的trigger吗？

**Comment by Janka55** [comment]
遇到同样问题了，求方案
