### ISSUE TITLE
误差线

### ISSUE THREAD

**Issue by AlanYiNew** [apache/incubator-echarts#6818]
### One-line summary [问题简述]

有支持误差线的功能吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
目前不支持，可以给个效果图吗？
