### ISSUE TITLE
请问地图下载还会恢复吗？

### ISSUE THREAD

**Issue by kidddfu** [apache/incubator-echarts#6821]
### One-line summary [问题简述]

如果会，什么时间能恢复？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jingsam** [comment]
应该不会恢复了，可以到这里下载：
https://github.com/ecomfe/echarts/tree/master/map

**Comment by chfw** [comment]
213 Countries, 28 Chinese provinces and 363 Chinese cities -> https://chfw.github.io/jupyter-echarts/
