### ISSUE TITLE
stacked area chart to include negative values in the stack.

### ISSUE THREAD

**Issue by chienleng** [apache/incubator-echarts#6830]
### One-line summary [问题简述]
stacked area chart to include negative values in the stack.

### Version & Environment [版本及环境]
echarts v3

### Expected behaviour [期望结果]
The stacked area chart should take the negative values and add to the positive values (in turn, the positive stacked area should be lowered)

### Other comments [其他信息]
<img width="107" alt="stacked-area" src="https://user-images.githubusercontent.com/349944/31583211-57ae956e-b1e2-11e7-91ff-fcaf804a3112.png">

**Comment by corradio** [comment]
+1

**Comment by garyfrost** [comment]
+1
