### ISSUE TITLE
Echarts3 怎么设置部分地图不可点击

### ISSUE THREAD

**Issue by catnoodle** [apache/incubator-echarts#6847]
### One-line summary [问题简述]
要怎么才能在使用series的type:map和联合visualMap的情况下设置没有上色的部分地图区域不可点击？
![image](https://user-images.githubusercontent.com/32472841/31623122-783295a8-b26c-11e7-8258-defbee73ae2a.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: windows 10

### Expected behaviour [期望结果]
没着色的地方不可以点击

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by rubbishquan** [comment]
这个是js问题，不是echarts的。要实现的话写个if判断一下。

**Comment by catnoodle** [comment]
@rubbishquan 请问一下具体怎么操作？小白不懂TAT

**Comment by rubbishquan** [comment]
@catnoodle 可点击的地区定义一个数组，foreach这个数组，if判断点击事件的params.name等不等于foreach的value，如果不等于就弹个信息框提示一下不可点击之类的。

**Comment by catnoodle** [comment]
@rubbishquan 这个我试过了，但是echart的onclick已经触发了，不可点击区域已经是选中状态了然后再弹窗说不能点击， 感觉很怪

**Comment by chenyumiao** [comment]
设置silent:true，可以不触发鼠标响应事件，不过是针对整个地图的

**Comment by Ovilia** [comment]
可以将 emphasis 样式设为默认样式

**Comment by Ovilia** [comment]
怎么控制？

**Comment by 799535610** [comment]
@Ovilia   emphasis 样式设为默认样式 ,  mouseover等鼠标还是手型， 所以问下是否有控制鼠标的选项

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-graph.cursor 有是有，但是只能控制整体的，不能控制单个的。

**Comment by 799535610** [comment]
@Ovilia 多谢，部分不可点击通过 绑定事件dispatchAction 的 mapUnSelect 迂回解决了， 鼠标通过 event.target 解决了

**Comment by alabihula** [comment]
> @Ovilia 多谢，部分不可点击通过 绑定事件dispatchAction 的 mapUnSelect 迂回解决了， 鼠标通过 event.target 解决了

哈喽能否列下代码
