### ISSUE TITLE
如何只显示地图map的绘制区域,以外的区域和以外的markpoint都不显示

### ISSUE THREAD

**Issue by lididi** [apache/incubator-echarts#6850]
### One-line summary [问题简述]
已实现:
①地图下钻至三级(市级地图)
②markPoint标记数据的位置

目前问题:
①由于项目里的返回车辆数据,只含有lng和lat,没有指明车辆是在哪一个城市的.
②因此下钻的时候,前端根据经纬度也不知道"车辆是在哪一个城市的".例如下钻到**"佛山市"**,会出现 理应该在"广州市"的车辆数据
<img width="400" alt="default" src="https://user-images.githubusercontent.com/32474320/31646290-a80e7c2a-b333-11e7-90fc-0d8b4ff83cf3.png">
<img width="400" alt="default" src="https://user-images.githubusercontent.com/32474320/31646292-ac3fa59e-b333-11e7-8e3f-fd0368453dc1.png">
<img width="400" alt="default" src="https://user-images.githubusercontent.com/32474320/31646735-3b559660-b336-11e7-9ad6-1fe699092bb1.png">

拟计划三种解决方案:
①射线法 (判断点落在区域上)
②百度逆地图编译API  (判断点在哪个市区)
③ 让地图map只显示绘制的部分,绘制以外的区域都不显示
由于以后车辆数据会更多,估计③是更加靠谱的方法

### Expected behaviour [期望结果]
下钻到某个城市, 只显示该城市的绘制地图以及以内的markpoint标记,地图以外的区域和markpoint都不显示.
<img width="503" alt="default" src="https://user-images.githubusercontent.com/32474320/31646301-b49921f2-b333-11e7-929f-812b09be845d.png">

@pissang

**Comment by rubbishquan** [comment]
@lididi http://api.map.baidu.com/lbsapi/getpoint/index.html百度和高德有类似的坐标查询api，通过经纬度确定省市区，用地区分好类之后再根据省市，用函数来控制点的显示。
