### ISSUE TITLE
我用demo画echart折线图没有问题，但是在路由环境下图画不出来

### ISSUE THREAD

**Issue by DickLicha** [apache/incubator-echarts#6858]
我用的echarts版本是3.7.2，跑demo程序折线图能绘制出来。当我引入到项目中（angularjs1.7，在路由界面）的时候canvas没法把图形界面渲染出来。进入调试模式查看的时候，我发现项目跟测试对比起来少了一个div，这个div是echarts绘制图形的吗？请问这个问题怎么解决

![image](https://user-images.githubusercontent.com/21870645/31698863-3c99cf52-b3f2-11e7-99b5-d859cd7a2c27.png)

**Comment by DickLicha** [comment]
![image](https://user-images.githubusercontent.com/21870645/31698924-8af136cc-b3f2-11e7-969f-9426a330d3a9.png)
这个是没有huizhi绘制出折线图的代码

**Comment by linjinxuan** [comment]
哈喽 你解决这个问题了吗？
