### ISSUE TITLE
graph关系图 太密看不清问题

### ISSUE THREAD

**Issue by sunscheung** [apache/incubator-echarts#6865]
Graph关系图展示太密 [问题简述]
关系图中，type为none， data中 x、y属性程序有规律生成，当某一列节点太多（x相同，y递增）
图中节点和线就会聚集在一起，看不清
![image](https://user-images.githubusercontent.com/9931345/31752660-9c7cb4a8-b4be-11e7-810c-c7cbb54b5cad.png)

Version & Environment [版本及环境]

ECharts version [3.7.2]:
Browser version [版本 59.0.3071.115（正式版本） （64 位）]:
OS Version [win7旗舰版(64位)(6.1，版本7600)]:

Expected behaviour [期望结果]

能够向节点少的这样，比较清楚，如：
 
![image](https://user-images.githubusercontent.com/9931345/31752681-bde8ef76-b4be-11e7-90cb-a8f3be004c50.png)

ECharts option [ECharts配置项]
//主要节点数据如下
option = {
    title: {
        text: 'Graph 简单示例'
    },
    tooltip: {},
    animationDurationUpdate: 1500,
    animationEasingUpdate: 'quinticInOut',
    series : [
        {
            type: 'graph',
            layout: 'none',
            symbolSize: 50,
            roam: true,
            label: {
                normal: {
                    show: true
                }
            },
            edgeSymbol: ['circle', 'arrow'],
            edgeSymbolSize: [4, 10],
            edgeLabel: {
                normal: {
                    textStyle: {
                        fontSize: 20
                    }
                }
            },
            data: [{
                name: '节点111',
                x: 300,
                y: 100
            },{
                name: '节点1111',
                x: 300,
                y: 300
            },{
                name: '节点11111',
                x: 300,
                y: 500
            },{
                name: '节点111111',
                x: 300,
                y: 700
            },{
                name: '节点1111111',
                x: 300,
                y: 900
            },{
                name: '节点11111111',
                x: 300,
                y: 1100
            },{
                name: '节点111111111',
                x: 300,
                y: 1300
            },{
                name: '节点1111111111',
                x: 300,
                y: 1500
            },{
                name: '节点11111111111',
                x: 300,
                y: 1700
            },{
                name: '节点111111111111',
                x: 300,
                y: 1900
            },{
                name: '节点1111111111111',
                x: 300,
                y: 2100
            },{
                name: '节点11111111111111',
                x: 300,
                y: 2300
            },{
                name: '节点111111111111111',
                x: 300,
                y: 2500
            },{
                name: '节点2222111111111111111',
                x: 300,
                y: 2700
            },{
                name: '节点222111111111111111',
                x: 300,
                y: 2900
            },{
                name: '节点22111111111111111',
                x: 300,
                y: 3100
            },{
                name: '节点2111111111111111',
                x: 300,
                y: 3300
            }, {
                name: '节点2',
                x: 800,
                y: 300
            }, {
                name: '节点3',
                x: 550,
                y: 100
            }, {
                name: '节点4',
                x: 550,
                y: 500
            }],
            // links: [],
            links: [{
                source: 0,
                target: 1,
                symbolSize: [5, 20],
                label: {
                    normal: {
                        show: true
                    }
                },
                lineStyle: {
                    normal: {
                        width: 5,
                        curveness: 0.2
                    }
                }
            }, {
                source: '节点2',
                target: '节点1',
                label: {
                    normal: {
                        show: true
                    }
                },
                lineStyle: {
                    normal: { curveness: 0.2 }
                }
            }, {
                source: '节点1111',
                target: '节点3'
            },{
                source: '节点111',
                target: '节点3'
            }, {
                source: '节点2',
                target: '节点3'
            }, {
                source: '节点2',
                target: '节点4'
            }, {
                source: '节点1',
                target: '节点4'
            }],
            lineStyle: {
                normal: {
                    opacity: 0.9,
                    width: 2,
                    curveness: 0
                }
            }
        }
    ]
};
Other comments [其他信息]

**Comment by sunscheung** [comment]
@leeight @cnberg @firede @chriswong @firedfox 
问题描述如有不清的地方，告知我，我会及时修改

**Comment by CapDuan** [comment]
@sunscheung 尝试修改symbolSize 以及结点坐标。将结点变小，y的递增值改大，字体改小。

**Comment by sunscheung** [comment]
@CapDuan    试了你的建议,，y增值变大。【x和y是相关联的，一并调整了】，效果还是不理想。如图：
![image](https://user-images.githubusercontent.com/9931345/31755709-75681ed4-b4d2-11e7-8d9f-788b6715bd89.png)

**Comment by CapDuan** [comment]
@sunscheung 

![default](https://user-images.githubusercontent.com/22721525/31756778-63b951fc-b4d8-11e7-968c-616fd390829d.png)
对应数值改一下，可以参考官方的graph[文档](http://echarts.baidu.com/option.html#series-graph)

**Comment by sunscheung** [comment]
@CapDuan  thank you ！  效果确实好了一些
