### ISSUE TITLE
在ecahrts-gl三维中国地图中没有南沙诸岛

### ISSUE THREAD

**Issue by xuyang198711** [apache/incubator-echarts#6866]
你好，最近在制作中国三维地图，发现引入的http://gallerybox.echartsjs.com/dep/echarts/map/js/china.js中没有南沙诸岛，由于是严肃主权问题，必须要有南沙诸岛，请问是否可以修改china.js？

这种仅仅展示中国地图的方式，南沙群岛应该是没有geo数据的，应该是程序中单独处理加上去的，echarts的普通地图中是有的，3d的没有，应该是忘记加上去了吧？

![image](https://user-images.githubusercontent.com/10275541/31800894-dab87d70-b576-11e7-8185-82d8595db690.png)

![image](https://user-images.githubusercontent.com/10275541/31800907-f49ef372-b576-11e7-951e-ce1710f0e200.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jingsam** [comment]
你这么一提醒，作者可能会把整个map文件夹删了，凡是涉及到国界的问题都是得严重的问题

**Comment by chfw** [comment]
哪里去寻找相关数据呢？我们可以加上去

**Comment by xuyang198711** [comment]
你好。这种只显示中国地图的，南沙诸岛应该只是一个图例，是程序单独加上去的吧？   
echarts的二维地图中就有的，三维的没有？你是echarts开发者么？能加上去么？
请看图示：
![image](https://user-images.githubusercontent.com/10275541/31801291-a82436da-b579-11e7-8545-8047aa9222cc.png)
![image](https://user-images.githubusercontent.com/10275541/31801296-b2312d72-b579-11e7-9b92-db3962ab269e.png)

**Comment by wuqi** [comment]
@chfw   http://www.webmap.cn/commres.do?method=result100W  可以下1:100万的公开数据,里面有,也有审图号：GS（2016）2556号

**Comment by chfw** [comment]
@wuqi 不能下载，订单系统出错

![screen shot 2017-10-24 at 09 18 39](https://user-images.githubusercontent.com/4280312/31931899-884775ea-b89c-11e7-983d-587ddf69d6f0.png)

**Comment by wuqi** [comment]
我周末才下了的啊,又坏了?  @chfw 要不留个邮箱,等晚上回去给你?有点大,不过你如果只要省的数据倒是还不算很大

**Comment by chfw** [comment]
wangc_2011@hotmail.com @wuqi

**Comment by webxmsj** [comment]
结论是什么？ 用户自己加吗？ 怎么加？
