### ISSUE TITLE
如何Echarts 折线图的线条尽头出现名称

### ISSUE THREAD

**Issue by viano2017** [apache/incubator-echarts#6870]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/31052753/31801853-5dd36e58-b57d-11e7-84d4-0fd509dca2cc.png
![10](https://user-images.githubusercontent.com/31052753/31801868-74e2dcc8-b57d-11e7-81b6-6f3d9d86a776.jpg)
![qq 20171020095955](https://user-images.githubusercontent.com/31052753/31801874-7b6b8428-b57d-11e7-8c59-2d7a20e734ae.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ Oon [操作系统类型和版本]:

[](url)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这个好像没办法实现
