### ISSUE TITLE
如何对折线图的整个内容进行整体缩小?而整体的内容不会减少。

### ISSUE THREAD

**Issue by shanewds** [apache/incubator-echarts#6879]
1>主要我一改变整体的div的大小，虽然显示的折线图变小了，但是内容显示就不完整.
如何解决?
2>源码如下
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="js/echarts.js"></script>
</head>
<body>
    
    <div id="main" style="width:600px;height:400px;"></div>
    <script type="text/javascript">
    
     /*   function myrefresh()
        {
        window.location.reload();
        }
        setTimeout('myrefresh()',3000); //指定几秒刷新一次*/

        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
    var option = {
               title: {
               text: ''
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
       data:['1H','2H','3H','4.1H','4.2H','5.1H','5.2H','6.1H','6.2H','7.1H','7.2H','8.1H','8.2H']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
           
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data : ['9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'1H',
            type:'line',
            stack: '总量',
            data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'2H',
            type:'line',
            stack: '总量',
            data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
            name:'3H',
            type:'line',
            stack: '总量',
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'4.1H',
            type:'line',
            stack: '总量',
            data:[320, 332, 301, 334, 390, 330, 320]
        },
        {
            name:'4.2H',
            type:'line',
            stack: '总量',
            data:[820, 932, 901, 934, 1290, 1330, 1320]
        },
         {
            name:'5.1H',
            type:'line',
            stack: '总量',
            data:[112, 224,, 234,256,357,388]
        },
        {
            name:'5.2H',
            type:'line',
            stack: '总量',
            data:[321,423,412,400,355,367,498]
        },
        {
            name:'6.1H',
            type:'line',
            stack: '总量',
            data:[287,354, 238,290,280,275,284]
        },
        {
            name:'6.2H',
            type:'line',
            stack: '总量',
            data:[375,334,356,321,378,442,765]
        },
        {
            name:'7.1H',
            type:'line',
            stack: '总量',
            data:[776,789,874,856,888,890,900]
        },
          {
            name:'7.2H',
            type:'line',
            stack: '总量',
            data:[489,512,524, 564,570,580,679]
        },
        {
            name:'8.1H',
            type:'line',
            stack: '总量',
            data:[567,768,870,900,891,916,998]
        },
        {
            name:'8.2H',
            type:'line',
            stack: '总量',
            data:[678,690,700,666, 954,1110,1200]
        }
    ]
};

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
</body>
</html>

**Comment by 100pah** [comment]
需要在缩小的时候调用 myChart.resize()，则能重设图表的大小
