### ISSUE TITLE
tooltip位置错乱，或者不显示

### ISSUE THREAD

**Issue by mathcoder23** [apache/incubator-echarts#6890]
### One-line summary [问题简述]
tooltip位置错乱，或者不显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.1
+ Browser version [浏览器类型和版本]:60.0.3112.113(32位)
+ OS Version [操作系统类型和版本]:
win7

### Expected behaviour [期望结果]
tooltip跟随鼠标显示

### ECharts option [ECharts配置项]

```javascript
option={
                title: { text: '' },
                tooltip: {},
                xAxis: {
                    data: []
                },
                yAxis: {},
                series: []
            }

```
>代码很多就不贴了，syncOption是在一个异步请求之后再设置的，但始终tooltip都无法友好跟随鼠标，我在页面加载的时候加载上面的option,然后在异步设置option，tooltip就能够正常，我的开发环境是vue+element，我猜测是tooltip的初始化有bug。

**Comment by pissang** [comment]
能否具体描述你的问题？

**Comment by wuranhw** [comment]
我的也是tootip异步请求的问题，就是找不到原因，悬浮框的数据来源于异步调用后台请求，但是鼠标放上去能够得到期望的数据，可是F12观测Network发现多次调用异步网络请求。。。太敏感了，动一下鼠标，一大堆请求。。 @pissang

**Comment by wuranhw** [comment]
另外请大神关注一下这个问题，就是上面我评论的那个问题 @pissang “echarts3.7.2版本在使用graph组件时tooltip的formatter进行异步数据请求发出多次http请求”
