### ISSUE TITLE
echart可以设置处理多少数据后暂停一下让出CPU给前端以响应鼠标动作吗？

### ISSUE THREAD

**Issue by wuminbin** [apache/incubator-echarts#6906]
### One-line summary [问题简述]
需要处理大量数据和逐步生成多个图，希望在第一个图出来时就可以响应鼠标事件，但实际情况是CPU占用过高而出现卡顿。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.3
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Mac

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个在计划里
