### ISSUE TITLE
图表渲染问题

### ISSUE THREAD

**Issue by Chasen-Zhang** [apache/incubator-echarts#6912]
### One-line summary [问题简述]
窗口切换，折线图表会消失。好像没有resize（）的那种感觉。这个bug很难测出来，是做新的谷歌浏览器上出现的问题，切换谷歌浏览器是切换走在切换回来。不知道是win10系统的bug还是echarts本事的bug，或者是谷歌浏览器的bug，谷歌浏览器版本 63.0.3236.0（正式版本） （64 位），我到官网上的实例去演示，也会出现bug，但是其他同事的浏览器又不会出现，今天我测了一下又不会。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts-3.5.2
+ Browser version [浏览器类型和版本]:谷歌浏览器版本 63.0.3236.0（正式版本） 
+ OS Version [操作系统类型和版本]:win10（10.0，版本10240）

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hanfengcan** [comment]
我的是图表内容全部消失了.不过把鼠标放过去tooltip还是会出现.resize后就显示了

谷歌浏览器,猎豹都会出现.页面不动他,放久了就会出现这情况.

如果是饼图,鼠标移动过去就会显示.

Windows10

**Comment by DukeGJ** [comment]
好像有人监控过，假如把一个页面放的久了，占用内存会越来越大直到崩溃，具体解决办法还没看到

**Comment by hanfengcan** [comment]
@DukeGJ 难道要写个定时器定时resize ....

**Comment by Chasen-Zhang** [comment]
但是页面也没放多久啊，tooltip会出来，应该不是占用内存的问题。
