### ISSUE TITLE
多图表定时渲染问题

### ISSUE THREAD

**Issue by since91** [apache/incubator-echarts#6917]
### One-line summary [问题简述]
一个页面中含有多个图表，并使用定时任务使用ajax获取数据，渲染图表。然后内存不断增高，这该如何解决。图表有饼图、柱图、折线图
下面是从网上查到的资料
http://blog.csdn.net/tqtiwvfdn/article/details/46313547

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:chrome 64.0.3251.0
+ OS Version [操作系统类型和版本]:win7 64位

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
描述下你项目具体是怎么样的？是否是项目中其它代码的问题？
