### ISSUE TITLE
Cannot read property 'getModel' of undefined

### ISSUE THREAD

**Issue by Lacorda** [apache/incubator-echarts#6923]
### One-line summary [问题简述]

echarts/lib/util/graphic.js，774行
var gTextStyleModel = ecModel || ecModel.getModel('textStyle')

ecModel为false，ecModel.getModel肯定报错,
ecModel为true，ecModel.getModel('textStyle')也不会执行
这里是否应该把||改成&& ？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   3.7.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
是哪里执行了这个方法？
