### ISSUE TITLE
怎样为关系图中的节点添加动态涟漪效果

### ISSUE THREAD

**Issue by zhiyouai** [apache/incubator-echarts#6926]
如题，想要在关系图中为一些重要节点添加动画效果，在能够获取节点坐标的情况下如何实现该效果？使用effectScatter可以实现吗？尝试了很长时间都没有成功

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
setOption 更新数据

**Comment by DukeGJ** [comment]
http://echarts.baidu.com/option.html#series-graph.animation

**Comment by zhiyouai** [comment]
不好意思，我已开始没描述清楚，我是想给关系图中的节点添加散点图中的那种涟漪或者类似效果

**Comment by pissang** [comment]
暂时不行，可以试下自己用自定义图形去实现动画效果

**Comment by zhiyouai** [comment]
您的意思是说，目前的配置项还不支持直接在关系图中为节点增加动画效果是吧，而您所说的自定义图形具体是指什么呢？

**Comment by 961900832** [comment]
effectScatter 是可以的，我在行情图下用 effectScatter ，将 data 设置好后效果是可以实现的。
![image](https://user-images.githubusercontent.com/19699561/32481701-7e8ab6d2-c3cf-11e7-99b6-e3a1742c4195.png)

**Comment by houx15** [comment]
也可以采取多图的方式，覆盖一个effectScatter在上面
