### ISSUE TITLE
讨论：通过echarts能不能实现这样的图

### ISSUE THREAD

**Issue by denlaku** [apache/incubator-echarts#6929]
画了一个样图：
https://github.com/denlaku/react-view/blob/master/2017-10-31_222500.png
展示不同品牌的平板，在各个尺寸、各个月的销量
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by realeve** [comment]
这里类似于 Tableau的布局，目前暂时可以用以下思路：
1.假设7寸、8寸、9寸从左至右分别是A/B/C三组数据
2.A设置Y轴标签和lengend，B/C隐藏这两部分数据。
3.A/B/C的Y轴最大值手动计算。
4.布局用css实现

以下是其中一段的DEMO：
`let series = [{
        name: '苹果',
        type: 'bar',
        stack: 'test',
        data: [320, 332, 30]
    },
    {
        name: '小米',
        type: 'bar',
        stack: 'test',
        data: [120, 132, 101]
    }
];

function getMaxValue() {
    let max = 0;
    let arr = [];
    arr = JSON.parse(JSON.stringify(series[0].data));
    arr.forEach((item, j) => {
        for (let i = 1; i < series.length; i++) {
            arr[j] += series[i].data[j];
        }
    })
    arr.forEach(item => {
        max = Math.max(item, max);
    })
    console.log(max);
    return Math.ceil(max / 100) * 100;
}

option = {
    tooltip: {},
    legend: {
        data: ['苹果', '小米']
    },
    grid: {
        containLabel: true
    },
    xAxis: [{
        type: 'category',
        data: ['周一', '周二', '周三']
    }],
    yAxis: [{
        type: 'value',
        max:getMaxValue()
    }],
    series
};`

**Comment by nspers** [comment]
官方例子里有这样的柱状图
