### ISSUE TITLE
移动端K线图下方柱状图有数据不显示

### ISSUE THREAD

**Issue by upupday** [apache/incubator-echarts#6937]
### One-line summary [问题简述]
采用最新版echarts官方示例 ，k线图下方柱状图数据不显示，官方演示地址：http://echarts.baidu.com/demo.html#candlestick-touch
修改示例代码如下：
修改第一处：
  原示例代码var data = [[17512.58,17633.11,17434.27,17642.81,86160000],后面数据不变
  修改后代码var data = [[17512.58,17633.11,17434.27,17642.81,160000],后面数据不变
修改第二处：
  原示例代码var volumes = [86160000,79330000,102600000,104890000,后面数据不变
  修改后代码var volumes = [160000,79330000,102600000,104890000,后面数据不变

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts官方实例演示版本
+ Browser version [浏览器类型和版本]:chrome 版本 61.0.3163.100
+ OS Version [操作系统类型和版本]: win7 64位 旗舰版

### Expected behaviour [期望结果]
柱状图可正常显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![echarts_bug](https://user-images.githubusercontent.com/1902022/32273695-7299b4ee-bf3e-11e7-8ebd-503f3942760c.jpg)

**Comment by 100pah** [comment]
> 修改后代码var volumes = [160000,79330000,102600000,104890000,后面数据不变
160000 相对于其他数值，太小了，只有 79330000 的 1 / 500，从而其柱子的高度也只有 79330000 柱子高度的 1 / 500

**Comment by upupday** [comment]
测试环境不变，删除多余数据，只留下三条测试数据，修改后数据如下：
var dates = ["2016-03-29", "2016-03-30", "2016-03-31"];
var data = [[17512.58,17633.11,17434.27,17642.81,1000],
            [17652.36,17716.66,17652.36,17790.11,12000],
            [17716.05,17685.09,17669.72,17755.7,12000]];
var volumes = [1000,12000,12000];
页面效果可查看图(一)，volumes的第一个值 修改为10000时不显示，volumes的第一个值修改为1000时显示，其它测试数据不变，页面效果如图(二)
![e_b_1](https://user-images.githubusercontent.com/1902022/32305489-c2f86e5e-bfb0-11e7-9f92-66c510cedd9e.png)
![e_b_2](https://user-images.githubusercontent.com/1902022/32305490-c33013b8-bfb0-11e7-94e5-9915d2e70c7e.png)
