### ISSUE TITLE
2.x 地图和柱状图如何混搭？

### ISSUE THREAD

**Issue by wangtun** [apache/incubator-echarts#6956]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
2.x 可以用两个 echarts 实例。

**Comment by wangtun** [comment]
@100pah 但是我还想用时间轴控制两个图表，饼图有个center控制显示位置，是不是柱状图也可以加一个？多谢！
