### ISSUE TITLE
3D球体+3D飞线，setoption渲染数据时会卡顿一下

### ISSUE THREAD

**Issue by wudada1992** [apache/incubator-echarts#6957]
### One-line summary [问题简述]
vue+echarts-gl，单页应用，开发了一个自传的3D球体，球体身上有3D飞线用于展示漏洞攻击，飞线数据每隔1分钟用setoption刷新一次，但是每次setoption新数据的时候地球和飞线都会卡顿一下。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts: ^3.7.2  echarts-gl: ^1.0.0-beta.5
+ Browser version [浏览器类型和版本]:chrome 62.0.3202.62（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:win7旗舰版（64位）

### Expected behaviour [期望结果]
期望我的3D球实时刷新数据的时候可以不卡一下，或者像echarts2D那样有过度动画。

### ECharts option [ECharts配置项]

```javascript
option = {
	globe: {
		baseTexture: 'static/imgs/land.jpg', //球面纹理，陆地
		heightTexture: 'static/imgs/height.jpg', //高纹理，夜晚
		displacementScale: 0.05, //海拔高度
		shading: 'lambert', //着色效果
		environment: "static/imgs/stars.png", //星空
		light: { //光源
			ambient: { //全局环境光
				intensity: 0.2
			},
			main: { //太阳光
				intensity: 0
			}
		},
		layers: [{
			type: 'blend',
			blendTo: 'emission',
			texture: 'static/imgs/light.jpg' //城市灯光
		}],
		viewControl: { //鼠标旋转控制
			autoRotateSpeed: 1, //自转速度
			damping: .9, //旋转时的延滞因子
			rotateSensitivity: [1, 2], //横向、纵向旋转操作的灵敏度
			alpha: 30,
			distance: 200, //默认视角距主体距离
			autoRotateDirection: 'ccw', //自转方向 自西向东
			autoRotateAfterStill: 10, //在鼠标静止操作后恢复自动旋转的时间间隔
			animationDurationUpdate: 0, //过渡动画时长，默认1000
		}
	},
	series: [{
		type: 'lines3D',
		effect: {
			show: true,
			period: 2,
			trailWidth: 2,
			trailLength: 0.9,
			trailOpacity: 1
		},
		data: []
	}]
}

```
拿到新数据刷新代码：
```javascript
let data=response.data
option = {
	this.myChart.setOption({
		series: [{
			data: data
		}]
	})
}
```		

### Other comments [其他信息]

![2017-11-06_100200](https://user-images.githubusercontent.com/24663098/32422171-9adfdff2-c2d9-11e7-8c82-a160b719abba.png)

**Comment by wudada1992** [comment]
@100pah

**Comment by DukeGJ** [comment]
你试试每次刷新是都clear一下

**Comment by wudada1992** [comment]
@DukeGJ 尝试过clear，即使不设置初始位置targetCoord，每次clear都会导致3d球先转回美国再继续自转，这就不仅仅是卡了还不如不clear。我们大概每2个小时clear一下，用于解决3d飞线越飞越慢的问题。

**Comment by pissang** [comment]
每次更新大概有多少数据？

**Comment by tangdaohai** [comment]
@pissang hello, 有一个问题, 在这里顺便问一下，在地球开启自动旋转后，每次使用 `setOption` 更新数据后，地球会回到 `北京` 重现开始旋转(假设 `targetCoord` 的值为`北京` 坐标)，当前是不支持保持当前位置继续旋转嘛？
