### ISSUE TITLE
迁徙图

### ISSUE THREAD

**Issue by tangyuan2013** [apache/incubator-echarts#6966]
### One-line summary [问题简述]
ECharts 2 迁徙图更改时输入第三个起始地点时，只显示地图，但如果输入两个起始点就没有任何问题，是什么原因

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:ECharts 2
+ Browser version [浏览器类型和版本]:microsoft edge
+ OS Version [操作系统类型和版本]: windows2010

### Expected behaviour [期望结果]
给出解决办法

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没懂什么意思
