### ISSUE TITLE
getOption如何获取legend的选中状态？

### ISSUE THREAD

**Issue by wxxcarl** [apache/incubator-echarts#6967]
### One-line summary [问题简述]
地图类型是map，隐藏了一个legend，然后获取的option和隐藏之前的没什么区别。请问怎么判断哪些legend被隐藏了？
我知道legend.selected可以设置，但是获取的option里面并没有这个

因为我自定义了tooltip.formatter,如果不能正确获取状态，那legend的隐藏就对tooltip的显示没影响了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.7.1
+ Browser version [浏览器类型和版本]: chrome 61.0.3163.100（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: Mac Os 10.12.6

### Expected behaviour [期望结果]

获取的option能正确显示隐藏的legend

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hunjixin** [comment]
you can get legend select status by code 
chart.getOption().legend[0].selected

**Comment by 100pah** [comment]
监听 [legendselectchanged](http://echarts.baidu.com/api.html#events.legendselectchanged) 事件能满足你的需求么？

**Comment by wxxcarl** [comment]
满足是能满足，但是太繁琐了，我做的是动态生成的图标，而且是多张，支持多个维度，通过事件触发去记录状态，复杂了点 @100pah
