### ISSUE TITLE
x,y轴同时设置情况下，同时手动设置min，max，interval，某些数值会导致某个色块位置脱离坐标区域。

### ISSUE THREAD

**Issue by OliviaSong** [apache/incubator-echarts#6969]
x,y轴同时设置情况下，同时手动设置min，max，interval，某些数值会导致某个色块位置脱离坐标区域。

### Version & Environment [版本及环境]
+ ECharts version :3.7.2

### Expected behaviour [期望结果]
 色块应该在坐标区域里面

### ECharts option [ECharts配置项]

```javascript
option ={
            "series": [
              {
                "name": "销量",
                "type": "bar",
  
                "data": [ "5795", "5900","5861" ]
              }
            ],
            "xAxis": {
              "type": "category",
              "data": [ "好又多",  "白象", "康师傅" ]
            },
            "yAxis": [
              {
                "type": "value",
                "min": 5794,
                "max": 5944,
                "interval": 30
              },
              {
                "type": "value",
                "min": -7100,
                "max": 12900,
                "interval": 4000
              }
            ]
          }

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/13759392/32534848-6dac99f2-c492-11e7-9a4c-bced57837178.png)

**Comment by hunjixin** [comment]
@100pah 

一处代码位于echart\src\layout\barGrid.js
`        var valueAxisStart = baseAxis.onZero
            ? valueAxis.toGlobalCoord(valueAxis.dataToCoord(0))
            : valueAxis.getGlobalExtent()[0];
`
取了基轴的onZero属性，我觉得此处应该取valueAxis的onZero属性
下面是我的fix
`            var valueAxisStart = valueAxis.onZero
                ? valueAxis.toGlobalCoord(valueAxis.dataToCoord(0))
                : valueAxis.getGlobalExtent()[0];
`
类似的移除位于echart\src\chart\line\lineAnimationDiff.js
`
    var baseAxis = coordSys.getBaseAxis();
    var valueAxis = coordSys.getOtherAxis(baseAxis);
    var valueStart = baseAxis.onZero
        ? 0 : valueAxis.scale.getExtent()[0];
`

我可以对这个问题提个pr么

**Comment by hunjixin** [comment]
@100pah

一处代码位于echart\src\layout\barGrid.js
`        var valueAxisStart = baseAxis.onZero
            ? valueAxis.toGlobalCoord(valueAxis.dataToCoord(0))
            : valueAxis.getGlobalExtent()[0];`
取了基轴的onZero属性，我觉得此处应该取valueAxis的onZero属性
下面是我的fix
`            var valueAxisStart = valueAxis.onZero
                ? valueAxis.toGlobalCoord(valueAxis.dataToCoord(0))
                : valueAxis.getGlobalExtent()[0];`
类似的一处位于echart\src\chart\line\lineAnimationDiff.js
`    var baseAxis = coordSys.getBaseAxis();
    var valueAxis = coordSys.getOtherAxis(baseAxis);
    var valueStart = baseAxis.onZero
        ? 0 : valueAxis.scale.getExtent()[0];`

fix
`        var baseAxis = coordSys.getBaseAxis();
        var valueAxis = coordSys.getOtherAxis(baseAxis);
        var valueStart = valueAxis.onZero
            ? 0 : valueAxis.scale.getExtent()[0];`

我可以对这个问题提个pr么
