### ISSUE TITLE
echarts GL立体地图只能实现世界地图的中国地图不好使

### ISSUE THREAD

**Issue by xiaochen19930512** [apache/incubator-echarts#6972]
### Version & Environment [版本及环境]
+ v3.7.2:
+360浏览器:
+ win10:

### Expected behaviour [期望结果]

项目中要用到中国地图和立体柱图搭配展现，然而现在的GL只支持把世界地图（world.js）通过geo3d方法转换成立体地图中国地图（china.js）却不好使，报错无法解决，希望早日修复这个问题。

### ECharts option [ECharts配置项]

```javascript
option = {
   geo3D:{
		show:true,
		map:'china'  
	  }
}

```

**Comment by pissang** [comment]
能具体点报了什么错么？
