### ISSUE TITLE
axisTick 与 axisLabel 的问题

### ISSUE THREAD

**Issue by chaserstrong** [apache/incubator-echarts#6974]
echarts 能否实现类似图中的这种效果：
纵坐标是数值轴，显示的时候，label正好在tick的中间。

![qq 20171108161351](https://user-images.githubusercontent.com/18061322/32538241-4a7d8a64-c4a0-11e7-8ec0-da7a0f703276.png)

**Comment by 100pah** [comment]
数值轴来说，目前没有很好的办法。
除非使用另一个类目轴和这个数值轴重叠，并且固定数值轴 tick 的数量。
