### ISSUE TITLE
版本更新出错

### ISSUE THREAD

**Issue by lwx466714769** [apache/incubator-echarts#6984]
### One-line summary [问题简述]
重新下载3.7.5版本的包 不可以使用 报错__DEV__ is not defined
下载最新的 ，昨天更新的3.8.0 也不可以使用，报错  Path.extend is not a function 好像是echarts更新了 ，但是zrender没有更新

使用npm install 下载的
如果使用以前已经安装好的echarts 3.7.2版本的包是可以使用的，昨天更新把以前的包也改了，都出错了
使用webpack进行编译的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.2  3.8.0
+ Browser version [浏览器类型和版本]: 谷歌
+ OS Version [操作系统类型和版本]:windows 8

### Expected behaviour [期望结果]
恢复以前的3.7.2

新更新的，也要可以使用！！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by superddr** [comment]
同样问题, 现在基本不可用了

**Comment by jenny86** [comment]
我的也是3.8不可用，回退3.7.2也不可用

**Comment by lwx466714769** [comment]
需要使用原来的包，不能用新下载的，昨天搞一晚上，今天才试出来

**Comment by superddr** [comment]
@jenny86 @lwx466714769  必须手动指定zrender版本到3.5.1, 因为echarts 3.7.2里面的依赖写的是^zrender3.5.1, 有个^,所以会自动下载高版本的zrender, 所以编译还是会失败的. 必须同时指定这两者的版本才能编译

**Comment by lwx466714769** [comment]
@superddr   厉害 这都能找到。我还是先使用原来下的包吧，应该很快会解决的！

**Comment by Xixi20160512** [comment]
vue-echarts 遇到同样的问题 怎么解决？

**Comment by lwx466714769** [comment]
@Xixi20160512   先用以前下载的包  把之前已经下载好的 echarts 和zrender都复制到现在的node_modules下 就可以使用

**Comment by ShowJoy** [comment]
我是回退到echarts 3.6.2 和zrender 3.5.2就好了

**Comment by ningzhenyi** [comment]
keng die

**Comment by ningzhenyi** [comment]
./~/echarts/src/echarts.js
Module not found: Can't resolve 'zrender/core/env' in 
回退出现这个错误

**Comment by pissang** [comment]
抱歉，今天下午会发小版本解决这个打包的问题。

**Comment by lwx466714769** [comment]
@pissang  没事的 ，  尽快解决就好 ！

**Comment by P-ppc** [comment]
同，期望更新

**Comment by ifengzp** [comment]
我在package-lock里面指定echarts 3.6.2 和echarts里面的依赖zrender 3.5.2，就可以了

**Comment by xjccc** [comment]
@ifengzp   
请问，package-lock更改完之后，把node_modules删除后，重新install吗？

**Comment by Jeffy2012** [comment]
能快点解决这个问题么？

**Comment by hithto** [comment]
@xjccc
請問你試成功了嗎?

**Comment by yuzmb** [comment]
不管怎么换版本，一直报错
Uncaught TypeError: Path.extend is not a function
    at Object.graphic.extendShape (app.js:13941)
    at Object.defineProperty.value (app.js:32708)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at Object.<anonymous> (app.js:165442)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at Object.<anonymous> (app.js:13762)
    at Object.module.exports.rawScriptExports (app.js:13782)
    at __webpack_require__ (app.js:689)

**Comment by yuzmb** [comment]
不管怎么换版本，一直报错
`Uncaught TypeError: Path.extend is not a function
    at Object.graphic.extendShape (app.js:13941)
    at Object.defineProperty.value (app.js:32708)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at Object.<anonymous> (app.js:165442)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at Object.<anonymous> (app.js:13762)
    at Object.module.exports.rawScriptExports (app.js:13782)
    at __webpack_require__ (app.js:689)`

**Comment by lwx466714769** [comment]
package.json  指定版本号  echarts 3.6.2 和zrender 3.5.2   重新install 这两个 试试 @yuzmb

**Comment by yuzmb** [comment]
@lwx466714769 试过了 还是报同样的错误。

**Comment by lwx466714769** [comment]
我这有之前下载好的 3.7.2的包  我这里使用没有问题  及需的话  可以发给你 。不及的话可以等等，应该会很快维护好的 @yuzmb

**Comment by yuzmb** [comment]
那能麻烦你发到我的邮箱吗？谢谢！744245329@qq.com

**Comment by yuzmb** [comment]
@lwx466714769 那能麻烦你发到我的邮箱吗？谢谢！744245329@qq.com

**Comment by tinn2015** [comment]
我也找了好久。。。。

**Comment by jmeviler** [comment]
[zrender-v3.5.1.zip](https://github.com/ecomfe/echarts/files/1456837/zrender.zip)
[echarts-v3.6.2.zip](https://github.com/ecomfe/echarts/files/1456840/echarts.zip)

**Comment by lwx466714769** [comment]
[echarts3.7.2.zip](https://github.com/ecomfe/echarts/files/1456858/echarts3.7.2.zip)
这是版本3.7.2的，里面有两个包，都需要放入node_modules。急需要用的，可以先下载用用，随后应该会修复bug 。

**Comment by hgs1** [comment]
什么时间修复呀，在线等，快下班了。

**Comment by hgs1** [comment]
本地环境指定版本可以，但是测试环境走jenkins发布，用jenkins发布完还是不行。

**Comment by cliberal** [comment]
指定echarts和zrender版本分别为3.7.2和3.6.2可以

**Comment by vankai** [comment]
在package.json的依赖中 把版本号改为以下的 ，可以指定3.7版本 临时解决一下。 
```
"echarts": "https://registry.npmjs.org/echarts/-/echarts-3.7.2.tgz",
 "zrender": "https://registry.npmjs.org/zrender/-/zrender-3.6.3.tgz"
```

**Comment by xjccc** [comment]
@hithto    试成功了。或者直接npm install这俩版本

**Comment by zhengcheng123** [comment]
@xjccc   怎么弄的呀

**Comment by zhengcheng123** [comment]
echart 3.6.2   zrender  3.5.2  重新install  查看node_module，如果有其他版本的echart或者render，就删掉保留3.6.2和3.5.2的版本

**Comment by HouCoder** [comment]
我这里临时解决方案是把 `echarts` 写死成 `3.7.2`，然后在 dependencies 里面添加一个：

```
"zrender": "3.6.3"
```

最终的样子是这样的：

```
"echarts": "3.7.2",
"zrender": "3.6.3",
```

**Comment by superddr** [comment]
hot fix 还没发布吗....jenkins死得笔挺

**Comment by PerseveranceZ** [comment]
package.json 里面写死这2个库的版本，可以暂时解决

"echarts": "3.7.2",
"zrender": "3.6.3",

**Comment by Oscar19921030** [comment]
用了echarts-for-react 组件，编译死挺了

**Comment by zphhhhh** [comment]
+1，希望 echarts 团队跟进哈......

**Comment by xsbear** [comment]
今天上线差点被坑，感谢 @PerseveranceZ

**Comment by yeqingyun** [comment]
换了版本，重新install也不行呀，我用的yarn，希望尽快解决，十分感谢！！

**Comment by liuya891012** [comment]
@pissang 不是发版修复么，大佬，我还一直等着呢

**Comment by weizs** [comment]
zrender升级3.7.0后path.extend那个报错能不能先修复下，由于项目特殊性，根项目依赖不能随便更新，内部组件动态引入echarts 3.7.1，但zrender ^3.6.1 自动更新到3.7.0了

**Comment by ChiaJune** [comment]
从昨天等到今天，退也报错，进也报错，求官方解决一下。

**Comment by zccccccc** [comment]
坐等

**Comment by cmlily8294** [comment]
@weizs 你在你的项目里把zrender固定在3.6.1就行。

**Comment by weizs** [comment]
@cmlily8294 我知道，只不过我们在做一个特殊平台，提供应用构建，基座packages.json目前没有这依赖，都是下面用户组件以npm包形式安装进来的，出现这问题包是其中一个客户用了echarts，我们不能为了一个客户在整个平台中增加echarts和zrender的依赖，太low了

**Comment by xingxinghuo1000** [comment]
坐等更新

**Comment by coldice945** [comment]
大佬解决一下哇。今天发版，被坑死了。指定版本号 echarts 3.6.2 和 zrender 3.5.2 本地可以了，但是 Jenkins 死活不行。

**Comment by YuyangGong** [comment]
@coldice945 CI的话，
1. package.json中指定版本号基本是可以的
2. package-lock.json中lock版本。
3. 以上都不行，但是事情比较紧急？ 那修改CI相应的yml配置文件吧，
比如
```
run unit test:
  stage: unit-test
  script:
    - npm install
    - npm run unit
```
修改为
run unit test:
  stage: unit-test
  script:
    - npm install
    - npm install echarts@3.6.2
    - npm install zrender@3.5.2
    - npm run unit
```

**Comment by mu-yu** [comment]
给大佬们递临时解决方案：https://github.com/ecomfe/echarts/issues/7000#issuecomment-343360074

**Comment by gitGksgk** [comment]
倒霉。久仰echarts大名，结果刚用就赶上issue..

**Comment by hgs1** [comment]
@coldice945  如果改动不需要太大，尝试script标签引用吧，我后来这么解决的

**Comment by pissang** [comment]
我们在新发布的 3.8.2 中将 lib 下的重新转译成了 CommonJS 格式并且去掉了 __DEV__，应该解决了大家构建的兼容问题。非常抱歉新版本的模块系统给大家造成了这么大的麻烦。

**Comment by ChiaJune** [comment]
然而，为啥我还是报错？
![](http://ww1.sinaimg.cn/large/0060lm7Tly1flcy2zv53pj30c7060dg5.jpg)
绝对是最新的版本：**echarts@3.8.2**  **zrender@3.7.2**

**Comment by pissang** [comment]
@ChiaJune 能发下你是怎么引入 echarts 的么？

**Comment by Yusoo** [comment]
3.8.2 webpack引入的默认没有map吗？
手动引入src\chart\map，又会报错 __DEV__ is not defined

**Comment by pissang** [comment]
@Yusoo 引入 `lib/chart/map`

**Comment by liuya891012** [comment]
@pissang 多谢大佬，升级到3.8.2完美解决

**Comment by ChiaJune** [comment]
@pissang 我是这样引入的
``` javascript
import * as echarts from 'echarts/lib/echarts'
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/bar'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/toolbox'
import 'echarts/lib/component/title'
import 'echarts/lib/component/legend'
import 'echarts/lib/component/grid'
```
但是我看官网，`lib`已经变成了`src`，不知道是不是这个原因

**Comment by pissang** [comment]
@ChiaJune 还是 lib 引入，不建议 src 引入（官网后面会修正，因为如果引入其它引入 lib 下模块的 echarts 插件的话可能会造成代码的重复打包

**Comment by Yusoo** [comment]
引入 `lib/chart/map` 和 `map/js/china` 还是报 ECharts Map is not loaded

**Comment by Yusoo** [comment]
3.8.3 正常了

**Comment by syyvstar** [comment]
@pissang 安装失败
![image](https://user-images.githubusercontent.com/30794902/32650770-f91066f6-c639-11e7-9096-ad1faf7b3ab0.png)

**Comment by aanari** [comment]
Thank you and your team for the hard work on this @pissang!

The combination of echarts 3.8.3 and zrender 3.7.2 finally did the trick for me.

**Comment by public6326** [comment]
辛苦了 各位开源贡献者  @pissang
