### ISSUE TITLE
3.8版本编译出错

### ISSUE THREAD

**Issue by jenny86** [apache/incubator-echarts#6985]
3.8版本编译不了，报错
回退到3.7.2页报相同错误

报错内容
_DEV_  is not  defined  

clazz.js 
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ShowJoy** [comment]
+1

**Comment by hithto** [comment]
+2

**Comment by luogao** [comment]
+3

**Comment by CoderFang** [comment]
+4

**Comment by vankai** [comment]
在package.json的依赖中 把版本号改为以下的 ，可以指定3.7版本 临时解决一下。 
```
"echarts": "https://registry.npmjs.org/echarts/-/echarts-3.7.2.tgz",
 "zrender": "https://registry.npmjs.org/zrender/-/zrender-3.6.3.tgz"
```

**Comment by PerseveranceZ** [comment]
package.json 里面写死这2个库的版本，可以暂时解决

"echarts": "3.7.2",
"zrender": "3.6.3",

**Comment by pissang** [comment]
我们在新发布的 3.8.2 中将 lib 下的重新转译成了 CommonJS 格式并且去掉了 __DEV__，应该解决了大家构建的兼容问题。非常抱歉新版本的模块系统给大家造成了这么大的麻烦。

**Comment by lemontizz** [comment]
搞了一上午，居然是官方的问题

**Comment by luogao** [comment]
谢谢 更新 哈哈

**Comment by wxxcarl** [comment]
把我给坑坏了，一直以为是我代码问题，昨晚弄到半夜
