### ISSUE TITLE
eacharts怎样在点击时，弹出一个框，在弹出框显示图表数据

### ISSUE THREAD

**Issue by xiwadai** [apache/incubator-echarts#6990]
### One-line summary [问题简述]
定义一个弹出框，一开始隐藏，在mounted中初始化报错
![image](https://user-images.githubusercontent.com/24467843/32587316-ac03738c-c542-11e7-95a4-8d7785160a90.png)

![image](https://user-images.githubusercontent.com/24467843/32587285-84af19d0-c542-11e7-8795-fca6cfcc85eb.png)

报错

can not get dom width and height

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.7.2
+ Browser version [浏览器类型和版本]:
谷歌浏览器
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

期望，现在点击弹出一个模态框，在框里面展示图表数据

### ECharts option [ECharts配置项]

```javascript
	var eChart = echarts.getInstanceByDom(document.getElementById('Timeface'));
							
								// 绘制图表
							
		



	eChart.setOption({
					title: {
						text: '接口访问统计',
						x: 'center'
						},
						tooltip: {},
					yAxis: [{
						type: 'value',
						boundaryGap: [0, 1],
						min: 0,
					        max: vm.maxte, //设置横坐标最大值
						}],

					xAxis: [{
						type: 'category',
						data: vm.SectionList,
						axisTick: {
							alignWithLabel: true
							}
						}],
						series: [{
							name: '访问量',
							type: 'bar',
							barMaxWidth: '30',
							data: vm.countList,
							itemStyle: {
									normal: {
										color: '#4ad2ff' //柱状图颜色
									}
										},
									}],
									//位置定位
									grid: {
										left: '30',

									},
								});


```

**Comment by navono** [comment]
提供一个思路。通过订阅zrender的click消息。在消息处理里面就可以做你想做的了。
