### ISSUE TITLE
希望能够支持时间不连续的曲线图

### ISSUE THREAD

**Issue by EarlYan** [apache/incubator-echarts#6993]
对于几组数据时间轴不相同的情况可以借鉴下
https://www.hcharts.cn/demo/highcharts/spline-irregular-time
类似于HighCharts中
每一组数据都传入时间和对应值

**Comment by hanfengcan** [comment]
data里面把时间一起写进入去格式类似于
```
series: {
  type: 'line'
  data: [
    {时间, 值}
]
}
```

然后某些时间点没有数据的,后面有数据就会连接过去了
