### ISSUE TITLE
tooltip怎么获取两个x轴上的值

### ISSUE THREAD

**Issue by chenxia123** [apache/incubator-echarts#6999]
### One-line summary [问题简述]

柱状图，有两个x轴，两个x轴的内容都需要在tooltip里显示， 现在的问题是：只能拿到第一组X轴的数据，另一个拿不到，该怎么办？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by navono** [comment]
@chenxia123 http://echarts.baidu.com/demo.html#grid-multiple

**Comment by chenxia123** [comment]
@navono 我把这个例子原样搬到本地， tooltip只会显现一组数据。试了下其他的双x轴的例子也一样， 只会显示出一组数据。不知道问题出在哪儿，我本地已经安装了最新版本的echarts。

**Comment by navono** [comment]
@chenxia123 有一种方式就是使用自定义的formatter的tooltip。触发tooltip时，看下传入的数据是什么。
