### ISSUE TITLE
 TypeError: Path.extend is not a function

### ISSUE THREAD

**Issue by sumshare** [apache/incubator-echarts#7005]
3.8.0 release之后，3.7.X的版本会报错

**Comment by kavinforever** [comment]
"echarts": "3.7.2",
"zrender": "3.6.3",
写死这两个包以后同样报错
![image](https://user-images.githubusercontent.com/9795441/32639547-1600d6d4-c58a-11e7-814c-45838b03b813.png)

**Comment by mocking3** [comment]
me too

**Comment by superddr** [comment]
写死包还报错的,应该是echarts的目录下多了个node_modules,里面还包含了一个高版本的zrender

**Comment by live106** [comment]
mee  too !

**Comment by yangbinlovegis** [comment]
me too

**Comment by EdikWang** [comment]
me too

**Comment by weizs** [comment]
@sumshare 不是3.8.0更新的原因，是zrender也更新了，zrender3.7.0以下的版本没问题

**Comment by sumshare** [comment]
@kavinforever 需要手动删除高版本的包

**Comment by weizs** [comment]
如果是本地项目，建议用yarn的resolutions，可以解决echarts目录下生成node_modules，并且按照3.7.0zrender的问题

**Comment by w345731923** [comment]
npm i echarts@3.7.3 zrender@3.6.3

**Comment by weizs** [comment]
`resolutions:{"zrender":"3.6.3"}`

**Comment by live106** [comment]
正式环境 CentOS， 清缓存全部重新编译了还是不灵。

**Comment by live106** [comment]
本地可以。

**Comment by Stupidism** [comment]
@w345731923 Couldn't find any versions for "echarts" that matches "3.7.3"

**Comment by weizs** [comment]
path.extend的问题大家去zrender跟进吧，是zrender更新导致
https://github.com/ecomfe/zrender/issues/293

**Comment by w345731923** [comment]
@Stupidism sorry,it's 3.7.1 or 3.7.2

**Comment by shshwzs** [comment]
翻到两个QQ，比较急的加QQ问问情况吧
QQ1：599316527
QQ2：474021406

**Comment by Stupidism** [comment]
我已经想跑到马路对面去敲百度echarts的门了

**Comment by magicdawn** [comment]
```
Path = {default: { extend: function(){ ... } }}
```

**Comment by v2018z** [comment]
me too

**Comment by pissang** [comment]
我们在新发布的 3.8.2 中将 lib 下的重新转译成了 CommonJS 格式并且去掉了 __DEV__，应该解决了大家构建的兼容问题。非常抱歉新版本的模块系统给大家造成了这么大的麻烦。
