### ISSUE TITLE
我想问一下symbol不支持gif图吗，有什么办法

### ISSUE THREAD

**Issue by jiangshichao** [apache/incubator-echarts#7027]
我想问一下symbol不支持gif图吗，有什么办法

**Comment by Ovilia** [comment]
不支持，你是想要有动画效果吗？那可以自己 setTimeout 控制，建议放在单独的层中，这样每次刷新就只修改它

**Comment by jiangshichao** [comment]
我也考虑过，我这边是做的map，使用geo坐标系，在map大小位置自适应的情况下，我自己的图层位置不好确定，而且可能会覆盖一些tips....想改源码，看的又比较晕....

**Comment by Ovilia** [comment]
建议使用百度地图作为底图，上面可以添加 gif：http://lbsyun.baidu.com/jsdemo.htm#c1_16

**Comment by jiangshichao** [comment]
谢谢，我去研究下
