### ISSUE TITLE
Ribbon Chord Diagram like echarts2

### ISSUE THREAD

**Issue by jonavila** [apache/incubator-echarts#7029]
### One-line summary [问题简述]
Is there a way to create a Ribbon Chord Diagram like echarts 2:
http://echarts.baidu.com/echarts2/doc/example/chord2.html

As far as I know, in echarts 2 you could specify ribbonType: true or false in the series options.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Hi, we are considering supporting this type of chart. Thanks for your suggestion. 😄

**Comment by kelvinau** [comment]
It's been about half a year. Is this planning to be implemented? I am trying to use echarts 2 for this chart type but it's quite hard to use, even for just changing the color of an item.
