### ISSUE TITLE
动态减少series数量时出现的BUG问题

### ISSUE THREAD

**Issue by hanxiansen** [apache/incubator-echarts#7035]
### One-line summary
![qq 20171114162539](https://user-images.githubusercontent.com/7412531/32770009-09bd0adc-c959-11e7-96f7-32bea34d073f.png)
 [问题简述]

动态减少bar chart 中的series数量时，图表上无法动态渲染减少后的数据图表

### Version & Environment [版本及环境]
+ECharts 版本 (ECharts version): 3.8.2
+浏览器类型和版本 (Browser version):  chrome latest
+操作系统类型和版本 (OS Version):   win10

### Expected behaviour [期望结果]

在react中使用echart，当动态减少series中的数据时无法实时渲染减少后的图表。

### ECharts option [ECharts配置项]

```javascript
option = {
//
}
```

### Steps to reproduce [重现步骤]
+在type: 'bar'的情况下，首次进入页面时是由四个series生成的数组
+当我改变接口数据，这时候会在原来的四个series数组上去掉最后一个series，这时候还有三个series，这种情况下，legend会显示有三个，但柱状图还是原来的四个

但是：
+如果在原来的四个series数组上增加一个series会运行正常
+如果在原来的四个series数组上上减少非最后一个series也会运行正常

### Other comments [其他信息]

![图表样式截图](http://upload-images.jianshu.io/upload_images/1412910-1192d0587c30d6cb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/700)

**Comment by bigfacewo** [comment]
要设置merge为false吧

**Comment by hanxiansen** [comment]
@bigfacewo echart文档中没有‘merge’这一项设置

**Comment by bigfacewo** [comment]
![setoption](https://user-images.githubusercontent.com/31603897/33052419-bbd3e74a-cea9-11e7-80c7-68ac69620e67.png)

这个不是吗？notMerge那一项。
http://echarts.baidu.com/api.html#echartsInstance.setOption
