### ISSUE TITLE
地图大小无法修改

### ISSUE THREAD

**Issue by jjxpeak** [apache/incubator-echarts#7045]
### One-line summary [问题简述]
地图大小无法修改

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.4 完整版 min 
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: WIN7

### Expected behaviour [期望结果]

压缩版地图大小可控

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jjxpeak** [comment]
地图大小无法修改

**Comment by pissang** [comment]
请具体描述你的问题

**Comment by jjxpeak** [comment]
显示南沙群岛问题，需要导入map包才可以，已经解决， 希望官网上指出压缩包并不包含相关模块
