### ISSUE TITLE
堆叠柱状图如何在顶部显示某项数据占比

### ISSUE THREAD

**Issue by zhangxiaoshang** [apache/incubator-echarts#7048]
![11521510730496_ pic](https://user-images.githubusercontent.com/19658966/32824888-b9c39b70-ca1d-11e7-9b8f-d97d40880c1c.jpg)

如图，在顶部展示一项占比 (334 / (334 + 99))%, 这个用EChart怎么实现？

**Comment by hahabazinga** [comment]
可以使用markPont，背景设为透明，文字颜色设为黑色
