### ISSUE TITLE
Need Help DataZoom option not working

### ISSUE THREAD

**Issue by krisklosterman** [apache/incubator-echarts#7049]
### One-line summary [问题简述]

I can not figure out how to get data zoom to work with my chart, the chart and data show up, but no datazoom. I am using a line chart with the following options.

here is some of the options config
```javascript
    "grid": {
      "bottom": 80
    },
    "toolbox": {
      feature: {
          dataZoom: {
              yAxisIndex: 'none'
          }
      }
    },
    "dataZoom": [
      {
        "show": true,
        "realtime": true,
        "start": 65,
        "end": 100
      }
    ],
      xAxis: {
          type : 'time',
      },
      yAxis: {
          type : 'value'
      }

```

the data in this type of format
```javascript
data : [{
name: new Date(dateVariableHere),
value: [
new Date(dateVariableHere),
floatValueHere
]
}];
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.x
+ Browser version [浏览器类型和版本]: Chrome 62.0.3202.94 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: Mac Sierra High / Windows 10

**Comment by rix1** [comment]
Hi @krisklosterman, I don't know @ecomfe's issue tracker policy – but questions like yours (help) generally belong in another channel – like StackOverflow, a Slack/Discord channel etc.  🙂 This is a issue tracker for tracking bugs and features.

**Comment by krisklosterman** [comment]
Is there a slack / discord channel I can join for eCharts?

**Comment by krisklosterman** [comment]
Might be a bug if I can't get it to work...

```
      "dataZoom": [
        {
          type: 'slider',
          show: true,
          start: 65,
          end: 100
        }
      ]
```
that setting does nothing either

**Comment by syntacticsolutions** [comment]
I'm having the same problem.

**Comment by syntacticsolutions** [comment]
This is definitely a bug.

**Comment by syntacticsolutions** [comment]
I think some other options are conflicting with it
