### ISSUE TITLE
如何为关系图节点添加自定义动画？

### ISSUE THREAD

**Issue by exdestroyer** [apache/incubator-echarts#7058]
### One-line summary [问题简述]
目前自带的展开动画太死板，我想给每个节点添加一个从中间向外移动的动画，能否实现，翻了一遍文档没有相关函数

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

能够添加自定义动画

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wuranhw** [comment]
我是遇到关系图初始化迭代动画时间太长，可以调短吗？不然它一直在疯狂运动
