### ISSUE TITLE
关于如何实现 按对数绘图，按原值显示 的问题

### ISSUE THREAD

**Issue by ytc272098215** [apache/incubator-echarts#7068]
RT
在使用雷达图时我遇到了这样一种情况，因为属性的值域非常大（上亿），所以在设计最大值选项时不得已必须选取非常大的上限，这种情况下想到了对原值求对数后再显示，可以有效的显示出大小的区分度，同时拉近较大值与较小值的比例关系。但是这时显示的的提示框的值也变为对数。
![image](https://user-images.githubusercontent.com/33748319/32939525-bb6c1576-cbba-11e7-8f87-05b03fd97740.png)
请问dalao我如何设置可以使雷达图按对数绘点，而提示框中仍显示原值

**Comment by galenjiang** [comment]
可以保存两列数值，tooltip时显示原数值。
