### ISSUE TITLE
建议增加Y轴指示器直接指向value功能

### ISSUE THREAD

**Issue by LkpCzt** [apache/incubator-echarts#7084]

**Comment by git-stf-01** [comment]
顶一个。我也有这个需求。

**Comment by pissang** [comment]
类似 markLine 这样的？

**Comment by LkpCzt** [comment]
@pissang 
![image](https://gitee.com/KPl_Demo/MyDemo/blob/master/GIF/Jietu20171114-095917.gif)

**Comment by LkpCzt** [comment]
![image](https://github.com/LkpCzt/MyImage/blob/master/Jietu20171123-143826.gif?raw=true)

**Comment by git-stf-01** [comment]
就是平行于x轴的那一条线。并且能随着折线的y值而变动。
