### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by xristina** [apache/incubator-echarts#7088]
### One-line summary [问题简述]
An error occurs in type:time graph when animating:
```
Uncaught TypeError: Cannot set property '0' of undefined
    at Vt (echarts.min.js:1)
    at onframe (echarts.min.js:1)
    at ft.i.onframe (echarts.min.js:1)
    at ft.fire (echarts.min.js:1)
    at ft.step (echarts.min.js:1)
    at wx._update (echarts.min.js:1)
    at t (echarts.min.js:1)
```

### Details
After some debugging I found that the error comes from dist/echarts.js line 3442 in interpolateArray function (with arrDim = 2 in my case):
```
function interpolateArray(p0, p1, percent, out, arrDim) {
    var len = p0.length;
    if (arrDim == 1) {
        for (var i = 0; i < len; i++) {
            out[i] = interpolateNumber(p0[i], p1[i], percent);
        }
    }
    else {
        var len2 = len && p0[0].length;
        for (var i = 0; i < len; i++) {
            for (var j = 0; j < len2; j++) {
                out[i][j] = interpolateNumber(
                    p0[i][j], p1[i][j], percent
                );
            }
        }
    }
}
```
because p0, p1 and out arrays do not always have the same length (the data get updated dynamically through server requests and may not be of equal length).

The error disappears if you change the function to:

```function interpolateArray(p0, p1, percent, out, arrDim) {
    var len = p0.length;
    if (arrDim == 1) {
        for (var i = 0; i < len; i++) {
            out[i] = interpolateNumber(p0[i], p1[i], percent);
        }
    }
    else {
        var len2 = len && p0[0].length;
        for (var i = 0; i < len; i++) {
            if (!out[i])                            // make sure the out[i] will exist
                out.push([])
            for (var j = 0; j < len2; j++) {
                if (p1[i])                          // make sure the p1[i] exists in order to interpolate
                    out[i][j] = interpolateNumber(
                        p0[i][j], p1[i][j], percent
                    );
                else                                // if p1[i] does not exist keep p0[i] as is
                    out[i][j] = p0[i][j];
            }
        }
    }
}
```
The above code does not throw errors when p0, p1 and out have different lengths. 
Could you please consider making the above change? Or is there something I do wrong and I should change to avoid the error? 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: Chrome 61.0.3163.100
+ OS Version [操作系统类型和版本]: OS X 10.11.6

### Expected behaviour [期望结果]
The expected behaviour is the graphs to not to throw console errors.

### ECharts option [ECharts配置项]

```javascript
option = {
        xAxis: [{
            type: 'time'
        }],
        yAxis: [{
            type: 'value'
        }],
        series: [{
            name: 'Cost',
            type: 'line',
            stack: 'f',
            areaStyle: {
                normal: {
                    color: "rgba(0,155,155,0.2)"
                }
            },
            data: [] //data get updated dynamically
        }]
}

```

**Comment by pissang** [comment]
Actually, we will fill the interpolated array to the same length before animating. Can you share us the code which can reproduce the issue so we can find where the problem is

**Comment by welkin-qing** [comment]
我也遇到了这种问题
![image](https://user-images.githubusercontent.com/20507251/103842580-3b682500-50d1-11eb-83ee-ce865cff0989.png)
也是这个函数interpolateArray
![image](https://user-images.githubusercontent.com/20507251/103842600-44f18d00-50d1-11eb-932f-be4aa2e49ce6.png)

**Comment by wangkuan0818** [comment]
> 我也遇到了这种问题
> ![image](https://user-images.githubusercontent.com/20507251/103842580-3b682500-50d1-11eb-83ee-ce865cff0989.png)
> 也是这个函数interpolateArray
> ![image](https://user-images.githubusercontent.com/20507251/103842600-44f18d00-50d1-11eb-932f-be4aa2e49ce6.png)

老哥解决了吗。我也遇到了一样的报错

**Comment by Joan428** [comment]
![image](https://user-images.githubusercontent.com/48681179/181670385-6ff3923f-e9c7-4413-92a7-c4e77923f133.png)
各位大佬怎么解决的呀T.T
