### ISSUE TITLE
求tree节点之间折线样式

### ISSUE THREAD

**Issue by asyty** [apache/incubator-echarts#7090]
### One-line summary [问题简述]
现在的树图，节点之间只有曲线连接的方式，求支持和echarts2一样的折线

### Expected behaviour [期望结果]
和echarts2类似的支持节点折线连接的树图

**Comment by Bbbzhao** [comment]
我同样有这个需求...

**Comment by deqingli** [comment]
后续会考虑加上，谢谢反馈

**Comment by lising1984** [comment]
请问什么时候能加上？

**Comment by Bbbzhao** [comment]
> 请问什么时候能加上？

我先用着echart2.0了

**Comment by qiaoqiao10001** [comment]
马上都2019年了。这个功能还没加上吗

**Comment by masterlirui** [comment]
强烈建议加上这个功能啊，另外就是不同层级节点之间的间隔距离设置

**Comment by 524882178** [comment]
2019年4月了~  还没有这个功能啊~~~

**Comment by DOVEMM** [comment]
2019年五月了~

**Comment by dingww** [comment]
还有同一层级节点之间的间隔距离设置。。这几个功能对于树图真的太重要。。。
求更呀～～

**Comment by alphatan** [comment]
家祭无忘告乃翁~

**Comment by deqingli** [comment]
#8313

**Comment by deqingli** [comment]
@masterlirui @dingww I have completed the polyline edge style which will be released in version 4.7.0 and the distance between the different layers and nodes is related to #10535. So I will close this issue if you still have any problem feel free to reopen this issue.
