### ISSUE TITLE
Map color disappears after setting option (v3.8.5)

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#7092]
Version: 3.8.5 (works in 3.7.2)

Example code: 
```
option = {
    "title":{
        "text":"title"
    },
    "series": [
        {
            "map": "world",
            "type": "map",
            "data": [
                {
                    "name": "China",
                    "itemStyle": {
                        "normal": {
                            "areaColor": "#2196f3"
                        }
                    }
                }
            ]
        }
    ]
}

setTimeout(() => {
    myChart.setOption({
        title:{
            text:"Changed title"
        }
    });    
}, 500);
```
When the chart is loaded, China region has color: 
![image](https://user-images.githubusercontent.com/561365/33118491-52ad3320-cf6c-11e7-99ed-24b6dea3559a.png)

Then after 500ms timeout, China looses its color after myChart.setOption() is called:

![image](https://user-images.githubusercontent.com/561365/33118458-3a97d8f8-cf6c-11e7-8055-af1678ffd529.png)

This works ok in 3.7.2

**Comment by pissang** [comment]
As always, thanks for the report.
