### ISSUE TITLE
echarts上的图标超出坐标轴，可不可以自动隐藏

### ISSUE THREAD

**Issue by AntoniaQiao** [apache/incubator-echarts#7093]
![dcb1a7df-7700-4cd7-87d7-16e0666e7d84](https://user-images.githubusercontent.com/19327642/33119909-6f12cebe-cfab-11e7-8783-47f58f843ec3.png)

**Comment by pissang** [comment]
能不能具体描述下这个问题出现的环境和代码？

**Comment by AntoniaQiao** [comment]
@pissang 
x轴设了一个最大值和最小时，是时间戳类型的。
第一个图是custome类型的，蓝条通过计算传入的起止时间画出来的，结束的时间大于设置的x轴最大的时间，所以超出了，在不处理数据的情况下，可以通过配置来隐藏掉超出的时间吗

**Comment by AntoniaQiao** [comment]
@pissang  大神这个可以通过某个配置隐藏掉吗

**Comment by 18830438187** [comment]
遇到了同样问题，有什么配置项可以解决吗

**Comment by distanting** [comment]
我也遇到这种问题了
