### ISSUE TITLE
双轴自动同步需求

### ISSUE THREAD

**Issue by chriswong** [apache/incubator-echarts#7094]
### One-line summary [问题简述]
目前要实现左右一样的 Y 轴，首先必须要有两个 yAxis 及对应的 serie，造成冗余配置。而在股票行业，对同步双轴的需求还是很多的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: 所有
+ OS Version [操作系统类型和版本]: 所有

### Expected behaviour [期望结果]
 坐标轴增加一个配置属性，即自动实现双轴并同步。

**Comment by ColinCLL** [comment]
![image](https://user-images.githubusercontent.com/19434659/34368741-2e0fdab8-eaf1-11e7-9e41-711136bc1838.png)
这个动态配置到一致，楼主是有实现吗？，Y轴分段计算逻辑是怎么样的逻辑。貌似没有强制分段个数，也不是被5整除就分5段。
