### ISSUE TITLE
Error: `setOption` should not be called during main process. 

### ISSUE THREAD

**Issue by 2448795365** [apache/incubator-echarts#7097]
图表的ajax在实时获取后台数据后，填充echarts图表，初次加载没错，当你继续打开浏览其他echarts图表页面时候，会报Error: `setOption` should not be called during main process. 我研究了一下，只要你不实时更新图表的数据就不会报错，只要更新就报错，但是项目需求就是要实时更新的。实在不知道怎么解决了。

### Version & Environment [版本及环境]
+ ECharts version [3.8.1]:
+ Browser version [火狐]:
+ OS Version [win10]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wuranhw** [comment]
我之前也遇到过这个错，后来用react实现的，，在ComponentWillReceive函数里面可以在数据发生更新的时候调用SetOption重新更新页面。
