### ISSUE TITLE
移动端怎么修改字体单位为rem

### ISSUE THREAD

**Issue by windy1114** [apache/incubator-echarts#7103]
### One-line summary [问题简述]

设置textStyle:的fontSize 只能接收int。想知道在移动端怎么实现字号的自适应大小。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

可以设置为rem

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by vercha** [comment]
FYI。
http://echarts.baidu.com/tutorial.html#%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%87%AA%E9%80%82%E5%BA%94
