### ISSUE TITLE
3里面的关系图可以给关系的线增加图例吗？通过选择线的图例选择不同的关系

### ISSUE THREAD

**Issue by yangyining** [apache/incubator-echarts#7115]
### One-line summary [问题简述]

3里面的关系图可以给关系的线增加图例吗？通过选择线的图例选择不同的关系

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]: 
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行
