### ISSUE TITLE
tooltip可复制

### ISSUE THREAD

**Issue by wuminbin** [apache/incubator-echarts#7120]
### One-line summary [问题简述]
能不能在设置tooltip可允许鼠标进入的同时可以选中数据复制？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by dfEric** [comment]
```javascript
tooltip:"<div contenteditable="true">your content</div>",
enterable:true
```
