### ISSUE TITLE
地图上富文本的问题，可是必须贴图片才行，求指教~~~

### ISSUE THREAD

**Issue by zhaodamao** [apache/incubator-echarts#7144]
### One-line summary [问题简述]

不能贴图片吗？？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
什么意思？
