### ISSUE TITLE
为什么地图上显示不了镇区，三级城市？填了坐标值也没有用，可是现在有这个需求。。怎么实现？？？求回复~~~

### ISSUE THREAD

**Issue by zhaodamao** [apache/incubator-echarts#7149]
### One-line summary [问题简述]

为什么地图上显示不了镇区，三级城市？填了坐标值也没有用，可是现在有这个需求。。怎么实现？？？求回复~~~

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这部分数据是没法拿到行政边界的

**Comment by zhaodamao** [comment]
那如何才能拿到。有这个需求呢。。

**Comment by pissang** [comment]
考虑下用百度地图插件？

**Comment by wuqi** [comment]
1:100万 是公开的,我记得有三级的行政边界  http://www.webmap.cn/commres.do?method=result100W  不过如果要出图必须要审核吧
