### ISSUE TITLE
x轴标签内容过长，应用了 interval: 0 后，左右两侧的标签依然无法显示

### ISSUE THREAD

**Issue by Nsrfc** [apache/incubator-echarts#7165]
### One-line summary [问题简述]
x轴标签内容过长，应用了 interval: 0 后，左右两侧的标签依然无法显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:Chrome
+ OS Version [操作系统类型和版本]:Windows7 32位

### Expected behaviour [期望结果]
所有的标签可以正常显示

### ECharts option [ECharts配置项]

```javascript
    <div id="mychart" style="width: 550px; height: 500px; margin: 50px auto;"></div>
    <script type="text/javascript">
        var myChart = echarts.init(document.getElementById('mychart'));
        myChart.setOption({
            legend: {
                data: ['测试数据']
            },
            xAxis: {
                data: ['沈阳市', '大连市', '鞍山市', '抚顺市', '本溪市', '丹东市', '锦州市', '营口市', '阜新市', '辽阳市', '盘锦市', '铁岭市', '朝阳市', '葫芦岛市'],
                axisLabel: {
                    interval: 0
                }
            },
            yAxis: {},
            series: [{
                name: '测试数据',
                type: 'bar',
                data: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
            }]
        });
    </script>

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/16621343/33472397-0ba64df2-d6ad-11e7-9f0c-1d356fa8dd3f.png)

**Comment by Erimus-Koo** [comment]
这里宽度是自动算的。  
就算开了showMin/Max，也会压缩隐藏其他的。  
而且字叠一起也看不清啊。  
正常做法是转角度，魔改方法是用负数padding。  

    axisLabel: {
        interval: 0,
        // showMinLabel:true,
        // showMaxLabel:true,
        // margin:20,
        padding:[0,-10],
        rotate:0,
    },

**Comment by guochengwei** [comment]
楼上的方法在cotainLabel = true的情况下 label会全被压缩至左上角,而且图表无法正常显示
![Uploading image.png…]()
把魔法方法值padding:[0,-10]改成
padding:[0,-10,0,-10]就好了

**Comment by territoryfan** [comment]
@Nsrfc 像楼上说的，一般是正常是旋转角度 或者 省略号显示 ，不知是否能帮到你   https://github.com/territoryfan/echarts
