### ISSUE TITLE
Echarts doesn't show legend colors on Firefox

### ISSUE THREAD

**Issue by hiltonmbr** [apache/incubator-echarts#7174]
Echarts doesn't show legend colors on Firefox Quantum 57.0.1.

Example:
https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-negative

Echarts 3.8.5
Firefox Quantum 57.0.1

Any ideas?

Thanks in advance!

**Comment by pissang** [comment]
Can't repeat the issue on my firefox quantum. Any more details will be helpful to us.
