### ISSUE TITLE
【求教】如果获取到legend的高度？

### ISSUE THREAD

**Issue by Erimus-Koo** [apache/incubator-echarts#7175]
- legend数量较多，且长度不统一。
- 横向排列，高度每次也会变化。
- 布局是上方grid，下方legend。
- 想要获取legend高度，然后设置给grid.bottom。防止legend和grid重叠。

请问能获取到吗？

**Comment by ericWenjp** [comment]
你好，请问这个问题解决了吗

**Comment by Erimus-Koo** [comment]
@ericWenjp 后来通过直接读取canvas像素点颜色的方式解决了。
- 获取legend前的icon位置，确认legend高度。
- resize grid。
