### ISSUE TITLE
【问题】echarts的触控不受父级容器的变形影响

### ISSUE THREAD

**Issue by Erimus-Koo** [apache/incubator-echarts#7176]
# 需求
- 在微信等手机浏览器下，视觉效果需要横屏显示。
- 如果手机是竖屏，则自动旋转90度显示。
- 这样一方面提示用户要横过来观看，同时万一用户锁屏也避免一次解锁。

# 问题
- 父容器旋转90度，echart显示旋转成立。
- 但是显示旋转之后，触控互动部分并未旋转。
- 该情况只发生在移动端，PC端chrome没问题，模拟手机就不行。手机真机上也不行。

![gif](https://user-images.githubusercontent.com/17139670/33527834-55050a24-d892-11e7-9f37-2a137bb6aa66.gif)

上述动画实际的点击点，其实依次是画面上侧：
- 0.5~1的格子
- 1.5~2的格子
- 2.5~3的格子

# 范例
[【点这里】](http://erimus.cc/weibo_memory/test.min.html) 
电脑上，需要把浏览器窗口调成高度大于宽度，自动旋转90度显示。
或者扫码
![](http://qr.liantu.com/api.php?w=400&text=http:%2F%2Ferimus.cc%2Fweibo_memory%2Ftest.min.html)

可以操作测试legend点击（顶部），或tooltip点击（表格内）。  
都在大约逆时针90度的左上角，不可见的对应区域。  
仅移动端有问题，桌面端就没问题。

# 建议
说实话这个应该算是canvas本身的问题吧。
### echarts能不能考虑加一个【全局旋转】的选项？
或者有什么办法直接在绘制的时候就把画面和触控逻辑都转过来？
还是有什么其他解法嘛？

**Comment by MrLiZ** [comment]
有解决吗？

**Comment by Erimus-Koo** [comment]
@MrLiZ 没呀，暂时放弃自适应朝向了。
