### ISSUE TITLE
错误的圆形显示

### ISSUE THREAD

**Issue by pk111and222** [apache/incubator-echarts#7183]
### One-line summary [问题简述]
页面使用中出现不光滑的突出

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:chrome62
+ OS Version [操作系统类型和版本]:win10

期望得到平滑的圆形
<img width="334" alt="wx20171204-175141 2x" src="https://user-images.githubusercontent.com/12478570/33546795-f02f8c10-d91c-11e7-8780-92c0b310fe57.png">

**Comment by pissang** [comment]
可以跟我们贴下你的 option 么？
