### ISSUE TITLE
双坐标 　markarea无效

### ISSUE THREAD

**Issue by PosseWang** [apache/incubator-echarts#7186]
### One-line summary [问题简述]

两个坐标 　markarea设置只显示最后一个

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请具体描述你的问题
