### ISSUE TITLE
How to hide series data if another series data not set ?

### ISSUE THREAD

**Issue by l2aelba** [apache/incubator-echarts#7189]
Example I have **2 series datasets**

```
series: [
   {
     name: 'A',
     data : [1, 2, 3]
   },
   {
     name: 'B',
     data : [1, 2, 3, 4]
   }
]
```

![screen shot 2017-12-04 at 12 05 53](https://user-images.githubusercontent.com/983458/33549656-88aab366-d8eb-11e7-9cd5-c331c028597d.png)

**Serie A** is a main and you see **serie** B has more data length than **serie A**
Im looking for some config something like "Dont show if another data set is empty"
(In the real world (screenshot) the last red dot will not be shown)

Thanks so much.

**Comment by pissang** [comment]
You can process the data outside.

In your case:
```js
var len = Math.min(dataA.length, dataB.length);
dataA.length = dataB.length = len;
...
series: [
   {
     name: 'A',
     data : dataA
   },
   {
     name: 'B',
     data : dataB
   }
]
```

**Comment by l2aelba** [comment]
Thanks @pissang. But my case is a bit more harder.

Does not eCharts has a native option for that ?

**Comment by pissang** [comment]
No proper option yet. Will improve it later:)

**Comment by l2aelba** [comment]
@pissang Aha thanks, I think this is useful feature :D

**Comment by l2aelba** [comment]
@pissang Any good new ?
