### ISSUE TITLE
折线图：默认选中第一条数据，即初始化图表时，第一条数据是被选中状态？效果如图

### ISSUE THREAD

**Issue by JsonShare** [apache/incubator-echarts#7197]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.7
+ Browser version [浏览器类型和版本]: chrome 60
+ OS Version [操作系统类型和版本]:  windows7 

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/19481829/33593063-ada6a778-d9c8-11e7-8f5f-972f7155541f.png)

**Comment by JsonShare** [comment]
@leeight

**Comment by JsonShare** [comment]
@leeight  能帮忙解决不？ O(∩_∩)O谢谢

**Comment by KobeBryant824** [comment]
有方案没
