### ISSUE TITLE
怎么进行省市县镇这个四级的下钻？

### ISSUE THREAD

**Issue by codertanp** [apache/incubator-echarts#7199]
目前下钻只能做到：
      1、全国地图 ---->省---->市
      2、全国地图 ---->直辖市
但是在实际中很多地方要用到    市下面一级或者两级  的行政区域，在网上找不到市下面一二级对应的json数据
我看了json的格式：
id:ID
type: ?
geometry: ?
	type:？
	coordinates:[xx]？
	encodeOffsets:[xx,xx]？
properties:
	cp:[xx,xx]
	name:'名称'
	childNum:下级数量
其中coordinates是一个加密串还是啥？官方为什么没有提供呢？是因为这个是开源免费的吗，所以没有做的更加详细呢。
    要是有人知道希望可以给我指教一下，2953646681，不胜感激 ~V~

**Comment by chfw** [comment]
Coordinates是用了UTF8 篇码 是是可以解码的

**Comment by nspers** [comment]
乡镇数据只能自己找或者买, 编码问题可以参考我提的问题: #7561
