### ISSUE TITLE
3.0版本 toolbox中设置orient: 'vertical'时文字不会居左和居右

### ISSUE THREAD

**Issue by IceButterfly** [apache/incubator-echarts#7201]
### One-line summary [问题简述]
文字会出现在图标的下方,遮盖下面的图标,官网实例就可以看到这个问题的
http://echarts.baidu.com/demo.html#bar-label-rotation

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by haojian20161987** [comment]
打扰下，请问你demo 右上角的close panel是怎么实现的啊？对应左边的哪些代码啊？我看了几遍，都没找到对应的API设置

**Comment by IceButterfly** [comment]
configParameters这个啊,左边对应1-37行,这个是官方实例哈

**Comment by pissang** [comment]
这个暂时还没解决方案，建议过小的 bar 不显示文字

**Comment by haojian20161987** [comment]
我现在是在用webpack vue引用echarts，希望能够在右上角显示一个http://echarts.baidu.com/demo.html#bar-label-rotation 和这个demo右上角相同的close panel，该如何实现啊？

**Comment by pissang** [comment]
@haojian20161987 右上角的我们用了 https://github.com/dataarts/dat.gui 这个组件

**Comment by haojian20161987** [comment]
谢谢

**Comment by pissang** [comment]
@IceButterfly toolbox 好像是有这个问题，后面会优化

**Comment by IceButterfly** [comment]
好的
