### ISSUE TITLE
数值轴中是否可以间隔显示label和tick

### ISSUE THREAD

**Issue by chaserstrong** [apache/incubator-echarts#7205]
类似图中这样子的demo，请问能在数值轴中实现吗？
![image](https://user-images.githubusercontent.com/18061322/33657819-64ba5238-dab5-11e7-88db-2930865b9d24.png)

**Comment by pissang** [comment]
数值轴是根据给定的 splitNumber 自动划分刻度

**Comment by chaserstrong** [comment]
@pissang 主要就是像图中，我splitNumber 给4的话，D,L,R,W就出不来了。 如果给8的话，就会出现多余的tick

**Comment by chaserstrong** [comment]
@pissang  请问有办法吗？
