### ISSUE TITLE
雷达图中series.data 里面的 label.normal 设置显示标签时，可否让每一个显示标签都在雷达图数值的外侧

### ISSUE THREAD

**Issue by luckFine** [apache/incubator-echarts#7220]
雷达图中series.data 里面的 label.normal 设置显示标签时，可否让每一个显示标签都在雷达图数值的外侧
，查了API，position里面可以设置left，right，top，bottom，inside等等，我想把显示标签显示在外侧，

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

<img width="456" alt="2017-12-08 10 24 03" src="https://user-images.githubusercontent.com/24777461/33748174-fc1e645a-dc01-11e7-9c91-75f50523d1a4.png">

position里面可以设置left，right，top，bottom，inside等等，但是我想要类似outside的样式，请问如何设置
这样得到的结果如下
<img width="130" alt="2017-12-08 10 28 42" src="https://user-images.githubusercontent.com/24777461/33748290-99c68c50-dc02-11e7-9af8-8a13ef1f6453.png">

我想要的结果如下
<img width="287" alt="2017-12-08 10 07 56" src="https://user-images.githubusercontent.com/24777461/33748120-bc85385a-dc01-11e7-9560-306be8241d31.png">

**Comment by zhangyao-zy** [comment]
请问解决了吗 我也遇到了类似的问题
