### ISSUE TITLE
echarts3 折线图 动态加载 内存问题

### ISSUE THREAD

**Issue by 785160953** [apache/incubator-echarts#7237]
### One-line summary [问题简述]
我是用的是echarts3.8.4，动态加载数据，使用折线图的话切出浏览器当前标签之后，echarts的那个浏览器页面的内存就会一直往上涨，知道浏览器崩溃，测试过火狐、猎豹、谷歌浏览，都是这样的；
但是转成柱状图的话，就不会有上述现象！！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有具体的可以复现的项目文件么？

**Comment by 785160953** [comment]
不好意思，前几天忘记看了；你可以看一下这个页面https://ylyn.xihc.xin/jvmInfoPage.html，里面的接口都是支持跨域请求的，你也可以单独是试一下；
打开这个页面后，切换到其他标签页，或者把浏览器最小化，过一会那个标签页的内存就会慢慢网上涨

**Comment by 785160953** [comment]
不再了吗？

**Comment by 785160953** [comment]
你好，请问现在怎么样了？
 echarts4.0还有这个问题吗？

**Comment by pissang** [comment]
4.0.2 中有修复的一个可能会造成内存泄漏的问题。https://github.com/ecomfe/zrender/commit/bffd892b005035b5abcfab108ab2449861f23a85

**Comment by 785160953** [comment]
好的，我回头也试一下

**Comment by pissang** [comment]
@785160953 最近在测试水球图内存泄漏的过程中（见 https://github.com/ecomfe/echarts-liquidfill/issues/28）发现只要有使用 Canvas 的 clip 方法，就可能会有内存泄漏（带动画的折线图和水球图都有用到这个方法），还没定位到具体的原因和解决方案，很可能是 chrome 底层实现的问题，如果是的话就比较难办了，目前有一个可行的解决方案是对折线图改用 svg 渲染

**Comment by oldRabbitForz** [comment]
> 有具体的可以复现的项目文件么？

demo哥，你不是在要demo，就是在要demo的路上
