### ISSUE TITLE
geo极系地图组件点击下钻怎么获取数据比如id和name

### ISSUE THREAD

**Issue by PolanZ** [apache/incubator-echarts#7244]
地图已经注册：echarts.registerMap(name, geojson);
地图渲染成功下
比如下面我定制的geo option

### One-line summary [问题简述]
当想要点击下钻下一级区域，比如点击广州，那么这时，我需要获取到广州的名称和ID，但是看了点击事件里event只要名称。这个时候怎么办？

想过在series里，添加一层map组件，但是这里又产生另外的问题，就是我需要滚动放大缩小的，两个图层就会有bug，当你鼠标放在地图上，只要放大缩小map组件（这时也想到去控制滚动事件，去触发geo的放大缩小，但是太麻烦了）。

### ECharts option [ECharts配置项]

```javascript
var regData = [{id: 200, name: '广州市'}, .......],
     nameMap = {200: '广州市', ........}
option = {

geo: {
              show: true,
              type: 'map',
              map: '广东省',
              nameMap: nameMap,
              regions: regData,
              roam: true,
              label: {
                normal: {show: false},
                emphasis: {
                  show: false
                }
              },
              itemStyle: {
                normal: {
                  areaColor: 'rgba(255,255,255,0)',
                  borderWidth: 1,
                  borderColor: '#7AC6FF'
                },
                emphasis: {
                  areaColor: 'rgba(255, 255, 255, 0)'
                }
              }
            }
}

```

![2a4ea68d-66d2-4f9d-95a2-aecc8d00a399](https://user-images.githubusercontent.com/8565486/33865614-71e90b80-df2d-11e7-8844-f0e1bd817ec1.png)
从图片上找不到ID，只有个name，怎么弄才有ID呢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.3.0
+ Browser version [浏览器类型和版本]:  Any
+ OS Version [操作系统类型和版本]: Any

**Comment by xu8117** [comment]
请问怎么解决的
