### ISSUE TITLE
svg渲染的饼状图，在手机上单击的时候会出现svg大小的轮廓阴影，请问是什么原因，怎么去掉呢？

### ISSUE THREAD

**Issue by changbb** [apache/incubator-echarts#7247]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
我会跟进一下，谢谢反馈！

**Comment by changbb** [comment]
我整明白是什么原因了 svg渲染的时候会自动生成一个父极元素div 这个轮廓的阴影也就是div的点击效果
 给div{ 
     -webkit-tap-highlight-color:rgba(255,255,255,0);
}
设置即可

**Comment by Ovilia** [comment]
谢谢，后面会在 ECharts 里设置一下！

**Comment by Ovilia** [comment]
@changbb 请问是给哪个 div 设置？我试了 svg 和 svg 的父元素，好像都没用

**Comment by ahfychangbb** [comment]
svg渲染，用的是div标签！ 插件会自动生成svg元素，同时还会生成一个直接父极div  你只要给这相关的div都设置就是了  你可以调试下 看看  到底是哪个div在影响！
