### ISSUE TITLE
散点图超出Gird部分hide的优化建议。

### ISSUE THREAD

**Issue by sdtazhanghe** [apache/incubator-echarts#7254]
### One-line summary [问题简述]

1.当我们在绘制散点图时，将散点大小进行visualMap映射。
2.对于靠近轴的数据，则默认会覆盖到坐标轴上面。
3.这时有两种思路处理：
     思路1：调整Axis坐标轴的z属性，使其大于series的z属性。
     思路2：将series的symbolOffset设置为['50%', '50%']。
         tips：思路2有个缺点就是当我右侧或上侧存在别的绘制元素，比如图例、数据映射控制器等，仍然会被气泡覆盖。
4.优化思路（或者说可以提供的思路）。
      在series中添加一个属性overFlowGrid: hide/show,当hide时， 超出直角坐标部分的散点进行截取处理。
![1](https://user-images.githubusercontent.com/28133347/33895236-052ddf3e-df9b-11e7-9301-e472cdb51c76.png)
![2](https://user-images.githubusercontent.com/28133347/33895237-05635c2c-df9b-11e7-9e96-9309e74a8e60.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这样会很奇怪，你可以试试给坐标轴加上 boundaryGap

**Comment by sdtazhanghe** [comment]
bug描述
![3](https://user-images.githubusercontent.com/28133347/33921523-57dc5c60-dfff-11e7-91f2-b1fbda261b87.png)
web端 使用Echarts
![1](https://user-images.githubusercontent.com/28133347/33921525-59ad2452-dfff-11e7-9f68-a46bfd15ca1d.jpg)
手机端 未使用Echarts
![2](https://user-images.githubusercontent.com/28133347/33921527-5b1e66c0-dfff-11e7-8ec9-67c45596f346.jpg)
我找产品经理再去撕一下逼吧。。。。

**Comment by sdtazhanghe** [comment]
如果有余力的话，希望还是加上吧，虽然产品经理撕逼成功，但是这种遮挡问题的确对于一些人（产品经理）来说不是很满意。
![1](https://user-images.githubusercontent.com/28133347/33972659-f67c6116-e0b9-11e7-9248-f8d8b0e9e4a8.png)
![2](https://user-images.githubusercontent.com/28133347/33972662-f8e4275e-e0b9-11e7-87f5-b0ac8de8702d.png)
![3](https://user-images.githubusercontent.com/28133347/33972663-fa6873f0-e0b9-11e7-9b93-b975b2c7b46e.png)

**Comment by chenweihao-demo** [comment]
使用自定义图表custom，它的clip属性会裁剪超出坐标轴的部分，这是例子
`var categoryData = [];
var errorData = [];
var barData = [];
var dataCount = 100;
for (var i = 0; i < dataCount; i++) {
  var val = Math.random() * 1000;
  categoryData.push('category' + i);
  errorData.push([
    i,
    echarts.number.round(Math.max(0, val - Math.random() * 100)),
    echarts.number.round(val + Math.random() * 80)
  ]);
  barData.push(echarts.number.round(val, 2));
}
option = {
  tooltip: {
    trigger: 'item',
    axisPointer: {
      type: 'shadow'
    }
  },
  title: {
    text: 'Error chart'
  },
  legend: {
    data: ['error']
  },
  xAxis: {
    data: categoryData
  },
  yAxis: {},
  series: [
    {
      type: 'custom',
      name: 'error',
      itemStyle: {
        borderWidth: 1.5
      },
      clip: true,
      renderItem: function (params, api) {
        var xValue = api.value(0);
        var highPoint = api.coord([xValue, api.value(1)]);
        var lowPoint = api.coord([xValue, api.value(2)]);
        var halfWidth = api.size([1, 0])[0] * 0.1;
        var style = api.style({
          stroke: api.visual('color'),
          fill: api.visual('color'),
        });
        return {
          type: 'circle',
          transition: ['shape'],
          shape: {
            cx: highPoint[0],
            cy: highPoint[1],
            r: 10
          },
          style: style
        };
      },
      data: errorData,
      z: 100
    }
  ]
};`
![image](https://user-images.githubusercontent.com/47056630/183231300-980c8c83-05b7-4c1d-96fa-96ddb9165200.png)
