### ISSUE TITLE
移动端部分浏览器在图表区域左右滑动会触发浏览器翻页事件

### ISSUE THREAD

**Issue by wyc3146** [apache/incubator-echarts#7258]
### One-line summary [问题简述]
我们用echarts画折线图嵌入页面，发现在图表区域左右滑动会触发大部分浏览器的翻页事件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]:搜狗5.8.0
+ OS Version [操作系统类型和版本]:安卓

### Expected behaviour [期望结果]
在图表区域左右滑动只会移动图标内的光标，不会出发浏览器翻页事件。在图表内上下滑动依旧可以滑动页面

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你可以试试用 event.preventDefault()
