### ISSUE TITLE
中国地图定时设置setOption之后，绑定在map上的click时间会被重复触发

### ISSUE THREAD

**Issue by vercha** [apache/incubator-echarts#7260]
### as titled, 中国地图设置setOption之后，绑定在map上的click时间会被重复触发

在echart上绑定click事件，单击某一省市跳转；
echart的itemstyle颜色通过一个setInterval()多次setOption（为了实现地区闪烁需求）;
问题：单击某一省市，会多次触发click事件；
测试排查：将setInterval()的时间间隔调到五分钟，问题依然存在；

环境： vue2 ；  echarts3  China map

### 不清楚map上的click事件怎么实现的，有没有什么办法可阻止单击该地区多次跳转？
谢谢！

setInterval()中setOption()只有series->data->itemstyle不同；

**Comment by pissang** [comment]
什么版本的 ECharts？

**Comment by vercha** [comment]
echarts@3.8.5

**Comment by kyriejoshua** [comment]
在使用 echarts-gl 最新版和这个 echarts 3.8.5 时也有问题，目前排查发现是series里和geo3D等不同的 zlevel 导致的。有多少个不同的 zlevel 就会调用几次click。
