### ISSUE TITLE
地图显示位置偏差

### ISSUE THREAD

**Issue by TonyChenJT** [apache/incubator-echarts#7269]
### One-line summary [问题简述]
使用国标的经纬度，在用echarts联合百度地图显示出来的位置很是有偏差

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望echarts能直接转换百度的经纬度显示正确的位置 最好能达到实时标准的要求

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
百度地图的坐标有偏移，需要转换一下

**Comment by TonyChenJT** [comment]
百度的转换公式是不对外开放的而且，用户每天转换还有数量的限制，如果十分钟显示几万条数据 的话，时间是来不及的

**Comment by TonyChenJT** [comment]
百度的转换公式是不对外开放的，而且用户每天转换还有数量的限制，如果十分钟显示几万条数据 的话，时间是来不及的

**Comment by pissang** [comment]
@TonyChenJT 抱歉这点我们也没办法
