### ISSUE TITLE
tree图不支持鼠标滚轮放大缩小

### ISSUE THREAD

**Issue by yokiyokiyoki** [apache/incubator-echarts#7271]
### One-line summary [问题简述]

tree图的径向布局不支持拖拽和鼠标滚轮放大缩小

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:chrome62
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
期望能参考graph图，可以开启拖拽或者鼠标滚轮放大缩小的功能

**Comment by tourze** [comment]
关注这个问题

**Comment by XXHJ** [comment]
同关注

**Comment by Deval520** [comment]
关注 tree不支持缩放真的有点失望

**Comment by deqingli** [comment]
This feature is supported with this [configuration](https://www.echartsjs.com/zh/option.html#series-tree.roam) `series-tree.roam`
