### ISSUE TITLE
怎么查看echarts.min.js和 echarts-gl.min.js的版本， 有没有接口， 比如echarts.version

### ISSUE THREAD

**Issue by succulen-plants** [apache/incubator-echarts#7272]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts.version

**Comment by UpAndDowns** [comment]
在项目引用echarts的地方使用console.log(echarts.version),或者在项目的前端页面（F12）console处输入console.log(echarts.version)
