### ISSUE TITLE
Polar坐标系,曲线径向渐变的圆心如何确定，目前看来是和数据有关的。。。求指导 

### ISSUE THREAD

**Issue by mayLong** [apache/incubator-echarts#7283]
### One-line summary [问题简述]

目前的情况看来，径向渐变是根据图形包围盒的大小来确定圆心的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
是否支持圆心不根据图形包围盒的大小变化

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
默认是在图案中心，可以具体一点你的问题吗？

**Comment by mayLong** [comment]
@Ovilia 我的意思是由于数据是变化的，造成图案的中心点也是变化的 。而我期望的结果是径向的圆点是在容器的中心点，而不是绘制图案的中心点。这样可以有实现方案么？

**Comment by xing00** [comment]
@Ovilia 使用雷达图遇到同样的问题，请问解决了吗？如下图所示，我的渐变中心想要在坐标轴的正中心，而不是填充区域的中心，请问能实现吗？
<img width="363" alt="2018-09-06 8 41 39" src="https://user-images.githubusercontent.com/7943928/45158059-76ae6c80-b215-11e8-9754-2d26647eb5ee.png">
