### ISSUE TITLE
多棵树的自适应问题

### ISSUE THREAD

**Issue by Bbbzhao** [apache/incubator-echarts#7296]
### One-line summary [问题简述]
查阅了官方的多棵树例子，多棵树是通过设置组件离容器的距离放置在页面中，假设离容器的距离设置不合理，树与树会发生重叠。

官方例子:
http://echarts.baidu.com/demo.html#tree-legend

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.X
+ Browser version [浏览器类型和版本]:chrome etc...
+ OS Version [操作系统类型和版本]:Windows

### Expected behaviour [期望结果]
在一个容器中，多棵树可以依据自己的大小，自动分配容器中的位置，树与树不会发生重叠。

**Comment by XXHJ** [comment]
赞 我也是觉得需要计算不合理
