### ISSUE TITLE
如何将y轴的名字显示在柱状图的每个条块的上方

### ISSUE THREAD

**Issue by AboyL** [apache/incubator-echarts#7309]
### One-line summary [问题简述]
一个柱状图
x轴是刻标尺
Y轴是各项名称，现在我想把y轴的名称显示到每个条块的上方，并且把每个条块的值显示在条块里面应该怎么实现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
设置柱状图的 label

**Comment by AboyL** [comment]
但是这个样子值跟名字是在一个纬度的
我现在希望的是条的上方显示名字，里面最右端显示值
