### ISSUE TITLE
tree 动态删除数据，第二次删除后无法渲染，报异常

### ISSUE THREAD

**Issue by sunxiongwei** [apache/incubator-echarts#7315]
### One-line summary [问题简述]
动态删除数据，第二次删除后无法渲染，报异常

为了简单复现，可以每次删除根节点的第一个子节点:
 root.children.splice(0, 1);
tab.treeChart.setOption($scope.getTreeDate(root), true);

第二次后开始报错

### Version & Environment [版本及环境]
+ ECharts version3.8.5 [ECharts 版本]:
+ Browser version  Chrome 版本 63.0.3239.84（正式版本） [浏览器类型和版本]:
+ OS Version  MAC [操作系统类型和版本]:

### Expected behaviour [期望结果]

解决

### ECharts option [ECharts配置项]

```javascript
option = {

                tooltip: {
                    trigger: 'item',
                    triggerOn: 'mousemove'
                },
                series: [
                    {
                        type: 'tree',
                        data: [data],
                        top: '1%',
                        left: '7%',
                        bottom: '1%',
                        right: '20%',
                        symbolSize: 17,
                        label: {
                            normal: {
                                position: 'left',
                                verticalAlign: 'middle',
                                align: 'right',
                                fontSize: 15
                            }
                        },
                        leaves: {
                            label: {
                                normal: {
                                    position: 'right',
                                    verticalAlign: 'middle',
                                    align: 'left'
                                }
                            }
                        },

                        expandAndCollapse: true,
                        animationDuration: 550,
                        animationDurationUpdate: 750
                    }
                ]
            
}

```

**Comment by sunxiongwei** [comment]
添加 treeChart.clear(); 不在出现异常

**Comment by gaoshijun1993** [comment]
@sunxiongwei clear会清空实例中的数据，这样的话做不到局部更新数据，假如有很多子节点，默认一些子节点是被折叠的，手动展开这些子节点后向某个子节点下添加一个子节点，那么clear后重绘，这些子节点就又会被折叠了。理想的展示效果是局部更新节点，或者说是能够记住节点的折叠状态

**Comment by pissang** [comment]
@gaoshijun1993 嗯，这个是现在临时的 workaround，新版本会修复这个 bug

**Comment by RobotJiang** [comment]
看了一下是因为node已经被移除，但是还在使用未移除时的索引造成的；找到了一个办法可以暂时Fix这个问题：
1，找到源代码下面的这个文件：echarts/src/chart/tree/TreeView.js
2,  找到 removeNode 方法，在无法找到node的时候，重新给node赋值
![image](https://user-images.githubusercontent.com/501182/35210681-22c71c00-ff8e-11e7-88ee-fa7a059de219.png)

**Comment by deqingli** [comment]
@sunxiongwei 你好，这个问题已经解决了，会随下个版本一起发布。欢迎验证，如果有问题可以 reopen 这个 issue，再次感谢给我们提建议！
