### ISSUE TITLE
嵌套环形图超过100%的友好显示

### ISSUE THREAD

**Issue by zhanjiejun** [apache/incubator-echarts#7316]
### One-line summary [问题简述]

Echarts嵌套环形图当计算的百分比超过100%时会出现下图的效果

![image](https://user-images.githubusercontent.com/17893732/34157106-1ba75302-e4fb-11e7-98f7-8c417363c2ad.png)

是否能处理成下图的效果
![image](https://user-images.githubusercontent.com/17893732/34157046-cf640238-e4fa-11e7-9379-de36cd4e8587.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by shiwanjun1995** [comment]
我有个需求和你这个一模一样，都过去6年了，官方示例也木有看到，请问实现了吗，这个场景还蛮常见的。
@pissang

**Comment by shiwanjun1995** [comment]
> ### One-line summary [问题简述]
> Echarts嵌套环形图当计算的百分比超过100%时会出现下图的效果
> 
> ![image](https://user-images.githubusercontent.com/17893732/34157106-1ba75302-e4fb-11e7-98f7-8c417363c2ad.png)
> 
> 是否能处理成下图的效果 ![image](https://user-images.githubusercontent.com/17893732/34157046-cf640238-e4fa-11e7-9379-de36cd4e8587.png)
> 
> ### Version & Environment [版本及环境]
> * ECharts version [ECharts 版本]:
> * Browser version [浏览器类型和版本]:
> * OS Version [操作系统类型和版本]:
> 
> ### Expected behaviour [期望结果]
> ### ECharts option [ECharts配置项]
> ```js
> option = {
> 
> }
> ```
> 
> ### Other comments [其他信息]

请问您这边后来是如何设置的呀。
我这个需求和你简直一摸一样。哈哈哈
![img_v2_936067aa-48b4-4e13-bc84-b6111b5715bg](https://github.com/apache/echarts/assets/38515714/925beb86-aae7-4e4a-bab8-cbbb41fab62a)
