### ISSUE TITLE
Gauge xAxis triggerEvent doesn't work

### ISSUE THREAD

**Issue by Alexpri** [apache/incubator-echarts#7328]
Could you help me and explain, why series gauge tooltip doesn't show even if I triggerEvent change to true

{

      // Add tooltip
      legend: {
        type: 'scroll',
      },
      tooltip: {
        // show:false,
        formatter(props) {
          console.log(false);
          const contentText = `
            ${props.data.name}<br>
            Target: ${props.data.target}<br>
            Generated: ${props.data.generated}
          `;

          return contentText;
        }
      },
      xAxis: {
        triggerEvent: true,
      },

      // Add series
      series: seriesData,
    };

**Comment by pissang** [comment]
gauge don't have xAxis
