### ISSUE TITLE
漏斗图怎么实现两个标识 如图

### ISSUE THREAD

**Issue by xuan1024** [apache/incubator-echarts#7335]
![tim 20171221105102](https://user-images.githubusercontent.com/22511126/34238509-f6c4cb80-e63c-11e7-9083-47c0d916b648.png)

echarts3 .8 我该怎么实现如图的效果， 找了很多资料都没有实现这个效果， 请帮我解答一下

**Comment by Ovilia** [comment]
左侧的文字可以自己用 DOM 实现吗？

**Comment by Erimus-Koo** [comment]
画两遍漏斗图
