### ISSUE TITLE
Width on bar series is incorrect on some case with barGap set to '-100%' (overlap the bar)

### ISSUE THREAD

**Issue by genezx** [apache/incubator-echarts#7356]
### One-line summary [问题简述]
有两个以上系列的柱状图通过barMaxWidth限定宽度，同时设置barGap:"-100%"重叠时，在特定宽度和特定密度下，整个柱状图会变形错位。
示例见 http://gallery.echartsjs.com/editor.html?c=xB1-s6MCMz
例子中有25列，柱子宽度限定为20像素。
当列数是25列时，浏览器宽度在大约1312至1780像素的情况下，两系列宽度不同且错位；浏览器宽度过小或过大均正常。
当列数是15列时，浏览器宽度在大约1000至1280像素的情况下，两系列宽度不同且错位；浏览器宽度过小或过大均正常。
由于目前主流屏幕分辨率均在以上范围内，该BUG影响范围还是挺广的，希望能尽快修复。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0.0-3.8.4
+ Browser version [浏览器类型和版本]: 所有浏览器
+ OS Version [操作系统类型和版本]: 所有操作系统

### Expected behaviour [期望结果]
两系列所有柱子宽度一致，不错位，分别完美重叠。

### ECharts option [ECharts配置项]

```javascript
var cat = [];
var data3 = [];
var data4 = [];
var days = 25;
for (var i = 0; i < days; i++) {
    cat.push(i);
    data3.push(i * 2);
    data4.push(50 - i * 2);
}
option = {
    title: {
        name: "数据纯属虚构"
    },
    tooltip: {
        trigger: "axis",
        axisPointer: {
            type: "shadow"
        }
    },
    xAxis: {
        type: "category",
        data: cat,
        interval: 1,
    },
    yAxis: {
        type: "value",
        min: 0,
    },
    series: [
        {
            type: "bar",
            name: "系列3",
            barMaxWidth: 20,
            data: data3,
        }, {
            type: "bar",
            name: "系列4",
            barMaxWidth: 20,
            data: data4,
            barGap: "-100%",
        }
    ],
}

```

**Comment by genezx** [comment]
4.0.0仍未修复。

错误结果：
![Uploading false.png…]()

期望结果：
![true](https://user-images.githubusercontent.com/31116612/34978158-4326c636-fad8-11e7-8970-deb65b6d3765.png)

**Comment by SuperAL** [comment]
同上，目前的效果是这样的：http://gallery.echartsjs.com/editor.html?c=xrkpVNZkIf&v=1
希望自适应的同时两个柱状图宽度一致。

**Comment by SuperAL** [comment]
@pissang

**Comment by tumblingG** [comment]
这个bug2017年就提出来了，怎么就没人解决呢？
