### ISSUE TITLE
candlestick 如何时时显示最后价格？

### ISSUE THREAD

**Issue by nullmu0** [apache/incubator-echarts#7367]
最高价 最低价能够显示出来  怎么显示最后价格呢？ 其他candlestick工具都有的功能

**Comment by pissang** [comment]
显示在哪？

**Comment by junjun16818** [comment]
![image](https://user-images.githubusercontent.com/955472/34389677-125e2268-eb76-11e7-8ad8-f0e80485107e.png)

**Comment by pissang** [comment]
最后的那个数据设置成 label: { normal: { show: true: } }

**Comment by junjun16818** [comment]
![image](https://user-images.githubusercontent.com/955472/34411968-47513c5e-ec15-11e7-9a5f-91ce7782bfe2.png)

我没有找到这个属性

**Comment by junjun16818** [comment]
![image](https://user-images.githubusercontent.com/955472/34412408-0ed87ba0-ec18-11e7-9374-baaf1e7094be.png)
是这么写吗？
