### ISSUE TITLE
如何改变sankey数据在X轴和Y轴方向上的位置

### ISSUE THREAD

**Issue by greyfeather0707** [apache/incubator-echarts#7369]
### One-line summary [问题简述]

不知道如何将d1的数据移动到蓝色框位置？
如何将数据按在x，y轴两个方向上自由放置，比如：
将d2放d1的上面，同时在x轴上的第二个位置，，

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:ECharts3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![360 20171227104306848](https://user-images.githubusercontent.com/26019575/34369252-3f04665a-eaf5-11e7-90f8-76e7c425ee24.jpg)

**Comment by AaronAlphabet** [comment]
@deqingli  不是拖拽的问题，是在生成图形的时候感觉应该在上面的图形，却跑到了下面的位置

**Comment by deqingli** [comment]
#6365
