### ISSUE TITLE
IE 10 及以下 兼容热力图么？

### ISSUE THREAD

**Issue by ycyucan** [apache/incubator-echarts#7376]
### One-line summary [问题简述]

http://gallery.echartsjs.com/editor.html?c=heatmap-map  官方事例 在IE10 上会报错。。请问是echart 热力图不兼容还是什么原因?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
报什么错？

**Comment by ycyucan** [comment]
@pissang 
![image](https://user-images.githubusercontent.com/18187084/34397663-fc2f4a3e-ebb2-11e7-9684-619c80461828.png)

**Comment by isence** [comment]
@ycyucan 解决了么，同样遇到的问题

**Comment by cpla13** [comment]
直接修改源码,那个报错的是ie11的才有，把那个替换成Uint8Array，我是这样解决的，或者写一个兼容的出来，我这样暴力一点

**Comment by cpla13** [comment]
@ycyucan @isence @pissang
