### ISSUE TITLE
chart图表旋转90度后点击每个里面的选项对应不上，有老铁遇到过这个问题么，有解决的么？

### ISSUE THREAD

**Issue by zhuzhensuo** [apache/incubator-echarts#7381]
比如说一个柱状图，正常情况下点击每个柱子tooltip会显示具体的信息，但是把这个柱状图整体transform:rotate(90deg)之后就不能正确点击每个柱子了，信息显示很混乱，我这样说你们能懂我意思吧？有老铁遇到过并解决了这个问题的么，有点话能告诉 我解决方案么，我会给你喊666。。。

**Comment by MrLiZ** [comment]
有解决吗？

**Comment by MrLiZ** [comment]
@Dowgen 没呢，直接用横屏了，不旋转了。

**Comment by zhuzhensuo** [comment]
把echart写在iframe 然后旋转iframe就可以了
