### ISSUE TITLE
实现echarts刻度轴的二级刻度的问题

### ISSUE THREAD

**Issue by bankly** [apache/incubator-echarts#7389]
目前版本好像 没有设置二级刻度的地方
![](http://img.blog.csdn.net/20170904112711251?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvbXVsdW1lbmc5ODE=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**Comment by pissang** [comment]
嗯，暂时还不支持 minor ticks

**Comment by Ovilia** [comment]
Duplicate of #7840 .
