### ISSUE TITLE
How to drag and zoom in Tree chart?

### ISSUE THREAD

**Issue by leesangboo** [apache/incubator-echarts#7399]
How to drag and zoom in Tree chart?

I cant found drag and zoom option in tree chart model.

**Comment by DennisGuo** [comment]
+1

**Comment by deqingli** [comment]
Hi all, This feature is currently under development and will be released as soon as possible. Thank you for your suggestions.

**Comment by jiehu567** [comment]
Hi, any update with this feature?

**Comment by rtrompier** [comment]
+1

**Comment by 100pah** [comment]
releasing in this week.

**Comment by MarkEhr** [comment]
Hi, was this merged? Is there any documentation about this?

**Comment by B-Esmaili** [comment]
any update on this?it's two years later.

**Comment by deqingli** [comment]
Hi all, we have already supported this feature, you can configure `roam: true` in `series.tree`. So I will close this issue if you have any other question you can reopen this issue.

**Comment by taylorfullstack** [comment]
> Hi all, we have already supported this feature, you can configure `roam: true` in `series.tree`. So I will close this issue if you have any other question you can reopen this issue.

Hello, the option roam: true makes drag and zoom work on desktop, but not on touch devices.
