### ISSUE TITLE
如何显示被跳过刻度对应的拐点？

### ISSUE THREAD

**Issue by nilptr** [apache/incubator-echarts#7403]
### One-line summary [问题简述]

当图表的宽度不够时，x 轴的一些刻度被跳过，对应的拐点也不会显示，只有当鼠标悬停会有加重显示。当被跳过的拐点和相邻的拐点斜率相近时，否则单凭肉眼很难察觉中间存在一个刻度。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望在 x 轴刻度被跳过的情况下依然显示对应的拐点。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

<https://jsbin.com/renubatumi/edit?html,js,output>

**Comment by Ovilia** [comment]
[interval](http://echarts.baidu.com/option.html#xAxis.interval) 设为0？
