### ISSUE TITLE
实现世界地图的深钻（至少能到州一级），哪里有世界各个州的地图数据？

### ISSUE THREAD

**Issue by ZhiRongYuan** [apache/incubator-echarts#7405]
### One-line summary [问题简述]
业务需要 能查看到世界各个州的地图，不知道哪里找得到JSON数据，怎么解决这个问题啊

**Comment by chfw** [comment]
你阅览过[pyecharts team](https://github.com/pyecharts)的这个项目么？是从@pissang的[starbucks](http://pissang.github.io/starbucks/)衍生出来的[echarts-countries-js](https://pyecharts.github.io/echarts-countries-js/preview.html)
