### ISSUE TITLE
echarts2 如何解决type：force电脑触屏不能拖动节点

### ISSUE THREAD

**Issue by AnShengLI** [apache/incubator-echarts#7406]
echarts2  电脑触摸屏实现拖动节点  应该怎么实现呢？
比较后发现echarts3 可以实现电脑触摸屏拖动节点。
但是，在echarts2中，我应该对应做出怎样的修改？

**Comment by pissang** [comment]
2 里不支持，如果需要的话请升级 3

**Comment by AnShengLI** [comment]
@pissang  由于项目需要，所以我只能在echarts2中做相应修改，我想知道 echarts3较echarts2在电脑触屏拖动功能的实现中，是增加了哪些函数..或是其他哪些修改？ 求指教。
