### ISSUE TITLE
k线图颜色问题

### ISSUE THREAD

**Issue by qinchenn** [apache/incubator-echarts#7409]
### One-line summary [问题简述]
K线图无法修改单个item的颜色，有没有可以修改单个节点颜色的方法？
如果没有能否提供这样一个回调方法？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-candlestick.data.itemStyle.color
