### ISSUE TITLE
echarts2雷达图  没有设置max   当把最后一个图例隐藏时，代码报错

### ISSUE THREAD

**Issue by sjh0824** [apache/incubator-echarts#7426]
echarts2雷达图  没有设置max   当把最后一个图例隐藏时，代码报错

    var myChart = echarts2.init(document.getElementById("radar"));
    var datas = {
        "data":[{"name":"IBM","value":[30,22,7,10,9,1,0,17,0,1],"tooltip":{"trigger":"item"}},{"name":"GE","value":[2,0,0,11,7,0,0,0,0,0],"tooltip":{"trigger":"item"}},{"name":"ABB","value":[4,4,4,0,9,4,3,1,0,1],"tooltip":{"trigger":"item"}},{"name":"阿里云","value":[23,21,5,4,6,1,0,1,9,0],"tooltip":{"trigger":"item"}},{"name":"华为","value":[23,13,10,3,24,5,8,3,0,3],"tooltip":{"trigger":"item"}},{"name":"西门子","value":[7,0,8,0,15,4,7,0,0,3],"tooltip":{"trigger":"item"}},{"name":"施耐德电气","value":[1,2,4,1,6,1,0,0,0,0],"tooltip":{"trigger":"item"}},{"name":"微软中国","value":[3,0,0,0,0,0,0,0,0,0],"tooltip":{"trigger":"item"}}],
        "indicator":[
            {"text":"人工智能"},
            {"text":"云计算"},
            {"text":"物联网"},
            {"text":"医疗"},
            {"text":"数字化"},
            {"text":"智能制造"},
            {"text":"智慧城市"},
            {"text":"区块链"},
            {"text":"et大脑"},
            {"text":"工业4.0"}],
        "legend":["IBM","GE","ABB","阿里云","华为","西门子","施耐德电气","微软中国"]};
    option = {
        tooltip : {
            trigger: 'axis'
        },
        legend: {
            data:datas.legend
        },
        polar : [
            {
                indicator : datas.indicator
            }
        ],

        series : [
            {
                type: 'radar',
                data : datas.data
            }
        ]
    };
    myChart.setOption(option);

解决问题方法：
![image](https://user-images.githubusercontent.com/18656791/34559618-7708085c-f17d-11e7-81e5-64742471bc18.png)

**Comment by pissang** [comment]
试一下 3，2 我们不会再继续升级

**Comment by sjh0824** [comment]
但是 echarts 3  雷达图的 tooltip属性中，trigger:'axis' 不能用
