### ISSUE TITLE
关于echarts在页面引入es5-shim.js和es6-shim.js时，在IE8下单图渲染时间翻倍问题

### ISSUE THREAD

**Issue by snowzijun** [apache/incubator-echarts#7439]
### One-line summary [问题简述]
在页面引用了es5.shim.js,es5.sham.js,es6.shim.js,es6.sham.js时，echarts图形在IE8页面渲染时间翻倍，导致页面加载速度很慢。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.8.4
+ Browser version [浏览器类型和版本]:
 ie8
+ OS Version [操作系统类型和版本]:
win xp 

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ericWenjp** [comment]
我觉得ie8下，echart就是慢，ie9及以上就好很多，不知道怎么优化了，页面直接卡死，等了半分钟才出来
