### ISSUE TITLE
怎么设置Y轴不从0开始 并以数据平均值为基本线

### ISSUE THREAD

**Issue by ViolainOt** [apache/incubator-echarts#7440]
### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/33077110/34661281-90748ca8-f483-11e7-9d5a-82c181064bf9.png)

现在是这样的
![image](https://user-images.githubusercontent.com/33077110/34661293-afeef140-f483-11e7-8944-7e998b5de173.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by git-stf-01** [comment]
顶一下，我也有这个需求。。。@pissang 求帮助。
//////
我最终的解决方法是：给yAxis设定min和max，求出平均值后设置markLine。
虽然可以达到要求但是。。。与理想中的x轴为平均值还是不太一样。。。

**Comment by ViolainOt** [comment]
![image](https://user-images.githubusercontent.com/33077110/34702021-728e4000-f526-11e7-846d-12c40d1618a1.png)
可以显示 但是怎么把Y轴的坐标自定义 （定义成1SD，2SD类似第一张图） 还有怎么让X轴一直在下面@Terry    @pissang

**Comment by ViolainOt** [comment]
![image](https://user-images.githubusercontent.com/33077110/34702160-2c42208e-f527-11e7-866e-2ba7671e02f9.png)

可以显示 但是怎么把Y轴的坐标定义成1SD，2SD，类似第一张图， 还有怎么让X轴一直在下面@Terry  你把数值放大100倍运算得到的平均值就一样了
    max: (parseInt(_this.showX*100) + parseInt(_this.showSD * 300))/100,
    min: (parseInt(_this.showX*100) - parseInt(_this.showSD * 300))/100,

**Comment by git-stf-01** [comment]
对于y轴坐标可以设置axisLabel中的formatter进行格式化。
x轴的位置可以设置xAxis的position属性

**Comment by ViolainOt** [comment]
能具体说一下吗，比如Y轴实际值为6.74，怎么让他在Y轴显示为X，而不是6.74@Terry

**Comment by git-stf-01** [comment]
http://echarts.baidu.com/option.html#yAxis.axisLabel.formatter
///////////////////////////////////////////////////////////////////////////////////////
yAxis.axisLabel.formatter string, Function
[ default: null ]
刻度标签的内容格式器，支持字符串模板和回调函数两种形式。

示例:

// 使用字符串模板，模板变量为刻度默认标签 {value}
formatter: '{value} kg'

// 使用函数模板，函数参数分别为刻度数值（类目），刻度的索引
formatter: function (value, index) {
    // 格式化成月/日，只在第一个刻度显示年份
    var date = new Date(value);
    var texts = [(date.getMonth() + 1), date.getDate()];
    if (index === 0) {
        texts.unshift(date.getYear());
    }
    return texts.join('/');
}
