### ISSUE TITLE
[Feature request] 支持玉珏图 （或者支持按比例来绘制legend并隐藏legend的symbol） 

### ISSUE THREAD

**Issue by DongShi** [apache/incubator-echarts#7447]
### One-line summary [问题简述]

请提供OOTB支持 玉珏图 （radial column chart）， 效果见这里：
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/radial-bar.html

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: latest 
+ Browser version [浏览器类型和版本]: all 
+ OS Version [操作系统类型和版本]: mac and win

### Expected behaviour [期望结果]

https://antv.alipay.com/zh-cn/g2/3.x/demo/other/radial-bar.html
社区gallery看到一些类似的实现，但是问题出现在legend部分，legend的item 大小没法按比例customize （height， weight都是number， 可以尝试resize 整个page，就会看到legend的布局就很不协调）
http://gallery.echartsjs.com/editor.html?c=xB1Kxbug0b

这种图形在商业报表和大屏展示中越来越常见，请考虑下此需求。

一个workaround是支持 隐藏legend symbol，并支持按比例来摆放 legend item。 目前好像都不支持。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://www.echartsjs.com/gallery/editor.html?c=bar-polar-stack 可以参考这个例子

**Comment by DongShi** [comment]
Nice example！  上述的例子固然可以解决一部分问题，但是用极坐标系图的一个限制就是，各个category要共享这个axis的最大最小值（上述例子中为[0, 15]）。而玉珏图应用场景并不限于此，例如第一个环表示华南销售部的业绩目标(100w)和完成度(50w) ，第二个表示华北地区的目标（200w）和完成度（150w）等等

当然，可以在数据处理阶段统一规约到 [0, 100%],但是用起来就会不方便（例如tooltip也只会显示百分比等等）。 
希望能加入pipeline
