### ISSUE TITLE
tree orient配置项声明错误

### ISSUE THREAD

**Issue by lingfulu** [apache/incubator-echarts#7466]
官方文档 tree orient配置项声明错误,orient 默认为horizontal,可选vertical;文档写成了包含symbol的对象,symbol应该是在series下的配置项,而不是在orient下声明;具体见截图
![default](https://user-images.githubusercontent.com/23699899/34782480-d2c07676-f663-11e7-841d-7611cd354456.JPG)

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-doc/commit/35dd744ce8166c3763cfcffcffd29d2184324373 中已修复，但是还没上线
