### ISSUE TITLE
3.8.4版本的完整压缩版在IE8下报错，无法显示。

### ISSUE THREAD

**Issue by imakemyworld** [apache/incubator-echarts#7473]
### One-line summary [问题简述]

3.8.4版本的完整压缩版，在第1行的179594左右，代码片段如下：
function Yp(t){var e,i={},n={true:2,move:1,false:0,undefined:-1};
原因：关键字 true 在IE8下不支持作为JSON的KEY。（其他浏览器无问题，顺便吐槽一下老不死的IE8）
源码版无问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]:IE8
+ OS Version [操作系统类型和版本]:win7（64位）

### Expected behaviour [期望结果]

下个版本，希望改进压缩工具，能支持ie8，或帮个忙，给个临时方案。

**Comment by hl-stone** [comment]
现在在线构建有兼容IE8的选项
