### ISSUE TITLE
图的高度会自己变化

### ISSUE THREAD

**Issue by wj811** [apache/incubator-echarts#7488]
### One-line summary [问题简述]
图的高度会自己变化，3.6的版本没出现这个问题
![image](https://user-images.githubusercontent.com/35447244/34932495-ff437f88-fa0d-11e7-893c-a7510dcac6c0.png)
                                     (图1，KDJ指标图，设置的高度)
![image](https://user-images.githubusercontent.com/35447244/34932501-0a069392-fa0e-11e7-8bf0-21b99793e4c7.png)
                                      (图2，成交量图，图自己变高了)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请具体描述你的问题

**Comment by wj811** [comment]
就是绘制带成交量的K线图时，我切换其中股票指标重新绘制的时候，图的高度会发生变化，例如上面截图中从KDJ指标切换到成交量时图的高度变化。反过来先显示成交量也比设置的高度大，切换到其它图的时候会回到设置的高度。
