### ISSUE TITLE
SVG渲染之后保存图片getDataURL方法就不能用了

### ISSUE THREAD

**Issue by yeqiaofeng** [apache/incubator-echarts#7500]
SVG渲染之后保存图片getDataURL方法就不能用了
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
SVG 版本的保存图片（暂时）只能保存成 SVG 文件，需要将 [type](http://echarts.baidu.com/option.html#toolbox.feature.saveAsImage.type) 设为 `'svg'`。

**Comment by chfw** [comment]
或者[这样](https://github.com/chfw/echarts-scrappeteer)：
```
scrappeteer -f svg your_file.html
scrappeteer -f svg http://your.domain.name/your_file.html
```
