### ISSUE TITLE
象形柱图 在svg渲染器下有问题

### ISSUE THREAD

**Issue by erickwang** [apache/incubator-echarts#7501]
### One-line summary [问题简述]
http://echarts.baidu.com/demo.html#pictorialBar-body-fill
这个官方例子，用canvs渲染器，是正常的。换为svg渲染器后，就有问题了。
渲染的颜色不是重底开始了，而且第一个底渲染宽度有偏差了

![问题图片](http://chuantu.biz/t6/207/1516097005x-1566638297.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: chrome 63.0.3239.132 （最新版）
+ OS Version [操作系统类型和版本]: macOS Sierra 10.12.3

### Expected behaviour [期望结果]
![期望结果](http://chuantu.biz/t6/207/1516097606x-1404781252.png)

### ECharts option [ECharts配置项]

```javascript
option = {
// 代码跟 http://echarts.baidu.com/demo.html#pictorialBar-body-fill 差不多，
}


this.chart = Echarts.init(this.holderDom, null, {renderer:  'svg'});
this.chart.setOption(config);

```

**Comment by Ovilia** [comment]
@erickwang 谢谢反馈，我会跟进的~

**Comment by erickwang** [comment]
@Ovilia 什么时候能修复？ 挺期待能用上svg的象形柱图

**Comment by Ovilia** [comment]
初步排查到是 clipPath 不对引起的，不知道[这里](https://github.com/ecomfe/echarts/blob/49476bc925de3d1af031f4d64c766d7b95f5ae87/src/chart/bar/PictorialBarView.js#L368) `clipShape` 负的 height 是不是合理的，麻烦 @100pah 有空的时候看下。测试文件在 test/pictorial-svg.html。
