### ISSUE TITLE
echarts4.0 svg模式不支持富文本编辑？

### ISSUE THREAD

**Issue by DYMFbigdata** [apache/incubator-echarts#7508]
### One-line summary [问题简述]

echarts4.0 svg模式不支持富文本编辑？后期有打算支持吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
后面会支持，目前只有 canvas 支持富文本

**Comment by panhuajian** [comment]
快三年了，还是没有支持。。。

**Comment by pissang** [comment]
@panhuajian https://echarts.apache.org/next/examples/zh/editor.html?c=bar-rich-text&renderer=svg
