### ISSUE TITLE
echart 最小高度

### ISSUE THREAD

**Issue by luokebi** [apache/incubator-echarts#7510]
echart是否有一个最小高度？我用一个宽150px，高50px的div来画折线图表，图表总是显示不完整，会画到canvas以外去。

**Comment by pissang** [comment]
div 设置 min-height ?

**Comment by peachQAQ** [comment]
好像是有的，我画的 pie，最小高度是400，宽度没去试。
但是我的确需要将它塞到一个200x200的框里，现在就很苦恼。
