### ISSUE TITLE
Echarts 能否做3D饼图？

### ISSUE THREAD

**Issue by Max-Law** [apache/incubator-echarts#7511]
### One-line summary [问题简述]
在您的官方文档中，并未找到相关 3d饼图的配置项，
请问你们有像 hcharts 类似的 3d饼图吗？ 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

无

### Expected behaviour [期望结果]
实现下面功能
![image](https://user-images.githubusercontent.com/24608133/35024540-0151a930-fb7b-11e7-9d3a-70d3b35b3fac.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没有提供三维饼图的打算，欢迎贡献:)
