### ISSUE TITLE
echart3 地图各省份区域有间隙，地图不连贯有缝隙

### ISSUE THREAD

**Issue by alen00** [apache/incubator-echarts#7522]
### Version & Environment [jsp、html ]
+ ECharts version [echart3.8.4]:
+ Browser version [谷歌，火狐]:
+ OS Version [windows7]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![Uploading QQ拼音截图未命名.jpg…]()

这个是demo的样式 是正常的
http://gallery.echartsjs.com/editor.html?c=xSkFFABj0e

**Comment by alen00** [comment]
![qq](https://user-images.githubusercontent.com/17330549/35077095-5ed18b3c-fc36-11e7-99eb-f191016a89d0.jpg)

**Comment by alen00** [comment]
页面中没有加任何的样式
也没有引用其他的js

**Comment by alen00** [comment]
@pissang

**Comment by rianran1993** [comment]
已举报，分裂祖国

**Comment by alen00** [comment]
能不能来个人帮下忙看看呢
这是个什么什么情况呢？

**Comment by IcarusLou** [comment]
地图json数据问题，不要复制，直接clone下一份用

**Comment by chuntaoXu** [comment]
> 不能来个人帮忙下忙看呢 这是一个什么什么情况呢？

你好后来解决了吗
