### ISSUE TITLE
MarkPoint的name错误

### ISSUE THREAD

**Issue by genezx** [apache/incubator-echarts#7531]
### One-line summary [问题简述]
MarkPoint的name错误

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.0 - 4.0.2
+ Browser version [浏览器类型和版本]: 所有
+ OS Version [操作系统类型和版本]: 所有

### Error behaviour [错误结果]
![false](https://user-images.githubusercontent.com/31116612/35085032-c4bca6ea-fc61-11e7-86d5-c8fd10f59adb.png)

### Expected behaviour [期望结果]
![true](https://user-images.githubusercontent.com/31116612/35085088-0087984c-fc62-11e7-8f03-ecc5b2434e42.png)

### ECharts option [ECharts配置项]

```javascript
option = {
	xAxis: {
		data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
	},
	yAxis: {},
	series: [{
		type: 'line',
		data:[220, 182, 191, 234, 290, 330, 310],
		markPoint: {
			data: [
				{
					name: "p1",
					coord: ["Tue",300],
				},
				{
					name: "p2",
					coord: ["Thu",200],
				},
			],
			label: {
				show: true,
				formatter: function (param) {
					return param.name;
				},
			},
		},
	}]
};
```

**Comment by pissang** [comment]
好像是 formatter 没调用到
