### ISSUE TITLE
数据视图中显示NaN

### ISSUE THREAD

**Issue by iamziyue** [apache/incubator-echarts#7533]
### One-line summary [问题简述]
http://www.echartsjs.com/gallery/editor.html?c=dataset-simple0
官网示例，工具栏加上数据视图图标后，点击打开数字不显示，都显示NaN字样

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:应该是4.x
+ Browser version [浏览器类型和版本]:QQ浏览器10预览版，Chrome内核
+ OS Version [操作系统类型和版本]:Win10家庭版

### Expected behaviour [期望结果]
显示数字

### ECharts option [ECharts配置项]

```javascript
option = {

    legend: {},
    tooltip: {},
    dataset: {
        source: [
            ['product', '2015', '2016', '2017'],
            ['Matcha Latte', 43.3, 85.8, 93.7],
            ['Milk Tea', 83.1, 73.4, 55.1],
            ['Cheese Cocoa', 86.4, 65.2, 82.5],
            ['Walnut Brownie', 72.4, 53.9, 39.1]
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ],
    "toolbox": {
    "feature": {
      "dataView": {}
    }}
}

```

**Comment by zhanglin00129** [comment]
+1 for this

**Comment by huzhenlong** [comment]
++1

**Comment by simon-shuffle** [comment]
++++1 ，this upset me a lot ~

**Comment by DackRen** [comment]
++++++++1, unbelievable

**Comment by never615** [comment]
+1

**Comment by hero1981** [comment]
+1

**Comment by tailenderY** [comment]
It seems not work yet. could u help @pissang

**Comment by yunyun2017** [comment]
+1

**Comment by hailongma** [comment]
+1  ,  need this

**Comment by AspirinMrmi** [comment]
+1 没人管么？

**Comment by AspirinMrmi** [comment]
试试这样https://aspirinlovehyn.top/2019/10/24/Echarts%E4%B8%AD%E4%BD%BF%E7%94%A8%E6%95%B0%E6%8D%AE%E8%A7%86%E5%9B%BE%E6%95%B0%E6%8D%AENaN%E7%9A%84%E9%97%AE%E9%A2%98/

**Comment by 1234567845246** [comment]
+1
