### ISSUE TITLE
Echarts3.0地图开启缩放以后，下钻到省地图，不居中显示

### ISSUE THREAD

**Issue by zhuiluo0987** [apache/incubator-echarts#7537]
### One-line summary [问题简述]

地图开启缩放以后，从全国地图点击相应省份下钻到省地图，不居中显示，并且我在省地图放大以后，返回全国地图，全国地图任处于放大状态。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

Echarts3.0

### Expected behaviour [期望结果]

期望每次下钻到省份居中显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![default](https://user-images.githubusercontent.com/20220029/35140661-06674e0c-fd33-11e7-9843-113e6140575c.png)

**Comment by zhuiluo0987** [comment]
@pissang 有没有一些解决方案

**Comment by sen96321** [comment]
遇到相同问题
