### ISSUE TITLE
官方示例的这个极坐标热力图貌似是错的？数值反了？

### ISSUE THREAD

**Issue by oenglish** [apache/incubator-echarts#7544]
### One-line summary [问题简述]
官方地址:
http://echarts.baidu.com/examples/editor.html?c=custom-polar-heatmap
加了下面的tooltip只是为了方便看数据，实例本身应该有问题
` tooltip: {
        formatter: function (params) {
          
		
			return  days[params.value[0]] + hours[params.value[1]] +'共发生 ' + params.value[2] + '个事件 ' ;
        }
    }`

将tooltip格式化可以看出效果，**鼠标指上去似乎上下极的值是反的？12P显示的是12A的值？**怎么个情况，天生有问题？ 求大神指点

我这里也建了一个实例
http://gallery.echartsjs.com/editor.html?c=xSJAq4YkSG

### Version & Environment [版本及环境]
+ ECharts version [4.02]:
+ Browser version [chrome 56,maxthon]
+ OS Version [windows10]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lauwen** [comment]
你好 这是demo的问题，具体修复方式可参考：https://github.com/lauwen/echarts-examples/commit/5a747df929feec1d11dcc1fd4645f3332eb93829

**Comment by lauwen** [comment]
你好 这是demo的问题，具体修复方式可参考：https://github.com/ecomfe/echarts-examples/pull/4

**Comment by Ovilia** [comment]
已修复~
