### ISSUE TITLE
新增的sunrise类图表怎么使用dataset？

### ISSUE THREAD

**Issue by adsort** [apache/incubator-echarts#7550]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.02
+ Browser version [浏览器类型和版本]:any
+ OS Version [操作系统类型和版本]:any

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
树结构的数据暂时还不支持 dataset

**Comment by ColinCLL** [comment]
https://colincll.github.io/jc-doc/page/doc.html#tree
这个可能可以帮到你。
