### ISSUE TITLE
如何使用网络字体

### ISSUE THREAD

**Issue by xaviertung** [apache/incubator-echarts#7564]
### One-line summary [问题简述]
我在全局样式中通过@font-face引入了网络字体，HTML DOM文本字体显示正常，在echarts的radar/name中设置fontFamily属性为网络字体，结果依然显示为echarts默认的字体，我看了一下issue也有网友提到过这个问题，大都是没得到有效解答。确认一下echarts是否支持网络字体，如果支持如何配置，谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.x
+ Browser version [浏览器类型和版本]: chrome63.x
+ OS Version [操作系统类型和版本]: windows 7

### Expected behaviour [期望结果]
通过@font-face全局定义好网络字体，echarts直接引用，字体正常显示。

### ECharts option [ECharts配置项]

```javascript
option = {
      title: {
        text: 'Title'
      },
      radar: {
        indicator: radarData.indicators,
        name:{
          fontFamily: 'Exo2.0',
          fontSize: 30
        }
      },
      series: [{
        type: 'radar',
        itemStyle: { normal: { areaStyle: { type: 'default' } } },
        data : [
          {
            value : radarData.scores,
          }
        ]
      }]
}

```

**Comment by imlifeilong** [comment]
你最后怎么解决的啊？ @xaviertung

**Comment by pissang** [comment]
可能是因为绘制的时候 font face 还没加载完，可以试下使用 SVG 渲染，SVG 渲染模式浏览器会在字体加载完自动重绘。

或者参考 https://stackoverflow.com/a/8223555 这里的例子，在字体加载完后再绘制

我写了一个 SVG 渲染中使用 font-face 的例子。

https://jsfiddle.net/pissang/b3eg2rca/1/

**Comment by xxxs** [comment]
https://jsfiddle.net/pissang/b3eg2rca/1/  @pissang 
Can't open the address, can you paste the code? Thank you
