### ISSUE TITLE
tooltip在引入微信jssdk的页面不显示

### ISSUE THREAD

**Issue by winweib** [apache/incubator-echarts#7565]
### One-line summary [问题简述]
升级了4.0.2版本后，在引入了微信jssdk的页面，tooptip组件无法显示内容。

https://github.com/ecomfe/echarts/commit/e5a5c24aaae9895996a9db51e15628aae9c4d425#diff-d5fbb7185a3802482df65d3d3a345c70
应该是这个commit（fix(wxa): disable tooltip for weixin）引起的，为何要在微信环境里面禁用tooltip？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.2
+ Browser version [浏览器类型和版本]:Chrome 63
+ OS Version [操作系统类型和版本]: Win 7 64位

### Expected behaviour [期望结果]
能显示tooltip

### ECharts option [ECharts配置项]

```javascript
option = {
  title: {
    text: "ECharts 入门示例"
  },
  tooltip: {},
  legend: {
    data: ["销量"]
  },
  xAxis: {
    data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
  },
  yAxis: {},
  series: [
    {
      name: "销量",
      type: "bar",
      data: [5, 20, 36, 10, 10, 20]
    }
  ]
}

```

### Other comments [其他信息]

https://codepen.io/anon/pen/rpRjmq
教程的例子，引入jssdk的js文件tooltip即无法显示，删除掉即可以显示

**Comment by zend** [comment]
这句代码应该是为了微信小程序而准备的，误伤了？
