### ISSUE TITLE
echart svg方式渲染的情况下在ie9-ie11上横坐标文字与坐标轴重合

### ISSUE THREAD

**Issue by songkejiang** [apache/incubator-echarts#7572]
echart 3.0+用 svg方式渲染的情况下在ie9-ie11上横坐标文字与坐标轴重合

**Comment by Ovilia** [comment]
有例子和截图吗？试过 4.0 吗？

**Comment by songkejiang** [comment]
echart版本是4.0.2最新版本的。我截了两张图，一个是在ie上的表现，一个是echart配置
![echart](https://user-images.githubusercontent.com/23692313/35268952-9db305a0-0065-11e8-9091-fb216de7b03d.jpg)
![echart-option](https://user-images.githubusercontent.com/23692313/35268964-a56b6774-0065-11e8-832d-daecda16aef7.jpg)
