### ISSUE TITLE
3.x如何升级到4.x

### ISSUE THREAD

**Issue by ireeoo** [apache/incubator-echarts#7573]
### One-line summary [问题简述]

3.x如何升级到4.x，有没有升级指南

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/7532

**Comment by ireeoo** [comment]
@pissang 了解
