### ISSUE TITLE
series[i]-effectScatter.animation 不起作用! bug

### ISSUE THREAD

**Issue by 18144802250** [apache/incubator-echarts#7579]
### One-line summary [问题简述]
series[i]-effectScatter.animation 不起作用!

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.4
+ Browser version [浏览器类型和版本]:Safari 版本 11.0.1  Google 版本 63.0.3239.132
+ OS Version [操作系统类型和版本]:macOS High Sierra 10.13.1

### Expected behaviour [期望结果]
希望可以控制开关动画

### ECharts option [ECharts配置项]
http://gallery.echartsjs.com/editor.html?c=xH12838ESf&v=2

**Comment by pissang** [comment]
你把 effectScatter 改成 scatter 不就可以了么...

**Comment by 18144802250** [comment]
@pissang 主要是需要动画效果，又希望能停掉（毕竟耗性能） 点击停止动画  直接改type不行吧
