### ISSUE TITLE
请教:地图整体轮廓颜色阴影的标注

### ISSUE THREAD

**Issue by then0917** [apache/incubator-echarts#7582]
### One-line summary [问题简述]
请教一下,在绘制地图的时候除了设置地图的区域描边的颜色和阴影, 还能给整体地图加一个描边和阴影(与每个区域的描边阴影效果不一样)吗?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by then0917** [comment]
![default](https://user-images.githubusercontent.com/13010882/35264616-6656fd62-0058-11e8-8949-0b9b4aa15374.png)

**Comment by then0917** [comment]
每个区域的描边和阴影实现是itemStyle: {
                            normal: {
                                // areaColor: '#323c48',
                                areaColor: '#252f32',
                                borderColor: '#252f32',
                                shadowBlur: 10,
                                shadowColor: 'rgba(12, 17, 34, 0.5)',
                                shadowOffsetY: 5,
                            },
                            emphasis: {
                                // areaColor: '#252f32',
                                // borderColor: '#252f32',
                                // shadowBlur: 10,
                                // shadowColor: 'rgba(12, 17, 34, 0.5)',
                                // shadowOffsetY: 5,
                            }
                        },
但是这个整体地图的描边效果支持吗?

**Comment by xingorg1** [comment]
最近遇到了相同的问题，想实现给整个中国地图描边，但是每个省份不描边。试了半天都不行，加上描边和阴影，其实是给所有省份加上了，没有加到中国地图上的选项吗？

**Comment by chfw** [comment]
我也想知道。

**Comment by yzhang921** [comment]
通过设置geo最底层阴影实现，不要设置在series之上

**Comment by Caocao12138** [comment]
> ![default](https://user-images.githubusercontent.com/13010882/35264616-6656fd62-0058-11e8-8949-0b9b4aa15374.png)

实现了吗
