### ISSUE TITLE
Mix Gauge and Line-Chart

### ISSUE THREAD

**Issue by weingaunity** [apache/incubator-echarts#7588]
Hi,
is there any possibility to mix a line-chart with a gauge within one container?

Thx.

**Comment by pissang** [comment]
Yes, you can put both gauge series and line series in one option.

**Comment by weingaunity** [comment]
how can i set the position of the gauge and line-chart? Do you have an example?
I know how to place the gauge, but what about the line-chart?

**Comment by pissang** [comment]
for line/bar/scatter chart. You position the grid with left/top/right/bottom properties.

```js
chart.setOption({
grid: {
   left: 10,
   right: '50%',
   top: 10,
   bottom: 10
}
})
```

for gauge/pie chart. You can use center/radius properties.

```js
chart.setOption({
series: [{
   type: 'gauge',
   center: ['75%', '50%'],
   radius: '40%'
}]
})
```

**Comment by weingaunity** [comment]
Hi, i tried this but it does not work:
`// specify chart configuration item and data
  option = {
      tooltip : {
          formatter: "{b} = {c} "
      },
      toolbox: {
          show : true,
          feature : {
              mark : {show: false},
              restore : {show: false},
              saveAsImage : {show: false}
          }
      },
      grid: {
         left: '60',
         right: '200',
         top: '400',
         bottom: '10'
      },
      xAxis: {
          type: 'value'
      },
      yAxis: {
          type: 'value'
      },
      series : [
          {
              name:'Flüssigkeitstemperatur',
              type:'gauge',
              z: 3,
              min:0,
              max:120,
              center:['30%','33.33%'],
              radius : '60%',
              splitNumber:12,
              axisLine: {            // 坐标轴线
                  lineStyle: {       // 属性lineStyle控制线条样式
                      width: 10,
                      color: [[90/120, '#48b'],[100/120, '#228b22'],[1, '#ff4500']],
                  },
              },
              axisTick: {            // 坐标轴小标记
                  length :15,        // 属性length控制线长
                  lineStyle: {       // 属性lineStyle控制线条样式
                      color: 'auto'
                  }
              },
              splitLine: {           // 分隔线
                  length :20,         // 属性length控制线长
                  lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                      color: 'auto'
                  }
              },
              title : {
                  textStyle: {       // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                      fontWeight: 'bolder',
                      fontSize: 20
                  }
              },
              detail : {
                  textStyle: {       // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                      fontWeight: 'bolder'
                  }
              },
              data:[{value: 40, name: 'Flüssigkeit / °C'}]
          },
          {
              name:'Dampftemperatur',
              type:'gauge',
              z: 3,
              min:0,
              max:120,
              center:['65%','20%'],
              radius : '36.666%',
              startAngle:140,
              endAngle:-55,

              splitNumber:12,
              axisLine: {            // 坐标轴线
                  lineStyle: {       // 属性lineStyle控制线条样式
                      width: 10,
                      color: [[90/120, '#48b'],[100/120, '#228b22'],[1, '#ff4500']],
                  },
              },
              axisTick: {            // 坐标轴小标记
                  length :15,        // 属性length控制线长
                  lineStyle: {       // 属性lineStyle控制线条样式
                      color: 'auto'
                  }
              },
              splitLine: {           // 分隔线
                  length :20,         // 属性length控制线长
                  lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                      color: 'auto'
                  }
              },
              title : {
                  textStyle: {       // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                      fontWeight: 'bolder',
                      fontSize: 20
                  }
              },
              detail : {
                  textStyle: {       // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                      fontWeight: 'bolder'
                  }
              },
              detail : {
                  show: false
              },
              data:[{value: 40, name: 'Dampf / °C'}]
          },
          {
              name:'Heizung',
              type:'gauge',
              center : ['65%', '46.666%'],    // 默认全局居中
              radius : '26.666%',
              min:0,
              max:1,
              startAngle:95,
              endAngle:-135,
              splitNumber:2,
              axisLine: {            // 坐标轴线
                  lineStyle: {       // 属性lineStyle控制线条样式
                      color: [[0.4, '#228b22'],[0.6, '#48b'],[1, '#ff4500']],
                      width: 10
                  }
              },
              axisTick: {            // 坐标轴小标记
                  splitNumber:10,
                  length :10,        // 属性length控制线长
                  lineStyle: {       // 属性lineStyle控制线条样式
                      color: 'auto'
                  }
              },
              axisLabel: {
                  formatter:function(v){
                      switch (v + '') {
                          case '0' : return 'On';
                          case '1' : return 'Off';
                      }
                  }
              },
              splitLine: {           // 分隔线
                  length :15,         // 属性length控制线长
                  lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                      color: 'auto'
                  }
              },
              title : {
                  show: true,
                  textStyle: {       // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                      fontWeight: 'bolder',
                      fontSize: 15
                  }
              },
              detail : {
                  show: false
              },
              data:[{value: 0.5, name: 'Heizung'}]
          },
          {
                  data: [],
                  type: 'line'
              }
      ]
  };`

**Comment by weingaunity** [comment]
It looks like this:

![grafik](https://user-images.githubusercontent.com/16756598/35407267-a97b2b86-020b-11e8-9af5-a6123881636b.png)

**Comment by weingaunity** [comment]
Any idea what i'm doing wrong?
