### ISSUE TITLE
Expose rawDataItem in custom series API

### ISSUE THREAD

**Issue by jonavila** [apache/incubator-echarts#7592]
### One-line summary [问题简述]
It would very useful if we can obtain the rawDataItem in the custom series api. Currently, we can only extract the value by using `api.value`, but other properties like name or custom ones are lost.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
In a custom series, we can define the data as an array of objects like:
```
{name: 'Jon', value: 40, itemStyle: {color: 'red'}, someObject: {...}}
```

It would be great if we could get to the `someObject` property from the api, by exposing a rawDataItem function that we can call with the dataIndex. 

The function could look like:
```
  /**
   * @public
   * @param {number} [dataIndexInside=currDataIndexInside]
   * @return {number|string} value
   */


  function rawDataItem(dataIndexInside) {
    dataIndexInside == null && (dataIndexInside = currDataIndexInside);
    return data.getRawDataItem(dataIndexInside);
  }
```
and could then be added to the userAPI object in `chart/custom.js`

```
  var userAPI = zrUtil.defaults({
    getWidth: api.getWidth,
    getHeight: api.getHeight,
    getZr: api.getZr,
    getDevicePixelRatio: api.getDevicePixelRatio,
    rawDataItem: rawDataItem, // this is the function we are adding
    value: value,
    style: style,
    styleEmphasis: styleEmphasis,
    visual: visual,
    barLayout: barLayout,
    currentSeriesIndices: currentSeriesIndices,
    font: font
  }, prepareResult.api || {});
  var userParams = {
    context: {},
    seriesId: customSeries.id,
    seriesName: customSeries.name,
    seriesIndex: customSeries.seriesIndex,
    coordSys: prepareResult.coordSys,
    dataInsideLength: data.count(),
    encode: wrapEncodeDef(customSeries.getData())
  };
```

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by helgasoft** [comment]
solution could be in v.6.0 - https://github.com/apache/echarts/pull/20226
