### ISSUE TITLE
项目中直接引用 echarts/dist/echarts.min.js 会报错 版本 4.0.2

### ISSUE THREAD

**Issue by zachshelter** [apache/incubator-echarts#7608]
### One-line summary [问题简述]

在代码中 

import echarts from 'echarts/dist/echarts.min.js';

会报错

![image](https://user-images.githubusercontent.com/7088129/35367880-a846e9c6-01bb-11e8-9803-2d933c3a2c44.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: 63.0.3239.132
+ OS Version [操作系统类型和版本]: MacOS 10.13.2

**Comment by zachshelter** [comment]
补充一下， 3.8.2 并不会出问题

**Comment by pissang** [comment]
有更多使用上的代码么？

**Comment by zachshelter** [comment]
import echarts from 'echarts/dist/echarts.min.js';
import numeral from 'numeral';
import { isString, cloneDeep, assignIn, uniq, isArray, isBoolean, isObject, gt, gte, isEmpty, merge } from 'lodash';
import warning from 'warning';
import ChartsTheme from './src/theme';

echarts.registerTheme('default', ChartsTheme['default']);
echarts.registerTheme('dark', ChartsTheme['dark']);

class UWChart {

  static origin = echarts;
  static themes = ChartsTheme;

  instance = null;

  _instanceOption = {
    type: '',
    xAxis: { type: 'category', boundaryGap: false },
    yAxis: { type: 'value', axisLabel: { formatter: numberUnitFormatter() } },
    grid: { top: 8, left: 16, right: 24, bottom: 16, containLabel: true },
    tooltip: { show: true, trigger: 'axis', confine: true, transitionDuration: 0, hideDelay: 0 },
    legend: {},
    series: null,
    animation: false,
  };

  constructor(dom, theme, option) {
    this.initOption = { dom, option };
    if (option || isString(theme)) {
      this.instance = echarts.init(dom, theme || 'default', option);
    } else {
      this.instance = echarts.init(dom, 'default', theme);
    }
    const that = this;
    return assignIn(this, this.instance);
  }


  line = (extraOption = {}) => {
    warning(this._instanceOption.series, 'Need to set seires before set type');
    this._instanceOption.series = this._instanceOption.series.map(serie => merge(
      { areaStyle: false },
      serie,
      extraOption,
      { type: 'line' },
    ));
    return this;
  }

  area = (extraOption = {}) => {
    warning(this._instanceOption.series, 'Need to set seires before set type');
    this._instanceOption.series = this._instanceOption.series.map(serie => merge(
      { areaStyle: { normal: { opacity: 0.3 } } },
      serie,
      extraOption, { type: 'line' }));
    return this;
  }

  bar = (extraOption = {}) => {
    warning(this._instanceOption.series, 'Need to set seires before set type');
    this._instanceOption.series = this._instanceOption.series.map(serie => merge(
      { areaStyle: false },
      serie,
      extraOption,
      { type: 'bar' },
    ));
    return this;
  }

  pie = (xAxis = [], extraOption = {}) => {
    this._instanceOption.xAxis = [];
    this._instanceOption.yAxis = [];
    this._instanceOption.tooltip = { show: true, trigger: 'item', formatter: '{b}: {c} ({d}%)', confine: true };

    this._instanceOption.series = this._instanceOption.series.map(serie => merge({
      center: ['50%', '50%'],
      radius: ['0%', '66%'],
      label: { normal: { show: false } },
    }, serie, extraOption, { type: 'pie' }));
    return this;
  }

  circle = (extraOption = {}) => {
    this._instanceOption.xAxis = [];
    this._instanceOption.yAxis = [];
    this._instanceOption.tooltip = { show: true, trigger: 'item', formatter: '{b}: {c} ({d}%)', confine: true };

    this._instanceOption.series = this._instanceOption.series.map(serie => ({
      radius: ['50%', '66%'],
      center: ['50%', '50%'],
      label: { normal: { show: false } },
      ...serie,
      type: 'pie',
    }));

    return this;
  }

  gauge = (extraOption) => {
    this._instanceOption.xAxis = [];
    this._instanceOption.yAxis = [];
    this._instanceOption.tooltip = { show: true, trigger: 'item', formatter: '{b}: {c} ({d}%)', confine: true };

    const _colors = ['#ec6455', '#f4be41', '#63c98b']; // 默认颜色
    const { min = 0, max = 100, value = null, showThresholds, colors = _colors, thresholds } = extraOption;
    const gaugeColor = getGaugeColor(value, thresholds, colors);
    const normalization = (value - min) / (max - min); // 归一化
    const data = (100 - normalization * 100) * 270 / 360;
    let series = [
      { type: 'pie', z: 100, radius: [showThresholds ? '48%' : '60%', '72%'], center: ['50%', '50%'], startAngle: 225, color: [gaugeColor, 'transparent'], hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [75, 25] },
      { type: 'pie', z: 120, radius: [showThresholds ? '48%' : '60%', '72%'], center: ['50%', '50%'], startAngle: 315, color: ['#F4F4F4', 'transparent'], hoverAnimation: false, clockwise: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [data, 100 - data] },
    ];
    if (showThresholds && thresholds) {
      const [thresholdsLow, thresholdsHigh] = thresholds.split(',').map(v => Number(v));
      if (thresholdsLow && thresholdsHigh) {
        const low = (100 - ((thresholdsLow - min) / (max - min)) * 100) * 270 / 360;
        const mid = (100 - ((thresholdsHigh - min) / (max - min)) * 100) * 270 / 360;
        series = [
          ...series,
          { type: 'pie', z: 100, radius: ['73%', '82%'], center: ['50%', '50%'], startAngle: 225, color: [colors[2], 'transparent'], hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [75, 25] },
          { type: 'pie', z: 120, radius: ['73%', '82%'], center: ['50%', '50%'], startAngle: 315, color: ['transparent', colors[0], 'transparent'], clockwise: false, hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [low, 75 - low, 25] },
          { type: 'pie', z: 100, radius: ['73%', '82%'], center: ['50%', '50%'], startAngle: 315, color: ['transparent', colors[1], 'transparent'], clockwise: false, hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [mid, 75 - mid, 25] },
        ];
      }
    }
    this._instanceOption.series = series;
    return this;
  }

  series = (seriesData) => {
    this._instanceOption.series = seriesData;

    return this;
  }

  xAxis = (_xAxis = [], extraOption = {}) => {
    let xAxis = cloneDeep(_xAxis);
    if (xAxis && !isEmpty(xAxis)) {
      this._instanceOption.xAxis = merge(this._instanceOption.xAxis, {
        show: true,
        data: xAxis,
      }, extraOption);
    } else {
      this._instanceOption.xAxis = merge(this._instanceOption.xAxis, { show: false });
    }
    return this;
  }

  yAxis = (extraOption = {}) => {
    if (extraOption) {
      this._instanceOption.yAxis = merge(this._instanceOption.yAxis, { axisLabel: { formatter: numberUnitFormatter(extraOption.unit) } }, extraOption);
    } else {
      this._instanceOption.yAxis = merge(this._instanceOption.yAxis, { show: false });
    }
    return this;
  }

  grid = (extraOption = {}) => {
    this._instanceOption.grid = merge(this._instanceOption.grid, extraOption);

    return this;
  }

  legend = (show = true, extraOption = {}) => {
    const legendOption = isBoolean(show) ? extraOption : show;
    const { position = 'left', data } = legendOption;
    const legend = data || uniq(this._instanceOption.series.map(serie => serie.name));
    const isShow = Boolean(show);
    const basicOption = { show: isShow, data: legend, type: 'scroll', padding: [0, 10, 10] };
    switch (isString(show) ? show : position) {
      case 'left':
        this._instanceOption.legend = merge(this._instanceOption.legend, basicOption, { left: 'left', top: 'bottom', orient: 'horizontal' }, extraOption);
        this._instanceOption.grid.bottom = 30;
        break;
      case 'center':
        this._instanceOption.legend = merge(this._instanceOption.legend, basicOption, { left: 'center', top: 'bottom', orient: 'horizontal' }, extraOption);
        this._instanceOption.grid.bottom = 30;
        break;
      default:
        this._instanceOption.legend = merge(this._instanceOption.legend, basicOption, { left: 'left', top: 'bottom', orient: 'horizontal' }, extraOption);
        this._instanceOption.grid.bottom = 30;
        // this._instanceOption.grid.right = '10%';
        // this._instanceOption.legend = { orient: 'vertical', left: 'right', top: 'bottom', ...extraOption };
    }
    return this;
  }

  tooltip = (show = true, extraOption = {}) => {
    if (isBoolean(show)) {
      this._instanceOption.tooltip = merge(this._instanceOption.tooltip, { show }, extraOption);
    }
    if (isObject(show)) {
      this._instanceOption.tooltip = merge(this._instanceOption.tooltip, { show });
    }
    return this;
  }

  render(callback) {
    clearTimeout(this.renderTimer);
    this.renderTimer = setTimeout(() => {
      this.instance.resize();
      this.instance.setOption(this._instanceOption, true);
      if (callback) callback();
    }, 100);
  }

  changeTheme = (theme) => {
    this.instance.dispose();
    this.instance = echarts.init(this.initOption.dom, theme, this.initOption.option);
    return assignIn(this, this.instance);
  }
}

export default UWChart;

function numberUnitFormatter(type) {
  return (value) => {
    switch (type) {
      case 'percent':
        return numeral(value).format('0[.]0 %');
      default:
        return numeral(value).format('0[.]0 a');
    }
  };
}

function getGaugeColor(_value, gaugeColor, colors) {
  const value = Number(_value);
  const [thresholdsLow, thresholdsHigh] = gaugeColor.split(',').map(v => Number(v));
  if (!thresholdsLow || !thresholdsHigh) {
    return colors[2];
  }
  if (gt(thresholdsLow, value)) return colors[0];
  if (gte(value, thresholdsLow) && gte(thresholdsHigh, value)) return colors[1];
  if (gt(value, thresholdsHigh)) return colors[2];
}

**Comment by zachshelter** [comment]
`
import echarts from 'echarts/dist/echarts.min.js';
import numeral from 'numeral';
import { isString, cloneDeep, assignIn, uniq, isArray, isBoolean, isObject, gt, gte, isEmpty, merge } from 'lodash';
import warning from 'warning';
import ChartsTheme from './src/theme';

echarts.registerTheme('default', ChartsTheme['default']);
echarts.registerTheme('dark', ChartsTheme['dark']);

class UWChart {

  static origin = echarts;
  static themes = ChartsTheme;

  instance = null;

  _instanceOption = {
    type: '',
    xAxis: { type: 'category', boundaryGap: false },
    yAxis: { type: 'value', axisLabel: { formatter: numberUnitFormatter() } },
    grid: { top: 8, left: 16, right: 24, bottom: 16, containLabel: true },
    tooltip: { show: true, trigger: 'axis', confine: true, transitionDuration: 0, hideDelay: 0 },
    legend: {},
    series: null,
    animation: false,
  };

  constructor(dom, theme, option) {
    this.initOption = { dom, option };
    if (option || isString(theme)) {
      this.instance = echarts.init(dom, theme || 'default', option);
    } else {
      this.instance = echarts.init(dom, 'default', theme);
    }
    const that = this;
    return assignIn(this, this.instance);
  }


  line = (extraOption = {}) => {
    warning(this._instanceOption.series, 'Need to set seires before set type');
    this._instanceOption.series = this._instanceOption.series.map(serie => merge(
      { areaStyle: false },
      serie,
      extraOption,
      { type: 'line' },
    ));
    return this;
  }

  area = (extraOption = {}) => {
    warning(this._instanceOption.series, 'Need to set seires before set type');
    this._instanceOption.series = this._instanceOption.series.map(serie => merge(
      { areaStyle: { normal: { opacity: 0.3 } } },
      serie,
      extraOption, { type: 'line' }));
    return this;
  }

  bar = (extraOption = {}) => {
    warning(this._instanceOption.series, 'Need to set seires before set type');
    this._instanceOption.series = this._instanceOption.series.map(serie => merge(
      { areaStyle: false },
      serie,
      extraOption,
      { type: 'bar' },
    ));
    return this;
  }

  pie = (xAxis = [], extraOption = {}) => {
    this._instanceOption.xAxis = [];
    this._instanceOption.yAxis = [];
    this._instanceOption.tooltip = { show: true, trigger: 'item', formatter: '{b}: {c} ({d}%)', confine: true };

    this._instanceOption.series = this._instanceOption.series.map(serie => merge({
      center: ['50%', '50%'],
      radius: ['0%', '66%'],
      label: { normal: { show: false } },
    }, serie, extraOption, { type: 'pie' }));
    return this;
  }

  circle = (extraOption = {}) => {
    this._instanceOption.xAxis = [];
    this._instanceOption.yAxis = [];
    this._instanceOption.tooltip = { show: true, trigger: 'item', formatter: '{b}: {c} ({d}%)', confine: true };

    this._instanceOption.series = this._instanceOption.series.map(serie => ({
      radius: ['50%', '66%'],
      center: ['50%', '50%'],
      label: { normal: { show: false } },
      ...serie,
      type: 'pie',
    }));

    return this;
  }

  gauge = (extraOption) => {
    this._instanceOption.xAxis = [];
    this._instanceOption.yAxis = [];
    this._instanceOption.tooltip = { show: true, trigger: 'item', formatter: '{b}: {c} ({d}%)', confine: true };

    const _colors = ['#ec6455', '#f4be41', '#63c98b']; // 默认颜色
    const { min = 0, max = 100, value = null, showThresholds, colors = _colors, thresholds } = extraOption;
    const gaugeColor = getGaugeColor(value, thresholds, colors);
    const normalization = (value - min) / (max - min); // 归一化
    const data = (100 - normalization * 100) * 270 / 360;
    let series = [
      { type: 'pie', z: 100, radius: [showThresholds ? '48%' : '60%', '72%'], center: ['50%', '50%'], startAngle: 225, color: [gaugeColor, 'transparent'], hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [75, 25] },
      { type: 'pie', z: 120, radius: [showThresholds ? '48%' : '60%', '72%'], center: ['50%', '50%'], startAngle: 315, color: ['#F4F4F4', 'transparent'], hoverAnimation: false, clockwise: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [data, 100 - data] },
    ];
    if (showThresholds && thresholds) {
      const [thresholdsLow, thresholdsHigh] = thresholds.split(',').map(v => Number(v));
      if (thresholdsLow && thresholdsHigh) {
        const low = (100 - ((thresholdsLow - min) / (max - min)) * 100) * 270 / 360;
        const mid = (100 - ((thresholdsHigh - min) / (max - min)) * 100) * 270 / 360;
        series = [
          ...series,
          { type: 'pie', z: 100, radius: ['73%', '82%'], center: ['50%', '50%'], startAngle: 225, color: [colors[2], 'transparent'], hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [75, 25] },
          { type: 'pie', z: 120, radius: ['73%', '82%'], center: ['50%', '50%'], startAngle: 315, color: ['transparent', colors[0], 'transparent'], clockwise: false, hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [low, 75 - low, 25] },
          { type: 'pie', z: 100, radius: ['73%', '82%'], center: ['50%', '50%'], startAngle: 315, color: ['transparent', colors[1], 'transparent'], clockwise: false, hoverAnimation: false, legendHoverLink: false, label: { normal: { show: false } }, labelLine: { normal: { show: false } }, data: [mid, 75 - mid, 25] },
        ];
      }
    }
    this._instanceOption.series = series;
    return this;
  }

  series = (seriesData) => {
    this._instanceOption.series = seriesData;

    return this;
  }

  xAxis = (_xAxis = [], extraOption = {}) => {
    let xAxis = cloneDeep(_xAxis);
    if (xAxis && !isEmpty(xAxis)) {
      this._instanceOption.xAxis = merge(this._instanceOption.xAxis, {
        show: true,
        data: xAxis,
      }, extraOption);
    } else {
      this._instanceOption.xAxis = merge(this._instanceOption.xAxis, { show: false });
    }
    return this;
  }

  yAxis = (extraOption = {}) => {
    if (extraOption) {
      this._instanceOption.yAxis = merge(this._instanceOption.yAxis, { axisLabel: { formatter: numberUnitFormatter(extraOption.unit) } }, extraOption);
    } else {
      this._instanceOption.yAxis = merge(this._instanceOption.yAxis, { show: false });
    }
    return this;
  }

  grid = (extraOption = {}) => {
    this._instanceOption.grid = merge(this._instanceOption.grid, extraOption);

    return this;
  }

  legend = (show = true, extraOption = {}) => {
    const legendOption = isBoolean(show) ? extraOption : show;
    const { position = 'left', data } = legendOption;
    const legend = data || uniq(this._instanceOption.series.map(serie => serie.name));
    const isShow = Boolean(show);
    const basicOption = { show: isShow, data: legend, type: 'scroll', padding: [0, 10, 10] };
    switch (isString(show) ? show : position) {
      case 'left':
        this._instanceOption.legend = merge(this._instanceOption.legend, basicOption, { left: 'left', top: 'bottom', orient: 'horizontal' }, extraOption);
        this._instanceOption.grid.bottom = 30;
        break;
      case 'center':
        this._instanceOption.legend = merge(this._instanceOption.legend, basicOption, { left: 'center', top: 'bottom', orient: 'horizontal' }, extraOption);
        this._instanceOption.grid.bottom = 30;
        break;
      default:
        this._instanceOption.legend = merge(this._instanceOption.legend, basicOption, { left: 'left', top: 'bottom', orient: 'horizontal' }, extraOption);
        this._instanceOption.grid.bottom = 30;
        // this._instanceOption.grid.right = '10%';
        // this._instanceOption.legend = { orient: 'vertical', left: 'right', top: 'bottom', ...extraOption };
    }
    return this;
  }

  tooltip = (show = true, extraOption = {}) => {
    if (isBoolean(show)) {
      this._instanceOption.tooltip = merge(this._instanceOption.tooltip, { show }, extraOption);
    }
    if (isObject(show)) {
      this._instanceOption.tooltip = merge(this._instanceOption.tooltip, { show });
    }
    return this;
  }

  render(callback) {
    clearTimeout(this.renderTimer);
    this.renderTimer = setTimeout(() => {
      this.instance.resize();
      this.instance.setOption(this._instanceOption, true);
      if (callback) callback();
    }, 100);
  }

  changeTheme = (theme) => {
    this.instance.dispose();
    this.instance = echarts.init(this.initOption.dom, theme, this.initOption.option);
    return assignIn(this, this.instance);
  }
}

export default UWChart;

function numberUnitFormatter(type) {
  return (value) => {
    switch (type) {
      case 'percent':
        return numeral(value).format('0[.]0 %');
      default:
        return numeral(value).format('0[.]0 a');
    }
  };
}

function getGaugeColor(_value, gaugeColor, colors) {
  const value = Number(_value);
  const [thresholdsLow, thresholdsHigh] = gaugeColor.split(',').map(v => Number(v));
  if (!thresholdsLow || !thresholdsHigh) {
    return colors[2];
  }
  if (gt(thresholdsLow, value)) return colors[0];
  if (gte(value, thresholdsLow) && gte(thresholdsHigh, value)) return colors[1];
  if (gt(value, thresholdsHigh)) return colors[2];
}
`

**Comment by zachshelter** [comment]
使用上和 3.8.2 无区别。只是普通的 setOption
