### ISSUE TITLE
title 可以设置字间距吗

### ISSUE THREAD

**Issue by liuvigongzuoshi** [apache/incubator-echarts#7650]
### One-line summary [title 可以设置字间距吗]

+ ECharts version [4.0]:

### Expected behaviour [原字间距太小了！！]

```javascript
option = {
text: '',
    x: '',
    textStyle: {
    }
}

```

**Comment by Ovilia** [comment]
ECharts 文字没有字间距的设置方式

**Comment by pissang** [comment]
@liuvigongzuoshi 可以试试用多个 title 组件
