### ISSUE TITLE
echarts4.0在ws大概1s两次的推送消息时，持续到一定时间，浏览器会卡崩

### ISSUE THREAD

**Issue by Juliiii** [apache/incubator-echarts#7655]
### One-line summary [问题简述]

问题是这样的，我们大概有4个图，同时渲染，每个图数据量在5000多时，并且websock会1s两次的推送数据，图的数据会增长，继续渲染。这个情况下，页面很大几率卡崩，浏览器会崩溃。请问，有什么好的解决方法吗，万万万万万分感谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.02
+ Browser version [浏览器类型和版本]: Chrome 63.0
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]

期望是，尽量不要在websock推送数据期间都不要卡崩，能给用户使用

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/23744602/35519506-6dcf06c4-054f-11e8-825d-6e735b41fb92.png)

**Comment by pissang** [comment]
有几个可以优化的地方 1）关闭动画 2）设置 [sampling](http://echarts.baidu.com/option.html#series-line.sampling) 属性

**Comment by Juliiii** [comment]
@pissang 十分感谢您的回复。上述方法已经使用过，在websock持续推送消息，更新数图一个小时左右，还是会让浏览器卡崩。另外有个问题想咨询您一下：line图在放大到只有一个点时，那根线会消失，而现在pm和老师觉得用户需要看那个线，好吧，我废话有点多了，简而言之就是 line图在缩放到构成不了一条线时，能不能还显示那条线？或者，有没有啥办法。例如下图
![image](https://user-images.githubusercontent.com/23744602/35551583-bd2f76ce-05ca-11e8-86b1-4f3d1a00d437.png)
![image](https://user-images.githubusercontent.com/23744602/35551602-d281cf9a-05ca-11e8-9fa4-61e0e965d7c0.png)

1图放大到2图，最右边那条横线没了。

最后万万万万分感谢。
