### ISSUE TITLE
数据量过大有什么优化方法吗

### ISSUE THREAD

**Issue by ZeyZhang** [apache/incubator-echarts#7665]
### One-line summary [问题简述]
angular项目里，在一幅图里面显示多条线，每条线最多的时候可能有十万左右的数据点，有什么方式可以优化鼠标交互和渲染速度吗?

### Version & Environment [版本及环境]
+ ECharts version [3.8.5]:
+ Browser version [chrome60+]:
+ OS Version [win7]:

### Expected behaviour [期望结果]
尽量优化性能

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
如果要禁止交互，可以设置 `silent: true`。
通过 [sampling](http://localhost/ec-doc/public/cn/option.html#series-line.sampling) 可以设置采样规则，减少渲染的点。
