### ISSUE TITLE
条形图type 类型为bar, series数据大于800条以上时，渲染的时候整个页面会卡住

### ISSUE THREAD

**Issue by YxbEvan** [apache/incubator-echarts#7669]
### One-line summary [问题简述]
type为bar的条形图，当数据为800条时，渲染时页面会卡住，无法进行其它操作。点击legend面板时，也会卡住。设置过animation为false，并无太大作用

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3
+ Browser version [浏览器类型和版本]:chrome 63.0.3239.132
+ OS Version [操作系统类型和版本]: mac 

### Expected behaviour [期望结果]

加载时不要整个页面卡住，滚动和点击都操作不了。让视图自己加载渲染没关系，但是需要页面流畅一些，不影响整个页面

### ECharts option [ECharts配置项]

```javascript
var mychart = echarts.init(dom);

  var legendName = []
  var data_1 = [];
  var data_2 = [];
  for(var i = 0; i < 30; i++){
    legendName.push(i)
    data_1.push(i+2);
    data_2.push(i+4)
  }


  var legend_data = []
  var servers = []
  for(var j = 0; j < 3000; j++){
    let obj = {
      name: j,
      type:'bar',
      data:data_1,
    }
    servers.push(obj);
    legend_data.push(j + '')
  }
option = {
    animation: false,
  tooltip: {
      trigger: 'axis',
  },
  legend: {
      data:legend_data,
      type: 'scroll',
      y: 'bottom'
  },
  xAxis: [
      {
          data: legendName,
      }
  ],
  yAxis: [
      {
          type: 'value',
          name: '收益率',
      }
  ],
  series: servers
}
mychart.setOption(option)
```

**Comment by pissang** [comment]
你这是 3000 个系列 * 30 条数据，不是 800 个数据

**Comment by YxbEvan** [comment]
不好意思，我这边是模拟的demo, 实际的数据是获取的，不好直接写所以写了模拟的。实际的是70内的数据*1000内的条数。但是效果就是我demo那样的，渲染时整个页面卡住，动不了，点击底部图标的分页时也是卡住。我想知道有方法优化吗，或者体验上的优化，避免页面操作不了的效果，谢谢

**Comment by pissang** [comment]
不建议直接显示 1000 个系列，你可以过滤一下只显示重要的部分

**Comment by YxbEvan** [comment]
感谢回复
