### ISSUE TITLE
themeRiver 图 怎么去掉高亮

### ISSUE THREAD

**Issue by sjh0824** [apache/incubator-echarts#7677]
echarts4 themeRiver图 

当鼠标没有放到SY上时，其颜色
![image](https://user-images.githubusercontent.com/18656791/35605263-97a842ba-0682-11e8-9171-ea0d3382f495.png)

当鼠标放到SY上时，会高亮显示，怎么才能去掉高亮呢
![image](https://user-images.githubusercontent.com/18656791/35605209-31071cac-0682-11e8-9b41-0dbf0112cf1f.png)

**Comment by Ovilia** [comment]
是要去掉高亮但是保留 tooltip 吗？请问是为什么有这样的需求？
目前没有很好的办法支持，只有把 emphasis 设为 normal 一样的颜色。你这个图用的默认颜色的话，只能把高亮的颜色设为 `['#c23531','#2f4554', '#61a0a8', '#d48265', '#91c7ae','#749f83',  '#ca8622', '#bda29a','#6e7074', '#546570', '#c4ccd3']`
