### ISSUE TITLE
多图中axisPointer为cross时,可否控制哪些图只显示线,不显示轴标签

### ISSUE THREAD

**Issue by weihaipy** [apache/incubator-echarts#7710]
### One-line summary [问题简述]
多图中axisPointer为cross时,可否控制哪些图只显示线,不显示轴标签

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4
+ Browser version [浏览器类型和版本]:标准浏览器
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]

多图中,比如类似交易软件的场景中,axisPointer为cross时,可以控制哪些图只显示光标线,而不显示轴标签.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

我试过axisPointer.label.formatter,但是只是修改了字符串,背景还是会出来,且只对x轴有效

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series.lines

**Comment by xiazhujie** [comment]
![image](https://user-images.githubusercontent.com/1284261/35812349-a42f108e-0acb-11e8-9c59-183ba0454918.png)
@pissang 你说的那个配置我之前试过,直接就不显示十字光标了,我的意思如图中所说,在有多个水平axes时,只希望x轴label没隐藏的显示光标的label

**Comment by Yinsls** [comment]
有没有找到方案呢，遇到了同样的问题，试过把label背景隐藏，但那样也不好看，求解惑
