### ISSUE TITLE
获取不到长宽

### ISSUE THREAD

**Issue by Jwangyi** [apache/incubator-echarts#7723]
[问题简述] 获取不到宽度，宽度设为屏幕的24%，显示时，宽度几乎为0 
```
.inline-div {
    width:   24%; 
    height: 300px;
    min-width:300px;
    margin:5px;
    float:left;
    overflow:auto;
    display:none;
}

<script>
 $("#main").show(); 
</script>

<div class="inline-div" id="main">
```

+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本] chrome;

![capture](https://user-images.githubusercontent.com/36178291/35837769-ec99c8bc-0b22-11e8-85de-7771e4996d65.PNG)

**Comment by shiwanmenghuxiahuashan** [comment]
显示知乎要resize 一下吧？
