### ISSUE TITLE
视觉映射，只设置最大值或最小值时生成图表报错

### ISSUE THREAD

**Issue by linwrui** [apache/incubator-echarts#7726]
### One-line summary [问题简述]

使用官方DEMO
http://echarts.baidu.com/examples/editor.html?c=line-aqi   
修改后面的
visualMap.pieces=[ {
                gt: 300,
                color: '#7e0023'
            }]
图表生成没有视觉映射效果，浏览器后台报错“Cannot read property 'coord' of undefined“

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:谷歌最新版
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
上面的DEMO修改后视觉映射能展示>300的效果，官方文档是说没有设置lt或lte时会使用无穷值替换，但实际上却报错了。

### ECharts option [ECharts配置项]

```javascript
$.get('data/asset/data/aqi-beijing.json', function (data) {
    myChart.setOption(option = {
        title: {
            text: 'Beijing AQI'
        },
        tooltip: {
            trigger: 'axis'
        },
        xAxis: {
            data: data.map(function (item) {
                return item[0];
            })
        },
        yAxis: {
            splitLine: {
                show: false
            }
        },
        toolbox: {
            left: 'center',
            feature: {
                dataZoom: {
                    yAxisIndex: 'none'
                },
                restore: {},
                saveAsImage: {}
            }
        },
        dataZoom: [{
            startValue: '2014-06-01'
        }, {
            type: 'inside'
        }],
        visualMap: {
            top: 10,
            right: 10,
            pieces: [ {
                gt: 300,
                color: '#7e0023'
            }],
            outOfRange: {
                color: '#999'
            }
        },
        series: {
            name: 'Beijing AQI',
            type: 'line',
            data: data.map(function (item) {
                return item[1];
            }),
            markLine: {
                silent: true,
                data: [{
                    yAxis: 50
                }, {
                    yAxis: 100
                }, {
                    yAxis: 150
                }, {
                    yAxis: 200
                }, {
                    yAxis: 300
                }]
            }
        }
    });
});

```

### Other comments [其他信息]

http://echarts.baidu.com/examples/editor.html?c=line-aqi

**Comment by pidongqianqian** [comment]
遇到同样的问题

**Comment by anbee** [comment]
我也遇到了同样的问题，请问有解决方法了吗？

**Comment by linwrui** [comment]
`        const minValue = (_.min(chartOption.series.map(x => _.min(x.data.map((d: any) => d instanceof Array ? d[1] : d.value))))) as number;
        const maxValue = (_.max(chartOption.series).map(x => _.max(x.data.map((d: any) => d instanceof Array ? d[1] : d.value))))) as number;
`
我用这个方法获取最大和最小值，手动设置了，有点蠢但可行。。。

**Comment by anbee** [comment]
请问能不能给一个完整的option，我不太明白这个minValue和maxValue要放在哪个api下？谢谢

**Comment by kevinlinjiajun** [comment]
请问有解决办法了么
