### ISSUE TITLE
文档配置项里dataZoom一块漏了一个singleAxisIndex的参数不方便refer

### ISSUE THREAD

**Issue by laoxu0212** [apache/incubator-echarts#7737]
### One-line summary [问题简述]
建立使用singleAxis建成的scatter图（参考了实例http://echarts.baidu.com/examples/editor.html?c=scatter-single-axis），即使用并建立了多条singleAxisIndex，需要使用dataZoom功能对多个轴进行同时缩放。查询文档，配置项手册，dataZoom只有xAxisIndex, yAxisIndex, radiusAxisIndex, angleAxisIndex四个用于选择对应轴的配置项。
在查询源代码前，仿照此形式瞎猜将singleAxisIndex: [0, 1]放入dataZoom中，成功，因而文档似乎是缺了一小项，希望补全以便之后其他人查询。

http://echarts.baidu.com/option.html#dataZoom
dataZoom 主要是对 数轴（axis） 进行操作（控制数轴的显示范围，或称窗口（window））。

可以通过 dataZoom.xAxisIndex 或 dataZoom.yAxisIndex 或 dataZoom.radiusAxisIndex 或 dataZoom.angleAxisIndex 来指定 dataZoom 控制哪个或哪些数轴。

**Comment by AndyKnight1201** [comment]
> ### One-line summary [問題簡述]
> 建立使用singleAxis建成的scatter圖（參考了實例[http://echarts.baidu.com/examples/editor.html?c=scatter-single-axis），即使用並建立了多條singleAxisIndex，需要使用dataZoom功能對多個軸進行同時縮放。查詢文檔，配置項手冊，dataZoom只有xAxisIndex](http://echarts.baidu.com/examples/editor.html?c=scatter-single-axis%EF%BC%89%EF%BC%8C%E5%8D%B3%E4%BD%BF%E7%94%A8%E5%B9%B6%E5%BB%BA%E7%AB%8B%E4%BA%86%E5%A4%9A%E6%9D%A1singleAxisIndex%EF%BC%8C%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8dataZoom%E5%8A%9F%E8%83%BD%E5%AF%B9%E5%A4%9A%E4%B8%AA%E8%BD%B4%E8%BF%9B%E8%A1%8C%E5%90%8C%E6%97%B6%E7%BC%A9%E6%94%BE%E3%80%82%E6%9F%A5%E8%AF%A2%E6%96%87%E6%A1%A3%EF%BC%8C%E9%85%8D%E7%BD%AE%E9%A1%B9%E6%89%8B%E5%86%8C%EF%BC%8CdataZoom%E5%8F%AA%E6%9C%89xAxisIndex) , yAxisIndex, radiusAxisIndex, angleAxisIndex四個用於選擇對應軸的配置項。 在查詢源代碼前，仿照此形式瞎猜將singleAxisIndex: [0, 1]放入dataZoom中，成功，因而文檔似乎是缺了一小項，希望補全以便之後其他人查詢。
> 
> http://echarts.baidu.com/option.html#dataZoom dataZoom 主要是對數軸（axis） 進行操作（控制數軸的顯示範圍，或稱窗口（window））。
> 
> 可以通過dataZoom.xAxisIndex 或dataZoom.yAxisIndex 或dataZoom.radiusAxisIndex 或dataZoom.angleAxisIndex 來指定dataZoom 控制哪個或哪些數軸。
