### ISSUE TITLE
echarts 4.0 里面axisLabel 以前的版本textStyle里面的align生效，现在4.0好像不生效了

### ISSUE THREAD

**Issue by mosejiang** [apache/incubator-echarts#7743]
当Y轴的值不确定时，希望文本左对齐，然后Y轴右撑开，之前的版本生效，升级到4.0之后，发现不生效了。
怎么样可以设置Y轴文本左对齐吗？

**Comment by pissang** [comment]
3.7.0 开始去掉了 textStyle 这个层级，之前版本有兼容，4.0 有个bug导致这个兼容失效了，下个版本会修复，不过建议改成最新的配置方式

**Comment by huangchaofei** [comment]
@pissang  现在还是不行啊?
