### ISSUE TITLE
dataZoom 数据过滤模式设置为 “none” 时系列的标记会越界

### ISSUE THREAD

**Issue by chenlijun99** [apache/incubator-echarts#7748]
### One-line summary [问题简述]
DataZoom 数据过滤模式设置为 “none” 时系列的标记会越界

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2 
+ Browser version [浏览器类型和版本]: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: Ubuntu 16.04

### Expected behaviour [期望结果]
当标记不在坐标系里时能够自动被隐藏起来。

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'time'
    },
    yAxis: {
        type: 'value'
    },
    dataZoom: [
    	{
	    	type: "slider",
	    	xAxisIndex: [0],
	    	filterMode: "none"
		},
	],
   series: [{
        data: [["2018-01-01", 932], ["2018-01-02", 934],
        ["2018-01-03", 1330], ["2018-01-05", 123]],
        type: 'line',
        step: "start"
    }]
};

```

### Other comments [其他信息]

![echarts 3](https://user-images.githubusercontent.com/20483759/35912075-d69fd5cc-0bfb-11e8-9129-f18e9009cc6f.png)

**Comment by 18830438187** [comment]
解决了吗，也遇到了同样的问题
