### ISSUE TITLE
label的文字溢出如何省略处理？

### ISSUE THREAD

**Issue by See-Cat** [apache/incubator-echarts#7749]
### One-line summary [问题简述]
做柱状图的时候Y轴的label 的文字特别容易过长，当宽度不够的时候文字就显示不全。想对label进行溢出省略处理。没有找到相关的配置，通过rich也没法做到。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]:Chrome / 45.0.2454.99
+ OS Version [操作系统类型和版本]:window 8

### Expected behaviour [期望结果]
Y轴的label 的文字是动态的，期望的效果是宽度够的话文字能显示齐全，不够的时候能省略处理。
想知道有什么方法能做到类似效果么？ 还是我没找到相关的方式而已？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![default](https://user-images.githubusercontent.com/20717588/35918515-0ad6005e-0c4d-11e8-83ce-497d6db9759e.png)

**Comment by fscommlx** [comment]
我是修改grid.left，

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#grid.containLabel>

**Comment by See-Cat** [comment]
@100pah 额。是解决了Label溢出后显示不全的问题，但是会影响整体的图表结构，当 label 特别长的时候会挤占右边柱状图的宽度，与设计稿不符。 这个问题暂时解决了，我利用了axisLabel.formatter， 方法中计算出label 实际宽度，再根据配置的字号截取出实际能显示的文字个数。 感谢热心回复~

**Comment by territoryfan** [comment]
@See-Cat  第二个图不知道是否能满足你说的   https://github.com/territoryfan/echarts
