### ISSUE TITLE
x 轴为time时 barchart 显示不正常

### ISSUE THREAD

**Issue by flexdeviser** [apache/incubator-echarts#7753]
### One-line summary [问题简述]

当x轴为time时 设置最大值为当月最后一天，最小值为当月第一天。然后series数据为其中某些天。 
3条数据应该分布到具体的天上，结果重叠在一起。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:max os

### Expected behaviour [期望结果]

每一个柱子落在具体的天上， 宽度也应该根据当前的时间间隔自动计算为当月的天数。

### ECharts option [ECharts配置项]

```javascript
app.title = '折柱混合';

option = {
    
   
    legend: {
        data:['A']
    },
    xAxis: [
        {
            type: 'time',
            max:1519736400999,
            min:1517403600000
        }
    ],
    yAxis: [
        {
            type: 'value',
            name: 'A',
            axisLabel: {
                formatter: '{value}'
            }
        }
    ],
    series: [
        {
            name:'A',
            type:'bar',
            data:[[1517925600000,1125.08],[1518012000000,5216.97],[1518098400000,13243.56]]
        }
    ]
};


```

### Other comments [其他信息]

<img width="1677" alt="screen shot 2018-02-08 at 15 28 40" src="https://user-images.githubusercontent.com/3424332/35955633-cb8c039c-0ce4-11e8-8b80-475d6f32b265.png">

**Comment by Amon8859** [comment]
我也遇到同样问题，echart2.0 显示正常。肯定是计算宽度存在bug

**Comment by flexdeviser** [comment]
我现在是这样解决的， 我把x轴的time变成了category。 所以还是放弃x轴使用time类型吧~
