### ISSUE TITLE
sunburst旭日图什么时候可以支持一下minAngle？

### ISSUE THREAD

**Issue by Mying666** [apache/incubator-echarts#7758]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以说下为什么需要这个配置项吗？

**Comment by Mying666** [comment]
@Ovilia 现在项目做的旭日图想在下钻之后显示label标签，如果数据量小的话对应的环图面积很小，label写不下，或者已经超出。所以希望可以像饼图那样可以有一个最小角度的限制

**Comment by Ovilia** [comment]
可以的，后面我加一下，要年后上线了

**Comment by Mying666** [comment]
@Ovilia 👍👍👍谢谢啦

**Comment by Ovilia** [comment]
解决完再 close
