### ISSUE TITLE
力导向图中的鼠标样式只能为手型，不能改成其他样式

### ISSUE THREAD

**Issue by summerhll** [apache/incubator-echarts#7764]
### One-line summary [问题简述]
今天想将力导向图改成 当鼠标移上去时，不显示手型。但是   代码中写：cursor : "move", 鼠标移上去还是手型，并不是移动手型。cursor改成其他的值，也是一样的效果。
这个是代码中的bug吧？求教，谢谢各位

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
 title: {
        text: 'Graph 简单示例'
    },
    tooltip: {},
    animationDurationUpdate: 1500,
    animationEasingUpdate: 'quinticInOut',
    series : [
        {
            type: 'graph',
            layout: 'none',
            symbolSize: 50,
            roam: true,
            label: {
                normal: {
                    show: true
                }
            },
            silent  : false,
            cursor : "move",
        
            data: [ {
                name: '节点3',
                x: 550,
                y: 100
            }]
          
          
        }
    ]

}

```

**Comment by Ovilia** [comment]
应该是个 bug，我会跟进一下

**Comment by vladimir-spintech** [comment]
@Ovilia Hi,

This fix missing from the released version for some reason 🙁

**Comment by topvis** [comment]
@Ovilia , I just want to confirm that the issue still exist in the current version 4.2.1

**Comment by Ovilia** [comment]
I tested. The fix is included in the source code of master branch but not in `dist`, which is 4.2.1. It will be included in the next release.
