### ISSUE TITLE
tooltip里面可以再绘制图表吗？？

### ISSUE THREAD

**Issue by silence-may** [apache/incubator-echarts#7765]
### One-line summary [问题简述]

需求是希望能在每个item的tooltip里再实现一个曲线图，
类似于这种：
![image](https://user-images.githubusercontent.com/20940285/36017187-9a148f6e-0db1-11e8-8fa7-89bf911cd74d.png)
请问具体该怎么做呢？？可以实现吗？？
望回复，谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
tooltip 没法做这样的事，如果要自己实现的话，可以通过 [on 事件](http://echarts.baidu.com/api.html#echartsInstance.on) 获取鼠标移动的信息，然后在相应的位置增加一个 HTML 的 DOM，然后这里面再用一个 ECharts 图表绘制折线图？

**Comment by territoryfan** [comment]
formatter 里面在放一个 echarts图标

**Comment by territoryfan** [comment]
formatter 里面 在放一个echarts图表
