### ISSUE TITLE
矩形树图treemap的样式问题。

### ISSUE THREAD

**Issue by silence-may** [apache/incubator-echarts#7766]
### One-line summary [问题简述]
请问在矩形树图中，如何根据矩形的面积大小，来进行每个item的label文字缩放呢？？
![image](https://user-images.githubusercontent.com/20940285/36017267-f6853546-0db1-11e8-858a-f1f58291f835.png)
我实现的这种，希望能面积大的块里面的文字更大，面积小的相应文字也小一点该怎么做啊？？
望回复！谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
[data.label.fontSize](http://echarts.baidu.com/option.html#series-treemap.data.label.fontSize) 可以为每一项数据指定文字大小，需要自己写一个循环，在 option 里传入每个数据对应的 fontSize

**Comment by lirongrong-github** [comment]
可以确定 treemap 每一个矩形的宽高吗，   我也遇到这个问题了。

**Comment by lirongrong-github** [comment]
这里可以拿到 矩形信息 https://github.com/apache/echarts/issues/14644#issue-855698522

**Comment by pissang** [comment]
We can use `labelLayout` to set font size based on the size of ect
```ts
labelLayout: function (params) {
    if (params.rect.width < 5 || params.rect.height < 5) {
        return {
            fontSize: 0
        };
    }
    return {
        fontSize: Math.min(Math.sqrt(params.rect.width * params.rect.height) / 10, 20)
    };
},
```

**Comment by lirongrong-github** [comment]
trank you

**Comment by MoonpieChaury** [comment]
> We can use `labelLayout` to set font size based on the size of rect. For example:
> 
> ```ts
> labelLayout: function (params) {
>     if (params.rect.width < 5 || params.rect.height < 5) {
>         return {
>             fontSize: 0
>         };
>     }
>     return {
>         fontSize: Math.min(Math.sqrt(params.rect.width * params.rect.height) / 10, 20)
>     };
> },
> ```

Could you please update the configuration item document? There is currently no labelLayout in the configuration items owned by Treemap. 
thanks

**Comment by lakshay2711** [comment]
I have one query here, in my case I need to increase the width of the treemap. Even if I am keeping it to 100% then it is not able to take the complete 100% width of the outer wrapped Card Component in vue3?
