### ISSUE TITLE
请问在treemap中想快速定位某个矩形放大并改变其颜色？？？

### ISSUE THREAD

**Issue by silence-may** [apache/incubator-echarts#7777]
### One-line summary [问题简述]
请问除了改变原始数据的设置外还有没有什么API可以使用啊？？因为如果去改变数据的话就需要循环数据找出所选项，很耗时！
望回复，谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
其实这个 [例子](https://github.com/ecomfe/echarts/blob/master/test/treemap-obama.html) 右上角有个“搜索按钮”，不知是否和你的场景类似？
