### ISSUE TITLE
legend怎么解析html代码

### ISSUE THREAD

**Issue by empty-back** [apache/incubator-echarts#7778]
### One-line summary [问题简述]

http://echarts.baidu.com/examples/editor.html?c=geo-lines
这个demo的右下角的三个筛选按钮如何解析为html代码而不只是文本。(例如加入img标签)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:http://echarts.baidu.com/examples/vendors/echarts/echarts.min.js?_v_=1518076267754
+ Browser version [浏览器类型和版本]:chrome  62.0.3202.89
+ OS Version [操作系统类型和版本]:windwos7

### Expected behaviour [期望结果]

http://echarts.baidu.com/examples/editor.html?c=geo-lines
这个demo的右下角的三个筛选按钮如何解析为html代码而不只是文本。(例如加入img标签)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
三个按钮不是使用 html 标签画的，所以不能直接解析为 html 代码。
