### ISSUE TITLE
eCharts切换功能

### ISSUE THREAD

**Issue by JaesunPark** [apache/incubator-echarts#7783]
### One-line summary [问题简述]

我想以切换格式在图表的图例中实现标签。

차트의 legend 안에 있는 label을 toggle 형식으로 구현하고 싶습니다.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 無
+ Browser version [浏览器类型和版本]: 無
+ OS Version [操作系统类型和版本]: 無

### Expected behaviour [期望结果]

我想以切换格式在图表的图例中实现标签。

系列：[{name：hello}，{name：tomas}]

图表实施后，当您点击图例中的“hello”标签时，“tomas”未被导出。

它是否由现有的eCharts支持？
或者你需要一个新的习惯？

----

차트의 legend 안에 있는 label을 toggle 형식으로 구현하고 싶습니다.

series : [{name : hello}, {name : tomas}]

차트가 구현된 후 legend 안에 있는 "hello" label을 클릭하였을 때 "tomas"는 비노출.

기존 eCharts에서 지원되는 기능인가요?
아니면 새로 커스텀을 해야하는건가요?

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
Sorry I have not yet understood your requirement. 
May be describe it explicitly in english (but not by machine translation) is better to understanding?

**Comment by cuibei** [comment]
还是个韩国人哦
