### ISSUE TITLE
Reversed log y axis

### ISSUE THREAD

**Issue by triggerfish1** [apache/incubator-echarts#7785]
### One-line summary [问题简述]

I want to plot a diagram with a reversed, logarithmic y axis. 

When I change the type to log and use a max value that is smaller than the min value, it seems to work. However, the Y axis labels disappear... 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
Does [yAxis.inverse](https://ecomfe.github.io/echarts-doc/public/en/option.html#yAxis.inverse) meet the requirement?
