### ISSUE TITLE
echarts 是用哪种坐标 的bd09ll、bd09mc、gcj02、wgs84 ？

### ISSUE THREAD

**Issue by hhxx1994** [apache/incubator-echarts#7787]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
这取决于使用的 geoJSON 是使用的哪种坐标。
