### ISSUE TITLE
set SplitArea specific interval  color

### ISSUE THREAD

**Issue by bogdanSanta** [apache/incubator-echarts#7793]
I want to color yaxis from value x to y with some color,I used splitArea but is no use to me because is a splitArea is a repeater, repeats color based on given interval.
 

 
![image](https://user-images.githubusercontent.com/641080/36472626-04271172-16fb-11e8-963c-439e6c6f81a6.png)

![image](https://user-images.githubusercontent.com/641080/36532111-8ca3191a-17c8-11e8-9d45-3fc292163818.png)

Using split area is not good option since repeats the colors 
```
yAxis: {
      splitArea:{
         show:true,
         areaStyle:{
          color:["rgba(255,0,0,0.7)",'yellow','green','green','green']
          }
        }
    },
```

It would be nice if echart will support something like ,
This is standard behavior in the popular charts like highcharts (ex: plotbands
 
If is not possible, can i at least override the drawing splitArea ?
 

i propose the splitarea to have something like this
```
 splitArea : [
            {
                start: 1,
                end: 10,
                color: "red"
            },
            {
                start: 10,
                end: 20,
                color: "blue",
            }
        ];
```

**Comment by Ovilia** [comment]
Try with [markArea](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.markArea)

**Comment by bogdanSanta** [comment]
It  does not help me , because i cannot set  multiple colors
for each  yaxis interval  i want  to set a different color 

![image](https://user-images.githubusercontent.com/641080/36532053-66d56b3e-17c8-11e8-80d5-b6ead5fea84c.png)

**Comment by Ovilia** [comment]
markArea can be an array of settings, each representing an area with specific color.

**Comment by bogdanSanta** [comment]
i tried this , but its does not work , based on echart documentation each series can have one markArea object not an array 
 ```
 

 markArea: [ {
                itemStyle: {
                    normal: {
                        color: "red"
                     },
 
                },
                data: [
                    [ {yAxis: 0 }, { yAxis: 1 }],
                ]
            },
            {
                itemStyle: {
                    normal: {
                        color: 'blue'
                     },
                },
                data: [
                    [{ yAxis: 1 }, { yAxis: 2 }],
                ]
            }],`

**Comment by bogdanSanta** [comment]
I made some workaround it work but i don't like it way 
for each color   i need to create a empty series containing only mark Area  
with the mention the  serie   name must be unique


 series: [
  ```     {  
           name:'randomx',
        type: 'bar',
           markArea: {
                itemStyle: {
                    normal: {
                        color: 'red'
                     },`
 
                }, 
                data: [
                    [ {yAxis: 0 }, { yAxis: 10000 }],
                ]
            }
            
        },
        {  
           name:'randomy',
        type: 'bar',
           markArea: {
                itemStyle: {
                    normal: {
                        color: 'green'
                     },
 
                },
                data: [
                    [ {yAxis: 10000 }, { yAxis: 200000 }],
                ]
            }
        }  
        ,{
        name: 'scatter',
        type: 'scatter',
        label: {
            emphasis: {
                show: true,
                position: 'left',
                textStyle: {
                    color: 'blue',
                    fontSize: 16
                }
            }
        },
        data: [1,2,3,4,4,5,6,6]
   }
]

**Comment by oddcitizenape** [comment]
> i tried this , but its does not work , based on echart documentation each series can have one markArea object not an array
> 
> ```
> 
> 
> markArea: [ {
>                itemStyle: {
>                    normal: {
>                        color: "red"
>                     },
> 
>                },
>                data: [
>                    [ {yAxis: 0 }, { yAxis: 1 }],
>                ]
>            },
>            {
>                itemStyle: {
>                    normal: {
>                        color: 'blue'
>                     },
>                },
>                data: [
>                    [{ yAxis: 1 }, { yAxis: 2 }],
>                ]
>            }],`
> ```

It's been a while, but maybe someone is interested. You should have just formatted the object a little differently. Then you don't need a workaround. That's a bit misleading, but it works:

`
 series: [
    {
      name: 'Axis name #1',
      type: 'line',
      smooth: true,
      data: data,
      markArea: {
        data: [
          [ 
            {
              name: 'Warning',
              yAxis: 110,
              itemStyle: {
                color: 'yellow',
                opacity: 0.3,
              },
            },
            { yAxis: 130 },
          ],
          [
            {
              name: 'Alarm',
              yAxis: 130,
              itemStyle: {
                color: 'red',
                opacity: 0.3,
              },
            },
            { yAxis: 450 }
          ]
        ],
      }
    },
  ],
`
