### ISSUE TITLE
Apply series styles globally?

### ISSUE THREAD

**Issue by kerryj89** [apache/incubator-echarts#7795]
### One-line summary [问题简述]
Scenario: Dashboard with multiple bar line charts.  Should be same style (line width, tooltip, etc.).

Question: Is there a documented way to define series styles globally?  So we do not need to repeat options over and over.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: OS X 10.13.1

### Expected behaviour [期望结果]
There is global theme (color palette support), so you would think there is a way to define global bar/line/etc. styles.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
This is called "theme" in ECharts. See [this tutorial](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Overview%20of%20Style%20Customization) for more information.
You can use [ECharts Theme Builder](http://echarts.baidu.com/theme-builder/) to generate your own theme. But it's in Chinese only. Hopefully, you can find some translator to use it. Thanks.

**Comment by N3GIS** [comment]
@Ovilia series不能在主题中配置吗？
