### ISSUE TITLE
使用百度地图，在brush模式下，地图随着鼠标跟着移动，能否优化一下

### ISSUE THREAD

**Issue by a6318539** [apache/incubator-echarts#7797]
### One-line summary [问题简述]
使用百度地图扩展，点击toolbox进入选择模式，此时地图跟着鼠标左键拖动，有无解决办法，让地图不移动，退出选择模式再回复地图拖动

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by dfEric** [comment]
Duplicate of #6825
