### ISSUE TITLE
webpack主题无法按需引入

### ISSUE THREAD

**Issue by mengxiong10** [apache/incubator-echarts#7803]
### [版本及环境]
+ ECharts version [ECharts 版本]:v4.0.2

### 代码
```
import echarts from 'echarts/lib/echarts'
import 'echarts/lib/chart/line'

import 'echarts/theme/macarons'
```
### 说明
由于theme文件夹下面主题文件require('echarts') 导致按需引入没用,
建议改成'echarts/lib/echarts', 下图:

![image](https://user-images.githubusercontent.com/14135808/36628000-5001124a-1986-11e8-818a-e7e1f2049fd8.png)

**Comment by wlf100220** [comment]
这个问题还没解决吗 两年了

**Comment by plainheart** [comment]
#5567 5.3 会优化一下。
