### ISSUE TITLE
可以在新版加入markpoint效果吗

### ISSUE THREAD

**Issue by jacobcyl** [apache/incubator-echarts#7808]
### One-line summary [问题简述]
3.0以后貌似在地图中不能使用markpoint散点图闪耀效果了，我想实现类似：
http://echarts.baidu.com/echarts2/doc/example/map15.html
这个效果，做在实时在线的模拟。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: >3.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
在新版echarts实现类似 http://echarts.baidu.com/echarts2/doc/example/map15.html 的效果

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以使用散点图的 shadowBlur 实现，参考：http://gallery.echartsjs.com/editor.html?c=scatter-weibo

**Comment by ljxtest** [comment]
我也在找这个功能，4.0版本的effectScatter 只有一种涟漪的动画达不到以前闪烁的效果。
