### ISSUE TITLE
转为svg渲染方式后，有没有什么方式页面打印的时候自适应纸张大小，而不至于超出打印范围

### ISSUE THREAD

**Issue by node-rookie** [apache/incubator-echarts#7809]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
跟 Canvas 是一样的，图表的渲染位置和大小取决于容器的位置和大小，所以可以将容器宽度设为 100%，然后就能实现你的需求吧？
