### ISSUE TITLE
饼状图（Pie）细线超出半径

### ISSUE THREAD

**Issue by YoussiaTang** [apache/incubator-echarts#7817]
### One-line summary [问题简述]
Pie加载之后，出现细线超出半径

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: 62.0.3202.94（正式版本） （32 位）
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
            text: '',
            subtext: '',
            x: 'center'
          },
          tooltip: {
            trigger: 'item',
            formatter: "{a} <br/>{b} : {c}元 ({d}%)"
          },
          legend: {
            orient: 'horizontal',
            left: 'left',
            data: this.legendData
          },
          series: [
            {
              name: '单项目消费金额',
              type: 'pie',
              smooth: true,
              minAngle: 1,
              radius: '55%',
              center: ['50%', '60%'],
              data: this.seriesData,
              itemStyle: {
                emphasis: {
                  shadowBlur: 10,
                  shadowOffsetX: 0,
                  shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
              }
            }
          ]
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/13634781/36708257-2b13307a-1bad-11e8-8e91-e296961b5036.png)

**Comment by Ovilia** [comment]
把 this.seriesData 提供一下

**Comment by TangTang912** [comment]
"seriesData" : [ {
      "name" : "test1",
      "value" : "11.61"
    }, {
      "name" : "test2",
      "value" : "50.32"
    }, {
      "name" : "test3",
      "value" : "4.35"
    }, {
      "name" : "test4",
      "value" : "0.48"
    }, {
      "name" : "test5",
      "value" : "17.88"
    }, {
      "name" : "test6",
      "value" : "8.71"
    }, {
      "name" : "test7",
      "value" : "1.45"
    }, {
      "name" : "test8",
      "value" : "0.00"
    }, {
      "name" : "test9",
      "value" : "0.09"
    } ]

**Comment by TangTang912** [comment]
"seriesData" : [ {
      "name" : "test1",
      "value" : "11.61"
    }, {
      "name" : "test2",
      "value" : "50.32"
    }, {
      "name" : "test3",
      "value" : "4.35"
    }, {
      "name" : "test4",
      "value" : "0.48"
    }, {
      "name" : "test5",
      "value" : "17.88"
    }, {
      "name" : "test6",
      "value" : "8.71"
    }, {
      "name" : "test7",
      "value" : "1.45"
    }, {
      "name" : "test8",
      "value" : "0.00"
    }, {
      "name" : "test9",
      "value" : "0.09"
    } ]


gitbub上也已提供，麻烦处理下~




By YoussiaTang
在2018年2月28日 16:40，Wenli Zhang<notifications@github.com> 写道：

把 this.seriesData 提供一下

**Comment by Ovilia** [comment]
这应该是 Chrome 的 bug，在 Firefox、Safari 都无法复现。

http://gallery.echartsjs.com/editor.html?c=xry1I1mS_M&v=2
