### ISSUE TITLE
Mac版本safari下渲染曲线卡死

### ISSUE THREAD

**Issue by likaihua** [apache/incubator-echarts#7818]
### One-line summary [问题简述]

Mac版本safari下渲染曲线卡死（lineStyle->normal->type设置为dashed或dotted）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:safari浏览器11.0.3
+ OS Version [操作系统类型和版本]:Mac OS

### ECharts option [ECharts配置项]

```javascript
option = {
lineStyle: {
          normal: {
            type: 'dotted'
          }
        }
}

```

**Comment by Ovilia** [comment]
完整的 option 复制一下？
