### ISSUE TITLE
请教问题（如何让graph图显示的像tree一样）

### ISSUE THREAD

**Issue by jin10086** [apache/incubator-echarts#7819]
这是我画的在线demo
http://gallery.echartsjs.com/editor.html?c=xHycXr2GdM&v=2

但是我想让他显示成这样
![image](https://user-images.githubusercontent.com/15347911/36724924-9afd39ca-1bef-11e8-8d93-78ae445f14e4.png)

**Comment by Ovilia** [comment]
可以手动指定 x y 位置，或者使用树图 http://echarts.baidu.com/option.html#series-tree

**Comment by 15036900300** [comment]
@Ovilia 现在就是关于x y位置不好计算啊，我也遇到这个问题了，就是图形展示的节点每次是动态读取数据库的，每次都需要计算x y，现在计算出来的很不美观，也不够灵活，如果用树图有个问题是根节点不止一个

**Comment by Ovilia** [comment]
@15036900300 根节点多个的话，是不是可以用多个树图系列？

**Comment by 15036900300** [comment]
@Ovilia 其实要展示的图形跟楼主有点像，但是还有10节点跟15节点有关联，这样的图形

**Comment by Ovilia** [comment]
那就不是树，是图了？

**Comment by 15036900300** [comment]
@Ovilia 是的，现在我是通过动态计算坐标来实现了

**Comment by 2675569545** [comment]
> @Ovilia 是的，现在我是通过动态计算坐标来实现了

请问关于计算坐标的算法，您使用的是什么呢？如果不涉及商业秘密，能否给点思路

**Comment by 15036900300** [comment]
@2675569545 我写的比较简陋，是定义好中心轴，然后根据每层的节点数来计算坐标的
