### ISSUE TITLE
是否有提供经过实际布局之后的区域的“宽高位置”等信息（比如dataZoom区域，图表内容区域，legend区域）？

### ISSUE THREAD

**Issue by tun100** [apache/incubator-echarts#7820]
### One-line summary [问题简述]
是否有提供经过实际布局之后的区域的“宽高位置”等信息（比如dataZoom区域，图表内容区域，legend区域）？我目前在项目中开发需要在一个type为line的图表里用到onClick事件，ECharts的事件是需要鼠标到移动到数据所在的数据Y轴上对应的那一个圆点，但是我想不移动到数据的那个圆点，而是当高亮的线移动到某一个X轴上并点击就能触发onClick事件。  
我后来没有用官方的onClick事件，而是通过EChart.Instance.getDom().onClick的方式进行，可是我发现，除了图表内容区域之外，legend和dataZoom也会受到影响，所以现在问题就是，能否提供一个经过布局之后的各个区域的x，y，width，height等信息，我相信这个接口可以使得ECharts更加地自定义化（我计算过属性grid，但始终会有偏差）。  
 求前辈解答，谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Chrome 最新版本
+ OS Version [操作系统类型和版本]: Ubuntu

### Expected behaviour [期望结果]
提供经过布局之后的宽高和位置等接口信息的接口

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by LaiHuanMin** [comment]
求助求助
