### ISSUE TITLE
Y轴多余四个就显示重叠

### ISSUE THREAD

**Issue by tiangew** [apache/incubator-echarts#7821]
### One-line summary [问题简述]
如果有四个Y轴，其中两个显示会重叠。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.3
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Windows

### Expected behaviour [期望结果]
四个轴都是单独显示，不重叠。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```
![image](https://user-images.githubusercontent.com/2575795/36764589-13a51324-1be2-11e8-9c1c-36a7ef92ab46.png)

**Comment by smile7sky** [comment]
配置项

var colors = ['#ffbaa2', '#91cf96', '#c881d2', '#29b6f6'];
var option = {
    color: colors,

    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'cross'
        }
    },
    grid: {
        right: '20%'
    },
    toolbox: {
        feature: {
            dataView: {
                show: true,
                readOnly: false
            },
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    legend: {
        data: ['LVEF % (Echo)', 'Rhythm', 'Height', 'Weight']
    },
    xAxis: {
        type: 'category',
        axisTick: {
            alignWithLabel: true
        },
        data: ['Visit 1', 'Visit 2', 'Visit 3', 'Visit 4', 'Visit 5']
    },
    yAxis: [{
            type: 'value',
            name: 'LVEF % (Echo)',
            min: 0,
            max: 100,
            offset: 25,
            position: 'left',
            axisLine: {
                lineStyle: {
                    color: colors[0]
                }
            },
            axisLabel: {
                formatter: '{value} %'
            }
        },
        {
            type: 'value',
            name: 'Rhythm',
            min: 60,
            max: 140,
            position: 'right',
            offset: 80,
            axisLine: {
                lineStyle: {
                    color: colors[1]
                }
            },
            axisLabel: {
                formatter: '{value} bpm'
            }
        },
        {
            type: 'value',
            name: 'Height',
            min: 160,
            max: 190,
            position: 'right',
            axisLine: {
                lineStyle: {
                    color: colors[2]
                }
            },
            axisLabel: {
                formatter: '{value} cm'
            }
        },
        {
            type: 'value',
            name: 'Weight',
            min: 50,
            max: 100,
            position: 'right',
            axisLine: {
                lineStyle: {
                    color: colors[3]
                }
            },
            axisLabel: {
                formatter: '{value} kg'
            }
        }
    ],
    series: [{
            name: 'LVEF % (Echo)',
            type: 'line',
            yAxisIndex: 0,
            data: [80, 70, 30, 20, 35]
        },
        {
            name: 'Rhythm',
            type: 'line',
            yAxisIndex: 1,
            data: [80, 76, 79, 82, 80]
        },
        {
            name: 'Height',
            type: 'line',
            yAxisIndex: 2,
            data: [185, 184, 183, 184, 185]
        },
        {
            name: 'Weight',
            type: 'line',
            yAxisIndex: 3,
            data: [65, 65, 65, 65, 65]
        }
    ]
};
