### ISSUE TITLE
新版本导致原demo出错

### ISSUE THREAD

**Issue by yld134** [apache/incubator-echarts#7822]
原demo报错了，无法打开：
demo地址:http://echarts.baidu.com/examples/editor.html?c=lines3d-flights-on-geo3d&gl=1 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
谢谢反馈，正在修复
