### ISSUE TITLE
X-Axis labels overlapping

### ISSUE THREAD

**Issue by marianban** [apache/incubator-echarts#7827]
### One-line summary [问题简述]
X axis value labels are overlapping

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Chrome 64.0.3282.140 
+ OS Version [操作系统类型和版本]: Win 10

### Expected behaviour [期望结果]
Labels arranged in way that they won't overlap

### ECharts option [ECharts配置项]

```javascript
option = {  
  xAxis: [
    {
      type: 'value',            
      min: 1519801744433.3,
      max: 1519801694535.4,
    },
  ],
  yAxis: [
    {
      type: 'value',         
    },
  ],
  series: [
    {
      name: 'test',
      type: 'line',      
      data: [
        [1519801744433.3, 16], 
        [1519801754433.3, 20], 
        [1519801764433.3, 12], 
        [1519801774433.3, 17],
        [1519801694535.4, 12]
      ],
    },
  ],
}

```

### Other comments [其他信息]

http://jsfiddle.net/2753aecd/1/

![image](https://user-images.githubusercontent.com/5712367/36774873-11bd9a08-1c60-11e8-9e81-0a279f0bc281.png)

I'm trying to display time based signal but I can't use a standard time axis because my time resolution is higher then the native time used in browsers. So I decided to use value based axis with custom formatting, unfortunately I encountered this problem. I'm wondering if this is a desired behavior for value axis type? Thanks

**Comment by Yishu29** [comment]
No update on this issue?
