### ISSUE TITLE
小程序 echarts 和wepy 不能混用

### ISSUE THREAD

**Issue by MrYinZhe** [apache/incubator-echarts#7828]
### One-line summary [问题简述]

小程序 echarts 和wepy 不能混用?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

wepy  需要关闭ES6转ES5。
而echarts需要打开ES6转ES5。

**Comment by Ovilia** [comment]
把 ec-canvas 文件夹自行转下 ES5，然后每次编译的时候关闭 ES6 转 ES5？转好也欢迎开源一下哈~
