### ISSUE TITLE
k线图和柱状图加上dataZoom组件后在IE9中不能完全渲染

### ISSUE THREAD

**Issue by yongdu555** [apache/incubator-echarts#7835]
echarts 4.0.2 k线图和柱状图加上dataZoom组件后在IE9中不能完全渲染

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]:IE9
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
在IE9下使用dataZoom组件，拖动滑动块，k线图和柱状图都能完全渲染出来
![image](https://github.com/yongdu555/project/raw/master/2.jpg)

### Expected behaviour [实际结果]
在IE9下使用dataZoom组件，滑动块100%可以正常渲染，拖动滑动块，k线图和柱状图都只能渲染前三条数据
![image](https://github.com/yongdu555/project/raw/master/1.jpg)

### ECharts option [ECharts配置项]

```javascript
option = {
     dataZoom: [{
                type: 'inside',
                xAxisIndex: [0, 1],
                start: 50,
                end: 100
            }, {
                show: true,
                xAxisIndex: [0, 1],
                type: 'slider',
                top: '85%',
                start: 50,
                end: 100
            }],
 series: [{
                name: 'Dow-Jones index',
                type: 'candlestick',
                data: data.values,
                dimensions: ['open', 'close', 'highest', 'lowest', 'd'],
                itemStyle: {
                    normal: {
                        color: 'transparent',
                        color0: 'green',
                        borderColor: 'red',
                        borderColor0: null
                    }
                }     
            }]
}

```

**Comment by EmperorOfCinder** [comment]
我也发现了一模一样的问题

**Comment by EmperorOfCinder** [comment]
已经解决，bug出在 listProto.diff 函数，将this.getIndices()改为this._indices 就可以修正了
