### ISSUE TITLE
图表显示不全问题

### ISSUE THREAD

**Issue by wufeng123456** [apache/incubator-echarts#7837]
### One-line summary [问题简述]
做图表自适应功能时，遇到 外层div 宽高包含  resize图表宽高，但图表在生成时就部分被遮挡
如下图：
![qq 20180301142102](https://user-images.githubusercontent.com/22437517/36830196-97a074f8-1d5d-11e8-9a59-9bb33b58927b.png)

原以为是 外层div遮挡问题，查看html 
如下图：
![qq 20180301142149](https://user-images.githubusercontent.com/22437517/36830275-db4a6984-1d5d-11e8-91ad-0dd4fd4ab747.png)

发现生成图表已经被遮挡

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:     "echarts": "^3.7.1",
+ Browser version [浏览器类型和版本]: chrome    版本 64.0.3282.167（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: win10  

### Expected behaviour [期望结果]
canvas 内容 能否等比例缩放，小点没事但不出现遮挡（不溢出外层div）

### ECharts option [ECharts配置项]

```javascript

getGrid() {
    return {
      left: 10,
      right: 10,
      bottom: 20,
      top: 20,
      containLabel: true
    };
  }
option = {
      tooltip: {
        trigger: 'item',
        formatter: '{b} <br/>{a}: {c} ({d}%)'
      },
      grid: this.getGrid(),
      legend: {
        show: false,
        data: chartData.legendFlag === false ? [] : xData
      },
      calculable: true,
      series：{
          name: v.name,
          type: 'pie',
          data: v.data,
          animationEasing: 'cubicInOut',
          label: {
            normal: {
              formatter: '{b}: {c} ({d}%)'
            }
          },
          animationDuration: 1000
     }
}

```

**Comment by wufeng123456** [comment]
饼图设置grid不起作用，可以用 radius和center控制饼图在容器的位置，但还是会出现遮挡。
遮挡原因：
1、就是容器遮挡
2、外层自己写的div 的宽高小于 生成 canvas的宽高
问题还没解决 ,头疼

**Comment by lianliu22** [comment]
any update from Echarts team?

**Comment by xuchao008** [comment]
same problem +1

**Comment by airwin** [comment]
我们也遇到了类似的问题，应该是饼图的avoidLabelOverlap防标签冲突机制，在标签密集时错位渲染，导致的超出容器，目前还没找到好的方案，只能临时调整一下startAngle来尽量规避，等待官方的解决方案

**Comment by lianliu22** [comment]
@airwin Can you share your fix?

**Comment by airwin** [comment]
@lianliu22 我后来暂时修改了源码，参见 #8513

**Comment by realchoi** [comment]
@Ovilia 请问现在这个 bug 有更新吗？我用的 4.x 版本重现了这个问题。

**Comment by Z-soda** [comment]
top值的比例设大点，试试 “30%”

**Comment by Ovilia** [comment]
如果还有问题的话，建议重新开一个 issue，附上 demo，这里先关了。

**Comment by zhoufanglu** [comment]
最后解决了吗？
