### ISSUE TITLE
图表有多条y轴，但是y轴要实现可以拖拽功能

### ISSUE THREAD

**Issue by lkpTomorrow** [apache/incubator-echarts#7844]
### One-line summary [问题简述]
一个图表上准备有多条y轴，为了使用起来交互性好一些，y轴是可以左右随意移动的（拖拽），为了对比数据把其他的y轴都移动到一边；现在缺少y轴可以移动的方法！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts：3.0

### Expected behaviour [期望结果]
y轴可以有一个选中事件，左右移动

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lkpTomorrow** [comment]
项目有这样的需求，还必须实现，时间紧任务重，跪求

**Comment by mgsod** [comment]
> 项目有这样的需求，还必须实现，时间紧任务重，跪求

有解决方案了吗
