### ISSUE TITLE
关于echarts.getInstanceByDom的疑问

### ISSUE THREAD

**Issue by weimingxinas** [apache/incubator-echarts#7848]
### One-line summary [问题简述]

通过dom节点需要设置延时才能拿到实例？请问是怎么回事呢？而且设置100毫秒还是拿不到

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: window

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
init 之后就能马上拿到
