### ISSUE TITLE
中国各大区板块图（华北，西北，华南等大区）

### ISSUE THREAD

**Issue by watersea** [apache/incubator-echarts#7851]
请教一下 E charts 的中国版图 如何生成五大区的样式

**Comment by cuibei** [comment]
我这里有数据，你要不？

**Comment by chfw** [comment]
我也有自己写个库包含这些个大区。等我写好了，把链接放在这里。

**Comment by cuibei** [comment]
根据我的认识应该是七个大区。我的CSDN里有下载，文件也不大，地址是http://blog.csdn.net/abcmaopao/article/details/79425848

**Comment by chfw** [comment]
补一下地理知识，华南是指广东、广西、海南、香港、澳门吧。

**Comment by chfw** [comment]
现在给个预览。有待进一步修改再发布。

每个图的左上角是图的注册名，地图是个各个省的合集。有改进意见么？

![screen shot 2018-03-07 at 10 18 14](https://user-images.githubusercontent.com/4280312/37086995-efad2d48-21f0-11e8-8adc-115025303916.png)

**Comment by chfw** [comment]
这个我的项目：https://github.com/echarts-maps/echarts-china-misc-js

[戳这里预览](https://echarts-maps.github.io/echarts-china-misc-js/preview.html)
