### ISSUE TITLE
现在的省市数据用的民政部哪个版本生成的，请在页面说明一下。

### ISSUE THREAD

**Issue by cuibei** [apache/incubator-echarts#7852]
http://echarts.baidu.com/examples/editor.html?c=map-province
这个demo里可以下载到所有省的json数据，但是某些地名和民政部2017年11月的对应不上。
http://echarts.baidu.com/examples/vendors/echarts/map/json/province/xizang.json
里面是那曲地区，而2017年11月版本是那曲市。
问一下这些数据是用http://www.mca.gov.cn/article/sj/tjbz/a/2017/里面的哪个版本生成的么?

**Comment by cuibei** [comment]
希望得到解答！如果在那个demo加上最好了！

**Comment by chfw** [comment]
比如说，哪些地名对不上。

**Comment by cuibei** [comment]
典型的，在2017年11月民政部。西藏的阿里叫阿里市，而从demo下载的数据渲染的名称是阿里地区！

**Comment by chfw** [comment]
http://www.mca.gov.cn/article/sj/xzqh/1980/2019/202002281436.html

阿里地区没有改成市。
