### ISSUE TITLE
如何在关系图(graph，斥力图)的某一类节点上增加涟漪的效果？

### ISSUE THREAD

**Issue by szsheng** [apache/incubator-echarts#7859]
### One-line summary [问题简述]
如何在关系图(graph，斥力图)的某一类节点上增加涟漪的效果？
1）现有的节点闪烁，好像只支持type为"effectScatter“类型的散点图。本来想将散点覆盖在关系图的点上，可惜由于是斥力的效果无法定位坐标，所以没办法做。
2）如果采用 gif 动画图片作为节点，好像不能正常显示（只显示第一帧）。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [ Chrome 63.0.3239.108]:
+ OS Version [Windws 10 Pro]:

### Expected behaviour [期望结果]
支持对关系图节点涟漪（或闪烁）效果。

### ECharts option [ECharts配置项]

```javascript
option = {
	color: ["rgb(21,65,166)","rgb(170,77,189)","rgb(247,223,211)","rgb(147,169,243)","rgb(159,176,187)","rgb(98,112,43)","rgb(211,167,159)","rgb(145,162,128)","rgb(30,33,51)","rgb(21,176,31)","rgb(54,15,70)","rgb(116,235,121)","rgb(111,120,108)","rgb(31,40,2)","rgb(125,253,10)","rgb(102,121,97)","rgb(136,254,174)","rgb(81,32,85)","rgb(242,71,16)","rgb(163,163,211)","rgb(162,51,63)","rgb(238,244,238)","rgb(213,169,237)"],
	title: {
		text: ''
	},
	animationDurationUpdate: 0,
	animation: false,
	series: [
		{
			type: 'graph',
			layout: 'force',
			edgeSymbol: ['none', 'arrow'],
			edgeSymbolSize: [4, 6],
			data: [ { "id": "02_05_347", "name": "已知解析式求函数定义域", "symbolSize": 10, "category": "0", "x": 50, "y": 650 }, { "id": "02_05_344", "name": "函数的概念（图象）", "symbolSize": 20, "category": "1", "x": 200, "y": 650 }, { "id": "02_05_346", "name": "区间的概念及应用", "symbolSize": 15, "category": "2", "x": 350, "y": 650 }, { "id": "02_05_351", "name": "函数的值域", "symbolSize": 20, "category": "3", "x": 350, "y": 350 }, { "id": "02_05_350", "name": "换元法求函数解析式", "symbolSize": 30, "category": "4", "x": 450, "y": 350 }, { "id": "02_05_359", "name": "映射的相关问题", "symbolSize": 10, "category": "0", "x": 100, "y": 650 }, { "id": "02_05_348", "name": "抽象函数的定义域", "symbolSize": 20, "category": "1", "x": 250, "y": 650 }, { "id": "02_05_358", "name": "分段函数的性质应用-分类讨论", "symbolSize": 20, "category": "2", "x": 400, "y": 650 }, { "id": "02_05_345", "name": "函数的三要素与函数相等", "symbolSize": 25, "category": "3", "x": 400, "y": 350 }, { "id": "5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0", "name": "方程组法求函数解析式", "symbolSize": 10, "category": "4", "x": 500, "y": 350 }, { "id": "46824c0b-c20d-4b5a-8ed3-c80f65374f30", "name": "待定系数法求函数解析式", "symbolSize": 5, "category": "0", "x": 150, "y": 650 }, { "id": "18288e9e-a390-4146-8471-af23495e173d", "name": "判别式法求函数的值域", "symbolSize": 10, "category": "1", "x": 300, "y": 650 }, { "id": "90c767f3-e90f-44e7-999d-f9c5035494bb", "name": "函数定义域的常见运用", "symbolSize": 5, "category": "2", "x": 450, "y": 650 }, { "id": "5dfb90dc-ecaa-48d5-b899-7fb7f5112e12", "name": "观察法求解函数的值域", "symbolSize": 10, "category": "3", "x": 350, "y": 400 }, { "id": "48b30aa4-d44a-4cc9-b8d8-3634c07f89ca", "name": "代数换元法求函数的值域", "symbolSize": 10, "category": "4", "x": 450, "y": 400 }, { "id": "6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a", "name": "图像法求函数的值域", "symbolSize": 10, "category": "0", "x": 50, "y": 700 }, { "id": "c3c0f0a8-7895-4e55-bc78-c915565b1dba", "name": "基本不等式法求函数的值域", "symbolSize": 10, "category": "1", "x": 200, "y": 700 }, { "id": "b4745445-d86b-478a-927f-d064bf46b538", "name": "三角换元法求函数的值域", "symbolSize": 5, "category": "2", "x": 350, "y": 700 }, { "id": "0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b", "name": "分离常数法求函数的值域", "symbolSize": 10, "category": "3", "x": 400, "y": 400 }, { "id": "a5166031-c0a8-45f5-abdf-332b03b785b4", "name": "单调性法求函数的值域", "symbolSize": 10, "category": "4", "x": 500, "y": 400 }, { "id": "76aa2f38-f5db-4f9b-a433-07fc00c5b593", "name": "有界性法求函数的值域", "symbolSize": 10, "category": "0", "x": 100, "y": 700 }, { "id": "a4031622-7a7f-423c-8ac0-0776f5b73c13", "name": "hs锚点b", "symbolSize": 0, "category": "1", "x": 250, "y": 700 }, { "id": "6b64d633-7575-4fed-bc5b-4a31a19dcdbe", "name": "test锚点1", "symbolSize": 0, "category": "2", "x": 400, "y": 700 } ],
			links: [{"source":"02_05_347","target":"90c767f3-e90f-44e7-999d-f9c5035494bb"},{"source":"02_05_346","target":"02_05_347"},{"source":"02_05_344","target":"02_05_345"},{"source":"02_05_344","target":"02_05_359"},{"source":"02_05_344","target":"02_05_448"},{"source":"02_05_343","target":"02_05_344"},{"source":"02_05_346","target":"02_05_347"},{"source":"02_05_346","target":"02_05_348"},{"source":"02_05_345","target":"02_05_346"},{"source":"02_05_351","target":"02_05_385"},{"source":"02_05_351","target":"02_05_352"},{"source":"02_05_350","target":"02_05_351"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"02_05_351"},{"source":"02_05_350","target":"02_05_353"},{"source":"02_05_350","target":"02_05_351"},{"source":"02_05_350","target":"02_05_388"},{"source":"02_05_350","target":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0"},{"source":"02_05_348","target":"02_05_350"},{"source":"46824c0b-c20d-4b5a-8ed3-c80f65374f30","target":"02_05_350"},{"source":"02_05_349","target":"02_05_359"},{"source":"02_05_344","target":"02_05_359"},{"source":"02_05_348","target":"02_05_384"},{"source":"02_05_348","target":"02_05_552"},{"source":"02_05_348","target":"02_05_350"},{"source":"02_05_346","target":"02_05_348"},{"source":"02_05_358","target":"02_05_362"},{"source":"02_05_358","target":"02_05_389"},{"source":"02_05_354","target":"02_05_358"},{"source":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0","target":"02_05_358"},{"source":"02_05_345","target":"02_05_346"},{"source":"02_05_345","target":"02_05_349"},{"source":"02_05_345","target":"02_05_428"},{"source":"02_05_345","target":"2e27413e-5eaf-4ced-b300-df0c7402fa9c"},{"source":"02_05_344","target":"02_05_345"},{"source":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0","target":"02_05_358"},{"source":"02_05_350","target":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0"},{"source":"46824c0b-c20d-4b5a-8ed3-c80f65374f30","target":"02_05_350"},{"source":"18288e9e-a390-4146-8471-af23495e173d","target":"b4745445-d86b-478a-927f-d064bf46b538"},{"source":"c3c0f0a8-7895-4e55-bc78-c915565b1dba","target":"18288e9e-a390-4146-8471-af23495e173d"},{"source":"02_05_347","target":"90c767f3-e90f-44e7-999d-f9c5035494bb"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"a5166031-c0a8-45f5-abdf-332b03b785b4"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"02_05_351"},{"source":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca","target":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a"},{"source":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b","target":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca"},{"source":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a","target":"76aa2f38-f5db-4f9b-a433-07fc00c5b593"},{"source":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca","target":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a"},{"source":"c3c0f0a8-7895-4e55-bc78-c915565b1dba","target":"18288e9e-a390-4146-8471-af23495e173d"},{"source":"76aa2f38-f5db-4f9b-a433-07fc00c5b593","target":"c3c0f0a8-7895-4e55-bc78-c915565b1dba"},{"source":"18288e9e-a390-4146-8471-af23495e173d","target":"b4745445-d86b-478a-927f-d064bf46b538"},{"source":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b","target":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca"},{"source":"a5166031-c0a8-45f5-abdf-332b03b785b4","target":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b"},{"source":"a5166031-c0a8-45f5-abdf-332b03b785b4","target":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"a5166031-c0a8-45f5-abdf-332b03b785b4"},{"source":"76aa2f38-f5db-4f9b-a433-07fc00c5b593","target":"c3c0f0a8-7895-4e55-bc78-c915565b1dba"},{"source":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a","target":"76aa2f38-f5db-4f9b-a433-07fc00c5b593"}],
			
			categories: [{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"}],
			label: {
				normal: {
					show: false,
					position: 'inside',
					formatter: '{b}'
				},
				emphasis: {
					position: 'right',
					show: true
				}
			},
			
			itemStyle: {
				emphasis: {
					shadowBlur: 10,
					shadowOffsetX: 0,
					shadowColor: 'rgba(255, 0, 0, 1)'
				}
			},
			roam: true,
			focusNodeAdjacency: true,
			lineStyle: {
				normal: {
					width: 1,
					curveness: 0,
					opacity: 0.6
				}
			},
			
		}
	]
}

```

**Comment by oYo-Byte** [comment]
可以是用gif图片作为节点，但是要使用svg渲染模式。

**Comment by zhouwenjing123** [comment]
> ### One-line summary [问题简述]
> 如何在关系图(graph，斥力图)的某一类节点上增加涟漪的效果？
> 1）现有的节点闪烁，好像只支持type为"effectScatter“类型的散点图。本来想将散点覆盖在关系图的点上，可惜由于是斥力的效果无法定位坐标，所以没办法做。
> 2）如果采用 gif 动画图片作为节点，好像不能正常显示（只显示第一帧）。
> 
> ### Version & Environment [版本及环境]
> * ECharts version [ECharts 版本]:
> * Browser version [ Chrome 63.0.3239.108]:
> * OS Version [Windws 10 Pro]:
> 
> ### Expected behaviour [期望结果]
> 支持对关系图节点涟漪（或闪烁）效果。
> 
> ### ECharts option [ECharts配置项]
> ```js
> option = {
> 	color: ["rgb(21,65,166)","rgb(170,77,189)","rgb(247,223,211)","rgb(147,169,243)","rgb(159,176,187)","rgb(98,112,43)","rgb(211,167,159)","rgb(145,162,128)","rgb(30,33,51)","rgb(21,176,31)","rgb(54,15,70)","rgb(116,235,121)","rgb(111,120,108)","rgb(31,40,2)","rgb(125,253,10)","rgb(102,121,97)","rgb(136,254,174)","rgb(81,32,85)","rgb(242,71,16)","rgb(163,163,211)","rgb(162,51,63)","rgb(238,244,238)","rgb(213,169,237)"],
> 	title: {
> 		text: ''
> 	},
> 	animationDurationUpdate: 0,
> 	animation: false,
> 	series: [
> 		{
> 			type: 'graph',
> 			layout: 'force',
> 			edgeSymbol: ['none', 'arrow'],
> 			edgeSymbolSize: [4, 6],
> 			data: [ { "id": "02_05_347", "name": "已知解析式求函数定义域", "symbolSize": 10, "category": "0", "x": 50, "y": 650 }, { "id": "02_05_344", "name": "函数的概念（图象）", "symbolSize": 20, "category": "1", "x": 200, "y": 650 }, { "id": "02_05_346", "name": "区间的概念及应用", "symbolSize": 15, "category": "2", "x": 350, "y": 650 }, { "id": "02_05_351", "name": "函数的值域", "symbolSize": 20, "category": "3", "x": 350, "y": 350 }, { "id": "02_05_350", "name": "换元法求函数解析式", "symbolSize": 30, "category": "4", "x": 450, "y": 350 }, { "id": "02_05_359", "name": "映射的相关问题", "symbolSize": 10, "category": "0", "x": 100, "y": 650 }, { "id": "02_05_348", "name": "抽象函数的定义域", "symbolSize": 20, "category": "1", "x": 250, "y": 650 }, { "id": "02_05_358", "name": "分段函数的性质应用-分类讨论", "symbolSize": 20, "category": "2", "x": 400, "y": 650 }, { "id": "02_05_345", "name": "函数的三要素与函数相等", "symbolSize": 25, "category": "3", "x": 400, "y": 350 }, { "id": "5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0", "name": "方程组法求函数解析式", "symbolSize": 10, "category": "4", "x": 500, "y": 350 }, { "id": "46824c0b-c20d-4b5a-8ed3-c80f65374f30", "name": "待定系数法求函数解析式", "symbolSize": 5, "category": "0", "x": 150, "y": 650 }, { "id": "18288e9e-a390-4146-8471-af23495e173d", "name": "判别式法求函数的值域", "symbolSize": 10, "category": "1", "x": 300, "y": 650 }, { "id": "90c767f3-e90f-44e7-999d-f9c5035494bb", "name": "函数定义域的常见运用", "symbolSize": 5, "category": "2", "x": 450, "y": 650 }, { "id": "5dfb90dc-ecaa-48d5-b899-7fb7f5112e12", "name": "观察法求解函数的值域", "symbolSize": 10, "category": "3", "x": 350, "y": 400 }, { "id": "48b30aa4-d44a-4cc9-b8d8-3634c07f89ca", "name": "代数换元法求函数的值域", "symbolSize": 10, "category": "4", "x": 450, "y": 400 }, { "id": "6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a", "name": "图像法求函数的值域", "symbolSize": 10, "category": "0", "x": 50, "y": 700 }, { "id": "c3c0f0a8-7895-4e55-bc78-c915565b1dba", "name": "基本不等式法求函数的值域", "symbolSize": 10, "category": "1", "x": 200, "y": 700 }, { "id": "b4745445-d86b-478a-927f-d064bf46b538", "name": "三角换元法求函数的值域", "symbolSize": 5, "category": "2", "x": 350, "y": 700 }, { "id": "0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b", "name": "分离常数法求函数的值域", "symbolSize": 10, "category": "3", "x": 400, "y": 400 }, { "id": "a5166031-c0a8-45f5-abdf-332b03b785b4", "name": "单调性法求函数的值域", "symbolSize": 10, "category": "4", "x": 500, "y": 400 }, { "id": "76aa2f38-f5db-4f9b-a433-07fc00c5b593", "name": "有界性法求函数的值域", "symbolSize": 10, "category": "0", "x": 100, "y": 700 }, { "id": "a4031622-7a7f-423c-8ac0-0776f5b73c13", "name": "hs锚点b", "symbolSize": 0, "category": "1", "x": 250, "y": 700 }, { "id": "6b64d633-7575-4fed-bc5b-4a31a19dcdbe", "name": "test锚点1", "symbolSize": 0, "category": "2", "x": 400, "y": 700 } ],
> 			links: [{"source":"02_05_347","target":"90c767f3-e90f-44e7-999d-f9c5035494bb"},{"source":"02_05_346","target":"02_05_347"},{"source":"02_05_344","target":"02_05_345"},{"source":"02_05_344","target":"02_05_359"},{"source":"02_05_344","target":"02_05_448"},{"source":"02_05_343","target":"02_05_344"},{"source":"02_05_346","target":"02_05_347"},{"source":"02_05_346","target":"02_05_348"},{"source":"02_05_345","target":"02_05_346"},{"source":"02_05_351","target":"02_05_385"},{"source":"02_05_351","target":"02_05_352"},{"source":"02_05_350","target":"02_05_351"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"02_05_351"},{"source":"02_05_350","target":"02_05_353"},{"source":"02_05_350","target":"02_05_351"},{"source":"02_05_350","target":"02_05_388"},{"source":"02_05_350","target":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0"},{"source":"02_05_348","target":"02_05_350"},{"source":"46824c0b-c20d-4b5a-8ed3-c80f65374f30","target":"02_05_350"},{"source":"02_05_349","target":"02_05_359"},{"source":"02_05_344","target":"02_05_359"},{"source":"02_05_348","target":"02_05_384"},{"source":"02_05_348","target":"02_05_552"},{"source":"02_05_348","target":"02_05_350"},{"source":"02_05_346","target":"02_05_348"},{"source":"02_05_358","target":"02_05_362"},{"source":"02_05_358","target":"02_05_389"},{"source":"02_05_354","target":"02_05_358"},{"source":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0","target":"02_05_358"},{"source":"02_05_345","target":"02_05_346"},{"source":"02_05_345","target":"02_05_349"},{"source":"02_05_345","target":"02_05_428"},{"source":"02_05_345","target":"2e27413e-5eaf-4ced-b300-df0c7402fa9c"},{"source":"02_05_344","target":"02_05_345"},{"source":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0","target":"02_05_358"},{"source":"02_05_350","target":"5f3910b3-5a6d-4809-aa6c-6a8a10cfd3c0"},{"source":"46824c0b-c20d-4b5a-8ed3-c80f65374f30","target":"02_05_350"},{"source":"18288e9e-a390-4146-8471-af23495e173d","target":"b4745445-d86b-478a-927f-d064bf46b538"},{"source":"c3c0f0a8-7895-4e55-bc78-c915565b1dba","target":"18288e9e-a390-4146-8471-af23495e173d"},{"source":"02_05_347","target":"90c767f3-e90f-44e7-999d-f9c5035494bb"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"a5166031-c0a8-45f5-abdf-332b03b785b4"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"02_05_351"},{"source":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca","target":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a"},{"source":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b","target":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca"},{"source":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a","target":"76aa2f38-f5db-4f9b-a433-07fc00c5b593"},{"source":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca","target":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a"},{"source":"c3c0f0a8-7895-4e55-bc78-c915565b1dba","target":"18288e9e-a390-4146-8471-af23495e173d"},{"source":"76aa2f38-f5db-4f9b-a433-07fc00c5b593","target":"c3c0f0a8-7895-4e55-bc78-c915565b1dba"},{"source":"18288e9e-a390-4146-8471-af23495e173d","target":"b4745445-d86b-478a-927f-d064bf46b538"},{"source":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b","target":"48b30aa4-d44a-4cc9-b8d8-3634c07f89ca"},{"source":"a5166031-c0a8-45f5-abdf-332b03b785b4","target":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b"},{"source":"a5166031-c0a8-45f5-abdf-332b03b785b4","target":"0d3ba2e8-5ac7-4ee4-b64b-fa19489eac5b"},{"source":"5dfb90dc-ecaa-48d5-b899-7fb7f5112e12","target":"a5166031-c0a8-45f5-abdf-332b03b785b4"},{"source":"76aa2f38-f5db-4f9b-a433-07fc00c5b593","target":"c3c0f0a8-7895-4e55-bc78-c915565b1dba"},{"source":"6c7ec3f0-6a34-4a9f-96cc-4e10cf86213a","target":"76aa2f38-f5db-4f9b-a433-07fc00c5b593"}],
> 			
> 			categories: [{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"},{"name":"3"},{"name":"4"},{"name":"0"},{"name":"1"},{"name":"2"}],
> 			label: {
> 				normal: {
> 					show: false,
> 					position: 'inside',
> 					formatter: '{b}'
> 				},
> 				emphasis: {
> 					position: 'right',
> 					show: true
> 				}
> 			},
> 			
> 			itemStyle: {
> 				emphasis: {
> 					shadowBlur: 10,
> 					shadowOffsetX: 0,
> 					shadowColor: 'rgba(255, 0, 0, 1)'
> 				}
> 			},
> 			roam: true,
> 			focusNodeAdjacency: true,
> 			lineStyle: {
> 				normal: {
> 					width: 1,
> 					curveness: 0,
> 					opacity: 0.6
> 				}
> 			},
> 			
> 		}
> 	]
> }
> ```
> 
> ### Other comments [其他信息]

这个问题解决了吗
