### ISSUE TITLE
xAxis.data[i].textStyle 配置无效

### ISSUE THREAD

**Issue by chulinyin** [apache/incubator-echarts#7864]
### 问题简述
按照[官方文档](http://echarts.baidu.com/option.html#xAxis.axisLabel)，在[官方实例](http://echarts.baidu.com/examples/editor.html?c=line-simple)中，配置 `xAxis.data[i].textStyle` 无效。
> 想要让折线图横轴第一个标签左对齐，最后一个右对齐，中间的居中。而通过 xAxis.axisLabel 只能设置所有标签样式，于是想通过 xAxis.data[i].textStyle 单独设置每个标签的样式。

### 版本及环境
+ ECharts 版本: 4.0
+ 浏览器类型和版本: Chrome  64.0.3282.167
+ 操作系统类型和版本: macOS High Sierra 10.13.3

### 期望结果
能单独配置 x 轴的每个标签样式

### ECharts配置项

```javascript
option = {
    xAxis: {
        type: 'category',
        data: [{
            value: '周一',
            // 突出周一
            textStyle: {
                fontSize: 20,
                color: 'red'
            }
        }, '周二', '周三', '周四', '周五', '周六', '周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
}

```

### 其他信息
![image](https://user-images.githubusercontent.com/16412234/36967342-6c08dbd8-209a-11e8-8daa-1d954216056d.png)

按照[官方文档](http://echarts.baidu.com/option.html#xAxis.axisLabel)，在[官方实例](http://echarts.baidu.com/examples/editor.html?c=line-simple)中跑，结果发现`周一`标签样式没有变化。
![image](https://user-images.githubusercontent.com/16412234/36967094-c031a4e8-2099-11e8-8c51-5f06664d9c3f.png)

**Comment by BhavinPatel04** [comment]
Yes, only the style applied in 'axisLabel' works here. The 'textStyle' property does not work.

**Comment by Adelaide1014** [comment]
` xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        axisLabel:{
			textStyle:{
				color: 'red',
			}
		},
    },`

这个修改的是所有标签的颜色
