### ISSUE TITLE
How to calculate start and end while dataZoom event triggered ?

### ISSUE THREAD

**Issue by yanzijun** [apache/incubator-echarts#7881]
### One-line summary [问题简述]
How to calculate start and end while dataZoom event triggered ?
I have 1,000 more data on xAxis. 
And I want to calculate the ``index`` of xAxis data by ``start`` and ``end`` value.

I has already tried these two ways:
[1] [Question: Dynamically change data existing data on Zoom event](https://github.com/ecomfe/echarts/issues/4990#issuecomment-330160327)
[2] [折线图的dataZoom能否指定下标而不是百分比？](https://github.com/ecomfe/echarts/issues/1150)

Any one of ways which I tried is fail : (sometimes need subtract 1)
```javascript
Math.round(data.values.length*(param.start/100))
// or subtract 1
Math.round(data.values.length*(param.start/100)) - 1
```
or
```javascript
Math.floor(data.values.length*(param.start / 100)) 
// or subtract 1
Math.floor(data.values.length*(param.start / 100)) - 1
```
Are there any methods can calculate ``start Index`` and ``end Index`` exactly ?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4
+ Browser version [浏览器类型和版本]: Chrome 64
+ OS Version [操作系统类型和版本]: Linux (Ubuntu) 16.04

### My Code [我的代碼]
```javascript
var start = Math.floor(zoom.batch[0].start / 100 * this.Content.length)
var end = Math.ceil(zoom.batch[0].end / 100 * this.Content.length)
```
The index sometimes was correct and sometimes wasn't.

**Comment by alanchanzm** [comment]
datazoom事件接受两个参数，第二个参数是echart实例
可以通过`echartsInstance._coordSysMgr._coordinateSystems`找到坐标轴属性

**Comment by yanzijun** [comment]
@alanchanzm Thanks. I has already fixed it by some methods.
I forget to close issue. Sorry.

**Comment by abrahtomi** [comment]
> @alanchanzm Thanks. I has already fixed it by some methods.
> I forget to close issue. Sorry.

May I ask what your solution was?

**Comment by whyayen** [comment]
@abrahtomi I am sorry! I don't have solution now because it's a project of my former company. But I am sure about that I implemented charts with D3.js finally.
