### ISSUE TITLE
热力图显示

### ISSUE THREAD

**Issue by shanewds** [apache/incubator-echarts#7883]
假如将一块区域(正方形800MX800M)，按照每隔10M进行划分,总共的小方格数80*80=6400个,可以计算出落到每一个小方格的人数;返回值包括该小方格的区域坐标类似于(x1,y1,x2,y2)和对应的数量;而echarts热力图插件只是(x,y,value)进行表示的,相当于是一个点,而不是一个范围。如何写类似于两个点对应一个值进行表示如(x1,y1,x2,y2,value)

**Comment by pissang** [comment]
可以试试用自定义系列实现，参考这个极坐标系上的热力图 http://www.echartsjs.com/gallery/editor.html?c=custom-polar-heatmap

**Comment by wztscau** [comment]
找到方法了么，我也想实现一个范围而不是一个点
