### ISSUE TITLE
堆叠图y轴的刻度区间数能无限大吗？目前我测试是79个区间

### ISSUE THREAD

**Issue by lester001** [apache/incubator-echarts#7884]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
理论上是可以的，大于 79 的表现是？

**Comment by see311** [comment]
#7839 
可以看这个问题，Y轴大于79的时候就乱了
@pissang
