### ISSUE TITLE
Dynamically disable and enable roam

### ISSUE THREAD

**Issue by wzrdtales** [apache/incubator-echarts#7886]
# Type

- Question

# Description

We have placed an echart in the middle of the page. When you scroll down now, it will catch the mouse instantly and disrupt the user experience. We would like to dynamically enable and disable the roam parameter, as we do want that functionality, but want to explicitly enable it. It does not work setting it with setOptions after it has been set once already. Is there already a possibility to do this?

**Comment by pissang** [comment]
Can you paste the code?

**Comment by wzrdtales** [comment]
not yet unfortunately. it is a treemap, just make a long page and place a tree map with full width somewhere. We have however for now fixed it with an overlay that blocks interaction with the treemap before it gets unlocked.
