### ISSUE TITLE
使用dataset进行绘图时，当数据列过多时，如何取消legend的默认选中状态，或只指定前n个选中

### ISSUE THREAD

**Issue by liangWenPeng** [apache/incubator-echarts#7891]
### One-line summary [问题简述]

使用dataset进行绘图时，当数据列过多时，如何取消legend的默认选中状态，或只指定前n个选中，必须在selected里面逐个设置吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

Echarts : the last version

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以用代码生成 legend 的 selected 项

**Comment by hanfengcan** [comment]
可以参考这里http://echarts.baidu.com/api.html#action
