### ISSUE TITLE
公司期望做的图表效果。。。感觉有好多实现不了= =

### ISSUE THREAD

**Issue by kiccer** [apache/incubator-echarts#7897]
![image](https://user-images.githubusercontent.com/23536402/37138406-edd98472-22e4-11e8-9806-ab913a14a82b.png)
这是期望效果。。。
仪表盘圆角效果，径向渐变，内阴影，这些都做不了啊。。。
还有发现一个
```
      // 这是3.X版本的

      itemStyle: {
        normal: {
          color: {
            image: document.getElementById('trendHeatChartPieBg'),
            repeat: 'no-repeat'
          }
        }
      }
```
这个里面 `repeat` 没有拉伸之类的其他选项。。。为了刚好适应，还要把图片处理到和canvas相同大小- -
希望ECharts团队可以考虑一下这块，能不能增加一些新功能，小弟拜谢~~

**Comment by zlpcrmm** [comment]
兄弟 最后实现没有？

**Comment by territoryfan** [comment]
如果光这样一个仪表盘 ，自己用canvas 画一个吧
