### ISSUE TITLE
markLine值大于坐标轴最大值时会显示不出，应该如何处理这种情况

### ISSUE THREAD

**Issue by tianhen0527** [apache/incubator-echarts#7907]
### One-line summary [问题简述]

官方示例 http://echarts.baidu.com/demo.html#bar-tick-align
修改以下代码
```js
series : [
{
name:'直接访问',
type:'bar',
barWidth: '60%',
data:[10, 52, 200, 334, 390, 330, 220],
markLine : {
data : [{
name : '均线',
yAxis : 500
}]
}
}
]
```
markLine显示不出，该如何处理

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Wheandis** [comment]
```js
yAxis: {
    max () {
        return 500;
    }
}
```
可以通过这种方式设置Y轴最大值
![image](https://user-images.githubusercontent.com/8326999/48049893-1d45c800-e1db-11e8-93cb-03de8c04f92a.png)
