### ISSUE TITLE
当渲染模型为‘svg’，饼图lengend.type = 'scroll'时，图例文字丢失，分页标签覆盖住了图例，类型为‘canvas’显示正常。

### ISSUE THREAD

**Issue by bigbigbigbear** [apache/incubator-echarts#7908]
### One-line summary [问题简述]
当渲染模型为‘svg’，饼图lengend.type = 'scroll'时，图例文字丢失，分页标签覆盖住了图例，类型为‘canvas’显示正常。
![9RoLxe.png](https://s1.ax1x.com/2018/03/10/9RoLxe.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.X
+ Browser version [浏览器类型和版本]: chrome 64.0.3282.168（正式版本） （32 位）
+ OS Version [操作系统类型和版本]: windows 64bit

### Expected behaviour [期望结果]
‘svg’模式下显示正常

### ECharts option [ECharts配置项]

```javascript
option = {
legend:{
```
                type: 'scroll',
                orient: 'vertical',
                right: 10,
                top: 10,
                bottom: 10,
                textStyle: {
                    color: '#333'
                },
                formatter: function (name) {
                    var oa = option.series[0].data;
                    for(var i = 0; i < option.series[0].data.length; i++){
                        if(name==oa[i].name){
                            return name + '  ' + parseInt(oa[i].value);
                        }
                    }
                },
                data: []
            },
```
}

```

**Comment by gracelinmumu** [comment]
渲染模型为canvas类型，图例为scroll时也有问题，具体描述见https://github.com/ecomfe/echarts/issues/7807

**Comment by Ovilia** [comment]
Please follow #9565 .
