### ISSUE TITLE
图表类型为pictorialBar时不支持stack配置

### ISSUE THREAD

**Issue by gracelinmumu** [apache/incubator-echarts#7916]
### One-line summary [问题简述]
图表类型为bar时，支持stack。
而图表类型为pictorialBar时为什么不支持stack配置呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0+
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lagelisu** [comment]
同问，目前的版本好像不支持堆叠的功能

**Comment by 100pah** [comment]
什么场景下，需要 pictorialBar 支持 stack 呢？如果场景合理，可以考虑支持 ~

**Comment by lagelisu** [comment]
@100pah 

![_20180910144846](https://user-images.githubusercontent.com/19690851/45280891-b1abeb00-b508-11e8-93fe-6435633d5cda.png)
这种场景，echarts目前支持吗 (运行环境 ie9)

**Comment by gu0zh1q1ang** [comment]
Still CANNOT make it in 2025 with version v5.6.0, but find a tricky solution [!here](https://www.makeapie.cn/echarts_content/x1X3VynDa-.html) , which render endpoints with pictorialBar but still use normal bar as main parts.
