### ISSUE TITLE
Webpage not working

### ISSUE THREAD

**Issue by anandbhaskaran** [apache/incubator-echarts#7921]
The webpage of echarts for visualizing themes is not working.

http://echarts.baidu.com/echarts2/doc/example/theme.html

**Comment by luissmg** [comment]
Hi. That is the old version of echarts and Id on't even know if they maintain that version.

You can try to use the new version and see the docs. I will leave you two links:

- [Theme's download page](http://echarts.baidu.com/download-theme.html)
- [Theme builder](http://echarts.baidu.com/theme-builder/)

In the second link you can see and try all default themes and build your own if you want.
