### ISSUE TITLE
在事件触发后，页面已经加载china.js的情况下地图显示不全，只有海南诸岛

### ISSUE THREAD

**Issue by liuhensiyuhua** [apache/incubator-echarts#7931]
### One-line summary [问题简述]

在事件触发后（比如点击事件），页面已经加载china.js的情况下地图显示不全，只有海南诸岛

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
这说明china.js 并未加载成功。
