### ISSUE TITLE
GEOJSON格式的文件无法加载，试了其他的可以。唯独"type": "LineString"格式的不能显示

### ISSUE THREAD

**Issue by WesleyYangJava** [apache/incubator-echarts#7935]
### One-line summary [问题简述]

使用GEOJSON 的lineString类型的文件无法显示地图。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.4
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:window10

### Expected behaviour [期望结果]

能够在地图上面显示河流信息的地图。

### ECharts option [ECharts配置项]

```javascript
option = {
	    	itemStyle:{
	    		areaColor:'#EEE',
	    		borderColor:'#000'
	    	},
	    	center:[102.9803466796875,30.097613277217132],
	    	nameMap:{
	    		'ddh':'DDD'
	    	},
	        series: [{
	        	name:'DDh MAP',
	            type: 'map',
	            roam:true,
	            hoverable:true,
	            map: 'ddh',
	            itemStyle: {  
                    normal: {  
                        borderWidth:1,  
                        borderColor:'#cccccc',  
                        color: '#f3f3f3',  
                        label: {  
                            show: false,  
                            textStyle: {  
                                color: '#ff0000'  
                            }  
                        }  
                    },  
                    emphasis: {                 // 也是选中样式  
                        borderWidth:1,  
                        borderColor:'#00ffff',  
                        color: '#ffffff',  
                        label: {  
                            show: true,  
                            textStyle: {  
                                color: '#ff0000'  
                            }  
                        }  
                    }  
                }
	        }]
	    

}

```

### Other comments [其他信息]

html
`
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<link rel="stylesheet" href="../../css/bootstrap.css">
<link rel="stylesheet" href="../../css/styles.css">
<style>
.div1{
	background-color:yellow;
	margin-left:auto;
	margin-right:auto;
	padding:0;
	algin:center;
	margin:1px;
	witdh:300px;	
	height:300px;
}
</style>
</head>
<body>
<div id="map" class="div1">
</div>
</body>
<script src="../../js/jquery.min.js"></script>
<script src="../../js/jquery.js"></script>
<script src="../../js/bootstrap.min.js"></script>
<script src="../../js/jquery.dataTables.min.js"></script>
<script src="../../js/dataTables.bootstrap.js"></script>	
<script src="../../js/custom.js"></script>	
<script src="../../js/echarts/lib/echarts.js"></script>
<script src="../../json/map.js"></script>		
</html>
`
js
`
$(function(){
	$.get('../../json/map8.json', function (ddhJson) {
	    echarts.registerMap('ddh', ddhJson);
	    var chart = echarts.init(document.getElementById('map'));
	    console.log(echarts.getMap('ddh'))
	    chart.setOption({
	    	itemStyle:{
	    		areaColor:'#EEE',
	    		borderColor:'#000'
	    	},
	    	center:[102.9803466796875,30.097613277217132],
	    	nameMap:{
	    		'ddh':'DDD'
	    	},
	        series: [{
	        	name:'DDh MAP',
	            type: 'map',
	            roam:true,
	            hoverable:true,
	            map: 'ddh',
	            itemStyle: {  
                    normal: {  
                        borderWidth:1,  
                        borderColor:'#cccccc',  
                        color: '#f3f3f3',  
                        label: {  
                            show: false,  
                            textStyle: {  
                                color: '#ff0000'  
                            }  
                        }  
                    },  
                    emphasis: {                 // 也是选中样式  
                        borderWidth:1,  
                        borderColor:'#00ffff',  
                        color: '#ffffff',  
                        label: {  
                            show: true,  
                            textStyle: {  
                                color: '#ff0000'  
                            }  
                        }  
                    }  
                }
	        }]
	    });
	});
});
`
geojson:

`
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "stroke": "#22a406",
        "stroke-width": 10,
        "stroke-opacity": 10
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            103.809814453125,
            30.840931139029916
          ],
          [
            103.612060546875,
            30.35391637229704
          ],
          [
            104.1888427734375,
            30.15462722077597
          ],
          [
            104.4964599609375,
            30.53387657299763
          ],
          [
            104.39208984375,
            30.911651004518244
          ],
          [
            103.282470703125,
            31.606609719226917
          ],
          [
            103.853759765625,
            30.831497881307918
          ]
        ]
      }
    }
  ]
}
`

**Comment by chfw** [comment]
请用http://echarts.baidu.com/option.html#series.lines
详情：https://github.com/ecomfe/echarts/issues/7709
