### ISSUE TITLE
使用svg渲染时，tooltip指示轴文本内容显示位置错误

### ISSUE THREAD

**Issue by realeve** [apache/incubator-echarts#7947]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/448208/37499150-34b6e4b6-28fd-11e8-80f2-6850478efc2e.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/448208/37499178-4eb9268a-28fd-11e8-9c5a-4ebe86512056.png)

### ECharts option [ECharts配置项]

```javascript
 var myChart = echarts.init(document.querySelector("#container"), null, {
        renderer: "canvas"
    });
    var option = {
        xAxis: {
            type: 'category',
            data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        },
        tooltip: {
            type: 'axis',
            axisPointer: {
                type: 'cross'
            }
        },
        yAxis: {
            type: 'value'
        },
        series: [{
            data: [820, 932, 901, 934, 1290, 1330, 1320],
            type: 'line'
        }]
    };

    myChart.setOption(option, true);

```

**Comment by Paul-Kijtapart** [comment]
**Update**
I found that this bug does not happen with echarts@3.8.5

**Comment by mecha9** [comment]
This bug started in 4.0.3 release commit: https://github.com/apache/incubator-echarts/commit/0d19f000884531b2ec45a8e7ed0de797ad636505?diff=unified

The 'fix stupid mistake' commit before it did not have this problem. Unfortunately the 4.0.3 release commit is very big.

**Comment by Ovilia** [comment]
Fixed in https://github.com/ecomfe/zrender/commit/bef18915d6cc66eb7b927cb327a2d38aa6e0fec4
