### ISSUE TITLE
echarts4.0以上版本“线特效”拖动图层，残影严重问题

### ISSUE THREAD

**Issue by tangqinGiser** [apache/incubator-echarts#7953]
对接示例发现echarts版本升级到4.0以上后，线条特效示例拖动残影严重，并且在拖动结束后，在之前的效果显示的位置还会留下痕迹。以下为echarts官方示例录制效果（这张动图残留痕迹可能看不太请，官网示例可重现该问题）：
![echarts4](https://user-images.githubusercontent.com/30792630/37505501-1fcb902e-2920-11e8-88bb-8fc73d746879.gif)
亲测echats3.8.5并没有出现该问题。是否拖拽事件处理有所改变，导致该问题？

**Comment by tangqinGiser** [comment]
![u05y h3lu4 kdri 3v0 qx](https://user-images.githubusercontent.com/30792630/37505674-fdd00256-2920-11e8-8a8b-dda858c88383.png)
这张底图残留痕迹清楚一点儿。

**Comment by dfEric** [comment]
animation默认开启，关掉就好了 setOption({animation:false}),

**Comment by tangqinGiser** [comment]
你的意思是这样么？这样设置依旧有残影



tangqin@supermap.com
 
发件人： eric
发送时间： 2018-03-16 14:50
收件人： ecomfe/echarts
抄送： tangqinGiser; Author
主题： Re: [ecomfe/echarts] echarts4.0以上版本“线特效”拖动图层，残影严重问题 (#7953)
animation默认开启，关掉就好了 setOption({animation:false}),

**Comment by tangqinGiser** [comment]
myChart.setOption(option = {
        animation: false,
        bmap: {}，
        series:[]
}
您的意思是这样么？若是的话，刚试了下，还是不行。

**Comment by dfEric** [comment]
我刚才也试了，不行，但是gallery中的demo: http://gallery.echartsjs.com/editor.html?c=bmap-bus 没有这个问题，官方示例(http://echarts.baidu.com/examples/editor.html?c=lines-bmap-effect)设置第一个series的zlevel为2也会好一些，你可以试试

**Comment by tangqinGiser** [comment]
http://gallery.echartsjs.com/editor.html?c=bmap-bus 这个示例没有问题是因为用的版本是3.8.0，第二个方式试了下，真的没有问题了，谢谢~



tangqin@supermap.com
 
发件人： eric
发送时间： 2018-03-16 16:00
收件人： ecomfe/echarts
抄送： tangqinGiser; Author
主题： Re: [ecomfe/echarts] echarts4.0以上版本“线特效”拖动图层，残影严重问题 (#7953)
我刚才也试了，不行，但是gallery中的demo: http://gallery.echartsjs.com/editor.html?c=bmap-bus 没有这个问题，官方示例(http://echarts.baidu.com/examples/editor.html?c=lines-bmap-effect)设置第一个series的zlevel为2也会好一些，你可以试试
