### ISSUE TITLE
backgroundColor:'none'不能正常消除背景色

### ISSUE THREAD

**Issue by TianXinX** [apache/incubator-echarts#7957]
### One-line summary [问题简述]
使用dark主题，默认具有背景颜色
更新到echarts4后
配置backgroundColor:'none' 背景色为纯黑色
更新前使用版本3.7.0，可以正常消除背景颜色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]:  Chrome 63.0.3239.132
+ OS Version [操作系统类型和版本]: Windows10

### Expected behaviour [期望结果]
希望可以支持backgroundColor:'none'的情况下无背景色

### ECharts option [ECharts配置项]

```javascript
option = {
   backgroundColor:'none',
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
}

```

**Comment by 100pah** [comment]
可设为 `null` 清除颜色。
