### ISSUE TITLE
对于漏斗图，当使用数据集提供数据时，工具提示回调函数参数dataIndex不正确

### ISSUE THREAD

**Issue by ChandradipJ** [apache/incubator-echarts#7960]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: Google Chrome  65.0.3325.162 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: Ubuntu 17.10

### Expected behaviour [期望结果]

dataIndex应该是屏幕数据点索引或数据集数组索引.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
能否麻烦贴出 option，从能能定位问题。
