### ISSUE TITLE
echarts4版本更换主题怎么设置

### ISSUE THREAD

**Issue by 56651971** [apache/incubator-echarts#7962]
在官网找不到更换主题的方法，用3的方法setTheme()试了没有效果。
要怎么才能实现更换主题实时更新图表呢

**Comment by yaofeiliu** [comment]
同样想知道

**Comment by Ovilia** [comment]
http://echarts.baidu.com/download-theme.html 最后有使用方法，如果要更换主题，需要重新调 init

**Comment by 56651971** [comment]
@Ovilia 试过了。重新init也不行，因为对应的ID已经实例化了，不会再重新实例化

**Comment by Ovilia** [comment]
先 dispose
