### ISSUE TITLE
4.0版本的scatter地图标记有错

### ISSUE THREAD

**Issue by daxiga** [apache/incubator-echarts#7965]
### One-line summary [问题简述]

4.0版本的scatter地图标记，显示的是坐标不是给于标记的数值

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
echarts 4.0 
谷歌浏览器
win7

### Expected behaviour [期望结果]

哪里可以修改，或者怎样设置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
在这里可以修改：<http://echarts.baidu.com/option.html#series-scatter.label.formatter>
