### ISSUE TITLE
堆叠图tooltip显示与图表的顺序不一致

### ISSUE THREAD

**Issue by wephotos** [apache/incubator-echarts#7968]
### One-line summary [问题简述]
堆叠图tooltip显示的图例与图表的顺序不一致，是相反的,看起来很不方便

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:all
+ OS Version [操作系统类型和版本]:all

### Expected behaviour [期望结果]

可以添加一个配置项可反转tooltip中的选项

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
tooltip 堆叠目前是依照系列声明的顺序显示的。

**Comment by zh-cn-qi** [comment]
在垂直堆叠的柱图下，tooltip堆叠顺序和柱图的顺序就是相反的了，看起来很别扭，希望可以提供配置选项。

**Comment by NathanYukai** [comment]
+1

**Comment by shikelong** [comment]
怎么怎么解决这个问题？

**Comment by zeroHu** [comment]
+1

**Comment by Fzzzzy** [comment]
+1

**Comment by susiwen8** [comment]
Will be support in 5.0
#12947
