### ISSUE TITLE
为什么echarts的click事件对于timeline的前进后退键无效？

### ISSUE THREAD

**Issue by ZhuGYao** [apache/incubator-echarts#7970]
### One-line summary [问题简述]
click事件对于timeline的前进以及后退键无效？捕获不到相应的点击事件,为什么这样设计？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:谷歌最新版
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
点击之后，可以触发相应事件，并且可以获得点击后，所对应的数据。

### ECharts option [ECharts配置项]

```javascript


```

### Other comments [其他信息]

![timeline](https://user-images.githubusercontent.com/24791960/37592450-a71919a8-2ba9-11e8-90b2-a0085f3a57e3.png)

**Comment by 100pah** [comment]
timeline 上的控制按钮本身已有给定的功能，所以并没有提供 click 事件。

**Comment by ZhuGYao** [comment]
这个问题其实是我在想办法解决上一个我提问的问题，就是播放的时候出现渲染Bug的那个，因为解决不了那个，我只好每选择一个时间点都进行clear(),然后获取到当前时间点赋值Option后，重新setOption。点击时间点以及点击开关都可以有相应事件，但是前进后退无法捕获，所以还是会出现渲染Bug.
虽然有一个timelineChange 事件可以监听，但是他也无法区分是否是前进后退键还是自动播放，以至于在自动播放时也会每一个时间点都进行重新setOption。导致页面不停重新绘制。所以我想找一个可以监听前进后退的事件，每点击一次都可以监听到，或者是可以有一个flag进行辨别.
另外就算不点击，路线在时间轴的控制下，自动播放四十秒左右也会渲染出错，以至于路线起点不再正确，而是在路线的一半进行绘制。
希望您能认真看一下我的回复，非常感谢！！！ @100pah

**Comment by ZhuGYao** [comment]
这个是对渲染那个问题解决的折中方案，但是还是有问题。希望可以解答一下，真心谢谢！！！ @100pah @leeight @cnberg @xvaara @firede

**Comment by ZhuGYao** [comment]
求解，万分感谢，大佬们！！！ @100pah @leeight @cnberg @xvaara @firede

**Comment by ZhuGYao** [comment]
大佬们可否回复一下我！我只想知道是否是Bug！还是我配置的问题！非常感谢！ @100pah @leeight @cnberg @xvaara @firede
