### ISSUE TITLE
数据量大的情况下，地图图层覆盖数据点

### ISSUE THREAD

**Issue by Vekaco** [apache/incubator-echarts#7971]
### One-line summary [问题简述]
数据量大的情况下，地图图层覆盖数据点

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]: IE10/chrome/firefox
+ OS Version [操作系统类型和版本]:windows7+/macOS 10.2.x+

### Expected behaviour [期望结果]
不论数据量大小，地图图层不应该覆盖数据点

### ECharts option [ECharts配置项]

可访问 http://www.mxonline.top/search/index.html
```javascript
option = {

}

```

### Other comments [其他信息]

1k 条数据显示正常，当数据量增加到10k条时出现地图覆盖数据点的情况
![1000](https://user-images.githubusercontent.com/6688756/37598647-c26a2486-2bbd-11e8-8f48-62dc603f7750.PNG)

![10000](https://user-images.githubusercontent.com/6688756/37718916-c469fa84-2d5e-11e8-9a8b-2681d9e6ae22.PNG)

**Comment by 100pah** [comment]
您的第二个图片似乎没有上传成功。所以还不知道怎么复现这个问题。

**Comment by clddup** [comment]
相同的问题
