### ISSUE TITLE
关于自定义Toolbox里面用的icon的pathData格式

### ISSUE THREAD

**Issue by shikelong** [apache/incubator-echarts#7972]
hi, 我想了解一下，

是不是pathData格式只支持包含单个path元素的svg?
如果一个svg包含了多个path元素，怎么转为echarts需要的path://的格式呢？

因为好像直接使用svg的话， svg的颜色不会随着选择/主题去改变。所以尽量想使用pathData形式来显示toolbox的图片

谢谢

**Comment by 100pah** [comment]
可以使用工具（比如 adobe illustrator）来合并 svg 路径。
