### ISSUE TITLE
 在条形图上，markPoints不会呈现。

### ISSUE THREAD

**Issue by ChandradipJ** [apache/incubator-echarts#7974]
在条形图上，markPoints不会呈现。

### One-line summary [问题简述]

在条形图上，markPoints数据设置为坐标时，不会呈现markPoints。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Ubuntu 17.10

### Current behavior [当前行为]
![image](https://user-images.githubusercontent.com/34739185/37694650-f9654c0e-2cee-11e8-874a-eff33f739af7.png)

### Expected behaviour [期望结果]

标记点应该在指定的坐标上呈现。

### ECharts option [ECharts配置项]

```javascript
option = {
	xAxis: {
		data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
	},
	yAxis: {},
	series: [{
		type: 'bar',
		data:[220, 182, 191, 234, 290, 330, 310],
		markPoint: {
			data: [
				{
					name: "p1",
					coord: ["Tue", 300],
				},
				{
					name: "p2",
					coord: ["Thu",200],
				},
			],
			label: {
				show: true
			},
		},
	}]
};

```

**Comment by 100pah** [comment]
您的问题是什么。

**Comment by ChandradipJ** [comment]
我已经更新了这个问题，希望现在您能理解这个问题。
仍然是我的问题是，通过上面提供的“选项”设置，标记点不会显示在之前的echart版本中显示的设置相同。

**Comment by algaeReed** [comment]
> 我也有同样的问题，柱状图里面没法显示markPoint。使用的是react-native-secharts的第三方库，使用的是4.x的Echarts版本

https://github.com/apache/echarts/issues/18468#issuecomment-1494102276
