### ISSUE TITLE
折线图是否有click事件，取得当前的x轴的数值

### ISSUE THREAD

**Issue by cwtuan** [apache/incubator-echarts#7987]
![image](https://user-images.githubusercontent.com/3455798/37708783-e5e6d96e-2d42-11e8-9595-31b34c1531f6.png)

能否在用户点击的时候，取得当前的x轴的数值。

以上图为例，希望能得到"周三"

**Comment by Genxx** [comment]
chart.getZr().on('click', function(param) {
    // var hz = param.name //横坐标的值
    console.log(param)
  })
试一下吧
