### ISSUE TITLE
折线图官网示例，只渲染出了点，没有把线段渲染出来

### ISSUE THREAD

**Issue by king-king** [apache/incubator-echarts#7988]
### One-line summary [问题简述]

运行官网折线图示例，结果只把点渲染出来了，没有把线渲染出来

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.2.3
+ Browser version [浏览器类型和版本]:chrome最新版
+ OS Version [操作系统类型和版本]:wind7

### Expected behaviour [期望结果]

希望能渲染出折线，但是只有点渲染出来了，线没渲染出来

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        areaStyle: {}
    }]
};

```

### Other comments [其他信息]

问题如下：只有点渲染出来了，线段没有渲染出来。由于是canvas，所以很不好定位问题原因。
![image](https://user-images.githubusercontent.com/8537319/37714802-662396f0-2d55-11e8-9f07-32f10679b85e.png)

**Comment by king-king** [comment]
我这是在一个很复杂的环境里运行，同时存在react和angularjs脚本，是否存在其他脚本影响了echarts本身的渲染机制？没有任何报错，加上是canvas渲染，所以从结果上调试有限，现在没有任何思路了

**Comment by 100pah** [comment]
去掉 `areaStyle: {}` 试试？
