### ISSUE TITLE
echarts legend Is the toggle function when clicked?

### ISSUE THREAD

**Issue by JaesunPark** [apache/incubator-echarts#7995]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: -
+ OS Version [操作系统类型和版本]: -

### Expected behaviour [期望结果]

eCharts line type When I click on legend in the chart, I ask if there is a function that is implemented as toggle type now :)
(Korean : eCharts line type Chart에서 legend를 클릭하였을 때 toggle 형태로 구현되는 기능이 현재 존재하는지 여쭤 봅니다 :))

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pchaganti** [comment]
👍
