### ISSUE TITLE
小程序中怎么获取点击折线图后的值

### ISSUE THREAD

**Issue by Genxx** [apache/incubator-echarts#7996]
想在折线图上方固定显示点击折线图上各个点的值，但是
myChart.on('click', function (params) {
    console.log(params);
});
这个在小程序中中并用不了。

且手机在折线图上按着左右移动，能获取折线图上的值。

**Comment by hgq520** [comment]
添加点击事件，只有点在了折线图的label圆点上，才会触发事件。因为不支持tooltip，所以无法手机在折线图上按着左右移动，能获取折线图上的值？
