### ISSUE TITLE
setOption增加数据，坐标轴会自动到最右边

### ISSUE THREAD

**Issue by liuweinan0575** [apache/incubator-echarts#8001]
### One-line summary [问题简述]
使用setOption增加数据，坐标轴会跟着往右移动。
再有缩放的情况下，用户当前看到最左边的数据，如果使用了setOption增加数据，那边坐标轴会自动到最右边。
setOption这种方式影响了用户看图表，用户希望还在它看到的（最左边的数据）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: Chrome Version 65.0.3325.162 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: maxOs High Sierra

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
因为您没有提供 option，所以不能知道这个问题的具体原因。
但是我猜测可能可以设置 `yAxis.axisLine.onZero: false` 试试。

**Comment by liuweinan0575** [comment]
@100pah 
比如下面的配置：
option = {
    title: {
        text: '动态数据',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'cross',
            label: {
                backgroundColor: '#283b56'
            }
        }
    },
    legend: {
        data:['最新成交价', '预购队列']
    },
    toolbox: {
        show: true,
        feature: {
            dataView: {readOnly: false},
            restore: {},
            saveAsImage: {}
        }
    },
    dataZoom: {
        show: false,
        start: 0,
        end: 100
    },
    xAxis: [
        {
            type: 'category',
            boundaryGap: true,
            data: (function (){
                var now = new Date();
                var res = [];
                var len = 10;
                while (len--) {
                    res.unshift(now.toLocaleTimeString().replace(/^\D*/,''));
                    now = new Date(now - 2000);
                }
                return res;
            })()
        },
        {
            type: 'category',
            boundaryGap: true,
            data: (function (){
                var res = [];
                var len = 10;
                while (len--) {
                    res.push(len + 1);
                }
                return res;
            })()
        }
    ],
    yAxis: [
        {
            type: 'value',
            scale: true,
            name: '价格',
            max: 30,
            min: 0,
            boundaryGap: [0.2, 0.2]
        },
        {
            type: 'value',
            scale: true,
            name: '预购量',
            max: 1200,
            min: 0,
            boundaryGap: [0.2, 0.2]
        }
    ],
    dataZoom: [
          {
            type: 'inside',
            xAxisIndex: [0, 0],
            start: 0,
            end: 40
          },
          {
            xAxisIndex: [0, 1],
            type: 'inside',
            start: 0,
            end: 40
          }
        ],
    series: [
        {
            name:'预购队列',
            type:'bar',
            xAxisIndex: 1,
            yAxisIndex: 1,
            data:(function (){
                var res = [];
                var len = 10;
                while (len--) {
                    res.push(Math.round(Math.random() * 1000));
                }
                return res;
            })()
        },
        {
            name:'最新成交价',
            type:'line',
            data:(function (){
                var res = [];
                var len = 0;
                while (len < 10) {
                    res.push((Math.random()*10 + 5).toFixed(1) - 0);
                    len++;
                }
                return res;
            })()
        }
    ]
};

app.count = 11;
setInterval(function (){
    axisData = (new Date()).toLocaleTimeString().replace(/^\D*/,'');

    var data0 = option.series[0].data;
    var data1 = option.series[1].data;
    // data0.shift();
    data0.push(Math.round(Math.random() * 1000));
    // data1.shift();
    data1.push((Math.random() * 10 + 5).toFixed(1) - 0);

    // option.xAxis[0].data.shift();
    option.xAxis[0].data.push(axisData);
    // option.xAxis[1].data.shift();
    option.xAxis[1].data.push(app.count++);

    myChart.setOption(option);
}, 2100);

我在缩放的同时拖到了最左边。当我正在看最左边的数据的时候，定时器获取了新数据，然后重新渲染了。我希望setOption后，它可以偷偷的进行渲染，而不影响我当前在看数据的操作（实际情况是清新渲染了，我又要缩放并拖到最左边，看之前的数据）
