### ISSUE TITLE
echarts graph 节点过多如何通过检索形式高亮显示出被检索到的数据

### ISSUE THREAD

**Issue by shitiankexin** [apache/incubator-echarts#8022]
### One-line summary [问题简述]
action.graph.focusNodeAdjacency
dispatchAction({
    type: 'focusNodeAdjacency',
    // 使用 dataIndex 来定位节点。
    dataIndex: 12
})
通过上面的配置，我可以实现单击的时候高亮单击的指定节点以及其所有邻接节点，单击事件中提供了params 参数形式，可以直接获取到 dataIndex的值。

_注意： 由于项目中node的数据特别多！_
******重点****：我怎么通过页面的一个文本框输入的值 来进行高亮显示检索到的节点数据(初衷: 想用文本框的效果实现 单击事件的效果形式！)，检索形式我不知道如何获取到dataIndex的值**

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: Google Chrome-版本 63.0.3239.132（正式版本）
+ OS Version [操作系统类型和版本]: windows 10

### Expected behaviour [期望结果]
期望通过文本检索实现 单击某节点进行高亮显示当前节点以及其所有邻接节点！

**Comment by loveliangakai** [comment]
谢谢大佬
