### ISSUE TITLE
关于legend自定义显示的问题

### ISSUE THREAD

**Issue by hanfengcan** [apache/incubator-echarts#8023]
### One-line summary [问题简述]

在实际使用中,类似于图片的这种,容器空间比较小,数据项目比较多的情况.legend会和图重叠.
是否能够和tooltip一样自定义修改样式呢.
或者说增加停靠特性或者hover之类的

![_20180326155519](https://user-images.githubusercontent.com/4559753/37893598-22b59d16-310e-11e8-8b37-7bc1685034f0.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
legend 具有停靠或者hover特性

**Comment by ZSH-HSZ** [comment]
可以设置饼状图的位置

**Comment by hanfengcan** [comment]
@ZSH-HSZ 设置位置只能简单的避免,如果有系列名很长的话,也可能会影响到.

不过可以将数量小的整合成其他
