### ISSUE TITLE
geo.label.emphasis被series(scatter)的散点遮挡问题

### ISSUE THREAD

**Issue by ZXand618** [apache/incubator-echarts#8036]
### One-line summary [问题简述]
通过geo给地图地图增加rich标签，省份高亮时显示，但标签会被图上的散点遮挡……效果如下图所示：
![default](https://user-images.githubusercontent.com/17038735/38004442-d8b9f2c2-326e-11e8-9674-5be52e902744.png)
经测试无法给geo.label单独配置zlevel，而修改geo和散点series的zlevel顺序时，散点会被地图遮挡，无法响应鼠标动作（显示tooltip）。
想修改label的position，放在容器固定位置，但发现position是相对于省份区域的；
想用tooltip实现，但发现geo没有tooltip；
尝试叠加series(map),使用tooltip实现，但发现map没有tooltip.rich……

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts.min.js，version4.0.4
+ Browser version [浏览器类型和版本]:Chrome，版本 65.0.3325.181（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:Microsoft Windows 10 教育版，10.0.16299 暂缺 Build 16299

### Expected behaviour [期望结果]
省份高亮时显示rich标签，标签要在散点上层，或者能够显示在容器特定位置（地图散点区域之外）
求大神解答……
谢谢~

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://gallery.echartsjs.com/editor.html?c=xHyO6au_cG&v=2

**Comment by xChu666** [comment]
2024年了，使用gl实现这个效果的时候也是出现了这个问题，无解...
