### ISSUE TITLE
Calendar scatter with problems in some months

### ISSUE THREAD

**Issue by luissmg** [apache/incubator-echarts#8047]
### One-line summary
When using series `type` as `scatter` and `coordinateSystem` as `calendar` some months have the days out of position and the month as his line out of place too. In this cases the calendar and day labels also change positions for some weird reason.

### Version & Environment
+ ECharts version: 4.0.4
+ Browser version: Firefox Quantum 59.0.2
+ OS Version: Windows 10

### Expected behaviour:
I would expect the same behaviour as in the other months. Check the screenshots and **ECharts option** section in this issue!

### ECharts option
Access to [this page](https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-pie) and in the function `getVirtulData` change the following variables:

```javascript
var date = +echarts.number.parseDate('2018-10-01');
var end = +echarts.number.parseDate('2018-11-01');
```

Also change the `range` property in `option` object to ``'2018-10'``.

### Other comments
_All the screenshots have been taken width the same window size and position to make comparison easier!_

**Working month _(2018-09)_:** _(calendar in the middle)_
![imagem](https://user-images.githubusercontent.com/20660551/38037813-8f264394-32a1-11e8-8c34-273a34082d4f.png)

**Non-working month _(2018-10)_:** _(calendar in the bottom for some reason)_
![imagem](https://user-images.githubusercontent.com/20660551/38037875-b73b1724-32a1-11e8-9713-fb6ccd18df35.png)

**Comment by MickaelNeves** [comment]
+1

**Comment by luissmg** [comment]
So, I was exploring the library and got news.
The problem with the positioning of the day (31) going on top is with (I think) the line 356 in [Calendar.js](https://github.com/apache/incubator-echarts/blob/master/src/coord/calendar/Calendar.js). I tried some stuff and it actually solved the problem, but only for this month. My solution was then adding bugs in other months.
Besides that, my solution was only fixing the position of the day. The lines were still wrong, so I think there is a problem with the function `_renderLines` (or any other callend inside) in [CalendarView.js](https://github.com/apache/incubator-echarts/blob/master/src/component/calendar/CalendarView.js).

Can someone look into this?
