### ISSUE TITLE
鼠标拖动时间轴进行播放，Bmap会跟着一起拖动，并且设置事件后，效果也不理想。

### ISSUE THREAD

**Issue by ZhuGYao** [apache/incubator-echarts#8054]
### One-line summary [问题简述]
鼠标拖动时间轴进行播放，Bmap会跟着一起拖动，并且设置事件后，效果也不理想。我基本上将echarts上的所有鼠标事件都用了，思路就是在发生鼠标事件的时侯将地图的拖动禁用，放开鼠标后再打开，但是效果非常差，基本是不可行的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:谷歌最新
+ OS Version [操作系统类型和版本]:Win10

### Expected behaviour [期望结果]
鼠标在时间轴拖动，地图不会随着动。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![bug](https://user-images.githubusercontent.com/24791960/38066099-142c7cf6-3339-11e8-89fc-d9f39940917d.png)

**Comment by a6318539** [comment]
一样的问题 应该是个bug

**Comment by ZhuGYao** [comment]
找到解决方案了吗？？谢谢 @a6318539
