### ISSUE TITLE
Display only specific labels for xAxis using formatter. Chart not displayed

### ISSUE THREAD

**Issue by BhavinPatel04** [apache/incubator-echarts#8064]
Example: 
`    xAxis: {
        type: 'category',
        data: ['a', 'a', 'a', 'Week 9',  'a', 'a', 'Week 10'],
        axisLabel: {
          formatter: function(value) {
            if(value != 'a') {
              return value;
            }
          }
    }
}    `

If this option is passed, chart is not even displayed.

I only want to show week numbers in the labels, no 'a'. any suggestion?

**Comment by Adelaide1014** [comment]
I think your question is not because passed  'a';
xAxis.data is the label shown in xAxis,you passed it,just don't show the label
the char type I test is 'type: 'line','
