### ISSUE TITLE
有什么办法可以将timeline的拖拽播放功能禁掉？？？

### ISSUE THREAD

**Issue by ZhuGYao** [apache/incubator-echarts#8066]
### One-line summary [问题简述]
有什么办法可以将timeline的拖拽播放功能禁掉？？？就只能靠点击时间点进行播放，不能拖着时间点前进。禁止拖拽，但是可以靠点击对应的时间点，只是单纯禁止拖拽。有解决办法吗？谢谢。万分感谢！！！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:谷歌最新
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![tuo](https://user-images.githubusercontent.com/24791960/38122099-9295c404-3405-11e8-9056-687ec2013cf2.png)

**Comment by komagic** [comment]
虽然没用过这个功能，但是我提供一个思路，首先判断是否有拖拽事件，然后给指定元素的拖拽事件函数清除或重新给一个新函数应该就可以了
