### ISSUE TITLE
echarts怎么在世界地图添加中国省份分界线

### ISSUE THREAD

**Issue by Mying666** [apache/incubator-echarts#8076]
### One-line summary [问题简述]
世界地图是各个国家的轮廓，中国地图里是各个省份的轮廓。目前想做一个世界地图，其中中国可以有各个省份的划分，请问怎样可以把china.js和world.js两个地图文件融合到一起？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
把 china feature 去掉 加入 35个省市自治区

**Comment by Mying666** [comment]
@chfw world.js里面的轮廓是按经纬度写的，china.js里面的轮廓{
            "id": "710000",
            "geometry": {
                "type": "MultiPolygon",
                "coordinates": [
                    [
                        "@@°Ü¯Û",
                        "@@ƛĴÕƊÉɼģºðʀ\\ƎsÆNŌÔĚänÜƤɊĂǀĆĴĤǊŨxĚĮǂƺòƌâÔ®ĮXŦţƸZûÐƕƑGđ¨ĭMó·ęcëƝɉlÝƯֹÅŃ^Ó·śŃǋƏďíåɛGɉ¿IċããF¥ĘWǬÏĶñÄ",
                        "@@\\p|WoYG¿¥Ij@",
                        "@@¡@V^RqBbAnTXeQr©C",
                        "@@ÆEEkWqë I"
                    ]
                ],
                "encodeOffsets": [
                    [
                        [
                            122886,
                            24033
                        ],
                        [
                            123335,
                            22980
                        ],
                        [
                            122375,
                            24193
                        ],
                        [
                            122518,
                            24117
                        ],
                        [
                            124427,
                            22618
                        ]
                    ]
                ]
            },
            "properties": {
                "cp": [
                    121.509062,
                    25.044332
                ],
                "name": "台湾",
                "childNum": 5
            }
        },
发现里面的数字都是很大很大的那种，感觉算法不一样，试过你说的那种方法，融合之后不抱错，也不出图。请问你有融合好的js或者json吗？

**Comment by Quintalq** [comment]
我也遇到这个问题了

**Comment by Mying666** [comment]
自己改的地图json，把需要的省份地图添加到中国地图里@Quintalq

**Comment by Quintalq** [comment]
谢谢您的回答，我已经这样改好了，但是如果想要所有国家的地图呢，如果把所有国家的json加进去感觉有点不现实，但是我这边只能用离线地图服务，您有没有做过这种呢

**Comment by bianfengshuo** [comment]
你好，请问下这个问题最后解决了吗？是怎样解决的？我也遇到这个问题了，怎样在世界地图中将中国区的省份的分割线也画出来，598846619@qq.com   有合并的world.js发给我一份，谢谢

**Comment by liwanglin12** [comment]
上面二位可否提供一份合并后的 GeoJson 呢？非常感谢。
