### ISSUE TITLE
坐标轴中grid支持虚线显示吗？

### ISSUE THREAD

**Issue by wuranhw** [apache/incubator-echarts#8085]
### One-line summary [问题简述]
坐标轴中grid支持虚线显示吗，如何实现，翻阅配置项手册没有找到，谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#yAxis.splitLine.lineStyle.type

**Comment by wuranhw** [comment]
@pissang 谢谢，大神能帮忙回答下另外一个issue吗？‘
bar实现鼠标左键点击高亮/右键点击取消高亮不生效
’
