### ISSUE TITLE
柱状图横坐标字符串很长如何截取才不会让数据错位？？

### ISSUE THREAD

**Issue by wuranhw** [apache/incubator-echarts#8102]
### One-line summary [问题简述]
我最近在项目组开发过程中遇到这样一个场景：
1）用到echarts4.0版本bar做柱状图，横坐标代表系统监视员名字，是最长255个字符的名字
那么排版上怕排布不下，所以想截取16个字符+'...'这样的方式展示，全名在点击柱状图时用悬浮tip字符串模板体现出来
但是这样会有个问题，数据还能正确映射到y轴的值吗？
有谁知道咋个截取吗？谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by emloxe** [comment]
问题解决了吗?可否提供一下思路

**Comment by territoryfan** [comment]
@wuranhw ，可以鼠标移入 文字 ，显示完整  https://github.com/territoryfan/echarts
