### ISSUE TITLE
bug，小程序真机调试bug。模拟器没有问题，真机调试出问题。

### ISSUE THREAD

**Issue by disook** [apache/incubator-echarts#8107]
模拟器开始es6转es5，开启代码压缩。

![image](https://user-images.githubusercontent.com/36912513/38425209-d155d946-39e5-11e8-8a08-5b720dd6fd16.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
ECharts 超过了 500k，会跳过转 es5 的。这个问题看起来是调试器基础库版本太低？
