### ISSUE TITLE
sankey图links中存在循环数据导致页面卡死并且无异常信息提示

### ISSUE THREAD

**Issue by hyZhang0701** [apache/incubator-echarts#8117]
### One-line summary [问题简述]
sankey图links中存在循环数据导致页面卡死并且无异常信息提示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4.0.4
+ Browser version [浏览器类型和版本]: 版本 65.0.3325.181（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:macOS Sierra 版本10.12.4

### Expected behaviour [期望结果]
sankey图links中存在循环数据时给出异常提示信息

### ECharts option [ECharts配置项]

```javascript
option = {
series: {
        type: 'sankey',
        layout:'none',
        data: [{
            name: 'a'
        }, {
            name: 'b'
        }],
        links: [{
            source: 'a',
            target: 'b',
            value: 5
        },{
            source: 'b',
            target: 'a',
            value: 5
        }]
    }
}

```

**Comment by hyZhang0701** [comment]
希望能给予支持

**Comment by deqingli** [comment]
你好，这个问题我现在在跟进会尽快处理的

**Comment by hyZhang0701** [comment]
@deqingli 赞，辛苦辛苦

**Comment by deqingli** [comment]
你好，这个问题是由于原始输入数据中存在环导致的。sankey 图理论上只支持有向无环图（DAG, Directed Acyclic Graph），所以原先的布局算法是默认输入数据是有向无环的，当有环的时候就会陷入死循环，当然这主要是我前期开发的时候欠考虑导致的，我会好好反思的。修改后的布局算法是按拓扑顺序遍历计算布局的，如果判断有环就会报错，不再绘制。

**Comment by deqingli** [comment]
修改后的功能会随下个版本一起发布，欢迎验证，如果有问题可以 reopen 这个 issue. ～ 祝好
