### ISSUE TITLE
effectScatter 有没有类似 scatter3D的用法 

### ISSUE THREAD

**Issue by succulen-plants** [apache/incubator-echarts#8118]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
scatter3D 暂时不支持动画效果
