### ISSUE TITLE
dataZoom 样式可有配置项

### ISSUE THREAD

**Issue by emloxe** [apache/incubator-echarts#8119]
### One-line summary [问题简述]
在黑色背景中 dataZoom  边框颜色为白色，可有配置项更改datazoom的颜色，官网文档已经查看，并没有相关配置的介绍

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Other comments [其他信息]

![_15232452349898](https://user-images.githubusercontent.com/15011303/38478424-2c5dcf72-3beb-11e8-822e-ae07eee79416.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#dataZoom-slider.borderColor
