### ISSUE TITLE
echarts3以上版本不能使用clickable属性

### ISSUE THREAD

**Issue by yang1eo** [apache/incubator-echarts#8137]
### One-line summary [问题简述]

要设置x轴、y轴标签为可点击，echarts2的版本可以使用clickable：true，但使用echarts3和echarts4版本不可以，是用其他属性代替了吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.x
+ Browser version [浏览器类型和版本]:Google Chrome 版本 65.0.3325.181（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: win 10 

### Expected behaviour [期望结果]

在echarts3或echarts4中与clickable同功能的参数是什么？
实现X轴、Y轴名称标签可以被点击。

**Comment by pissang** [comment]
3 之后需要将 http://echarts.baidu.com/option.html#xAxis.silent 和 http://echarts.baidu.com/option.html#xAxis.triggerEvent 同时开启
