### ISSUE TITLE
Splitline 'interval' function not get invoke for value axis.  

### ISSUE THREAD

**Issue by amittonge** [apache/incubator-echarts#8139]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by amittonge** [comment]
Please add support of the interval for value axis also. Or suggest any other way to do this.

**Comment by gakkifans** [comment]
我也有同样的问题，而且interval作为function的时候，在呈现上有点迷

**Comment by pissang** [comment]
interval 作为回调函数，是在类目轴的时候决定每个类目是否显示，数值轴因为是连续的，所以没有这个场景
