### ISSUE TITLE
graph 股权持股比例指向少一个指向

### ISSUE THREAD

**Issue by ass233** [apache/incubator-echarts#8147]
现在links 指向是7个，但是出来关系图确实6个求指教
"links":[
　　　　{
　　　　　　"source":"benefit1",
　　　　　　"id":"43.686%",
　　　　　　"target":"benefit0"
　　　　},
　　　　{
　　　　　　"source":"benefit6",
　　　　　　"id":"68.370%",
　　　　　　"target":"benefit1"
　　　　},
　　　　{
　　　　　　"source":"benefit2",
　　　　　　"id":"0.420%",
　　　　　　"target":"benefit1"
　　　　},
　　　　{
　　　　　　"source":"benefit3",
　　　　　　"id":"100.000%",
　　　　　　"target":"benefit2"
　　　　},
　　　　{
　　　　　　"source":"benefit4",
　　　　　　"id":"100.000%",
　　　　　　"target":"benefit3"
　　　　},
　　　　{
　　　　　　"source":"benefit5",
　　　　　　"id":"100.000%",
　　　　　　"target":"benefit4"
　　　　},
　　　　{
　　　　　　"source":"benefit7",
　　　　　　"id":"100.000%",
　　　　　　"target":"benefit6"
　　　　}
　　]

我是通过id做的指向关系，benefit5 和benefit7   那么是重复的  但是指向是不一样的，但是benefit5指向是有的，benefit7指向是没有的，求指教 谢谢！

**Comment by pissang** [comment]
请发一个可以复现这个问题的链接，可以在 http://gallery.echartsjs.com/explore.html 创建一个

**Comment by ass233** [comment]
http://gallery.echartsjs.com/editor.html?c=xHybfUqaiz&v=1  这是我创建的表 求求大神帮忙解决下 急需  在线等  谢谢

**Comment by Lily-Jian** [comment]
原因在legend写错。
legend.data[i].name string，图例项的名称，应等于某系列的name值（如果是饼图，也可以是饼图单个数据的 name）。
因为你的配置项里name没有等于data.name，所以默认从0开始，所以你一共可以显示的类别只到4。而你的benefit5.category等于5，大于4，所以该节点没有显示，所以连线也不会显示。
