### ISSUE TITLE
candlestick图表tooltip不显示“Open”“Close”“Lowest”“Highest”这几项数据

### ISSUE THREAD

**Issue by DemoHu** [apache/incubator-echarts#8149]
### One-line summary [问题简述]
官方candlestick实例中的demo代码有关于“Open”“Close”“Lowest”“Highest”这几项数据的tooltip设置，但是图中并没有这几项数据
[candlestick-brush实例](http://echarts.baidu.com/examples/editor.html?c=candlestick-brush)
`tooltip: {
   formatter: function (param) {
    param = param[0];
    return [
     'Date: ' + param.name + '<hr size=1 style="margin: 3px 0">',
     'Open: ' + param.data[0] + '<br/>',
     'Close: ' + param.data[1] + '<br/>',
     'Lowest: ' + param.data[2] + '<br/>',
     'Highest: ' + param.data[3] + '<br/>'
    ].join('');
  }`

![2](https://user-images.githubusercontent.com/26042365/38714047-f6457b6e-3f06-11e8-8612-3181899317bb.png)
![3](https://user-images.githubusercontent.com/26042365/38714051-f8ab4186-3f06-11e8-871c-c2008e3cd223.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新官方demo
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DemoHu** [comment]
![3](https://user-images.githubusercontent.com/26042365/38714020-d2c080c6-3f06-11e8-8169-8154153547f8.png)
没有“Open”等这几项数据的展示

**Comment by pissang** [comment]
好像是 series.tooltip.formatter 没起作用 @100pah 看下？

**Comment by toien** [comment]
> 好像是 series.tooltip.formatter 没起作用 @100pah 看下？

是的呢，4.7.0 貌似还有这个问题

**Comment by leosj** [comment]
@pissang @100pah 5.3.1也是同样的问题，4年过去了
