### ISSUE TITLE
Feat Request: Add arrow to the data line in line chart. 给折线加个箭头。

### ISSUE THREAD

**Issue by chenxxzhe** [apache/incubator-echarts#8153]
### One-line summary [问题简述]

可不可给折线图(type: line) 折线的右端加个箭头？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4
+ Browser version [浏览器类型和版本]: any
+ OS Version [操作系统类型和版本]: any

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Zamlos** [comment]
Actually, that would be interesting
