### ISSUE TITLE
tooltip 默认时文字前面相应颜色的圆点，在设置 tooltip.formatter 后，如何显示？

### ISSUE THREAD

**Issue by maoyr** [apache/incubator-echarts#8161]
### One-line summary [问题简述]
tooltip 默认时文字前面相应颜色的圆点，在设置 tooltip.formatter 后，不能显示了。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

tooltip 默认时文字前面相应颜色的圆点，在设置 tooltip.formatter 后，如何显示？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by coldq** [comment]
+1

**Comment by territoryfan** [comment]
@maoyr  都用formatter了 ，圆点也可以自己定义啊

**Comment by 100pah** [comment]
可使用 
`var markerHTML = echarts.util.format.getTooltipMarker('#123456');`
