### ISSUE TITLE
请问一张地图，如何让一部分边界线为虚线，一部分为实线？

### ISSUE THREAD

**Issue by komagic** [apache/incubator-echarts#8166]
### One-line summary [问题简述]
请问注册好一张地图，如何才能让一部分边界线为虚线，一部分为实线？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
I want to know too.

**Comment by komagic** [comment]
我认为 zrender 可以实现，只是不知道渲染 geo 二维数组 边界 经纬度的方法在哪里？
