### ISSUE TITLE
`xAxis.data.textStyle` is not working

### ISSUE THREAD

**Issue by zunsthy** [apache/incubator-echarts#8168]
### One-line summary [问题简述]

Axis `data` option can't specify text style.

坐标轴 `data` 设置的文本样式未生效。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: All
+ OS Version [操作系统类型和版本]: All

### Expected behaviour [期望结果]

X-axis "周一" label will be red color.

X坐标轴上的“周一”显示为红色。

### ECharts option [ECharts配置项]

```javascript
option = {
  xAxis: {
    type: 'category',
    data: [{
      value: '周一',
      textStyle: { color: 'red' },
    }, '周二', '周三', '周四', '周五', '周六', '周日'],
  },
  yAxis: {},
  series: [{
    type: 'line',
    data: [3, 1, 2, 5, 3, 1, 2],
  }],
};
```

### Other comments [其他信息]

Doc: http://echarts.baidu.com/option.html#xAxis.data.textStyle

**Comment by cuijian-dexter** [comment]
@zunsthy The latest version seems to have been fixed.Try it
