### ISSUE TITLE
能否给出一个echars的版本属性呢？

### ISSUE THREAD

**Issue by ZXJ-Git** [apache/incubator-echarts#8174]
### One-line summary [问题简述]
能否给出一个echars的版本属性呢？
比方说在初始化后能在初始化的对象里面得到echarts的版本信息，这样方便通过版本信息，设置不同的echarts配置，帮助兼容浏览显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts.version
