### ISSUE TITLE
3D地图下，产生点与点之间的连线，鼠标hover在线上时，怎么触发tooltip显示数据

### ISSUE THREAD

**Issue by WQMDC** [apache/incubator-echarts#8179]
### One-line summary [问题简述]
3D地图下，在地图上使用3D连线，怎样让鼠标hover到线上时，line的tooltip显示出数据？？？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
可以在鼠标hover到线上时，tooltip可以显示出数据

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
3d 的线暂时不支持 tooltip
