### ISSUE TITLE
关于table表格形式展示数据

### ISSUE THREAD

**Issue by toweave** [apache/incubator-echarts#8189]
### One-line summary [问题简述]
1. 在做数据可视化与表格数据切换的时候，需要添加多个维度，如果用table的行、列合并非常不方便；
2. 现在有商业数据分析工具，已经做了类似的操作（用canvas实现的）；
3. 下图展示table数据形式，从table数据可以切换到可视化（饼、柱、折等图）（注：前端自己交互实现）

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/12064408/38925190-7224de90-4331-11e8-9320-44ef90cca97b.png)
![image](https://user-images.githubusercontent.com/12064408/38925214-89c40986-4331-11e8-901a-c9bec1b6bcf5.png)

![image](https://user-images.githubusercontent.com/12064408/38925493-5c48dc9c-4332-11e8-911e-de717c4c7665.png)
![image](https://user-images.githubusercontent.com/12064408/38925471-4adfeb4e-4332-11e8-9b96-e0cc373fb6b3.png)

**Comment by chfw** [comment]
我也想知道更多。

**Comment by toweave** [comment]
你的意思是没有描述清楚吗？

**Comment by chfw** [comment]
哦，哪到不是。注册一下自己的名字，将来好查询。

**Comment by toweave** [comment]
@pissang  在多维度数据，且在数据维度上有聚合等操作，table 数据表格本身会有一个很好的树形结构，也是可是化的一部分。因此就存在了，在切换维度的时候。有了树枝上数据的聚合。实际现象就是上面图上的数据行的转换，和行的数据聚合。
