### ISSUE TITLE
有人碰到过我这种问题吗 echarts切换tab时，第一个图表显示，第二个图表不显示的解决办法

### ISSUE THREAD

**Issue by zilinyo** [apache/incubator-echarts#8197]
### One-line summary [问题简述]

echarts切换tab时，第一个图表显示，第二个图表不显示的解决办法  一定要点击一下第一张表，然后在点击第二张表才会显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]: google
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by komagic** [comment]
你是不是没有clean啊
