### ISSUE TITLE
Echarts 4 + React 无法渲染由dataset方式提供的数据

### ISSUE THREAD

**Issue by Honghe** [apache/incubator-echarts#8198]
### One-line summary [问题简述]
Echarts 4无法渲染由dataset方式提供的数据

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  ^4.0.4
+ Browser version [浏览器类型和版本]: Chrome 66
+ OS Version [操作系统类型和版本]: Ubuntu 16.04
+ 何种方式使用Echarts: 与React模块化加载方式使用

### Expected behaviour [期望结果]
正常渲染由dataset方式提供的数据

### ECharts option [ECharts配置项] 与其它信息
已将渲染有问题的demo代码上传至GitHub https://github.com/Honghe/bug_echarts

**Comment by pissang** [comment]
dataset 组件需要单独引入

**Comment by Honghe** [comment]
Thanks! It works.
