### ISSUE TITLE
请问这种图怎么做？

### ISSUE THREAD

**Issue by Gweixing** [apache/incubator-echarts#8199]
### One-line summary [问题简述]

我需要做出这种图表，我在其他地方有请教别人，但是解决方式并不是我需要的这种效果
这种图表我不懂的地方在如何连接两个数据，让他们首尾相连，即卖单数据的起点是在买单数据后面

![11](https://user-images.githubusercontent.com/29749532/39038427-1122a092-44b6-11e8-82e6-200cbe988d49.png)

下面是我做的，但是它是这样的
![123](https://user-images.githubusercontent.com/29749532/39039186-a4ace83a-44b7-11e8-97a4-0eb940d6d7de.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.x
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by territoryfan** [comment]
@Gweixing  你需要后面的坐标值借上前面的  https://github.com/territoryfan/echarts
