### ISSUE TITLE
Tree图树图：滚动条

### ISSUE THREAD

**Issue by Snowfish1994** [apache/incubator-echarts#8207]
### One-line summary [问题简述]
1、在树图容器过小，而节点多且节点较大时，树图节点重叠的情况很严重，影响美观，例子如截图
2、在节点的高度的一半(height/2)大于Top时，根节点溢出容器，且没有滚动条

### Expected behaviour [期望结果]

可否新增配置项对树图的展现方式进行配置？
比如：
各层间距
各节点间距
溢出显示overflow-x,-y：隐藏、显示、滚动条
![1](https://user-images.githubusercontent.com/16447839/39106470-832a9f70-46ee-11e8-9442-bd5a213a5cb6.png)

**Comment by deqingli** [comment]
会增加 roam 的功能
