### ISSUE TITLE
怎样在x轴显示不是y轴对应的数据

### ISSUE THREAD

**Issue by YEXIAO419** [apache/incubator-echarts#8213]
### One-line summary [问题简述]
x轴显示地区，y轴显示收入
如何在x轴柱形上面显示相应的人数

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请具体描述你的问题
