### ISSUE TITLE
echarts实现实时显示数据

### ISSUE THREAD

**Issue by cynthia2495** [apache/incubator-echarts#8217]
### One-line summary [问题简述]
想要用echats实时的显示动态数据，查到有addData接口，但无法使用，这个接口是不是已经被取消了？如果是，改用什么来实时添加数据呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/38683036/39171648-1ac9fedc-47d2-11e8-8c83-246a6faa779c.png)

**Comment by 9590** [comment]
addData已经取消了，我记得好像现在是用data.push(), https://github.com/apache/incubator-echarts/wiki/ECharts-2-%E5%8D%87%E7%BA%A7%E5%88%B0-ECharts-3-%E7%9A%84%E6%94%B9%E5%8A%A8
