### ISSUE TITLE
lines使用了effect后无法clear

### ISSUE THREAD

**Issue by MaiZheYuan** [apache/incubator-echarts#8226]
### One-line summary [问题简述]
lines使用了effect后无法clear

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.04
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Adelaide1014** [comment]
https://github.com/apache/incubator-echarts/issues/8225
