### ISSUE TITLE
手动调用触发图表下载

### ISSUE THREAD

**Issue by 759325100** [apache/incubator-echarts#8228]
### One-line summary [问题简述]

echarts是否支持通过调用示例方法，触发图表下载，主要是想要把下载图标放到图表外部，通过点击触发下载

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by AntoniaQiao** [comment]
可以的，

this.myChart = echarts.init(document.getElementById('observable-chart' + this.index));   // 实例化
const url = this.myChart.getDataURL({
        pixelRatio: 2,
        backgroundColor: '#fff'
      });

下载 
 downLoadChart(url) {
    const a = document.createElement('a');
    a.setAttribute('href', url);
    a.setAttribute('download', 'export');
    a.style.visibility = 'hidden';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }
