### ISSUE TITLE
Preserve graph options for magictype

### ISSUE THREAD

**Issue by HanchengZhao** [apache/incubator-echarts#8229]
### One-line summary [问题简述]

Echarts doesn't provide an option to configure default rendering for magictype. For example, the default option is the tiled line graph, but we also want to show stacked bar chart on rendering.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: chrome 65.0.3325.181
+ OS Version [操作系统类型和版本]: macOS 10.13.2

### Expected behaviour [期望结果]

Provide default rendering options for magictype/

### ECharts option [ECharts配置项]

```javascript
option = {
  toolbox: {
                feature: {
                  dataZoom: {
                    title: {
                      zoom: 'Zoom',
                      back: 'One step back'
                    },
                    yAxisIndex: 'none'
                  },
                  restore: {
                    title: 'Restore'
                  },
                  magicType: {
                    type: ['line', 'bar', 'stack', 'tiled'],
                    title: {
                      line: 'Line Chart',
                      bar: 'Bar Chart',
                      stack: 'Stack',
                      tiled: 'Tiled'
                    }
                  },
                  dataView: {
                    title: 'DataView',
                    lang: ['DataView', 'Close', 'Refresh']
                  },
                  saveAsImage: {
                    title: 'Save as Image'
                  }
                }
              },
}

```

**Comment by deepakup94** [comment]
Is there any way to preserve magicType so that data can be stacked/unstacked or choose between bar and line. Can we use dispatchAction to select any type?
