### ISSUE TITLE
饼状图中扇形图pc端只有鼠标滑过的事件，如何改成点击？移动端自动变成点击，且保留了高亮状态。

### ISSUE THREAD

**Issue by ChenYCL** [apache/incubator-echarts#8233]
案例是这个
http://echarts.baidu.com/examples/editor.html?c=pie-doughnut

期待：
想要pc端能变成移动端的点击，且保留高亮，不用鼠标滑过触发

**Comment by skyfeiz** [comment]
多研究一下echarts的教程，echarts教程中，有一项 **ECharts 中的事件和行为** ，在下面有一项 **代码触发 ECharts 中组件的行为**。使用 myChart.dispatchAction 方法。
官网案例地址 http://www.echartsjs.com/gallery/editor.html?c=doc-example/pie-highlight

**Comment by ChenYCL** [comment]
好的，发现配合 echat.on('click') 触发dispatchAction可以。
