### ISSUE TITLE
angular5 中如何使echarts自适应父元素宽度的大小

### ISSUE THREAD

**Issue by Yin-Xie** [apache/incubator-echarts#8249]
### One-line summary [问题简述]

<div echarts [options]="chartOption" class="chart"></div>
angular5中这样引用的如何根据父元素自适应宽度！急急急！！！！！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
resize
