### ISSUE TITLE
Edge drawing schemes in graph

### ISSUE THREAD

**Issue by Mockasoehnchen** [apache/incubator-echarts#8253]
### One-line summary [问题简述]
I want to draw edges in a graph after different schemes than just straight (or curved) lines.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4

### Expected behaviour [期望结果]
When drawing links in a graph I would like to be able to use different drawing schemes to straight/curved lines. For example merging links with the same target at the closest possible location or links being drawn as a combination of one horizontal and one vertical line.
I should be able to provide a function in lineStyle that implements such a scheme or at least be able to select between multiple versions.

### Other comments [其他信息]

As far as I understand this behaviour could be emulated by using a lines series. But introducing this new series and therefore splitting the edges from the nodes makes some features of graph, like node adjacency, roam options and force layout, basically non-usable.

**Comment by Ovilia** [comment]
Could you provide some images of these requirements to help others understand?
