### ISSUE TITLE
如何保存整张图片，而不是当前屏幕显示的部分

### ISSUE THREAD

**Issue by ymli1981** [apache/incubator-echarts#8258]
画了一个很大的关系图，在浏览器中可以拖动查看，
但保存图片时，只能保存当前屏幕显示的部分
如何能保存整张图片？

**Comment by surui0419** [comment]
f12打开浏览器后台，再按ctrl+shift+p会出现一个搜索框，在搜索框中输入full,选中"Capture full size screenshot",浏览器会自动帮你下载完整页面的图片
