### ISSUE TITLE
x轴是否支持HTML片段

### ISSUE THREAD

**Issue by lw604217818** [apache/incubator-echarts#8259]
x轴是否支持HTML片段？还是只支持字符串？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以用富文本 http://www.echartsjs.com/gallery/editor.html?c=pie-nest

**Comment by lw604217818** [comment]
这个是知道的，不过目前碰到的情形是富文本也不满足目前需要，要支持HTML
