### ISSUE TITLE
3d地球上的3d飞线尾迹特效在长时间运行后会静止不动，但2d飞线上的尾迹特效却一直在运动

### ISSUE THREAD

**Issue by surui0419** [apache/incubator-echarts#8261]
### One-line summary [问题简述]

使用echartsGL画一个3d地球，在地球上包裹一个2d的世界地图实例，并让地球自转。
给3d地球实例配置setOption时，在series中使用了type为“lines3D”的3d飞线，并且飞线上添加了尾迹动态特效。
在地球上包裹的2d世界地图实例上添加type为“lines”的2d飞线，飞线上也添加尾迹特效。
页面运行一天一夜后，偶尔会出现如下情况：
    3d地球在正常自传，地球上的3d飞线尾迹特效静止，地球上的世界地图的2d飞线的尾迹特效依然在跑动。有没有大神知道这是什么原因造成的？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  ECharts 4.0.4，ECharts GL 1.0.1
+ Browser version [浏览器类型和版本]: chrome 68
+ OS Version [操作系统类型和版本]:  Win10

### Expected behaviour [期望结果]

页面一直挂在那，3d飞线上的尾迹特效能正常运动。

### ECharts option [ECharts配置项]

```javascript

 // 在echarts容器上创建地球实例
      this.globalEchart = echarts.init(this.$refs.global);
      // 在实例上绘制3d地球
      this.globalEchart.setOption({
        globe: {
          left: 0,
          right: '8%',
          top: '4.5%',
          bottom: 0,
          globeRadius: 95,
          baseTexture: this.worldEchart, // 地球的纹理，支持图片或canvas对象或echarts实例作为纹理
          shading: "color", // 不受光照影响
          globeRadius: 97,
          viewControl: {// 用于鼠标的旋转缩放控制
            zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
            rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
            autoRotate: true, // 控制地球是否自转
            autoRotateDirection: "ccw", //控制自转方向
            autoRotateAfterStill: 4,
            targetCoord: [105.9526, 22.3017],
            autoRotateSpeed:10
          }
        },
        series: {
          type: 'lines3D',
          coordinateSystem: 'globe',
          blendMode: 'lighter',
          effect: { // 飞线 特效
            show: true,
            peroid: 2,
            trailColor: 'greenyellow'
          },
          lineStyle: { // 飞线颜色
            width: 2,
            color: '#02fd00',
            opacity: 0.8
          },
          data: this.worldLine
        }
      })

 // 在echarts中注册世界地图的数据
      echarts.registerMap("world", world);
      // 绘制世界地图的实例worldEchart作为纹理
      this.worldEchart = echarts.init(document.createElement("canvas"), null, {
        width: 4000,
        height: 2000
      });
      // 配置worldEchart
      this.worldEchart.setOption({
        geo: {
          // 绘制坐标系上的散点图、线集
          map: "world", // 地图类型
          name: "world_map",
          itemStyle: { // 地图图形样式
            areaColor: "rgba(0,0,0,0.2)",
            borderColor: "rgba(255, 253, 250, 0.6)"
          },
          emphasis: { //高亮时区域内的颜色
            label:{
              show:false,
              color:'#eee'
            },
            itemStyle: {
              areaColor: 'rgba(42,51,61,0)'
            }
          },
          selectedMode: 'single',
          // 绘制完整尺寸的 echarts 实例
          top: '2%',
          left: 0,
          right: 0,
          bottom: 0,
          boundingCoords: [// 定义地图的左上角和右下角经纬度
            [-180, 90],
            [180, -90]
          ]
        },
        series: [
          {
            type: 'lines', //上海到苏里南飞线
            coordinateSystem: "geo",
            zlevel: 4,
            effect: { // 飞线 特效
              show: true,
              period: 4,
              color: "#02fd00",
              symbol: this.lineSymbol,
              symbolSize:13,
              trailLength: 0
            },
            lineStyle: {  //飞线的颜色
              width: 1,  
              color: '#02fd00',
              opacity: {
                cuiveness: 0.2
              }
            },
            data: this.singleLine
          }
        ]
      });
```

**Comment by surui0419** [comment]
![717853389878654425](https://user-images.githubusercontent.com/38311239/39556575-e45253e8-4eb3-11e8-8717-61ce45fbab75.png)
这是效果图

**Comment by surui0419** [comment]
点击世界地图时，将世界地图上的飞线和特效点数据清空，并且地球停止转动，弹出中国地图。
点击中国地图的容器，让中国地图的消失，并且注销中国地图的echarts实例，再给世界地图的飞线和特效点添加数据，让地球恢复转动。反复进行这种操作会导致地球上的3d飞线尾迹特效静止吗？

//点击地球时地球停止转动，中国地图打开
 this.globalEchart.getZr().on('click', ()=>{
        // 地球停止转动并且光照变暗
        this.globalEchart.setOption({
          globe:{   
            viewControl: {// 用于鼠标的旋转缩放控制
              zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
              rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
              autoRotate: false, // 控制地球是否自转
              autoRotateSpeed:0
            }
          }
        })
        this.openChinaMap()
      })

//打开中国地图时绘制中国地图，并将世界地图上的飞线、点数据清空
 openChinaMap () { // 中国地图显示
      this.globalEchart.getZr().off('click')
     //绘制中国地图方法
      this.drawChinaMap()
       // 世界地图边界线变暗
      this.worldEchart.setOption({
        geo:{
          regions: [],
          itemStyle: {borderColor: "rgba(180, 183, 179, 0.01)"}
        }
      })
      // 世界地图的飞线消失
      this.globalEchart.setOption({series: {data: []}})
      // 世界地图上的特效点消失
      this.worldEchart.setOption({series: [
          { data: []},
          { data: []}
      ]})
    },

//点击某容器关闭、销毁中国地图并且让地球边界线恢复亮度、飞仙特效点也都重新加入数据，地球转动
closeChinaMap () { // 中国地图隐藏
      var that = this
      this.isHideChina = true 
      this.isShowChina = false 
      // 世界地图边界线恢复
      this.worldEchart.setOption({
        geo:{ 
          regions: [
            {
               name: 'South Africa\n南非',
               label:{
                  show:true,
                  fontSize:22,
                  color: '#02fd00'
                },
               itemStyle:{
                 areaColor: 'rgba(0,0,0,0.3)'
               }
            },
            {
               name: '上海',
               label:{
                  show:true,
                  fontSize:16,
                  color: '#02fd00'
                },
               itemStyle:{
                 areaColor: 'rgba(0,0,0,0.3)'
               }
             },
              {
               name: 'Lao PDR\n老挝',
               label:{
                  show:true,
                  fontSize:22,
                  color: '#02fd00'
                },
               itemStyle:{
                 areaColor: 'rgba(0,0,0,0.3)'
               }
             },
            {
              name: 'United State\n美国',
              label:{
                show:true,
                fontSize:22,
                color: '#b7c0c9'
              }
            }
          ],
          itemStyle: {borderColor: "rgba(255, 253, 250, 0.8)"}
        }
      })
      if(that.chinaEchart && !that.chinaEchart.isDisposed()) {
        that.chinaEchart.clear()
        that.chinaEchart.dispose()
        echarts.registerMap("china", {})
        // 世界地图的飞线显示
        that.globalEchart.setOption({ series: {data: that.worldLine}})
        // 世界地图上的特效点显示
        that.worldEchart.setOption({series: [
          {data: that.geoCoordMap.slice(0, 21).map((val)=>{
            return {
              name: val.name,
              value:val.value.concat([val.circleValue])
            }
          })},
          {data: that.singleLine}
        ]})
        // setTimeout(()=>{
        that.globalEchart.setOption({
          globe:{
            viewControl: {// 用于鼠标的旋转缩放控制
              zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
              rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
              autoRotate: true, // 控制地球是否自转
              autoRotateDirection: "ccw", //控制自转方向
              targetCoord: [105.9526, 22.3017],
              autoRotateSpeed:10
            }
          }
        })
        // },2000)
      }
      setTimeout(()=>{
        this.globalEchart.getZr().on('click', ()=>{
          // 地球停止转动并且光照变暗
          this.globalEchart.setOption({
            globe:{   
              viewControl: {// 用于鼠标的旋转缩放控制
                zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
                rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
                autoRotate: false, // 控制地球是否自转
                autoRotateSpeed:0
              }
            }
          })
          this.openChinaMap()
        })
      },4000)
    },

**Comment by surui0419** [comment]
点击世界地图时，将世界地图上的飞线和特效点数据清空，并且地球停止转动，弹出中国地图。
点击中国地图的容器，让中国地图的消失，并且注销中国地图的echarts实例，再给世界地图的飞线和特效点添加数据，让地球恢复转动。反复进行这种操作会导致地球上的3d飞线尾迹特效静止吗？

//点击地球时地球停止转动，中国地图打开
this.globalEchart.getZr().on('click', ()=>{
// 地球停止转动并且光照变暗
this.globalEchart.setOption({
globe:{
viewControl: {// 用于鼠标的旋转缩放控制
zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
autoRotate: false, // 控制地球是否自转
autoRotateSpeed:0
}
}
})
this.openChinaMap()
})

//打开中国地图时绘制中国地图，并将世界地图上的飞线、点数据清空
openChinaMap () { // 中国地图显示
this.globalEchart.getZr().off('click')
//绘制中国地图方法
this.drawChinaMap()
// 世界地图边界线变暗
this.worldEchart.setOption({
geo:{
regions: [],
itemStyle: {borderColor: "rgba(180, 183, 179, 0.01)"}
}
})
// 世界地图的飞线消失
this.globalEchart.setOption({series: {data: []}})
// 世界地图上的特效点消失
this.worldEchart.setOption({series: [
{ data: []},
{ data: []}
]})
},

//点击某容器关闭、销毁中国地图并且让地球边界线恢复亮度、飞仙特效点也都重新加入数据，地球转动
closeChinaMap () { // 中国地图隐藏
var that = this
this.isHideChina = true
this.isShowChina = false
// 世界地图边界线恢复
this.worldEchart.setOption({
geo:{
regions: [
{
name: 'South Africa\n南非',
label:{
show:true,
fontSize:22,
color: '#02fd00'
},
itemStyle:{
areaColor: 'rgba(0,0,0,0.3)'
}
},
{
name: '上海',
label:{
show:true,
fontSize:16,
color: '#02fd00'
},
itemStyle:{
areaColor: 'rgba(0,0,0,0.3)'
}
},
{
name: 'Lao PDR\n老挝',
label:{
show:true,
fontSize:22,
color: '#02fd00'
},
itemStyle:{
areaColor: 'rgba(0,0,0,0.3)'
}
},
{
name: 'United State\n美国',
label:{
show:true,
fontSize:22,
color: '#b7c0c9'
}
}
],
itemStyle: {borderColor: "rgba(255, 253, 250, 0.8)"}
}
})
if(that.chinaEchart && !that.chinaEchart.isDisposed()) {
that.chinaEchart.clear()
that.chinaEchart.dispose()
echarts.registerMap("china", {})
// 世界地图的飞线显示
that.globalEchart.setOption({ series: {data: that.worldLine}})
// 世界地图上的特效点显示
that.worldEchart.setOption({series: [
{data: that.geoCoordMap.slice(0, 21).map((val)=>{
return {
name: val.name,
value:val.value.concat([val.circleValue])
}
})},
{data: that.singleLine}
]})
// setTimeout(()=>{
that.globalEchart.setOption({
globe:{
viewControl: {// 用于鼠标的旋转缩放控制
zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
autoRotate: true, // 控制地球是否自转
autoRotateDirection: "ccw", //控制自转方向
targetCoord: [105.9526, 22.3017],
autoRotateSpeed:10
}
}
})
// },2000)
}
setTimeout(()=>{
this.globalEchart.getZr().on('click', ()=>{
// 地球停止转动并且光照变暗
this.globalEchart.setOption({
globe:{
viewControl: {// 用于鼠标的旋转缩放控制
zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
autoRotate: false, // 控制地球是否自转
autoRotateSpeed:0
}
}
})
this.openChinaMap()
})
},4000)
},

**Comment by userLinXiang** [comment]
3D飞线动画特效卡顿这个问题是怎么解决的呀？我也遇到了，求指教

**Comment by userLinXiang** [comment]
> ### One-line summary [问题简述]
> 使用echartsGL画一个3d地球，在地球上包裹一个2d的世界地图实例，并让地球自转。 给3d地球实例配置setOption时，在series中使用了type为“lines3D”的3d飞线，并且飞线上添加了尾迹动态特效。 在地球上包裹的2d世界地图实例上添加type为“lines”的2d飞线，飞线上也添加尾迹特效。 页面运行一天一夜后，偶尔会出现如下情况： 3d地球在正常自传，地球上的3d飞线尾迹特效静止，地球上的世界地图的2d飞线的尾迹特效依然在跑动。有没有大神知道这是什么原因造成的？
> 
> ### Version & Environment [版本及环境]
> * ECharts version [ECharts 版本]:  ECharts 4.0.4，ECharts GL 1.0.1
> * Browser version [浏览器类型和版本]: chrome 65
> * OS Version [操作系统类型和版本]:  Win10
> 
> ### Expected behaviour [期望结果]
> 页面一直挂在那，3d飞线上的尾迹特效能正常运动。
> 
> ### ECharts option [ECharts配置项]
> ```js
>  // 在echarts容器上创建地球实例
>       this.globalEchart = echarts.init(this.$refs.global);
>       // 在实例上绘制3d地球
>       this.globalEchart.setOption({
>         globe: {
>           left: 0,
>           right: '8%',
>           top: '4.5%',
>           bottom: 0,
>           globeRadius: 95,
>           baseTexture: this.worldEchart, // 地球的纹理，支持图片或canvas对象或echarts实例作为纹理
>           shading: "color", // 不受光照影响
>           globeRadius: 97,
>           viewControl: {// 用于鼠标的旋转缩放控制
>             zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
>             rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
>             autoRotate: true, // 控制地球是否自转
>             autoRotateDirection: "ccw", //控制自转方向
>             autoRotateAfterStill: 4,
>             targetCoord: [105.9526, 22.3017],
>             autoRotateSpeed:10
>           }
>         },
>         series: {
>           type: 'lines3D',
>           coordinateSystem: 'globe',
>           blendMode: 'lighter',
>           effect: { // 飞线 特效
>             show: true,
>             peroid: 2,
>             trailColor: 'greenyellow'
>           },
>           lineStyle: { // 飞线颜色
>             width: 2,
>             color: '#02fd00',
>             opacity: 0.8
>           },
>           data: this.worldLine
>         }
>       })
> 
>  // 在echarts中注册世界地图的数据
>       echarts.registerMap("world", world);
>       // 绘制世界地图的实例worldEchart作为纹理
>       this.worldEchart = echarts.init(document.createElement("canvas"), null, {
>         width: 4000,
>         height: 2000
>       });
>       // 配置worldEchart
>       this.worldEchart.setOption({
>         geo: {
>           // 绘制坐标系上的散点图、线集
>           map: "world", // 地图类型
>           name: "world_map",
>           itemStyle: { // 地图图形样式
>             areaColor: "rgba(0,0,0,0.2)",
>             borderColor: "rgba(255, 253, 250, 0.6)"
>           },
>           emphasis: { //高亮时区域内的颜色
>             label:{
>               show:false,
>               color:'#eee'
>             },
>             itemStyle: {
>               areaColor: 'rgba(42,51,61,0)'
>             }
>           },
>           selectedMode: 'single',
>           // 绘制完整尺寸的 echarts 实例
>           top: '2%',
>           left: 0,
>           right: 0,
>           bottom: 0,
>           boundingCoords: [// 定义地图的左上角和右下角经纬度
>             [-180, 90],
>             [180, -90]
>           ]
>         },
>         series: [
>           {
>             type: 'lines', //上海到苏里南飞线
>             coordinateSystem: "geo",
>             zlevel: 4,
>             effect: { // 飞线 特效
>               show: true,
>               period: 4,
>               color: "#02fd00",
>               symbol: this.lineSymbol,
>               symbolSize:13,
>               trailLength: 0
>             },
>             lineStyle: {  //飞线的颜色
>               width: 1,  
>               color: '#02fd00',
>               opacity: {
>                 cuiveness: 0.2
>               }
>             },
>             data: this.singleLine
>           }
>         ]
>       });
> 点击世界地图时，将世界地图上的飞线和特效点数据清空，并且地球停止转动，弹出中国地图。
> 点击中国地图的容器，让中国地图的消失，并且注销中国地图的echarts实例，再给世界地图的飞线和特效点添加数据，让地球恢复转动。反复进行这种操作会导致地球上的3d飞线尾迹特效静止吗？
> 
> //点击地球时地球停止转动，中国地图打开
> this.globalEchart.getZr().on('click', ()=>{
> // 地球停止转动并且光照变暗
> this.globalEchart.setOption({
> globe:{
> viewControl: {// 用于鼠标的旋转缩放控制
> zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
> rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
> autoRotate: false, // 控制地球是否自转
> autoRotateSpeed:0
> }
> }
> })
> this.openChinaMap()
> })
> 
> //打开中国地图时绘制中国地图，并将世界地图上的飞线、点数据清空
> openChinaMap () { // 中国地图显示
> this.globalEchart.getZr().off('click')
> //绘制中国地图方法
> this.drawChinaMap()
> // 世界地图边界线变暗
> this.worldEchart.setOption({
> geo:{
> regions: [],
> itemStyle: {borderColor: "rgba(180, 183, 179, 0.01)"}
> }
> })
> // 世界地图的飞线消失
> this.globalEchart.setOption({series: {data: []}})
> // 世界地图上的特效点消失
> this.worldEchart.setOption({series: [
> { data: []},
> { data: []}
> ]})
> },
> 
> //点击某容器关闭、销毁中国地图并且让地球边界线恢复亮度、飞仙特效点也都重新加入数据，地球转动
> closeChinaMap () { // 中国地图隐藏
> var that = this
> this.isHideChina = true
> this.isShowChina = false
> // 世界地图边界线恢复
> this.worldEchart.setOption({
> geo:{
> regions: [
> {
> name: 'South Africa\n南非',
> label:{
> show:true,
> fontSize:22,
> color: '#02fd00'
> },
> itemStyle:{
> areaColor: 'rgba(0,0,0,0.3)'
> }
> },
> {
> name: '上海',
> label:{
> show:true,
> fontSize:16,
> color: '#02fd00'
> },
> itemStyle:{
> areaColor: 'rgba(0,0,0,0.3)'
> }
> },
> {
> name: 'Lao PDR\n老挝',
> label:{
> show:true,
> fontSize:22,
> color: '#02fd00'
> },
> itemStyle:{
> areaColor: 'rgba(0,0,0,0.3)'
> }
> },
> {
> name: 'United State\n美国',
> label:{
> show:true,
> fontSize:22,
> color: '#b7c0c9'
> }
> }
> ],
> itemStyle: {borderColor: "rgba(255, 253, 250, 0.8)"}
> }
> })
> if(that.chinaEchart && !that.chinaEchart.isDisposed()) {
> that.chinaEchart.clear()
> that.chinaEchart.dispose()
> echarts.registerMap("china", {})
> // 世界地图的飞线显示
> that.globalEchart.setOption({ series: {data: that.worldLine}})
> // 世界地图上的特效点显示
> that.worldEchart.setOption({series: [
> {data: that.geoCoordMap.slice(0, 21).map((val)=>{
> return {
> name: val.name,
> value:val.value.concat([val.circleValue])
> }
> })},
> {data: that.singleLine}
> ]})
> // setTimeout(()=>{
> that.globalEchart.setOption({
> globe:{
> viewControl: {// 用于鼠标的旋转缩放控制
> zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
> rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
> autoRotate: true, // 控制地球是否自转
> autoRotateDirection: "ccw", //控制自转方向
> targetCoord: [105.9526, 22.3017],
> autoRotateSpeed:10
> }
> }
> })
> // },2000)
> }
> setTimeout(()=>{
> this.globalEchart.getZr().on('click', ()=>{
> // 地球停止转动并且光照变暗
> this.globalEchart.setOption({
> globe:{
> viewControl: {// 用于鼠标的旋转缩放控制
> zoomSensitivity: 0, // 缩放灵敏度 0关闭缩放
> rotateSensitivity: [2,0], //控制横、纵旋转灵敏度
> autoRotate: false, // 控制地球是否自转
> autoRotateSpeed:0
> }
> }
> })
> this.openChinaMap()
> })
> },4000)
> },
> ```
> 
> ### Other comments [其他信息]

3D飞线动画特效卡顿这个问题是怎么解决的呀？我也遇到了，求指教
