### ISSUE TITLE
区域填充颜色如何使用系列颜色呢

### ISSUE THREAD

**Issue by hanfengcan** [apache/incubator-echarts#8262]
### One-line summary [问题简述]
在使用区域填充的时候,需要在 colorStops指定颜色

```js
  colorStops: [{offset: 0, color: 'rgba(128, 128, 128, 0.5)'}]
```

如果想实现这种效果,需要知道系列的颜色

![_20180502171626](https://user-images.githubusercontent.com/4559753/39515567-16fa1524-4e2d-11e8-9b6e-85fb9ba96f85.png)

有什么合适的方法实现呢.

现在是使用`getModel().getSeriesByIndex(0).getData().getVisual('color')`来获取系列颜色.在把hex改成rgba的格式

**Comment by territoryfan** [comment]
@hanfengcan  https://github.com/territoryfan/echarts

**Comment by hanfengcan** [comment]
@territoryfan LinearGradient函数文档没有详细说明吧
