### ISSUE TITLE
Add size support for bar chart like scatter. 

### ISSUE THREAD

**Issue by amittonge** [apache/incubator-echarts#8265]
### One-line summary [问题简述]

It would be better if we have callback function for barWidth so that we can configure different bar width for individual item on the basic of some other dimension like scatter plot.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hanfengcan** [comment]
That sounds strange that Bar charts with different widths 😅

**Comment by ChandradipJ** [comment]
@hanfengcan, This is a real use case. You can check top BI tools like Tableau which have this functionality. With this functionality, you can compare different dimensions in a single chart.

**Comment by vasu-vvp** [comment]
@hanfengcan there is nothing strange with bar having different widths. 
It would be better if echarts also add this support.

**Comment by hanfengcan** [comment]
@ChandradipJ Is this http://echarts.baidu.com/examples/editor.html?c=custom-profit

**Comment by ChandradipJ** [comment]
@hanfengcan, no I want output as ![image]((https://user-images.githubusercontent.com/34739185/39568686-97eec8ce-4ee0-11e8-9dbe-124ec355ed16.png))
