### ISSUE TITLE
咨询关于dataset的数据转换方案

### ISSUE THREAD

**Issue by netwild** [apache/incubator-echarts#8268]
### One-line summary [问题简述]
这是个集成echarts的问题，非Bug，打扰了！

现有系统中返回的业务数据绝大多数都是动态的，典型格式如下：
[
    { 'month': '1月', 'dept': '生产部', 'value': 47 },
    { 'month': '1月', 'dept': '销售部', 'value': 39},
    { 'month': '1月', 'dept': 'XXX部', 'value': i...},
    //...
    { 'month': '2月', 'dept': '生产部', 'value': 36 },
    { 'month': '2月', 'dept': '销售部', 'value': 53},
    { 'month': '2月', 'dept': 'XXX部', 'value': i...},
    //...
    { 'month': '3月', 'dept': '生产部', 'value': 52},
    { 'month': '3月', 'dept': '销售部', 'value': 61},
    { 'month': '3月', 'dept': 'XXX部', 'value': i...},
    //...
]

将其转换为Charts的数据格式之后：
dimensions: ['month', '生产部', '销售部', 'XXX部', ... ],
source: [
    {'month': '1月', '生产部': 47, '销售部': 39, 'XXX部': i, ...},
    {'month': '2月', '生产部': 36, '销售部': 53, 'XXX部': i, ...},
    {'month': '3月', '生产部': 52, '销售部': 61, 'XXX部': i, ...}
]

之后可以正常显示图形，这里都OK

问题是，对于这些动态数据，类似上面的序列（dept）往往是不可预期的
那在面向用户的表单中创建Options时，有什么办法才能对series中的每个序列进行自定义设置
包括序列的个数，以及每个序列的type、itemStyle等

我看到在echarts 4.0中提供了dataset相关API和视觉映射（visualMap）等各种组件
功能都很强大，但对于我这种情况，不太确定哪种更适合
只想得到一个最灵活的解决思路，感谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Win10

**Comment by hanfengcan** [comment]
是不是可以转换成
'''[month, xx部，xx部，，，，]
[1月，32，43，，，，，]'''

然后指定维度
