### ISSUE TITLE
关系图normal状态下label.rotate字段配置无响应

### ISSUE THREAD

**Issue by liuswin** [apache/incubator-echarts#8269]
### One-line summary [问题简述]
Les Miserables Demo: layout: 'none'，设置label.normal.rotate字段无效。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  官方Demo
+ Browser version [浏览器类型和版本]:  Chrome version: 66.0.3359.139
+ OS Version [操作系统类型和版本]: MacOS 10.13.4

### ECharts option [ECharts配置项]

```javascript
myChart.showLoading();
$.get('data/asset/data/les-miserables.gexf', function (xml) {
    myChart.hideLoading();

    var graph = echarts.dataTool.gexf.parse(xml);
    var categories = [];
    for (var i = 0; i < 9; i++) {
        categories[i] = {
            name: '类目' + i
        };
    }
    graph.nodes.forEach(function (node) {
        node.itemStyle = null;
        node.value = node.symbolSize;
        node.symbolSize /= 1.5;
        node.label = {
            normal: {
                show: node.symbolSize > 10
            }
        };
        node.category = node.attributes.modularity_class;
    });
    option = {
        title: {
            text: 'Les Miserables',
            subtext: 'Circular layout',
            top: 'bottom',
            left: 'right'
        },
        tooltip: {},
        legend: [{
            // selectedMode: 'single',
            data: categories.map(function (a) {
                return a.name;
            })
        }],
        animationDurationUpdate: 1500,
        animationEasingUpdate: 'quinticInOut',
        series : [
            {
                name: 'Les Miserables',
                type: 'graph',
                layout: 'none',
                circular: {
                    rotateLabel: true
                },
                data: graph.nodes,
                links: graph.links,
                categories: categories,
                roam: true,
                label: {
                    normal: {
                        position: 'right',
                        formatter: '{b}',
                        rotate: 45
                    },
                    emphasis: {
                        rotate: 45
                    }
                },
                lineStyle: {
                    normal: {
                        color: 'source',
                        curveness: 0.3
                    }
                }
            }
        ]
    };

    myChart.setOption(option);
}, 'xml');

```

**Comment by tangj1206** [comment]
您好 此问题解决了吗？

**Comment by liuswin** [comment]
我这边是在echarts源码中graph这一块添加了自定义的字段cusLabelRotate，然后自己处理旋转角度。改完后自己把源码压缩一下使用就可以了。

**Comment by tangj1206** [comment]
非常感谢您的分享！

**Comment by DopeMax** [comment]
@liuswin 能告诉下是如何添加的吗，方便的话，帮忙贴个代码片段出来，万分感谢。

**Comment by liuswin** [comment]
> @liuswin 能告诉下是如何添加的吗，方便的话，帮忙贴个代码片段出来，万分感谢。

data.eachItemGraphicEl(function (el, idx) {
  ...
  if (seriesModel.get('data')[idx].label.cusLabelRoate === true) {
    var pos = data.getItemLayout(idx);
    var rad = Math.atan2(pos[1] - cy, pos[0] - cx);
    if (rad < 0) {
        rad = Math.PI * 2 + rad;
    }
    var isLeft = pos[0] < cx;
    if (isLeft) {
        rad = rad - Math.PI;
    }
    var textPosition = isLeft ? 'left' : 'right';
    symbolPath.setStyle({
        textRotation: -rad,
        textPosition: textPosition,
        textOrigin: 'center'
    });
    symbolPath.hoverStyle && (symbolPath.hoverStyle.textPosition = textPosition);
  }
}

**Comment by DopeMax** [comment]
> > @liuswin 能告诉下是如何添加的吗，方便的话，帮忙贴个代码片段出来，万分感谢。
> 
> data.eachItemGraphicEl(function (el, idx) {
> ...
> if (seriesModel.get('data')[idx].label.cusLabelRoate === true) {
> var pos = data.getItemLayout(idx);
> var rad = Math.atan2(pos[1] - cy, pos[0] - cx);
> if (rad < 0) {
> rad = Math.PI * 2 + rad;
> }
> var isLeft = pos[0] < cx;
> if (isLeft) {
> rad = rad - Math.PI;
> }
> var textPosition = isLeft ? 'left' : 'right';
> symbolPath.setStyle({
> textRotation: -rad,
> textPosition: textPosition,
> textOrigin: 'center'
> });
> symbolPath.hoverStyle && (symbolPath.hoverStyle.textPosition = textPosition);
> }
> }

 @liuswin 非常感谢
