### ISSUE TITLE
需要最新地图数据：地图下钻--全国/省/市-地图下钻--市县地图是旧的

### ISSUE THREAD

**Issue by Snatch-jie** [apache/incubator-echarts#8270]
因为现在echarts官网下载不了地图数据额了。
从网上找了很多js/json或者主要城市(县) geojson数据。
但是无一例外都是旧的。

### One-line summary [问题简述]
 比如我找到的深圳（只有宝安,龙岗,福田,罗湖,南山,盐田）。没有龙华 大鹏新区 光明等
求各位老大哪位有最新的市区地图数据。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
ECharts 版本：3.8.5
浏览器：谷歌
windows操作系统
### Expected behaviour [期望结果]
期望echarts 官网或者哪位老大能提供下最新的市区数据

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hele10086** [comment]
没有的话可以自己自定义，地址：http://geojson.io/
先导入旧的再修改会快一点。

**Comment by Snatch-jie** [comment]
@hele10086    @万分感谢提供方法(虽然还不会用)。感谢~~~~

**Comment by pissang** [comment]
我们短期内不再提供地图数据

**Comment by chfw** [comment]
用 https://github.com/echarts-maps/echarts-mapmaker 和 geojson.io 是可以自己做的。

欢迎来参加：https://github.com/echarts-maps

**Comment by Snatch-jie** [comment]
@chfw  好的  万分感谢。
geojson.io  自己会用了
