### ISSUE TITLE
gallery无法使用百度账号登录

### ISSUE THREAD

**Issue by songjinghe** [apache/incubator-echarts#8271]
### One-line summary [问题简述]
如题，在http://gallery.echartsjs.com 下任意页面点击登录按钮，跳转到https://openapi.baidu.com/oauth/2.0/authorize?client_id=bMQacMs0X70eP0o2UNOyXCOY&response_type=code&redirect_uri=http%3A%2F%2Fgallery.echartsjs.com%2Flogin%3FecOrigin%3Dhttp%253A%252F%252Fgallery.echartsjs.com%252Fexplore.html%2523sort%253Drank~timeframe%253Dall~author%253Dall
输入用户名密码后就会跳转到http://static.tieba.baidu.com/tb/error.html?tc=21528875740823640586050311

重试多次（删掉*.baidu.com下的所有cookie）也不行。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version: Google Chrome Version 65.0.3325.162
+ OS Version [操作系统类型和版本]: win10专业版

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/3754416/39559265-711071f8-4ec7-11e8-9abc-4ed07e4b1519.png)

**Comment by hanfengcan** [comment]
我是无法保存例子

**Comment by songjinghe** [comment]
@hanfengcan 你退出后可以正常登录吗？

**Comment by hanfengcan** [comment]
一直不能保存!@songjinghe

**Comment by songjinghe** [comment]
@hanfengcan 我现在可以登录了，你那边应该也好了吧
