### ISSUE TITLE
 canvas: an attempt to set strokeStyle or fillStyle to a value that is neither a string, a CanvasGradient, or a CanvasPattern was ignored. 

### ISSUE THREAD

**Issue by fengxufang** [apache/incubator-echarts#8273]
### One-line summary [问题简述]
[22:59:31.765] canvas: an attempt to set strokeStyle or fillStyle to a value that is neither a string, a CanvasGradient, or a CanvasPattern was ignored. @ http://localhost:8083/DB_Service/Oracle/timemap.html

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.0
+ Browser version [浏览器类型和版本]:火狐，10.0.5版本
+ OS Version [操作系统类型和版本]:Linux version 2.6.32-279.el6.x86_64 (mockbuild@x86-008.build.bos.redhat.com) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Wed Jun 13 18:24:36 EDT 2012

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
What's your detailed option?
