### ISSUE TITLE
xAxis.type='time' + zoomData时卡顿问题

### ISSUE THREAD

**Issue by LonHon** [apache/incubator-echarts#8277]
### One-line summary [问题简述]
@pissang 
使用折线图   series.length为2

已设置animation: false

xAxis.type='time' + zoomData时，目前1000条数据，当全部展示时卡顿比较严重，较小范围展示内存占用增加了100M。

同样的数据 xAxis.type='category'  时十分流畅。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: Chrome 65.0.3325.162
+ OS Version [操作系统类型和版本]:
小米pro 16G win10

### Expected behaviour [期望结果]

卡顿效果能够优化

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能否发我们下完整的能够复现的 option

**Comment by LonHon** [comment]
抱歉，option是动态修改的，数据2000条左右，主要配置：
1. 折线图
2. 两个Y轴
3. X轴设置了formatter

其余的为默认设置。

---

感觉zoomData拖动时卡顿问题出在 x轴文本的格式化上

刚刚试了下，如果没有使用axisLabel则拖动流畅，添加格式化方法后会明显卡顿

然后xAxis.type='time' 时，从效果上看也是动态调整了axisLabel。

**Comment by LonHon** [comment]
@pissang  虽然个人已经解决卡顿问题，还是放上option供你们去寻找原因。

官方demo： http://echarts.baidu.com/examples/editor.html?c=dynamic-data2

电脑配置是小米pro顶配，在数据量4000时会明显卡顿，应该是渲染 series ** showSymbol, hoverAnimation ** 存在问题

代码
```
function randomData() {
    now = new Date(+now + oneDay);
    value = value + Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
            Math.round(value)
        ]
    }
}

var data = [], data1 = [], timeline = [];
var now = +new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var value = Math.random() * 1000;
for (var i = 0; i < 4000; i++) {
    data.push(randomData());
}

option = {
    title: {
        text: '动态数据 + 时间坐标轴'
    },
    tooltip: {
        trigger: 'axis'
    },
    xAxis: {
        type: 'time'
    },
    yAxis: [{
        type: 'value',
        boundaryGap: [0, '100%']
    },{
        type: 'value',
        boundaryGap: [0, '100%']
    }],
    series: [{
        name: '模拟数据',
        type: 'line',
        data: data
    }],
};
```
