### ISSUE TITLE
graph symbol 图片取不到的时候 怎么使用默认图片代替

### ISSUE THREAD

**Issue by xccxcs** [apache/incubator-echarts#8279]
### One-line summary [问题简述]

graph symbol 图片地址失效了 取不到照片 怎么使用默认图片代替

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by komagic** [comment]
解耦吧,  所有数据应该在 外面设置好了再传进option吧.    let image=无图片.png || 无图片2.png || 默认图片.png 呗

**Comment by xccxcs** [comment]
但是这样不应该先把图片全部请求好才能进行下去吗

**Comment by komagic** [comment]
你也可以有个默认option先setoption，然后异步请求完成后再根据得到的data 进行setOption刷新内容
