### ISSUE TITLE
Echars Galery中的项目怎么下载

### ISSUE THREAD

**Issue by wulifangfang** [apache/incubator-echarts#8280]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![qq 20180504101426](https://user-images.githubusercontent.com/38749500/39610575-f8bf6f52-4f83-11e8-8a11-455dcce80457.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以按照入门教程建好项目后把 option 下下来替换
