### ISSUE TITLE
4.1.0 渲染方式改成svg，结果绘制的时候还是canvas

### ISSUE THREAD

**Issue by ashen9** [apache/incubator-echarts#8281]
### One-line summary [问题简述]

4.1.0 渲染方式改成svg，结果绘制的时候还是canvas

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: chrome v65.0.3325.181
+ OS Version [操作系统类型和版本]: windows10

### Expected behaviour [期望结果]

渲染方式svg

### Other comments [其他信息]

我看代码里init方法参数的注释是这样的@param {string} [opts.renderer] Currently only 'canvas' is supported.
是否代表不支持svg模式？

**Comment by pissang** [comment]
引入 svg 模块了么？

**Comment by ashen9** [comment]
引入了  import 'zrender/lib/svg/svg';

**Comment by PandaTsui** [comment]
mee too
