### ISSUE TITLE
X轴空值匹配存在问题

### ISSUE THREAD

**Issue by Ericdmb** [apache/incubator-echarts#8283]
### One-line summary [问题简述]
在series的type为line或bar的类型（其他类型未知）时，对x轴进行赋值，当x轴存在null值时，series中的data无法与x轴数据进行正确的映射。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echarts4.0
+ Browser version [浏览器类型和版本]:Chrome66.0.3359.139
+ OS Version [操作系统类型和版本]:Win10

### Expected behaviour [期望结果]
series中[null,5]能够映射到‘’null‘’上，或者x轴的null不会被转换成‘null’并能与数据正确映射。
即线有单调性。

### ECharts option [ECharts配置项]

```javascript
option ={
    legend: {},
    tooltip: {},
    xAxis: {
        type: 'category',
        data:['A','B','C','D',null]
    },
    yAxis: {},
    series: [
        {
            type:'line',
            data:[['A',1],['B',2],['C',3],['D',4],[null,5]],
            encode:{
                x:0,
                y:1
            }
        },
    ]
};

```

### Other comments [其他信息]

http://gallery.echartsjs.com/editor.html?c=xrJD2aPYTz&comment=0
这上面的案例是我建的，与提交的option差别在seies的数据我把C，D的顺序调换了一下

**Comment by cookie314** [comment]
+1 3.8.5版本也有同样的问题
