### ISSUE TITLE
Google charts: timelines [question]

### ISSUE THREAD

**Issue by giorgiopagnoni** [apache/incubator-echarts#8288]
Can we create something like [Google charts timelines](https://developers.google.com/chart/interactive/docs/gallery/timeline) with Echarts?

<img width="738" alt="screen shot 2018-05-04 at 15 26 10" src="https://user-images.githubusercontent.com/7541741/39630411-85907432-4faf-11e8-9d08-6d9933af3909.png">

**Comment by pissang** [comment]
You can use `custom` series to implement this. Like what this example do.  https://ecomfe.github.io/echarts-examples/public/editor.html?c=custom-profile

**Comment by giorgiopagnoni** [comment]
Thank you, I don't know how I missed that. But I think there's something wrong with the legend in that example, am I right?

**Comment by pchaganti** [comment]
👍

**Comment by 100pah** [comment]
@giorgiopagnoni ye, I will fix the example.

**Comment by giorgiopagnoni** [comment]
@100pah thank you; drop me a line when the legend works
