### ISSUE TITLE
如何绑定ecxel中的数据

### ISSUE THREAD

**Issue by shenqi139** [apache/incubator-echarts#8289]
实际现在很多的数据都是放在excel中  或者csv格式的,但是现在官方貌似没有这方面的教程,并且百度也很多人问的, 我觉得一定可以实现,只是我不知道,所以希望有人看到能教一下子,我也觉得有更多的人都有这方面的疑问,谢谢

**Comment by chfw** [comment]
你可以参照这个 https://github.com/pyecharts/pyecharts/issues/524

现在还是在起步阶段
