### ISSUE TITLE
如何绘制自定义对象

### ISSUE THREAD

**Issue by peach5460** [apache/incubator-echarts#8290]
目前我使用Echart主要是散点图和折线图
在散点图里面，我希望能添加自定义的基本对象：
比如说我希望能绘制矩形或者手绘多边形用于框出某些点集做示例；
或者我希望在图中增加一些自定义的文字及箭头做简单的展示说明。
在折线图里我希望添加一些箭头做展示。

但是，目前我在API文档中没有找到相关的接口。
而且，我希望我添加的基本对象能和坐标绑定。
因为我曾经考虑过自己使用canvas的draw来绘制我自己的特定基本对象。但是因为我的draw是基于像素的，所以在页面进行了缩放，大小改变后，我很不方便进行重算。
因为我自己不方便算DP到LP的转换，所以我的基本对象位置经常跑偏。

请问：
1，是否有原生的接口可以用于自定义基本对象的绘制
2，有没有方法可以方便我进行一些基本对象的锚定

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E5%88%97
