### ISSUE TITLE
geo.regions[i].itemStyle.areaColor的文档描述错误

### ISSUE THREAD

**Issue by luguokong** [apache/incubator-echarts#8292]
### One-line summary [问题简述]

配置手册中geo.regions[i].itemStyle.areaColor的文档有问题
geo.regions[i].itemStyle.areaColor.color设置颜色值不会生效
geo.regions[i].itemStyle.areaColor设置颜色值才会生效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://gallery.echartsjs.com/editor.html?c=xrkrKqlj6M&v=3

**Comment by pissang** [comment]
谢谢反馈，这里层级出现了点问题

**Comment by webCoderJ** [comment]
没更新到文档呢？踩了好多坑...
