### ISSUE TITLE
getDataURL的api获取的base64中，没有包含柱状的图形

### ISSUE THREAD

**Issue by antstudio-git** [apache/incubator-echarts#8293]
### One-line summary [问题简述]
Bar类型的图表，调用getDataURL方法后，只有坐标系和数字，但是没有柱状显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: mac OS

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
去掉 animation 试试
