### ISSUE TITLE
4.1.0版本中使用SVG渲染bar、line的series label存在异常（报错、字体大小异常）

### ISSUE THREAD

**Issue by Lestry** [apache/incubator-echarts#8295]
### One-line summary [问题简述]
在使用SVG渲染时：
1、series（type：'bar'）中配置了显示label（show：true）的情况报错
2、series（type：'line'）中配置的label字体大小异常（截图中为fontSize：12的情况）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:Chrome 66.0.3359.139 x64
+ OS Version [操作系统类型和版本]:Window 10 x64

### Expected behaviour [期望结果]
1、正常渲染图表
2、字体大小符合配置

### ECharts option [ECharts配置项]

```javascript
option = {
 xAxis: [
        {
          type: 'category',
          data: ['本月', '上月'],
        }
    ],
    yAxis: [
        {
          type: 'value'
        }
    ],
    series: [
        {
            name: '数量',
            type: 'bar',
            silent: true,
            label: {
                show: true,
                position: 'top',
                rotate: 0
            },
            data: [38, 42],
        }
    ]
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/17736150/39689967-1916f2be-520b-11e8-93e9-20d9986654de.png)
![image](https://user-images.githubusercontent.com/17736150/39690291-29137b3c-520c-11e8-84dd-1f97e046fec0.png)

**Comment by Lestry** [comment]
@pissang

**Comment by Ovilia** [comment]
https://github.com/ecomfe/zrender/commit/0cc622196d8665f40d02b6156450cc7a87fe3a67 已修复
