### ISSUE TITLE
parallel图渲染问题

### ISSUE THREAD

**Issue by lvybriage** [apache/incubator-echarts#8304]
### One-line summary [问题简述]
parallel图中，最简单的平行图里，如果设置 smooth: true的话，渲染的时候，会出现先后渲染，最后才会渲染轴线顶部的线条。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  "echarts": "^4.0.2", "echarts-for-react": "^2.0.8",
+ Browser version [浏览器类型和版本]: 谷歌浏览器
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

同步渲染，而不是有先后。

### ECharts option [ECharts配置项]

```javascript
option = {
    parallelAxis: [
        {dim: 0, name: 'Price'},
        {dim: 1, max: 1028,name: 'eight'},
        {dim: 2, name: 'Amount'},
        {
            dim: 3,
            name: 'Score',
            type: 'category',
            data: ['Excellent', 'Good', 'OK', 'Bad']
        }
    ],
    series: {
        type: 'parallel',
        smooth: true,
        lineStyle: {
            width: 4
        },
        data: [
            [12.99, 100, 82, 'Good'],
            [9.99, 80, 77, 'OK'],
            [20, 1024, 60, 'Excellent']
        ]
    }
};

```

### Other comments [其他信息]

刚开始渲染的时候，20 1028这段并没有渲染，而是在整个图完成之后最后渲染的。

![image](https://user-images.githubusercontent.com/35484733/39741100-ffb1dd46-52ca-11e8-93ef-105694e6c02d.png)

option中去掉 smooth： true 这个属性就没这个问题了。

![image](https://user-images.githubusercontent.com/35484733/39741109-08dafdd0-52cb-11e8-8071-c37348b9278d.png)

但是因为需求，我们需要平滑的曲线。

求大神支招。

**Comment by lvybriage** [comment]
I know, 在选择绘制平滑曲线之后，echarts绘制原理是先找到两个点，然后在点之间连接平滑曲线，所以就出现了我说的 渲染延迟的问题。

**Comment by seriousAA** [comment]
了解了，感谢分享
