### ISSUE TITLE
How to react on clicks inside of marked Areas

### ISSUE THREAD

**Issue by eskimoblood** [apache/incubator-echarts#8307]
### One-line summary [问题简述]
I want to add some interactions when the user clicks inside of a marked Area, is there an event triggered that I can listen on?

**Comment by pissang** [comment]
You can set `markArea.silent` true to enable mouse interaction

**Comment by eskimoblood** [comment]
But how to catch them

**Comment by pissang** [comment]
```js
chart.on('click', e => {
    if (e.componentType === 'markArea) {
        .......
    }
});
```

**Comment by eskimoblood** [comment]
got it, thanks
