### ISSUE TITLE
柱状图加折线图双y轴情况下发现若干问题

### ISSUE THREAD

**Issue by zhg-645479206** [apache/incubator-echarts#8309]
我的场景是股市图 ,柱状图加折线图(双y轴情况)，双y轴的起点都不是从0开始时:
注：左侧轴是折线图的，右侧轴是柱状图的；事关保密协议不方便贴图上来 ;

------------------------------------------------------------------------------
+ ECharts version:    4.0.4
+ Browser version :  谷歌浏览器
+ OS Version:           windos 10 操作系统
------------------------------------------------------------------------------

问题详细描述: 
1.  点击关闭 折线图legend 后图表变动，柱状图的起点从canvas画布的最下方开始绘制,并不是从x轴开始
  绘制，此时grid的bottom值等都等于无效。
2. 点击关闭 图例legend, 图表对应的图形消失，但是相匹配的y轴和splitLine并没有消失.
3. 针对问题2我使用legend的legendSelectChange偏方处理，但是又发现y轴的show属性设置为false后,
  y轴隐藏，而y轴的name值并没有消失，还是显示在原位置上。（不得已我又设置y轴的name属性为空字符串)

注: 以上三个问题的出现条件为双y轴的起点都大于0；

### Expected behaviour [新发现问题]
1.  左侧折线轴起点从0开始，右侧柱状图起点大于0, 柱状图绘制错误，起点从canvas底部开始，应该是从
x轴开始绘制.
2.  双Y轴起点都不从0开始时,最底部原始的x轴变为很淡的状态(比其它的splitLine颜色浅),并且和紧挨的上一条splitLine有固定的间隔像素(固定的间隔是从哪里来的?), 期望原始的x轴这种情况下自动隐藏或者和紧挨的上一条splitLine线重合，不出现很淡的一条放在原位置上。

### Expected behaviour [期望结果]
相关问题被解决.

**Comment by qinshenghechu** [comment]
同样遇到这个问题、不知最新版是否已经修复该问题、求解答
