### ISSUE TITLE
Feature: tree 增加直角线条功能

### ISSUE THREAD

**Issue by gaoshijun1993** [apache/incubator-echarts#8313]
树形图会经常用于组织机构的展现,对于组织机构的展现一般用直角的线条会比较合适,但是目前tree 的节点线条都是平滑的,所以希望能够增加直角的线条展现配置功能

**Comment by gaoshijun1993** [comment]
@elliot-cj 没有...

**Comment by pchaganti** [comment]
👍

**Comment by edgarhong** [comment]
同求

**Comment by keke195** [comment]
+1

**Comment by tingwu55** [comment]
+1

**Comment by Moderation-T** [comment]
同求

**Comment by lising1984** [comment]
同求

**Comment by lising1984** [comment]
同求

**Comment by lurenj** [comment]
同求

**Comment by masterlirui** [comment]
是的 我也遇到这个问题，期望线条样式可以有直线转角，而不只是曲线设置曲度。翻了很多资料 貌似echarts2.0可以实现，高版本的都不行。另外就是不同层级的节点之间的间距设置也没有相关介绍。

**Comment by xukui529** [comment]
只有2.x版本是直角

**Comment by deqingli** [comment]
I have completed the polyline edge style which will be released in version 4.7.0. So I will close this issue if you still have any problem feel free to reopen this issue.

**Comment by liuz666** [comment]
> 我已经完成了折线边缘样式，该样式将在4.7.0版中发布。因此，如果您仍然有任何问题可以随时重新打开此问题，我将关闭此问题。

你好，我在4.7版本里面的文档并没有看到这个配置项啊？
