### ISSUE TITLE
multiple tree共用一个root？

### ISSUE THREAD

**Issue by baoqger** [apache/incubator-echarts#8318]
现在只支持left to right, 或者right-to-left的tree形图，如果left和right都需要的话，如何处理呢？想用multiple tree来模拟，但是又不能共用一个root，无法实现。

**Comment by deqingli** [comment]
left 和 right 都要，请问是什么样的可视化图形

**Comment by deqingli** [comment]
@baoqger  Since you haven't reply for a long time, so I will close this issue. If you still have any problem in the future you can reopen it.
