### ISSUE TITLE
Suggestions for clearing and redrawing a chart?

### ISSUE THREAD

**Issue by pchaganti** [apache/incubator-echarts#8331]
### One-line summary [问题简述]
Unable to reset a chart with newly retrieved dynamic data. Tried setOption(true). Still leaves the old data in there. Anyone have any suggestions or pointers to how to accomplish this?

thanks

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
Could I have your `option` to reproduce the issue.

**Comment by pchaganti** [comment]
Here is a fiddle - https://jsfiddle.net/pchaganti/L7d18gpr/

Clicking on the icon top right in the toolbox area calls redrawChart() with a new option. 

thanks for your help!

**Comment by pchaganti** [comment]
While making that fiddle, found the issue. It was a typo.

thanks!
