### ISSUE TITLE
API 文档是不是描述错了

### ISSUE THREAD

**Issue by since91** [apache/incubator-echarts#8333]
http://echarts.baidu.com/option.html#series-lines 中写的是
在 ECharts 3 里建议使用单独的 lines 类型图表。
而当前版本是echarts4 是不是写错了？
挺多地方都写了Echarts 3

http://echarts.baidu.com/option.html#series-map

**Comment by pissang** [comment]
这些都可以理解为从 echarts3 开始建议....
