### ISSUE TITLE
一个很低级的BUG 折线图  单个name 文本的样式设置不了

### ISSUE THREAD

**Issue by wunayou** [apache/incubator-echarts#8339]
### One-line summary [问题简述]
第一步打开官网的DEMO 
http://echarts.baidu.com/examples/editor.html?c=line-simple

第二步 改数据
```option = {
    xAxis: {
        type: 'category',
        data: [{value:'123',textStyle:{color:'red'}
// 这个颜色不能改#111111 这种数字类型
}, 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};
```
把DATA的数据 改成对象 然后运行 ，字体变成红色了

但是 我如果改成 把red 变成“#212121” 就没有效果了？
```option = {
    xAxis: {
        type: 'category',
        data: [{value:'123',textStyle:{color:'#212121'}}, 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

版本用的 4.0
浏览器chrome

### Expected behaviour [期望结果]

期望可以改成 非英文的 颜色

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        data: [{value:'123',textStyle:{color:'#212121'}}, 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};

```

**Comment by wunayou** [comment]
没有找到 这个文件的位置 所以不能提PR了

**Comment by komagic** [comment]
option = {
     xAxis: {
        type: 'category',
        data: [{value:'123',textStyle:{color:'#669966'}

}, 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};
没问题啊 - -0
