### ISSUE TITLE
echarts是否规划支持 arearange 图

### ISSUE THREAD

**Issue by yeegaka** [apache/incubator-echarts#8340]
### One-line summary [问题简述]
echarts是否支持 arearange 图

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
能够提供类似于highcharts arearange 图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![arearange](https://user-images.githubusercontent.com/697279/40041757-b16c6624-5851-11e8-8f20-d3d19cb51157.png)

**Comment by maxid** [comment]
为什么不支持？
