### ISSUE TITLE
能绘制复合饼图或者复合条饼图吗? Can echarts make these charts which created by EXCEL, or any ideas?

### ISSUE THREAD

**Issue by guoliangfei** [apache/incubator-echarts#8354]
echarts可以实现类似excel中的复合饼图或者复合条饼图吗？或者有什么实现思路？

![1](https://user-images.githubusercontent.com/4520090/40153506-b9539d14-59bc-11e8-8fc4-fa64f83b76a6.png)

![2](https://user-images.githubusercontent.com/4520090/40153510-bde437ee-59bc-11e8-9744-13d39c463d3c.png)

**Comment by tubbodeTang** [comment]
我在一个canvas上画了两个图，然后想自己画两条线把两个图连起来，然后我发现……
用 type:graph 画不出来线，坐标位置不知道怎么调整才对，很诡异

**Comment by guoliangfei** [comment]
@tubbodeTang 我也想过直接画两个图，但是连接线就是没有办法画出来

**Comment by tubbodeTang** [comment]
饼图的，我大概做成了[这样](http://gallery.echartsjs.com/editor.html?c=xHJaWqD-1Q&v=1)，其他的条状图的情况还没遇到过，遇到了再看，haha

**Comment by xibaoHu** [comment]
复合饼图有哪些插件可以实现吗？echarts可以画出两个饼图，就是连接线不知道怎么画，有比较好的思路可以交流下吗
