### ISSUE TITLE
能绘制正态分布图吗

### ISSUE THREAD

**Issue by liucs6666** [apache/incubator-echarts#8355]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以使用程序生成的正态分布数据画

**Comment by liucs6666** [comment]
能说的再具体吗？或者有demo吗？谢谢！发自我的华为手机-------- 原始邮件 --------主题：Re: [apache/incubator-echarts] 能绘制正态分布图吗 (#8355)发件人：Yi Shen 收件人：apache/incubator-echarts 抄送：liucs6666 ,Author 可以使用程序生成的正态分布数据画

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-echarts","title":"apache/incubator-echarts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-echarts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pissang in #8355: 可以使用程序生成的正态分布数据画"}],"action":{"name":"View Issue","url":"https://github.com/apache/incubator-echarts/issues/8355#issuecomment-389742520"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [apache/incubator-echarts] 能绘制正态分布图吗 (#8355)","sections":[{"text":"","activityTitle":"**Yi Shen**","activityImage":"https://avatars3.githubusercontent.com/u/841551?s=160\u0026v=4","activitySubtitle":"@pissang","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"apache/incubator-echarts\",\"issueId\":8355,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"apache/incubator-echarts\",\"issueId\":8355}"},{"targets":[{"os":"default","uri":"https://github.com/apache/incubator-echarts/issues/8355#issuecomment-389742520"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":336156735}"}],"themeColor":"26292E"}
