### ISSUE TITLE
怎么让地图里的splitlist的start 和 end的值有一个娶不到，我现在要做一个区间值

### ISSUE THREAD

**Issue by Reed228** [apache/incubator-echarts#8365]
怎么把一组数据划分4个区间段，注因为有小数，默认的值域都是闭区间

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没理解你的问题
