### ISSUE TITLE
echarts能否让graph关系图中的每个node都是一个piechart，甚至sunburst?

### ISSUE THREAD

**Issue by jokbull** [apache/incubator-echarts#8366]
### One-line summary [问题简述]
echarts是否让graph关系图中的每个node都是一个piechart，甚至sunburst?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

效果类似于
![nodecharts](https://user-images.githubusercontent.com/2133825/40264620-01be5b30-5b5b-11e8-9879-00d52c217705.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ymli1981** [comment]
这样就厉害了
