### ISSUE TITLE
如何配置背景颜色，从坐标轴开始

### ISSUE THREAD

**Issue by mumu1993** [apache/incubator-echarts#8367]
![image](https://user-images.githubusercontent.com/17734732/40265620-2f5d4c6e-5b6e-11e8-99a5-e8f815961b1a.png)
需求是这样的
![image](https://user-images.githubusercontent.com/17734732/40265628-5f07f50e-5b6e-11e8-836d-8ba133ce24b2.png)
但是做出来是这样的，想知道有没有相关配置？？让背景色可以从坐标轴开始？

**Comment by pissang** [comment]
使用 `markArea` 组件

**Comment by mumu1993** [comment]
这个具体应该怎么用呢？有demo么 @pissang

**Comment by mumu1993** [comment]
找到demo了 谢谢
