### ISSUE TITLE
sunburst自动下钻

### ISSUE THREAD

**Issue by cartWalk** [apache/incubator-echarts#8371]
可以实现自动下钻吗？不用鼠标点击
 
dispatchAction 好像没有该类型的

目前版本"echarts": "^4.1.0",

**Comment by Ovilia** [comment]
https://github.com/apache/incubator-echarts/commit/ab621a4497cd8a02ec75bb016a81e656f512cc7a 这里做了支持，下个版本可以以这样的形式调用：

```
chart.dispatchAction({
    type: 'sunburstRootToNode',
    targetNode: 'nike'
});
```

其中 targetNode 对应系列中一个 node 的 id，比如：
```
{
    name: 'Uncle Nike',
    id: 'nike'
    children: [{
        name: 'Cousin Betty',
        value: 1
    }, {
        name: 'Cousin Jenny',
        value: 2
    }]
}
```

如果急着用，可以自己 build 一下。`npm install; node build/build.js --release`

**Comment by drinkmooon** [comment]
能否通过这个action将sunburst图退回到根节点？
根节点是没有id的，该如何选中。
比如
```data: [
    { name: 'Uncle Nike', id: 'nike', children: [] },
    { name: 'Aunt Andy', id: 'andy', children: [] },
]```
当点击`UncleNike`以后 ，如何让图表退回到未点击的状态?
