### ISSUE TITLE
echarts2.0实例中以前有地图，现在没有这个分类了，我想找到那个城市冒圈圈的效果

### ISSUE THREAD

**Issue by daoke0818** [apache/incubator-echarts#8384]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.0
+ Browser version [浏览器类型和版本]:chrome66
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by komagic** [comment]
多的是，在官网gallary里

**Comment by daoke0818** [comment]
谢谢！



jianlong.li@hlsofttech.com
 
发件人： Jacky
发送时间： 2018-05-31 09:34
收件人： apache/incubator-echarts
抄送： daoke0818; Author
主题： Re: [apache/incubator-echarts] echarts2.0实例中以前有地图，现在没有这个分类了，我想找到那个城市冒圈圈的效果 (#8384)
多的是，在官网gallary里
