### ISSUE TITLE
例子里纵坐标和线的值根本对不上

### ISSUE THREAD

**Issue by haiyin-liu** [apache/incubator-echarts#8387]
### One-line summary [问题简述]

今天想试试echarts ，选了个基础的例子
http://echarts.baidu.com/examples/editor.html?c=line-stack 
发现这个例子里纵坐标和线的值根本对不上

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

快修正

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by haiyin-liu** [comment]
单条线是对的 ，多条线是错的

**Comment by boolak** [comment]
你没明白这个图的意思，人家这里是多个类目的累加值，所以是没有问题的

**Comment by haiyin-liu** [comment]
别忽悠我。一个横坐标对应好几个点呢？都是累加值？

**Comment by boolak** [comment]
自己多看文档吧

**Comment by haiyin-liu** [comment]
明白了
