### ISSUE TITLE
http://echarts.baidu.com/feature.html  该页面中柱状图和折线图链接相同

### ISSUE THREAD

**Issue by youyuyixiu** [apache/incubator-echarts#8391]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by youyuyixiu** [comment]
please check it

**Comment by Ovilia** [comment]
谢谢，我会修复一下
