### ISSUE TITLE
dataset.source 为空数组造成 echarts 抛错

### ISSUE THREAD

**Issue by skordyr** [apache/incubator-echarts#8395]
### One-line summary [问题简述]
dataset 在 dataset.source 为空数组的时候，在 DefaultDataProvider 方法中因为 sourceFormat 被判定为 unknown 导致继承不了 count 方法，然后在 listProto.initData 中会调用 count 方法导致抛出错误，导致后续无法更新视图

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本] : Chrome/66.0.3359.181
+ OS Version [操作系统类型和版本]: Mac OS X 10_13_4

### Expected behaviour [期望结果]
不影响后续的更新

### ECharts option [ECharts配置项]

```javascript
option = {
  dataset: {
    source: []
  },
 ....
}

```

### Other comments [其他信息]

[![Edit 0p91r1qxmp](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0p91r1qxmp)

**Comment by senro** [comment]
确实有这个问题，多数据集的情况也会有这个问题，希望官方尽快解决吧！挺影响使用的

**Comment by JonasGao** [comment]
+1 我也是，因为数据异步加载，初始化的时候肯定是没数据的

**Comment by Ovilia** [comment]
已修复
