### ISSUE TITLE
线形图异步数据加载动画错误

### ISSUE THREAD

**Issue by harsima** [apache/incubator-echarts#8397]
### One-line summary [问题简述]
当使用官网的异步加载示例时，将图表类型改为line时，图表线从上面滑落下来，而不是从左向右逐步画出来。
当图表类型为line，并且yAxis有min和max时，无加载动画

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 65.0.3325.181
+ OS Version [操作系统类型和版本]: Windows 10 1803

### Expected behaviour [期望结果]
如正常line型图表，动画为从左到右描线显示

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: '异步数据加载示例'
    },
    tooltip: {},
    legend: {
        data:['销量']
    },
    xAxis: {
        data: []
    },
    yAxis: {
        min: 0,
        max: 40
    },
    series: [{
        name: '销量',
        type: 'line',
        data: []
    }]
}

```

### Other comments [其他信息]

实例页面：[http://www.echartsjs.com/gallery/editor.html?c=doc-example/tutorial-async](http://www.echartsjs.com/gallery/editor.html?c=doc-example/tutorial-async)
请按照上文中option进行替换或修改（其实只修改了`series.type`及`yAxis`）
![3](https://user-images.githubusercontent.com/24699131/40490432-12b47dc4-5f9e-11e8-86b0-b9c208a018b7.gif)

**Comment by dagundejuzi** [comment]
请问怎么解决的？
