### ISSUE TITLE
怎么去掉toolbox中点击“数据视图”图标时的title

### ISSUE THREAD

**Issue by child110** [apache/incubator-echarts#8404]
### One-line summary [问题简述]
移动端去掉toolbox中点击图标时的title，但是点击【关闭】后显示[object,object],

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   4.1.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
 toolbox: {
                    feature: {
                        showTitle:false,
                        dataView: {
                            readOnly: true,
                            title:'',
                            lang : ['','关闭'],
                          }
                      }
              }
}

```

### Other comments [其他信息]

![_20180525141411](https://user-images.githubusercontent.com/32191006/40529092-f99a5e5c-6025-11e8-8c19-2f94fcf9b98c.png)

**Comment by child110** [comment]
想去掉dataView里面点开列表上的标题

**Comment by zy343134464** [comment]
option = {
 toolbox: {
                    feature: {
                        showTitle:false,
                        dataView: {
                            readOnly: true,
                            title:'数据视图',
                            lang : [' ','关闭'],
                          }
                      }
              }
}
