### ISSUE TITLE
中国的geo地图label不生效，不能显示自定义label

### ISSUE THREAD

**Issue by kharry126** [apache/incubator-echarts#8406]
One-line summary [问题简述]
在载geo地图，如果定义geo组件，且系列中通过geoIndex指定这个geo组件，系列中label不生效，
如果在geo组件中添加label的时候，能控制label显示以及修改字体样式等，当时formatter不生效，不能自定义label
![tim 20180525175413](https://user-images.githubusercontent.com/9064056/40538722-07e8cb32-6045-11e8-8f0f-2d1394bad581.png)

Version & Environment [版本及环境]
ECharts version :"echarts": "^4.0.4",
Browser version: chrome 66.0.3359.139
OS Version [操作系统类型和版本]: win10 64位

Expected behaviour [期望结果]
支持自定义label，地图显示文本

![aaaa](https://user-images.githubusercontent.com/9064056/40538708-fd56a464-6044-11e8-9f34-4b54f5b2231d.png)

### ECharts option [ECharts配置项]
option ={
	"geo": {
		"map": "china",
		label:{
            show:true,
            color:"#fff000",
            formatter: 'ssfsdfdsfdsf'
        }
	},
	"visualMap": {
		"min": 0,
		"max": 520,
		"text": [
			"高",
			"低"
		],
		"left": 4,
		"bottom": 4
	},
	"series": [{
		"name": "ShipAddress",
		"data": [
			{
				"value": 68,
				"displayValue": [
					"福建省",
					"68"
				],
				"rawName": "福建省",
				"rowIndex": [
					1,
					1
				],
				"colIndex": 1,
				"name": "福建"
			},
			{
				"value": 118,
				"displayValue": [
					"广东省",
					"118"
				],
				"rawName": "广东省",
				"rowIndex": [
					2,
					2
				],
				"colIndex": 1,
				"name": "广东"
			}
		],
		"type": "map"
	}]
}

**Comment by chfw** [comment]
nameMap?

**Comment by kharry126** [comment]
nameMap 不行  我需要的是动态的
