### ISSUE TITLE
如何给label里面的文字添加监听事件？

### ISSUE THREAD

**Issue by HaijieChen** [apache/incubator-echarts#8415]
label  无法编译html代码，我想在label里面的文字添加监听事件，没其他办法吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.X
+ Browser version [浏览器类型和版本]:chrom
+ OS Version [操作系统类型和版本]:window

### ECharts option [ECharts配置项]

```javascript
option = {
label:{
},
data:[{
label:{
}
}]
}

```

**Comment by pissang** [comment]
label 暂时不支持事件监听
