### ISSUE TITLE
bar3D堆叠bug

### ISSUE THREAD

**Issue by hanchengz** [apache/incubator-echarts#8416]

**Comment by jjjhai** [comment]
请问这个问题解决了吗？我在geo3D上实现叠加的bar3D，配置了相同的stack，但是不显示叠加的效果
![_20181228114541](https://user-images.githubusercontent.com/15151350/50501978-eaaba380-0a96-11e9-8429-eca5288942a6.png)

**Comment by zhaoxiaoran** [comment]
请问你的具体option是怎么配置的？我这边设置stack之后，柱状图并没有堆叠，而是重合在一起...
