### ISSUE TITLE
toolbox 如何顯示繁體中文

### ISSUE THREAD

**Issue by Scovin** [apache/incubator-echarts#8418]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by komagic** [comment]
formatter 嘛

**Comment by chfw** [comment]
请参照这个PR：https://github.com/apache/incubator-echarts/pull/6863
