### ISSUE TITLE
myChart.addData is not a function？这个是怎么回事

### ISSUE THREAD

**Issue by ITLiuQing** [apache/incubator-echarts#8421]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
3.0 开始没有 addData 这个方法
