### ISSUE TITLE
How to make a node above the axis?

### ISSUE THREAD

**Issue by rundleman** [apache/incubator-echarts#8426]
## One-line summary: 
In my case the axis overlaps the node. On the examples of the site I saw this (look pictures below), but I can't find an option
![screenshot from 2018-05-30 15-58-41_cut-photo ru](https://user-images.githubusercontent.com/24862906/40716517-b6ab5b68-6422-11e8-8924-77be7c2d7639.png)
## Version & Environment: 
ECharts version : 4.1.0
Browser version  : Chrome/66
OS Version: Linux Mint 18
## Expected behaviour 
![screenshot from 2018-05-30 16-02-39_cut-photo ru](https://user-images.githubusercontent.com/24862906/40716668-32061050-6423-11e8-9701-3537bc61ea8a.png)
## ECharts option 
I dont know

**Comment by rundleman** [comment]
I found. I need zlevel attribute.

Close.

**Comment by komagic** [comment]
u could find “data“ in “series“（type:"line"）,and u can insert some numbers, like[2,3,4],also u can insert    an object, instead of numbers,e.g.[{value:2,label:{...}},{value:3,label:{...}}]

**Comment by komagic** [comment]
![555](https://user-images.githubusercontent.com/13415767/40755935-45bc10aa-64b3-11e8-8818-10b6e5469a5f.png)
