### ISSUE TITLE
echarts tree(纵向)高度问题

### ISSUE THREAD

**Issue by jaslou** [apache/incubator-echarts#8430]
### One-line summary [tree 当设置树所在的div的height大于32000px的时候树就显示不出来了，一片空白，但是用IE11话可以显示，但是最后面的节点显示不全]
正常的div高度可以设置的可不止32000px。

相关代码如下：

var container = document.getElementById('echarts-line-chart');
var allNodes=lineChart._chartsViews[0]._data._graphicEls;
var currentHeight=20*(allNodes.length-1);
var newWidth=Math.max(currentHeight,height);
container.style.height = newWidth + 'px';  
myChart.resize();

当newWidth大于33000px的时候整颗树就显示不出来了。请问一下是什么原因呢？谢谢！

### Version & Environment [版本及环境]
+ ECharts version [4.0.0]:
+ Browser version [Chrome 66.0.3359.181 or Firefox 60.0.1]:
+ OS Version [win10]:

### Expected behaviour [期望结果]
不管设置height为多少，只要不操作html标签的最大高度的话应该可以显示的。

### ECharts option [ECharts配置项]

```javascript
option = {
}
```

**Comment by pissang** [comment]
这个应该是因为浏览器中 canvas 画布的高度限制...

**Comment by jaslou** [comment]
好吧，难怪我调试进源码都没有发现有关于高度的相关限制。
刚看了一下，canvas画布高度限制为32767，超过了就画不出了。
thanks！
