### ISSUE TITLE
如何让散点图能像饼图一样使用labelline？

### ISSUE THREAD

**Issue by raonian** [apache/incubator-echarts#8431]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
如图：
![image](https://user-images.githubusercontent.com/11386431/40758578-94c4c0b8-64c0-11e8-83a7-b87c8a6ce8e4.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
散点图还不支持 labelLine，可以尝试使用自定义系列或者 graphic 组件去实现
