### ISSUE TITLE
echarts 4.0 的兼容性怎么样，兼容IE8吗？

### ISSUE THREAD

**Issue by summerhll** [apache/incubator-echarts#8432]
### One-line summary [问题简述]
请问在哪里可以看到echarts的兼容性描述，在官网没找到，谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
基础图表都支持 IE8
