### ISSUE TITLE
如何获取省内每个市的坐标建立地图？

### ISSUE THREAD

**Issue by KellySha** [apache/incubator-echarts#8436]
### One-line summary [问题简述]
如何获取省内每个市的坐标建立地图？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3or4
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
想画出广东省深圳市的地图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ppsj** [comment]
你需要的是单个地图的话。
其实可以吧广东省地图下载下载再删除=。=
http://www.ourd3js.com/wordpress/638/

**Comment by chfw** [comment]
请参考这个图库： https://github.com/echarts-maps/echarts-china-cities-js#pyecharts-usage

<img src="https://user-images.githubusercontent.com/4280312/29755070-9bc9ae70-8b89-11e7-9bf2-bec09cb5f1a1.png" width=600>

城市坐标请审核这个[坐标文件](https://github.com/pyecharts/pyecharts/blob/master/pyecharts/datasets/city_coordinates.json)

**Comment by komagic** [comment]
echarts 源码里不是有map吗?
但是如果严格要求的话echarts地图不符合测绘法,不让用.大项目不要用

**Comment by chfw** [comment]
我的理解是中国地图需要进一步审核。其他省市地图并不包含敏感地区，比如北京，河北，理论上是可以的。根据国家地图法，所有商用地图需要国家审查备案之后才能用。

**Comment by komagic** [comment]
我之前用的时候杭州湾，新疆，海南、内蒙古有些问题。。关键是现在还要求敏感边界要虚线，海岸线要虚线，echarts虚线效果也不好，很烦
