### ISSUE TITLE
如何实现一个梯形波图（频谱图）

### ISSUE THREAD

**Issue by Bonjourjw** [apache/incubator-echarts#8439]
One-line summary [问题简述]
echarts如何实现绘制一个梯形频谱图，相当于每个数据是一个频谱范围，每个数据的展示就是一个梯形图。看了自定义系列，type类只有原有的'line'、'pie'……，只能利用本来有的类型进行修改。
我需要修改源码来实现吗？

Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3or4
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:win7

 Expected behaviour [期望结果]
类似于下面这种效果，不过波谷不会绘制出来
![image](https://user-images.githubusercontent.com/35286719/40772028-7dd3a65e-64f1-11e8-9d1c-0dc1bb9c63be.png)

ECharts option [ECharts配置项]

option = {

}

```




 Other comments [其他信息]

**Comment by Bonjourjw** [comment]
谢谢，我之前一直想要用自定义系类画来着，不过发现，折线图更简单，哈哈，已经实现。
![image](https://user-images.githubusercontent.com/35286719/40896620-9b6774a8-67e8-11e8-9f16-8a6e4e87b031.png)

**Comment by memorybx** [comment]
> 谢谢，我之前一直想要用自定义系类画来着，不过发现，折线图更简单，哈哈，已经实现。
> ![image](https://user-images.githubusercontent.com/35286719/40896620-9b6774a8-67e8-11e8-9f16-8a6e4e87b031.png)

作者你好：
请问你是怎么实现的，可以倾角一下吗？如何定义x轴的数据，比如说第一个，0-60之间的数据的？
