### ISSUE TITLE
xAxis ticks disappappear when set negative min Yaxis value.

### ISSUE THREAD

**Issue by ghost** [apache/incubator-echarts#8441]
When I set negative min. value at  yAxis value the xAxis ticks disappear. I attach a picture.

**Here is the wrong chart with negativr axes.**
![chart](https://user-images.githubusercontent.com/32642115/40774328-9466131a-64c5-11e8-9cc0-9d165db3f92f.png)

**Here with just postive values:**
![screenshot from 2018-05-31 11-27-02](https://user-images.githubusercontent.com/32642115/40774434-e19d4eb4-64c5-11e8-93f1-79fd1dce94a9.png)

EDITED:
I have forgot to note that I use 'time' type at the xAxes.

**Comment by pissang** [comment]
The label of xAxis is always on the bottom of chart.

**Comment by bummm26** [comment]
Oke, but is there any way to make visible the ticks in that case?

**Comment by Ovilia** [comment]
The tick is already visible.
