### ISSUE TITLE
‘treemap’ 的默认背景色不是 ‘transparent’ 而是白色

### ISSUE THREAD

**Issue by 007c** [apache/incubator-echarts#8447]
### One-line summary [问题简述]
‘treemap’ 的默认背景色不是 ‘transparent’ 而是白色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 66.0
+ OS Version [操作系统类型和版本]: Mac OS 10.13.1

### Expected behaviour [期望结果]
背景色应该是透明的而不是白色

### ECharts option [ECharts配置项]

```javascript
option = {
    series: [{
        type: 'treemap',
        data: [{
            name: 'nodeA',            // First tree
            value: 10,
            itemStyle: {
                color: 'transparent',
            },
            children: [{
                name: 'nodeAa',       // First leaf of first tree
                value: 4
            }, {
                name: 'nodeAb',       // Second leaf of first tree
                value: 6
            }]
        }, {
            name: 'nodeB',            // Second tree
            value: 20,
            children: [{
                name: 'nodeBa',       // Son of first tree
                value: 20,
                children: [{
                    name: 'nodeBa1',  // Granson of first tree
                    value: 20
                }]
            }]
        }]
    }]
};
```

**Comment by Hobbes1987** [comment]
## The default background color of 'treemap' is not 'transparent' but white
We're running into this issue too. How can we make the treemap transparent?

**Comment by shizhihuaxu** [comment]
同遇到此问题

**Comment by plainheart** [comment]
默认似乎会用 borderColor 作为背景色，如需透明可以设置 `itemStyle.borderColor` 为 `transparent`

```js
series: [{
  type: 'treemap',
  itemStyle: {
    borderColor: 'transparent'  
  }
}]
```

**Comment by zxgMaster** [comment]
> 默认似乎会用 borderColor 作为背景色，如需透明可以设置 为`itemStyle.borderColor``transparent`
> 
> ```js
> series: [{
>   type: 'treemap',
>   itemStyle: {
>     borderColor: 'transparent'  
>   }
> }]
> ```

这个有效，找了一天了，终于找到能改的了
