### ISSUE TITLE
echarts中的canvas画布如何设置width,height属性跟其style中的width、height

### ISSUE THREAD

**Issue by unlangchan** [apache/incubator-echarts#8448]
### One-line summary [问题简述]

echarts中的canvas画布如何设置width,height属性跟其style中的width、height

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.x
+ Browser version [浏览器类型和版本]: all
+ OS Version [操作系统类型和版本]:all

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
通过在 init 的时后设置里面的 devicePixelRatio, width, height 参数，不建议改里面 canvas 的属性，会出无法预料的问题。

见 http://echarts.baidu.com/api.html#echarts.init
