### ISSUE TITLE
动态嵌套饼图时， Cannot read property 'startAngle' of undefined

### ISSUE THREAD

**Issue by sai111** [apache/incubator-echarts#8450]
### One-line summary [问题简述]
动态嵌套饼图，使用onmouseover 经过外层饼图，内层饼图动态发生变化，出现

PieView.js:38 Uncaught TypeError: Cannot read property 'startAngle' of undefined
    at toggleItemSelected (PieView.js:38)
    at PiePiece.webpackJsonp../node_modules/_echarts@4.0.4@echarts/lib/chart/pie/PieView.js.piePieceProto.updateData (PieView.js:126)
    at DataDiffer._update (PieView.js:256)
    at DataDiffer.execute (DataDiffer.js:76)
    at ExtendedClass.render (PieView.js:264)
    at Task.progress [as _progress] (Chart.js:228)
    at Task.webpackJsonp../node_modules/_echarts@4.0.4@echarts/lib/stream/task.js.taskProto.perform (task.js:89)
    at echarts.js:1330
    at ExtendedClass.<anonymous> (Global.js:479)
    at Array.forEach (<anonymous>)

具体代码
function toggleItemSelected(el, layout, isSelected, selectedOffset, hasAnimation) {
  var midAngle = (layout.startAngle + layout.endAngle) / 2;
 **这里出现问题  Cannot read property 'startAngle' of undefined**
  var dx = Math.cos(midAngle);
  var dy = Math.sin(midAngle);
  var offset = isSelected ? selectedOffset : 0;
  var position = [dx * offset, dy * offset];
  hasAnimation // animateTo will stop revious animation like update transition
  ? el.animate().when(200, {
    position: position
  }).start('bounceOut') : el.attr('position', position);
}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
echarts 版本 4.0.4 
浏览器 chroom 11
window10 

### Expected behaviour [期望结果]
不再出现找不到 startAngle undefined

### ECharts option [ECharts配置项]

```javascript

 this.chart.on("mouseover", function(params) {
        if (params.seriesName === "外层的数据") {
          var id = params.data.id
          _this.patrol_pie_problem.series[0].data = _this.dispatch_finish[id]
          _this.chart.setOption({ ...patrol_pie_problem })
      }
      })

const CommonColor = [
  "#1668FF",
  "#4974FF",
  "#299EFF",
  "#29CAFF",
  "#00FFFF",
  "#FF9711",
  "#FFD34E",
  "#FFE44E",
  "#F0FF4E"
]
option = {
  title: {
    text: "",
    left: "center",
    top: 20,
    textStyle: {
      color: "#fff",
      align: "right"
    }
  },
  tooltip: {
    trigger: 'item',
    formatter: "{a} <br/>{b}: {c} ({d}%)",
  },
  legend: {
    show: true,
    type: 'scroll',
    data: [],
    selected: true,
    bottom: 20,
    left: 10,
    right: 10,
    pageIconColor: '#299eff',
    pageIconInactiveColor: '#299eff',
    pageIconSize: 10,
    pageTextStyle: {
      fontSize: 10,
      color: '#fff',
    },
    textStyle: {
      color: "#fff",
      fontSize: '10'
    },
    color: CommonColor
  },
  series: [
    {
      color: ["#4974FF", "#299EFF"],
      name: '完成率',
      type: 'pie',
      radius: [0, '30%'],
      label: {
        normal: {
          position: 'inner'
        }
      },
      labelLine: {
        normal: {
          show: false
        }
      },
      data: []
    },
    {
      color: CommonColor,
      name: '公司',
      type: 'pie',
      radius: ['40%', '55%'],
      label: {
        normal: {
          show: false
        },
        emphasis: {
          show: true
        }
      },
      data: []
    }
  ]
}

```

**Comment by hl-stone** [comment]
也发现 有此问题，在IE9、8 浏览器下面 option 代码如下，点击 legend 控制台错误：【startAngle 为空或不是对象】
var option3 = {
		title : {
			text: '年末从业人数',
			backgroundColor:'#00479d',
			borderRadius: 5,
			left: 'left',
			top: 0,
			textStyle: {
				color: '#fff',
				fontWeight:'normal'
			},
			padding:[5,15]
		},
		toolbox: {
			show : false,
			feature : {
				mark : {show: true},
				dataView : {show: true, readOnly: false},
				magicType : {
					show: true,
					type: ['pie', 'funnel'],
					option: {
						funnel: {
							x: '25%',
							width: '50%',
							funnelAlign: 'left',
							max: 1548
						}
					}
				},
				restore : {show: true},
				saveAsImage : {show: true}
			}
		},
		legend: {
			textStyle:{
				color:'#ffffff'
			},
			data: ['外方','中方'],
			itemWidth: 10,
			itemHeight: 10,
			right: 20
		},
		tooltip: {
			trigger: 'item',
			formatter: "{a} <br/>{b} : {c} ({d}%)"
		},
		series: [{
			name: '',
			type: 'pie',
			startAngle:90,
			radius: '55%',
			center: ['27%', '50%'],
			data: [{
				value: 45,
				name: '外方'
			}, {
				value: 25,
				name: '中方'
			}],
			label: {
				normal: {
					textStyle: {
						color: '#fff',
						fontSize: 12,
					},
					position: 'inside',
					formatter: '{b}\n{d}%'
				}
			},
			labelLine: {
				normal: {
					show: false
				}
			},
			itemStyle: {
				normal: {
					borderWidth: 2,
					borderColor: '#022b7c',
				},
				emphasis: {
					borderWidth: 0,
					shadowBlur: 10,
					shadowOffsetX: 0,
					shadowColor: 'rgba(0, 0, 0, 0.5)'
				}
			}
		},
		{
			name: '',
			type: 'pie',
			startAngle:90,
			radius: '55%',
			center: ['72%', '50%'],
			data: [{
				value: 456,
				name: '外方'
			}, {
				value: 251,
				name: '中方'
			}, ],
			label: {
				normal: {
					textStyle: {
						color: '#fff',
						fontSize: 12,
					},
					position: 'inside',
					formatter: '{b}\n{d}%'
				}
			},
			labelLine: {
				normal: {
					show: false
				}
			},
			itemStyle: {
				normal: {
					borderWidth: 2,
					borderColor: '#022b7c',
				},
				emphasis: {
					borderWidth: 0,
					shadowBlur: 10,
					shadowOffsetX: 0,
					shadowColor: 'rgba(0, 0, 0, 0.5)'
				}
			}
		}],
		color: [
			'#e6ad0a',
			'#3ba0f5',
			'#79d9f1',
			'#a7e7ff',
			'#c8efff'
		],
	};
