### ISSUE TITLE
echart 3d地图缩放时不能像2d地图一样缩放中心在鼠标位置吗

### ISSUE THREAD

**Issue by Jfs007** [apache/incubator-echarts#8451]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  4.1.0
+ Browser version [浏览器类型和版本] :chrome
+ OS Version [操作系统类型和版本]: mac os

### Expected behaviour [期望结果]

3d地图缩放时可以像2d地图一样缩放中心在鼠标位置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个不会支持，3D 和 2D 的操作方式有很大的不同

**Comment by Jfs007** [comment]
那这种有办法实现吗，看源码看的有些懵，请问放大缩小是直接transform自由变化实现的吗
