### ISSUE TITLE
bar3d  detailTexture给3d柱状图贴图。

### ISSUE THREAD

**Issue by ljxtest** [apache/incubator-echarts#8454]
### One-line summary [问题简述]
求助我想给3d柱状图柱体贴一个颜色渐变的图片，贴图上去效果不对显示的不是我加载的那张图片的样子。shading几种着色方式都试了。。。

### Version & Environment [版本及环境]
var echartsGl = {
    version: '1.1.1',
    dependencies: {
        echarts: '4.1.0',
        claygl: '1.2.1'
    }
};

### ECharts option [ECharts配置项]
        var optionPro = {
            tooltip: {},
            xAxis3D: {
                type: 'category',
                data: hours
            },
            yAxis3D: {
                type: 'category',
                data: days
            },
            zAxis3D: {
                type: 'value'
            },
            grid3D: {
                boxWidth: 200,
                boxDepth: 80,
                light: {
                    main: {
                        intensity: 2,
                        shadow: false
                    },
                    ambient: {
                        intensity: 0
                    }

                }
            },
            series: [{
                type: 'bar3D',
                data: data.map(function (item) {
                    return {
                        value: [item[1], item[0], item[2]],
                    }
                }),
                shading: 'realistic',
                barSize:50,
                realisticMaterial:{
                    detailTexture:'/img/bc1.png'
                },
                label: {
                    textStyle: {
                        fontSize: 16,
                        borderWidth: 1
                    }
                }
            }]
        }
        this.myChart.setOption(optionPro);

![image](https://user-images.githubusercontent.com/25787395/40833918-d469ccb6-65c1-11e8-9d28-728f98b3de5d.png)

**Comment by pissang** [comment]
bar3D 暂时还不支持 detailTexture 的设置

**Comment by FEbean** [comment]
> bar3D 暂时还不支持 detailTexture 的设置

你好，咨询下，现在还不支持detailTexture 吗？ 那bar3D 支持routhness这个字段的调整吗
