### ISSUE TITLE
服务器挂了

### ISSUE THREAD

**Issue by HTMLWU** [apache/incubator-echarts#8459]
### One-line summary [问题简述]
http://gallery.echartsjs.com/explore.html?u=bd-2135947294  此链接请求接口报错，服务器挂了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jsvr** [comment]
echart 图例页面全挂了

**Comment by pissang** [comment]
已恢复，谢谢反馈
