### ISSUE TITLE
数据点均匀分布

### ISSUE THREAD

**Issue by Zhenbin24** [apache/incubator-echarts#8465]
![image](https://user-images.githubusercontent.com/33947214/40964250-30121618-68dd-11e8-8bd1-1d5b5f288d20.png)

就像上面的图像一样，line1和line2拥有共同的x轴，而且x轴的长度是固定的，但是y轴的数据长度就不固定了，但不会超过x轴的长度，现在我想不管y轴有多少个数据，与x轴构成的点总能均匀的分布在图像当中，像上面的图，请教下各位，怎么取去实现？

**Comment by pissang** [comment]
没理解你的意思

**Comment by Zhenbin24** [comment]
@pissang 谢谢问题已经解决了，利用双轴实现了效果。
