### ISSUE TITLE
官网接口文档3.x的版本不对，貌似和4.x 一致的，希望能修复

### ISSUE THREAD

**Issue by qingniaotonghua** [apache/incubator-echarts#8477]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请详细描述你的问题
