### ISSUE TITLE
graph 关系图label标签可以是支持html 吗？

### ISSUE THREAD

**Issue by julien-joe** [apache/incubator-echarts#8478]
### One-line summary [问题简述]
graph 关系图label标签可以是支持html 吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
3.37

### Expected behaviour [期望结果]
关系图图表lable 有点击事件

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以使用富文本标签
