### ISSUE TITLE
echarts怎么让刷新图表数据后 datazoom保持在之前拖拽到的位置

### ISSUE THREAD

**Issue by huangenzi** [apache/incubator-echarts#8479]
### One-line summary [问题简述]

echarts怎么让刷新图表数据后 datazoom保持在之前拖拽到的位置

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

刷新图表数据后 datazoom保持在之前拖拽到的位置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
getOption 获得 dataZoom 的 start 和 end， 再在 setOption 的时候设置

**Comment by surplus-cat** [comment]
`if (this.option.hasOwnProperty('dataZoom')) {
        `this.myChart.on('dataZoom',` (params) => {
          this.option.dataZoom.start = params.start;
          this.option.dataZoom.end = params.end;
        });
      }`
监听 dataZoom事件
