### ISSUE TITLE
echarts中graph图拖拽某一个点之后，点到了拽到的位置不再弹回去

### ISSUE THREAD

**Issue by jasperjiang0204** [apache/incubator-echarts#8480]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
目前无法实现
