### ISSUE TITLE
赤尾屿和南海诸岛不显示？

### ISSUE THREAD

**Issue by seasolzombie** [apache/incubator-echarts#8485]
### One-line summary [问题简述]
中国全图必须表示南海诸岛、钓鱼岛、赤尾屿等重要岛屿，并用相应的符号绘出岛屿归属线--国家测绘局
请看国家测绘局链接 http://www.sbsm.gov.cn/ggfw/zsyd/chzs/btzs/200711/t20071102_83290.shtml
我们公司要使用echart做一个地图，但是插件里面根本不显示南海诸岛和赤尾屿等重要岛屿，官网里面的例子全是这样的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:v3
+ Browser version [浏览器类型和版本]:chrome 63
+ OS Version [操作系统类型和版本]:macOS

### Expected behaviour [期望结果]
显示南海诸岛和赤尾屿等重要岛屿

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
ECharts 不再提供地图的数据，请自行寻找符合国家标准的测绘数据

**Comment by ceerqingting** [comment]
在echarts的源码修改nanhai的坐标，修改成如下即可
const points = [
    [
      [-180, 110],
      [-175, 120]
    ],
    [
      [-170, 148],
      [-173, 158]
    ],
    [
      [-200, 198],
      [-199, 208]
    ],
    [
      [-165, 228],
      [-150, 226]
    ],
    [
      [-130, 198],
      [-120, 188]
    ],
    [
      [-100, 158],
      [-94, 146]
    ],
    [
      [-90, 124],
      [-89, 112]
    ],
    [
      [-80, 92],
      [-72, 80]
    ],
    [
      [-56, 58],
      [-44, 44]
    ],
    [
      [-36, 28],
      [-32, 14]
    ]
  ]
