### ISSUE TITLE
坐标轴添加箭头不成功

### ISSUE THREAD

**Issue by succulen-plants** [apache/incubator-echarts#8491]
### One-line summary [问题简述]
yAxis: {
                type: 'value',
                splitLine: {show: false},
                axisLine: {
                    show: true,
                    symbol: ['none','arrow'],
                }
    
            },

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
先升级到最新版本
