### ISSUE TITLE
怎么设置关系图节点位置？

### ISSUE THREAD

**Issue by jane0326** [apache/incubator-echarts#8496]
### One-line summary [问题简述]
怎么设置关系图节点位置？我自己生成的图中一共有80个节点左右，200条关系线，有的节点value值比较大，周围就空了一片，有的节点挨得比较近，还会出现节点覆盖的情况。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
echarts 3.8.7
chrome 66
windows10

### Expected behaviour [期望结果]
在节点不是很多的情况下，让节点不会有覆盖的情况，或者让节点均匀分布

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![qq 20180610204354](https://user-images.githubusercontent.com/26913869/41201691-03867754-6cef-11e8-975d-7b7f34cecef6.jpg)

**Comment by jane0326** [comment]
补充一点：程序中没有单独给几点设置x，y轴的值

**Comment by pissang** [comment]
这个是自动布局的，你可以把那些小点的 symbolSize 设置得大点
