### ISSUE TITLE
3D散点图无法触发鼠标事件和显示提示框

### ISSUE THREAD

**Issue by cheeyanyeong** [apache/incubator-echarts#8498]
### One-line summary [问题简述]
当3D 散点图只有一个数据点的时候，鼠标悬浮在该数据点上时没办法触发鼠标事件和显示提示框。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  echarts, version 4.1.0 and echarts-gl, version 1.1.0
+ Browser version [浏览器类型和版本]: Google Chrome Version 67.0.3396.79 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: Windows 7 Profesional

### Expected behaviour [期望结果]
当3D 散点图只有一个数据点的时候，鼠标悬浮在该数据点上时能够触发鼠标事件和显示提示框。

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis3D: {
        type: 'value'
    },
    yAxis3D: {
        type: 'value'
    },
    zAxis3D: {
        type: 'value'
    },
    grid3D: {
        axisLine: {
            lineStyle: { color: '#fff' }
        },
        axisPointer: {
            lineStyle: { color: '#fff' }
        }
    },
    series: [
        {
            type: 'scatter3D',
            data:  [
                //[1,1,1],
                [2,2,2]
            ]
        },
        // {
        //     type: 'scatter3D',
        //     data:  [
        //         //[2,1,2],
        //         [3,1,1]
        //     ]
        // }
    ],
    tooltip: {}
}

```

**Comment by Lion0707** [comment]
你需要设置tooltip：{}这个属性啊

**Comment by liangyinga** [comment]
现在还是会有部分散点无法触发

**Comment by liangyinga** [comment]
现在还是会有部分散点无法触发，偶尔会在散点旁边的部位触发

**Comment by liangyinga** [comment]
现在还是会有部分散点无法触发，偶尔会在散点旁边的部位触发 echarts 5.2.2,  echarts-gl 2.0.8

**Comment by liangyinga** [comment]
只有一个点的时候也无法触发
