### ISSUE TITLE
支持Weex吗

### ISSUE THREAD

**Issue by cileLV** [apache/incubator-echarts#8500]
能在Weex项目中使用吗？想在Weex项目中绘制图表，如何使用？

**Comment by Ovilia** [comment]
只要支持 Canvas API 就支持

**Comment by cileLV** [comment]
Weex中不支持dom,也没有Canvas。我集成了GCanvas，但是不能正确的绘制图表。
var ref = this.$refs.canvas_holder
var gcanvas = GCanvas.start(ref)
var ctx = gcanvas.getContext('2d')
ctx.fillStyle = 'red'
 ctx.fillRect(0, 0, 100, 100)   // 这个红色的矩形能绘制
var myChart = echarts.init(gcanvas)
var option={......}
myChart.setOption(option)

**Comment by Ovilia** [comment]
那需要做挺多兼容性的事情的，我们没有额外支持 weex 的经历，你可以参考我们兼容微信小程序的方案（也是没有 DOM 操作）https://github.com/ecomfe/echarts-for-weixin/blob/master/ec-canvas/wx-canvas.js

**Comment by aixiaoxiang** [comment]
期待有一个 weex 版本的
