### ISSUE TITLE
echarts可以同时引用多个本地数据文件吗

### ISSUE THREAD

**Issue by jasperjiang0204** [apache/incubator-echarts#8502]
### One-line summary [问题简述]
有多个数据文件，不方便将数据合并在一个文件中。。请问用$.get()函数应该怎么做？

`url1='data/1.txt'
    url2='data/2.txt'
	$.get(url1,
function(xml) {`

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这是 jQuery 的问题吧，无关，关闭了
