### ISSUE TITLE
series map和百度地图之间坐标如何进行转换？

### ISSUE THREAD

**Issue by nekonabe-tokumori** [apache/incubator-echarts#8504]
尝试在map图表下铺一层百度地图，但是发现没有办法很好的重合？但是同样的数据，直接绘制polygon可以在地图上很好的显示。尝试将geo坐标WGS84没有明显效果。

对转换到对地图这块不是很了解，求教如何转换2者间的坐标？
polygon绘制
![wechatimg555](https://user-images.githubusercontent.com/38372920/41274026-7a1c6db4-6e4e-11e8-98ed-677b7832327e.jpeg)
Map图表
![wechatimg556](https://user-images.githubusercontent.com/38372920/41274061-930f794c-6e4e-11e8-9b90-5de27177d24b.jpeg)

**Comment by pissang** [comment]
建议还是用自定义系列的 polygon 绘制

**Comment by nekonabe-tokumori** [comment]
使用的就是polygon绘制，只是polygon现在不支持绑定交互事件，看到之前这个issue一直打开着

**Comment by DorisOu** [comment]
您好，你这个自定义的区域是怎么用polygon实现的？我只能画出一个区域。求代码

**Comment by DorisOu** [comment]
@nekonabe-tokumori  自定义坐标是这样的格式；
//自定义区域坐标
    var paths = [
        [
            [113.447976, 22.363792],
            [113.328872, 22.422652],
            [113.370276, 22.308298],
            [113.474307, 22.260588]
        ],
        [
            [113.55542316292018, 22.451920414231754],
            [113.55552840279444, 22.452818734758235],
            [113.55371761986818, 22.453423869526087],
            [113.55356109301499, 22.454512840320145]
        ]
    ]
renderItem这样用没有问题，但是我要怎么循环渲染出pths的多边形？
function renderItem(params, api) {
        var coords = paths[0];
        var points = [];
        for (var i = 0; i < coords.length; i++) {
            points.push(api.coord(coords[i]));
        }
        return {
            type: 'polygon',
            shape: {
                points: echarts.graphic.clipPointsByRect(points, {
                    x: params.coordSys.x,
                    y: params.coordSys.y,
                    width: params.coordSys.width,
                    height: params.coordSys.height
                })
            },
            style: api.style({
                fill: 'lightblue',
                stroke: '#000'
            })
        }
    }
