### ISSUE TITLE
如何用代码控制缩放模式开启

### ISSUE THREAD

**Issue by LIUGUANZ** [apache/incubator-echarts#8505]
ECharts 版本：4.1.0
如何用代码控制缩放模式开启 （toolbox.feature.dataZoom）是工具栏里的内置的缩放，正常使用是鼠标点击开启后，在图表中框选放大的范围。
 想要实现的效果是，不需要去点击开启，可以直接在图表中框选。

**Comment by lizhancheng** [comment]
Here is the solution
https://github.com/apache/incubator-echarts/issues/5994
