### ISSUE TITLE
如何给散点图中圆点旁边的lable添加click事件

### ISSUE THREAD

**Issue by BobLuo** [apache/incubator-echarts#8506]
### One-line summary [问题简述]
如何给散点图中圆点旁边的lable添加click事件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.4
+ Browser version [浏览器类型和版本]: 66.0.3359.181
+ OS Version [操作系统类型和版本]: win 10

### Expected behaviour [期望结果]
可以监听散点图中圆点旁边的lable click事件

**Comment by Paul-Yellow** [comment]
我也遇到了点击lable的问题了  是tree的树形图的lable，获取不到事件
