### ISSUE TITLE
地图的demo显示不了地图

### ISSUE THREAD

**Issue by alonlion** [apache/incubator-echarts#8516]
### One-line summary [问题简述]

http://echarts.baidu.com/examples/editor.html?c=map-polygon
这个地图显示不了了，之前还是可以的，是百度地图有限制了？还是最新版本的js有问题了？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新
+ Browser version [浏览器类型和版本]:Google Chrome 67.0.3396.62
+ OS Version [操作系统类型和版本]:win10 企业版

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个是新版本 backgroundColor 优化带来的问题，backgroundColor 的绘制会在百度地图之前，去掉 backgroundColor 就好了

**Comment by pissang** [comment]
qu
