### ISSUE TITLE
如何将数据库查询结果直接绑定到dataset

### ISSUE THREAD

**Issue by zqdabao** [apache/incubator-echarts#8518]
这不是bug，是寻求一个技术帮助
我是初学者，技术的不太熟悉，求帮忙。
我看了官方教程，目前是可以将json数据添加到dataset上，然后更新图标。
可是从从数据库查询数据怎么转成json，不知道，然后转成的json文件是要存哪里，还是直接就可绑定到dataset，然后更新表？
我的数据库是SQL server，我想设计几个按钮，点不同按钮就从数据库查询不同数据更新图表。
谢谢！

**Comment by pissang** [comment]
这个建议先学习一些前端的基础知识
