### ISSUE TITLE
Component series.gauge not exists. Load it first.

### ISSUE THREAD

**Issue by alert-0822** [apache/incubator-echarts#8521]
在使用echarts 过程出现如题（Component series.gauge not exists. Load it first.）的报错

![image](https://user-images.githubusercontent.com/29430962/41356188-f112262c-6f55-11e8-9081-f53324cf5ea5.png)

echarts 版本 4.1.0

期望结果：
期望仪表盘正常显示

以下是为option
let getOption = (data) => {
  let option = {
    tooltip: {
      formatter: "{b} : {c} %"
    },
    series: {
      name: "加油站运营率",
      type: "gauge",
      data: [
        {
          value: parseInt(data.result), // ajax 返回数据
          name: "运营率"
        }
      ],
      radius: "90%",
      axisLine: {
        lineStyle: {
          width: 10
        }
      },
      axisTick: {
        length: 15, // 属性length控制线长
        lineStyle: {
          color: "auto"
        }
      },
      splitLine: {
        length: 20, // 属性length控制线长
        lineStyle: {
          color: "auto"
        }
      },
      axisLabel: {
        color: "#eee",
        textShadowBlur: 2,
        textShadowOffsetX: 1,
        textShadowOffsetY: 1,
        textShadowColor: "#222"
      },
      title: {
        fontWeight: "bolder",
        fontSize: 18,
        fontStyle: "italic",
        color: "#fff"
      },
      detail: {
        fontWeight: "bolder",
        fontSize: 16,
        borderRadius: 3,
        backgroundColor: "#444",
        borderColor: "#aaa",
        shadowBlur: 5,
        shadowColor: "#333",
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        borderWidth: 2,
        textBorderColor: "#000",
        textBorderWidth: 2,
        textShadowBlur: 2,
        textShadowColor: "#fff",
        textShadowOffsetX: 0,
        textShadowOffsetY: 0,
        fontFamily: "Arial",
        width: 100,
        color: "#fff",
        formatter: "{value}%",
        offsetCenter: [0, "65%"]
      },
      pointer: {
        width: 5
      },
      itemStyle: {
        borderWidth: 1
      }
    }
  };
  // option.series.data[0].value = parseInt(data.result)
  return option
}

export default getOption

**Comment by pissang** [comment]
需要引入仪表盘组件

**Comment by MilkyWay-MJ** [comment]
谢谢楼上

**Comment by OKennysO** [comment]
我5.5.0也报这个错，图也全部导入了
