### ISSUE TITLE
echarts   legeng分页时的分页数据重复

### ISSUE THREAD

**Issue by sai111** [apache/incubator-echarts#8525]
### One-line summary [问题简述]
 echarts  legend type:scroll  ,出现重复的legend的data,上一页的最后一条数据，会出现在第二页的第一条，点击分页还会出现 分页数和当前页码对不上的问题
看了官网案例，发现有重复的问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts  4.0.4
谷歌浏览器
window10

### Expected behaviour [期望结果]
分页数据不会出现重复

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ink0101** [comment]
也碰到了同样的问题，请问这个bug什么时候可以解决？

**Comment by 100pah** [comment]
This is not a bug.
If do not repeat the last item as the first item of the next page, when the size is not perfect enough to show the last item completely, there is no chance to show it completely.
