### ISSUE TITLE
map,visualMap存在时,如何单独给某个省份设置颜色?

### ISSUE THREAD

**Issue by thinkal01** [apache/incubator-echarts#8526]
### One-line summary [问题简述]
给data单独设置的颜色会被visualMap颜色所覆盖,希望当value为0时,能单独设置颜色#eee,而不使用visualMap的颜色lightskyblue,代码如下:
**visualMap颜色设置**
        visualMap: {// 颜色的设置  dataRange
            left: 'left',
            bottom: '10%',
            min: 0,
            max: 500,
            calculable: true,// 颜色呈条状
            text: ['高', '低'],// 文本，默认为数值文本
            inRange: {
                color: ['lightskyblue', 'yellow', 'orangered']
            }
        },
**给data数据单独设置颜色**
data: [
        {
            name: '北京', value: 0,
            itemStyle: {
                areaColor: '#eee'
            }
        },
        {
            name: '天津', value: 0,
            itemStyle: {
                areaColor: '#eee'
            }
        }
]

**Comment by pissang** [comment]
暂时不行
