### ISSUE TITLE
echart 如何在vue中使用

### ISSUE THREAD

**Issue by zhangfan19970406** [apache/incubator-echarts#8528]
### One-line summary [问题简述]

最近在使用echart想请教一下 这个 在vue项目中应该怎么使用呢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/vue-echarts
