### ISSUE TITLE
微信小程序下的echarts 的异常

### ISSUE THREAD

**Issue by kawaiiz** [apache/incubator-echarts#8530]
### One-line summary [问题简述]
环状图   安卓有的时候中间的圆会添加背景颜色 ，而ios不会（ios显示完美）。
 当前echarts 最新版在小程序上绘图，ios会非常卡顿，和别人讨论，可能是微信更新了基础库为2.1.0  导致， 因为之前用起来非常流程，现在连官方的小程序用iphone打开都卡顿 ，希望能适配一下

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts版本   4.1.0.
微信小程序
ios 与安卓

### Expected behaviour [期望结果]
小程序 ，安卓手机上中间的圆不需要背景颜色， ios能够流畅运行

### ECharts option [ECharts配置项]

```javascript
option = {
 
}

```

### Other comments [其他信息]

![_20180615093820](https://user-images.githubusercontent.com/25151442/41446031-d5787878-707f-11e8-8b2a-77a941e58f95.jpg)

**Comment by pissang** [comment]
谢谢反馈，我们正在跟进卡顿的问题
