### ISSUE TITLE
how to build  Multiple Sub Groups in xAxis?

### ISSUE THREAD

**Issue by ranjithtgandhi** [apache/incubator-echarts#8540]
Reference like Highcharts  : http://blacklabel.github.io/grouped_categories/

**Comment by pissang** [comment]
try http://gallery.echartsjs.com/editor.html?c=xBk7TY_hWx

**Comment by ranjithtgandhi** [comment]
Hi **Yi Shen**

Thank you for your response.
I tried already, Kindly check it the link : http://gallery.echartsjs.com/editor.html?c=xB1SSywwZ7.

Here,  **Month** and **Year** are repeated, not **grouped categories**.
So that, I want the result **grouped categories** like : http://blacklabel.github.io/grouped_categories/ (Highcharts).

Can you help me, how to build grouped categories? Thanks in advance.
