### ISSUE TITLE
echarts保存图片显示模糊，如何解决?数据来源于后台返回的值.

### ISSUE THREAD

**Issue by shanewds** [apache/incubator-echarts#8542]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="js/echarts.js"></script>
</head>
<body>
    
    <div id="main" style="width:500px;height:300px;"></div>
    <script type="text/javascript">
    
     /*   function myrefresh()
        {
        window.location.reload();
        }
        setTimeout('myrefresh()',3000); //指定几秒刷新一次*/

        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
         var option = {
        		    title : {
        		        text: '',
        		        subtext: ''
        		    },
        		    tooltip : {
        		        trigger: 'axis'
        		    },
        		    legend: {
        		        data:['']
        		    },
        		  
        		    toolbox: {
        		        show : true,
        		        feature : {
        		            mark : {show: true},
        		            dataView : {show: true, readOnly: false},
        		            magicType : {show: true, type: [ 'bar']},
        		            restore : {show: true},
        		            saveAsImage : {show: true}
        		        }
        		    },
        		    calculable : true,
        		    xAxis : [
        		        {
        		            type : 'category',
        		            data : ['avg','28日','29日','30日','1日']
        		        }
        		    ],
        		    yAxis : [
        		        {
        		            type : 'value'
        		        }
        		    ],
        		    series : [
        		        {
        		            name:'',
        		            type:'bar',
        		            data:[1520,699,1350,1805,2226],
        		            /* 显示数据到顶端*/
        		            itemStyle: {
        		            	     normal: {
        		            		  lineStyle:{    
        		                            color:'#EB3223'    
        		                      },  
        		            		 
        		                     label: {
        		                         show: true,
        		                         textStyle: {
        		                             fontWeight: 'bolder',
        		                             fontSize: '12',
        		                             fontFamily: '微软雅黑'
        		                         },
        		                         position: 'top'
        		                     },
        		                     color: function (params) {
        		                         var colorList = [
        		                             '#B02318', '#305866', '#305866', '#305866',
        		                             '#305866', '#305866', '#305866', '#305866',
        		                             '#305866', '#305866', '#305866'
        		                         ];
        		                         return colorList[params.dataIndex]
        		                     }
        		                 }
        		            },
        		            markPoint : {
        		                data : [
        		                       
        		                ]
        		            },
        		            markLine : {
        		                data : [
        		                  //{type : 'average', name: ''}
        		                ]
        		            }
        		        }
        		    ]
          };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
</body>
</html>

图片显示如下: 数字显示模糊
  
![echarts](https://user-images.githubusercontent.com/19984920/41580960-7e52a4b2-73cf-11e8-9427-7aaaf10f5a5d.png)

**Comment by pissang** [comment]
没感觉模糊啊...

**Comment by shanewds** [comment]
字体显示模糊啊。 再发两张图片  
@pissang 
这张是截屏的图片
<img width="647" alt="wx20180620-181050 2x" src="https://user-images.githubusercontent.com/19984920/41652430-905cf540-74b5-11e8-9950-94d9b09180ba.png">

下一张是使用自带的按钮进行下载的图片

![echarts 1](https://user-images.githubusercontent.com/19984920/41652447-9dab31bc-74b5-11e8-9562-18150275bd1c.png)

**Comment by shanewds** [comment]
设置分辨率即可解决
    saveAsImage : {
                                 show: true,type: 'png',	            	
 		            	pixelRatio:5
}
