### ISSUE TITLE
折线图堆叠 左侧数据和折线位置不一致，请查看官网实例Demo

### ISSUE THREAD

**Issue by xiongwu1** [apache/incubator-echarts#8552]
### One-line summary [问题简述]

折线图堆叠 纵向的数据和折线图的位置好像不一致啊，单独一条线访问的时候没问题的，好几条折线同时展示的时候就会有这样的问题，如下图所示
![image](https://user-images.githubusercontent.com/15642586/41645286-190962f6-74a3-11e8-8ebe-9e87b1c8faf0.png)

### Version & Environment [查看官网实例]
+ ECharts version [查看官网实例]:
+ Browser version [chrome 67.0.3396.87（正式版本） （64 位）]:
+ OS Version [macOS High sierra 10.13.5]:

### Expected behaviour [期望结果]

期望结果 左侧的数字应该和折线图对应的位置一致

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by thbgh** [comment]
http://echarts.baidu.com/faq.html#line-chart

**Comment by xiongwu1** [comment]
感谢 已经知道了。
