### ISSUE TITLE
如何切换主题

### ISSUE THREAD

**Issue by emloxe** [apache/incubator-echarts#8558]
### One-line summary [问题简述]
主题之间如何切换，有什么方法吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: 谷歌 67.0.3396.87（正式版本）
+ OS Version [操作系统类型和版本]: 微软 win 10

### Expected behaviour [期望结果]
通过方法，进行主题切换

我找到了 init时候可以传入主题，可是初始化后如何进行主题切换

在 http://gallery.echartsjs.com/editor.html?c=xByMbusdiz 中可以看到

![image](https://user-images.githubusercontent.com/15011303/41701832-83807d1e-7560-11e8-899d-d94c2c6e8f9e.png)

是可以直接点击进行主题切换的，可是在文档中没有找到相关的方法

另外有 主题配置相关的文档吗？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by emloxe** [comment]
刚刚发现  http://gallery.echartsjs.com/editor.html?c=xByMbusdiz 中切换主题后整个dom被移除，估计只有初始化的时候才能指定主题。切换主题只有销毁之前的然后重新创建？？

**Comment by pissang** [comment]
只能 dispose 后再重新 init 的时候切换主题
