### ISSUE TITLE
visualMap.pieces的数值设置不能小于0

### ISSUE THREAD

**Issue by wirechen** [apache/incubator-echarts#8566]
### One-line summary [问题简述]
visualMap.pieces中不能设置小于0，否则会四舍五入。如图：
![](https://github.com/wirechen/github-readme/blob/master/img/temp1.png?raw=true)
![](https://github.com/wirechen/github-readme/blob/master/img/temp2.png?raw=true)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.x
+ Browser version [浏览器类型和版本]: Google Chrome 67.0.3396.87
+ OS Version [操作系统类型和版本]: MacOS 10.13.3

### Expected behaviour [期望结果]
visualMap.pieces能支持0以下的小数，并在在分段图中显示出来，如0-0.2、0.2-0.4

### ECharts option [ECharts配置项]

```javascript
option = {
     visualMap: {
            top: 10,
            right: 10,
            pieces: [{
                gt: 0,
                lte: 0.2,
                color: '#096'
            }, {
                gt: 0.2,
                lte: 0.4,
                color: '#ffde33'
            }, {
                gt: 0.4,
                lte: 0.8,
                color: '#ff9933'
            },
            .....
            ],
            outOfRange: {
                color: '#999'
            }
        },
}

```

**Comment by hxyong** [comment]
我也遇到这个问题，有法解决吗，还是可以设置

**Comment by hxyong** [comment]
可以在visualMap里面加precision: 1,表示显示精度

**Comment by wirechen** [comment]
十分感谢！
