### ISSUE TITLE
Mark line 的lebel 文本的方向会改变

### ISSUE THREAD

**Issue by mike-han** [apache/incubator-echarts#8569]
### 问题简述

在下面提供的示例中，默认**mark line** 的**label**是**横向**的（**end**）。
把**label**的**position**由**end**改成**middle**再改成**end**, **mark line label**的方向变成了**纵向**的。

### 版本及环境
+ ECharts version [ECharts 版本]: v4.1.0.rc2
+ Browser version [浏览器类型和版本]: Chrome  67.0.3396.87（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: win10

### 期望结果
当position为end的时候，**mark line label**的方向还是横向的。
或者提供控制文本方向的参数。

### 其他信息
http://gallery.echartsjs.com/editor.html?c=xr1ny2GqZQ&v=1

**Comment by wlmbj** [comment]
碰到同样问题
