### ISSUE TITLE
堆叠柱状图显示数字问题

### ISSUE THREAD

**Issue by wangyahua** [apache/incubator-echarts#8571]
### One-line summary [问题简述]
堆叠柱状图中间显示数字问题，比如数据为100，150，160
但是我想数据不变化  每个柱状图上的数字自定义   自定义为1，2，3

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: win

### Expected behaviour [期望结果]
堆叠柱状图中间显示数字问题，比如数据为100，150，160
但是我想数据不变化  每个柱状图上的数字自定义   自定义为1，2，3

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![qq 20180622160413](https://user-images.githubusercontent.com/20548874/41765191-f0f01258-7635-11e8-8c93-c66578e858a1.png)

**Comment by pissang** [comment]
formatter
