### ISSUE TITLE
三维圆柱

### ISSUE THREAD

**Issue by wudonghua** [apache/incubator-echarts#8573]
### One-line summary [问题简述]
我这个应该是疑问而不是问题,我在Echarts的例子里面没有找到关于三维圆柱体的实例,是没有支持吗?如果支持了,麻烦给我一个示例(我已经找了很多地方了,没有相关的贴子和描述),如果没有支持的话,有没有什么代替方案或者解决方案,急急急.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不支持圆柱的绘制
