### ISSUE TITLE
设置提示框的formatter之后，最前边的类型显示没有了

### ISSUE THREAD

**Issue by PeiWenfeng** [apache/incubator-echarts#8576]
### One-line summary [问题简述]

下面是我没有设置formatter的情况
![image](https://user-images.githubusercontent.com/40558183/41833918-da2b20f2-7884-11e8-8318-0111525fc480.png)

我在设置了formatter之后，最前边显示的颜色的那个框没有了。
```js
tooltip: {
              trigger: 'axis',
              formatter: '{b0}<br />{a0}: {c0}<br />{a1}: {c1}<br />{a2}: {c2}%',
              axisPointer: 
              {
                type: 'cross'
              }
          },
```
![image](https://user-images.githubusercontent.com/40558183/41833897-c58881ee-7884-11e8-99fe-604fb4621157.png)

请问为什么呢？

还有一个问题是，我在加载完Echart之后，摁数据视图，会显示当前的数据，这时候我通过页面上别的按钮重新加载echart，数据视图的数据不会变，请问这个现象是正常的吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wangcongyi** [comment]
#4427 
@PeiWenfeng  提 issue 之前，希望查找下~~
