### ISSUE TITLE
地图比例问题

### ISSUE THREAD

**Issue by datianjiao** [apache/incubator-echarts#8577]
### 请问echarts使用中国geojson生成的地图比例，为什么和百度地图，highchart，d3 等生成的比例不一样呢？

东北明显被压小了，请问哪种才是标准的？百度地图和d3生成的效果一致。偏偏echarts生成的地图不一样

### 截图
Echarts生成的地图
![image](https://user-images.githubusercontent.com/16029014/41835202-56ac8572-7889-11e8-8829-294b0478d31e.png)
百度地图
![image](https://user-images.githubusercontent.com/16029014/41835408-12ab7f3a-788a-11e8-9765-f8c25dbb9945.png)
d3生成的地图
![image](https://user-images.githubusercontent.com/16029014/41835252-854fa8a0-7889-11e8-8f3f-a47cc48fd364.png)

**Comment by pissang** [comment]
这是因为用了不同的投影，echarts 是按经纬度画的，百度地图或者其它的地图服务一般都是用的墨卡托投影
