### ISSUE TITLE
关于bar3d-punch-card三维坐标轴的问题

### ISSUE THREAD

**Issue by HuanziDebuger** [apache/incubator-echarts#8581]
尊敬的echarts开发工程师们，
   我在使用echarts里的bar3d-punch-card这个三维图时，遇到了一个问题，公司产品的需求是希望X,Y,Z三维轴的位置坐下改动，三维轴放到里面，类似于下面这种效果

![image](https://user-images.githubusercontent.com/23313465/41844242-30a5802c-78a2-11e8-876d-d8d0b09bad44.png)

跪求解决办法，谢谢

update:

如果是购买企业付费版的echarts,能否实现这个功能

**Comment by pissang** [comment]
这个暂时没法实现，为了能够更方便的看清坐标轴，现在坐标轴的位置是根据视角动态计算

**Comment by HuanziDebuger** [comment]
那请问如果购买企业付费版的，能实现这个功能吗
