### ISSUE TITLE
请问echarts-liquidfill.js有兼容ie8的方法吗？ 

### ISSUE THREAD

**Issue by joker-xc** [apache/incubator-echarts#8590]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
水球图需要一些 IE8 无法实现的特性，所以无法兼容IE8
