### ISSUE TITLE
关系图 data 的 name 属性不允许重复，会报错。

### ISSUE THREAD

**Issue by xiashuyuan** [apache/incubator-echarts#8597]
### One-line summary [问题简述]

关系图 data 的 name 属性不允许重复，会报错。

前提： 目前关系图节点的 name 属性既是节点展示文本的来源，也是 link 中 source、target 来源之一。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: 69.0.3464.2
+ OS Version [操作系统类型和版本]: 10.13.5 (17F77)

### Expected behaviour [期望结果]
data 中 name 只用来节点名称展示，用另一个属性，例如 id 或 key， 来标记节点唯一性；
links 中source，target 的值用 id(或key)，替代 name 来承接链路关系。

以期满足多个重复名称节点之间的拓扑关系展示。

### ECharts option [ECharts配置项]
http://echarts.baidu.com/examples/editor.html?c=graph-simple
在这个官方示例中把 data 中的某一项 name 改成跟其他项 name 相同

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/17895516/41957538-ddd16fea-7a19-11e8-834c-7cf9394e942b.png)

**Comment by pissang** [comment]
现在就支持用 id 吧

**Comment by xiashuyuan** [comment]
@pissang 现在只支持 name 和 索引，没找到 id。

这是配置项手册里的描述：
series[i]-graph.links[i].source string, number
边的源节点名称的字符串，也支持使用数字表示源节点的索引。

**Comment by xiashuyuan** [comment]
已解决：
1. 保持 data 中name不重复，用 value 或其他字段名称表示要展示的节点名称；
2. 使用 label.formatter 输出节点名称；
3. links 中 source 和 target 用数据项的索引值。

option = {
label:{
                show: true,
                formatter: function(value){
                    return value.data.value;
                }
            },
            data: [{
                // name: '节点1',
                a: '`1',
                value: 10,
                x: 300,
                y: 300,
            }, {
                // name: '节点2',
                value: 20,
                x: 800,
                y: 300
            }, {
                // name: '节点3',
                value: 10,
                x: 550,
                y: 100
            }, {
                // name: '节点4',
                value: 30,
                x: 550,
                y: 500
            }, {
                name: '节点4',
                value: 10,
                x: 550,
                y: 500
            }],
            // links: [],
            links: [{
                source: 0,
                target: 1,
                symbolSize: [5, 20],
                label: {
                    normal: {
                        show: true
                    }
                },
                lineStyle: {
                    normal: {
                        width: 5,
                        curveness: 0.2
                    }
                }
            }],
};

**Comment by singlelonghair** [comment]
如果我的需求是target、source、category只要一个不同就认为是一组需要打印的关系，这个好像echarts还没支持

**Comment by singlelonghair** [comment]
当前我测试出也是target不能出现一样的，即每个节点只能被做为target一次。

**Comment by singlelonghair** [comment]
这个我使用了d3_js，它支持，实际上是需要echarts支持三元关系

**Comment by zhangsenhua** [comment]
```javascript
option = {
    series : [
        {
            type: 'graph',
            layout: 'circular',
            symbolSize: 50,
            roam: true,
            label: {
                show: true,
                position: 'bottom',
                formatter: params => params.data.value
            },
            edgeSymbol: ['none', 'arrow'],
            data: [{
                name: '1',// use id or key
                value: '节点1',// use display name or value
            }, {
                name: '2',
                value: '节点2',
            }, {
                name: '3',
                value: '节点3',
            }, {
                name: '4',
                value: '节点3',
            }],
            links: [{
                source: '1',
                target: '3'
            }, {
                source: '2',
                target: '3'
            }, {
                source: '1',
                target: '4'
            }, {
                source: '2',
                target: '4'
            }],
        }
    ]
};
```
[Demo: 关系图支持相同 name 节点显示](https://gallery.echartsjs.com/editor.html?c=x0793oC44)
@xiashuyuan
