### ISSUE TITLE
我在webpack中按虚引入，legend不显示，请问怎么解决

### ISSUE THREAD

**Issue by renzhao1113** [apache/incubator-echarts#8601]
### One-line summary [问题简述]
如提

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: 最新版谷歌浏览器
+ OS Version [操作系统类型和版本]: win10
webpack版本: 4

### ECharts option [ECharts配置项]

```javascript
option = {
 legend:{
   data:["本周"]
 }
}

```

**Comment by pissang** [comment]
有对应的 series 时 legend 才会显示
