### ISSUE TITLE
svg模式下使用label就出错

### ISSUE THREAD

**Issue by maozhenhua2** [apache/incubator-echarts#8605]
### One-line summary [问题简述]
svg模式下，使用label就出错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.10rc2
+ Browser version [浏览器类型和版本]:chrome 67.0.3396.99（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:win10 64 10.0.17134.112

### Expected behaviour [期望结果]
使用label

### ECharts option [ECharts配置项]

```javascript
option = {"color":["rgb(0, 103, 156)"],"grid":{"x":20,"y":30,"x2":20,"y2":30,"borderColor":"#fff"},"xAxis":{"axisTick":{"show":false},"type":"category","data":["项目标杆值","项目中位值","单店值"]},"yAxis":{"show":false,"type":"value"},"series":[{"type":"bar","label":{"normal":{"show":true,"position":"insideBottom"}},"barWidth":"30%","data":[0.97,0.78,0.84]}]}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/7087532/42010945-ad197ece-7ac3-11e8-8ac2-19135057cbf6.png)
https://codepen.io/maozhenhua/pen/BVGNmb

**Comment by pissang** [comment]
这是这个版本的 bug，新版本已经修复，发布之前建议先用之前的版本
