### ISSUE TITLE
echart配置项求助。

### ISSUE THREAD

**Issue by lxd0130** [apache/incubator-echarts#8608]
### One-line summary [问题简述]
 grid: [
        {x: '7%', y: '7%', width: '38%', height: '38%'},
        {x2: '7%', y: '7%', width: '38%', height: '38%'},
        {x: '7%', y2: '7%', width: '38%', height: '38%'},
        {x2: '7%', y2: '7%', width: '38%', height: '38%'}
    ],
请问一下这中间的x，x2，y，y2分别代表什么意思。我在配置项手册中看到grid可以定义多个，推荐的示例中是这么写的，但是并没有提到x，x2这些

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
x = left, y= top, x2 = right, y2 = bottom

这是 3 之前的写法
