### ISSUE TITLE
使用mapbox3D，数据为map3D系列，鼠标移入图形区就报错

### ISSUE THREAD

**Issue by tuziel** [apache/incubator-echarts#8618]
### One-line summary [问题简述]
1. 版本为`echarts 4`、`echars-gl 1.1.1`
2. mapbox3d下，map3D鼠标移入图形区就报错，同样的代码在`v1.0.0`下正常运行
3. 无论是`v1.1.1`还是`v.1.0.0`都不能配置`itemStyle`的`borderColor`

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4.1.0
+ ECharts-GL version [ECharts-GL 版本]: v1.1.1
+ Browser version [浏览器类型和版本]: chorme 64.0.3282.186
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
1. 鼠标移入图形区显示标签
2. 显示图形区轮廓

### ECharts option [ECharts配置项]
可以直接使用[这个demo](http://gallery.echartsjs.com/editor.html?c=xHJJRIJxN-)
demo版本为`v1.0.0`
demo中改为使用下方option，没有出现轮廓颜色
```javascript
option = {
  visualMap: {
    show: false,
    min: 0.4,
    max: 1,
    inRange: {
      color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
    }
  },
  mapbox: {
    center: [13.409779, 52.520645],
    zoom: 13,
    pitch: 50,
    bearing: -10,
    style: 'mapbox://styles/mapbox/dark-v9',
  },
  series: [{
    type: 'map3D',
    coordinateSystem: 'mapbox',
    map: 'buildings',
    itemStyle: {
      areaColor: '#ff0',
      borderColor: '#f00',
      borderWidth: 1
    },
    data: buildingsGeoJSON.features.map(function (feature) {
      return {
        name: feature.properties.name,
        height: 1
      };
    }),
  }]
}
```

将`mapbox`配置及坐标系配置`coordinateSystem: 'mapbox',`移除，则正常显示轮廓

本地运行时，使用`v1.1.1`，鼠标移入图形区会报错
```
echarts-gl.js:20836
Uncaught TypeError: Cannot read property '0' of undefined
```

### Other comments [其他信息]
echarts配置:
![a2a793236b62de44202b30ccd5993e0.png](https://upload-images.jianshu.io/upload_images/4922748-5d2778c4eee6903b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

`v1.1.1`: 
![7b27449fc4b4950c444a62ca4e11815.png](https://upload-images.jianshu.io/upload_images/4922748-10cc49a733a4c2e6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

`v1.0.0`: 
![d09cd0b39c28b4a99d40ad5e549b597.png](https://upload-images.jianshu.io/upload_images/4922748-ceccc7b8ccbfdf64.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by succulen-plants** [comment]
遇到同样的问题， 而且 不能监听到鼠标点击事件‘
