### ISSUE TITLE
配置项文档的错误

### ISSUE THREAD

**Issue by Rhuaer** [apache/incubator-echarts#8622]
### One-line summary [问题简述]
现在echarts官网上的3.x版本的bar图的配置项文档有问题，在series.itemStyle里面，现在没有了normal属性。导致用户如果按照文档去配置，在3.8.5版本的echarts库会有问题，无法正确显示所需要的颜色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:chrome 66
+ OS Version [操作系统类型和版本]:win 10

### Expected behaviour [期望结果]
修正文档

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar',
        itemStyle:{
//在3.8.5的echarts上无法正确显示蓝色
            color: 'blue'
        }
    }]
}

```

**Comment by pissang** [comment]
itemStyle 下设置 color 是 4 开始的写法，3.x 版本的文档请切换到 http://echarts.baidu.com/option3.html#title

**Comment by Rhuaer** [comment]
上面我没描述清楚，其实上面的代码我是按照3.x的文档写出来的，一图胜千言，请看3.x的官方文档截图：

![image](https://user-images.githubusercontent.com/13702561/42193954-1c88d6f4-7ea4-11e8-9b5d-47047d16d4a5.png)

**Comment by pissang** [comment]
...那应该是文档有问题了

**Comment by pissang** [comment]
确认了问题，我们修复一下，谢谢大家的反馈
