### ISSUE TITLE
柱状图显示越界

### ISSUE THREAD

**Issue by pandaiiz** [apache/incubator-echarts#8647]
### One-line summary [问题简述]
![image](https://user-images.githubusercontent.com/25072780/42300650-0efab970-8044-11e8-8837-70e57bf87bd4.png)
柱状图越界了，如图所示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
什么版本的 echarts？
