### ISSUE TITLE
echarts有配置项可以让图表立刻显示，不显示一个加载的过程

### ISSUE THREAD

**Issue by liuhetongzi** [apache/incubator-echarts#8648]
### One-line summary [问题简述]

使用echarts3 有配置项可以在页面打开的时候让图表立刻展示，而不显示一个图表延伸加载的过程。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
去掉 showLoading 和 hideLoading
