### ISSUE TITLE
echart4.x版本双柱状图在双轴下图显示不正确

### ISSUE THREAD

**Issue by aolieWanyan** [apache/incubator-echarts#8650]
### One-line summary [问题简述]
4.x的版本使用分组柱状图绘制两个柱状图在双Y轴中如果两组数据既有正也有负，第二个柱状图显示不了正确的正负关系。而在3.8.0的版本中是正确的。

### Version & Environment [版本及环境]
+ ECharts version [4.X]:
+ Browser version [chrome V67.0.3396.99]:
+ OS Version [MacOs]:

### Expected behaviour [期望结果]
修复bug

### ECharts option [ECharts配置项]

```javascript
option = {
    "color": ["#EE0000", "#45a7ca"],
    "legend": {
        "data": ["面包", "牛奶"]
    },
    "xAxis": [{
        "type": "category",
        "data": ["2016-01", "2016-02", "2016-03", "2016-04", "2016-05", "2016-06", "2016-07"]
    }],
    "yAxis": [{
        "type": "value",
        "name": "需求增长（%）",
        "axisLabel": {
            "formatter": "{value} %"
        },
        "scale": true
    },{
        "type": "value",
        "name": "需求增长2（%）",
        "axisLabel": {
            "formatter": "{value} %"
        },
        "scale": true
    }],
    "series": [{
        "barWidth": 25,
        "name": "面包",
        "barGap":0,
        "type": "bar",
        "data": [0.05, 0.71, -0.75, 0.05, 0.05, 0.01, 0.02]
    }, {
        "barWidth": 25,
        "name": "牛奶",
        "yAxisIndex":1,
        "type": "bar",
        "data": [-21.04, 2.33, 11.84, 1.91, 0.41, -0.49, 1.59]
    }]
}

```

### Other comments [其他信息]

echarts 4.x
![image](https://user-images.githubusercontent.com/20442955/42301341-444f0380-8047-11e8-91fe-e76d0a235a12.png)
echarts 3.8.0
![image](https://user-images.githubusercontent.com/20442955/42301414-a5fbc280-8047-11e8-80cd-815225883448.png)

**Comment by bigfacewo** [comment]
同样有这个问题，但是官方似乎不搭理这个问题
