### ISSUE TITLE
右键“复制图片”，粘贴出来的图片只有折线了。。

### ISSUE THREAD

**Issue by zfy603206328** [apache/incubator-echarts#8657]
问题简述 (One-line summary)
3.x版本在Chrome右键“复制图片”，粘贴到word中背景是黑色的，刻度标题等等内容全都不见了，只有折线还在。

版本及环境 (Version & Environment)
ECharts 版本 (ECharts version):3.x
浏览器类型和版本 (Browser version):Chrome65
操作系统类型和版本 (OS Version):win7
重现步骤 (Steps to reproduce)
1.图上右键“复制图片”。

期望结果 (Expected behaviour)
粘贴到word中跟导出的图片一样。

其他信息 (Other comments)
Mac上面复制是白色，windows是黑色
http://jsfiddle.net/zhaofy/cj31rtpf/1076/

**Comment by chfw** [comment]
用 snipping tool 截屏

或者 用 echarts 工具栏点击下载
