### ISSUE TITLE
Echarts do not show in https

### ISSUE THREAD

**Issue by xuuxii** [apache/incubator-echarts#8676]
### One-line summary [问题简述]
I have here 2 examples, which show the problem. The First one is http access, echarts displays well. The Second one is https access, all charts/echarts do not show. Anyone know where the problem is?

Link with Http access: http://www.4smartcity.com/datawiki/index.php?clsv=8888&pageid=0&function_id=2&object_id=5

Link with Https access: https://www.4smartcity.com/datawiki/index.php?clsv=8888&pageid=0&function_id=2&object_id=5

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ultcyber** [comment]
Looks like the .js scripts are being loaded from a http resource rather than https which throws a "mixed content" error

![echarts](https://user-images.githubusercontent.com/16682784/42624999-ffc9d200-85c6-11e8-9a1a-aaf0f36cef7e.PNG)

**Comment by xuuxii** [comment]
thank you!

**Comment by chfw** [comment]
try the following link from https://github.com/pyecharts/jupyter-echarts because they are served from https link:

https://pyecharts.github.io/jupyter-echarts/echarts/echarts.min.js
https://pyecharts.github.io/jupyter-echarts/echarts/echarts-gl.min.js
