### ISSUE TITLE
关于bmap手册和geo.map数据问题

### ISSUE THREAD

**Issue by qingming418** [apache/incubator-echarts#8680]
你好！现在用echarts做地图相关功能时，遇到几个问题想请教一下:
1. 在 webpack 中使用 ECharts，通过按需加载模块 例如var echarts = require('echarts/lib/echarts')，没有 bmap的模块，而且在光网的配置项手册没有 bmap的相关配置项，时还没有文档吗？
2. 通过配置 geo.map对应的地图数据时，提示在http://echarts.baidu.com/download-map.html上面下载，但页面好像不支持下载了
![image](https://user-images.githubusercontent.com/20061205/42557717-d8adc942-8521-11e8-8440-d0a90e3da023.png)， 请问还有什么方式可以获取地图数据呢？

**Comment by pissang** [comment]
可以使用 @chfw 贡献的 https://github.com/echarts-maps/echarts-china-cities-js

**Comment by qingming418** [comment]
能够筛选出指定的城市或省的数据吗？
