### ISSUE TITLE
Website does not render Charts anymore

### ISSUE THREAD

**Issue by JonasMedu** [apache/incubator-echarts#8687]
The white spaces where the charts should appear are emtpy.
e.g. [echarts options](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-custom)
or 
[tutorial](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Customized%20Chart%20Styles)

(location germany, browser: chrome, edge, firefox mobil, OS: windows, android)

**Comment by hk-ng** [comment]
It is because the website is using HTTPS while the example in iframe use HTTP.

**Comment by JonasMedu** [comment]
Charts do render again.
