### ISSUE TITLE
3D Surface 是否可以GPU加速

### ISSUE THREAD

**Issue by iamweixiaohang** [apache/incubator-echarts#8688]
### One-line summary [问题简述]

你好，我使用的是tesla K80 gpu，但是绘制3D Surface还是很慢（基本上速度没变化），想问一下是否支持GPU加速？

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

方便的话给3D Surface加上GPU加速配置项。谢谢。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
现在就是 GPU 绘制的，慢可能是因为数据处理，大概多少的数据量？
