### ISSUE TITLE
pie图数值比较大的时候变白色

### ISSUE THREAD

**Issue by zhouxiumin** [apache/incubator-echarts#8689]
### One-line summary [问题简述]

在使用pie图的时候，我发现data里的value数值大于600左右，当前饼图的颜色就变成白色了，和itemStyle里不一致了，这是bug还是设计就是这样的？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4
+ Browser version [浏览器类型和版本]: chrome 最新
+ OS Version [操作系统类型和版本]: windows

### ECharts option [ECharts配置项]

```javascript
option = {
// ......
            data:[
                {value:3000, name:'直接访问'},
                {value:2000, name:'邮件营销'},
                {value:2200, name:'联盟广告'},
                {value:3030, name:'视频广告'},
                {value:1300, name:'搜索引擎'}
            ].sort(function (a, b) { return a.value - b.value; }),
// ......
}

```

**Comment by Ovilia** [comment]
这是写了 visualMap 吧
