### ISSUE TITLE
矩形树图背景底色无法调节（如图）

### ISSUE THREAD

**Issue by DLCJianyf** [apache/incubator-echarts#8690]
如下图
![tim 20180713093928](https://user-images.githubusercontent.com/18675306/42667969-da7085ca-8680-11e8-878b-0d4544f54531.png)

在矩形树图配置参数中没有找到相应的参数来控制背景底色

**Comment by petsgre** [comment]
+1

**Comment by petsgre** [comment]
我修改了zrender的代码。可以把图形的背景色都透明
也可以通过echart传个颜色过来进行拓展
// Path.js  
![image](https://user-images.githubusercontent.com/22208613/44460198-bcc4d700-a63e-11e8-82a6-a1239f6025d5.png)

**Comment by petsgre** [comment]
![image](https://user-images.githubusercontent.com/22208613/44460308-21803180-a63f-11e8-9377-354f634daae0.png)

**Comment by Ovilia** [comment]
配置参数是 http://echarts.baidu.com/option.html#series-treemap.itemStyle.borderColor @petsgre 写死似乎是不对的，用这个配置项应该就可以，有问题再反馈~

**Comment by petsgre** [comment]
@Ovilia borderColor和backgroundColor使用同一个配置项有些不妥吧？

**Comment by DLCJianyf** [comment]
目前的配置我都试过了，背景与层级有关，只有单独一级的话配置不了

**Comment by DLCJianyf** [comment]
代码合并了？ @petsgre

**Comment by DLCJianyf** [comment]
嗯嗯
