### ISSUE TITLE
折线图对brush组件的兼容问题

### ISSUE THREAD

**Issue by haojay5** [apache/incubator-echarts#8699]
### One-line summary [问题简述]
目前版本还不能支持折线图brush组件，这个问题好久之前就有人提出来过，为什么一年多的时间这个问题还是没有处理呢，柱状图都可以支持的，折线图对于这种需求是不是要更合理一些，请问官方人员有计划支持吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: chrome 67.0.3396.99
+ OS Version [操作系统类型和版本]: windows 7

### Expected behaviour [期望结果]
折线图也能支持brush组件选取数据。

### ECharts option [ECharts配置项]

```javascript
option = {
brush: {
			toolbox: ["lineX"],
			xAxisIndex: 0,
			throttleType: "debounce",
			throttleDelay: 0
		},
series: [{
type: "line"
}]
}

```

**Comment by Ovilia** [comment]
#6718 如果有这个需求的人多，会优先支持一下。

**Comment by atomtong** [comment]
强烈需求
