### ISSUE TITLE
功能改进：X轴过长提供截字处理，hover轴标题显示全部内容。

### ISSUE THREAD

**Issue by sdtazhanghe** [apache/incubator-echarts#8703]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/28133347/42793061-e3636328-89aa-11e8-8f31-f945c3455826.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by territoryfan** [comment]
我有做过，看我的 图二效果 ，https://github.com/territoryfan/echarts

**Comment by territoryfan** [comment]
@sdtazhanghe   我有做过，看我的 图二效果 ，https://github.com/territoryfan/echarts
