### ISSUE TITLE
雷达图 radius设置成数组会显示异常

### ISSUE THREAD

**Issue by Xujkstra** [apache/incubator-echarts#8717]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 67.0.3396.99
+ OS Version [操作系统类型和版本]: MAC

将radar.radius 设置成字符串，number或者只有一个值的数组时，都没问题设置成[50, 100]或者[100，50]这种类型的都不能正常渲染，显示如下图

![image](https://user-images.githubusercontent.com/14145818/42873308-4bbf363e-8ab1-11e8-85af-b20ea358998d.png)

**Comment by ensignwy** [comment]
我也遇到了这个问题，
  
文档上写的radius明明类型是string,number类型的，但是还说数组的第一项是内半径，第二项是外半径。这文档有 bug啊

**Comment by ensignwy** [comment]
@pissang @100pah
