### ISSUE TITLE
双轴，右侧Y轴的柱形图如果有负数，右轴的柱状图显示有问题

### ISSUE THREAD

**Issue by victor-deng-github** [apache/incubator-echarts#8727]
### One-line summary [问题简述]
双轴，
左轴含有负数据，柱状图正常。
右轴含有负数据，右轴的柱状图不从0开始，而是从底部开始。
![111](https://user-images.githubusercontent.com/31848023/42938218-1c1785a2-8b84-11e8-8b2c-39b9f24745f5.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.10
+ Browser version [浏览器类型和版本]:chrome、360浏览器
+ OS Version [操作系统类型和版本]:window

### Expected behaviour [期望结果]
右轴含有负数据的时候，右轴的柱状图能和左轴的柱状图一样从0开始。
![222222](https://user-images.githubusercontent.com/31848023/42938284-59e391be-8b84-11e8-96d3-1e1ce1961858.png)

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis : [
        {
            type : 'category',
            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
        }
    ],
    yAxis : [
        {
            name:"利润",
            type : 'value'
        },
        {
            name:"利润率",
            type : 'value'
        }
    ],
    series : [
        {
            name:'利润',
            type:'bar',
            data:[2.0, 4.9, 7.0, -23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
        },
        {
            yAxisIndex:1,
            name:'利润率',
            type:'bar',
            data:[2.6, 5.9, 9.0, -26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
        }
    ]
};

```

### Other comments [其他信息]

正确的：
![222222](https://user-images.githubusercontent.com/31848023/42938284-59e391be-8b84-11e8-96d3-1e1ce1961858.png)

有问题的：
![111](https://user-images.githubusercontent.com/31848023/42938218-1c1785a2-8b84-11e8-8b2c-39b9f24745f5.png)

**Comment by kuky121** [comment]
我目前的临时解决方法是在第二个y轴的series中，加入一个stack。但使用echarts3没有此问题，应该是个bug

**Comment by victor-deng-github** [comment]
@kuky121 我已经回滚到3.8版本了，不过还是非常感谢。
