### ISSUE TITLE
桑基图自适应

### ISSUE THREAD

**Issue by cttin** [apache/incubator-echarts#8741]
### One-line summary [问题简述]
对于数据量不确定大小的桑基图，有的时候数据量过大导致页面混乱，目前的方案是根据节点数据来设置高度，好像不大合理。而且节点文字有的时候会显示不全。

![image](https://user-images.githubusercontent.com/19873549/43063859-c9d58442-8e8f-11e8-860c-3c61aa34b44a.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
对于数据量不确定大小的桑基图，是否能自适应的画桑基图。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by gsl100** [comment]
> ### One-line summary [问题简述]
> 对于数据量不确定大小的桑基图，有的时候数据量过大导致页面混乱，目前的方案是根据节点数据来设置高度，好像不大合理。而且节点文字有的时候会显示不全。
> 
> ![image](https://user-images.githubusercontent.com/19873549/43063859-c9d58442-8e8f-11e8-860c-3c61aa34b44a.png)
> 
> ### Version & Environment [版本及环境]
> * ECharts version [ECharts 版本]: 4.0
> * Browser version [浏览器类型和版本]:
> * OS Version [操作系统类型和版本]:
> 
> ### Expected behaviour [期望结果]
> 对于数据量不确定大小的桑基图，是否能自适应的画桑基图。
> 
> ### ECharts option [ECharts配置项]
> ```js
> option = {
> 
> }
> ```
> 
> ### Other comments [其他信息]

大哥 桑基图自适应高度有什么思路吗
