### ISSUE TITLE
双Y轴双bar图有负数的问题

### ISSUE THREAD

**Issue by kuky121** [apache/incubator-echarts#8747]
### One-line summary [问题简述]
在双Y轴，并且两个图都是bar的情况下，如果第二个Y轴的数据有负数时，画出的柱子不是从0开始，而是从图形底部向上画。目前临时的解决方案是在第二个Y轴数据的series中加入一个stack，让其从0开始积累。使用echarts3没有此问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0.rc2
+ Browser version [浏览器类型和版本]: chrome 67.0.3396.99(32位)
+ OS Version [操作系统类型和版本]:windows 10

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        },
        {
            type : 'value'
        }
    ],
    series : [
        {
            yAxisIndex:0,
            name:'数据1',
            type:'bar',
            data:[10, -52]
        },
        {
            yAxisIndex:1,
            name:'数据2',
            type:'bar',
            data:[10, -52]
        }
    ]
}

```

**Comment by sdtazhanghe** [comment]
遇到了相同的问题，请帮忙看一下

**Comment by Ovilia** [comment]
经定位是 https://github.com/apache/incubator-echarts/commit/1da24731995a41700d9f638a1b26afef5cab2d55#diff-cd2cd80a0b7478193285daebf4d1fc4a 这个 commit 引起的 bug，逻辑有点复杂，辛苦 @100pah 看下~
