### ISSUE TITLE
Gauge chart

### ISSUE THREAD

**Issue by liuxuhan** [apache/incubator-echarts#8748]
### One-line summary [问题简述]
对每个刻度设置不同颜色的时候， 每个颜色之间有缝隙的感觉

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 2.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: windows

### Expected behaviour [期望结果]

可以无缝连接吗

### ECharts option [ECharts配置项]

```javascript
option = {
series
}

```

### Other comments [其他信息]

![capture](https://user-images.githubusercontent.com/9164771/43128799-78eb0198-8f65-11e8-9616-19e127e33d5a.JPG)

**Comment by Ovilia** [comment]
Fixed in https://github.com/apache/incubator-echarts/pull/9195 use `axisLine: { show: false }` to hide.
