### ISSUE TITLE
雷达图刻度可以从外往里设置吗？即最外层是第一，最里面最大~

### ISSUE THREAD

**Issue by Sanbingo** [apache/incubator-echarts#8749]
### One-line summary [问题简述]
雷达图刻度可以从外往里设置吗？即最外层是第一，最里面最大~

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
Echart: V4.0+
+ Browser version [浏览器类型和版本]:
Chrome: V67
+ OS Version [操作系统类型和版本]:
MacOS：10.13.6

### Expected behaviour [期望结果]

雷达图刻度可以支持从外往里设置，即最外层是第一，最里面最大~

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/5332100/43132580-da6a4a6a-8f6e-11e8-89b0-31209031e0c6.png)

**Comment by imoyao** [comment]
你好，看到你关闭这个问题是找到解决方案了还是没有回应啊？因为我也遇到类似的问题了：[echarts 中如何设置雷达图某一项指标值越小越靠近满分？ - SegmentFault 思否](https://segmentfault.com/q/1010000038811846)
