### ISSUE TITLE
Legend图例问题（严重）图例文字自定义问题（设置文字旋转，文字不能旋转）

### ISSUE THREAD

**Issue by daminga** [apache/incubator-echarts#8755]
图例文字自定义，设置文字旋转，文字不能旋转
### One-line summary [问题简述]

legend: {
        orient: 'horizontal',

        left: 'left',
        formatter: function(name){return '{a|'+name+'}'},
        textStyle:{
            rich:{
                a:{
                    
                        rotate:90 ，
                  
                    color: 'red'
                }
            }
        }
    },

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:ALL
+ Browser version [浏览器类型和版本]:ALL
+ OS Version [操作系统类型和版本]:ALL

### Expected behaviour [期望结果]

自定义文字旋转设置后，文字不能旋转。文字和前面的图例不能够随意的改变位置。只有固定的两个位置。期望文字和前面图例可以随意变换位置。

### ECharts option [ECharts配置项]

```javascript
option = {
................................................
    legend: {
        orient: 'horizontal',
        left: 'left',
        formatter: function(name){return '{a|'+name+'}'},
        textStyle:{
            rich:{
                a:{
                        rotate:90 ，
                    color: 'red'
                }
             }
          }
       },
..............................
}

```

**Comment by swwinone** [comment]
我遇到同样问题，不知到有没有解决方案啊？？？

**Comment by Ovilia** [comment]
#8777
