### ISSUE TITLE
tree 怎么开启缩放

### ISSUE THREAD

**Issue by BusyHe** [apache/incubator-echarts#8762]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by BusyHe** [comment]
![image](https://user-images.githubusercontent.com/17348825/43263618-5cbee6a8-9116-11e8-9198-bb1d30bc0ab2.png)

**Comment by BusyHe** [comment]
![image](https://user-images.githubusercontent.com/17348825/43263635-6ef2380c-9116-11e8-8296-c110a77843af.png)

自家写的demo都有问题

**Comment by fengmiaosen** [comment]
+1 按照文档写的设置 roam 为true，不起作用

**Comment by pissang** [comment]
4.2.0-rc.1 支持开启缩放

**Comment by fengmiaosen** [comment]
4.2 正式版何时可以发布

**Comment by screamsyk** [comment]
me too

**Comment by caidaodumogu** [comment]
> 
> 
> 4.2.0-rc.1 支持开启缩放

开启缩放后，再进行一些点击节点操作后，再次点击根节点会出现tree图消失的问题！！！
