### ISSUE TITLE
Display bar chart with thumbnails in yAxis instead of label

### ISSUE THREAD

**Issue by akvaliya** [apache/incubator-echarts#8764]
I am using this library in my project.

I want to display bar chart with thumbnails. I need to display log of banners.

So i will need chart like below just images in axis.

[![enter image description here][3]][3]

  [3]: https://i.stack.imgur.com/yqwBr.png

I am not sure it is possible or not with this library.

If anyone has any ideas then please let me know.

**Comment by luguokong** [comment]
https://echarts.apache.org/tutorial.html#Rich%20Text

**Comment by akvaliya** [comment]
It works only with data without space & some characters(-,_).
Below is my yAxis options 

```
yAxis: {
        type: 'category',
        inverse: true,
        data: ['Full Sunny', 'Cloudy', 'Showers'],
        axisLabel: {
            formatter: function (value) {
                return '{value|' + value + '}  {' + value + '| }';
            },
            margin: 20,
            rich: {
                value: {
                    lineHeight: 30,
                    align: 'center'
                },
                'Full Sunny': {
                    height: 40,
                    align: 'center',
                    backgroundColor: {
                        image: weatherIcons.Sunny
                    }
                },
                'Cloudy': {
                    height: 40,
                    align: 'center',
                    backgroundColor: {
                        image: weatherIcons.Cloudy
                    }
                },
                'Showers': {
                    height: 40,
                    align: 'center',
                    backgroundColor: {
                        image: weatherIcons.Showers
                    }
                }
            }
        }
    }
```

This is result chart


![](https://content.screencast.com/users/Hardik3416/folders/Jing/media/bc1d0420-8295-4124-8af4-7f9b9bbf9aaa/2018-08-02_2040.png)


As you can see images displaying in "Cloudy" & "Showers" (without space). 
But image is not displaying in 'Full Sunny'. 

What am i missing here?

**Comment by Ovilia** [comment]
@akvaliya You're right. `rich` doesn't support space in name. We think it make sense since variable name cannot contain space in JavaScript. 
In which case must you have space in `rich` name?

**Comment by akvaliya** [comment]
Variable can contain space in javascript. In json key-value pair can be like `var temp = {"Full Sunny"  : any_value}`. Any type of string can be key. it can be accessed by `temp["Full Sunny"]`.

I have a data with string with space like i have mentioned in question.

Will this issue be resolved in any release? This is a critical bug.

**Comment by Ovilia** [comment]
@akvaliya How about converting your string to remove these characters? 
Currently, `/\{([a-zA-Z0-9_]+)\|([^}]*)\}/g` is used for detecting the key. We will change it if we find the reason is common need for others. 
Thanks!

**Comment by akvaliya** [comment]
Yes i can remove characters. But what about space?
I have data array of companies name. I can't remove space from company name.  
I want to display company logo with name. How can i achieve this?

**Comment by Ovilia** [comment]
Does `'Company Name {icon|}'` work for you?

**Comment by akvaliya** [comment]
@Ovilia I want to display company name with icon like i displayed in image in question. I need to know formatter for it. Current formatter is not working with company name containing space or any special characters(like dash -).

**Comment by Ovilia** [comment]
See http://www.echartsjs.com/gallery/editor.html?c=treemap-obama around line 135 `params.name`

**Comment by ardey26** [comment]
> See http://www.echartsjs.com/gallery/editor.html?c=treemap-obama around line 135 `params.name`

Is this still open? The provided URL just redirects me to the root
