### ISSUE TITLE
希望官方可以对 DefinitelyTyped (.d.ts) 进行维护

### ISSUE THREAD

**Issue by JonasGao** [apache/incubator-echarts#8767]
提 issue 前，先查了一下老 issue。没有发现有用的内容。
同时，@types 中 echarts 的定义 (https://www.npmjs.com/package/@types/echarts / https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/echarts) 也看了下 committer，好像也不是官方的。所以最终还是来开了 issue。

我的想法是：
1. 现在的 @types/echarts 非官方维护，不一定能保证 99% 可用。如果可以官方维护，则可以同  echarts 
 发布。保证 100%
2. @types/echarts 现在的版本号为 0.0.x，不与 echarts 的版本号同步，体验并不是很好。如果可以官方维护，则可以保证版本同步，体验更好。

**Comment by Ovilia** [comment]
我给 @types/echarts 提了个 PR 同步了现在的 API。
从下个版本起，我们将同步更新 @types/echarts。

关于版本号，我没有看到 DefinitelyTyped 哪里可以写 @types/echarts 的版本，你知道吗？

**Comment by liveangela** [comment]
hi，终于等到官方维护type的消息了，作为echarts和ts的追随者实在感到高兴。
之前在echart4版本发布后PR了一份给@types官方，但是更新频率还是不够。
关于@types/echarts版本控制问题，个人理解目前PR使用@types内部统一版本自增机制，
一般的做法是在index.d.ts文件头部备注一下当前针对哪个版本，如：
```// Type definitions for Echarts.js v4.0.4```

@types和库的版本号不一致，其实还是可以理解的

**Comment by Ovilia** [comment]
@liveangela 懂了，谢谢~
现在 Option 部分的类型还不太高级，只是个 `Object`，但要是细些的话工作量有点大得惊人，而且目前没有觉得特别有必要，所以暂时准备就这样了。
而接口的更新一般不是很频繁，频繁变动的往往是 Option。后面发版我会尽量记得去 @types 更新的~
