### ISSUE TITLE
为什么使用echart出现很多get undefined错误？

### ISSUE THREAD

**Issue by zhangmengyi** [apache/incubator-echarts#8771]
### One-line summary [问题简述]
页面经常出现很多get undefined错误？

![image](https://user-images.githubusercontent.com/30336413/43313323-504070b6-91c2-11e8-9112-2d9c4032862c.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  
     "echarts": "^4.1.0",
    "echarts-for-react": "^2.0.13",
+ Browser version [浏览器类型和版本]:谷歌最新版
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
不确定出现问题的原因，猜测是在渲染图表完成前，改动了浏览器窗口导致的。希望能解决这个问题。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
方便提供下 option 内容么？方便定位问题。

**Comment by zhangmengyi** [comment]
您好，感谢你的回复。这有个新的issue地址：https://github.com/apache/incubator-echarts/issues/8723 <https://github.com/apache/incubator-echarts/issues/8723> 更详细描述了这个问题 也有option。期待您的回复~
