### ISSUE TITLE
How do I draw 100% stacked column/bar chart ? 

### ISSUE THREAD

**Issue by vadasambar** [apache/incubator-echarts#8785]
I can't seem to find an option to make the height of all stacked y axis bars 100%.  

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0.rc2
+ Browser version [浏览器类型和版本]: Chrome 67.0.3396.99
+ OS Version [操作系统类型和版本]: macOS High Sierra 10.13.3

### Expected behavior

This is what I want: 
![image](https://user-images.githubusercontent.com/34534103/43444232-e0d68344-94c0-11e8-99cd-e29831590a45.png)

This is what I am getting now:
![echarts demo 1](https://user-images.githubusercontent.com/34534103/43444302-090ed2ee-94c1-11e8-8297-e260a6f63d47.png)

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: 'Lorem Ipsum',
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        }
    },
    legend: {
        data: ['2018', '2019']
    },
    xAxis: {
        data: ['Foo','Bar','Baz'],

    },
    yAxis: {
        // type: 'category',
    },
    series: [
        {
            name: '2018',
            type: 'bar',
            data: [18203, 23489, 29034],
            markLine: {
                data: [{
                        name: 'Maximum',
                        type: 'max',
                    },
                    {
                        name: 'Minimum',
                        type: 'min',
                    }
                ]
            },
            stack: '1',
        },
        {
            name: '2019',
            type: 'bar',
            data: [ 10497, 13174, 63023],
            markLine: {
                data: [{
                        name: 'Maximum',
                        type: 'max',
                    },
                    {
                        name: 'Minimum',
                        type: 'min',
                    }
                ]
            },
            stack: '1'
        }
    ]
};
```

**Comment by Ovilia** [comment]
I believe you need to calculate the data into percentage by yourself and pass data like: `[0.2, 0.3]` for the first series, and `[0.8, 0.7]` for the second series.

**Comment by vadasambar** [comment]
@Ovilia , that's what I ended up doing. I converted the data into percentages and passed it to echarts. Thank you!

**Comment by theshashiverma** [comment]
@vadasambar hi, how did you convert the data?

**Comment by theshashiverma** [comment]
@Ovilia

**Comment by karchingla** [comment]
Can you post an example or snippet of code which shows what you did?

**Comment by LeoDiep** [comment]
This is a very good feature, we use this a lot in Excel. Please add it
