### ISSUE TITLE
X轴刻度间距离无法获取

### ISSUE THREAD

**Issue by lixianyang1987** [apache/incubator-echarts#8794]
### One-line summary [问题简述]
你好，我是一个新人，我想了解X轴两个刻度间的距离怎么获取到，或者是X轴的整体长度是多少，我在官网上找了好久了，一直没有解决，希望百忙之中，您们可以帮帮我

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
好像没有接口直接得到这个值，请问使用场景是怎么样的？

**Comment by sunzongzheng** [comment]
@Ovilia 我这里的场景是：判断`label宽度`超过`刻度间距`后则倾斜或者省略号，我现在只能写死阈值来处理
