### ISSUE TITLE
Consider mark line while calculating axis range

### ISSUE THREAD

**Issue by amittonge** [apache/incubator-echarts#8796]
### One-line summary [问题简述]
Currently axis scale is calculated on the basic of series data. Please consider following case where mark line is not visible if its value greater than axis scale.
There are number of use cases where mark line value is greater than series data max.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

If markline value is grater than series data max then axis scale should extend to mark line value so that it get shown on chart. We can do this by setting axis max but then setiing axis  'scale' to true does not take effect. 

### ECharts option [ECharts配置项]

```javascript
option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220],
            
            markLine: {
                data: [{
                    name:"Targeted Profit",
                    yAxis:450
                }]
            }
        }
    ]
};

```

### Other comments [其他信息]

![markline](https://user-images.githubusercontent.com/11725750/43517485-84823016-95a6-11e8-9cce-0fd618a5e7c6.png)

**Comment by Ovilia** [comment]
Thanks @amittonge . It's true that axis range will not automatically change due to markline data. I believe this makes sense since *markline* is served as a *mark* rather than data. And if the related data is not in the range, the markline is designed to be hidden.
We recommend you set max to the data value related to the markline you want to display.

**Comment by amittonge** [comment]
@Ovilia Thanks for reply. I have already mentioned the workaround in the issue which you have recommended to me but  if we set max value to axis then setting axis 'scale' to true/false does not take effect.

**Comment by Ovilia** [comment]
It is available only in numerical axis, so category won't work.
