### ISSUE TITLE
Is it possible to create an EEG chart?

### ISSUE THREAD

**Issue by warpgate3** [apache/incubator-echarts#8797]
First of all, thank you for providing these libraries.
Is it possible to create an EEG chart?

It's on one x-axis (TIME SERIRES)
Multiple y-axes with different ranges are indicated.

Thank you

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
See this example: http://gallery.echartsjs.com/editor.html?c=xrkeZYLl6G
