### ISSUE TITLE
lines类型图期望

### ISSUE THREAD

**Issue by node-rookie** [apache/incubator-echarts#8801]
### One-line summary [问题简述]

Echart能不能画出如下图所示的效果，现在的lines类型的图好像只能画直线或者曲线

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/7260662/43574306-69a2445e-9676-11e8-892a-4f0d78778275.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
有弧线，但效果跟上面的略有不同，参见 http://www.echartsjs.com/gallery/editor.html?c=geo-lines 文档有点 bug，应该是 lineStyle.curveness

**Comment by node-rookie** [comment]
那lines类型的曲线  能不能像tree类型的那样画类似s形的曲线 而不是简单的加个弯曲度，而且好像lines类型的曲线都是顺时针弯曲

**Comment by Ovilia** [comment]
不行哦
