### ISSUE TITLE
佛山市下所有区的地图资源

### ISSUE THREAD

**Issue by WQMDC** [apache/incubator-echarts#8805]
### One-line summary [问题简述]
有谁提供一下佛山市下面所有区的一个地图资源，js或者Json~感激不尽！！！没有搜到相关的资源包。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
https://github.com/echarts-maps/echarts-china-cities-js 相关问题请到这个项目中提问
