### ISSUE TITLE
Doughnut question

### ISSUE THREAD

**Issue by abdelwahed-mohamed** [apache/incubator-echarts#8808]
### One-line summary [问题简述]
i want to show a percent label on every doughnut arc and then when i hover an arc i show extended label in the center of the chart.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: chrome 68
+ OS Version [操作系统类型和版本]: windows 10

**Comment by Ovilia** [comment]
Currently we don't support changing position when hover. See this example: http://www.echartsjs.com/gallery/editor.html?c=pie-doughnut
One ad hoc method could be, with the above example, add another doughnut chart with transparent color and the same data, which is only used for label.

**Comment by abdelwahed-mohamed** [comment]
@Ovilia Thank you very much it works , nice little hack.
