### ISSUE TITLE
bar3D one color for each step yAxis3D

### ISSUE THREAD

**Issue by aandrieux** [apache/incubator-echarts#8809]
### One-line summary [问题简述]
bar3D one color by step yAxis3D

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0.rc2
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: None

### Expected behaviour [期望结果]
Starting from this example : https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar3d-punch-card&gl=1

I would like a different bar color for each of the Y-axis lines and therefore all the bars on the same Y-line have the same color

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {},
    visualMap: {
        max: 20,
        inRange: {
            color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
        }
    },
    xAxis3D: {
        type: 'category',
        data: hours
    },
    yAxis3D: {
        type: 'category',
        data: days
    },
    zAxis3D: {
        type: 'value'
    },
    grid3D: {
        boxWidth: 200,
        boxDepth: 80,
        viewControl: {
            // projection: 'orthographic'
        },
        
    },
    series: [{
        type: 'bar3D',
        data: data.map(function (item) {
            return {
                value: [item[1], item[0], item[2]],
            }
        }),
        shading: 'lambert',

        label: {
            textStyle: {
                fontSize: 16,
                borderWidth: 1
            }
        },

        
    }]
}
```

### Other comments [其他信息]

https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar3d-punch-card&gl=1

**Comment by Ovilia** [comment]
Please ask in https://github.com/ecomfe/echarts-gl
