### ISSUE TITLE
如何实现y轴隐藏x轴数据可动态修改 y轴单位不统一

### ISSUE THREAD

**Issue by gaotianshuang** [apache/incubator-echarts#8812]
### One-line summary [问题简述]
如何实现y轴隐藏，x轴数据可动态修改，且 y轴单位不统一的折线图

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

最新版

### Expected behaviour [期望结果]

实现效果

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
通过 [yAxis.show](http://echarts.baidu.com/option.html#yAxis.show) 设为 false 实现隐藏 y 轴。
x 轴数据可动态修改，重新 setOption 即可。
y 轴单位不统一是想怎么显示？这里有几个例子：http://gallery.echartsjs.com/editor.html?c=xrkeZYLl6G http://gallery.echartsjs.com/editor.html?c=xrySKpOnjM http://gallery.echartsjs.com/editor.html?c=xH1bfMkauM

**Comment by gaotianshuang** [comment]
就是类似一个x轴 可以实现多个y轴吗 @@Ovilia

**Comment by Ovilia** [comment]
是啊，看我给的例子
