### ISSUE TITLE
折线图的Y轴坐标当刻度值超过5位数之后就会裁剪掉数字

### ISSUE THREAD

**Issue by KellenHu** [apache/incubator-echarts#8813]
### One-line summary [问题简述]

折线图的Y轴坐标当刻度值超过5位数之后就会裁剪掉数字
需求：
由于统计数额比较大，所以刻度有可能会出现6位，7位数
但是竖坐标就会裁剪掉多余的位

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
怎么调整才能完全展示看到我要的刻度值，不通过将大值整除1K折算显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以通过 http://echarts.baidu.com/option.html#grid.left 调整画布位置，比如将这个值设得大一点，坐标轴空间就大一点，就能显示更多位数了
