### ISSUE TITLE
4.1.0 release files have old time stamp?

### ISSUE THREAD

**Issue by pchaganti** [apache/incubator-echarts#8816]
### One-line summary [问题简述]
Downloading the latest 4.1.0 release from github, all the files have a time stamp of May 21, 2018? The release was done today right? 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Hi, did you download ECharts through https://github.com/apache/incubator-echarts/releases/tag/4.1.0-release ? This is the latest release. Please feel free to use it. Thanks!

**Comment by pchaganti** [comment]
Yes. That release download has all files with a timestamp of May 21, 2018.

**Comment by pchaganti** [comment]
Screenshot of the files in the downloaded release

![screen_shot_2018-08-05_at_6_41_23_am](https://user-images.githubusercontent.com/6500/43685107-c9df3cfe-987a-11e8-8af8-c49538d48a1d.jpg)

**Comment by pchaganti** [comment]
Yes. that was the release I downloaded. Screenshot ..
![screen_shot_2018-08-05_at_6_41_23_am](https://user-images.githubusercontent.com/6500/43685153-85eefc9a-987b-11e8-8faf-025890ac04cb.jpg)

**Comment by Ovilia** [comment]
Did you download the zip file? I believe the timestamp should be the uncompress time... 😕

**Comment by pchaganti** [comment]
Both the zip and the tarball are doing this with the same May21 timestamp on all files and folders within.

**Comment by Ovilia** [comment]
This is because we have a long release process to go since we joined Apache. Anyway, the files you downloaded is for sure the latest release. Feel free to use it. Thanks!
