### ISSUE TITLE
如何改变sankey的文字颜色

### ISSUE THREAD

**Issue by siguang1983** [apache/incubator-echarts#8818]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/9248645/43702267-d5e7b8ca-998b-11e8-90b5-32ba6905591a.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by LptCai** [comment]
http://www.echartsjs.com/option.html#series-sankey.label
更改Label的配置项
