### ISSUE TITLE
请问数据加载前如何实现背景气泡动画

### ISSUE THREAD

**Issue by EDOaide** [apache/incubator-echarts#8822]
上网查阅资料发现是echarts2的特性，无数据以及满数据时即可实现气泡动画。
但是我已经引用了echarts3的js，而echarts2却不是一个js而是一大堆文件不知道如何引用，望告知！
或者希望能有更好的解决方法，感激不尽！

**Comment by Ovilia** [comment]
ECharts 现在不支持这一效果，但是数据加载动画还是有的，效果不太一样，参见：https://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0
