### ISSUE TITLE
echart 3.x 版本图片的title 字体颜色不能修改

### ISSUE THREAD

**Issue by qibingshen** [apache/incubator-echarts#8824]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### option ={
 title: {
  text: '测试',
  textStyle: {
    color: "#e34c26"
  }
 }
}

### 期望标题改变颜色

**Comment by Ovilia** [comment]
测试过 4.1.0 版本没问题（虽然我觉得 3.x 应该也不会有这个问题），更新代码试下吧，不行的话在 http://gallery.echartsjs.com/editor.html 复现一下

**Comment by qibingshen** [comment]
我把官网的例子下了下来也好了就 但是放在自己的项目里面就不能改够生效了，单纯什么都没有引用，可能影响字体颜色的属性有些什么，我尝试了一天删除了一些地图的插件也不能够生效，头疼纠结中
