### ISSUE TITLE
如何让折线图渐变色的效果中，线条渐变色按照指定的维度值变化？

### ISSUE THREAD

**Issue by overrei** [apache/incubator-echarts#8826]
### One-line summary [问题简述]
折线图使用visualMap可以实现渐变色效果。但是我的需求是渐变色是按照指定维度值进行改变的，和直线本身的值的维度无关。这种业务我配置出来后，发现折线的点可以按照指定维度进行颜色渐变，但是折线本身并没有进行变化。请问应该怎么配置？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]:chrome 68.0.3440.84
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]

折线本身也可以按照指定的维度值进行颜色渐变。
相当于折线的走向和折线的颜色是无关的，可以体现两个维度的值变化

### ECharts option [ECharts配置项]

```javascript
option = {
 "xAxis": [{
        "type": "category",
        "data": ["2014年10月30日", "2015年12月18日", "2015年12月21日", "2016年1月26日", "2016年2月24日", "2016年3月02日", "2016年3月04日", "2016年3月07日", "2016年3月15日", "2016年3月17日", "2016年3月30日"]
    }],
    "yAxis": [{
        "type": "value",
    }],
     "tooltip": {
        "trigger": "axis",
        formatter:'{b0}<br />numZH:  {c0}'
    },
    "series": [{
        "name": "numZH",
        "type": "line",
        "encode": {
            "x": 1,
            y:0
        },
        "symbolSize": 10, 
        lineStyle:{
            color:"#ddd"
        }
    }],
    "visualMap": {
        "show": false,
        "min": 7.7,
        "max": 760.2,
        "calculable": true,
        "inRange": {
            "color": ["rgb(215, 218, 245)", "rgb(17,40,248)"]
        },
        "type": "continuous",
        "dimension": 2
    },
    "dataset": {
        "source": [
            ["", "", ""],
            ["111", "2014年10月30日", "222.0"],
            ["711", "2015年12月18日", "160.2"],
            ["200", "2015年12月21日", "500"], 
            ["306", "2016年1月26日", "700"],
            ["200", "2016年2月24日", "500"], 
            ["200", "2016年3月02日", "120"], 
            ["6", "2016年3月04日", "707"], 
            ["700", "2016年3月07日", "200"], 
            ["605", "2016年3月15日", "180"], 
            ["326", "2016年3月17日", "210"],
            ["150", "2016年3月30日", "360"]
        ]
    }
}

```

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html?c=xByOl2q_tg

**Comment by overrei** [comment]
你好，你发的demo我看了下，和我这边的需求不太一样，我这边想要实现的是，颜色和折线走向无关的业务。
相当于数据是多维的。第一个维度表示的是折线走向，第二个维度是名称，第三个维度才是代表渐变色的维度值。折线走向高的不一定代表颜色深，颜色深浅是由第三个维度表示的。

**Comment by Ovilia** [comment]
那好像没有很好的办法支持，除非自己计算出颜色，然后传入渐变色？

**Comment by overrei** [comment]
谢谢你。
没有这个功能的话那我这边暂时用灰色来表示线条颜色吧，折线上的标记点本身颜色是没问题的。

还有就是我想提个小建议。
在visualMap这个配置里面的dimension配置项可以传入字符串的key值，然后在series的data里面使用key，value的键值对数据，这样通过key来进行查找。不一定非要用数组下标，这样在配置的时候会更灵活一些。

还有我刚才在做pie的渐变色效果时发现一个不知道是不是bug的问题。原理和我上面的折线图一样，pie在使用其他数据来体现渐变色效果时，如果这个数据不是series里面data的value中数据，legend的颜色是没有渐变效果的。


其实以上几个问题都是源于渐变颜色和图表本身数据不一致的情况下才会出现的。因为在一个图表使用渐变色的情况下，虽然有业务是渐变色本身和图表数据是对应的。但同时有很多业务场景是用颜色表示其他维度的数据。

谢谢解惑
