### ISSUE TITLE
sankey图 focusNodeAdjacency参数没有效果

### ISSUE THREAD

**Issue by wisdomsuper** [apache/incubator-echarts#8827]
### One-line summary [问题简述]

sankey图 focusNodeAdjacency参数没有效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

移动到节点上有高亮显示

### ECharts option [ECharts配置项]

```javascript
option = {
        title: {
            text: 'Sankey Diagram'
        },
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'

        },
        series: [
            {
                type: 'sankey',
                layout:'none',
                focusNodeAdjacency :true,
                data: data.nodes,
                links: data.links,
                itemStyle: {
                    normal: {
                        borderWidth: 1,
                        borderColor: '#aaa'
                    }
                },
                lineStyle: {
                    normal: {
                        curveness: 0.5
                    }
                }
            }
        ]
    }

```

**Comment by deqingli** [comment]
您好，之前不支持直接设为 true，只支持 `inEdges`, `outEdges`, `allEdges` 这三个值。现在可以支持直接设为 `true`，等同于 `allEdges`.

**Comment by deqingli** [comment]
您好，之前不支持直接设为 true，只支持 `inEdges`, `outEdges`, `allEdges` 这三个值。现在可以支持直接设为 `true`，等同于 `allEdges`.

**Comment by deqingli** [comment]
您好，之前不支持直接设为 true，只支持 `inEdges`, `outEdges`, `allEdges` 这三个值。现在可以支持直接设为 `true`，等同于 `allEdges`.

**Comment by deqingli** [comment]
您好，之前不支持直接设为 true，只支持 `inEdges`, `outEdges`, `allEdges` 这三个值。现在可以支持直接设为 `true`，等同于 `allEdges`.

**Comment by deqingli** [comment]
您好，之前不支持直接设为 true，只支持 `inEdges`, `outEdges`, `allEdges` 这三个值。现在可以支持直接设为 `true`，等同于 `allEdges`.

**Comment by deqingli** [comment]
您好，之前不支持直接设为 true，只支持 `inEdges`, `outEdges`, `allEdges` 这三个值。现在可以支持直接设为 `true`，等同于 `allEdges`.

**Comment by deqingli** [comment]
http://localhost:8067/incubator-echarts/test/sankey-nodeAlign-left.html
