### ISSUE TITLE
title中rich该如何应用

### ISSUE THREAD

**Issue by DeveloperCharles** [apache/incubator-echarts#8828]
title中rich该如何应用 官网文档没有

![image](https://user-images.githubusercontent.com/34536912/43757402-43cc5746-9a4b-11e8-8e5c-ab7a020ec214.png)

官网中title下rich示例放的是label示例

title中既没有formatter 也没有 label

希望文档能定期维护 并在配置项贴上对应示例代码 （不要把label的示例贴到title处）

**Comment by Ovilia** [comment]
title 里 rich 的写法和 label 里的 rich 部分是一样的。文档会再改进下，谢谢。
