### ISSUE TITLE
normal配置项该如何使用

### ISSUE THREAD

**Issue by DeveloperCharles** [apache/incubator-echarts#8829]
title中rich该如何应用 官网文档未给出说明

在官网实例中见到normal多次

![image](https://user-images.githubusercontent.com/34536912/43757781-8a6b4ddc-9a4c-11e8-9b77-3b92c261db30.png)
（此为官网实例 折线图中的Rainfall实例）

但在官网配置项中未见此配置说明 

normal可以在哪些配置项下层使用？

与emphasis可否结对使用？

希望文档能够详细说明

**Comment by Ovilia** [comment]
normal 是 ECharts 3.x 版本的遗留产物，4.0 做了兼容，新写的代码建议按现在文档的格式，不需要写 normal
