### ISSUE TITLE
什么时候echarts考虑使用WebAssembly

### ISSUE THREAD

**Issue by mafa1993** [apache/incubator-echarts#8835]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
是要解决什么问题？

**Comment by mafa1993** [comment]
数据量较大的情况下渲染较慢, 使用gl相关组件时, 并没有那么流畅, 如缩放操作等

**Comment by mafa1993** [comment]
数据量较大的情况下渲染较慢, 使用gl相关组件时, 并没有那么流畅, 如缩放操作等

**Comment by Ovilia** [comment]
暂时没有计划引入
