### ISSUE TITLE
怎么做出excel的效果？

### ISSUE THREAD

**Issue by mkoijncool** [apache/incubator-echarts#8836]
效果直接上图把（实现x轴多维，图表附带表格数据）

![1](https://user-images.githubusercontent.com/32202152/43830140-33483906-9b33-11e8-8e2b-2353fcde038f.png)

### Version & Environment [版本及环境]
+ ECharts version 4.0
+ Browser version chrome60+ 64bit
+ OS Version windows 7

**Comment by Ovilia** [comment]
表格：http://gallery.echartsjs.com/editor.html?c=xHJqznUm2f
维度1维度2那里似乎没想到什么直接的实现方式，可能数据还是按维度1放，维度2只能作为表格显示用？

**Comment by mkoijncool** [comment]
@Ovilia 

 如果表格可以设置边框就可以达到预期效果了，这个可以做到吗？（title这么用也是666）

**Comment by Ovilia** [comment]
可以的，改下 getTableLine 部分

**Comment by mkoijncool** [comment]
@Ovilia 不太熟这个，搞了半天没弄好，方便帮我看看怎么改吗，多谢
