### ISSUE TITLE
希望提供 legend的反选按钮

### ISSUE THREAD

**Issue by huntergd** [apache/incubator-echarts#8837]
### One-line summary [问题简述]
我的lengend很多，大于10个，我想看到某一个legend，目前的做法，是先把不想看的逐个点，灰掉，才能看到我想看那个，需要操作10多步。希望提供全反选，一键灰 掉所有legend，然后选择想看按个，减少到2步完成。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4
+ Browser version [浏览器类型和版本]:chrome 最新版
+ OS Version [操作系统类型和版本]:win10

**Comment by Ovilia** [comment]
目前界面上有点不好放按钮，有看到过类似的设计吗？自己倒是可以在外面增加一个按钮控制全选全灰，然后调用 http://echarts.baidu.com/api.html#action.legend

**Comment by PikachuHy** [comment]
樓上正解
```
        const legends = this.data.columns
        for (let i = 1; i < legends.length; i++) {
          this.echart.dispatchAction({
            type: 'legendToggleSelect',
            // 图例名称
            name: legends[i]
          })
        }
```

**Comment by jiaqizhang77** [comment]
> 樓上正解
> 
> ```
>         const legends = this.data.columns
>         for (let i = 1; i < legends.length; i++) {
>           this.echart.dispatchAction({
>             type: 'legendToggleSelect',
>             // 图例名称
>             name: legends[i]
>           })
>         }
> ```
请问 this.data.columns 怎么获取到？
