### ISSUE TITLE
给折线图添加背景图片

### ISSUE THREAD

**Issue by Carolineliu** [apache/incubator-echarts#8839]
### One-line summary [问题简述]
给折线图添加背景图片，图片不能撑满echarts容器

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
图片能变大撑满容器

### ECharts option [ECharts配置项]

```javascript

var fullImage = new Image(width,height)
fullImage.src =url //不是base64
       
option = {
backgroundColor：{
  image: fullImage，
  repeat：‘no-repeat’
}
}

```

**Comment by Ovilia** [comment]
最简单的方式是通过 HTML 里加…… 用 ECharts 加的话 http://echarts.baidu.com/option.html#graphic.elements-image.type

**Comment by Ovilia** [comment]
这个是图片受污染（可能因为来自跨域？）画上去以后导出的 canvas 就会报这个错，你搜一下 canvas 的相关解决方案吧
