### ISSUE TITLE
如何让axisPointer展示的label锁定的位置在折线图的线上

### ISSUE THREAD

**Issue by smallpit** [apache/incubator-echarts#8842]
### One-line summary [问题简述]
value形的数据，折线图，step: 'middle', x轴设置的axisPointer的snap为false，y轴的axisPointer的snap为true,y轴展示数据根据鼠标最接近y轴坐标贴合了，如图，
![image](https://user-images.githubusercontent.com/19749283/43885906-cf50e208-9bec-11e8-84e5-149c58390bbc.png)
，如何让y轴贴合的值也根据X轴判断，或者有没有哪个配置项设置展示xy轴值为图形上线的点坐标呢？

**Comment by Ovilia** [comment]
同 #7651 ，目前还不支持，请关注那个 issue

**Comment by smallpit** [comment]
好的 谢谢
