### ISSUE TITLE
vue2.x echarts..getModel().getComponent('bmap')报错

### ISSUE THREAD

**Issue by deluo** [apache/incubator-echarts#8846]
### One-line summary [问题简述]
使用vue2.5.2 在map组件中代码如下
 mounted() {
    var myMap = echarts.init(document.getElementById("main"));
    myMap.setOption({
      bmap: {
        center: [120.13066322374, 30.240018034923],
        zoom: 14,
        roam: true,
        mapStyle: {
          styleJson: [
            {
              featureType: "land", //调整土地颜色
              elementType: "geometry",
              stylers: {
                color: "#081734"
              }
            },
            {
              featureType: "building", //调整建筑物颜色
              elementType: "geometry",
              stylers: {
                color: "#04406F"
              }
            },
            {
              featureType: "building", //调整建筑物标签是否可视
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "highway", //调整高速道路颜色
              elementType: "geometry",
              stylers: {
                color: "#015B99"
              }
            },
            {
              featureType: "highway", //调整高速名字是否可视
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "arterial", //调整一些干道颜色
              elementType: "geometry",
              stylers: {
                color: "#003051"
              }
            },
            {
              featureType: "arterial",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "green",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "water",
              elementType: "geometry",
              stylers: {
                color: "#044161"
              }
            },
            {
              featureType: "subway", //调整地铁颜色
              elementType: "geometry.stroke",
              stylers: {
                color: "#003051"
              }
            },
            {
              featureType: "subway",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "railway",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "railway",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "all", //调整所有的标签的边缘颜色
              elementType: "labels.text.stroke",
              stylers: {
                color: "#313131"
              }
            },
            {
              featureType: "all", //调整所有标签的填充颜色
              elementType: "labels.text.fill",
              stylers: {
                color: "#FFFFFF"
              }
            },
            {
              featureType: "manmade",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "manmade",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "local",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "local",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "subway",
              elementType: "geometry",
              stylers: {
                lightness: -65
              }
            },
            {
              featureType: "railway",
              elementType: "all",
              stylers: {
                lightness: -40
              }
            },
            {
              featureType: "boundary",
              elementType: "geometry",
              stylers: {
                color: "#8b8787",
                weight: "1",
                lightness: -29
              }
            }
          ]
        }
      },
      series: [
        {
          type: "scatter",
          coordinateSystem: "bmap",
          data: [[120, 30, 1]]
        }
      ]
    });
    console.log(myMap.getModel());
    var bmap = myMap
      .getModel()
      .getComponent('bmap')
      .getBMap();

    bmap.addControl(new BMap.MapTypeControl());
  } 

报错:Error in mounted hook: "TypeError: Cannot read property 'getBMap' of undefined";
Cannot read property 'getBMap' of undefined;

不使用vue.仅仅在html中使用相同的代码,不会报错,并且显示效果正常

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:68.0  64位
+ OS Version [操作系统类型和版本]:win10 64位

### ECharts option [ECharts配置项]

```javascript
option ={
      bmap: {
        center: [120.13066322374, 30.240018034923],
        zoom: 14,
        roam: true,
        mapStyle: {
          styleJson: [
            {
              featureType: "land", //调整土地颜色
              elementType: "geometry",
              stylers: {
                color: "#081734"
              }
            },
            {
              featureType: "building", //调整建筑物颜色
              elementType: "geometry",
              stylers: {
                color: "#04406F"
              }
            },
            {
              featureType: "building", //调整建筑物标签是否可视
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "highway", //调整高速道路颜色
              elementType: "geometry",
              stylers: {
                color: "#015B99"
              }
            },
            {
              featureType: "highway", //调整高速名字是否可视
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "arterial", //调整一些干道颜色
              elementType: "geometry",
              stylers: {
                color: "#003051"
              }
            },
            {
              featureType: "arterial",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "green",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "water",
              elementType: "geometry",
              stylers: {
                color: "#044161"
              }
            },
            {
              featureType: "subway", //调整地铁颜色
              elementType: "geometry.stroke",
              stylers: {
                color: "#003051"
              }
            },
            {
              featureType: "subway",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "railway",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "railway",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "all", //调整所有的标签的边缘颜色
              elementType: "labels.text.stroke",
              stylers: {
                color: "#313131"
              }
            },
            {
              featureType: "all", //调整所有标签的填充颜色
              elementType: "labels.text.fill",
              stylers: {
                color: "#FFFFFF"
              }
            },
            {
              featureType: "manmade",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "manmade",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "local",
              elementType: "geometry",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "local",
              elementType: "labels",
              stylers: {
                visibility: "off"
              }
            },
            {
              featureType: "subway",
              elementType: "geometry",
              stylers: {
                lightness: -65
              }
            },
            {
              featureType: "railway",
              elementType: "all",
              stylers: {
                lightness: -40
              }
            },
            {
              featureType: "boundary",
              elementType: "geometry",
              stylers: {
                color: "#8b8787",
                weight: "1",
                lightness: -29
              }
            }
          ]
        }
      },
      series: [
        {
          type: "scatter",
          coordinateSystem: "bmap",
          data: [[120, 30, 1]]
        }
      ]
    }

```

**Comment by Ovilia** [comment]
检查下 map 组件是否正确引入？地图有画出来吗？

**Comment by deluo** [comment]
[这篇博客](http://www.huchiwei.com/2018/01/11/%E8%A7%A3%E5%86%B3Vue%E5%BC%95%E5%85%A5%E7%99%BE%E5%BA%A6%E5%9C%B0%E5%9B%BEJSSDK%EF%BC%9ABMap%20is%20undefined%20%E9%97%AE%E9%A2%98/)解决了问题,大致是引入百度地图api失败导致的问题

**Comment by 576189318** [comment]
我也遇到了一样的问题，是怎么解决掉的？

**Comment by 576189318** [comment]
我单独引用BMap时可以正确显示地图，放在Echarts内时就会报告同样的错误。请问您是怎么解决的？
