### ISSUE TITLE
bug: Bar series with multiple axis

### ISSUE THREAD

**Issue by node-rookie** [apache/incubator-echarts#8848]
### One-line summary [问题简述]
版本4.1.0绘制双坐标轴柱状图时，有负值的坐标轴绘图时起点是从没有负值的坐标轴的起点值开始绘制
4.1.0版本错误绘制截图：
![image](https://user-images.githubusercontent.com/7260662/43893982-578e622e-9c03-11e8-9169-107bf404fb95.png)
3.8.5版本正确的绘制图：
![image](https://user-images.githubusercontent.com/7260662/43894012-71b8cfc2-9c03-11e8-9709-14e7354dc15b.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:Mac Os

### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/7260662/43894098-ae7afb10-9c03-11e8-8900-c08566ba183a.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wangcongyi** [comment]
@Ovilia 我怎么觉得就你一个人在维护了？ open 的 issue 有 2K 了....

**Comment by Ovilia** [comment]
@wangcongyi 都在维护的，我回 issue 多一些，最近大家业务都比较多 😭

**Comment by elephantme** [comment]
@Ovilia 当设置scale为true时，坐标轴下方溢出了（4.1.0版本）

![echart-bar](https://user-images.githubusercontent.com/20337682/45530722-aa455400-b81e-11e8-990d-9fd6885ab43a.png)

option配置如下：

```javascript
option = {
    "xAxis": {
        "type": "category",
        "axisLabel": {
            "rotate": 45
        }
    },
    "yAxis": {
        "type": "value",
        "scale": true
    },
    "legend": {
        "show": true
    },
    "dataset": {
        "dimensions": [
            {
                "name": "005",
                "displayName": "日期"
            },
            {
                "name": "002",
                "displayName": "新用户"
            },
            {
                "name": "003",
                "displayName": "老用户"
            },
            {
                "name": "004",
                "displayName": "主页面用户数"
            },
            {
                "name": "006",
                "displayName": "登出用户数"
            }
        ],
        "source": [
            {
                "002": 30000,
                "003": 18000,
                "004": 12300,
                "006": 23409,
                "005": "支付电费支付电费支付电费"
            },
            {
                "002": 32000,
                "003": 18600,
                "004": 14400,
                "006": 25012,
                "005": "2017-01-02"
            },
            {
                "002": 23000,
                "003": 18700,
                "004": 13400,
                "006": 13456,
                "005": "2017-01-03"
            },
            {
                "002": 24000,
                "003": 18200,
                "004": 14500,
                "006": 13466,
                "005": "2017-01-04"
            },
            {
                "002": 14000,
                "003": 17600,
                "004": 12800,
                "006": 15690,
                "005": "2017-01-05"
            }
        ]
    },
    "series": [
        {
            "key": "002",
            "name": "新用户",
            "type": "bar"
        },
        {
            "key": "003",
            "name": "老用户",
            "stack": "test01",
            "type": "bar"
        },
        {
            "key": "004",
            "name": "主页面用户数",
            "type": "bar"
        },
        {
            "key": "006",
            "name": "登出用户数",
            "type": "bar"
        }
    ],
    "tooltip": {
        "trigger": "axis"
    }
}
```

**Comment by pissang** [comment]
@elephantme 嗯这个是已知问题，我们正在讨论怎么修复

**Comment by LiuZiqi-dual** [comment]
> @elephantme 嗯这个是已知问题，我们正在讨论怎么修复

请问一下这个已经修复好了么？3.8.5版本出现这个问题，是否升级到最新版即可解决？

**Comment by Ovilia** [comment]
还没修复，预计下一个版本修复

**Comment by yufeng04** [comment]
This issue can't be reproduced in 4.2.1
![image](https://user-images.githubusercontent.com/22974511/65134253-8b336080-da36-11e9-98e0-101b70da880c.png)

**Comment by pissang** [comment]
This issue has been resolved in the version 4.2.1. But the fix caused another issue https://github.com/apache/incubator-echarts/issues/11086 . We fixed in the commit https://github.com/apache/incubator-echarts/commit/de98ef690ddfc0e608c7a0e9af4d6f7b30beb0fd .It will be included in the release 4.4.0
