### ISSUE TITLE
关于tooltips的formatter

### ISSUE THREAD

**Issue by GodzillaHe** [apache/incubator-echarts#8849]
### One-line summary [问题简述]

目前想实现如下效果，当光标标移到图上时，显示常规tooltips，当光标移动到某一条线上时，只显示当前项的数据。有什么办法可以判断光标是否在线上吗？
![image](https://user-images.githubusercontent.com/13843799/43934485-2189c04a-9c82-11e8-89b7-c689ab1a35bf.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: 最新版chrome
+ OS Version [操作系统类型和版本]: window or mac

**Comment by Ovilia** [comment]
似乎做不到，因为只能选择以这两种方式中的一种显示 tooltip

**Comment by GodzillaHe** [comment]
![image](https://user-images.githubusercontent.com/13843799/44011005-7c97ae08-9ee8-11e8-9962-b6b66bc99e2e.png)
这种tooltips是如何实现的？ @Ovilia

**Comment by Ovilia** [comment]
默认就是这种的（但是没有灰色的竖线），http://echarts.baidu.com/option.html#tooltip.trigger 设为 'item'

**Comment by GodzillaHe** [comment]
echarts版本是4.1.0

**Comment by Ovilia** [comment]
`trigger: 'item'`

**Comment by GodzillaHe** [comment]
sorry，这个option忘记改了，改成```trigger: 'item'```tooltips就不出现了
