### ISSUE TITLE
tab切换的时候 宽度100%无效  默认变成了100px   或者0   ------Bug

### ISSUE THREAD

**Issue by miloshu** [apache/incubator-echarts#8855]
[
### One-line summary [问题简述]

项目需要做tab切换, 刚开始用的tab去切换 发现切换后的页面echart图宽度高度都没了, 后面改用路由切换,发现没问题,  但是用了resize监听自适应, 只要稍微动一下浏览器大小 改变浏览器宽高, 图表宽度就没了,  , 高必须写死, 但是宽度又变回了100px宽, 请问该如何解决？ 为什么不支持100%? 

http://m.qpic.cn/psb?/V11wSDi74XbFHJ/RoeFgPAHFavpreEp6UuIYDMWZ0U78KJ5WCNBBG.jfRA!/b/dGcBAAAAAAAA&bo=5gO.AQAAAAADB3g!&rf=viewer_4
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
能把那100px 换成100% ?

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by miloshu** [comment]
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+YAAAG+CAYAAAAeIh6UAAAgAElEQVR4nO3dX2xc2X0f8EOJIkVrbZO0k0hUXFuUi2RFtEkpuolAOU26BNI2YgO42QBGNwlagKsHQw4fCil+SgIU8DJoAy300GpVoMXuumi9zUvIbIKGizabVVUgIoO0FhdNIim2Y1HrtUXSSy7/SOJU565nQlIcajicO2ckfj7EaO69594fj/T21flzm2bn5gthG+YXVsLhQx3beQQAAAAoY0/qDgAAAMBuJpgDAABAQoI5AAAAJCSYAwAAQEKCOQAAACQkmAMAAEBCgjkAAAAk1FzNQ9+anql1PwAAAGBXqiqYHz7UUet+AAAAwK5kKjsAAAAkJJgDAABAQoI5AAAAJCSYAwAAQEKCOQAAACQkmAMAAEBCgjkAAAAkJJgDAABAQoI5AAAAJCSYAwAAQEKCOQAAACTUXO2D906cqGU/AAAAIHfNV66k7sJDqg7m2cMN+BcCAACAzTTqALOp7AAAAJCQYA4AAAAJCeYAAACQkGAOAAAACQnmAAAAkJBgDgAAAAkJ5gAAAJCQYA4AAAAJCeYAAACQUE2D+ezsbPit3/qt7HutycnJcOnSpVr+KgAAAHgiNNeyWHt7exgYGAgjIyPh3Llz2XkM5ePj4+HMmTMP3R8D/EsvvRSef/757N54/uKLL4Zf/uVfDkeOHNlRX27evJnVWlxcLHtPZ2dnqZ8AAACQQtPs3HxhOw/ML6yEw4c6wr0TJ0LzlSul69UE4Rjab926FU6dOrWuzsWLF8Pp06cfGc7j77pw4UI4duzYuho7tfY/E9ra2mpWFwAAgHQ25thGUdMR8+PHj4df+qVfyo5jwB4dHQ1DQ0NZuC2Ojq917dq10NPTE770pS+FO3furGt74YUXsu+tRrVfffXVbIS+t7e3ln+NrF78D4M33nijpoEfAAAANqppMJ+YmAhvvfXWumvDw8Ol4xiyi2Jwv3HjRhgcHAxf/vKXt/274vNxxPzpp5+uvsNbOHnyZPYfCfHbVHcAAADykmzEPE4VX1payo7j1PEY6uO9RY9abx5H22No3myqeawXp8NXotyIfDzv6OjI/vOg1iPyAAAAUJRkxDyG9m9961th//792Xkc9Y7PxevFEB4DcQzdBw8efOj3xJHy2B6nwW8mBuliMI8B/7XXXgvPPfdcVu+VV17JAn0lm8sdOnSogr81AAAAVC/JiPnMzEz47Gc/mwX5KLZ3d3dno+DFwBzb4vrxnW6+Fn/XVhvSPUpca27EHAAAgLzULJjHQL3VKHScGn727NnsOAbdGNSLwTyKo98xyMcQvby8nAXqGNZ3KtaJ4b7agN/V1bXjPgAAAEA5NQnmY2NjWajezNqp7FEMyL/6q7+ard9eqzhl/fbt21mYjq9AK7fpWjFox/u2+s+AGPLjFPm4wVy59kuXLmXtm9WJ9ctNlwcAAIBaqEkwj68U2/hasY1T2TeKI+ZrxXu++MUvZmE5PlcuTBfFafNxxL3cNPNYf2RkJPT395cN73FkPm5At/E/CYrPT09Pb9oGAAAAtVLTNebViOH6q1/96kPX43rzqDjCvjFcx0Ae71m7YVxR3JX95Zdf3vS5GLSL70iP+vr6Nh2ZjyPtW43aAwAAQC00zc7NF7bzwPzCSjh8qCPcO3EiNF+5kle/KlIcFX/22WdrukFbDPbxdW5nzpzZ8eZzAAAANIZGyLGbeayDOQAAAFSqUXPsntQdAAAAgN1MMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgISad/Lw4uJiuHDhQrh+/Xp23tfXF4aGhsrePzY2Fi5fvhzOnTsX2tvb110fHR3dtMZWbRtrV1Oj0voAAACQhx2NmL/xxhthYGAgXLx4MZw/fz7MzMxkQXejycnJcPr06XDjxo2wf//+h9piWB8ZGXmoxlZttahRaX0AAADIy46C+alTp0Jvb2923NbWFo4dOxamp6cfui/eE8P74ODgQ20TExOhv78/G0GPNWLQn5qaykbjt2qrRY1K6wMAAEBearbGPIbZGGoPHTq0rWfip6enp3Sto6MjuzY3N1e2bXl5ecc1Kq0PAAAAedrRGvO1Xn311ez7mWeeqfiZGIDj9PHtttWiRqX1qzG/sLDufF9zc2htbc3ldwEAAPB423Ewn52dzdZod3d3h7Nnz27r2RhW4yj1dttqUaPS+tV46sCBXOoCAADw5NnRVPabN2+GF154ITz//PNV72a+tLS0buQ6Hsf13i0tLWXbNo4+V1NjO/UBAAAgLzsK5uPj4+HkyZPhyJEjVT1f3HAt1imuFY/H8VpnZ2fZtvjcTmtUWh8AAADytKOp7HGE+erVq6X3gEdHjx4NZ86cCW+//Xa26/mjRtLjju3xvuHh4ew87txe3Ol9q7b4qrNi/WprbNUGAAAA9dA0Ozdf2M4D8wsr4fChjnDvxInQfOVK2fvi+8C7urpyC7p51wcAAODJ8qgcm0rNXpe2VpwWHt9nHjeEexzrAwAAQL3kNmIOAAAAjaRRc2wuI+YAAABAZQRzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASKg5dQeedHdW3g0zDz5tez8Uuto+lbo7AAAANBjBPEdfm/2T8J+u/9vS+Wd/8B+Hn//EryTsEQAAAI3GVPYcvfnO6+vO//jbv5+oJwAAADQqwbzOFu8vpO4CAAAADUQwz9HhD31q3fmhtk+Gtr0H0nQGAACAhmSNeY7ievKF+++F6++9Hf7+x346fObjP526SwAAADQYwTxnP/KRHwtNhabws13Ppu4KAAAADagmwXxsbCxcvnw5nDt3LrS3t296z6VLl8LVq1ez46NHj4YzZ86Etra20vOjo6PZcV9fXxgaGlpXu1zbxj5UU6PS+gAAAJCHHa0xn5ycDKdPnw43btwI+/fvL3tfDL8zMzPh/Pnz2Sd64403SjViqB8ZGcna4n3x/ke1bexHNTUqrb8jhUJt6wEAAPBE2VEw7+3tDRcvXgyDg4OPvPfYsWPZCHn8xOPp6ens+sTEROjv789G2mPbwMBAmJqaCouLi1u2rVVtjUrrAwAAQF7qsiv7yZMns8A7Ozubhd44wh5DcDyOn56entK9HR0d2bW5ubmybcvLy6Vr1daotD4AAADkqW6bv8Vp4nENetTZ2ZmF4BiA4/XNbNVW6X21qF+N+YW/eVf50oPfs7q6msvvAQAA4PFXlxHz1157LXR3d2fT3uMnTh9/6aWXssAaA/pmWltby7ZVel+1bTv11IEDpU/8PXv2eF08AAAAm8s9Mcbp67du3cqmrhfF6eNxyvjKykpYWlpaN3Idj+N675aWlrJtMeyuVU2N7dQHAACAvOQezOPGal1dXWF8fLx07dq1a1kA/uhHP5oF9thWXCsej+O1ON29XFvxNWtRcdO27daotD4AAADkKbc15vFVZHHX8/he8Oeeey5cuHAhe7VatPY95nFn93jf8PBw1hZ3eI/Xoq3a1tavtsZWbQAAAFAPTbNz89t60fb8wko4fKgj3DtxIjRfuVL2vvg+8DhSnlfQzbt+rVz97h+Fv/je18Lnj3whdVcAAAB2tUfl2FRymcoep4XH95THDd8ex/oAAABQL7lMZY9T1OMU87zkXR8AAADqxXu8AAAAICHBPGeFsK0l/AAAAOwygjkAAAAkJJgDAABAQoI5AAAAJCSYAwAAQEKCOQAAACQkmAMAAEBCgjkAAAAkJJgDAABAQoJ5zgqFQuouAAAA0MAEcwAAAEhIMAcAAICEBHMAAABISDDPWSFYYw4AAEB5gjkAAAAkJJgDAABAQoI5AAAAJCSYAwAAQEKCOQAAACQkmAMAAEBCgjkAAAAkJJgDAABAQoJ5zgoPfgAAAKAcwRwAAAASEswBAAAgIcEcAAAAEhLMAQAAICHBHAAAABISzAEAACAhwRwAAAASEsxzVih4jzkAAADlCeYAAACQkGAOAAAACTXXosjY2Fi4fPlyOHfuXGhvb3+ofXZ2NoyMjIQ7d+6Urp0+fTr09vaWnh8dHc2O+/r6wtDQ0Lra5do29qGaGpXWBwAAgDzsaMR8cnIyC9g3btwI+/fvL3vfzMxM1h7D+cWLF7NPMZTHGjHUx7bz589n98aw/Ki2jf2opkal9XfGGnMAAADK21Ewj+E6huzBwcFH3tvR0RFaW1sfuj4xMRH6+/uzkfa2trYwMDAQpqamwuLi4pZttahRaX0AAADIS02msj9KHIm+du1aGB4ezs5jkD916lQWgOOnp6endG8M8PHa3Nxc2bbl5eUsSEfV1qi0fjXmFxZKx8srK2F1dbXqWgAAADzZ6hLMiyPrUXG9eVdXV+ju7s5C+2ZiOC7XVul91bbt1FMHDpSOW99vCXtW7LEHAADA5uqeGOO08Th9PE4jj1Pb4yj1ZrZqq/S+WtQHAACAPCUfyl1aWlo3ch2P4zTylpaWsm0b16pXU2M79XfC1m8AAABspS7BfHp6unR88+bNMD4+Ho4fP17acC2eF9eKx+N4rbOzs2zb2vXf1daotD4AAADkKbc15vFVZHG6enwveAzmv/Ebv1FqW/sO8/gd71u7MVwlbWvrV1tjqzYAAACoh6bZufltzbaeX1gJhw91hHsnToTmK1fK3hffBx43eMsr6OZdv1b+17t/GL4+/+fh80e+kLorAAAAu9qjcmwquUxlj9PC4yh53HX9caxfW1aZAwAAUF4uU9njGu04xTwvedcHAACAekm+KzsAAADsZoI5AAAAJCSY56xgjTkAAABbEMwBAAAgIcEcAAAAEhLMAQAAICHBHAAAABISzHNWsPcbAAAAWxDMAQAAICHBHAAAABISzAEAACAhwTx3FpkDAABQnmAOAAAACQnmAAAAkJBgDgAAAAkJ5jkrWGMOAADAFgRzAAAASEgwBwAAgIQEcwAAAEhIMAcAAICEBHMAAABISDAHAACAhARzAAAASEgwBwAAgIQE85wVHvwAAABAOYI5AAAAJCSYAwAAQEKCOQAAACQkmOetYI05AAAA5QnmAAAAkJBgDgAAAAkJ5gAAAJCQYJ4zK8wBAADYSnMtioyNjYXLly+Hc+fOhfb29ofaFxcXw4ULF8L169ez876+vjA0NLTu+dHR0W23bexDNTUqrQ8AAAB52NGI+eTkZDh9+nS4ceNG2L9/f9n73njjjTAwMBAuXrwYzp8/H2ZmZrJAXKwRQ/3IyMi22jb2o5oaldYHAACAvOwomPf29mZhe3BwcMv7Tp06ld0btbW1hWPHjoXp6ensfGJiIvT392cj7bEtBvipqalslH2rtrWqrVFpfQAAAMhL3deYx9Abw++hQ4ey4/jp6ekptXd0dGTX5ubmyrYtLy+vq1dNjUrrV2N+YaH0WVlZDqurqzuqBwAAwJOrJmvMt+PVV1/Nvp955pksAMfp45vZqq3S+2pRvxpPHThQOm6Zbwl77tljDwAAgM3VLTHOzs6GL33pS9nx2bNns6njra2t2Sj1ZrZqq/S+WtQHAACAPNUlmN+8eTO88MIL4fnnn39o1/OlpaV1I9fxOIb2lpaWsm0xVO+0xnbqAwAAQF7qEszHx8fDyZMnw5EjR9ZdL264FtuLa8XjcbzW2dlZti0+t9MaldYHAACAPOW2xjy+iizuev7cc89lI9FXr14tvS88Onr0aDhz5ky2W3u8b3h4OLsed3gv7uC+VVuxfhyBr7bGVm21UnjwAwAAAOU0zc7Nbys5zi+shMOHOsK9EydC85UrZe+L7wPv6uqqedCtV/1a+Z/vjIbp978RPn/kC6m7AgAAsKs9KsemkstU9jgtPL6nvLu7O4/yudcHAACAesllKntco71xk7fHqT4AAADUixdsAwAAQEKCOQAAACQkmAMAAEBCgjkAAAAkJJjnrFDwHnMAAADKE8wBAAAgIcEcAAAAEhLMAQAAICHBPGeFYI05AAAA5QnmAAAAkJBgDgAAAAkJ5gAAAJCQYA4AAAAJCeYAAACQkGAOAAAACQnmAAAAkJBgDgAAAAkJ5jkrPPgBAACAcgRzAAAASEgwBwAAgIQEcwAAAEhIMM+dNeYAAACUJ5gDAABAQoI5AAAAJCSYAwAAQEKCOQAAACQkmOesYO83AAAAtiCYAwAAQEKCOQAAACQkmAMAAEBCgnnuLDIHAACgPMEcAAAAEhLMAQAAIKHmev2iS5cuhatXr2bHfX19YWhoqNQ2NjYWRkdHt922VrU1Kq0PAAAAeajLiHkMvzMzM+H8+fPZJx5PTk5mbfH78uXLYWRkpNQW739U21rV1qi0/k4UrDEHAABgC7kH88XFxTA1NRUGBgZCW1tb9onHExMTWXv87u/vD+3t7aW2eH98bqu2taqtUWl9AAAAyEuyNeZxdPrOnTtZCO7p6Sld7+joyK7Nzc2VbVteXi5di+fV1Ki0PgAAAOQp92AeR6Jj4B0fHy+NRBdHy1dWVrKAvpkYjsu1VXpftW07Nb+wUPqs3L0bVldXc/k9AAAAPP7qMmL+3HPPZd/Dw8Ph9OnTWVDfv39/aGlpyY4309raWrat0vuqbduppw4cKH1a9u0Le/bY/B4AAIDN1SUxxlHzs2fPhosXL2afGMq7u7uz60tLS+tGruNxvB5De7m2GKrXqqbGduoDAABAXuo+lHvz5s1sKvvJkydLG64Vp7nHTzyO1zo7O8u2xeeKqq1RaX0AAADIU13eYx5fSxZHyqMYiM+dO5fthB719vZmQT1Oc48GBweza49qizVjW3zveLU1tmoDAACAemianZvf1ou25xdWwuFDHeHeiROh+cqVvPr1SPF9411dXQ0fpP9w+nfCd5Zuh88f+ULqrgAAAOxqqXNsOY/lrmRx2vn09HS2Tr3RFcK2/t8DAACAXaYuU9lrLa4Bj1PYAQAA4HH3WI6YAwAAwJNCMAcAAICEBPOcFQrWmAMAAFCeYA4AAAAJCeYAAACQkGAOAAAACQnmAAAAkJBgDgAAAAkJ5gAAAJCQYA4AAAAJCeY5KwTvMQcAAKA8wRwAAAASEswBAAAgIcEcAAAAEhLMAQAAICHBPHc2fwMAAKA8wRwAAAASEswBAAAgIcEcAAAAEhLMc1awxBwAAIAtCOYAAACQkGAOAAAACQnmAAAAkJBgnjuLzAEAAChPMAcAAICEBHMAAABISDAHAACAhATznBWsMQcAAGALgjkAAAAkJJgDAABAQoI5AAAAJCSYAwAAQEKCOQAAACTUXK9ftLi4GC5cuBCuX7+enQ8ODoZTp05lx2NjY2F0dDQ77uvrC0NDQ6Xntmpbq9oaldYHAACAPNRlxLwYygcGBsLFixezTzGUT05OhsuXL4eRkZFw/vz5MDMzk4XlR7WtVW2NSusDAABAXuoSzN9+++3Q0dERent7H2qbmJgI/f39ob29PbS1tWXhfWpqKgvzW7XVokal9QEAACAvdZnKHgNwDObDw8NZ6O3s7Aznzp0Lra2t2XlPT0/p3nhfvDY3N1e2bXl5OQvSUTyvpkal9Xeq8OAHAAAAysl9xDwG3ThF/MaNG+HLX/5yNo29u7s7vPbaa1kAjm2b2aqt0vtqUb8a8wsLpc/K3bthdXU1l98DAADA469uu7LHaeLFUeh4fOvWrbC0tJSNUm8mjqaXa6v0vmrbduqpAwdKn5Z9+8KePTa/BwAAYHO5J8YYxrcKwDGcrx25jsfxmZaWlrJtMVTvtMZ26gMAAEBe6jKUe/z48Wzq+uzsbHY+Pj4eurq6wsGDB7PR83heXCsej+O1uA69XNva9d/FTdu2W6PS+jtVKFhjDgAAQHl12fwt7sYep67HDd+io0ePhjNnzpTa4uZwcWO4KL7fvLh7+1Zt8VVnsS2+d7zaGlu1AQAAQD00zc7Nb2tId35hJRw+1BHunTgRmq9cyatfjxTfNx5H3Rs9SI/99VfCe3dnw+ePfCF1VwAAAHa11Dm2nMdyV7I47Xx6ejrb3R0AAAAeZ3WZyl5rcQ14nMIOAAAAj7vHcsQcAAAAnhSCOQAAACQkmAMAAEBCgjkAAAAkJJjnrBC29TY6AAAAdhnBHAAAABISzAEAACAhwRwAAAASEsxzZ405AAAA5QnmAAAAkJBgDgAAAAkJ5gAAAJCQYJ4zK8wBAADYimAOAAAACQnmAAAAkJBgDgAAAAkJ5gAAAJCQYJ63gu3fAAAAKE8wBwAAgIQEcwAAAEhIMAcAAICEBPOc3V76Zri19PVw9bt/lLorAAAANKDm1B14kv3H6/8m/Pn3/m92/F/+6t+F7y5/O/xs17OJewUAAEAjMWKeo2uzV9edX/3um4l6AgAAQKMSzHNUyH7+5qxlT2vC3gAAANCITGXPyZ2Vd0vHxXAumAMAALCRYJ6T1//6P4emBz9FMZzP3/teug4BAADQkExlz8k3Fq6vO48hvblpX6LeAAAA0KgE85x84kD399eYfzCRPX4f+fCPJu4VAAAAjcZU9px8eF/7uqnszU3N4Rc/+XzCHgEAANCIjJjn5Nb7X193fr9wPyzeX0jUGwAAABqVYF5HbXsPpO4CAAAADUYwz8lnPv4P1p33feynEvUEAACARla3NeZjY2NhdHQ0Ox4cHAynTp3atK2vry8MDQ1V1Fau/nZqVFp/uz7zsZ8O04tfD2++83oYOPjPwj86/Is1qQsAAMCTpS4j5pOTk9n3xYsXw6/92q+Ft956K9y8ebPUdvny5TAyMhLOnz8fZmZmsrD8qLaN9aupUWn9ajU9+OeNe7J/tLWzZjUBAAB4stQlmPf29pZGyA8ePBg6OzuzEBxNTEyE/v7+0N7eHtra2sLAwECYmpoKi4uLW7atVW2NSutX481vvx7+6J3fy3Zm/52v/4fwtdk/2XFNAAAAnjx1X2N++/btLPh2d3dn3/HT09NTau/o6Miuzc3NlW1bXl4uXau2RqX1q/W733x53Xmc0g4AAAAb1W2N+aVLl8LVq1ez0fJz585lo9Szs7OlkfONYjgu11bpfdW27dT8wsOvRZtZeTeX3wUAAMDjrW7BPG6qFj8xjMc13c8++2x4+umns1HqzbS2tpZtq/S+att26qkDB8Khtk9mm78VHf3wsVx+FwAAAI+3uk9ljyPlcV13XN8dLS0trRu5jsdxvXdLS0vZthiq16qmxnbqV+NffPpfhYNtnwiFBz/xVWk//4lf2XFNAAAAnjx1CeavvPJKaRf2OGIed0I/fvx4acO18fHx0lrxeByvxSnv5dric0XV1qi0frU6W34g/PCHurPN337i4/8wtO09sOOaAAAAPHnqMpU9vrc8Tl+/c+dO6Tzu1B7F7zh6Pjw8vK22+Kqz2Banx1dbY6u2Wlgt3M++9zTVfWICAAAAj4mm2bn5wnYemF9YCYcPdYR7J06E5itX8urXI8X3jXd1ddU0SNfaKzdeDH82cyV88Uf/dfhbBz6dujsAAAC7WuocW85jOZQbp51PT09nr1xrZEbMAQAAeJS67cpeS3ENeJzC3uhWH/xEcZ05AAAAbMZQbo7uF+5l30bMAQAAKEdizNFq4fsj5oI5AAAAZUiMOXnz26+Hv3jva9nxf/2rfx8W7y8k7hEAAACNSDDPwZ2Vd8PvfvPlUCishsKDn28uXA///dZ/S90tAAAAGpBgnoPb73/jwZ8fvIUubvwWj76x8JdJ+wQAAEBjEsxz8M7yt0JYsxN7PNrTtDdZfwAAAGhcgnkOVu4vP3Ttkwf+doKeAAAA0OgE8xz8nY7PPHTt6Y/+vQQ9AQAAoNEJ5jnoavtU+JGP/N1sbXlTU1P4mYP/NBz98LHU3QIAAKABCeY5iK9K+3/f+z/Z2vJCoRD+x+3fzXZqBwAAgI0E8xxcf28qe01a4fs7s8fvmWXBHAAAgIc1p+7Ak+j9e/PZa9KK4nFb84cS9ggAAIBGZcQ8B/N333voWlx3DgAAABsJ5jn48L6PpO4CAAAAjwnBPAc/1vmT2fcHa8wLoe9jP5W2QwAAADQsa8xz8Gd3/nf2XVxn3tHyAym7AwAAQAMzYp6D6/NT2XdxV/Zrs1dTdgcAAIAGJpjnKI6Yx3D+/v2F1F0BAACgQQnmNfbmO6+vO4+T2QuF1TSdAQAAoOEJ5jU2ceetde8wj9G8Ze/+ZP0BAACgsQnmNVYIq9/fi/2DP6Mf2n84aZ8AAABoXIJ5jf1A68FsvLzp+39GP/VD/yRpnwAAAGhcgnmNfWPhL0u7sRf/7H7q6ZRdAgAAoIEJ5jU2s/Kd0hrzbOO3devNAQAAYD3BPGd7/RMDAACwBamxxlr3rN+B/ehHehL1BAAAgMeBYF5j//LTZx+E87ZsffknDhwNgz/8z1N3CQAAgAYmmNfY12b/JCyvLmYry2eWvxP27z2QuksAAAA0MMG8hm4t/lV489u/Xzqfvzcb/vid1xP2CAAAgEYnmNfQn3738oY92JvC23N/mqg3AAAAPA4E8xpavP9+WH3wE99jvhpC9t3Z+oOpuwUAAEADE8xraPbud0vHxX/YH/3oj6fpDAAAAI8FwbyG/uJ7X3vwD/rBP2kcOY/T2g+3fSppnwAAAGhszak7kNrY2FgYHR3Njvv6+sLQ0FDVte4V7mVhvCn7+WAqe1vzh2rTUQAAAJ5Iu3rEfHJyMly+fDmMjIyE8+fPh5mZmSyoVwOaPPIAAARWSURBVOP3/vorD238Fn+6jJgDAACwhV0dzCcmJkJ/f39ob28PbW1tYWBgIExNTYXFxcVt1/re3bmHrrXsaatFNwEAAHiC7dpgHsN3/PT09JSudXR0ZNeWl5e3Xe/HOn7ioWs/8fGf2VEfAQAAePLt2mAew3ecul4rx9qPh5/8+DNh/94DoXVPW/iRp348PNP5C2F+YaGqoA8AAMDusGs3f2ttbc1GyGvpFz45lH0AAACgUrt2xDxaWlpaN2oej+Na8xjaAQAAoB52bTAvbvY2Pj5eWm8ej+O12AYAAAD1sGunske9vb3ZzuzDw8PZ+eDgYHYNAAAA6mVXB/NoaGgo+wAAAEAKu3YqOwAAADQCwRwAAAASEswBAAAgIcEcAAAAEhLMAQAAICHBHAAAABISzAEAACAhwRwAAAASEswBAAAgIcEcAAAAEhLMAQAAICHBHAAAABISzAEAACAhwRwAAAASEswBAAAgoebUHXhc/OZv/mZ4//33w927d8Pq6mp23NTUFAqFQume4nn8jtra2sLS0lJ2/9p7X3rppSR/BwAAABqPEfMK/fqv/3pobm4O8/PzpVC+1trzGMDjJ94XQ3nxGgAAAGwkmFdocnIyvPvuu9nx2hC+MZCvHTUvfja7FwAAACJT2Stw8+bN8JWvfKVssN44pb04Yr52WnvxOgAAAKxlxLwCExMT4b333sumpRcDd1HxuDg6vnHN+dp7AAAAYCPBvAI/93M/Fz73uc+FlpaWdWE7ftaG9eJ68mJ70Z49H/wzm8oOAADARqayV+D27dvhD/7gD8K9e/ey87UBe+/evaXj4oh5MYgXbZzSDgAAAEVGzCtw5MiRMDw8vG50vDgivvF47bViGC8GdlPaAQAA2Egwr9B3vvOddSPhG3db32xUvBjEiyPta68BAABAJJhXYHFxMbz88sub7rxeHEUvXit+r31VWnz/eZEp7QAAAKwlmFfg2rVrYXl5+aEd2KPNNnbbuEHc2ucAAABgLZu/VaCvry/7vPLKK+HkyZNZUB8dHc2C9tGjR8OZM2dCW1tb9r7zF198MRthX3s9+u3f/u3w1FNPheeffz7x3wYAAIBG0jQ7N7+tRc/zCyvh8KGOcO/EidB85Upe/QIAAICaatQcayo7AAAAJCSYAwAAQEKCOQAAACQkmAMAAEBCgjkAAAAkJJgDAABAQoI5AAAAJNS8k4fjO+AAAACA6lUdzBvxpewAAADwuDGVHQAAABISzAEAACAhwRwAAAASEswBAAAgIcEcAAAAEhLMAQAAIKGqgnmhUOtuAAAAwO607WC+d++esHL3Xh59AQAAgF1n28G8eW9TWFhYyqMvAAAAsOtsO5jv27c3rNy9H+aFcwAAANix5moeam3d+yCYL4eVlXvhwIH9oWVfc2hqqnXXAAAA4MnXNDs3X/VWbnfv3g/37hfC/furtewTAAAA7BpVjZgXxWnt+/bVqisAAACw+/x/6nTqa6WQ8VoAAAAASUVORK5CYII=

**Comment by Ovilia** [comment]
等切到图表页的时候，再调用下 `chart.resize()`？

**Comment by Ovilia** [comment]
这个问题不是由于 ECharts 不支持 100% 引起的，事实上，ECharts 不管你 CSS 写的是像素值还是百分比，只管实际容器的大小。而在 tab 切换的时候，其实这个容器是 0x0 的，所以再切回这个 tab 的时候当然是需要 resize 一下的。
@CJELLYS 可以具体说下为什么切换回 tab 之后调用 resize 不行呢？或者你的困惑的点在哪里？

**Comment by miloshu** [comment]
没有解决啊 ！  我的同一个页面有tab切换 和不同页面 顶部tag-view 切换都会出现这种问题; 都有重置初始化没有效果   大bug啊

**Comment by miloshu** [comment]
刚用定时器解决 了呵呵哒

**Comment by SmileAjh** [comment]
怎么使用定时器解决这个问题呢？
