### ISSUE TITLE
折线图性能问题

### ISSUE THREAD

**Issue by eniaclyl** [apache/incubator-echarts#8856]
你好，我在使用折线图显示六千多个点的时候 会出现明显卡顿，包括在缩放的时候，我不想使用sampling优化我的点，这样用这个会把某些点给删掉了，不知道还有没有什么别的办法优化，我不太了解sampling的原理，估计缩放后显示的点也比我原来的点少，有什么办法解决显示六千个点不卡顿吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
sampling 的原理是把原先一个像素点内的多个点用一个点表示，可以指定用什么算法生成这个点，比如是平均数还是最大最小值等，详见 http://echarts.baidu.com/option.html#series-line.sampling
不用 sampling 的原因在我看来可能是怕 tooltip 的时候显示不出其中的某些点？但是其实本来一个像素内有多个点，也很可能选不中那个点吧？

**Comment by eniaclyl** [comment]
你那有没有邮箱，我发邮件截图给你 这个gethub不太好用

**Comment by Ovilia** [comment]
@eniaclyl oviliazhang at gmail.com

**Comment by eniaclyl** [comment]
请问 我使用了折线图的优化功能sampling: 'average'，但是我将曲线放大后 优化掉的点没有显示回来，如何才能让优化的点显示回来呢？

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html 复现一下
