### ISSUE TITLE
如何让graph分组后点击高亮

### ISSUE THREAD

**Issue by wangtian521125** [apache/incubator-echarts#8857]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html?c=xrJkv-mSOf

**Comment by Ovilia** [comment]
先通过 [on('click', function() {...})](http://echarts.baidu.com/api.html#echartsInstance.on) 获得点击事件，然后根据你自己维护的节点的连接关系，得出相邻的点，然后通过 [dispatchAction](http://echarts.baidu.com/api.html#action.highlight) 触发 `highlight` 事件。是会有点麻烦，但是这种比较特殊的需求，是需要自己定制化一下的。

**Comment by wangtian521125** [comment]
我之前就是用的dispatchAction出发focusNodeAdjacency，没有分组点击可以高亮，分组后点击高亮节点有时高亮成其他节点，有时不高亮，我在8845问题中有描述

**Comment by Ovilia** [comment]
嗯，这个需求没想到别的解决方法，这个先关了，#8845 后面看下是不是 bug

**Comment by yang19930204** [comment]
目测是个bug
