### ISSUE TITLE
对数坐标的指数为10，怎样不显示10，100，1000，而是显示20，200，2000？

### ISSUE THREAD

**Issue by zhjb7** [apache/incubator-echarts#8867]
### One-line summary [问题简述]
我需要使用对数坐标，指数是10，设置的最小值是20，最大值是20000，但默认的横坐标是100，1000，10000。
我希望不显示100，1000，10000，而是显示**200，2000，20000**。但我找遍了文档也没有可以修改的地方。
请问我能修改参数达到我的需求吗？非常感谢大家了！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:Chrome:Version 68.0.3440.106 (Official Build) unknown (64-bit)
+ OS Version [操作系统类型和版本]:ubuntu:16.04

### Expected behaviour [期望结果]
希望指数坐标的标签值可以定制。

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: '对数轴示例',
        left: 'center'
    },
    yAxis: {
        type: 'value',
       
    },

    xAxis: {
        type: 'log',
        min:20,
        max:20000
    },
    series: [
        {
            type: 'line',
            smooth:true,
            data: [[1000, 3],[2000,9],[3000,3]]
        }
    ]
}

```

### Other comments [其他信息]

![q -20180814121322](https://user-images.githubusercontent.com/7479250/44071438-8ff5bb06-9fbb-11e8-9162-af519887bbcd.png)

**Comment by Ovilia** [comment]
对数坐标轴是基于“对数”的，之所以显示 10 100 100 是因为他们是 10 的指数，而 20 200 2000 不是什么整数的指数，因而是没法用对数轴正确实现的。举例来说，如果将 [logBase](http://echarts.baidu.com/option.html#yAxis.logBase) 设为 3，那么坐标轴显示的是 3 9 27 81...
20 200 2000 根本不是指数分布了，所以看起来是不能实现的了。

**Comment by zhjb7** [comment]
谢谢 Ovilia，我刚刚实现了这个chart。我一共加入了2个X轴，第1个原来的对数轴给隐藏了，第2个X轴设置为数值轴，但只显示X轴标签最小值20和最大值20000。之后加入了4个bar的series，每个bar宽度设置为1，data设置为[200,y轴最小值],[200,y轴最大值],[2000,y轴最小值],[2000,y轴最大值]，其中y轴最小值的2个bar设置label为显示为x轴的值。
代码如下：

option = {
            title: {
                text: '对数轴示例',
                left: 'center'
            },
            yAxis: {
                type: 'value',
                min:-20,max:20,interval:4
            },

            xAxis: [
                {
                    show:false,
                    name:"real_x_axis",
                    position:"top",
                    type:"log",
                    logBase:10,
                    nameGap:30,
                    axisTick:{show:false},
                    axisLine:{
                        lineStyle:{
                            width:1.5,
                            color:"#F0F0F0"
                        }
                    },
                    axisLabel:{
                        show:true,
                        color:"#000000"
                    },
                    min:20,
                    max:20000
                },
                {
                    type:"value",
                    position:"bottom",
                    axisLine:{
                        lineStyle:{
                            width:1.5,
                            color:"#000000"
                        }
                    },
                    axisTick:{show:false},
                    axisLabel:{
                        show:true,
                        showMinLabel:true,
                        showMaxLabel:true,
                        color:"#000000"
                    },
                    interval:20000,
                    min:20,
                    max:20000
                }
            ],
            series: [
                {
                    type: 'line',
                    smooth:true,
                    data: [[1000, 3],[2000,9],[3000,3]]
                },
                {
                    type: 'bar',
                    barWidth:1,
                    itemStyle:
                    {
                        color:"#000000"
                    },
                    data: [[200,20],
                    {
                        value: [200,-20],
                        label:
                        {
                            show:true,
                            color:"#000000",
                            position:"insideBottom",
                            distance:-20,
                            formatter: '{@[0]}'
                        }
                    },
                    [2000,20],
                    {
                        value: [2000,-20],
                        label:
                        {
                            show:true,
                            color:"#000000",
                            position:"insideBottom",
                            distance:-20,
                            formatter: '{@[0]}'
                        }
                    }]
                }
            ]
        };

![q -20180815163500](https://user-images.githubusercontent.com/7479250/44139306-44ad1c54-a0a9-11e8-8efa-138e3ef53a3e.png)
