### ISSUE TITLE
离线展示省市县三级下钻，现在无法下载地图数据，请问有什么别的方式么。。

### ISSUE THREAD

**Issue by tanghf0403** [apache/incubator-echarts#8879]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
你是问地图数据哪里下载吗？ECharts 官方不提供地图数据下载。

**Comment by tanghf0403** [comment]
谢谢。明白了

**Comment by chfw** [comment]
请读 echarts 最新自述文档
