### ISSUE TITLE
中国地图数据省份划分有问题

### ISSUE THREAD

**Issue by surmerming** [apache/incubator-echarts#8881]
### One-line summary [问题简述]

这是百度地图显示的：
![image](https://user-images.githubusercontent.com/4033937/44186562-c042f480-a14c-11e8-9450-e3709def8639.png)

这是中国标准地图服务的：
![image](https://user-images.githubusercontent.com/4033937/44186606-f6807400-a14c-11e8-87b6-e247cae107dc.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
ECharts 官方不提供地图数据下载，如果使用第三方下载的地图，请自行负责。
