### ISSUE TITLE
dispatchAction hideTip used in line charts, trigger line still exists

### ISSUE THREAD

**Issue by initialdmg** [apache/incubator-echarts#8892]
### One-line summary [问题简述]

dispatchAction hideTip used in line charts, tip is hided only, trigger line still exists and remain highlight state

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 68
+ OS Version [操作系统类型和版本]: Win 7 SP1

### Expected behaviour [期望结果]

all tip related components hided, including trigger lines, just like mousehover behavior

### ECharts option [ECharts配置项]

```javascript
option = {

}

```
at [echarts official demo](http://echarts.baidu.com/examples/editor.html?c=line-stack)

### Other comments [其他信息]

command:
```js
var inst = echarts.getInstanceByDom(document.getElementById('chart-panel'));
inst.dispatchAction({type: 'showTip', seriesIndex: 0, dataIndex: 1});

inst.dispatchAction({type: 'hideTip',});
```

**Comment by initialdmg** [comment]
@pissang Hello, can you confirm if this is  a bug or designed behavior? :smile:

**Comment by LHMing01** [comment]
This problem has been discussed in #7303 .

**Comment by fuscoantonio** [comment]
This is still an issue as of version 5.2.2. dispatching a 'hideTip' action does not hide the tooltip. In order to hide the tooltip I'm forced to use reset option with:

`instance.setOption(option)`
