### ISSUE TITLE
关于3D地球(about 3d earth)

### ISSUE THREAD

**Issue by ch-zgh-1993** [apache/incubator-echarts#8893]
我在地球上标记了一些国家，或者是一些点。地球在转动过程中，我能得知当前转动到哪个点或者国家吗?
I have marked some countries or some points on the earth. In the course of rotation, can I know which point or country to turn to?

应该可以通过计算转动角度来计算获取，但是这样我需要隔离用户的鼠标操作。我想知道是否有一种更加好用的方式来获取，类似事件？
It should be able to calculate the rotation angle, but I need to isolate the user's mouse operation. I want to know if there is a more convenient way to obtain similar events.

非常感谢！
Thank you very much!

**Comment by lxd0130** [comment]
请问有解决办法了吗，我也碰到了这个需求。

**Comment by lxd0130** [comment]
> > 请问有解决办法了吗，我也碰到了这个需求。
> 
> 如果不需要用户操作的话，你可以试试上面那个思路。。

请问如何获取转动角度？自己写个计时器去计算吗？
