### ISSUE TITLE
柱形图label根据正负显示上下不同位置

### ISSUE THREAD

**Issue by dcharlie123** [apache/incubator-echarts#8894]
### One-line summary [问题简述]
柱形图label根据正负显示上下不同位置
### Expected behaviour [期望结果]

![图](http://om10n1h33.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180818094526.png)

**Comment by Ovilia** [comment]
目前没有很好的办法，只能把负值的放到另一个系列中

**Comment by pissang** [comment]
@dcharlie123 @Ovilia 每个 data 项都可以设置 label 的位置
