### ISSUE TITLE
使用echarts如何自定义时间范围按钮

### ISSUE THREAD

**Issue by 601724080** [apache/incubator-echarts#8896]
### One-line summary [问题简述]
使用echarts如何实现下面功能

![image](https://user-images.githubusercontent.com/25952552/44305417-43f91d00-a3a9-11e8-8421-1b033c63f6ea.png)

**Comment by pissang** [comment]
可以自己实现这个组件

**Comment by 601724080** [comment]
好吧，只不过这种功能也比较常用，还是希望echarts能够支持
![5bv2npysfn nv s9v gzu](https://user-images.githubusercontent.com/25952552/44316171-d1497980-a45c-11e8-96e1-a5cf16483993.png)
