### ISSUE TITLE
圆环图 均分大小

### ISSUE THREAD

**Issue by wangzhijun-github** [apache/incubator-echarts#8898]
![image](https://user-images.githubusercontent.com/24643503/44321622-9c98ea80-a47b-11e8-90e3-dd0a8288ca2c.png)
版本是：4.1.0
问题：使用圆环图配置的时候，有时候会出现这种均分大小的问题，其他时候又是按照比例就行区分的
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
什么问题？

**Comment by wangzhijun-github** [comment]
饼图有时候会均分给出的数据(如上图所示)，但是提示框里面的数据大小却不一样。有时候又是正常按照大小进行比列划分。

**Comment by wangzhijun-github** [comment]
每次画图我都会clear了一下的

**Comment by Ovilia** [comment]
配置项提供一下
