### ISSUE TITLE
类型转换有问题每次转换变成false

### ISSUE THREAD

**Issue by 13407316406** [apache/incubator-echarts#8901]
### One-line summary [问题简述]
每次bar和折线转换时 起点发生变化,line boundaryGap 变成了false

 newOption[axisType][axisIndex].boundaryGap = type === 'bar' ? true : false;

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

折线柱状变换不发生起点变化
 newOption[axisType][axisIndex].boundaryGap = type === 'bar' || 'line' ? true : false;

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这是不同类型图表的设置不同引起的，建议自行通过 setOption 设置
