### ISSUE TITLE
datazoom走势与折线图走势不一致

### ISSUE THREAD

**Issue by zpeento** [apache/incubator-echarts#8903]
### One-line summary [问题简述]
折线图x轴类型设为'time',时间点不均匀
xAxis: {
     type: 'time',
},
datazoom显示的走势与折线实际走势不一致，需要对datazoom进行什么配置才能让datazoom的趋势与折线图趋势保持一致呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
同 #8186
