### ISSUE TITLE
双y轴曲线，但x轴刻度不一样

### ISSUE THREAD

**Issue by yqyily** [apache/incubator-echarts#8906]
### One-line summary [问题简述]
想实现双y轴曲线，但是两条线的x轴刻度不一样，比如第一条线只有在x轴是2,4,6,8，9,10下有数值，而第二条线只有在1,2,5,7,9下有数值，这样的两天曲线可以用双y轴表示吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以，没有值的用 `'-'` 表示，比如：`[100, 20, '-', 30]`
