### ISSUE TITLE
gl  实例页面打不开

### ISSUE THREAD

**Issue by caozengzeng** [apache/incubator-echarts#8911]
gl  加载特别慢，加载完了也出不来，控制台报错！！！！！！！！！！！！！！！

**Comment by YuanZhencai** [comment]
gl 请求报错啊，官网的证书也是不安全的啊，求赶快修复下啊

**Comment by YuanZhencai** [comment]
刚访问了下可以查看了 http是好的，  但是 https 的能查到列表数据，但是图表不能展示。现在 过了会  gl 网站好像又挂了

**Comment by YuanZhencai** [comment]
![image](https://user-images.githubusercontent.com/4961592/44440795-528b4280-a5fc-11e8-9d9d-69049305f6e5.png)
