### ISSUE TITLE
现在gallery所有例子都被清空了？

### ISSUE THREAD

**Issue by aweffr** [apache/incubator-echarts#8917]
### One-line summary [问题简述]
[http://gallery.echartsjs.com](http://gallery.echartsjs.com) 打开无实例。
具体图表页面如 [http://gallery.echartsjs.com/editor.html?c=xryHrMdE2M](http://gallery.echartsjs.com/editor.html?c=xryHrMdE2M)
也无法打开。

主机在电信网上。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:/
+ Browser version [浏览器类型和版本]: Chrome V67
+ OS Version [操作系统类型和版本]: Win10

### Expected behaviour [期望结果]

能正常访问gallery。

### ECharts option [ECharts配置项]
不涉及option。

### Other comments [其他信息]

![gallery-exception](https://user-images.githubusercontent.com/17469534/44450478-a3626180-a623-11e8-82e2-7a123c76244f.png)
![gallery-exception2](https://user-images.githubusercontent.com/17469534/44450479-a52c2500-a623-11e8-9b88-65456ddd2bdc.png)

**Comment by aweffr** [comment]
今天（2018-8-23）恢复了

**Comment by Ovilia** [comment]
服务器不稳定，在排查中
