### ISSUE TITLE
data zoom should only work for x axis on connected charts

### ISSUE THREAD

**Issue by vimalraj-ponnusamy** [apache/incubator-echarts#8920]
In Connected charts of echarts while datazoom using the tool box , It is zooming both x axis and y axis for all the connected charts. but xaxis should only be connected not the yaxis. have any one have the idea to acheive this

**Comment by tchaton** [comment]
Yes, having the same issue. As the y scale isn't the same, this causes lot of issues. I tried modifying the events but without success.

**Comment by Itschotsch** [comment]
Looks like https://github.com/apache/echarts/issues/17504.

**Comment by djaszak** [comment]
Any chance for this to still be catched up?
