### ISSUE TITLE
connectnulls not working properly with step chart

### ISSUE THREAD

**Issue by vimalraj-ponnusamy** [apache/incubator-echarts#8921]
### One-line summary [问题简述]

chart data with null for step charts. if we connect nulls using connectNulls property,
it is showing as line chart not as step chart

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

It should show as step chart

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: 'Step Line'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['Step Start', 'Step Middle', 'Step End']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'Step Start',
            type:'line',
            step: 'start',
            connectNulls:true,
            data:[120, null, 101, 134, 90, 230, 210]
        },
        {
            name:'Step Middle',
            type:'line',
            step: 'middle',
             connectNulls:true,
            data:[220, 282, 201, 234, null, 430, 410]
        },
        {
            name:'Step End',
            type:'line',
            step: 'end',
             connectNulls:true,
            data:[450, 432, 401, null, 590, 530, 510]
        }
    ]
};


```

**Comment by cuijian-dexter** [comment]
It's `series[i].connectNulls` instead of `series[i].data[0].connectNulls`.

**Comment by vimalraj-ponnusamy** [comment]
Data Sample also   series[i].connectNulls only right ? Its not series[i].data[0].connectNulls.

**Comment by cuijian-dexter** [comment]
@vimalraj-ponnusamy  `connectNulls` is effective for all data

**Comment by vimalraj-ponnusamy** [comment]
@cuijian-dexter  can you give the correct example for the same

**Comment by vimalraj-ponnusamy** [comment]
@cuijian-dexter 
still not working nulls are not getting connected,
attached the image for your reference
![capture](https://user-images.githubusercontent.com/16756355/52103344-365bea80-260b-11e9-958e-7ee0e1c6c646.PNG)
