### ISSUE TITLE
charts 图例部分可以点击，部分不可以点击

### ISSUE THREAD

**Issue by anneyangyue** [apache/incubator-echarts#8924]
### One-line summary [问题简述]

一共有5个图例，希望前2个可以点击，后3个不可以点击，前2个只是展示的效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
在获取到 [legend 更改](http://echarts.baidu.com/api.html#events.legendselectchanged)之后判断下是哪个，然后如果是不可点击的，再通过 [dispatchAction](http://echarts.baidu.com/api.html#action.legend.legendSelect) 重新选中……

**Comment by anneyangyue** [comment]
非常感谢，问题解决了
