### ISSUE TITLE
足够宽度，类目数据显示不全

### ISSUE THREAD

**Issue by jin9999** [apache/incubator-echarts#8937]
### One-line summary [问题简述]
http://echarts.baidu.com/examples/editor.html?c=bar-tick-align
缩小柱状图宽度之后，类目数据重叠部分自动隐藏，再放大柱状图图宽度到足够显示所有类目之后，类目数据之前重叠不显示部分仍然不显示。
在3.8.5版本不存在这个问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: windows 7

### Expected behaviour [期望结果]
足够宽度时，类目数据能全部显示。

### ECharts option [ECharts配置项]

```javascript
app.title = '坐标轴刻度与标签对齐';

option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220]
        }
    ]
};

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/22189628/44559980-ecc7c380-a77f-11e8-8297-0dfb9f4c17d1.png)

**Comment by maoyr** [comment]
+1
