### ISSUE TITLE
Treemap keep depth when removing data

### ISSUE THREAD

**Issue by alesbrelih** [apache/incubator-echarts#8939]
Is there a chance of doing this? Since the setOption resets the selected depth.

**Comment by alesbrelih** [comment]
Or if there is a way to travel after the reset to the previously selected node. I've tried with "dispatchAction( type: 'treemapRootToNode' or 'treemapZoomToNode' ) but no success

**Comment by Ovilia** [comment]
It should work with `treemapZoomToNode`. We will check it out later.
