### ISSUE TITLE
折线图横坐标每个间隔内展示的数据点个数能不同吗

### ISSUE THREAD

**Issue by cxkobe** [apache/incubator-echarts#8940]
![image](https://user-images.githubusercontent.com/23737315/44570227-b3a74780-a7af-11e8-81c3-f77cf0aeb0c1.png)
请问：如图，每个区间能展示的数据点个数能不相同吗，比如业务场景：横坐标从0点到12点分布，每个间隔是一个小时，然后0点到1点之间我想展示5个数据点，1点到两点之间展示4个数据点，这个有办法实现吗

**Comment by Ovilia** [comment]
可以，横坐标用 category 不要用 time
