### ISSUE TITLE
Emphasis styling is not properly documented for custom series

### ISSUE THREAD

**Issue by hon2a** [apache/incubator-echarts#8941]
### Documentation for custom series' `renderItem` is missing any mention of how to apply styling set in `series[i].emphasis`.

All examples in the documentation show application of `style: api.style()` in `renderItem`, but that doesn't do anything about `emphasis`. After catching the `api` in runtime and examining its contract, I found that it also provides a `styleEmphasis` method and that I can set the returned object's `styleEmphasis` to control its emphasis styling.

### Version & Environment [版本及环境]

_Irrelevant._

### Expected behaviour [期望结果]

Documentation for custom series' `renderItem` should clearly describe how to apply emphasis styling.

### ECharts option

```javascript
option = {
  // ...
  series: [{
    type: 'custom',
    itemStyle: {
      color: 'red'
    },
    emphasis: {
      itemStyle: {
        color: 'cyan'
      }
    },
    renderItem(params, api) {
      // ...
      return {
        // ...,
        style: api.style(), // the documentation shows this ...
        styleEmphasis: api.styleEmphasis() // ... but never mentions this
      }
    },
    // ...
  }]
}
```

**Comment by Ovilia** [comment]
The link to `series.itemStyle.emphasis` in [styleEmphasis](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-custom.renderItem.arguments.api.styleEmphasis) is wrong. It's `https://ecomfe.github.io/echarts-doc/public/en/option.html#series-custom.itemStyle.emphasis` now, but should be `https://ecomfe.github.io/echarts-doc/public/en/option.html#series-custom.emphasis.itemStyle`. @100pah
