### ISSUE TITLE
tooltip默认类目值前面的有色圆点不能够调节大小

### ISSUE THREAD

**Issue by yaya0144** [apache/incubator-echarts#8945]
在tooltip中重新设置了字体大小
 tooltip: {
            trigger: 'axis' ,
            textStyle: {
                fontSize:24
            }
        }

悬浮框的字变大了 ，但是前面的小圆点没有变化

期望效果:类目前小圆点可以调节大小

**Comment by yaya0144** [comment]
我暂时改了源码 
function getTooltipMarker(opt, extraCssText) {
    opt = isString(opt) ? {color: opt, extraCssText: extraCssText} : (opt || {});
    var color = opt.color;
    var type = opt.type;
    var extraCssText = opt.extraCssText;

    if (!color) {
        return '';
    }

    return type === 'subItem'
        ? '<span style="display:inline-block;vertical-align:middle;margin-right:8px;margin-left:3px;'
            + 'border-radius:4px;width:4px;height:4px;background-color:'
            + encodeHTML(color) + ';' + (extraCssText || '') + '"></span>'
        : '<span style="display:inline-block;margin-right:5px;'
            + 'border-radius:20px;width:20px;height:20px;background-color:'
            + encodeHTML(color) + ';' + (extraCssText || '') + '"></span>';
}

**Comment by Ovilia** [comment]
通过 http://echarts.baidu.com/option.html#tooltip.extraCssText 修改样式
