### ISSUE TITLE
k线图，做出来的均线和kdj怎么线上都有圆圈求解答

### ISSUE THREAD

**Issue by wanzhen** [apache/incubator-echarts#8946]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
请提供配置项
