### ISSUE TITLE
雷达图中如何显示数据的label，其中label中不仅显示具体的数据，还需要显示对应的indicator的name

### ISSUE THREAD

**Issue by katherinebai** [apache/incubator-echarts#8949]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
似乎现在不支持？@100pah
