### ISSUE TITLE
Get the wrong color info of sunburst area 

### ISSUE THREAD

**Issue by yingxu9871** [apache/incubator-echarts#8952]
### One-line summary [问题简述]

Get the wrong color info of sunburst area . Could reproduce by echart demo. 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Other comments [其他信息]

1.  Copy  the following code in the echart demo: http://echarts.baidu.com/examples/editor.html?c=sunburst-simple to show the color in the tooltip.  Note copy the code in the "options" part.

    tooltip: {
            formatter: function (info) {
                let tooltipHtml=`<div style='width: 38px;
                            height: 5px;
                            border-radius: 20px;
                            background-color:${info.color};'>
                            </div>`
            return tooltipHtml;
            },
    },

2.  move the mouse to the "cousin Jenny" area, which should show the "blue" color bar in the tooltip, but it is not.

![image](https://user-images.githubusercontent.com/28331441/44645026-bbadf400-aa08-11e8-9110-d099a8edf24d.png)

3. copy the same code in another sunburst demo: http://echarts.baidu.com/examples/editor.html?c=sunburst-drink, its show the right color bar. 

![image](https://user-images.githubusercontent.com/28331441/44645137-219a7b80-aa09-11e8-8f26-1d8771549e62.png)

**Comment by weizhanzhan** [comment]
最后咋解决的？

**Comment by plainheart** [comment]
@weizhanzhan 测试了下，我认为这个问题在当前ECharts版本中应该已经被解决了。
