### ISSUE TITLE
请问时间数据支持堆叠吗？

### ISSUE THREAD

**Issue by maoyr** [apache/incubator-echarts#8955]
### One-line summary [问题简述]
在做甘特图，需要时间数据进行堆叠，但好像现在不支持时间数据的堆叠展示？

因为要用 dataZoom，如果把数据转换为数值的话，堆叠是正常的，但 dataZoom 就不能用了。

如果设置 barGap 为 '-100%'，可以使柱子重叠，在此基础上，增加了一个坐标系为隐藏，但 barGap 对 series 中所有柱子生效，还是不能实现甘特图。barGap 能否设置为只针对某一坐标系下的 series 柱子重叠？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

在官网运行下面的例子

### Expected behaviour [期望结果]
希望时间数据可以堆叠，或者有什么方法将时间数据转换然后展示正常，并且 dataZoom 可用。

### ECharts option [ECharts配置项]

```javascript
function  FormatTime(oldTime){    
    let newTime = [];
    oldTime.forEach((time)=>{
        newTime.push( new Date(time) );
    })
    return newTime ;
}

option = {
    tooltip: {
        trigger: 'axis'
    },
    xAxis: [
        {
            type: 'time'
           
        }
    ],
    yAxis: [
        {
            type: 'category',
            data: ['task1','task2','task3','task4','task5' ]
        }
    ],
     dataZoom: [ {
        type: 'slider'
    }],
    series: [
        {
            name:'计划开始时间',
            type: 'bar',
            stack: '计划',
            itemStyle: {
                normal: {
                    borderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                },
                emphasis: {
                    borderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                }
            },
            data: FormatTime ([
                "2018/01/01", 
                "2018/02/01", 
                "2018/03/01", 
                "2018/04/01", 
                "2018/05/01"
            ])
        },
        {
            name:'计划结束时间',
            type: 'bar',
            stack: '计划',
            data: FormatTime ([
                "2018/02/01", 
                "2018/03/01", 
                "2018/04/01", 
                "2018/05/01", 
                "2018/06/01"
            ])
        },
        {
            name:'实际开始时间',
            type: 'bar',
            stack: '实际',
            itemStyle: {
                normal: {
                    borderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                },
                emphasis: {
                    borderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                }
            },
            data: FormatTime ([
                "2018/01/01", 
                "2018/03/01", 
                "2018/04/01", 
                "2018/05/01", 
                "2018/06/01"
            ])
        },
        {
            name:'实际结束时间',
            type: 'bar',
            stack: '实际',
            data: FormatTime ([
                "2018/03/01", 
                "2018/04/01", 
                "2018/05/01", 
                "2018/06/01", 
                "2018/07/01"
            ])
        }
        
    ]
};


```

**Comment by Ovilia** [comment]
传入数据的时候还是传数字，而不是时间，因为理论上时间点和时间点的叠加是没有意义的，只有时长的叠加才是有意义的。

**Comment by Ovilia** [comment]
数据可以这样处理，`new Date().getTime()` 作为实际数据，再用 `formatter` 转为日期时间类型，不影响使用 dataZoom

**Comment by maoyr** [comment]
目前静止状态展示正常，但区域缩放时，柱子会超出窗口范围，展示错乱。请问是哪里没设置好吗？
`
function GetTime( oldTime ){
	let newTime = [];
	
	oldTime.forEach((time)=>{
     newTime.push( new Date(time).getTime());
	})
	
	return newTime;
}

function GetDuration( endTime, startTime ){
	let duration = [];
	
	endTime.forEach(( time, index )=>{
		duration.push( time - startTime[index] );
	})
	
	return duration;
}

const startTime_plan = GetTime([
	'2018/01/01', 
	'2018/02/01', 
	'2018/03/01', 
	'2018/04/01', 
	'2018/05/01'
]);
const endTime_plan = GetTime([
	'2018/06/01', 
	'2018/07/01', 
	'2018/08/01', 
	'2018/09/01', 
	'2018/10/01'
]);
const startTime_actual = GetTime([
	'2018/02/01', 
	'2018/03/01', 
	'2018/04/01', 
	'2018/05/01', 
	'2018/06/01'
]);
const endTime_actual = GetTime([
	'2018/07/01', 
	'2018/08/01', 
	'2018/09/01', 
	'2018/10/01', 
	'2018/11/01'
]);
const startTime = new Date('2018/01/01').getTime();
const duration_plan = GetDuration( endTime_plan, startTime_plan );
const duration_actual = GetDuration( endTime_actual, startTime_actual );

function FormatTime(oldTime){    
    let newTime = [];
	
    oldTime.forEach((time)=>{
        newTime.push( time - startTime );
    })
    return newTime ;
}
option = {
    legend:{
        data:[ '计划时长', '实际时长' ]
    },
    tooltip: {
        trigger: 'axis'
    },
    xAxis: [
        {
            type: 'value',
            axisLabel: { 
                formatter: (value) => {
                    let tempValue = value + startTime;
                    let year = new Date(tempValue).getFullYear();
                    let month = new Date(tempValue).getMonth()+1;
                    let date = new Date(tempValue).getDate();
                    
                    return year+'-'+month+'-'+date;
                }
            }
        }
    ],
    yAxis: [
        {
            type: 'category',
            data: ['task1','task2','task3','task4','task5' ]
        }
    ],
     dataZoom: [ {
        type: 'slider',
        xAxisIndex: 0,
        labelFormatter: (value) => {
            let tempValue = value + startTime;
            let year = new Date(tempValue).getFullYear();
            let month = new Date(tempValue).getMonth()+1;
            let date = new Date(tempValue).getDate();
            
            return year+'-'+month+'-'+date;
        }
    }],
    series: [
        {
            name:'计划开始时间',
            type: 'bar',
            stack: '计划',
            data: FormatTime(startTime_plan)
        },
        {
            name:'计划时长',
            type: 'bar',
            stack: '计划',
            data: duration_plan
        },
        {
            name:'计划结束时间',
            type: 'bar',
            data: FormatTime (endTime_plan)
        },
        {
            name:'实际开始时间',
            type: 'bar',
            stack: '实际',
            data: FormatTime (startTime_actual)
        },
        {
            name:'实际时长',
            type: 'bar',
            stack: '实际',
            data: duration_actual
        },
        {
            name:'实际结束时间',
            type: 'bar',
            data: FormatTime (endTime_actual)
        }
        
    ]
};
`

**Comment by Ovilia** [comment]
在是一个已知的 bug #8935 会尽快修复。别的没问题的话可以 close 这个 issue 了。

**Comment by maoyr** [comment]
好的。
