### ISSUE TITLE
Documentation error: Add "{normal:" to scatter label

### ISSUE THREAD

**Issue by RichardJECooke** [apache/incubator-echarts#8957]
On this page https://ecomfe.github.io/echarts-doc/public/en/option.html#series-scatter.label you don't mention the property `normal` in the label. And it doesn't work in version 4 of Echarts if you try to use it.

Instead this example of yours, https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-label-rotation, correctly shows on line 71 that you need to include a subproperty called `normal`. Then my chart shows labels.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
`normal` can be ignored since ECharts 4.0, but it also works if there is `normal` to compat ECharts 3. Here's an example, `fontSize` works with or without `normal`.
```js
option = {
    xAxis: {},
    yAxis: {},
    series: [{
        symbolSize: 20,
        data: [
            [10.0, 8.04],
            [8.0, 6.95]
        ],
        type: 'scatter',
        label: {
            show: true, 
            fontSize: 30
        }
    }]
};
```
