### ISSUE TITLE
框选型数据区域缩放组件（dataZoomSelect）

### ISSUE THREAD

**Issue by chenjus** [apache/incubator-echarts#8964]
### One-line summary [问题简述]

框选型数据区域缩放组件（dataZoomSelect）不能设置数据选择框的背景颜色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]:  5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0
+ OS Version [操作系统类型和版本]:Win8

### Expected behaviour [期望结果]
因为我grid的背景颜色是黑色，默认的数据选择框背景色也是黑色的，所以导致选择数据时看不见数据选择框，希望可以设置数据选择框的背景颜色，就像dataZoomSlider有一dataBackground属性一样。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
dataZoomSelect 是什么？是 dataZoom 么？

**Comment by chenjus** [comment]
@Ovilia 是在toolbox里的dataZoom

toolbox.feature.dataZoom

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#toolbox.feature.dataZoom.iconStyle.color 是这个么，不行就截图看看你要改哪部分~

**Comment by chenjus** [comment]
不是这个，这个是设置toolbox图标的颜色，我需要设置的是数据选择框的背景色，如图中黑色阴影部分的颜色：

**Comment by chenjus** [comment]
不是这个喔，这个是toolbox图标的颜色，我需要设置的是如下图中黑色阴影部分的颜色：
![Image](https://github.com/chenjus/MyApp/blob/master/2.png)

https://github.com/chenjus/MyApp/blob/master/2.png

**Comment by PandaTsui** [comment]
我也遇到了这个问题，请问现在解决了吗？

**Comment by yangchao35071** [comment]
同问, dataZoom中没有属性可以设置鼠标选择区域的颜色
