### ISSUE TITLE
为什么我给涟漪动画设置了时间（period），它还一直动，为什么

### ISSUE THREAD

**Issue by LIHAO520** [apache/incubator-echarts#8965]
### One-line summary [问题简述]

 type: 'effectScatter',  //带着涟漪特效动画的散点图   
                            coordinateSystem: 'bmap',
                            data: convert(data),
                            symbolSize: 20,
            
                            showEffectOn: 'render', //配置何时显示特效。 'render' 绘制完成后显示特效。'emphasis' 高亮（hover）的时候显示特效。
            
                            rippleEffect: {   //涟漪动画的相关配置  
                                period:3,
                                brushType: 'stroke'
                            },
                            hoverAnimation: true,  //是否开启鼠标 hover 的提示动画效果。
                            itemStyle: {
                                normal: {
                                    color: '#ddb926',
                                    shadowBlur: 10,
                                    shadowColor: '#333'
                                }
                            },
                            zlevel: 1

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这个配置项表示周期（文档已改进，还没上线），如果想定时关闭，就 `setTimeout` 把这个系列删了即可。

**Comment by LIHAO520** [comment]
定时把这个系列删掉？怎么写？求教

**Comment by Ovilia** [comment]
给你写了个例子 http://gallery.echartsjs.com/editor.html?c=xr1zoX07D7&v=1

**Comment by LIHAO520** [comment]
那这个大概什么时候上线，删除了我的数据就没了啊，顺便提另外一个问题，是关于散点图的悬浮提示框，散点图的提示框它的文本是怎么来的，如何去自定义修改文本的内容，不是用tooltip

**Comment by Ovilia** [comment]
“删除了我的数据就没了啊”是什么意思？你要的效果是到时间后这些点没有涟漪么？可以 setTimeout 里把 `rippleEffect.period` 设为 0 就不动里。tooltip 内容看下 http://echartsjs.com/option.html#series-scatter.tooltip.formatter

**Comment by LIHAO520** [comment]
@Ovilia   这个悬浮提示框自定义的   如何换行啊，只能在一行拼接吗

**Comment by LIHAO520** [comment]
你说文档已上线，是最新的版本是吗？为什么我设置了这个period还是没用呢？我在你们官网里面加还是没生效，难道你们官网不是最新版本的吗

**Comment by Ovilia** [comment]
文档更新的是“动画的周期，秒数。”

正如我上面跟你解释的：
> 这个配置项表示周期，如果想定时关闭，就 setTimeout 把这个系列删了即可。

周期懂不懂？周期是 4 秒的意思是，4 秒后重复开始动画，不是 4 秒后结束动画，就是这么设定的。

给你写了个完整的例子，你再好好理解下： http://gallery.echartsjs.com/editor.html?c=xLjxAXRtNt&v=2
