### ISSUE TITLE
为什么我调用了clear()方法，我在切换的时候还是会有上一次的数据存在，只不过是静态的，像个残影

### ISSUE THREAD

**Issue by LIHAO520** [apache/incubator-echarts#8970]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
代码？

**Comment by LIHAO520** [comment]
https://segmentfault.com/q/1010000016199600这个链接里你可以看到代码，不知道什么原因，clear（）方法清除图表组件的时候是有时间间隔的吗
