### ISSUE TITLE
实例（全国主要城市空气质量）显示错误

### ISSUE THREAD

**Issue by fancyzhou** [apache/incubator-echarts#8973]
### One-line summary [问题简述]
在该热力图上，鼠标移到气泡上显示的是该城市的y坐标值'val[1]'（应该为value值’val[2]‘）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:这个是你们的官方实例，，
+ Browser version [浏览器类型和版本]:chrome 68
+ OS Version [操作系统类型和版本]:windows10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by fancyzhou** [comment]
![tim 20180830094019](https://user-images.githubusercontent.com/19216022/44824734-cac7b880-ac39-11e8-8fc3-a58d8bc7d290.png)

**Comment by LIHAO520** [comment]
它显示的是纬度，我也在做这样的一个项目，在tooltip里用formatter改是可以的，但是不知道你要效果最终是哪样；
