### ISSUE TITLE
柱状图柱子存在偏移

### ISSUE THREAD

**Issue by HuangWenJ** [apache/incubator-echarts#8976]
### One-line summary [问题简述]
绘制柱状图时，设置x轴为非类目轴，并设定了xAxis.max，xAxis.min和xAxis.interval后绘出的柱状图貌似存在偏移，第一个柱子对应的x坐标为0，但是却不和0刻度线对齐，而是超过了y轴，详情可以运行option配置项得知（不知道为什么issue上传不了截图png文件）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0.rc2/echarts-en.common.js
+ Browser version [浏览器类型和版本]:Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]:Ubuntu 18.04.1 LTS

### Expected behaviour [期望结果]
第一个柱子的左边缘和y轴重合对齐，不要超过y轴

### ECharts option [ECharts配置项]

```javascript
option = {
    legend:{
        data:["PassengerId"]
    },
    xAxis: {
        type: 'value',
          min:0,
          max:900,
          interval:25,
        
    },
    yAxis: {

    },
    series: [{
        boundaryGap:"1%",
        name:"PassengerId",
        data: [[0, 24],[22.5, 20],[45, 25],[67.5, 20],[90, 25],[112.5, 20],[135, 25],[157.5, 20],[180, 25],[202.5, 20],[225, 25],[247.5, 20],[270, 25],[292.5, 20],[315, 25],[337.5, 20],[360, 25],[382.5, 20],[405, 25],[427.5, 20],[450, 25],[472.5, 20],[495, 25],[517.5, 20],[540, 25],[562.5, 20],[585, 25],[607.5, 20],[630, 25],[652.5, 20],[675, 25],[697.5, 20],[720, 25],[742.5, 20],[765, 25],[787.5, 20], [810, 25],[832.5, 20],[855, 25],[877.5, 12],[900, 0]],
        type: 'bar'
    }]
};

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#xAxis.boundaryGap

**Comment by HuangWenJ** [comment]
十分感谢回复，我之前已经试过设置xAxis.boundaryGap，但是不管是设置为true或者是['20%', '20%']，都没有效果，而且文档也说了在设置 xAxis.min 和 xAxis.max 后设置xAxis.boundaryGap无效，请问还有其他的解决方法吗？

**Comment by Ovilia** [comment]
类似这样：

```js
var offset = 5;
var data = [[0, 24],[22.5, 20],[45, 25],[67.5, 20],[90, 25],[112.5, 20],[135, 25],[157.5, 20],[180, 25],[202.5, 20],[225, 25],[247.5, 20],[270, 25],[292.5, 20],[315, 25],[337.5, 20],[360, 25],[382.5, 20],[405, 25],[427.5, 20],[450, 25],[472.5, 20],[495, 25],[517.5, 20],[540, 25],[562.5, 20],[585, 25],[607.5, 20],[630, 25],[652.5, 20],[675, 25],[697.5, 20],[720, 25],[742.5, 20],[765, 25],[787.5, 20], [810, 25],[832.5, 20],[855, 25],[877.5, 12],[900, 0]];
for (var i = 0; i < data.length; ++i) {
    data[i] = [data[i][0] + offset, data[i][1]];
}

option = {
    legend:{
        data:["PassengerId"]
    },
    xAxis: {
        type: 'value',
      min:0,
      max:900,
      interval:25,
        offset: 10
    },
    yAxis: {

    },
    series: [{
        boundaryGap:"1%",
        name:"PassengerId",
        data: data,
        type: 'bar',
        barWidth: 10
    }]
};
```

**Comment by HuangWenJ** [comment]
感激不尽！！只能先用着这种方法，还是很奇怪柱子为什么不能和坐标轴对齐？

**Comment by Ovilia** [comment]
因为你是在 xy 轴都是数值轴的坐标系里放柱状图，而柱状图的中间用来表示其对应的数字，而不是左侧，因此如果第一个数据 x 值是 0 的话，意味着第一个柱子的中间是 0，也就是 y 轴的位置。
这种需求本来就不太常见（可能在某些场景下是合理的），通常柱状图都是横轴是类目轴（category），纵轴是数值轴。

**Comment by jimStyle88** [comment]
我也遇到类似的情况，设置 xAxis.min = "dataMin"  和 xAxis.max = max:"dataMax"  后
`series: {
          label: {
            show: true,
            fontSize: 22,
            color: '#000',
          },
          boundaryGap:["20%","20%"],
          barMaxWidth:50,
          type: 'bar',
        },`
![image](https://user-images.githubusercontent.com/20588608/48468485-fadd2b80-e826-11e8-8565-4c034f2b0124.png)
往下偏移了，，如果 xAxis.min = 50  和 xAxis.max = 200  表现如下
![image](https://user-images.githubusercontent.com/20588608/48468585-3ed03080-e827-11e8-9cff-bd7fcab5564f.png)
为什么2种设置表现差这么多。
