### ISSUE TITLE
这样子的柱状图怎么画?

### ISSUE THREAD

**Issue by harae** [apache/incubator-echarts#8977]
![image](https://user-images.githubusercontent.com/19524407/44831357-c363d780-ac58-11e8-9045-00f56bf51aac.png)

需要 Y轴 从大到小  x轴在下，柱状也从下开始
使用反转的话 柱状图的根是在上面的 不太行。。
求解

**Comment by Ovilia** [comment]
那就自己改 yAxis 的 label.formatter 吧

**Comment by harae** [comment]
使用堆叠实现了，谢谢老哥

发自冯巍鑫
