### ISSUE TITLE
echarts  Uncaught TypeError: Cannot read property 'dataToCoord' of undefined

### ISSUE THREAD

**Issue by xhochipe** [apache/incubator-echarts#8978]
One-line summary [问题简述]

 Version & Environment [4.1.0 win10]
+ ECharts version [ECharts [4.1.0 ]:
+ Browser version [chrome  65.0.3325.181 ]:
+ OS Version [win10 ]:

 ECharts option [ECharts配置项]
javascript
var option =  {
	"series": [
		{
			"type": "radar",
			"areaStyle": {
				"normal": {}
			},
			"data": [
				{
					"value": [
						compliance.score,
						market.score,
						opinion.score,
						manage.score
					],
				}
			],
			itemStyle: {
				emphasis: {
					shadowBlur: 10,
					shadowOffsetX: 0,
					shadowColor: 'rgba(0, 0, 0, 0.5)'
				}
			}
		}
	],
	 tooltip: {
		trigger: 'axis',
		axisPointer: {
			type: 'cross'
		},
		backgroundColor: 'rgba(245, 245, 245, 0.8)',
		borderWidth: 1,
		borderColor: '#ccc',
		padding: 10,
		textStyle: {
			color: '#000'
		},
		position: function (pos, params, el, elRect, size) {
			var obj = {top: 10};
			obj[['left', 'right'][+(pos[0] < size.viewSize[0] / 2)]] = 30;
			return obj;
		},
		extraCssText: 'width: 170px'
	},
	"radar": {
		"radius": 120,
		"name": {
			"textStyle": {
				"fontWeight": 600,
				"padding": [
					3,
					5
				],
				"color": "#545454",
				"borderRadius": 3,
				"fontSize": 12
			}
		},
		"indicator": [
			{
				"name": '合规',
				"max": 100
			},
			{
				"name": "市场 ",
				"max": 100
			},
			{
				"name": "形象 ",
				"max": 100
			},
			{
				"name": "经营 ",
				"max": 100
			}
		],
		triggerEvent:true
	}
};

**Comment by Ovilia** [comment]
`ReferenceError: compliance is not defined`
给个能直接跑的例子吧
