### ISSUE TITLE
tooltip时，X轴怎样设置高亮

### ISSUE THREAD

**Issue by vijay19920608** [apache/incubator-echarts#8983]
tooltip时，让X轴高亮
![_20180830182107](https://user-images.githubusercontent.com/28383371/44845940-7fd19380-ac81-11e8-8427-5fcc0f6aea9b.png)

**Comment by Ovilia** [comment]
会有点麻烦，思路是，先获取到高亮事件：http://echarts.baidu.com/api.html#events.%E9%BC%A0%E6%A0%87%E4%BA%8B%E4%BB%B6
获得对应 X 轴 id，然后手动通过 setOption 改变相应样式。

**Comment by vijay19920608** [comment]
你好，高亮事件是哪一个

**Comment by vijay19920608** [comment]
tooltip的显示和隐藏只能派发事件吧？如果有获取tooltip的显示和隐藏事件就好办，不然，就算你通过click事件去改变当然x轴的颜色，你却监听不到tooltip隐藏事件，然而就不能把原来高亮的x轴颜色改回来

**Comment by Ovilia** [comment]
好像是没法监听 Tooltip 事件……
