### ISSUE TITLE
tooltip 移动端Bug

### ISSUE THREAD

**Issue by vijay19920608** [apache/incubator-echarts#8987]
移动端当触发tooltip时，页面滑动后，tooltip的提示框就会被柱状图给遮挡了。

![_20180831102110](https://user-images.githubusercontent.com/28383371/44889247-a20df480-ad07-11e8-99a5-d98bac374bcb.png)

希望触发tooltip后，页面滑动，或者操作了其他区域的动作后，tooltip的提示框自动隐藏，只有再次点击这个图表才触发tooltip

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html 复现一下简单的例子

**Comment by Ovilia** [comment]
如何复现 tooltip 在之下？我这边手机和 PC 都没有这个问题。事实上除非你有多个 Canvas 层，也不可能位于之下，你可以审查元素看看。
