### ISSUE TITLE
力矢量图如何设置坐标

### ISSUE THREAD

**Issue by ZaZaLee** [apache/incubator-echarts#8999]
### One-line summary [问题简述]
使用力矢量图设置动态图形展示，期望能够设置图标的初始位置，
从目前的option里面找不到x,y坐标的参数

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.2.7
+ Browser version [浏览器类型和版本]:chrome 68.0.3440.106
+ OS Version [操作系统类型和版本]:mac & windows

### Expected behaviour [期望结果]

期望能够设置力矢量图图标的初始坐标位置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
如果 “力矢量图” 指的是 “力导向图” 的话，因为是自动布局的，所以设置初始位置，似乎没有什么意义？

**Comment by ZaZaLee** [comment]
自动布局不能设置初始位置吗，因为自动布局在数量较多的时候会比较杂乱
就是期望能够设置位置，不用自动布局。

**Comment by Ovilia** [comment]
不是有 xy 么 http://echartsjs.com/option.html#series-graph.data.x
