### ISSUE TITLE
Tooltip in line chart.

### ISSUE THREAD

**Issue by geekboy0801** [apache/incubator-echarts#9000]
### One-line summary [问题简述]
Triggering tooltip when moving mouse on the *line chart*.
Highcharts tooltip triggers smoothly when the mouse is moving on the chart apart from the points which make up line chart, but Echarts doesn't in my experience.
Echarts only triggers tooltip near the points.

Echart: https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-simple
Highchart: https://jsfiddle.net/208odfjb/1/

Can i implement the same behavior by means of Echarts or not?

**Comment by 100pah** [comment]
Thanks.

I think `tooltip.trigger: 'axis'` make similar experience like highcharts does:

```js
option = {
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'none'
        }
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};
```

**Comment by geekboy0801** [comment]
Hi, @100pah .
Thank you for your kind reply.

But what do you think about the case of too many series, such as my case?
In such cases, tooltip should be too long to show it and as a result it overflows.

In my poor view of point, this is a simple bug.

**Comment by 100pah** [comment]
Excuse me I can not find where your case is. Is it in another issue?
Generally, when too many series cause the size of the default tooltip longer than viewport, 
we probably customize the tooltip by `tooltip.format`, switch it to another simple style.

**Comment by Ovilia** [comment]
Close due to low activity.
