### ISSUE TITLE
bmap严重抖动

### ISSUE THREAD

**Issue by vijay19920608** [apache/incubator-echarts#9002]
在bMap的基础上，增加闪点，拖动地图的时候，会抖动。这个很严重，有大神解决么

**Comment by vijay19920608** [comment]
已解决，忘记引入baidu.js

**Comment by vijay19920608** [comment]
还有一个问题，在bMap的基础上，增加闪点，拖动地图的时候，会抖动。这个很严重，有大神解决么

**Comment by 100pah** [comment]
不知是什么抖动，闪点是指什么。

**Comment by Ale-cc** [comment]
解决办法 tooltip 设置延迟、关闭动画，新版本也还存在这问题。
`
tooltip: {
            showDelay: 500,
            hideDelay: 500,
            transitionDuration: 0,
        },
`
