### ISSUE TITLE
echarts3.0 4.0版本如何使用自定义热力图

### ISSUE THREAD

**Issue by aaa583834691** [apache/incubator-echarts#9006]
RT echarts2版本是有自定义热力图的·但是现在用Echarts3之后 需要坐标或者地图才能实现热力图·

   需求就是···我有一张图片在底层··我需要在这张图片的上面显示热力图··
  例子：http://echarts.baidu.com/echarts2/doc/example/heatmap.html
请问一下 现在在4.0版本中 如何才能实现上述效果·？谢谢

**Comment by aaa583834691** [comment]
echart2的我知道、问题是现在不能用echarts2的版本的话就无法实现了··

**Comment by aaa583834691** [comment]
echart2的我知道，问题是现在不能用echarts2的版本的话就无法实现了··

**Comment by 100pah** [comment]
echarts3、echarts4 也是同样的原理的。

**Comment by aaa583834691** [comment]
我看了 他现在要求定义为极坐标或者地图坐标才能用 使用了2D极坐标之后就会要求使用X轴与Y轴 ·····这样就与之前的不符了····大佬要是有空的话 帮忙写个demo 可以吗 谢谢··项目需求··
