### ISSUE TITLE
Echart tooltip formatter自定义的提示信息中的URL无法点击到

### ISSUE THREAD

**Issue by shikenian** [apache/incubator-echarts#9012]
### One-line summary [问题简述]

我在使用Echart的过程中，使用tooltip的formatter自定义了一个方法，这样鼠标在图形中移动的过程中就可以展示我们自定义的数据了。
现在到 问题是，我在自定义显示的内容中包含链接信息，也就是快捷方式。我希望的是能够鼠标移动的过程中，弹出的提示信息中的快捷方式能够被我点击到。
现在的问题是，当我尝试移动鼠标去点击图形中的快捷方式的时候，图形会随着我鼠标的移动而移动，导致永远没法点击到里面的内容。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
最新版本
+ Browser version [浏览器类型和版本]:
Chrome最新版本
+ OS Version [操作系统类型和版本]:
Windows10

### Expected behaviour [期望结果]
希望鼠标移动的过程中产生产生的提示信息中的超链接可以被我点击到。

### ECharts option [ECharts配置项]

```javascript
option = {
 xAxis: {
			        type: 'category',
			        data: xAxis_values
			    },
			    yAxis: {
			        type: 'value'
			    },
			    tooltip: {
			    	formatter: function (datas) {
			    		console.log(datas)
			    		//name 横坐标
			    		//value 纵坐标
			    		//dataIndex 索引
			    		var name = datas.name
			    		var value = datas.value
			    		var dataIndex = datas.dataIndex
			    		var result = ""
			    		result += "bin:" + name + "<br/>"
			    		result += "count:" + value + "<br/>"

			    		var json_data = window._tone_json_data
			    		result += "<ul>"
			    		toparts = json_data.tonechart[dataIndex].toparts
			    		for (var i = 0; i < toparts.length; i++) {
			    			var topchart = toparts[i]
			    			result += "<li>" + "<a href='" + topchart.url +"'>" + topchart.title +"</a>" + "</li>"

			    		}
			    		result += "</ul>"

			    		return result
			    	}
			    },
			    series: [{
			        data: yAxis_values,
			        type: 'bar'
			    }]
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/7303314/45066715-399d8980-b0f2-11e8-86b6-09a32d4263da.png)

**Comment by 100pah** [comment]
参见：http://echarts.baidu.com/option.html#tooltip.enterable
