### ISSUE TITLE
Format time on x and y axis to day of the week or week number in a year, etc.

### ISSUE THREAD

**Issue by jaworek** [apache/incubator-echarts#9015]
Is it possible to specify a way time format is displayed on x and y axis? 
What I would like to achieve is to have for example 'Mon', 'Fr' or 'Week 23' instead of '03-05-2018'.
I tried to use 'minInterval' and 'maxInterval', but it does not produce outcomes that I am looking for. 
Is it possible to do it in echarts or do I need to use separate library?

**Comment by 100pah** [comment]
echarts provides `echarts.format.formatTime`:

```js
var option = {
    // ...
    xAxis: {
        type: 'time',
        axisLabel: {
            formatter: function (value) {
                return echarts.format.formatTime('yyyy-MM-dd', value);
                // And other formatter tool (e.g. moment) can be used here.
            }
        }
    }
}
```

**Comment by royemmerich** [comment]
Where is this documented?

**Comment by maliayas** [comment]
> 
> 
> Where is this documented?

It seems there is no documentation for now but you can [check the code](https://github.com/apache/incubator-echarts/blob/4.6.0/src/util/format.js#L191)
