### ISSUE TITLE
#Multiple Categories Boxplot# 包含多组数据的箱线图 outliers 显示异常

### ISSUE THREAD

**Issue by wannuliang** [apache/incubator-echarts#9017]
### One-line summary [问题简述]
http://gallery.echartsjs.com/editor.html?c=boxplot-multi
这个官方示例中，如果取消勾选一些可选项，outliers不会随之发生改变。如下图所示：
+ 正常显示状态
![image](https://user-images.githubusercontent.com/17905481/45130898-3e7b3f80-b1bd-11e8-8b34-2c13e5c84b72.png)
+ 取消勾选某些选项后
![image](https://user-images.githubusercontent.com/17905481/45130909-4a670180-b1bd-11e8-81d0-4e377fbcbc60.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0.rc2
+ Browser version [浏览器类型和版本]: Chrome 69
+ OS Version [操作系统类型和版本]: Win10

### ECharts option [ECharts配置项]
官方示例自带源码。

**Comment by 100pah** [comment]
Thanks. fixed.
