### ISSUE TITLE
为什么http://gallery.echartsjs.com总是出问题呢

### ISSUE THREAD

**Issue by hsilence** [apache/incubator-echarts#9018]
![222](https://user-images.githubusercontent.com/20702713/45139842-b0667f80-b1e3-11e8-9a62-b3728cc69941.png)

总是没有内容

**Comment by Rain1874** [comment]
我也是，最近打开经常出问题。。。。，官方给个回复啊倒是

**Comment by Ovilia** [comment]
查不出原因，我们也很着急……

**Comment by hiwanz** [comment]
@Ovilia 目测是安全部门的锅=，=

**Comment by hsilence** [comment]
@Ovilia 
![333](https://user-images.githubusercontent.com/20702713/45143541-296ad480-b1ee-11e8-8e1d-10bfc755cf7e.png)
