### ISSUE TITLE
How to change the smoothing of a line chart

### ISSUE THREAD

**Issue by DennisOosterling** [apache/incubator-echarts#9020]
### One-line summary [问题简述]

How to change the smoothing of a line chart

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
"echarts": "4.0.4",
"echarts-for-react": "2.0.8"

+ Browser version [浏览器类型和版本]:
Chrome 

+ OS Version [操作系统类型和版本]:
Ubuntu 16.04

### Expected behaviour [期望结果]

How can the smoothing formula of a line chart be changed? (So **not** the animation, but the drawing of the line itself)
I would like to use something like `quarticOut`
![image](https://user-images.githubusercontent.com/31688709/45142158-14734e80-b1b8-11e8-9117-7c7b46ce0e75.png)

**Comment by 100pah** [comment]
Currently, only built-in smooth algorithm can be used, see <https://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.smoothMonotone> for details.

But in fact do you want to draw a quarticOut line, like this [example](https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-easing) dose?
