### ISSUE TITLE
双value轴时，areaStyle向y轴方向填充颜色

### ISSUE THREAD

**Issue by live9080** [apache/incubator-echarts#9025]
### One-line summary [问题简述]
预期图像效果：
![_20180906195437](https://user-images.githubusercontent.com/6326386/45156255-41535000-b210-11e8-834c-35e79687d2d4.png)
```javascript
option = {
    xAxis: {type: 'value'},
    yAxis: {type: 'category'},
    series: [{
        data: [[820, 10], [932, 20], [901, 30],[934, 40],[1290, 50],[1330, 60],[1320, 70]],
        type: 'line',
        smooth: true,
        areaStyle: {}
    }]
};

```
当Y轴type为category可轻易实现，**可当X轴，Y轴类型皆为value时，无法选择areaStyle填充方向**。
当前实际效果：
![image](https://user-images.githubusercontent.com/6326386/45156880-0520ef00-b212-11e8-859c-bebf2a0f49a2.png)
```javascript
option = {
    xAxis: { type: 'value' },
    yAxis: {type: 'value' },
    series: [{
        data: [[820, 10], [932, 20], [901, 30],[934, 40],[1290, 50],[1330, 60],[1320, 70]],
        type: 'line',
        smooth: true,
        areaStyle: {}
    }]
};
```

希望添加areaStyle填充方向参数设置，或有其他效果达到预期效果吗？非常感谢。
tips:
不可调换xy轴数据, 老板需求就是需要横向填充。

**Comment by live9080** [comment]
#8963

**Comment by sumile-ting** [comment]
@live9080 最终有解决办法了吗？遇到同样的问题

**Comment by live9080** [comment]
@sumile-ting  很早以前的需求了，当时怎么妥协的已经忘记了…… Sorry.
