### ISSUE TITLE
Axis Label overlapping

### ISSUE THREAD

**Issue by geekboy0801** [apache/incubator-echarts#9026]
Hi.
I have a question about axis label of Echarts.
Let's look at this image.

![image](https://user-images.githubusercontent.com/40581883/45169596-36ba9b80-b1bb-11e8-9099-e7c32d93fb55.png)

As you can see, when the container of Echarts gets smaller, Echarts does not control axis interval automatically. 
So my question is: *Do i have to adjust this manually?*
I guess Echarts has the built-in function to solve such this small issue.
I want your help!
Thanks.

**Comment by 100pah** [comment]
If `yAxis.type` is `'value'`, it can be adjusted automatically.
If `yAxis.type` is `'category'`, it uses another strategy to adjust them but not perfect.

Could I have your `option` to check this issue in detail?

**Comment by geekboy0801** [comment]
Hi, @100pah . I am now using ReactEchart component. And the code stuff is as below.
  
    eChartOption(graphData, xAxisCategories) {
    const yAxisLines = this.getYAxisLines(graphData, xAxisCategories);

    const isLarge = this.props.size === Size.XLARGE;
    const isW2W = this.props.operationType === W2W_OPTYPE;

    const series = graphData.map(oneGraph => ({
      name: oneGraph.get('name'),
      type: 'bar',
      barWidth: '50%',
      stack: '1',
      itemStyle: {
        normal: {
          color: oneGraph.get('color'),
        },
      },

      tooltip: {
        borderColor: oneGraph.get('color'),
        formatter: params => (
          `${params.value[2]}<br />
           ${params.seriesName}: ${params.value[1].toFixed(1)} mins<br />
           ${params.value[3]}`
        ),
      },
      data: oneGraph.get('data').map(item => [
        item.get('x'),
        item.get('y'),
        item.get('name'),
        item.get('depth'),
      ]).toArray(),
    })).toArray();

    let legend;
    if (isW2W && !isLarge) {
      const legends = [
        graphData.filter((item, index) => index < 3),
        graphData.filter((item, index) => index >= 3),
      ];

      legend = legends.map((oneLegend, index) => ({
        show: true,
        type: 'scroll',
        bottom: index === 0 ? 0 : 15,
        align: 'left',
        itemHeight: 10,
        itemWidth: 10,
        textStyle: {
          color: '#888',
        },
        formatter: (name) => {
          const space = ' ';
          const nLength = String(name).length;
          return `${name}${space.repeat(25 - nLength)}`;
        },
        data: oneLegend.map(oneGraph => ({
          name: oneGraph.get('name'),
          icon: 'rect',
        })).toArray(),
      }));
    } else {
      legend = {
        show: true,
        bottom: 0,
        itemHeight: 10,
        itemWidth: 10,
        textStyle: {
          color: '#888',
        },
        data: graphData.map(oneGraph => ({
          name: oneGraph.get('name'),
          icon: 'rect',
        })).toArray(),
      };
    }

    const chartOption = {
      animation: false,
      legend,
      xAxis: [{
        type: 'category',
        axisLine: { show: false },
        axisTick: { show: false },
        axisLabel: {
          color: '#888',
          rotate: isLarge ? 0 : 45,
          margin: 12,
        },
        data: xAxisCategories.toArray(),
      }],

      yAxis: {
        name: 'Operation Time (minutes)',
        nameLocation: 'middle',
        nameTextStyle: {
          color: '#aaa',
        },
        nameGap: 35,
        type: 'value',   //--------------------------------------------------------------------------------
        axisTick: { show: false },
        axisLine: { show: false },
        splitLine: { show: false },
        axisLabel: {
          color: '#888',
        },
      },

      grid: {
        left: 40,
        right: 10,
        bottom: (this.props.operationType === W2W_OPTYPE) ? 50 : 25,
        top: 10,
        containLabel: true,
        show: true,
        borderWidth: 0,
      },

      tooltip: {
        trigger: 'item',
        axisPointer: {
          type: 'shadow',
        },
        backgroundColor: 'rgba(221,221,221,0.9)',
        borderColor: '#198bff',
        borderWidth: 1,
        textStyle: {
          color: '#000',
        },
      },

      series: [...series, {
        name: 'Goal Line',
        type: 'line',
        markLine: {
          silent: true,
          symbol: 'none',
          data: yAxisLines.map(yAxisLine => ({
            yAxis: yAxisLine.get('value'),
            lineStyle: {
              normal: {
                color: yAxisLine.get('color'),
                type: 'solid',
              },
            },
            label: {
              normal: {
                position: yAxisLine.get('position'),
                formatter: `{style|${yAxisLine.get('text')}}`,
                color: yAxisLine.get('color'),
                rich: {
                  style: {
                    width: '100%',
                    align: yAxisLine.get('align'),
                    padding: [0, 0, -15, 0],
                    rotation: 90,
                  },
                },
              },
            },
          })).toArray(),
        },
      }],
    };

    return chartOption;
  }

**Comment by 100pah** [comment]
[splitNumber](https://ecomfe.github.io/echarts-doc/public/en/option.html#yAxis.splitNumber) is mainly used to determine the number of displayed label and ticks.

Probably this approach can be tried: 
when changing the size of a chart, 
```js
function onChartContainerDomChange() {
    var height = chart.getHeight();
    var splitNumber = height < 200
        ? 2
        : height < 300
        ? 4
        : null;
    console.log(height, splitNumber);
    chart.setOption({
        yAxis: {splitNumber: splitNumber}
    });
    chart.resize();
}
```

**Comment by geekboy0801** [comment]
Thank you, @100pah .
Just fixed when adding one line such as below

    splitNumber: containerPixelHeight < 500 ? 2 : 4, 

But split number of axis line is not exactly the same as the value we set (2, 4).
It is random but overlapping does not happen.
Is that expected?

**Comment by 100pah** [comment]
`splitNumber` is a reference value. The final number of the result segments will be auto-adjusted according to the readability of the value on each tick(for example, round as far as possible).
