### ISSUE TITLE
legend的icon颜色bug

### ISSUE THREAD

**Issue by eniaclyl** [apache/incubator-echarts#9030]
### One-line summary [问题简述]
曲线图中设置了一个曲线，然后中途修改这个曲线的颜色，比如改为蓝色，legend图例的icon颜色不会同时跟着变化，我不知道这个内部是什么原理，这个算不算bug，如何让曲线颜色修改后，图例的icon颜色也跟着变化？谢谢。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
因为不知道您是使用什么 option 进行设置的，所以难于知道您的问题所在。

**Comment by eniaclyl** [comment]
就是option创建好一个曲线以后 在外部 用option.series.data..lineStyle.color = '#e30000' 又单独改变了下曲线的颜色，然后又myChart.setOption(option, true); 这样legend的颜色就不和曲线颜色一样了，这个问题是不是bug 怎么能让legend颜色和改变后的曲线颜色一样呢

**Comment by Ovilia** [comment]
legend 也传入相同的颜色
