### ISSUE TITLE
在火狐浏览器下进入到echarts相应实例下，点击download无反应。

### ISSUE THREAD

**Issue by zuoliansheng** [apache/incubator-echarts#9031]
### One-line summary [问题简述]
比如在火狐浏览器打开这个链接   http://echarts.baidu.com/examples/editor.html?c=area-basic
在右下角的download按钮，点击无反应，其他相应的链接，在火狐浏览器下点击download也均无反应。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]:firefox61.0.2
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
点击download能够正常下载。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by initialdmg** [comment]
You could move to echarts' website reposity - [echarts-www](https://github.com/ecomfe/echarts-www). About this problem, see [Programmatical click on <a>-tag not working in Firefox](https://stackoverflow.com/questions/32225904/programmatical-click-on-a-tag-not-working-in-firefox/32226068). Location: editor.js:L694 @leeight
