### ISSUE TITLE
这个loop实现有点奇怪，例如在使用setOption更新图数据时，加入数据前后相同，这种实现effect居然不会重绘，就算数据不完全相同，那些相同的数据也不会重绘，个人认为在刷新数据之后，即使数据相同，effect配置一样，也应该重绘吧。谁能解答这个问题，用了最新的版本了，里面也设置了loop，但还是没有解决

### ISSUE THREAD

**Issue by LIHAO520** [apache/incubator-echarts#9032]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
是否能给出 option ？

**Comment by LIHAO520** [comment]
怎么个给出法呢？ 每次调用函数加载数据的时候都要创建这个option对象啊 @100pah

**Comment by LIHAO520** [comment]
@100pah 你有什么好方法吗？

**Comment by pissang** [comment]
和 https://github.com/apache/incubator-echarts/issues/9044 重复
