### ISSUE TITLE
Override dataZoom event

### ISSUE THREAD

**Issue by MarcMagnin** [apache/incubator-echarts#9036]
Hi,

Within a line chart with time as X axis, is there is any way to prevent the default datazoom to query new data for the selected time range rather than zooming in?

I'm currently using `echarts._componentsViews[Object.keys(echarts._componentsViews)[0]]._features['dataZoom'].model.iconPaths.zoom.trigger('click');` to trigger the datazoom feature but it doesn't seems that I can get an handle on the event to prevent it's normal execution.

Many thanks!

**Comment by 100pah** [comment]
I think if you intend to select a range of data, probably [brush](https://ecomfe.github.io/echarts-doc/public/en/option.html#brush) can be used rather than `dataZoom`.
