### ISSUE TITLE
ecarts支持XY轴自动翻转吗

### ISSUE THREAD

**Issue by daoyuanjiao** [apache/incubator-echarts#9037]
我画出了一张折线图，但有时候需要XY轴调换一下看图（比如说原来X轴显示距离，Y轴显示时间,现在点击按钮，X轴显示时间，Y轴显示距离，数据都是一样的）。ecarts有这个功能吗？还是需要我重新设定XY轴后再加载数据？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
重新 setOption，把 xAxis 和 yAxis 的配置交换。
