### ISSUE TITLE
柱状图横向排，居中对齐

### ISSUE THREAD

**Issue by menciusKael** [apache/incubator-echarts#9038]
![image](https://user-images.githubusercontent.com/29659731/45263104-08a4b800-b456-11e8-9bcb-bb6a22d5a3a5.png)

1. 柱状图，水平排版，然后如何居中对齐，而不是靠左对齐？？

2. 有没有排序功能，长一点的柱子在上面

**Comment by menciusKael** [comment]
版本 echarts4.0  chrome最新浏览器

**Comment by 100pah** [comment]
1. 可以实现，但是没有直接的方法实现，因为这已经超出的传统“柱状图”的定义。
实现的方法，比如：
（A）y 轴放中间，两个系列，一正一负。
（B）使用 custom series。
2. 先对数据排序，然后传入 echarts。

**Comment by pissang** [comment]
可以试试使用自定义系列，参考 http://www.echartsjs.com/gallery/editor.html?c=custom-profile

**Comment by menciusKael** [comment]
自定义系列玩不来，那个渲染函数，实践了几次，解决不了，求哪位大神给个解决方案，感谢

**Comment by JinxCarry9527** [comment]
这个目前纯靠漏斗貌似实现不了
我用柱状图实现了这个效果
@Ovilia 产品经理支持一下呀
