### ISSUE TITLE
The Legend formatter prop how to customize style

### ISSUE THREAD

**Issue by weixianpin** [apache/incubator-echarts#9039]
### One-line summary [问题简述]
The Legend formatter prop how to customize style？like this:
![image](https://user-images.githubusercontent.com/16029151/45264635-3dbf0380-b472-11e8-9f22-10ac0561c353.png)
let the text（%） align right, or let formatter recognize html tag like [#5212](https://github.com/apache/incubator-echarts/issues/5212)(closed but not solved) 
 said? 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:google chrome  68.0.3440.106（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:Windows 10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
It can be implemented by [Rich text](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Rich%20Text) now.

**Comment by weixianpin** [comment]
Rich Text solved this problem，but the align prop didn't work.The final result like this:
![image](https://user-images.githubusercontent.com/16029151/45604591-6d6c9d80-ba68-11e8-8d29-f810784a2391.png), and how could i let the text(%) align right as my title said？

**Comment by weixianpin** [comment]
> It can be implemented by [Rich text](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Rich%20Text) now.

Rich Text solved this problem，but the align prop didn't work.The final result like this:
![image](https://user-images.githubusercontent.com/16029151/45604591-6d6c9d80-ba68-11e8-8d29-f810784a2391.png), and how could i let the text(%) align right as my title said？

**Comment by Ovilia** [comment]
No idea...
