### ISSUE TITLE
echart gl 可以单独设置背景图片吗

### ISSUE THREAD

**Issue by icecxh** [apache/incubator-echarts#9041]
### One-line summary [问题简述]

echart gl 可以单独设置背景图片吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

echart gl 可以单独设置背景图片吗

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by icecxh** [comment]
已解决

**Comment by Williamlook** [comment]
> 已解决

怎么增加的背景图片啊，大佬

**Comment by Immanding** [comment]
> > 已解决
> 
> 怎么增加的背景图片啊，大佬

四年过去了，早忘了，慢慢找吧，反正是可以的
