### ISSUE TITLE
Map3D为什么不支持geoIndex

### ISSUE THREAD

**Issue by icecxh** [apache/incubator-echarts#9042]
### One-line summary [问题简述]

Map3D为什么不支持geoIndex

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
需要什么样的效果？

**Comment by pissang** [comment]
抱歉目前暂时还不支持，你先试试你说的那个方案吧
