### ISSUE TITLE
这个loop实现真的奇怪，搞了好几天了，还是有问题，例如在使用setOption更新图数据时，加入数据前后相同，这种实现effect居然不会重绘，就算数据不完全相同，那些相同的数据也不会重绘，个人认为在刷新数据之后，即使数据相同，effect配置一样，也应该重绘吧。谁能解答这个问题，用了最新的版本了，里面设置了loop，但还是没有解决，二次加载数据的时候还是不会重绘，希望再这里得到各位的帮助！！！ 

### ISSUE THREAD

**Issue by LIHAO520** [apache/incubator-echarts#9044]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by gangyahaidao** [comment]
至少要把必要的代码放进来，仅仅看描述不知道具体是什么

**Comment by LIHAO520** [comment]
// setInterval("bigdata.mapAjax()",3000);   这里定时调用这个函数  
mapAjax: function () {
        $.ajax({
            url: "" + urls + "bigData/scooter/queryTrack?cityCode="+city+"",
            success: function (data) {
                var busLines=data.result;

                var data=busLines.map(function(v){
                    return v.points;
                })
                var hStep = 300 / (data.length - 1);
                // var max=[];
                var busLines = [].concat.apply([], data.map(function (busLine, idx) {
                    var prevPt;
                    var points = [];
                    for (var i = 0; i < busLine.length; i += 2) {
                        // busLine[i]  所展示的是每一辆车的经纬度 
                        var pt = [busLine[i], busLine[i + 1]];
                        // pt  是一个经纬度的数组   就是把这辆车每移动的一个经纬度添加为一个数组  
                        if (i > 0 && i < busLine.length) {
                            pt = [
                                prevPt[0] + pt[0],
                                prevPt[1] + pt[1]
                            ];
                        }
                        prevPt = pt;

                        points.push([pt[0] / 1e4, pt[1] / 1e4]);

                        var pre=[prevPt[0]/ 1e4,prevPt[1]/ 1e4];

                        var po=points[points.length-1];

                       if(pre[0]==po[0] && pre[1]==po[1]){

                       }
                        
                    }
                    
                    // max.push(points);
                    return {
                        coords: points,
                        lineStyle: {
                            normal: {
                                color: echarts.color.modifyHSL('#5A94DF', Math.round(hStep * idx))
                            }
                        }
                    };
                }));
                // var zd=Math.max(...max.map(v=>v.length));
                // var newData=max.map(v=>(v.splice(v.length,0,...new Array(zd-v.length).fill(v[v.length-1])),v));
                
                var jwds=[];
                var ds=busLines.forEach(function(v) {
                    var obj={
                        jd:v.coords[0][0],
                        wd:v.coords[0][1],
                    }
                    jwds.push(obj);
                })
                if(btnFirst){
                    position={
                        x: jwds[0].jd,
                        y: jwds[0].wd
                    }
                    btnFirst=false;
                }
                option={
                    bmap: {
                        // center: [position.x,position.y],
                        // zoom:17,
                        roam: true,
                        mapStyle: {
                            'styleJson': [{
                                    'featureType': 'water',
                                    'elementType': 'all',
                                    'stylers': {
                                        'color': '#031628'
                                    }
                                },
                                {
                                    'featureType': 'land',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#000102'
                                    }
                                },
                                {
                                    'featureType': 'highway',
                                    'elementType': 'all',
                                    'stylers': {
                                        'visibility': 'off'
                                    }
                                },
                                {
                                    'featureType': 'arterial',
                                    'elementType': 'geometry.fill',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'arterial',
                                    'elementType': 'geometry.stroke',
                                    'stylers': {
                                        'color': '#0b3d51'
                                    }
                                },
                                {
                                    'featureType': 'local',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'railway',
                                    'elementType': 'geometry.fill',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'railway',
                                    'elementType': 'geometry.stroke',
                                    'stylers': {
                                        'color': '#08304b'
                                    }
                                },
                                {
                                    'featureType': 'subway',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'lightness': -70
                                    }
                                },
                                {
                                    'featureType': 'building',
                                    'elementType': 'geometry.fill',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'all',
                                    'elementType': 'labels.text.fill',
                                    'stylers': {
                                        'color': '#857f7f'
                                    }
                                },
                                {
                                    'featureType': 'all',
                                    'elementType': 'labels.text.stroke',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'building',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#022338'
                                    }
                                },
                                {
                                    'featureType': 'green',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#062032'
                                    }
                                },
                                {
                                    'featureType': 'boundary',
                                    'elementType': 'all',
                                    'stylers': {
                                        'color': '#465b6c'
                                    }
                                },
                                {
                                    'featureType': 'manmade',
                                    'elementType': 'all',
                                    'stylers': {
                                        'color': '#022338'
                                    }
                                },
                                {
                                    'featureType': 'label',
                                    'elementType': 'all',
                                    'stylers': {
                                        'visibility': 'off'
                                    }
                                }
                            ]
                        }
                    },
                    series: [{
                        type: 'lines',
                        coordinateSystem: 'bmap',
                        polyline: true,
                        data: [],
                        silent: true,
                        lineStyle: {
                            normal: {
                                // color: '#c23531',
                                // color: 'rgb(200, 35, 45)',
                                opacity: 0.2,
                                width: 1
                            }
                        },
                        progressiveThreshold: 500,  //启用渐进式渲染的图形数量阈值，在单个系列的图形数量超过该阈值时启用渐进式渲染。
                        progressive: 200   //渐进式渲染   
                    }, {
                        type: 'lines',
                        coordinateSystem: 'bmap',
                        polyline: true,
                        data: busLines,
                        lineStyle: {
                            normal: {
                                width: 0
                            }
                        },
                        effect: {   //线特效的配置  
                            constantSpeed: 5,  //是否是固定速度  
                            period:5,//特效动画的时间
                            show: true,
                            // loop: false,  //是否循环特效
                            trailLength: 0.6,  //特效尾际的长度   
                            symbolSize: 1.5  //特效的大小
                        },
                        animation: true,
                        zlevel: 1
                    }]
                };
                // console.log(option.series[1].effect.loop);
                
                if(centerFirst){
                    option.bmap.center=[position.x,position.y]
                    option.bmap.zoom=15
                    centerFirst=false;
                }
                
                mapEcharts.setOption(option);
                
            }
        })
    }
@gangyahaidao 这个就是实例代码  麻烦了

**Comment by pissang** [comment]
不会重绘是目前我们期望的效果

**Comment by LIHAO520** [comment]
希望的效果就是第二次加载数据过，无论数据是否相同，都希望重绘再地图上？能否加上去这个功能   
比方说：现在有十辆车要做实时动态路径；每隔一分钟加载一次数据，可能会多一些车辆，也有可能会少车；但是绘制的时候因为设置false，所以它只会绘制新增的车辆 ，而之前的就不绘制了，是因为数据重合，所以，我希望不管是新的数据还是之前的数据，都可以绘制，可以增加这个新功能吗？

**Comment by pissang** [comment]
可以试下每个数据都加一个唯一标志的 id

**Comment by LIHAO520** [comment]
如果加上这个id的话，实现这个效果的逻辑是什么呢，能提供思路吗？确保可以实现这个功能吗？

**Comment by pissang** [comment]
现在是根据 id 来决定上次的数据和这次数据是否是一个，不是的画会重新绘制

**Comment by LIHAO520** [comment]
那这样肯定不行啊，老铁，比方说：现在来了十辆车，给每辆车一个id，我现在获取当前十辆车的坐标点，然后绘制出来，我下次也是获取这些车的坐标点啊，然后再次绘制；只不过我再次获取的时候可能会新增一些车的坐标点  ，不可能我第一次获取到这些车的数据，下次来了新数据不可能不绘制啊，这样的话车不就没有了实时动态运动轨迹了吗

**Comment by LIHAO520** [comment]
@pissang 每辆车它的坐标点不可能只有一次数据吧    肯定有很多的坐标  需要对这辆车定时去调用它的数据坐标

**Comment by LIHAO520** [comment]
@pissang 有好方法没

**Comment by pissang** [comment]
如果要实时更新车辆坐标，建议就别加动画了，每次 setOption 更新坐标就行

**Comment by LIHAO520** [comment]
暂时我们做的就是更新坐标，没用做动画了，但是后期可以加上这个功能吗？我觉得以后像这样的实时动态需求肯定会很多

**Comment by LIHAO520** [comment]
有demo吗？散点图做实施动画，那轨迹弄出来效果不是很丑？

**Comment by pissang** [comment]
轨迹可以用没有特效动画 lines 系列绘制

**Comment by LIHAO520** [comment]
轨迹能弄出来，就是这个特效动画，让它停，再次重绘的问题，老铁；散点图可以做到这样的效果吗？

**Comment by pissang** [comment]
参考 http://www.echartsjs.com/gallery/editor.html?c=scatter-nutrients-matrix

**Comment by LIHAO520** [comment]
老铁，这散点图，能画出动态的实时轨迹特效动画？？？

**Comment by gangyahaidao** [comment]
我觉得你的关注点有点跑偏了，增量式数据更新是合理的做法，每次setOption全部数据重新加载才是不好的做法，绘制轨迹实际上有很多种方式，可以把你想要的功能借助于现有的方法来实现，比如重新构造渲染的数据结构，或者仔细看一下例子找找适合你的方法

**Comment by gangyahaidao** [comment]
程序的数据加载可以改进一下，不用每次$.ajax都重新构造数据，可以只更新特定的option参数，然后再调用setOption

**Comment by arieslx** [comment]
前辈您好，我也遇到了同样的问题。
具体描述为：三屏的演示窗口，左右屏为echarts图表数据展示，同样的json数据（具体包含饼状图，柱状图，水球图），要求点击刷新左右屏按钮，重绘页面（要求特效动画）。不知道，有没有解决方式，尝试了在echarts.init（）前，dom.removeAttribute("_echarts_instance_");但是还是不会出现重绘动画

**Comment by arieslx** [comment]
> 前辈您好，我也遇到了同样的问题。
> 具体描述为：三屏的演示窗口，左右屏为echarts图表数据展示，同样的json数据（具体包含饼状图，柱状图，水球图），要求点击刷新左右屏按钮，重绘页面（要求特效动画）。不知道，有没有解决方式，尝试了在echarts.init（）前，dom.removeAttribute("_echarts_instance_");但是还是不会出现重绘动画

echarts.init(document.getElementById('echarts')).dispose();//销毁前一个实例
var myEcharts = echarts.init(document.getElementById('echarts'));//构建下一个实例
--------------------- 
作者：jiang_mingyi 
来源：CSDN 
原文：https://blog.csdn.net/jiang_mingyi/article/details/75655657 
版权声明：本文为博主原创文章，转载请附上博文链接！

最后这样解决了功能实现

**Comment by nongzhenli** [comment]
> 轨迹可以用没有特效动画的 lines 系列绘制

你好，我目前使用 Lines + bmap 依照最标点描绘轨迹！为了保证轨迹的 `effect` 点的始终仅在一条线上划动，将loop关闭了！并且使用 setOption()动画更新图表！
