### ISSUE TITLE
在vue中使用最新的echarts.在使用setOption的时候报"vue.runtime.esm.js?2b0e:587 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'get' of undefined""的错

### ISSUE THREAD

**Issue by maxiaoqu** [apache/incubator-echarts#9045]
### One-line summary [问题简述]
在vue中使用最新的echarts.在使用setOption的时候报" [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'get' of undefined""的错

具体是在使用饼状图在vue下封装组件时会报此错误，其他类型的图形不报错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:"^4.1.0"
+ Browser version [浏览器类型和版本]:谷歌浏览器(版本 68.0.3440.106（正式版本） （64 位)
+ OS Version [操作系统类型和版本]:Windows

### ECharts option [ECharts配置项]

```javascript
option = {
          title:{
		   text: "echarts【饼状图】图表展示",
		   show: true
	},
	color:["#ff6700","#999999","yellow","red"],
    series: [
        {
            type:'pie',
            data:[
                {value:222, name:'周1'},
    		     {value:212, name:'周2'},
    		    {value:422, name:'周3'},
    		   {value:225, name:'周4'},
    		   {value:252, name:'周5'},
    		   {value:422, name:'周6'},
    		   {value:223, name:'周7'}
            ]
        }
		   
	]
}

```

**Comment by pissang** [comment]
有更详细的报错信息和复现代码么？

**Comment by doufugeshihua** [comment]
lazyUpdate设为true会报这个错，false就不会
