### ISSUE TITLE
echart toolbox 自定义按钮的鼠标移入移出事件

### ISSUE THREAD

**Issue by anneyangyue** [apache/incubator-echarts#9046]
### One-line summary [问题简述]

echart toolbox 自定义按钮的鼠标移入移出事件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
缺乏信息
