### ISSUE TITLE
dataZoom如何控制缩放start和end

### ISSUE THREAD

**Issue by vincentfintend** [apache/incubator-echarts#9047]
现有的dataZoom事件是放大缩小会同时改变start和end，但我希望可以控制其中一边的值固定，只改变start值或者end值。我试过采用dispatchAction进行控制，但效果不行，所以想问问有没有什么方法可以做到这个事情？

版本： echarts 3.8.5

**Comment by vincentfintend** [comment]
@pissang  
```js
myChart.getZr().on('mousewheel', (e) => {})
```
请问这个有阻止冒泡的方法么？因为我发现可以通过设置zoomLock：true, 再通过此方法去监听滚轮事件，再调用dispatchAction以此满足我所需要的，但当滚轮滚动时，页面会跟着滚动。因为getZr方法似乎无文档可以查看相关配置项。。

**Comment by pissang** [comment]
`e.event.preventDefault()` 应该就可以
