### ISSUE TITLE
无法点到澳门

### ISSUE THREAD

**Issue by fengyy51** [apache/incubator-echarts#9048]
One-line summary [问题简述]
在用echarts3地图时，发现广东的区域范围包括了澳门地区。

Version & Environment [版本及环境]
ECharts version [ECharts 版本]:3
Browser version [浏览器类型和版本]:Google Chrome，FireFOx
OS Version [操作系统类型和版本]:WIN10
Expected behaviour [期望结果]
两个区域能够区分开

ECharts option [ECharts配置项]
option = {

}
Other comments [其他信息]

**Comment by pissang** [comment]
这个是数据的原因，echarts 不再维护地图的数据
