### ISSUE TITLE
xAxis 'Name' Long character overflow is hidden

### ISSUE THREAD

**Issue by xianghongai** [apache/incubator-echarts#9049]
![overflow is hidden](https://user-images.githubusercontent.com/2075006/45350670-f0b06e00-b5e6-11e8-9b92-fe112d3709bf.png)

![nameRotate](https://user-images.githubusercontent.com/2075006/45350686-f9a13f80-b5e6-11e8-9654-0c9b7c79346a.png)

[online demo](http://echarts.baidu.com/examples/editor.html?c=line-log&qq-pf-to=pcqq.c2c)

settings:

```json
    xAxis: {
        type: 'category',
        name: 'abcefghijklmnopqrstuvwxyz',
        nameLocation:'end',
        nameGap:5,
        // nameRotate:90,
        splitLine: {show: false},
        data: ['一', '二', '三', '四', '五', '六', '七', '八', '九']
    },
```

**Comment by pissang** [comment]
可以把文字放在中间，或者设置 grid.right 大一点
