### ISSUE TITLE
Echarts 的 PPT 插件什么时候可以用？

### ISSUE THREAD

**Issue by jinjian624** [apache/incubator-echarts#9052]
### One-line summary [问题简述]

Echarts 的 PPT 插件什么时候可以用？4.0发布的时候就已经说了，但是现在大半年了都还没有消息啊
有没有什么方法可以先体验到呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]: 
+ OS Version [操作系统类型和版本]: Windows 

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
非常抱歉，因为人力紧张，PPT 的插件最近暂时处于搁置的状态

**Comment by cainnn** [comment]
快一年了，这个插件还在开发吗？

**Comment by hiyangguo** [comment]
https://vis.baidu.com/
![image](https://user-images.githubusercontent.com/15609339/67351889-21502e80-f581-11e9-9ff2-49b1a7c6e3a4.png)
这个插件现在怎么样了？ 
@Ovilia @pissang

**Comment by minren118** [comment]
我开发了EasyShu，除了传统的Excel原生方式作图，也加了ECharts图表，欢迎各位有兴趣探讨ECharts与OFFICE软件结合的过来围观下。公众号：Excel催化剂与EasyShu里都可查看到最新信息。
