### ISSUE TITLE
echarts在mode: "production" 下无法正常显示

### ISSUE THREAD

**Issue by baigod** [apache/incubator-echarts#9055]
### One-line summary [问题简述]
我用 webpack集成echarts，当webpack配置为mode: "development"时，显示正常，但当配置为mode: "production"或不配置（不配置默认是production）时，则无法显示。console没有报任务错误。因此我在开发环境调试时正常，到了生产环境就不显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: "echarts": "^4.1.0"
+ Browser version [浏览器类型和版本]: 谷歌浏览器最新版本
+ OS Version [操作系统类型和版本]: Windows

**Comment by pissang** [comment]
请先排查一下是否因为其它因素造成的

**Comment by baigod** [comment]
同时使用了 jquery  ，难道冲突？  其他什么都没有，很纯净的webpack项目

**Comment by baigod** [comment]
![image](https://user-images.githubusercontent.com/23446974/45475330-980bdd00-b76e-11e8-92a0-cc076e4aa697.png)

**Comment by baigod** [comment]
![image](https://user-images.githubusercontent.com/23446974/45476012-7ad80e00-b770-11e8-982c-2036fbe62faa.png)

**Comment by baigod** [comment]
"sideEffects": [
    "./src/*.js",
    "./src/*.css"
  ],

跟这个有关系貌似，去掉了就可以

**Comment by shivamsriva31093** [comment]
@baigod Hi. I am acing similar issue. Can you explain what did you do?

**Comment by yimingsue** [comment]
有没有遇到生产环境图表完全不显示的问题？
