### ISSUE TITLE
echarts在谷歌34版本中，datazoom设为竖直时，无法显示下拉条。

### ISSUE THREAD

**Issue by wangqipov** [apache/incubator-echarts#9056]
### One-line summary [问题简述]
echarts在谷歌34版本中，datazoom设为竖直时，无法显示datazoom滚动条，此时datazoom滚动条是透明的，可以拖动。（柱状图）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请给出更多可以复现的信息

**Comment by wangqipov** [comment]
浏览器：谷歌34版
echarts版本：已测版本echarts4.1.0，echarts.3.8.4.都有这种情况
现象：数值时datazoom滚动条看不到，但能拖动
设置： dataZoom: [{
		   	        	orient: 'vertical',
		   	        	zoomLock:true,
		   	        	zoomOnMouseWheel:false,
		   	        	right:32,
			        	width:10,
			        	// height: 15,
			            startValue:0,
			            endValue:5,
			            handleSize: '80%',
			            handleStyle: {
			                color: '#fff',
			                shadowBlur: 3,
			                shadowColor: 'rgba(0, 0, 0, 0.6)',
			                shadowOffsetX: 2,
			                shadowOffsetY: 2
			            }
			        }],

**Comment by wangqipov** [comment]
谷歌34版中：echarts的饼状图文字颜色会自动变为饼图的颜色，
       比如文字设置成黑色，饼图设置为蓝色。那么文字会先为灰色，然后再自动变为蓝色。

**Comment by Ovilia** [comment]
34 版本太老了吧，最新都 69 了。给个完整的代码我看下能不能复现。
