### ISSUE TITLE
Echarts Toolbar inconsistent with the toolbox.magicType.type of "line"

### ISSUE THREAD

**Issue by theNotoriousHxc** [apache/incubator-echarts#9057]
Here's the link to an example:

https://ecomfe.github.io/echarts-examples/public/editor.html?c=mix-line-bar

The bug with the line chart option in `toolbox.magicType.type` happens when:
* If this is the first thing you selected, then it would switch up the axises in the series.
* Or if you press **reset**, then press **line** then the bug would also appear.

Any solution about this one?

**Comment by Ovilia** [comment]
Sorry I can't understand. What do you mean by *it would switch up the axises in the series*?

**Comment by theNotoriousHxc** [comment]
@Ovilia you could see on the example that it would switch axis designated colors. The first series in the example should **always** be red but when you press **reset** then press **line** in the toolbar, you can see that the first series now no longer is colored red.
