### ISSUE TITLE
series 中的type 不支持动态配置

### ISSUE THREAD

**Issue by zhoujiamin** [apache/incubator-echarts#9058]
### One-line summary [问题简述]

想通过事件触发 series 中的type改变，但是发现type是一个计算属性，
并没有找到配置这个的api

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  ^4.1.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
setOption 更新
