### ISSUE TITLE
自定义图标动态切换

### ISSUE THREAD

**Issue by menciusKael** [apache/incubator-echarts#9059]
![image](https://user-images.githubusercontent.com/29659731/45419701-9f71ae80-b6ba-11e8-8a5a-b0a0787040be.png)

![image](https://user-images.githubusercontent.com/29659731/45419877-16a74280-b6bb-11e8-8317-780019a8fa63.png)

```js
feature: {
        myTool1: {
          show: true,
          title: "往上",
          icon: "image://../img/drill_up_h.png",
          onclick: function () {
            alert("myToolHandler1");
            // option.toolbox.feature.myTool1.icon
          }
        },
        myTool2: {
          show: true,
          title: "往下",
          icon: "image://../img/drill_down.png",
          onclick: function () {
            alert("myToolHandler1");
          }
        },
       
      }
```
怎么实现这个自定义图标动态切换，就是只有一个当前选中，选中颜色为绿色，是一张本地图片，选中一个另一个变灰色，求大神指点，谢谢

**Comment by pissang** [comment]
暂时不支持

**Comment by menciusKael** [comment]
有没有其他变通的实现方法呢，比如magicType 或者 brush能做到吗

**Comment by pissang** [comment]
可以尝试监听事件然后 setOption 设置

**Comment by menciusKael** [comment]
谢谢，已解决，每个图表点击后回重新执行echarts渲染，传个参数做判断，然后三元运算给图片地址就行

**Comment by lishihong** [comment]
> 谢谢，已解决，每个图表点击后回重新执行echarts渲染，传个参数做判断，然后三元运算给图片地址就行

怎么解决的啊
