### ISSUE TITLE
想问一下，柱状图的横坐标是否只可以位于柱子的中心

### ISSUE THREAD

**Issue by guo897654050** [apache/incubator-echarts#9060]
### One-line summary [问题简述]
由于柱状图，提供一组x,y的列表，那么每次画图，X坐标值均位于柱子的中间，怎么才可以让其位于柱子左侧

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        data: [1,2,3,4,5,6,7]
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar'
    }]
};


```

**Comment by luguokong** [comment]
yAxis.axisLabel.padding

**Comment by guo897654050** [comment]
谢谢




发自网易邮箱大师
在2018年09月12日 23:06，路过空 写道：

yAxis.axisLabel.padding
