### ISSUE TITLE
toolbox中的icon

### ISSUE THREAD

**Issue by zhoujiamin** [apache/incubator-echarts#9061]
### One-line summary [问题简述]
想获得toolbox中，magicType 中 line bar 的icon，即转化为折线图，转换为柱状图的icon

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
获得是什么意思，知道这个图片还是要替换？
