### ISSUE TITLE
Echarts可以在地图上标点吗？比如一个随机的经纬度数据，可以在地图上标注出来吗？

### ISSUE THREAD

**Issue by 1558204459** [apache/incubator-echarts#9065]
Echarts可以在地图上标点吗？比如一个随机的经纬度数据，可以在地图上标注出来吗？
在文档中没看到有这种api，特来咨询一下

**Comment by pissang** [comment]
可以 `myChart.getZr().on('click')` 监听事件后再用 `convertFromPixel` 方法转成经纬度
