### ISSUE TITLE
页面稳定性

### ISSUE THREAD

**Issue by zztisoftwyj** [apache/incubator-echarts#9068]
![Uploading image.png…]()
大佬，gallery雪崩啊，最近都不是很稳定，可以看看吗

**Comment by zztisoftwyj** [comment]
![image](https://user-images.githubusercontent.com/13317571/45527505-9691f180-b80e-11e8-82b3-340135502ce5.png)

**Comment by pissang** [comment]
gallery 相关的问题在 https://github.com/ecomfe/echarts-gallery-feedback 反馈，这个是已知问题，正在努力修复
