### ISSUE TITLE
一个grid实现双y轴展示2条line，每条y轴的name和对应的刻度对调了没匹配上

### ISSUE THREAD

**Issue by limeng90** [apache/incubator-echarts#9069]
### One-line summary [问题简述]
一个grid实现双y轴展示2条line，每条y轴的name和对应的刻度对调了没匹配上

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
每条y轴的名字和刻度对应上。如图所示，我的options中series，和yaxis是对应的，但是画出的图y轴对调了

### ECharts option [ECharts配置项]

```javascript
option = {
如图
}

```

### Other comments [其他信息]

![2](https://user-images.githubusercontent.com/22675176/45528908-1e7afa00-b815-11e8-8aaa-1d1ad5777fd7.png)
![3](https://user-images.githubusercontent.com/22675176/45528911-2175ea80-b815-11e8-903e-a2d4d111a7bb.png)
![4](https://user-images.githubusercontent.com/22675176/45528913-233fae00-b815-11e8-9a9d-50e3cc05ed0c.jpg)

**Comment by Yi-Frank** [comment]
![_20180914125153](https://user-images.githubusercontent.com/24606096/45530400-fdb6a280-b81c-11e8-9b33-863a2939baa8.png)

yAxisIndex设置反了   好好去看下配置说明吧....
