### ISSUE TITLE
getDataURL获取的URL，折线图的线条不显示

### ISSUE THREAD

**Issue by vijay19920608** [apache/incubator-echarts#9073]
下载图片时，使用了getDataURL获取base64格式，在赋值给img的src上，折线图的线条不显示

原来的图
![_20180914145701](https://user-images.githubusercontent.com/28383371/45535025-a4a43a00-b82f-11e8-817e-5ff3fad5da7a.png)

下载后的图
![_20180914145733](https://user-images.githubusercontent.com/28383371/45535034-ac63de80-b82f-11e8-9354-f025ffc6fa02.png)

**Comment by pissang** [comment]
关闭动画试试呢？

**Comment by vijay19920608** [comment]
可以了，关闭动画
