### ISSUE TITLE
gallery示例经常老是访问不了，一直报缺少跨域头

### ISSUE THREAD

**Issue by anthinkingcoder** [apache/incubator-echarts#9074]
![image](https://user-images.githubusercontent.com/17498633/45537124-0798cf80-b836-11e8-9188-faabd9676dac.png)

**Comment by yaowei9363** [comment]
对,每天都有一段时间这样

**Comment by pissang** [comment]
Gallery 的问题请前往 https://github.com/ecomfe/echarts-gallery-feedback/issues 反馈，我们最近也在解决 gallery 访问不稳定的问题
