### ISSUE TITLE
number类型数据显示问题

### ISSUE THREAD

**Issue by Leescj** [apache/incubator-echarts#9075]
![image](https://user-images.githubusercontent.com/35555735/45539889-978e4780-b83d-11e8-9304-51a1fc8bea91.png)
请问如何将 整数数据显示保留两位小数  ，例如 80 显示为 80.00 ，我传入的数据是 80.00 但显示是整数80，请问该如何调整

**Comment by pissang** [comment]
可以 `label.formatter` 里用 toFixed 保留两位小数点
