### ISSUE TITLE
Echarts x axis and y axis

### ISSUE THREAD

**Issue by geekboy0801** [apache/incubator-echarts#9077]
### Change position with each other

Hi, there!
Highcharts has the ability to change the x and y axis position without changing series data.
It is done when we just set `chart.inverse=true`
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/inverted/

But with echarts, i can't implement this function.
In order to change the position of x and y axis, i should implement data structure differently every time.
Maybe you can think changing data structure is very easy, but when dealing with big and complicated data, it's not easy.

Could you let me know echarts supports this ability or not?
If not, what is the best solution?

**Comment by pissang** [comment]
In echarts `encode` is used to determine which dimension of data will be displayed on xAxis or yAxis. For example `{ x: 1, y: 0 }` will do to the flip. More details on this post https://echarts.apache.org/tutorial.html#Dataset

If you case is more like the highcharts demo in your link. You can simply swap the `xAxis` and `yAxis`

```js
option = {
    yAxis: {
        type: 'category',
        data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    xAxis: {
        type: 'value'
    },
    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
        type: 'line'
    }]
}
```
