### ISSUE TITLE
[Bug] 火狐浏览器下使用Mac触控板触发的滚动事件无法阻止默认事件

### ISSUE THREAD

**Issue by vincentfintend** [apache/incubator-echarts#9078]
### One-line summary [问题简述]

火狐浏览器下使用Mac触控板触发的滚动事件无法阻止默认事件(event.preventDefault不生效)。

当使用鼠标中间滚轮的时候，不会让页面触发滚动，可是使用Mac触控板的话，页面会发生滚动，chrome浏览器下则不会有此问题。

为了实现一些echart不支持的功能，我自己通过原生事件控制echart的dataZoom，然后发现火狐滚动事件有兼容性问题，不清楚echart的实现，但产生的问题是一样的，所以想看看大家有没有什么解决方案，或者实现过类似的事情。

```js
    const firefox = navigator.userAgent.indexOf('Firefox') != -1;
    firefox ? eCharts.addEventListener('DOMMouseScroll',mouseWheel) : (eCharts.onmousewheel = mouseWheel);
    const mouseWheel = (event) => {
      event = event || window.event;
      if (event.preventDefault) event.preventDefault();
      else event.returnValue = false;
    }
```
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]:firefox lastest
+ OS Version [操作系统类型和版本]: Mac OS 10.13.6

这个可以说是火狐的问题，鼠标中间的滚轮才可以正确的event.preventDefault()，Mac的触控板则不行，（需要有Mac触控板和普通鼠标滚轮去对比查看效果）。

**Comment by Ovilia** [comment]
这个应该是看 js 通用的解决方案，跟 ECharts 有什么直接的关系呢？

**Comment by vincentfintend** [comment]
@Ovilia 因为echarts一样存在不合预期的问题，尽管这是浏览器兼容性导致的问题。

因为浏览器的异同而导致的表现不一致，在火狐浏览器下，使用Mac触控板在echarts上触发滚轮事件无法与鼠标滚轮触发滚轮事件表现一致，我认为这应该算是一个可以去改善的问题。

Demo Link: [echart](http://www.echartsjs.com/gallery/editor.html?c=candlestick-sh)

在火狐浏览器下打开该link，然后通过F12，将右侧视图right-container添加属性height: 120%，使用mac触控板放大缩小k线图可以体验到我所说的问题。

> 如果认为浏览器兼容性带来的效果差距不属于需解决的问题，可以close此issue
