### ISSUE TITLE
Chart collapsed when set height of chart around 120px.

### ISSUE THREAD

**Issue by mya12321** [apache/incubator-echarts#9084]
### One-line summary [问题简述]

Chart collapsed when set height of chart around 120px.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0-rc.1
+ Browser version [浏览器类型和版本]: Google Chrome Version 69.0.3497.92
+ OS Version [操作系统类型和版本]: Linux version 4.18.7-1-default

### Expected behaviour [期望结果]

The same as in tutorials.

### ECharts option [ECharts配置项]

```javascript
option = {
        title: {
          text: 'ECharts entry example'
        },
        tooltip: {},
        legend: {
          data:['Sales']
        },
        xAxis: {
          data: ["shirt","cardign","chiffon shirt","pants","heels","socks"]
        },
        yAxis: {},
        series: [{
          name: 'Sales',
          type: 'bar',
          data: [5, 20, 36, 10, 10, 20]
        }]
      }

```

### Other comments [其他信息]

Using the same option as in tutorial, except for the size:
`<div id="main" style="width: 200px;height:120px;"></div>`
The result is like below: 
![screenshot_20180916_154129](https://user-images.githubusercontent.com/14355408/45594092-302edf80-b984-11e8-9de8-4400f62f22f8.png)

**Comment by pissang** [comment]
You can use `top`/`right`/`bottom`/`left` properties to layout each componet. But I don't suggest you still display so many components in such a small area.

**Comment by mya12321** [comment]
> You can use `top`/`right`/`bottom`/`left` properties to layout each componet. But I don't suggest you displaying so many components in such a small area.

I can remove other components, only remain chart content, but it's the same issue:
```javascript
option = {
        xAxis: {
          data: ["shirt","cardign","chiffon shirt","pants","heels","socks"]
        },
        yAxis: {},
        series: [{
          name: 'Sales',
          type: 'bar',
          data: [5, 20, 36, 10, 10, 20]
        }]
      }
```
The result like below: 
![screenshot_20180916_155546](https://user-images.githubusercontent.com/14355408/45594185-f65ed880-b985-11e8-9ca7-1ab4c1bf0115.png)
Once you change the height smaller, it should be much better: 
`<div id="chart" style="width: 150px;height: 80px;">`
![screenshot_20180916_160107](https://user-images.githubusercontent.com/14355408/45594243-b3513500-b986-11e8-98db-b36d4da651ac.png)

**Comment by luguokong** [comment]
> > You can use `top`/`right`/`bottom`/`left` properties to layout each componet. But I don't suggest you displaying so many components in such a small area.
> 
> I can remove other components, only remain chart content, but it's the same issue:
> 
> ```js
> option = {
>         xAxis: {
>           data: ["shirt","cardign","chiffon shirt","pants","heels","socks"]
>         },
>         yAxis: {},
>         series: [{
>           name: 'Sales',
>           type: 'bar',
>           data: [5, 20, 36, 10, 10, 20]
>         }]
>       }
> ```
> 
> The result like below:
> ![screenshot_20180916_155546](https://user-images.githubusercontent.com/14355408/45594185-f65ed880-b985-11e8-9ca7-1ab4c1bf0115.png)
> Once you change the height smaller, it should be much better:
> `<div id="chart" style="width: 150px;height: 80px;">`
> ![screenshot_20180916_160107](https://user-images.githubusercontent.com/14355408/45594243-b3513500-b986-11e8-98db-b36d4da651ac.png)

set the option.grid.top and option.grid.bottom at suitable value , the result will be normal

**Comment by mya12321** [comment]
> > > You can use `top`/`right`/`bottom`/`left` properties to layout each componet. But I don't suggest you displaying so many components in such a small area.
> > 
> > 
> > I can remove other components, only remain chart content, but it's the same issue:
> > ```js
> > option = {
> >         xAxis: {
> >           data: ["shirt","cardign","chiffon shirt","pants","heels","socks"]
> >         },
> >         yAxis: {},
> >         series: [{
> >           name: 'Sales',
> >           type: 'bar',
> >           data: [5, 20, 36, 10, 10, 20]
> >         }]
> >       }
> > ```
> > 
> > 
> > The result like below:
> > ![screenshot_20180916_155546](https://user-images.githubusercontent.com/14355408/45594185-f65ed880-b985-11e8-9ca7-1ab4c1bf0115.png)
> > Once you change the height smaller, it should be much better:
> > `<div id="chart" style="width: 150px;height: 80px;">`
> > ![screenshot_20180916_160107](https://user-images.githubusercontent.com/14355408/45594243-b3513500-b986-11e8-98db-b36d4da651ac.png)
> 
> set the option.grid.top and option.grid.bottom at suitable value , the result will be normal

Got it. Thanks.
