### ISSUE TITLE
配置项grid.tooltip.axisPointer.label.margin的数据类型错误？

### ISSUE THREAD

**Issue by DanterM** [apache/incubator-echarts#9090]
### One-line summary [问题简述]
配置项grid.tooltip.axisPointer.label.margin的数据类型应为Number，不应为Boolean

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4.x
+ Browser version [浏览器类型和版本]: Google Chrome 69.0.3497.92
+ OS Version [操作系统类型和版本]: macOS Mojave 10.14

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://echartsjs.com/option.html#grid.tooltip.axisPointer.label.margin 哪里是 boolean 了？
