### ISSUE TITLE
4.2.0 图例scroll 超出的部分并没有hidden

### ISSUE THREAD

**Issue by node-rookie** [apache/incubator-echarts#9091]
### One-line summary [问题简述]
如题：
![image](https://user-images.githubusercontent.com/7260662/45618004-ceb36180-baa6-11e8-9edd-f41fe7b078ba.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2.0-rc.1
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:mac os

### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/7260662/45618033-ee4a8a00-baa6-11e8-8c4b-2434be2248f3.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Duplicate of #9093

**Comment by ayesha-omarali** [comment]
Check if your `opts: {renderer: 'canvas'}` instead of 'svg', this fixed it for me!

**Comment by node-rookie** [comment]
> Check if your `opts: {renderer: 'canvas'}` instead of 'svg', this fixed it for me!

thank you, but i wanna use svg mode
