### ISSUE TITLE
Unclear API Docs on how to use Title Rich Text

### ISSUE THREAD

**Issue by civilwarrock** [apache/incubator-echarts#9092]
### One-line summary [问题简述]

I've been studying this for an hour or so and tinkering with it, but I cannot seem to understand how to use the rich text styles for the title option. Usually you get to define a formatter but there is no mention of it for a title. Are we able to use the rich text feature? Or is this a API Doc mistake?

Thanks.

https://ecomfe.github.io/echarts-doc/public/en/option.html#title.textStyle.rich

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by luguokong** [comment]
https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Rich%20Text

I think this doc will be useful

**Comment by civilwarrock** [comment]
> https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Rich%20Text
> 
> I think this doc will be useful

Thanks for the reply, I've also read that doc a few times, it's all for labels and components that have a formatter. It doesn't apply to the title component. I studied over the title component code, looks like rich text isn't being used: https://github.com/apache/incubator-echarts/blob/master/src/component/title.js

However, I'm not an expert in this repo so maybe rich text is enabled for the title component.

**Comment by civilwarrock** [comment]
@Ovilia Have you tried to style the title option using that doc yet? I'm on version 4.2.0-rc.1 and even following that page, you do not get a styled title.

**Comment by civilwarrock** [comment]
This would be why it's not working. I'm on the SVG renderer. I had to dig to find this, but now I understand. Thanks. Hope this helps someone else.

![image](https://user-images.githubusercontent.com/3253940/45667853-8e1c0e00-bacf-11e8-8475-afa7aae6c961.png)
