### ISSUE TITLE
k线图中color配置transparent，显示却不是空心的

### ISSUE THREAD

**Issue by 799677446** [apache/incubator-echarts#9094]
![2018-09-18 11 36 46](https://user-images.githubusercontent.com/13121299/45668155-556f4980-bb4e-11e8-9696-6bbd2ba94273.png)
<img width="381" alt="2018-09-18 11 36 57" src="https://user-images.githubusercontent.com/13121299/45668156-556f4980-bb4e-11e8-92ea-22b8c3adb38f.png">

实例demo全都是空心，请问下是什么问题引起的

**Comment by iamweilee** [comment]
试试4.2.0-rc.1版本
我用这个版本开发没这个问题

**Comment by git-stf-01** [comment]
@799677446 
为什么我显示的空心也不对。。。和楼主一样啊
