### ISSUE TITLE
你们的网页api是不是写错了。

### ISSUE THREAD

**Issue by lxd0130** [apache/incubator-echarts#9099]
### One-line summary [问题简述]
在api页面echartsInstance appendData中可视化建筑群的连接是<a href=\"ooption-gl.html#series-polygons3D\" target=\"_blank\">可视化建筑群（polygons3D）</a>
不应该是<a href=\"option-gl.html#series-polygons3D\" target=\"_blank\">可视化建筑群（polygons3D）</a>吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
谢谢，是写错了
