### ISSUE TITLE
折线图数据显示和坐标轴不一致

### ISSUE THREAD

**Issue by mouday** [apache/incubator-echarts#9101]
### One-line summary [问题简述]

折线图数据显示和坐标轴不一致

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 2.0
+ Browser version [浏览器类型和版本]: chrome v69
+ OS Version [操作系统类型和版本]: mac os 10.11.6

### Expected behaviour [期望结果]

期望显示正常

### ECharts option [ECharts配置项]

原有默认配置，官方示例
[http://www.echartsjs.com/examples/editor.html?c=line-stack](http://www.echartsjs.com/examples/editor.html?c=line-stack)

### Other comments [其他信息]

<img width="767" alt="wx20180919-151605 2x" src="https://user-images.githubusercontent.com/24365682/45737007-44423d80-bc1f-11e8-9689-310be5403d96.png">

**Comment by Ovilia** [comment]
把 stack 去掉

**Comment by mouday** [comment]
图表加载失败

**Comment by Ovilia** [comment]
把 stack 那行去掉……

**Comment by mouday** [comment]
ok，谢谢，这个参数。。。。
