### ISSUE TITLE
散点图，symbol通过 'image://url' 设置为图片，图片本身是方形，能否通过配置显示为圆形

### ISSUE THREAD

**Issue by Lost-Kun** [apache/incubator-echarts#9102]
### One-line summary [问题简述]
散点图，symbol通过 'image://url' 设置为图片，图片本身是方形，能否通过配置显示为圆形

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: macOS

### ECharts option [ECharts配置项]

```javascript
option = {
  seriers: [
    {
       type: 'scatter',
       symbol: 'image://https://apic.douyucdn.cn/upload/avatar/default/10_middle.jpg',
    }
  ]
}

```

**Comment by Ovilia** [comment]
不支持，把图片改圆的，周围的用透明的
