### ISSUE TITLE
从echarts3更新到4后，sankey图设置的visualmap inRange节点颜色失效

### ISSUE THREAD

**Issue by xianxianya** [apache/incubator-echarts#9105]
### One-line summary [问题简述]
react里相同option，从echarts3更新到4后，sankey图，visualmap里inRange设置不同类别的节点对应不同颜色失效了，节点都变成了白色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2.0-rc.1
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows7

### Expected behaviour [期望结果]
同一serie里某维度不同类别的节点对应不同颜色

### ECharts option [ECharts配置项]

```javascript
option = {
           serie:[{type:'sankey',
                       data:nodes,
                       links:links
            }],
           visualMap:[{type:'piecewise',
                              dimension:1,
                              categories:categories,
                              inRange:{color:colors}
                              }]
}

```

**Comment by xianxianya** [comment]
发现把dimension设为0是有效的，但是设为其他的就没有颜色了，这是echarts 4的bug吗

**Comment by Ovilia** [comment]
完整对例子给一下
