### ISSUE TITLE
引入微信小程序的的js文件会起冲突怎么解决

### ISSUE THREAD

**Issue by Bright2017** [apache/incubator-echarts#9123]
### One-line summary [问题简述]
引入微信小程序的的js文件echarts的提示框就不显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.4
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:windows
+ 微信小程序js版本:jweixin-1.0.0.js

### Expected behaviour [期望结果]

能显示提示框

### ECharts option [ECharts配置项]

```javascript
option = {
   tooltip: {
            trigger: 'axis'
  }
}

```

**Comment by Ovilia** [comment]
最新版本 ECharts 是支持 tooltip 的，如果还有问题，请到 https://github.com/ecomfe/echarts-for-weixin/issues 提问
