### ISSUE TITLE
touch events support + touch device legend touch scroll + manual coding

### ISSUE THREAD

**Issue by guylando** [apache/incubator-echarts#9124]
1. So my final goal is that the legend scroll will be controlled by swiping in touch device. Is there a way to do it?
2. I thought to implement myself if you would expose touch events but couldn't find information about touch events and only saw mouse events. So do you support touch events or plan to add it?
3. How can I add functionality to my chart without using echarts options? Is there some way to get raw access to the chart canvas so that I can add missing functionality by myself to my own chart while still using some of echarts canvas objects? If I get the html canvas object in javascript and start writing to it then I will probably mass up the echarts handling of the canvas so is there some built-in "clean" way to do that?

I am thinking about using HammerJS to discover swipe event on canvas legends and then trigger legendScroll echarts action.
https://hammerjs.github.io/recognizer-swipe/
https://ecomfe.github.io/echarts-doc/public/en/api.html#action.legend.legendScroll

If you would add swipe detection in echarts graphics object then you could just register onswipe similar to onclick here to add swipe scroll support:
https://github.com/apache/incubator-echarts/blob/master/src/component/legend/ScrollableLegendView.js#L120

Seems you already have some touch events handling here: https://github.com/apache/incubator-echarts/blob/master/src/component/helper/RoamController.js but they arent exposed in graphics

**Comment by guylando** [comment]
anyone?

**Comment by Ovilia** [comment]
I think you might try using SVG so that you can control the content more directly.
```js
var chart = echarts.init(container, null, { renderer: 'svg' })
```

**Comment by guylando** [comment]
@Ovilia 
Hi Olivia,
In my opinion the whole point of using echarts is that its the best CANVAS based charting library. There are plenty of more mature alternatives if using svg (such as Amcharts) and echarts lacks a lot of features when rendered as svg (plenty of github issues about that).
And the whole point of canvas is the better performance which I would not want to give up.
I have done research on canvas based charting and the main thing about that is that when using canvas based charting then you are mostly limited to what the charting library itself exposes. In this regard it seems that echarts is the most complete solution I found and I was able to achieve most of what I wanted using its canvas mode and the main obstacle encountered was the touch support required in the legend scrolling and in generel touch events support (which could allow me to implement the behavior myself as I described in the issue).

**Comment by Ovilia** [comment]
OK. Do you need access to the canvas object, or touch event?
For canvas object, it can be accessed by [chart.getDom](https://ecomfe.github.io/echarts-doc/public/en/api.html#echartsInstance.getDom). It returns the container of the chart, so it may be `<canvas>` or `<div>` depending on init. If it is the later one, you may call `getElementsByTagName` on the result.
For touch event, what interface do you need exactly?

**Comment by guylando** [comment]
@Ovilia getting access to the raw canvas html object is easy by just a normal query selector but I dont see how it will help since the whole echarts objects charting on top of the canvas will be unknown and thus any manual rendering or use of the raw canvas will not work good together with echarts. I would expect echarts to expose those abilities in the echarts graphics object which is AWARE of the echarts charting and objects on top of the canvas.

Echarts exposes events registration for echarts components: https://ecomfe.github.io/echarts-doc/public/en/api.html#events but there are no touch events in there so the interface I need is this same events interface but add touch events (including complex ones such as swipe) there so I can register to touch events for each echarts component.

Another request is that you add to scrollable legend interface a flag which adds swipe scroll support on touch devices but this will be easy for you if you add touch events to all components because then will just need to trigger legendScroll action on swipe.

Also additional question please? Is there some way to reach echarts support faster? Because it took 11 days to get an answer here and if we put system in production that is a big problem.

**Comment by Ovilia** [comment]
I'm afraid ECharts cannot provide touch events for all components. Or at lease we are not intended to do so.
Sorry for the late reply. As you can see, ECharts has so many issues and we work in our spare time to do all these things.
I'm closing this issue for we cannot provide a better solution right now.

**Comment by guylando** [comment]
@Ovilia Suggestion: If you add a (not too expensive) paid plan which includes dedicated prioritized support for users who pay then I am sure many will pay and then it will compensate your time to spend time adding features like touch support.
