### ISSUE TITLE
Documentation for echarts.util

### ISSUE THREAD

**Issue by jaworek** [apache/incubator-echarts#9125]
Is there a documentation for echarts.util methods? 

I am trying to implement draggable bar charts and based on this [example](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#An%20Example:%20Implement%20Dragging).
It seem that this example uses functions that are not described in the API documentation.

**Comment by guylando** [comment]
@jaworek check out code comments here: https://github.com/apache/incubator-echarts/tree/master/src/util
