### ISSUE TITLE
键盘缩放事件

### ISSUE THREAD

**Issue by 799677446** [apache/incubator-echarts#9128]
图表中直接按上下键可以缩放图表，左右键可以直接左右来回切指标

**Comment by pissang** [comment]
可以试试监听键盘事件然后 setOption 去缩放和切换

**Comment by 799677446** [comment]
能否给个例子参考下，如果一直按方向键启不是一直接在setOption么？？

**Comment by pissang** [comment]
监听`keydown`事件就行了

**Comment by 799677446** [comment]
![image](https://user-images.githubusercontent.com/13121299/46069534-520f3a00-c1ae-11e8-8e0d-15be8c18576a.png)
你好，现有需求是以鼠标移动的指标为中心点，点击方向键以这个中心点放大或者缩小，主要是麻烦在这一点上，想请教下有什么好思路解决

**Comment by 799677446** [comment]
![image](https://user-images.githubusercontent.com/13121299/46069643-8a167d00-c1ae-11e8-92ab-185a67630491.png)
你好，现在的需求是以鼠标移动到的指标为中心点，通过方向键以这个中心点放大缩小，主要是这点不知如何处理，想请教下有什么好方法解决

**Comment by iamweilee** [comment]
去看看dataZoom的start和end startValue和endValue的配置项就知道了

**Comment by 799677446** [comment]
你好，我用了datazoom设置了startValue跟endValue，发现设定后都是不能以指标的中心点进行缩放，能否给个deom参考下

**Comment by iamweilee** [comment]
你得先找到中心点的dataIndex，然后再去计算startvalue endvalue，例子就不贴了

**Comment by pissang** [comment]
试试 convertFromPixel 方法

**Comment by iamweilee** [comment]
鼠标移动到对应光标是什么意思
