### ISSUE TITLE
官网文档是否有误

### ISSUE THREAD

**Issue by clChenLiang** [apache/incubator-echarts#9131]
### [文档链接](http://www.echartsjs.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E6%A0%B7%E5%BC%8F%E7%AE%80%E4%BB%8B)
内容:
> 如果保存为 UMD 格式的 JS 文件，那么支持了自注册

其中 `UMD` 是否为 `CMD` ?

**Comment by clChenLiang** [comment]
另,英文文档的对应处,并没有 js 文件的规范描述, 且,出现中文. 
> 或者
因为没有找到文档的 `github` 仓库,所以就在这里提了

**Comment by pissang** [comment]
`UMD` 不是笔误，参见具体的规范描述 https://github.com/umdjs/umd

**Comment by clChenLiang** [comment]
好的，谢谢。可以关闭了
