### ISSUE TITLE
graph设置有没有scalelimit这样的配置

### ISSUE THREAD

**Issue by jasminecjc** [apache/incubator-echarts#9132]
### One-line summary [问题简述]

geo类型图有scalelimit控制最大最小缩放，graph也有控制缩放的需求，尤其是在使用触控板的时候，缩放graph很容易缩成一团，糊到看不清

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
缩放你们给 出的demo就可以发现问题
http://echarts.baidu.com/examples/editor.html?c=graph-force

### Expected behaviour [期望结果]
希望graph图能有控制最大最小缩放的配置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/13568376/46069766-d5309000-c1ae-11e8-8d37-1b84c3d22779.png)
触控板很容易缩小到这种糊的状态

**Comment by pissang** [comment]
graph 也支持 scaleLimit，跟 geo 用法一样，文档里有遗漏
