### ISSUE TITLE
需要在折线图的tooltip面板上显示百分号，感觉有一些问题。

### ISSUE THREAD

**Issue by dickbinge** [apache/incubator-echarts#9135]
期望的结果图：

结果图：

### One-line summary [问题简述]
如下图所示，我需要在这个柱状折线图的tooltip上显示数据，但是第三列异常率需要显示百分号，于是我用formatter:"{b0}<br />{a0}: {c0}<br />{a1}: {c1}<br />{a2}: {c2}%", 第三列数据的百分号出现了，但是点击上方的legend 出现如下的问题。第三列依然存在，且是这样的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/27794570/46073803-7f60e580-c1b8-11e8-82d5-9dec82837e30.png)

###目前的结果：
![image](https://user-images.githubusercontent.com/27794570/46073983-f1d1c580-c1b8-11e8-9422-acda6639168f.png)

### ECharts option [ECharts配置项]

```javascript
option = {
       tooltip={
                show:true,
                trigger: 'axis',
                axisPointer: {
                    type: 'shadow',
                },
                formatter:"{b0}<br />{a0}: {c0}<br />{a1}: {c1}<br />{a2}: {c2}%",
                textStyle:{
                    align:'left',
        },
}

```

**Comment by wangcongyi** [comment]
需要自己 formatter
例如：
```js
  option = {
      tooltip: {
          formatter: params => params[0].value + '%'
    }
}
```

**Comment by pissang** [comment]
是不是只有两个系列...
