### ISSUE TITLE
How to draw vertical lines between bars when xAxis.type='category'

### ISSUE THREAD

**Issue by geekboy0801** [apache/incubator-echarts#9138]
Hi! 
I have some issues with horizontal markline when bar chart mode.
Since x axis type should be category when we draw bar chart, i can't draw markline between two bars. (like this)

![image](https://user-images.githubusercontent.com/40581883/46100762-74419180-c187-11e8-991f-1f5d72c8d6c3.png)

So i want to know how we can implement this...
Could you help me please? 

Thank you!

**Comment by pissang** [comment]
Try graphic component to draw this line
