### ISSUE TITLE
仪表盘的圆环能否设置圆角？

### ISSUE THREAD

**Issue by zlpcrmm** [apache/incubator-echarts#9140]
### One-line summary [问题简述]

项目需求是仪表盘的环形两端是圆角，查了文档只有柱状图可以设置，请问gauge TYPE的图形能支持圆角吗？谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不支持圆角设置

**Comment by Ovilia** [comment]
相关问题：#7121
