### ISSUE TITLE
myecharts.addData 报错，未定义

### ISSUE THREAD

**Issue by xuhuiwqq** [apache/incubator-echarts#9147]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
是 [appendData](http://echartsjs.com/api.html#echartsInstance.appendData) 吧？
