### ISSUE TITLE
echarts散点图怎么取消事件冒泡

### ISSUE THREAD

**Issue by ypkb** [apache/incubator-echarts#9150]
### One-line summary [问题简述]

 myChart.on('click', (e) => {})可以点击到基于散点图画出的点
 myChart.getZr().on('click', (e) => {})可以点击基于canvas上的任意区域
但是当点击到散点图时我不希望myChart.getZr().on('click', (e) => {})也触发事件
也就是取消掉echarts的事件冒泡

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   v4
+ Browser version [浏览器类型和版本]:Google Chrome 已是最新版本 版本 69.0.3497.100（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:  

### Expected behaviour [期望结果]

希望有方法可以解决

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
`event.stopPropagation()` 可以不？

**Comment by sanliu2015** [comment]
请问怎么解决的，我也想把tree的事件冒泡取消掉

**Comment by sanliu2015** [comment]
> `event.stopPropagation()` 可以不？

试了都不行啊

**Comment by RITAWONG** [comment]
e.event.stop("click");

**Comment by coldice945** [comment]
@RITAWONG 感谢。RITAWONG 提供的方法可用。
