### ISSUE TITLE
Drawing line doesn't appear in toolbox

### ISSUE THREAD

**Issue by rezaxdi** [apache/incubator-echarts#9153]
Hi there,
Is drawing line feature (mark) deleted from e-charts v4 ?
Is there any plugin that can bring the function back or I have to switch to v2 ?

**Comment by Ovilia** [comment]
Hi, you may draw lines with [graphic.line](https://ecomfe.github.io/echarts-doc/public/en/option.html#graphic.elements-line.type) or [series.markLine](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.markLine).
