### ISSUE TITLE
请教个饼图的实现方案

### ISSUE THREAD

**Issue by limeng90** [apache/incubator-echarts#9155]
### One-line summary [问题简述]

请教个饼图的实现方案

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:last version
+ Browser version [浏览器类型和版本]:chrome last version
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]

如图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![4](https://user-images.githubusercontent.com/22675176/46252819-d9a3c400-c4a0-11e8-92c4-dccb71ed5c4b.png)

**Comment by limeng90** [comment]
请教一下，这两根线怎么实现

**Comment by Ovilia** [comment]
https://ecomfe.github.io/echarts-doc/public/en/option.html#graphic.elements-line.type
