### ISSUE TITLE
左右方向键控制tooltip左右平移，到最左边或最右边会消失，如何才能再向左或再向右平移

### ISSUE THREAD

**Issue by 799677446** [apache/incubator-echarts#9159]
左右方向键控制tooltip左右平移，到最左边或最右边会消失，如何才能继续向左或再向右平移

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Chrome 69
+ OS Version [操作系统类型和版本]:

![image](https://user-images.githubusercontent.com/13121299/46255411-15558280-c4cf-11e8-8ffd-472c833ffd36.png)

**Comment by iamweilee** [comment]
感觉你这些都是业务逻辑，参考文华财经或者其它行情软件的业务逻辑可能你就知道怎么实现了
