### ISSUE TITLE
label color 支持回调函数

### ISSUE THREAD

**Issue by liyuanqiu** [apache/incubator-echarts#9160]
### One-line summary [问题简述]
经过研究以及搜索，series.scatter.label.formatter 似乎无法根据params.value的取值来决定显示什么颜色。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: latest
+ Browser version [浏览器类型和版本]: chrome 69
+ OS Version [操作系统类型和版本]: macOS

### Expected behaviour [期望结果]
1. 是否可以给出解决方法，或是workaround，来达到效果
2. 如果目前无解，serials.scatter.label.color 是否可以支持传入function(params) {}

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {},
    yAxis: {},
    series: [{
        symbolSize: 20,
        data: [
            [10.0, 8.04],
            [8.0, 6.95],
            [13.0, 7.58],
            [9.0, 8.81],
            [11.0, 8.33],
            [14.0, 9.96],
            [6.0, 7.24],
            [4.0, 4.26],
            [12.0, 10.84],
            [7.0, 4.82],
            [5.0, 5.68]
        ],
        type: 'scatter',
        label: {
            show: true,
            position: 'top',
            formatter(params) {
                // TODO 此处无法根据value来决定显示什么颜色
                return params.value[1];
            },
            // TODO 此处是否增加支持传入 function(params)
            color: 'black',
        }
    }]
};


```

### Other comments [其他信息]

http://jsfiddle.net/5oqfbgz6/

**Comment by Ovilia** [comment]
Not reproducible with v4.2.1: http://jsfiddle.net/ovilia/wyontx73/1/
