### ISSUE TITLE
Reduce gap width between stacked bars

### ISSUE THREAD

**Issue by shrenik007** [apache/incubator-echarts#9163]
I have stacked bar chart and i want to reduce space between all the bar stacks. 
How can I do that?
![chart](https://user-images.githubusercontent.com/16061768/46457431-f0fbed80-c7cf-11e8-875d-180d8dd12d8d.png)
Above is the image of chart whose gap width i want to reduce

**Comment by Ovilia** [comment]
You may set [barWidth](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-bar.barWidth) to be larger so that the bars are wider. Or you may set [grid width](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.width) to be smaller.
