### ISSUE TITLE
How do I change map of world to the map of USA for geo-3D map ? I need bar graphs on the top of map of USA.

### ISSUE THREAD

**Issue by lrjoshi** [apache/incubator-echarts#9164]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Here's an example: http://www.echartsjs.com/examples/editor.html?c=bar3d-global-population&gl=1
