### ISSUE TITLE
如何修改world.js使世界地图可以显示china.js中国地图中的省界？

### ISSUE THREAD

**Issue by 437072341** [apache/incubator-echarts#9167]
### One-line summary [问题简述]

如何修改world.js使世界地图可以显示china.js中国地图中的省界？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

希望能提示修改方法
如何修改world.js使世界地图可以显示china.js中国地图中的省界？
可否修改加入省内城市分界？
只能修改json文件吗？js文件方便修改吗？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
ECharts 官方不提供地图下载，相关使用问题和风险需自行解决，建议使用百度地图的地图，参考：http://www.echartsjs.com/examples/#chart-type-map
