### ISSUE TITLE
求教xAxis.axisPointer.label的位置问题

### ISSUE THREAD

**Issue by iamweilee** [apache/incubator-echarts#9168]
### One-line summary [问题简述]

![21212](https://user-images.githubusercontent.com/1096160/46583493-e7ea7500-ca8a-11e8-8075-cc87510bb30b.png)

如图黄色方框的部分如何可以显示在图标的右边，同时axisLabel仍然在左边，效果如下图黄色方框区域:
![22332](https://user-images.githubusercontent.com/1096160/46583527-5d564580-ca8b-11e8-8e85-0df64a015897.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts4.1.0-rc2
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: win8

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
不明白你的需求是什么，文档在 http://www.echartsjs.com/option.html#yAxis.axisPointer.label 而且似乎应该是 yAxis 的

**Comment by iamweilee** [comment]
需求是有一个position属性配置label的位置（left or right）  你给的文档中并没有类似的属性。

**Comment by Ovilia** [comment]
right 的话是希望在哪里显示？整个 grid 的右侧么？那似乎应该把 yAxis 放到右侧。

**Comment by Ovilia** [comment]
看起来应该是需要增加一个配置项

**Comment by iamweilee** [comment]
是哦，最好另外再多加一个配置项，用于控制label相对于axisPointer的那根线（姑且成为line）的位置，目前是默认居于中线的，但若想让label在line的右侧且紧贴line则是做不到的，同样的左侧、上侧、下侧也是无法做到的目前。

**Comment by iamweilee** [comment]
找到配置项了 哈哈哈哈哈哈哈 脑子不够灵活 现在终于想到怎么配置了

**Comment by Ovilia** [comment]
@iamweilee 可否说下怎么配置的？

**Comment by xiaotianxt** [comment]
> 找到配置项了 哈哈哈哈哈哈哈 脑子不够灵活 现在终于想到怎么配置了

同问大哥，怎么配置的？

**Comment by xiaotianxt** [comment]
> > 找到配置项了 哈哈哈哈哈哈哈 脑子不够灵活 现在终于想到怎么配置了
> 
> 同问大哥，怎么配置的？

我想明白了，两个 axes，其中一个隐藏起来只显示 axisPointer 就行啦！

**Comment by 2784899153** [comment]
可以跟我说说是怎么配置的吗
