### ISSUE TITLE
大约6000条数据，setOption 花费了10S

### ISSUE THREAD

**Issue by Carolineliu** [apache/incubator-echarts#9169]
### One-line summary [问题简述]
   this.echart.setOption({
            series: this.series
        })

在vue里面，我执行了这段代码，大约6000条数据，执行了12s，能有什么方法优化吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts: "^4.1.0",
chrome:'最新版'

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
折线图还是什么图表类型？

**Comment by Carolineliu** [comment]
是折线图类型，我把this.echart改成echart就很快的出来了

**Comment by 100pah** [comment]
把 chart 放到 this 上会被 vue 给每个属性做包装，会很慢。
