### ISSUE TITLE
在BMap上如何绘制连线能够实现向右连线

### ISSUE THREAD

**Issue by yiptsangkin** [apache/incubator-echarts#9173]
### One-line summary [问题简述]
在BMap上如何绘制连线能够实现向右连线，即北京连接洛杉矶是向右画线的，echart2是可以的，echart3不知道为什么不行。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:chrome 69
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
能够根据需要确定在世界地图上，是要把点画在左边的北美洲还是右边的北美洲

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这应该在百度地图上调用接口吧？

**Comment by yiptsangkin** [comment]
应该不是，我是用echart画连线的哈，而且echart2是可以的，3跟百度地图的方法也不一样了。

**Comment by Ovilia** [comment]
“左边的北美洲还是右边的北美洲”是什么意思，为什么会有两个北美洲？

**Comment by yiptsangkin** [comment]
就是echarts跟bmap结合，如果屏幕足够大的话，会出现两个美洲，左边一个，右边一个，我昨天到百度地图那边提了反馈，回复说是已知的bug

**Comment by yiptsangkin** [comment]
说是暂不支持跨日期线画轨迹

**Comment by Ovilia** [comment]
嗯，我理解这的确是百度地图的问题
