### ISSUE TITLE
我们是否可以全局设置animation 为false?

### ISSUE THREAD

**Issue by gdutwyg** [apache/incubator-echarts#9174]
### One-line summary [问题简述]
我这边地图实例了很多个，不想一个个去设置animation 为false，请问是否有全局的设置方法？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4
+ Browser version [浏览器类型和版本]: 69
+ OS Version [操作系统类型和版本]:window10

### Expected behaviour [期望结果]
可以全局设置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#animation

**Comment by gdutwyg** [comment]
@Ovilia  我是想覆盖默认的true，全局覆盖，第二次实例化不用传`animation: false`

**Comment by Ovilia** [comment]
哦，不行的，传个 animation: false 很麻烦么？

**Comment by Ovilia** [comment]
嗯，这个是不能改的

**Comment by gdutwyg** [comment]
好吧，因为我们公司的管理平台里面的地图很多，不想一个一个加，想找有没有快捷的方法

**Comment by Ovilia** [comment]
没有，这个加一下也不麻烦吧……

**Comment by gdutwyg** [comment]
嗯嗯，thanks
