### ISSUE TITLE
bmap的画线有没有办法随着线的移动改变线的颜色

### ISSUE THREAD

**Issue by GeiDiao** [apache/incubator-echarts#9175]
![image](https://user-images.githubusercontent.com/30138064/46603789-c048ea80-cb26-11e8-9b27-3d45b171a13a.png)
这个效果跟官网的先特效有些像，我想让线在运动的过程中会改变颜色，由此来达到显示线路客流量变化的效果

**Comment by Ovilia** [comment]
边走边改颜色好像不行，类似的效果：http://gallery.echartsjs.com/editor.html?c=bmap-bus

**Comment by GeiDiao** [comment]
> 边走边改颜色好像不行，类似的效果：http://gallery.echartsjs.com/editor.html?c=bmap-bus

好吧，看来我只有另想办法了
