### ISSUE TITLE
通过dispatchAction方法触发关系图的缩放无效

### ISSUE THREAD

**Issue by overrei** [apache/incubator-echarts#9177]
### One-line summary [问题简述]
我试图用dispatchAction触发关系图的缩放方法，但是并没有生效。
我在源码里面找到的事件类型类型graphRoam，通过这个可以监听到缩放事件。但是无法通过这个类型触发缩放

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2.0-rc.1
+ Browser version [浏览器类型和版本]:chrome69
+ OS Version [操作系统类型和版本]:win7

### ECharts option [ECharts配置项]

```javascript
 myChart.dispatchAction({
            originX: 682,
            originY: 425,
            type: 'graphRoam',
            zoom:1.1, 
            // seriesId: id
            seriesIndex: 0 
  });

```

**Comment by Ovilia** [comment]
graph 的 action 确实不支持 groupRoam。http://echarts.baidu.com/api.html#action.graph
