### ISSUE TITLE
仪表盘为什么没有示例啊

### ISSUE THREAD

**Issue by kylinthinker** [apache/incubator-echarts#9180]
### One-line summary [问题简述]

仪表盘为什么没有示例啊

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

Echarts 4.x  demo
其他的图表都有示例，为什么仪表盘的没有示例啊

### Expected behaviour [期望结果]

添加一个示例

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/examples/#chart-type-gauge
http://gallery.echartsjs.com/explore.html#charts=gauge~sort=rank~timeframe=all~author=all
