### ISSUE TITLE
try to make echarts international

### ISSUE THREAD

**Issue by ramarro123** [apache/incubator-echarts#9183]
for people that doesn't understand chinese, echarts it's a bit hard to get.
some docs are in chinese, some examples are in chinese.

some browser doesn't have chinese font installed :)

do you plan to switch to english at a certain time to make it more international?

**Comment by ramarro123** [comment]
now i am on osx, but basically it shows little square

**Comment by Ovilia** [comment]
OK. I understand. We will discuss about this problem. Thank you.
