### ISSUE TITLE
Event listener on group of bars in bar-graph

### ISSUE THREAD

**Issue by hamidhasnain** [apache/incubator-echarts#9186]
https://jsfiddle.net/hmdhs/dty2nb8g/

Echarts version: 4.2.0

I need to publish the data when user selects the group of bars associated to each x-axis label. I don't see any way to select the group on click as the columns/grid can't be made clickable. Though, the individual bars can be made clickable using onclick and contains data in their onclick callback params.

Is there a way to select the group?

**Comment by Ovilia** [comment]
Seems not to be feasible right now.
