### ISSUE TITLE
Echarts 4.x 在线定制，graph图表渲染时会有透明度

### ISSUE THREAD

**Issue by yuanlove521** [apache/incubator-echarts#9190]
在线定制内容：
    图表：
        柱状图
        折线图
        饼图
        关系图
        仪表盘
    坐标系：
        直角坐标系
    组件：
        标题
        图例
        提示框
        标线
    其他选项：
        SVG渲染

正常引入
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
    </head>
    <body>
        <script src="/echarts.min.js"></script>
        <script src="/iconfont.js"></script>
        <div id="app"></div>
    </body>
</html>
```
在渲染graph图表时出现透明度问题
![image](https://user-images.githubusercontent.com/19182582/46730417-a8a26b00-ccba-11e8-80d8-59cbfbf29a1a.png)

鼠标经过元素之后又恢复正常了

**Comment by Ovilia** [comment]
代码？

**Comment by yuanlove521** [comment]
echarts配置：
{
    "title": {
        "text": ""
    },
    "series": [
        {
            "type": "graph",
            "focusNodeAdjacency": true,
            "roam": true,
            "emphasis": {
                "lineStyle": {
                    "width": 4
                },
                "edgeLabel": {
                    "show": true
                }
            },
            "data": [
                {
                    "symbolSize": 18,
                    "name": "年龄",
                    "value": "年龄",
                    "x": -22,
                    "y": -20,
                    "itemStyle": {
                        "color": "#547b95"
                    },
                    "label": {
                        "show": true,
                        "color": "#547b95",
                        "position": "bottom"
                    },
                    "emphasis": {
                        "itemStyle": {
                            "borderWidth": 4,
                            "borderColor": "#547b95"
                        }
                    }
                },
                {
                    "symbolSize": 18,
                    "name": "性别",
                    "value": "性别",
                    "x": 32,
                    "y": 12,
                    "itemStyle": {
                        "color": "#547b95"
                    },
                    "label": {
                        "show": true,
                        "color": "#547b95",
                        "position": "bottom"
                    },
                    "emphasis": {
                        "itemStyle": {
                            "borderWidth": 4,
                            "borderColor": "#547b95"
                        }
                    }
                },
                {
                    "symbolSize": 18,
                    "name": "毕业院校",
                    "value": "毕业院校",
                    "x": -32,
                    "y": 12,
                    "itemStyle": {
                        "color": "#547b95"
                    },
                    "label": {
                        "show": true,
                        "color": "#547b95",
                        "position": "bottom"
                    },
                    "emphasis": {
                        "itemStyle": {
                            "borderWidth": 4,
                            "borderColor": "#547b95"
                        }
                    }
                },
                {
                    "symbolSize": 18,
                    "name": "公司",
                    "value": "公司",
                    "x": 32,
                    "y": -12,
                    "itemStyle": {
                        "color": "#547b95"
                    },
                    "label": {
                        "show": true,
                        "color": "#547b95",
                        "position": "bottom"
                    },
                    "emphasis": {
                        "itemStyle": {
                            "borderWidth": 4,
                            "borderColor": "#547b95"
                        }
                    }
                },
                {
                    "name": "我",
                    "symbolSize": 60,
                    "x": 0,
                    "y": 0,
                    "itemStyle": {
                        "color": "#de7e7b",
                        "fontSize": 14
                    },
                    "label": {
                        "show": true,
                        "position": "inside"
                    }
                }
            ],
            "links": [
                {
                    "source": "我",
                    "lineStyle": {
                        "color": "#666"
                    }
                },
                {
                    "source": "我",
                    "target": "年龄",
                    "lineStyle": {
                        "color": "#666"
                    }
                },
                    {
                    "source": "我",
                    "target": "性别",
                    "lineStyle": {
                        "color": "#666"
                    }
                },
                {
                    "source": "我",
                    "target": "毕业院校",
                    "lineStyle": {
                        "color": "#666"
                    }
                },
                    {
                    "source": "我",
                    "target": "公司",
                    "lineStyle": {
                        "color": "#666"
                    }
                }
            ]
        }
    ]
}
打开[此链接](http://www.echartsjs.com/examples/editor.html?c=graph-force2)，将上述代码粘贴复制。可以看到问题的复现

**Comment by 100pah** [comment]
可暂时将 `edgeLabel: true` 去掉。下版本修复。

**Comment by 100pah** [comment]
Fixed and will be released in 4.2.0-rc.3.

**Comment by SeeFuturer** [comment]
![image](https://user-images.githubusercontent.com/25840609/56739814-3438a080-67a2-11e9-978e-f8f08d18565f.png)
想问下引入自定义图片报错，有没有解决方案
