### ISSUE TITLE
横坐标怎么设定起始和末尾时间，数据就在这段区间加载，但是数据是动态的，不知道数据中时间集合

### ISSUE THREAD

**Issue by Carolineliu** [apache/incubator-echarts#9193]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
坐标轴用 `'time'` 类型，然后设 `'min'`、`'max'` 可以不？

**Comment by Carolineliu** [comment]
已经解决了，谢谢，我接到数据的时候update xAxis了，设定了时间轴范围
