### ISSUE TITLE
柱状图一组数据（根据正负值）显示在同一水平线上不同颜色（显示同一方向）

### ISSUE THREAD

**Issue by hxiaol** [apache/incubator-echarts#9201]
### One-line summary [问题简述]
柱状图一组数据（根据正负值）显示在同一水平线上不同颜色
显示柱状图方向不同

 {
        name: 'aa',
        type: 'bar',
        xAxisIndex: 1,
        yAxisIndex: 1,
        data: [12,22,-10,-5,11,31],
        itemStyle: {
          color: function (p) {
            return p.value > 0 ? '#eb3d42' : '#00802d';
          }
        }       
      }

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

柱状图一组数据（根据正负值）显示在同一水平线上不同颜色
显示柱状图方向相同

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
```js
var data = [12, 22, -10, -5, 11, 31];

var displayData = data.map(v => Math.abs(v));

option = {
    xAxis: {
        data: ['a', 'b', 'c', 'd', 'e', 'f']
    },
    yAxis: {
        
    },
    series: {
        name: 'aa',
        type: 'bar',
        data: displayData,
        itemStyle: {
            color: function(p) {console.log(p)
                return data[p.dataIndex] > 0 ? '#eb3d42' : '#00802d';
            }
        }
    }
}
```

**Comment by hxiaol** [comment]
谢谢。可以了

**Comment by hks2002** [comment]
如果是使用Dataset的要怎么操作? 现在的主要问题是柱状图的 color function(p)的 参数p里面没有data的数据. 在散点图里面就有, 可以用p.data(1)这样获得一条数据里面的其他字段的值,来进行判断.
