### ISSUE TITLE
lines 线不显示的问题（迁徙lines）

### ISSUE THREAD

**Issue by cd-smallBear** [apache/incubator-echarts#9202]
### One-line summary [问题简述]
设置series : lines 后，数据更新后再 用setOption 设置 setires 后，没有lines线条 ，必须刷新重绘，才会正常显示 lines

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.01
+ Browser version [浏览器类型和版本]:  chrome
+ OS Version [操作系统类型和版本]: 

### Expected behaviour [期望结果]

刷新后，当我再次点击中国时，lines 线，可以重绘

[示例代码](http://gallery.echartsjs.com/editor.html?c=xR2-eoMyVx&v=1)

**Comment by Ovilia** [comment]
可以在 http://gallery.echartsjs.com/editor.html 复现一下简单的例子么，把不是必须的部分删去，越简单越好

**Comment by dfEric** [comment]
@Ovilia 我也被这个问题困扰了，我将代码示例简化了

[示例代码](http://gallery.echartsjs.com/editor.html?c=xgErnnK4p0&v=2)

点击point1之后绘制point2和lines,effectLines,过5秒自动刷新之后point2在，但是线都没了

不知道是不是同一个问题

**Comment by cd-smallBear** [comment]
@Ovilia [示例代码](http://gallery.echartsjs.com/editor.html?c=xR2-eoMyVx&v=1)
再次点击 中国 的时候 ，没有绘出线图

**Comment by cd-smallBear** [comment]
已经找出问题，用lines，决不能zoom geo ，给下面的同学加点buffer

**Comment by mzy2240** [comment]
@cd-smallBear 你能稍微解释下什么是不能zoom geo吗？ 之前也碰到了同样的问题，如果用setoption更新series data scatter能正常更新但lines就会消失， @Ovilia 也验证了是bug但还没有修复，请问你找到解决方案了吗？多谢！
