### ISSUE TITLE
[New Feature] About realize voice visualization 

### ISSUE THREAD

**Issue by NumerHero** [apache/incubator-echarts#9204]
Hi 文xian莉zhe女神 @Ovilia :

With web audio API development, hope ECOMFEers can visualize dataes of voice !

I make a simple example like this:

[e.g.](https://github.com/NumerHero/animations/tree/master/voice-virtual-animation)
  
## Expected behaviour

![gif](https://numerhero.github.io/assets/download/animations/voice-virtual.gif)

Yours Sincerely

**Comment by Ovilia** [comment]
Cool!
Closing because it's not related to ECharts project. But loooking forward to your new work. 😄

**Comment by NumerHero** [comment]
ok , Thx 🌻
