### ISSUE TITLE
How to add additional geocoords?

### ISSUE THREAD

**Issue by Andy-Post** [apache/incubator-echarts#9205]
Hey there,

I need to know how to add additional geoCoordinates on this:
https://ecomfe.github.io/echarts-examples/public/editor.html?c=geo-lines

In the example planes flying from A to B - how to get it done that the planes are flying from A to B over C?

Thanks for your help!

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Make another B to C.
