### ISSUE TITLE
k线如果设置背景色为透明则实体部分会被上下影线穿过实体，之前在serie中用data字段引入数据没这个问题，现在使用dataset引入数据则出现了这个问题

### ISSUE THREAD

**Issue by iamweilee** [apache/incubator-echarts#9211]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
复现的代码给一份～

**Comment by iamweilee** [comment]
又发现个新问题，使用dataset引入数据后，通过chart.getOption得到的配置数据和通过之前setOption设置进去的数据项的值并不完全一致，似乎有些值没有设置进去，但是渲染的结果却是正确的。这让人很疑惑。。
