### ISSUE TITLE
怎么控制tree图的显示位置

### ISSUE THREAD

**Issue by side9527** [apache/incubator-echarts#9216]
很抱歉打扰了
配置中开启了缩放和平移
![image](https://user-images.githubusercontent.com/22114281/46859142-7d955400-ce3f-11e8-816f-cd7fc6deaa41.png)
当tree图移到上图所示位置时，点击最上面的节点，tree图就会消失了，怎么规避这个问题呢

**Comment by side9527** [comment]
前几天找到了一个比较蹩脚的解决方法，就是点击节点的时候根据chartChild._chartsViews[0]._data._graphicEls.length 来判断点击的节点是否为根节点（length < 3即为根节点），如果是根节点就使用chartChild.setOption(chartChild.getOption())重新产开，也算是不让他收起根节点吧，别的方法找了很多没找到，就先暂时用的这个，希望维护的大大可以开发一个控制每个节点是否能收缩的功能

**Comment by deqingli** [comment]
#10291
