### ISSUE TITLE
Echarts地图，visualMap颜色渐变IE兼容性问题，chrome浏览器没问题

### ISSUE THREAD

**Issue by q1017269237** [apache/incubator-echarts#9218]
### One-line summary [问题简述]
我在Echarts的visualMap里，颜色填充为白色到藏青色，在IE浏览器里显示从中间向两端渐变，
chrome浏览器里正常从一端向另一端渐变

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.5
+ Browser version [浏览器类型和版本]:IE:11.0.9600.18738IS   Chrome:68.0.3440.106
+ OS Version [操作系统类型和版本]:Win7 旗舰版

### Expected behaviour [期望结果]
IE浏览器下，Echarts的visualMap组件，颜色渐变正常从一端向另一端渐变

### ECharts option [ECharts配置项]

```javascript
option = {
	  visualMap: {		        
			min: 0,		        
			max: 30,		   
			left: 'left',		        
			top: 'bottom',		        
			text: ['高','低'],           // 文本，默认为数值文本
			calculable: true,
			type: 'continuous',
			inRange: {
	                      color: ['#FFFFFF', '#4472C5']
	                }
		}
}

```

### Other comments [其他信息]

![_20181015135313](https://user-images.githubusercontent.com/44088032/46932353-e4a24b00-d081-11e8-848d-e47becd5b2a3.png)
![_20181015135413](https://user-images.githubusercontent.com/44088032/46932367-f1bf3a00-d081-11e8-8e47-49dfe9f69bd8.png)

**Comment by Ovilia** [comment]
IE 8？不支持 IE 8

**Comment by q1017269237** [comment]
> IE 8？不支持 IE 8

提供截图是IE 11 和 chrome 68
