### ISSUE TITLE
Think about simulating click event of legend

### ISSUE THREAD

**Issue by fangbinwei** [apache/incubator-echarts#9223]
### One-line summary [问题简述]
因为有需求要点击legend之后, 响应点击事件, 但是了解到legend并没用`click`事件, 在`selectedMode`为`true`的情况下#6266, 可以监听`legendselectchanged`事件来实现自定义的操作, 但是select操作本身有默认的隐藏图表的行为.

所以我在`legendselectchanged`事件中触发`legendSelect` action #1081, 在点击legend之后, 又重新将全部的legend选中, 但是这就相当于先隐藏图表, 又重新将图表显示, 这样hack了`click`事件, 但是副作用就是点击legend, 图表会有动画, 除非设置`animation: false`禁掉动画.
### Version & Environment [版本及环境]
+ ECharts version [4.1.0.rc2]:
+ Browser version [chrome69.0.3497.100]:
+ OS Version [macos]:

### Expected behaviour [期望结果]
想了解兼顾图表动画的同时, 又能实现legend`click`的思路#3564

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        x: 'left',
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series: [
        {
            name:'访问来源',
            type:'pie',
            radius: ['50%', '70%'],
            avoidLabelOverlap: false,
            //hoverAnimation: false,
            //animation: false,
            label: {
                normal: {
                    show: true,
                    position: 'center',
                    textStyle: {
                        fontSize: '30',
                        fontWeight: 'bold'
                    },
                    formatter: 'center text',
                    color: '#000'
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
}

```

#### 附上demo
[jsfiddle地址](https://jsfiddle.net/fangbinwei/uye7vpt9/)

**Comment by Ovilia** [comment]
你想要的效果是怎样的，点击 legend 之后不隐藏系列，而是处理自己的逻辑？

**Comment by fangbinwei** [comment]
@Ovilia 嗯嗯, 想要的效果是点击legend后不隐藏系列, 处理自己的逻辑. 但是现有的api似乎无法做到, 我给出demo里的实现方法, 点击legend后, 会有不必要的动画, 使用`animation: false`又一下子禁了全部的动画.

**Comment by Ovilia** [comment]
点击 legend 不隐藏应该用 http://echarts.baidu.com/option.html#legend.selectedMode 设为 false

**Comment by fangbinwei** [comment]
@Ovilia 设为false之后, legend直接无法点击了, 这样似乎没办法处理自己的逻辑

**Comment by Ovilia** [comment]
目前没有更好的解决方案。
