### ISSUE TITLE
百度地图扩展组件，无法同步移动

### ISSUE THREAD

**Issue by wlfei0502** [apache/incubator-echarts#9224]
### One-line summary [问题简述]
示例中的“全国空气质量”，当地图拖动的时候，echarts图表无法保持同步移动，需要等待地图移动完毕才去移动

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2.0
+ Browser version [浏览器类型和版本]:chrome 63.0.3239.84
+ OS Version [操作系统类型和版本]:windows10

### Expected behaviour [期望结果]
希望echarts 图表能像地图上的marker一样随地图同步移动

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]
当前效果：全国空气质量（http://echarts.baidu.com/examples/editor.html?c=effectScatter-bmap)
期望效果：全国空气质量  (https://lzxue.github.io/echartsLayer/demo/effectScatter-map.html)

**Comment by andywwu** [comment]
你好，请问这个问题是怎么解决的？

**Comment by woleicom** [comment]
> 你好，请问这个问题是怎么解决的？
option：关闭动画
animation:false,

**Comment by woleicom** [comment]
@andywwu 
option参数关闭动画
animation:false,
