### ISSUE TITLE
GL 矢量场图报Cannot read property 'dimensions' of null

### ISSUE THREAD

**Issue by taohewu** [apache/incubator-echarts#9226]
使用的是http://www.echartsjs.com/examples/editor.html?c=global-wind-visualization-2&gl=1的示例代码，我这边本地代码如下

<script src="js/jquery.min.js"></script>
<script src="js/echarts.min.js"></script>
<script src="js/echarts-gl.min.js"></script>

<div id="main" style="width: 1000px;height:800px;"></div>
<script type="text/javascript">
// 基于准备好的dom，初始化echarts实例
var myChart = echarts.init(document.getElementById('main'));

但在浏览器中访问，报Cannot read property 'dimensions' of null错误，图像无法显示，请问是哪里遗漏了吗？

**Comment by taohewu** [comment]
已解决，找了别人的例子，原来是未引入地图js，这个官网文档也没个说明啊

**Comment by shinham** [comment]
import '../../node_modules/echarts/map/js/world.js' 

if anyone else encountered the same issue, add this import will do
