### ISSUE TITLE
折线图刷新后不一定能显示

### ISSUE THREAD

**Issue by mhxy13867806343** [apache/incubator-echarts#9229]
###One-line summary [问题简述]
使用的技术是纯html+jquery编写的图形方式，加载页面后，echarts生成的折线图，会显示不出来，通过如下代码
series:[
            {
                name:'',
                type:'line',
                data:[120, 132, 5101, 3134, 90, 2230, 1210,4000,8000,1000,18000,24000]

            },
            {
                name:'',
                type:'line',
                stack: '总量',
                normal: {
                    show: true,
                    position: 'top'
                },
                data:[220, 182, 4191, 22234, 12290, 3130, 2310]
            }
        ]

生成数据

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2.1
+ Browser version [浏览器类型和版本]:Google Chrome 已是最新版本版本 69.0.3497.100（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: Windows 7 旗舰版 版本 6.1 （内部版本 7601：Service Pack 1）

### Expected behaviour [期望结果]
当页面加载后，能够显示在页面上，并且刷新后依然还在

### ECharts option [ECharts配置项]

```javascript

我编写的代码
function line(){
    var line=document.getElementById('echartContainer');
    var lines=echarts.init(line);
    var arrListMouth=[]
    for(var i=1;i<13;i++){
        arrListMouth.push(`${i}月`)
    }
    lines.setOption({
        title:{
            text:'2018年线路销售量折线统计图',
            x:'center',
            textStyle: {
                fontSize:24,
                color:'#6e6e6e'
            }
        },
        tooltip: {
            trigger: 'axis',
            axisPointer:{
                type:'cross',
                label: {
                    backgroundColor:"#6a7985",
                    formatter: function (params) {
                        return `${params.value}的销售量为${params.seriesData.length? '：' + params.seriesData[0].data : ''} ;`
                    }
                }
            }
        },
        legend:{
            data: [],
            y:'bottom'
        },
        markPoint:{
            data: [
                { type: 'max', name: '最大值' },
                { type: 'min', name: '最小值' }
            ]
        },
        toolbox:{
            feature: {
                saveAsImage: { show: true }, //导出图片
                dataView: { show: true }, //数据视图
                magicType: { //动态类型切换
                    type: [ 'line', 'bar' ]
                },
                dataZoom: { show: true }, //数据区域缩放
                restore: { show: true }, //重置
            }
        },
        grid:{
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        calculable: true,
        xAxis:[
            {
                type:'category',
                boundaryGap:false,
                data:arrListMouth,
            }
        ],
        yAxis:[
            {
                type:'value',
                name:''
            }
        ],
        series:[
            {
                name:'',
                type:'line',
                data:[120, 132, 5101, 3134, 90, 2230, 1210,4000,8000,1000,18000,24000]

            },
            {
                name:'',
                type:'line',
                stack: '总量',
                normal: {
                    show: true,
                    position: 'top'
                },
                data:[220, 182, 4191, 22234, 12290, 3130, 2310]
            }
        ]
    })
}
```

### Other comments [其他信息]

正常显示的
![1234](https://user-images.githubusercontent.com/4418166/46931179-aeae9800-d07c-11e8-8357-a28b1e3e1157.png)

非正常显示(红色部分标记)

![2345](https://user-images.githubusercontent.com/4418166/46931238-e584ae00-d07c-11e8-83b4-077eb931f29a.png)

**Comment by cuijian-dexter** [comment]
@mhxy13867806343 Other charts can show processing, and it should not be related to echart. See if your DOM exists.

**Comment by deqingli** [comment]
您好，我在我们 echarts 的 在线作品社区 http://gallery.echartsjs.com/editor.html 上试过您的配置项并连续刷新了，没有什么问题。可以排除您代码中 echarts 配置项的错误。
