### ISSUE TITLE
如何将折线图的拐点按照不同的角度旋转

### ISSUE THREAD

**Issue by zhouzebin** [apache/incubator-echarts#9230]
### One-line summary [问题简述]
echarts能否做风力风向统计图，就是如何将折线图的拐点按照不同的角度旋转

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2
+ Browser version [浏览器类型和版本]:chrome/
+ OS Version [操作系统类型和版本]:Windows10

### Expected behaviour [期望结果]

可以有类似的解决方案完成需求

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by deqingli** [comment]
您好，echarts 官网上有个天气的示例 http://echarts.baidu.com/examples/editor.html?c=wind-barb，跟您说的需求类似，您可以参考下

**Comment by zhouzebin** [comment]
感谢大神，但是不理解，为啥我在官网上找不到你说的这个呢。
