### ISSUE TITLE
Treemap第二个例子ECharts 配置项查询分布有个展示bug

### ISSUE THREAD

**Issue by xhrjdzw** [apache/incubator-echarts#9231]
### One-line summary [问题简述]

父节点的数据会展示在子节点的数据中,影响展示效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

谷歌浏览器

### Expected behaviour [期望结果]
子节点展示不应该计算父节点的$count

### ECharts option [ECharts配置项]

```javascript
option = {
//28行处理是错误的 应该删除这个else判断
target.children.push({
                        name: basePath,
                        value: source.$count
                    });

```

**Comment by deqingli** [comment]
您好，谢谢您的反馈，这里的 source 不是指父节点，这里的 source 是 convert(source, target, basePath) 函数里的目标原数据，而 target 是指处理后的数据。 我调试了 convert 数据处理的过程，没有什么问题，产出的数据也是对的。不过，例子中 xAxis.axisLabel 这一矩形块展示的 label 数据的确有问题，我会继续跟进。Anyway，再次感谢您的反馈。
