### ISSUE TITLE
echarts只能通过setOption更新数据

### ISSUE THREAD

**Issue by liucrui** [apache/incubator-echarts#9234]
### One-line summary [问题简述]
改变data中的数据后，想刷新图表，只能通过setOption来重绘，我的树形图手动展开的节点，又恢复了初始化展开的节点

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1
+ Browser version [浏览器类型和版本]:Google Chrome
+ OS Version [操作系统类型和版本]:win10专业版

### Expected behaviour [期望结果]
能不能不通过setOption方法进行图表重绘，只局部刷新data中的数据亦或者有没有其他好的方法

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by cuijian-dexter** [comment]
@liucrui do you have a example ? 
`setOption` has parameters `notMerge` . parameter `lazyUpdate` and parameter `silent`.

**Comment by deqingli** [comment]
@liucrui  您好，谢谢您的反馈。现在 setOption() 后，还没办法 merge 每个节点的操作行为，后续我们会考虑支持这块的功能。
