### ISSUE TITLE
多条折线的图，如何让坐标轴跟随曲线同步显示和隐藏

### ISSUE THREAD

**Issue by zhyt0520** [apache/incubator-echarts#9236]
### One-line summary [问题简述]
折线图，多条数据，多个坐标轴，鼠标点击图例时，对应的曲线可以显示/隐藏，如何实现在点击图例时让对应的坐标轴也同步的显示/隐藏？

**Comment by deqingli** [comment]
您好，麻烦提供更详细的信息，目前的效果图以及 echarts option 的完整配置。

**Comment by deqingli** [comment]
您好，由于这个 issue 您一周没回复，为了方便管理 issue, 我会先 close 这个 issue，如果后续您还有什么问题，可以 reopen 这个 issue，记得提供详细的信息。望理解，谢谢！

**Comment by zhyt0520** [comment]
抱歉，问题描述的过于简单

示例配置
<pre>option = {
    legend: {
        data:['一','二'],
        selectedMode:true
    },
    xAxis: {
        type: 'category',
        data: [1,2,3,4,5,6,7]
    },
    yAxis: [{
        type: 'value',
        id:'one',
        position:'left'
    },{
        type:'value',
        id:'two',
        position:'left',
        offset:50
    }],
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        yAxisId:'one',
        name:'一'
    },{
        data: [123, 456, 654, 789, 582, 321, 523],
        type: 'line',
        yAxisId:'two',
        name:'二'
    }]
};</pre>

效果图一
![snipaste_20181024_100745](https://user-images.githubusercontent.com/10279099/47401631-b7862480-d774-11e8-97f6-0a5ebb3367a3.png)
`legend`的selectedMode为默认true的时候，点击图例，可以让对应的曲线隐藏、显示
效果图二
![snipaste_20181024_100802](https://user-images.githubusercontent.com/10279099/47401628-b7862480-d774-11e8-8b38-624406e7efe7.png)
点击图例的【二】后，【二】这条曲线隐藏

**希望达到的效果**

**我希望点击图例的【二】后，曲线【二】和其对应的y轴（id:'two'）同时隐藏，然后再次点击图例的时候二者再同时显示**

查过配置手册，没找到现成的设置选项，不清楚目前是否支持我上述期望
如果目前不支持直接设置中达到上述效果，希望大佬指点如何手动实现的上述效果的方向

**Comment by zhyt0520** [comment]
@deqingli 我 reopen 不了这个 issue 啊，不确定你是否能看到我的回复，在这@一下，麻烦帮我 reopen 吧
