### ISSUE TITLE
Stacked bars positioned out of the grid when datazoom toolbox feature is used

### ISSUE THREAD

**Issue by hamidhasnain** [apache/incubator-echarts#9237]
https://jsfiddle.net/hmdhs/96cox2nz/

Echarts version: 4.2.0

Stacked bar graph when used with datazoom toolbox feature goes out of the grid. Without datazoom graph behaves as expected.

**Comment by deqingli** [comment]
Thank for your feedback.

**Comment by Ovilia** [comment]
Duplicate of #8935 .
