### ISSUE TITLE
add tooltipShow event

### ISSUE THREAD

**Issue by dashixiong1990** [apache/incubator-echarts#9240]
### 问题简述

建议添加 tooltipShow 事件，折线图经常碰到tooltip展示后，与外部UI产生联动的效果。

现在只能使用mousemove事件来实现，缺点是只有move到symbol上时才能进行触发，触发范围过小

**Comment by deqingli** [comment]
您好，如果方便的话，建议您提供联动的效果图，以及 echarts 的 option 配置。

**Comment by dashixiong1990** [comment]
效果图如下，当用户鼠标在图表中move或hover到某一横坐标点，出现tooltip的时候，右边表格根据hover的日期，来进行进一步的数据展示  

![效果图](https://p5.ssl.qhimg.com/t01f59686c6cf6f17fb.png)

昨天搜到的一些之前提到的关于这个想法的issue, 提到一些解决方案，都不是很优雅
[4375](https://github.com/apache/incubator-echarts/issues/4375)
[5297](https://github.com/apache/incubator-echarts/issues/5297)

**Comment by Ovilia** [comment]
We are working on this problem. Please follow #9281.
