### ISSUE TITLE
当数据达到一定数量时，会多出一条连接起点和终点的线

### ISSUE THREAD

**Issue by yezhihao17** [apache/incubator-echarts#9241]
### One-line summary [问题简述]
在vue项目中直接引入echarts.js文件，选择折线图模式，数据结构为:
data: [
{name: 'xxx', value: [ 'aaa', 'bbb' ] }
  ...
]
并且数据量达到一定时，会多出一条连接起点和终点的线。

### Version & Environment [版本及环境]
+ ECharts version 4.2.0:
+ Browser version chrome 69.0.3497.100:
+ OS Version win10:

### Expected behaviour [期望结果]

消除多余的线条。

### ECharts option [ECharts配置项]

```javascript
option = {
        title: {
            text: '动态数据 + 时间坐标轴'
        },
        xAxis: {
            type: 'time',
            splitLine: {
                show: false
            }
        },
        yAxis: {
            type: 'value',
            splitLine: {
                show: false
            },
            scale: true
        },
        series: {
            name: '模拟数据',
            type: 'line',
            showSymbol: false,
            hoverAnimation: false,
            data: newData.contractPrice,
        }
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/22880743/47013978-7cd02b00-d17b-11e8-9442-8a6908044497.png)

**Comment by deqingli** [comment]
您好，请问这是完整的 echarts option 配置么，有配置  markLine 之类的么

**Comment by yezhihao17** [comment]
感谢你的回复！
上面的配置是完整的options，问题已经找到，造成这样的原因是因为我的data数据的value第一个维度是时间戳，而这个时间戳并不是正常的时间戳，时间戳会在达到一定长度后循环，比如：15:00到18:00，然后又从15:00到18:00这样的一个结果。 这样就会造成渲染出来的折线图多了一条直线。不知道这个机制是不是框架设计成这样的还是存在的一个问题。
