### ISSUE TITLE
showTip 怎么持续显示

### ISSUE THREAD

**Issue by zwmmm** [apache/incubator-echarts#9242]
### One-line summary [问题简述]
折线图上想默认显示一个tip
通过使用dispatchAction 的 showTip 事件可以达到初始时默认显示一个tip 但是一旦鼠标悬浮其他的数据 最终将不会再有默认显示的tip

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: window 7

### Expected behaviour [期望结果]

持续显示一个tip 并且在鼠标悬浮离开之后还生效

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by deqingli** [comment]
您好，可以添加 markPoint，参考官网的这个示例 http://echarts.baidu.com/examples/editor.html?c=bar-rich-text

**Comment by zwmmm** [comment]
@deqingli  markPoint是需要自己设置样式么 我想要这种效果
![image](https://user-images.githubusercontent.com/30194521/47130532-aa78b980-d2cc-11e8-9e46-b89dc73f2ae0.png)

**Comment by zwmmm** [comment]
已解决 直接给canvas注册一个鼠标离开事件，离开时的时候触发showTip
```js
this.$refs.canvas.onmouseout = this.showTip;
```

**Comment by iamweilee** [comment]
不是有个配置项可以用嘛  alwaysShowContent：true

**Comment by zwmmm** [comment]
@iamweilee 非常感谢
