### ISSUE TITLE
effectScatter和lines如何结合使用？

### ISSUE THREAD

**Issue by flyiiiiii** [apache/incubator-echarts#9243]
### One-line summary [问题简述]
希望effectScatter点能沿着 特定的线运动，即与lines结合。

与版本无关
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

effectScatter与lines结合

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
那只能不断 setOption 改 effectScatter 坐标
