### ISSUE TITLE
Problems with Echart Radar

### ISSUE THREAD

**Issue by TomasDSD** [apache/incubator-echarts#9251]
Hello everyone, 

I'm using Echarts Demo in order to produce a specific Radar Chart (with a json code), but i have several problems :

- I want to add the "%" to all numbers (but not add the "%" in each values, maybe using "formatter")
- I want to define the width and heigth of all text, avoiding the text leaves the screen
- I want to define for all number for not showing decimals (I already use parseInt(), but i need a global configuration)

Sorry, i'm not developper :)

Can you help me please ? Thanks you !

I use this link : https://ecomfe.github.io/echarts-examples/public/editor.html?c=radar, and i copy past the following code : 

`option = {
    "tooltip": {},
    "legend": {
        "top": 0,
        "center": 0,
        "data": [
            "Initial",
            "Final"
        ]
    },
    "radar": {
        "indicator": [
            {
                "max": 100,
                "chapitre": "1",
                "color": "#548235",
                "niveau": "1",
                "text": "text1text1text1text1text1text1text1text1"
            },
            {
                "max": 100,
                "chapitre": "2",
                "color": "#00b067",
                "niveau": "2",
                "text": "text2text2text2text2text2text2text2text2"
            },
            {
                "max": 100,
                "chapitre": "3",
                "color": "#9fbf65",
                "niveau": "3",
                "text": "text3"
            },
            {
                "max": 100,
                "chapitre": "4",
                "color": "#0076d7",
                "niveau": "4",
                "text": "text4"
            },
            {
                "max": 100,
                "chapitre": "5",
                "color": "#eb5740",
                "niveau": "5",
                "text": "text5text5text5text5text5text5text5text5"
            },
            {
                "max": 100,
                "chapitre": "6",
                "color": "#cb0000",
                "niveau": "6",
                "text": "text6text6text6text6text6"
            }
        ]
    },
    "series": [
        {
            "type": "radar",
            "data": [
                {
                    "name": "Initial",
                    "value": [
                       "0.00",
                       "50.83",
                       "54.31",
                       "60.83",
                       "57.33",
                       "43.33"
                    ],
                    "label": {
                        "normal": {
                            "show": true
                        }
                    },
                    "areaStyle": {
                        "normal": {
                        "opacity": 0.3,
                         
                        }
                    },
                     "lineStyle": {
                      "normal": {
                         "type": "dashed"
                        }
                    }
                },
                {
                    "name": "Final",
                    "symbol": "rect",
                    "symbolSize": 3,
                    "value": [
                        "0.00",
                        "53.75",
                        "58.89",
                        "54.00",
                        "60.00",
                        "65.00"
                    ],
                    
                    "label": {
                        "normal": {
                            "show": true,
                        }
                    },
                    "areaStyle": null
                    
                }
                
            ]
        }
    ]
};`

**Comment by sxmpasch** [comment]
As you mentioned, you can use formatter in the label:
- adding just a "%" would be easy:  "formatter": '{c}%'
- if you want to limit the number of decimals, you have to use a callback:
```
"formatter": function (params, ticket, callback) {
        return parseInt(params.value).toFixed(2)+' %';
    }

```

**Comment by sxmpasch** [comment]
Sorry, I haven't read your request properly: You set the desired number of decimals with "toFixed()". In your case this would be toFixed(0) since you do not want any decimals...

Regarding the indicators: You just add a "\n" in the text to get a multi-line label. This will help as first step...

**Comment by TomasDSD** [comment]
Thanks for response.

I cannot use the \N, because i will received automaticaly all text.

It's for this i need a global configuration avoiding the text leaves the screen.

Maybe i need to insert a thing in this part : 

![capture](https://user-images.githubusercontent.com/39341148/47148704-b155fb00-d2d1-11e8-8bac-967da5fbb299.PNG)

**Comment by TomasDSD** [comment]
For decimals, it works thanks :)

The last problem is "I want to define the width and heigth of all text, avoiding the text leaves the screen"

**Comment by sxmpasch** [comment]
you could use one of the typical word wrapping algorithms by yourself. For this, you could add one  of these specific javascript libraries - or if this is too complicated - define a simple algorithm on your own:
Add this code to the radar.name { } area (w is the desired with in letters):
`
        formatter: function (value, indicator) {
            w=30;
            t=value.split(' ');
			l=0;
			o='';
            for (var tw of t) {
				if (l+tw.length >= w) {
					o += (l?'\n':'')+tw+' ';
					l=tw.length+1;
				} else {
				  o += tw+' '
				  l += tw.length+1;
				}
            }
            return o;
        }
`

**Comment by TomasDSD** [comment]
Thanks @sxmpasch,

I have an error ;

![sans titre](https://user-images.githubusercontent.com/39341148/47152685-ac974400-d2dd-11e8-8fb9-80f8946045ed.png)

**Comment by TomasDSD** [comment]
It WORK ! BIG THANKS @sxmpasch

**Comment by Nabeelhassan** [comment]
hey @TomasDSD could you help me on this one? i am stuck on the same issue.
