### ISSUE TITLE
echarts 4.0 树缩放 后收拢根节点会玩失踪

### ISSUE THREAD

**Issue by 020cui** [apache/incubator-echarts#9256]
### One-line summary [问题简述]
前置条件：
1，当树的配置 启用了内部缩放，与拖动
2，视图中拖动过树，（或做过缩放动作）

对根节点进行收缩处理，根节点会向树根反方向飘移一个较大的距离，
根节点在边缘的话，就会看不见树，（树跨界了）且没办法找到树，

临时解决办法：只能重置或刷新页面

### Version & Environment [版本及环境]
+ ECharts version [4.0]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]
myChart.showLoading();
$.get('data/asset/data/flare.json', function (data) {
    myChart.hideLoading();

    myChart.setOption(option = {
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series:[
            {
                type: 'tree',

                data: [data],

                left: '2%',
                right: '2%',
                top: '8%',
                bottom: '20%',

                symbol: 'emptyCircle',

                orient: 'vertical',

                expandAndCollapse: true,
                roam: true,
                label: {
                    normal: {
                        position: 'top',
                        rotate: -90,
                        verticalAlign: 'middle',
                        align: 'right',
                        fontSize: 9
                    }
                },

                leaves: {
                    label: {
                        normal: {
                            position: 'bottom',
                            rotate: -90,
                            verticalAlign: 'middle',
                            align: 'left'
                        }
                    }
                },

                animationDurationUpdate: 750
            }
        ]
    });
});

```javascript
option = {

}

```

### Other comments [其他信息]
http://www.echartsjs.com/gallery/editor.html?c=tree-vertical

![image](https://user-images.githubusercontent.com/26127578/47195075-d6f40a80-d38c-11e8-9135-1acbc32757f2.png)

**Comment by side9527** [comment]
我之前也遇到这个问题，后来的解决方法是，点击节点的时候根据chartChild._chartsViews[0]._data._graphicEls.length 来判断点击的节点是否为根节点（length < 3即为根节点），如果是根节点就使用chartChild.setOption(chartChild.getOption())重新产开，也算是不让他收起根节点吧，别的方法找了很多没找到，就先暂时用的这个

**Comment by mm007008009** [comment]
补充一下：
1.开启roam属性后，才会有这个问题，必现；如果不开启roam属性，概现。
2.横竖树图都有这个问题，是往展开方向的反方向，进行位移。

**Comment by lurenj** [comment]
问一下，现在这个问题解决了吗？

**Comment by dingww** [comment]
找到解决办法了！

给树图的Echarts组件加一个点击事件，当event.dataIndex === 1时，初始化一个Echarts实例 myCharts，然后将myChart._chartsViews[0].group.position 重置为 [0, 0]就可以了。

亲测有效。

**Comment by deqingli** [comment]
#10291

**Comment by yuxiaoxia** [comment]
怎么解决？关系图也有这样的问题

**Comment by wangmeijian** [comment]
配置setOption的第二个参数设置为true即可，意思是重新绘制

**Comment by yangNice94** [comment]
请问有人解决这个问题了吗？

**Comment by cengcengceng** [comment]
getOption后设置center为null，setOption即可。
