### ISSUE TITLE
动画循环播放的设置问题

### ISSUE THREAD

**Issue by BugDaShu** [apache/incubator-echarts#9259]
我在设置动画的时候依次设置了延迟的时间    effect.delay: 2000 * i, 这样动画可以形成一个依次播放的效果，可是如果我希望整个动画效果循环播放，那么设置loop:true,则会出现后面的动画还未开始，而第一个动画已经重复播放，所以希望可以增加一个属性就是动画循环播放的间隔时间。

**Comment by deqingli** [comment]
您好，麻烦按照 issue 的模版提供详细的信息，包括整个 option 的配置等。
