### ISSUE TITLE
自定义的工具的icon如果类似"image://http://echarts.baidu.com/images/favicon.png"，此时不能导出图表

### ISSUE THREAD

**Issue by ohohyea** [apache/incubator-echarts#9260]
### One-line summary [问题简述]

自定义的工具的icon如果类似"image://http://echarts.baidu.com/images/favicon.png"，此时不能导出图表，按钮saveAsImage和mychart.getDataURL()报错，浏览器控制台异常：Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be

如果为相对路径"image:///images/favicon.png"，则没有问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:Chrome，IE11
+ OS Version [操作系统类型和版本]:windows10

### ECharts option [ECharts配置项]

```javascript
var option ={
  toolbox: {
    feature: {myTool1: {
      icon: "image://http://echarts.baidu.com/images/favicon.png",
//      icon: 'path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444z M421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876z M421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062,591.891,421.146,591.891L421.146,591.891zM421.146,591.891',
    },
    saveAsImage:{}
  }}
};

```

**Comment by lijiliang1** [comment]
将图片放到本地静态文件里面，直接引用
feature: {
            saveAsImage: {
              title: 'download',
              icon: 'image:///images/svg/download.svg'
            },
          }
