### ISSUE TITLE
tooltip的触发方式改为click后，频繁快速点击一个点，弹框会消失

### ISSUE THREAD

**Issue by justJokee** [apache/incubator-echarts#9261]
### One-line summary [问题简述]
当echarts与百度地图结合时，运用了effectScatter系列在地图上标注了一些点，当点击点时弹出tootip，但是tooltip的触发方式改为click后，频繁快速点击一个点，弹框会消失。
[官方实例](http://www.echartsjs.com/examples/editor.html?c=map-polygon)，添加triggerOn:true,可以直接复现问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:^4.1.0
+ Browser version [浏览器类型和版本]:Chrome
+ OS Version [操作系统类型和版本]:windows8

### Expected behaviour [期望结果]

频繁快速点击一个点，tooltip不会消失

### ECharts option [ECharts配置项]

```javascript
option = {
 tooltip : {
            trigger: 'item',
            triggerOn: 'click',
            enterable:  false,
            position:"top",
            alwaysShowContent: false,
}
}

```

**Comment by justJokee** [comment]
chrome版本 68.0.3440.84

**Comment by Ovilia** [comment]
似乎是因为双击操作会在百度地图上触发放大地图的操作，没有明显感觉到这是个 bug
