### ISSUE TITLE
Sum of stacks of Stacked bar chart

### ISSUE THREAD

**Issue by shrenik007** [apache/incubator-echarts#9264]
I have a stacked bar chart where I am showing data labels in the middle of each stack but I want to show sum of all the stack on the top of the last stack.

Is there any way in echarts where I can do this?

![chart](https://user-images.githubusercontent.com/16061768/47281150-410fe800-d5f7-11e8-9c0b-483a7106a990.png)

**Comment by sxmpasch** [comment]
Just either change the label on the topmost stacked series, or add another series. Label change: Something like this:
```
            label: {
                normal: {
                    show: true,
                    position: 'top',
                    formatter: function(params) {
                        let val=0;
                        this.option.series.forEach(s => { 
                            val+=s.data[params.dataIndex];
                        } );
                        return val;
                    }
                }
            },

```

**Comment by sxmpasch** [comment]
Either change your topmost label or add another series with 0-values on top with something like the following label formatter:
```
            label: {
                normal: {
                    show: true,
                    position: 'top',
                    formatter: function(params) {
                        let val=0;
                        this.option.series.forEach(s => { 
                            val+=s.data[params.dataIndex];
                        } );
                        return val;
                    }
                }
            },

```

**Comment by deqingli** [comment]
hi @shrenik007,  It seems that your problem is solved by @sxmpasch, so I will close this issue, if you have any problem, you can reopen it.

**Comment by geetha-mindtree** [comment]
it's not working for me. can u pls help me on this

**Comment by hughess** [comment]
I got this working, but noticed that when you deselect a series from the legend, the total labels do not recompute, so the totals become inaccurate.

Is there any way to have it updated based on only the visible series in the chart?
