### ISSUE TITLE
Custom loader

### ISSUE THREAD

**Issue by cheezyXx** [apache/incubator-echarts#9270]
### One-line summary
I would like to add custom loader to echarts, because I want to use loader in another part of my application and the styles/look should be the same.

### Version & Environment
+ ECharts version:  4.1.0
+ Browser version: chrome 70
+ OS Version: Windows 10 Pro

### Expected behaviour
Define custom styles of loader and put them into echarts.

**Comment by Ovilia** [comment]
Hi, what do you mean by a loader, and what is it used for?

**Comment by 100pah** [comment]
Make a loader by dom and cover it on the echarts container, does it meet the requirement?

**Comment by cheezyXx** [comment]
It is possible (I think), but it's not the solution. It would be fine to use this - https://echarts.apache.org/api.html#echartsInstance.showLoading. I think it would be fine improvement in this package.

**Comment by Ovilia** [comment]
Loading styles may differ greatly for varied requirements. So I guess this has to be done by DOM, or do you have other suggestions on how we could provide this style setting in a more general way?

**Comment by demoprazol** [comment]
Hi, at least we should use .gif for the loading animation, for example, I want to use the loading dots instead of the loading cycle, I have a loading dots animated gif file, it could be perfect if I can directly use it.
