### ISSUE TITLE
饼图环形图里面的提示标题如果名字重复的话只显示一个名字

### ISSUE THREAD

**Issue by zhjibi742626083** [apache/incubator-echarts#9271]
### One-line summary [问题简述]

饼图环形图里面的提示标题如果名字重复的话只显示一个名字

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0
+ Browser version [浏览器类型和版本]:chremo 70
+ OS Version [操作系统类型和版本]:win 10

### Expected behaviour [期望结果]
根据传入的参数值，是什么就显示什么，而不是如果series里面的data里面的对象如果name值相同的话就显示一个

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        x: 'left',
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series: [
        {
            name:'访问来源',
            type:'pie',
            radius: ['50%', '70%'],
            avoidLabelOverlap: false,
            label: {
                normal: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    show: true,
                    textStyle: {
                        fontSize: '30',
                        fontWeight: 'bold'
                    }
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'直接访问'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
}

```

### Other comments [其他信息]

![69cbe8a0-f5b8-438a-852c-43471613fc17](https://user-images.githubusercontent.com/29059279/47426571-2472dc00-d7c0-11e8-9b2d-aedc1b2abff0.png)
![77a44e2a-b0b4-43d7-a646-a57fe974805c](https://user-images.githubusercontent.com/29059279/47426694-85021900-d7c0-11e8-8033-1f6d4f39b620.png)

**Comment by sxmpasch** [comment]
There is a direct reference between legend data and series data item. You cannot use the same name in the legend data. 
If the names have to be the same, just add a ' ' after one of them.

图例数据和序列数据项之间有直接参考。您不能在图例数据中使用相同的名称。
如果名称必须相同，只需在其中一个之后添加一个' '。

**Comment by sxmpasch** [comment]
Example:
```
option = {
tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        x: 'left',
        data:['直接访问','直接访问 ','联盟广告','视频广告','搜索引擎']
    },
    series: [
        {
            name:'访问来源',
            type:'pie',
            radius: ['50%', '70%'],
            avoidLabelOverlap: false,
            label: {
                normal: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    show: true,
                    textStyle: {
                        fontSize: '30',
                        fontWeight: 'bold'
                    }
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'直接访问 '},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
}

```

**Comment by Ovilia** [comment]
为什么会有同名的需求？

**Comment by zhjibi742626083** [comment]
> 例：
> 
> ```
> option = {
> tooltip: {
>         trigger: 'item',
>         formatter: "{a} <br/>{b}: {c} ({d}%)"
>     },
>     legend: {
>         orient: 'vertical',
>         x: 'left',
>         data:['直接访问','直接访问 ','联盟广告','视频广告','搜索引擎']
>     },
>     series: [
>         {
>             name:'访问来源',
>             type:'pie',
>             radius: ['50%', '70%'],
>             avoidLabelOverlap: false,
>             label: {
>                 normal: {
>                     show: false,
>                     position: 'center'
>                 },
>                 emphasis: {
>                     show: true,
>                     textStyle: {
>                         fontSize: '30',
>                         fontWeight: 'bold'
>                     }
>                 }
>             },
>             labelLine: {
>                 normal: {
>                     show: false
>                 }
>             },
>             data:[
>                 {value:335, name:'直接访问'},
>                 {value:310, name:'直接访问 '},
>                 {value:234, name:'联盟广告'},
>                 {value:135, name:'视频广告'},
>                 {value:1548, name:'搜索引擎'}
>             ]
>         }
>     ]
> }
> ```

非常感谢，已经解决。

**Comment by zhjibi742626083** [comment]
> 为什么会有同名的需求？

因为名字是用户用命令写的，需要展示。

**Comment by Lanchouchou** [comment]
如果重复的比较多呢 怎么处理？ 希望都展示

**Comment by jinbiao-bianjie** [comment]
> 如果重复的比较多呢怎么处理？ 希望都展示

I think you can set up a mapping and show through the mapping relationship。
我觉得可以建立一个映射，通过映射关系来展示

**Comment by a3246995** [comment]
我解决了就一行代码,我来分享下往上都是啥分组啥的, 遍历给name加上空格制造差异性: 
processedArray = arry.map((item, index) => {
      return {
        name: `${item.deviceName}${index > 0 ? Array(index + 1).join(" ") : ""}`,
    })
}

**Comment by shenxiang216** [comment]
processedArray = arry.map((item, index) => {
return {
name: ${item.deviceName}${index > 0 ? Array(index + 1).join(" ") : ""},
})
}加的空格很多时，不会导致展示样式有问题吗

**Comment by shenxiang216** [comment]
> 为什么会有同名的需求？

![image](https://github.com/apache/echarts/assets/57433548/c71d2e23-2687-4364-a385-11d48bd40d3b)
展示类似这样的图表
