### ISSUE TITLE
饼图能否只让selectedOffset变色

### ISSUE THREAD

**Issue by Justin-Shen** [apache/incubator-echarts#9272]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/7840139/47435117-7aeb1500-d7d6-11e8-8992-28becbccb70e.png)

饼图能否实现像这种效果，hover时外圈的颜色跟圆的颜色有差异，用border好像又不是，不能只控制外圈？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by cuijian-dexter** [comment]
@Justin-Shen  Not for the time being. I have temporarily added functions by adding series.
http://gallery.echartsjs.com/editor.html?c=xZ9ppRyjWM&v=1，Do you see what you want?

**Comment by Justin-Shen** [comment]
> @Justin-Shen Not for the time being. I have temporarily added functions by adding series.
> http://gallery.echartsjs.com/editor.html?c=xZ9ppRyjWM&v=1
> Do you see what you want?

thanks a ton!!!!
