### ISSUE TITLE
Echarts主题的颜色搭配是否使用了某种算法

### ISSUE THREAD

**Issue by fbambi** [apache/incubator-echarts#9276]
### One-line summary [问题简述]

我对几个主题的颜色搭配在RGB和HSL上都进行了分析，结果是没什么规律。

那么，Echarts主题的颜色搭配是否应用了某种算法/规律，还是是完全依靠设计师手工搭配的？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
手工配的，除了纯粹美观上的考虑，还会考虑到色盲等情况所以不能用同样亮度的颜色等等。
