### ISSUE TITLE
Mouse events for the grid area of charts

### ISSUE THREAD

**Issue by lilililee** [apache/incubator-echarts#9281]
### One-line summary [问题简述]
![image](https://user-images.githubusercontent.com/24242242/47498602-4e93cf00-d890-11e8-8c4e-6aaa226555d0.png)

It is expected to trigger mousover events when mouse is at the red position, rather than on the data point.

It is mentioned in other issues that this can be fixed by using xAxis.triggerEvent, but it is only trigger when hover on axis label in my test.

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]:  chrome69
+ OS Version [操作系统类型和版本]: windows

### Expected behaviour [期望结果]

A solution is expected.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by cuijian-dexter** [comment]
Do you want to trigger in the blank area hover?

**Comment by YuhangGe** [comment]
@Ovilia 目前，在 chrome 下面，可以采取监听 echart 绑定的父亲 dom 元素的 mousedown/mouseup 事件，来实现一些跟这个 issue 相关的需求。但 ie/edge 下面，mousedown/mouseup 事件没有冒泡上去，被吃掉了，导致无能为力。希望可以解决这个 issue 的同时，关注下 ie/edge 下面的事件冒泡问题～

**Comment by Ovilia** [comment]
@YuanYifei I'll have a lot at it. Thanks.
Please use English to communication in issues since there are more and more non-Chinese speakers in the community after we became under Apache incubating.

**Comment by cuijian-dexter** [comment]
@YuhangGe  I build an example.Hope to help you.
http://gallery.echartsjs.com/editor.html?c=x513OMxUv6&v=1

**Comment by YuhangGe** [comment]
@cuijian-dexter yes, it works! thanks! 

By the way, I suggest adding this interface `getZr` and example to document.

**Comment by arslanhashmi** [comment]
@Ovilia is this feature available now?
