### ISSUE TITLE
roamController subsitute ?

### ISSUE THREAD

**Issue by burhandodhy** [apache/incubator-echarts#9291]
### One-line summary [问题简述]
roamController option is removed in new version. What are the orther subsitute of roamController ?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]: Google Chrome
+ OS Version [操作系统类型和版本]: Windows 10

### ECharts option [ECharts配置项]

```javascript
option = {
              roamController: {
                show: true,
                mapTypeControl: {
                  'world': true
                },
                x: 'right',
                y: 'bottom'
              },
}

```

**Comment by 100pah** [comment]
Sorry, currently no substitute. But I think it is necessary to support again.

**Comment by burhandodhy** [comment]
Hope you will add it soon.
