### ISSUE TITLE
echarts3.8.5 - y轴 - min 使用回调函数后，y轴刻度不显示

### ISSUE THREAD

**Issue by hepeifang** [apache/incubator-echarts#9300]
### One-line summary [问题简述]
yAxisDefault = {
          ...yAxisDefault,
          min: 'dataMin',
          max: 'dataMax'
        }
以上代码有效，y轴刻度最大最小值取数据最大最小值
yAxisDefault = {
          ...yAxisDefault,
          min: function (value) {
            return value.min - 100
          },
          max: function (value) {
            return value.max + 100
          }
        }
以上代码无效，y轴刻度不显示，且最小刻度还是取数据最小值（没有-100）(仅修改'dataMin'为function(){})

**Comment by 100pah** [comment]
新版本有这个问题么？

**Comment by Ovilia** [comment]
Could you please provide a full example at http://gallery.echartsjs.com/editor.html ?
