### ISSUE TITLE
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by meihangbo** [apache/incubator-echarts#9305]
#### 场景:
    主页通过load去加载子页面, 子页面是中国地图的图表.第一次加载很完美.
    然后再去点击页面上的加载地图链接,重新load地图页面, 等地图和数据加载完成, 去改变浏览器大小,触发resize后,浏览器就直接报错.而且一直在重复报错. 

    Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4.2.0.rc2
+ Browser version [浏览器类型和版本]: Chrome 70.0.3538.77（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]
解决 Chrome 下报的这个错,谢谢!

[代码](https://github.com/meihangbo/mhbDemo/tree/master/ecresize)

### ECharts option [ECharts配置项]

```javascript
option = {
配置项见下边例子
}

```

### Other comments [其他信息]

![error](https://user-images.githubusercontent.com/4393475/47713810-1fa5a080-dc76-11e8-85db-b34755e2ecd9.png)

[例子链接](https://meihangbo.github.io/mhbDemo/ecresize/index.html)

**Comment by SchnWalter** [comment]
I've checked the linked repository and the error doesn't seem to exist. Tested in:
* Google Chrome 70.0.3538.77
* Firefox Quantum, Mozilla v63.0.1 - Snap
* Opera v56.0.3051.99 - Snap

**Comment by Ovilia** [comment]
这个问题的本质原因是点击「加载地图」后没有销毁 resize 事件，调用到 `mapCharts.resize` 时，这个对象还是存在的，但是对应的 DOM 节点已经不存在了，所以宽高是 0。
ECharts 这边可以做个优化，在 `drawImage` 的时候判断下是不是有宽高，没有就不画。但本质原因是应该销毁对 window resize 事件的监听。

**Comment by meihangbo** [comment]
@Ovilia 谢谢您的回答,当前代码如何修改呢,谢谢!

**Comment by Ovilia** [comment]
你需要在点击加载地图的时候，先判断先当前是不是有 `setTimeout(function (){mapCharts.resize(); }, 500)` 这个返回的数字，有的话在加载图表前先 `clearTimeout` 一下。
