### ISSUE TITLE
官方示例 Binning on Map 后台获取数据的读取问题

### ISSUE THREAD

**Issue by MrZhangCF** [apache/incubator-echarts#9306]
[Binning on Map链接](http://echarts.baidu.com/examples/editor.html?c=map-bin)
官网上给的示例数据是一个2*3的数组，我从后台获取的数据也是这样，如下：
[[49,3,0],[48,4,2],[49,4,0],[50,4,0],[47,5,0],[48,5,2],[49,5,0],......,[50,5,0],[51,5,2],[46,6,2],[47,6,0]]

getSingleData(1)函数是我用axios获取数据的函数

数据渲染的方式如下：

~~~
export default {
  name: "Map",
  methods: {
    getData(){
      let data = []
      getSingleData(1).then(response => {
        if (response.data.code === 200) {
          data =  response.data.result
        }
      })
      return data
    },
    draw() {
      let echart= echarts.init(document.getElementById('bMap'))
      echart.setOption({
        tooltip: {
          // show : true
        },
        visualMap: {
          //省略。。。
        },
        series: [
          {
            type: 'custom',
            coordinateSystem: 'bmap',
            renderItem: renderItem,
            animation: false,
            itemStyle: {
              emphasis: {
                color: 'yellow'
              }
            },
            encode: {
              tooltip: 2
            },
            data: this.getData()
          }
        ],
        bmap: {
          //省略。。。
        }
  },
  mounted(){
    this.draw()
  }
}
~~~

结果就是网格部分没有被渲染出来，望解答，多谢

**Comment by mzy2240** [comment]
Do you include the renderItem function? I have tried this case as an example during the summer, and it runs ok for me.

**Comment by MrZhangCF** [comment]
@mzy2240 Hi mzy2240, yes i include the renderItem function.and my problem is that the `data:this.getData()`   doesn't work, the `getData()` function returns the data from the server by axios ，
here is the part of the data:
`[[49,3,0],[48,4,2],[49,4,0],[50,4,0],[47,5,0],[48,5,2],[49,5,0],......,[50,5,0],[51,5,2],[46,6,2],[47,6,0]]`

:(

**Comment by dreamkai** [comment]
能给我发一下vue 实现binning on Map 的例子吗
