### ISSUE TITLE
disable a serie by default

### ISSUE THREAD

**Issue by ramarro123** [apache/incubator-echarts#9308]
it's possible to disable a serie by default, as per having "delelect" it on legend?
legend should be disabled as well, making it possible to re-enable it if needed. i can't find an option for that

**Comment by sxmpasch** [comment]
1.
Yes, have a look at legend.selected option for disabling/enabling a single series.
E.g. take example https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-label-rotation
and fill in e.g.
```
    legend: {
        data: ['Forest', 'Steppe', 'Desert', 'Wetland'],
        selected:{'Forest':false, 'Steppe':true,'Desert':false},
    },

```

2.
Yes, this would be possible as well. To demonstrate, I take the example mentioned above.
Add a variable outside of option:
```
var showLegend=true;

```

Then you simply can add a custom button to the toolbox:
```
    toolbox: {
        show: true,
        orient: 'vertical',
        left: 'right',
        top: 'center',
        feature: {
            mark: {show: true},
            dataView: {show: true, readOnly: false},
            magicType: {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore: {show: true},
            saveAsImage: {show: true},
            myTool1: {
                show: true,
                title: 'show/hide legend',
                icon: 'path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444z M421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876z M421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062,591.891,421.146,591.891L421.146,591.891zM421.146,591.891',
                onclick: function (){
                    showLegend = (showLegend)?false:true;
                    myChart.setOption(
                        { legend: { show:showLegend }}
                    )
                }
            },
        }
    },


```

**Comment by 100pah** [comment]
Trigger legend related actions like <https://ecomfe.github.io/echarts-doc/public/en/api.html#action.legend.legendToggleSelect>

**Comment by iamweilee** [comment]
这样估计不能达到预期效果，因为设置了legend.selected并不会影响grid，可能作者需要grid也跟着隐藏和显示

**Comment by ramarro123** [comment]
@iamweilee  scusa ma non parlo cinese, puoi tradurmelo in italiano?

**Comment by ramarro123** [comment]
anyway, the first method work for me, and i see it's also on the doc, so shame on me :)

tnx for pointing that out.

property should be in alphabetic order on docs, make it a bit more easy to read, imho.
