### ISSUE TITLE
当渲染模型为‘svg’，饼图lengend.type = 'scroll'时，图例文字丢失，分页标签覆盖住了图例，类型为‘canvas’显示正常

### ISSUE THREAD

**Issue by chensongtao** [apache/incubator-echarts#9312]
One-line summary [问题简述]
当渲染模型为‘svg’，饼图lengend.type = 'scroll'时，图例文字丢失，分页标签覆盖住了图例，类型为‘canvas’显示正常。

同样的问题：https://github.com/apache/incubator-echarts/issues/7908#issue-304041322
原因大概在：clip-path属性，改成clip-path = "none"出现了 , 

Version & Environment [版本及环境]
ECharts version [ECharts 版本]: 4.X
Browser version [浏览器类型和版本]: chrome 64.0.3282.168（正式版本） （32 位）
OS Version [操作系统类型和版本]: windows 64bit
Expected behaviour [期望结果]
‘svg’模式下显示正常

ECharts option [ECharts配置项]
option = {"series":[{"type":"pie","name":"页面浏览的总次数","data":[{"value":74,"name":"其它"},{"value":50,"name":"en-US"},{"value":5604,"name":"zh-CN"},{"value":99,"name":"zh"},{"value":150,"name":"zh-TW"}],"center":["50%","48%"],"radius":[0,"65%"],"itemStyle":{"emphasis":{"shadowBlur":10,"shadowOffsetX":0,"shadowColor":"rgba(0, 0, 0, 0.5)"}},"label":{"show":true,"position":"outside"},"smooth":true}],"title":{},"xAxis":[],"yAxis":[],"tooltip":{"trigger":"item","axisPointer":{"type":"shadow"},"textStyle":{"fontSize":12}},"grid":{"top":"5%","left":"2%","right":"2%","bottom":"10%","containLabel":true},"legend":{"type":"scroll","orient":"horizontal","bottom":-2,"data":["其它","en-US","zh-CN","zh","zh-TW"],"tooltip":{"show":true}}}
Other comments [其他信息]

**Comment by jeff0905** [comment]
查看了下， <text alignment-baseline="middle" x="30" y="7" fill="#999999" fill-opacity="1" stroke="none" transform="matrix(1,0,0,1,5,281.5)" clip-path="url(#zr4338-clip-7)" style="font: 12px &quot;Microsoft YaHei&quot;;"><tspan alignment-baseline="middle" text-anchor="start" x="30" y="7">其它</tspan></text>
是因为clip-path='url.....' 这个造成的。 把clip-path改成 clip-path="none" 就可以显示了。

**Comment by jeff0905** [comment]
svg 的 text 元素 的属性 clip-path造成的。 clip-path="url(#zr4338-clip-7)" ， 如果把clip-path改成 "none" 就可以显示出来。

**Comment by jeff0905** [comment]
Any update/progress on this one?

**Comment by jeff0905** [comment]
Hi, Any update/progress on this one?

**Comment by jeff0905** [comment]
Hi, Good morning, Any update/progress on this one?

**Comment by jeffmobiles** [comment]
Hi, Any update/progress on this one?

**Comment by Ovilia** [comment]
Please follow #9565 .
