### ISSUE TITLE
prevent x-y axis inversion

### ISSUE THREAD

**Issue by 1u0n** [apache/incubator-echarts#9313]
in line and bar charts, if `yAxis.type === 'category'` and `xAxis.type === 'value'|'time'` the chart's projection direction will be automatically inverted (bars will be horizontal instead of vertical, for example). This makes sense in most scenarios, but if still want to keep the original direction, how could this be done?

I haven't found any option to control this default behaviour. Please note that changing x and y in `series.encode` won't do the job as I still want xAxis to be value/time, yAxis to be category.

**Comment by 100pah** [comment]
Currently, if there is a category axis or time axis in a cartesian, the bar goes toward that axis.
If both axes is value axes, the bar goes towards x axis. 
It is possible that set your yAxis as a `value` axis?

**Comment by 1u0n** [comment]
the use case could be a `time` xAxis where for every month you show on yAxis a `category` describing that month's aggregated results like "good", "average", "bad"...

Only way I found was to also set xAxis as category, then bars will still go vertical.

Maybe it's worth considering an option to modify default behaviour, and let user decide?
