### ISSUE TITLE
Pie Chart - label 'align' and 'verticalAlign' don't effect label position

### ISSUE THREAD

**Issue by rweller59** [apache/incubator-echarts#9318]
I can't seem to change the alignment of labels on pie. Have tried different combinations of align, verticalAlign but the label position does not change.

```
{
          name:'time',
          type:'pie',
          radius : ['70%', '75%'],
          data: this.getOptionClock1()
}

getOptionClock = () => {
    const data = [];
    for(let i=0; i<24; i++) {
      data.push({
        value: 1, 
        name: clockLabel(i),
        label: { 
          show: clockLabelShow(i), 
          position: 'inside', 
          align: 'center', 
          verticalAlign: 'middle',
          padding: clockLabelPadding(i),
        },
        labelLine: { show: false },
        itemStyle: { 
          color: clockColor(i),
         },
      });
    }
    return data;
  }
```

**Comment by 100pah** [comment]
Currently `label.align` and `label.verticalAlign` can not be specified. Consider that a pie label might be left or right of the pie, its align should be 'right' or 'left' correspondingly. 
The doc should be updated.

**Comment by rweller59** [comment]
I am trying to have label centered over slice tick mark. For example, if each slice represents an hour of time, I would like the first label at the top of the 'clock' centered over the beginning tick. Is there any other way to do this? Or I could try to position using padding?

**Comment by rweller59** [comment]
I positioned using padding parameters. I may play around with polar charts later but all set for now.

thanks.
