### ISSUE TITLE
家谱图的绘制

### ISSUE THREAD

**Issue by neverlous** [apache/incubator-echarts#9323]
最近有个需求，做个家谱图，就是父母有孩子，可以是多个孩子，孩子也也有配偶和孩子。配偶关系还存在前任配偶的关系。这样的家庭关系图，一直没有好的解决方案。大家有什么好的办法吗？

**Comment by cuijian-dexter** [comment]
You can use `tree` diagrams.
http://echarts.baidu.com/examples/editor.html?c=tree-basic
