### ISSUE TITLE
折线图用按钮切换改变数据的时候，会短暂的出现一条竖线然后消失

### ISSUE THREAD

**Issue by HengLiYang** [apache/incubator-echarts#9328]
比如 现在有两个按钮A 和按钮B， 默认初始化显示是A按钮的数据，点击B按钮切换折线图数据，没有问题，当我再次点击A按钮的时候，就会出现一条竖线，大概0.5s，然后消失，请问大家有没有解决的办法？

**Comment by HengLiYang** [comment]
更新下这个问题，是在animation开启的时候会有这个问题，animation关闭的时候没有，可能是贝塞尔曲线的过渡有问题，不知道大家如何处理？

**Comment by 100pah** [comment]
没有提供 option，难于知道具体问题。
