### ISSUE TITLE
Candlestick组件中，markPoint宽度怎么随缩放改变大小？也就是markPoint宽度，随着拖拉，和k线宽度保持一致

### ISSUE THREAD

**Issue by yequ1006** [apache/incubator-echarts#9336]
### One-line summary [问题简述]

Candlestick组件中，markPoint宽度怎么随缩放改变大小？也就是markPoint宽度，随着拖拉，和k线宽度保持一致

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by cuijian-dexter** [comment]
Please add `option` to facilitate understanding of the problem.
