### ISSUE TITLE
饼图在配合setInterval使用时数据未能更新的问题

### ISSUE THREAD

**Issue by KaylaChiu** [apache/incubator-echarts#9337]
### One-line summary [问题简述]
饼图配合计时器setInterval使用时，当实例重新setOption，
会出现某一项data的数据未能刷新的情况，即数据仍然为上一次渲染时的数据：

![image](https://user-images.githubusercontent.com/32062252/47987610-ea3bff80-e11a-11e8-9fc3-7ef128947b06.png)

，而当鼠标悬停在上面的时候，数据则能恢复正常：

![image](https://user-images.githubusercontent.com/32062252/47987600-e4461e80-e11a-11e8-90ec-4fe9d9eefe2d.png)

图为在官方实例Doughnut Chart上试验的结果，而出现数据未能刷新的情况也没有规律。
尝试过手动频繁操作刷新数据，也没有出现类似的情况

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0-release
+ Browser version [浏览器类型和版本]: chrome 70.0.3538.77
+ OS Version [操作系统类型和版本]: win10

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        x: 'left',
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series: [
        {
            name:'访问来源',
            type:'pie',
            radius: ['50%', '70%'],
            avoidLabelOverlap: false,
            label: {
                normal: {
                    show: true,
                    position: 'outside',
                    textStyle: {
                        fontSize: '30'
                    },
                    formatter:'{b}\n{d}%'
                },
                emphasis: {
                    show: true,
                    textStyle: {
                        fontSize: '30'
                    }
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
}

**setInterval(function(){
    option.series[0].data.forEach(function(ele){
        ele.value = Math.ceil(Math.random() * 100);
    });
    myChart.setOption(option);
}, 10000);**

```

**Comment by KaylaChiu** [comment]
找到规律了，刷新时如果鼠标悬停在某个块上，刷新后就会出现该块在默认状态下维持上一次刷新时的数据的情况

**Comment by cuijian-dexter** [comment]
@KaylaChiu  I didn't repeat this question.

**Comment by KaylaChiu** [comment]
> @KaylaChiu I didn't repeat this question.

Did you hold the mouse on one of the parts and wait for 10sec?

**Comment by KaylaChiu** [comment]
@cuijian-dexter Did you hold the mouse on one of the parts and wait for 10sec?

**Comment by cuijian-dexter** [comment]
@KaylaChiu  Sure

**Comment by cuijian-dexter** [comment]
This is really a bug.

**Comment by cuijian-dexter** [comment]
@KaylaChiu The problem seems to have been solved.Please，verify and close it. Thanks~
