### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by xcsweb** [apache/incubator-echarts#9338]
![image](https://user-images.githubusercontent.com/20693737/47990260-0ee7a580-e122-11e8-8b9c-ceddf464d463.png)
![image](https://user-images.githubusercontent.com/20693737/47990335-3d658080-e122-11e8-9eac-b16174d5b80e.png)
![image](https://user-images.githubusercontent.com/20693737/47990502-a1884480-e122-11e8-8e65-5950e3c48dbf.png)

![image](https://user-images.githubusercontent.com/20693737/47990274-17d87700-e122-11e8-8d19-c242e6bb0c40.png)
![image](https://user-images.githubusercontent.com/20693737/47990316-3179be80-e122-11e8-8add-0bc387da5573.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 4]:
+ Browser version [chrome69]:
+ OS Version [window7]:

### ECharts option [ECharts配置项]

```javascript
option ={
                    title : {
                    text: '某站点用户访问来源',
                    subtext: '纯属虚构',
                    x:'center'
                },
                series : [
                    {
                        name: '访问来源',
                        type: 'pie',
                        radius : '55%',
                        center: ['50%', '60%'],
                        data:[
                            {value:335, name:'直接访问'},
                            {value:310, name:'邮件营销'},
                            {value:234, name:'联盟广告'},
                            {value:135, name:'视频广告'},
                            {value:1548, name:'搜索引擎'}
                        ]
                    }
                ]
                }

```

**Comment by hlbj105** [comment]
这个是什么问题的？怎么修复的？
