### ISSUE TITLE
导出到excel上是报错

### ISSUE THREAD

**Issue by leijue** [apache/incubator-echarts#9340]
### One-line summary [问题简述]
Uncaught TypeError: Cannot create property 'pixelRatio' on string 'png'
at ECharts.echartsProto.getRenderedCanvas (VM6856 echarts.js:26850)
导出图表到excel时报错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请给出更详细的复现信息

**Comment by leijue** [comment]
> 请给出更详细的复现信息

$('#export').click(function () {
	var imagesBase64 = lineFault.getDataURL('png');
	$.ajax({
		url: getRootPath() + '/device/DeviceFaultInfo/export',
		type: 'POST',
		data: {
			'imagesBase64': imagesBase64
		},
		success: function () {
			alert('导出成功');
		},
		error: function () {
			alert('导出失败');
		}
	});
});

var imagesBase64 = lineFault.getDataURL('png'); 
这里会报Cannot create property 'pixelRatio' on string 'png'的错误

**Comment by willxiang** [comment]
请问Cannot create property 'pixelRatio' on string 'png'解决了吗？我也碰到了类似问题

**Comment by leijue** [comment]
> 请问Cannot create property 'pixelRatio' on string 'png'解决了吗？我也碰到了类似问题

var typeBase64 = typeFault.getDataURL({
	type: 'png',
	pixelRatio: 1
});

我是这样解决的  希望能帮到你

**Comment by willxiang** [comment]
> > 请问Cannot create property 'pixelRatio' on string 'png'解决了吗？我也碰到了类似问题
> 
> var typeBase64 = typeFault.getDataURL({
> type: 'png',
> pixelRatio: 1
> });
> 
> 我是这样解决的 希望能帮到你

谢谢你的帮助！
