### ISSUE TITLE
events defined by `chart.on(eventName, ...` are not triggered

### ISSUE THREAD

**Issue by arashdalir** [apache/incubator-echarts#9341]
### defined events are not triggered
(at least) `finished` and `rendered` events are not triggered/executed.

### Version & Environment
+ ECharts version v4.2.0-rc2
+ Browser version chrome-70.0.3538.77 
+ OS Version windows 7

### Expected behaviour 
the function defined should be triggered.
in given example: 
having 'finished loading' in console 

### ECharts option 
```javascript
var myChart = echarts.init(document.getElementById('chart1'), null, {
	"devicePixelRatio": null,
	"renderer": "canvas",
	"width": null,
	"height": "600px"
});
myChart.setOption({
	"title": {
		"text": "test",
	},
	"grid": [
		{
			"top": "5%",
			"height": "60%",
			"width": "60%",
			"left": "5%",
			"containLabel": false,
			"borderColor": "transparent",
			"show": "1"
		}
	],
	"xAxis": [
		{
			"type": "time",
			"min": "dataMin",
			"max": "dataMax"
		}
	],
	"yAxis": [
		{
			"type": "value",
		}
	],
	"series": {"name": "insufficient_data", "type": "bar"},
});

myChart.on('finished', function (params){
	console.log('finished loading');
});
```
![image](https://user-images.githubusercontent.com/2896170/47997287-97068480-e0fb-11e8-8397-248f5dc99171.png)

**Comment by sxmpasch** [comment]
@arashdalir - this works for me without problems running on Chrome 70 / Windows 7.
Could it be you do not wait for page loading complete before initializing your div object?
E.g.
```
<body onload="init()">
...

```

**Comment by arashdalir** [comment]
found the issue. there is a problem with triggering the events when the dataset is empty. if there is no data to be rendered, the events are not triggered. it is not dependant on the `onload` function, but rather the `data` of the series; which is a big inconevience. 

there is also another problem with mouse-events; they ONLY WORK if users click on series, but not on the chart itself. I assume the triggers are defined on the wrong subjects. please check out the commented series in following example:

```javascript

console.log('started loading');

var myChart = echarts.init(document.getElementById('chart1'), null, {
	"devicePixelRatio": null,
	"renderer": "canvas",
	"width": null,
	"height": "600px"
});
myChart.setOption({
	"title": {
		"text": "test",
	},
	"grid": [
		{
			"top": "5%",
			"height": "60%",
			"width": "60%",
			"left": "5%",
			"containLabel": false,
			"borderColor": "transparent",
			"show": "1"
		}
	],
	"xAxis": [
		{
			"type": "category",
			"min": "dataMin",
			"max": "dataMax"
		}
	],
	"yAxis": [
		{
			"type": "value",
		}
	],
	// "series": {"name": "insufficient_data", "type": "bar", "data": [[1, 2], [2, 3]]}, // this works
	// "series": {"name": "insufficient_data", "type": "bar", "data": []}, // this doesn't work
	// "series": {"name": "insufficient_data", "type": "bar"}, // this neither
});

console.log('options set');

myChart.on('finished', function (params){
	console.log('finished loading');
});
```

**Comment by arashdalir** [comment]
even `// "series": {"name": "insufficient_data", "type": "bar", data:[[0,0]]}` doesn't work! which is now causing real issues...

**Comment by sxmpasch** [comment]
Hmm, it still works for me. But I have set the finished event handler before setting the option...:

```
<!doctype HTML5>
<html>
    <head>
	<script src="./echarts-en.min.js"></script>
	<script type="text/javascript">



function init() {
 console.log("init");
 
 
console.log('started loading');

var myChart = echarts.init(document.getElementById('chart1'), null, {
	"devicePixelRatio": null,
	"renderer": "canvas",
	"width": null,
	"height": "600px"
});
myChart.on('finished', function (params){
	console.log('finished loading');
});
myChart.setOption({
	"title": {
		"text": "test",
	},
	"grid": [
		{
			"top": "5%",
			"height": "60%",
			"width": "60%",
			"left": "5%",
			"containLabel": false,
			"borderColor": "transparent",
			"show": "1"
		}
	],
	"xAxis": [
		{
			"type": "category",
			"min": "dataMin",
			"max": "dataMax"
		}
	],
	"yAxis": [
		{
			"type": "value",
		}
	],
	// "series": {"name": "insufficient_data", "type": "bar", "data": [[1, 2], [2, 3]]}, // this works
	// "series": {"name": "insufficient_data", "type": "bar", "data": []}, // this doesn't work
	// "series": {"name": "insufficient_data", "type": "bar"}, // this neither
});

console.log('options set');

 
};

</script>
    </head>
    <body onload="init()">
	<h1>Test</h1>
	<div id="chart1" style="width:480px; height:480px"></div>
</body>
</html>

```

**Comment by sxmpasch** [comment]
@arashdalir : Regarding Event triggers: There is a feature planned to expose grid events as well, see e.g. issue #9281.
@Ovilia - is there already a release planned containing this feature?

**Comment by sxmpasch** [comment]
As intermediate solution, you could add an event listener to the parent div object in order to receive click-coordinates. They then can be transformed into real axis coordinates:

```
document.getElementById('chart-panel').addEventListener("click",function(e){
    console.log(e.zrX+"#"+e.zrY+'#'+myChart.convertFromPixel({xAxisIndex:0, yAxisIndex:0},[e.zrX,e.zrY]));
})

```

**Comment by arashdalir** [comment]
I'm afraid I have to inform you this **only works to some extension**. 
now, 

- if _there are no series defiend_, `finished` event is happening **before** options are set.
- if _there is at least one series defined_, the `finished` event is **happening** after options are set.

```javascript
console.log('started loading');

var myChart = echarts.init(document.getElementById('chart1'), null, {
	"devicePixelRatio": null,
	"renderer": "canvas",
	"width": null,
	"height": "600px"
});

myChart.on('finished', function (){
	console.log('finished loading');
});

console.log('setting options');
myChart.setOption({
	"title": {
		"text": "test",
	},
	"grid": [
		{
			"top": "5%",
			"height": "60%",
			"width": "60%",
			"left": "5%",
			"containLabel": false,
			"borderColor": "transparent",
			"show": "1"
		}
	],
	"xAxis": [
		{
			"type": "category",
		}
	],
	"yAxis": [
		{
			"type": "value",
		}
	],
	//"series": {"name": "insufficient_data", "type": "scatter", data:[[0,0]]},
});
console.log('options set');
```
```
// console output WITHOUT SERIES:
started loading
setting options
finished loading
options set

// console output WITH series:
started loading
setting options
options set
finished loading
```

> Hmm, it still works for me. But I have set the finished event handler before setting the option...:
> 
> ```
> <!doctype HTML5>
> <html>
>     <head>
> 	<script src="./echarts-en.min.js"></script>
> 	<script type="text/javascript">
> 
> 
> 
> function init() {
>  console.log("init");
>  
>  
> console.log('started loading');
> 
> var myChart = echarts.init(document.getElementById('chart1'), null, {
> 	"devicePixelRatio": null,
> 	"renderer": "canvas",
> 	"width": null,
> 	"height": "600px"
> });
> myChart.on('finished', function (params){
> 	console.log('finished loading');
> });
> myChart.setOption({
> 	"title": {
> 		"text": "test",
> 	},
> 	"grid": [
> 		{
> 			"top": "5%",
> 			"height": "60%",
> 			"width": "60%",
> 			"left": "5%",
> 			"containLabel": false,
> 			"borderColor": "transparent",
> 			"show": "1"
> 		}
> 	],
> 	"xAxis": [
> 		{
> 			"type": "category",
> 			"min": "dataMin",
> 			"max": "dataMax"
> 		}
> 	],
> 	"yAxis": [
> 		{
> 			"type": "value",
> 		}
> 	],
> 	// "series": {"name": "insufficient_data", "type": "bar", "data": [[1, 2], [2, 3]]}, // this works
> 	// "series": {"name": "insufficient_data", "type": "bar", "data": []}, // this doesn't work
> 	// "series": {"name": "insufficient_data", "type": "bar"}, // this neither
> });
> 
> console.log('options set');
> 
>  
> };
> 
> </script>
>     </head>
>     <body onload="init()">
> 	<h1>Test</h1>
> 	<div id="chart1" style="width:480px; height:480px"></div>
> </body>
> </html>
> ```

**Comment by Ovilia** [comment]
I tried with option without series provided by @arashdalir , but the `rendered` and `finished` event is triggered.
As about the mouse event on other components, we are considering to support this. See: https://github.com/apache/incubator-echarts/issues/9281

**Comment by arashdalir** [comment]
@Ovilia  as said, the functions work, but in the wrong order. interesting enough, this has no effect on the chart's options (i.e. `var options = chart.getOptions` delivers the right options). so technically, it's not an issue on itself, but rather a chronological problem with the events...

**Comment by mohitjain0824** [comment]
In the axis option, you might have to add triggerEvent property.

`myChart.setOption({
        .
        .
	"xAxis": [
		{
			triggerEvent: true,
		}
	],
	"yAxis": [
		{
			triggerEvent: true,
		}
	],
})`

This worked for me.
Hope it helps.
