### ISSUE TITLE
如何在Echart中同一个Series对应多个legend？

### ISSUE THREAD

**Issue by csxiang18** [apache/incubator-echarts#9343]
### One-line summary [问题简述]
在一个折线图中标有直线和点，我通过将name设置成一样，这样在legend中就可以有一个legend同时控制直线和点的开关。但目前还有一个需求是添加一个legend单独控制点的开关，应该如何设置Option？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0-release
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Mac OS

### Expected behaviour [期望结果]
添加一个legend单独控制点的开关。

### ECharts option [ECharts配置项]

```javascript
option = {
    legend: {
        data: ['test']
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [10, 20, 30, 40, 50, 60, 70],
        type: 'line',
        name: 'test',
    },{
        data: [['Mon', 10], ['Wed', 30]],
        type: 'effectScatter',
        name: 'test'
    }]
}

```

### Other comments [其他信息]

<img width="908" alt="wx20181105-201803 2x" src="https://user-images.githubusercontent.com/40510996/47997841-38abc700-e138-11e8-9534-a816e4028453.png">

**Comment by Ovilia** [comment]
By using the same name with different series, user can toggle legend display at the same time.
We are considering adding an all-in-one legend toggling method to switch on and off all the legends. But currently you should use the same series name to do so.

**Comment by csxiang18** [comment]
> By using the same name with different series, user can toggle legend display at the same time.
> We are considering adding an all-in-one legend toggling method to switch on and off all the legends. But currently you should use the same series name to do so.

Yes, but when I use the same series name, I can not control the series independently. All I want is to control some of series all-in-one but also control series independently.

**Comment by Ovilia** [comment]
By now, you have to use different series name, and then listen to legend events and trigger legend action.

**Comment by csxiang18** [comment]
> By now, you have to use different series name, and then listen to legend events and trigger legend action.

I have already solve it by listen to legend events and set the symbolSize to 0 to implement this feature. I think this issue can be closed. Thanks a lot!

**Comment by mmmaomao21** [comment]
你好，你具体是怎么解决这个问题的？正好也做到这个需求

**Comment by csxiang18** [comment]
可以添加一个虚拟的legend，然后监听他的点击事件，把点的symbolSize设置0就好了。

mmmaomao21 <notifications@github.com> 于2019年3月4日周一 上午11:41写道：
