### ISSUE TITLE
pie图使用dataset，然后label使用{c}，显示上有问题

### ISSUE THREAD

**Issue by hanfengcan** [apache/incubator-echarts#9344]
### One-line summary [问题简述]

修改官方一个例子，http://echarts.baidu.com/examples/editor.html?c=dataset-default

label使用{c}，显示dataset某一行的全部数据。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

合理显示某行某列交叉的那个值

### ECharts option [ECharts配置项]

```javascript
var option = {
    legend: {},
    tooltip: {},
    dataset: {
        source: [
            ['product', '2012', '2013', '2014', '2015', '2016', '2017'],
            ['Matcha Latte', 41.1, 30.4, 65.1, 53.3, 83.8, 98.7],
            ['Milk Tea', 86.5, 92.1, 85.7, 83.1, 73.4, 55.1],
            ['Cheese Cocoa', 24.1, 67.2, 79.5, 86.4, 65.2, 82.5],
            ['Walnut Brownie', 55.2, 67.1, 69.2, 72.4, 53.9, 39.1]
        ]
    },
    series: [{
        type: 'pie',
        radius: 60,
        center: ['25%', '30%']
        // No encode specified, by default, it is '2012'.
    }, {
        type: 'pie',
        radius: 60,
        center: ['75%', '30%'],
        encode: {
            itemName: 'product',
            value: '2013'
        }
    }, {
        type: 'pie',
        radius: 60,
        center: ['25%', '75%'],
        encode: {
            itemName: 'product',
            value: '2014'
        }
    }, {
        type: 'pie',
        radius: 60,
        center: ['75%', '75%'],
        encode: {
            itemName: 'product',
            value: '2015'
        },
        label: {
            formatter: '{c}'
        }
    }]
};

```

### Other comments [其他信息]

![_20181106105235](https://user-images.githubusercontent.com/4559753/48039982-1bb3da00-e1b2-11e8-9cfc-c964d1323b2a.png)

**Comment by hanfengcan** [comment]
在源码 test/pie.HTML 是使用
`
                    dataset: {
                        source: [
                            {name: 'a', value: 123},
                            {name: 'b', value: 456},
                            {name: 'should be selected', value: 789, selected: true}
                        ]
                    },
`
就没有这个问题。

**Comment by cuijian-dexter** [comment]
@hanfengcan  You can try it 
`label: {
            formatter: '{@[4]}'
        }`

**Comment by tz158310601** [comment]
我改写了这个方法，将就凑合一下吧
function formatTpl(tpl, paramsList, encode) {
    if (!isArray(paramsList)) {
        paramsList = [paramsList];
    }
    var seriesLen = paramsList.length;
    if (!seriesLen) {
        return '';
    }

    var $vars = paramsList[0].$vars || [];
    for (var i = 0; i < $vars.length; i++) {
        var alias = TPL_VAR_ALIAS[i];
        tpl = tpl.replace(wrapVar(alias), wrapVar(alias, 0));
    }
    for (var seriesIdx = 0; seriesIdx < seriesLen; seriesIdx++) {
        for (var k = 0; k < $vars.length; k++) {
            var val = paramsList[seriesIdx][$vars[k]];
			if (zrUtil.isObject(val)) {
				if(paramsList[seriesIdx].componentSubType=='pie'){
					for( var key in val){
						if(val[key] !=paramsList[seriesIdx].name){
							val =val[key] 
						}
					}
				}
			}
            tpl = tpl.replace(
                wrapVar(TPL_VAR_ALIAS[k], seriesIdx),
                encode ? encodeHTML(val) : val
            );
        }
    }

    return tpl;
}



-----------------只有当dataset只有两维数据才有效。如果数据维度多了，这个循环可能就指向的是错误 的数据了

**Comment by quick-sort** [comment]
in 

> 在源码 test/pie.HTML 是使用
> 
> ```
>                     dataset: {
>                         source: [
>                             {name: 'a', value: 123},
>                             {name: 'b', value: 456},
>                             {name: 'should be selected', value: 789, selected: true}
>                         ]
>                     },
> ```
> 就没有这个问题。

似乎这个也是有问题的
https://echarts.baidu.com/examples/editor.html?c=dataset-simple1
option = {
    legend: {},
    tooltip: {},
    dataset: {
        dimensions: ['product', '2015', '2016', '2017'],
        source: [
            {product: 'Matcha Latte', '2015': 43.3, '2016': 85.8, '2017': 93.7},
            {product: 'Milk Tea', '2015': 83.1, '2016': 73.4, '2017': 55.1},
            {product: 'Cheese Cocoa', '2015': 86.4, '2016': 65.2, '2017': 82.5},
            {product: 'Walnut Brownie', '2015': 72.4, '2016': 53.9, '2017': 39.1}
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar',
            label: {
                show: true,
                formatter: a => JSON.stringify(a.value)
            }
        }
    ]
};
<img width="1280" alt="Screen Shot 2019-04-10 at 10 47 38 AM" src="https://user-images.githubusercontent.com/7898590/55847986-18b47f80-5b7e-11e9-9f86-ba40e41aa456.png">
