### ISSUE TITLE
Tooltip 模块，有类似 Highcharts 里的 Tooltip.shared ，或是 Grafana 里 Hover tooltip 的 All series / Single 的功能吗？

### ISSUE THREAD

**Issue by jsers** [apache/incubator-echarts#9347]
### One-line summary [问题简述]
Tooltip 模块，有类似 Highcharts 里的 Tooltip.shared ，或是 Grafana 里 Hover tooltip 的 All series / Single 的功能吗？

只在文档里面找到 Tooltip.trigger 发现这个配置并不能满足我的需求， item 不会 "吸附到最近点"，axis 只能同时看所有 series 的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4.x
+ Browser version [浏览器类型和版本]: Chrome v69
+ OS Version [操作系统类型和版本]: Mac

**Comment by Ovilia** [comment]
Can you provide an image to show what you need?

**Comment by jsers** [comment]
![image](https://user-images.githubusercontent.com/7424634/48401920-3a434380-e765-11e8-86cf-4dcec909c0ff.png)

**Comment by Ovilia** [comment]
So let me be clear.
What you want from ECharts is:
(1) Not to show item (the green triangle and the purple rectangle) of other series
(2) Not to show information of other series in tooltip

You may try with [tooltip.trigger to be `'item'`](http://echarts.baidu.com/option.html#tooltip.trigger) and [axisPointer](http://echarts.baidu.com/option.html#axisPointer) to be shown. See doc for more detials.
