### ISSUE TITLE
showLoading操作不能自定义变量

### ISSUE THREAD

**Issue by guoqn** [apache/incubator-echarts#9349]
### One-line summary [问题简述]

this.chart.showLoading(
      {
        text: '请稍后...',
        color: 'blue',
        textColor: '#fff',
        maskColor: 'rgba(0, 0, 0, 0.8)',
        zlevel: 0
      }
    )

无法自定义

### Version & Environment [版本及环境]
+ ECharts version [4.2.0-rc.2 ]:
+ Browser version [chrome65]:
+ OS Version [10.13.4 (17E202)]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以参考 https://github.com/apache/incubator-echarts/blob/master/src/loading/default.js 实现自己的 loading 效果，使用 echarts.registerLoading 方法注册，参考 https://github.com/apache/incubator-echarts/blob/master/src/echarts.js#L2330

**Comment by guoqn** [comment]
echarts [4.2.0-rc.2]似乎没有暴露这个 registerLoding   api ... 
另外，可否注册到主题中~

**Comment by guoqn** [comment]
> 可以参考 https://github.com/apache/incubator-echarts/blob/master/src/loading/default.js 实现自己的 loading 效果，使用 echarts.registerLoading 方法注册，参考 https://github.com/apache/incubator-echarts/blob/master/src/echarts.js#L2330

你好，针对这个方法实验后端效果  似乎并不理想,效果没有被覆盖

echarts.registerTheme('customed',...conf);
echarts.registerLoading('customed', {
        text: '请稍后...',
        color: 'blue',
        textColor: '#fff',
        maskColor: 'rgba(0, 0, 0, 0.8)',
        zlevel: 0
      })
结果还是原来多

**Comment by cuijian-dexter** [comment]
http://gallery.echartsjs.com/editor.html?c=x-bLMl6BVu&v=1
