### ISSUE TITLE
“myChart.getModel().getSeriesByIndex(0).getData().getVisual('color')”这个在折线图例中有效，在饼状图是无效，是不是又是不另外一个方法获取了？

### ISSUE THREAD

**Issue by mlgzzz** [apache/incubator-echarts#9354]
_Originally posted by @newenter in https://github.com/apache/incubator-echarts/issues/3571#issuecomment-254758629_

**Comment by pissang** [comment]
myChart.getModel().getSeriesByIndex(0).getData().getItemVisual(dataIndex, 'color')
