### ISSUE TITLE
地图显示背景图片

### ISSUE THREAD

**Issue by huimei123** [apache/incubator-echarts#9362]
![image](https://user-images.githubusercontent.com/28640116/48123898-088a3280-e2b6-11e8-8818-3e769ca37882.png)

中国地图希望可以显示背景图片，现在找到的配置基本都是颜色，不知道有没有背景图的设置呢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by huimei123** [comment]
> 一下试使用http://echarts.baidu.com/option.html#geo.itemStyle.areaColor 这里写的纹理填充模式

在geo 里写上了纹理填充模式，但是感觉不生效。引用的样式还是visualMap里面的

**Comment by cn-xufei** [comment]
这个居然都没有解决
