### ISSUE TITLE
Dataset的dimensions存在'0'，无法正常工作，图表报错

### ISSUE THREAD

**Issue by elephantme** [apache/incubator-echarts#9363]
### One-line summary [问题简述]

将官方提供的[demo](http://www.echartsjs.com/gallery/editor.html?c=dataset-simple0)中的`source`中的2015修改为0，控制台报错，无法正常绘制图表

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Mac OS

### Expected behaviour [期望结果]

正常工作

### ECharts option [ECharts配置项]

```javascript
option = {
    legend: {},
    tooltip: {},
    dataset: {
        source: [
            ['product', '0', '2016', '2017'],
            ['Matcha Latte', 43.3, 85.8, 93.7],
            ['Milk Tea', 83.1, 73.4, 55.1],
            ['Cheese Cocoa', 86.4, 65.2, 82.5],
            ['Walnut Brownie', 72.4, 53.9, 39.1]
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ]
};
```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#dataset.dimensions 参考 dimensions 文档里，可以设置字段类型，防止自动识别类型错误

**Comment by elephantme** [comment]
> http://echarts.baidu.com/option.html#dataset.dimensions 参考 dimensions 文档里，可以设置字段类型，“0” 这样的可能会被自动识别成数字

我换成这种写法可以了：

`option = {
    legend: {},
    tooltip: {},
    dataset: {
        dimensions: ['product', {displayName: '0'}, '2', '3'],
        source: [
            ['Matcha Latte', 43.3, 85.8, 93.7],
            ['Milk Tea', 83.1, 73.4, 55.1],
            ['Cheese Cocoa', 86.4, 65.2, 82.5],
            ['Walnut Brownie', 72.4, 53.9, 39.1]
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ]
};`

你说的dimensions中的type我理解是指定dataset中data的数据类型的。目前这个问题是维度名称中出现'0'，js就会报错，换成'1'都是可以正常展示的。

**Comment by yujinranran** [comment]
@pissang 大哥，修复了没，我也遇到了 啊！

**Comment by yujinranran** [comment]
很耽误事，维度为啥不是自动为 string

**Comment by yujinranran** [comment]
三万颗星，如此严重的故障，到现在还没修复，

> 
http://echarts.baidu.com/option.html#dataset.dimensions 参考 dimensions 文档里，可以设置字段类型，“0” 这样的可能会被自动识别成数字

这个说实话也看不懂，这么坑，文档还不好理解
