### ISSUE TITLE
dataZoom动态扩展xAxisIndex失败

### ISSUE THREAD

**Issue by hyfjjjj** [apache/incubator-echarts#9366]
### One-line summary [问题简述]
新增x轴后，试图设置原来的dataZoom的xAxisIndex来控制新的x轴失败

### Version & Environment [版本及环境]
+ ECharts version : 4.2.0
+ Browser version : Google Chrome 72.0.3604.0
+ OS Version : macOS Mojave 10.14.1

### Expected behaviour [期望结果]
dataZoom控件能够控制新增的x轴

### ECharts option [ECharts配置项]
原始的option:
{
  xAxis: [{...}],    // 只有一个
  dataZoom: {type: 'inside', xAxisIndex: [0], moveOnMouseMove: true, preventDefaultMouseMove: false}
}
然后执行option:
{
  xAxis: [{...}, {...}],    // 变成2个
  dataZoom: [{xAxisIndex: [0,1]}]  // xAxisIndex也改成2个
}
会出现js异常

### Other comments [其他信息]
![2018-11-08 3 27 53](https://user-images.githubusercontent.com/7194638/48183788-e4d4f400-e36a-11e8-88db-1b957efbdf5d.png)

**Comment by pissang** [comment]
有完整的 option 么？

**Comment by sogo5370** [comment]
我出現了一樣的問題，請問有解決方法嗎？
