### ISSUE TITLE
echarts未来是否有计划遵循可视化语法

### ISSUE THREAD

**Issue by dlutls** [apache/incubator-echarts#9368]
### One-line summary [问题简述]
echarts未来是否有计划遵循可视化语法，实现类似如下矩阵图表效果：  
![26](https://user-images.githubusercontent.com/8817369/48189633-9da32f00-e37b-11e8-9741-d43896febdea.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个图跟可视化语法的关系是？

**Comment by pissang** [comment]
高维数据的视觉映射参考 http://www.echartsjs.com/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE
