### ISSUE TITLE
options.xAxis.hoverAnimation without options.xAxis.animation

### ISSUE THREAD

**Issue by jbadilla** [apache/incubator-echarts#9370]
### One-line summary [问题简述]
"hoverAnimation = true" should work for the line graphs, even if "animation" is set to "false" .

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
`xAxis` component seems have no hoverAnimation option.
