### ISSUE TITLE
map天津市地图与实际不符

### ISSUE THREAD

**Issue by JarVan007** [apache/incubator-echarts#9373]
### One-line summary [问题简述]
require("echarts/map/js/province/tianjin");
引用内部天津市地图插件与百度地图天津市不符缺少蓟州区部分
![image](https://user-images.githubusercontent.com/24792319/48241335-60897c00-e411-11e8-9bde-61c8d22e4b22.png)
![image](https://user-images.githubusercontent.com/24792319/48241343-6d0dd480-e411-11e8-8cc1-56f93f680b05.png)
百度百科
![image](https://user-images.githubusercontent.com/24792319/48241375-90388400-e411-11e8-85f4-f22360f00876.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
"echarts": "^4.2.0-rc.1"
chrome 版本 70.0.3538.67（正式版本） （64 位）
 win 10

### Expected behaviour [期望结果]

补全地图缺失区域

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
我们不再继续提供地图数据，你可以从 https://github.com/echarts-maps/echarts-china-cities-js 等渠道获取需要的地图数据

**Comment by JarVan007** [comment]
ok, thank you~

**Comment by liubobuzhidao** [comment]
> 我们不再继续提供地图数据，你可以从 https://github.com/echarts-maps/echarts-china-cities-js 等渠道获取需要的地图数据

上面的链接没有天津市的地图，不过可以使用阿里云的http://datav.aliyun.com/tools/atlas/#&lat=39.51675478434244&lng=116.75445556640625&zoom=8

**Comment by JarVan007** [comment]
嗯，谢谢~
