### ISSUE TITLE
当柱状图 开启  yAxis 开启 scale: true 时候，柱子不是从X轴起始的地方开始画的，而是从下面开始

### ISSUE THREAD

**Issue by zhuzhiyuan** [apache/incubator-echarts#9377]
echart version 3.8.5 
npm install echarts 安装
chrome 浏览器，用官方 预览器没问题，下载的版本就不行 

option = {"color":["#50A1FD","#59CC76","#F8AC59"],"grid":{"top":"10%","left":"3%","right":"4%","bottom":"70px","containLabel":true},"xAxis":{"name":"时间","axisTick":{"alignWithLabel":true},"type":"category","data":["2018-01","2018-03","2018-04","2018-05","2018-06","2018-07"]},"yAxis":[{"name":"门店复购率","type":"value","scale":true},{"name":"排行率","type":"value","scale":true}],"series":[{"name":"门店评分","data":["4.89","4.99","5.00","5.00","4.79","4.98"],"type":"bar","barMaxWidth":50},{"name":"好评率全国排行","data":["13.38","76.94","99.78","78.38","69.05","41.73"],"type":"line","yAxisIndex":1}]}

效果如下
![image](https://user-images.githubusercontent.com/5226445/48265631-f18b4200-e467-11e8-92fa-0b60925ceda6.png)

**Comment by cuijian-dexter** [comment]
你可以下载最新版本4.2.0-rc.2
http://www.echartsjs.com/download.html

**Comment by zhuzhiyuan** [comment]
请问有npm版本吗

**Comment by zhuzhiyuan** [comment]
果然可以，谢谢

**Comment by cuijian-dexter** [comment]
@zhuzhiyuan 不用客气
