### ISSUE TITLE
saveAsImage – Specify path

### ISSUE THREAD

**Issue by jbadilla** [apache/incubator-echarts#9379]
### One-line summary [问题简述]
I would like to be able to specify the path for the 'saveAsImage' file that is downloaded. Is that possible?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
toolbox: {
  feature: {
      saveAsImage: {
          ...,
          path: 'file://....'
      }
  }
}
}

```

**Comment by cuijian-dexter** [comment]
@jbadilla I built an example.
http://gallery.echartsjs.com/editor.html?c=xIKpCw9YjJ&v=1

```javascript
option = {
toolbox: {
  feature: {
      saveAsImage: {
          icon: 'file://....'
      }
  }
}
}
```

**Comment by jbadilla** [comment]
Hey! Thanks for your response. I think you misunderstood, though.

What I am wondering is if you have the ability to add functionality such that I can **specify the path of the saved file relative to my file system.** I imagine I cannot do this on react, since it is client side, though..

**Comment by chfw** [comment]
Browser settings control the download folder.

**Comment by jbadilla** [comment]
All is good, guys! I've decided to just convert the base 64 to a blob, and then send it in the request to the server so that it is handled in the back-end. I just wanted to know if there was compatibility like other tools (i.e. browserify-fs).
