### ISSUE TITLE
echarts渲染不出来报错

### ISSUE THREAD

**Issue by luruxi** [apache/incubator-echarts#9383]
### One-line summary [问题简述]
vue+echarts渲染的图表比较多，有时候会出现一个图表不显示的问题，再次操作全部图表都不显示了，会有个报错，尝试更改echarts版本没效--TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')
![image](https://user-images.githubusercontent.com/33649116/48336225-cd637700-e69a-11e8-9d0f-40a0a3a4efe9.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.4，3.8.4，3.5.4都尝试过
+ Browser version [浏览器类型和版本]:ios手机safari，iphone 8P（12.1），7P（12.1），6P有问题；iphone 6s（10）没问题
+ OS Version [操作系统类型和版本]:ios12.1

### Expected behaviour [期望结果]
能够指导下怎么个情况，各种尝试都没能解决，资料也没有查到

### ECharts option [ECharts配置项]

```javascript
option = {

}
resourceDatachushi(el){
          let _this=this
        let dataT=el

        let xinshuzu=[]
       for(let i=0;i<dataT.length;i++){
                if(dataT[i].kpi_id=='I_04000072'){
                  _this.neibushangjishu=dataT[i].year_complete
                }else if(dataT[i].kpi_id=='I_04000076'){
                  _this.neibushangjijine=dataT[i].year_complete
                  xinshuzu.push({name:'内部商机',value:dataT[i].year_complete})
                }else if(dataT[i].kpi_id=='I_04000064'){
                  _this.waibushangjishu=dataT[i].year_complete
                }else if(dataT[i].kpi_id=='I_04000068'){
                  _this.waibushangjijine=dataT[i].year_complete
                  xinshuzu.push({name:'外部商机',value:dataT[i].year_complete})
                }
       }

       alert(JSON.stringify(xinshuzu))
//        if(this.$echarts.getInstanceByDom(this.$refs.Business_ji)){
//          this.$echarts.getInstanceByDom(this.$refs.Business_ji).dispose();
//        }
        let  myChart = this.$echarts.init(this.$refs.Business_ji)

        let option = {
//          color:['#FD9D67', '#FED350', '#A9D3FE', '#8FD3DE', '#A9D371', '#85E1CA', '#E7BD81', '#DBB1E1'],
          color:['#FED350', '#59CA92'],
          title:{
//            text:zongrenhus+"人"+"\n"+"员工总数",
            x:"center",
            y:"center",
            textStyle:{
              fontSize:"28px",
              color:"rgb(88,88,88)",
            },
          },
          tooltip: {
            confine:true,
            show:false,
            trigger: 'item',
            formatter: "{b}:{d}%"
          },
          legend: {
            data:['教育事业','环保事业','赈灾扶贫','其他公益事业'],
            bottom: 0,
            left: 'center',
          },
          series: [
            {
              type: 'pie',
              avoidLabelOverlap:true,
              clockwise:false,
              silent: true,
//              radius: ["20%","38%"],
//              center: ['50%', '50%'],
              radius: ["45%","65%"],
              center: ['50%', '50%'],
//              minAngle:10,
              labelLine:{
                show:true,
                length2:28
//                length:10,
//                length2:5
              },
              label: {
                normal: {
                  show: false,
//                  formatter:function (params) {
//                    let name = params.name;
//                    let tmp = "";
//                    if(name.length <= 5)
//                      tmp = name;
//                    else {
//                      if(name.length > 5){
//                        tmp += name.substring(0,4) + "\n";
//                        name = name.substring(4)
//                      }
//                      tmp += name;
//                    }
//                    return tmp +"\n"+params.percent+"%"+"\n"+params.value+'个'
//                  },
                },
                emphasis: {
                  show: false,
                  textStyle: {
                    fontSize: '10',
                    fontWeight: 'bold'
                  }
                }
              },
               itemStyle: {
                 normal: {
                   color: function (p){
                     if ( p.name == "外部商机" ) {
                       return "#59CA92";
                     } else if ( p.name == "内部商机" ) {
                       return "#FED350";
                     }
                   }
                 }
               },
              data:xinshuzu
            }
          ]
        };
       alert(JSON.stringify(option.series[0].data))
        myChart.setOption(option);
        alert(JSON.stringify(myChart.getOption()))

        $(window).resize(function () {
          myChart.resize();
        })
      },
```

**Comment by Ovilia** [comment]
Please add an example at jsfiddle.net to reproduce this.

**Comment by luruxi** [comment]
`<template>
     <div class="Business_opportunity_template">
          <div class="dahuikuai">

          </div>
          <div class="Business_opportunity_template_title">
              <div class="Business_opportunity_template_nei">
                <img src="../../assets/images/lantiao_title.png" alt="" class="lantiao_title">
                <span class="Business_opportunity_template_text">商机</span>
                <img src="../../assets/images/xiazuan_title.png" alt="" class="xiazuan_title" @click="tiaoerjiyemian">
              </div>
              <div class="huixian_fenge">

              </div>
          </div>
       <div class="Business_opportunity_template_bing">
         <div class="Business_ji" ref="Business_ji">

         </div>
         <div class="Business_opportunity_template_biaoshi">
           <div class="neibushangji">
             <div class="neibushangji_kuai">

             </div>
             <div class="neibushangji_text">
               内部商机
             </div>
             <div class="neibushangji_shuliang">
               数量&nbsp:&nbsp&nbsp<span>{{neibushangjishu|quzhengl}}个</span>
             </div>
             <div class="neibushangji_jine">
               金额&nbsp:&nbsp&nbsp<span>{{neibushangjijine|quzhengl}}万元</span>
             </div>
           </div>
           <div class="neibushangji">
             <div class="waibushangji_kuai">

             </div>
             <div class="neibushangji_text">
               外部商机
             </div>
             <div class="neibushangji_shuliang">
               数量&nbsp:&nbsp&nbsp<span>{{waibushangjishu|quzhengl}}个</span>
             </div>
             <div class="neibushangji_jine">
               金额&nbsp:&nbsp&nbsp<span>{{waibushangjijine|quzhengl}}万元</span>
             </div>
           </div>
         </div>
       </div>
     </div>
</template>
<style scoped>
  .dahuikuai{
    width: 100%;
    height: 14px;
    background: #f2f2f2;
  }
  .neibushangji_text{
   position: relative;
    top:-3px;
    font-size: 26px;
    color: #111111;
  }
  .Business_opportunity_template_biaoshi .neibushangji:nth-child(2){
    margin-top: 15px;
  }
  .Business_opportunity_template_biaoshi .neibushangji:first-child{
    margin-top: 40px;
  }
  .neibushangji_jine{
    margin-left:28px;
    font-size: 26px;
    color: #111111;
  }
  .neibushangji_shuliang{
    margin-left:28px;
    font-size: 26px;
    color: #111111;
  }
  .waibushangji_kuai{
    width: 24px;
    height: 24px;
    background:#59CA92;
    display: inline-block;
  }
  .neibushangji_text{
    display: inline-block;
  }
  .neibushangji_kuai{
    width: 24px;
    height: 24px;
    background:#FED350 ;
    display: inline-block;
  }
  .Business_opportunity_template_biaoshi{
    width: 50%;
    height: 340px;
    float: right;
  }
  .Business_ji{
    width: 50%;
    height: 340px;
    float: left;
  }
  .Business_opportunity_template_bing{
    width: 100%;
    height: 340px;
    background: #ffffff;
  }
  .huixian_fenge{
    width: 95%;
    border-bottom: 2px solid #606870;
    opacity:0.13;
    float: right;
  }
  .Business_opportunity_template_text{
    font-size: 30px;
    color: #222222;
  }
  .xiazuan_title{
    width: 14px;
    height: 24px;
    float: right;
    margin-top: 40px;
  }
  .lantiao_title{
    width: 6px;
    height:18px;
  }
  .Business_opportunity_template_nei{
    width: 90%;
    margin: 0 auto;
    height: 100px;
    line-height: 100px;
  }
  .Business_opportunity_template_title{
    width: 100%;
    height: 100px;
    background: #ffffff;

  }
    .Business_opportunity_template{
      width: 100%;
    }
</style>
<script>
  import commonJS from '@/common/js/common.js';
  export default {
    data() {
      return {
//          内部商机数
          neibushangjishu:'',
        //          内部商机金额
        neibushangjijine:'',
        //          外部商机数
        waibushangjishu:'',
        //          外部商机金额
        waibushangjijine:'',

      }
    },
    props:['shangji_moban'],
    mounted() {
      this.$nextTick(function () {
        let _this = this;
        _this.shangjiU()
      })
    },
    created() {
//      this.$nextTick(function () {
//        let _this = this;
//        setTimeout(function () {
//          _this.clickFlag = true;
//        },1000)
//        console.log('++++++++++++++++++++++++++++++++++++++++')
//      })
    },
    watch:{ // 监听时间日期插件
      "shangji_moban":function (val) {
        let _this=this
//        _this.resourceDatachushi()
      }
    },
    filters:{
      quzhengl(el){
          if(el!=''&&el!='null'&&el!=null){
              return Number(el).toFixed(0)
          }
      }
    },
    methods: {
       shangjiU(){
           let _this=this
//         商机的请求
         _this.$axios({
           method: 'post',
           url: '/edata-icome/icomeIot/getIotList',
           params: {
             zqid:'TC000151',
//            zqid:_this.$store.state.zqid,
             dataTable:'icome_teche_marketqs_kpi_h',
             kpi_id:'I_04000072,I_04000076,I_04000064,I_04000068',
             count_date:_this.$store.state.dateOnly.substring(0,6)
           }
         }).then((response) => {
//           _this.shangjishuzu=response.data.data
           console.log(response.data.data)
//           setTimeout(function () {

             _this.resourceDatachushi(response.data.data)
//           },500)

         }).catch((response) => {
           console.log(response)
         })
       },
//      饼图方法
      resourceDatachushi(el){
          let _this=this
        let dataT=el

        let xinshuzu=[]
       for(let i=0;i<dataT.length;i++){
                if(dataT[i].kpi_id=='I_04000072'){
                  _this.neibushangjishu=dataT[i].year_complete
                }else if(dataT[i].kpi_id=='I_04000076'){
                  _this.neibushangjijine=dataT[i].year_complete
                  xinshuzu.push({name:'内部商机',value:dataT[i].year_complete})
                }else if(dataT[i].kpi_id=='I_04000064'){
                  _this.waibushangjishu=dataT[i].year_complete
                }else if(dataT[i].kpi_id=='I_04000068'){
                  _this.waibushangjijine=dataT[i].year_complete
                  xinshuzu.push({name:'外部商机',value:dataT[i].year_complete})
                }
       }

       alert(JSON.stringify(xinshuzu))
//        if(this.$echarts.getInstanceByDom(this.$refs.Business_ji)){
//          this.$echarts.getInstanceByDom(this.$refs.Business_ji).dispose();
//        }
        let  myChart = this.$echarts.init(this.$refs.Business_ji)

        let option = {
//          color:['#FD9D67', '#FED350', '#A9D3FE', '#8FD3DE', '#A9D371', '#85E1CA', '#E7BD81', '#DBB1E1'],
          color:['#FED350', '#59CA92'],
          title:{
//            text:zongrenhus+"人"+"\n"+"员工总数",
            x:"center",
            y:"center",
            textStyle:{
              fontSize:"28px",
              color:"rgb(88,88,88)",
            },
          },
          tooltip: {
            confine:true,
            show:false,
            trigger: 'item',
            formatter: "{b}:{d}%"
          },
          legend: {
            data:['教育事业','环保事业','赈灾扶贫','其他公益事业'],
            bottom: 0,
            left: 'center',
          },
          series: [
            {
              type: 'pie',
              avoidLabelOverlap:true,
              clockwise:false,
              silent: true,
//              radius: ["20%","38%"],
//              center: ['50%', '50%'],
              radius: ["45%","65%"],
              center: ['50%', '50%'],
//              minAngle:10,
              labelLine:{
                show:true,
                length2:28
//                length:10,
//                length2:5
              },
              label: {
                normal: {
                  show: false,
//                  formatter:function (params) {
//                    let name = params.name;
//                    let tmp = "";
//                    if(name.length <= 5)
//                      tmp = name;
//                    else {
//                      if(name.length > 5){
//                        tmp += name.substring(0,4) + "\n";
//                        name = name.substring(4)
//                      }
//                      tmp += name;
//                    }
//                    return tmp +"\n"+params.percent+"%"+"\n"+params.value+'个'
//                  },
                },
                emphasis: {
                  show: false,
                  textStyle: {
                    fontSize: '10',
                    fontWeight: 'bold'
                  }
                }
              },
               itemStyle: {
                 normal: {
                   color: function (p){
                     if ( p.name == "外部商机" ) {
                       return "#59CA92";
                     } else if ( p.name == "内部商机" ) {
                       return "#FED350";
                     }
                   }
                 }
               },
              data:xinshuzu
            }
          ]
        };
       alert(JSON.stringify(option.series[0].data))
        myChart.setOption(option);
        alert(JSON.stringify(myChart.getOption()))

        $(window).resize(function () {
          myChart.resize();
        })
      },
      tiaoerjiyemian(){
        this.$router.push({
          path: '/second/chuanyueshangji_erjiyemian',
//          query: {
//            dataObj: $(el.currentTarget).attr("att"),
//            secondTil:$(el.currentTarget).attr("bss"),
//          }
        })
      }
    }
  }
</script>
`

**Comment by Ovilia** [comment]
This is by no means helpful. If you want get help from the community, you should first debug by yourself and provide useful information.

**Comment by fengfengxia** [comment]
这个问题我也遇到了，我做了4个tab页，每个tab页有十几个图表，在ios端快速切换这4个tab的时候就会出现和你一样的情况

**Comment by luruxi** [comment]
> 这个问题我也遇到了，我做了4个tab页，每个tab页有十几个图表，在ios端快速切换这4个tab的时候就会出现和你一样的情况

后来解决了吗，我试过延时加载，更新加载等，也不成

**Comment by luruxi** [comment]
> This is by no means helpful. If you want get help from the community, you should first debug by yourself and provide useful information.

http://jsfiddle.net/eywraw8t/477614/
这里是代码演示，问题主要是在苹果手机显示或者苹果电脑safari能出现，很偶尔的出现，但是一出现其他的图表都不渲染了
![image](https://user-images.githubusercontent.com/33649116/49056368-76cb7080-f236-11e8-8059-70d4859d16c0.png)

**Comment by fengfengxia** [comment]
请问你的问题解决了吗

**Comment by JonasGao** [comment]
Occasionally +1.

**Comment by luruxi** [comment]
> 请问你的问题解决了吗

没有呢

**Comment by yaoningvital** [comment]
Occasionally +1

**Comment by yaoningvital** [comment]
I have solved this problem in my project.

When I debuged my project, it would sometimes log the errors like this:
![image](https://user-images.githubusercontent.com/17041261/54177227-7ba5ee80-44cc-11e9-9aaa-f8e26799ec00.png)

From the errors tips, it significantly show that this error appeared when execute this code:
```
this.ctx.dpr = this.dpr
```
in `Layer.js` 、`Painter.js`、`zrender.js` etc.

So I detect the Layer.js file, in `node_modules\zrender\lib\Layer.js` , I saw this code in a function named 'initContext':
```
initContext: function () {
    this.ctx = this.dom.getContext('2d');
    this.ctx.dpr = this.dpr;
  },
```

I modified this function to the code below:
```
initContext: function () {
    this.ctx = this.dom.getContext('2d');
    try {
      this.ctx.dpr = this.dpr;
    } catch (e) {
      setTimeout(() => {
        location.reload()
      }, 500)
    }
  },
```
 And the bug resolved.

I think this is a iOS bug happened occasionally, when the Layer.js or other Javascript library execute the command like `this.ctx = this.dom.getContext('2d');`，the lib find `this.dom` is not found, `this.dom` here represent the HTMLCanvasElement, so `this.ctx` is `null`, so it will throw error when execute 
`this.ctx.dpr = this.dpr;`.

**Comment by luruxi** [comment]
> I have solved this problem in my project.
> 
> When I debuged my project, it would sometimes log the errors like this:
> ![image](https://user-images.githubusercontent.com/17041261/54177227-7ba5ee80-44cc-11e9-9aaa-f8e26799ec00.png)
> 
> From the errors tips, it significantly show that this error appeared when execute this code:
> 
> ```
> this.ctx.dpr = this.dpr
> ```
> 
> in `Layer.js` 、`Painter.js`、`zrender.js` etc.
> 
> So I detect the Layer.js file, in `node_modules\zrender\lib\Layer.js` , I saw this code in a function named 'initContext':
> 
> ```
> initContext: function () {
>     this.ctx = this.dom.getContext('2d');
>     this.ctx.dpr = this.dpr;
>   },
> ```
> 
> I modified this function to the code below:
> 
> ```
> initContext: function () {
>     this.ctx = this.dom.getContext('2d');
>     try {
>       this.ctx.dpr = this.dpr;
>     } catch (e) {
>       setTimeout(() => {
>         location.reload()
>       }, 500)
>     }
>   },
> ```
> 
> And the bug resolved.
> 
> I think this is a iOS bug happened occasionally, when the Layer.js or other Javascript library execute the command like `this.ctx = this.dom.getContext('2d');`，the lib find `this.dom` is not found, `this.dom` here represent the HTMLCanvasElement. It exactly is a canvas element in most time, when the iOS javascript engines display correctly, but sometimes it would not, it was not found instead. So `this.ctx` is `null`, so it will throw error when execute `this.ctx.dpr = this.dpr;`.

Thank you. I'll try

**Comment by WangSuwen** [comment]
朋友，这个问题 你解决了吗？

**Comment by QingLeiLi** [comment]
同样遇到了这个问题。
上面已经有同学提供了[demo](http://jsfiddle.net/eywraw8t/477614/)，@Ovilia 可以帮忙确认下问题吗？

**Comment by AlexJerryX** [comment]
Is anyone solve the problem yet ?

**Comment by AlexJerryX** [comment]
Change the render to svg can solve my problem
