### ISSUE TITLE
lines图画轨迹时，数据更新问题。

### ISSUE THREAD

**Issue by chaserstrong** [apache/incubator-echarts#9387]
### One-line summary [问题简述]

有这样的一个需求： 画一个模拟迁徙的图，但是和我们官方demo不同的是，demo中数据是固定的，而我这的数据是每5s轮训更新一次的。并且需要用到尾迹这种效果。 
但是现在出现的情况是，每次数据更新，setOption时，会出现尾迹断掉的问题，请问有没有办法解决？
ps： 其实其他的转场效果都做不了。

![image](https://user-images.githubusercontent.com/18061322/48350711-031c5600-e6c3-11e8-8a38-30e0ac59d72d.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新
+ Browser version [浏览器类型和版本]: 最新
+ OS Version [操作系统类型和版本]: mac air

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chaserstrong** [comment]
@pissang  求大神指教~

**Comment by cuijian-dexter** [comment]
I think you can try the `appendData` method.
http://echarts.baidu.com/api.html#echartsInstance.appendData

**Comment by chaserstrong** [comment]
> I think you can try the `appendData` method.
> http://echarts.baidu.com/api.html#echartsInstance.appendData

In fact,  the doc gives the attention: 目前并非所有的图表都支持分片加载时的增量渲染。目前支持的图有：ECharts 基础版本的 散点图（scatter） 和 线图（lines）。ECharts GL 的 散点图（scatterGL）、线图（linesGL） 和 可视化建筑群（polygons3D）。

**Comment by chaserstrong** [comment]
> 我也遇到图表更新时尾迹遗留的问题，请问你解决了嘛

not yet.

**Comment by chaserstrong** [comment]
> This is due to the implementation of the comet-tail effect. Because it needs to blend with previous frames, it is not possible to remain the previous result when set new data.

so what can i do? 😂

**Comment by duuliy** [comment]
需要跟你一样的效果，就算用appendData 只只能增加点，不能增加彗星的线，而且一样的有闪烁效果。。请问你或者是用其他的可视化方案解决的吗? @chaserstrong

**Comment by llsldwy** [comment]
@chaserstrong 请问有解决方案吗？我们这边也面临类似的问题
