### ISSUE TITLE
radar图版本升级文档缺失？

### ISSUE THREAD

**Issue by fengxianhua** [apache/incubator-echarts#9390]
### One-line summary [问题简述]

![Uploading image.png…](https://img.alicdn.com/tfs/TB1qNHmpcfpK1RjSZFOXXa6nFXa-2160-676.png)
这两个属性3.X中是在radar下的，4.X中没有axisTick和axisLabel，文档中label貌似归入了series，但是未找到axisTick

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.x
+ Browser version [浏览器类型和版本]: chrome 70.0.3538.77
+ OS Version [操作系统类型和版本]: osx

### Expected behaviour [期望结果]
完善文档。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Axis label for radar is currently not supported. See #9282 for further information.
