### ISSUE TITLE
geojson生成的地图，如何在地图上点击获取经纬度

### ISSUE THREAD

**Issue by janxy** [apache/incubator-echarts#9392]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sxmpasch** [comment]
Take as example https://ecomfe.github.io/echarts-examples/public/editor.html?c=map-usa  
and add an event handler:

以https://ecomfe.github.io/echarts-examples/public/editor.html?c=map-usa为例
并添加一个事件处理程序：

```
    myChart.on('click',function(e){
        let x=e.event.event.zrX;
        let y=e.event.event.zrY;
       console.log(myChart.convertFromPixel({seriesIndex:0},[x,y]));
    });

```
This example prints latitude and longitude on the console...
