### ISSUE TITLE
多个图例时,怎么实现双击某一图例,隐藏其他图例呢

### ISSUE THREAD

**Issue by sumaoge** [apache/incubator-echarts#9393]
### 多个图例时,怎么实现双击某一图例,隐藏其他图例呢？
+ 比如有 图例1,图例2,图例3 ， 我要的效果是 双击 “图例1" 时, 隐藏"图例2” 和"图例3"

**Comment by Ovilia** [comment]
We are considering the feature of switching all legend elements on and off. But not with double-click perhaps, since this is not a natural interaction way for users to think of.

**Comment by yf-feng** [comment]
这个echarts 上有这个实现吗？

**Comment by sumaoge** [comment]
> 这个echarts 上有这个实现吗？

可以自己实现的/. 你去看下API,可以覆盖echarts的一个事件 .

**Comment by MissFlower** [comment]
这个有实现吗
