### ISSUE TITLE
一个页面中多个Echarts的渲染速度很慢

### ISSUE THREAD

**Issue by LPink777** [apache/incubator-echarts#9398]
### One-line summary [问题简述]
  页面轮播，每个轮播页都会有3个echart图，轮播的时候每个页面有四条数据依次自动发送请求然后返回的数据加载到echart图中进行渲染。数据量每个图的数据多的话会有几千条，少的话几条，在依次发送请求的过程中，echart的渲染速度很慢如何进行优化，我有把动画关掉

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: chrome 64+
+ OS Version [操作系统类型和版本]: windows10

### Expected behaviour [期望结果]
提升echart的渲染速度

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Here are some tips that you may try with:

- Use SVG instead of Canvas
- Dispose charts in not active tabs and init it when active
- Only call setOption for active tabs rather than when request call backs

**Comment by LPink777** [comment]
@Ovilia echart如何切换成svg
