### ISSUE TITLE
echart是否有考虑支持知识图谱的各种需求

### ISSUE THREAD

**Issue by chairy11** [apache/incubator-echarts#9408]
Hi, 近期在开发知识图谱，想使用echarts中的graph，force类型，但感觉的确比较费劲，很多需要自己处理数据的地方，超过1000个点，速度很慢，使用GL版本貌似依然很卡。

不知道后续echarts有没有考虑去支持这些需求？

常用的功能，比如：

1. 点击某个节点，可展开相关的子节点。
2. 动态删减节点和边。
3. 一个节点有多个属性，可以动态设置，映射到不同visualMap，比如
    某节点:
```
{
  "id": "645138",
  "dataIndex": 3,
  "name": "银行",
  "detail": "",
  "category": 0,
  "return": -0.012490607142857144,
  "sentiment": 0.5018892857142856,
  "capital": 20.657123607604735,
  "class": 0,
  },
```
   
 可以在visualMap里动态设置，节点颜色映射到return，节点大小映射到capital。
4. 节点的过滤、边的过滤

现在我都是通过更改数据去实现这些，但可能官方有些更有针对性的配置或方法，可能更好。
比如：增删节点和边addNodes，addEdges方法。
过滤部分节点：
```
getNodes().filter(function(node) {
    return node.getData('age') > 50;
});
```

这时候，其它节点只是隐藏，而不是数据改变了。

**Comment by Ovilia** [comment]
About performance, you may refer http://echarts.baidu.com/examples/editor.html?c=graphgl-npm-dep&gl=1&theme=dark . This example has 10000+ nodes and 27000 edges, so 1000 data shouldn't be too slow.

As other features, you are very welcomed to make pull requests to support those. :)

**Comment by thWinterSun** [comment]
> Hi, 近期在开发知识图谱，想使用echarts中的graph，force类型，但感觉的确比较费劲，很多需要自己处理数据的地方，超过1000个点，速度很慢，使用GL版本貌似依然很卡。
> 
> 不知道后续echarts有没有考虑去支持这些需求？
> 
> 常用的功能，比如：
> 
> 1. 点击某个节点，可展开相关的子节点。
> 2. 动态删减节点和边。
> 3. 一个节点有多个属性，可以动态设置，映射到不同visualMap，比如
>    某节点:
> 
> ```
> {
>   "id": "645138",
>   "dataIndex": 3,
>   "name": "银行",
>   "detail": "",
>   "category": 0,
>   "return": -0.012490607142857144,
>   "sentiment": 0.5018892857142856,
>   "capital": 20.657123607604735,
>   "class": 0,
>   },
> ```
> 可以在visualMap里动态设置，节点颜色映射到return，节点大小映射到capital。
> 4. 节点的过滤、边的过滤
> 
> 现在我都是通过更改数据去实现这些，但可能官方有些更有针对性的配置或方法，可能更好。
> 比如：增删节点和边addNodes，addEdges方法。
> 过滤部分节点：
> 
> ```
> getNodes().filter(function(node) {
>     return node.getData('age') > 50;
> });
> ```
> 这时候，其它节点只是隐藏，而不是数据改变了。

你好，我也在用echarts 做知识图谱的开发，也遇到了很多问题。比如echarts 不能实现两个点之前的多条线的问题，希望能与你交流。

**Comment by thWinterSun** [comment]
我也在用echarts 做知识图谱的二次开发，遇到很多问题。比如两点将多条线的问题无法用echarts实现，希望能与你交流经验。
