### ISSUE TITLE
grid.containLabel 设置为true， 设置xAxis.axisLabel.padding图表展示异常

### ISSUE THREAD

**Issue by jingxiawl** [apache/incubator-echarts#9411]
- [ ] I am using English in this issue.

## General Questions

- [x] I have read the document and examples and tried to solve it by myself.
- [x] I have searched for similar issues and that didn't help.
- [x] I have tried with the latest version of ECharts and still have this problem.

In this issue, I have provided information with:
- [x] issue type
- [x] one sentence description in issue details
- [x] demo if this is bug report

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*
- [x] I have a bug to report
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*
- [ ] There's something wrong with the documents
- [ ] Others, or I'm not sure which issue types to choose here

## Issue Details

当我使用 grid.containLabel 设置为true的时候， 如果我同时设置了xAxis.axisLabel.padding的话图表展示异常。

### Expected Behavior

应该是坐标轴缩进防止label溢出：
![image](https://user-images.githubusercontent.com/11657532/48539533-65a76900-e8f2-11e8-8cee-4c0ddae57957.png)

### Current Behavior

图表绘制错误
![image](https://user-images.githubusercontent.com/11657532/48539578-8bcd0900-e8f2-11e8-8d18-4e849f72b6a1.png)

### Online Example

{ADD_LINK_OF_DEMO_HERE}

如果设置xAxis.axisLabel.padding，就会出现错误显示，如果关掉xAxis.axisLabel.padding设置就是对的
```javascript
option = {
	"legend": {
		"data": [{
				"name": "营业收入(亿元)",
				"icon": "circle",
				"textStyle": {
					"color": "#fff",
					"fontSize": 16
				}
			}, {
				"name": "同比",
				"icon": "circle",
				"textStyle": {
					"color": "#fff",
					"fontSize": 16
				}
			}
		],
		"left": "5%"
	},
	"grid": {
		"bottom": 50,
		containLabel: true
	},
	"xAxis": [{
			"type": "category",
			"boundaryGap": true,
			"data": ["2018\n年报", "2018\n年报", "2018\n年报", "2018\n月报}"],
			"axisTick": {
				"show": false
			},
			"axisLine": {
				"lineStyle": {
					"color": "#fff"
				}
			},
			"axisLabel": {
				"fontSize": 12,
				"borderColor": "#ddd",
				"borderWidth": 1,
				"borderRadius": 6,
				"padding": [6, 10]
			}
		}, {
			"type": "category",
			"boundaryGap": true,
			"data": ["2018\n年报", "2018\n年报", "2018\n年报", "2018\n月报}"],
			"axisLabel": {
				"show": false
			},
			"axisLine": {
				"show": false
			},
			"axisTick": {
				"show": false
			}
		}
	],
	"yAxis": [{
			"type": "value",
			"scale": true,
			"max": 361300,
			"min": 0,
			"interval": 72260,
			"splitLine": {
				"show": true,
				"lineStyle": {
					"color": "#999"
				}
			},
			"axisLabel": {
				"color": "#fff"
			},
			"axisLine": {
				"show": false
			},
			"axisTick": {
				"show": false
			},
			"boundaryGap": [0.2, 0.2]
		}, {
			"type": "value",
			"scale": true,
			"axisLabel": {
				"color": "#fff",
				"formatter": "{value}%"
			},
			"max": 30,
			"min": 0,
			"interval": 6,
			"splitLine": {
				"show": true,
				"lineStyle": {
					"color": "#999"
				}
			},
			"axisLine": {
				"show": false
			},
			"axisTick": {
				"show": false
			},
			"boundaryGap": [0.2, 0.2]
		}
	],
	"dataZoom": [{
			"type": "inside",
			"xAxisIndex": [0, 1],
			"maxValueSpan": 5,
			"startValue": 0,
			"endValue": 4,
			"zoomLock": true,
			"preventDefaultMouseMove": false
		}
	],
	"series": [{
			"name": "营业收入(亿元)",
			"type": "bar",
			"barWidth": 12,
			"data": [237025, 298048, 361299, 234646],
			"itemStyle": {
				"color": "#29D6F4",
				"shadowBlur": 6,
				"shadowColor": "rgba(0, 0, 0, 0.5)"
			},
			"label": {
				"show": true,
				"position": "top",
				"color": "#fff",
				"fontSize": 16,
				"formatter": "{c}亿"
			}
		}, {
			"name": "同比",
			"type": "line",
			"yAxisIndex": 1,
			"xAxisIndex": 1,
			"lineStyle": {
				"color": "#E7306D"
			},
			"symbol": "circle",
			"symbolSize": 10,
			"data": [16.98, 25.74, 21.22, 25.23]
		}
	]
}

```

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

{DESCRIBE_HERE}

## Environment

- ECharts version: 官网编辑器版本

- [ ] It happens only on certain browsers or operating systems. {BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by cuijian-dexter** [comment]
You can use `padding: [10, 10, 10, 10]` to solve it first.

**Comment by jingxiawl** [comment]
@cuijian-dexter  谢谢可以了
