### ISSUE TITLE
How to inverse indicator(RadiusAxes) in Radar Chart

### ISSUE THREAD

**Issue by TomasDSD** [apache/incubator-echarts#9419]
Hello Everyone, 

I have a problem with inverse RadiusAxes. There is any function/code for doing this ?
In my example, i want '市场（Marketing)' Begin at left.

Very Thanks to all.

![image](https://user-images.githubusercontent.com/39341148/48614397-73123100-e98e-11e8-99b8-cfeafaab84ed.png)

Link of radar : https://ecomfe.github.io/echarts-examples/public/editor.html?c=radar

Code :

`option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        name: {
            textStyle: {
                color: '#fff',
                backgroundColor: '#999',
                borderRadius: 3,
                padding: [3, 5]
           }
        },
        indicator: [
           { name: '销售（sales）', max: 6500},
           { name: '管理（Administration）', max: 16000},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            },
             {
                value : [5000, 14000, 28000, 31000, 42000, 21000],
                name : '实际开销（Actual Spending）'
            }
        ]
    }]
};`

**Comment by TomasDSD** [comment]
Maybe impossible ?

**Comment by SchnWalter** [comment]
You just need to set add `startAngle: 60` (as in 360/6 data point) to your `radius: {}` options, next to the `indicator` array.

**Comment by TomasDSD** [comment]
I mean i want, left To right starting trop botom : sales, marketing, development, customer, information and

**Comment by loperia2** [comment]
Any progress on this?
