### ISSUE TITLE
广东省地图

### ISSUE THREAD

**Issue by mofengfs** [apache/incubator-echarts#9420]
同样的代码, 内蒙古地图可以正常显示, 但是我将name='内蒙古'换成name='广东', 将data的数据换成广东各地市的数据,也引入了province中的guangdong.js文件, 然而并没有把图渲染出来,  其他一切正常, 也没有报错.

**Comment by Ovilia** [comment]
The name in `echarts.registerMap('guangdong', geoJson);` should be the same with that in guangdong.js file. Please check the name in guangdong.js file.
