### ISSUE TITLE
大数据量下特效散点图动态更新闪烁

### ISSUE THREAD

**Issue by inioo** [apache/incubator-echarts#9423]
散点图会动态更新当前最活跃的点添加涟漪效果，
setOption(option, true)覆盖之前的涟漪效果.
更新之后所有散点都会重绘. 导致散点会出现闪烁的情况.
查文档没找到可用的参数.
大数据量的情况下怎么避免重绘

**Comment by Ovilia** [comment]
Duplicate of #9387 https://github.com/apache/incubator-echarts/issues/9387#issuecomment-438594371
