### ISSUE TITLE
Chart Color change error when drag datazoom

### ISSUE THREAD

**Issue by shikelong** [apache/incubator-echarts#9431]
Please see the gif.

![echarts](https://user-images.githubusercontent.com/4499997/48750871-bd641c80-ecc4-11e8-81fd-0da6b9063a37.gif)

How to fix it? Thanks.

**Comment by deqingli** [comment]
Hi, Please provide a detailed demo address for us to debug, and please describe the problem and the results you want, which I can't see from the picture. Thank you
