### ISSUE TITLE
echarts+bmap 用svg模式渲染出来的散点图移动地图是位置会偏移

### ISSUE THREAD

**Issue by luozejian** [apache/incubator-echarts#9432]
One-line summary [问题简述]
散点图在当拖动地图移动时，位置不会随着移动,换成canvas模式就不会有这种问题

Version & Environment [版本及环境]
bmap   version [百度地图 版本]:3.0
ECharts version [ECharts 版本]:
Browser version [浏览器类型和版本]:版本 69.0.3497.100（正式版本） （64 位）
OS Version [操作系统类型和版本]:win10
Expected behaviour [期望结果]
地图上的散点随着地图拖动而动,固定在坐标上
ECharts option [ECharts配置项]
option = {

}
Other comments [其他信息]

**Comment by Ovilia** [comment]
无法复现，请提供例子？
