### ISSUE TITLE
Echarts数据和配置分离

### ISSUE THREAD

**Issue by darrenywyu** [apache/incubator-echarts#9433]
1.同一个chart，要为每一个series指定type

对于数据是从接口获取来的情况下，这种必须要处理数据，而不是说可以指定一个统一的type，series的值直接取数据data赋值。

2. markLine和markArea要在series中配置

本身series的数据是需要从接口中获取的，而且同时可能会获得多个seriese，这时候如果想要为趋势图设置一条阈值线，必须在拿到数据之后对数据进行多种判断处理，但其实像阈值线是只和坐标轴相关的，如果能在坐标轴上设置，直接可以在配置中固定，不需要对数据处理

3.dataset还是要一一对应series
如果我数据源数据条数是不固定的情况下，没办法直接固定series的配置，还是需要根据数据改变series，同时series的的配置没办法共享，必须要一个一个配置

**Comment by deqingli** [comment]
我来说一下自己的一些拙见：
+ 从数据可视化层面来说，你的图表是由你的数据驱动的，同一份数据，每一个用户想要呈现的数据信息不同，可能有的用户只是想看一些数据中的关键指标的变化，那么处理数据得到这些关键指标直接绘个简单的柱状图就 ok 了。然而其他的用户可能想看数据的内在关系，那么他就得把数据处理成关系型数据，然后选择一些关系型的可视化图表进行呈现，希望呈现什么样的数据信息的自主权是由用户把控的。
+ 坐标轴也是由数据决定的。
+ 可以将一些通用的配置抽离出来，其他地方引用就行了。
