### ISSUE TITLE
移动端 CSS transform 后点击位置的 bug

### ISSUE THREAD

**Issue by cn-xufei** [apache/incubator-echarts#9434]
- [ ] I am using English in this issue.

## General Questions

- [ ] I have read the document and examples and tried to solve it by myself.
- [ ] I have searched for similar issues and that didn't help.
- [ ] I have tried with the latest version of ECharts and still have this problem.

In this issue, I have provided information with:
- [ ] issue type
- [ ] one sentence description in issue details
- [x] demo if this is bug report

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*
- [x] I have a bug to report
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*
- [ ] There's something wrong with the documents
- [ ] Others, or I'm not sure which issue types to choose here

## Issue Details

echarts在移动端，当父容器使用了css的transform属性，比如rotate，scale等属性，图表上的点击和显示tooltip交互产生了偏移，迫切的希望能解决此问题，这个问题会阻碍echarts在移动端的发展。

### Expected Behavior

{DESCRIBE_HERE}

### Current Behavior

![image](https://user-images.githubusercontent.com/14144811/48756168-fc996a00-ecd2-11e8-80f4-ed512162b5a5.png)

**Comment by cn-xufei** [comment]
你好，这个问题请问如何解决可以指点一下吗？这个问题影响很严重

**Comment by cn-xufei** [comment]
antv-f2

**Comment by cn-xufei** [comment]
请重视一些移动端吧

**Comment by cn-xufei** [comment]
echarts: 4.2.0-rc.2

**Comment by cn-xufei** [comment]
这个问题翻下issues，存在很久了

**Comment by cn-xufei** [comment]
各位辛苦了:rose:
啥时候官宣解决次问题？
有没有计划可以分享下
等着fix拯救世界:muscle:

**Comment by cn-xufei** [comment]
@100pah 打扰了

**Comment by cn-xufei** [comment]
这个问题有计划修复吗？ @Ovilia @deqingli @100pah @kant

**Comment by cn-xufei** [comment]
非常期待echarts团队能够修复此问题

**Comment by cn-xufei** [comment]
@100pah 
你好，请问这个问题可以临时通过什么方法解决吗？

**Comment by Ovilia** [comment]
@cn-xufei 这个问题 @100pah 在跟进了，会尽快解决一下的。
