### ISSUE TITLE
line series animation to follow axis direction

### ISSUE THREAD

**Issue by MohammadYounes** [apache/incubator-echarts#9439]
- [x] I am using English in this issue. 

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself.
- [x] Required: I have searched for similar issues and that didn't help.
- [x] Required: I have tried with the latest version of ECharts and still have this problem.

In this issue, I have provided information with: 
- [x] Required: issue type
- [x] Required: one sentence description in issue details
- [x] Required: demo
- [x] Required: ECharts version

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*
- [ ] I have a bug to report
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*
- [ ] There's something wrong with the documents
- [ ] Others, or I'm not sure which issue types to choose here

## Issue Details

Line chart animation starts from left even when the axis is inverted.

### Expected Behavior

Line animation to start from right, according to axis direction.

### Current Behavior

![echarts](https://user-images.githubusercontent.com/4712046/48790510-2e70f780-ecf8-11e8-84b8-6de6da757e74.gif)

### Online Example

https://jsfiddle.net/o4j0hkwL/

```js
// based on prepared DOM, initialize echarts instance
var myChart = echarts.init(document.getElementById('main'));

// specify chart configuration item and data
var option = {
	title: {
    	text: "Echarts v" + echarts.version,
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        inverse:true,
    },
    yAxis: {
        type: 'value',
        position:'right'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};

// use configuration item and data specified to show chart
myChart.setOption(option);
```

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

 N/A

## Environment

- ECharts version: v4.2.0
- [ ] It happens only on certain browsers or operating systems.

**Comment by cuijian-dexter** [comment]
#9322    Repeat with this question.

**Comment by deqingli** [comment]
Because this issue is repeated with #9322, I have to turn this off and follow up under that, hope you understand.
