### ISSUE TITLE
> 这个问题麻烦@Ovilia看一下吧

### ISSUE THREAD

**Issue by 972688893** [apache/incubator-echarts#9446]
多谢 麻烦帮我确认一下 是我应用的问题 还是应用时确实存在这样的问题，我在查阅资料时看到有挺多人遇到了这样的问题

_Originally posted by @972688893 in https://github.com/apache/incubator-echarts/issues/9359#issuecomment-437261488_

**Comment by Ovilia** [comment]
在原问题下跟进，抱歉答复有点晚。

**Comment by 972688893** [comment]
> 抱歉回复晚了。关闭并按照原点问题。我这个星期会检查一下。

嗯呐
