### ISSUE TITLE
echarts折线图显示不规则问题

### ISSUE THREAD

**Issue by nielei19920921** [apache/incubator-echarts#9454]
![nx j58xc lw2y3 zcnb](https://user-images.githubusercontent.com/27334643/48888075-76189000-ee6c-11e8-96c5-23dabe971263.png)

两个点之间没有数据 后一个点不连接前一个点 而是直接一根竖线连接横坐标再连接前一个点

**Comment by deqingli** [comment]
Please provide the demo link, we need to know the content of echarts `option`, for us to debug.
