### ISSUE TITLE
暂时解决由于数据量大导致页面卡顿问题，希望官方可以优化一下

### ISSUE THREAD

**Issue by wangfeiixang** [apache/incubator-echarts#9457]
**One-line summary [问题简述]**
解决过程就不说了，说一下解决方案。
（1）通过npm包引入echarts，需要修改node_modules/echarts/lib/chart/helper/SymbolDraw.js
  将symbolDrawProto.updateData方法里内容注释即可
（2）下载echarts.js源码文件，也是将symbolDrawProto.updateData方法里内容注释即可
结果页面会流畅很多，和highcharts数据多时效果差不多
**Version & Environment [版本及环境]**
ECharts version [ECharts 版本]:  4.1.0
Browser version [浏览器类型和版本]:  chrome 
OS Version [操作系统类型和版本]: windows 10
**Expected behaviour [期望结果]**
希望官方可以给出更优方法

**Comment by wangfeiixang** [comment]
**Additional explanation [补充说明]**
`echarts config:`
```
xAxis{
  type: 'time'
}
```
用的是时间轴折线图

**Comment by JedidiahY** [comment]
https://www.echartsjs.com/zh/api.html#echartsInstance.appendData正在研究这个，只是这个增量渲染技术，应该也是有限制的

**Comment by pissang** [comment]
这个可以通过设置 showSymbol: false  解决

**Comment by zhixinJ** [comment]
> 这可以通过设置 showSymbol: false 解决
但是这个只在type： line有效，type：time是无效的

**Comment by wangfeiixang** [comment]
多谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 暂时解决由于数据量大导致页面卡顿问题，希望官方可以优化一下 (#9457)





  
这可以通过设置 showSymbol: false 解决
 但是这个只在type： line有效，type：time是无效的
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
