### ISSUE TITLE
Hope to perfect the model!希望能改进表格的显示

### ISSUE THREAD

**Issue by WytheO** [apache/incubator-echarts#9475]
## General Questions

PLEASE MAKE SURE OF ALL THE FOLLOWING OPTIONS IN REQUIRED FIELDS ARE TICKED (with x)!
Otherwise, the issue will not be answered.
And think before you tick. :)
请确保以下每项都打上勾了！并且确保都做了这些事哦~ 这将大量简化我们的工作流程，使你的问题更快速得到解答。

- [x ] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I am using the latest version of Echarts and V-Charts. （必填）我正在用最近的echarts和v-charts

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

A lot of user feedback said, look at this effect is very uncomfortable!
很多用户反馈说，看着这个效果非常的难受！
![image](https://user-images.githubusercontent.com/38578631/49067291-a1c9ba80-f25e-11e8-8c0b-c7257e8172bf.png)

in using！
![image](https://user-images.githubusercontent.com/38578631/49067341-c6be2d80-f25e-11e8-9d48-89d2d4b3bf27.png)

### Expected Behavior

I hope that the numbers are would't be cover up!
我希望这些数字不会被掩盖
to see [yours](https://v-charts.js.org/#/bar)
like this:

![image](https://user-images.githubusercontent.com/38578631/49067682-afcc0b00-f25f-11e8-9c9c-b1eb313b8f54.png)

Soft environment：Chrome V8 & electron
谷歌V8环境和Electron窗体程序
## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [x] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

{DESCRIBE_HERE}

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
All latest version！
- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by sxmpasch** [comment]
This is V-Charts. Just add a grid with a proper margin to the chart:
只需在图表中添加一个具有适当边距的网格即可

```
<div id="app">
  <ve-bar :data="chartData" :grid="grid" :settings="chartSettings"></ve-bar>
</div>

```
and
```
new Vue({
  el: '#app',
  data () {
    this.chartSettings =  {
      legendName: {
        'cost': 'costmoney'
      }
    }
    this.grid = {
        show: true,
        top: 50,
        left: 10,
        right: 30,
    }    
    return {
      chartData: {
        columns: ['date', 'cost', 'profit'],
        rows: [
          { 'date': '01/01', 'cost': 123, 'profit': 300 },
          { 'date': '01/02', 'cost': 1223, 'profit': 600 },
          { 'date': '01/03', 'cost': 2123, 'profit': 9000 },
          { 'date': '01/04', 'cost': 4123, 'profit': 1200 },
          { 'date': '01/05', 'cost': 3123, 'profit': 1500 },
          { 'date': '01/06', 'cost': 7123, 'profit': 2000 }
        ]
      }
    }
  }
})

```

**Comment by WytheO** [comment]
先谢谢您能快速的回复我！

The  demo has great simple code but not useful enuogh!But the really useful code is hidden in complex API documentation and configuration document!
简介里的代码过于简洁，那只是为了引入，但是那里有图例，应该把一些重要的配置项特别是通用的配置项用例子展示出来。这些真正有用的配置项却藏在复杂的文档里，文档却没有足够的分类选项用于筛选。demo前后仅靠两张表格告诉开发者有些什么配置项是不够的。

I hope that some of the advanced configuration items for diagrams should be shown in the demo rather than going through the documentation！
我希望对于图表的一些高级配置项应该在demo里就展示出来，而不是另外去翻文档。

如果可以，我愿意举一个例子！

**Comment by WytheO** [comment]
作为每一个图表都有的提示框和图表内容样式控制应该作为基本demo代码在示例里展示出来！
