### ISSUE TITLE
Whether echarts can listen to the event when the points be snapped

### ISSUE THREAD

**Issue by heartAndRain** [apache/incubator-echarts#9478]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

PLEASE MAKE SURE OF ALL THE FOLLOWING OPTIONS IN REQUIRED FIELDS ARE TICKED (with x)!
Otherwise, the issue will not be answered.
And think before you tick. :)
请确保以下每项都打上勾了！并且确保都做了这些事哦~ 这将大量简化我们的工作流程，使你的问题更快速得到解答。

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Whether echarts can listen to the event when the points be snapped, just like the gif below

![example](https://raw.githubusercontent.com/heartAndRain/static/master/echarts-issue-example.gif)

### Expected Behavior

A callback should be provided

### Current Behavior

I can not find some information about this in the document

### Online Example

THIS IS REQUIRED FOR ALL BUG REPORTS AND QUESTIONS!!! 如果是提问或报 bug 一定要提供这一项！

http://www.echartsjs.com/examples/editor.html?c=line-stack

## Topics

- [ ] Legend
- [ ] Tooltip
- [x] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: 3.7.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by cuijian-dexter** [comment]
@heartAndRain 
What events do you need?
What is the trigger mode?

**Comment by 100pah** [comment]
There is a event "updateAxisPointer".

```js
chart.on('updateAxisPointer', function (e) { ... });
```

**Comment by heartAndRain** [comment]
> There is a event "updateAxisPointer".
> 
> ```js
> chart.on('updateAxisPointer', function (e) { ... });
> ```

Thanks, this solved my problem. But why can't I find a description about it in the official documentation?

**Comment by leij1ang** [comment]
更新文档还是积极点好
虽然麻烦，但是值得。。。。
”updateAxisPointer“这个事件要是不看实例，还真不知道有这个
