### ISSUE TITLE
RadiusAxis doesn't show categories which actually fit.

### ISSUE THREAD

**Issue by ivanpadavan** [apache/incubator-echarts#9481]
- [x] I have a bug to report；我想要报 bug

## Issue Details

`RadiusAxis` of `category` type doesn't handle categoryLabels properly.

If paste this configuration
 ```
option = {
    angleAxis: {
    },
    radiusAxis: {
        type: 'category',
        data: ['Long sentence 1', 'Long sentence 2', 'Long sentence 3', 'Long sentence 4'],
        z: 10
    },
    polar: {
    },
    series: [{
        type: 'bar',
        data: [1, 2, 3, 4],
        coordinateSystem: 'polar',
        name: 'A',
        stack: 'a'
    }]
};
```
[here](https://ecomfe.github.io/echarts-examples/public/editor.html), you can see that category labels are cropped while there are enough space.

### Expected Behavior
Labels should be rendered as there are enough space.
### Current Behavior
Could be seen with info provided under issue details heading.
## Anything Else We Need to Know
This could be fixed by adding
```
  getRotate: () => 90,
```
to the [RadiusAxis class](https://github.com/apache/incubator-echarts/blob/master/src/coord/polar/RadiusAxis.js)

## Environment
- ECharts version；4.2.0rc-2

**Comment by sxmpasch** [comment]
Add the following to the radiusAxis:
```
       axisLabel: {
           interval:0
       }

```

**Comment by 100pah** [comment]
Just as @sxmpasch said:

```js
option = {
    angleAxis: {
    },
    radiusAxis: {
        type: 'category',
        axisLabel: {
           interval:0
        },
        data: ['Long sentence 1', 'Long sentence 2', 'Long sentence 3', 'Long sentence 4'],
        z: 10
    },
    polar: {
    },
    series: [{
        type: 'bar',
        data: [1, 2, 3, 4],
        coordinateSystem: 'polar',
        name: 'A',
        stack: 'a'
    }]
};
```

**Comment by ivanpadavan** [comment]
@100pah
