### ISSUE TITLE
配置文档错误

### ISSUE THREAD

**Issue by lolysc** [apache/incubator-echarts#9498]
官方文档错误：4.0的timeline.controlStyle.borderWidth说明文档多了一层borderWidth，这是错误的。已经测试过，不需要borderWidth下面再来一层borderWidth，直接赋值就好。
![image](https://user-images.githubusercontent.com/29295710/49216558-5e11b500-f406-11e8-904a-7d0ecd544c62.png)

**Comment by 100pah** [comment]
Fixed on ecomfe/echarts-doc@68d435b
