### ISSUE TITLE
line->tooltip 鼠标放上面5s左右就消失了

### ISSUE THREAD

**Issue by mqliutie** [apache/incubator-echarts#9499]
具体发生问题情况看下面的动图

![untitled](https://user-images.githubusercontent.com/11795518/49272817-d4b5bd80-f4ad-11e8-8b91-1fb76c2b6298.gif)

当时柱状图时不会出现这问题, 如下动图

![untitled](https://user-images.githubusercontent.com/11795518/49272870-029b0200-f4ae-11e8-8df6-3908306a8974.gif)

**Comment by 100pah** [comment]
Is the chart being refreshed repeatly? (for example, chart.setOption() is being called repeatly)
What is the version of echarts?
And could I have the runnable `option`?

**Comment by mqliutie** [comment]
@100pah Thanks for reminding, **line** chart will be reset option in 5s by http request. close!
