### ISSUE TITLE
Echarts 2.0 版本如何让地图上默认就显示数值或自定义的图片，而不是鼠标移动才会弹出tooltip？

### ISSUE THREAD

**Issue by showerying** [apache/incubator-echarts#9505]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

PLEASE MAKE SURE OF ALL THE FOLLOWING OPTIONS IN REQUIRED FIELDS ARE TICKED (with x)!
Otherwise, the issue will not be answered.
And think before you tick. :)
请确保以下每项都打上勾了！并且确保都做了这些事哦~ 这将大量简化我们的工作流程，使你的问题更快速得到解答。

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [ ] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

如何在Echarts2中实现地图上每个省会默认就显示图片及文字，而不是通过鼠标移动触发tooltip单个显示。
How to show image and text by default in every capital city, rather than moving the mouse to activate a single tooltip.

### Expected Behavior

我想实现那种像图针钉在一点的效果，上面显示具体的数值
Need a pin-like images pointed to a city and shows detailed data.

### Current Behavior

只能通过label在点四周显示文字，不直观。
Only show plain text with label

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [x] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

**Comment by 100pah** [comment]
It might be difficult to implement it in ECharts 2.0.

But in ECharts 3/4, you can implement it by `scatter` series and `geo` coordinate system.

**Comment by showerying** [comment]
参考gallery，用了 scatter 和 geo 解决。
