### ISSUE TITLE
magic

### ISSUE THREAD

**Issue by kenghuo** [apache/incubator-echarts#9515]

**Comment by kenghuo** [comment]
这个 toolbox 中的 magicType 可以在渲染完成默认激活其中一个吗?

**Comment by kenghuo** [comment]
![likethis](https://user-images.githubusercontent.com/35257133/49363665-45aedc80-f71d-11e8-9c51-d9c145ed1972.png)

**Comment by cuijian-dexter** [comment]
http://echarts.baidu.com/api.html#events.magictypechanged

**Comment by kenghuo** [comment]
@cuijian-dexter 这个应该怎么使用 我看这个是切换触发事件用的，我希望的效果是手动触发点击事件。

**Comment by cuijian-dexter** [comment]
@kenghuo http://echarts.baidu.com/api.html#echartsInstance.dispatchAction

**Comment by kenghuo** [comment]
this.chart.dispatchAction({
	type: 'magictypechanged',
	currentType: 'line'
});
这样用吗？

**Comment by cuijian-dexter** [comment]
@kenghuo  是的，但是貌似不起作用了

**Comment by kenghuo** [comment]
@cuijian-dexter 大佬，还有没有其他办法？

**Comment by kenghuo** [comment]
let option = Object.getOwnPropertyNames(chart._componentsMap) ;

/* 获取图表中 magicType 模拟line 点击 */
option.map(item => {
	item.includes('toolbox') && 
        chart._componentsMap[item]._features['magicType'].model.iconPaths.line.trigger('click');
 });

可以实现效果

**Comment by Nekosandesu** [comment]
> 
> 
> let option = Object.getOwnPropertyNames(chart._componentsMap) ;
> 
> /* 获取图表中 magicType 模拟line 点击 */
> option.map(item => {
> item.includes('toolbox') &&
> chart._componentsMap[item]._features['magicType'].model.iconPaths.line.trigger('click');
> });
> 
> 可以实现效果

大佬，试了图标倒是亮了，但是图表还是没切换过来呀呜呜呜

**Comment by sunny-cmm** [comment]
@kenghuo 请问有清空magicType选中的逻辑吗？我想实现，线性，柱状，堆叠（固定柱状堆叠）为一组单选项，发现选中堆叠后，无法清空线性或柱状的选中状态
