### ISSUE TITLE
Legend Values Must be Series Names

### ISSUE THREAD

**Issue by jfarrin1** [apache/incubator-echarts#9518]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

PLEASE MAKE SURE OF ALL THE FOLLOWING OPTIONS IN REQUIRED FIELDS ARE TICKED (with x)!
Otherwise, the issue will not be answered.
And think before you tick. :)
请确保以下每项都打上勾了！并且确保都做了这些事哦~ 这将大量简化我们的工作流程，使你的问题更快速得到解答。

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

I would like to define a custom legend, but `setOptions.legend.data` can **only** contain `series.name` values (most charts) or `series.data[i].name` (pie/funnel charts).

### Expected Behavior

I have a multi-series graph where I want a legend that includes all `data.name` values from each series. In the demo example, I want a legend that shows: Germany, England, and France with the corresponding color.

![image](https://user-images.githubusercontent.com/16660267/49381870-39bf1c80-f715-11e8-8328-86de23f63d95.png)

### Current Behavior

Currently, the legend values of a non-pie like chart can **only** come from the `series.name` and cannot be set to the `series.data.name` values. If the values in `legend.data` do not mach a `series.name` value, then no legend is displayed (as shown in demo).

I assume this is an issue because of how the legend interacts with the series - like how clicking on a legend name can toggle displaying of that series.

### Online Example

THIS IS REQUIRED FOR ALL BUG REPORTS AND QUESTIONS!!! 如果是提问或报 bug 一定要提供这一项！

http://gallery.echartsjs.com/editor.html?c=xLFLb0Uw7O&v=3

```
option = {
    title: {
        text: 'Top 2 Countries by Category (fake data)'
    },
    legend: {
        data: ['Germany', 'England', 'France']
    },
    color: ['green', 'pink', 'blue'],
    xAxis: {
        data: ['Healthcare', 'Crime', 'GDP']
    },
    yAxis: {},
    series: [{
        name: "Countries1",
        type: 'bar',
        label:{
          show: true,
          formatter: '{b}'
        },
        data:[{value: 220, name: 'Germany', itemStyle:{color: 'green'}}, {value: 258, name: 'England', itemStyle:{color: 'pink'}}, {value: 211, name: 'Germany', itemStyle:{color: 'green'}}]
    },
    {
        name: "Countries2",
        type: 'bar',
        label:{
          show: true,
          formatter: '{b}'
        },
        data:[{value: 120, name: 'England', itemStyle:{color: 'pink'}}, {value: 158, name: 'France', itemStyle:{color: 'blue'}}, {value: 111, name: 'France', itemStyle:{color: 'blue'}}]
    }]
};
```

## Topics

- [x] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

N/A

## Environment

- ECharts version；ECharts 版本: 4.2.0

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by jfarrin1** [comment]
> You can try `legend.formatter` to display any text you want. But the data in legend must be same with `series.name` so they can be connected properly

Using the formatter still only passes the `series.name` value, there is no way to access the `data[i].name` values. There must also only be 1 legend label per series - of course that makes sense for the default functionality, but then there is no way to have more labels than series. I don't need the legend labels to be connected toggle a series on/off or have any functionality on click. I just need a custom legend that can be whatever array of names I want. As I understand, this is not possible at the moment.

**Comment by Ovilia** [comment]
You may add a series that doesn't contain data, but only to show legend.

**Comment by atealxt** [comment]
> You may add a series that doesn't contain data, but only to show legend.

This is interesting and tricky, should mention in docs or support natively.
