### ISSUE TITLE
http://echarts.baidu.com/api.html#action.highlight

### ISSUE THREAD

**Issue by JudySu31** [apache/incubator-echarts#9519]
`seriesIndex` and `dataIndex` can set to `Array` type
```
myChart.dispatchAction({
    type: 'highlight',
    seriesIndex: [0],
    dataIndex: [0,1]
})
```

_Originally posted by @cuijian-dexter in https://github.com/apache/incubator-echarts/issues/9514#issuecomment-443691483_

dataIndex can not set to array

**Comment by cuijian-dexter** [comment]
This is the same question.It is recommended not to ask multiple identical questions.Thanks
