### ISSUE TITLE
如何把图表中文字大小使用rem控制

### ISSUE THREAD

**Issue by xuehuayous** [apache/incubator-echarts#9525]
项目要用在4K高清大屏上展示，图表可以自适应，但是文字特小。请问，有没有什么方法能统一把单位从px改成rem ？

**Comment by pissang** [comment]
目前不支持 rem 字体，可以在设置的时候根据分辨率设置文本的字体

**Comment by pjar** [comment]
Would be a nice feature. It's possible to use percentages. We use that for label, the disadvantage is that the font family will be reset to default one as the generated this way text styles look like this:
```style="font: 80% px sans-serif;"```

One trick here would be add your desired font named as `px` :)

**Comment by little-sean** [comment]
how to use this trick, could you give code example, I tried like below,but it didnt work
```js
label: {
         fontSize: '150%',
         fontFamily: 'px  :) Simsun',
 }
```
```js
label: {
        fontSize: '150%',
        fontFamily: 'px  Simsun',
}
```

**Comment by zhoufanglu** [comment]
2021年了，这个功能有支持了吗？

**Comment by plainheart** [comment]
@zhoufanglu Using `rem` unit in font size has been supported since v5.

**Comment by zhoufanglu** [comment]
> @zhoufanglu Using `rem` unit in font size has been supported since v5.

4.9支持吗？我现在用的是4.9..

**Comment by plainheart** [comment]
@zhoufanglu I'm afraid no. It's a new feature brought in ECharts 5. Refer to ecomfe/zrender#612 for more details.

**Comment by zhoufanglu** [comment]
> @zhoufanglu I'm afraid no. It's a new feature brought in ECharts 5. Refer to [ecomfe/zrender#612](https://github.com/ecomfe/zrender/pull/612) for more details.

好的 谢谢大佬的回答
