### ISSUE TITLE
echarts监听中如何调用vue方法？

### ISSUE THREAD

**Issue by XiaoNode** [apache/incubator-echarts#9528]
`export default {
  name: "rejectratio",
  data() {
    return {
      monthData: {
        title: { text: "Production line annual reject rate", x: "center" },
        xAxis: {
          data: ["1月", "2月", "3月", "4月"]
        },
        series: [
          {
            name: "Production line annual reject rate",
            type: "bar",
            data: ["1", "2", "3", "2"],
            barWidth: "70%",
            animationDelay: function(idx) {
              return idx * 100;
            }
          }
        ]
      },
      MMcur: -1,
    };
  },
  mounted() {
    this.drawMonth()
  },
  methods: {
    drawMonth() {
      let myChart = this.$echarts.init(document.getElementById("MM"));
      myChart.setOption(this.monthData);

      myChart.on("click", function(params) {  
         // echarts中如何调用vue方法funTest?
      });
    },
    funTest() {
      console.log("this is test msg")
    }
  }
};`
新手问，vue项目中使用了echarts，如何在echarts监听中调用其他vue方法或者变量？

**Comment by ManjusakaGF** [comment]
this.funTest()

**Comment by XiaoNode** [comment]
这....
`      myChart.on("click", function(params) {
        this.funTest();
})`
提示：this.funTest is not a function...

**Comment by XiaoNode** [comment]
opp,犯错了，已经解决了，谢谢
