### ISSUE TITLE
散点图根据ajax异步数据同时动态显示多个tooltip

### ISSUE THREAD

**Issue by ManjusakaGF** [apache/incubator-echarts#9529]
散点图根据不同颜色来显示类型，现在需求是某几种类型的散点根据ajax异步数据同时动态显示多个tooltip，尝试配置dispatchAction只能显示一个，配置多个会覆盖！
希望的效果如下图：
![image](https://user-images.githubusercontent.com/23520373/49499969-7bcd9700-f8aa-11e8-99be-0c2b72a13e47.png)

现在的效果如下图：
![image](https://user-images.githubusercontent.com/23520373/49499901-488b0800-f8aa-11e8-80e4-44faf2f40d9d.png)

**Comment by Ovilia** [comment]
Try mark points?

**Comment by ManjusakaGF** [comment]
Thank you! I think I know how to do it.
