### ISSUE TITLE
echart4.0 graph 使用focusNodeAdjacency 能否显示到跟节点，不只是邻进的

### ISSUE THREAD

**Issue by xj785292159** [apache/incubator-echarts#9542]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [ ] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [ ] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [ ] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [ ] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by xj785292159** [comment]
echart4.0 graph开始focusNodeAdjacency，能否显示到跟节点，现在显示的是邻进的

**Comment by Ovilia** [comment]
No. It is supposed to focus adjacent nodes, rather than ascentors.

**Comment by Mying666** [comment]
今天也碰到这种需求了，官方考虑开发一下没

**Comment by xj785292159** [comment]
> 今天也碰到这种需求了，官方考虑开发一下没

我自己改了源码，你可以试下

**Comment by Mying666** [comment]
@xj785292159 改动大吗？pr一下呗

**Comment by xj785292159** [comment]
> @xj785292159 改动大吗？pr一下呗

看源码 找focusNodeAdjacency相关内容 更改其方法，主要t是target，source，node的关系

**Comment by ilovepumpkin** [comment]
同求！希望能reopen这个issue, 这个需求感觉还挺普遍的。

**Comment by zyjgit** [comment]
能否把修改的源码借鉴一下

**Comment by zyjgit** [comment]
能否把修改的源码借鉴一下

**Comment by guolimeng** [comment]
能否把修改的源码借鉴一下

**Comment by guolimeng** [comment]
能否把修改的源码借鉴一下
