### ISSUE TITLE
dataset 第一列是数字时，饼状图显示错误

### ISSUE THREAD

**Issue by Cyycl** [apache/incubator-echarts#9545]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

dataset 有两列，第一列全是数字时，饼状图会将第一列既当成维度，也当成指标

### Expected Behavior

dataset 有两列，即使第一列全是数字，饼状图将第一列作为维度，第二列作为指标

### Current Behavior

dataset 有两列，第一列全是数字时，饼状图会将第一列既当成维度，也当成指标

### Online Example

https://codepen.io/AliJser/pen/EOqYQj

```
var option = {
  legend: {},
  tooltip: {},
  dataset: {
    source: [
      ["时间（分钟）", "数量"],
      ["10", "51141"],
      ["40", "23130"],
      ["220", "4803"],
      ["500", "1282"],
      ["575", "931"],
      ["665", "674"],
      ["825", "440"],
      ["1375", "21"],
      ["1435", "18"],
      ["1145", "8"]
    ]
  },
  series: [{
    type: 'pie',
  }]
};
```

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
v4.1.0

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by cuijian-dexter** [comment]
this is a bug.you can set `tooltip.formatter` first

**Comment by Ovilia** [comment]
This is not a bug. Please use it in this way:
```js
var option = {
  legend: {},
  tooltip: {},
  dataset: {
    source: [
      ["时间（分钟）", "数量"],
      ["10", "51141"],
      ["40", "23130"],
      ["220", "4803"],
      ["500", "1282"],
      ["575", "931"],
      ["665", "674"],
      ["825", "440"],
      ["1375", "21"],
      ["1435", "18"],
      ["1145", "8"]
    ]
  },
  series: [{
    type: 'pie',
    encode: {
        value: '数量'
    }
  }]
};
```

**Comment by jiangyh1024** [comment]
@Ovilia 
![image](https://user-images.githubusercontent.com/34930870/66907016-3be34e80-f03b-11e9-8bb9-049676689ffa.png)

there isn't a 'encode' property on pie series

**Comment by jiangyh1024** [comment]
不用dataset 直接用series的 data赋值 就不会有这个问题

**Comment by Ovilia** [comment]
Set [`sourceHeader`](https://echarts.apache.org/zh/option.html#dataset.sourceHeader) to be `false`.

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/67077327-a625fb80-f1c1-11e9-85a8-ff421ac1bb78.png)

```
option = {
    legend: {},
    tooltip: {},
    dataset: {
        dimension: ['product', 'count'],
        source: [
            { name: '123', count: 2 },
            { name: '355', count: 2 },
            { name: 'prsd', count: 2 }
        ],
        sourceHeader: false
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'pie'},
    ]
};
```

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/67077380-c48bf700-f1c1-11e9-83e9-7ddd21700ddd.png)
```
option = {
    legend: {},
    tooltip: {},
    dataset: {
        dimension: ['product', 'count'],
        source: [
            { product: '123', count: 2 },
            { product: '355', count: 2 },
            { product: 'prsd', count: 2 }
        ],
        sourceHeader: false
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'pie'},
    ]
};
```
