### ISSUE TITLE
echarts下载的时候添加水印

### ISSUE THREAD

**Issue by panda403** [apache/incubator-echarts#9548]
echarts作图，想显示的时候没有水印，但是下载的时候添加水印，如何实现

**Comment by Ovilia** [comment]
1. Add a custom toolbox feature http://echarts.baidu.com/option.html#toolbox.feature
2. In `onclick`, [get canvas in the form of base64](http://echarts.baidu.com/api.html#echartsInstance.getDataURL)
3. Create a new canvas and use `drawImage` to draw watermark onto the original chart
4. [Export canvas](https://stackoverflow.com/questions/10673122/how-to-save-canvas-as-an-image-with-canvas-todataurl)
