### ISSUE TITLE
地图map图层放大后，EffectScatter图层坐标不能适配；map图层的tooltip在鼠标靠近右侧边缘时被地图遮挡

### ISSUE THREAD

**Issue by authasme** [apache/incubator-echarts#9549]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [ ] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [ ] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [ ] Required: issue type；（必填）issue 类型
- [ ] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

### Expected Behavior

1.地图map图层缩放，经纬度位置跟所缩放，使EffectScatter图层坐标可以自动跟随。
2.鼠标放在map图层，地图区域不会遮挡tooltip内容。

### Current Behavior

map zoom=1  aspectScale=0.75 时陕西省地图的坐标位置基本正常
![qq 20181207102124](https://user-images.githubusercontent.com/22970441/49623746-dd584780-fa09-11e8-9465-65affb6178b2.jpg)

map zoom=1 aspectScale=1.2时
![qq 20181207100146](https://user-images.githubusercontent.com/22970441/49624131-4096a980-fa0b-11e8-80a3-1dfe1873e0f6.jpg)

map zoom=1.2 aspectScale=1.2时
![qq 20181207100217](https://user-images.githubusercontent.com/22970441/49624138-47252100-fa0b-11e8-9308-98fc17325575.jpg)

鼠标靠近地图中线稍微靠右时tooltip被遮挡
![qq 20181207100543](https://user-images.githubusercontent.com/22970441/49624149-4ee4c580-fa0b-11e8-9129-4c35024341d5.jpg)

鼠标靠近地图中线稍微靠左时tooltip正常
![qq 20181207100559](https://user-images.githubusercontent.com/22970441/49624155-53a97980-fa0b-11e8-908d-eacaed121b4b.jpg)

## Topics

- [ ] Legend
- [x] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [x] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
echarts v4.1.0

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}
windows 7  chrome版本 67.0.3396.99（正式版本） （64 位）

**Comment by Ovilia** [comment]
Can you provide a demo?

**Comment by chenqing8** [comment]
你这个缩放不会产生有一层不能 跟着缩放吗

**Comment by authasme** [comment]
@chenqing8 可能你说到点上了，这个图层用的是series.map属性配置，geo.show属性为false但是geo属性必须存在
