### ISSUE TITLE
lines series overflow with dataZoom

### ISSUE THREAD

**Issue by highalps** [apache/incubator-echarts#9551]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

using lines with dataZoom, it overflow

### Online Example

![image](https://user-images.githubusercontent.com/20738369/49634605-9afe2d00-fa40-11e8-919a-b15bf7174ef8.png)

[http://gallery.echartsjs.com/editor.html?c=xxhGpd5qiK&v=2](http://gallery.echartsjs.com/editor.html?c=xxhGpd5qiK&v=2)

**Comment by Ovilia** [comment]
Not see dataZoom in your demo.

**Comment by highalps** [comment]
@Ovilia code below includes datazoom, sorry :( , not in link
