### ISSUE TITLE
calendar在改变range的时候 出现了报错

### ISSUE THREAD

**Issue by zhangtaoBqteam** [apache/incubator-echarts#9556]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [ ] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [x] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by zhangtaoBqteam** [comment]
echart版本： 4.1.0
问题描述：在修改日历图的range时，由传入的变量修改option，再调用setOption的方法，在页面上图是可以显示的且数据都准确，但是在检查工具栏中报错了，自己检查了一下代码发现，把修改calendar range的那段代码注释掉，工具栏中就不会报错，真的不知道原因，烦请熟悉的大神帮忙看看
报错信息：
<img width="481" alt="2018-12-09 3 33 07" src="https://user-images.githubusercontent.com/43007011/49694586-00305a80-fbc8-11e8-9b2f-e4a32a6445fb.png">
<img width="492" alt="2018-12-09 3 33 15" src="https://user-images.githubusercontent.com/43007011/49694587-00c8f100-fbc8-11e8-9277-a587e409746c.png">
代码：
```
this.option.calendar = this.calendar;
this.option.series[0].data = this.series_data;
if (this.visualMap_range.length > 0) {
    this.option.visualMap.min = this.visualMap_range[0];
    this.option.visualMap.max = this.visualMap_range[1];
}
this.$refs.dashboard_calendar_chart.setOption(this.option);
```
```
this.calendar = [
        {
          range: ["2018-01-01", "2018-12-08"],
          cellSize: "auto"
        }
]
```

**Comment by Ovilia** [comment]
Please provide your option.

**Comment by zhangtaoBqteam** [comment]
```
option: {
        tooltip: {
          position: "top",
          formatter: function(params) {
            return `${params.data[0]}: ${params.data[1]} 千瓦时`;
          },
          confine: true
        },
        visualMap: {
          min: 0,
          max: 1000,
          calculable: true,
          orient: "horizontal",
          left: "center",
          top: "top"
        },
        calendar: [
          {
            range: ["2017-01-01", "2017-12-31"],
            cellSize: "auto"
          }
        ],
        series: [
          {
            type: "heatmap",
            coordinateSystem: "calendar",
            calendarIndex: 0,
            data: []
          }
        ]
 }
```
