### ISSUE TITLE
Strange behavior when rendering chart in a table

### ISSUE THREAD

**Issue by kimuraz** [apache/incubator-echarts#9559]
- [X] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [X] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [X] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [X] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [X] Required: issue type；（必填）issue 类型
- [X] Required: one sentence description in issue details；（必填）一句话的问题描述
- [X] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [X] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [X] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

When a line chart (not sure about the others) is rendered on a table, it randomly `moves across the cells` and `vary its width`, even with the same data.

### Expected Behavior

All the charts, along with the table cells, should have the same `width` and position when they have the same `data`

### Current Behavior

The charts are rendered in random positions and with random width.

### Online Example

Using React: https://codepen.io/kimuraz/pen/OrPPRr
Using Vue: https://codepen.io/kimuraz/pen/XoJrXE?editors=1111
> Note: I tested both because I supected it was something about Vue's rendering, but the same occured on React.

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

I've tested with both SVG and Canvas rendering.

## Environment

- ECharts version；ECharts 版本: {4.1.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
If you log the width of the container in `mounted`, you may find that the width of them are not the same:
```js
console.log(this.$refs.chart.clientWidth)
// prints 477, 633, 654, 655 in my case
```

This is because the width of a column is decided by content width of each columns. And it changes when content changes.
In your case, I'd suggest setting `<td>` width using CSS to be fixed, like `40%` or `200px`. Hopefully that will help.

**Comment by kimuraz** [comment]
Thanks for the quick reply!

It simply worked: https://codepen.io/kimuraz/pen/OrPPRr
