### ISSUE TITLE
SVG and Canvas have different results for "Pie with scrollable legend" chart in echarts example

### ISSUE THREAD

**Issue by wmjcom** [apache/incubator-echarts#9565]
I test "Pie with scrollable legend" chart in echarts example. This is the url "http://www.echartsjs.com/examples/editor.html?c=pie-legend". I click the "Download" button to save the html file into local. Then I compare the chart to render on canvas and svg.

The first result is the default html. It looks good.
![default](https://user-images.githubusercontent.com/45786005/49791446-77eaba80-fd6b-11e8-8055-7918d8de6b9d.png)

I only make below changes to support svg in the html.
var myChart = echarts.init(dom, null, {renderer: 'svg'});
![default](https://user-images.githubusercontent.com/45786005/49791632-e0399c00-fd6b-11e8-8ed8-acc74f6c320c.png)

The svg chart has three issues different to canvas chart.
(1) Title is out of top range.
(2) Legend text cannot be shown.
(3) When move over pie chart, the section is to white. But it keeps same color for canvas.

Can anyone give some suggestions? Thanks.

**Comment by Meldanen** [comment]
I was just about to create the same ticket regarding the legends :)

**Comment by wmjcom** [comment]
@Ovilia Can you give any help? It is echarts example.

**Comment by wmjcom** [comment]
> I was just about to create the same ticket regarding the legends

I also find many issues for other charts in echarts example. If we know exact reason for this issue, we can know others.

**Comment by Ovilia** [comment]
Seems to have something to do with clipPath. I'll check it out ASAP.

**Comment by wmjcom** [comment]
@Ovilia Is this a bug? When can your team fix it? Thanks.

**Comment by Ovilia** [comment]
Sorry, not have time to check it. I'll check it tomorrow.

**Comment by Ovilia** [comment]
Confirmed that this is a bug caused by SVG transform with clipPath. I'm afraid it should take some time to be fixed since it's not very easy to fix it.

**Comment by SunGuoQiang123** [comment]
same issue for line chart

**Comment by Mr-jiangzhiguo** [comment]
I meet the same issues.

When will it be fixed ?

**Comment by Ovilia** [comment]
@Mr-jiangzhiguo This bug needs much code changes so I scheduled it in 5.0.0.

**Comment by chenjigeng** [comment]
我也遇到这个问题~请问目前最新版本修复了吗

**Comment by Composur** [comment]
> 我也遇到这个问题~请问目前最新版本修复了吗
更新到了5.0 用 SVG 渲染问题还在

**Comment by pissang** [comment]
5.0 中已经修复这个问题
