### ISSUE TITLE
ConnectNulls not connecting to values

### ISSUE THREAD

**Issue by Bjodol** [apache/incubator-echarts#9567]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

`connectNulls:false` is not connecting to non-values.

### Expected Behavior

Simple modified screenshot to describe expected behaviour
![image](https://user-images.githubusercontent.com/1528977/49814478-fe9e9800-fd69-11e8-843f-67ac9b8f7c09.png)

Even both of the neighbor values are null, there should there be an area beneath the current value.

### Current Behavior

Currently only the marker is drawn, and no area is shown beneath it.

![image](https://user-images.githubusercontent.com/1528977/49814327-b2ebee80-fd69-11e8-8b93-f2421420a7e0.png)

### Online Example

http://jsfiddle.net/2f67q5yu/

Options:
```
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [null, null, 901, null, null, null, null],
        type: 'line',
        areaStyle:{color: '#ff00ff'}
    }]
};
```

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: 4.2.0-rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
1. You should set `connectNulls: true` to make it connect nulls
2. You don't have `connectNulls` in your demo
3. It only connects from value to `null`, which means `[null, 1, null, 2]` will not have the line from the first data to `1`, but will connect between `1` and `2`.

**Comment by Ovilia** [comment]
@Bjodol Sorry, I can't understand your requirement here. 
> Even both of the neighbor values are null, there should there be an area beneath the current value.

What does the `area` mean? And why should it be?
