### ISSUE TITLE
graphic cannot be attributed to a gridIndex

### ISSUE THREAD

**Issue by Julien76** [apache/incubator-echarts#9568]
- [ x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x ] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x ] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [ x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x ] Required: issue type；（必填）issue 类型
- [ x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ x] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

When using graphic element, such as the online draggable example:
https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-draggable

There is no way to defined a gridIndex to which the graphic should be associated.

### Expected Behavior

The draggable point should respect the gridIndex that has been allocated.

### Current Behavior

If the draggable data are for example on gridIndex 1, the draggable circle stay on gridIndex 0.
Adding gridIndex in the graphic options has not impact.

### Online Example

Example of the issue:

http://gallery.echartsjs.com/editor.html?c=x06nfAxual&v=1

var symbolSize = 20;
var data = [[15, 0], [-50, 10], [-56.5, 20], [-46.5, 30], [-22.1, 40]];

option = {
    title: {
        text: 'Try Dragging these Points'
    },
    tooltip: {
        triggerOn: 'none',
        formatter: function (params) {
            return 'X: ' + params.data[0].toFixed(2) + '<br>Y: ' + params.data[1].toFixed(2);
        }
    },
    grid: [{
        bottom: '60%'
    }, {
        top: '60%'
    }],
    xAxis: [
        {
            min: -100,
            max: 80,
            type: 'value',
            axisLine: {onZero: false},
            gridIndex: 0
        },
        {
            min: -100,
            max: 80,
            type: 'value',
            axisLine: {onZero: false},
            gridIndex: 1
        },
    ],
    yAxis: [
        {
            min: -30,
            max: 60,
            type: 'value',
            axisLine: {onZero: false},
            gridIndex: 0
        },
        {
            min: -30,
            max: 60,
            type: 'value',
            axisLine: {onZero: false},
            gridIndex: 1
        }
    ],
    dataZoom: [
        {
            type: 'slider',
            xAxisIndex: 0,
            filterMode: 'empty'
        },
        {
            type: 'slider',
            yAxisIndex: 0,
            filterMode: 'empty'
        },
        {
            type: 'inside',
            xAxisIndex: 0,
            filterMode: 'empty'
        },
        {
            type: 'inside',
            yAxisIndex: 0,
            filterMode: 'empty'
        }
    ],
    series: [
        {
            id: 'a',
            type: 'line',
            smooth: true,
            symbolSize: symbolSize,
            data: data,
            xAxisIndex: 1, 
            yAxisIndex: 1
        }
    ]
};

if (!app.inNode) {
    setTimeout(function () {
        // Add shadow circles (which is not visible) to enable drag.
        myChart.setOption({
            graphic: echarts.util.map(data, function (item, dataIndex) {
                return {
                    type: 'circle',
                    position: myChart.convertToPixel('grid', item),
                    shape: {
                        cx: 0,
                        cy: 0,
                        r: symbolSize / 2
                    },
                    invisible: false,
                    draggable: true,
                    gridIndex: 1,
                    ondrag: echarts.util.curry(onPointDragging, dataIndex),
                    onmousemove: echarts.util.curry(showTooltip, dataIndex),
                    onmouseout: echarts.util.curry(hideTooltip, dataIndex),
                    z: 100
                };
            })
        });
    }, 0);

    window.addEventListener('resize', updatePosition);
}

myChart.on('dataZoom', updatePosition);

function updatePosition() {
    myChart.setOption({
        graphic: echarts.util.map(data, function (item, dataIndex) {
            return {
                position: myChart.convertToPixel('grid', item)
            };
        })
    });
}

function showTooltip(dataIndex) {
    myChart.dispatchAction({
        type: 'showTip',
        seriesIndex: 0,
        dataIndex: dataIndex
    });
}

function hideTooltip(dataIndex) {
    myChart.dispatchAction({
        type: 'hideTip'
    });
}

function onPointDragging(dataIndex, dx, dy) {
    data[dataIndex] = myChart.convertFromPixel('grid', this.position);

    // Update data
    myChart.setOption({
        series: [{
            id: 'a',
            data: data
        }]
    });
}

## Topics

- [ ] Legend
- [ ] Tooltip
- [x ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: 4.1.0

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
You should have more than one element in `grid` to use it.

**Comment by Julien76** [comment]
Could you please elaborate? I have two elements in the grid.

**Comment by Julien76** [comment]
I see now how it should be done.

I should replace 'grid' by { gridIndex: 1} in convertToPixel and in comvertFromPixel

This then work as intended.
