### ISSUE TITLE
SVG and Canvas have different results for "Candlestick shanghai index" chart in echarts example

### ISSUE THREAD

**Issue by wmjcom** [apache/incubator-echarts#9571]
I test "Candlestick shanghai index" chart in echarts example. This is the url "https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-sh". I click the "Download" button to save the html file into local. Then I compare the chart to render on canvas and svg.
The first result is the default html. It looks good.
![image](https://user-images.githubusercontent.com/45786005/49850956-7d530e00-fe1a-11e8-8bd4-240822b39c21.png)

I only make below changes to support svg in the html.
var myChart = echarts.init(dom, null, {renderer: 'svg'});
![image](https://user-images.githubusercontent.com/45786005/49851042-c4410380-fe1a-11e8-9059-0ceaddec6c59.png)

The svg chart has three issues different to canvas chart.
(1) Title "上证指数" is out of top range.
(2) The text data for xAxis are shown in the xAxis line. And the text data are not same in both results. 
(3) The value "2445" is out of the ball.

Can anyone give some suggestions? Thanks.

**Comment by Ovilia** [comment]
Hi. What's the version of your SVG ECharts? I tried with the latest version and it's the same as canvas result.

**Comment by wmjcom** [comment]
>           Hi. What's the version of your SVG ECharts? I tried with the latest version and it's the same as canvas result.

I just download the example from "https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-sh". It is using "<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts.min.js"></script>".
I only make below changes to support svg in the html.
var myChart = echarts.init(dom, null, {renderer: 'svg'});
It still has these issues.

**Comment by Ovilia** [comment]
Close due to cannot reproduce.
