### ISSUE TITLE
Drawing of custom label on Y-Axis

### ISSUE THREAD

**Issue by ezubarev** [apache/incubator-echarts#9582]
Is it possible to draw a custom label on YAxis in that way or another?
![image](https://user-images.githubusercontent.com/5698522/49956662-53900900-ff38-11e8-8df3-e42861791630.png)

**Comment by Ovilia** [comment]
Hi. Here's an example. Not quite the same, but something you can try with. http://gallery.echartsjs.com/editor.html?c=x6Y0rsxTG5

**Comment by ezubarev** [comment]
Thank you, @Ovilia. I've already seen this example, but it doesn't meet my requirements. Are there any other ways, maybe custom? Like Rich Text, but on axis? I don't want to refuse this wonderful library because of it.

**Comment by dperetz1** [comment]
> Hi. Here's an example. Not quite the same, but something you can try with. http://gallery.echartsjs.com/editor.html?c=x6Y0rsxTG5

that link doesn't work anymore, is there any other example?
