### ISSUE TITLE
webAPP: Failed to execute'arc'on'Canvas Rendering Context2D': The radius provided (-8) is negative.at echarts-all.js

### ISSUE THREAD

**Issue by Poolisde** [apache/incubator-echarts#9584]
## General Questions

- [x ] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [ x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [ x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [ ] Required: issue type；（必填）issue 类型
- [ ] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

 Failed to execute'arc'on'Canvas Rendering Context2D': The radius provided (-8) is negative. at echarts.all.js:13

### Expected Behavior

 How to solve this problem or avoid it in future programs 

### Current Behavior

 There are a lot of error escalation, too many errors will lead to program instability 

### Online Example

 I don't know where the error was caused. If I turned on the software the second time, it would not happen. 

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [x ] SVG
- [ ] Map
- [ x] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
What's your ECharts version? This seems to be an old bug, and please try with the latest version.

**Comment by Poolisde** [comment]
Thank you for your answer. I went to compare the code versions. The reason is that the old project is not updated in time.
