### ISSUE TITLE
Custom property in ECharts

### ISSUE THREAD

**Issue by anchalj-hexaware** [apache/incubator-echarts#9587]
Can we create any custom property in ECharts so as to fulfill the requirements which are not there in Echarts

**Comment by Ovilia** [comment]
What requirement do you mean?

**Comment by anchalj-hexaware** [comment]
i want to implement trend line in a line chart, but apparently i found out there is no property for trendline in echarts. However i have analyzed the formula for it, so i want to create a custom property for that, is there any way i can do that?
