### ISSUE TITLE
为什么我关闭了防止重叠还是有一些label没有显示出来了

### ISSUE THREAD

**Issue by yizhengfeng-jj** [apache/incubator-echarts#9589]
## 问题
我的echarts图稍微小一点的时候，我们的lable就会有的被隐藏了，这是因为echarts的防重叠机制自动把lable去掉了,可以设置interval:0,来解决这个问题
![image](https://user-images.githubusercontent.com/20452750/49991483-3270fc00-ffbc-11e8-9f28-90f2f9c2b45f.png)
我本以为这样解决了问题 但是我缩小图的时候，确实中间部分不会被隐藏，但是第一个和最后一个也就是周一和周日无论怎么样，都会被影藏
## 第一次结果
![image](https://user-images.githubusercontent.com/20452750/49991565-749a3d80-ffbc-11e8-93cc-2fd00c342330.png)
## 分析结果
这个周一，和周日被隐藏了，但是我是不想让与他们讷隐藏的，后来我查了一下，第一个和最后一个要用
showMaxLabel:true,showMinLabeel: true,这个就是在重叠的时候，控制最大，最小的标签显示，于是写上去，确实周一和周日有了，但是中间的周二又少了，难道showMaxLable,showMinLable,interval不能共存么，
## 第二次结果
![image](https://user-images.githubusercontent.com/20452750/49992010-cdb6a100-ffbd-11e8-8cc7-abfc14f83a54.png)

![image](https://user-images.githubusercontent.com/20452750/49991768-13269e80-ffbd-11e8-8977-72869cc503f6.png)
## 疑惑
难道就没有什么方法，显示全部的标签么，无论图多小，全部显示，就让他重叠，没有这种方法么?

**Comment by wjhcc2018** [comment]
我也遇到了这个问题，哎

**Comment by wmasfoe** [comment]
这问题咋也不解决就关闭了

**Comment by realize-me** [comment]
我是从这个地址过来的。
![image](https://github.com/apache/echarts/assets/55303255/32a01925-a960-48d5-a381-e97c37eacae5)
https://echarts.apache.org/zh/changelog.html

我设置interval:0可以显示所有类目，但是最后一个类目颜色被加深了。
