### ISSUE TITLE
不知道这是否是一个Bug，两次图标渲染不一致。

### ISSUE THREAD

**Issue by NikolasNull** [apache/incubator-echarts#9590]
同样的数据，切换按钮传参，请求后台数据后，渲染的折线图有差别。
![image](https://user-images.githubusercontent.com/27730211/49999522-0b252980-ffd2-11e8-95db-d34478e5e914.png)
![image](https://user-images.githubusercontent.com/27730211/49999533-11b3a100-ffd2-11e8-8e40-958962a884cc.png)

**Comment by Ovilia** [comment]
Please reproduce it on http://gallery.echartsjs.com/editor.html

**Comment by NikolasNull** [comment]
[](url)

> Please reproduce it on http://gallery.echartsjs.com/editor.html

刚加过了

**Comment by Ovilia** [comment]
What's the URL?
