### ISSUE TITLE
Treemap : ZoomToNode and Highlight

### ISSUE THREAD

**Issue by Skullnick** [apache/incubator-echarts#9591]
- [X] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [X] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [X] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [X] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [X] Required: issue type；（必填）issue 类型
- [X] Required: one sentence description in issue details；（必填）一句话的问题描述
- [X] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [X] Required: ECharts version 4.2.0-rc.2；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [X] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [X] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

I'm still waiting on the following open issues : 
1. **https://github.com/apache/incubator-echarts/issues/8815**
Would it be possible to have a **dispatchAction of type: 'treemapZoomToNode'**.
Why ? So that I can trigger a zoom to node within a search bar in a another component.

2. **https://github.com/apache/incubator-echarts/issues/8811**
Would it also be possible to have a **dispatchAction of type 'highlight'**.
Reason is same as above : so it's easier to find a node in a treemap.

3. **https://github.com/apache/incubator-echarts/issues/8810**
**Emphasis on ItemStyle not working properly**
When can we expect it to get fixed ?

## Topics

- [ ] Legend
- [ ] Tooltip
- [X] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version **4.2.0-rc.2**；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Please follow these issue. And we do wish you could send us a pull request about them. Since you can see, there are so many features requested or bugs, it may take some time before we could fix them.
