### ISSUE TITLE
Echarts 4.2.0-rc.2 English Version

### ISSUE THREAD

**Issue by huseinzol05** [apache/incubator-echarts#9594]
Translated version [4.2.0-rc.2](https://ecomfe.github.io/echarts-doc/public/en/download.html)

![screenshot 2018-12-17 at 12 24 54 am](https://user-images.githubusercontent.com/19810909/50056075-348cb380-0192-11e9-978b-339ab666fefe.png)

_Originally posted by @huseinzol05 in https://github.com/apache/incubator-echarts/issues/2321#issuecomment-447656234_

**Comment by Ovilia** [comment]
What's the problem here?

**Comment by huseinzol05** [comment]
I will close this issue, just wanted to share the translated version. Thanks!
