### ISSUE TITLE
点击柱形图，展示一个显示具体信息的列表

### ISSUE THREAD

**Issue by iayun** [apache/incubator-echarts#9595]
根据数据库的值，统计得到柱形图。现在想通过点击柱形图，打开一个grid，在页面上展示详细的值。是不是可以出个doc.

**Comment by cuijian-dexter** [comment]
you can set `tooltip.formatter` or bind click events.
http://www.echartsjs.com/api.html#events.%E9%BC%A0%E6%A0%87%E4%BA%8B%E4%BB%B6

**Comment by deqingli** [comment]
sorry, there is no official tutorial,  you can listen to the click events, and then call `setOption()`.
