### ISSUE TITLE
Setting fontsize on one label influences other labels' fontsize

### ISSUE THREAD

**Issue by wangyi7099** [apache/incubator-echarts#9596]
## Reproduction Link
 http://www.echartsjs.com/examples/editor.html?c=pie-rich-text

As you can see in the picture below, 
![bug](https://user-images.githubusercontent.com/24426655/50063476-7431ba80-01e7-11e9-97ee-ec6aeaac6dfd.png)

I set `font-sze: 40px` on `rate`, the `fontSize` of other labels also seem to become `40`.

**Comment by cuijian-dexter** [comment]
you can set `series.label.normal.rich` = {}

```
series : [
        {
            label:{
                normal:{
                    rich:{}
                }
            },
            data:{}
        }
]
```

**Comment by wangyi7099** [comment]
I know I can set `rich` . 

But when I set rich on one item, other items' label style also changed, this is **unreasonable** .

**Comment by cuijian-dexter** [comment]
you can set `series.label.normal.rich`, then  set `series.data[i].label.normal.rich`.

**Comment by wangyi7099** [comment]
Thanks . It works.

**Comment by deqingli** [comment]
@wangyi7099  This is a known issue, and we have resolved it in next release version.

**Comment by deqingli** [comment]
@100pah When will we release the next version?

**Comment by 100pah** [comment]
Probably before the new year.
