### ISSUE TITLE
Bug with width of markline

### ISSUE THREAD

**Issue by ezubarev** [apache/incubator-echarts#9598]
Sometimes line width doesn't match provided settings. 

```
markLine: {
    lineStyle: {
        normal: {
            type: 'solid',
            width: 1,
            color: 'black'
        },
    },
}
```

![image](https://user-images.githubusercontent.com/5698522/50068474-a4358980-01f8-11e9-970e-020583b95a36.png)

Two lines have the same configuration but the upper one is wider than lower one.

http://gallery.echartsjs.com/editor.html?c=xCUWInr4gz&v=1

Probably, you have to resize a window to reproduce it.

**Comment by pissang** [comment]
It's a common subpixel artifact in canvas when the pixel is not exactly on the x.5 position.

**Comment by ezubarev** [comment]
Thank you, @pissang! Interesting to see how you will fix it in the code.

**Comment by deqingli** [comment]
@ezubarev  I have fixed the problem, you can see it with the associated commit.

**Comment by ezubarev** [comment]
Great! Well done!

**Comment by ezubarev** [comment]
Bug has been reproduced in latest version. You should fix it again.

**Comment by ezubarev** [comment]
@pissang @deqingli
