### ISSUE TITLE
关于echarts全屏显示问题

### ISSUE THREAD

**Issue by jinriwen** [apache/incubator-echarts#9599]
本人echarts入门,想要实现一个点击全屏按钮后,chart能够全屏显示,点击缩放按钮后,chart能够回到原本的正常尺寸,就好像视频软件中的全屏显示和回到最初比例一样的功能,求各位大神指教,感激不尽.

**Comment by cuijian-dexter** [comment]
This doesn't seem to be the basic function of graphs. You can do it by expanding the parent container and calling resize.

**Comment by jinriwen** [comment]
thanks for your help
