### ISSUE TITLE
鼠标样式被更改

### ISSUE THREAD

**Issue by luotom** [apache/incubator-echarts#9600]
当横向柱形图在series中设置
itemStyle:{
                    normal:{
                        color: 'rgb(144, 160, 179, .7)'
                    }
                }
以后，鼠标移到柱形图上时，鼠标样式被改成了箭头，而不是原来的手的样式；而普通柱形图的鼠标样式则不会改变

**Comment by deqingli** [comment]
Thank you for your feedback, this is a bug, we will fix it.

**Comment by 100pah** [comment]
@luotom  Should be `rgba(144, 160, 179, .9)` but not `rgb(144, 160, 179, .9)`.

**Comment by luotom** [comment]
Thanks
