### ISSUE TITLE
如何在Xaxis中的一列中隐藏serise中的某一项data

### ISSUE THREAD

**Issue by tirelyl** [apache/incubator-echarts#9613]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

想请教一下，如何在Xaxis中的一列中隐藏serise中的某一项data，我想隐藏我的serise data中一些value为0的数据，但是查找api后可以通过 itemStyle的opacity设置为0 或者 value设置为 null 来不渲染。但是占据的x轴的位置并不能隐藏

### Expected Behavior

![image](https://user-images.githubusercontent.com/20921324/50202178-1c868100-0398-11e9-8e34-36e1d149cecd.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/20921324/50202194-290ad980-0398-11e9-9891-9f083b798d75.png)
![image](https://user-images.githubusercontent.com/20921324/50202361-d54cc000-0398-11e9-8c49-de54554831ee.png)

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
@tirelyl  You can filter out data with value 0 directly through data preprocessing?
