### ISSUE TITLE
remove brush

### ISSUE THREAD

**Issue by djy2017** [apache/incubator-echarts#9617]
通过事件或者点击brush按钮添加了选框后，除了点击clear按钮还有其他方式移除选框吗？
如何通过JS调用API直接移除

**Comment by 100pah** [comment]
```js
        myChart.dispatchAction({
            type: 'brush',
            areas: []
        });
```
集可。
参见 <http://echarts.baidu.com/api.html#action.brush.brush>

**Comment by nanmucoffin** [comment]
那怎么移除鼠标的画笔功能，恢复正常鼠标模式

**Comment by nanmucoffin** [comment]
chart.on('brush', (p: any) => {
      if (p.command === 'clear') {
        this.map.chart.dispatchAction({
          type: 'takeGlobalCursor',
          key: 'brush',
          brushOption: {
            brushType: false,
            brushMode: 'single'
          }
        })
     }

**Comment by nanmucoffin** [comment]
this.chart.dispatchAction({
            type: 'brush',
            areas: []
        });
        this.chart.dispatchAction({
          type: 'takeGlobalCursor',
          key: 'brush',
          brushOption: {
            brushType: false,
            brushMode: 'single'
          }
        }）
