### ISSUE TITLE
stacked column behavior is strange when the data range is too small.

### ISSUE THREAD

**Issue by katherinebai** [apache/incubator-echarts#9625]
Using the following option, the echart behavior is so strange as picture:
![image](https://user-images.githubusercontent.com/36399340/50328050-686a2f00-052c-11e9-8825-f62ad201956f.png)

option = {
	"legend": {
		"show": true,
		"data": ["s1", "s2"]
	},
	"series": [{
		"name": "s1",
		"z": 3,
		"type": "bar",
		"data": [{
			"value": 0.990566
		}, {
			"value": 0.9756098
		}, {
			"value": 0.9868421
		}, {
			"value": 0.9879518
		}],
		"itemStyle": {
			"color": "#4F81BD"
		},
		"stack": "s1"
	}, {
		"name": "s2",
		"z": 2,
		"type": "bar",
		"data": [{
			"value": 0.009434
		}, {
			"value": 0.0243902
		}, {
			"value": 0.0131579
		}, {
			"value": 0.0120482
		}],
		"itemStyle": {
			"color": "#C0504D"
		},
		"stack": "s1"
	}],
	"xAxis": {
		"show": true,
		"type": "category",
		"data": ["a", "b", "c", "d"]
	},
	"yAxis": {
		"show": true,
		"type": "value",
		"max": 1,
		"min": 0.96,
		"splitNumber": 8
	}
};

**Comment by deqingli** [comment]
I have fixed some error in your demo and reproduce a new one, you can see this [URL](http://gallery.echartsjs.com/editor.html?c=xyhLOwA8T9&v=4).

**Comment by katherinebai** [comment]
![image](https://user-images.githubusercontent.com/36399340/50368973-791cb280-05c9-11e9-8ecd-c8c8e2690cb5.png)
I can't see your fixed demo.

**Comment by deqingli** [comment]
This is the new option, you can try it.
```js
option = {
    
    legend: {
        show: true,
        data: ["s1", "s2"]
    },
    "series": [
        {
            "name": "s1",
            // "z": 3,
            "type": "bar",
            "data": [
                {
                    "value": 0.990566
                }, 
                {
                    "value": 0.9756098
                }, 
                {
                    "value": 0.9868421
                }, 
                {
                    "value": 0.9879518
                }
            ],
            "itemStyle": {
                "color": "#4F81BD"
            },
            "stack": "total"
        }, 
        {
            "name": "s2",
            // "z": 2,
            "type": "bar",
            "data": [{
            "value": 0.009434
            }, {
            "value": 0.0243902
            }, {
            "value": 0.0131579
            }, {
            "value": 0.0120482
            }],
            "itemStyle": {
            "color": "#C0504D"
            },
            "stack": "total"
        }
    ],
    "xAxis": {
        "show": true,
        "type": "category",
        "data": ["a", "b", "c", "d"]
    },
    "yAxis": {
        "show": true,
        "type": "value",
        // "max": 1,
        // "min": 0.96,
        "splitNumber": 8
    }
};
```

**Comment by katherinebai** [comment]
Thank you.
