### ISSUE TITLE
legend设置2个data，series设置2个data 出现问题

### ISSUE THREAD

**Issue by luozhining** [apache/incubator-echarts#9628]
![image](https://user-images.githubusercontent.com/23116642/50375098-27107700-0633-11e9-881d-6c76ea97d63a.png)
![image](https://user-images.githubusercontent.com/23116642/50375103-3099df00-0633-11e9-8cad-e008d77417c5.png)

谢谢帮忙解答，帮忙看下用法是不是错了。

**Comment by luozhining** [comment]
![image](https://user-images.githubusercontent.com/23116642/50375123-76ef3e00-0633-11e9-8519-86176564f963.png)

**Comment by cuijian-dexter** [comment]
@luozhining  Refer to this example.
http://echarts.baidu.com/examples/editor.html?c=bar-y-category

**Comment by luozhining** [comment]
你给的例子，legend只设置了一个data。legend能不能设置两个data

**Comment by cuijian-dexter** [comment]
@luozhining http://www.echartsjs.com/option.html#legend.data

**Comment by luozhining** [comment]
可以给个demo吗，我是新手，谢谢啦。
