### ISSUE TITLE
echarts箱线图

### ISSUE THREAD

**Issue by yaorun** [apache/incubator-echarts#9630]
![image](https://user-images.githubusercontent.com/19942344/50388893-47d4eb80-075d-11e9-82c7-c36bf0f6543c.png)

能不能帮忙看一下 echarts 能否使用箱线图实现上图的效果。

**Comment by cuijian-dexter** [comment]
@yaorun I don't quite understand your needs.Look at the following examples. Do they meet your requirements?
http://gallery.echartsjs.com/editor.html?c=boxplot-light-velocity
