### ISSUE TITLE
How to encode polygon in format?

### ISSUE THREAD

**Issue by stephanbochet** [apache/incubator-echarts#9635]
Is there a formula name or a formula available that performs the encoding of a Polygons coordinate?

I am trying to encode a polygons coordinate in a manner that can be read by the decodePolygon function in the src/coord/geo/parseGeoJson.js.

Is there an encodePolygon function available somewhere compatible with the decodePolygon function below?
```
function decodePolygon(coordinate, encodeOffsets, encodeScale) {
  var result = [];
  var prevX = encodeOffsets[0];
  var prevY = encodeOffsets[1];

  for (var i = 0; i < coordinate.length; i += 2) {
    var x = coordinate.charCodeAt(i) - 64;
    var y = coordinate.charCodeAt(i + 1) - 64; // ZigZag decoding

    x = x >> 1 ^ -(x & 1);
    y = y >> 1 ^ -(y & 1); // Delta deocding

    x += prevX;
    y += prevY;
    prevX = x;
    prevY = y; // Dequantize

    result.push([x / encodeScale, y / encodeScale]);
  }

  return result;
}
```

**Comment by 100pah** [comment]
Check this please <https://github.com/ecomfe/echarts-map-tool/blob/gh-pages/maker/tool/compress.js>
