### ISSUE TITLE
android webview 硬件加速 截图 空白

### ISSUE THREAD

**Issue by Anjon-github** [apache/incubator-echarts#9640]
为什么android webview开启硬件加速后，加载echarts，截图显示空白；

关闭硬件加速后，就可以正常截图；

但是关闭后，H5页面滑动很卡

**Comment by 100pah** [comment]
Could I have your: Android info, echarts option, echarts version?

**Comment by TobyCheung** [comment]
This is a common problem that I also met.

**Comment by Ovilia** [comment]
What chart do you use? Can you provide a demo?
