### ISSUE TITLE
echarts 地图散点绘制缓慢，dispatchAction也迟缓

### ISSUE THREAD

**Issue by yezidream** [apache/incubator-echarts#9642]
你好，echarts绘制地图散点图的时候特别卡，已经把animation都禁用了，使用了时间轴，时间轴一共1440左右的点，每一个时间点在地图上绘制大概330个点，在使用dispatchAction手动控制play的时候也很缓慢，请问这有优化的方法吗？

**Comment by 100pah** [comment]
Could I have your `option` and `data` to reproduce this scenario?
