### ISSUE TITLE
柱状图X轴显示两级类目实现原理

### ISSUE THREAD

**Issue by heianqishizhisuiyuan** [apache/incubator-echarts#9644]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [√] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [√] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [√] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [√] Required: issue type；（必填）issue 类型
- [√] Required: one sentence description in issue details；（必填）一句话的问题描述
- [√] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [√ ] Required: ECharts version；ECharts 版本

## Issue Type

- [√] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [√] I have a bug to report；我想要报 bug
- [ x] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ x] There's something wrong with the documents；文档有些问题
- [ x] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details
 柱状图X轴显示两级类目

### Expected Behavior
![image](https://user-images.githubusercontent.com/20060464/50440129-b36eb280-092f-11e9-9b45-ff1ef8675a69.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/20060464/50440181-fa5ca800-092f-11e9-811a-17282e1073fc.png)

### Online Example

http://gallery.echartsjs.com/editor.html?c=xQNLk5u-67

       axisTick: {
              show:true,
              length: 110,
              alignWithLabel: false,
              interval: function(param,value){
                if(value ==undefined){
                  return true
                }
                return param%4 ===0;
              },
            },

## Topics

- [ x] Legend
- [ x] Tooltip
- [ x] Event
- [x ] Performance
- [ x] SVG
- [ x] Map
- [x ] ECharts GL
- [ x] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know
1.我想实现 柱状图X轴显示两级类目，想利用了两个x轴实现，但是发现第二个类目没法居中（兼容dataZoom放大缩小）例子(版本3.8.0)：http://gallery.echartsjs.com/editor.html?c=xQNLk5u-67。
2，当我把你echarts 版本切换到最新的版本(4.2.0)时 把相同的代码（从3.8.0代码复制来，发现意想不到的结果，主要原因就是x.axisTick.interval 这个属性导致的，但是无论我怎么调都不管用。好像在最新版本中这个interval有bug。 例子(版本4.2.0))：http://gallery.echartsjs.com/editor.html?c=xQNLk5u-67。

## Environment

- ECharts version；ECharts 版本: {3.8.0}

- [ x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
An example:
<http://gallery.echartsjs.com/editor.html?c=xR9ug3y7FY&v=2>

**Comment by heianqishizhisuiyuan** [comment]
> An example:
> http://gallery.echartsjs.com/editor.html?c=xR9ug3y7FY&v=2

你这个有个bug 当出发了datazoon(放大)时 可以发现x轴的分类会发生变化，不是一个季度对应一个分类。这么做是错误的。

**Comment by heianqishizhisuiyuan** [comment]
> An example:
> http://gallery.echartsjs.com/editor.html?c=xR9ug3y7FY&v=2

你这个有个bug 当触发了dataZoom(放大)时 可以发现x轴的分类会发生变化，不是一年（四个季度）对应一个分类。这么做是错误的

**Comment by 100pah** [comment]
#9819
