### ISSUE TITLE
dblclick事件中无法使用setoption刷新数据（渲染画布）。

### ISSUE THREAD

**Issue by lostpuck** [apache/incubator-echarts#9646]
各位echarts的开发者们，你们好！

单行总结[问题简述]
dblclick事件中无法使用setoption刷新数据（渲染画布）。

版本与环境[版本及环境]
ECharts版本[ECharts版本]：
4.2.0-rc.2

**浏览器版[浏览器类型和版本]：**
chrome

预期行为[期望结果]
能够渲染，或者局部渲染，不改变图表位置或样式

详细描述：
目前在使用dataZoom + scatter的组合，当我改变scatter的样式的时候想渲染界面。在click中使用setoption可以渲染，没问题。不过换到dblclick事件中用setoption就不起作用了，不知道是什么原因，在dblclick中必须用.clear()才清除视图后才能刷新数据（渲染界面），但是用clear()会使画布还原，这样一来会丢失很多其他数据（虽然缩放比例是可以还原，但是还有其他的数据没法还原），尝试了很多办法都没解决这个问题，请问有什么好的办法吗？

**Comment by 100pah** [comment]
请问 dbclick 是点击在什么上的？

**Comment by lostpuck** [comment]
> 请问dbclick是点击在什么上的？

是双击scatter时触发，用的是echarts.on('dblclick', function (e){})函数
