### ISSUE TITLE
关系图在大量节点的时候使用edgeSymbol会导致标签虚化

### ISSUE THREAD

**Issue by hadg** [apache/incubator-echarts#9648]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

关系图在大量节点的时候使用edgeSymbol会导致标签虚化 

### Expected Behavior

标签正常显示

### Current Behavior

标签被虚化

### Online Example

官方的例子（http://echarts.baidu.com/examples/editor.html?c=graph-npm）

正常显示：
![image](https://user-images.githubusercontent.com/4592450/50470396-415ba380-09eb-11e9-9966-5ba233e71851.png)

加入edgeSymbol: ['none', 'arrow']属性后标签虚化了：
![image](https://user-images.githubusercontent.com/4592450/50470453-7831b980-09eb-11e9-8c75-69ff51b936ca.png)

修改后的代码：
````myChart.showLoading();
$.getJSON('data/asset/data/npmdepgraph.min10.json', function (json) {
    myChart.hideLoading();
    myChart.setOption(option = {
        title: {
            text: 'NPM Dependencies'
        },
        animationDurationUpdate: 1500,
        animationEasingUpdate: 'quinticInOut',
        series : [
            {
                type: 'graph',
                layout: 'none',
                // progressiveThreshold: 700,
                edgeSymbol: ['none', 'arrow'],
                data: json.nodes.map(function (node) {
                    return {
                        x: node.x,
                        y: node.y,
                        id: node.id,
                        name: node.label,
                        symbolSize: node.size,
                        itemStyle: {
                            normal: {
                                color: node.color
                            }
                        }
                    };
                }),
                edges: json.edges.map(function (edge) {
                    return {
                        source: edge.sourceID,
                        target: edge.targetID
                    };
                }),
                label: {
                    emphasis: {
                        position: 'right',
                        show: true
                    }
                },
                roam: true,
                focusNodeAdjacency: true,
                lineStyle: {
                    normal: {
                        width: 0.5,
                        curveness: 0.3,
                        opacity: 0.7
                    }
                }
            }
        ]
    }, true);
});
````

## Topics

- [x] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {4.2.0-rc.2}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
It has been fixed in 4.3.0
