### ISSUE TITLE
实例（全国主要城市空气质量）数据间相差过大，点遮挡整个界面

### ISSUE THREAD

**Issue by lfzx** [apache/incubator-echarts#9662]
原例子
![image](https://user-images.githubusercontent.com/34572392/50547384-be00b300-0c73-11e9-92e9-e267e33c3f0e.png)
用了我的数据后
![image](https://user-images.githubusercontent.com/34572392/50547404-e5f01680-0c73-11e9-9a99-680ac88b351a.png)
这是部分数据，如果我全部除以某个值，很小的值便不会显示。请问我该如何做才能使每个点都能出现，且符合原来的大小比值。先在此谢谢解答了！
var data = [
  {"name": "衡阳","value": 13},
  {"name": "宜昌","value": 20},
  {"name": "内江","value": 8},
  {"name": "台州","value": 681},
  {"name": "焦作","value": 15},
  {"name": "佛山","value": 1865},
  {"name": "南宁","value": 77},
  {"name": "南阳","value": 27},
  {"name": "萍乡","value": 30},
  {"name": "郴州","value": 34},
  {"name": "上饶","value": 44},
  {"name": "惠州","value": 516},
  {"name": "南充","value": 36},
  {"name": "昆明","value": 65},
  {"name": "漯河","value": 141},
  {"name": "赤峰","value": 7},
  {"name": "洛阳","value": 156},
  {"name": "吕梁","value": 10},
  {"name": "哈尔滨","value": 24},
  {"name": "西宁","value": 2},
  {"name": "南平","value": 72},
  {"name": "三门峡","value": 1},
  {"name": "黄冈","value": 3},
  {"name": "湖州","value": 1381},
  {"name": "盐城","value": 159},
  {"name": "荆州","value": 180},
  {"name": "衢州","value": 12},
  {"name": "滨州","value": 4},
  {"name": "莆田","value": 249},
  {"name": "扬州","value": 343},
  {"name": "泰州","value": 77},
  {"name": "连云港","value": 618},
  {"name": "长治","value": 9},
  {"name": "深圳","value": 9065},
  {"name": "长春","value": 28},
  {"name": "潮州","value": 64},
  {"name": "泸州","value": 7},
  {"name": "揭阳","value": 598},
  {"name": "吉安","value": 3},
  {"name": "常州","value": 628},
  {"name": "芜湖","value": 164},
  {"name": "呼和浩特","value": 87},
  {"name": "阳江","value": 21},
  {"name": "朔州","value": 7},
  {"name": "聊城","value": 32},
  {"name": "湘潭","value": 1},
  {"name": "沧州","value": 6},
  {"name": "武汉","value": 2665},
  {"name": "东沙","value": 1},
  {"name": "德州","value": 3},
  {"name": "铜陵","value": 42},
  {"name": "潍坊","value": 144},
  {"name": "咸阳","value": 14},
  {"name": "杭州","value": 15406},
  {"name": "丽水","value": 433},
  {"name": "广州","value": 15215},
  {"name": "宣城","value": 26},
  {"name": "通辽","value": 23},
  {"name": "澳洲","value": 54},
  {"name": "随州","value": 8},
  {"name": "温州","value": 3272},
  {"name": "朝鲜","value": 1},
  {"name": "大连","value": 263},
  {"name": "漳州","value": 232},
  {"name": "泉州","value": 5920},
  {"name": "安顺","value": 7},
  {"name": "襄阳","value": 10},
  {"name": "伊春","value": 3},
  {"name": "北京","value": 6455},
  {"name": "太原","value": 7},
  {"name": "香港","value": 118},
  {"name": "赣州","value": 248},
  {"name": "成都","value": 1559},
  {"name": "苏州","value": 8062},
  {"name": "济宁","value": 1},
  {"name": "景德镇","value": 156},
  {"name": "淮安","value": 225},
  {"name": "云浮","value": 1},
  {"name": "南昌","value": 438},
  {"name": "榆林","value": 21},
  {"name": "黄山","value": 1},
  {"name": "越南","value": 1},
  {"name": "唐山","value": 16},
  {"name": "上海","value": 29617},
  {"name": "宁波","value": 2775}
]

**Comment by chfw** [comment]
需要调整数据
