### ISSUE TITLE
桑基图的矩形节点的tooltip如何将该节点对应的value之和显示上去

### ISSUE THREAD

**Issue by zhangtaoBqteam** [apache/incubator-echarts#9667]
目前在官方示例中，矩形节点的tooltip是没有显示该节点所有的value之和的，我看了一下官方文档关于sankey图的介绍，也没有找到关于这方面的参数设置

**Comment by elephantme** [comment]
这个问题你解决了么？自定义tooltip的时候，矩形节点返回的params中没有总量的数据。

**Comment by zhangtaoBqteam** [comment]
我是判断param的dataType类型，有node和edge两种，其中node类型的会有这个节点的总量数据（value），edge类型的value是流向的数量


------------------------------------------------------------------
发件人：dong <notifications@github.com>
发送时间：2019年10月22日(星期二) 15:58
收件人：apache/incubator-echarts <incubator-echarts@noreply.github.com>
抄　送：张涛 <zhangtao@bqteam.com>; State change <state_change@noreply.github.com>
主　题：Re: [apache/incubator-echarts] 桑基图的矩形节点的tooltip如何将该节点对应的value之和显示上去 (#9667)

这个问题你解决了么？自定义tooltip的时候，矩形节点返回的params中没有总量的数据。

**Comment by elephantme** [comment]
谢谢回复~ 我用的4.3.0-rc.2版本，dataType为node时，value是undefined，没有总量数据，你用的哪个版本呢？

**Comment by zhangtaoBqteam** [comment]
我用的是4.2.1...



------------------------------------------------------------------
发件人：dong <notifications@github.com>
发送时间：2019年10月22日(星期二) 17:25
收件人：apache/incubator-echarts <incubator-echarts@noreply.github.com>
抄　送：张涛 <zhangtao@bqteam.com>; State change <state_change@noreply.github.com>
主　题：Re: [apache/incubator-echarts] 桑基图的矩形节点的tooltip如何将该节点对应的value之和显示上去 (#9667)

谢谢回复~ 我用的4.3.0-rc.2版本，dataType为node时，value是undefined，没有总量数据，你用的哪个版本呢？

**Comment by elephantme** [comment]
我用4.2.1版本，发现value依然是undefined呀

**Comment by zhangtaoBqteam** [comment]
我是这么用的，可以获取到value值的...你可以再确认一下版本...或者把你使用的方式发我看一下把
------------------------------------------------------------------
发件人：dong <notifications@github.com>
发送时间：2019年10月22日(星期二) 19:08
收件人：apache/incubator-echarts <incubator-echarts@noreply.github.com>
抄　送：张涛 <zhangtao@bqteam.com>; State change <state_change@noreply.github.com>
主　题：Re: [apache/incubator-echarts] 桑基图的矩形节点的tooltip如何将该节点对应的value之和显示上去 (#9667)

我用4.2.1版本，发现value依然是undefined呀

**Comment by elephantme** [comment]
官方示例用的4.4.0也拿不到总数，4.4.0-rc.1版本修复了这个问题

**Comment by clarissahu** [comment]
![image](https://user-images.githubusercontent.com/24582696/76090422-84090a80-5ff6-11ea-8156-ae7e01e961b1.png)
我发现这样是可以的，在data里自己手动写上value。这样写就要自己确保数据的准确性了，因为这个value即使是乱写（即不等于节点下的数据流向之和）也会正常显示的。
