### ISSUE TITLE
interval，和 minInterval间隔 在定了max和min后间隔不平均

### ISSUE THREAD

**Issue by liuyc123** [apache/incubator-echarts#9668]
间隔计算总是从0开如间隔 比如要分成五条线，会有的间隔间距大有的间隔间距小不平均，
![default](https://user-images.githubusercontent.com/28505081/50597363-294fbc80-0ee2-11e9-99bf-e0a604dbf747.png)

**Comment by pissang** [comment]
It's a common strategy to make sure the number of interval ticks is nice(eg, have steps 2, 3, 5, 10) when min and max are fixed.
