### ISSUE TITLE
Add cross to available symbols

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/incubator-echarts#9674]
Hello and Happy New Year !

I would like you to add a new symbol in the list of available symbols https://ecomfe.github.io/echarts-doc/public/en/option.html#series-scatter.symbol

The symbol should look like this ✚ and its name can be called "cross". I found the symbol here https://www.alt-codes.net/latin-cross.php and it is called "heavy cross".

I saw that it can be added in the source from here
https://github.com/apache/incubator-echarts/blob/fd064123626c97b36cbd6da1b5fc73385c280abd/src/util/symbol.js
but I don't have a JS dev environment to make the changes.

Best regards.

**Comment by pissang** [comment]
Happy new year!

You can use `path://` description to add custom symbol shape. For example, a heavy cross can be

```js
symbol: 'path://M5.979 10.974v5.021h7.041v11.99h5.042v-11.99h6.958v-5.021h-6.958v-6.958h-5.042v6.958h-7.041z'
```

You can find the path description in the svg file. Which is usually in the `path` element.

**Comment by MINDoSOFT** [comment]
Yes that would be a way to add it. Thanks!
