### ISSUE TITLE
emergency：draw two bars in one container，but the second bar not show at the Xaxis

### ISSUE THREAD

**Issue by DorisOu** [apache/incubator-echarts#9679]
this problem reproduce in the bellow address:
http://gallery.echartsjs.com/editor.html?c=xwP8K_ytFJ&v=1
pls help, it's urgent，thks

**Comment by pissang** [comment]
Please use a different `stack` name on the second grid.

**Comment by DorisOu** [comment]
I have solved this problem, this two  stack's should be different.

**Comment by DorisOu** [comment]
tks pissang, yes I just solved this, but also tks your help.
