### ISSUE TITLE
折线图如何加入多个tooltip,并且可以选中过个一块拖动展示，急求

### ISSUE THREAD

**Issue by luanxinwei** [apache/incubator-echarts#9680]
就是可以在曲线图中加入过个tooltip,就是类似于游标一样可以加入多个，可以选中其中的几个来回拖动，并且提示内容也跟着一块改变。正常曲线都是鼠标移动时候才会出现提示框，鼠标移除以后提示框跟着消失，我现在需要满足动态加入提示框，并且可以加入多个，可以一块移动。

**Comment by pissang** [comment]
Please describe your question with more detail.

**Comment by luanxinwei** [comment]
就是可以在曲线图中加入过个tooltip,就是类似于游标一样可以加入多个，可以选中其中的几个来回拖动，并且提示内容也跟着一块改变。正常曲线都是鼠标移动时候才会出现提示框，鼠标移除以后提示框跟着消失，我现在需要满足动态加入提示框，并且可以加入多个，可以一块移动。
