### ISSUE TITLE
[4.2.0][bug]设置legend的背景色backgroundColor，图例依然被覆盖。

### ISSUE THREAD

**Issue by ihwf** [apache/incubator-echarts#9683]
**版本**
[4.2.0]

**重现条件**
legend: {
        data: ['line', 'bar'],
        textStyle: {
            color: ['#fff', '#ccc'],
            backgroundColor: 'rgba(255,0,0,.5)'
        }
},
设置textStyle: {
    color: ['#fff', '#ccc'],
    backgroundColor:'red'
}
主要是color为数组的时候, 同时设置backgroundColor, backgroundColor就会覆盖掉图例

**截图**
![image](https://user-images.githubusercontent.com/17941662/50678478-d38e2800-1039-11e9-96b2-fc9ad2255881.png)

**Comment by Ovilia** [comment]
经测试 4.2.1 版本无法复现
<img width="711" alt="屏幕快照 2019-03-18 下午4 05 45" src="https://user-images.githubusercontent.com/779050/54515838-400d9780-4998-11e9-8147-480870d223ff.png">
