### ISSUE TITLE
urgent： multiple charts in one page,select legend to change the different charts, how to set legend?

### ISSUE THREAD

**Issue by DorisOu** [apache/incubator-echarts#9684]
check the bellow link, I reproduce it in this link.
http://gallery.echartsjs.com/editor.html?c=xgSLl-2GF0&v=1

pls help me to solve this, thks.

**Comment by pissang** [comment]
I modified it a bit http://gallery.echartsjs.com/editor.html?c=xgSLl-2GF0&v=2

**Comment by DorisOu** [comment]
@pissang tks,but i need the lines show it's name when the mouse hover over it,such as in the left chart first line's name is 'iron',second line's name is 'food'. the right chart is the same as the left one.

**Comment by Ovilia** [comment]
@DorisOu What do you mean by "first line's name"? Can you show it in your demo?
