### ISSUE TITLE
饼图，第一个data.value为非数字时，无动画效果

### ISSUE THREAD

**Issue by zhyblack** [apache/incubator-echarts#9688]
option.series[0].data[0].value不为数字，饼图出现无动画效果，
第一个数据的value。

**Comment by pissang** [comment]
Please use number to represent value.

**Comment by zhyblack** [comment]
but i set it null because i want to  hide the zero value in picture and show the zero value int the list of top-left.how to solve it ?thank you !

**Comment by pissang** [comment]
It seems to be a bug. Thanks for the report @zhyblack
