### ISSUE TITLE
treemap resize

### ISSUE THREAD

**Issue by Jwangyi** [apache/incubator-echarts#9691]
## Issue Type

- [x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

resize treeMap  will change its position .

![image](https://user-images.githubusercontent.com/36178291/50746801-d6705f00-126b-11e9-9297-dca79a23266d.png)

![image](https://user-images.githubusercontent.com/36178291/50746813-e12af400-126b-11e9-8696-293f3a345e27.png)

### Expected Behavior

I Hope it will not change  the position and keep  where they were.

## Environment

- ECharts version；ECharts 版本: {4.1.*}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Jwangyi** [comment]
I am sorry for my English .I don't want to change the original position, when I resize the chart.
As shown in figure
" The sitting room should be on the right,After Changing  the browser size,The sitting room is at the bottom.Distribution changed"  This is not what I want.How to don't change the distribution . like a floor plan

**Comment by pissang** [comment]
I think in your scenario `map` is better. Treemap will sort and place each region automatically for better display.
