### ISSUE TITLE
Default value of the radar splitArea show option has to be true in docs.

### ISSUE THREAD

**Issue by algoshipda** [apache/incubator-echarts#9694]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [x] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Default value of the radar splitArea show option has to be true in docs.
See https://ecomfe.github.io/echarts-doc/public/en/option.html#radar.splitArea
and see https://github.com/apache/incubator-echarts/blob/master/src/coord/radar/RadarModel.js#L148

**Comment by Ovilia** [comment]
Thanks! Fixed in https://github.com/ecomfe/echarts-doc/commit/2efb0b18cc364d07a071213d295e5a7f36051a91 .
