### ISSUE TITLE
A little confused

### ISSUE THREAD

**Issue by bolanlaike** [apache/incubator-echarts#9697]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

![image](https://user-images.githubusercontent.com/25760559/50759901-4c42ed80-12a1-11e9-9b76-edece5c1c698.png)

![image](https://user-images.githubusercontent.com/25760559/50759082-f79e7300-129e-11e9-8a47-1b2ebab212e9.png)

**geo.id is a string, but series[i].map.geoIndex is a number. Is it a bug?** 

## Environment

- ECharts version；ECharts 版本: V4.x

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by pissang** [comment]
It's not a bug. `geoIndex` is the index of target geo component described in `geo` property.

**Comment by bolanlaike** [comment]
> It's not a bug. `geoIndex` is the index of target geo component described in `geo` property.

Thanks.
But why when I set geo.id=1, and set geoIndex=1, it doesn't work.
![image](https://user-images.githubusercontent.com/25760559/50807237-7c879c00-1334-11e9-8a43-b9e2008a6801.png)
![image](https://user-images.githubusercontent.com/25760559/50807248-88735e00-1334-11e9-82fd-d4c9612e2492.png)
![image](https://user-images.githubusercontent.com/25760559/50807402-3b43bc00-1335-11e9-9e07-935b3c077fe8.png)

And when I don't set geo.id and set geoIndex=0,it works.
![image](https://user-images.githubusercontent.com/25760559/50807310-d1c3ad80-1334-11e9-821e-8bb6d9864619.png)
![image](https://user-images.githubusercontent.com/25760559/50807390-2535fb80-1335-11e9-8b71-6ae3a60023c3.png)

**Comment by Ovilia** [comment]
You can take `id` as a unique name of geo, while `geoIndex` is the index of the geo if `geo` is an array.

**Comment by bolanlaike** [comment]
> You can take `id` as a unique name of geo, while `geoIndex` is the index of the geo if `geo` is an array.

Oh, I see .Thank you !
