### ISSUE TITLE
Link to the English version of the docs after the project description

### ISSUE THREAD

**Issue by gnijuohz** [apache/incubator-echarts#9699]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [x] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Change the link after project description on Github to the English version of the docs

Currently the link points to the Chinese docs.

### Expected Behavior

Use this link https://echarts.apache.org/index.html instead of http://echarts.baidu.com/ so the project description becomes

> A powerful, interactive charting and visualization library for browser https://echarts.apache.org/index.html

### Current Behavior

Project description is 

> A powerful, interactive charting and visualization library for browser http://echarts.baidu.com/

## Anything Else We Need to Know

ECharts is a very good charting library and I'm sure joining Apache Incubator makes it reach a wider user base. Therefore, I think it makes sense to change the url since it's most likely the thing most users would click on when first checking out the library. So maybe linking to an English version of the docs is better?

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Thanks! Done.
