### ISSUE TITLE
如何实现中国地图中国边界线和海岸线颜色突出

### ISSUE THREAD

**Issue by Evenyoo** [apache/incubator-echarts#9707]
## Issue Type

- [x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

我需要实现类似中国海岸线以及国界线颜色效果，如下：  
![image](https://user-images.githubusercontent.com/24247076/50820146-f0429c80-1366-11e9-8d99-e103767045a9.png)

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
ECharts 不提供地图相关的数据和样式处理，请使用百度地图等底图。

**Comment by Evenyoo** [comment]
谢谢，已经通过一个小技巧实现啦，将两张地图重叠，下面的地图itemStyle边界线宽度设为4，上面的一层将geoIndex设置为10，不设置itemStyle即可，哈哈
