### ISSUE TITLE
How to make the line symbol different for each point and make the mark line style different for each line?

### ISSUE THREAD

**Issue by wmjcom** [apache/incubator-echarts#9709]
I have two requirements.
(1) Make the line symbol different for each point.
     For example, current the line symbol is 'rect' and it is used for all points. How can we set different symbol for each point? I want that point 1 is 'rect' and point 2 is 'circle'.

(2) Make the mark line style different for each mark line.
     For example, current the mark line style is 'solid' and it is used for all lines. How can we set different style for each line? I want that the first mark line is 'solid', the second mark line is 'dashed' and the third mark line is 'dotted'.

This is my codes:
option = {
    xAxis: {    
        type: 'category',
        data: ['Mon', 'Tue', 'Wed']
    },
    yAxis: {
        type: 'value',
    },
    series: [{
        data: [15, 45, 25],
        type: 'line',
        symbol: 'rect',
        symbolSize: 10,
        symbolRotate: 90,
        markLine: {
                silent: true,
                lineStyle: {
                    type:'solid'
                },
                data: [{
                    name: 'LSL',
                    yAxis: 20
                }, {
                    name: 'X',
                    yAxis: 30
                }, {
                    name: 'USL',
                    yAxis: 40
                }]
            }
    }]
};   

Blow is the code result.
![20190108173351](https://user-images.githubusercontent.com/45786005/50822606-13704a80-136d-11e9-8b22-e7099ee00e23.png)

How can I customize the line symbol and the mark line style? Thanks.

**Comment by Ovilia** [comment]
Each element of `series.data` and `markPoint.data` can be an object that contains `itemStyle`, which can override the settings of series and markPoint. Please refer to http://echarts.apache.org/option.html#series-line.data.itemStyle .

**Comment by wmjcom** [comment]
@Ovilia Thanks for supports. It works now.

(1) For the mark line, I add lineStyle.
                   name: 'LSL',
                    yAxis: 20,
                    lineStyle: {
                        type: 'dashed',
                        color: 'blue',
                    },
(2) For the line symbol, I add markPoint.data with different symbol.
        markPoint:{
          data: [
            {
                name: 'one data',
                coord: [1, 45],
                symbol: 'arrow',
                symbolSize: 20,
                symbolRotate: 180,
                itemStyle: {
                    color: 'red'
                }            },
