### ISSUE TITLE
echarts 使用bmap, 如何设置bmap disableDoubleClickZoom()

### ISSUE THREAD

**Issue by Hppyyung** [apache/incubator-echarts#9711]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

### Expected Behavior

百度地图 可以 设置双击无效 

### Current Behavior

设置：
let map = myChart.getModel().getComponent('bmap').getBMap();
 map.disableDoubleClickZoom(); // dont work
 双击仍触发了zoom

## Environment

- ECharts version；ECharts 版本: {4.2.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
请查阅百度地图相关文档
