### ISSUE TITLE
【功能建议】使用echarts绘制拓扑图关系图时，能否在节点附近增加外接圆表示区域的效果？

### ISSUE THREAD

**Issue by lxccc1207** [apache/incubator-echarts#9713]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [x] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

使用echarts绘制拓扑图关系图时，能否在节点附近增加外接圆表示区域的效果？

### Expected Behavior

![_20190109102445](https://user-images.githubusercontent.com/31816546/50872198-86bf9e00-13f9-11e9-9b69-d9bd1ee0e8f2.png)

### Current Behavior

![tim 20190109103029](https://user-images.githubusercontent.com/31816546/50872227-a22aa900-13f9-11e9-9613-7b18b44aac3b.png)

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
4.2.0
- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
不太好实现，需要自己用 [graphic](https://echarts.baidu.com/option.html#graphic.elements) 画，并且需要手动指定位置
