### ISSUE TITLE
How to set the background color of the area inside axises different to all backgrournd color?

### ISSUE THREAD

**Issue by wmjcom** [apache/incubator-echarts#9717]
The property backgroundColor is used to set the background chart for all chart area. Blow is the result. All area is set to yellow. 

I want to set the area inside axis to red and keep the area outside axis to yellow. How to do it? Thanks.

![20190109133050](https://user-images.githubusercontent.com/45786005/50878686-d2cb0c80-1412-11e9-9c86-5adf36fc5e8b.png)

**Comment by Ovilia** [comment]
That should be [grid.backgroundColor](http://echarts.apache.org/option.html#grid.backgroundColor)

**Comment by wmjcom** [comment]
@Ovilia It works with below codes. Thanks.
    grid:{
        backgroundColor: 'white',
        show: true
    },

**Comment by electroheadfx** [comment]
hey, but is it possible to color only the xAxis in black for exemple, like a axis bar with white label text?

**Comment by andyg2** [comment]
> hey, but is it possible to color only the xAxis in black for exemple, like a axis bar with white label text?

You can change anything when you update the chart, this updates the pointer color if the value is over a threshold.

[echarts-apache-editor](https://echarts.apache.org/examples/en/editor.html?c=gauge-simple&code=G4QwTgBALgFmCmBnGB7ANgEwgXggZgAYBuAKFEgGMBXMBAOygH1Q0r4cIBGYs8CAWxAAPDt2IQA9BIhVE7flTRQAlgAc0SCCgBmXAgWgoBIANbsVFE4giJl_dfDC9IsBMnQZGGeBTsg0ovqSEAAUgiLSrkiomACUwWKkJCiqKih0HADeJBAQAEYglgDmYChUdBgAwugoYABcEADkAMTabY0ANJLSAMrwUBAgA6UoAxrA8Gg5No7KSA0A2tO52blrEHQg_PANjQAKbog08J3La1AAnqo7TUUgVEUnHWe5qqUlSIgNq-tr7gDuDSgYDYLwgAF9nr9BkJlIgACrKSzfMG5RDqZRQAByVH4eUcDQArFD1pCXvxlHQGgQSetwg1wrS1t4oCBlGgUdDciw2ABBOh-NJU6Ag-BM9baWqCKBQAlNTI8-DgiB7eApDSNMFk6EYIYgRaoiA_LkQRUNai0eAMZj-Nji36bba7ACKVBADAumpN4LBAF17cI4QAZSk3Y2_NChnqXDSck0Qf7KDCwBqEe3rCg1eoQJbxtYLKLuTBeHx-NBdFoATk4FAA7CATv7uhAAOIIK0QSWQRXWAA8uEIhvWC04Fda2gALIT9I1fc2AErwLBd022zQAPnwBCHEF9hu1XK19tUKEpsuz4fWmPg_GjF1jRp3mbQtV246nM-bABFlAgKANn1qVdWHgfcjzBFQoAfS81kA7MWjwRCvV-H1SWmPdwSSOQoAASQYRwWBCbRyn_ZR0lCeIfkzOhEGGd0MBQfhGDoXF8UgXAAGoQgAWSGGAADowHoxiQniAAqYwhFifioBQAAxZQhCXEICFiJJcn4C5KhgcAoH47CAHlUjIugQnDOQwDmL4czBGDcl1VkDTzOzfjNCAhIqRjmNYxx0wdLYbkaV13UuZDvUNf1DRPM85Rc3Jr1vGMwx3XI4IaDyGKYli8UcCBN0LGIsAAfiad9pwIRoIDfas6wbMKuVQhqtTOPdcnBNSSEhPR9DUoA)
