### ISSUE TITLE
图表很大时，tooltip有时候会超出屏幕，因为tooltip以父类div定位，所以当页面滚动到一定位置时tooltip会超出屏幕

### ISSUE THREAD

**Issue by wangqipov** [apache/incubator-echarts#9720]
图表很大时，tooltip有时候会超出屏幕，因为tooltip以父类div定位，所以当页面滚动到一定位置时tooltip会超出屏幕
![image](https://user-images.githubusercontent.com/25898498/50887007-f307c500-142c-11e9-897c-a020317a9a23.png)

**Comment by cuijian-dexter** [comment]
Do you want to limit tooltip to the area of the chart?
https://echarts.baidu.com/option.html#tooltip.confine
