### ISSUE TITLE
折线图如何加入多个tooltip,并且可以选中多个一块拖动展示，急求

### ISSUE THREAD

**Issue by luanxinwei** [apache/incubator-echarts#9721]
I'd like a new feature
可以在曲线图中加入过个tooltip,就是类似于游标一样可以加入多个，可以选中其中的几个来回拖动，并且提示内容也跟着一块改变。正常曲线都是鼠标移动时候才会出现提示框，鼠标移除以后提示框跟着消失，我现在需要满足动态加入提示框，并且可以加入多个，可以一块移动。 @pissang @100pah

**Comment by Ovilia** [comment]
不支持多个 tooltip，请问应用场景是什么？

**Comment by Ovilia** [comment]
markPoint?

**Comment by Ovilia** [comment]
目前没有计划支持这一功能，有什么通用的场景会需要用到吗？

**Comment by luanxinwei** [comment]
在一些数据分析时会经常使用该功能，类似于下图这种分析，在电力行业分析数据时会经常用到呢
![image](https://user-images.githubusercontent.com/30032313/52615411-1b715c00-2ed0-11e9-800e-6b6378cc6ccf.png)
@Ovilia

**Comment by luanxinwei** [comment]
还有可不可以再帮我看一下 #9831这个问题，谢谢 @Ovilia

**Comment by Ovilia** [comment]
从上面的图看，确实更像是 markLine 的功能，所以你想要的是可以拖动的 markLine 吗？

**Comment by luanxinwei** [comment]
> 从上面的图看，确实更像是 markLine 的功能，所以你想要的是可以拖动的 markLine 吗？

类似的也可以，可以加入多个就更好了。
还想请教一个问题就是：我如何获取选中点的相对坐标
![image](https://user-images.githubusercontent.com/30032313/52831287-0a625e00-310f-11e9-959f-3b43385e448b.png)就是我在调用完tooltip 中formatter方法回调完成后获取选中点的位置坐标
![image](https://user-images.githubusercontent.com/30032313/52831363-5b725200-310f-11e9-99d7-adb4d47ead30.png)

**Comment by Ovilia** [comment]
https://echarts.baidu.com/api.html#echartsInstance.convertToPixel 看看这个是不是你需要的
