### ISSUE TITLE
柱状图叠加问题，当barGap设置为-100%产生叠加效果，如果视图的宽度小的时候会有问题

### ISSUE THREAD

**Issue by jiankebe** [apache/incubator-echarts#9722]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by jiankebe** [comment]
series: [
                            {
                                type: 'bar',
                                barMaxWidth: 16,
                                barMinWidth: 8,
                                barMinHeight: 18,
                                barCategoryGap: 1,
                                itemStyle: {
                                    normal: {
                                        color: '#6BCCB2'
                                    }
                                },
                                data: yData
                            },
                            {
                                type: 'bar',
                                barMaxWidth: 16,
                                barMinWidth: 8,
                                barMinHeight: 18,
                                barCategoryGap: 1,
                                itemStyle: {
                                    normal: {
                                        color: '#47A98E'
                                    }
                                },
                                data: selected
                            },
                            {
                                type: 'bar',
                                barMaxWidth: 16,
                                barMinWidth: 8,
                                barMinHeight: 74,
                                barCategoryGap: 1,
                                itemStyle: {
                                    normal: {
                                        color: '#ff0000',
                                        opacity: 0
                                    }
                                },
                                data: yData
                            }
                        ]
参数设置

**Comment by jiankebe** [comment]
[](url)
<img width="244" alt="wechatimg212" src="https://user-images.githubusercontent.com/7916816/50898343-d5952400-1449-11e9-8950-db6d174869d2.png">

**Comment by Ovilia** [comment]
请在 https://gallery.echartsjs.com/editor.html 复现一下

**Comment by jiankebe** [comment]
https://gallery.echartsjs.com/editor.html?c=xUk6lbVKBp&v=2

缩小右边的范围区域可看到效果

**Comment by tumblingG** [comment]
怎么没解决就关闭了
