### ISSUE TITLE
echarts地图坐标体系采用的是什么坐标体系，如果不是WGS84坐标如何进行转换？

### ISSUE THREAD

**Issue by shanewds** [apache/incubator-echarts#9726]
官网实例图
<img width="722" alt="wx20190110-094922 2x" src="https://user-images.githubusercontent.com/19984920/50940798-50e3ed80-14bd-11e9-9df2-259dec2fba8c.png">

<img width="420" alt="wx20190110-095349 2x" src="https://user-images.githubusercontent.com/19984920/50940882-af10d080-14bd-11e9-8acf-2b20e24b6437.png">

若不是WGS84坐标,如何进行转换？转换公式是？
我给的是WGS84坐标，投放到该图上，若不是，我如何转换。

**Comment by Ovilia** [comment]
具体我不是很清楚，看看这个有没有帮助？https://github.com/apache/incubator-echarts/blob/8eeb7e5abe207d0536c62ce1f4ddecc6adfdf85e/src/util/mapData/rawData/encode.js
@pissang @100pah 回答一下~
