### ISSUE TITLE
Axis text color change api

### ISSUE THREAD

**Issue by luogeng2017** [apache/incubator-echarts#9730]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [x] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

如何动态改变轴文字颜色，比如监听鼠标移入轴文字的事件来改变轴文字的颜色

### Expected Behavior

加入改变轴文字颜色的接口

### Current Behavior

不能改变轴文字颜色或不清楚

### Online Example

none

## Topics

 Check those topics that are related. 选择相关主题。
- [x] Legend
- [ ] Tooltip
- [x] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [x] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

none

## Environment

- ECharts version；ECharts 版本: 4.1.0

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
调用 setOption https://echarts.baidu.com/option.html#yAxis.axisLabel.color

**Comment by luogeng2017** [comment]
这样会不会造成图表的闪烁（重绘）?

**Comment by Ovilia** [comment]
目前没法得到移到轴文字的事件。之后会增强一下，关注 #3853 。
闪烁应该不会的。

**Comment by luogeng2017** [comment]
好的，谢谢您的解答！
