### ISSUE TITLE
安卓环境截图必须关闭硬件加速，否则截图空白

### ISSUE THREAD

**Issue by TobyCheung** [apache/incubator-echarts#9731]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

安卓环境截图必须关闭硬件加速，否则截图空白

### Expected Behavior

安卓环境关闭硬件加速后可以截取到图表

### Current Behavior

安卓环境关闭硬件加速后无法截取到图表

### Online Example

import Echarts from 'native-echarts';
import ViewShot from 'react-native-view-shot';

Let option = {"tooltip":{"trigger":"axis"},"legend":{"data":[{"name":"日低点($)","icon":"circle"},{"name":"开盘价($)","icon":"circle"},{"name":"收盘价($)","icon":"circle"}],"itemWidth":8,"itemHeight":8,"itemGap":15,"top":15},"color":["#008610","#fe4c2c","#33bbff"],"grid":{"top":50,"left":50,"bottom":40,"right":25},"xAxis":{"type":"category","boundaryGap":false,"data":["10-11","10-12","10-15","10-16","10-18","10-19","10-22","10-23","10-24","10-25","10-26","10-29","10-30","10-31","11-01","11-02","11-05","11-06","11-07","11-08","11-09","11-12","11-13","11-14","11-15","11-16","11-19","11-20","11-21","11-22","11-23","11-26","11-27","11-28","11-29","11-30","12-03","12-04","12-05","12-06","12-07","12-10","12-11","12-12","12-13","12-14","12-17","12-18","12-19","12-20","12-21","12-24","12-27","12-28","12-31","01-02","01-03","01-04","01-07","01-08","01-09"],"splitNumber":5,"splitLine":{"show":true}},"yAxis":[{"type":"value","min":2.01,"max":"3.99","interval":0.33,"axisLabel":{}}],"series":[{"name":"日低点($)","type":"line","data":[3.5,3.5,3.5,3.5,3.4,3.4,3.4,3.4,3.35,3.35,3.35,3.35,3.3,3.3,3.3,3.3,3.25,3.2,3.2,3.2,3.1,3.1,3.1,3.05,3.05,3.05,3.05,3.05,3,3,3,3,3,3,3,3,3,2.98,2.98,2.98,2.97,2.97,2.97,2.97,2.97,2.97,2.95,2.94,2.94,2.92,2.9,2.9,2.88,2.85,2.8,2.7,2.6,2.6,2.6,2.6,2.6],"symbol":"circle","symbolSize":4,"itemStyle":{"normal":{"lineStyle":{"width":1}}}},{"name":"开盘价($)","type":"line","data":[3.55,3.5,3.5,3.5,3.5,3.4,3.4,3.4,3.35,3.35,3.35,3.35,3.3,3.3,3.3,3.3,3.25,3.2,3.2,3.2,3.15,3.1,3.1,3.05,3.05,3.05,3.05,3.05,3.02,3,3,3,3,3,3,3,3,2.98,2.98,2.98,2.97,2.97,2.97,2.97,2.97,2.97,2.97,2.94,2.94,2.92,2.92,2.9,2.88,2.85,2.8,2.75,2.65,2.6,2.6,2.6,2.6],"symbol":"circle","symbolSize":4,"itemStyle":{"normal":{"lineStyle":{"width":1}}}},{"name":"收盘价($)","type":"line","data":[3.5,3.5,3.5,3.5,3.4,3.4,3.4,3.4,3.35,3.35,3.35,3.35,3.3,3.3,3.3,3.3,3.25,3.2,3.2,3.2,3.1,3.1,3.1,3.05,3.05,3.05,3.05,3.05,3,3,3,3,3,3,3,3,3,2.98,2.98,2.98,2.97,2.97,2.97,2.97,2.97,2.97,2.95,2.94,2.94,2.92,2.9,2.9,2.88,2.85,2.8,2.7,2.6,2.6,2.6,2.6,2.6],"symbol":"circle","symbolSize":4,"itemStyle":{"normal":{"lineStyle":{"width":1}}}}],"animation":false};

let priceTrend = (
    <View style={styles.priceTrend} collapsable={false}>
        <SectionHeader
            title={'价格走势'}
            rightView={
                <ScrollableTabBar
                    ref={(scrollableTabBar) => this.scrollableTabBar = scrollableTabBar}
                    tabs={this.priceTrendTabs}
                    activeTab={this.trendRange}
                    activeTextColor={'#24b5fe'}
                    inactiveTextColor={'#4c4c4c'}
                    fontSize={scaleSize(28)}
                    onTabClick={(index) => {
                        this._onTrendTabClick(index)
                    }}
                    containerWidth={screenW - 135}
                    containerHeight={scaleSize(93)}
                    scrollEnabled={false}
                />
            }
        />
        <Line/>
        <Echarts option={option} height={scaleSize(500)} width={screenW}/>
    </View>
)

let shareBoard = (
	<ScrollView style={{width:screenW + realSize(80), height: 0.5}} >
		<ViewShot
                  ref={r => this.shareView = r}
                  options={{format:"jpg", quality:1.0}}
              >
			<View
				style={{
					width:screenW + realSize(80),
					alignItems: 'center',
					paddingLeft:realSize(40),
					paddingRight:realSize(40),
					backgroundColor:'#ebf2fd'
				}}
			>
				<Image source={Images.information.message_share01}
					   style={{width:realSize(270), height:realSize(65), marginTop:realSize(60), marginBottom:realSize(60)}}/>
				<View style={{
					width:screenW,
					paddingTop:scaleSize(20),
					paddingBottom:scaleSize(20),
					borderRadius:scaleSize(20),
					borderWidth: scaleSize(4),
					borderColor:'#e5ebf6',
					backgroundColor:'#fafcff'
					// backgroundColor:'#f4f5f7'
				}}>
					<SectionHeader title={this.productType}/>
					<Line/>
					{topViewShare}
					<Line style={{marginTop: scaleSize(15)}} width={screenW - scaleSize(80)} height={realSize(1)}
						  color={'#f2f2f2'}
						  leftSpace={scaleSize(40)}/>
					{priceView}
					<Line style={{marginTop: scaleSize(10)}} width={screenW - scaleSize(80)} height={realSize(1)}
						  color={'#f2f2f2'}
						  leftSpace={scaleSize(40)}/>
					{priceView1}
					{priceTrend}
				</View>
				<View style={{
					width:screenW,
					height:scaleSize(220),
					backgroundColor:'#fafcff',
					marginTop:scaleSize(60),
					marginBottom:scaleSize(40),
					borderRadius:scaleSize(20),
					borderWidth: scaleSize(4),
					borderColor:'#e5ebf6',
					flexDirection: 'row',
					alignItems: 'center',
					justifyContent: 'space-between',
					paddingLeft: scaleSize(20),
					paddingRight: scaleSize(20),
				}}>
					<Image source={Images.information.message_share03} style={{width:scaleSize(508), height:scaleSize(140)}}/>
					<Image source={Images.information.message_qrCode} style={{width:scaleSize(140), height:scaleSize(140)}}/>
				</View>
				<Image source={Images.information.message_share04}
					   style={{width:scaleSize(600), height:scaleSize(32), marginBottom:scaleSize(40)}}
					   resizeMode={'contain'}/>
			</View>
		</ViewShot>
          </ScrollView>
);

_shareIOS = () => {
	this.shareView.capture()
           .then(uri => {
               console.log('uri:'+uri);
			let imgUrl = '';
			if (isIOS) {
				imgUrl = uri;
			} else {
				imgUrl = uri.replace('file:///', '/');
			}
			let text = '';
			let img = imgUrl;
			let title = '';
			let url = '';
			let list = [0, 2, 3, 32, 1];

			UMShareUtil.shareboard(text, img, url, title, list, (code, message) => {
				// Alert.alert(message);
			});
           })
		.catch(
			(error) => alert(error)
		);
};

## Anything Else We Need to Know

在我的安卓应用中(准确地说是ReactNative项目)需要将使用eCharts的页面截图分享出去，如果不关闭安卓设备硬件加速则截取到的图表部分显示空白，关闭硬件加速后可以截取到图表。问题是，关闭硬件加速后会导致应用中其他使用webView显示的页面滑动卡顿，想请教是否有不关闭安卓设备硬件加速而又可以截取到图表的方法，谢谢。

## Environment

- ECharts version；ECharts 版本:0.4.0

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：Android 6.0+

**Comment by Ovilia** [comment]
请到 native-echarts 提问~
