### ISSUE TITLE
默认颜色能否设置顺寻-Default color can be set to follow

### ISSUE THREAD

**Issue by acc-674e-4e50** [apache/incubator-echarts#9733]
在不设置颜色的情况下会自适应颜色，自适应颜色的顺序能否设置。

可能会出现不确定折线图条数的情况，直接默认颜色的话显示的颜色并不是客户所需要的颜色

Adaptive colors can be set without setting the color. Can the order of adaptive colors be set?
There may be an uncertain number of broken line chart, the color shown is not the color the customer needs if the color is the default color

**Comment by Ovilia** [comment]
https://echarts.baidu.com/option.html#color Is this what you want?

**Comment by lduhejian** [comment]
https://echarts.apache.org/en/option.html#color
