### ISSUE TITLE
桑基图能实现从中间流向两边吗

### ISSUE THREAD

**Issue by lishuai1021** [apache/incubator-echarts#9734]
## Issue Type

- [ x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

桑基图中间向左向右双向流，中间一个类别的节点分成两块，分别代表流向两边

### Expected Behavior

中间代表启始节点，两边是终点节点，中间流向两边。

### Current Behavior

中间节点数据是流向两边数据的总和，不能拆分

## Environment
window10
- ECharts version；ECharts 版本: {ehcarts4}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
好像没有看到过这样的图，有应用场景吗？

**Comment by lishuai1021** [comment]
全国异地就诊，中间节点是疾病类型，两边节点分别代表某种疾病各省市流出和流入的情况

**Comment by lishuai1021** [comment]
> 好像没有看到过这样的图，有应用场景吗？

**Comment by ceerqingting** [comment]
同问
