### ISSUE TITLE
option/tooltip/legend/selected 无法国际化处理

### ISSUE THREAD

**Issue by luo772435545** [apache/incubator-echarts#9735]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

option/tooltip/legend/selected 无法国际化处理 因为显示的为key值

### Expected Behavior

selected 使用value值控制

### Online Example

 legend: {
         selected: {
            '中文': true,
            '中文1': false
          }
        },

**Comment by Ovilia** [comment]
You may use [English version](https://github.com/apache/incubator-echarts/tree/master/dist). Or overwrite Chinese text. What part to you want to change exactly?

**Comment by luo772435545** [comment]
key值为中文无法国际化；
The key ('中文') cannot be internationalized in Chinese
legend: {
   selected: {
      '中文': true,
      '中文1': false
}
}

**Comment by Ovilia** [comment]
@luo772435545 This key is passed by user. You may use English if you wish.

**Comment by luo772435545** [comment]
@Ovilia 您考虑问题的方式真的。。。打扰了
