### ISSUE TITLE
折线图多条线数据处理问题

### ISSUE THREAD

**Issue by webxiaobian** [apache/incubator-echarts#9737]
在使用折线图时 我发现echarts和antv对比以后，发现如果数据中的点和时间是对应的 但是 在某类数据中可能不会返回这个时间点的数据 而是返回了一个其他时间点的数据。这个时候渲染处理数据应该怎么做呢？
const data = [
  { type: '序列1', year: '1991', value: 3 },
  { type: '序列1', year: '1992', value: 4 },
  { type: '序列1', year: '1993', value: 3.5 },
  { type: '序列1', year: '1994', value: 5 },
  { type: '序列1', year: '1995', value: 4.9 },
  { type: '序列1', year: '1996', value: 6 },
  { type: '序列1', year: '1997', value: 7 },
  { type: '序列1', year: '1998', value: 9 },
  { type: '序列1', year: '1999', value: 13 },
  { type: '序列2', year: '1991', value: 6 },
  { type: '序列2', year: '1992', value: 8 },
  { type: '序列2', year: '1993', value: 5.5 },
  { type: '序列2', year: '1994', value: 7 },
  { type: '序列2', year: '1995', value: 9.9 },
  { type: '序列2', year: '1996', value: 6 },
  { type: '序列2', year: '1997', value: 5 },
  { type: '序列2', year: '2000', value: 10 },
  { type: '序列2', year: '1999', value: 19 },
  { type: '序列3', year: '1991', value: 2 },
  { type: '序列3', year: '1992', value: 6 },
  { type: '序列3', year: '1993', value: 9 },
  { type: '序列3', year: '1994', value: 10 },
  { type: '序列3', year: '1995', value: 15 },
  { type: '序列3', year: '1996', value: 8 },
  { type: '序列3', year: '1997', value: 5 },
  { type: '序列3', year: '1998', value: 4.6 },
  { type: '序列3', year: '2000', value: 4 },
];

![image](https://user-images.githubusercontent.com/37388788/51027248-50d21380-15cb-11e9-9d6a-9c5132838391.png)
应该是要像这样的展示

**Comment by Ovilia** [comment]
Please provide a running example at http://gallery.echartsjs.com/editor.html
