### ISSUE TITLE
echarts可以实现这种效果吗？没看到demo

### ISSUE THREAD

**Issue by mlyknown** [apache/incubator-echarts#9738]
类似于傅里叶变换的效果，比如
![download 1](https://user-images.githubusercontent.com/12880984/51027152-21230b80-15cb-11e9-9b9b-a34c1ec6b800.jpeg)

![worddav06c6196a8e43e9b9255d34a595fb07cf](https://user-images.githubusercontent.com/12880984/51023149-2aa77600-15c1-11e9-9d08-eadfaa569b01.png)

**Comment by Ovilia** [comment]
See an example here: https://echarts.baidu.com/examples/editor.html?c=scatter3D-dataset&gl=1
