### ISSUE TITLE
Why doesn't the tooltip show in the heatmap?

### ISSUE THREAD

**Issue by bolanlaike** [apache/incubator-echarts#9739]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

**I draw a heatmap and lines on the baidu map,but tooltip doesn't work in the heatmap while works in the lines.**
It works in the lines.
![image](https://user-images.githubusercontent.com/25760559/51036476-365a6300-15e8-11e9-880a-5298abc893e8.png)
It doesn't work in the heatmap
![image](https://user-images.githubusercontent.com/25760559/51036556-6dc90f80-15e8-11e9-8025-7016fbb47a0a.png)

![image](https://user-images.githubusercontent.com/25760559/51036682-c7313e80-15e8-11e9-9bd2-77bcdf3ed901.png)
![image](https://user-images.githubusercontent.com/25760559/51036695-d3b59700-15e8-11e9-83ee-22b7d4f704c2.png)

Hope you can help me,please!

## Environment

- ECharts version；ECharts 版本: v4.x

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Yes, heatmap doesn't support tooltip.
