### ISSUE TITLE
次x坐标轴怎么实现

### ISSUE THREAD

**Issue by Cyycl** [apache/incubator-echarts#9740]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

双x轴，次x轴是对上一级x轴数据的分类

### Expected Behavior

类似antv的效果。https://antv.alipay.com/zh-cn/g2/3.x/demo/column/column13.html

### Online Example

https://antv.alipay.com/zh-cn/g2/3.x/demo/column/column13.html

## Environment

- ECharts version；ECharts 版本: 4.1.3

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
https://gallery.echartsjs.com/editor.html?c=xR9ug3y7FY

**Comment by Cyycl** [comment]
@Ovilia , 你的例子是固定间隔的，我这边想自定义合并。按照你给的example，写了一个例子，但是有两个问题：
1. 分割线，分割不正确；
2. 次类目轴，合并后，label名称怎么能够置中
例子：https://codepen.io/AliJser/pen/maogyj
想实现的目标：'2017Q1', '2017Q2', '2017Q3', '2017Q4' 归到 类目1，其他归到 类目2

谢谢~~

**Comment by 100pah** [comment]
https://gallery.echartsjs.com/editor.html?c=xR9ug3y7FY

**Comment by Cyycl** [comment]
@100pah , 非常感谢！但是例子在echart v4.2.0 下，有一个问题，x轴的分割刻度线没有了，在data里设置了值，但是分割刻度线分割区域不对，例子链接：
https://codepen.io/AliJser/pen/xMbqae

谢谢~~

**Comment by 100pah** [comment]
Sorry that is a bug in `4.2.0-rc.1`. 
Please use `4.2.1-rc.1` instead.

**Comment by liqiuqiui** [comment]
> [@Ovilia](https://github.com/Ovilia) , 你的例子是固定间隔的，我这边想自定义合并。按照你给的example，写了一个例子，但是有两个问题：
> 
> 1. 分割线，分割不正确；
> 2. 次类目轴，合并后，label名称怎么能够置中
>    ——————————————————————
>    例子：https://codepen.io/AliJser/pen/maogyj
>    想实现的目标：'2017Q1', '2017Q2', '2017Q3', '2017Q4' 归到 类目1，其他归到 类目2
> 
> 谢谢~~

哈喽，请问次类目轴合并且lebel居中这个功能有实现吗
