### ISSUE TITLE
横坐标密集时展示不全

### ISSUE THREAD

**Issue by zhans1099** [apache/incubator-echarts#9745]
### One-line summary [问题简述]
当横坐标很密集、而且宽度不够宽时不会展示倒数第二个，哪怕把字体大小改到1也不行。
比如参见配置中的宽度小于1580时，第49就看不见  缩小字体也不行

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0
+ Browser version [浏览器类型和版本]: 版本 70.0.3538.77 （64 位）
+ OS Version [操作系统类型和版本]:  Mac OS 10.14.1

### Expected behaviour [期望结果]
disabled中的属性禁止点击操作

### ECharts option [ECharts配置项]

```javascript
参见配置
option = {
	"animation": false,
	"tooltip": {},
	"grid": {
		"left": "40px",
		"right": "30px"
	},
	"xAxis": {
		"splitNumber": 50,
		"axisLabel": {
			"rotate": 0,
			"fontSize": 10
		}
	},
	"axisLabel": {
		"showMaxLabel": true
	},
	"yAxis": {
		"splitLine": {
			"show": false
		},
		"type": "value",
		"name": "Kr"
	},
	"series": [{
		"lineStyle": {
			"color": "#3398DB"
		},
		"itemStyle": {},
		"symbol": "circle",
		"showAllSymbol": true,
		"data": [
			[1, 0.41],
			[2, 0.52],
			[3, 0.56],
			[4, 0.57],
			[5, 0.45],
			[6, 0.54],
			[7, 0.68],
			[8, 0.67],
			[9, 0.59],
			[10, 0.64],
			[11, 0.49],
			[12, 0.66],
			[13, 0.75],
			[14, 0.67],
			[15, 0.67],
			[16, 0.74],
			[17, 0.82],
			[18, 0.72],
			[19, 0.82],
			[20, 0.88],
			[21, 0.84],
			[22, 0.88],
			[23, 0.86],
			[24, 0.85],
			[25, 0.85],
			[26, 1.47],
			[27, 1.41],
			[28, 1.49],
			[29, 1.49],
			[30, 1.4],
			[31, 1.36],
			[32, 1.36],
			[33, 1.29],
			[34, 1.32],
			[35, 1.31],
			[36, 1.33],
			[37, 1.31],
			[38, 1.3],
			[39, 1.25],
			[40, 1.12],
			[41, 1.21],
			[42, 1.23],
			[43, 1.31],
			[44, 1.3],
			[45, 1.32],
			[46, 1.36],
			[47, 1.2],
			[48, 1.26],
			[49, 1.31],
			[50, 1.16]
		],
		"type": "line",
		"smooth": true,
		"markLine": {
			"lineStyle": {
				"color": "#ff0700",
				"type": "solid"
			},
			"data": [{
				"yAxis": 1.25,
				"name": "警戒值"
			}]
		}
	}],
	"title": {
		"text": "曲线图",
		"left": "center"
	}
};


```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/6141342/51085361-b01e5800-1772-11e9-8016-854fad5b1fbe.png)

**Comment by Ovilia** [comment]
[interval](https://echarts.baidu.com/option.html#xAxis.interval) 设为0，并且使用最新版 ECharts。

**Comment by zhans1099** [comment]
> [interval](https://echarts.baidu.com/option.html#xAxis.interval) 设为0，并且使用最新版 ECharts。

xAxis.interval 设为了0横坐标就都看不到了；
![image](https://user-images.githubusercontent.com/6141342/51151223-0390c300-18a5-11e9-88bd-20c8630bdc3c.png)

如果把xAxis.splitNumber 去掉，xAxis.interval 设置为1，效果也是49看不到。

版本使用的是官网后台下载的 4.2.0-rc 完整版，最新版本不是这个？
![image](https://user-images.githubusercontent.com/6141342/51151386-a34e5100-18a5-11e9-8af2-0ec119a2ba48.png)

**Comment by xinzai2014** [comment]
我看 没有这个问题
![tim 20190117121532](https://user-images.githubusercontent.com/24290736/51295258-b9991000-1a51-11e9-860f-f1c531ca2f0d.png)
