### ISSUE TITLE
数据过大，分批加载

### ISSUE THREAD

**Issue by Axiaomo** [apache/incubator-echarts#9746]
散点图，数据过大，想开始定再某个时间段，然后通过左右拉动变换时间轴，加载新的数据？目前，可以实现吗

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by cuijian-dexter** [comment]
`appendData ` can load data in fragments and incremental rendering
https://echarts.baidu.com/api.html#echartsInstance.appendData

**Comment by deqingli** [comment]
@Axiaomo  sorry, I can't understand you. It will be better if you can provide a more detailed message, such as an image or demo.

**Comment by Axiaomo** [comment]
like this one ,i want ajax only loading "2019/01/09-2019/01/11" json
if left ,ajax loading Other time periods json"2019/01/01-2019/01/09".
Oh~,my English is terrible. I hope you can understand it.
![image](https://user-images.githubusercontent.com/22358671/51101831-5cb21580-1817-11e9-9470-6b9c333e4dca.png)

**Comment by Ovilia** [comment]
Seems not possible right now. Because when data is not loaded, you cannot have a preview in dataZoom.
