### ISSUE TITLE
react中使用echarts4.x visualMap 折线分段显示颜色设置的不起作用

### ISSUE THREAD

**Issue by dongkang1993** [apache/incubator-echarts#9755]
哪位大佬求告知配置哪里出错

> const option = {
    grid: {
      containLabel: true,
      left: 10,
      right: 10,
    },
    xAxis: {
      type: 'category',
      axisLabel: {
        show: false,
      },
      data: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
        '21', '22', '23', '24', '25', '26', '27', '28', '29', '30'],
      splitLine: {
        show: true,
        lineStyle: {
          color: 'rgb(237, 232, 249)',
        },
      },
      axisLine: {
        lineStyle: {
          color: 'rgb(237, 232, 249)',
        },
      },
    },
    yAxis: {
      type: 'value',
      axisLine: {
        lineStyle: {
          color: 'rgb(237, 232, 249)',
        },
      },
      axisLabel: {
        color: 'rgba(145,145,145,1)',
      },
    },
    series: [{
      data: [1820, 932, 1901, 2934, 1290, 1330, 320, 423, 1289, 2345, 2235, 3234, 2725, 234, 123, 1465, 67, 78, 435, 824, 354, 546, 446, 346, 46, 673, 36, 903, 2896, 3534],
      type: 'line',
    }],
    visualMap: [
      {
        pieces: [{
          gt: 0,
          lte: 1000,
          color: '#673CD1',
        }],
        outOfRange: {
          color: '#7e0023',
        },
      }
    ],
  }

[https://codesandbox.io/s/wn71qo10ll](url)

**Comment by anbee** [comment]
请问最后问题解决了吗？我现在也遇到了相似的问题

**Comment by dongkang1993** [comment]
![image](https://user-images.githubusercontent.com/20965177/53727772-fe66f200-3eab-11e9-9a13-a58413ec390f.png)
，要引入visulmap @anbee
