### ISSUE TITLE
> 请问 你们这个问题解决了吗？

### ISSUE THREAD

**Issue by sannai** [apache/incubator-echarts#9756]
> 请问 你们这个问题解决了吗？
1.修改源码
nodemodules-echarts-lib-data-Graph.js中graphProto.addEdge：
if (edgesMap[key]) {
  return;
}
return注释掉
2.代码中曲度改用随机
curveness: Math.random()

_Originally posted by @HowToMeetYou in https://github.com/apache/incubator-echarts/issues/6811#issuecomment-451900942_

**Comment by HowToMeetYou** [comment]
我猜你只是在setOption中加了curveness: Math.random()
要在每个点的属性中都加上curveness
图等下

**Comment by HowToMeetYou** [comment]
![default](https://user-images.githubusercontent.com/41479550/51165705-1e325e80-18dc-11e9-84e5-3584fbca3a53.png)
