### ISSUE TITLE
Is there a way to use superindexes and subindexes on labels?

### ISSUE THREAD

**Issue by pauturvalles** [apache/incubator-echarts#9760]
Because I am trying to write as labels the mathematical units of some measures, and I would need to write some squared meters as "m2" but with the 2 as superindex instead.

**Comment by deqingli** [comment]
@pauturvalles  sorry, I am confused about what you want? It would be better if you can provide a picture/demo about what effect you want.

**Comment by pauturvalles** [comment]
Reopened

**Comment by Ovilia** [comment]
I'm afraid this feature is somewhat off the topic that ECharts should provide. So sorry it may not in our next plans.
