### ISSUE TITLE
仪表盘title和detail设置颜色有冲突

### ISSUE THREAD

**Issue by miaocunzhi** [apache/incubator-echarts#9762]
环境：官方仪表盘示例
操作：把仪表盘的title和detail两者的color，设置为一样的颜色，detail文字会消失。
譬如：同时为#000等（注：一个为#000另一个为#000000是不会消失的）
![1547608543](https://user-images.githubusercontent.com/20124199/51224302-32c83280-1980-11e9-9852-42ec90626589.jpg)
![1547608543 1](https://user-images.githubusercontent.com/20124199/51224306-3491f600-1980-11e9-8cf3-3eb1764d7a7c.jpg)

**Comment by deqingli** [comment]
@miaocunzhi  This is a bug, Thank you for your feedback.

**Comment by deqingli** [comment]
@miaocunzhi  This is a bug, Thank you for your feedback.
