### ISSUE TITLE
angleAxis.triggerEvent =true无效 

### ISSUE THREAD

**Issue by fuyongxia** [apache/incubator-echarts#9765]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

angleAxis.triggerEvent =true无效

### Expected Behavior

angleAxis.triggerEvent =true无效 的问题在哪，是库本身就有问题吗

### Online Example

https://gallery.echartsjs.com/editor.html?c=xINzhTRaHL&v=1

 app.title = '极坐标系下的堆叠柱状图';

option = {
    angleAxis: {
        type: 'category',
        triggerEvent: true,
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
        z: 10
    },
    radiusAxis: {
        //  triggerEvent: true,

    },
    polar: {
        triggerEvent: true,

    },
    series: [{
        type: 'bar',
        data: [1, 2, 3, 4, 3, 5, 1],
        coordinateSystem: 'polar',
        name: 'A',
        stack: 'a'
    }, {
        type: 'bar',
        data: [2, 4, 6, 1, 3, 2, 1],
        coordinateSystem: 'polar',
        name: 'B',
        stack: 'a'
    }, {
        type: 'bar',
        data: [1, 2, 3, 4, 1, 2, 5],
        coordinateSystem: 'polar',
        name: 'C',
        stack: 'a'
    }],
    legend: {
        show: true,
        data: ['A', 'B', 'C']
    }
};

## Environment

- ECharts version；ECharts 版本: {v4.2.0-rc.2}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{chrome}

**Comment by peter-wang-wsl** [comment]
@100pah 关闭的bug的说明是什么？解决了吗？在哪个版本解决的？

**Comment by peter-wang-wsl** [comment]
@100pah @deqingli 
`myChart.on('click','angleAxis.axisLabel',function(){
    alert(1)
})
`

**Comment by fuyongxia** [comment]
关闭的bug解决的是angleAxis.triggerEvent =true无效,不识别鼠标事件，只在master分支上做了更改，可以查看fix 9765，release版本似乎是没有更新的




------------------ 原始邮件 ------------------
发件人: "peter-wang-wsl"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 上午10:48
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "小霞"<1101152873@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] angleAxis.triggerEvent =true无效  (#9765)




@100pah 关闭的bug的说明是什么？解决了吗？在哪个版本解决的？

**Comment by peter-wang-wsl** [comment]
@fuyongxia 请问我把github上的工程下载后，如何在本地dist目录生成基于master的echarts.js?

**Comment by fuyongxia** [comment]
npm run prepublish




------------------ 原始邮件 ------------------
发件人: "peter-wang-wsl"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 中午12:50
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "小霞"<1101152873@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] angleAxis.triggerEvent =true无效  (#9765)




@fuyongxia 请问我把github上的工程下载后，如何在本地dist目录生成基于master的echarts.js?

**Comment by peter-wang-wsl** [comment]
@fuyongxia 十分感谢，dist文件夹内文件没有更新...

**Comment by fuyongxia** [comment]
你先确定你本地的开源代码是新版本的，对比一下src/component/axis/AngleAxisView.js 这个文件有没有import AxisBuilder from './AxisBuilder';  然后再确定是在echarts项目下进行npm run prepublish的吗




------------------ 原始邮件 ------------------
发件人: "peter-wang-wsl"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 下午2:06
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "小霞"<1101152873@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] angleAxis.triggerEvent =true无效  (#9765)




@fuyongxia 十分感谢，dist文件夹内文件没有更新...

**Comment by peter-wang-wsl** [comment]
![图片](https://user-images.githubusercontent.com/15857181/56943696-43796e80-6b53-11e9-855e-013573bde754.png)
运行报错，npm install fs-extra还报错...

**Comment by fuyongxia** [comment]
https://github.com/apache/incubator-echarts/issues/9774   看下我之前提的这个问题，是因为z-render这个包的问题，用它修复后的包

------------------ 原始邮件 ------------------
发件人: "peter-wang-wsl"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 下午2:24
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "小霞"<1101152873@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] angleAxis.triggerEvent =true无效  (#9765)





 运行报错，npm install fs-extra还报错...

**Comment by peter-wang-wsl** [comment]
我使用echarts master和zrender master重新编译了，但形如myChart.on('click','angleAxis.category',function(){ alert(1) }) 没有被触发，已提 #10382
