### ISSUE TITLE
xAxis.axisLabel.formatter: '{value}' show index of element in xAxis.data

### ISSUE THREAD

**Issue by cheqianxiao** [apache/incubator-echarts#9767]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

`xAxis.axisLabel.formatter: '{value}'` not working as described in docs

### Expected Behavior

show  the default label of xAxis

### Current Behavior

show index of element in xAxis.data

### Online Example

[https://codepen.io/oobakoyo/pen/magydK](https://codepen.io/oobakoyo/pen/magydK)

## Environment

- ECharts version；ECharts 版本: 4.1.0

- [] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
@cheqianxiao  I have tested it in our [official example](https://echarts.baidu.com/examples/editor.html?c=bar-simple) and it works well, you can try it.

**Comment by Ovilia** [comment]
@cheqianxiao So I guess this is solved? Feel free to re-open if you still have a problem.
