### ISSUE TITLE
tooltip 溢出边界 可不可以scrollable （How to make the echarts tooltip scrollable? ）

### ISSUE THREAD

**Issue by Aslantoe** [apache/incubator-echarts#9768]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
Please provide a detailed message, such as an image or demo.

**Comment by Aslantoe** [comment]
![4vlt 4u8m0slk_ 64 5teo](https://user-images.githubusercontent.com/18546413/51313153-d51f0d80-1a87-11e9-94c2-86d64e8a0a63.png)

**Comment by Aslantoe** [comment]
> Please provide a detailed message, such as an image or demo.

**Comment by Aslantoe** [comment]
> Please provide a detailed message, such as an image or demo.
![51313153-d51f0d80-1a87-11e9-94c2-86d64e8a0a63](https://user-images.githubusercontent.com/18546413/54123570-0f2edf00-443b-11e9-84ab-0fae79681016.png)

BROWSER_VERSION：google chrome  72.0.3626.121
浏览器版本：谷歌浏览器 72.0.3626.121
