### ISSUE TITLE
迁徙图动画不流畅问题

### ISSUE THREAD

**Issue by saojun1024** [apache/incubator-echarts#9771]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

迁徙图特效会出现不连续现象  

![image](https://user-images.githubusercontent.com/24247076/51290578-07584d00-1a3f-11e9-9097-6eb2303b8b91.png)

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
@Evenyoo  please provide detailed environment message.

**Comment by alex2wong** [comment]
@saojun1024  I am not sure how you make line trail, maybe you use customized symbol in effectLine layer.
[An enhancement](https://github.com/apache/incubator-echarts/pull/11893) in effect line has been included in master branch, which can be tested in next release. you guys can have a try, thanks.
hence close the issue, if any issue still exist, feel free to reopen it.
