### ISSUE TITLE
仪表盘图中设置axisTick.splitNumber左上角有异常显示

### ISSUE THREAD

**Issue by vision-yip** [apache/incubator-echarts#9776]
官方示例中: https://echarts.baidu.com/examples/editor.html?c=gauge
option = {
    tooltip : {
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            restore: {},
            saveAsImage: {}
        }
    },
    series: [
        {
            name: '业务指标',
            type: 'gauge',
           // 此处为添加项
           axisTick: {
                splitNumber: 0
            },
            detail: {formatter:'{value}%'},
            data: [{value: 50, name: '完成率'}]
        }
    ]
};

setInterval(function () {
    option.series[0].data[0].value = (Math.random() * 100).toFixed(2) - 0;
    myChart.setOption(option, true);
},2000);

**Comment by cuijian-dexter** [comment]
It does show an exception.
you can set `axisTick.show` and `splitLine.show` to `false`
