### ISSUE TITLE
【bug】 当动态折线图数据更新时，鼠标hover时应该高亮的点不会高亮，请及时修复

### ISSUE THREAD

**Issue by kxcc** [apache/incubator-echarts#9779]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

当动态折线图数据更新时，恰好鼠标hover未动，应该高亮的点不会高亮

### Expected Behavior

期望当数据更新后，鼠标不需要移动，高亮原本高亮的数据点。

### Current Behavior

当动态折线图数据更新前，恰好鼠标hover，有tooltip显示，axisPointer所在的数据点会高亮显示。
此时如果用户在查看tooltip内容，保持鼠标不动。
当动态折线图数据更新后，鼠标未动，有tooltip显示，但是axisPointer所在的数据点 没有 高亮显示，需要鼠标大幅移动，重新回到该位置，数据点才会高亮。

### Online Example

官网的demo可直接观察到有该现象

https://echarts.baidu.com/examples/editor.html?c=dynamic-data2

请参考官网demo
https://echarts.baidu.com/examples/editor.html?c=dynamic-data2

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
所有ECharts均有该问题。
- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by changingshow** [comment]
我也遇到了类似的问题，我的需求是动态改变柱子颜色，如果鼠标落在某个柱子上，该柱子就不会变颜色，除非移走鼠，等待下次更新数据才会变，具体事例见：
https://gallery.echartsjs.com/editor.html?c=xQQQcc5ZCJ&comment=0

**Comment by 100pah** [comment]
It has been fixed and will be released this week.

**Comment by kxcc** [comment]
发布后，请在此回复已解决该问题的版本号

**Comment by changingshow** [comment]
> It has been fixed and will be released this week.

thank you，waiting the new version。

**Comment by 100pah** [comment]
Fixed in version `4.2.1-rc.1`.
