### ISSUE TITLE
nodes exceed the canvas in force layout graph

### ISSUE THREAD

**Issue by JohnForYang** [apache/incubator-echarts#9785]
how can I limit all the nodes in the div canvas whatever the force.repulsion and force.edgeLength is.

**Comment by sunui** [comment]
意思就是可不可以给 graph 图设置边界  不要让节点超出画布。我现在也遇到这个问题。 @deqingli

**Comment by LW728** [comment]
> 意思就是可不可以给 graph 图设置边界 不要让节点超出画布。我现在也遇到这个问题。 @deqingli
我也遇到同样的问题，请问你找到解决方法了吗？谢谢~

**Comment by sunui** [comment]
> > 意思就是可不可以给 graph 图设置边界 不要让节点超出画布。我现在也遇到这个问题。 @deqingli
> > 我也遇到同样的问题，请问你找到解决方法了吗？谢谢~

使用  left top width  height 吧 参考 https://www.echartsjs.com/examples/zh/editor.html?c=graph-force2
