### ISSUE TITLE
zrender文件夹下npm run prepublish，生成的lib中缺少文件

### ISSUE THREAD

**Issue by fuyongxia** [apache/incubator-echarts#9786]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

通过在incubator-echarts文件夹下npm install或者在zrender文件夹下npm run prepublish，生成的lib中缺少文件，造成运行时出现module not found的问题出现

### Current Behavior

ERROR in ./lib/echarts/lib/util/graphic.js
Module not found: Error: Cannot resolve module 'zrender/lib/graphic/helper/subPixelOptimize' in E:\work-space\work\sh-isoc\sh-isoc-situation-web\src\main\develop\lib\echarts\lib\util
 @ ./lib/echarts/lib/util/graphic.js 104:27-81

## Environment

- ECharts version；ECharts 版本: {v4.2.0-rc.2}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
What file is missing? please provide detailed message.

**Comment by fuyongxia** [comment]
missing file: zrender/lib/graphic/helper/subPixelOptimize.js

**Comment by fuyongxia** [comment]
> What file is missing? please provide detailed message.
missing file: zrender/lib/graphic/helper/subPixelOptimize.js

**Comment by fuyongxia** [comment]
> What file is missing? please provide detailed message.

missingInfo:
missing file: zrender/lib/graphic/helper/subPixelOptimize.js

How is the problem solved?

**Comment by Ovilia** [comment]
I believe this has been fixed. Please check again and open a new issue if this problem still exists.
