### ISSUE TITLE
legend 分别给每个icon和文字的整体加个boder如何实现

### ISSUE THREAD

**Issue by dragonlyl** [apache/incubator-echarts#9789]
<img width="318" alt="wechate3555dfb9ef099acd87a25b98fbae0f8" src="https://user-images.githubusercontent.com/16730592/51365820-37761d80-1b1d-11e9-9bce-61164dbef673.png"> 

这边测了一下 : 专门给每个文字加border 是用 legend.textStyle.borderWidth(但是icon是不会被包括在边框里面的);给legend整体加上边框是legend.borderWidth.  那么如何像上图一样分别给每个icon和文字的整体加个boder(找了好久没找到,不知道能不能配出这种效果)?

**Comment by deqingli** [comment]
There is no configuration item to do this directly, you can try to implement legend icon with rich text.
