### ISSUE TITLE
抱歉，问一个技术无关的问题

### ISSUE THREAD

**Issue by miniboxhaha** [apache/incubator-echarts#9790]
我想请问下
https://www.echartsjs.com/option-gl.html#globe这个页面中globe.shading中示例的地球贴图在哪里可以找到？
如果方便请告诉我下，非常感谢！实在找不到其他途径提问了，还请原谅。

**Comment by pissang** [comment]
The textures in globe demo are all from https://visibleearth.nasa.gov/view_cat.php?categoryID=1484

**Comment by miniboxhaha** [comment]
> The textures in globe demo are all from https://visibleearth.nasa.gov/view_cat.php?categoryID=1484

thank for your anwser.but i didn't find the image what i looking for.

**Comment by pissang** [comment]
It's rendered by echarts

**Comment by miniboxhaha** [comment]
is there any example i can learn from echarts website?
