### ISSUE TITLE
折线图，x、y轴箭头不会设置超出刻度，有方法吗

### ISSUE THREAD

**Issue by chen9091** [apache/incubator-echarts#9792]
4.2.0版，x、y轴箭头不能设置超出，我想要实现箭头超出 刻度一段距离，常见的那种数据轴，
`                                            axisLine: {
							symbol: ['none', 'arrow'],//是否显示 箭头  
//							symbolOffset:100,
							lineStyle: {
								color:'#e01116'
							}
						},`
我设置symbolOffset，x轴离箭头之间的100px是空白，没有刻度线，是我设置有问题吗？有没有这个设置的方法呢？或者就是超出刻度留一部分，不要x轴满刻度，有没好的方法

**Comment by deqingli** [comment]
There is no better way at the moment.
