### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by ClemMakesApps** [apache/incubator-echarts#9798]
This project seems to be missing a code of conduct. May I suggest https://www.contributor-covenant.org/ as the code of conduct to use for this project?

**Comment by Ovilia** [comment]
Thanks Clem. 
I'll dive into it and Apache Software Foundation related documents to make a further decision.

**Comment by Ovilia** [comment]
As Apache has its own COC Web page, it may not be a good idea to make a copy here. So I added a link in the readme.

**Comment by ClemMakesApps** [comment]
Sounds great, thanks
