### ISSUE TITLE
echarts stack属性为什么数据小于0就叠加不了，只是基于x轴以上叠加么

### ISSUE THREAD

**Issue by yizhengfeng-jj** [apache/incubator-echarts#9800]
##  问题
我设置两个图，都设置了stack为一个固定值，但是其中一个图的数据全部小于0，在x轴以下，其中一个图数据全部大于0，在x轴以上，这样堆叠好像失效了

## 异常结果
![image](https://user-images.githubusercontent.com/20452750/51434282-31587c00-1c98-11e9-9b75-c77de9faaa4c.png)

## 期望结果
期望的结果是，右边红框框的地方也是有阴影的，并且有堆叠的情况，其实没有堆叠，如果有堆叠，右边第一个点是90，不会是120

## 疑惑
请问是我哪里没设设置好么，期待解答。谢谢

**Comment by deqingli** [comment]
@yizhengfeng-jj, please provide the link of the demo.

**Comment by 100pah** [comment]
Only support that: positive values stack with positive values, negative values stack with negative values.
