### ISSUE TITLE
想要在三维散点图中添加一个对角面，或者在某一个面上添加一条对角线

### ISSUE THREAD

**Issue by Lucynie** [apache/incubator-echarts#9803]
## Issue Type

- [x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

想要在三维散点图中添加一个对角面，或者在某一个面上添加一条对角线

## Environment

- ECharts version；ECharts 版本: { "echarts-gl": "1.1.1"}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
Probably <https://www.echartsjs.com/option-gl.html#series-surface.type> can meet your requirement.
