### ISSUE TITLE
series type='scatter' 时symbol无法设置成回调函数

### ISSUE THREAD

**Issue by Evenyoo** [apache/incubator-echarts#9804]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [x ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

希望地图上使用 series type ='scatter'可以设置成函数形式，对地图上不同地点设置成不同的图片，例如symbol:'pin'时可以通过itemStyle回调函数改变样式：
```
itemStyle: {
       normal: {
           color:function(params){
                  return params.data.alarmNum==0 ? '#67C23A':'red'
           },
       }
 },
```
但是当symbol是自定义的图片时，通过itemStyle是无法实现上述效果的，我需要这样：
```
 symbol:params=>{
      return params.data.alarmNum==0 ?
       "image://data:"+ normalBase64() : "image://data:"+ abnormalBase64()
  },
```
但是很遗憾，echarts似乎不能对symbol设置函数格式。

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
Probably <https://echarts.baidu.com/option.html#series-custom.type> can be used in this case.
