### ISSUE TITLE
echarts支持3d饼状图吗

### ISSUE THREAD

**Issue by zhupengxiang** [apache/incubator-echarts#9807]
echarts支持3d饼状图吗

**Comment by 100pah** [comment]
Do not support it until necessary.
In most cases, it is not necessary to render a pie chart in 3D style.

**Comment by tukusejssirs** [comment]
I understand that 3D pie charts are not supported by Echarts (yet), but we have a client who requests 3D pie charts.

Is it possible to create regular pie charts and then create a 3D one like in [Bar 3D charts](https://echarts.apache.org/examples/en/index.html#chart-type-bar3D)?

**Comment by susiwen8** [comment]
https://www.makeapie.com/editor.html?c=xzc6Fw_Q4
https://www.makeapie.com/editor.html?c=xojSDhHAMm

**Comment by tukusejssirs** [comment]
Thanks, @susiwen8! :pray:

**Comment by idabaicai** [comment]
> 

This site can’t be reached in 2023-08-04
