### ISSUE TITLE
echarts 在ios显示不正常

### ISSUE THREAD

**Issue by ChenJunhan** [apache/incubator-echarts#9809]
![image](https://user-images.githubusercontent.com/29296597/51470494-014fcc80-1daf-11e9-9247-eb8d1d80bded.png)
这是安卓手机显示的正常情况，
![image](https://user-images.githubusercontent.com/29296597/51470534-1af11400-1daf-11e9-81d8-31d14affe50d.png)
这是ios手机显示的情况，字体都变得很大，是用uni-app开发的app，页面是通过<web-view></web-view>嵌入到app里面的，用ios的浏览器打开页面正常，但在app里面打开显示不正常，有没有大佬出现过这种情况，谢谢！

**Comment by 100pah** [comment]
Have you set something about:
```html
<meta name="viewport" content="...."/>
```
