### ISSUE TITLE
bug: treemap highlight action not triggered

### ISSUE THREAD

**Issue by Janine-ZN** [apache/incubator-echarts#9816]
```javascript
chart.dispatchAction({
        type: 'highlight',
        seriesId: "Disk Usage0",
        seriesIndex: 0,
        dataIndex: 72,
        name: "Contents"
})
```

**Comment by huiye98** [comment]
be cought in this issue,too...

**Comment by benmo1602** [comment]
`    activeName(value, oldVal) {
      if (oldVal) {
        this.myChart.dispatchAction({
          type: "downplay",
          name: oldVal
        });
      }
      this.myChart.dispatchAction({
        type: 'highlight',
        name: value
      });
    }`
我在 4.7.0 版本 中这样使用 依然是 无法使用

**Comment by benmo1602** [comment]
`    activeName(value, oldVal) {
      if (oldVal) {
        this.myChart.dispatchAction({
          type: "downplay",
          name: oldVal
        });
      }
      this.myChart.dispatchAction({
        type: 'highlight',
        name: value
      });
    }`
