### ISSUE TITLE
Sankey chart - Not able to control display order of nodes 

### ISSUE THREAD

**Issue by spime-web** [apache/incubator-echarts#9820]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

As per the https://github.com/apache/incubator-echarts/issues/4986, order of the nodes displayed in the Sankey chart will be based on the series.data. But the latest version (4.2.0) doesn't work as expected. 

### Expected Behavior

When below option is specified for Sankey charts, the order of nodes should be AAAAAAA, CCCCCCC and DDDDDD. 

    var data = [{"name":"AAAAAAA","value":7},
                  {"name":"CCCCCCC","value":6},
                  {"name":"DDDDDD","value":5},
                  {"name":"EEEEEE","value":4},
                  {"name":"FFFFFF","value":3},
                  {"name":"BBBBBB","value":2}];
    var links = [
				{"source":"DDDDDD","target":"EEEEEE","value":1},
				{"source":"CCCCCCC","target":"FFFFFF","value":1},
				{"source":"AAAAAAA","target":"BBBBBB","value":1},
                {"source":"AAAAAAA","target":"EEEEEE","value":1}]
      
    myChart.setOption(option = {
        title: {
            text: 'Sankey Diagram'
        },
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'sankey',
                data: data,
                links: links,
                focusNodeAdjacency: 'allEdges',
                itemStyle: {
                    normal: {
                        borderWidth: 1,
                        borderColor: '#aaa'
                    }
                },
                lineStyle: {
                    normal: {
                        color: 'source',
                        curveness: 0.5
                    }
                }
            }
        ]
    });

### Current Behavior

But the nodes are in different order as shown in the below image:

![sankey-chart-actual](https://user-images.githubusercontent.com/19399559/51530451-f6557480-1e60-11e9-9dfc-c31558f70af6.PNG)

### Online Example
Go to https://ecomfe.github.io/echarts-examples/public/editor.html?c=sankey-energy and replace the left panel code with the code snippet provided in the "Expected behavior" section and click Run.

## Anything Else We Need to Know
A similar issue has been reported earlier (https://github.com/apache/incubator-echarts/issues/4986) but as that issue has been closed, I am creating a this issue.

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by spime-web** [comment]
Hi, 

It would be great if you could provide some rough idea on when the fix would be available.

Thanks & Regards,
Bala

**Comment by deqingli** [comment]
> Hi,
> 
> It would be great if you could provide some rough idea on when the fix would be available.
> 
> Thanks & Regards,
> Bala

Hi @spime-web, you can set `layoutIterations = 0`.
