### ISSUE TITLE
Is it possible to configure the use of synchronous rendering of charts?

### ISSUE THREAD

**Issue by willxiang** [apache/incubator-echarts#9828]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

是否可以配置使用同步渲染图表？
Is it possible to configure the use of synchronous rendering of charts?

### Expected Behavior

调用setOption方法结束后图表就绘制完毕
After the call to the setOption method, the chart is drawn. 

### Current Behavior

当前调用setOption方法后，line类型的图表可以即时显示，但bar,scatter类型好像是异步绘制的.
After the current call to the setOption method, the line type chart can be displayed instantly, but the bar, scatter type seems to be drawn asynchronously.

## Environment

- ECharts version；ECharts 版本: {4.2.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
> After the call to the setOption method, the chart is drawn.

`line` and `scatter` are the same. After `setOption` called, it starts to render synchronously.
But if `animation` or `progressive` enabled, it would be finished the render after a while.
