### ISSUE TITLE
建议坐标轴标签旋转能参考Excel的样式

### ISSUE THREAD

**Issue by linwrui** [apache/incubator-echarts#9838]
现在坐标轴标签旋转90度之后是这样显示的：
![image](https://user-images.githubusercontent.com/22316156/51659614-0054b000-1fe6-11e9-9523-c964046b8ea0.png)
我们希望能向Excel一样：
![image](https://user-images.githubusercontent.com/22316156/51659649-211d0580-1fe6-11e9-8648-9c35e9b27df6.png)

**Comment by kxcc** [comment]
你可以用富文本，想怎么显示怎么显示

**Comment by luguokong** [comment]
你可以通过字符间添加 ‘\n’ 来实现同样的效果
