### ISSUE TITLE
china.js map show question

### ISSUE THREAD

**Issue by iHadDream** [apache/incubator-echarts#9839]
![image](https://user-images.githubusercontent.com/20382918/51663504-ec16b000-1ff1-11e9-94f4-308ff9592fde.png)

**Comment by iHadDream** [comment]
https://github.com/apache/incubator-echarts/tree/master/map/js/china.js
引的这个js，然后省份分裂了。

**Comment by 100pah** [comment]
Could you provide echarts `version` and `option` to reproduce it.

**Comment by iHadDream** [comment]
i replace china.js file and map is normal show 
 echarts version is 4.1.0
