### ISSUE TITLE
series custom don't want to  average xAxis label如何让自定义图形x轴刻度不等分显示

### ISSUE THREAD

**Issue by martinko2009** [apache/incubator-echarts#9841]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

当我使用series type 为custom的时候，设置了xAxis和yAxis类型都为value，然后给xAxis设置了max和min，让x轴数值从min到max，但是这样一来，x轴的刻度，只能平均等分显示，我不想这样，想他按照我提供的值显示。
When I use series type custom to draw a bar, I set the type option of xAxis and yAxis to 'value', and set max and min options for xAxis. but the label of xAxis is displayed by average value, I don't want to that. I need display the label of xAxis by my configuration.

### Expected Behavior

我希望x轴的刻度不要等分显示，而是根据我提供的值显示，像xAxis的type为category的时候那样。
I need display the label of xAxis by my configuration. Like the type option of xAxis is set to category
### Current Behavior

现在貌似x轴的刻度只能等分显示。
now the label of xAxis is displayed by average value.

### Online Example

```
let option = {
    xAxis : [
	{
		type : 'value',
		min: 10,
		max: 100,
		interval: (100 - 10) / 14
		data: [10, 13, 18, 25, 30, 36, 38, 46, 53, 68, 78, 80, 90, 100]
	}
],
yAxis : [
	{
		type : 'value',
	}
],
series : [ 
	{
		name: 'xxxx',
		type: 'custom',
		renderItem: function(params, api) {
			var yValue = api.value(2);
			var start = api.coord([api.value(0), yValue]);
			var size = api.size([api.value(1) - api.value(0), yValue]);
			var style = api.style();
			return {
				type: 'rect',
				shape: {
					x: start[0] + 1,
					y: start[1],
					width: size[0],
					height: size[1]
				},
				style: style
			};
		},
		label: {
			normal: {
				show: true,
				position: 'top'
			}
		},
		encode: {
			x: [0, 1],
			y: 2,
			tooltip: 2,
			label: 2
		},
		itemStyle: {
			normal: {
				borderWidth: 1,
				borderColor: '#000'
			}
		},
		data: [[10, 13, 10], [13, 18, 5], [18, 25, 12], [25, 30, 10],
				[30, 36, 12], [36, 38, 20], [38, 46, 9], [46, 53, 7],
				[53, 68, 5], [68, 78, 2], [78, 80, 2], [80, 90, 6],
				[90, 100, 10]
		]
	}
]
}
```
## Environment

- ECharts version；ECharts 版本: {3.6.0}
  3.6.0
- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{chrome 70}
  chrome 70

**Comment by 100pah** [comment]
Use value axis (`axis.type: 'value'`), please. That would be meet your scenario.
