### ISSUE TITLE
堆积bar图在显示“缩放区域”工具栏按钮后柱子超出Y轴最大值

### ISSUE THREAD

**Issue by mismo** [apache/incubator-echarts#9847]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

The stacked bar graph shows the column exceeding the maximum value of Y axis after the button in the "Zoom Area" toolbar is displayed.
堆积bar图在显示“缩放区域”工具栏按钮后柱子超出Y轴最大值。

### Expected Behavior

The stacked bar chart does not exceed the Y-axis maximum after displaying the "Zoom Zone" toolbar button.
堆积bar图在显示“缩放区域”工具栏按钮后柱子不超出Y轴最大值。

### Current Behavior

![04](https://user-images.githubusercontent.com/1709961/51813765-fdfa9a80-22f2-11e9-9945-4ba2495cb6f9.png)
![05](https://user-images.githubusercontent.com/1709961/51813766-fe933100-22f2-11e9-81b6-471e21842c48.png)

### Online Example

```javascript
option = {
	"series": [
		{
			"data": [
				15015.81,
				22607.685
			],
			"name": "东北",
			"stack": "default",
			"type": "bar"
		},
		{
			"data": [
				128955.52,
				107812.755
			],
			"name": "华北",
			"stack": "default",
			"type": "bar"
		},
		{
			"data": [
				47635.565,
				52360.035
			],
			"name": "华东",
			"stack": "default",
			"type": "bar"
		}
	],
	"toolbox": {
		"feature": {
			"dataZoom": {
			}
		}
	},
	"tooltip": {
	},
	"xAxis": {
		"data": [
			"饮料",
			"日用品"
		],
		"type": "category"
	},
	"yAxis": {
		"type": "value"
	}
}


```

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE} 4.2.0-rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Duplicated of #8935
