### ISSUE TITLE
Control different area color in line area chart?

### ISSUE THREAD

**Issue by TonyPan1124** [apache/incubator-echarts#9852]
Is there a way to control the area color under a line chart in different Line and not to cover the other Line?

1. I have a Line Chart like thie:

![image](https://user-images.githubusercontent.com/47103348/51826732-b855c600-2322-11e9-8e10-1d18eee45306.png)

2. How can I get the final Chart like this:

![image](https://user-images.githubusercontent.com/47103348/51827002-5c3f7180-2323-11e9-90a0-f409e9bff70b.png)

The Stack is not my need,Thanks for any ideas!

**Comment by pissang** [comment]
You can try sorting the series to get the darker series are on the top.
