### ISSUE TITLE
series-scatter doesn't respect data format when `coordinateSystem` is `geo` in echarts version 4.2.0-rc.2

### ISSUE THREAD

**Issue by hamidhasnain** [apache/incubator-echarts#9854]
I need to create exactly this visualisation: [https://ecomfe.github.io/echarts-examples/public/editor.html?c=geo-map-scatter] with echarts version 4.2.0-rc.2

The example website is using version 4.2.1 which is not yet released.

Issue: 
`  const option = {
    geo: {
      map: 'USA',
      roam: true
    },
    series: [
      {
        type: 'scatter',
        coordinateSystem: 'geo',
        data: [{name: 'n1', value: [<lang>, <lat>, <value>]}]
      }
    ]
  }`

in version 4.2.0-rc.2 lang and lat values are not respected. 
I do not find documentation for data format to be used with this version.

**Comment by pissang** [comment]
I think it is a bug in 4.2.0-rc.2. Please upgrade to 4.2.1-rc.1 to solve this issue.

**Comment by hamidhasnain** [comment]
> I think it is a bug in 4.2.0-rc.2. Please upgrade to 4.2.1-rc.1 to solve this issue.

@pissang Any idea when will it be released in npm? Thanks.

**Comment by pissang** [comment]
@hamidhasnain  https://github.com/apache/incubator-echarts/issues/9855#issuecomment-458416895
