### ISSUE TITLE
When will 4.2.1-rc1 be released in NPM?

### ISSUE THREAD

**Issue by jonavila** [apache/incubator-echarts#9855]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [x ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

ECharts version 4.2.1-rc1 is not available in NPM. I'm wondering when it will be published.

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by ClemMakesApps** [comment]
Based on the dev mailing list email, it looks like the voting has closed and there were no objections to the release. I would assume it would take place within the next few days.

**Comment by pissang** [comment]
`4.2.1-rc.1` has been released with `rc` tag. You can run `npm i echarts@rc` to install the latest rc version.

**Comment by ClemMakesApps** [comment]
@pissang not sure if there was an error on the publishing step but https://www.npmjs.com/package/echarts is showing that the latest version is `4.2.0-rc.2` even though `4.2.1-rc.1` is listed as a published tag as well

**Comment by jonavila** [comment]
@pissang @ClemMakesApps How can I sign-up to the dev mailing list?

**Comment by ClemMakesApps** [comment]
@jonavila it is dev@echarts.incubator.apache.org and can be found on http://echarts.apache.org/maillist.html

**Comment by pissang** [comment]
@ClemMakesApps We found it's a mistake to publish 4.2.0-rc.2 as latest version. So we corrected it and published 4.2.1-rc.1 with `rc` tag. ASAP we release 4.2.1, we will publish it as latest version to replace 4.2.0-rc.2
