### ISSUE TITLE
echarts接入高德地图后，tooltip属性失效，鼠标移到地理飞线上，不显示提示信息

### ISSUE THREAD

**Issue by scarecrow111** [apache/incubator-echarts#9856]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by pissang** [comment]
Please describe the bug with more information.

**Comment by scarecrow111** [comment]
当前的应用场景是，在地图上显示所有航线，鼠标移动到航线轨迹上时，显示该条航线上的所有人员信息，通过echarts接入高德地图，当鼠标移动到地理飞线上时，tooltip未显示出信息，确切的说是，并未对鼠标事件作出反应，与之相对的是，接入百度地图的时候，是可以进行显示人员信息的。

**Comment by plainheart** [comment]
请考虑是否是zIndex小于高德地图底图 高德地图结构和百度地图结构不同 如果你的高德地图echarts扩展插件没有对此进行处理 就会存在无法点击echarts图表元素的问题。

**Comment by yuanssss** [comment]
大神求教echarts如何接入地图API
