### ISSUE TITLE
TypeScript 声明文件 SeriesBar.markPoint.data 类型声明有误

### ISSUE THREAD

**Issue by NickeyLin** [apache/incubator-echarts#9859]
## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

TypeScript 声明文件 SeriesBar.markPoint.data 类型声明有误。而且感觉整个声明文件很乱，有些应该相同的类型，因为在不同的series中，类型却不一样，比如`fontWeight`，有些地方声明为: `'normal' | 'bold' | 'bolder' | 'lighter' | 100 | 200 | 300 | 400`，有些地方却只是简单的 `string`。

### Expected Behavior

在TypeScript中能正确使用柱形图的markPoint，并且希望TypeScript声明更加规范一点。

### Current Behavior

下面语句会报错
```ts
get barSerie(): EChartOption.SeriesBar {
    return {
      name,
      data: this.data.map(item => ({ name: item.name, value: item.value, itemStyle: { ...item.barItemStyle } })),
      markPoint: {
        ...this.markPoint,
        data: [
          {
            name: '最大值',
            type: 'max'
          }
        ]
      }
    };
  }
```

错误信息
```
属性“data”的类型不兼容。
    类型“{ name: string; type: string; }[]”与类型“{ name?: string | undefined; type?: string | undefined; valueIndex?: number | undefined; valueDim?: string | undefined; coord?: any[] | undefined; x?: number | undefined; y?: number | undefined; ... 7 more ...; label?: { ...; } | undefined; }”不具有相同的属性。
```
markPoint.data 应该是数组类型，但是声明文件里面却是object。

![image](https://user-images.githubusercontent.com/2948405/51881020-83924f00-23b4-11e9-9ad4-6ae35fcff658.png)

## Topics

- [x] TypeScript
## Environment

- ECharts version；ECharts 版本: {@4.2.0-rc.2}  @types/echarts 版本:{4.1.3}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
This is generated by https://github.com/iRON5/echarts-ts-describer . Please open an issue there.
Thanks!
