### ISSUE TITLE
[Feature request] Multiple legend

### ISSUE THREAD

**Issue by lqxlearn** [apache/incubator-echarts#9860]
I have a feature to request；
我需要一个新功能

每个数据有自己的legend 像tooltip那样。
each data has its own legend,like tooltip.

**Comment by pissang** [comment]
Please describe your feature request with more detail. An example will be great.

**Comment by lqxlearn** [comment]
var option = {
    legend: {},
    tooltip: {},
   toolbox: {
				show : true,
				right:40,
				feature : {
					saveAsImage : {show: true,name:'ConferenceReports'}
				}
			},
    series: [{
        type: 'pie',
        radius: 60,
        center: ['25%', '30%'],
        data:[41.1, 30.4, 65.1, 53.3, 83.8, 98.7]
        // No encode specified, by default, it is '2012'.
    }, {
        type: 'pie',
        radius: 60,
        center: ['75%', '30%'],
        data:[86.5, 92.1, 85.7, 83.1, 73.4, 55.1],
        encode: {
            itemName: 'product',
            value: '2013'
        }
    }, {
        type: 'pie',
        radius: 60,
        center: ['25%', '75%'],
        encode: {
            itemName: 'product',
            value: '2014'
        },
        data:[24.1, 67.2, 79.5, 86.4, 65.2, 82.5],
    }, {
        type: 'pie',
        radius: 60,
        center: ['75%', '75%'],
        encode: {
            itemName: 'product',
            value: '2015'
        },
        data:[55.2, 67.1, 69.2, 72.4, 53.9, 39.1],
    }]
};

多表一个下载。
