### ISSUE TITLE
echars的扩展图 （graphGL） 节点事件（点击、鼠标滑入滑出、双击）有的节点生效有的节点不生效，原因是什么？该怎么解决？

### ISSUE THREAD

**Issue by chenyeye** [apache/incubator-echarts#9864]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by pissang** [comment]
Please provide more information for us to reproduce your issue.

**Comment by chenyeye** [comment]
- I send an email to you.Please check it，thank you very much.

**Comment by chenyeye** [comment]
>           Please provide more information for us to reproduce your issue.
I send an email to you.Please check it，thank you very much.

**Comment by chenyeye** [comment]
> Please provide more information for us to reproduce your issue.
我创建了一个仓库，您打开看看，当鼠标滑入滑出某些节点时console里面有打印，当滑入滑出其他节点时是没有打印信息的，说明这两个事件在有些节点上是生效的有些节点上不生效，我不清楚这个问题的原因是什么，该怎么解决，如果您有时间的话麻烦您看看
https://github.com/chenyeye/echarts-graphGL-Demo

**Comment by chenyeye** [comment]
> Please provide more information for us to reproduce your issue.
> 
> 
> I send an email to you.Please check it，thank you very much.
