### ISSUE TITLE
Example calendar-graph not working

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/incubator-echarts#9866]
Hello there,

I have noticed that the following calendar example is not working. 

https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-graph

It says "Errors exist in code!".

Best regards,

Sergios.

**Comment by ClemMakesApps** [comment]
I was able to reproduce this as well.

![Uploading Google Chrome_2019-01-29 08-48-47@2x.png…]()

**Comment by Ovilia** [comment]
Cannot reproduce in my environment.
@MINDoSOFT Does it work now? What's your OS and Web browser?

**Comment by ClemMakesApps** [comment]
Looks like the page documentation pages have been updated. I no longer see the error @Ovilia

**Comment by MINDoSOFT** [comment]
Hello there.

I am using Ubuntu 18.04 and Chrome 72.0.3626.109.

Still see the error on https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-graph

Maybe the updated examples code is not deployed ?

Best regards,

Sergios.

**Comment by Ovilia** [comment]
@MINDoSOFT My test Environment is Mac on Chrome 72.0.3626.109.
Is there any chance that this is a previous error which is cached in your case?
Can you try clear cache and check again? Thanks.

**Comment by MINDoSOFT** [comment]
Hi there,

I have just cleared my cache and still I get the same error. When I say error I mean that the chart appears but it is empty and also it says "error exists in code".

@ClemMakesApps can you send me the link where you see the page working ?

Also from what I see this type of coordinate system "calendar" used in this example is missing from the documentation. https://ecomfe.github.io/echarts-doc/public/en/option.html#series-graph.coordinateSystem

Thanks !

**Comment by ClemMakesApps** [comment]
@MINDoSOFT I am using https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-graph which is the same link in my original screenshot with the original error.

I've also clicked the `run` button to re-run the example, and it does not give me an error

**Comment by MINDoSOFT** [comment]
We are using the same url indeed, but I am still seeing the error. 

Also I tested it on windows with internet explorer, and multiple computers and I still get the exception an no data on the echart (like your original exception screenshot).

Thanks for your time. If you have any idea how this can be fixed let me know.

**Comment by MINDoSOFT** [comment]
Hello there,
I have located the problem, it has to do with the links in the echart configuration. Once I comment out the links, the charts display properly.

This problem happens with every chart that contains links e.g. 

- https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-graph 
- https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-charts

Best regards,
Sergios.

**Comment by MINDoSOFT** [comment]
In https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-graph if I remove the first element of graphData, the example works.

![screenshot from 2019-02-20 16-11-43](https://user-images.githubusercontent.com/890368/53097527-57d53580-352a-11e9-9912-fd448b2f398f.png)

Also the same thing with the https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-charts example.

![screenshot from 2019-02-20 16-12-56](https://user-images.githubusercontent.com/890368/53097617-8f43e200-352a-11e9-947e-c5e524fb4b96.png)

The cause of this problem is this data (in both cases) : 
```
    [
        1485878400000,
        260
    ],
```
although I don't know why they are causing it.

**Comment by ClemMakesApps** [comment]
@MINDoSOFT do you get the same error when you run the same code in JSFiddle?

**Comment by 100pah** [comment]
@MINDoSOFT could I have your timezone of OS?
For example, what `new Date()` prints in the console of the browser?

**Comment by MINDoSOFT** [comment]
@ClemMakesApps I have tried to run the code on [jsfiddle](http://jsfiddle.net/zd2mvx9y/1/)  and I still get an error when the first element of graphData is there. If I comment it out (and keep the rest of the data) it works. The error is the following :

> echarts.min.js:21 Uncaught TypeError: Cannot read property 'off' of undefined
>     at echarts.min.js:21
>     at oC.aC.eachEdge (echarts.min.js:21)
>     at i.render (echarts.min.js:21)
>     at or.progress (echarts.min.js:21)
>     at ar (echarts.min.js:21)
>     at or.XM.perform (echarts.min.js:21)
>     at echarts.min.js:21
>     at i.<anonymous> (echarts.min.js:21)
>     at Array.forEach (<anonymous>)
>     at d (echarts.min.js:21)

@100pah it prints :

> Mon Feb 25 2019 09:15:32 GMT+0200 (Eastern European Standard Time)

Thank you for your help.

**Comment by MINDoSOFT** [comment]
Hi there, 

I will close this issue because it looks like it occurs because the timestamps in the data do not take into account the timezones and something weird happens. I can live with just deleting the first data in the array. :)

Best regards,

Sergios.
