### ISSUE TITLE
Echarts textStyle not work for axisLabel

### ISSUE THREAD

**Issue by borodovisin** [apache/incubator-echarts#9870]
When you set textStyle as global in echarts, that configuration doesn't work on axisLabel inside xAxis or yAxis, the user must to set that property inside xAxis.

Example doesn't work:
<code>var option = { 
textStyle: {
fontSize: '24'
}
}
</code>

In this case it works:
<code>var option = { 
xAxis: {
    axisLabel: {
        fontSize: '24'
    }
}
}</code>

**Comment by Ovilia** [comment]
This is probably because the default setting of axisLabel overrode that of global.
