### ISSUE TITLE
Echarts 3.4.4 markLine plotting wrong with for values less than 0.01

### ISSUE THREAD

**Issue by mariazahidd** [apache/incubator-echarts#9872]
I have a ECharts line chart where I am setting a target using markline. The problem is that, echarts is not plotting markLine correct with values less than 0.01.
```
{
    name: 'target',
    markLine: {
     data: [{ yAxis: 0.0064}]
    }
}
```
Here is the full code,
```
{
 name: 'target',
 type: 'line',
 animation: false,
 symbol: 'none',
 silent: true,
 itemStyle: {
   normal: {
     lineStyle: {
      type: 'dashed',
      width: '1',
      color: 'blue'
     }
   }
 },
 markLine: {
  symbol: 'none',
  data: [{ yAxis: 0.0064}],
  label: {
    normal: {
     show: false
    }
  },
  itemStyle: {
    normal: {
      lineStyle: {
        type: 'dashed',
        width: '1',
        color: 'blue'
      }
    }
  }    
 }
```
Other series are plotted correctly with values less than 0.01.

I have attached screenshot. You can see blue dotted markLine is not plotted at 0.0064 but other series' point is plotted correctly at 0.0054
![targetlineissue](https://user-images.githubusercontent.com/29012463/51965815-7779c080-248c-11e9-8293-b88e31ba9bcf.PNG)

Echarts version : 3.4.4

**Comment by Ovilia** [comment]
Can you provide a full option?

**Comment by Ovilia** [comment]
Please provide the full option rather than series. And please try with the latest version.

**Comment by POILover** [comment]
Aha! I thought I was the only one!!! #11517
