### ISSUE TITLE
echarts 4.x  版本是否还支持将 legend配置为数组类型

### ISSUE THREAD

**Issue by sundaesfruit** [apache/incubator-echarts#9878]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [x] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

echarts 4.x版本是否支持配置属性 legend 的值配置为 数组类型？ 我翻阅了官方配置文档上面，属性legend的类型为对象；
![image](https://user-images.githubusercontent.com/15335914/52045349-4d54fb00-257f-11e9-8013-77cd5bef35d8.png)

![image](https://user-images.githubusercontent.com/15335914/52045410-71184100-257f-11e9-8ba8-9af79a1c3c92.png)

### Expected Behavior

希望知道是否支持，或者以后是否会废除该写法

## Environment

- ECharts version；ECharts 版本: {4.2.1}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by pissang** [comment]
Yes, any component except tooltip can be an array.

**Comment by sundaesfruit** [comment]
thanks，but there is a instruction that you said about the configuration of component on the official website ？ @pissang
