### ISSUE TITLE
Bar chart issue: Generates merged bar chart if we reduces width of zoom bar to its certain width.

### ISSUE THREAD

**Issue by medhalohar** [apache/incubator-echarts#9882]
Description:
1. Created bar chart with following given option object:
2. I reduced width of zoom bar to its certain width, as given in option object:  "minSpan": 0.5 
3. Have a look at attached screenshot.

option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar'
    }],
     "dataZoom": {
    "type": "slider",
    "show": true,
    "minSpan": 0.5,
    "filterMode": "empty",
    "start": 87.65476305836627,
    "end": 94.3056847654145,
    "xAxisIndex": [
      0
    ]
  },
};

Result:
![medha2](https://user-images.githubusercontent.com/47210090/52050658-432efe80-2577-11e9-8b48-e6ae20d30ed4.png)
![medha1](https://user-images.githubusercontent.com/47210090/52050660-432efe80-2577-11e9-9a77-9641eb34fbce.png)

**Comment by ClemMakesApps** [comment]
Here's a gif that explains the issue better:

![2019-01-31 11 31 57](https://user-images.githubusercontent.com/3363898/52073004-04378380-254c-11e9-8544-9fb112e1b417.gif)

**Comment by Ovilia** [comment]
@medhalohar Thanks for your report. Seems to be a bug.

**Comment by Jivanvl** [comment]
This also affects stacked column charts

![2019-03-25_12 52 42](https://user-images.githubusercontent.com/1641877/55021582-a14bf100-4fbe-11e9-9c78-2bf890843e3f.gif)

**Comment by 100pah** [comment]
Sorry it is a bug.
