### ISSUE TITLE
Chart no respect div size

### ISSUE THREAD

**Issue by jonasaraujo96** [apache/incubator-echarts#9883]
## Issue Type

- [X] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Hi, how set to chart respect a div size?

### Expected Behavior

![image](https://user-images.githubusercontent.com/36088468/52057557-6e502880-254c-11e9-9fc6-a7beab9a982a.png)
![image](https://user-images.githubusercontent.com/36088468/52057371-fbdf4880-254b-11e9-89b2-c87d09b5d006.png)
![image](https://user-images.githubusercontent.com/36088468/52057458-334df500-254c-11e9-811b-883d98ef10e5.png)
![image](https://user-images.githubusercontent.com/36088468/52057494-49f44c00-254c-11e9-95d3-00337f905925.png)

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Hi, could explain what's happening here? What's wrong and what's expected?
