### ISSUE TITLE
Select xAxis to draw value.

### ISSUE THREAD

**Issue by nawelittle** [apache/incubator-echarts#9884]
## General Questions

Is it possible to choose the x axis where I want to draw the values? , I need that the bars have 2 different colors and are on 2 different axes

### Expected Behavior

![image](https://user-images.githubusercontent.com/27011081/52059667-30053a00-2549-11e9-99a3-f9e0cd356142.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/27011081/52059701-4612fa80-2549-11e9-9a7b-27380bf53fbc.png)

the two series are being drawn on the axis1

### Online Example
http://jsfiddle.net/kfbp5j9z/1/

## Environment

- ECharts version；ECharts 版本: 4.1.0

**Comment by Ovilia** [comment]
You can use `data: [['axis1', 30]]`. See demo here: http://jsfiddle.net/ovilia/b1dmg93v/2/
