### ISSUE TITLE
How to set splitline color when xAxis is category

### ISSUE THREAD

**Issue by shatle** [apache/incubator-echarts#9886]
I have read the ducument, and did not find the option for this ->

https://www.echartsjs.com/gallery/editor.html?c=doc-example/line-stack-tiled

![image](https://user-images.githubusercontent.com/1129872/52101200-863faf00-2615-11e9-8922-ba03bcd3d47a.png)

Thanks for anyone

**Comment by pissang** [comment]
https://echarts.apache.org/option.html#tooltip.axisPointer.lineStyle.color

**Comment by shatle** [comment]
@pissang  Thanks

**Comment by guinguo** [comment]
how to show it while no just hover.   
I want to show all that line (exclude first and last), but splitLine `splitLine: {show: true} `not this line  
thanks
