### ISSUE TITLE
Synchronize tooltip between two charts (grid)

### ISSUE THREAD

**Issue by azpublic** [apache/incubator-echarts#9890]
## Issue Type

- [ x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

 I would like to know if it is possible to have a synchronized tooltip between two grid elements.

### Expected Behavior

 When moving the mouse on my candlestick chart I would like the cross tooltip to move simultaneously to the corresponding X axis position of the other chart (2nd grid element) that is located right below. They share the same X axis data (dates). Is this possible in any way? 

Thanks !   

### Current Behavior

 Current behavior is that the cursor and tooltip only moves on the chart that the mouse is hovering. 
Ideally the seccond chart would display the tooltip and cross too at the same time.

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Please see if this is what you want https://gallery.echartsjs.com/editor.html?c=xSyqudQB5-

**Comment by azpublic** [comment]
Yes thank you ! This is exactly what I need.

**Comment by zimtsui** [comment]
thank you

**Comment by stellasis** [comment]
hi! it seems the link is not available anymore. can anyone post the updated link?

**Comment by MeMeMax** [comment]
@Ovilia unfortunately the link you provided is down. I got the same problem but this github issue doesn´t provide the answer.

**Comment by arusak** [comment]
Here's an example with two synced grids:
https://echarts.apache.org/examples/en/editor.html?c=grid-multiple
