### ISSUE TITLE
Problem with bar chart borders

### ISSUE THREAD

**Issue by dimunidze** [apache/incubator-echarts#9900]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [x] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

The problem is that when you click the borders of the bar chart should be painted in red, and painted in yellow, example code:
https://codepen.io/dimunidze/pen/NorbOr?editors=0011

The following is an example:
![50146279-d7e1e380-02cc-11e9-9d60-d6688818275d](https://user-images.githubusercontent.com/23029495/52564588-04723180-2e1e-11e9-9322-449e01e82ad6.gif)

### Expected Behavior

After selecting the column, the border is painted in the color that was transmitted.

## Environment

- ECharts version；ECharts 版本: 4.2.0-rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by cuijian-dexter** [comment]
You should set `barBorderColor `instead of `borderColor`

```
function getDataItemStyle(isSelected: boolean) {
		if(isSelected) {
			const borderProps = {
				barBorderColor: "#ff0000",
				barBorderWidth: 5
			};
			return {opacity: 1, ...borderProps}
		} else {
			return {opacity: 0.5}
		}
	}
```
