### ISSUE TITLE
The axis name align way base on x/y axis line ?

### ISSUE THREAD

**Issue by xianghongai** [apache/incubator-echarts#9901]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [x] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

### Expected Behavior

![how-to-align-left-of-yaxis-that-name](https://user-images.githubusercontent.com/2075006/52611761-0261ae80-2ec2-11e9-8d5a-041c42708364.png)

### Current Behavior

If the axis name too long, it will overflow the canvas.

### Online Example

```javascript
option = {
    xAxis: {
        type: 'category',
        name: `Axis name very very very very very very very very long`,
        nameLocation: 'start',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value',
        name: `Axis name very very very very very very very very long`,
        nameLocation: 'end',
        nameAlign: 'end',
        nameGap: 15,
        
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        smooth: true
    }]
};
```

## Anything Else We Need to Know

PS: This issue template, the `Issue Details` section, `<!-- DESCRIBE_HERE} -->` tips message missing  `{` chart.

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE} 4.2.0

- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE} All Browser, All OS

**Comment by Ovilia** [comment]
Please use https://echarts.baidu.com/option.html#yAxis.nameTextStyle.align

**Comment by xianghongai** [comment]
![yaxis nametextstyle align-not-working](https://user-images.githubusercontent.com/2075006/52616962-3eead580-2ed5-11e9-948c-241aac78f33b.png)

```javascript
option = {
    xAxis: {
        type: 'category',
        name: `xAxis very very very very very very very very long`,
        nameGap: 35,
        nameLocation: 'end',
        nameTextStyle: {
            color: '#00f',
            fontWeight: 'bolder',
            align: 'left',
            verticalAlign: 'left'
        },
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value',
        name: `yAxis very very very very very very very very long`,
        nameGap: 35,
        nameLocation: 'end',
        nameTextStyle: {
            color: '#f00',
            fontWeight: 'bolder',
            align: 'right'
        }
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        smooth: true
    }]
};
```

**Comment by yangchao35071** [comment]
请问解决了吗? 我也是这个问题yAxis.nameTextStyle.align不生效, 但是低版本的echarts却可以

**Comment by Ovilia** [comment]
@yangchao35071 Not yet. Scheduled in v4.3.0.

**Comment by wjhcc2018** [comment]
我也遇到这个问题了，大家偶读解决了

**Comment by wjhcc2018** [comment]
我也遇到这个问题了，大家解决了吗

**Comment by zhouye0211** [comment]
我也遇到了这个问题，现在我在用grid.left去调整
