### ISSUE TITLE
曲线图 如何获取自动吸附点相对于cancas的坐标 急

### ISSUE THREAD

**Issue by luanxinwei** [apache/incubator-echarts#9902]
曲线图 当曲线焦点自动吸附后，如何获取选中点相对于cancas的坐标

![image](https://user-images.githubusercontent.com/30032313/52775618-0b49b000-307b-11e9-92b5-c792f69a603e.png)

**Comment by deqingli** [comment]
You can listen to the hover event, the parameter of the event's callback function contains the coordinates of the point.
