### ISSUE TITLE
Layered bar chart

### ISSUE THREAD

**Issue by Turm0** [apache/incubator-echarts#9905]
- [x] Required: I have read the document and examples and tried to solve it by myself.
- [x] Required: I have searched for similar issues and that didn't help.
- [x] Required: I have tried with the latest version of ECharts and still have this problem.

In this issue, I have provided information with: 
- [x] Required: issue type；
- [x] Required: one sentence description in issue details
- [ ] Required: demo；
- [x] Required: ECharts version；

- [x] I have a question to ask about *how to use ECharts to ...*；

## Issue Details

Is it possible to display a bar chart where the series' are layered on top of each other.

### Expected Behavior

![layeredbarrenderersample](https://user-images.githubusercontent.com/43402579/52640450-28e21280-2edf-11e9-82f3-a73fa46433fa.png)

This is the expected behavior. The series' are layered and subsequent bars are thinner than the previous ones. The serie count is dynamic in my case so hard coded solutions are not relevant.

### Current Behavior

![1](https://user-images.githubusercontent.com/43402579/52640499-48793b00-2edf-11e9-9c85-6b3d52990138.PNG)

I managed to get this far with the bar border, but it seems it cannot be set for only the left and right sides. I also tried to change the bar gap and widths with no results. 

## Anything Else We Need to Know

N/A

## Environment

- ECharts version；ECharts 版本: 4.1.1

**Comment by cuijian-dexter** [comment]
Hope to help you.
https://jsfiddle.net/6sgLbuja

**Comment by Turm0** [comment]
> Hope to help you.
> https://jsfiddle.net/6sgLbuja

This approach works with 2 series. With dynamic number of them, it seems impossible to center the bars as there can be only one bar gap set for the whole chart.

**Comment by Ovilia** [comment]
@Turm0 You can use a function to generate the series with a count parameter.

**Comment by Turm0** [comment]
> @Turm0 You can use a function to generate the series with a count parameter.

Could you elaborate a bit how is this relevant to the problem.

**Comment by Ovilia** [comment]
Based on the code of https://jsfiddle.net/6sgLbuja , you can change the parameters according to series amount.
