### ISSUE TITLE
在曲线图和散点图中tooltip形状获取出错

### ISSUE THREAD

**Issue by foolmadao** [apache/incubator-echarts#9908]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

   在曲线图和散点图中，如何设置tooltip中的形状

如图右边的legend的形状和图像中hover产生的tooltip的形状不一样
![image](https://user-images.githubusercontent.com/39939976/52694514-e6830900-2fa4-11e9-8382-89f8bdcde1e7.png)
tooltip用formatter实现
![image](https://user-images.githubusercontent.com/39939976/52694876-1088fb00-2fa6-11e9-97c8-3d499de43f20.png)
经检查发现无论legend和series中设置的symbol为什么形状，formatter函数中获取的point的maker都是圆形
![image](https://user-images.githubusercontent.com/39939976/52695263-fac80580-2fa6-11e9-8ad2-425238a47dfa.png)

散点图中存在相同的情况

![image](https://user-images.githubusercontent.com/39939976/52695613-f6501c80-2fa7-11e9-823d-33cd345e0b59.png)

### Expected Behavior

期望tooltip的图标和图中点及legend一致
## Environment

- ECharts version；ECharts 版本: {4.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
Hi, currently the tooltip and legend don't keep icons consistent. You can draw any icon in HTML with the tooltip `formatter`.
