### ISSUE TITLE
How can I get the number of interies in a single slider interval

### ISSUE THREAD

**Issue by Zahma** [apache/incubator-echarts#9911]
## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Wind barb sample with many data

I'm following this example : https://ecomfe.github.io/echarts-examples/public/editor.html?c=wind-barb
the problem is that I have a lot of data to manage therefore the custom type of the top representing temperature and images, get overlapped. One solution to this problem is to hide this bar according to the number of data elements (either the interval slider is set or not). How can I get the number of data elements inside, renderWeather() ?

### Online Example

https://ecomfe.github.io/echarts-examples/public/editor.html?c=wind-barb

## Environment

- ECharts version；ECharts 版本: {4.1.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
sorry, I don't quite understand what you mean, the number of the data elements inside depends on the raw data you provide.
