### ISSUE TITLE
关于力导向布局图数据传输与接收问题问题

### ISSUE THREAD

**Issue by wenboi** [apache/incubator-echarts#9922]
## Issue Type

- [ x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

现在我需要将flask和echats结合起来，将数据传入到模板中的echats中。然后echats接收传入的数据作图，就是力导向布局图  nodes:,links:，这两个参数接收我传入的列表，列表中的数据是字典格式的。但是我尝试了很多的方法，都是没有成功的画出力导向图

### Expected Behavior

根据后端传入的数据，然后做出相应的力导向图

### Current Behavior

一片空白

### Online Example

app.py代码：
   test_source = [{'source': 'shay', 'target': 'mahrsheelab', 'weight': 1}, {'source': 'shay', 'target': 'zorolord', 'weight': 3}, {'source': 'shay', 'target': 'bindu7', 'weight': 1}, {'source': 'shay', 'target': 'antogginly', 'weight': 1}]
    test_node = [{'category': 4, 'name': 'nishant', 'value': 4}, {'category': 4, 'name': 'hackethis29', 'value': 1}, {'category': 4, 'name': 'digitalyatri', 'value': 2}, {'category': 6, 'name': 'xxclickalotxx123', 'value': 2}]
#在浏览器上渲染my_templaces.html模板
   return render_template('my_template.html',node_source = test_node,link_source = test_source)
my_template.html代码：
                   nodes:{{node_source}}
                   links:{{link_source}}

## Environment

- ECharts version；ECharts 版本: {echats-2.2.7}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{macOS Mojave pycharm python3.6}

**Comment by deqingli** [comment]
你好，你可以将你的 `nodes` 和 `links` 在 console 中打印出来，看是否正确
