### ISSUE TITLE
Echarts 4.2.0 does not work in Chrome 73  (dev and Canary)  or higher.

### ISSUE THREAD

**Issue by DheLastManStanding** [apache/incubator-echarts#9923]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Echarts 4.2.0 does not work in Chrome 73  (dev and Canary)  or higher.

### Expected Behavior

Just rendering charts normally.

### Current Behavior

If you are using Chrome 73(or 74,both latest dev and Canary have reached this version),Echarts does not render anything,even in offical demos,all you can see is a blank page.

### Online Example

https://www.echartsjs.com/examples/editor.html?c=area-basic

## Topics

 Check those topics that are related. 选择相关主题。
- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [x] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {4.2.0}

- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{Chrome 74.0.3702.0 (dev or Canary)}

**Comment by 100pah** [comment]
I have tried on Chrome 74.0.3712.0 (Official Build) canary (64-bit) (macOS 10.13.5) 
using the link <https://www.echartsjs.com/examples/editor.html?c=area-basic>. 
It seems to work normally.

Could I have your OS info?

**Comment by DheLastManStanding** [comment]
> Could I have your OS info?

Sorry to reply you so late.
My OS info: Windows 7(Ultimate).
The issue still happens in Chrome(dev) 74.0.3702.0,but now, on Chrome 74.0.3712.0 (Official Build),it works normally.
So...I think there's no need for us to care about this issue any more.
