### ISSUE TITLE
angleAxis 事件BUG

### ISSUE THREAD

**Issue by starm328** [apache/incubator-echarts#9939]
angleAxis 中的设置triggerEvent 无效，不能触发点击事件
重现demo可以使用https://echarts.baidu.com/examples/editor.html?c=bar-polar-stack-radial
然后设置
`myChart.on('click', function (params) {
    // 控制台打印数据的名称
    alert(11)
});`
并不能触发这个事件

**Comment by Ovilia** [comment]
Please use https://ecomfe.github.io/echarts-issue-helper to create the issue.
