### ISSUE TITLE
echarts的框选问题（brush），非常紧急

### ISSUE THREAD

**Issue by NingMengMeng** [apache/incubator-echarts#9944]
你好，由于我的散点图要渲染几十万甚至上百万的数据，使用了appendData进行分片段展示，但是对于这种情况，一点击框选按钮(brush)就重新渲染，一去框选去框选还是重新渲染。请问针对大数据量的散点图，如何实现框选功能呢

**Comment by Ovilia** [comment]
Please use https://ecomfe.github.io/echarts-issue-helper to create the issue.
