### ISSUE TITLE
echarts的框选问题（brush）

### ISSUE THREAD

**Issue by NingMengMeng** [apache/incubator-echarts#9946]
### Version
4.2.1-rc1

### Steps to reproduce
1、点击框选按钮
2、框选

### What is expected?
大数据的散点图，期望能够实现框选功能，即区域选择

### What is actually happening?
你好，由于我的散点图要渲染几十万甚至上百万的数据，使用了appendData进行分片段展示，但是对于这种情况，一点击框选按钮(brush)就重新渲染，一去框选还是重新渲染。请问针对大数据量的散点图，如何实现框选功能呢

**Comment by Ovilia** [comment]
Duplicate of #9945
