### ISSUE TITLE
There is a matrix bug when you use SVG render a Graph Chart.（svg渲染graph表标签显示错误）

### ISSUE THREAD

**Issue by gloye** [apache/incubator-echarts#9949]
### Version
4.1.0-release

### Steps to reproduce
step 1:  {renderer:'SVG'},
step 2:  setOptions  https://www.echartsjs.com/examples/editor.html?c=graph-simple
step 3:  change Symbol Size , you would see the labels are also changed.
![img](http://thyrsi.com/t6/672/1550646740x2890174040.png)
### What is expected?
as the same as rendered by Canvas

### What is actually happening?
if you changed the Symbol size, the label's atrribute matrix would change too.
在svg模式下，symbol的改变会影响label文字的大小，因为label的matrix受到影响了

**Comment by Ovilia** [comment]
Seems to be fixed. Please try 4.2.1-rc1.

**Comment by gloye** [comment]
> Seems to be fixed. Please try 4.2.1-rc1.

The version 4.2.1-rc1 is OK ， thank you
