### ISSUE TITLE
何时发布一个版本带上这个#9182修复啊？急用哦

### ISSUE THREAD

**Issue by CharonTao** [apache/incubator-echarts#9952]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by Ovilia** [comment]
4.2.1-rc1 中应该是有的

**Comment by CharonTao** [comment]
并没有哦，我用的就是最新的，而且我也看了源码，并没有哦！那个修复的是graph的rotate参数不生效问题。
下图是4.2.1-rc1的源码
![image](https://user-images.githubusercontent.com/19574430/53081356-aa681f00-3535-11e9-8d98-fd6057460b02.png)

**Comment by CharonTao** [comment]
![image](https://user-images.githubusercontent.com/19574430/53081707-57429c00-3536-11e9-8a5f-9988fcd50a76.png)
这个是相关的pull request ，并没有在最新的版本中

**Comment by Ovilia** [comment]
@100pah Please help to check.

**Comment by 100pah** [comment]
这个修改确实没有被包括在 4.2.1-rc1 中。而是仍然在 master 中。
但是会包含在 4.3.0 中。

**Comment by CharonTao** [comment]
啥时候会发布4.3.0这个版本呢？我等这个已经等了2个月了。（哭

**Comment by CharonTao** [comment]
> 这个修改确实没有被包括在 4.2.1-rc1 中。而是仍然在 master 中。
> 但是会包含在 4.3.0 中。

啥时候会发布4.3.0这个版本呢？我等这个已经等了2个月了。（哭

**Comment by 100pah** [comment]
@CharonTao 很不好意思。因为比较忙以及一些 Apache 流程原因发版拖延比较久。
而按照 [milestone](https://github.com/apache/incubator-echarts/milestones) ，4.3.0 将在 3 月初。

**Comment by CharonTao** [comment]
@100pah 那好吧，也只能等了。谢谢！！
