### ISSUE TITLE
IE11下line线条多的情况下页面操作非常卡

### ISSUE THREAD

**Issue by qqfei1858** [apache/incubator-echarts#9955]
### Version
4.2.1-rc1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xJ96BGanCD&v=1](https://gallery.echartsjs.com/editor.html?c=xJ96BGanCD&v=1)

### Steps to reproduce
就是普通的折线图,但是线条多,15-20条左右,每条线上的数据量有30万个数据点,项目需要加载完成的时候,所有的数据点全部集中在一起!这个时候,IE11下操作页面或者legend选项的时候会非常卡,当放大到一定的范围的时候,也就不集中的时候不会卡,谷歌下还好!

### What is expected?
解决ie线条数据量多卡顿问题

### What is actually happening?
ie11下线条数据量多卡

**Comment by 100pah** [comment]
是否设置过 sampling 呢？

**Comment by qqfei1858** [comment]
> 是否设置过采样呢？

设置了 sampling:"average"!
 {
      name: val.name,
      type: 'line',
      smooth: true,
      symbol: 'circle',
      symbolSize: 8,
      sampling: 'average',
      connectNulls: true,
      clipOverflow: false,
      data: echartsData.seriesDataValue
};

**Comment by Ovilia** [comment]
Try with `showSymbol: false`

**Comment by qqfei1858** [comment]
> showSymbol
@100pah @Ovilia 
不行哦,项目上需要有Symbol属性!

**Comment by Ovilia** [comment]
主要就是由于绘制 symbol 太多引起的。30万个点的折线图绘制 symbol 的意义何在？
