### ISSUE TITLE
IE11 line线条多,数据量大,页面操作卡!

### ISSUE THREAD

**Issue by qqfei1858** [apache/incubator-echarts#9961]
### Version
4.2.1-rc1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xJ96BGanCD&v=1](https://gallery.echartsjs.com/editor.html?c=xJ96BGanCD&v=1)

### Steps to reproduce
就是普通的折线图,但是线条多,15-20条左右,每条线上的数据量有30万个数据点,项目需要加载完成的时候,所有的数据点全部集中在一起!这个时候,IE11下操作页面或者legend选项的时候会非常卡,当放大到一定的范围的时候,也就不集中的时候不会卡,谷歌下还好!

### What is expected?
解决IE11下卡顿

### What is actually happening?
IE11下卡顿

**Comment by Ovilia** [comment]
Duplicate of #9955
