### ISSUE TITLE
安全漏洞:加密密钥进行硬编码

### ISSUE THREAD

**Issue by chehxing** [apache/incubator-echarts#9964]
### Version
3.3.0

### Steps to reproduce
用Fortify Audit Workbench扫描系统， 发现系统报了一个关于echarts的漏洞。

### What is expected?
通过验证

### What is actually happening?
Porous Defenses - CWE ID 798
使用硬编码凭证。 CWE-798 声明:“软件包含硬编码凭证，例如密码或加密密钥，用于自身的入站验证、 外部组件的出站通信或者内部数据的加密”。

public/js/echarts.min.js:1
Sink: Operation
Enclosing Method: lambda() Source:
SCA
public/js/echarts.min.js:1
Sink: Operation Enclosing Method: hv() Source:
SCA

**Comment by 100pah** [comment]
> Porous Defenses - CWE ID 798
使用硬编码凭证。 CWE-798 声明:“软件包含硬编码凭证，例如密码或加密密钥，用于自身的入站验证、 外部组件的出站通信或者内部数据的加密”。
> public/js/echarts.min.js:1
> Sink: Operation
> Enclosing Method: lambda() Source:
> SCA
> public/js/echarts.min.js:1
> Sink: Operation Enclosing Method: hv() Source:
> SCA

Generally, echarts has no "certification" or "key" in code.

And I can not find "hv()" or "lambda()" in `dist/echarts.min.js` of [release 3.3.0]
(https://github.com/apache/incubator-echarts/blob/8f885ec3a42506c05f907385244a482d078d9b0a/dist/echarts.min.js)

Could I have more detailed info about it?

**Comment by Ovilia** [comment]
Close due to missing info.
