### ISSUE TITLE
textBorderWidth and textBorderColor are both bugged and removes random axis labels

### ISSUE THREAD

**Issue by Kondinator** [apache/incubator-echarts#9969]
### Version
4.1.0-release

### Steps to reproduce
Use either textBorderwidth or textBorderColor, on axis labels makes random labels dissapear.

axisLabel: {                       
                        color: '#fff',
                        fontSize: 15,
                        textBorderColor: '#333',
                        textBorderWidth: '2',
                        
                    },

### What is expected?
All labels shown

### What is actually happening?
not all are shown.

---
i tested with all my other options for my labels and these were the only ones that caused my problem.

**Comment by 100pah** [comment]
Could I have the fill `echarts option` to reproduce this issue?

**Comment by Kondinator** [comment]
var option = {

                title: {
                    text: 'Rum temperatur',
                    textStyle: {
                        color: '#fff',
                        fontSize: 30,
                        textShadowBlur: 2,
                        textShadowColor: '#000',
                        textShadowOffsetX: 0,
                        textShadowOffsetY: 1,
                        textBorderColor: '#333',
                        textBorderWidth: 2

                    },

                },

                tooltip: {

                },

                xAxis: { //bunden
                    type: 'category',

                    axisTick: {
                        //alignWithLabel: true,
                    },

                    axisLabel: {
                        //align: 'center',
                        color: 'black',
                        fontSize: 15,
                        textShadowBlur: 1,
                        textShadowColor: 'white',
                        textShadowOffsetX: 1,
                        textShadowOffsetY: 1,
                        //textBorderColor: '#333',
                        //textBorderWidth: '2',
                        //showMinLabel: true,
                        //showMaxLabel: true,
                    },

                    data: tidspunkt
                },
                yAxis: { //siden
                    min: lowest,
                    max: highest,
                    type: 'value',

                    axisLabel: {
                        show: true,
                        color: 'black',
                        fontSize: 15,
                        textShadowBlur: 2,
                        textShadowColor: 'white',
                        textShadowOffsetX: 0,
                        textShadowOffsetY: 1,
                        textBorderColor: 'white', //bugged
                        textBorderWidth: '2', //bugged

                    },
                },

                series: [{
                    name: 'Temperatur',
                    type: 'line',
                    smooth: true,
                    lineStyle: {
                        width: 5,
                    },
                    data: celsius


                }]
            };
            myChart.setOption(option);

**Comment by 100pah** [comment]
This `option` miss data so can not run directly to reproduce the issue.

I guess that set `xAxis.axisLabel.interval: 0` might help.

**Comment by Kondinator** [comment]
it shouldnt matter what data i put in, i have variables as my data so it wouldnt make sense to post it here. 
and its not interval as you suggested, ive tried so many things to no avail. that is why i might think its a bug as its only present when those 2 options are put in.

**Comment by Kondinator** [comment]
> This `option` miss data so can not run directly to reproduce the issue.
> 
> I can only guess that set `xAxis.axisLabel.interval: 0` might help.

you didnt read what i wrote man..

**Comment by Kondinator** [comment]
@100pah hey can you please respond, you didnt read what i first read. my options dont matter, what matter are the 2 lines of options. you can try them in your own. it doesnt work.

**Comment by Ovilia** [comment]
Please use image to demo what you want and what's wrong now. I cannot understand your request from above dialogs. And please provide an option that can run.
