### ISSUE TITLE
桑基图 orient 属性不起作用

### ISSUE THREAD

**Issue by DoesntWong** [apache/incubator-echarts#9972]
### Version
4.1.0-release

### Steps to reproduce
npm 安装echarts 最新版本和 @types/echarts

chartOption: EChartOption = {
    color: [
      '#67001f', '#b2182b', '#d6604d', '#f4a582', '#fddbc7', '#d1e5f0', '#92c5de', '#4393c3', '#2166ac', '#053061'
    ],
    tooltip: {
      trigger: 'item',
      triggerOn: 'mousemove'
    },
    animation: false,
    series: [
      {
        type: 'sankey',
        bottom: '10%',
        focusNodeAdjacency: 'allEdges',
        data: [
          {name: 'a'},
          {name: 'b'},
          {name: 'a1'},
          {name: 'b1'},
          {name: 'c'},
          {name: 'e'}
        ],
        links: [
          {source: 'a', target: 'a1', value: 5},
          {source: 'e', target: 'b', value: 3},
          {source: 'a', target: 'b1', value: 3},
          {source: 'b1', target: 'a1', value: 1},
          {source: 'b1', target: 'c', value: 2},
          {source: 'b', target: 'c', value: 1}
        ],
        orient: 'vertical',
        label: {
          position: 'top'
        },
        lineStyle: {
          normal: {
            color: 'source',
            curveness: 0.5
          }
        }
      }
    ]
  }

<div echarts [options]="chartOption" class="demo-chart"></div>

### What is expected?
我想要得到跟官方示例一样上下结构的桑基图
https://echarts.baidu.com/examples/editor.html?c=sankey-vertical

### What is actually happening?
实际还是左右结构的，orient: 'vertical', 不起作用

---
看源码SankeySeries.js  defaultOption就没有orient这个属性，麻烦看一下谢谢

**Comment by 100pah** [comment]
It works in `4.2.1-rc.1`.
