### ISSUE TITLE
Can I control the order of stack line charts with an attribute? 

### ISSUE THREAD

**Issue by tz310200** [apache/incubator-echarts#9990]
### What problem does this feature solve?
if I dynamically add a line, but the line is always at the top of the stack.
```javascrpt
option = {
    title: {
        text: '折线图堆叠'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[120, 132, 101, 134, 90, 230, 210]
        },

        {
            name:'视频广告',
            type:'line',
            stack: '总量',
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'直接访问',
            type:'line',
            stack: '总量',
            data:[320, 332, 301, 334, 390, 330, 320]
        },
        {
            name:'搜索引擎',
            type:'line',
            stack: '总量',
            data:[820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
};
setTimeout(function() {
    myChart.setOption({
        series: [{        
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[220, 182, 191, 234, 290, 330, 310]
        }].concat(option.series)
    })
    
}, 1000);
```
I want series-line '联盟广告' at the bottom

online demo [https://codesandbox.io/s/5k8zxkv89n?fontsize=14](https://codesandbox.io/s/5k8zxkv89n?fontsize=14)

### What does the proposed API look like?
```
series: [
        {
            index: 0 // Control stack line order
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[120, 132, 101, 134, 90, 230, 210]
        },
]
```

**Comment by Ovilia** [comment]
I don't think this is possible right now.

**Comment by alex2wong** [comment]
@tz310200  After diving into source code around  https://github.com/alex2wong/incubator-echarts/blob/master/src/util/model.js#L150 for a while.

I suppose this mappingToExists function has ability to merge new chart option to existing ones by series.id attr.  Which means you can specify the series of data you wanna put at bottom with the same id as the previous bottom one. then the new series would be rendered at its new order.

For instance, I provide a new forked codesandbox. 
https://codesandbox.io/s/echarts-series-stackid-g8dvh

You can see the new added series are rendered replacing the previous bottom one.. wish it help, thx

**Comment by alex2wong** [comment]
attached doc reference : https://www.echartsjs.com/zh/option.html#series-line.id

**Comment by tz310200** [comment]
> 随附的文档参考：[https](https://www.echartsjs.com/zh/option.html#series-line.id) : [//www.echartsjs.com/zh/option.html#series-line.id](https://www.echartsjs.com/zh/option.html#series-line.id)

awesome, thank you
