### ISSUE TITLE
希望增加金字塔图

### ISSUE THREAD

**Issue by segmafrontend** [apache/incubator-echarts#9991]
### What problem does this feature solve?
金字塔图是饼图的另外一种展现形式，图形始终为一个三角形，每层的面积大小表示该项数据在总数据中的占比，参考 https://www.highcharts.com.cn/demo/highcharts/pyramid

### What does the proposed API look like?
参看饼图API

**Comment by Ovilia** [comment]
我不认为金字塔图是一个很好的图表类型，它几乎在任何时候都会造成读者的误解。
读者很容易将图形的面积以为是数据比，但其实底边的边长才是数据比。
有什么理由说服我吗？

**Comment by segmafrontend** [comment]
我认为，漏斗图的数据比是底边边长的比；而金字塔图始终需要保证整体是一个三角形，所以数据比是每一层的高度比，而不是面积比。读者很直观的就可以看到数据比，demo：https://jshare.com.cn/demos/hhhhi1，所有数据都相同，每层金字塔高度相同，实际面积并不相同，视觉上感觉数据就是相同的
